feat: Add pre-commit config
scipy-conference/scipy_proceedings pull request #1017
Opened 2024-08-21 03:36 UTC by matthewfeickert

Resolves #1016 

* Add pre-commit/pre-commit-hooks for general linting.
   - Ignore CSV files.
* Add python-jsonschema/check-jsonschema for GitHub Actions.
  schema validation
* Add pre-commit.ci config.
   - Set autoupdate schedule to quarterly (the longest possible).

The second commit in this PR is huge, but it is just applying the results of the added pre-commit hooks via

```
pre-commit run --all-files
```

as @tkoyama010 has started setting up pre-commit.ci (https://github.com/scipy-conference/scipy_proceedings/issues/1016#issuecomment-2299911858) and pre-commit.ci will run the equivalent of `pre-commit run --all-files` on each commit. This commit can get ignored automatically from GitHub's `git blame` on diffs via adding it to a `.git-blame-ignore-revs` (c.f. https://github.com/matplotlib/matplotlib/blob/1e8ea2f6ac758b331fb8b6838d69822424e86cb4/.git-blame-ignore-revs for an example).

2024-08-21 03:44 UTC, matthewfeickert commented on .pre-commit-config.yaml
This would also benefit from codespell-project/codespell being added (c.f. https://github.com/scipy-conference/scipy-conference/blob/3755b74eb94a00ca7038b5210f01f021b5127e72/.pre-commit-config.yaml#L30-L38) but given that there are multiple words that need to get added to an ignore list and fixed in files, I've decided to not do that in this PR. as it would need some input from other parties.

2024-08-21 03:45 UTC, matthewfeickert commented
@scipy-conference/proceedings this is ready for review. Let me know if you have any questions. @tkoyama010 a review from you would be welcome also. :)

2024-08-21 03:57 UTC, tkoyama010 requested changes

2024-08-21 03:57 UTC, tkoyama010 commented on .pre-commit-config.yaml
> +        args: ["--verbose"]
Let's also add prettier to format `yaml, html, css, scss, javascript, json, toml`.
ref [PC180 in Scientific Python Library Development Guide](https://learn.scientific-python.org/development/guides/style/#prettier).
```suggestion

  - repo: https://github.com/python-jsonschema/check-jsonschema
    rev: 0.29.1
    hooks:
      - id: check-github-workflows
        args: ["--verbose"]

  - repo: https://github.com/pre-commit/mirrors-prettier
    rev: v3.1.0
    hooks:
      - id: prettier
        types_or: [yaml, html, css, scss, javascript, json, toml]
```

2024-08-21 04:00 UTC, tkoyama010 commented
A markdown formatter should also be added, but the impact is too great and should be discussed carefully.
- https://github.com/igorshubovych/markdownlint-cli/tree/master

2024-08-21 05:08 UTC, matthewfeickert commented
> A markdown formatter should also be added, but the impact is too great and should be discussed carefully.
> 
> * https://github.com/igorshubovych/markdownlint-cli/tree/master

I like the idea, but as it would be a big diff
<details>
<summary>Results of applying igorshubovych/markdownlint-cli:</summary>

```console
markdownlint.............................................................Failed
- hook id: markdownlint
- exit code: 1

publisher/getting_ready_for_new_year.md:8:1 MD051/link-fragments Link fragments should be valid [Expected: #what-problem-are-we-solving; Actual: #What-problem-are-we-solving] [Context: "[the problem section](#What-problem-are-we-solving)"]
publisher/getting_ready_for_new_year.md:10 MD025/single-title/single-h1 Multiple top-level headings in the same document [Context: "# Workflow"]
publisher/getting_ready_for_new_year.md:30:81 MD013/line-length Line length [Expected: 80; Actual: 99]
publisher/getting_ready_for_new_year.md:32:81 MD013/line-length Line length [Expected: 80; Actual: 88]
publisher/getting_ready_for_new_year.md:33:81 MD013/line-length Line length [Expected: 80; Actual: 91]
publisher/getting_ready_for_new_year.md:74:49 MD026/no-trailing-punctuation Trailing punctuation in heading [Punctuation: '.']
publisher/getting_ready_for_new_year.md:89:65 MD026/no-trailing-punctuation Trailing punctuation in heading [Punctuation: '.']
publisher/getting_ready_for_new_year.md:94:1 MD051/link-fragments Link fragments should be valid [Expected: #workflow; Actual: #Workflow] [Context: "[](#Workflow)"]
publisher/README.md:1:41 MD026/no-trailing-punctuation Trailing punctuation in heading [Punctuation: '.']
publisher/README.md:5:81 MD013/line-length Line length [Expected: 80; Actual: 153]
publisher/README.md:7:81 MD013/line-length Line length [Expected: 80; Actual: 91]
publisher/README.md:9:81 MD013/line-length Line length [Expected: 80; Actual: 132]
publisher/README.md:11:17 MD026/no-trailing-punctuation Trailing punctuation in heading [Punctuation: ':']
publisher/README.md:23:81 MD013/line-length Line length [Expected: 80; Actual: 91]
publisher/README.md:27:81 MD013/line-length Line length [Expected: 80; Actual: 242]
publisher/README.md:31:81 MD013/line-length Line length [Expected: 80; Actual: 125]
publisher/README.md:47:1 MD007/ul-indent Unordered list indentation [Expected: 2; Actual: 4]
publisher/README.md:48:1 MD007/ul-indent Unordered list indentation [Expected: 2; Actual: 4]
publisher/README.md:50:1 MD007/ul-indent Unordered list indentation [Expected: 2; Actual: 4]
publisher/README.md:51:1 MD007/ul-indent Unordered list indentation [Expected: 2; Actual: 4]
publisher/README.md:57:81 MD013/line-length Line length [Expected: 80; Actual: 148]
publisher/README.md:67:81 MD013/line-length Line length [Expected: 80; Actual: 93]
publisher/README.md:83:81 MD013/line-length Line length [Expected: 80; Actual: 91]
publisher/README.md:109:1 MD023/heading-start-left Headings must start at the beginning of the line [Context: "  ## DOI metadata"]
publisher/README.md:116:1 MD007/ul-indent Unordered list indentation [Expected: 2; Actual: 4]
publisher/README.md:117:1 MD007/ul-indent Unordered list indentation [Expected: 2; Actual: 4]
publisher/README.md:118:1 MD007/ul-indent Unordered list indentation [Expected: 4; Actual: 8]
publisher/README.md:119:1 MD007/ul-indent Unordered list indentation [Expected: 4; Actual: 8]
publisher/README.md:120:1 MD007/ul-indent Unordered list indentation [Expected: 4; Actual: 8]
publisher/README.md:124:2 MD034/no-bare-urls Bare URL used [Context: "http://www.issn.org/understand..."]
publisher/README.md:136:2 MD034/no-bare-urls Bare URL used [Context: "https://doi.org/10.25080/shinm..."]
publisher/README.md:137 MD032/blanks-around-lists Lists should be surrounded by blank lines [Context: "- which resolves the proceedin..."]
pull_request_template.md:1 MD041/first-line-heading/first-line-h1 First line in a file should be a top-level heading [Context: "If you are creating this PR in..."]
pull_request_template.md:2:5 MD034/no-bare-urls Bare URL used [Context: "http://procbuild.scipy.org/"]
pull_request_template.md:8 MD012/no-multiple-blanks Multiple consecutive blank lines [Expected: 1; Actual: 2]
README.md:9:81 MD013/line-length Line length [Expected: 80; Actual: 116]
README.md:12:81 MD013/line-length Line length [Expected: 80; Actual: 129]
README.md:17:81 MD013/line-length Line length [Expected: 80; Actual: 133]
README.md:42 MD032/blanks-around-lists Lists should be surrounded by blank lines [Context: "- with many people contributin..."]
README.md:43:1 MD007/ul-indent Unordered list indentation [Expected: 2; Actual: 4]
README.md:44:1 MD007/ul-indent Unordered list indentation [Expected: 2; Actual: 4]
README.md:46:1 MD007/ul-indent Unordered list indentation [Expected: 2; Actual: 4]
README.md:46:21 MD034/no-bare-urls Bare URL used [Context: "https://github.com/scipy-confe..."]
README.md:47:1 MD007/ul-indent Unordered list indentation [Expected: 2; Actual: 4]
README.md:47:15 MD034/no-bare-urls Bare URL used [Context: "https://github.com/scipy-confe..."]
README.md:50 MD032/blanks-around-lists Lists should be surrounded by blank lines [Context: "- build system:"]
README.md:51:1 MD007/ul-indent Unordered list indentation [Expected: 2; Actual: 4]
README.md:52:1 MD007/ul-indent Unordered list indentation [Expected: 2; Actual: 4]
README.md:53:1 MD007/ul-indent Unordered list indentation [Expected: 2; Actual: 4]
README.md:55:1 MD007/ul-indent Unordered list indentation [Expected: 2; Actual: 4]
README.md:56:1 MD007/ul-indent Unordered list indentation [Expected: 2; Actual: 4]
README.md:57:1 MD007/ul-indent Unordered list indentation [Expected: 2; Actual: 4]
README.md:58:1 MD007/ul-indent Unordered list indentation [Expected: 2; Actual: 4]
README.md:73:1 MD007/ul-indent Unordered list indentation [Expected: 2; Actual: 4]
README.md:74:1 MD007/ul-indent Unordered list indentation [Expected: 2; Actual: 4]
README.md:74:81 MD013/line-length Line length [Expected: 80; Actual: 96]
README.md:82:1 MD007/ul-indent Unordered list indentation [Expected: 2; Actual: 4]
README.md:83:1 MD007/ul-indent Unordered list indentation [Expected: 2; Actual: 4]
README.md:86:34 MD034/no-bare-urls Bare URL used [Context: "http://conference.scipy.org/pr..."]
README.md:103 MD012/no-multiple-blanks Multiple consecutive blank lines [Expected: 1; Actual: 2]
README.md:106:81 MD013/line-length Line length [Expected: 80; Actual: 164]
README.md:109 MD032/blanks-around-lists Lists should be surrounded by blank lines [Context: "- Meghann Agarwal (@mepa)"]
README.md:119:81 MD013/line-length Line length [Expected: 80; Actual: 115]
README.md:138:81 MD013/line-length Line length [Expected: 80; Actual: 271]
README.md:169:51 MD026/no-trailing-punctuation Trailing punctuation in heading [Punctuation: ':']
README.md:173:1 MD007/ul-indent Unordered list indentation [Expected: 2; Actual: 4]
README.md:174:1 MD007/ul-indent Unordered list indentation [Expected: 4; Actual: 8]
README.md:175:1 MD007/ul-indent Unordered list indentation [Expected: 4; Actual: 8]
README.md:176:1 MD007/ul-indent Unordered list indentation [Expected: 4; Actual: 8]
README.md:177:1 MD007/ul-indent Unordered list indentation [Expected: 2; Actual: 4]
README.md:178:53 MD034/no-bare-urls Bare URL used [Context: "http://procbuild.scipy.org"]
README.md:182:81 MD013/line-length Line length [Expected: 80; Actual: 112]
README.md:183:81 MD013/line-length Line length [Expected: 80; Actual: 126]
README.md:190:81 MD013/line-length Line length [Expected: 80; Actual: 135]
README.md:210 MD040/fenced-code-language Fenced code blocks should have a language specified [Context: "```"]
README.md:216 MD040/fenced-code-language Fenced code blocks should have a language specified [Context: "```"]
README.md:224:81 MD013/line-length Line length [Expected: 80; Actual: 99]
README.md:227:81 MD013/line-length Line length [Expected: 80; Actual: 123]
README.md:228:81 MD013/line-length Line length [Expected: 80; Actual: 167]
R [...]

2024-08-22 04:37 UTC, tkoyama010 commented
Closing to try pre-commit.ci

2024-08-22 04:38 UTC, tkoyama010 approved these changes
OK. It seems run fine 👍

2024-08-22 17:41 UTC, matthewfeickert commented
A note here for @scipy-conference/proceedings given Slack discussion. After this PR is merged this should get backported to the [`2024` branch](https://github.com/scipy-conference/scipy_proceedings/tree/2024) so that all the PRs targeting it for the 2024 proceedings will be targeting a branch with a `.pre-commit-config.yaml` on it for pre-commit.ci to use.

2024-08-22 17:55 UTC, TahiriNadia commented
Hello, 

We have a new error: .pre-commit-config.yaml is not recognized as a file. I think it's related to the new test.
Tests:
![image](https://github.com/user-attachments/assets/2e94addd-7dec-4725-8f4f-ad886e03d684)

precommit.ci:
![image](https://github.com/user-attachments/assets/6efa3901-2fd1-4287-ab36-0242a123e843)

See [PR 925](https://github.com/scipy-conference/scipy_proceedings/pull/925), and we look at the [log](https://results.pre-commit.ci/repo/github/1825629).

2024-08-22 18:26 UTC, matthewfeickert commented
@TahiriNadia c.f. https://github.com/scipy-conference/scipy_proceedings/pull/1017#issuecomment-2305306115

2024-08-22 18:53 UTC, cbcunc requested changes
Is there some reason this branch seeks to make so many minor formatting and other changes to so many files other than just adding .pre-commit-config.yaml ?

2024-08-22 19:03 UTC, matthewfeickert commented
> Is there some reason this branch seeks to make so many minor formatting and other changes to so many files other than just adding .pre-commit-config.yaml ?

@cbcunc Please read the PR body where this is explained: https://github.com/scipy-conference/scipy_proceedings/pull/1017#issue-2476970734

2024-08-22 19:21 UTC, cbcunc commented
> @cbcunc Please read the PR body where this is explained: [#1017 (comment)](https://github.com/scipy-conference/scipy_proceedings/pull/1017#issue-2476970734)

Does not explain why it needs to run on --all-files.

2024-08-22 21:13 UTC, matthewfeickert commented
> Does not explain why it needs to run on --all-files.

@scipy-conference/2024-proceedings Okay, let me try to unpack

> The second commit in this PR is huge, but it is just applying the results of the added pre-commit hooks via
> 
> ```
> pre-commit run --all-files
> ```
> 
> as @tkoyama010 has started setting up pre-commit.ci (https://github.com/scipy-conference/scipy_proceedings/issues/1016#issuecomment-2299911858) and pre-commit.ci will run the equivalent of `pre-commit run --all-files` on each commit. This commit can get ignored automatically from GitHub's `git blame` on diffs via adding it to a `.git-blame-ignore-revs` > (c.f. https://github.com/matplotlib/matplotlib/blob/1e8ea2f6ac758b331fb8b6838d69822424e86cb4/.git-blame-ignore-revs for an example).

in much more detail then.

* If we go back to https://github.com/scipy-conference/scipy_proceedings/pull/1015#discussion_r1723733133 which is what I quoted to make Issue https://github.com/scipy-conference/scipy_proceedings/issues/1016 this was in the context of the discussion about adding pre-commit and then enabling pre-commit.ci.
   - Hypothetical question: "Why do you want pre-commit.ci?". Answer: Because you both want to make sure that commits not passing pre-commit don't get into your repository and more importantly, if a contributor doesn't have pre-commit installed locally, and so pushes changes that might not pass, then it will catch these and hopefully be able to push back a fix so the contributor doesn't even have to go fix it themselves.
* Given this, this PR (PR https://github.com/scipy-conference/scipy_proceedings/pull/1017) is in written in the context assuming that pre-commit.ci will be turned on and used.
* pre-commit.ci runs the equivalent of `pre-commit run --all-files` on every commit as a check. If any files in the repository doesn't pass then the check fails. It will try to push back changes, but if it can't the check fails. This is not a configurable behavior. If you use pre-commit.ci, it will always run over every file.
* As pre-commit.ci is going to need to do this anyway, I separated this PR out into two commits (originally, but then two more were added as suggestions) to make it easy to review. The first commit adds the `.pre-commit-config.yaml`. The second then applies the changes that running `pre-commit run --all-files` will enforce and fixing those that it can't automatically get (c.f. the commit message for an example).

I think that should explain why `pre-commit run --all-files` was used.

As I also mentioned, I understand that this is a large change, and people generally don't want to have to deal with this noise when using `git blame` to try to trace the history of changes through a file. This is why `.git-blame-ignore-revs` exists, as it will be automatically picked up by GitHub and all the commits listed in it will be ignored for `git blame` reasons. You can manually apply it at the command line with [`--ignore-revs-file`](https://git-scm.com/docs/git-blame#Documentation/git-blame.txt---ignore-revs-fileltfilegt). Many projects do this to ignore big stylistic changes from their `git blame`s, like turning on `pre-commit` or adding a new linter (like `black` or `ruff`). Matplotlib is an example of one of those projects, so I list it here as an example if people want to see how they're using it.

I did not include a `.git-blame-ignore-revs` in this PR as it requires the commit hash. If this was going to be squashed and merged then the commit hash would change and the file would be wrong. So I would suggest adding a `.git-blame-ignore-revs` _after_ this PR is in and the commits are known.

2024-08-22 23:51 UTC, matthewfeickert commented
> A note here for @scipy-conference/proceedings given Slack discussion. After this PR is merged this should get backported to the [`2024` branch](https://github.com/scipy-conference/scipy_proceedings/tree/2024) so that all the PRs targeting it for the 2024 proceedings will be targeting a branch with a `.pre-commit-config.yaml` on it for pre-commit.ci to use.


Be aware that when this is backported to the `2024` branch there is already a `.pre-commit-config.yaml` file there from PR https://github.com/scipy-conference/scipy_proceedings/pull/1018 that will get overwritten.

2024-08-24 01:29 UTC, matthewfeickert commented
@scipy-conference/2024-proceedings I see from PR https://github.com/scipy-conference/scipy_proceedings/pull/925 that pre-commit.ci has been disabled as it doesn't show up in the checks and when you look at the pre-commit.ci page for the repo (https://results.pre-commit.ci/repo/github/1825629) it was disabled before the last pushes https://github.com/scipy-conference/scipy_proceedings/pull/925#commits-pushed-bba46c3.

Is there still interest in using pre-commit.ci (even if not while the 2024 proceedings are still in process)?

2024-08-24 02:04 UTC, cbcunc commented
> Is there still interest in using pre-commit.ci (even if not while the 2024 proceedings are still in process)?

Yes, after we're done with the 2024 process.

2024-09-02 22:21 UTC, mepa commented
> Is there still interest in using pre-commit.ci (even if not while the 2024 proceedings are still in process)?

In [my original comment](https://github.com/scipy-conference/scipy_proceedings/pull/1015#discussion_r1723733133) I should have mentioned incorporating use of pre-commit.ci after the 2024 proceedings are published. Thank you, @matthewfeickert and @tkoyama010, for your work on this.

2025-02-03 19:33 UTC, matthewfeickert commented
:wave: @scipy-conference/2024-proceedings (as `@scipy-conference/2025-proceedings` doesn't exist yet) can this PR get revisited now, given that there's starting to be 2025 updates?

2025-06-25 17:25 UTC, matthewfeickert commented on .pre-commit-config.yaml
Ah @fwkoch, I guess you get around the issue I mentioned in https://github.com/scipy-conference/scipy_proceedings/pull/1118#discussion_r2167228313 by not formatting Markdown? :+1: 

```diff
$ git diff upstream/feat/pre-commit-again -- .pre-commit-config.yaml
diff --git a/.pre-commit-config.yaml b/.pre-commit-config.yaml
index aee8a132..6786b9b2 100644
--- a/.pre-commit-config.yaml
+++ b/.pre-commit-config.yaml
@@ -30,14 +30,16 @@ repos:
           (?x)^(
               .*\.csv
           )$
+
   - repo: https://github.com/python-jsonschema/check-jsonschema
-    rev: 0.31.1
+    rev: 0.33.1
     hooks:
       - id: check-github-workflows
         args: ["--verbose"]
 
-  - repo: https://github.com/pre-commit/mirrors-prettier
-    rev: v3.1.0
+  - repo: https://github.com/rbubley/mirrors-prettier
+    rev: "v3.6.1"
     hooks:
       - id: prettier
-        types_or: [yaml, html, css, scss, javascript, json, toml]
+        types_or: [yaml, markdown, html, css, scss, javascript, json]
+        args: [--prose-wrap=always]

```

2025-06-25 17:30 UTC, matthewfeickert commented on presentations/keynote/example/myst.yml
> +    with the power of machine learning.'
@fwkoch For `prettier` there's line breaks that I don't think are super useful, but I'm not sure how to properly ignore these.

2025-06-25 17:41 UTC, fwkoch commented
Thanks for rebasing this PR! Regarding the discussion above, I agree we should hold off applying `prettier` to markdown files - we need to test it out with MyST files before we dive in. (Looks like that aligns with the current state of the pre-commit config.)

I'll pull this branch locally and try running pre-commit again, and then get it merged!

2025-06-25 17:43 UTC, fwkoch commented on presentations/keynote/example/myst.yml
> +    with the power of machine learning.'
I'm not sure why this change didn't happen on my other PR 🤔

I agree that these line breaks are not super useful, but for just the yaml, it seems acceptable if we cannot figure out how to ignore. Yaml is structured enough that line breaks will not impact the content. (As opposed to markdown where I worry there might be lingering issues like this, where applying prettier breaks it: https://github.com/prettier/prettier/issues/9232)

2025-06-25 17:56 UTC, matthewfeickert commented on presentations/keynote/example/myst.yml
> +    with the power of machine learning.'
@henryiii had mentioned:

> Pretty sure it supports https://editorconfig.org
> https://github.com/editorconfig/editorconfig/wiki/EditorConfig-Properties
> `max_line_length` is supported. That’s how I’ve always configured it

Though for things like abstracts in YAML config files it seems reasonable to allow for a "1 sentence per line" system, so unless `max_line_length` is unlimited (which doesn't seem helpful) not sure how to get around that.

2025-06-25 18:03 UTC, fwkoch commented on presentations/keynote/example/myst.yml
> +  abstract: |
This time, I did see the prettier changes in this file locally. I modified the file to use pipes for the new lines (I think this looks slightly nicer 🤷 a bit clearer that the content is on the next line) and prettier is still happy.

2025-06-25 18:05 UTC, matthewfeickert commented on presentations/keynote/example/myst.yml
> +  abstract: |
SGTM :+1:

2025-06-25 18:05 UTC, fwkoch commented
Ok - I'm going to merge this - it's just going into dev, so it will not have immediate impacts on 2025 submissions. We can continue to iterate on settings, prettier file formats, etc.

Thanks @matthewfeickert and @tkoyama010 for getting this set up in the first place! (and sorry for being glacially slow to land it.)

2025-06-25 18:15 UTC, merged