Update for 2018
scipy-conference/scipy_proceedings pull request #364
Opened 2018-04-08 07:51 UTC by mpacer

This PR updates the README to have new dates for 2018 as well as restructures them to reflect conversations had during the 2018 proceedings committee meetings.

Key points:
- updates dates with new dates
- updates server link

There are also a number of major changes:
- This removes dates from the plaintext descriptions, making it easier to find and modify the dates in the future. 
    - plain text now refers to the named event that occurs on the date (not the date itself)
- This creates a top level schedule and Author/Reviewer specific list of Deadlines
- Author and Reviewer sections are now linked to and better encapsulated
    - this should make it possible to isolate these sections in separate files, 
    - this is part of a larger process to make the top-level README more useful in general while ensuring authors and reviewers have all the details they need.
- This adds *much* greater detail for new Authors on how to make a submission
- This adds a new section describing how to make PRs that change the build system
- This adds a new Organising principles section describing the ways in which Openness is manifested in the decisions made to organise the conference.
    - This is also part of the larger proecess to make the top-level README more generally useful
- This now links to the publisher README for more information.

@dalippa  I imagine you in particular would care about this PR.

2018-04-08 14:12 UTC, dalippa requested changes
👍 overall, but I had some suggestions

2018-04-08 14:12 UTC, dalippa commented on README.md
> +**All** communication between authors and reviewers should be civil. There are
Have we ever had a case where communication has not been civil?

2018-04-08 14:12 UTC, dalippa commented on README.md
> +- Conversations occur in the open, allowing for transparency in this open review
I would mention instead of "in the open" something about real names and user names attached to comments to hold authors/reviewers accountable.

2018-04-08 14:12 UTC, dalippa commented on README.md
> +## Timeline for 2018
You may want this in a separate file to make it easier to change for future years.

2018-04-08 14:12 UTC, dalippa commented on README.md
> +the PR's comment sections. It is important to remember in this case that we expect **all** communication between authors and reviewers to be civil.
Add something about what to do when deadlocked (e.g. reviewer requires a change that author is not willing to change). I would probably add something explicitly to the effect that the editors/cochairs of the proceedings have final say in acceptance to the proceedings.

You may want to add something about consequences of failure to follow the policies (authors may get rejected, new reviewers may be reassigned).

2018-04-08 14:12 UTC, dalippa commented on README.md
> +alert a Proceedings Co-Chair to this situation.
This should probably be higher up in the document.

2018-04-08 14:12 UTC, dalippa commented on README.md
> -## General Guidelines
General Deadlines, not guidelines. We don't want the dates to be considered flimsy. It's the exception and not the rule that an extension may be given.

2018-04-08 14:12 UTC, dalippa commented on README.md
> +5. Write your paper, commit changes, and build your paper.
You might want to cite the build paper instructions, since you're pretty detailed everywhere else and we don't want to duplicate. Also, consider adding a Step 7 for a final review on the build server to see what the final paper would look like (in case there is a risk it might look different locally)

2018-04-08 14:12 UTC, dalippa commented on README.md
> +**All** communication between authors and reviewers should be civil at all times.
You mention this multiple times. Is that intentional?

2018-04-08 14:12 UTC, dalippa commented on README.md
> +outstanding issues remaining. As a heuristic, if you think the paper should not
If there *is* a large outstanding issue, it should be escalated to the proceedings cochairs. We don't want to have what happened last year where we had to reject a paper last minute.

2018-04-08 18:21 UTC, deniederhut commented on README.md
> +**All** communication between authors and reviewers should be civil. There are
Better to have it and not need it than need it and not have it? We could also link to the CoC here

2018-04-08 18:32 UTC, deniederhut commented
Does this include the requirement to include DOIs for references? See #302

2018-04-08 20:09 UTC, mpacer commented on README.md
> +- Conversations occur in the open, allowing for transparency in this open review
Sounds great!

2018-04-08 20:10 UTC, mpacer commented on README.md
> +## Timeline for 2018
I more want to move the other sections into separate files than this one. If we could do an `\include{}` in markdown, that'd be a different story, but I think the timeline is one of the things everyone should see on the landing page.

2018-04-08 20:11 UTC, mpacer commented on README.md
> +the PR's comment sections. It is important to remember in this case that we expect **all** communication between authors and reviewers to be civil.
> Add something about what to do when deadlocked (e.g. reviewer requires a change that author is not willing to change). I would probably add something explicitly to the effect that the editors/cochairs of the proceedings have final say in acceptance to the proceedings.

Yes, that sounds great!

2018-04-08 20:11 UTC, mpacer commented on README.md
> +the PR's comment sections. It is important to remember in this case that we expect **all** communication between authors and reviewers to be civil.
> You may want to add something about consequences of failure to follow the policies (authors may get rejected, new reviewers may be reassigned).

You're right, though I'm not sure how to word that.

2018-04-08 20:12 UTC, mpacer commented on README.md
> -## General Guidelines
The `general Guidelines` text was removed not included — I find that looking at diffs in the split view (https://github.com/scipy-conference/scipy_proceedings/pull/364/files?diff=split) tends to make it easier to catch what is removed and what is added.

2018-04-08 20:13 UTC, mpacer commented on README.md
> +6. Repeat step 6, while also responding to reviewer feedback.
Oops, wrong number.

2018-04-08 20:13 UTC, mpacer commented on README.md
> +5. Write your paper, commit changes, and build your paper.
I was planning on adding links to the sections below that give more details.

2018-04-08 20:55 UTC, mpacer commented on README.md
> +**All** communication between authors and reviewers should be civil at all times.
Yes — it's important, but I can cut if if we want.

2018-04-08 20:55 UTC, mpacer commented on README.md
> +outstanding issues remaining. As a heuristic, if you think the paper should not
Yea that's true — I'll change this to make the case more explicit and dire sounding.

2018-04-08 20:55 UTC, mpacer commented on README.md
> +alert a Proceedings Co-Chair to this situation.
Do you have a suggestion as to where?

2018-04-08 20:55 UTC, mpacer commented on README.md
> +**All** communication between authors and reviewers should be civil. There are
Good idea, i'll link the CoC.

2018-04-09 01:17 UTC, deniederhut commented on README.md
> +the PR's comment sections. It is important to remember in this case that we expect **all** communication between authors and reviewers to be civil.
I'm not so sure. I would worry that a threat of future desk rejects might discourage people from submitting a paper to the proceedings.

2018-04-09 15:33 UTC, mpacer commented on README.md
> +the PR's comment sections. It is important to remember in this case that we expect **all** communication between authors and reviewers to be civil.
Good point, I’ll leave this as it is for now.

2018-04-10 02:35 UTC, mpacer commented on README.md
> +alert a Proceedings Co-Chair to this situation.
So I added a line above about Co-Chairs having a final say about acceptance and reiterated that that is to occur in this context as well.

2018-04-10 04:05 UTC, mpacer commented on README.md
> +**All** communication between authors and reviewers should be civil at all times.
I mention it in the reviewers and in the authors sections. Also I'm going to add the word respectful in addition to civil.

2018-04-10 04:19 UTC, mpacer commented
@deniederhut I'm adding a line in the General Author Guidelines to the effect : 

```
- All citations that have DOIs should include those DOIs in the paper's 
  references section, see [`mybib.bib`](./papers/00_bibderwalt/mybib.bib).
```

2018-04-10 13:31 UTC, deniederhut commented
👏 👏 👏

2018-04-10 16:26 UTC, mpacer commented
@dalippa does this satisfy what your review asked for?

2018-04-12 01:18 UTC, dalippa commented
Bravo zulu 👍

2018-04-12 01:18 UTC, dalippa approved these changes

2018-04-12 23:44 UTC, mpacer commented
KK, merging.

2018-04-12 23:44 UTC, merged