Update mailings
scipy-conference/scipy_proceedings pull request #369
Opened 2018-04-14 06:52 UTC by mpacer

So this does a few things to improve our existing email generating system.

The first thing it does is it standardises a few of the fields that had previously been template specific.

The second thing it does is introduces a new Mailer class which contains the common logic for all of the email scripts and reduces the amount of boilerplate we need to keep around in each script.

this new Mailer object is intended to be subclassed with the ability to customise the fields needed for the particular template with the `custom_data` property, as can be seen in the call_for_papers example.

@dalippa and @deniederhut If you have a chance to look at this, I'd appreciate it… i'm probably going to use this to send out the emails as soon as I have the list and I figure out how to hook this up to my gmail.

My (hard) todos on this are:

- [ ] Get session to connect appropriately
- [ ] Fix/clarify authentication logic
- [ ] setup new authors json based on the papers info

My (soft) todos on this are:
- [ ] update other scripts to use Mailer
- [ ] setup nicer addresses for the recipients

2018-04-15 17:32 UTC, mpacer commented
@gforsyth this is the email system we currently have up and running, if you have any suggestions on how to adapt it for the json that you'll be creating I'd appreciate it!

2018-04-15 17:50 UTC, dalippa requested changes

2018-04-15 17:50 UTC, dalippa commented on publisher/mail/_mailer.py
> +    editors = proc.get('editor', [])
to be consistent, consider using editor or editors, not both

2018-04-15 17:50 UTC, dalippa commented on publisher/mail/_mailer.py
> +def create_committee(data=None):
Why not use `**kwargs` here?

2018-04-15 17:50 UTC, dalippa commented on publisher/mail/_mailer.py
>          return
Consider moving the return statement below the `smtplib.SMTP` call so you can use the dry run to verify credentials against the mail server.

2018-04-15 17:50 UTC, dalippa commented on publisher/mail/_mailer.py
> +             print('file at {} not found'.format(os.path.abspath(s)))
If the data file doesn't exist, would it be better to raise an exception since the dependent functions cannot do what they need to do otherwise?

2018-04-15 17:50 UTC, dalippa commented on publisher/mail/_mailer.py
> +def load_data_sources(sources):
I think there is a way to merge dictionaries with `x.update(y)`. Why not use that instead of creating the new_dict over and over?

2018-04-15 17:50 UTC, dalippa commented on publisher/mail/_mailer.py
> +def editor_email_string(data=None):
Minor comment: these methods are implementation details used by the class; from a design standpoint, prefixing "private" methods with `_` is the usual convention.

2018-04-15 17:50 UTC, dalippa commented on publisher/mail/_mailer.py
> +        return 'blah@blah.org'
Is this a comma or semicolon delimited list? Usually a property that is in plural form returns a list, not a single string. At a minimum, consider documenting so classes that override this method would know the contract.

2018-04-15 17:50 UTC, dalippa commented on publisher/mail/_mailer.py
> +        self.dry_run = True
You use `self._sender` for member variables later, but `self.dry_run` here. Consider a consistent naming convention.

2018-04-15 17:50 UTC, dalippa commented on publisher/mail/_mailer.py
> +        return self._sender if self._sender else self.template_data["sender"]
What if the template_data has an empty string or something? Consider `self.template_data.get("sender")` which would raise an exception or `self.template_data.get("sender", "cochairs@scipy.org")` or something like that to provide a default.

2018-04-15 17:50 UTC, dalippa commented on publisher/mail/_mailer.py
> +    def display_message(self, recipients, message):
maybe `display_dryrun_message`?

2018-04-15 17:50 UTC, dalippa commented on publisher/mail/_mailer.py
>      if args.dry_run:
consider making the dry run message in the class below a static method and call it here.

2018-04-15 17:50 UTC, dalippa commented on publisher/mail/email.json
>     "reviewers": [
Change the reviewers too?

2018-04-15 17:50 UTC, dalippa commented on publisher/mail/templates/call_for_papers.txt.tmpl
> +look forward to seeing your poster or presentation! As in the past, SciPy2018
Use `{{year}}` here as well

2018-04-15 19:11 UTC, mpacer commented on publisher/mail/templates/call_for_papers.txt.tmpl
> +look forward to seeing your poster or presentation! As in the past, SciPy2018
I think this might be `{{conference}}`, but definitely a good idea.

2018-04-15 19:18 UTC, dalippa commented on publisher/mail/_mailer.py
>      session.quit()
try/finally on session quit?

2018-04-16 00:27 UTC, mpacer commented on publisher/mail/_mailer.py
> +def create_committee(data=None):
that might be possible… but I generally try to avoid using **kwargs and then testing if it's none. But I see where you're coming from.

2018-04-16 00:31 UTC, mpacer commented on publisher/mail/_mailer.py
> +        self.dry_run = True
I was using underscores to indicate private member variables not just member variables in general. I usually do that whenever I have a property for the public member variable, but still need to store the info somewhere.

2018-04-16 00:32 UTC, mpacer commented on publisher/mail/_mailer.py
> +def load_data_sources(sources):
You're right, there's gotta be a better way than this… i was trying to avoid update because of the way it changes everything in place, but you can't unpack dictionaries in a comprehension as far as I could tell.

2018-04-16 00:32 UTC, mpacer commented on publisher/mail/_mailer.py
> +             print('file at {} not found'.format(os.path.abspath(s)))
yes, I'll make that happen.

2018-04-16 00:38 UTC, mpacer commented on publisher/mail/_mailer.py
> +        return self._sender if self._sender else self.template_data["sender"]
If we use `self.template_data.get("sender")` it would return None, which wouldn't return an exception locally, it would raise an exception somewhere further down the line. 

also sender looks to be expected as a dict not a string, so I should probably make that work consistently.

2018-04-16 00:39 UTC, mpacer commented on publisher/mail/_mailer.py
> +        return self._sender if self._sender else self.template_data["sender"]
This is making me realise just how much of this logic is only for validating and working with these "name" "email" pairs… I should probably factor that out into its own class…

2018-04-16 00:42 UTC, mpacer commented on publisher/mail/email.json
>     "reviewers": [
They're just test reviewers… it actually helped me realise that because they were from so long ago.

2018-04-16 00:44 UTC, mpacer commented on publisher/mail/_mailer.py
>          return
I got this from the old way of approaching the problem… we could do that, but it would require passing in a password each time you wanted to do the dry_run, which would have put a huge amount of overhead when trying to iterate quickly over this code.

2018-04-16 00:48 UTC, mpacer commented on publisher/mail/_mailer.py
> +def editor_email_string(data=None):
I moved these methods inside the class, and now they should be able to be overwritten if needed… whether that would be necessary I'm not sure, but I can make them private if you want.

2018-04-16 00:50 UTC, mpacer commented on publisher/mail/_mailer.py
> +        return 'blah@blah.org'
Honestly, I was treating this as a string because that's sort of how it was being done before. 

In any case, I was slightly inclined to raise a `NotImplementedError`… since it shouldn't need to be set unless someone wants to do so explicitly.

2018-04-16 00:50 UTC, mpacer commented on publisher/mail/_mailer.py
>      if args.dry_run:
Great idea… I'll implement that shortly.

2018-04-16 00:52 UTC, mpacer commented on publisher/mail/_mailer.py
>      session.quit()
I'll add this in both here and the method.

2018-04-16 00:53 UTC, dalippa approved these changes
Minor recommendations. Feel free to fix them before merging, or after.

2018-04-16 00:53 UTC, dalippa commented on publisher/mail/_mailer.py
> +        are_str = lambda x: (isinstance(x['name'], str) and isinstance(x['email'], str))
not sure what `are_str` is here. Do you mean `is_str`?

2018-04-16 00:53 UTC, dalippa commented on publisher/mail/mail_call_for_papers.py
> +        # this is for testing
Minor: Consider moving this into a test file and creating a "fake" class `TestAuthorMailer` that subclasses `AuthorMailer` and does this.

2018-04-16 00:53 UTC, dalippa commented on publisher/mail/templates/call_for_papers.txt.tmpl
> +Papers must be submitted as pull requests by {{submission_date}}.
Consider combining this sentence with the prior and following sentences:

"To submit a paper to the proceedings, submit a pull request to {{github_url}} by {{submission_date}}, when the six-week open review period begins."

2018-04-16 00:53 UTC, mpacer commented on publisher/mail/_mailer.py
>      session.quit()
actually… doesn't the context manager already handle this?

2018-04-16 05:56 UTC, mpacer commented on publisher/mail/templates/call_for_papers.txt.tmpl
> +Papers must be submitted as pull requests by {{submission_date}}.
I originally did it and it read rather long & not obviously containing crucial information. These are both important pieces of information so I wanted them to be highlighted separately.

2018-04-16 05:58 UTC, mpacer commented
This was able to send off most of the emails we needed to send. With minimal issues.

For some reason it swallowed the `+scipyproc` from mpacer.phd+scipyproc@gmail.com, not sure why.

2018-04-17 17:07 UTC, mpacer commented
Ah — I think it it probably swallowed that because of the "login" value. I'll play around with that a bit to see if adding `.` and `+*` works as a login value.

2021-04-12 00:55 UTC, closed without merging