Organic Molecules in Space: Insights from the NASA Ames Molecular Database
scipy-conference/scipy_proceedings pull request #402
Opened 2018-05-23 01:39 UTC by mattjshannon

If you are creating this PR in order to submit a draft of your paper,
see http://procbuild.scipy.org/ for logs generated by the build
process.

See the [project readme](https://github.com/scipy-conference/scipy_proceedings#build-your-paper)
for more information.

2018-06-10 02:51 UTC, dalippa requested changes
Overall notes:
* Well written introduction/scientific background, but the later parts of the paper are a bit more convoluted. The paper could be reduced substantially for readability, and could include more code samples to improve reproducibility. Graphics add value to understanding the contributions of pypahdb.
* Explain the contribution of the library separately from the site. Jumping around between these two dilutes the flow of the paper.
* Consider using active voice more than passive voice
* Cite web sites as you would other articles to improve the paper's flow/readability
* acronym "pyPAHdb" is inconsistently all lowercase or written as "pyPAHdb".
* Use consistent syntax for either American or British English (e.g. whilst vs while)
* Paper oscillates between a highly technical tone (when discussing the science behind the library), and a very informal tone (when talking about the software itself). Paper sometimes reads like it was written in sections by two different people and then combined, rather than a unified author.
* Discussion of further testing required is a substantial issue. If the library has not been significantly tested, the value of the library (and therefore the paper) is in doubt. What testing has been performed to ensure parity with the IDL tools?

2018-06-10 02:51 UTC, dalippa commented on papers/matthew_shannon/mshannon.rst
> +:cite:`1998ApJ...498..579G`. Those astronomers who study star- and
extremely minor: remove hyphen or add to next line: "... study star- and planet-formation" or "... study star and planet formation".

2018-06-10 02:51 UTC, dalippa commented on papers/matthew_shannon/mshannon.rst
> +with the software developed at the NASA Ames Research Center.
This software package? or others? If not this package, why is this comment relevant?

2018-06-10 02:51 UTC, dalippa commented on papers/matthew_shannon/mshannon.rst
> +culmination of more that 30 years of laboratory and computational
"more than"?

2018-06-10 02:51 UTC, dalippa commented on papers/matthew_shannon/mshannon.rst
> +that enables astronomers to probe and quantitatively analyze the state
Paragraph is essentially two sentences; may need to be broken up some for readability.

For example: this sentence is a bit long and awkward. Recommend putting one of them (the second one) in parentheses to improve readability: "... analyze the state of the PAH population, such as ionization balance, size, structure, and composition and tie these to the prevailing local astrophysical conditions (e.g. electron density, ...)"

2018-06-10 02:51 UTC, dalippa commented on papers/matthew_shannon/mshannon.rst
> +At `www.astrochemistry.org/pahdb/
Consider writing this as a download citation to remove the sentence

2018-06-10 02:51 UTC, dalippa commented on papers/matthew_shannon/mshannon.rst
> +screenshot of the website's landing page. Downloads are offered
Why is the landing page significant?

2018-06-10 02:51 UTC, dalippa commented on papers/matthew_shannon/mshannon.rst
> +with a diameter of 6.5 m made up from 18 individual hexagonal segments
Avoid unnecessary jargon: are the telescope specifications relevant to the discussion of the paper?

2018-06-10 02:51 UTC, dalippa commented on papers/matthew_shannon/mshannon.rst
> +   3D-rendering of *JWST* using the Maya® 3D animation, modeling,
I think it might be sufficient to cite papers regarding the JWST rather than side-tracking the paper with it. What matters is that pypahdb was designed to analyze its data.

2018-06-10 02:51 UTC, dalippa commented on papers/matthew_shannon/mshannon.rst
> +alone. pypahdb is the Lite version of the full suite of Python
Lite -> light

2018-06-10 02:51 UTC, dalippa commented on papers/matthew_shannon/mshannon.rst
> +On the eve of the *JWST* era, it is our goal to make PAHdb a go-to
Recommend: "... make PAHdb the astronomical community's primary tool for analyzing and interpreting PAH emission spectra."

2018-06-10 02:51 UTC, dalippa commented on papers/matthew_shannon/mshannon.rst
> +<4 seconds, while >60 seconds were needed to fit with the full IDL suite.
write out "less than" and "more than"

2018-06-10 02:51 UTC, dalippa commented on papers/matthew_shannon/mshannon.rst
> +It should be noted that their were differences in the actual implementation of
What were the differences?

2018-06-10 02:51 UTC, dalippa commented on papers/matthew_shannon/mshannon.rst
> +redshift of 15 cm\ :sup:`-1` is applied to each of the band positions
Where did the redshift value come from?

2018-06-10 02:51 UTC, dalippa commented on papers/matthew_shannon/mshannon.rst
> +   large-to-small PAHs (PAHs are considered large when they contain 30
Consider rephrasing the sentences here not to use parentheses to improve sentence flow, such as "... and the lower panel the breakdown of PAHs in descending order from the largest, containing 30 atoms or more, to the smallest."

2018-06-10 02:51 UTC, dalippa commented on papers/matthew_shannon/mshannon.rst
> +across NGC 7023. As one would expect, the fraction is systematically
"As one would expect" -> "As expected"

2018-06-10 02:51 UTC, dalippa commented on papers/matthew_shannon/mshannon.rst
> +The future
Instead of "The future", consider "Future Work"

2018-06-10 02:51 UTC, dalippa commented on papers/matthew_shannon/mshannon.rst
> +analysis tool is anticipated to be complete well before *JWST*'s launch, which is
Is this library a stable beta? Active development does not detract from how production-ready software is. Is the library in a finalized state? If so, that should be stated, along with enhancements to coincide with the JWST's launch in 2020.

2018-06-10 02:51 UTC, dalippa commented on papers/matthew_shannon/mshannon.rst
> +*SOFIA*, etc. Our current efforts are focused on streamlining pypahdb,
Streamlining how? The API?

2018-06-10 02:51 UTC, dalippa commented on papers/matthew_shannon/mshannon.rst
> +will be performed to ensure all parts of pypahdb function as
I would consider removing this sentence; if the library hasn't been tested, it almost refutes the value of the paper. What testing has already been done to ensure that it is correct?

2018-06-10 02:51 UTC, dalippa commented on papers/matthew_shannon/mshannon.rst
> +and variations in PAH charge and size.
The paper transitions into future work a bit abruptly.

2018-06-14 21:40 UTC, mattjshannon commented on papers/matthew_shannon/mshannon.rst
> +At `www.astrochemistry.org/pahdb/
Do you mean making a bibtex entry for it? Sorry, I'm pretty new to markdown! Thanks.

2018-06-14 21:47 UTC, mattjshannon commented on papers/matthew_shannon/mshannon.rst
> +screenshot of the website's landing page. Downloads are offered
Our mistake -- landing page is the wrong term here, as we replaced the figure to instead show the information page for a specific PAH (C32H14). I suppose this figure serves as an example of a PAH's appearance (carbon skeleton with hydrogen atoms attached to its edges), in addition to some properties/vibrational modes of the molecule itself accessible at the website. Do you think we should replace this figure with just a diagram of a typical PAH (e.g., https://en.wikipedia.org/wiki/Ovalene#/media/File:Ovalene_3D_ball.png)?

2018-06-14 23:42 UTC, mattjshannon commented
Dear reviewer,

Thank you for your comments. We are working on implementing your suggested changes. We just have a few questions/clarifications we'd like to ask you.

Comment: "Well written introduction/scientific background, but the later parts of the paper are a bit more convoluted. The paper could be reduced substantially for readability, and could include more code samples to improve reproducibility."
Question: Are there any specific sections/subsections that you think should be shortened/reduced? We will add more code samples per your suggestion.

Comment: "Explain the contribution of the library separately from the site. Jumping around between these two dilutes the flow of the paper."
Question: I believe you are referring to the second major section, labelled "NASA Ames PAH IR Spectroscopic Database (PAHdb)". Would an acceptable solution be to split this section into two subsections, one describing the database itself (PAHdb), and the other describing how the website that serves as the access point for the database?

Comment: "Paper oscillates between a highly technical tone (when discussing the science behind the library), and a very informal tone (when talking about the software itself). Paper sometimes reads like it was written in sections by two different people and then combined, rather than a unified author."
Question: You are absolutely right. We will work on improving the consistency of the writing throughout the paper. Is it fair to assume that we should make the parts about the software itself less informal?

Comment: "Discussion of further testing required is a substantial issue. If the library has not been significantly tested, the value of the library (and therefore the paper) is in doubt. What testing has been performed to ensure parity with the IDL tools?"
Question/clarification: There is a distinction between the 'library' (PAHdb) and the 'software' (pyPAHdb) that we have not made clear enough -- sorry about that. The libraries of laboratory and DFT-computed spectra have supported astrochemistry for over three decades and continues to be a valuable resource for the astronomical community to interpret observations; these data have been validated in their own right. Software tools that use those libraries include those available online at the website, through IDL and through Python. pyPAHdb is considered a light version of a full Python suite of analysis tools. Parity between the different language implementations have been tested by considering the same data set and doing a complete analysis; there is a one-on-one parity between the implementations, i.e., the exact same results are obtained. The testing we refer to is not regarding the spectral library, the PAH emission model nor the database-fitting approach. Rather, the testing we refer is regarding program logic, i.e., can we 'blindly' import input spectra encapsulated in different data formats; CSV, XML, FITS, etc., can we 'blindly' trust the parallelism mechanisms (it turns out not, as on MacOS multiprocessing and numpy.cdot don't work well together), etc. We intend to rework the text to make these points clear and apologize for the confusion.

Thank you!

2018-06-15 02:03 UTC, dalippa commented on papers/matthew_shannon/mshannon.rst
> +At `www.astrochemistry.org/pahdb/
Yes, as a bibtex entry. Sorry, we just started doing that more regularly this year, and in past years, it was done differently.

2018-06-15 02:08 UTC, dalippa commented
My comments are in-line

Comment: "Well written introduction/scientific background, but the later parts of the paper are a bit more convoluted. The paper could be reduced substantially for readability, and could include more code samples to improve reproducibility."
Question: Are there any specific sections/subsections that you think should be shortened/reduced? We will add more code samples per your suggestion.

> It was an overall comment, and I saw it happen in more than one section. Let's start the conversation this way: what sections do you think can be shortened?

Comment: "Explain the contribution of the library separately from the site. Jumping around between these two dilutes the flow of the paper."
Question: I believe you are referring to the second major section, labelled "NASA Ames PAH IR Spectroscopic Database (PAHdb)". Would an acceptable solution be to split this section into two subsections, one describing the database itself (PAHdb), and the other describing how the website that serves as the access point for the database?

> Yes, that's a good way to do this.

Comment: "Paper oscillates between a highly technical tone (when discussing the science behind the library), and a very informal tone (when talking about the software itself). Paper sometimes reads like it was written in sections by two different people and then combined, rather than a unified author."
Question: You are absolutely right. We will work on improving the consistency of the writing throughout the paper. Is it fair to assume that we should make the parts about the software itself less informal?

> I would make the writing *consistent*. Making the parts about the software itself less informal would be great.

Comment: "Discussion of further testing required is a substantial issue. If the library has not been significantly tested, the value of the library (and therefore the paper) is in doubt. What testing has been performed to ensure parity with the IDL tools?"
Question/clarification: There is a distinction between the 'library' (PAHdb) and the 'software' (pyPAHdb) that we have not made clear enough -- sorry about that. The libraries of laboratory and DFT-computed spectra have supported astrochemistry for over three decades and continues to be a valuable resource for the astronomical community to interpret observations; these data have been validated in their own right. Software tools that use those libraries include those available online at the website, through IDL and through Python. pyPAHdb is considered a light version of a full Python suite of analysis tools. Parity between the different language implementations have been tested by considering the same data set and doing a complete analysis; there is a one-on-one parity between the implementations, i.e., the exact same results are obtained. The testing we refer to is not regarding the spectral library, the PAH emission model nor the database-fitting approach. Rather, the testing we refer is regarding program logic, i.e., can we 'blindly' import input spectra encapsulated in different data formats; CSV, XML, FITS, etc., can we 'blindly' trust the parallelism mechanisms (it turns out not, as on MacOS multiprocessing and numpy.cdot don't work well together), etc. We intend to rework the text to make these points clear and apologize for the confusion.

> If the testing is not with regard to the spectral library but the program logic, some additional clarity would be welcome.

2018-06-21 07:04 UTC, suzanne-stathatos commented
Overall, well-written and well-organized paper. I appreciated the sections and subsections to help lead the readers in the right direction. I also like that you give sufficient background on PAH before diving into the software. However, I worry that too little of the focus is on the python tool. I would like to see more detail about the python in your paper. I would also like to have a greater understanding of how I could reproduce the results. I've organized my comments to follow with each of the sections.

**Science Rationale:** 
_Polycyclic aromatic hydrocarbons_
Rather than saying *that* they're important, start with *how* they are important - i.e. PAH molecules are critical to our spectroscopic understanding of the Universe. 

There's a lot of what in this section, and it's unclear how it relates back to the python - does it matter that the molecules are large? Does it matter how many carbon atoms they have? Does their geometric shape matter w.r.t. the python tool? 

_The importance of astronomical PAHs_

Some of the sentences are long/verbose and could be shortened/split up. They could also use the active tense I.e 

Over time, PAHs are incorporated into dense clouds, wherein they participate in ongoing chemistry and are eventually brought into newly-forming star and budding planetary systems 

Could be 

Over time, dense clouds incorporate PAHs. This integration stimulates ongoing chemical reactions, which create new stars and planetary systems 

The third paragraph in this section (Thanks to their ubiquity...) is the best and clearest indicator of PAHs significance. I might shuffle this up to the top and let the other paragraphs support it.

treasure trove of information - sounds a bit colloquial

_The next great facility for PAH research: JWST_

This sentence could use some rewording for clarification. It could also be more specific - is the python tool part of the new tools you're talking about? It's the only tool this paper cares about, so be explicit about it

To best exploit the extensive capabilities of JWST, we will provide new tools for the astronomical community, as JWST will be the foremost platform for astronomical PAH research for years to come.

**NASA Ames PAH IR Spectroscopic Database (PAHdb)**

This database includes.. is a very long sentence.

These sentences

However, Python is seeing increasingly widespread usage among astronomers, in part due to its nonproprietary nature. Python has significantly matured over the last two decades and many astronomical utilities once only available through IDL and/or IRAF have been ported to Python (e.g., PyFITS; www.astropy.org). Notably, many of the astronomical utilities offered by the Space Telescope Science Institute, including the Data Analysis Toolbox for use with NASA’s upcoming James Webb Space Telescope (JWST; www.jwst.nasa.gov), are being developed in Python

Can probably be made more concise. I.e. 

However, due to Python's maturity,  and increased utility, JWST's Data Analysis software tools are being developed in Python.

**pyPAHdb: a tool designed for JWST**

It looks like the first sentence still needs some editing. There are ellipses in the built pdf.

You describe the hope of the tool a lot in this first paragraph, along with the ERS program. I'd rather see more initially on what the tool is and what it does. The ERS program, for example, shouldn't matter in this discussion, so long as a reference is provided. 

I'd remove the first paragraph and begin with the second paragraph (pyPAHdb analyzes spectroscopic observations....) 

It should be noted that their -> there

A table comparison of pyPAHdb vs. IDL would be useful in comparing the two tooling suites. It might also be worth noting the computational power of what the tools will be running on - does it matter if they are fast/slow?

_The underlying PAH physics_

You rush over a lot of details in this first paragraph. I'd like to see more here.

How will all of these features (vibrational temperature, spectral intensity, etc.) be used by the python tool? 

What database fitting do you do? Why did you choose to use non-negative least squares?

_Demonstration_ 

Figure ?? -> Figure 6?

_Summary and Prospects_

a guide with analysis "recipes" - very informal tone for a paper, and I'm not entirely sure I understand what you mean by recipe.

This seems too early to give a future works type of section. The prospect is the tool will continue to be worked on - why do you want to consolidate output parameters? What digital formats do you want to support? Why?

2018-06-21 23:59 UTC, mattjshannon commented
Hi Suzanne,

Thanks very much for the comments. We appreciate you taking the time. We are in the process of applying your suggested changes (including shortening some unnecessarily long sections, which was certainly the case). We are both somewhat new to GitHub, so we will have a few commits coming in the next few days (while working on the changes). I'll make another comment in this PR when I think we are ready for another evaluation.

Thank you!
Matt

2018-06-28 00:37 UTC, mattjshannon commented
Dear reviewers,

We have attempted to address all of your suggestions with our latest commits. Please let us know if there are any additional modifications you would like to see. Thank you kindly for your time.

2018-06-30 22:42 UTC, deniederhut commented
Dear @dalippa and @suzanne-stathatos , do you feel this paper is now ready for inclusion in the proceedings?

2018-07-01 12:44 UTC, dalippa requested changes
@mattjshannon The paper is close to ready. There are a few minor changes I am recommending.

1. Revisit where you use dashes like "class-attribute" and "decomposer-object".
2. Consider moving longer side notes into footnotes for greater readability.

@suzanne-stathatos do you have anything to add?

2018-07-01 12:44 UTC, dalippa commented on papers/matthew_shannon/mshannon.rst
> +    ``spectrum``-object, which holds the data in terms of absissa and
minor: ``spectrum`` object. No dash needed.

2018-07-01 12:44 UTC, dalippa commented on papers/matthew_shannon/mshannon.rst
> +    ordinate values using ``numpy``-arrays. The units associated with
minor: ``numpy`` arrays. No dash needed.

2018-07-01 12:44 UTC, dalippa commented on papers/matthew_shannon/mshannon.rst
> +    stored as a class-attribute. The spectral coordinate system is
"class attribute"

2018-07-01 12:44 UTC, dalippa commented on papers/matthew_shannon/mshannon.rst
> +    to wavenumber. Subsequently, a pre-computed ``numpy``\-matrix of
Minor: ``numpy`` matrix

2018-07-01 12:44 UTC, dalippa commented on papers/matthew_shannon/mshannon.rst
> +Summary
Consider adding a "future work" section. Consider renaming "Summary" to "Conclusion"

2018-07-01 12:44 UTC, dalippa commented on papers/matthew_shannon/mshannon.rst
> +    (see the Section "The underlying PAH-photo physics" for more
Consider moving side notes into footnotes for greater readability.

2018-07-03 16:44 UTC, suzanne-stathatos commented
This looks good to me!

2018-07-04 02:55 UTC, dalippa approved these changes

2018-07-04 23:45 UTC, merged