Paper: Practical Applications of Astropy
scipy-conference/scipy_proceedings pull request #404
Opened 2018-05-23 16:11 UTC by stargaser

The paper includes examples from the Zwicky Transient Facility project. A number of first light papers are in preparation with submission targeted for early June. 

The talk is in the astronomy mini-symposium.

If you are creating this PR in order to submit a draft of your paper,
see http://procbuild.scipy.org/ for logs generated by the build
process.

See the [project readme](https://github.com/scipy-conference/scipy_proceedings#build-your-paper)
for more information.

2018-06-18 19:32 UTC, PBarmby requested changes
Hi David - please find some comments and suggestions below. A few more general comments:
- right now the figures are not referenced in the text
- is there a public repository for the code described here? Please link if so.
- are there "lessons learned" for astropy from your deployment?  Did any of these get fed back to that project?

2018-06-18 19:32 UTC, PBarmby commented on papers/david_shupe/david_shupe.rst
> +The Zwicky Transient Facility (ZTF) is a new robotic survey now underway, using the 48-inch
If there is a reference describing ZTF, please add.

2018-06-18 19:32 UTC, PBarmby commented on papers/david_shupe/david_shupe.rst
> +wide-area time-domain survey designed to discove fast, young and rare flux transients;
typo

2018-06-18 19:32 UTC, PBarmby commented on papers/david_shupe/david_shupe.rst
> +variable stars and eclipsing binaries; and Solar System objects. The entire visible sky
This list of events has a lot of astro-jargon. Don't know that you want to explain all of them; a reference describing time-domain astro in general is probably enough.

2018-06-18 19:32 UTC, PBarmby commented on papers/david_shupe/david_shupe.rst
> +on sky location, 0.5 to 1 billion point source measurements are extracted per
suggest "individual object" for "point source" (less jargon-y)

2018-06-18 19:32 UTC, PBarmby commented on papers/david_shupe/david_shupe.rst
> +The Astropy Project is a community-driven effort to provide both a core Python package of
Reference in text as well as abstract?

2018-06-18 19:32 UTC, PBarmby commented on papers/david_shupe/david_shupe.rst
> +night. Within a few minutes of receipt of an exposure at IPAC, a real-time pipeline
IPAC and several other abbreviations (SCAMP, LDAC, WCS, etc) not spelled out when first used.

2018-06-18 19:32 UTC, PBarmby commented on papers/david_shupe/david_shupe.rst
> +rms. Atmospheric effects cause distortions on small scales, and these effects are
suggest "image distortions" or maybe "optical distortions"

2018-06-18 19:32 UTC, PBarmby commented on papers/david_shupe/david_shupe.rst
> +the WCS in the LDAC file of detections using astropy.io.fits were unsuccessful.
Suggest a reference to one of the WCS definition papers somewhere here.

2018-06-18 19:32 UTC, PBarmby commented on papers/david_shupe/david_shupe.rst
> +the right ascensions and declinations to eta, nu in the tangent plane:
eta, nu are italicized elsewhere. Define here?

2018-06-18 19:32 UTC, PBarmby commented on papers/david_shupe/david_shupe.rst
> +The statsmodels package is used to fit a linear model relating image pixel values
astropy.statsmodels ?

2018-06-18 19:32 UTC, PBarmby commented on papers/david_shupe/david_shupe.rst
> +a linear fit is made to yield CD-matrix values for each quadrant. This procedure
CD-matrix needs explanation

2018-06-18 19:32 UTC, PBarmby commented on papers/david_shupe/david_shupe.rst
> +outer CCDs. We use an AltAz model to recompute airmass when analyzing statistics:
statistics of what?

2018-06-18 19:32 UTC, PBarmby commented on papers/david_shupe/david_shupe.rst
> +* It is possible to make code that knows nothing about Astropy or Python,
(by which you mean SCAMP?)

2018-06-18 19:32 UTC, PBarmby commented on papers/david_shupe/david_shupe.rst
> +Astropy is also used to provide heliocentric julian dates for each source.
typo "julian"

2018-06-18 19:32 UTC, PBarmby commented on papers/david_shupe/david_shupe.rst
> +frame is defined at the maximum coordinate for a field, and then a 9x9 grid
This should no doubt be obvious - but why the maximum coordinate?

2018-06-18 19:32 UTC, PBarmby commented on papers/david_shupe/david_shupe.rst
> +frame. This provides an accuracy in the calculation of the heliocentric date
Do you mean accuracy or precision here? "Less than" can be confusing - would "better than" be clearer?

2018-06-18 19:32 UTC, PBarmby commented on papers/david_shupe/david_shupe.rst
> +.. code-block:: python
This block is long enough that it would be helped by a few comments

2018-06-18 19:32 UTC, PBarmby commented on papers/david_shupe/david_shupe.rst
> +  offset_frame is very usefel when working on a patch of sky.
typo: "useful"

2018-06-18 19:32 UTC, PBarmby commented on papers/david_shupe/david_shupe.rst
> +distance to the star or galaxy of interest. Plotly Dash was chosen as the
Ref for Plotly Dash

2018-06-18 19:32 UTC, PBarmby commented on papers/david_shupe/david_shupe.rst
> +Here is another example:
Suggest explaining this a bit more: what is the nef function, what equations does it implement?

2018-06-18 19:32 UTC, PBarmby commented on papers/david_shupe/david_shupe.rst
> +The Planck 2015 cosmology is one of the built-in cosmologies in the package.
Needs reference

2018-06-18 19:32 UTC, PBarmby commented on papers/david_shupe/david_shupe.rst
> +For re-gridding the wavelength spectrum, we used the pysynphot package to interpolate
Needs reference

2018-06-18 19:32 UTC, PBarmby commented on papers/david_shupe/david_shupe.rst
> +The application has been deployed on the Heroku platform [#]_.
Any lessons learned in this section?

2018-06-18 19:32 UTC, PBarmby commented on papers/david_shupe/david_shupe.rst
> +Space Telescope.
Please add one or two sentences summarizing the lessons learned, future work.

2018-06-21 13:50 UTC, alexabate reviewed
These are what I found to be the main issues:
* It's hard to tell which pieces being described are related to astropy and which are not
* Each section could do with a tiny intro about what the processing is trying to achieve (input data -> output data)
* Clear description on what features astropy has that made it the package chosen for the application
* Clear explanation of the details of how astropy was applied in each specific case (again because it's hard to tell which is astropy/some other package/general astronomy issues)

2018-06-21 13:50 UTC, alexabate commented on papers/david_shupe/david_shupe.rst
> +modules, making especially heavy use of world coordinate systems, FITS header manipulation,
Remove “world coordinate systems” because it's too jargon-y for an abstract and it can be considered to be under “coordinate conversions” anyway

2018-06-21 13:50 UTC, alexabate commented on papers/david_shupe/david_shupe.rst
> +module provides easy redshifting of our template galaxy spectrum, and astropy.units enabled
Make the tenses consistent in this last sentence

2018-06-21 13:50 UTC, alexabate commented on papers/david_shupe/david_shupe.rst
> +The ZTF data system (Masci et al. in prep) is operated by the IPAC data center
Move this sentence ("The ZTF data system (Masci et al. in prep)") to just before the sentence "Within a few minutes of receipt of an exposure at IPAC ..."

2018-06-21 13:50 UTC, alexabate commented on papers/david_shupe/david_shupe.rst
> +
You can shorten this code snipped by creating one dict to loop over

2018-06-21 13:50 UTC, alexabate commented on papers/david_shupe/david_shupe.rst
> +++++++++++++++++++++++++++++++++
A more descriptive title of what is being implemented here would be helpful

2018-06-21 13:50 UTC, alexabate commented on papers/david_shupe/david_shupe.rst
> +be provided in LDAC FITS format. This format consists of header information encoded in
LDAC catalog format needs reference and probably also an explanation

2018-06-21 13:50 UTC, alexabate commented on papers/david_shupe/david_shupe.rst
> +However, the header information in the LDAC file can be overridden by a text file
Is ability to override the header information something that is unique to astropy?

2018-06-21 13:50 UTC, alexabate commented on papers/david_shupe/david_shupe.rst
> +a linear fit is made to yield CD-matrix values for each quadrant. This procedure
👍

2018-06-21 13:50 UTC, alexabate commented on papers/david_shupe/david_shupe.rst
> +the right ascensions and declinations to eta, nu in the tangent plane:
👍

2018-06-21 13:50 UTC, alexabate commented on papers/david_shupe/david_shupe.rst
> +transfers the pointing to the center of each individual qudrant-image.
qudrant typo

2018-06-21 13:50 UTC, alexabate commented on papers/david_shupe/david_shupe.rst
> +Parameters for each quadrant are saved to be used by the astrometry pipeline. The
What are the parameters here? CD matrix, CRPIX1 etc?

2018-06-21 13:50 UTC, alexabate commented on papers/david_shupe/david_shupe.rst
> +developed a scale check test of the final solution against the prior.
Same as the distortion prior mentioned at the beginning of the sentence

2018-06-21 13:50 UTC, alexabate commented on papers/david_shupe/david_shupe.rst
> +++++++++++++++++++++++++++++++++
Also a pipeline diagram would be incredibly helpful in showing exactly what is being processed here

2018-06-21 13:50 UTC, alexabate commented on papers/david_shupe/david_shupe.rst
> +
Is `SkyCoord` from astropy? Unclear at this stage

2018-06-21 13:50 UTC, alexabate commented on papers/david_shupe/david_shupe.rst
> +Another critical speed improvement was in pre-fetching static copies of
Was this speed improvement helped by astropy?

2018-06-21 13:50 UTC, alexabate commented on papers/david_shupe/david_shupe.rst
> +file is overwritten every time a different versions of Astropy version is imported.
Overwriting of a config file on import sounds terrifying? Why does astropy do this?

2018-06-22 20:55 UTC, stargaser commented
@PBarmby and @alexabate -- thank you very much for your review and comments. I've been working through the smaller ones and following how the LSST pipeline developers do it, I'll put a thumbs-up on the straightforward ones as I fix them (so as not to generate lots of emails).

Addressing the global issues raised:

- Neither of the code repositories are public. In both cases (ZTF and the OST tool) there is non-Python code for which we lack permission to release. My goal is to pull out some useful code examples where Astropy was used to solve a problem. I'll tighten this up per your recommendations and try to include, for each example, a clearer statement of the problem and to make explicit where Astropy was used.
- There are a couple of lessons learned that could be fed back to the Astropy project. Astropy has been conducting a survey of performance issues. I'll make sure we feed back the configuration file issue, and speeding up the calculation of heliocentric dates.

I'm aiming to push an updated version by Monday, July 25.

2018-06-23 00:03 UTC, stargaser commented on papers/david_shupe/david_shupe.rst
> +
I'm not sure I understand...combine `field_ra` and `field_dec` into one dict?

2018-06-23 00:05 UTC, stargaser commented on papers/david_shupe/david_shupe.rst
> +be provided in LDAC FITS format. This format consists of header information encoded in
Added a footnote.

2018-06-23 00:07 UTC, stargaser commented on papers/david_shupe/david_shupe.rst
> +night. Within a few minutes of receipt of an exposure at IPAC, a real-time pipeline
LDAC and WCS now expanded. I'm changing SCAMP to *Scamp* since it isn't an acronym. IPACers have been directed not to use the old acronym expansion as part of a rebranding to expand beyond infrared.

2018-06-23 00:22 UTC, stargaser commented on papers/david_shupe/david_shupe.rst
> +the right ascensions and declinations to eta, nu in the tangent plane:
Yes, italicized now, and called "projection plane coordinates" with reference to Calabretta and Greisen 2002 (WCS Paper II).

2018-06-23 00:23 UTC, stargaser commented on papers/david_shupe/david_shupe.rst
> +The statsmodels package is used to fit a linear model relating image pixel values
Not part of Astropy so I'll just say a linear fit is made...

2018-06-23 00:31 UTC, stargaser commented on papers/david_shupe/david_shupe.rst
> +
added imports to make clear this comes from Astropy

2018-06-23 14:19 UTC, alexabate commented on papers/david_shupe/david_shupe.rst
> +
```
field_radec = {619: (143.619, 26.15), ... }
```
or 
```
field_radec = {619: {'ra': 143.619, 'dec': 26.15}, ... }
```
then (if dict value is tuple)
`for field, (ra, dec) in field_radec.items():`

2018-06-26 23:36 UTC, stargaser commented
Addressed many of the comments and suggestions. Still a few items outstanding:

- Pipeline diagram for the astrometry discussion
- Break up large code block on light-travel-times / heliocentric modified Julian dates with some more explanation
- In each section, introducing what the processing tries to achieve and making clear the features of Astropy that made it possible

2018-06-29 21:21 UTC, deniederhut commented
Hi @stargaser ! Is this ready for the reviewers to take another look?

2018-06-30 05:28 UTC, stargaser commented
@deniederhut I think I have addressed everything except adding a pipeline diagram. I also have in hand some minor wording comments from a coauthor. I could have these done the evening of 6/30 (tomorrow), but if we're out of time, I could forego them.

2018-06-30 22:02 UTC, deniederhut commented
I just want to make sure that we're leaving enough time for the reviewers to have a second pass.

Dear @PBarmby and @alexabate, do you feel this paper is ready for inclusion in the proceedings?

2018-07-01 04:18 UTC, stargaser commented
@deniederhut I've just pushed everything I planned to put in. @PBarmby and @alexabate , many thanks to you for the comments. All of this will help the talk in any event.

2018-07-03 14:38 UTC, PBarmby commented
@deniederhut I think it's ready for inclusion.

2018-07-06 14:21 UTC, deniederhut commented
Hey @alexabate ! I think this paper is still waiting on your approval

2018-07-10 02:38 UTC, deniederhut commented
The number of authors on that Planck 2015 paper :eyes: 

I'm going to step for @alexabate and mark this as ready.

2018-07-17 22:46 UTC, merged