submission of draft
scipy-conference/scipy_proceedings pull request #405
Opened 2018-05-23 16:34 UTC by sjsrey

If you are creating this PR in order to submit a draft of your paper,
see http://procbuild.scipy.org/ for logs generated by the build
process.

See the [project readme](https://github.com/scipy-conference/scipy_proceedings#build-your-paper)
for more information.

2018-06-19 03:20 UTC, msarahan commented
I'm far from an expert here, but I found this paper interesting to read as someone interested in demographic trends for studying the effects of gerrymandering.  I have nothing to recommend or add to this paper, other than to say nice work.

2018-06-20 04:56 UTC, FatihAkici requested changes
Overall very good paper and tool. Thanks for your contribution to SciPy 2018! Other than a few comments that I left in-line, my two main comments regarding the overall quality of the paper are:

1. The title and abstract are too broad. It would be better both for the paper and reader if OSLNAP, the center of this paper, was mentioned in both title and abstract.
2. Figures are unreadable. Please make them bigger.

Thank you!

2018-06-20 04:56 UTC, FatihAkici commented on papers/serge_rey/serge_rey.rst
> +Spatio-temporal analysis of socioeconomic neighborhoods
Title is too broad. Since this is a paper on the OSLNAP tool, and not the analysis of socioeconomic neighborhoods per se, why not include that in the title?

2018-06-20 04:56 UTC, FatihAkici commented on papers/serge_rey/serge_rey.rst
> +spatially explicit approaches to the study of longitudinal neighborhood dynamics
"we discuss the development of novel, spatially explicit approaches..." sounds too broad to me. "We discuss the development of a novel, spatially explicit tool, OSLNAP..." sounds more accurate and appealing to the reader.

2018-06-20 04:56 UTC, FatihAkici commented on papers/serge_rey/serge_rey.rst
> +   connections to  pubilic data services
Typo: pubilic

2018-06-20 04:56 UTC, FatihAkici commented on papers/serge_rey/serge_rey.rst
> +space-time data set, the ``cluster`` module allows users to cluster (a) a single
What "the cluster module allows..." is a little unclear. Can you extend this a little bit? For example, what do you mean by clustering a single time period? I believe clustering neighborhoods at a given time? These capabilities deserve a little more detailed explanation with examples to illustrate the idea better.

2018-06-20 04:56 UTC, FatihAkici commented on papers/serge_rey/serge_rey.rst
> +been assigned a categorical variable for each point in time (e.g.the output of
Space after e.g.

2018-06-20 04:56 UTC, FatihAkici commented on papers/serge_rey/serge_rey.rst
> +interested in. For example, the cost of substution may capture units' socioeconomic
Typo: substution

2018-06-20 04:56 UTC, FatihAkici commented on papers/serge_rey/serge_rey.rst
> +We allows for various cost functions and further extend the definition
Typo: We allows

2018-06-20 04:56 UTC, FatihAkici commented on papers/serge_rey/serge_rey.rst
> +of the neighborhood boundaries identified are remarkably stable, such as
Typo: some of the of the

2018-06-20 04:56 UTC, FatihAkici commented on papers/serge_rey/serge_rey.rst
> +maps can serve as foundations for descriptive analyses or analyzed as
"or be analyzed"

2018-06-20 04:56 UTC, FatihAkici commented on papers/serge_rey/serge_rey.rst
> +directly comparable over time. Thus, we focuses only on the
Typo: we focuses

2018-06-20 04:56 UTC, FatihAkici commented on papers/serge_rey/serge_rey.rst
> +:math:`(14,14)` transition probability matrices for ward and affinity
Typo: ward -> Ward

2018-06-20 04:56 UTC, FatihAkici commented on papers/serge_rey/serge_rey.rst
> +census years. This is especially true for the ward neighborhood type 4 which is
Typo: ward -> Ward

2018-06-20 04:56 UTC, FatihAkici commented on papers/serge_rey/serge_rey.rst
> +of interpreting the 100 percent to be tracts "perfectly stuck at" ward neighborhood type 0 if the spatial lag
Typo: ward -> Ward

2018-06-20 04:56 UTC, FatihAkici commented on papers/serge_rey/serge_rey.rst
> +Clusterings for both the raw hamming edit distance and the weighted hamming edit
Typo: hamming -> Hamming

2018-06-20 04:56 UTC, FatihAkici commented on papers/serge_rey/serge_rey.rst
> +particularly in in the areas of central northern LA near the Hollywood Hills, as
Typo: in in

2018-06-20 04:56 UTC, FatihAkici commented on papers/serge_rey/serge_rey.rst
> +will enhance and improve the usefulness of ``OSLNAP`` for reproducible urban science.
"Enhance and improve" sounds redundant.

2018-06-20 09:59 UTC, AngelosPsy commented
#  Spatio-temporal analysis of socioeconomical neighborhoods,

In their manuscript named Spatio-temporal analysis of socioeconomical neighborhoods, Rey, Knaap, Han, Wolf, & Kang present a program for analyses of socioecononomic neighborhoods. Overall, the manuscript is strong, with clear examples on what the module can do. I would like to congratulate the authors for delivering such a solid manuscript. My comments refer mostly to textual changes so that it will enable the text to be a bit easier to follow by individuals outside the particular field (such as myself). I list all my suggestions below. 


# Written quality

- "...however, neighborhoods remain understudied because researchers lack appropriate analytical tools for under- standing their evolution through time and space.": I reckon that somebody could also think of other reasons why neighborhoods are understudied than just the lack of appropriate tools. I would rephrase this to something like "...however, neighborhoods remain understudied. One of the reasons for that is because".

- Some of the included lists could be rewritten so that they enable them to be read more easily. To illustrate, on page 2 the authors write: "Compile and query a spatiotemporal database using either local data or connectionsÉÓ and then lists the types of queries. I think it would be better for the text's comprehension, as well as for saving some space so that the some of the figures could be enlarged (see below), if the lists were included in the main text. This also goes to the list on p. 3.

- (p. 4) "We allows". Is this a typo? 

- (p. 7) Apart from the first paragraph, the conclusion section is mostly a list of future directions. It would be better if this section is rephreased to _future directions_ with a separate conclusion section following it.

# Technical Content

- I find the technical content excellent.

# Novelty and impact

- Excellent work by the authors in terms of what is new with the software and why the particular software is important to the community (e.g., end of abstract, p. 2, third paragraph).


# Verifiability

- No code snippets are included. The paper includes plenty of code references and rough descriptions about what the code can do. Maybe the authors want to check again the verifiability requirements that each paper should meet (https://github.com/scipy-conference/scipy_proceedings/blob/master/review_criteria.md#verifiability). I understand that due to the length of the paper it is hard to include source code but maybe the authors should consider that.

# Figures

- Figures 2, 3, 4, 7, and 8 are quite small, making it difficult to see them.

2018-06-21 11:38 UTC, TomAugspurger reviewed
Like Michael, this is outside my area of expertise and I don't have anything to add. It was an enjoyable read.

2018-06-21 11:38 UTC, TomAugspurger commented on papers/serge_rey/serge_rey.rst
> +and the pydata stack for attribute calculations :cite:`rey2009`. The
pydata -> PyData?

2018-06-29 21:18 UTC, deniederhut commented
Hi @sjsrey ! Do you have some updates on the paper?

2018-06-29 21:19 UTC, sjsrey commented
@deniederhut Yes - planning on this weekend for the updates.

2018-07-02 13:09 UTC, sjsrey commented on papers/serge_rey/serge_rey.rst
> +directly comparable over time. Thus, we focuses only on the
fixed

2018-07-02 13:09 UTC, sjsrey commented on papers/serge_rey/serge_rey.rst
> +Spatio-temporal analysis of socioeconomic neighborhoods
Thank you for this suggestion. We agree that the title and abstract needed to be more explicitly linked to the tool, and we have changed both in this regard.

2018-07-02 13:10 UTC, sjsrey commented on papers/serge_rey/serge_rey.rst
> +spatially explicit approaches to the study of longitudinal neighborhood dynamics
Incorporated.

2018-07-02 13:10 UTC, sjsrey commented on papers/serge_rey/serge_rey.rst
> +   connections to  pubilic data services
Corrected.

2018-07-02 13:10 UTC, sjsrey commented on papers/serge_rey/serge_rey.rst
> +:math:`(14,14)` transition probability matrices for ward and affinity
fixed

2018-07-02 13:10 UTC, sjsrey commented on papers/serge_rey/serge_rey.rst
> +census years. This is especially true for the ward neighborhood type 4 which is
Fixed

2018-07-02 13:10 UTC, sjsrey commented on papers/serge_rey/serge_rey.rst
> +of interpreting the 100 percent to be tracts "perfectly stuck at" ward neighborhood type 0 if the spatial lag
fixed

2018-07-02 13:10 UTC, sjsrey commented on papers/serge_rey/serge_rey.rst
> +Clusterings for both the raw hamming edit distance and the weighted hamming edit
Fixed

2018-07-02 13:11 UTC, sjsrey commented on papers/serge_rey/serge_rey.rst
> +particularly in in the areas of central northern LA near the Hollywood Hills, as
Fixed

2018-07-02 13:11 UTC, sjsrey commented on papers/serge_rey/serge_rey.rst
> +will enhance and improve the usefulness of ``OSLNAP`` for reproducible urban science.
Agreed.

2018-07-02 15:04 UTC, deniederhut commented
Dear @msarahan , @AngelosPsy , and @AngelosPsy do you feel that this paper is now ready for inclusion in the proceedings?

2018-07-02 15:34 UTC, AngelosPsy commented
Dear @deniederhut. Thank you for your message. Will be abroad tomorrow. Will check the revised paper on Wednesday. Is that OK?

2018-07-03 01:15 UTC, deniederhut commented
Sure thing. And sorry, one of those @s was supposed to be for @FatihAkici

2018-07-03 03:54 UTC, FatihAkici commented
@sjsrey Thanks for the revision! The paper is looking much nicer and better-organized. However the "we focuses" typo is still there, and some images are still hard to see (Figures 2, 3, 4, 8). The dates on the Fig. 4 are tiny, and the headers&legends on Fig. 8 are impossible to see. And also, only the figures 2, 3, 5 and 6 are mentioned in the text. Do you mind mentioning the rest and their contexts?

@deniederhut, once the points I just noted are addressed, and @AngelosPsy gives the thumbs-up, we should be good to go!

2018-07-04 12:23 UTC, AngelosPsy commented
Dear @sjsrey, thank you for all the revisions. The paper is much better now. Could you just add a short conclusion paragraph at the end -- it was mentioned in my initial review. If not, please let me know.

2018-07-05 00:05 UTC, sjsrey commented
@AngelosPsy Thank you (and all the reviewers) for your careful reading of our work and very helpful comments. We’ve added the short conclusion paragraph and cut a little elsewhere to remain within the 8 page limit.

2018-07-05 09:43 UTC, AngelosPsy commented
Dear @sjsrey. Thank you for addressing my final comment. For me the paper is good to go now. @FatihAkici  if your comments are addressed sufficiently, we can notify the committee.

2018-07-05 19:20 UTC, FatihAkici commented
Dear @AngelosPsy thanks so much for your review, and thanks again for the paper, dear @sjsrey! @proceedings, the paper is ready to be merged.

2018-07-05 19:20 UTC, FatihAkici approved these changes

2018-07-06 11:32 UTC, deniederhut requested changes
Hi @sjsrey ! It looks like these citations are missing their DOIs. Could I ask you to add them in before we merge this paper?

2018-07-06 13:59 UTC, sjsrey commented
@deniederhut I added the doi for the one dataset that is used in the illustration. If we add doi's for all the citations were are going to go over the 8 page limit. Should we add doi's to every citation, or is it required that the data sources be referenced in this fashion?

2018-07-06 14:03 UTC, deniederhut commented
The legal agreement that lets us issue a DOI for your paper requires that
your paper reference other DOIs where possible.

On Fri, Jul 6, 2018, 08:59 Sergio Rey <notifications@github.com> wrote:

> @deniederhut <https://github.com/deniederhut> I added the doi for the one
> dataset that is used in the illustration. If we add doi's for all the
> citations were are going to go over the 8 page limit. Should we add doi's
> to every citation, or is it required that the data sources be referenced in
> this fashion?
>
> —
> You are receiving this because you were mentioned.
>
> Reply to this email directly, view it on GitHub
> <https://github.com/scipy-conference/scipy_proceedings/pull/405#issuecomment-403042725>,
> or mute the thread
> <https://github.com/notifications/unsubscribe-auth/AGjNrDvT8xBvKwnPbvnvoosTK0tHLMPWks5uD21FgaJpZM4UKzFA>
> .
>

2018-07-06 14:13 UTC, sjsrey commented
@deniederhut I can add them where possible, but this will mean probably 9 pages of text - is that permissible?

2018-07-10 02:44 UTC, deniederhut commented
Thanks for adding the DOIs! We would still prefer that papers stay within the page limit - would it be possible to pull out a paragraph somewhere? Or maybe find a more compact way to represent those lists of neighborhood labels?

2018-07-10 21:01 UTC, deniederhut approved these changes

2018-07-10 21:02 UTC, deniederhut commented
Thanks for working with us on the paper! This looks good to me

2018-07-17 22:47 UTC, merged