Cloudknot: Submit first draft for review
scipy-conference/scipy_proceedings pull request #406
Opened 2018-05-23 17:44 UTC by richford

This is the first draft of "Cloudknot: A Python Library to Run your Existing Code on AWS Batch" for the Scipy 2018 Proceedings.

2018-06-12 07:57 UTC, FatihAkici commented
Dear Adam and Ariel,

I'll be reviewing your paper. I am not an expert in this field, so please take my questions and suggestions as inputs from a curious learner. I'll leave my comments inside the body of the paper, and will present an overall evaluation here.

Thanks,
Fatih

2018-06-12 08:59 UTC, FatihAkici requested changes
Dear Adam and Ariel,

This is a very interesting paper on an interesting Python library, thank you for contributing it to SciPy and the world! I just submitted my in-line comments to your paper. I am not an expert in this field, so please take my questions and suggestions as inputs from a curious learner. There were a few typos here and there. Other than that, my two main questions are:

1. Which Python versions are supported?
2. Corect me if I am wrong, but as far as I gather, the main advantage of Cloudknot is not necessarily performance, but easiness to use with a comparable performance to existing methods. Providing some simple examples on how one would have to do the examples presented in the API section with Pywren could better enable the reader to realize the easiness of Cloudknot.

These are my comments for now. I will add more, if any, as I go one more round.

Thanks,
Fatih Akici

2018-06-12 08:59 UTC, FatihAkici commented on papers/adam_richie-halford/adam_richie-halford.rst
> +
"such as Pywren" and which other libraries? cottoncandy? Also, how does it compare to running UDFs using SQL syntax as explained here: https://aws.amazon.com/blogs/aws/user-defined-functions-for-amazon-redshift/

2018-06-12 08:59 UTC, FatihAkici commented on papers/adam_richie-halford/adam_richie-halford.rst
> +       is difficult to cite.
Typo: ubiququitous -> ubiquitous

2018-06-12 08:59 UTC, FatihAkici commented on papers/adam_richie-halford/adam_richie-halford.rst
> +   Cloudknot takes to create the SP. The right columns depicts
Typo: right columns depicts -> right column depicts.
Also, since this is the place they are used for the first time in the body of the paper, isn't it a better idea to explicitly write single program and multiple data instead of SP and MD?

2018-06-12 08:59 UTC, FatihAkici commented on papers/adam_richie-halford/adam_richie-halford.rst
> +the Conclusion.
I think a pretty standard "The next section discusses ... , the API section describes ... , and finally Conclusion presents ..." kind of an organizational layout would make the paper easier to read.

2018-06-12 08:59 UTC, FatihAkici commented on papers/adam_richie-halford/adam_richie-halford.rst
> +.. code-block:: python
Major question: What Python versions are supported?

2018-06-12 08:59 UTC, FatihAkici commented on papers/adam_richie-halford/adam_richie-halford.rst
> +However, when similations are too large or complicated to fit well into
Typo: similations -> simulations

2018-06-12 08:59 UTC, FatihAkici commented on papers/adam_richie-halford/adam_richie-halford.rst
> +Two important caveats to this analysis: the first is that the analysis
Please rephrase to a more formal language: There are two important caveats to this analysis...

2018-06-12 08:59 UTC, FatihAkici commented on papers/adam_richie-halford/adam_richie-halford.rst
> +compute power. For example, in experiments that evaluate the mobility of
Typo:  compute power ->  computing power

2018-06-12 08:59 UTC, FatihAkici commented on papers/adam_richie-halford/adam_richie-halford.rst
> +that shows that Cloudknot performs comparably to other distributed
Typo: analyses is plural, use "show" instead of "shows".

2018-06-12 13:00 UTC, richford commented on papers/adam_richie-halford/adam_richie-halford.rst
> +       is difficult to cite.
Thanks. Fixed in [16e37e5](https://github.com/scipy-conference/scipy_proceedings/pull/406/commits/16e37e5f9c1b41c8507072efd685cf241199afa0).

2018-06-12 13:00 UTC, richford commented on papers/adam_richie-halford/adam_richie-halford.rst
> +   Cloudknot takes to create the SP. The right columns depicts
Thanks. Fixed in [16e37e5](https://github.com/scipy-conference/scipy_proceedings/pull/406/commits/16e37e5f9c1b41c8507072efd685cf241199afa0).

2018-06-12 13:00 UTC, richford commented on papers/adam_richie-halford/adam_richie-halford.rst
> +However, when similations are too large or complicated to fit well into
Thanks. Fixed in [16e37e5](https://github.com/scipy-conference/scipy_proceedings/pull/406/commits/16e37e5f9c1b41c8507072efd685cf241199afa0).

2018-06-12 13:00 UTC, richford commented on papers/adam_richie-halford/adam_richie-halford.rst
> +compute power. For example, in experiments that evaluate the mobility of
Thanks. Fixed in [16e37e5](https://github.com/scipy-conference/scipy_proceedings/pull/406/commits/16e37e5f9c1b41c8507072efd685cf241199afa0).

2018-06-12 13:01 UTC, richford commented on papers/adam_richie-halford/adam_richie-halford.rst
> +that shows that Cloudknot performs comparably to other distributed
Thanks. Fixed in [16e37e5](https://github.com/scipy-conference/scipy_proceedings/pull/406/commits/16e37e5f9c1b41c8507072efd685cf241199afa0).

2018-06-12 13:01 UTC, richford commented on papers/adam_richie-halford/adam_richie-halford.rst
> +Two important caveats to this analysis: the first is that the analysis
Thanks. Fixed in [16e37e5](https://github.com/scipy-conference/scipy_proceedings/pull/406/commits/16e37e5f9c1b41c8507072efd685cf241199afa0).

2018-06-12 14:54 UTC, richford commented on papers/adam_richie-halford/adam_richie-halford.rst
> +.. code-block:: python
Thanks. Cloudknot supports Python 2.7 and 3.5+. I added a line about this in [800a1df](https://github.com/scipy-conference/scipy_proceedings/pull/406/commits/800a1dfb9767a788b3d865341ab624e74edb55fd)

2018-06-12 14:55 UTC, richford commented on papers/adam_richie-halford/adam_richie-halford.rst
> +the Conclusion.
Thanks. I changed this line accordingly in [800a1df](https://github.com/scipy-conference/scipy_proceedings/pull/406/commits/800a1dfb9767a788b3d865341ab624e74edb55fd).

2018-06-14 19:29 UTC, richford commented on papers/adam_richie-halford/adam_richie-halford.rst
> +
The comparison to cottoncandy is apt. Cloudknot, pywren, and cottoncandy all allow the user to interact with amazon services without leaving the python environment (and without using boto3). However, cottoncandy does not allow the user to execute UDFs so rather than adding a line to abstract, I have added a sentence to the second paragraph of the introduction talking about cottoncandy (see [commit dcdc2c6](https://github.com/scipy-conference/scipy_proceedings/pull/406/commits/dcdc2c65861290c59a00d9c6b5a5188184534e07)).

Launching UDFs on Amazon Redshift looks interesting. In contrast to cloudknot, the Redshift approach only returns scalars, requires the user to leave their python environment, doesn't import arbitrary dependencies, and still requires a longer $t_env$ to get all your data into Redshift, learn SQL, etc.

2018-06-14 19:32 UTC, richford commented
@FatihAkici Thanks for your feedback. I responded inline to each of your comments (you may have to click on the `Show outdated` button to see my responses). I believe I've responded to all of your comments. If you have any further questions or comments, please don't hesitate to reach out.

2018-06-15 02:01 UTC, dalippa requested changes
Overall, I have some concerns about some of the claims made in the paper, particularly about parity. The data and charts are presented in a misleading way and should be changed.

The overall value of this package is not that it achieves near-parity, but that it lowers the barrier for entry into cloud computing with an easily comprehensible abstraction.

2018-06-15 02:01 UTC, dalippa commented on papers/adam_richie-halford/adam_richie-halford.rst
> +
I agree with half of each of your claims. Lambdas are essentially distributed functions with time limits, so Pywren is a good comparison. I don't think Cottoncandy is a good comparison though (it's an AWS abstraction but not a computational one)

2018-06-15 02:01 UTC, dalippa commented on papers/adam_richie-halford/adam_richie-halford.rst
> +this service (currently maximum 300 seconds of execution time, 1.5 GB of
Move the limitations of Lambda to a footnote to improve readability.

2018-06-15 02:01 UTC, dalippa commented on papers/adam_richie-halford/adam_richie-halford.rst
> +(such as the amount of memory required for a single job) and the number
Avoid using parentheses and instead use apositives with commas. If it interrupts the sentence too much, consider a footnote.

2018-06-15 02:01 UTC, dalippa commented on papers/adam_richie-halford/adam_richie-halford.rst
> +straight-forward abstractions: a *job*, which is an atomic task to
This sentence is way too long. Consider a bulleted list or breaking up the single sentence, which is the entire paragraph.

2018-06-15 02:01 UTC, dalippa commented on papers/adam_richie-halford/adam_richie-halford.rst
> +While Batch provides useful abstractions for batch computing, the user
You use the word batch twice in the same sentence. Consider: "While Batch provides useful functional abstractions for processing data in bulk..."

2018-06-15 02:01 UTC, dalippa commented on papers/adam_richie-halford/adam_richie-halford.rst
> +requires learning many of the terms that control its execution and does
This is true of all APIs. In the case of AWS, there are a lot of common terms. Using a custom library here would be a *disadvantage* since you'd be using your own terms.

2018-06-15 02:01 UTC, dalippa commented on papers/adam_richie-halford/adam_richie-halford.rst
> +to offer a user-friendly single point of access to these resources.
This is core to your paper; how do you prove this claim?

2018-06-15 02:01 UTC, dalippa commented on papers/adam_richie-halford/adam_richie-halford.rst
> +We propose that software designed to aid computational and data
Not all abstractions achieve this goal. Another goal, possibly more important, is that scientists shouldn't have to know much about *cloud computing* in general, and this abstraction increases *accessibility* to the scientific community.

2018-06-15 02:01 UTC, dalippa commented on papers/adam_richie-halford/adam_richie-halford.rst
> +       our original insight but rather an adage so ubiquitous that it
I think you can probably cite Agile methodologies for improving cycle times and iterating toward the end result. This is a good comparison between data science research and programming, where it's well understood.

2018-06-15 02:01 UTC, dalippa commented on papers/adam_richie-halford/adam_richie-halford.rst
> +   t_\mathrm{result} = t_\mathrm{understand} + t_\textrm{compute},
The formuale don't really add much to the paper and makes it appear pretensious; you don't compare it with traditional bare metal hardware. It's also hard to quantify the savings, but you can use other comparisons (e.g. with coding - which is a part of data science) and citations to make the point. You can then use the graphs on page 4 that show the execution time to reduce cycle times when iterating on data science research.

2018-06-15 02:01 UTC, dalippa commented on papers/adam_richie-halford/adam_richie-halford.rst
> +   rounded squares represent components of Cloudknot's user-facing
Nice explanation of the workflow diagram

2018-06-15 02:01 UTC, dalippa commented on papers/adam_richie-halford/adam_richie-halford.rst
> +Cloudknot's use of Docker allows it to handle non-trivial software and
Why does Docker allow handling non-trivial software? What backs up that claim?

2018-06-15 02:01 UTC, dalippa commented on papers/adam_richie-halford/adam_richie-halford.rst
> +- AWS Identity and Access Management (IAM) Roles
Consider moving some of the information in the AWS bullet points and definitions to an appendix or footnotes.

2018-06-15 02:01 UTC, dalippa commented on papers/adam_richie-halford/adam_richie-halford.rst
> +:code:`Knot` uses sensible defaults for the job definition and compute
How can Knot use sensible data points for all types and sizes of data? Is this computed dynamically or hard-coded? If the latter, the defaults will *not* be intelligent in certain cases.

2018-06-15 02:01 UTC, dalippa commented on papers/adam_richie-halford/adam_richie-halford.rst
> +Finally, :code:`Knot` exposes AWS resource tags to the user so that
One of the most complex aspects of AWS is its permissions model. Can you go into how you simplified that as well?

2018-06-15 02:01 UTC, dalippa commented on papers/adam_richie-halford/adam_richie-halford.rst
> +it to the user. Since AWS Batch, and therefore Cloudknot, allows
Remove either "AWS Batch" or "and therefore Cloudknot"; both are not necessary.

2018-06-15 02:01 UTC, dalippa commented on papers/adam_richie-halford/adam_richie-halford.rst
> +:code:`concurrent.futures.ThreadPoolExecutor` instance where each
Abstracting parallel computing defaults is another area where using intelligent defaults adds value for scientists. Why don't you raise that in the earlier sections?

2018-06-15 02:01 UTC, dalippa commented on papers/adam_richie-halford/adam_richie-halford.rst
> +run on AWS Batch. Cloudknot uses the `pipreqs` :cite:`pipreqs` package
The calculation of pi seems to be too trivial and is "filler" for the paper. Why not dive into the real, practical example sooner? Do you have sample datasets and the algorithms so someone can reproduce it in an IPython notebook?

2018-06-15 02:01 UTC, dalippa commented on papers/adam_richie-halford/adam_richie-halford.rst
> +AWS resources that were created in a previous session, this setup time
What you might want to describe in the prior section, instead of calculation of pi, is how to iterate on data results. Start with implementing a UDF that can operate locally, and then branch off to use AWS when the dataset size warrants it.

2018-06-15 02:01 UTC, dalippa commented on papers/adam_richie-halford/adam_richie-halford.rst
> +which vary by instance type but never exceeded 200 instances. The user
You may want to condense this paragraph some and use a footnote to cover the specifications, which are less important than the analysis between the methods.

2018-06-15 02:01 UTC, dalippa commented on papers/adam_richie-halford/adam_richie-halford.rst
> +:math:`\mathcal{O}(1)` scaling for much of the argument range, revealing
Do you mean `O(1)` for Pywren? It's hard to do better than that, and the graphs don't appear to show `O(1)` execution time as the number of inputs grows. It looks more like O(n) to me, but with a low constant; also, the axes in the graphs are skewed so it's a bit misleading. One instance of this: the "number of arguments" graph visually appears to be a linear increase but the x-axis is exponentially growing. Based on the graph, when I look at the times for 64 args (32), 256 args (~64), and 1024 args (256) - it appears that what you really have is `O(n)` with a constant of 0.25. This pattern seems to continue for all values after 256 arguments.

2018-06-15 02:01 UTC, dalippa commented on papers/adam_richie-halford/adam_richie-halford.rst
> +   MRI analysis pipeline with data requirements. A comparison of
This appears to show Cloudknot is substantially slower, especially since this is on a logarithmic graph. If you plotted this linearly, it would appear that Cloudknot does not perform well for small data sets, something that should be called out explicitly. It would be interesting, however, to know where the inflection point is (when it would be better to use something like Dask vs Cloudknot.

2018-06-15 02:01 UTC, dalippa commented on papers/adam_richie-halford/adam_richie-halford.rst
> +Conclusion
What about testing UDFs prior to the slower iterations for uploading to the cloud and such?

2018-06-15 02:01 UTC, dalippa commented on papers/adam_richie-halford/adam_richie-halford.rst
> +that show that Cloudknot performs comparably to other distributed
10-25% difference cited earlier is not comparable. Dask, Myria, and Spark are all comparable with one another.

2018-06-15 02:01 UTC, dalippa commented on papers/adam_richie-halford/adam_richie-halford.rst
> +does not introduce undue overhead burden and exploits the scaling
Cloudknot increases accessibility and development speed, but at the cost of up to 25% performance decrease when executing. "undue overhead burden" needs to be clarified.

2018-06-15 02:01 UTC, dalippa commented on papers/adam_richie-halford/adam_richie-halford.rst
> +including the time for users to learn a new system is a human computer
The HCI comment is not really relevant.

2018-06-15 02:01 UTC, dalippa commented on papers/adam_richie-halford/adam_richie-halford.rst
> +limitations to solve at this time. But we believe an extra 30-50% in
30-50% execution time is *not* trivial. You may believe it is, but this belief shouldn't be cited in the paper. If it takes a week to learn a new system, then as long as the number of iterations * the amount of time per iteration exceeds a week, the other method is better.

2018-06-15 02:01 UTC, dalippa commented on papers/adam_richie-halford/adam_richie-halford.rst
> +Cloudknot's simplified API and ability to achieve rough parity with
The parity claim does not hold given the data cited.

2018-06-15 02:01 UTC, dalippa commented on papers/adam_richie-halford/adam_richie-halford.rst
> +Acknowledgements
Please consider adding a Future Work section.

2018-06-16 15:07 UTC, FatihAkici approved these changes

2018-06-20 19:06 UTC, richford commented on papers/adam_richie-halford/adam_richie-halford.rst
> +
Completely agree. Cottoncandy is only comparable in that it allows users to interact with S3 without leaving their python session or relying on boto3.

2018-06-20 19:07 UTC, richford commented on papers/adam_richie-halford/adam_richie-halford.rst
> +this service (currently maximum 300 seconds of execution time, 1.5 GB of
Thanks. Moved to footnote in [845e7c1](https://github.com/scipy-conference/scipy_proceedings/pull/406/commits/845e7c19c01de906ea79aa74a8dc76d9d36b8c90).

2018-06-20 19:07 UTC, richford commented on papers/adam_richie-halford/adam_richie-halford.rst
> +(such as the amount of memory required for a single job) and the number
Thanks. Fixed this in [845e7c1](https://github.com/scipy-conference/scipy_proceedings/pull/406/commits/845e7c19c01de906ea79aa74a8dc76d9d36b8c90).

2018-06-20 19:08 UTC, richford commented on papers/adam_richie-halford/adam_richie-halford.rst
> +straight-forward abstractions: a *job*, which is an atomic task to
Thanks. Changed to bulleted list in [845e7c1](https://github.com/scipy-conference/scipy_proceedings/pull/406/commits/845e7c19c01de906ea79aa74a8dc76d9d36b8c90).

2018-06-20 19:08 UTC, richford commented on papers/adam_richie-halford/adam_richie-halford.rst
> +While Batch provides useful abstractions for batch computing, the user
Thanks. Fixed this in [845e7c1](https://github.com/scipy-conference/scipy_proceedings/pull/406/commits/845e7c19c01de906ea79aa74a8dc76d9d36b8c90).

2018-06-20 19:10 UTC, richford commented on papers/adam_richie-halford/adam_richie-halford.rst
> +requires learning many of the terms that control its execution and does
I’m not quite convinced that AWS uses a lot of common terms. When learning about AWS, many users find the different services and terminology frustrating. Rather than introducing its own new set of terms, Cloudknot attempts to mimic Pythons concurrent futures’ `Executor` objects. The `Knot` is the one new object that user’s will have to learn. And its `map` method should be familiar to many Python users. We have added a sentence to the discussion: "Rather than introducing its own set of terms and abstractions, Cloudknot attempts to mimic Pythons concurrent futures’ `Executor` objects. Users of Cloudknot have to familiarize themselves with one new object: the `Knot`, while some of its functionality will initially be new to users of Cloudknot (e.g., the way that resources on AWS are managed), its `map` method should be familiar to most Python users."

New sentence added in [640bef3](https://github.com/scipy-conference/scipy_proceedings/pull/406/commits/640bef3639ed59fe166aa403f7a56fce36815156).

2018-06-20 19:11 UTC, richford commented on papers/adam_richie-halford/adam_richie-halford.rst
> +to offer a user-friendly single point of access to these resources.
We wrote Cloudknot specifically because something like it didn't exist already, and we wanted something like it. We are not aware of anything that we should've used instead.

2018-06-20 19:24 UTC, richford commented on papers/adam_richie-halford/adam_richie-halford.rst
> +We propose that software designed to aid computational and data
We agree with this! We changed the last paragraph of the introduction to reflect this in [89fe2f8](https://github.com/scipy-conference/scipy_proceedings/pull/406/commits/89fe2f86bd25cd4bd1acfd247605aad0130b0fe0).

2018-06-20 19:25 UTC, richford commented on papers/adam_richie-halford/adam_richie-halford.rst
> +       our original insight but rather an adage so ubiquitous that it
Interesting comparison. I’m not as well versed in the agile development literature. What’s a good reference for that comparison? In either case, I worry that the extra comparison, and perhaps the footnote as well is a distraction from the broader point. Perhaps we should just remove the footnote entirely.

2018-06-20 19:26 UTC, richford commented on papers/adam_richie-halford/adam_richie-halford.rst
> +Cloudknot's use of Docker allows it to handle non-trivial software and
We have added the following sentence to this section: “This is because Docker provides a consistent and isolated environment. This allows complete control over the software dependencies of a particular application, and near-immediate deployment of these dependencies“. We have also added a citation to a paper that explains this in more detail (https://arxiv.org/pdf/1410.0846.pdf)

2018-06-20 19:27 UTC, richford commented on papers/adam_richie-halford/adam_richie-halford.rst
> +:code:`Knot` uses sensible defaults for the job definition and compute
That’s a good point! We have changed the text to say "`Knot` uses job definition and compute environment defaults conservative enough to run most simple jobs, with the goal of minimizing errors due to insufficient resources. The casual user may never need to concern themselves with selecting an instance type or specifying an AMI. Users who want to minimize costs by specifying the minimum sufficient resources or users who need additional resources for intensive jobs can control..."

2018-06-20 19:28 UTC, richford commented on papers/adam_richie-halford/adam_richie-halford.rst
> +Finally, :code:`Knot` exposes AWS resource tags to the user so that
That’s a good point. We just assume that the user has the same permissions that would be needed to run using AWS Batch in the console.

We have added the following sentence in the Methods: "One of the most complex aspects of AWS is its permissions model. Here, we assume that the user has the permissions needed to run AWS Batch in the console"

2018-06-20 19:28 UTC, richford commented on papers/adam_richie-halford/adam_richie-halford.rst
> +it to the user. Since AWS Batch, and therefore Cloudknot, allows
Thanks. Fixed this in [845e7c1](https://github.com/scipy-conference/scipy_proceedings/pull/406/commits/845e7c19c01de906ea79aa74a8dc76d9d36b8c90).

2018-06-20 19:30 UTC, richford commented on papers/adam_richie-halford/adam_richie-halford.rst
> +run on AWS Batch. Cloudknot uses the `pipreqs` :cite:`pipreqs` package
We admit that the calculation of pi is a trivial one, but we think that a trivial example is potentially useful for readers of the paper, as a way to introduce the API. The paper includes several other examples with more complex computations, but at this early point in the paper we’d like to avoid distracting the reader from the API with details of a more complex use-case. 

All of the examples that we use in the paper, in additional to other more pedagogical examples, are available on the Cloudknot github repository. We’ve added a sentence to indicate that in [640bef3](https://github.com/scipy-conference/scipy_proceedings/pull/406/commits/640bef3639ed59fe166aa403f7a56fce36815156)

2018-06-20 19:31 UTC, richford commented on papers/adam_richie-halford/adam_richie-halford.rst
> +AWS resources that were created in a previous session, this setup time
Please see [response to a previous comment](https://github.com/scipy-conference/scipy_proceedings/pull/406#discussion_r196915050) about the calculation of pi.

2018-06-20 19:32 UTC, richford commented on papers/adam_richie-halford/adam_richie-halford.rst
> +which vary by instance type but never exceeded 200 instances. The user
Thanks for the suggestion. I moved details to a footnote in [640bef3](https://github.com/scipy-conference/scipy_proceedings/pull/406/commits/640bef3639ed59fe166aa403f7a56fce36815156)

2018-06-20 19:35 UTC, richford commented on papers/adam_richie-halford/adam_richie-halford.rst
> +:math:`\mathcal{O}(1)` scaling for much of the argument range, revealing
Yes, the O(1) scaling is for Pywren. We wrote that in the paper but we take the fact that you thought we were talking about Cloudknot in that sentence to mean that we need more clarification in the discussion of the figure. We have rewritten that paragraph in [640bef3](https://github.com/scipy-conference/scipy_proceedings/pull/406/commits/640bef3639ed59fe166aa403f7a56fce36815156) to read:

>First, we hold the grid size constant at 10 x 10 and parallelize over different temperature constraints on one edge of the simulation grid. We investigate the scaling of job execution time as a function of the size of the argument array. In Figure 2 we show the execution time as a function of nargs, the length of the argument array (with a log2 scale on the x-axis and a log10 scale on the y-axis). We testing scaling using Cloudknot’s default parameters and also using custom parameters [footnote 3]. Regardless of the Knot parameters, Pywren outperformed Cloudknot at all argument array sizes. Indeed, Pywren appears to achieve O(1) scaling between 4 ≤ nargs ≤ 512, revealing AWS Lambda’s capabilities for massively parallel computation. For nargs > 512, Pywren appears to conform to O(n) scaling with a constant of roughly 0.25. By contract, Cloudknot exhibits noisy O(n) scaling for nargs > 32, with a constant that is comparable to Pywren’s scaling constant for nargs > 512. Precise determination of these scaling constants would require more data for a larger range of argument sizes."

We have also changed the figure to use log-10 on the y-axis so that the reader can see the familiar logarithmic minor tick marks on the y-axis. This violates Tufte’s data-ink principle but the added familiarity is likely worth it. The x-axis label has a parenthetical mention of the log-2 scale. And the text has been changed from previous line reminding the reader that the axis were both log-2 to a new one reminding the reader that the y-axis is log-10 and the x-axis is log-2.

2018-06-20 19:38 UTC, richford commented on papers/adam_richie-halford/adam_richie-halford.rst
> +   MRI analysis pipeline with data requirements. A comparison of
Agreed. Cloudknot is substantially slower than the Dask, Spark, and Myria implementations for small problem sizes. We mention this explicitly in the caption to Figure 4 and in the text (see line number 546-547 in the rst file using commit [89fe2f8](https://github.com/scipy-conference/scipy_proceedings/pull/406/commits/89fe2f86bd25cd4bd1acfd247605aad0130b0fe0)). We were also excited about the possibility of a cross-over point, below which it would be better to use Dask and above which it would be better to use Cloudknot. If we extrapolate from Figure 4, it looks like the cross-over point might be somewhere before 32 subjects, but we aren’t willing to predict the existence or location of a cross-over point in the paper given the limitations in our scaling data.

2018-06-20 19:39 UTC, richford commented on papers/adam_richie-halford/adam_richie-halford.rst
> +Conclusion
We're not sure that we completely understand this comment. Are you talking about optionally testing UDFs locally before creating Batch resources on AWS? This can certainly be done and we do so regularly in our own work. Should we explain that the UDF can be run locally before it is uploaded to Batch?

2018-06-20 19:43 UTC, richford commented on papers/adam_richie-halford/adam_richie-halford.rst
> +including the time for users to learn a new system is a human computer
We took out this comment and changed the line to "Precisely measuring :math:`t_\mathrm{env}` is beyond the scope of this paper so the reduction in :math:`t_\mathrm{compute}` is admittedly speculative."

2018-06-20 19:44 UTC, richford commented on papers/adam_richie-halford/adam_richie-halford.rst
> +limitations to solve at this time. But we believe an extra 30-50% in
We completely agree that this is not trivial. However, as we wrote in the text, for some use-cases it *may be acceptable*. Whether it is acceptable or not depends in large part exactly on the conditions that you mention. We have added a sentence that clarifies this "But we believe an extra 30-50% in execution time may be acceptable in some situations. For example, if the amount of time that a user will spend learning a new queueing system or batch processing language exceeds the time savings due to reduced execution time, then it will be advantageous to accept Cloudknot's suboptimal execution time in order to use its simplified API."

2018-06-20 19:45 UTC, richford commented on papers/adam_richie-halford/adam_richie-halford.rst
> +does not introduce undue overhead burden and exploits the scaling
We have rephrased the last sentence of that paragraph so that it transitions into the next paragraph where we discuss the trade-off between execution time and development time.

2018-06-20 19:46 UTC, richford commented on papers/adam_richie-halford/adam_richie-halford.rst
> +that show that Cloudknot performs comparably to other distributed
We have changed this sentence to read "And we've included scaling analyses that show Cloudknot's performance compared to other distributed computing frameworks."

2018-06-20 19:48 UTC, richford commented on papers/adam_richie-halford/adam_richie-halford.rst
> +Cloudknot's simplified API and ability to achieve rough parity with
This comment and some of your other comments have highlighted some assumptions we made about the different definitions of the word "comparable" and the word "parity." I think we were using an astronomer's kind of definition of "comparable" where if something is within an order of magnitude, it's comparable. This was appropriate for most of our use cases. But you are correct that it might not be applicable for other researchers. So we thank you for pointing out an unstated assumption.

To eliminate this confusion, we have removed the word "parity" from the paper and included more discussion about the trade-offs involved between execution time and the simplified API. For this sentence in particular, we changed it to read "Cloudknot's simple API and its conditionally acceptable execution time compared to other distributed computing frameworks make it a viable tool for researchers who want distributed execution of their computational workflow, from within their Python environment, without the steep learning curve of learning a new platform."

2018-06-20 20:07 UTC, richford commented on papers/adam_richie-halford/adam_richie-halford.rst
> +Acknowledgements
Future work section added in [9bc31b1](https://github.com/scipy-conference/scipy_proceedings/pull/406/commits/9bc31b15655508d62f614bef9341f3192608b12f).

2018-06-20 20:14 UTC, richford commented
Thanks @dalippa for your thorough review. I've responded to individual comments inline. You may have to click on the "Show outdated" button to see them. Overall, we think your concerns about the claims of parity stem from our differing working definitions of parity and comparability. So we thank you for pointing out an unstated assumption about those terms that might not generalize to all readers. We've gone through the paper and made the comparisons to other distributed computing platforms more explicit. We've also written a bit more about the trade-offs between execution time and using a simplified API. Lastly, we modified the chart axis and included more discussion of the figure that you felt was misleading.

We think the concerns that you raised and our resulting edits have made it a stronger paper so thanks for your review!

2018-06-22 10:26 UTC, richford commented on papers/adam_richie-halford/adam_richie-halford.rst
> +:code:`concurrent.futures.ThreadPoolExecutor` instance where each
We're not sure that we completely understand this comment. We're happy to add a discussion about this in the paper but want to make sure we understand what you mean. Could you expound on this comment a bit? We understand that a cloudknot user doesn't have to learn about thread pools but they wouldn't have to do so in the AWS console either.

2018-06-25 21:42 UTC, richford commented
Hi @dalippa, have you had a chance to review our edits in response to your comments? Thanks for your review.

2018-06-25 23:50 UTC, dalippa commented
I'm going to re-review this evening @richford

2018-06-26 00:33 UTC, dalippa requested changes
@richford The paper is greatly improved but still needs more polish. I have more comments and questions given the changes you have made.

I still have to review from the conclusion onward. I will get to that later tonight.

2018-06-26 00:33 UTC, dalippa commented on papers/adam_richie-halford/adam_richie-halford.rst
> +platforms have the advantage of scalability: users can access limitless
linear scalability is probably more accurate.

2018-06-26 00:33 UTC, dalippa commented on papers/adam_richie-halford/adam_richie-halford.rst
> +could in principle offer substantial speedups. But because of the
"could, in principle,"

2018-06-26 00:33 UTC, dalippa commented on papers/adam_richie-halford/adam_richie-halford.rst
> +complexity and steep learning curve associated with a transition to
It's far less steep than it used to be. Dask used to be very difficult to run in parallel (as had other python-based platforms). It's *more* accessible than it used to be. I think you need to differentiate between researchers with and without the cloud computing knowledge. Computer Science researchers have used cloud/distributed computing for over 15 years now. I think the issue is that data has grown so much that distributed computing is *necessary* in fields that didn't need it years ago.

2018-06-26 00:33 UTC, dalippa commented on papers/adam_richie-halford/adam_richie-halford.rst
> +,such as the amount of memory required for a single job, and the number
",such" => ", such"

2018-06-26 00:33 UTC, dalippa commented on papers/adam_richie-halford/adam_richie-halford.rst
> +bid percentage to use with AWS Spot Instances.
You might want to explain bid percentage here or in a footnote.

2018-06-26 00:33 UTC, dalippa commented on papers/adam_richie-halford/adam_richie-halford.rst
> +- a *job*, which is an atomic task to repeat on multiple inputs,
an atomic, independent task. Independent is very important. It won't help if you need all of the data at once (e.g. normal computation formula for standard deviation).

2018-06-26 00:33 UTC, dalippa commented on papers/adam_richie-halford/adam_richie-halford.rst
> +- a *job queue*, which serves as a scheduler for the jobs,
A queue isn't a scheduler. It is a set of tasks in the order in which they are executed. The scheduler is what puts the items on the queue.

2018-06-26 00:33 UTC, dalippa commented on papers/adam_richie-halford/adam_richie-halford.rst
> +- a *compute environment*, which defines the details of the
rather than "details", consider "configuration", which more accurately represents what this is

2018-06-26 00:33 UTC, dalippa commented on papers/adam_richie-halford/adam_richie-halford.rst
> +its execution and does not facilitate scripting and/or reproducibility.
Do you have anything that backs up the claim that the "AWS web console still resists automation, requires..."? Perhaps cite the documentation for batch or the AWS console?

2018-06-26 00:33 UTC, dalippa commented on papers/adam_richie-halford/adam_richie-halford.rst
> +designed to offer a user-friendly single point of access to these
It's very user friendly for a software engineer, but is not *accessible* to all. Consider focusing on accessibility rather than "user-friendly".

2018-06-26 00:33 UTC, dalippa commented on papers/adam_richie-halford/adam_richie-halford.rst
> +Here, we introduce a new Python library: Cloudknot
Consider "we introduce a new Python library with support for Python 2.7 and 3.5+: ...." and removing "Cloudknot supports..." below which interrupts the flow of the narrative.

2018-06-26 00:33 UTC, dalippa commented on papers/adam_richie-halford/adam_richie-halford.rst
> +the :code:`Knot`, while some of its functionality will initially be new
This sentence is a bit of a run-on. Consider breaking it up as "the Knot. While some of its functionality will ..."

2018-06-26 00:33 UTC, dalippa commented on papers/adam_richie-halford/adam_richie-halford.rst
> +We propose that software designed to aid computational and data
This needs to be cited sooner. Cloud computing is not currently accessible to computational and data scientists. This is core to your argument, and should possibly be included in the introduction.

2018-06-26 00:33 UTC, dalippa commented on papers/adam_richie-halford/adam_richie-halford.rst
> +       our original insight but rather an adage so ubiquitous that it
Try this free PDF resource: http://agilehandbook.com/agile-handbook.pdf

You can remove the footnote, if you think that would improve clarity.

2018-06-26 00:33 UTC, dalippa commented on papers/adam_richie-halford/adam_richie-halford.rst
> +   t_\mathrm{result} = t_\mathrm{understand} + t_\textrm{compute},
@richford Please address this comment.

2018-06-26 00:33 UTC, dalippa commented on papers/adam_richie-halford/adam_richie-halford.rst
> +Methods
I think design might fit better here than Methods

2018-06-26 00:33 UTC, dalippa commented on papers/adam_richie-halford/adam_richie-halford.rst
> +- AWS Identity and Access Management (IAM) Roles
@richford Please address this comment.

2018-06-26 00:33 UTC, dalippa commented on papers/adam_richie-halford/adam_richie-halford.rst
> +conservative enough to run most simple jobs, with the goal of minimizing
Most data science applications don't need conservative defaults, but accurate ones. They don't have the luxury of trying to optimize the settings. They need intelligent defaults based on various parameters of the data. Consider adding such parameter auto-detection to future work to simplify things even more.

2018-06-26 00:33 UTC, dalippa commented on papers/adam_richie-halford/adam_richie-halford.rst
> +Finally, :code:`Knot` exposes AWS resource tags to the user so that
Not everyone knows what AWS resource tags are. Consider a footnote or sentence with an explanation.

2018-06-26 00:33 UTC, dalippa commented on papers/adam_richie-halford/adam_richie-halford.rst
> +To operate on the MD, the :code:`Knot.map()` method serializes each
What splits up the data to be executed on multiple hosts?

2018-06-26 00:33 UTC, dalippa commented on papers/adam_richie-halford/adam_richie-halford.rst
> +   from local machine to S3 and back. I don't think we need to mention
Actually, the speed of transfer within a data center as opposed to across data centers is important from a speed perspective. Then, you can cite that it is optimal from a cost and performance standpoint.

2018-06-26 00:33 UTC, dalippa commented on papers/adam_richie-halford/adam_richie-halford.rst
> +Finally, :code:`Knot.map()` downloads the output from S3 and returns it
What if the dataset is too large for any given machine? The purpose of cloud computing isn't just reproducibility but being able to handle more data than any one machine can.

2018-06-26 00:33 UTC, dalippa commented on papers/adam_richie-halford/adam_richie-halford.rst
> +inside the UDF itself.
I would clarify that it is "inside the module of the UDF" and not inside the *function*. UDF = User Defined Function, which makes this statement more ambiguous.

2018-06-26 00:33 UTC, dalippa commented on papers/adam_richie-halford/adam_richie-halford.rst
> +We can then query the result status using :code:`future.done()`
What is the largest dataset that you've tried to analyze with Cloudknot? That would probably be useful information earlier in the paper, particularly if it is several orders of magnitude bigger than what can be processed on a single machine.

2018-06-26 00:33 UTC, dalippa commented on papers/adam_richie-halford/adam_richie-halford.rst
> +In this section, we will present a few use-cases of Cloudknot, including
"a few real use cases of Cloudknot."

2018-06-26 00:33 UTC, dalippa commented on papers/adam_richie-halford/adam_richie-halford.rst
> +the complexity by adding first data dependencies and subsequently
Please add the data sizes for each case. Your final example, if it's to be considered equal in power to Dask and Spark, should be quite large.

2018-06-26 00:33 UTC, dalippa commented on papers/adam_richie-halford/adam_richie-halford.rst
> +conform to :math:`\mathcal{O}(n)` scaling with a constant of roughly
Big-Oh notation seems a bit unnecessary in this section. Consider using "constant" and "linear" instead of O(1) and O(n).

2018-06-26 00:33 UTC, dalippa commented on papers/adam_richie-halford/adam_richie-halford.rst
> +   with more available vCPUs. Note the :math:`log_2` scale for the
Rather than saying "note the log2 scale" please consider making the graphic less confusing. Including that sentence here disrupts the flow of the paragraph.

2018-06-26 00:33 UTC, dalippa commented on papers/adam_richie-halford/adam_richie-halford.rst
> +   that the additional overhead associated with building the Docker
Consider adding to future work pre-computing the docker environments, or ways to get parity with Pywren.

2018-06-26 00:33 UTC, dalippa commented on papers/adam_richie-halford/adam_richie-halford.rst
> +AWS Lambda's execution time and memory limitations and does not have
You should probably also mention Lambda's limitation of 5 minutes of execution time and cite that as an advantage over AWS Batch.

2018-06-26 00:33 UTC, dalippa commented on papers/adam_richie-halford/adam_richie-halford.rst
> +However, when simulations are too large or complicated to fit well into
Why is Cloudknot good for stateful functions (as opposed to Pywren's stateless function framework)?

2018-06-26 00:33 UTC, dalippa commented on papers/adam_richie-halford/adam_richie-halford.rst
> +improve alongside the Lambda increases. It is likely that there will
This is an unlikely claim since Lambda and Batch have different purposes. They won't move in lock-step or linearly. Please consider taking the sentence "It is likely that.." out.

2018-06-26 00:33 UTC, dalippa commented on papers/adam_richie-halford/adam_richie-halford.rst
> +individual tasks on data can be addressed by preloading the data into
Specify data size? MB? GB? TB?

2018-06-26 00:33 UTC, dalippa commented on papers/adam_richie-halford/adam_richie-halford.rst
> +this type of data proceeds in an embarassingly parallel manner: even for
remove "embarassingly".

2018-06-26 00:33 UTC, dalippa commented on papers/adam_richie-halford/adam_richie-halford.rst
> +conducted first at the level of each individual brain, and aggregation
This paragraph is comprised of 2 sentences. Please consider breaking this up to improve comprehension.

2018-06-26 00:33 UTC, dalippa commented on papers/adam_richie-halford/adam_richie-halford.rst
> +individual level. For example: selection of regions of interest within
"For example" is not a complete sentence; it's a clause. "For example, ..."

2018-06-26 00:33 UTC, dalippa commented on papers/adam_richie-halford/adam_richie-halford.rst
> +work: Spark :cite:`Zaharia2010-rp`, Myria :cite:`Halperin2014-vu` and
Why not Hadoop? Hadoop is still used and probably has *more* overhead than Cloudknot does.

2018-06-26 00:33 UTC, dalippa commented on papers/adam_richie-halford/adam_richie-halford.rst
> +Cython in Dipy :cite:`Garyfallidis2014`. In contrast to the other
"... implemented in Python and Cython in Dipy." This sentence is a bit awkward.

2018-06-26 00:33 UTC, dalippa commented on papers/adam_richie-halford/adam_richie-halford.rst
> +into the individual instances. Parallelization was implemented only at
What if the data is too large for a single host? If it isn't what is the benefit of this over standard parallel processing with threads?

2018-06-26 00:33 UTC, dalippa commented on papers/adam_richie-halford/adam_richie-halford.rst
> +25 subjects (the largest number we used), Cloudknot is less than 10% slower
consider removing the parentheses which interrupt the flow of the sentence. Consider: "With the largest number of subjects used, Cloudknot processed 25 subjects 10% slower than Spark and Myria; however, it was 25% slower than Dask, the fastest of the tools we previously benchmarked"

2018-06-26 00:33 UTC, dalippa commented on papers/adam_richie-halford/adam_richie-halford.rst
> +added to the cluster (see :cite:`mehta2017comparative` for details).
No need to "see ... for details", just use the citation.

2018-06-26 00:33 UTC, dalippa commented on papers/adam_richie-halford/adam_richie-halford.rst
> +Notably, even for the largest amount of data that was benchmarked (25
The size of the data files is very important given the number of machines, CPUs, and RAM.

2018-06-26 00:33 UTC, dalippa commented on papers/adam_richie-halford/adam_richie-halford.rst
> +image data, often stored in multiple large files.
How large? "Big data" is usually measured in TB, PB, and ZB. Small data is usually GB or smaller.

2018-06-26 00:33 UTC, dalippa commented on papers/adam_richie-halford/adam_richie-halford.rst
> +ImageJ and Trackmate are both written in Java, and can be scripted using
"are written in Java and can be scripted..."

2018-06-26 00:33 UTC, dalippa commented on papers/adam_richie-halford/adam_richie-halford.rst
> +Conclusion
Unit testing has been used in software engineering for decades. Testing the UDF on a small dataset locally is important to iterate on results quickly. When the full dataset needs to be analyzed, they should then use the cluster.

2018-06-26 02:32 UTC, dalippa requested changes

2018-06-26 02:32 UTC, dalippa commented on papers/adam_richie-halford/adam_richie-halford.rst
> +scale all from within their Python environment.
"... at scale from within ..."

2018-06-26 02:32 UTC, dalippa commented on papers/adam_richie-halford/adam_richie-halford.rst
> +We have demonstrated Cloudknot's ability to handle complicated data and
Complex - but you need to also prove too large (e.g. "big" data) to process on a single machine.

2018-06-26 02:32 UTC, dalippa commented on papers/adam_richie-halford/adam_richie-halford.rst
> +microscopy. And we've included scaling analyses that show Cloudknot's
I would not mention the scaling analyses except: "Cloudknot's niche is the data scientist for whom development speed is more important than computational speed".

2018-06-26 02:32 UTC, dalippa commented on papers/adam_richie-halford/adam_richie-halford.rst
> +extra 30-50% in execution time may be acceptable in some situations. For
You claim a 30-50% speed difference here, but 10-25% earlier. That seems inconsistent to me.

2018-06-26 02:32 UTC, dalippa commented on papers/adam_richie-halford/adam_richie-halford.rst
> +API. Beginning Cloudknot users simply add an extra import statement,
Have you tested the learning curve of Cloudknot over that of the others?

2018-06-26 02:32 UTC, dalippa commented on papers/adam_richie-halford/adam_richie-halford.rst
> +Cloudknot's simple API and its conditionally acceptable execution
Consider: "Cloudknot trades runtime performance for development performance and is best used when development speed matters most."

2018-06-26 02:32 UTC, dalippa commented on papers/adam_richie-halford/adam_richie-halford.rst
> +viable tool for researchers who want distributed execution of their
This may have business applications as well. Data scientists conducting exploratory research would benefit from short development time.

2018-06-26 02:32 UTC, dalippa commented on papers/adam_richie-halford/adam_richie-halford.rst
> +Currently, Cloudknot does not support computational pipelines that
This is one of Dask's strengths.

2018-06-26 02:32 UTC, dalippa commented on papers/adam_richie-halford/adam_richie-halford.rst
> +a simple way to connect to EC2 instances to allow in-situ monitoring
What about Cloudwatch?

2018-06-26 18:26 UTC, richford commented on papers/adam_richie-halford/adam_richie-halford.rst
> +platforms have the advantage of scalability: users can access limitless
Fixed in [3b261ff](https://github.com/scipy-conference/scipy_proceedings/pull/406/commits/3b261ffcdcac4a917e042ad044ad6a7f8800de07).

2018-06-26 18:26 UTC, richford commented on papers/adam_richie-halford/adam_richie-halford.rst
> +could in principle offer substantial speedups. But because of the
Fixed in [3b261ff](https://github.com/scipy-conference/scipy_proceedings/pull/406/commits/3b261ffcdcac4a917e042ad044ad6a7f8800de07).

2018-06-26 18:34 UTC, richford commented on papers/adam_richie-halford/adam_richie-halford.rst
> +complexity and steep learning curve associated with a transition to
Fixed in [3b261ff](https://github.com/scipy-conference/scipy_proceedings/pull/406/commits/3b261ffcdcac4a917e042ad044ad6a7f8800de07).

We agree that users who are already well versed in cloud computing will not face the same impediments. We broke up the first paragraph into two paragraphs. The first one addresses the potential benefits and the second one now addresses the learning curve, with some context about improvements in Dask. As an aside, although researchers with lots of cloud computing experience won't face the same learning curve, we want to resist the impression that Cloudknot will be useful only to the tyro.

2018-06-26 18:34 UTC, richford commented on papers/adam_richie-halford/adam_richie-halford.rst
> +,such as the amount of memory required for a single job, and the number
Fixed in [3b261ff](https://github.com/scipy-conference/scipy_proceedings/pull/406/commits/3b261ffcdcac4a917e042ad044ad6a7f8800de07).

2018-06-26 18:34 UTC, richford commented on papers/adam_richie-halford/adam_richie-halford.rst
> +bid percentage to use with AWS Spot Instances.
Fixed in [3b261ff](https://github.com/scipy-conference/scipy_proceedings/pull/406/commits/3b261ffcdcac4a917e042ad044ad6a7f8800de07).

2018-06-26 18:37 UTC, richford commented on papers/adam_richie-halford/adam_richie-halford.rst
> +- a *job queue*, which serves as a scheduler for the jobs,
Fixed in [3b261ff](https://github.com/scipy-conference/scipy_proceedings/pull/406/commits/3b261ffcdcac4a917e042ad044ad6a7f8800de07).

2018-06-26 18:37 UTC, richford commented on papers/adam_richie-halford/adam_richie-halford.rst
> +- a *compute environment*, which defines the details of the
Fixed in [3b261ff](https://github.com/scipy-conference/scipy_proceedings/pull/406/commits/3b261ffcdcac4a917e042ad044ad6a7f8800de07).

2018-06-26 18:37 UTC, richford commented on papers/adam_richie-halford/adam_richie-halford.rst
> +designed to offer a user-friendly single point of access to these
Fixed in [3b261ff](https://github.com/scipy-conference/scipy_proceedings/pull/406/commits/3b261ffcdcac4a917e042ad044ad6a7f8800de07).

2018-06-26 18:37 UTC, richford commented on papers/adam_richie-halford/adam_richie-halford.rst
> +Here, we introduce a new Python library: Cloudknot
Fixed in [3b261ff](https://github.com/scipy-conference/scipy_proceedings/pull/406/commits/3b261ffcdcac4a917e042ad044ad6a7f8800de07).

2018-06-26 18:37 UTC, richford commented on papers/adam_richie-halford/adam_richie-halford.rst
> +the :code:`Knot`, while some of its functionality will initially be new
Fixed in [3b261ff](https://github.com/scipy-conference/scipy_proceedings/pull/406/commits/3b261ffcdcac4a917e042ad044ad6a7f8800de07).

2018-06-26 18:38 UTC, richford commented on papers/adam_richie-halford/adam_richie-halford.rst
> +Methods
Fixed in [3b261ff](https://github.com/scipy-conference/scipy_proceedings/pull/406/commits/3b261ffcdcac4a917e042ad044ad6a7f8800de07).

2018-06-26 18:40 UTC, richford commented on papers/adam_richie-halford/adam_richie-halford.rst
> +       our original insight but rather an adage so ubiquitous that it
Footnote removed in [3b261ff](https://github.com/scipy-conference/scipy_proceedings/pull/406/commits/3b261ffcdcac4a917e042ad044ad6a7f8800de07).

2018-06-26 18:42 UTC, richford commented on papers/adam_richie-halford/adam_richie-halford.rst
> +inside the UDF itself.
Fixed in [3b261ff](https://github.com/scipy-conference/scipy_proceedings/pull/406/commits/3b261ffcdcac4a917e042ad044ad6a7f8800de07). We wrote "...imported in the source code of the UDF itself" in order to avoid any confusion if the user has a Python module containing several candidate UDFs.

2018-06-26 18:42 UTC, richford commented on papers/adam_richie-halford/adam_richie-halford.rst
> +In this section, we will present a few use-cases of Cloudknot, including
Fixed in [3b261ff](https://github.com/scipy-conference/scipy_proceedings/pull/406/commits/3b261ffcdcac4a917e042ad044ad6a7f8800de07).

2018-06-26 18:42 UTC, richford commented on papers/adam_richie-halford/adam_richie-halford.rst
> +conform to :math:`\mathcal{O}(n)` scaling with a constant of roughly
Fixed in [3b261ff](https://github.com/scipy-conference/scipy_proceedings/pull/406/commits/3b261ffcdcac4a917e042ad044ad6a7f8800de07).

2018-06-26 18:43 UTC, richford commented on papers/adam_richie-halford/adam_richie-halford.rst
> +this type of data proceeds in an embarassingly parallel manner: even for
Fixed in [3b261ff](https://github.com/scipy-conference/scipy_proceedings/pull/406/commits/3b261ffcdcac4a917e042ad044ad6a7f8800de07).

2018-06-26 18:43 UTC, richford commented on papers/adam_richie-halford/adam_richie-halford.rst
> +conducted first at the level of each individual brain, and aggregation
Fixed in [3b261ff](https://github.com/scipy-conference/scipy_proceedings/pull/406/commits/3b261ffcdcac4a917e042ad044ad6a7f8800de07).

2018-06-26 18:43 UTC, richford commented on papers/adam_richie-halford/adam_richie-halford.rst
> +individual level. For example: selection of regions of interest within
Fixed in [3b261ff](https://github.com/scipy-conference/scipy_proceedings/pull/406/commits/3b261ffcdcac4a917e042ad044ad6a7f8800de07).

2018-06-26 18:44 UTC, richford commented on papers/adam_richie-halford/adam_richie-halford.rst
> +Cython in Dipy :cite:`Garyfallidis2014`. In contrast to the other
Fixed in [3b261ff](https://github.com/scipy-conference/scipy_proceedings/pull/406/commits/3b261ffcdcac4a917e042ad044ad6a7f8800de07).

2018-06-26 18:44 UTC, richford commented on papers/adam_richie-halford/adam_richie-halford.rst
> +25 subjects (the largest number we used), Cloudknot is less than 10% slower
Fixed in [3b261ff](https://github.com/scipy-conference/scipy_proceedings/pull/406/commits/3b261ffcdcac4a917e042ad044ad6a7f8800de07).

2018-06-26 18:44 UTC, richford commented on papers/adam_richie-halford/adam_richie-halford.rst
> +added to the cluster (see :cite:`mehta2017comparative` for details).
Fixed in [3b261ff](https://github.com/scipy-conference/scipy_proceedings/pull/406/commits/3b261ffcdcac4a917e042ad044ad6a7f8800de07).

2018-06-26 18:45 UTC, richford commented on papers/adam_richie-halford/adam_richie-halford.rst
> +ImageJ and Trackmate are both written in Java, and can be scripted using
Fixed in [3b261ff](https://github.com/scipy-conference/scipy_proceedings/pull/406/commits/3b261ffcdcac4a917e042ad044ad6a7f8800de07).

2018-06-26 18:45 UTC, richford commented on papers/adam_richie-halford/adam_richie-halford.rst
> +scale all from within their Python environment.
Fixed in [3b261ff](https://github.com/scipy-conference/scipy_proceedings/pull/406/commits/3b261ffcdcac4a917e042ad044ad6a7f8800de07).

2018-06-26 18:48 UTC, richford commented on papers/adam_richie-halford/adam_richie-halford.rst
> +extra 30-50% in execution time may be acceptable in some situations. For
Fixed in [3b261ff](https://github.com/scipy-conference/scipy_proceedings/pull/406/commits/3b261ffcdcac4a917e042ad044ad6a7f8800de07).

We chose the 30-50% number to include the differences we saw in both the heat equation example and the dMRI example. But we fixed this by simply removing the percentage numbers entirely since the percentage doesn't really matter so long as it satisfies the conditions described in the rest of the paragraph.

2018-06-26 18:51 UTC, richford commented on papers/adam_richie-halford/adam_richie-halford.rst
> +API. Beginning Cloudknot users simply add an extra import statement,
We haven't. We state that measuring t_env precisely is beyond the scope of the paper (previous version stated that it's an HCI problem beyond the scope of the paper). We could add an HCI study of Cloudknot and other systems to the Future Work section.

2018-06-26 19:00 UTC, richford commented on papers/adam_richie-halford/adam_richie-halford.rst
> +Cloudknot's simple API and its conditionally acceptable execution
Fixed in [00e32fa](https://github.com/scipy-conference/scipy_proceedings/pull/406/commits/00e32fad63864f51ec1cf026436b0b1d5dfa4678).

2018-06-26 19:00 UTC, richford commented on papers/adam_richie-halford/adam_richie-halford.rst
> +viable tool for researchers who want distributed execution of their
Suggestion adopted in [00e32fa](https://github.com/scipy-conference/scipy_proceedings/pull/406/commits/00e32fad63864f51ec1cf026436b0b1d5dfa4678).

2018-06-26 19:00 UTC, richford commented on papers/adam_richie-halford/adam_richie-halford.rst
> +Currently, Cloudknot does not support computational pipelines that
Fixed in [00e32fa](https://github.com/scipy-conference/scipy_proceedings/pull/406/commits/00e32fad63864f51ec1cf026436b0b1d5dfa4678).

2018-06-26 19:01 UTC, richford commented on papers/adam_richie-halford/adam_richie-halford.rst
> +a simple way to connect to EC2 instances to allow in-situ monitoring
Cloudwatch does provide the ability to view standard out, after the process is done, but does not provide access to monitoring during the process.

2018-06-26 20:22 UTC, richford commented on papers/adam_richie-halford/adam_richie-halford.rst
> +- a *job*, which is an atomic task to repeat on multiple inputs,
Fixed in [2eba37d](https://github.com/scipy-conference/scipy_proceedings/pull/406/commits/2eba37dbeab2f527c1159f9eb0ef2e8eb04a9010).

2018-06-26 20:25 UTC, richford commented on papers/adam_richie-halford/adam_richie-halford.rst
> +its execution and does not facilitate scripting and/or reproducibility.
Fixed in [2eba37d](https://github.com/scipy-conference/scipy_proceedings/pull/406/commits/2eba37dbeab2f527c1159f9eb0ef2e8eb04a9010).

We referenced the AWS Batch documentation. For all of the examples in the documentation, the user is instructed to use the console and needs to familiarize themselves with the AWS Batch vocabulary.

2018-06-26 20:26 UTC, richford commented on papers/adam_richie-halford/adam_richie-halford.rst
> +Finally, :code:`Knot` exposes AWS resource tags to the user so that
Fixed in [2eba37d](https://github.com/scipy-conference/scipy_proceedings/pull/406/commits/2eba37dbeab2f527c1159f9eb0ef2e8eb04a9010).

2018-06-26 21:38 UTC, richford commented on papers/adam_richie-halford/adam_richie-halford.rst
> +- AWS Identity and Access Management (IAM) Roles
Moved to a footnote in c240de0

2018-06-26 21:39 UTC, richford commented on papers/adam_richie-halford/adam_richie-halford.rst
> +conservative enough to run most simple jobs, with the goal of minimizing
Added to Future Work section in c240de0.

2018-06-26 21:44 UTC, richford commented on papers/adam_richie-halford/adam_richie-halford.rst
> +Conclusion
It is possible that we have not emphasized this enough, but the design of the software facilitates exactly this: you write a function, test it locally, and then when you are ready to scale it up, you pass it to a Knot object, and run map over the inputs.

We'll look for a good place to add some comments about unit testing and how it fits into the development process with Cloudknot.

2018-06-26 22:01 UTC, richford commented on papers/adam_richie-halford/adam_richie-halford.rst
> +Notably, even for the largest amount of data that was benchmarked (25
Added a sentence about data size in b59772c.

2018-06-26 23:33 UTC, dalippa commented on papers/adam_richie-halford/adam_richie-halford.rst
> +API. Beginning Cloudknot users simply add an extra import statement,
👍 to adding this to Future Work

2018-06-26 23:39 UTC, dalippa reviewed
@richford I noticed there are a number of comments that aren't addressed or replied to yet. If you're not going to change something I raised, please add why as a reply in the comments.

2018-06-26 23:39 UTC, dalippa commented
@richford Please tag me when you're ready for a re-review.

2018-06-27 00:13 UTC, richford commented
@dalippa, will do. We're still working on the responses but I'll tag you when we're done and ready for another review round.

2018-06-27 03:14 UTC, richford commented on papers/adam_richie-halford/adam_richie-halford.rst
> +   from local machine to S3 and back. I don't think we need to mention
Added a paragraph about this in e509cd3. It reads

>If the instances and S3 bucket are in the same region, then users do not
pay for transfer from S3 to the EC2 instances and back. They pay only
for transfer out of the data center (i.e. from their local machine to
S3 and back). Transfer speed within the data center also outperforms
transfer speed between data centers. So it is both less costly and more
performant to colocate the Cloudknot S3 bucket with the EC2 instances.
Cloudknot includes utility functions to change regions and S3 buckets
for this purpose.

2018-06-27 03:19 UTC, richford commented on papers/adam_richie-halford/adam_richie-halford.rst
> +To operate on the MD, the :code:`Knot.map()` method serializes each
Under the hood, it's just a for loop. We have a one-to-one mapping between the elements along the outer most dimension of the input array and the launched Batch jobs. We added a sentence about this in e509cd3 and 53d7692.

2018-06-27 03:21 UTC, richford commented on papers/adam_richie-halford/adam_richie-halford.rst
> +API. Beginning Cloudknot users simply add an extra import statement,
Added to future work in e509cd3.

2018-06-27 13:34 UTC, richford commented on papers/adam_richie-halford/adam_richie-halford.rst
> +   with more available vCPUs. Note the :math:`log_2` scale for the
Fixed in d97ce64. The base of the log is now consistent for both the x and y-axes. And log_2 is used explicitly in the axes labels. To drive this point home, we changed the numbers in the paragraphs to exponents of 2 when discussing the number of arguments (e.g. 2^9 instead of 512). We also re-estimated the speculative scaling constants for Cloudknot.

2018-06-27 13:44 UTC, richford commented on papers/adam_richie-halford/adam_richie-halford.rst
> +AWS Lambda's execution time and memory limitations and does not have
Fixed in 586e76c. Instead of mentioning the execution time and memory limitations and requiring the reader to refer back to the first footnote on page 1, we now state the 5 minute execution time and the 1.5 GB memory limitations explicitly, reiterating the footnote from page 1.

2018-06-27 16:13 UTC, richford commented on papers/adam_richie-halford/adam_richie-halford.rst
> +However, when simulations are too large or complicated to fit well into
We think the use of the "stateless function" phrase was distracting here since it took away from the main point of this section and paragraph. So in 586e76c we simply removed the reference to Pywren's stateless function framework. It now reads "...Pywren's framework..."

It also drew an unintended distinction since Cloudknot can handle both stateless and stateful functions (assuming the user has done due diligence to avoid race conditions and all that). With sufficiently complicated S3 hackery, Pywren could probably support stateful functions as well, but Cloudknot's use of AWS Batch lets the user save state in AMI's, attached storage, or on S3.

The previous paragraph addresses your question but also shows the extent to which the "stateless function" phrase was distracting, thereby justifying our decision to remove it.

2018-06-27 17:23 UTC, richford commented on papers/adam_richie-halford/adam_richie-halford.rst
> +We propose that software designed to aid computational and data
We agree that Cloudknot makes cloud computing more accessible. But this line is already in the introduction and we don't see how to discuss the the simplified API any sooner. We have however added a line to the abstract in 461aa78 so that readers know what's coming:

>Cloudknot minimizes the cognitive load of learning a new API by introducing only one new object and using the familiar `map` method.

2018-06-27 22:59 UTC, arokem commented on papers/adam_richie-halford/adam_richie-halford.rst
> +individual tasks on data can be addressed by preloading the data into
We've analyzed TB-scale data. See https://github.com/richford/scipy_proceedings/commit/3fd8e141221f759d4b35edef8efef0baa615e07c

2018-06-27 22:59 UTC, arokem commented on papers/adam_richie-halford/adam_richie-halford.rst
> +We can then query the result status using :code:`future.done()`
This is addressed in https://github.com/richford/scipy_proceedings/commit/3fd8e141221f759d4b35edef8efef0baa615e07c

2018-06-27 23:00 UTC, arokem commented on papers/adam_richie-halford/adam_richie-halford.rst
> +the complexity by adding first data dependencies and subsequently
Addressed in https://github.com/richford/scipy_proceedings/commit/3fd8e141221f759d4b35edef8efef0baa615e07c

2018-06-27 23:05 UTC, arokem commented on papers/adam_richie-halford/adam_richie-halford.rst
> +work: Spark :cite:`Zaharia2010-rp`, Myria :cite:`Halperin2014-vu` and
Our previous benchmark paper did not include Hadoop, so we don’t include it here either.

2018-06-27 23:07 UTC, arokem commented on papers/adam_richie-halford/adam_richie-halford.rst
> +image data, often stored in multiple large files.
This is addressed in https://github.com/scipy-conference/scipy_proceedings/pull/406/commits/3fd8e141221f759d4b35edef8efef0baa615e07c

2018-06-27 23:14 UTC, arokem commented on papers/adam_richie-halford/adam_richie-halford.rst
> +   t_\mathrm{result} = t_\mathrm{understand} + t_\textrm{compute},
We didn't think it was pretentious, but maybe a bit quirky. We opted to remove this section (and references to these equations in the Conclusions) altogether in https://github.com/richford/scipy_proceedings/pull/18.

2018-06-27 23:21 UTC, arokem commented on papers/adam_richie-halford/adam_richie-halford.rst
> +microscopy. And we've included scaling analyses that show Cloudknot's
Surely the conclusion should refer back to the results? I am not sure if this comment is specifically the word "scaling" that triggered this comment, so I removed it in https://github.com/scipy-conference/scipy_proceedings/pull/406/commits/bf3d1cbf480b29fc85bbb5723678e175ae84294a. But I think that it would be good for us to refer back to the results in the conclusion.

2018-06-27 23:23 UTC, arokem commented on papers/adam_richie-halford/adam_richie-halford.rst
> +image data, often stored in multiple large files.
We've also added a statement about this in the Introduction, in https://github.com/scipy-conference/scipy_proceedings/pull/406/commits/a8fcbcb7b9397a4433d3a5a64d7634d3252f0de0

2018-06-27 23:41 UTC, richford commented on papers/adam_richie-halford/adam_richie-halford.rst
> +Finally, :code:`Knot.map()` downloads the output from S3 and returns it
For input data, if the dataset is too large to fit on the local machine, then the user can write a UDF that accepts a pointer to the remote data. We do this, for example, with the neuroimaging example; the UDF accepts an S3 address containing the input data to operate on. In this way, the local machine does not need to have a complete copy of all of the input. Since we mentioned this in the dMRI example, we didn’t make any additions to the text about input data.

For output data, This process can be done in reverse. The UDF could write its data to S3 or some other remote storage and then return the address at which to retrieve the result. We have added the following sentence:

>If the results are too large to fit on the local machine, the user may augment their UDF to write results to S3 or some other remote storage and then simply return the address at which to retrieve the result.

2018-06-27 23:42 UTC, richford commented on papers/adam_richie-halford/adam_richie-halford.rst
> +   that the additional overhead associated with building the Docker
After restructuring the future work section, we have added the following sentence to the final paragraph:

>In addition to these capability enhancements, Cloudknot could benefit from performance enhancements designed to address the performance gap with other distributed computing platforms. This might involve prebuilding certain Docker containers or intelligently selecting an AWS region to minimize cost or queueing time.

2018-06-27 23:43 UTC, richford commented on papers/adam_richie-halford/adam_richie-halford.rst
> +improve alongside the Lambda increases. It is likely that there will
We think this claim is fairly uncontroversial. Perhaps our use of the word “alongside” connotes a stricter relationship between improvements in Lambda and Batch. So we’ve removed the word "alongside" and rewritten the sentence so that we are no longer claiming that this regime will always exist and instead state the conditional: if it does exist, Cloudknot will be useful.

>We agree and note only that EC2 and AWS Batch limitations are likely to improve as well. So long as there exists a computational regime between the two sets of limitations, Cloudknot can offer researchers a simple platform with which to execute their scientific workloads.

2018-06-27 23:44 UTC, richford commented on papers/adam_richie-halford/adam_richie-halford.rst
> +into the individual instances. Parallelization was implemented only at
In this case, each EC2 instance only downloads the portion of the input data that it needs to operate on, rather than all of the input data required by all of the jobs. We rewrote this sentence to make it more explicit:

>In contrast to the other systems, essentially no changes had to be made to the reference implementation when using Cloudknot, except to download the part of the data required for an individual job from S3 into the individual instances.

2018-06-27 23:47 UTC, richford commented on papers/adam_richie-halford/adam_richie-halford.rst
> +We have demonstrated Cloudknot's ability to handle complicated data and
We've addressed the data sizes of the examples and what to do if data is too large for the local machine in response to other comments above.

2018-06-27 23:49 UTC, richford commented
@dalippa, we're finished with the responses and ready for review.

2018-06-28 02:30 UTC, dalippa requested changes
Some grammatical mistakes, some recommended corrections. The language is still a bit overly flowery, and I've made some recommendations where that can be reduced.

I think after these changes are completed, the paper will be ready for acceptance.

2018-06-28 02:30 UTC, dalippa commented on papers/adam_richie-halford/adam_richie-halford.rst
> +:cite:`helm`. Yet despite these improvements, the cloud remains
computation in the cloud?

2018-06-28 02:30 UTC, dalippa commented on papers/adam_richie-halford/adam_richie-halford.rst
> +set of terms and abstractions, Cloudknot attempts to mimic Pythons
Python's. But this group of possessive nouns is a bit harder to follow. Consider "Cloudknot provides a simple abstraction on top of Executor objects whose results are returned by concurrent futures."

2018-06-28 02:30 UTC, dalippa commented on papers/adam_richie-halford/adam_richie-halford.rst
> +to be loaded on each compute resource. Or they may simply request a
"Or, they may..."

2018-06-28 02:30 UTC, dalippa commented on papers/adam_richie-halford/adam_richie-halford.rst
> +One of the most complex aspects of AWS is its permissions model. Here,
I would mention that you won't cover the details of the permissions model but provide a link as a footnote. This will aid in reproducibility.

2018-06-28 02:30 UTC, dalippa commented on papers/adam_richie-halford/adam_richie-halford.rst
> +assign each element to a separate AWS Batch job. It serializes each
"It" is ambiguous here and could refer to Knot.map() or the separate AWS job.

2018-06-28 02:30 UTC, dalippa commented on papers/adam_richie-halford/adam_richie-halford.rst
> +internally consistent with the expectations of the CLI. It then launches
ibid

2018-06-28 02:30 UTC, dalippa commented on papers/adam_richie-halford/adam_richie-halford.rst
> +run on AWS Batch. Cloudknot uses the `pipreqs` :cite:`pipreqs` package
OK. I am satisfied with that.

2018-06-28 02:30 UTC, dalippa commented on papers/adam_richie-halford/adam_richie-halford.rst
> +if the UDF signature were :code:`def udf(arg0, arg1)`, one could execute
I would refrain from using arg0 and arg1 as parameter names. If you can, provide meaningful names.

2018-06-28 02:30 UTC, dalippa commented on papers/adam_richie-halford/adam_richie-halford.rst
> +including real life uses of the software in data analysis. We will
The two clauses "a few real use cases of Cloudknot" and "including real life uses of the software in data analysis" are redundant. Please pick one, or combine them.

2018-06-28 02:30 UTC, dalippa commented on papers/adam_richie-halford/adam_richie-halford.rst
> +In this unrealistic example, we wish to parallelize execution both over a range
Good callout that this is unrealistic, but is used for the sake of making your point.

2018-06-28 02:30 UTC, dalippa commented on papers/adam_richie-halford/adam_richie-halford.rst
> +limit of 300s. So Pywren was unable to compute on the larger grid sizes.
This is a great point. For some data size *n*, Pywren will fall over and Cloudknot will not.

2018-06-28 02:30 UTC, dalippa commented on papers/adam_richie-halford/adam_richie-halford.rst
> +As an example, we implemented a pipeline for analysis of human MRI
Size of MRI data?

2018-06-28 02:30 UTC, dalippa commented on papers/adam_richie-halford/adam_richie-halford.rst
> +the largest number of subjects used, Cloudknot processed 25 subjectss
misspelling: subjects

2018-06-28 02:30 UTC, dalippa commented on papers/adam_richie-halford/adam_richie-halford.rst
> +the fastest of the tools that we previously benchmarked.
remove "previously"

2018-06-28 02:30 UTC, dalippa commented on papers/adam_richie-halford/adam_richie-halford.rst
> +with 8 vCPUs). The benchmark code does run faster with more nodes added
does run faster => executes faster

2018-06-28 02:30 UTC, dalippa commented on papers/adam_richie-halford/adam_richie-halford.rst
> +data that was benchmarked was for 25 subjects, corresponding to 105 GB
I take it 105 GB was for all 25 subjects, so each dataset per person was 4-5 GB?

2018-06-28 02:30 UTC, dalippa commented on papers/adam_richie-halford/adam_richie-halford.rst
> +Conclusion
That sounds good to me.

2018-06-28 02:30 UTC, dalippa commented on papers/adam_richie-halford/adam_richie-halford.rst
> +We have demonstrated Cloudknot's ability to handle complicated data and
"to handle complicated data..." => "to execute complex algorithms over vast quantities of data using real-world examples from neuroimaging and microscopy."

2018-06-28 02:30 UTC, dalippa commented on papers/adam_richie-halford/adam_richie-halford.rst
> +microscopy. And we've included analyses that show Cloudknot's performance
"And we've included analyses..." - I would remove this sentence and add a clause to the prior statement: "... neuroimaging and microscopy with a fraction of the human effort needed to set up a computational cloud". After all, setup time is the main value proposition of Cloudknot

2018-06-28 02:30 UTC, dalippa commented on papers/adam_richie-halford/adam_richie-halford.rst
> +Cloudknot in comparison to other distributed computing platforms.
"in comparison to" => "compared to"

2018-06-28 02:30 UTC, dalippa commented on papers/adam_richie-halford/adam_richie-halford.rst
> +spent on systems administration, setup and particularly on rewriting
remove "particularly on". "on" is already implied from the earlier list

2018-06-28 02:30 UTC, dalippa commented on papers/adam_richie-halford/adam_richie-halford.rst
> +of existing code. For example, if the amount of time that a user will
"For example..." can be removed. It's already implied earlier in the paper that the if time spent learning is vastly greater than time executing analyses, Cloudknot fits that use case perfectly. Maybe rewrite this sentence?

2018-06-28 02:30 UTC, dalippa commented on papers/adam_richie-halford/adam_richie-halford.rst
> +call the :code:`map()` method, and wait for results. And because
Not *quite* true. There is probably some AWS configuration that needs to be done, particularly granting AWS Batch access.

2018-06-28 02:30 UTC, dalippa commented on papers/adam_richie-halford/adam_richie-halford.rst
> +Dockerfiles or specify instance types.
"Docker files"?

2018-06-28 02:30 UTC, dalippa commented on papers/adam_richie-halford/adam_richie-halford.rst
> +Cloudknot trades runtime performance for development performance and
Nice way to end the conclusion.

2018-06-28 02:30 UTC, dalippa commented on papers/adam_richie-halford/adam_richie-halford.rst
> +Cloudknot can benefit from several approaches to enhancement:
"benefit from several enhancements:"

2018-06-28 02:30 UTC, dalippa commented on papers/adam_richie-halford/adam_richie-halford.rst
> +other distributed computing platforms. But we did not rigorously
"... than other distributed computing platforms, but we did not ..."

2018-06-29 23:39 UTC, arokem commented on papers/adam_richie-halford/adam_richie-halford.rst
> +Cloudknot trades runtime performance for development performance and
Thanks!

2018-06-30 00:06 UTC, arokem commented
The edits in https://github.com/scipy-conference/scipy_proceedings/pull/406/commits/4de64e744cf27114b92ad2155581ad6fd3c5ebd4 should address the remaining comments.

2018-06-30 04:32 UTC, richford commented
@dalippa, tagging you as requested. @arokem's changes are ready for review.

2018-06-30 18:55 UTC, dalippa requested changes
Some comments were left unchanged or were not at least responded to.


Overall, mostly minor changes. Please do address vertical vs horizontal scaling.

2018-06-30 18:55 UTC, dalippa commented on papers/adam_richie-halford/adam_richie-halford.rst
> +       time, 1.5 GB of RAM, 512 MB of local storage, and no root access.
Why is root access relevant?

2018-06-30 18:55 UTC, dalippa commented on papers/adam_richie-halford/adam_richie-halford.rst
> +  container,
Minor: consider using semicolons to delineate between terms

2018-06-30 18:55 UTC, dalippa commented on papers/adam_richie-halford/adam_richie-halford.rst
> +so that all jobs execute the SP. The user may ask :code:`Knot` to
""The user may restrict its compute..."

2018-06-30 18:55 UTC, dalippa commented on papers/adam_richie-halford/adam_richie-halford.rst
> +objects. If the results are too large to fit on the local machine, the
S3 will help for exceeding disk tolerance. But what about executing an algorithm in parallel?

2018-06-30 18:55 UTC, dalippa commented on papers/adam_richie-halford/adam_richie-halford.rst
> +including real life uses of the software in data analysis. We will
@richford Please address this comment.

2018-06-30 18:55 UTC, dalippa commented on papers/adam_richie-halford/adam_richie-halford.rst
> +   building the Docker image, along with EC2 service limits limited
"limits reduced Cloudknot's throughput"

2018-06-30 18:55 UTC, dalippa commented on papers/adam_richie-halford/adam_richie-halford.rst
> +work: Spark :cite:`Zaharia2010-rp`, Myria :cite:`Halperin2014-vu` and
OK

2018-06-30 18:55 UTC, dalippa commented on papers/adam_richie-halford/adam_richie-halford.rst
> +of the r4.16xlarge type -- each with 64 vCPUs and 488 GB of RAM. In
These systems could fit the entire dataset into memory. What about the case where the datasets cannot fit completely in memory? Also, you talk about scaling. What you're referring to is *vertical* scaling (better machines, more CPUs) rather than horizontal scaling (more machines).

2018-06-30 18:55 UTC, dalippa commented on papers/adam_richie-halford/adam_richie-halford.rst
> +We have demonstrated Cloudknot's ability to handle complicated data and
@richford Please address this comment

2018-07-02 00:44 UTC, arokem commented on papers/adam_richie-halford/adam_richie-halford.rst
> +       time, 1.5 GB of RAM, 512 MB of local storage, and no root access.
Because it might limit the ability of the user to install complex software dependencies.

2018-07-02 00:46 UTC, arokem commented on papers/adam_richie-halford/adam_richie-halford.rst
> +  container,
Addressed in 85ed820e59cfd0c5eb7fe3cbda125c053d5a308e

2018-07-02 00:48 UTC, arokem commented on papers/adam_richie-halford/adam_richie-halford.rst
> +so that all jobs execute the SP. The user may ask :code:`Knot` to
Addressed in 6c18f3299154abb86fb367a45117d742556ef951

2018-07-02 00:48 UTC, arokem commented on papers/adam_richie-halford/adam_richie-halford.rst
> +objects. If the results are too large to fit on the local machine, the
We don't understand this comment. That's exactly what Cloudknot and AWS Batch do: execute the program in parallel.

2018-07-02 00:49 UTC, arokem commented on papers/adam_richie-halford/adam_richie-halford.rst
> +   building the Docker image, along with EC2 service limits limited
We prefer "affected"

Addressed in a1533a1ff529c66826d1e9618b7921a4322be1d5

2018-07-02 01:06 UTC, arokem commented on papers/adam_richie-halford/adam_richie-halford.rst
> +of the r4.16xlarge type -- each with 64 vCPUs and 488 GB of RAM. In
I am not sure that I entirely understand the question. In cases where the entire dataset cannot fit into memory on any machine available on AWS, you would probably need to split it up into parts anyway. And these parts would each probably fit onto some type of AWS machine. For example, for the human MRI dataset, the total amount of data was >100 GB, but it could be parallelized across individuals (each ~4 GB).

Regarding horizontal vs. vertical scaling -- we've now called this out explicitly, addressed in: eae847cdcb274d45855af3407609ac6addda62d0

2018-07-02 01:07 UTC, arokem commented on papers/adam_richie-halford/adam_richie-halford.rst
> +Cloudknot in comparison to other distributed computing platforms.
Addressed in 2b972d96cc685a5df051683204f5ab8cbb7f0346

2018-07-02 01:08 UTC, arokem commented on papers/adam_richie-halford/adam_richie-halford.rst
> +We have demonstrated Cloudknot's ability to handle complicated data and
Addressed in 572604cfdab69fcc965bb2cfd5ea023290ad9275

2018-07-02 01:10 UTC, arokem commented on papers/adam_richie-halford/adam_richie-halford.rst
> +microscopy. And we've included analyses that show Cloudknot's performance
The sentence that we currently have there is a statement of fact: the paper include analyses that demonstrate the (usually inferior) performance of Cloudknot. On the other hand, the sentence you propose is speculative, given that we haven't measured the effort involved. I'd rather leave this as is.

2018-07-02 01:12 UTC, arokem commented on papers/adam_richie-halford/adam_richie-halford.rst
> +data that was benchmarked was for 25 subjects, corresponding to 105 GB
Yes. That's right. 

This is also included in a table in Figure 8 of the Mehta et al. VLDB paper.

2018-07-02 01:14 UTC, arokem commented on papers/adam_richie-halford/adam_richie-halford.rst
> +including real life uses of the software in data analysis. We will
Addressed in 743dacb7bb754afd883bb69f7847ffa8cd5c52dd

2018-07-02 01:15 UTC, arokem commented on papers/adam_richie-halford/adam_richie-halford.rst
> +so that all jobs execute the SP. The user may ask :code:`Knot` to
https://github.com/scipy-conference/scipy_proceedings/pull/406/commits/6c18f3299154abb86fb367a45117d742556ef951

2018-07-02 01:16 UTC, arokem commented on papers/adam_richie-halford/adam_richie-halford.rst
> +  container,
https://github.com/scipy-conference/scipy_proceedings/pull/406/commits/85ed820e59cfd0c5eb7fe3cbda125c053d5a308e

2018-07-02 01:16 UTC, arokem commented on papers/adam_richie-halford/adam_richie-halford.rst
> +   building the Docker image, along with EC2 service limits limited
https://github.com/scipy-conference/scipy_proceedings/pull/406/commits/a1533a1ff529c66826d1e9618b7921a4322be1d5

2018-07-02 01:16 UTC, arokem commented on papers/adam_richie-halford/adam_richie-halford.rst
> +of the r4.16xlarge type -- each with 64 vCPUs and 488 GB of RAM. In
https://github.com/scipy-conference/scipy_proceedings/pull/406/commits/eae847cdcb274d45855af3407609ac6addda62d0

2018-07-02 01:17 UTC, arokem commented on papers/adam_richie-halford/adam_richie-halford.rst
> +Cloudknot in comparison to other distributed computing platforms.
https://github.com/scipy-conference/scipy_proceedings/pull/406/commits/2b972d96cc685a5df051683204f5ab8cbb7f0346

2018-07-02 01:19 UTC, arokem commented on papers/adam_richie-halford/adam_richie-halford.rst
> +We have demonstrated Cloudknot's ability to handle complicated data and
https://github.com/scipy-conference/scipy_proceedings/pull/406/commits/572604cfdab69fcc965bb2cfd5ea023290ad9275

2018-07-02 01:19 UTC, arokem commented on papers/adam_richie-halford/adam_richie-halford.rst
> +including real life uses of the software in data analysis. We will
https://github.com/scipy-conference/scipy_proceedings/pull/406/commits/743dacb7bb754afd883bb69f7847ffa8cd5c52dd

2018-07-02 01:19 UTC, arokem commented
@dalippa : I think we've addressed the remaining comments.

2018-07-02 02:04 UTC, dalippa commented on papers/adam_richie-halford/adam_richie-halford.rst
> +objects. If the results are too large to fit on the local machine, the
Yes, they execute the algorithm in parallel, but nothing describes how the work is broken up. The example provided with the dMRI data explains that it's parallelized per patient (e.g. one patient per process).

2018-07-02 02:05 UTC, dalippa commented on papers/adam_richie-halford/adam_richie-halford.rst
> +       time, 1.5 GB of RAM, 512 MB of local storage, and no root access.
I thought one of the purposes of Python sandboxing is to work around that issue.

2018-07-02 02:20 UTC, dalippa reviewed
@richford @proceedings There were a few lingering issues that should be explained, but once those are addressed, I think this paper is ready.

2018-07-02 02:20 UTC, dalippa commented on papers/adam_richie-halford/adam_richie-halford.rst
> +part to tools such as dask-ec2 :cite:`dask-ec2` and kubernetes/helm
Dask naturally parallelizes well (http://dask.pydata.org/en/latest/custom-graphs.html), and has a scheduler that distributes computation to different machines using its scheduler (discussed in the Dask paper last year). dask-ec2 makes using dask in cloud computing environments better.

2018-07-02 02:20 UTC, dalippa commented on papers/adam_richie-halford/adam_richie-halford.rst
> +executes the UDF, and sends output back to S3. :code:`Knot` then packages
how is the task broken up in parallel?

2018-07-02 02:20 UTC, dalippa commented on papers/adam_richie-halford/adam_richie-halford.rst
> +type -- each with 64 vCPUs and 488 GB of RAM. In terms of RAM, this is
Cloudknot's usefulness would be much more impressive if it scaled horizontally, to smaller, cheaper instances like m3.large

2018-07-02 02:36 UTC, arokem commented on papers/adam_richie-halford/adam_richie-halford.rst
> +part to tools such as dask-ec2 :cite:`dask-ec2` and kubernetes/helm
That's why we say that it used to be hard to use in parallel.

2018-07-02 02:37 UTC, arokem commented on papers/adam_richie-halford/adam_richie-halford.rst
> +executes the UDF, and sends output back to S3. :code:`Knot` then packages
Along the outer-most dimension of the array, as mentioned on line 236.

2018-07-02 02:45 UTC, arokem commented on papers/adam_richie-halford/adam_richie-halford.rst
> +type -- each with 64 vCPUs and 488 GB of RAM. In terms of RAM, this is
I'm not sure that makes sense, because the cost/cpu is lower for the really large instances, and cost per GB of RAM is almost identical regardless of the size of the machine on which this runs, but you can specify the instance type you want to use as a keyword argument.

2018-07-02 02:46 UTC, arokem commented
@dalippa : does this address the remaining concerns?

2018-07-02 02:50 UTC, dalippa commented on papers/adam_richie-halford/adam_richie-halford.rst
> +executes the UDF, and sends output back to S3. :code:`Knot` then packages
OK

2018-07-02 02:50 UTC, dalippa commented on papers/adam_richie-halford/adam_richie-halford.rst
> +part to tools such as dask-ec2 :cite:`dask-ec2` and kubernetes/helm
I disagree that it's hard to use in parallel, but it *is* hard to set up in a cloud computing environment.

2018-07-02 02:51 UTC, dalippa commented on papers/adam_richie-halford/adam_richie-halford.rst
> +type -- each with 64 vCPUs and 488 GB of RAM. In terms of RAM, this is
Does this mean that the data is streamed from S3 so it doesn't need to be loaded/stored in memory completely?

2018-07-02 02:52 UTC, dalippa commented
@arokem @richford Kind of. There are still the two outstanding issues on my previous review; please see my comments.

2018-07-02 02:55 UTC, dalippa commented
@proceedings this paper is now ready.

2018-07-02 02:55 UTC, arokem commented on papers/adam_richie-halford/adam_richie-halford.rst
> +type -- each with 64 vCPUs and 488 GB of RAM. In terms of RAM, this is
Each task uses its own memory, so it doesn't matter if it's sharing tenancy with a dozen other tasks on a r4.16xlarge machine, or got its own r4.large to work on.

2018-07-02 02:56 UTC, arokem commented on papers/adam_richie-halford/adam_richie-halford.rst
> +part to tools such as dask-ec2 :cite:`dask-ec2` and kubernetes/helm
Addressed in https://github.com/scipy-conference/scipy_proceedings/pull/406/commits/fa2e337792097f76bbdc488cf851c19f651dad31

2018-07-03 23:43 UTC, merged