Paper: WrightSim
scipy-conference/scipy_proceedings pull request #408
Opened 2018-05-23 22:04 UTC by ksunden

If you are creating this PR in order to submit a draft of your paper,
see http://procbuild.scipy.org/ for logs generated by the build
process.

See the [project readme](https://github.com/scipy-conference/scipy_proceedings#build-your-paper)
for more information.

2018-06-23 20:30 UTC, deniederhut commented
Hi Wrightsim team! I'm stepping in to provide a review for this paper. 

As a first observation, we probably don't need the output of `pipenv` commited into the proceedings. Would you mind removing these?

I'll leave detailed comments about spelling and grammar and whatnot in-line (when I get back from watching the new Mr Rogers documentary), but here are some general comments in the mean time. 

1. This looks super cool! And I mean all of it: the library, the use case, and I especially like your discussion of how you found the performance bottlenecks and mitigated them. It's showing -- not telling -- how this problem was analyzed and addressed. You're not just creating a library; you're also creating an educational resource.
2. The paper mentions that there are closed-source libraries for performing similar tasks. What are they (besides NISE)? Do they have conspicuous downsides beyond not being able to see under the hood?
3. The docs currently recommend modifying the source to change from 3D experiments to 2D experiments. This feels a bit risky, and that use case will probably be better served via a CLI or config option. I see that you mention this toward the end of the paper, but it still feels... unconventional.
4. Currently, the test suite only contains a smoke test (importability). How have you established the validity of wrightsim? Viz., how do you know that the output is correct?
5. ❤️ for including all the DOIs

2018-06-23 20:41 UTC, deniederhut commented
Hmm... also the installation is throwing a build error:

```
The package setup script has attempted to modify files on your system
that are not within the EasyInstall build area, and has been aborted.

This package cannot be safely installed by EasyInstall, and may not
support alternate installation locations even if you run its setup
script by hand.  Please inform the package's author and the EasyInstall
maintainers to find out if a fix or workaround is available.
```

2018-06-24 16:22 UTC, deniederhut requested changes

2018-06-24 16:22 UTC, deniederhut commented on papers/kyle_sunden/wrightsim.rst
> +    each-other and with externally applied electric fields in the course of a
I'm not sure that we need the hyphen here

2018-06-24 16:22 UTC, deniederhut commented on papers/kyle_sunden/wrightsim.rst
> +    Numerical integration (of the Liouville-von Neumann equation) is used to
I think we're missing some linking phrases here that would make the first handful of sentences in the abstract feel less disjoint. Alternatively, we might push this part into the intro and let the abstract be restricted to WrightSim and its properties.

2018-06-24 16:22 UTC, deniederhut commented on papers/kyle_sunden/wrightsim.rst
> +A generic MDS experiment involves exiting a sample with multiple pulses of
Should this read "exciting"?

2018-06-24 16:22 UTC, deniederhut commented on papers/kyle_sunden/wrightsim.rst
> +This system that we have chosen for this simulation is very simple, with a single
We might want this to read "The system"

2018-06-24 16:22 UTC, deniederhut commented on papers/kyle_sunden/wrightsim.rst
> +This two-dimensional simulation is merely representative of ``WrightSim``'s ability
I'm not sure that "merely representative" is the semantics we want here.

2018-06-24 16:22 UTC, deniederhut commented on papers/kyle_sunden/wrightsim.rst
> +computational time relative to prior implementations.
There are different ways to think about computation time. I might say explicitly that we are concerned about wall clock time.

2018-06-24 16:22 UTC, deniederhut commented on papers/kyle_sunden/wrightsim.rst
> +``WrightSim`` is still at a nascent stage of development, but has already
Nascency can only refer to a stage of development. We might be able to reduce this to something like "While nascent, WrightSim has already..."

2018-06-24 16:22 UTC, deniederhut commented on papers/kyle_sunden/wrightsim.rst
> +shown itself to be a powerful tool.
As evidenced by what?

2018-06-24 16:22 UTC, deniederhut commented on papers/kyle_sunden/wrightsim.rst
> +This places ``WrightSim`` at an intermediate level of theory, one where
We could probably incude readibility here with stronger linking phrases. For example, it is not obvious only from the sentence structure that "intermediate" here refers to the level between "ab initio" and "plotting" in the next sentence.

2018-06-24 16:22 UTC, deniederhut commented on papers/kyle_sunden/wrightsim.rst
> +Careful analysis of the algorithms, identifying and measuring the bottlenecks and working
I think we're missing an Oxford comma here.

2018-06-24 16:22 UTC, deniederhut commented on papers/kyle_sunden/wrightsim.rst
> +was removed entirely in favor of a simpler scheme for denoting which values to
What was this scheme?

2018-06-24 16:22 UTC, deniederhut commented on papers/kyle_sunden/wrightsim.rst
> +:cite:`Nickolls_2008` was performed. In order to make the
I don't typically think of an implementation as something that is performed. It might be clearer to reduce this to "the algorithm was re-implemented in CUDA".

2018-06-24 16:22 UTC, deniederhut commented on papers/kyle_sunden/wrightsim.rst
> +propagation function were written, however it is extensible to
Have you written any more since the original implementation?

2018-06-24 16:22 UTC, deniederhut commented on papers/kyle_sunden/wrightsim.rst
> +the Matrices prior to entering the loop. This was done to conserve
This is an important point for people who are not used to working with GPUs!

2018-06-24 16:22 UTC, deniederhut commented on papers/kyle_sunden/wrightsim.rst
> +without the help of NumPy do perform automatic broadcasting of shapes.
I think we want "to" here.

2018-06-24 16:22 UTC, deniederhut commented on papers/kyle_sunden/wrightsim.rst
> +startling proof of concept display of how ``PyCUDA`` can be applied to this
While this an interesting paper, I'm not sure that I would call myself startled.

2018-06-24 16:22 UTC, deniederhut commented on papers/kyle_sunden/wrightsim.rst
> +implementation. Certain values represented by the Hamiltonian were
Which values? Is it reasonable to assume that they would remain fixed across experiments?

2018-06-24 16:22 UTC, deniederhut commented on papers/kyle_sunden/wrightsim.rst
> +implementations, there are several remaining avenues to gain even
To gain what even further?

2018-06-24 16:22 UTC, deniederhut commented on papers/kyle_sunden/wrightsim.rst
> +The CUDA implementation does not currently take full advantage shared
I think we're missing an "of" here.

2018-06-24 16:23 UTC, deniederhut commented
Thanks for pulling out the reqfile! However, it looks like a gitignore was accidentally committed during the process. Could I ask you to pull that out as well?

2018-06-26 00:39 UTC, untzag commented on papers/kyle_sunden/wrightsim.rst
> +propagation function were written, however it is extensible to
We have several that we are interested in writing / in the process, but unfortunately nothing complete at this time.

Certainly we have tried to design WrightSim to accommodate many different Hamiltonians (both built-in and user specified)... following through on that design principle is one of the first larger tasks on our road map.

2018-06-26 03:37 UTC, ksunden commented on papers/kyle_sunden/wrightsim.rst
> +was removed entirely in favor of a simpler scheme for denoting which values to
(addressed on following line)

2018-06-26 04:57 UTC, ksunden commented
Hi @deniederhut

Thanks for your review!

We have addressed the majority of the smaller comments, let us know if any of our changes require further attention.

As for other implementations, we have a bit of a round up over on our [issue tracker #10](https://github.com/wright-group/WrightSim/issues/10).
The ones mentioned here vary in how closely aligned they are to our particular niche of spectroscopy, taking different tacts.
Some try to be much more general electric field simulators, some quite a bit more narrow.
They do range in license, but none of the OSI approved licensed packages take the approach we do with `WrightSim`.
The one that is probably most closely aligned (though I have not used it, myself) is called SPECTRON. The source is distributed, however there is no explicit license applied.
I know other programs exist, but they are developed in research labs much like our own, and do not (publicly) distribute binaries or even have names, such as those used in `Gelin2009`.
I'm sure other labs have their own.
Our long term hope is that we can get our community to coalesce around an open solution for this approach, and we want to lead by example.
NISE is our own package, as well, though without the CUDA implementation, and with a much messier codebase, and not designed from the start used by others (though is MIT licensed and available).
The pain of using it was the reason for starting over from scratch.

The docs give an example script to use as a starting point for using `WrightSim` as a library.
Our primary focus thus far has been on the python API, allowing individual scripts to be made easily.
We would like to build a CLI entry point/config file front end (and I even would love to tie such front end into our GUI data acquisition apps, if nothing else as a fun weekend project at that point).
However, thus far, our focus is on library/API design and performance.
Perhaps our README should be a bit more clear that that is a starting point, not actually have users edit that directly.

Testing is the very next thing on my list for this package, I plan to get at least a few high level integration tests written within the week.
Proper unit tests will follow, as well.
The importability test was added mostly so we would have the framework ready when we got to this stage.

On your issue with installing: This was an issue that we made in one package/setup.py file, which then got copied around before we found it. It has now been fixed in the `development` branch (Was also a problem in one of our second order dependencies, but that has a new PyPI version out now as well).
We will get this fix merged into master shortly.

Thanks,
The WrightSim team

2018-06-30 21:52 UTC, deniederhut commented on papers/kyle_sunden/wrightsim.rst
> +    ``WrightSim`` is made using modules that can be exchanged to accomidate many
I'm not sure this spelling is correct. If you're on unix, a quick run through aspell should catch this kind of thing.

2018-06-30 21:52 UTC, deniederhut commented on papers/kyle_sunden/wrightsim.rst
> +We also discuss parallelzation approaches we have taken, and show how the
Also spelling.

2018-06-30 21:52 UTC, deniederhut commented on papers/kyle_sunden/wrightsim.rst
> +Experimentalists isolate this condition spatially, by placing an aperature
Also spelling.

2018-06-30 21:52 UTC, deniederhut commented on papers/kyle_sunden/wrightsim.rst
> +record, simply storing a list of the indicies directly.
Also spelling

2018-06-30 21:55 UTC, deniederhut commented
Great work! The abstract still feels a bit choppy, and I've caught some spelling errors, but otherwise this is looking really good! One brief question:

> Our long term hope is that we can get our community to coalesce around an open solution for this approach, and we want to lead by example.

This feels like an important point -- is this aspiration written in the paper?

2018-07-03 01:24 UTC, deniederhut commented
Okay - this looks good to me! @proceedings, I think we are ready to go!

2018-07-03 01:27 UTC, deniederhut approved these changes

2018-07-03 01:29 UTC, ksunden commented
Thank you, @deniederhut

2018-07-03 23:46 UTC, merged