Paper: "Harnessing the power of Scientific Python to Investigate Metaproteomes and Biogeochemistry of the Central Pacific Ocean"
scipy-conference/scipy_proceedings pull request #410
Opened 2018-05-23 23:39 UTC by naheld

If you are creating this PR in order to submit a draft of your paper,
see http://procbuild.scipy.org/ for logs generated by the build
process.

See the [project readme](https://github.com/scipy-conference/scipy_proceedings#build-your-paper)
for more information.

2018-05-24 02:40 UTC, mpacer commented
You do not include `figure1b.png` in the PR. This is needed for the paper to build.

2018-05-24 12:06 UTC, naheld commented
My mistake - just updated Figure 1

2018-06-04 18:56 UTC, cbcunc commented on papers/n_held/n_held.rst
> +  Oceanographic expeditions commonly generate millions of data points for various chemical, biological, and physical features, all in different formats. Scientific Python tools are extremely useful f
oxygen-depleted

2018-06-04 19:02 UTC, cbcunc commented on papers/n_held/n_held.rst
> +  Oceanographic expeditions commonly generate millions of data points for various chemical, biological, and physical features, all in different formats. Scientific Python tools are extremely useful f
6,000 metadata? Unclear.

2018-06-04 19:22 UTC, cbcunc commented on papers/n_held/n_held.rst
> +  Oxygen concentrations in the world ocean at 300m depth. Warm colors indicate more oxygen, cool colors indicate less. The sampling locations of the ProteOMZ cruise are overlaid as yellow stars. Prot
oxygen-depleted

2018-06-06 16:37 UTC, cbcunc commented on papers/n_held/n_held.rst
> +We travelled to the oxygen poor Pacific ocean in winter 2016 to study biological and chemical processes on the ProteOMZ research cruise (https://schmidtocean.org/cruise/investigating-life-without-oxy
space between `(18 variables)` and `which`

2018-06-06 16:39 UTC, cbcunc commented on papers/n_held/n_held.rst
> +  Oceanographic expeditions commonly generate millions of data points for various chemical, biological, and physical features, all in different formats. Scientific Python tools are extremely useful f
I think this was supposed to be `6,000 metadata points` as that is the language further into the paper.

2018-06-06 16:43 UTC, cbcunc commented on papers/n_held/n_held.rst
> +We travelled to the oxygen poor Pacific ocean in winter 2016 to study biological and chemical processes on the ProteOMZ research cruise (https://schmidtocean.org/cruise/investigating-life-without-oxy
Regarding using semicolon to make a compound sentence (`transformations within microbial cells; as such, protein datasets provide`), you may as well make it two sentences for added readability (`transformations within microbial cells. As such, protein datasets provide`)

2018-06-06 20:09 UTC, cbcunc commented on papers/n_held/n_held.rst
> +We developed a visualization platform to explore the hydrographic data, which includes physical parameters such as temperature and chemical parameters such as ammonium concentrations. The visualizati
`with surface values at the top (figure)`. Which figure? In the next sentence: `each variable is in a seperate column (Figure 2)`, so maybe you have two references to Figure 2? possibly consider splitting Figure 2 into two figures as references to it regard two different things (plots vs. CSV file).

2018-06-06 20:10 UTC, cbcunc commented on papers/n_held/n_held.rst
> +We developed a visualization platform to explore the hydrographic data, which includes physical parameters such as temperature and chemical parameters such as ammonium concentrations. The visualizati
`CSV` file should be capitalized. It is an acronym. Yes, the file extension csv is lower case. But you are referring to the file itself rather than the file extension.

2018-06-06 20:14 UTC, cbcunc commented on papers/n_held/n_held.rst
> +  Visualization of the station map and hydrography data as a function of water column depth. The file is exported by Bokeh as a standalone html document, allowing it to be easily shared with collabor
If the figure is not split into multiple parts, then describe all the components of the figure including the CSV display and the cruise path map.

2018-06-06 20:15 UTC, cbcunc commented on papers/n_held/n_held.rst
> +  Visualization of the station map and hydrography data as a function of water column depth. The file is exported by Bokeh as a standalone html document, allowing it to be easily shared with collabor
It is confusing to have a[n] (almost unredable) caption on the cruise path map within a figure with its own caption. Consider splitting the cruise path map into its own figure, with the caption in the same style as the other captions.

2018-06-06 20:16 UTC, cbcunc commented on papers/n_held/n_held.rst
> +We developed a visualization platform to explore the hydrographic data, which includes physical parameters such as temperature and chemical parameters such as ammonium concentrations. The visualizati
I see other references in your paper to CSV file which are properly capitalized.

2018-06-06 20:47 UTC, cbcunc commented on papers/n_held/n_held.rst
> +The main product of this work is a fully interactive Bokeh server application, which integrates protein quantitative data, protein annotations, and hydrographic data. For full interactivity among plo
`For illustrative purposes we use in this paper a truncated CSV file` is better phrased `For illustrative purposes in this paper we use a truncated CSV file`

2018-06-06 20:49 UTC, cbcunc commented on papers/n_held/n_held.rst
> +The CSV file is read as a pandas dataframe [PANDAS]_ and consists of 103 rows (one per each unique sampling location and depth) and over 15,000 columns, where each column represents a different prote
Less stilted: ` the full protein dataset of 60,000  proteins.`

2018-06-06 20:58 UTC, cbcunc commented on papers/n_held/n_held.rst
> +We now describe a use case to demonstrate the utility of the application (Figure 3). On initial load, the user can see a map of the ProteOMZ 2016 sampling locations. The user can select a Station via
Figure 3 describes `a use case to demonstrate the utlity of the application`? I think the figure reference here is unwanted.

2018-06-06 21:00 UTC, cbcunc commented on papers/n_held/n_held.rst
> +We now describe a use case to demonstrate the utility of the application (Figure 3). On initial load, the user can see a map of the ProteOMZ 2016 sampling locations. The user can select a Station via
Or did you mean to refer to Figure 4?

2018-06-07 13:13 UTC, cbcunc commented on papers/n_held/n_held.rst
> +We now describe a use case to demonstrate the utility of the application (Figure 3). On initial load, the user can see a map of the ProteOMZ 2016 sampling locations. The user can select a Station via
Figure 3 is the aggregated data model. Did you mean Figure 4?

2018-06-07 13:16 UTC, cbcunc commented on papers/n_held/n_held.rst
> +  A- Initial load of the Bokeh application at Station 5. B- Selecting on a single protein and investigating relationship to hydrographic data. C- Filtering on the taxon, we can see that Prochlorococc
Please consider splitting Figure 4 into four (larger, more readable) figures and reference each in the place of the text which the illustrate. As it is the Figure 4 covers a verbose amount of text which would support multiple figure references.

2018-06-07 14:16 UTC, cbcunc commented on papers/n_held/n_held.rst
> +So far we have looked only at protein function, but a user may also be interested in taxonomic origin of the proteins. At Station 5, we see in the Diversity of Microbial Proteins bar graph that most
If you are not going to split Figure 4, then please reference which part of the Figure to which you refer, for instance, `(Figure 4C)` instead of `(Figure 4)`.

2018-06-07 14:18 UTC, cbcunc commented on papers/n_held/n_held.rst
> +So far we have looked only at protein function, but a user may also be interested in taxonomic origin of the proteins. At Station 5, we see in the Diversity of Microbial Proteins bar graph that most
Also, please circle the specific widget in the Figures to which the text refers and annotate in the figure caption.

2018-06-07 14:20 UTC, cbcunc commented on papers/n_held/n_held.rst
> +We quickly discovered that attempting to display over 15,000 lines on a single Bokeh plot was infeasible. We thus display only the top 5% most abundant proteins but allow the user to adjust this perc
I don't see the Percentile slider in the figure.

2018-06-07 14:43 UTC, cbcunc commented on papers/n_held/n_held.rst
> +At Station 5, we see a dark band of proteins that are slightly more abundant than average but are largely conservative in the deep ocean below 200m (:ref:: Figure 5). At 120m a large number of protei
`Thus we can can see clearly that the phytoplankton proteins, which are highly abundant in the surface ocean, disappear.` This is not at all clear from the referenced Figure 5. If we are displaying all 15,000 proteins, what in the display is identifying phytoplankton speicifcally as more abundant at the surface?

2018-06-07 15:18 UTC, cbcunc commented on papers/n_held/n_held.rst
> +We used Datashader implemented in Holoviews and a Jupyter notebook to view the dataset in its entirety to see if major patterns in protein abundance emerge when all 15,000 test dataset lines are disp
`a Dask dataframe [DASK]_, which significantly improved performance over a Pandas dataframe.` That is a claim which should either be cited (with something more than a link to the Dask web site) or demonstrated. Otherwise, you might rephrase as `converted to a Dask dataframe [DASK]_ for performance reasons` (which makes no specific performance claim.)

2018-06-07 16:06 UTC, cbcunc commented on papers/n_held/n_held.rst
> +A key challenge to this project was building a data model that worked most efficiently with the libraries we selected. For instance, the Bokeh ColumnDataSource imposed a 2D structure on our multi-dim
`documentation of the data modules and best practices` data *models* maybe?

2018-06-07 16:09 UTC, cbcunc commented on papers/n_held/n_held.rst
> +The visualizations we built are already proving to be useful. We discuss above just one high level example in which the application helps us to explore taxonomic and functional differences between ox
`finer level analyses are sure to uncover even more exciting trends.` Get rid of the semicolon and put in a standalone sentence.

2018-06-07 20:25 UTC, cbcunc reviewed
Noelle, this is a preliminary review in order to give you some time to respond and make changes before the date for final approval.

I generally favor the inclusion of this paper. I think it is noteworthy work and it interests me. But I am required by the review guidelines (https://github.com/scipy-conference/scipy_proceedings/blob/master/review_criteria.md) to point out a few issues which should be resolved before final approval.

The first set of issues have to do with the criteria for written quality and are all addressed in comments interspersed below throughout the file changes for n_held.rst. Hopefully these comments are self-explanatory and don't have to be repeated in this comment.

The other issues have to do with the requirement to verify the computational content. Fortunately, you have made your code and sample data available. I ran them in an updated Anaconda3 conda environment with holoviews and datashader installed. Conda-forge is my preferred package channel. I believe this matches the environment used by most people attending SciPy.

1) I believe the example repos could each use a README.

2) The hydrography notebook ran well. I was able to click on a row in the table and see the data for that station and depth highlighted in the plots. However, clicking on the stations in the station map did not highlight the data points for that station. I can't tell from the paper, however, whether that was the intended behavior or not, so I'm just reporting my result.

3) The Bokeh app didn't seem to do anything. It's a .py file, so I simply ran it with `python visualization_application.py`I put a print function at the end of the script (after make_layout is added to curdoc) on my local checkout just to make sure it was running to the end. It creates no files. It doesn't start a browser with plots. Just nothing. Maybe this was supposed to run in a notebook? There's just no notebook in the repo. Maybe is needs a call to bokeh.io.show? This is why you need READMEs. Tell us what to do with your repo in a README.

4) in the datashader notebook, there is no output, either from the "View the data without datashading" cells, or the "Now try with datashader" cells. This was in an Anaconda3 conda environment with bokeh, holoviews, and datashader installed from conda-forge.

2018-06-11 14:34 UTC, naheld commented
Thanks for your detailed review. I agree with most of the editorial changes you pointed out and will begin incorporating them. Thanks especially for the reminder to add READMEs to the repos. 

The Bokeh app needs to be run with Bokeh server. You can run it with `bokeh serve --show visualization_application.py` and it will typically open automatically in your browser. I'll be sure to include this in the README to avoid future confusion.

2018-06-11 14:55 UTC, cbcunc commented on papers/n_held/n_held.rst
> +We quickly discovered that attempting to display over 15,000 lines on a single Bokeh plot was infeasible. We thus display only the top 5% most abundant proteins but allow the user to adjust this perc
Now that I can run the boken app, I can see the percentile slider. It was just too small to see in the figure in the paper. I could magnify the figure. But the resolution at higher magnification was not enough to identify the slider.

2018-06-11 14:58 UTC, cbcunc commented
Thanks. The Bokeh app works as described. In fact, it is huge and I need to scroll the browser to see it all. Maybe scale it some. I can see the percentile slider now, though.

2018-06-11 15:03 UTC, cbcunc commented
Also, in the Bokeh app, the initial station is 4. It is not highlighted in the map, however. Only after selecting another station with the station widget is the station highlighted on the map.

2018-06-12 19:54 UTC, jrleeman reviewed
I also favor the inclusion of this paper with minor revisions. Some comments:

## General
* Figures 2, 3, 4 are all too small and should either be made landscape pages or with text enlarged. Maybe even just callouts to what things are would help.
* Are the repositories always going to live under individual user accounts or should you link to a more general GitHub organization or WHIO group page with links to the code?

## Code
* If you linked the plots y axes in the Bokeh app it would be handy so we're looking at the same area of all data possibly.
* It would be very helpful to provide an `environment.yml` or `requirements.txt` in the repositories so users can get up and running easily.
* As mentioned, adding a README would be great.
* I'd run flake8 on the notebook code just to help clean up the appearance and increase readability for other scientists that may want to modify it. It's also a good set of guides to request any future contributors to follow.
* Some of the plot generation in the notebooks would be simplified and easier to change if you used a dict of kwargs for the things that will be the same in all plots. 

Overall, this was very interesting work. The manuscript suggestions should be addressed, the code suggestions are purely optional.

2018-06-12 19:54 UTC, jrleeman commented on papers/n_held/n_held.rst
> +  Oceanographic expeditions commonly generate millions of data points for various chemical, biological, and physical features, all in different formats. Scientific Python tools are extremely useful f
"causes deoxygenation", not "cause" possibly?

2018-06-12 19:54 UTC, jrleeman commented on papers/n_held/n_held.rst
> +Oceanography is concerned with understanding the ocean as a holistic and dynamic system, integrating information from disciplines such as biology, chemistry, geology, and physics. But just how to inc
You're not just looking at major trends though right? Maybe generalize that to "trends and relations" or similar if that is indeed the case.

2018-06-12 19:54 UTC, jrleeman commented on papers/n_held/n_held.rst
> +In this paper, we describe our efforts to create an integrated proteomics and metadata visualization tool. The application is intended as an exploratory tool for user-driven discovery of patterns in
"recommendations for scientists working with and for contributors to these libraries."?

2018-06-12 19:54 UTC, jrleeman commented on papers/n_held/n_held.rst
> +We quickly discovered that attempting to display over 15,000 lines on a single Bokeh plot was infeasible. We thus display only the top 5% most abundant proteins but allow the user to adjust this perc
Missing space : "that proteins"

2018-06-12 19:54 UTC, jrleeman commented on papers/n_held/n_held.rst
> +At Station 5, we see a dark band of proteins that are slightly more abundant than average but are largely conservative in the deep ocean below 200m (:ref:: Figure 5). At 120m a large number of protei
The reference to figure 5 isn't rendering properly in the final PDF.

2018-06-13 14:55 UTC, cbcunc commented on papers/n_held/n_held.rst
> +  Oceanographic expeditions commonly generate millions of data points for various chemical, biological, and physical features, all in different formats. Scientific Python tools are extremely useful f
"temperatures cause" is correct. However, the comma following "temperature" should be removed.

2018-06-18 17:04 UTC, naheld commented
Some recent updates:
I added README and enviornment.yml files to all of the repositories related to this paper. 
Figures 2, 3, and 4 are now larger/broken into parts, facilitating viewing

2018-06-19 20:10 UTC, jrleeman requested changes
Thank you for addressing many of the points in this revision. I'd like to point out several things:

* I'd spell out "Google Maps" vs. "gmap"
* I didn't mark up each instance, but many of the figure numbers are now incorrect. Please carefully check and fix these.
* Figure 2 should be re-captured as the cropping it too large and there is a tool tip for the refresh button showing.

2018-06-21 18:53 UTC, cbcunc approved these changes
I approve this paper. Thank you for making my suggested changes. There is one small one outstanding change yet to make: "oxygen-depleted" (hyphenated) in two places instead of "oxygen deplete" ("deplete" is a verb, not an adjective). However, I want to give my approval now and changes may be made up until the July 7 deadline.

2018-06-22 16:05 UTC, jrleeman approved these changes
Approved for inclusion.

2018-06-24 19:23 UTC, dalippa commented
@cbcunc @jrleeman Please tag @proceeedings when you feel the paper is ready. Thanks!

2018-06-25 12:51 UTC, cbcunc commented
@dalippa, there is no @proceedings tag when I enter it into a comment. There is a @scipy-proceedings-bot tag entered in this comment. Is that the one you meant? GitHub tags are made on entire repository releases and I don't think you meant the entire repository. Maybe you meant a label? I am not authorized in this repository to add, change, or remove labels.

2018-06-25 15:32 UTC, deniederhut commented
Hi @cbcunc ! I saw your comment yesterday and tagged the paper as "ready", so we are good to go here.

2018-06-26 02:36 UTC, dalippa commented
@cbcunc You won't see a @proceedings tag, but it will reach all of us co-chairs if you add it.

2018-07-03 23:49 UTC, deniederhut requested changes
Hi @naheld ! Paper PRs should not modify the repository outside of their own folder. It looks like you have... five? image files committed to the root of the repo. Could I ask you to move/remove these as appropriate?

2018-07-04 13:05 UTC, naheld commented
@deniederhut Sorry about that - not sure how it happened but I have just resolved it.

2018-07-04 23:41 UTC, deniederhut commented
Oh hey, congrats on your GRFP! And thanks for rming those files. This looks good to me!

2018-07-04 23:41 UTC, deniederhut approved these changes

2018-07-04 23:42 UTC, merged