Paper: Reproducible Environments for Reproducible Results
scipy-conference/scipy_proceedings pull request #411
Opened 2018-05-24 01:47 UTC by werwty

If you are creating this PR in order to submit a draft of your paper,
see http://procbuild.scipy.org/ for logs generated by the build
process.

See the [project readme](https://github.com/scipy-conference/scipy_proceedings#build-your-paper)
for more information.

2018-06-18 10:52 UTC, WorklnProgress reviewed
Overall a good draft, some formatting issues. A few suggestions for improving clarity. I think the paper would greatly benefit by clearly identifying how Pulp is a confluence of all the things mentioned above it. A suggestion to do this would be identify drawback of each technology in isolation and then in Pulp portion, add a section that addresses each. Also a diagram showing the Pulp workflow would be greatly beneficial.

2018-06-18 10:52 UTC, WorklnProgress commented on papers/zhang_macdonald/zhang_macdonald.rst
> +
I would recommend seeing the paper built by the build server and having some consistency in the font (size can differ) between abstract and the main paper.

2018-06-18 10:52 UTC, WorklnProgress commented on papers/zhang_macdonald/zhang_macdonald.rst
> +Pulp is an open source repository manager[2]_ that can be used to create
I think this would benefit a lot from a diagram showing the workflow and what steps are repeatable etc. As it stands now, it's really difficult to get an understanding of the exact process and reasons behind the steps.

2018-06-18 10:52 UTC, WorklnProgress commented on papers/zhang_macdonald/zhang_macdonald.rst
> +
Some code block formatting issues. If you see the paper on the build server, you can see that some code blocks leak to the second column.

2018-06-18 10:52 UTC, WorklnProgress commented on papers/zhang_macdonald/zhang_macdonald.rst
> +For researches who use code in their methods, it is crucual to consider the
typo, crucial?

2018-06-18 10:52 UTC, WorklnProgress commented on papers/zhang_macdonald/zhang_macdonald.rst
> +Vandewalle identifies several necessities for complete reproducibility
may be bullets to emphasize what the two factors are clearly?

2018-06-18 10:52 UTC, WorklnProgress commented on papers/zhang_macdonald/zhang_macdonald.rst
> +Ansible_ is an IT automation tool. It can configure systems, deploy software,
May be emphasize that there are other tools like Ansible and explain the reason behind describing only Ansible just like at the end of the paper, a section explains why `Docker` over the more general `LXC` etc has been chosen.

2018-06-18 10:52 UTC, WorklnProgress commented on papers/zhang_macdonald/zhang_macdonald.rst
> +This Image can be given to peer reviewers and other collaborators as a baseline
may be `image` instead of Image

2018-06-18 10:52 UTC, WorklnProgress commented on papers/zhang_macdonald/zhang_macdonald.rst
> +A Dockerfile is a text document that contains all the commands a user could call
Yaml file instead of text document?

2018-06-18 10:52 UTC, WorklnProgress commented on papers/zhang_macdonald/zhang_macdonald.rst
> +    Content units (like Python Wheel, or Ansible Role) in Pulp are organized by
General formatting with color, beginning of paragraphs etc in this section, can be easily seen on the build server.

2018-06-18 15:29 UTC, dalippa requested changes
Overall, the paper makes a weak case and is mostly a survey of existing software methods for ensuring reproducibility and a listing of API calls to use pulp. Very little of the paper focuses on the novelty of pulp, comparing and contrasting with existing systems (especially git), and notably excludes CI-CD systems and IPython notebooks that are currently top choices for reproducing results.

The structure of the paper also needs work: the paper narrative doesn't flow, does not describe the benefits of pulp (which was introduced abruptly and briefly), etc.

2018-06-18 15:29 UTC, dalippa commented on papers/zhang_macdonald/zhang_macdonald.rst
> +But this only manages package dependencies and not system dependencies. And,
Can you give an example of system dependencies? Are you referring to configuration? OS? System architecture?

2018-06-18 15:29 UTC, dalippa commented on papers/zhang_macdonald/zhang_macdonald.rst
> +Vandewalle identifies several necessities for complete reproducibility
Bullets or a semicolon delimited list after a colon work well.

2018-06-18 15:29 UTC, dalippa commented on papers/zhang_macdonald/zhang_macdonald.rst
> +Scholarly research containing descriptions of methodology is no longer
This is the third time on this page that source code isn't sufficient. Consider removing this sentence.

2018-06-18 15:29 UTC, dalippa commented on papers/zhang_macdonald/zhang_macdonald.rst
> +what was actually done and what is described in literature." :cite:`Boettiger`
What about hosted IPython notebooks? This has been commonplace in the Python community for many years now.

2018-06-18 15:29 UTC, dalippa commented on papers/zhang_macdonald/zhang_macdonald.rst
> +Publishing source code in papers makes them inflexible to change-- bugs fixed
This is a good point, but can be solved by version control. Scripts that automatically check out the latest on master, or equivalent, have been part of continuous integration-continuous deployment (CI-CD) systems for a long time now. Why is it not possible to extend the same principles to such scripts?

2018-06-18 15:29 UTC, dalippa commented on papers/zhang_macdonald/zhang_macdonald.rst
> +package manager. System dependencies in git can only be documented-- and need
This is incorrect. Dependencies in git can be used to manage the environment via submodules (https://git-scm.com/book/en/v2/Git-Tools-Submodules).

2018-06-18 15:29 UTC, dalippa commented on papers/zhang_macdonald/zhang_macdonald.rst
> +For Python users who need to guarantee deterministic builds, another step is
For deterministic builds, it might be best to have CI-CD systems build an egg rather than leave it to the user to build the system.

2018-06-18 15:29 UTC, dalippa commented on papers/zhang_macdonald/zhang_macdonald.rst
> +1. Set up a pulp repository to mirror a subset of packages from PyPI that
What does pulp bring to the table that other current mechanisms do not?

2018-06-18 15:29 UTC, dalippa commented on papers/zhang_macdonald/zhang_macdonald.rst
> +Publish a repository
Can you contrast this with git? What's the difference between publish and a push?

2018-06-18 15:29 UTC, dalippa commented on papers/zhang_macdonald/zhang_macdonald.rst
> +Acknowledgements
Future work section?

2018-06-19 18:25 UTC, cyrush commented
Overall Recommendations:
- needs to be clearly framed as focused on introducing Pulp
- needs a more focused related work section
- needs more details on Pulp, how it address shortfalls with other tools, etc

Review Details:

Since this is focused on Pulp, I recommend you include Pulp in the title.

The introduction provides motivation and states it explores several different methods for managing environmental reproducibility. I don't think the narrative supports the "several different methods" aspiration. Environmental Management section only focuses on introducing Pulp.  No need to make such broad claims, I recommend removing this claim and simply focusing the overall narrative on introducing Pulp. 

This paper needs a more focused related work section. 

There are many existing efforts in this space (conda's environment support, binder, popper (https://github.com/systemslab/popper), etc) 

It would be intractable to do a deep, in-depth comparison with all of these tools, but since they are closer to Pulp than tools which are discussed (published source code, using version control), they should be included. 

The `Tools` section as written is part background, part related work, part components leveraged by Pulp -- this makes it hard to parse. 

There are also quite a few narrative gaps, here are a few examples:

The Containers subsection in Tools introduces the concept of a Container and Image, but then jumps
to talking about Docker files without introducing Docker. What is missing is a statement that Docker is a specific container technology.  The listed drawbacks of containers reference specific issues related to Docker (from Docker's bug tracker). Yes, Docker is a behemoth and often colloquially synonymous with Containers, but there are other Container technologies.

The Python Packaging section talks about how "Pip was selected", but it is not clear what it was selected for (Pulp hasn't really even been introduced at this point )

The paper needs more content related to Pulp. The Pulp subsection provides a specific example workflow using Pulp -- but it does not clearly outline Pulp's design, which parts of the Tools section are leveraged, or how it addresses listed limitations in other tools, etc.

2018-06-29 21:12 UTC, deniederhut commented
Howdy @werwty ! How is the rewrite going?

2018-06-29 21:29 UTC, werwty commented
Hey, it's going, I will push out the revision next Monday.

On Fri, Jun 29, 2018, 17:12 Dillon Niederhut <notifications@github.com>
wrote:

> Howdy @werwty <https://github.com/werwty> ! How is the rewrite going?
>
> —
> You are receiving this because you were mentioned.
>
>
> Reply to this email directly, view it on GitHub
> <https://github.com/scipy-conference/scipy_proceedings/pull/411#issuecomment-401475407>,
> or mute the thread
> <https://github.com/notifications/unsubscribe-auth/AF6ytkxZ1mPl1nGY3NKbRF67lo_kKZgWks5uBphFgaJpZM4ULb5J>
> .
>

2018-06-29 22:52 UTC, deniederhut commented
Hm... that won't leave much time for the reviewers to take another pass through the paper. Is there any chance you could push something sooner?

2018-06-30 15:07 UTC, werwty commented
Ack, we will have the revision ready by tonight/early tomorrow morning

On Fri, Jun 29, 2018, 18:52 Dillon Niederhut <notifications@github.com>
wrote:

> Hm... that won't leave much time for the reviewers to take another pass
> through the paper. Is there any chance you could push something sooner?
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub
> <https://github.com/scipy-conference/scipy_proceedings/pull/411#issuecomment-401493087>,
> or mute the thread
> <https://github.com/notifications/unsubscribe-auth/AF6yti8kdKGH3dLlVgzY1iwsAz5uqazTks5uBq_JgaJpZM4ULb5J>
> .
>

2018-07-02 00:15 UTC, dalippa commented
Hi @werwty. You mentioned you would have a new revision available. Will it be up by Monday evening for re-review?

2018-07-02 12:41 UTC, werwty commented
Revision is up and ready for re-review. Sorry about the delay.

2018-07-02 14:59 UTC, deniederhut commented
Dear @WorklnProgress and @cyrush do you feel this paper is now ready for inclusion in the proceedings?

2018-07-03 16:19 UTC, cyrush commented
@deniederhut  I plan to review today.

2018-07-04 03:48 UTC, deniederhut commented
Hi @WorklnProgress ! We are compiling the names of our reviewers for acknowledgment in the proceedings. There is not a name attached to your GitHub handle - would you mind sending it my way? If you don't want it publicly listed, that's okay too.

2018-07-05 13:56 UTC, WorklnProgress commented
Update my name in the profile. I will review once more tonight. Thank you!

On Tue, Jul 3, 2018 at 11:48 PM Dillon Niederhut <notifications@github.com>
wrote:

> Hi @WorklnProgress <https://github.com/WorklnProgress> ! We are compiling
> the names of our reviewers for acknowledgment in the proceedings. There is
> not a name attached to your GitHub handle - would you mind sending it my
> way? If you don't want it publicly listed, that's okay too.
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub
> <https://github.com/scipy-conference/scipy_proceedings/pull/411#issuecomment-402355114>,
> or mute the thread
> <https://github.com/notifications/unsubscribe-auth/AJU0cEtbec6y6rEFJFR_iMb8cSpVonGlks5uDDskgaJpZM4ULb5J>
> .
>

2018-07-05 19:39 UTC, cyrush commented
This reads better and addressed several requests. I still think it could use a related work section -- there are several things close or trying to solve similar problems.  The paper is still quite short (~3 pages w/o references). There isn't a hard threshold on number of pages, but it does seem more text could clarify the presentation.


There are still a few narrative jumps:  

1) Ansible Roles are referenced before they are described.

2)  "Pulp’s tasking system requires running rq.", Whats rq?


A diagram for the example workflow would help guide readers through that section.


Here are a few minor things I spotted:

Pulp Architecture Diagram:

For the diagram, the titles of the components aren't separated from their descriptions, for example:

1) WSGI application Pulp’s web application is ...
component.

Maybe add a '-'?

1) WSGI application - Pulp’s web application is ...


Containers subsection:

The sentence after Container is quoted, but not sure why + there is no attribution for the quote

2018-07-06 13:39 UTC, dalippa requested changes
@werwty @WorklnProgress @proceedings Overall the paper is improved, but I recommend we reject it on the basis that there are claims that are not backed up or are incorrect, alternatives that are not explored, and issues in the narrative & citations.

I am open to the possibility of an extension, so that the paper would be published after the conference with the final copy of the proceedings.

2018-07-06 13:39 UTC, dalippa commented on papers/zhang_macdonald/zhang_macdonald.rst
> +attention. Because software is an integral part of modern science, software distributions and its
"and their"

2018-07-06 13:39 UTC, dalippa commented on papers/zhang_macdonald/zhang_macdonald.rst
> +frequently interfere, leading to increasingly complex solutions. Various communities (often formed
interfere => conflict

2018-07-06 13:39 UTC, dalippa commented on papers/zhang_macdonald/zhang_macdonald.rst
> +   ecosystem and a universal package manager called Pulp_, this paper explores various approaches
"universal package manager" is incredibly important, especially if it's language agnostic. If that's truly the case, it belongs in the abstract.

2018-07-06 13:39 UTC, dalippa commented on papers/zhang_macdonald/zhang_macdonald.rst
> +optimizing for a different balance of needs. Rapid evolution within these communities can increase
"Rapid evolution within these communities can increase the already significant learning curve" - how so? Evolution of the language? Java has been the same for about 10-15 years; Python for the the past 8. This isn't "rapid". Please clarify this thought some more.

2018-07-06 13:39 UTC, dalippa commented on papers/zhang_macdonald/zhang_macdonald.rst
> +Python Packaging Ecosystem
What about Anaconda? It handles cases when dependencies rely on native libraries, something that is ignored in this paper, and is increasingly more important as Python uses more native code for the sake of speed.

2018-07-06 13:39 UTC, dalippa commented on papers/zhang_macdonald/zhang_macdonald.rst
> +infrequent updates. This pattern is leads to chronically outdated software, and when security is an
Why is security of such a concern for researchers? Researchers often operate in sandboxed, not public, environments. If the goal of the paper was reproducibility in production environments, this argument has more weight. For research, not as much.

2018-07-06 13:39 UTC, dalippa commented on papers/zhang_macdonald/zhang_macdonald.rst
> +install software which might otherwise have conflicts. Additionally, each virtualenv can use a
This needs a bit more clarity.

Actually, a virtualenv is a private Python repository so that the system environment doesn't pollute the local environment. It *also* helps with conflicting dependencies between local and system, but does *not* help with conflicts between dependencies within the scope of the application. That must be managed/mitigated by the developer.

2018-07-06 13:39 UTC, dalippa commented on papers/zhang_macdonald/zhang_macdonald.rst
> +that researchers pin their versions.
When releasing *any* software, pinning versions is important.

2018-07-06 13:39 UTC, dalippa commented on papers/zhang_macdonald/zhang_macdonald.rst
> +is described in literature." :cite:`Boettiger`
Have you compared your method to something like Vagrant or Chef where you can create an entire *system* environment, which would be less flexible (e.g. for cloud computing) but provides a true private sandbox?

2018-07-06 13:39 UTC, dalippa commented on papers/zhang_macdonald/zhang_macdonald.rst
> +correct bits. This approach is incomplete however, because git lacks the ability to do
What about submodules (https://git-scm.com/book/en/v2/Git-Tools-Submodules)?

2018-07-06 13:39 UTC, dalippa commented on papers/zhang_macdonald/zhang_macdonald.rst
> +leveraging a plugin architecture. With the python plugin, for example, Pulp is able to
Are there plugins for other languages? Is this truly a universal package manager?

2018-07-06 13:39 UTC, dalippa commented on papers/zhang_macdonald/zhang_macdonald.rst
> +containing only the desired versions of packages. Source code should be packaged with twine,
twine?

2018-07-06 13:39 UTC, dalippa commented on papers/zhang_macdonald/zhang_macdonald.rst
> +If a security flaw is discovered in a dependency that was used in published research, a new
What about deprecation in case there is a security flaw with the package itself?

2018-07-06 13:39 UTC, dalippa commented on papers/zhang_macdonald/zhang_macdonald.rst
> +Summary
Future work section?

2018-07-06 13:39 UTC, dalippa commented on papers/zhang_macdonald/zhang_macdonald.rst
> +References
Please use APA style for references.

2018-07-12 04:58 UTC, deniederhut commented
Hi @werwty ! I know this is a busy time with the conference in full swing, but will you have time to respond to these comments?

2018-07-12 16:20 UTC, asmacdo commented
@deniederhut, although we'd love to clean it up and get this into the proceedings, I don't think we will have time during the conference. Feel free to close. Thanks for all the review, maybe we can get this in next year :)

2018-07-12 18:07 UTC, deniederhut commented
I'm sorry to hear this, but thanks for your honesty. Closing as withdrawan.

2018-07-12 18:07 UTC, closed without merging