Paper: WIP Earthsim paper 1st Draft
scipy-conference/scipy_proceedings pull request #415
Opened 2018-05-24 04:48 UTC by dharhas

This is not fully complete. Some incomplete sections will be fleshed out over the next few days.

2018-06-04 14:38 UTC, deniederhut commented
Hi everyone! It looks like this paper currently does not build on the preprint server. Can I ask someone to confirm whether this paper builds locally?

2018-06-08 01:54 UTC, dharhas commented
@deniederhut I was having trouble building it locally. Haven't tracked down the error yet will look into it.

2018-06-10 20:39 UTC, deniederhut commented
@dharhas the reviewers will be working off of the PDF on the build server, so it's important that we fix this quickly. I might take a look at your figure captions - this seems to be crashing the build. Also, it looks like someone has removed the header for the references section.

2018-06-11 00:47 UTC, dharhas commented
@deniederhut Thanks for the hint on captions. Looks like you cannot use underscores in label names. It is building now.

2018-06-11 02:47 UTC, deniederhut commented
😄

2018-06-19 12:25 UTC, ricardobarroslourenco commented on papers/dharhas_pothina/dharhas_pothina.rst
> +   GSSHA (Gridded Surface Subsurface Hydrologic Analysis) simulators. The goal is
`The goal is to provide a set of tools that can easily be reconfigured and repurposed as needed to rapidly solve specific emerging issues.` For which emerging issues? It would be valuable to know which novel areas would be impacted by the usage of such simulation techniques.

2018-06-19 12:35 UTC, ricardobarroslourenco commented on papers/dharhas_pothina/dharhas_pothina.rst
> +where there is often the need for highly accurate, high-resolution physical modeling. But the existing tools and workflows
`But the existing tools and workflows are too heavyweight for other potential applications, such as making short-term operational decisions in novel locations. They also make it difficult to flexibly switch between desktop and remote high-performance-computing (HPC) systems as needed for scaling up and for interactive use.` Are these tools publically available? Is there any reference paper or reports on their implementation? It would be nice to show their limitations explicitly.

2018-06-19 12:39 UTC, ricardobarroslourenco commented on papers/dharhas_pothina/dharhas_pothina.rst
> +the AdH and GSSHA simulators [cite adh & gssha]. The goal is to provide a set of flexible, high-performance tools that can easily be reconfigured and repurposed
`The goal is to provide a set of flexible, high-performance tools that can easily be reconfigured and repurposed as needed to rapidly solve specific emerging issues.` Same comment made at the abstract section.

2018-06-19 13:16 UTC, ricardobarroslourenco commented on papers/dharhas_pothina/dharhas_pothina.rst
> +4. Data gridding: Based on the model specification, any spatially varying material properties, initial conditions and
`Data gridding: Based on the model specification, any spatially varying material properties, initial conditions and time-varying forcing functions (i.e. boundary conditions) are regridded from the original data sources to the computational mesh.` A general comment for this part of the paper, but also on your contributions on regredding(later on the text): Which interpolation algorithms are available? Are all them parallelizable? What is the efficiency of different classes of interpolators in your implementation? When you shift from a parallel execution run in a local desktop to one run in an HPC environment, how the runtimes improve? Are there cases that it doesn't scale well?

2018-06-19 13:19 UTC, ricardobarroslourenco commented on papers/dharhas_pothina/dharhas_pothina.rst
> +is run on an HPC system.
`For larger simulations, this is run on an HPC system.` Which system? What is a general configuration?

2018-06-19 13:32 UTC, ricardobarroslourenco commented on papers/dharhas_pothina/dharhas_pothina.rst
> +available.  This linkage of
`This linkage of computation and visualization can be very problematic, because the local machine may not have enough processing power to simulate the model in a reasonable time, but if the model is simulated remotely, the resulting data files can be too large to be practical to transfer to the local machine for analysis.` This is an important statement. However, it lies in the specifics of HPC environment you are dealing with. Certain HPC environments are not designed for _online interactive_ visual processing, such as high tier CPU Supercomputers. So it would be beneficial to bring context to this statement because large runs often happen in an offline way, and if parameters need to be changed, another run often is necessary.

2018-06-19 14:09 UTC, ricardobarroslourenco commented on papers/dharhas_pothina/dharhas_pothina.rst
> +Moreover, the tools that implement the current workflow are primarily "heavyweight" approaches that encode a wide
It is not true that is not necessary to include assumptions / architectural decisions when running HPC jobs. This could be abstracted to the end user, but such information is indeed necessary. Abstractions may be flexible, either by using various configurations or even with ML-based performance tuning (or setup parametrization), but still, this information needs to be supplied.

2018-06-19 14:20 UTC, ricardobarroslourenco commented on papers/dharhas_pothina/dharhas_pothina.rst
> +EarthSim is a website and associated GitHub repository that serves two purposes. First, it is a location to work on
Please include links to the repo and to the website. If the website is not permanent, include a website citation _(often includes a note: "accessed in dd/mm/yyyy")_

2018-06-19 14:27 UTC, ricardobarroslourenco commented on papers/dharhas_pothina/dharhas_pothina.rst
> +The overall goal is to provide a set of tools that work well together and can easily be reconfigured and repurposed
(Same comment of abstract: need to clarify goal)

2018-06-19 14:30 UTC, ricardobarroslourenco commented on papers/dharhas_pothina/dharhas_pothina.rst
> +other new open source tools Filigree and Quest. Short descriptions of these tools follow:
Short descriptions of tools are ok, but it would be nice to reference them. Is there just the library guides/repos or there are any paper on their implmentation? (for example scikit-learn is cited as this [paper](http://www.jmlr.org/papers/volume12/pedregosa11a/pedregosa11a.pdf))

2018-06-19 14:37 UTC, ricardobarroslourenco commented on papers/dharhas_pothina/dharhas_pothina.rst
> +All of the above tools are fully general, applicable to *any* data-analysis or visualization project, and establish a baseline capability for running analysis and visualization of arbitrarily large d
`establish a baseline capability for running analysis and visualization of arbitrarily large datasets locally or remotely, with fully interactive visualization in the browser regardless of dataset size` 

This is a bold statement, and hard to prove right. Often for visualization on these tools, you need to reduce data by some sort of encoding/compression/modeling method, or subsampling, as well on relying on distributed processing frameworks for data handling. The visualization libraries don't implement that by themselves. Also, always important to remember the issue of what large is: GB? TB? PB? It would be fun to allocate 1 EB of data at once and render it without loss.

2018-06-19 14:39 UTC, ricardobarroslourenco commented on papers/dharhas_pothina/dharhas_pothina.rst
> +
(same comment of citation of papers and repos made before)

2018-06-19 14:52 UTC, ricardobarroslourenco commented on papers/dharhas_pothina/dharhas_pothina.rst
> +   Visualization of drawing tools showing drawn polygons, points, paths, and boundary boxes overlaying a web tile service. :label:`drawingtools`
What is the `bounding box` bounding? It seems that the polyline is _leaking_ out of the bbox. The upper polyline seems to have two vertexes leaking out too. How are you calculating this convex hull?

An additional comment is regarding coordinate systems, and ellipsoid. How is this defined in all your images, and in the application as a whole?

2018-06-19 14:57 UTC, ricardobarroslourenco commented on papers/dharhas_pothina/dharhas_pothina.rst
> +For example, LANDSAT data can then be retrieved for the ROI as:
Cool to load Landsat data. Is it possible to render images? If so, how composites are defined? How is the data loaded? Where is it coming from? GDAL also allows this, so how it would be better/different?

2018-06-19 15:03 UTC, ricardobarroslourenco commented on papers/dharhas_pothina/dharhas_pothina.rst
> +Enhancements: Annotations
This is a very cool feature. How are these drawn assets stored? Is it possible to export them as vectorial data (ex.: shp, kml, GeoJSON, etc)? Do they have a coordinate system assigned?

2018-06-19 15:05 UTC, ricardobarroslourenco commented on papers/dharhas_pothina/dharhas_pothina.rst
> +
(same comment on the previous regrid section. Needs to clarify how this is done, because it is a central feature in such system, where datasets need to be compatibilized to a common scale for data intergration).

2018-06-19 15:11 UTC, ricardobarroslourenco commented on papers/dharhas_pothina/dharhas_pothina.rst
> +
Triangulated regular network (TIN) is a classical class of interpolator with [several works published](https://scholar.google.com/scholar?q=Triangular+irregular+networks+(TIN)&hl=pt-BR&as_sdt=0&as_vis=1&oi=scholart). How are you implementing it? Is there any improvement?

2018-06-19 15:12 UTC, ricardobarroslourenco commented on papers/dharhas_pothina/dharhas_pothina.rst
> +
Where are these examples?

2018-06-20 01:28 UTC, Roy21py commented
The abstract needs to be more clear about the primary objective of the paper: "multiple proprietary desktop tools that do not interoperate well" can be elaborated a bit more to clearly explain where the interoperability issues pop -up; eg:- performance intensive/writing parsers at each step to make multiple modules talk not each other etc. 
The objective is split between two things - building a Jupyter notebook environment vs improvement to existing python packages & creation of new packages - if improvements and creation of new packages were a by product of the main goal - explain clearly where the main motivation of the paper lies instead of focusing on the steps taken to achieve your main goal.

2018-06-21 03:19 UTC, Roy21py requested changes

2018-06-21 03:19 UTC, Roy21py commented on papers/dharhas_pothina/dharhas_pothina.rst
> +4. Data gridding: Based on the model specification, any spatially varying material properties, initial conditions and
` In addition, two new open source projects are being released for triangular mesh generation and environmental data access [cite filigree & quest]` It will be good to explain the drawbacks of other python packages that exist. Eg: -pymesh

2018-06-21 03:19 UTC, Roy21py commented on papers/dharhas_pothina/dharhas_pothina.rst
> +is run on an HPC system.
`For larger simulations, this is run on an HPC system. ` It will be good to describe "larger simulations" quantitatively. Add examples in terms of - order of magnitude of computation , time of execution, dimesionality of the datasets etc. which exceed the configuration of a local machine and need to use HPC clusters.

2018-06-21 03:19 UTC, Roy21py commented on papers/dharhas_pothina/dharhas_pothina.rst
> +available.  This linkage of
`This overall pipeline can give very high quality results, but it takes 3-6 months to build and run a model,` Can you cite a source?

2018-06-21 03:19 UTC, Roy21py commented on papers/dharhas_pothina/dharhas_pothina.rst
> +EarthSim is a website and associated GitHub repository that serves two purposes. First, it is a location to work on
`set of assumptions and architectural decisions` - Please cite a source
`much of the functionality required to implement the above workflow is already available as general-purpose 
+libraries in the Python software ecosystem` - Names of the packages and cite their source as DOI/paper if available.

2018-06-21 03:19 UTC, Roy21py commented on papers/dharhas_pothina/dharhas_pothina.rst
> +For example, LANDSAT data can then be retrieved for the ROI as:
Is there a function or module that deals with coordinate reference systems? Once you are integrating multiple data source - you might want to bring them into the same CRS for ease of computation.

2018-06-21 03:19 UTC, Roy21py commented on papers/dharhas_pothina/dharhas_pothina.rst
> +Moreover, the tools that implement the current workflow are primarily "heavyweight" approaches that encode a wide
`local machine may not have enough processing power to simulate the model in a reasonable time`. Since you are talking about in-memory efficiency of computation, it will be better to explain what is a reasonable timeframe?
Comparing traditional methods with your approach in terms of efficiency later on needs to be quantified in terms of performance improvements.

`resulting data files can be too large to be practical to transfer to the local machine for analysis` - state large in terms of file size, what is the bit rate of file transfer etc. usually if there is a linux scp command on a cluster - the file transfers are pretty fast. Are you talking about some other methods for remote file transfer?

2018-06-21 03:19 UTC, Roy21py commented on papers/dharhas_pothina/dharhas_pothina.rst
> +
`Although Earth imaging data is typically measured on a regular grid, how quickly the values change across the Earth's surface is highly non-uniform.` - Can you cite the sources?

2018-06-21 03:19 UTC, Roy21py commented on papers/dharhas_pothina/dharhas_pothina.rst
> +Enhancements: Annotations
Is there a way to integrate drawing tools with ArcGIS via arcpy?

2018-06-21 03:19 UTC, Roy21py commented on papers/dharhas_pothina/dharhas_pothina.rst
> +
Adding a diagram of the entire workflow for earthsim would be expected and reasonable. Also mentioning about the dependencies on several other packages and how Earthsim might be affected with upgrades of individual packages involved might be an issue to look into in the future. Also, for some of the example code - the execution time is pretty slow aroun ~2 mins for a cell to run in local machine. If performance improvement is your  motivation then you need to work to make the code execute faster.

2018-06-29 21:10 UTC, deniederhut commented
Hi @dharhas ! How are the revisions coming along?

2018-07-02 13:28 UTC, dharhas commented
@deniederhut 

I've been on vacation overseas. Just got back. We will start addressing the review comments this week.

2018-07-05 16:16 UTC, dharhas commented on papers/dharhas_pothina/dharhas_pothina.rst
> +   GSSHA (Gridded Surface Subsurface Hydrologic Analysis) simulators. The goal is
addressed in commit 583c033

2018-07-05 16:21 UTC, dharhas commented on papers/dharhas_pothina/dharhas_pothina.rst
> +the AdH and GSSHA simulators [cite adh & gssha]. The goal is to provide a set of flexible, high-performance tools that can easily be reconfigured and repurposed
addressed in commit 583c033

2018-07-05 16:39 UTC, dharhas commented on papers/dharhas_pothina/dharhas_pothina.rst
> +4. Data gridding: Based on the model specification, any spatially varying material properties, initial conditions and
@ricardobarroslourenco Ok I think we have a fundamental miscommunication here. EarthSim is not an end to end solution, but a library of components that are designed to work with well with each other and with the rest of the scientific python ecosystem. Using the existing desktop tools we are limited to whatever interpolation techniques exist inside those desktop tools. Adding new interpolators/functionality requires paying the software vendor to custom code them and add them into the next version. Since EarthSim is a loose library of components, you can use whatever interpolator you can find in the scientific python ecosystem or anything you decide to code yourself. The regridding tools mentioned later in the paper are targeted specifically at providing responsive interactive visualization in the browser... I'll try and clarify this in the text.

2018-07-05 19:34 UTC, dharhas commented on papers/dharhas_pothina/dharhas_pothina.rst
> +4. Data gridding: Based on the model specification, any spatially varying material properties, initial conditions and
@Roy21py there is nothing stopping someone using pymesh with the rest of the earthsim tools if it meets the users needs. That said, pymesh wraps Triangle for constrained delauney triangulation which is fairly old software (circa 2005) and does not produce very good quality meshes for hydrodynamic modeling. I'll add something to explain this.

2018-07-05 21:46 UTC, dharhas commented on papers/dharhas_pothina/dharhas_pothina.rst
> +   Visualization of drawing tools showing drawn polygons, points, paths, and boundary boxes overlaying a web tile service. :label:`drawingtools`
@ricardobarroslourenco The bounding box and polylines are unconnected, it is juts an example of the type of glyphs that can be drawn over an image and then accessed from python or vice versa.

regarding coordinate systems etc. it is whatever you defined. we are using standard python tools like cartopy etc.

2018-07-05 21:49 UTC, dharhas commented on papers/dharhas_pothina/dharhas_pothina.rst
> +EarthSim is a website and associated GitHub repository that serves two purposes. First, it is a location to work on
Mostly listed in the EarthSim description section. Not sure that it makes sense to list things like numpy, xarray or the GIS python stack etc.

2018-07-05 21:49 UTC, dharhas commented on papers/dharhas_pothina/dharhas_pothina.rst
> +is run on an HPC system.
done

2018-07-05 21:53 UTC, dharhas commented on papers/dharhas_pothina/dharhas_pothina.rst
> +
It actually isn't a central feature, the datashader regridding is specifically only for interactive visualization in the browser. For interpolation of data onto say a computational grid, the user would use whatever algorithm or library that they felt was best suited. We have one inside the Filigree package or you could use Scipy.Interpolate or anything else...

2018-07-06 13:20 UTC, dharhas commented
@deniederhut we have a code block that is bleeding into the second column, do you know how to fix the formatting on that?

2018-07-06 13:38 UTC, deniederhut commented
You'll have to do the line wrapping by hand. Code blocks will respect your
placement of newlines.

On Fri, Jul 6, 2018, 08:20 Dharhas Pothina <notifications@github.com> wrote:

> @deniederhut <https://github.com/deniederhut> we have a code block that
> is bleeding into the second column, do you know how to fix the formatting
> on that?
>
> —
> You are receiving this because you were mentioned.
>
> Reply to this email directly, view it on GitHub
> <https://github.com/scipy-conference/scipy_proceedings/pull/415#issuecomment-403032244>,
> or mute the thread
> <https://github.com/notifications/unsubscribe-auth/AGjNrPJ1gwIjWrq6VG9jFxgXp4K8uLXwks5uD2Q5gaJpZM4ULjyB>
> .
>

2018-07-06 17:22 UTC, dharhas commented
@deniederhut I think we have addressed the reviewer comments. A couple, I don't think were directly relevant since they seemed to assume that EarthSim was a standalone product whereas it is actually a loose collection of tools. I've tried to clarify that in the description. If there is anything we have missed, please let us know.

2018-07-10 02:48 UTC, deniederhut commented
Dear @Roy21py and @ricardobarroslourenco , do you feel this paper is now ready for inclusion in the proceedings?

2018-07-10 03:43 UTC, ricardobarroslourenco commented on papers/dharhas_pothina/dharhas_pothina.rst
> +The key is concept is that the local client system is will always be cabable of performing the visualization, i.e. can deliver it to the user in a browser, regardless of the dataset size.  The assump
`the local client system is will always be cabable of performing the visualization` needs to fix spelling.

2018-07-10 03:45 UTC, ricardobarroslourenco commented
@deniederhut I think that it is ready to go. @dharhas I've just put a comment on a spelling change I've caught, but I liked that you addressed all questions. Seems a very nice work :)

2018-07-10 14:15 UTC, dharhas commented on papers/dharhas_pothina/dharhas_pothina.rst
> +The key is concept is that the local client system is will always be cabable of performing the visualization, i.e. can deliver it to the user in a browser, regardless of the dataset size.  The assump
fixed.

2018-07-10 14:33 UTC, Roy21py commented
@deniederhut : Most of the comments have been addressed by @dharhas ..so I guess its good to go!

2018-07-17 22:52 UTC, merged