Paper: Add paper from Laura Noren and Anthony Suen
scipy-conference/scipy_proceedings pull request #418
Opened 2018-05-24 07:44 UTC by sideye

If you are creating this PR in order to submit a draft of your paper,
see http://procbuild.scipy.org/ for logs generated by the build
process.

See the [project readme](https://github.com/scipy-conference/scipy_proceedings#build-your-paper)
for more information.

2018-06-14 00:08 UTC, marianneke commented on papers/laura_noren_anthony_suen/laura_noren_anthony_suen.rst
> +This paper aims to understand how Jupyterhub is affecting the equity, scalability, and sustainability of data science education by providing four cases studies of how Jupyterhubs are being deployed i
> We seek to ask specifically understand
Specifically, we seek to understand

2018-06-18 15:54 UTC, dalippa requested changes
Overall the verbiage is very flowery and can be condensed by writing in active rather than passive voice. Inconsistent grammar and use of phrases; it makes the paper feel incomplete. The paper makes an audacious claim at the end that a national Jupyterhub deployment is warranted, but only does so with limited information based on a single use case (Canada). The US is much larger, has many more universities, and has a much more fractured government. The state level seems to be the right proposal, based on the scenarios provided: government sponsorship is clearly needed to handle costs and scale for the benefit of all, and the US already has state-run universities that can already collaborate to provide this service to students.

2018-06-18 15:54 UTC, dalippa commented on papers/laura_noren_anthony_suen/laura_noren_anthony_suen.rst
> +   We seek to understand the current state of equity, scalability, and sustainability of data science education infrastructure in both the U.S. and Canada. Our analysis of the technological, funding,
What kind of divergences?

2018-06-18 15:54 UTC, dalippa commented on papers/laura_noren_anthony_suen/laura_noren_anthony_suen.rst
> +We conducted over a dozen qualitative interviews with university faculty and IT staff from around the U.S. and Canada.  We also reviewed documentation found on Github. We structured our analysis by f
Any quantitative data available?

2018-06-18 15:54 UTC, dalippa commented on papers/laura_noren_anthony_suen/laura_noren_anthony_suen.rst
> +In Spring 2015, UC Berkeley became one of the first universities to adopt Jupyterhub. Initially set up for 100 students in the new Foundations of Data Science Course, the Jupyterhub instance, led by
* Who led the effort is probably not important. 
* Why does the strong relationships with cloud vendors matter? Does the lack of such relationship negatively impact how an institution can deploy the software? I would think the close relationships with the Jupyter team has more of an impact on that.

2018-06-18 15:54 UTC, dalippa commented on papers/laura_noren_anthony_suen/laura_noren_anthony_suen.rst
> +This infrastructural team is in charge of running Berkeley’s instance of Jupyterhub, “Datahub”, consists of the Dean of the new Data Science Division, one tenured teaching faculty, one full-time staf
* "infrastructure team"
* The sentence "The internal technical team.." is a bit subjective and doesn't seem to belong in this paragraph.

2018-06-18 15:54 UTC, dalippa commented on papers/laura_noren_anthony_suen/laura_noren_anthony_suen.rst
> +Despite some of this success, there are several long term issues with the Berkeley model. Replicability of UC Berkeley’s model are not easy given the team composition or industry relations for comput
* "Replicating UC Berkeley's model is..."
* You should mention providing this service at scale is easier *and* harder. That's probably the critical point that is not stated: scale enables specialization, justify budget for use, etc.

2018-06-18 15:54 UTC, dalippa commented on papers/laura_noren_anthony_suen/laura_noren_anthony_suen.rst
> +Case Study 2: Small Liberal Arts University
Universities

2018-06-18 15:54 UTC, dalippa commented on papers/laura_noren_anthony_suen/laura_noren_anthony_suen.rst
> +The team interviewed several small liberal arts colleges to see how they have fitted the data science or computer science curriculum by utilizing Jupyterhub. We learned that lack of funding, technica
* fitted?
* "to see how they utilized Jupyterhub in their curricula"
* "is Byn Mawr; its ..."

2018-06-18 15:54 UTC, dalippa commented on papers/laura_noren_anthony_suen/laura_noren_anthony_suen.rst
> +The conditions are different at well funded private universities. Their ecosystem has IT professional surrounded by other IT professionals. Even if internal IT staff have limitations, rich private un
"range from min $34 .." seems irrelevant given the previous sentence. Cost per user/student is more informative than cost per 20 users (unless 20 is the average size of classes, in which case the metric is cost per class).

2018-06-18 15:54 UTC, dalippa commented on papers/laura_noren_anthony_suen/laura_noren_anthony_suen.rst
> +Most of the classes that have deployed Jupyterhub are still relatively small with most being 12-50 students. At Harvard, JupyterHub was deployed on AWS for two classes in School of Engineering that p
One alternative that hadn't been proposed was *not* hosting Jupyterhub would be using software such as vagrant to allow users to download and self-host, rather than using centralized hosting. Had that been considered?

2018-06-18 15:54 UTC, dalippa commented on papers/laura_noren_anthony_suen/laura_noren_anthony_suen.rst
> +Wealthier universities often have multiple JupyterHub deployments. For example, Harvard Medical School runs its own Jupyterhub deployment, while its School of Engineering and Applied Science (SEAS) r
Why does having a separate deployment matter?

2018-06-18 15:54 UTC, dalippa commented on papers/laura_noren_anthony_suen/laura_noren_anthony_suen.rst
> +In 2017, an initiative in Canada led by the Pacific Institute of Mathematics and Sciences (PIMS) and Compute Canada started a new federated model for Jupyterhub that provides access to numerous insti
"time donation" - there appears to be an unprintable character there.

2018-06-18 15:54 UTC, dalippa commented on papers/laura_noren_anthony_suen/laura_noren_anthony_suen.rst
> +Conclusion  - A Path Forward to a National Jupyterhub
Why national? Why not at the state level where universities already have means of collaborating in terms of budget and such?

2018-06-18 15:54 UTC, dalippa commented on papers/laura_noren_anthony_suen/laura_noren_anthony_suen.rst
> +References
Future research/work?

2018-06-18 19:56 UTC, marianneke requested changes

2018-06-18 19:56 UTC, marianneke commented on papers/laura_noren_anthony_suen/laura_noren_anthony_suen.rst
> +The conditions are different at well funded private universities. Their ecosystem has IT professional surrounded by other IT professionals. Even if internal IT staff have limitations, rich private un
Nit: "well funded" -> "well-funded"

> bringing costs for small classes from $15 per student to $3 per student. With EC2 its cost ranges from min $34 - max $717/month for 20 users

It is unclear to me how these two sentences are related. How is the $3 per student (for the case of EC2 I presume) computed? And does this somehow follow from the information in the second sentence?

2018-06-18 19:56 UTC, marianneke commented on papers/laura_noren_anthony_suen/laura_noren_anthony_suen.rst
> +Despite this hassle-free experience, it runs into major issues in replicability and scalability. Other private universities have less experience with cloud computing or cannot rely on their universit
This comment:
> cannot rely on their university’s operating budget to support this type of teaching expense especially if classes were still relatively small (12-50 students).

seems to contradict the following comment:
> When they scale, costs will grow with each instance, especially when factoring in deployment costs of contractors.

Could you clarify how these statements fit together?

2018-06-18 19:56 UTC, marianneke commented on papers/laura_noren_anthony_suen/laura_noren_anthony_suen.rst
> +There are some potential bottlenecks such as having only one person conducting core management. Some scaling issues also exist as any institution’s Jupyterhub is not able to handle ~2 classes of stud
Since in other case studies costs per student are mentioned, it would be helpful to see this for the federated model as well.

Also, are there any differences between Canadian schools and universities and American ones that may provide other obstacles with working together?

2018-06-29 16:33 UTC, dalippa commented
@sideye any update for the paper?

2018-07-04 02:58 UTC, dalippa commented
@proceedings the author has not submitted any changes. We should reject the paper by @sideye if there are no changes made soon.

2018-07-04 03:01 UTC, sideye commented
@dalippa We are currently working on various changes on another platform. We will update the PR as soon as those are done, in the next 1 or 2 days.

2018-07-05 18:07 UTC, sideye reviewed
Changes made to most review comments.

2018-07-07 07:05 UTC, sideye commented
Final fixes complete. Addressed all reviewer comments and other language/syntactic issues.

2018-07-07 16:01 UTC, dalippa requested changes
@proceedings @sideye  this paper is not quite ready yet. This paper might not make it into the pre-conference proceedings, but if it's done by Sunday evening, we'll make sure it gets into the final copy that is published after the conference.

Overall comments:

Please remove the .DS_Store files that accidentally made it in.

More grammar mistakes. Some unexplored alternatives before suggesting "the path forward."

For next time, it would help if each paragraph were broken up into more lines so that the in-line comments would be more clear.

2018-07-07 16:01 UTC, dalippa commented on papers/laura_noren_anthony_suen/laura_noren_anthony_suen.rst
> +Data science education has experienced great demand over the past five years, with increasing numbers of undergraduate programs and majors being developed. This demand has fueled the growth of Jupyte
"which creates" => "which create"
"on demand" => "on-demand"
Avoid rhetorical questions such as "But what has been the experience been like..." and consider an alternative way to express the same thought.

2018-07-07 16:01 UTC, dalippa commented on papers/laura_noren_anthony_suen/laura_noren_anthony_suen.rst
> +This paper aims to understand how Jupyterhub is affecting the equity, scalability, and sustainability of data science education by providing four cases studies of how Jupyterhubs are being deployed i
Reframe the rhetorical questions as statements.

2018-07-07 16:01 UTC, dalippa commented on papers/laura_noren_anthony_suen/laura_noren_anthony_suen.rst
> +This infrastructure team in charge of running Berkeley’s instance of Jupyterhub, “Datahub”, consists of the Dean of the Division of Data Sciences, one tenured teaching faculty, one full-time staff me
"This" is the first reference to the infrastructure team, so "this" is dangling. Consider reworking this sentence.
"that built out workflow" => "a workflow"
What is autograding in this context?

2018-07-07 16:01 UTC, dalippa commented on papers/laura_noren_anthony_suen/laura_noren_anthony_suen.rst
> +Despite some of this success, UC Berkeley’s model faces sustainability challenges given the heavy reliance on undergraduates, graduate students and postdoc staff and donated computing credits from cl
This a lack of consistent support staff, which also implies that there is a lack of consistent expertise.

2018-07-07 16:01 UTC, dalippa commented on papers/laura_noren_anthony_suen/laura_noren_anthony_suen.rst
> +The team interviewed several small liberal arts colleges to see how they utilized Jupyter in their data science or computer science curricula. We learned that lack of funding, technical resources (re
technical resources are different than "relationship with industry".

2018-07-07 16:01 UTC, dalippa commented on papers/laura_noren_anthony_suen/laura_noren_anthony_suen.rst
> +One of the exceptions is Bryn Mawr College; its Jupyterhub deployment currently hosts and allows access to a wide range of courses. Some courses such as *Introduction to Computing* (introductory comp
Consider using footnotes instead of parentheses to keep the narrative smooth

2018-07-07 16:01 UTC, dalippa commented on papers/laura_noren_anthony_suen/laura_noren_anthony_suen.rst
> +Compared to smaller liberal arts universities, the conditions are vastly different at well-funded private universities. Their ecosystem have plentiful IT professionals, and even if internal IT staff
"ecosystem have" => "ecosystem has" or "ecosystems have"
What are the other traditional solutions?

2018-07-07 16:01 UTC, dalippa commented on papers/laura_noren_anthony_suen/laura_noren_anthony_suen.rst
> +We conducted over 10 qualitative interviews with university faculty and IT staff from around the U.S. and Canada. We also reviewed documentation found on Github and websites of 20 institutions regard
The premise here is that there is a certain economy of scale that is necessary to make Jupyterhub deployments work well. You should mention that earlier in the paper

2018-07-07 16:01 UTC, dalippa commented on papers/laura_noren_anthony_suen/laura_noren_anthony_suen.rst
> +References
Please use APA format: http://www.bibme.org/citation-guide/apa/website/

2018-07-07 16:01 UTC, dalippa commented on papers/laura_noren_anthony_suen/laura_noren_anthony_suen.rst
> +Instead of deploying and maintaining their own Jupyterhubs, other universities have found success by contracting a third party vendor to make their Jupyterhub deployment experience completely hassle
"third party" => "third-party"

2018-07-07 16:01 UTC, dalippa commented on papers/laura_noren_anthony_suen/laura_noren_anthony_suen.rst
> +Conclusion  - A Path Forward to a National Jupyterhub
Did you consider the alternative of something like a Vagrant image that could be prepared and downloaded by students to be run locally on their machine? This would be much more reproducible and would scale, since all students do have their own computing hardware.

2018-07-07 16:01 UTC, dalippa commented on papers/laura_noren_anthony_suen/laura_noren_anthony_suen.rst
> +In 2017, an initiative in Canada led by the Pacific Institute of Mathematics and Sciences (PIMS) and Compute Canada started a new federated model for Jupyterhub that provides access to numerous insti
There is a weird character right before "time donation"

2018-07-07 16:01 UTC, dalippa commented on papers/laura_noren_anthony_suen/laura_noren_anthony_suen.rst
> +While the grassroots efforts across the U.S. have sparked significant innovation in the realm of data science education infrastructure, it has also created a growing chasm of capabilities between ins
The four case studies show that some scaled solution is necessary. Nationalized Jupyterhubs might work, but there are other scalable solutions that might work better and should be explored before laying out a path forward.

2018-07-07 16:13 UTC, dalippa commented
@sideye the initial proceedings have already been posted, but the final ones won't be done until after the conference. @proceedings will work with you to make sure this can be included. Sorry about the confusion.

2018-07-07 22:19 UTC, sideye commented on papers/laura_noren_anthony_suen/laura_noren_anthony_suen.rst
> +Conclusion  - A Path Forward to a National Jupyterhub
We mentioned in the introduction: "compared to local Jupyter environments, a Jupyterhub provides many conveniences including ease of installation, compatibility between students and different courses, grading, and computing flexibility, so that users even on Chromebooks or iPads are able to run Jupyter notebooks. " We can make this more clear there.

2018-07-08 01:52 UTC, sideye commented
Edits based on comments complete. Also elaborated on potential pathways and changed citation format.

2018-07-10 02:51 UTC, deniederhut commented
Dear @marianneke do you feel this paper is now ready for inclusion in the proceedings?

2018-07-12 14:51 UTC, deniederhut commented
Unless someone chimes in requesting further changes, I'm going to mark this paper as ready for inclusion. Congrats team!

2018-07-17 18:28 UTC, sideye commented
@deniederhut thank you! When will the final proceedings become available?

2018-07-17 18:29 UTC, deniederhut commented
The only papers that are published online right now are the ones that were
ready before the deadline. We'll republish the proceedings with all of the
papers, bibfiles, and DOIs later this week.

On Tue, Jul 17, 2018, 13:28 Alan <notifications@github.com> wrote:

> @deniederhut <https://github.com/deniederhut> thank you! When will the
> final proceedings become available?
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub
> <https://github.com/scipy-conference/scipy_proceedings/pull/418#issuecomment-405681944>,
> or mute the thread
> <https://github.com/notifications/unsubscribe-auth/AGjNrBZXFWp4WrR_Bh4QO4K1c0ZBXbUiks5uHizSgaJpZM4ULuUx>
> .
>

2018-07-17 22:56 UTC, deniederhut commented
Hey! One more quick change request. You have two `.DS_Store` files committed, one of which is outside your paper's directory. Could I ask you to remove these before I merge the paper?

2018-07-17 23:53 UTC, sideye commented
@deniederhut removed.

2018-07-18 02:47 UTC, deniederhut commented
Hm... so it looks like in the process of removing one of these system caches, we've introduced another in `publisher/.DS_Store` (and we still have the one in `papers/anthony_suen_laura_noren_alan_liang_andrea_tu/.DS_Store`). Could we take one more stab at pulling these out? It may help to do something like the following:

```sh
git rm publisher/.DS_Store
git rm papers/anthony_suen_laura_noren_alan_liang_andrea_tu/.DS_Store
git commit -m "BUG: strip those darned folder caches once and for all!"
git push origin scipy_proceedings.
```

2018-07-18 04:51 UTC, sideye commented
@deniederhut Removed both .DS_STORE files. Pushed to branch 2018.

2018-07-18 23:46 UTC, merged