The Econ-ARK: Open Source Tools for Computational Economics
scipy-conference/scipy_proceedings pull request #420
Opened 2018-05-28 19:02 UTC by jackiekazil

There are a few pending minor changes that might come through relating on the following items... 
- Author's contact and institutions
- Title 
- Abstract
- Keywords

2018-06-17 18:05 UTC, FatihAkici commented
I am going to submit my review on this paper, and highly encourage the other reviewers to please share their valuable perspectives as well.

This is an exciting project and paper. I think there is a growing need in the field of economics for a centralized and standardized platform for simulating economic models. Moreover, paradigms like heterogeneous agent modeling and agent based modeling are gaining a growing popularity. Because of these reasons, the Econ-ARK project and its first framework, HARK, is very promising!

My main criticism to the paper is that it gives the impression of an incomplete or a not-carefully-written paper. There are incomplete sentences, typos, missing references, etc. Introduction can be organized better. Reading is highly impeded by the frequent usage of parentheses. I am going to present my review as in-line comments. Looking forward to your edits for further discussion.

Thank you!

2018-06-17 19:19 UTC, jackiekazil commented
Thank you @FatihAkici! Looking forward to your comments.

2018-06-17 21:19 UTC, FatihAkici requested changes
Fantastic project! Thank you for contributing this to SciPy 2018, and the world of computational economics! I left 37 comments, some are really minor typos, and some are more major. I think I'll have more questions once you guys address the existing comments. Hope I can help improve your paper. I am also planning to download and test the package, which can lead to further questions and humble recommendations.

2018-06-17 21:19 UTC, FatihAkici commented on papers/carroll_et_al/ccarroll_et_al_scipy_2018.rst
> + Heterogeneous-Agent Resources toolKit, econ-ark, computational economics, economics modeling
Typo: economic modeling

2018-06-17 21:19 UTC, FatihAkici commented on papers/carroll_et_al/ccarroll_et_al_scipy_2018.rst
> +Academic research in statistics has standardized on the use of the ‘R’ modeling language for scholarly communication, and on a suite of tools and standards of practice (the use of R-markdown, e.g.) t
1. The intro is very abrupt. Why not start with a general context regarding the importance of standardized and reproducible platforms, and then move to the example of the statistics field? Starting off with statistics is a little distracting.
2. Why the example of R markdown? I mean, Dynare is definitely a good example of a compact tool whereby you can do a lot of things easily, but if R markdown's usage in statistics is a good example of your argument, why isn't simply Jupyter's usage in economics not an equivalently good example? I think the goal Econ-ARK is trying to achieve is more than R markdown/Jupyter notebooks. Am I missing something?
3. Grammar: "allow scholars easily and transparently to exchange" -> "allow scholars to easily and transparently exchange"

2018-06-17 21:19 UTC, FatihAkici commented on papers/carroll_et_al/ccarroll_et_al_scipy_2018.rst
> +shares bought).
1. I really feel like a good reference on the summary of heterogeneous agent modeling is needed here. I've always thought that Alan Kirman's 1992 JEP paper "Whom or What Does the Representative Individual Represent?" is a phenomenal summary on the foundations of the field. This paper can enable the reader to explore the economic roots of the concepts deeper. A more recent review can be Guvenen (2011) "Macroeconomics With Heterogeneity: A Practical Guide"
2. To make this section mode philosophically delightful to the readers outside of economics, why don't you mention the concept of "emergence" in physics, i.e. "the whole is greater than the sum of its parts". This can describe the context of heterogeneous (and interacting) agents better. A book that I had enjoyed reading was: https://www.springer.com/us/book/9788847007246, and here is a more recent one: https://www.springer.com/us/book/9783319440569

2018-06-17 21:19 UTC, FatihAkici commented on papers/carroll_et_al/ccarroll_et_al_scipy_2018.rst
> +large number of ways. Models with heterogeneity among agents have
"heterogeneous in a large number of ways", such as what? What types of heterogeneity does this tool allow?

2018-06-17 21:19 UTC, FatihAkici commented on papers/carroll_et_al/ccarroll_et_al_scipy_2018.rst
> +recent work by has shown that changes in interest rates (caused, for
Missing reference: recent work by who?

2018-06-17 21:19 UTC, FatihAkici commented on papers/carroll_et_al/ccarroll_et_al_scipy_2018.rst
> +transparency, openness, and reproducibility is particularly manifest,
manifest or manifested?

2018-06-17 21:19 UTC, FatihAkici commented on papers/carroll_et_al/ccarroll_et_al_scipy_2018.rst
> +markets.
This paragraph contains long sentences with too many parentheses. Please consider going two-three passes on each sentence instead of squeezing the details into one using parentheses. For example, you can divide the third sentence as follows:

Changes in the economy can arise from the fact that economic agents being impacted differently from stimuli. For example, changes in interest rates can affect the economy in large part by reallocating income flows across different types of households rather than by causing every household to change their behavior in the same way.
In fact, recent work by [someone] shows that interest rate changes caused by monetary policy affect borrowers differently than lenders, as opposed to what a traditional RA model would suggest.

2018-06-17 21:19 UTC, FatihAkici commented on papers/carroll_et_al/ccarroll_et_al_scipy_2018.rst
> +impact over the past few years. But the literature remains small, and
I think the inclusion of the papers and books I humbly mentioned above, and more you can think of, can establish the basis for this claim.

2018-06-17 21:19 UTC, FatihAkici commented on papers/carroll_et_al/ccarroll_et_al_scipy_2018.rst
> +researchers dealing in computational methods. Researchers who must
You mean deal with, not deal in.

2018-06-17 21:19 UTC, FatihAkici commented on papers/carroll_et_al/ccarroll_et_al_scipy_2018.rst
> +researchers’ code.
The block from the sentence that starts with "Researchers who must review the" to the end of this paragraph breaks the flow of thought. This block is really about general motivation, which was already touched upon at the very beginning. Please move this block to just above the paragraph starting with "The HARK project addresses".

That way, the "In large part" paragraph and this block details the motivation of HARK. Then the "The HARK project addresses" paragraph and the "In addition to these methodological advances" sentence concludes that flow of thought by talking about HARK. "The rest of this paper will" paragraph nicely concludes the Intro section by explaining the organization of the rest of the paper.

2018-06-17 21:19 UTC, FatihAkici commented on papers/carroll_et_al/ccarroll_et_al_scipy_2018.rst
> +The sections are organized as follows: discusses the natural modular
What discusses?

2018-06-17 21:19 UTC, FatihAkici commented on papers/carroll_et_al/ccarroll_et_al_scipy_2018.rst
> +structure of the types of problems HARK solves and overviews the code
What overviews?

2018-06-17 21:19 UTC, FatihAkici commented on papers/carroll_et_al/ccarroll_et_al_scipy_2018.rst
> +structure that implements these solutions. outlines details of the core
What outlines?

2018-06-17 21:19 UTC, FatihAkici commented on papers/carroll_et_al/ccarroll_et_al_scipy_2018.rst
> +code modules used by HARK. outlines two example models that illustrate
What outlines?

2018-06-17 21:19 UTC, FatihAkici commented on papers/carroll_et_al/ccarroll_et_al_scipy_2018.rst
> +models in the HARK framework. summarizes and concludes.
What summarizes?

2018-06-17 21:19 UTC, FatihAkici commented on papers/carroll_et_al/ccarroll_et_al_scipy_2018.rst
> +heterogneous-agents rational model:
Should be rational heterogeneous-agents models.

2018-06-17 21:19 UTC, FatihAkici commented on papers/carroll_et_al/ccarroll_et_al_scipy_2018.rst
> +these models.
Please mention about the paper's organization at the end of the Intro and remove this sentence ("The rest of this section outlines the code structure HARK employs, and the next section outlines the theory behind these models.")

2018-06-17 21:19 UTC, FatihAkici commented on papers/carroll_et_al/ccarroll_et_al_scipy_2018.rst
> +attributes of the module ``HARK.utilities``. In order to calculate CRRA
This sentence (CRRAutility is called attributes of the module HARK.utilities) is unclear to me.

2018-06-17 21:19 UTC, FatihAkici commented on papers/carroll_et_al/ccarroll_et_al_scipy_2018.rst
> +the “microeconomic” and “macroeconomic” sections below come from “Model
"“microeconomic” and “macroeconomic” sections" are confusing. Are they sections? The sections are named “microeconomics” and “macroeconomics”. Do you mean the “microeconomic” and “macroeconomic” models inside the "Model Modules" section?

2018-06-17 21:19 UTC, FatihAkici commented on papers/carroll_et_al/ccarroll_et_al_scipy_2018.rst
> +coefficient of relative risk aversio n and shifter for an age-varying
Typo: "aversio n"

2018-06-17 21:19 UTC, FatihAkici commented on papers/carroll_et_al/ccarroll_et_al_scipy_2018.rst
> +associated documentation for references to the application modules.
Please refer to the link of the GitHub page here. Also, capitalize the letter H.

2018-06-17 21:19 UTC, FatihAkici commented on papers/carroll_et_al/ccarroll_et_al_scipy_2018.rst
> +that the tools now available – Python, Github, and Jupyter
Please capitalize the letter H.

2018-06-17 21:19 UTC, FatihAkici commented on papers/carroll_et_al/ccarroll_et_al_scipy_2018.rst
> +``HARKinterpolator2D``, wrapper classes that ensures interoperability
Typo: classes that ensure.

2018-06-17 21:19 UTC, FatihAkici commented on papers/carroll_et_al/ccarroll_et_al_scipy_2018.rst
> +market or other mechanisms by which agents interactions are aggregated
Typo:  Apostrophe after the s is needed - agents'.

2018-06-17 21:19 UTC, FatihAkici commented on papers/carroll_et_al/ccarroll_et_al_scipy_2018.rst
> +:math:`C_t` , discounting future utility at a constant rate; he receives
Please end the sentence after `C_t`, and have the next sentence ("Discounting future utility...") as a new sentence.

2018-06-17 21:19 UTC, FatihAkici commented on papers/carroll_et_al/ccarroll_et_al_scipy_2018.rst
> +a particular stream of labor income each period :math:`Y_t`, and knows
Please use the variables right after their descriptions, such as: "a particular stream of labor income `Y_t` each period"

2018-06-17 21:19 UTC, FatihAkici commented on papers/carroll_et_al/ccarroll_et_al_scipy_2018.rst
> +particular period :math:`C_t` out of total market resources :math:`M_t`
Please use the variable right after its description:"how much to consume `C_t`"

2018-06-17 21:19 UTC, FatihAkici commented on papers/carroll_et_al/ccarroll_et_al_scipy_2018.rst
> +An agent’s problem is thus characterized by values of :math:`\rho`,
"The agent" would be more appropriate than "an agent".

2018-06-17 21:19 UTC, FatihAkici commented on papers/carroll_et_al/ccarroll_et_al_scipy_2018.rst
> +is currently “flowing” forward, specfies that the sequence of periods
Typo: specfies

2018-06-17 21:19 UTC, FatihAkici commented on papers/carroll_et_al/ccarroll_et_al_scipy_2018.rst
> +propensity to consume out of wealth doesn’t change whether theconsumer
Typo: theconsumer

2018-06-17 21:19 UTC, FatihAkici commented on papers/carroll_et_al/ccarroll_et_al_scipy_2018.rst
> +certainty. However as agents facing uncertainty get richer, their
Comma needed after "However"

2018-06-17 21:19 UTC, FatihAkici commented on papers/carroll_et_al/ccarroll_et_al_scipy_2018.rst
> +In , the solid blue line is consumption under certainty, while the
"In ," -> In Figure 1?

2018-06-17 21:19 UTC, FatihAkici commented on papers/carroll_et_al/ccarroll_et_al_scipy_2018.rst
> +plot are extended.
Typo: are -> is

2018-06-17 21:19 UTC, FatihAkici commented on papers/carroll_et_al/ccarroll_et_al_scipy_2018.rst
> +for improvement, and the opportunities for improvement, are great.  In
Please simplify this sentence "both the need for improvement, and the opportunities for improvement, are great" -> "both the need and opportunities for improvement are great". Also, there are two spaces at the end of this sentence.

2018-06-17 21:19 UTC, FatihAkici commented on papers/carroll_et_al/ccarroll_et_al_scipy_2018.rst
> +methodological suggestions are strongly encouraged to contribute.
Can you briefly describe how to contribute? In particular, what are the future improvements on your plate, and especially which ones do you need help with the most?

2018-06-17 21:19 UTC, FatihAkici commented on papers/carroll_et_al/ccarroll_et_al_scipy_2018.rst
> +
A final note: What Python versions are supported? Please answer this question early in the paper.

2018-06-17 21:19 UTC, FatihAkici commented on papers/carroll_et_al/ccarroll_et_al_scipy_2018.rst
> +for a fuller argument).
Are there similar tools right now? I mean, in particular, in what aspects is QuantEcon (https://quantecon.org/quantecon-py) similar or different than the HARK project?

2018-06-17 22:50 UTC, mnwhite commented
Thanks for the comments, Fatih.  I'm about to board a transatlantic flight, so I will start addressing these tonight.

Coauthors: I claim the pen on our fork until 4pm European time tomorrow (10am eastern).

2018-06-20 15:52 UTC, seethakris commented
Hi authors, 

I am currently traveling with limited access to the internet. So I couldn’t create pull requests for the review. I wrote down my comments and I am pasting it here as soon as I obtained WiFi. There are probably comments that overlap with the other reviewer. 

I am not in the field of economics but I work in fields where translating ever improving statistical models described in papers into code can be tedious. Every lab has a version that is undocumented and chaotic and there are no standardized frameworks. This toolbox should be an excellent resource for the field and I applaud your efforts to create and put together this project. I hope to see the project expand over the years!

As the other reviewer noted, there are number of grammatical errors, typos, missing and unformatted references that need correction to create an improved and final version of the paper. I have them noted and will comment on them when I get better internet access, if the other reviewers /authors haven’t already caught them. I do recommend that the authors proofread the paper thoroughly. Readability can also be considerably improved.

Hope my comments makes sense, feel free to ask me questions if they don’t and I look forward to discussing more about it later in the week. 


Major comments:

1. The beginning of the introduction describing frameworks created in R seems unnecessary and so does the description of toolboxes in other scholarly fields - especially since it lacks references to such toolboxes. In fact,  Jupyter and the reference to Paul Romer’s blog post seems unnecessary in the introduction as this tool is not used in this package. Its place might be better in the conclusion for future work.  
2. The overall organization of the introduction could be improved. The narrative goes from generic to specific to generic constantly. Currently the paragraphs talk about open-source work in general, then explains economic modeling and it goes back to open source and code use in general and back to HARK.
3. Introduction: Paragraph 6 - I don’t understand the use of the term idiosyncratic agents : what is it referring to here? The use of the stock market example does not match the borrower saver example described above. I feel like something is missing there. 
4. Introduction: Paragraph 7, line 4 - heterogenous in large number of ways needs expansion.
5. The title should include HARK. The paper does not explain much about Econ-ARK. 
6. There are some jargons used in the text and either elaborating on them or cleaning them up will make readability easier. 

-  What is the difference between an heterogenous agent model and a heterogenous agent rational model?
-  What are solution and estimation methods?
-  What is CRRA utility? [It is expanded much later than when it is first used)
-  What is model misspecification? It is unclear how HARK is robust to it.

7. The authors might want to consider combining the introductions to tool, model and application modules in the HARK structure paragraph with their expansion sections for readability. It is hard to follow the connections between the two sections. 
8. The Hark Structure has nicely bulleted list of steps taken to create a heterogenous model but I am confused how this model is created in the toolkit. This might be the readability issue, while the structure is detailed in the bullet points and perhaps it is present in the text, the connectivity is lost in the way the paragraphs are arranged.

Minor comments:
1. Missing references in 

- Introduction: Paragraph 2 - Dynare toolkit needs a reference.
- Introduction: Paragraph 7, line 6.
2. What is the python version used? 
3. How can others contribute?
4. Figure1 is not referenced in the text. Though it is explained, nothing says “in Figure1..”
5. The sentences that explain how sections are organized can be written better (perhaps, with bullets?). This is the last paragraph of the Introduction

2018-06-29 21:07 UTC, deniederhut commented
Hi @jackiekazil ! How are the revisions going?

2018-07-02 14:38 UTC, mnwhite commented
One of our team members has this in process today.  Apologies for the long delay.

2018-07-02 20:12 UTC, mnwhite commented
We will likely do more edits, as a couple of items are known to be outstanding, but Nate Palmer just did a sweep of most of the comments.

2018-07-03 01:13 UTC, deniederhut commented
Dear @seethakris and @FatihAkici , do you feel this paper is now ready for inclusion in the proceedings?

2018-07-03 01:17 UTC, mnwhite commented
I just merged in another commit from Nate, following feedback from Chris on the two items that were left untouched.

Other team members will look it over for additional responses to reviewer comments (Chris, Jackie, and me... hopefully tomorrow).

2018-07-03 04:21 UTC, FatihAkici commented
Thanks for the updates @mnwhite and @jackiekazil! The manuscript is looking really good. Really cosmetic comment: The Adjemian2011 and Guvenen2011's journals need to be italicized. Also the Figure 1 has this weird name of "Fig. 1: Consumption Functions[fig:consumption-functions]", please take a look at that.

@deniederhut I'd like to re-read one more time tomorrow, and once @seethakris approves the changes too, we should green-light!

2018-07-04 21:07 UTC, seethakris commented
Thanks for the updates, and apologies I couldn't view this sooner. I am liking the structure of the paper, the introduction is looking really good now. 
Although, I am unable to find the author response to my comments? Am I missing something? I see some changes made but I am unable to verify them.

2018-07-04 22:19 UTC, npalmer-professional commented
@seethakris - apologies, I just saw your most recent comment. I will directly address your comments very soon, most likely early tomorrow morning!

2018-07-05 15:15 UTC, npalmer-professional reviewed
Addressed all of @FatihAkici comments in place and sumbitted prevous pull requests to incorporate changes from npalmer-professional branch to econ-ark branch.

2018-07-05 15:15 UTC, npalmer-professional commented on papers/carroll_et_al/ccarroll_et_al_scipy_2018.rst
> + Heterogeneous-Agent Resources toolKit, econ-ark, computational economics, economics modeling
Hi Fatih, Thanks so much for you comments! On our end I just went through and addressed nearly all of them. I hope you don't mind if I put responses to you comment here. (Many of them will be boring, like this one). -Nathan 
Reply: Fixed, thank you!

2018-07-05 15:15 UTC, npalmer-professional commented on papers/carroll_et_al/ccarroll_et_al_scipy_2018.rst
> +Academic research in statistics has standardized on the use of the ‘R’ modeling language for scholarly communication, and on a suite of tools and standards of practice (the use of R-markdown, e.g.) t
Hi Fatih, quick responses: 

1. we added a brief, more gentle intro to the paper that introduces the need at a high level. 
2. The person who wrote this portion mentioned that essentially they hope Jupyter notebooks *will* become as ubiquitous in econ as R/R-markdown in statistics. 
3. Fixed, thanks!

2018-07-05 15:15 UTC, npalmer-professional commented on papers/carroll_et_al/ccarroll_et_al_scipy_2018.rst
> +that the tools now available – Python, Github, and Jupyter
Fixed

2018-07-05 15:15 UTC, npalmer-professional commented on papers/carroll_et_al/ccarroll_et_al_scipy_2018.rst
> +for a fuller argument).
We added a brief discussion of QuantEcon and where the projects differ.

2018-07-05 15:15 UTC, npalmer-professional commented on papers/carroll_et_al/ccarroll_et_al_scipy_2018.rst
> +transparency, openness, and reproducibility is particularly manifest,
manifested, fixed

2018-07-05 15:15 UTC, npalmer-professional commented on papers/carroll_et_al/ccarroll_et_al_scipy_2018.rst
> +shares bought).
1. We've extended this discussion to include both the papers you suggested, as well as reference the 2 Handbooks of Computational Economics on this topic (vol 2, which I'm sure you're familiar with, and vol 4, which is formally out sometime this week, I believe). Those really do an excellent job of outlining a lot of text in this field. 
2. We added some more discussion on this topic briefly, via discussion of ABMs.

2018-07-05 15:15 UTC, npalmer-professional commented on papers/carroll_et_al/ccarroll_et_al_scipy_2018.rst
> +large number of ways. Models with heterogeneity among agents have
We've added a more detailed description of what we mean by the "number of ways."

2018-07-05 15:15 UTC, npalmer-professional commented on papers/carroll_et_al/ccarroll_et_al_scipy_2018.rst
> +markets.
The text has been rearranged to address this. Thanks!

2018-07-05 15:15 UTC, npalmer-professional commented on papers/carroll_et_al/ccarroll_et_al_scipy_2018.rst
> +impact over the past few years. But the literature remains small, and
I agree, thanks! We've made sure to reference the paper and discuss this briefly.

2018-07-05 15:15 UTC, npalmer-professional commented on papers/carroll_et_al/ccarroll_et_al_scipy_2018.rst
> +researchers dealing in computational methods. Researchers who must
Fixed.

2018-07-05 15:15 UTC, npalmer-professional commented on papers/carroll_et_al/ccarroll_et_al_scipy_2018.rst
> +researchers’ code.
Excellent suggestion. Done.

2018-07-05 15:15 UTC, npalmer-professional commented on papers/carroll_et_al/ccarroll_et_al_scipy_2018.rst
> +The sections are organized as follows: discusses the natural modular
It appears that the section references from the baseline tex version of this paper were somehow all dropped when we converted it to rst -- fixed now!

2018-07-05 15:15 UTC, npalmer-professional commented on papers/carroll_et_al/ccarroll_et_al_scipy_2018.rst
> +structure of the types of problems HARK solves and overviews the code
fixed

2018-07-05 15:15 UTC, npalmer-professional commented on papers/carroll_et_al/ccarroll_et_al_scipy_2018.rst
> +structure that implements these solutions. outlines details of the core
fixed

2018-07-05 15:15 UTC, npalmer-professional commented on papers/carroll_et_al/ccarroll_et_al_scipy_2018.rst
> +code modules used by HARK. outlines two example models that illustrate
fixed

2018-07-05 15:15 UTC, npalmer-professional commented on papers/carroll_et_al/ccarroll_et_al_scipy_2018.rst
> +models in the HARK framework. summarizes and concludes.
fixed

2018-07-05 15:15 UTC, npalmer-professional commented on papers/carroll_et_al/ccarroll_et_al_scipy_2018.rst
> +heterogneous-agents rational model:
Fixed.

2018-07-05 15:15 UTC, npalmer-professional commented on papers/carroll_et_al/ccarroll_et_al_scipy_2018.rst
> +these models.
Fixed.

2018-07-05 15:15 UTC, npalmer-professional commented on papers/carroll_et_al/ccarroll_et_al_scipy_2018.rst
> +attributes of the module ``HARK.utilities``. In order to calculate CRRA
Fixed (removed, text edited slightly).

2018-07-05 15:15 UTC, npalmer-professional commented on papers/carroll_et_al/ccarroll_et_al_scipy_2018.rst
> +the “microeconomic” and “macroeconomic” sections below come from “Model
I've edited and added a bit more discussion to make this more clear. One type of model is built using the other, which can be important for describing the structure of the project, but that wasn't made clear here. Hopefully the new discussion can make this a lot more clear.

2018-07-05 15:15 UTC, npalmer-professional commented on papers/carroll_et_al/ccarroll_et_al_scipy_2018.rst
> +coefficient of relative risk aversio n and shifter for an age-varying
Fixed.

2018-07-05 15:15 UTC, npalmer-professional commented on papers/carroll_et_al/ccarroll_et_al_scipy_2018.rst
> +associated documentation for references to the application modules.
Fixed and fixed.

2018-07-05 15:15 UTC, npalmer-professional commented on papers/carroll_et_al/ccarroll_et_al_scipy_2018.rst
> +``HARKinterpolator2D``, wrapper classes that ensures interoperability
Fixed.

2018-07-05 15:15 UTC, npalmer-professional commented on papers/carroll_et_al/ccarroll_et_al_scipy_2018.rst
> +market or other mechanisms by which agents interactions are aggregated
Fixed.

2018-07-05 15:15 UTC, npalmer-professional commented on papers/carroll_et_al/ccarroll_et_al_scipy_2018.rst
> +:math:`C_t` , discounting future utility at a constant rate; he receives
Fixed.

2018-07-05 15:15 UTC, npalmer-professional commented on papers/carroll_et_al/ccarroll_et_al_scipy_2018.rst
> +a particular stream of labor income each period :math:`Y_t`, and knows
Done.

2018-07-05 15:15 UTC, npalmer-professional commented on papers/carroll_et_al/ccarroll_et_al_scipy_2018.rst
> +particular period :math:`C_t` out of total market resources :math:`M_t`
Done.

2018-07-05 15:15 UTC, npalmer-professional commented on papers/carroll_et_al/ccarroll_et_al_scipy_2018.rst
> +An agent’s problem is thus characterized by values of :math:`\rho`,
Done.

2018-07-05 15:15 UTC, npalmer-professional commented on papers/carroll_et_al/ccarroll_et_al_scipy_2018.rst
> +is currently “flowing” forward, specfies that the sequence of periods
Done.

2018-07-05 15:15 UTC, npalmer-professional commented on papers/carroll_et_al/ccarroll_et_al_scipy_2018.rst
> +propensity to consume out of wealth doesn’t change whether theconsumer
Done.

2018-07-05 15:15 UTC, npalmer-professional commented on papers/carroll_et_al/ccarroll_et_al_scipy_2018.rst
> +certainty. However as agents facing uncertainty get richer, their
Done.

2018-07-05 15:15 UTC, npalmer-professional commented on papers/carroll_et_al/ccarroll_et_al_scipy_2018.rst
> +In , the solid blue line is consumption under certainty, while the
Fixed.

2018-07-05 15:15 UTC, npalmer-professional commented on papers/carroll_et_al/ccarroll_et_al_scipy_2018.rst
> +for improvement, and the opportunities for improvement, are great.  In
Done.

2018-07-05 15:15 UTC, npalmer-professional commented on papers/carroll_et_al/ccarroll_et_al_scipy_2018.rst
> +methodological suggestions are strongly encouraged to contribute.
Added.

2018-07-05 15:15 UTC, npalmer-professional commented on papers/carroll_et_al/ccarroll_et_al_scipy_2018.rst
> +
Added to the new introduction.

2018-07-05 15:17 UTC, npalmer-professional commented
Hello all, I have addessed all of @seethakris comments in my most recent pull request, here: https://github.com/econ-ark/scipy_proceedings/pull/6

For convenience, I will copy-paste @seethakris comments, with our notes on addressing each comment, here also (our notes in bold) :

___________________________________________

Major comments:

1. The beginning of the introduction describing frameworks created in R seems unnecessary and so does the description of toolboxes in other scholarly fields - especially since it lacks references to such toolboxes. In fact, Jupyter and the reference to Paul Romer’s blog post seems unnecessary in the introduction as this tool is not used in this package. Its place might be better in the conclusion for future work.
    - **We have edited the introduction to describe the use case that Econ-ARK addresses directly (instead of indirectly as you point out in your comment), and have moved the references to Jupyter and Romer blog post to the conclusion.**
2. The overall organization of the introduction could be improved. The narrative goes from generic to specific to generic constantly. Currently the paragraphs talk about open-source work in general, then explains economic modeling and it goes back to open source and code use in general and back to HARK.
    - **In response to both this comment and Fatih's comment, we have changed the introductions structure and organization.**
3. Introduction: Paragraph 6 - I don’t understand the use of the term idiosyncratic agents : what is it referring to here? The use of the stock market example does not match the borrower saver example described above. I feel like something is missing there.
    - **We have changed "idiosyncratic" -> "individual" to be more precise, and we have changed the example from the stock market to a borrower/saver example.**
4. Introduction: Paragraph 7, line 4 - heterogenous in large number of ways needs expansion.
    - **In response to both this comment and Fatih's comment, we have expanded the description here.**
5. The title should include HARK. The paper does not explain much about Econ-ARK.
    - **HARK has been included in the title.**
6. There are some jargons used in the text and either elaborating on them or cleaning them up will make readability easier.
    - What is the difference between an heterogenous agent model and a heterogenous agent rational model?
        - **The description of the steps has been updated to make this more clear**
    - What are solution and estimation methods?
        - **We have added an explicit description and reference to the solution method and estimation method to the text.** 
    - What is CRRA utility? [It is expanded much later than when it is first used)
        - **We have expanded CRRA at the point of its first use.**
    - What is model misspecification? It is unclear how HARK is robust to it.
        - **We have added a brief description of this term and a pointer to an approachable discussion of this topic.**
7. The authors might want to consider combining the introductions to tool, model and application modules in the HARK structure paragraph with their expansion sections for readability. It is hard to follow the connections between the two sections.
    - **In response to this and Fatih's comment, we have reworked this area, particularly around the "microecnomic" and "macroeconomic" discussion terms. We have added more description of how these model components work together, which we hope makes the structure more clear.**
8. The Hark Structure has nicely bulleted list of steps taken to create a heterogenous model but I am confused how this model is created in the toolkit. This might be the readability issue, while the structure is detailed in the bullet points and perhaps it is present in the text, the connectivity is lost in the way the paragraphs are arranged.
    - **We have added pointers to direct examples of the models being solved with the code, and expanded the discussion of the model solution concepturally as space allows. We hope this helps make the creation of a model more clear.**


Minor comments:

1. Missing references in
    - Introduction: Paragraph 2 - Dynare toolkit needs a reference. **Added**
    - Introduction: Paragraph 7, line 6.
2. What is the python version used? **Added to new introduction**
3. How can others contribute? **Added to conclusion**
4. Figure1 is not referenced in the text. Though it is explained, nothing says “in Figure1..”  **Figure one now referenced**
5. The sentences that explain how sections are organized can be written better (perhaps, with bullets?). This is the last paragraph of the Introduction **Edited to make more clear**

2018-07-05 15:18 UTC, mnwhite commented
I *think* all comments / requested changes from Fatih and Seetha have been addressed now; see Nate Palmer's responses on the commit I just merged in.  I think missing Seetha's review was somewhat a case of three blind men examining an elephant, but the details don't matter.

Thanks for your time in reviewing this!

2018-07-05 19:42 UTC, seethakris commented
Coool! 

Some mistakes I spotted - 
1. The second last paragraph of the conclusion is missing a P in the beginning
2. Last sentence - "getting started **with** contributing"
3. Didn't notice before that the abstract says "(articulated below)". Isn't that kinda obvious? =)
4. commas missing after However in places. Extra spaces and Extra commas in places (before citations). A quick proofread would help.
5. The subtitle in the introduction - "Relation to other sub-fields" is soooo broad for everything that follows (did you mean to remove it following rearrangement?). You might need to add another subtitle for the other HARK related paragraphs or easier, just remove the subtitle. 

Its a great revision otherwise ! I approve.

2018-07-05 19:44 UTC, mnwhite commented
Awesome.  Let me see if I can make those quick fixes right now / momentarily.  If Fatih approves as well, then we're ready to go?

2018-07-05 21:17 UTC, FatihAkici commented
Dear @mnwhite @npalmer-professional @jackiekazil since this cool project is sponsored by NumFOCUS, if you guys can please include an Acknowledgment section and mention that, I'd love to approve today! Also, please include a space in front of the first item in bibliography for consistency. Thanks!

2018-07-05 21:19 UTC, mnwhite commented
Yes, I will do that in the changes I'm making right now.

2018-07-06 01:09 UTC, mnwhite commented
I've made these changes (with one exception, see below); waiting for another team member to merge.

I don't understand this comment from Fatih: "Also, please include a space in front of the first item in bibliography for consistency."

2018-07-06 01:12 UTC, mnwhite commented
Okay, I understand now.  I'm not sure why that first entry is failing to indent.

2018-07-06 01:53 UTC, mnwhite commented
Update: My changes broke our paper, fails to build.  We are working on fixing it right now.

2018-07-06 03:04 UTC, mnwhite commented
@FatihAkici @seethakris I believe that all requested changes have been made, and the paper now successfully builds.  Thanks again for reviewing this!

2018-07-06 03:59 UTC, FatihAkici commented
@mnwhite Thanks so much, really appreciate your edits! The more conventional way of mentioning fiscal support is, to my humble knowledge, having a section titled Acknowledgments at the end of the paper, right after the Conclusion section. Do you think it is doable quickly? Please let me know if it is not. Also probably after the final fix the final paragraph of Section 3 (Model Modules), that starts with "Each subclass of Market...", started having some quotation issues that you may want to look into.

2018-07-06 04:04 UTC, mnwhite commented
I'll make these changes in a few minutes. As you can see from the commit
history, we had some formatting issues.

I will move the acknowledgements. We tried to put them as something like
the abstract, but that didn't work. We left it at the top because this sort
of note is usually on the cover page of an econ paper.

On Thu, Jul 5, 2018, 11:59 PM Fatih Akici <notifications@github.com> wrote:

> @mnwhite <https://github.com/mnwhite> Thanks so much, really appreciate
> your edits! The more conventional way of mentioning fiscal support is, to
> my humble knowledge, having a section titled Acknowledgments at the end of
> the paper, right after the Conclusion section. Do you think it is doable
> quickly? Please let me know if it is not. Also probably after the final fix
> the final paragraph of Section 3 (Model Modules), that starts with "Each
> subclass of Market...", started having some quotation issues that you may
> want to look into.
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub
> <https://github.com/scipy-conference/scipy_proceedings/pull/420#issuecomment-402918847>,
> or mute the thread
> <https://github.com/notifications/unsubscribe-auth/ANUQFdPxAWgx7Nck030OcOBBMN5pCtQVks5uDuCSgaJpZM4UQhIv>
> .
>

2018-07-06 04:30 UTC, mnwhite commented
Done.  I'm going to bed now, but I'll be up around 7am (U.S. eastern) and able to respond to requests shortly after.

2018-07-06 14:59 UTC, FatihAkici approved these changes

2018-07-06 15:02 UTC, FatihAkici commented
Thanks, @mnwhite! @proceedings, the paper is ready to be merged.

2018-07-06 15:12 UTC, deniederhut requested changes
Hey team! The paper looks great, but it loos like we're missing DOIs for the papers you are referencing. Could I ask you to add these?

2018-07-06 16:35 UTC, mnwhite commented
Nate Palmer is working on putting DOIs in now.

2018-07-06 17:29 UTC, mnwhite commented
DOIs have been added for all references that actually have a DOI.  The three references that do not have a DOI have a direct URL.

2018-07-08 13:07 UTC, jackiekazil commented
@deniederhut, because we are cutting it close, can you let us know if this is suitable?

2018-07-09 14:12 UTC, deniederhut commented
This week is a bit busy for me, but I'll take a look as soon as I can.

On Sun, Jul 8, 2018, 08:07 Jackie Kazil <notifications@github.com> wrote:

> @deniederhut <https://github.com/deniederhut>, because we are cutting it
> close, can you let us know if this is suitable?
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub
> <https://github.com/scipy-conference/scipy_proceedings/pull/420#issuecomment-403286599>,
> or mute the thread
> <https://github.com/notifications/unsubscribe-auth/AGjNrPY5lXG1NlacZOhvZjB3J6ziGE1Yks5uEgQFgaJpZM4UQhIv>
> .
>

2018-07-10 03:10 UTC, deniederhut approved these changes

2018-07-17 23:00 UTC, merged