Paper: test build system with draft
scipy-conference/scipy_proceedings pull request #454
Opened 2019-04-19 16:49 UTC by lastephey

If you are creating this PR in order to submit a draft of your paper,
see http://procbuild.scipy.org/ for logs generated by the build
process.

See the [project readme](https://github.com/scipy-conference/scipy_proceedings#build-your-paper)
for more information.

2019-05-03 16:44 UTC, TahiriNadia commented
Missing references?

2019-05-03 16:53 UTC, lastephey commented
Yes, the references are currently broken. I am using a .bib file for the references but clearly something is not working. (I have looked at the examples from 2018 and am trying to replicate what they did.) My bib file is automatically generated by Zoterro so I'm not sure if that's an issue. I'd appreciate any help or additional documentation you could send to help me fix this. Thank you.

2019-05-03 17:41 UTC, deniederhut commented
Hm... my first suggestion would be to run `make clean` before building to make sure an old .aux file is not preventing the bibfile from being included. The next step is to look at the .log file to see if there is an error.

2019-05-03 18:44 UTC, lastephey commented
Thank you for the suggestions. I found the problem: the underscore in my bib name (I changed it from scipy_bib to scipybib and now it works). I'll push another test draft.

2019-05-22 05:24 UTC, lastephey commented
Hi @deniederhut and @TahiriNadia, I noticed that my most recent changes are not showing up in the build system. It is still showing an older version (commit 0f1f760 instead of 
f4cf05a). Is there something I should do? I have tried building a few times with the most recent commit and can't seem to get it to refresh. Thank you.

2019-05-22 06:09 UTC, TahiriNadia commented
Hi @lastephey the system takes time to build (update) the paper. Now, your last modification was updated on the system. You need to check this last version. Thank you

2019-05-22 12:41 UTC, deniederhut commented
procbuild -- for better or worse -- will only rebuild a paper if the last build is more than five minutes old. Is the newer version showing up now?

2019-05-22 13:58 UTC, lastephey commented
Hi @TahiriNadia and @deniederhut, thanks for your help. I waited longer than 5 minutes before trying to build again. It is still showing the older version. The newer version builds without any problems on my laptop.

2019-05-22 16:10 UTC, deniederhut commented
Hm I will need to take a look

2019-05-22 16:19 UTC, lastephey commented
Thank you. For some reason the build system just seems to be one commit behind. I guess I could try to push a dummy commit to force it to update if you think that's a good option.

2019-05-22 22:26 UTC, deniederhut commented
Might have been related to this GitHub outage -- https://www.githubstatus.com/incidents/nf4gcjtcsqdb

Is the paper on procbuild now the correct one?

2019-05-22 22:43 UTC, lastephey commented
Yes it's correct now. Thanks for your help!

2019-05-23 03:25 UTC, lastephey commented
This paper is ready to be submitted. Thanks for your help.

2019-06-10 22:08 UTC, tschaume requested changes
Excellent paper and already in great shape! I thoroughly enjoyed reading it :) There are only a few minor suggestions to consider which I added as inline comments.

As an additional minor formatting suggestion, I think it would help readability if all functions were encapsulated in backticks.

2019-06-10 22:08 UTC, tschaume commented on papers/laurie_stephey/stephey_thomas_bailey.rst
> +configuration will be very valuable to DESI.
Maybe add details/examples how this flexibility will be valuable?

2019-06-10 22:08 UTC, tschaume commented on papers/laurie_stephey/stephey_thomas_bailey.rst
> +runtime for a single frame was decreased from 4000 s to 525 s for KNL, from 862
be consistent with usage of `seconds` or `s`

2019-06-10 22:08 UTC, tschaume commented on papers/laurie_stephey/stephey_thomas_bailey.rst
> +amount of processing.  Higher specific throughput translates indicates more effective
two verbs "translates" or "indicates"?

2019-06-10 22:08 UTC, tschaume commented on papers/laurie_stephey/stephey_thomas_bailey.rst
> +a single exposure is still a relatively small test because DESI expects to
maybe split in two sentences for readability?

2019-06-10 22:08 UTC, tschaume commented on papers/laurie_stephey/stephey_thomas_bailey.rst
> +7-10x in raw processing speed.
👍

2019-06-10 22:08 UTC, tschaume commented on papers/laurie_stephey/stephey_thomas_bailey.rst
> +instructive. First, they demonstrate the restructuring-based optimizations were
"**that** the restructuring-based optimizations were more valuable **than** the JIT based optimizations"

2019-06-10 22:08 UTC, tschaume commented on papers/laurie_stephey/stephey_thomas_bailey.rst
> +   \end{table*}
Maybe visualize this table as a graph? The conclusions in the main text are harder to deduce from the table format.

2019-06-10 22:08 UTC, tschaume commented on papers/laurie_stephey/stephey_thomas_bailey.rst
> +between bundles (although this has been addressed now in the subbundle
move parenthesis to footnote?

2019-06-10 22:08 UTC, tschaume commented on papers/laurie_stephey/stephey_thomas_bailey.rst
> +take the entire MPI job with it. (This is not an issue in Dask, in which dead
move parenthesis to footnote?

2019-06-10 22:08 UTC, tschaume commented on papers/laurie_stephey/stephey_thomas_bailey.rst
> +and collect their results via a concurrent futures API. (It should be noted
Don't think parentheses are required here. It's an important note to the SLURM-savvy reader.

2019-06-10 22:08 UTC, tschaume commented on papers/laurie_stephey/stephey_thomas_bailey.rst
> +time to completion.
I think it can't be overstated here how much of a benefit this 80% reduction in computing time will have on data reprocessing! This will likely happen more often than once a year because "mistakes happen".

2019-06-11 15:59 UTC, lastephey commented
@tschaume Hi Patrick, thank you for your review and your comments. We will work on incorporating them.

2019-06-11 16:08 UTC, lastephey commented on papers/laurie_stephey/stephey_thomas_bailey.rst
> +runtime for a single frame was decreased from 4000 s to 525 s for KNL, from 862
changed from s to seconds for consistency

2019-06-11 16:10 UTC, lastephey commented on papers/laurie_stephey/stephey_thomas_bailey.rst
> +amount of processing.  Higher specific throughput translates indicates more effective
removed translates

2019-06-11 16:50 UTC, lastephey commented on papers/laurie_stephey/stephey_thomas_bailey.rst
> +configuration will be very valuable to DESI.
added some more details here

also surrounded functions with code formatting

2019-06-11 16:57 UTC, lastephey commented on papers/laurie_stephey/stephey_thomas_bailey.rst
> +a single exposure is still a relatively small test because DESI expects to
split into two sentences

2019-06-11 16:59 UTC, lastephey commented on papers/laurie_stephey/stephey_thomas_bailey.rst
> +instructive. First, they demonstrate the restructuring-based optimizations were
nice catch, fixed

2019-06-11 17:10 UTC, lastephey commented on papers/laurie_stephey/stephey_thomas_bailey.rst
> +and collect their results via a concurrent futures API. (It should be noted
parentheses removed

2019-06-11 17:12 UTC, lastephey commented on papers/laurie_stephey/stephey_thomas_bailey.rst
> +time to completion.
added (at least) in the text

2019-06-11 17:18 UTC, lastephey commented on papers/laurie_stephey/stephey_thomas_bailey.rst
> +   \end{table*}
replaced table with line graph, now figure 9

2019-06-11 17:36 UTC, lastephey commented on papers/laurie_stephey/stephey_thomas_bailey.rst
> +between bundles (although this has been addressed now in the subbundle
moved to footnote

2019-06-11 17:41 UTC, lastephey commented on papers/laurie_stephey/stephey_thomas_bailey.rst
> +take the entire MPI job with it. (This is not an issue in Dask, in which dead
is this duplicated? or do you mean that I should move the second parenthetical (this is not an issue in Dask...) also to a footnote?

2019-06-11 17:45 UTC, tschaume commented on papers/laurie_stephey/stephey_thomas_bailey.rst
> +take the entire MPI job with it. (This is not an issue in Dask, in which dead
Meant to move the second parenthetical to a footnote, too. Sorry.

2019-06-11 17:52 UTC, lastephey commented on papers/laurie_stephey/stephey_thomas_bailey.rst
> +take the entire MPI job with it. (This is not an issue in Dask, in which dead
no problem, thank you for clarifying. 

parenthetical moved to footnote

2019-06-12 13:40 UTC, deniederhut commented
Hi @lastephey ! It looks like one of your reviewers (Zach Golkhou) misunderstood their instructions and sent the review to me personally via email. Here it is:

> Dear SciPy 2019 Proceedings Chairs, Hi -
> Here is my initial review of the paper entitled “Optimizing Python-Based Spectroscopic Data Processing on NERSC Supercomputers” written by Laurie A. Stephey, Rollin C. Thomas, Stephen J. Bailey.
> The authors present a case study of optimizing a Python-based cosmology data processing pipeline designed to run in parallel on thousands of cores using supercomputers at the National Energy Research Scientific Computing Center (NERSC). They aim to improve the performance of DESI’s spectroscopic data processing pipeline at NERSC while satisfying their productivity requirement that the software remain in Python. At the end based on their implemented strategy, they are able to achieve a factor of 5-7 X speedup. They employed profiling tools such as “cProfile” and “gprof2dot” to find out bottlenecks in the DESI spectroscopic pipeline and implemented modules Numba and JIT to overcome the issue with time-consuming processes in the code.
> In general, this paper is easily readable, understandable and the presented strategy makes sense and can be verifiable.
> Throughout the paper, a few tasks have been mentioned to be done in the future and I would like to be removed from the paper since we can not verify or see their effects in the optimization process, here. Also, the authors investigated the possibility of replacing MPI with Dask which I like the idea. I would like to know if they have also considered replacing MPI implementation with Apache Spark (PySpark) as a Standard Industry tool for data parallelism which is an open-source distributed general-purpose cluster-computing framework.
> Best
> Zach

2019-06-12 17:22 UTC, lastephey commented
Thank you @deniederhut 

Thank you for your review and comments @zgolkhou

We will add some details about why we thought Spark was not a good option for this project (it would require a more extreme refactor than Dask and preclude smaller-scale users from running these routines on their workstations, for example). 

We would like to respectfully push back against the recommendation to remove any mention of work that is in progress/future work. Of course the comment that we have no data from current/future work is correct. However, we still believe these efforts are worth mentioning. We can re-frame the discussion to say that we still have several known issues (poor load balancing, job inflexibility) and are taking steps to correct them.

2019-06-13 00:25 UTC, deniederhut commented
> However, we still believe these efforts are worth mentioning. We can re-frame the discussion to say that we still have several known issues (poor load balancing, job inflexibility) and are taking steps to correct them.

I would agree. It's common (and I believe also wise) for papers to end with current limitations and future directions.

2019-06-16 22:46 UTC, zgolkhou commented
I agree that probably SPARK would make things more complicated for this specific project.

I also agree that it would certainly be useful for papers to end with current limitations and future directions. I didn’t see such structure for future work in this paper and I wanted to point it out. Reframing future work would help readers to appreciate better what has been accomplished in this project.  Thanks. Zach

2019-06-18 02:33 UTC, deniederhut commented
Hi @tschaume and @zgolkhou ! Do you feel this paper is ready for inclusion?

2019-06-18 17:14 UTC, tschaume commented
> Hi @tschaume and @zgolkhou ! Do you feel this paper is ready for inclusion?

yes, I think it's ready to go.

2019-06-18 21:35 UTC, zgolkhou commented
> > Hi @tschaume and @zgolkhou ! Do you feel this paper is ready for inclusion?
> 
> yes, I think it's ready to go.

Sure. I agree.

2019-06-19 23:38 UTC, deniederhut commented
Awesome! @lastephey it looks like a couple of the citations are missing DOIs. Could I ask you to add them before we merge this PR?

2019-06-20 01:03 UTC, lastephey commented
Hi @deniederhut, sorry about that! I just added some DOIs. If I missed any of them please let me know.

2019-06-21 11:46 UTC, deniederhut commented
Thanks! This looks good to me!

2019-07-03 13:15 UTC, merged