submission of Solving Polynomial Systems with phcpy
scipy-conference/scipy_proceedings pull request #461
Opened 2019-05-20 01:18 UTC by janverschelde

With this PR we submit a draft of our paper
Solving Polynomial Systems with phcpy

Sincerely Yours,
 Jan Verschelde

2019-06-13 00:24 UTC, deniederhut commented
Hi @janverschelde ! We had fewer reviewers complete a review for your paper than we were expecting, so I'll be stepping in. Please expect comments from me some time in the next handful of days 🙂.

2019-06-15 00:53 UTC, deniederhut requested changes
Excellent paper! I left a few inline suggestions about spelling errors and sentence structure. One general comment I have is that there is a lot of field-specific terminology here. You won't have room in this paper to explain all of them, but it could be helpful to readers if you provide descriptions for some of the more critical concepts in your library.

2019-06-15 00:53 UTC, deniederhut commented on make_paper.sh
> +python3 publisher/build_paper.py $DIR
Please don't modify files outside of your paper's directory

2019-06-15 00:53 UTC, deniederhut commented on papers/jan_verschelde/phcpy.rst
> +The meaning of *solving* evolved from computing approximations to
Some commas might might this a bit easier to parse, e.g. "from computing approximations, to all isolated solutions, to the numerical"

2019-06-15 00:53 UTC, deniederhut commented on papers/jan_verschelde/phcpy.rst
> +not only the isolated solutions, but also representations for all
"also the representations"

2019-06-15 00:53 UTC, deniederhut commented on papers/jan_verschelde/phcpy.rst
> +accelerated with graphics processing units [VY15]_.
Ooh nice 😄

2019-06-15 00:53 UTC, deniederhut commented on papers/jan_verschelde/phcpy.rst
> +mention its application to their computations.
:tada:

2019-06-15 00:53 UTC, deniederhut commented on papers/jan_verschelde/phcpy.rst
> +The mission of phcpy is to bring polynomial homotopy continuation
It might be a good idea to provide a short explanation of homotopy continuation and how it works, for readers who are not familiar.

2019-06-15 00:53 UTC, deniederhut commented on papers/jan_verschelde/phcpy.rst
> +phcpy wraps the shared object files of a compiled PHCpack,
Geez you wrote the interfaces by hand. This isn't crucial for the paper, but I am curious why you didn't use something like swig or cython.

2019-06-15 00:53 UTC, deniederhut commented on papers/jan_verschelde/phcpy.rst
> +Learning a new API is daunting enough without also being a crash course in algebraic geometry. Therefore, the user's manual of phcpy [PHCPY]_ begins with a tutorial section using only the blackbox so
Yeah I took a quick trip through your documentation and it is quite extensive 👍

2019-06-15 00:53 UTC, deniederhut commented on papers/jan_verschelde/phcpy.rst
> +Our input is a list of polynomials in several variables.
Is there a reason you aren't using numpy for passing numeric data back and forth?

2019-06-15 00:53 UTC, deniederhut commented on papers/jan_verschelde/phcpy.rst
> +the continuity of the solution set in function of changing
I'm having a hard time parsing this sentence -- are we missing an article somewhere?

2019-06-15 00:53 UTC, deniederhut commented on papers/jan_verschelde/phcpy.rst
> +   |  dd   | 42.41 |  5.07 |  3.88 |
Am I reading this correctly that the double-double task takes just as long on 8 cores as it does on a single core?

2019-06-15 00:53 UTC, deniederhut commented on papers/jan_verschelde/phcpy.rst
> +``phcpy`` was used to find edge lengths with maximally many real embeddings, exploiting the flexibility of being able to specify their starting system. This sped up their algorithm by perturbing from
"by perturbing the solutions"

2019-06-15 00:53 UTC, deniederhut commented on papers/jan_verschelde/phcpy.rst
> +Parameter hopotopies were used by Gross et. al [GHR16]_ to perform model selection on a mammalian phosphorylation pathway (to distinguish whether the kinase acts processively, i.e. adding more than o
"Parameter homotopies"

2019-06-15 22:16 UTC, cbcunc requested changes
Please see the inline comments.

I ran all the code examples including the Apollonius problem (from a GItHub clone) on your JupyterHub server. The JupyterHub server with p was a big help.

Overall, this is a very good paper, if a little all over the map. I will be glad to approve it when the inline comments are addressed.

2019-06-15 22:16 UTC, cbcunc commented on papers/jan_verschelde/phcpy.rst
> +was recently parallelized for phcy [Ver18]_.
s/phcy/phcpy/

2019-06-15 22:16 UTC, cbcunc commented on papers/jan_verschelde/phcpy.rst
> +phcpy wraps the shared object files of a compiled PHCpack,
It looks very odd to have a lowercase first letter in a paragrph. Most style guides would say capilitalize even if it a usually lowecase name. I am not dogmatic about this, so do what you feel is right.

2019-06-15 22:16 UTC, cbcunc commented on papers/jan_verschelde/phcpy.rst
> +Version 1.4 of Bertini (released under a too restrictive license)
Leave out the editorializing of "too restrictive." That is a subjective judgment dependent on the desired purpose. At the most you could say "more restrictive." But it adds nothing as the current version of Bertini is GPL3. Some dependencies of Bertini 2 are more restrictive than GPL3, but then the argument gets complicated. I would advocate eliminating the parenthetical phrase entirely as it's not germane to your topic.

2019-06-15 22:16 UTC, cbcunc commented on papers/jan_verschelde/phcpy.rst
> +MySLQdb does the management of user data, including a) names and encrypted passwords, b) generic, random folder names to store data files, and c) file names with polynomial systems they have solved.
Maybe provide references for MySQLdb. At first I thought is was a misspelling of MySQL db as I had not previously heard of this package. smtplib is standard library, so it's not as important to have a reference for that, although it doesn't hurt if you decide to.

2019-06-15 22:16 UTC, cbcunc commented on papers/jan_verschelde/phcpy.rst
> +As of the middle of May 2019, our web server has 146 user accounts, each having access to our new JupyterHub instance.
JupyterHub itself may also bear a reference, even though you have a reference for how you use JupyterHub with phcpy.

2019-06-15 22:16 UTC, cbcunc commented on papers/jan_verschelde/phcpy.rst
> +For the user administration, we refreshed our first web interface. A custom JupyterHub Authenticator connects to the existing MySQL database, and triggers a SystemdSpawner that isolates the actions o
Lose the comma after "database."

2019-06-15 22:16 UTC, cbcunc commented on papers/jan_verschelde/phcpy.rst
> +The account management prompts by e-mail were hooked to new Tornado Handler instances, which perform account registration and activation on the database, as well as password recovery and reset. Each
s/Handler/RequestHandler/
Also, "pathway?" That's not a Jupyter or Tornado term as I know it. Reword or clarify.
Also, "their" and "its" refer to what? Reword or clarify.

2019-06-15 22:16 UTC, cbcunc commented on papers/jan_verschelde/phcpy.rst
> +The first solution of the given trinomial can be read off as (0.48613… + 0.0i, 0.34258… - 0.0i), where the imaginary part of x_0 is exactly zero, and that of y_0 negligibly small. Programmatically, t
s/be read off as/be read as/

2019-06-15 22:16 UTC, cbcunc commented on papers/jan_verschelde/phcpy.rst
> +One consequence of the Jupyter notebook's rich output is the possibility of rich input, as explored through ipywidgets and interactive plotting libraries. The combination of rich input with fast nume
Possobly provide a reference for ipywidgets.

2019-06-15 22:16 UTC, cbcunc commented on papers/jan_verschelde/phcpy.rst
> +This system of 3 nonlinear constraints in 5 parameters for each of 8 possible tangent circles (some of which have imaginary position or radius in certain configurations), which we solved interactivel
This first sentence is incomplete. Essentially it says, "This system, which we solved." The sentences needs a verb and possibly a subject.

2019-06-15 22:16 UTC, cbcunc commented on papers/jan_verschelde/phcpy.rst
> +This family is called the homotopy.  Homotopy methods take a polynomial
s/system on input/system as input/

2019-06-15 22:16 UTC, cbcunc commented on papers/jan_verschelde/phcpy.rst
> +   tuple of Newton polytopes associated to the system is a sharp upper
s/associated to/associated with/

2019-06-15 22:16 UTC, cbcunc commented on papers/jan_verschelde/phcpy.rst
> +1. *dense polynomial systems*
All three of these classes of polynomial systems need references to substantiate the claims made about them.

2019-06-15 22:16 UTC, cbcunc commented on papers/jan_verschelde/phcpy.rst
> +The online SymPy documentation uses the cyclic 4-roots problem
Reference for SymPy or SymPy documentation.

2019-06-15 22:16 UTC, cbcunc commented on papers/jan_verschelde/phcpy.rst
> +.. code-block:: python
Is it possible to get the code block to appear before the two tables? I don't see anything in your RST to indicate that it shouldn't. But that's not how it's being rendered.

2019-06-15 22:16 UTC, cbcunc commented on papers/jan_verschelde/phcpy.rst
> +The interpolation allows to estimate running times for a number
"allows to estimate" is unclear. How about simply "The interpolation estimates running times..." or something like that.

2019-06-15 22:16 UTC, cbcunc commented on papers/jan_verschelde/phcpy.rst
> +One could interpolate between the sizes of working precision
s/One/one/

2019-06-15 22:16 UTC, cbcunc commented on papers/jan_verschelde/phcpy.rst
> +The conformations of proteins [LML14]_, molecules [EM99]_, and robotic mechanisms (discussed further below) can be studied by counting and classifying unique mechanisms, i.e. real embeddings of graph
"(which we gloss in this section)" is an unnecessary apology which diverts the narrative to first person. It's an eight page paper discussing a complex topic. It's inevitable that many things in the paper are glossed over. No apology is needed.

2019-06-15 22:16 UTC, cbcunc commented on papers/jan_verschelde/phcpy.rst
> +Consider a graph :math:`G` whose edges each have a given length. A graph embedding is a function that maps the vertices of :math:`G` into :math:`D`-dimensional Euclidean space (especially :math:`D` =
"The number of unique mechanisms is thus a function of :math:`G` and :math:`d`, and an upper bound over :math:`d` (for which it isn't infinite) and :math:`G` with k vertices (yielding lower bounds for graphs with :math:`n \geq k` vertices) can be computed."

That is a serious run-on sentence I had to read several times to parse. Separate into at least two sentences and then parenthetical phrases will be also be unnecessary depending on whether "it" refers to the upper bound or the spatial dimension. That is, please rephrase without parenthetical phrases making use of unclear indefinite pronouns: 

"The number of unique mechanisms is thus a function of :math:`G` and :math:`d`. An upper bound over :math:`d` (for which it isn't infinite) and :math:`G` with k vertices (yielding lower bounds for graphs with :math:`n \geq k` vertices) can be computed.

2019-06-15 22:16 UTC, cbcunc commented on papers/jan_verschelde/phcpy.rst
> +Consider a graph :math:`G` whose edges each have a given length. A graph embedding is a function that maps the vertices of :math:`G` into :math:`D`-dimensional Euclidean space (especially :math:`D` =
Please give a reference for the Cayley-Menger matrix.

2019-06-15 22:16 UTC, cbcunc commented on papers/jan_verschelde/phcpy.rst
> +Bartzos et. al implemented, using ``phcpy``, a constructive method yielding all 7-vertex minimally rigid graphs in 3D space (the smallest open case) and certain 8-vertex cases previously uncounted. A
If you are using a Latin abbreviation not in this list, https://en.wikipedia.org/wiki/List_of_Latin_abbreviations, then you should probably not be abbreviating whatever it is you are trying to say. If "s.t." is not a Latin abbreviation, it is unclear what it is and it should be explicit. I would guess "subject to," but that is ungrammatical in the sentence.

2019-06-15 22:16 UTC, cbcunc commented on papers/jan_verschelde/phcpy.rst
> +In fact, many iterations of sampling have to be performed if the wrong number of real embeddings is found; in each case, a different subgraph is selected based on a heuristic implemented by ``DBSCAN`
"In fact" is, in fact, almost always unnecessary. Also, 

Try "by the DBSCAN class of scikit-learn."

"E.g." needs to be surrounded by commas if it is in the middle of a sentence and looks awkward. Just use ", for instance," instead.

2019-06-15 22:16 UTC, cbcunc commented on papers/jan_verschelde/phcpy.rst
> +Parameter hopotopies were used by Gross et. al [GHR16]_ to perform model selection on a mammalian phosphorylation pathway (to distinguish whether the kinase acts processively, i.e. adding more than o
"et al." no period on the "et," It is a complete Latin word. Period on the "al." It is an abbreviation of _alia_.

Please split the unbalanced run-on sentence into two sentences:

Their analysis validated experimental work showing processivity in vivo. And they obtained >50x speedup over non-parameter homotopies (for running times in minutes, not hours) on systems tracking 20 paths.

2019-06-15 22:16 UTC, cbcunc commented on papers/jan_verschelde/phcpy.rst
> +Polynomial homotopy continuation has also been adapted to the field of chemical engineering to locate critical points of multicomponent mixtures [SWM16]_, i.e. temperature and pressure satisfying a m
Comma after "i.e."

2019-06-15 22:16 UTC, cbcunc commented on papers/jan_verschelde/phcpy.rst
> +* Mobility analysis - degrees of freedom of a mechanism (sometimes exceptional), sometimes specific to certain configurations (e.g. gimbal lock);
Comma after "e.g."

2019-06-15 22:16 UTC, cbcunc commented on papers/jan_verschelde/phcpy.rst
> +We have discussed an application of numerical methods to counting unique instances of rigid-body mechanisms. In fact, kinematics and numerical algebraic geometry have a close historical relationship.
Comma before "e.g."

2019-06-15 22:16 UTC, cbcunc commented on papers/jan_verschelde/phcpy.rst
> +Whether a model biological system is multistationary or oscillatory, and whether this depends on its rate constants, are all properties of its steady-state locus. Following the survey of Gross et. al
"et al." instead of "et. al"

2019-06-15 22:16 UTC, cbcunc commented on papers/jan_verschelde/phcpy.rst
> +Whether a model biological system is multistationary or oscillatory, and whether this depends on its rate constants, are all properties of its steady-state locus. Following the survey of Gross et. al
"one might investigate: determine" concatenantes two transitive verbs. Reword, possibly substituting the gerund form of the second verbs in the list:

determining
evaluating
describing

2019-06-15 22:16 UTC, cbcunc commented on papers/jan_verschelde/phcpy.rst
> +   This paper explores the development of phcpy, a scripting interface for    PHCpack, over the past five years.  One result is the availability of phcpy   through a JupyterHub featuring Python2, Pyt
"through a JupyterHub **server**"

2019-06-19 23:39 UTC, deniederhut commented
@janverschelde feel free to @ us when you feel this submission is ready for re-review 😄

2019-06-20 19:28 UTC, janverschelde commented on papers/jan_verschelde/phcpy.rst
> +The mission of phcpy is to bring polynomial homotopy continuation
Added a second paragraph in the introduction to explain homotopy continuation very briefly.

2019-06-20 19:30 UTC, janverschelde commented on papers/jan_verschelde/phcpy.rst
> +Our input is a list of polynomials in several variables.
The symbolic format for multivariate polynomials is more common and the parsing of the strings is done directly by the code in PHCpack.

2019-06-20 19:30 UTC, janverschelde commented on papers/jan_verschelde/phcpy.rst
> +   |  dd   | 42.41 |  5.07 |  3.88 |
Thanks for catching that error!

2019-06-20 19:33 UTC, janverschelde commented on papers/jan_verschelde/phcpy.rst
> +.. code-block:: python
Yes, the insertion of a "..raw:: latex" did the trick.

2019-06-20 19:36 UTC, janverschelde commented
Thanks for the detailed comments and suggestions.

We addressed most of them, I think.

The submission may indeed be ready for re-review.


________________________________
From: Dillon Niederhut <notifications@github.com>
Sent: Wednesday, June 19, 2019 6:39 PM
To: scipy-conference/scipy_proceedings
Cc: Verschelde, Jan; Mention
Subject: Re: [scipy-conference/scipy_proceedings] Paper: Solving Polynomial Systems with phcpy (#461)


@janverschelde<https://github.com/janverschelde> feel free to @ us when you feel this submission is ready for re-review 😄

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub<https://github.com/scipy-conference/scipy_proceedings/pull/461?email_source=notifications&email_token=AA53KBI4AMGLX4QCDQCB2FDP3K7THA5CNFSM4HN52372YY3PNVWWK3TUL52HS4DFVREXG43VMVBW63LNMVXHJKTDN5WW2ZLOORPWSZGODYDSNGI#issuecomment-503785113>, or mute the thread<https://github.com/notifications/unsubscribe-auth/AA53KBNDMTLMRSNAWUUUMELP3K7THANCNFSM4HN5237Q>.

2019-06-20 19:46 UTC, JazzTap commented
I'm currently revising the abstract, besides clarifying a couple other sentences. Be ready in an hour.

2019-06-21 00:34 UTC, JazzTap commented on papers/jan_verschelde/phcpy.rst
> +Whether a model biological system is multistationary or oscillatory, and whether this depends on its rate constants, are all properties of its steady-state locus. Following the survey of Gross et. al
Removed first transitive verb. (s/investigate/seek to/)

2019-06-21 00:37 UTC, JazzTap commented on papers/jan_verschelde/phcpy.rst
> +The account management prompts by e-mail were hooked to new Tornado Handler instances, which perform account registration and activation on the database, as well as password recovery and reset. Each
Applied. Reworded to 'route'. Addressed the 'HTML forms' directly.

2019-06-21 00:48 UTC, JazzTap commented on papers/jan_verschelde/phcpy.rst
> +This system of 3 nonlinear constraints in 5 parameters for each of 8 possible tangent circles (some of which have imaginary position or radius in certain configurations), which we solved interactivel
Intervening parentheses moved outside of problematic sentence. Revised paragraph.

2019-06-21 00:50 UTC, JazzTap commented on papers/jan_verschelde/phcpy.rst
> +1. *dense polynomial systems*
Added by @janverschelde.

2019-06-21 00:51 UTC, JazzTap commented on papers/jan_verschelde/phcpy.rst
> +The interpolation allows to estimate running times for a number
s/allows to/allows us to/

2019-06-21 00:53 UTC, JazzTap commented on papers/jan_verschelde/phcpy.rst
> +The conformations of proteins [LML14]_, molecules [EM99]_, and robotic mechanisms (discussed further below) can be studied by counting and classifying unique mechanisms, i.e. real embeddings of graph
Removed, 'per ...' left as attribution for the following discussion.

2019-06-21 00:59 UTC, JazzTap commented on papers/jan_verschelde/phcpy.rst
> +Consider a graph :math:`G` whose edges each have a given length. A graph embedding is a function that maps the vertices of :math:`G` into :math:`D`-dimensional Euclidean space (especially :math:`D` =
Cited a survey of euclidian distance geometry w/ relevant discussion (which shares a citation with Bartzos et al. of a textbook in the field, at that point).

2019-06-21 01:00 UTC, JazzTap commented on papers/jan_verschelde/phcpy.rst
> +Bartzos et. al implemented, using ``phcpy``, a constructive method yielding all 7-vertex minimally rigid graphs in 3D space (the smallest open case) and certain 8-vertex cases previously uncounted. A
Changed to 'such that'

2019-06-21 01:01 UTC, JazzTap commented on papers/jan_verschelde/phcpy.rst
> +In fact, many iterations of sampling have to be performed if the wrong number of real embeddings is found; in each case, a different subgraph is selected based on a heuristic implemented by ``DBSCAN`
Applied

2019-06-21 01:03 UTC, JazzTap commented on papers/jan_verschelde/phcpy.rst
> +Parameter hopotopies were used by Gross et. al [GHR16]_ to perform model selection on a mammalian phosphorylation pathway (to distinguish whether the kinase acts processively, i.e. adding more than o
Applied throughout. Split.

2019-06-21 01:04 UTC, JazzTap commented on papers/jan_verschelde/phcpy.rst
> +MySLQdb does the management of user data, including a) names and encrypted passwords, b) generic, random folder names to store data files, and c) file names with polynomial systems they have solved.
Package references added throughout, except smtplib.

2019-06-21 01:04 UTC, JazzTap commented on papers/jan_verschelde/phcpy.rst
> +Version 1.4 of Bertini (released under a too restrictive license)
Has been dropped

2019-06-22 01:11 UTC, deniederhut commented on papers/jan_verschelde/phcpy.rst
> +Parameter hopotopies were used by Gross et al. [GHR16]_ to perform model selection on a mammalian phosphorylation pathway, determining whether the kinase acts processively (i.e. adding more than one
I still think this was mean to read "homotopies".

2019-06-22 21:54 UTC, deniederhut commented
Thanks for all the edits! 

@cbcunc were there any other changes you wanted to see before approving the paper?

2019-06-22 21:55 UTC, deniederhut approved these changes

2019-06-27 20:28 UTC, cbcunc approved these changes
Thank you for your revisions.

2019-06-28 02:21 UTC, deniederhut commented
Woohoo! Thanks everyone!

2019-07-03 13:16 UTC, merged