Paper: An intelligent shopping list
scipy-conference/scipy_proceedings pull request #465
Opened 2019-05-21 04:45 UTC by TahiriNadia

If you are creating this PR in order to submit a draft of your paper,
see http://procbuild.scipy.org/ for logs generated by the build
process.

See the [project readme](https://github.com/scipy-conference/scipy_proceedings#build-your-paper)
for more information.

2019-06-13 00:22 UTC, deniederhut commented
Hi @TahiriNadia ! It looks like none of our reviewers were able to complete their reviews for your paper by the deadline, so I'll be stepping in to complete a review myself. Please expect comments from me some time in the next handful of days 🙂.

2019-06-13 00:50 UTC, stargaser reviewed
Thank you @TahiriNadia for this interesting paper! I have reviewed it and I think it is mostly in good shape. I have made many comments inline, many of which are wording or grammar suggestions; some others are more substantial.

In particular, I suggest to move Figure 5 (graphical illustration) to the start of the model section, and to relate the NNMF piece more clearly to the text describing the model -- preferably with a NNMF subsection.

I look forward to iterating with you on the comments.

2019-06-13 00:50 UTC, stargaser commented on papers/nadia_tahiri/nadia_tahiri.rst
> +The principal component analysis (linear and polynomial PCA [Jol11]_) was first computed to visualize the initial data
```suggestion
A principal component analysis (linear and polynomial PCA [Jol11]_) was first computed to visualize the initial data  
```

2019-06-13 00:50 UTC, stargaser commented on papers/nadia_tahiri/nadia_tahiri.rst
> +Firstly, by using the grocery shopping database in Canada `MyGroceryTour` [#]_ (see Figure :ref:`MyGroceryTour`),
```suggestion
First, by using the grocery shopping database in Canada `MyGroceryTour` [#]_ (see Figure :ref:`MyGroceryTour`), 
```

2019-06-13 00:50 UTC, stargaser commented on papers/nadia_tahiri/nadia_tahiri.rst
> +Secondly, we developed a statistical model to predict which products previously purchased will be
```suggestion
Second, we developed a statistical model to predict which products previously purchased will be 
```

2019-06-13 00:50 UTC, stargaser commented on papers/nadia_tahiri/nadia_tahiri.rst
> +based on dynamic programming, was used to achieve objectives (i),
```suggestion
based on dynamic programming, was used to achieve objective (i), 
```

2019-06-13 00:50 UTC, stargaser commented on papers/nadia_tahiri/nadia_tahiri.rst
> +where these products are to be purchased. We also calculated the consumer's optimal weekly commute
```suggestion
where these products are to be purchased. We also calculate the consumer's optimal weekly commute 
```
(present tense since this is part of what the shopping list does)

2019-06-13 00:50 UTC, stargaser commented on papers/nadia_tahiri/nadia_tahiri.rst
> +was used to achieve objectives (ii). Those implementations are going to create a significant interest to consumers.
```suggestion
were used to achieve objective (ii). Those implementations can provide significant benefits to consumers.
```

2019-06-13 00:50 UTC, stargaser commented on papers/nadia_tahiri/nadia_tahiri.rst
> +to predict whether or not the given product will be included in the grocery list of the consumer.
```suggestion
predict whether or not the given product will be included in the grocery list of the consumer. 
```

2019-06-13 00:50 UTC, stargaser commented on papers/nadia_tahiri/nadia_tahiri.rst
> +in the next shop :math:`_{t+1}` of :math:`u`
Does "shop" mean a "shopping trip" or a "purchase"? Not a store, right? 

(after reading the rest of the paper, I think it means "store"?)

2019-06-13 00:50 UTC, stargaser commented on papers/nadia_tahiri/nadia_tahiri.rst
> +- **user\_id**: user number. We take care of anonymized all data set. :math:`user\_id \in \underbrace{\{1 \cdots 374\}}_{\text{reals}} \cup \underbrace{\{375 \cdots 1374\}}_{\text{generated}}`
```suggestion
- **user\_id**: user number. We took care to anonymize the dataset. :math:`user\_id \in \underbrace{\{1 \cdots 374\}}_{\text{reals}} \cup \underbrace{\{375 \cdots 1374\}}_{\text{generated}}`
```
The generated user_ids are not sequential? or was 1 to 375 randomly mapped to 1000 to 1374?

2019-06-13 00:50 UTC, stargaser commented on papers/nadia_tahiri/nadia_tahiri.rst
> +Finally, we increased the `special` feature. This variable is based on the composition of the baskets, choosing a special random proportional to the Boltzmann distribution [AAR+18]_.
a "special random distribution", or a "special random variable drawn from a Boltzmann distribution"?

2019-06-13 00:50 UTC, stargaser commented on papers/nadia_tahiri/nadia_tahiri.rst
> +We observed that the baskets generated to follow the same distribution that original basket in term of the basket size
```suggestion
We observed that the sizes of the generated baskets follow the same distribution as the original basket sizes
```

2019-06-13 00:50 UTC, stargaser commented on papers/nadia_tahiri/nadia_tahiri.rst
> +.. code-block:: bash
I recommend to leave out the bash script contents as many of the lines are not that interesting. You might write in text that the preprocessing had a 48 hour limit and used 32 GB of memory. Also, I tried to look up what `#!SBATCH` does (the exclamation point) and as far as I can tell, it would comment out that line.

2019-06-13 00:50 UTC, stargaser commented on papers/nadia_tahiri/nadia_tahiri.rst
> +the product data, and the department data. The bash script has given as follow:
Here and elsewhere, I am unclear what "department" means. Is it a department in each grocery store (like "produce department", "meat department")?

2019-06-13 00:50 UTC, stargaser commented on papers/nadia_tahiri/nadia_tahiri.rst
> +Preprocessing dataset
In this section, I really want to know how much data was being processed! How many Gigabytes or in whatever appropriate unit?

2019-06-13 00:50 UTC, stargaser commented on papers/nadia_tahiri/nadia_tahiri.rst
> +A combined RNN and CNN trained to predict the probability that a user will order a product at each timestep.
```suggestion
A combined RNN and CNN was trained to predict the probability that a user will order a product at each timestep. 
```

2019-06-13 00:50 UTC, stargaser commented on papers/nadia_tahiri/nadia_tahiri.rst
> +In this section, we described the workflow (see Figure :ref:`workflow`) and the models we used.
```suggestion
In this section, we describe the workflow (see Figure :ref:`workflow`) and the models we used.
```

I really would like to see this figure before reading the text of this section. I would like this figure to be Figure 4 and to appear before the LSTM diagram.

2019-06-13 00:50 UTC, stargaser commented on papers/nadia_tahiri/nadia_tahiri.rst
> +The last layer is a fully-connected layer which makes the classification.
This last layer must mean the CNN, yes? What classification is it making? In other words, what are the classes?

2019-06-13 00:50 UTC, stargaser commented on papers/nadia_tahiri/nadia_tahiri.rst
> +
In the caption, please explain C, H, and X. In the interior of the box, do f_t, C-bar_t, I_t, O_t correspond in some way to forget, learn, remember and use?

2019-06-13 00:50 UTC, stargaser commented on papers/nadia_tahiri/nadia_tahiri.rst
> +Overall characteristics of the neuron networks which used in this project are described as follow:
```suggestion
Overall characteristics of the neural networks which are used in this project are described as follows:
```
Is the `rnn` function from TensorFlow? Or another package? Please indicate.

2019-06-13 00:50 UTC, stargaser commented on papers/nadia_tahiri/nadia_tahiri.rst
> +regression with a variety of response distributions including Gaussian [Car03]_, Bernoulli [CMW16]_, Poisson [PJ73]_, and Laplace [Tay19].
```suggestion
regression with a variety of response distributions including Gaussian [Car03]_, Bernoulli [CMW16]_, Poisson [PJ73]_, and Laplace [Tay19]_. 
```

2019-06-13 00:50 UTC, stargaser commented on papers/nadia_tahiri/nadia_tahiri.rst
> +Moreover, in this study, we denote frequently missing data in the history grocery list by the user, that is why this technique is more adapted.
Does "denote frequently missing data" mean that you are flagging, or masking, missing data in the user's purchase history?

2019-06-13 00:50 UTC, stargaser commented on papers/nadia_tahiri/nadia_tahiri.rst
> +The final model has two neuron networks and a GBT classifier.
```suggestion
The final model has two neural networks and a GBT classifier.
```

2019-06-13 00:50 UTC, stargaser commented on papers/nadia_tahiri/nadia_tahiri.rst
> +Once trained, it was used to predict in real time what would be the basket consumer, based on the history of purchases and current promotions in neighboring stores.
```suggestion
Once trained, it was used to predict in real time what would be the consumer's basket, based on their history of purchases and current promotions in neighboring stores.
```

2019-06-13 00:50 UTC, stargaser commented on papers/nadia_tahiri/nadia_tahiri.rst
> +Based on the validation loss function, we eliminated the LSTM Rays and LSTM model size (see Figure :ref:`lstm`).
How do the LSTM Rays and LSTM model size relate to the elements in Figure 4?

2019-06-13 00:50 UTC, stargaser commented on papers/nadia_tahiri/nadia_tahiri.rst
> +        NNMF & Users & $1,374 \times 25$\\
NNMF appears only in Table 2 and Figure 5. I did not find a definition for it. How does it relate to the RNN + CNN described in the text?

2019-06-13 00:50 UTC, stargaser commented on papers/nadia_tahiri/nadia_tahiri.rst
> +where True Positive :math:`(TP)=\mathbb{I}[\lfloor p(i)\rceil=1]\mathbb{I}[R_i=1]`, False Negative :math:`(FN)=\mathbb{I}[\lfloor p(i)\rceil=0]\mathbb{I}[R_i=1]`, False Positive :math:`(FP)=\mathbb{I
```suggestion
where True Positive :math:`(TP)=\mathbb{I}[\lfloor p(i)\rceil=1]\mathbb{I}[R_i=1]`, False Negative :math:`(FN)=\mathbb{I}[\lfloor p(i)\rceil=0]\mathbb{I}[R_i=1]`, False Positive :math:`(FP)=\mathbb{I}[\lfloor p(i)\rceil=1]\mathbb{I}[R_i=0]` and :math:`R_i=1` if the product :math:`i` was bought in the basket :math:`p'\in \mathcal{P}`, else :math:`0`.\\
```

2019-06-13 00:50 UTC, stargaser commented on papers/nadia_tahiri/nadia_tahiri.rst
> +.. figure:: figures/workflow.png
Please move this figure to the start of the Models section, where it is first referenced.

2019-06-13 00:50 UTC, stargaser commented on papers/nadia_tahiri/nadia_tahiri.rst
> +   The first level of the model used LSTM and NNMF.
Please define NNMF (probably in the text). Also, it seems to me that the Models section should have a subheading NNMF, in parallel with the subheadings LSTM and GBT.

2019-06-13 00:50 UTC, stargaser commented on papers/nadia_tahiri/nadia_tahiri.rst
> +==========
```suggestion
-------------
```
I think Statistics should be a bold heading?

2019-06-13 00:50 UTC, stargaser commented on papers/nadia_tahiri/nadia_tahiri.rst
> +The *F-measure* or :math:`F_1` precise the classifier, as well as how robust it is (does not miss a significant number of instances).
F1 is the classifier, is what is meant?  And a value of 1 would mean the product would definitely be purchased (100% probability)?

2019-06-13 00:50 UTC, stargaser commented on papers/nadia_tahiri/nadia_tahiri.rst
> +We examined these six evaluation metrics on this study.
After reading this sentence, I really want to see a table! which is Table 3, I see. Maybe tell the reader these are in the next section?

2019-06-13 00:50 UTC, stargaser commented on papers/nadia_tahiri/nadia_tahiri.rst
> +Weightings are needed to give the model more robust.
```suggestion
Weightings are needed to make the model more robust. 
```

2019-06-13 00:50 UTC, stargaser commented on papers/nadia_tahiri/nadia_tahiri.rst
> +The results show clearly the cluster of Pasta sauce with Pasta group.
Pasta group means, Mexican Style Rice & Pasta, plus Whole Grain Thin Spaghetti Pasta? Why is Penne Pasta so far from this group? Do the Categories in Table 2 include a Pasta Group?

2019-06-13 00:50 UTC, stargaser commented on papers/nadia_tahiri/nadia_tahiri.rst
> +For the first group, they are products includes on restriction regime
```suggestion
For the first group, they are products included on restriction regimes 
```

2019-06-13 00:50 UTC, stargaser commented on papers/nadia_tahiri/nadia_tahiri.rst
> +   Distribution of :math:`F_1` measures against stores (a) and rebates (b). :label:`violon`
```suggestion
   Distribution of :math:`F_1` measures against rebates (a) and stores (b). :label:`violon`
```
In the figure, it would be helpful for the x-axis of the right-hand plot to be "Store" instead of "shop".

2019-06-13 00:50 UTC, stargaser commented on papers/nadia_tahiri/nadia_tahiri.rst
> +In future work, we plan to predict the next grocery shop and to include the product quantities on the basket proposed to the user.
```suggestion
In future work, we plan to predict the grocery store that will visited next, and to include the product quantities in the basket proposed to the user. 
```

2019-06-13 00:50 UTC, stargaser commented on papers/nadia_tahiri/nadia_tahiri.rst
> +We suggest also to ponderate the algorithm with the distance between shop and user home coordinates to the promotion rate.
I can't recall seeing the word "ponderate" before! Perhaps, "We will investigate weighting the algorithm by distance between the user's home and the store, and the promotion rate." ?

2019-06-13 00:50 UTC, stargaser commented on papers/nadia_tahiri/nadia_tahiri.rst
> +:math:`F_1` statistics maximization algorithm [NCLC12]_,
The definition of the F1 statistic is provided in the end of the Statistics section. It might help readers to mention that it is define later.

```suggestion
An :math:`F_1` statistics maximization algorithm [NCLC12]_, 
```

2019-06-13 00:50 UTC, stargaser commented on papers/nadia_tahiri/nadia_tahiri.rst
> +Since the real dataset was not enough to complete correctly the project, we increased it.
I would really like to know how much of the dataset is simulated.

2019-06-13 00:50 UTC, stargaser commented on papers/nadia_tahiri/nadia_tahiri.rst
> +.. figure:: figures/order_frequency.png
Are these histograms normalized in some way? If the blue and red histograms represent the same numbers, it would imply the number of synthesized baskets are about the same as the number original baskets.

2019-06-13 02:33 UTC, TahiriNadia commented
@deniederhut Thank you for your input!
@stargaser Thank you David! I'm looking into each of your remarks and will be incorporating them

2019-06-14 04:52 UTC, deniederhut requested changes
Great paper! I look forward to having your algorithms organize my shopping lists 😄 . I think I may have missed the part where you talk about predicting which store people will purchase from -- it's a bit past my bedtime right now. Was this somewhere in the methods?

2019-06-14 04:52 UTC, deniederhut commented on papers/nadia_tahiri/nadia_tahiri.rst
> +during an inter-category grocery were weekly specials and promotions, and about 30% of consumers
What is an inter-category grocery?

2019-06-14 04:52 UTC, deniederhut commented on papers/nadia_tahiri/nadia_tahiri.rst
> +known preferences and specials available in local stores.
"known preferences and specials" -> "known preferences, and specials"

I'm big on the oxford comma 😅

2019-06-14 04:52 UTC, deniederhut commented on papers/nadia_tahiri/nadia_tahiri.rst
> +The application of efficient partitioning methods, such as K-means [Jai10]_ and X-means [PM+00]_,
Did you consider hdbscan?

2019-06-14 04:52 UTC, deniederhut commented on papers/nadia_tahiri/nadia_tahiri.rst
> +- **category\_id**: unique category number for a product. :math:`category\_id \in \{1 \cdots 24\}`
Who determines product categories?

2019-06-14 04:52 UTC, deniederhut commented on papers/nadia_tahiri/nadia_tahiri.rst
> +We found that there are 3 consumer profiles see [WJ03]_, [WJ02]_, and [TNTK16]_.
How did you discover this? Was this from the clustering step? If so, which algorithm did you use for scoring the coherence of each cluster?

2019-06-14 04:52 UTC, deniederhut commented on papers/nadia_tahiri/nadia_tahiri.rst
> +Since the real dataset was not enough to complete correctly the project, we increased it.
Was it not large enough? Not complete enough? Also "complete correctly" -> "correctly complete".

2019-06-14 04:52 UTC, deniederhut commented on papers/nadia_tahiri/nadia_tahiri.rst
> +The data is divided into 2 groups (training and validation) which comprise 90% and 10% of the data respectively.
Does your test set include any of the simulated data?

2019-06-14 04:52 UTC, deniederhut commented on papers/nadia_tahiri/nadia_tahiri.rst
> +- **TP** is True Positive, i.e. the number of positively labeled data, which have been classified as `Positive`, correct class,
We probably don't need to worry about defining these in the paper

2019-06-14 04:52 UTC, deniederhut commented on papers/nadia_tahiri/nadia_tahiri.rst
> +The authors thank PyCon Canada for their valuable comments on this project. This work used
🇨🇦

2019-06-17 20:15 UTC, cbcunc requested changes

2019-06-17 20:15 UTC, cbcunc commented on papers/nadia_tahiri/nTahiriSciPy.bib
> +@misc{fazliu2017utforskande,
This reference is incomplete.

2019-06-17 20:15 UTC, cbcunc commented on papers/nadia_tahiri/nadia_tahiri.rst
> +References
All citations that have DOIs should include those DOIs in the paper's references section.

2019-06-18 15:38 UTC, TahiriNadia commented on papers/nadia_tahiri/nadia_tahiri.rst
> +where these products are to be purchased. We also calculated the consumer's optimal weekly commute
exactly, fixed

2019-06-18 15:41 UTC, TahiriNadia commented on papers/nadia_tahiri/nadia_tahiri.rst
> +was used to achieve objectives (ii). Those implementations are going to create a significant interest to consumers.
thanks for this suggestion

2019-06-18 15:44 UTC, TahiriNadia commented on papers/nadia_tahiri/nadia_tahiri.rst
> +A combined RNN and CNN trained to predict the probability that a user will order a product at each timestep.
nice catch, fixed

2019-06-18 15:51 UTC, TahiriNadia commented on papers/nadia_tahiri/nadia_tahiri.rst
> +We observed that the baskets generated to follow the same distribution that original basket in term of the basket size
Fixed!

2019-06-18 15:53 UTC, TahiriNadia commented on papers/nadia_tahiri/nadia_tahiri.rst
> +regression with a variety of response distributions including Gaussian [Car03]_, Bernoulli [CMW16]_, Poisson [PJ73]_, and Laplace [Tay19].
Good catch! Fixed!

2019-06-18 15:54 UTC, TahiriNadia commented on papers/nadia_tahiri/nadia_tahiri.rst
> +Once trained, it was used to predict in real time what would be the basket consumer, based on the history of purchases and current promotions in neighboring stores.
Fixed!

2019-06-18 15:55 UTC, TahiriNadia commented on papers/nadia_tahiri/nadia_tahiri.rst
> +where True Positive :math:`(TP)=\mathbb{I}[\lfloor p(i)\rceil=1]\mathbb{I}[R_i=1]`, False Negative :math:`(FN)=\mathbb{I}[\lfloor p(i)\rceil=0]\mathbb{I}[R_i=1]`, False Positive :math:`(FP)=\mathbb{I
Nice catch, fixed!

2019-06-18 15:58 UTC, TahiriNadia commented on papers/nadia_tahiri/nadia_tahiri.rst
> +For the first group, they are products includes on restriction regime
Fixed!

2019-06-18 16:04 UTC, TahiriNadia commented on papers/nadia_tahiri/nadia_tahiri.rst
> +Weightings are needed to give the model more robust.
Nice suggestion! Fixed.

2019-06-18 17:07 UTC, TahiriNadia commented on papers/nadia_tahiri/nadia_tahiri.rst
> +known preferences and specials available in local stores.
Oxford comma is great. Fixed in https://github.com/scipy-conference/scipy_proceedings/pull/465/commits/1c3d95c55a6078f3a5541d8c18fdc010959908c5

2019-06-19 15:05 UTC, TahiriNadia commented on papers/nadia_tahiri/nadia_tahiri.rst
> +References
Great! I've added DOIs here https://github.com/scipy-conference/scipy_proceedings/pull/465/commits/500b30a4d51442448795faf4f3a56c254c60cdaf

2019-06-19 15:38 UTC, TahiriNadia commented on papers/nadia_tahiri/nTahiriSciPy.bib
> +@misc{fazliu2017utforskande,
Good catch! Not easy to find this compete for reference, so I decide to switch to another one see https://github.com/scipy-conference/scipy_proceedings/pull/465/commits/9142d15c31e8e2d73bb0749da495aeafefb3506f

2019-06-19 18:59 UTC, TahiriNadia commented on papers/nadia_tahiri/nadia_tahiri.rst
> +==========
I've changed Statistics to the bold heading

2019-06-19 23:49 UTC, deniederhut commented
@TahiriNadia feel free to @ us when you feel this is ready for re-review 😄

2019-06-22 00:20 UTC, TahiriNadia commented
> Thank you @TahiriNadia for this interesting paper! I have reviewed it and I think it is mostly in good shape. I have made many comments inline, many of which are wording or grammar suggestions; some others are more substantial.
> 
> In particular, I suggest to move Figure 5 (graphical illustration) to the start of the model section, and to relate the NNMF piece more clearly to the text describing the model -- preferably with a NNMF subsection.
> 
> I look forward to iterating with you on the comments.

Thank you for your comments. Following your recommendations, we moved Figure 5 to the start of the model section and related the NNMF method to the text describing the model.

2019-06-22 00:21 UTC, TahiriNadia commented on papers/nadia_tahiri/nadia_tahiri.rst
> +in the next shop :math:`_{t+1}` of :math:`u`
“shop” in this case means “shopping basket”. This correction was applied.

2019-06-22 00:22 UTC, TahiriNadia commented on papers/nadia_tahiri/nadia_tahiri.rst
> +- **user\_id**: user number. We take care of anonymized all data set. :math:`user\_id \in \underbrace{\{1 \cdots 374\}}_{\text{reals}} \cup \underbrace{\{375 \cdots 1374\}}_{\text{generated}}`
The IDs (`user\_id`) are not sequentially. In total, we have 1374 users. Among them, we have 374 real users and 1000 users whose behavior was generated following the distribution of real users (see Figure 3) and the consumer statistics available in the report by Statistics Canada (2017).

2019-06-22 00:23 UTC, TahiriNadia commented on papers/nadia_tahiri/nadia_tahiri.rst
> +Finally, we increased the `special` feature. This variable is based on the composition of the baskets, choosing a special random proportional to the Boltzmann distribution [AAR+18]_.
Sorry about this confusion. The following correction has been applied: “a special random variable drawn from a Boltzmann distribution”.

2019-06-22 00:23 UTC, TahiriNadia commented on papers/nadia_tahiri/nadia_tahiri.rst
> +.. code-block:: bash
Done! We removed the bash script and added: “The preprocessing had a 48 hour limit and used 32 GB of the RAM memory.” Exactly, #!SBATCH does (the exclamation point) comment out that line. By default, the server allows 32 GB of memory.

2019-06-22 00:24 UTC, TahiriNadia commented on papers/nadia_tahiri/nadia_tahiri.rst
> +the product data, and the department data. The bash script has given as follow:
Sorry for this confusion, by “department” we denoted the product category. We have 24 product categories such as breakfast, frozen foods, pasta, fruits, and vegetables (see http://mygrocerytour.com/#!/categories). We changed the word “department” by “product category” throughout the paper.

2019-06-22 00:25 UTC, TahiriNadia commented on papers/nadia_tahiri/nadia_tahiri.rst
> +Preprocessing dataset
Initially, the data were stocked in CSV files at a MySQL database taking 1.4 GB. Then, the data were stocked in a dataframe.

2019-06-22 00:26 UTC, TahiriNadia commented on papers/nadia_tahiri/nadia_tahiri.rst
> +In this section, we described the workflow (see Figure :ref:`workflow`) and the models we used.
Fixed! We switched Figures 4 and 5.

2019-06-22 00:27 UTC, TahiriNadia commented on papers/nadia_tahiri/nadia_tahiri.rst
> +The last layer is a fully-connected layer which makes the classification.
The last layer includes a gradient tree boosting (GTB) classifier used to predict the products that will be bought during the current week. The classifier contains two classes: 0 (i.e. will be bought) and 1 (i.e. won’t be bought).

2019-06-22 00:32 UTC, TahiriNadia commented on papers/nadia_tahiri/nadia_tahiri.rst
> +Overall characteristics of the neuron networks which used in this project are described as follow:
The Tensorflow package was used to implement our `rnn` class which takes into account the features described in the previous section. Fixed!

2019-06-22 00:33 UTC, TahiriNadia commented on papers/nadia_tahiri/nadia_tahiri.rst
> +.. figure:: figures/workflow.png
Fixed! We switched Figures 4 and 5.

2019-06-22 00:35 UTC, TahiriNadia commented on papers/nadia_tahiri/nadia_tahiri.rst
> +   The first level of the model used LSTM and NNMF.
Fixed! Added subheading NNMF.

2019-06-22 00:35 UTC, TahiriNadia commented on papers/nadia_tahiri/nadia_tahiri.rst
> +The *F-measure* or :math:`F_1` precise the classifier, as well as how robust it is (does not miss a significant number of instances).
Corrected: “The *F-measure* or :math:`F_1` is a well-known and reliable evaluation metric.” The value of 1 would the mean perfect accuracy, i.e., the product would definitely be purchased.

2019-06-22 00:36 UTC, TahiriNadia commented on papers/nadia_tahiri/nadia_tahiri.rst
> +We examined these six evaluation metrics on this study.
Corrected by adding: “We examined these five evaluation metrics in our study (see the next section for the results of the F1 measure).”

2019-06-22 00:36 UTC, TahiriNadia commented on papers/nadia_tahiri/nadia_tahiri.rst
> +   Distribution of :math:`F_1` measures against stores (a) and rebates (b). :label:`violon`
Corrected.

2019-06-22 00:37 UTC, TahiriNadia commented on papers/nadia_tahiri/nadia_tahiri.rst
> +We suggest also to ponderate the algorithm with the distance between shop and user home coordinates to the promotion rate.
Great, thank you for this recommendation. We added the following sentence to the revised manuscript: We will investigate weighting the algorithm by the distance between the user's home and the store, and the promotion rate.

2019-06-22 00:38 UTC, TahiriNadia commented on papers/nadia_tahiri/nadia_tahiri.rst
> +Since the real dataset was not enough to complete correctly the project, we increased it.
Fixed!

2019-06-22 00:40 UTC, TahiriNadia commented on papers/nadia_tahiri/nadia_tahiri.rst
> +Since the real dataset was not enough to complete correctly the project, we increased it.
In fact, 72.73% of the data were simulated (1000 out of 1374 baskets were simulated).

2019-06-22 00:41 UTC, TahiriNadia commented on papers/nadia_tahiri/nadia_tahiri.rst
> +.. figure:: figures/order_frequency.png
Exactly, these histograms confirm that the simulated data follow the same distribution that the real data.

2019-06-22 00:42 UTC, TahiriNadia commented
> Great paper! I look forward to having your algorithms organize my shopping lists 😄 . I think I may have missed the part where you talk about predicting which store people will purchase from -- it's a bit past my bedtime right now. Was this somewhere in the methods?

Thank you. In this first version of the algorithm, the prediction of the store people will purchase from was not yet performed, but on the perspective, we plan to investigate this question.

2019-06-22 00:43 UTC, TahiriNadia commented on papers/nadia_tahiri/nadia_tahiri.rst
> +during an inter-category grocery were weekly specials and promotions, and about 30% of consumers
Sorry, it’s a mistake. I change “inter-category” by “a grocery shopping”.

2019-06-22 00:44 UTC, TahiriNadia commented on papers/nadia_tahiri/nadia_tahiri.rst
> +The application of efficient partitioning methods, such as K-means [Jai10]_ and X-means [PM+00]_,
It seems to be a good idea to consider hdbscan. Thank you. In this study, we did not use it. In the future, we plan to compare more ensemble-based techniques, including hdbscan.

2019-06-22 01:10 UTC, TahiriNadia commented on papers/nadia_tahiri/nadia_tahiri.rst
> +- **category\_id**: unique category number for a product. :math:`category\_id \in \{1 \cdots 24\}`
The product categories were determined with the purchase histories is the current version of our model does not allow a new product to be bought by a user (i.e., every user can only buy products that were in at least one of its previous shopping baskets).

2019-06-22 01:11 UTC, TahiriNadia commented on papers/nadia_tahiri/nadia_tahiri.rst
> +We found that there are 3 consumer profiles see [WJ03]_, [WJ02]_, and [TNTK16]_.
These values were obtained from Statistics Canada. Moreover, the distributions used our study follow these statistics.

2019-06-22 01:11 UTC, TahiriNadia commented on papers/nadia_tahiri/nadia_tahiri.rst
> +Since the real dataset was not enough to complete correctly the project, we increased it.
The original dataset was composed of 375 users. It may be not enough to apply an appropriate machine learning method.

2019-06-22 01:12 UTC, TahiriNadia commented on papers/nadia_tahiri/nadia_tahiri.rst
> +The data is divided into 2 groups (training and validation) which comprise 90% and 10% of the data respectively.
After simulating the dataset, the strategy used was to merge real and simulated data and then split them into two groups (training and validation datasets). The test set was composed of the real and simulated dataset.

2019-06-22 21:39 UTC, TahiriNadia commented on papers/nadia_tahiri/nadia_tahiri.rst
> +- **TP** is True Positive, i.e. the number of positively labeled data, which have been classified as `Positive`, correct class,
Following your recommendations, we removed the definition. See https://github.com/scipy-conference/scipy_proceedings/pull/465/commits/92091095e4d5353b6c93d58e9ed028938f29adcb

2019-06-23 15:47 UTC, TahiriNadia commented on papers/nadia_tahiri/nadia_tahiri.rst
> +
Fixed! See https://github.com/TahiriNadia/scipy_proceedings/commit/25fe61103f2cc97ffa0cc09c7fbcd8e7bb77f5bf

2019-06-23 16:09 UTC, TahiriNadia commented on papers/nadia_tahiri/nadia_tahiri.rst
> +Based on the validation loss function, we eliminated the LSTM Rays and LSTM model size (see Figure :ref:`lstm`).
LSTM Rays and LSTM model size is not related to the elements in Figure 4, but only to the LSTM structure used. The new formulation is as follows: “Based on the validation loss function, we removed the following parameters from our input data: 1) LSTM Category and 2) LSTM size of the next basket.

2019-06-23 16:10 UTC, TahiriNadia commented on papers/nadia_tahiri/nadia_tahiri.rst
> +Based on the validation loss function, we eliminated the LSTM Rays and LSTM model size (see Figure :ref:`lstm`).
see https://github.com/TahiriNadia/scipy_proceedings/commit/cc5b896282332e6135a3316b26093332c45bdbd1

2019-06-23 16:14 UTC, TahiriNadia commented on papers/nadia_tahiri/nadia_tahiri.rst
> +The results show clearly the cluster of Pasta sauce with Pasta group.
This embedding plot was generated with 20 random products. Some trends can be observed here, but there are also some exceptions as it often happens with real data. In Table 2, Pasta Group was included in the product Categories.
See https://github.com/TahiriNadia/scipy_proceedings/commit/934a2cd5306074f3a4c9765aafb4eded9b0f95fe

2019-06-23 22:09 UTC, TahiriNadia commented on papers/nadia_tahiri/nadia_tahiri.rst
> +Moreover, in this study, we denote frequently missing data in the history grocery list by the user, that is why this technique is more adapted.
This means that the composition of the shopping history list is not complete in the sense we do not have the composition of the baskets for each user for all weeks. See https://github.com/TahiriNadia/scipy_proceedings/commit/9800b0296e3675ea2d38e41a228eaac42596e295

2019-06-23 22:18 UTC, TahiriNadia commented on papers/nadia_tahiri/nadia_tahiri.rst
> +   The first level of the model used LSTM and NNMF.
We added the subsection for NNMF. Please the revised text. See https://github.com/TahiriNadia/scipy_proceedings/commit/ac5a7edcef5f4908a5dc51d460ac00cf91ece18c

2019-06-23 22:41 UTC, TahiriNadia commented on papers/nadia_tahiri/nadia_tahiri.rst
> +        NNMF & Users & $1,374 \times 25$\\
We combined RNN and CNN to predict the probability that a user will order a product at each timestep.

2019-06-23 22:51 UTC, TahiriNadia commented
@deniederhut  @cbcunc  and @stargaser  I believe it should be ready for a second review now!

2019-06-25 03:16 UTC, deniederhut requested changes
I like the new tables! I think they add a lot of useful detail about the work that you have done, and about the data that went into the model. 

I'm still a little unclear about the overall architecture of your pipeline. Where does the total basket size fit in the prediction? Where does the prediction about product categories go? What about the user clustering?

I think this might be a specific case of something more general that I noticed. There are a lot of great details in the paper, and it would be easier to put them in context if they were organized together. Maybe think about organizing the methods to have one section for each experiment you did?

2019-06-25 03:16 UTC, deniederhut commented on papers/nadia_tahiri/nadia_tahiri.rst
> +An :math:`F_1` statistics maximization algorithm [NCLC12]_ (see the Statistics section),,
We seem to have an extra comma here

2019-06-25 03:16 UTC, deniederhut commented on papers/nadia_tahiri/nadia_tahiri.rst
> +The product categories were determined with the purchase histories is the current version of our model
I'm having trouble parsing this sentence. Was it meant to read "in the current version of our model, which does not allow"?

2019-06-25 03:16 UTC, deniederhut commented on papers/nadia_tahiri/nadia_tahiri.rst
> +The difficulty to manage the categorical variable is very important in our study.
"The difficulty of managing the categorical variables"

2019-06-25 03:16 UTC, deniederhut commented on papers/nadia_tahiri/nadia_tahiri.rst
> +These values were obtained from Statistics Canada. Moreover, the distributions used our study follow these statistics.
How was this determined? Tweaking the k in k means? Chi-square on expected values?

2019-06-25 03:16 UTC, deniederhut commented on papers/nadia_tahiri/nadia_tahiri.rst
> +Assuming that the store coordinates are normally distributed :math:`\mathcal{N}(0,\sigma^2)`,
This sentence is repeated

2019-06-25 03:16 UTC, deniederhut commented on papers/nadia_tahiri/nadia_tahiri.rst
> +A combined RNN and CNN was trained to predict the probability that a user will order a product at each timestep.
What defines a time step? Is it each outing? A visit to a specific store?

2019-06-25 03:16 UTC, deniederhut commented on papers/nadia_tahiri/nadia_tahiri.rst
> +The RNN is a single-layer LSTM and the CNN is a 6-layer causal CNN with dilated convolutions.
Which dimension are you running the convolution over?

2019-06-25 03:16 UTC, deniederhut commented on papers/nadia_tahiri/nadia_tahiri.rst
> +Non-negative matrix factorization NNMF [LS01]_ is a technique consists in combining linear algebra and multivariate analysis to produce two matrices `W` and `H` with
"is a technique that consists of combining"

2019-06-25 03:16 UTC, deniederhut commented on papers/nadia_tahiri/nadia_tahiri.rst
> +   Finally, the last test considered to predict the next basket by using :math:`F_1`. :label:`workflow`
I'm not sure what this sentence means

2019-06-25 03:16 UTC, deniederhut commented on papers/nadia_tahiri/nadia_tahiri.rst
> +regression with a variety of response distributions including Gaussian [Car03]_, Bernoulli [CMW16]_, Poisson [PJ73]_, and Laplace [Tay19]_.
Do you have binary features for whether or not a person bough a particular product? Or do you have the count number of each item that was purchased?

2019-06-25 03:16 UTC, deniederhut commented on papers/nadia_tahiri/nadia_tahiri.rst
> +The data are divided into two groups (training and validation) which comprising 90% and 10% of the data respectively.
"which comprise"

2019-06-25 03:16 UTC, deniederhut commented on papers/nadia_tahiri/nadia_tahiri.rst
> +The test set was composed of the real and simulated dataset.
There's an inherent danger in testing on your augmented data. If you restrict the test set to only be real data, do you see a change in the model accuracy?

2019-06-25 03:16 UTC, deniederhut commented on papers/nadia_tahiri/nadia_tahiri.rst
> +Once trained, it was used to predict in real time the content of the current grocery basket, based on the history of purchases and current promotions in neighbouring stores.
What does "real time" mean? Is this second-by-second?

2019-06-25 03:16 UTC, deniederhut commented on papers/nadia_tahiri/nadia_tahiri.rst
> +The last layer includes a GTB classifier used to predict the products that will be bought during the current week.
Is this a different GBT than the real-time one?

2019-06-25 03:16 UTC, deniederhut commented on papers/nadia_tahiri/nadia_tahiri.rst
> +   \max_\mathcal{P} \mathbb{E}_{p'\in \mathcal{P}}[F_1(\mathcal{P})]=\max_\mathcal{P}\mathbb{E}_{p'\in \mathcal{P}}\bigg[\frac{2\sum_{i\in \mathcal{P}}\text{TP}(i)}{\sum_{i\in \mathcal{P}}(2\text{VP}
I don't think it is necessary to define all of these metrics.

2019-06-25 03:16 UTC, deniederhut commented on papers/nadia_tahiri/nadia_tahiri.rst
> +Statistic score
I'm not sure we need this section here either. Maybe pare it down to just the description of f1, since that is what you are using for thresholding?

2019-06-25 03:16 UTC, deniederhut commented on papers/nadia_tahiri/nadia_tahiri.rst
> +Figure :ref:`productpca` illustrates PCA of 20 random products projected into 2 dimensions.
Did your model use PCA to generate clusers of products? If so, where does it fit in your model architecture? If not, what point are you making by including it in the paper?

2019-06-25 03:16 UTC, deniederhut commented on papers/nadia_tahiri/nadia_tahiri.rst
> +   Distribution of :math:`F_1` measures against rebates (a) and stores (b). :label:`violon`
What am I supposed to be learning about your model from this plot?

2019-06-25 03:16 UTC, deniederhut commented on papers/nadia_tahiri/nadia_tahiri.rst
> +                     Banana &   6138 \\
I find this table very surprising. I would have expected to see things like bread and potato chips in the top ten products. Do people really eat more lemons, limes, avocados, and bananas than bread?

2019-06-25 12:29 UTC, TahiriNadia commented on papers/nadia_tahiri/nadia_tahiri.rst
> +An :math:`F_1` statistics maximization algorithm [NCLC12]_ (see the Statistics section),,
nice catch, fixed https://github.com/scipy-conference/scipy_proceedings/pull/465/commits/27d6186d02af7d0f3e102fc540fb7b0603c18eaf

2019-06-25 12:38 UTC, TahiriNadia commented on papers/nadia_tahiri/nadia_tahiri.rst
> +The difficulty to manage the categorical variable is very important in our study.
Thanks @deniederhut 
Fixed https://github.com/scipy-conference/scipy_proceedings/pull/465/commits/6ed4568b393f72ca32f982add791876b1a29756e

2019-06-25 12:43 UTC, TahiriNadia commented on papers/nadia_tahiri/nadia_tahiri.rst
> +Assuming that the store coordinates are normally distributed :math:`\mathcal{N}(0,\sigma^2)`,
removed https://github.com/scipy-conference/scipy_proceedings/pull/465/commits/28ecaaf350cfee455320ec45d70ca0bb807e436c

2019-06-25 12:48 UTC, TahiriNadia commented on papers/nadia_tahiri/nadia_tahiri.rst
> +Non-negative matrix factorization NNMF [LS01]_ is a technique consists in combining linear algebra and multivariate analysis to produce two matrices `W` and `H` with
Great! Replaced https://github.com/scipy-conference/scipy_proceedings/pull/465/commits/9817bfd019f6e4af249f279a91a5082e7e30b9b0

2019-06-25 12:51 UTC, TahiriNadia commented on papers/nadia_tahiri/nadia_tahiri.rst
> +The data are divided into two groups (training and validation) which comprising 90% and 10% of the data respectively.
Great! Replaced https://github.com/scipy-conference/scipy_proceedings/pull/465/commits/ade97798991c4224ee178a33b3196baa9bcf1235

2019-06-25 21:55 UTC, stargaser reviewed
Thank you @TahiriNadia for the updated version. I am very glad to see the placement of Figure 4, the addition of Figure 6, the expanded caption in Figure 5, and the NNMF subsection. Those changes help the clarity of the model section. 

I put a couple of minor comments in-line concerning the `F_1` values.

2019-06-25 21:55 UTC, stargaser commented on papers/nadia_tahiri/nadia_tahiri.rst
> +For the first group, they are products included on restriction regimes
Does a large positive `F_1` score mean: if the user has purchased this product before, they are likely to purchase it again? It makes sense to me that a user on a restriction regime would be likely to purchase the same products.

Vanilla Chocolate Peanut Butter Ice Cream Bars appears to be a notable exception to this statement!

2019-06-25 21:55 UTC, stargaser commented on papers/nadia_tahiri/nadia_tahiri.rst
> +        \caption{The average value of $F_1$ for all products considered.}
This caption still puzzles me, since these must not be all products (too many, 49,000+). Are these the products with the highest and lowest values of `F_1`? The average must be over the users, do I understand correctly?

2019-06-26 02:39 UTC, TahiriNadia commented on papers/nadia_tahiri/nadia_tahiri.rst
> +The product categories were determined with the purchase histories is the current version of our model
We restructured the sentence to be clearer. See https://github.com/scipy-conference/scipy_proceedings/pull/465/commits/598e8ea7048d7f727451b303440d48d2a0858610

2019-06-26 02:47 UTC, TahiriNadia commented on papers/nadia_tahiri/nadia_tahiri.rst
> +These values were obtained from Statistics Canada. Moreover, the distributions used our study follow these statistics.
We used the Calinski-Harabazs cluster validity index [CH74]_ to determine the number of cluster in K-means. The Silhouette index [RPJ87]_ could be also used for this purpose. We added this information to the Introduction section of the revised manuscript. See https://github.com/scipy-conference/scipy_proceedings/pull/465/commits/d7da7d714f5c8c6bc7151a355f70b2c93e57b61e

2019-06-26 02:52 UTC, TahiriNadia commented on papers/nadia_tahiri/nadia_tahiri.rst
> +A combined RNN and CNN was trained to predict the probability that a user will order a product at each timestep.
A time step was defined by the composition of the basket and the store location on the map (see Figure 2). This information was added to the revised manuscript. See https://github.com/scipy-conference/scipy_proceedings/pull/465/commits/1cf3ca7f5241765ab4439fbbf626feca4f7416d2

2019-06-26 02:56 UTC, TahiriNadia commented on papers/nadia_tahiri/nadia_tahiri.rst
> +The RNN is a single-layer LSTM and the CNN is a 6-layer causal CNN with dilated convolutions.
The width of the convolutional neural network was equal to 1374 (i.e., the number of users), the height was equal to 8 (i.e., the number of features), and the depth was equal to 100 (i.e., the number of orders). This information was added to the revised manuscript. See https://github.com/scipy-conference/scipy_proceedings/pull/465/commits/cbef47fe49ab2e2a8e5265c59ffc8717a318465b

2019-06-26 03:00 UTC, TahiriNadia commented on papers/nadia_tahiri/nadia_tahiri.rst
> +   Finally, the last test considered to predict the next basket by using :math:`F_1`. :label:`workflow`
We revised this sentence, which is now as follows: “The graphical illustration of the proposed model intended to predict the content of the current grocery basket. At the first level of the model the LSTM and NNMF networks were used. At the second level of the model, the GBT model was applied. Finally, at the last step we predicted the current grocery basket using:math:`F_1`. :label:`workflow`”. See https://github.com/scipy-conference/scipy_proceedings/pull/465/commits/493b13abd4f045021d1a4e661207ef1c9bf2cdcc

2019-06-26 03:01 UTC, TahiriNadia commented on papers/nadia_tahiri/nadia_tahiri.rst
> +regression with a variety of response distributions including Gaussian [Car03]_, Bernoulli [CMW16]_, Poisson [PJ73]_, and Laplace [Tay19]_.
In fact, one of the features we consider is `reorder` that is equal to 1 if the product has been ordered by the given user in the past, and is equal to 0 otherwise.

2019-06-26 03:10 UTC, TahiriNadia commented on papers/nadia_tahiri/nadia_tahiri.rst
> +The test set was composed of the real and simulated dataset.
The results in Table 5 illustrates that a better model accuracy was obtained when the original dataset of 374 real users was enriched by 1000 artificial users. The accuracy of 49% was obtained for the augmented dataset, compared to the accuracy of 27% for the original dataset. This information was added to the revised manuscript.
See https://github.com/scipy-conference/scipy_proceedings/pull/465/commits/506d9ec0f66dd859342c4eb3b6534be8ab675b55

2019-06-26 03:14 UTC, TahiriNadia commented on papers/nadia_tahiri/nadia_tahiri.rst
> +Once trained, it was used to predict in real time the content of the current grocery basket, based on the history of purchases and current promotions in neighbouring stores.
Actually, the “real time” does not mean "second-by-second", but rather "day-by-day". We scheduled it using the crontab. This information was added to the revised manuscript. See https://github.com/scipy-conference/scipy_proceedings/pull/465/commits/e5ff76e8b88413d587228fdaae3bbe459f4e34b0

2019-06-26 03:16 UTC, TahiriNadia commented on papers/nadia_tahiri/nadia_tahiri.rst
> +The last layer includes a GTB classifier used to predict the products that will be bought during the current week.
GBT model was modelled using “by user“ and “by order“ frameworks. See https://github.com/scipy-conference/scipy_proceedings/pull/465/commits/dd3bc40c6e273cdbe552490d9b92cac6988900ab

2019-06-26 03:17 UTC, TahiriNadia commented on papers/nadia_tahiri/nadia_tahiri.rst
> +   \max_\mathcal{P} \mathbb{E}_{p'\in \mathcal{P}}[F_1(\mathcal{P})]=\max_\mathcal{P}\mathbb{E}_{p'\in \mathcal{P}}\bigg[\frac{2\sum_{i\in \mathcal{P}}\text{TP}(i)}{\sum_{i\in \mathcal{P}}(2\text{VP}
Our main statistic used for prediction is F1-score, but we think that the other statistics (such as accuracy and recall) are also very important. The FPRate score results were however removed from the text of the paper following your recommendations.

2019-06-26 03:21 UTC, TahiriNadia commented on papers/nadia_tahiri/nadia_tahiri.rst
> +Statistic score
We removed the FPRate score results from the paper. 
We evaluated the model (see Section 'Statistic scores') using the `sklearn` metrics (see  https://github.com/scipy-conference/scipy_proceedings/pull/465/commits/ca278725778859d6510cc61f3ff1a24046e6055f):

2019-06-26 03:25 UTC, TahiriNadia commented on papers/nadia_tahiri/nadia_tahiri.rst
> +   Distribution of :math:`F_1` measures against rebates (a) and stores (b). :label:`violon`
PCA was used to visualize the clustering of 20 selected products. It was used to show that some products are frequently bought together with the other products. Such a clustering was not used explicitly in our model, by an artificial network model is supposed to capture and use it implicitly in order to provide a better prediction. This information was added to the revised manuscript. See https://github.com/scipy-conference/scipy_proceedings/pull/465/commits/b6fea3a315f81facde7b2cff7829dd95c0d4f6ba

2019-06-26 03:25 UTC, TahiriNadia commented on papers/nadia_tahiri/nadia_tahiri.rst
> +Figure :ref:`productpca` illustrates PCA of 20 random products projected into 2 dimensions.
PCA was used to visualize the clustering of 20 selected products. It was used to show that some products are frequently bought together with the other products. Such a clustering was not used explicitly in our model, by an artificial network model is supposed to capture and use it implicitly in order to provide a better prediction. This information was added to the revised manuscript. See https://github.com/scipy-conference/scipy_proceedings/pull/465/commits/b6fea3a315f81facde7b2cff7829dd95c0d4f6ba

2019-06-26 03:36 UTC, TahiriNadia commented on papers/nadia_tahiri/nadia_tahiri.rst
> +                     Banana &   6138 \\
In fact, here we tested our model with 1000 products only (out of 49,684 products), which belonged to 5 of the 24 available categories, i.e. `Fruits-Vegetables`, `Pasta-Flour`, `Organic Food`, `Beverages`, and `Breakfast`, the rest of the categories were not considered in this test. This information was added to the revised manuscript. See https://github.com/scipy-conference/scipy_proceedings/pull/465/commits/70b52e893a1a4f54cb08d29ea3cf8aab3e987322

2019-06-26 03:37 UTC, TahiriNadia commented on papers/nadia_tahiri/nadia_tahiri.rst
> +For the first group, they are products included on restriction regimes
Yes, in most cases a large positive F_1 score means that the user, who has purchased this product before, is likely to purchase it again, but there are also some exceptions from it. Overall, we tested our model with 1,000 products only (out of 49,684 products), which belonged to 5 of the 24 available categories, i.e. `Fruits-Vegetables`, `Pasta-Flour`, `Organic Food`, `Beverages`, and `Breakfast`, the rest of the categories were not considered in our test.

2019-06-26 03:41 UTC, TahiriNadia commented on papers/nadia_tahiri/nadia_tahiri.rst
> +        \caption{The average value of $F_1$ for all products considered.}
Exactly, you are right. Here we presented only the products with the five highest and the five lowest values of `F_1`. Yes, the average, in this case, was taken over all users who purchased these products. This information was added to the revised version of the table caption. See https://github.com/scipy-conference/scipy_proceedings/pull/465/commits/8cce231fec9fc516daa4a51bc55346605e5cf319

2019-06-26 04:10 UTC, TahiriNadia commented
@deniederhut @cbcunc and @stargaser I believe it should be ready for a review. I hope it will be OK :blush:

2019-06-26 20:30 UTC, stargaser approved these changes
I am happy with the latest revisions. Thank you for the new Table 5.

I just have one minor grammar correction on the Table 5 caption (in-line).

(also, an explicit acknowledgment was not necessary -- but thank you)

2019-06-26 20:30 UTC, stargaser commented on papers/nadia_tahiri/nadia_tahiri.rst
> +        \caption{Statistic score results for real data, and real with augmented data. Table clarify the impact of augmented data instead of only used real data.}
```suggestion
        \caption{Statistic score results for real data, and real with augmented data. The table clarifies the impact of using augmented data instead of only real data.}
```

2019-06-26 21:08 UTC, TahiriNadia commented on papers/nadia_tahiri/nadia_tahiri.rst
> +        \caption{Statistic score results for real data, and real with augmented data. Table clarify the impact of augmented data instead of only used real data.}
Thank you for your review and comments @stargaser 
This information was added to the revised manuscript. See https://github.com/scipy-conference/scipy_proceedings/pull/465/commits/e077a81c086e50b2fd75b3c52c20e693cfd3f71a

2019-06-28 17:45 UTC, TahiriNadia commented
@deniederhut and @cbcunc Let me know if you have any additional suggestions.

2019-06-29 00:35 UTC, deniederhut commented on papers/nadia_tahiri/nadia_tahiri.rst
> +Initially, the data were stocked in csv files at a MySQL database taking 1.4 GB. Then, the data were stocked in a dataframe in our Python script.
😂 is that a grocery store pun?

2019-06-29 00:41 UTC, deniederhut commented on papers/nadia_tahiri/nadia_tahiri.rst
> +Statistic score
Hm. I still see descriptions of accuracy, precision, and recall here

2019-06-29 00:50 UTC, deniederhut commented on papers/nadia_tahiri/nadia_tahiri.rst
> +                     Banana &   6138 \\
The  product_id description is pretty far away from this table caption in the paper. I might either:

A. link back to it explicitly from the caption (like you did in your comment here 😄); or,
B. or mention in the caption that the "top" products are from a subset comprising 2% of all available products

2019-06-29 03:03 UTC, TahiriNadia commented on papers/nadia_tahiri/nadia_tahiri.rst
> +Statistic score
Fixed. We removed the description of accuracy, precision, and recall. See https://github.com/scipy-conference/scipy_proceedings/pull/465/commits/8d46c3b3d43aef32fd2e669f5107217c32c3e0d6

2019-06-29 03:11 UTC, TahiriNadia commented on papers/nadia_tahiri/nadia_tahiri.rst
> +                     Banana &   6138 \\
Thanks for this note. We have chosen option B and we updated the caption following your recommendations. See https://github.com/scipy-conference/scipy_proceedings/pull/465/commits/ece39bdc2227ed6e5f5749e7a7bd552e957c9dd6

2019-06-29 03:17 UTC, TahiriNadia commented on papers/nadia_tahiri/nadia_tahiri.rst
> +Initially, the data were stocked in csv files at a MySQL database taking 1.4 GB. Then, the data were stocked in a dataframe in our Python script.
😂 We proposed this new formulation https://github.com/scipy-conference/scipy_proceedings/pull/465/commits/1834db0376c12b929ed9e12e71cfc5b0f129e120

2019-06-29 03:24 UTC, TahiriNadia commented on papers/nadia_tahiri/nadia_tahiri.rst
> +Initially, the data were stocked in csv files at a MySQL database taking 1.4 GB. Then, the data were stocked in a dataframe in our Python script.
@deniederhut Thanks for your recommendations. 
All items are fixed!

2019-06-29 03:53 UTC, TahiriNadia commented
@deniederhut Thanks for your recommendations.
All items are fixed!

2019-06-29 18:24 UTC, deniederhut commented
Thanks for turning this around so quickly! 

One last thing - I can't find a python package called F1Optimizer. The closest match returned by my google-fu is this kaggle post https://www.kaggle.com/mmueller/f1-score-expectation-maximization-in-o-n/comments about implementing the algorithm in the paper you cite as NCLC12, which was part of a very similar set of tasks predicting shopping baskets but for Instacart instead of MyGroceryTour. 

If it's a publicly-available python package, please include the citation for it. If you copied the code from the post, please reference that post.

2019-06-30 15:51 UTC, TahiriNadia commented
> Thanks for turning this around so quickly!
> 
> One last thing - I can't find a python package called F1Optimizer. The closest match returned by my google-fu is this kaggle post https://www.kaggle.com/mmueller/f1-score-expectation-maximization-in-o-n/comments about implementing the algorithm in the paper you cite as NCLC12, which was part of a very similar set of tasks predicting shopping baskets but for Instacart instead of MyGroceryTour.
> 
> If it's a publicly-available python package, please include the citation for it. If you copied the code from the post, please reference that post.

Thank you for this note.
I've added the `F1Optimizer` package reference.

2019-06-30 20:21 UTC, deniederhut approved these changes

2019-06-30 20:21 UTC, deniederhut commented
Perfect! Thanks everyone!

2019-07-02 22:11 UTC, TahiriNadia commented
Some important English improvements have been found today. Is it possible to correct them?

2019-07-02 22:22 UTC, stargaser commented
@TahiriNadia my understanding is that @deniederhut is planning to merge the PRs tomorrow, so it is still possible to make corrections by tomorrow morning.

2019-07-03 13:23 UTC, merged