Hongsup shin
scipy-conference/scipy_proceedings pull request #468
Opened 2019-05-22 00:59 UTC by hongsups

If you are creating this PR in order to submit a draft of your paper,
see http://procbuild.scipy.org/ for logs generated by the build
process.

See the [project readme](https://github.com/scipy-conference/scipy_proceedings#build-your-paper)
for more information.

2019-06-13 00:21 UTC, deniederhut commented
Hi @hongsups ! It looks like none of our reviewers were able to complete their reviews for your paper by the deadline, so I'll be stepping in to complete the review myself. Please expect comments from me some time in the next handful of days 🙂.

2019-06-14 03:58 UTC, deniederhut requested changes

2019-06-14 03:58 UTC, deniederhut commented on papers/Hongsup_Shin/Hongsup_Shin.rst
> +   When designing microprocessors, engineers must verify whether the proposed design, defined in hardware description language, do what is intended. Duering this verification process, engineers run s
I think you mean to say: 

"does what is intended"
"During this verification"
"complexity of the design"
"real-world constraints"

What do you mean by "severe imbalanced"? Imbalance in the labels?

> which are not often discussed in machine learning and data science research

😅 I don't know that I would say "often", but yes it is nice to see what can be done without infinite time and infinite money. Maybe we could rephrase this to "which are sometimes not discussed"?

2019-06-14 03:58 UTC, deniederhut commented on papers/Hongsup_Shin/Hongsup_Shin.rst
> +Hardware verification is the process of checking that a given design correctly implements the specification, which are the technical descriptions of the computer's components and capabilities. It is
I think you might mean to say:

"implements a specification"
"which is the technical description"
"adopts a mathematical approach"
"the more widely used approach"

> the total number states is :math:`2^N` 

another way to say this is that the complexity grows exponentially

2019-06-14 03:58 UTC, deniederhut commented on papers/Hongsup_Shin/Hongsup_Shin.rst
> +The ultimate goal of hardware verification is to have a (close-to) bug-free design. From the simulation-based testing perspective, this is an exploration problem where machine learning can be useful.
Did you mean to write "these approaches are based on probability-based methods"? Or maybe "these approaches tend to be based on..."?

I might replace "difficult to be scalable" with "difficult to scale". I might also replace "lack the mention" with "fail to mention".

2019-06-14 03:58 UTC, deniederhut commented on papers/Hongsup_Shin/Hongsup_Shin.rst
> +   Proportional relationship between the number of failures (x axis) and the number of unique fail signatures (UFS) on the y axis (mean and standard error from 100 random draws; among 250k simlated t
"simulated"

2019-06-14 03:58 UTC, deniederhut commented on papers/Hongsup_Shin/Hongsup_Shin.rst
> +In practice, a testbench is built to make the random simulation of tests efficient and be automated to a degree such as running a batch of tests regularly to explore random parts of the design. Once
Did you mean to write:
"and includes the specific signature of the failure"
"which may require the model to be retrained"

2019-06-14 03:58 UTC, deniederhut commented on papers/Hongsup_Shin/Hongsup_Shin.rst
> +This situation requires a unique approach. Since it is impossible to eliminate randomness in test generation, which makes it difficult to guide testbench, we can consider *filtering* the tests. By us
Maybe instead of:

> Since it is impossible to eliminate randomness in test generation, which makes it difficult to guide testbench, we can consider *filtering* the tests. 

Try:

> It is impossible to eliminate randomness in the test generation step, which makes it difficult to guide testbench to test specific input values or parts of the system. Instead, we leave the inputs to be generated randomly and filter them afterward.

> we still have to explore new design parts

Yes! Very important.

2019-06-14 03:58 UTC, deniederhut commented on papers/Hongsup_Shin/Hongsup_Shin.rst
> +I used both supervised and unsupervised models to address the severe class imbalance problem and used the union of the prediction from both models. With this approach, for a set of independent testin
I might rewrite "The tool has been deployed and been used since early this year." as "The tool has been deployed in production since early this year."

2019-06-14 03:58 UTC, deniederhut commented on papers/Hongsup_Shin/Hongsup_Shin.rst
> +Simulation-based testing is run almost every day via testbench. Every simulated test and the result, such as whether the test has passed or failed (and its UFS), is stored in a database. ngineers pus
"ngineers push various commits" -> "Engineers push various commits"
"This may include new implementation" -> "This may include a new implementation"

> Depending on the amount of changes, the data drift might be significant. 

This is a very important point, but I'm not sure you've defined what you mean by "data drift" in the paper yet.

"a month worth" -> "a month's worth" 

> The data were preprocessed based on the consultation with domain experts and stakeholders.

What do you mean by this? Rows were removed? Values were normalized? How many observations were removed? How many were changed?

2019-06-14 03:58 UTC, deniederhut commented on papers/Hongsup_Shin/Hongsup_Shin.rst
> +I used an ensemble of a supervised and an unsupervised learning model. Due to the severe class imbalance between passes and failures (near 99% pass and 1% failure ratio) in the training data, we can
Could you enumerate the supervised classification models you tried? Which ones worked best? Do you have an intuition as to why?

2019-06-14 03:58 UTC, deniederhut commented on papers/Hongsup_Shin/Hongsup_Shin.rst
> +It turns out engineers care more about failure signatures than simple binary labels. Even if we find many failures in test simulation, if many failures share fail signatures and we end up with very f
> It turns out engineers care more about failure signatures 

Oh this is interesting. So the objective function that you really care about is recall of signatures, not necessarily recall of failures?

2019-06-14 03:58 UTC, deniederhut commented on papers/Hongsup_Shin/requirements.txt
> +matplotlib == 2.0.2
Is there a reason you have a requirements file for your paper?

2019-06-14 03:58 UTC, deniederhut commented on papers/Hongsup_Shin/Hongsup_Shin.rst
> +For both supervised and unsupervised models, I used recall and precision as basic metric but also used more practical metrics. For the unsupervised, I treated the outliers and failures and computed t
What do you mean when you say "treated the outliers"

2019-06-14 03:58 UTC, deniederhut commented on papers/Hongsup_Shin/Hongsup_Shin.rst
> +**UFS recovery rate**: The number of UFS in tests predicted as failure divided by the total number of UFS we would have collected if we had run all tests. This is equivalent to recall score but inste
I think you forgot to finish this sentence: "This is equivalent to recall score but instead of"

2019-06-14 03:58 UTC, deniederhut commented on papers/Hongsup_Shin/Hongsup_Shin.rst
> +   First 17 days of model performance (efficiency) after deployment. Efficiency is computed as the ratio of precision between the ML flow and the random flow. The precision is computed as the proport
What is the sample size at each time step?

2019-06-14 03:58 UTC, deniederhut commented on papers/Hongsup_Shin/Hongsup_Shin.rst
> +Other engineers and I wrote a Python script with in my group, which is a command-line tool that engineers can run without changing their main *random* flow. The script takes test candidates as input
"script with in my group" -> "script within my group"
"In the following sessions" -> "in the following sections"

2019-06-14 03:58 UTC, deniederhut commented on papers/Hongsup_Shin/Hongsup_Shin.rst
> +   The effect of the number of tests that are provided to the models and the performance variability. Each vertical line represnets a single simulated run. Since we use the models to filter out the t
"the performance becomes less variable" -> "the less variable the performance becomes"

2019-06-14 03:58 UTC, deniederhut commented on papers/Hongsup_Shin/Hongsup_Shin.rst
> +During the initial deployment stage, we retrained the models manually whenever we made major changes in tool for instance how we preprocess data or whenever the production engineers announced that th
"whenever we made major changes in tool for instance" -> "whenever we made major changes in the tool, for instance"
"These weights are applied to objective function" -> "These weights are applied to the objective function"
"Since every day multiple tests are generated, same weights are assigned to data points if they were generated on a same day" -> "Since multiple tests are generated for each day, they each get the same weights."

2019-06-14 03:58 UTC, deniederhut commented on papers/Hongsup_Shin/Hongsup_Shin.rst
> +All combinatorial scenarios were tested via simulation across multiple datasets (Fig. :ref:`Fig.5`). When the rolling window is too small (e.g., :math:`N=3`), performance was low in both UFS recovery
"When the rolling window is too small" -> "When the rolling window was too small"

2019-06-14 03:58 UTC, deniederhut commented on papers/Hongsup_Shin/Hongsup_Shin.rst
> +To address these issues, I have built a prototype that provide test candidates and filters out failure-prone tests instead of trying to guide the testbench itself, used both supervised and unsupervis
"I have also conducted experimetns" -> "I have also conducted experiments"

2019-06-14 03:59 UTC, deniederhut commented
This is a great paper! I really enjoyed reading about your approach. I've left a couple of inline comments about spelling and grammar -- I think I caught most of the mistakes, but you may want to run this through a spellchecker just to be sure.

2019-06-14 04:43 UTC, mepa commented on papers/Hongsup_Shin/Hongsup_Shin.rst
> +   When designing microprocessors, engineers must verify whether the proposed design, defined in hardware description language, do what is intended. Duering this verification process, engineers run s
This is an interesting application of ML to improve efficiency of hardware design verification testing.

I'll make a first pass review listing spelling, grammar, clarity, etc. suggestions as follows.
- "Duering" -> During
- "**do** what is intended" -> **does** what is intended
- "Due to **the severe imbalance**" -> Please clarify, e.g., 99% test success and 1% test failure
- "constrations" -> constraints

2019-06-14 04:43 UTC, mepa commented on papers/Hongsup_Shin/Hongsup_Shin.rst
> +Hardware verification is the process of checking that a given design correctly implements the specification, which are the technical descriptions of the computer's components and capabilities. It is
- "specification" -> specifications
- "recoginsed" -> recognized
- "approach" -> approaches
- "Thus, **the** more widely..."
- "During **the** simulation-based testing" -> Please drop "**the**" in this case and all cases below (unless referring to a particular "testing" in which case it could be clarified which testing is in mind)
- "part" -> parts

2019-06-14 04:43 UTC, mepa commented on papers/Hongsup_Shin/Hongsup_Shin.rst
> +The ultimate goal of hardware verification is to have a (close-to) bug-free design. From the simulation-based testing perspective, this is an exploration problem where machine learning can be useful.
- "bug-free design" -> It may be interesting to a non-specialized audience to read specific examples of bugs met during hardware verification.
- "For instance, reinforcement learning algorithm..." -> Correct singular/plural agreement in this sentence.
- "of **the** approach" -> of **this** approach

2019-06-14 04:43 UTC, mepa commented on papers/Hongsup_Shin/Hongsup_Shin.rst
> +In practice, a testbench is built to make the random simulation of tests efficient and be automated to a degree such as running a batch of tests regularly to explore random parts of the design. Once
- "stimulu" -> stimulus
- "parts **is** challenging" -> parts challenging
- "everyday" -> every day
- "require model" -> require **the** model

2019-06-14 04:43 UTC, mepa commented on papers/Hongsup_Shin/Hongsup_Shin.rst
> +I used both supervised and unsupervised models to address the severe class imbalance problem and used the union of the prediction from both models. With this approach, for a set of independent testin
- I suggest clarifying "the severe class imbalance problem" on first time meeting the phrase, though I see that it's spelled out under the *Models* paragraph.
- "has been deployed" -> to where? used by whom and how often? or, if it will be described further in a later section it may be nice to state that here
- "insights to post-deployment" -> insights to **the** post-deployment

2019-06-14 04:43 UTC, mepa commented on papers/Hongsup_Shin/Hongsup_Shin.rst
> +Simulation-based testing is run almost every day via testbench. Every simulated test and the result, such as whether the test has passed or failed (and its UFS), is stored in a database. ngineers pus
- "ngineers" -> engineers

2019-06-14 04:43 UTC, mepa commented on papers/Hongsup_Shin/Hongsup_Shin.rst
> +I used an ensemble of a supervised and an unsupervised learning model. Due to the severe class imbalance between passes and failures (near 99% pass and 1% failure ratio) in the training data, we can
- "we can train a supervised model with adjusted class weight or either" -> we can **either** train a supervised model with adjusted class weight or
- "I found that supervised and the unsupervised" -> I found that **the** supervised and unsupervised

2019-06-14 04:43 UTC, mepa commented on papers/Hongsup_Shin/Hongsup_Shin.rst
> +For both supervised and unsupervised models, I used recall and precision as basic metric but also used more practical metrics. For the unsupervised, I treated the outliers and failures and computed t
- "as basic metric" -> as basic metrics
- "I treated the outliers and failures" -> what does "treated" mean here?

2019-06-14 04:54 UTC, mepa commented on papers/Hongsup_Shin/Hongsup_Shin.rst
> +   When designing microprocessors, engineers must verify whether the proposed design, defined in hardware description language, do what is intended. Duering this verification process, engineers run s
@deniederhut, @hongsups, sorry for the duplicate comments from me. I had reviewed earlier this week but neglected to hit the "Finish review" button. Just did so now :)

2019-06-14 19:36 UTC, hongsups commented
> Hi @hongsups ! It looks like none of our reviewers were able to complete their reviews for your paper by the deadline, so I'll be stepping in to complete the review myself. Please expect comments from me some time in the next handful of days 🙂.

Thanks, Dillon. Would you want me to wait until you complete the review, to make changes in the manuscript or is it okay if I start working on it as soon as possible? Honestly the draft was submitted with rush, so I think I can fix some problems by myself.

2019-06-14 20:05 UTC, deniederhut commented
My review is already submitted - you should be able to see the inline comments here on this page.

2019-06-15 11:57 UTC, mepa commented
> > Hi @hongsups ! It looks like none of our reviewers were able to complete their reviews for your paper by the deadline, so I'll be stepping in to complete the review myself. Please expect comments from me some time in the next handful of days 🙂.
> 
> Thanks, Dillon. Would you want me to wait until you complete the review, to make changes in the manuscript or is it okay if I start working on it as soon as possible? Honestly the draft was submitted with rush, so I think I can fix some problems by myself.

Hi @hongsups, @deniederhut - apologies for not getting my initial review in on time. I think go ahead and make changes in the manuscript, then we can continue adding more content-based review comments before the final deadline.

2019-06-17 12:31 UTC, hongsups commented
> > > Hi @hongsups ! It looks like none of our reviewers were able to complete their reviews for your paper by the deadline, so I'll be stepping in to complete the review myself. Please expect comments from me some time in the next handful of days 🙂.
> > 
> > 
> > Thanks, Dillon. Would you want me to wait until you complete the review, to make changes in the manuscript or is it okay if I start working on it as soon as possible? Honestly the draft was submitted with rush, so I think I can fix some problems by myself.
> 
> Hi @hongsups, @deniederhut - apologies for not getting my initial review in on time. I think go ahead and make changes in the manuscript, then we can continue adding more content-based review comments before the final deadline.

@mepa Will do. I will upload the updated manuscript in 2-3 days this week!

2019-06-17 13:24 UTC, hongsups commented on papers/Hongsup_Shin/requirements.txt
> +matplotlib == 2.0.2
Ah, it does not but I thought it would be more informative to show package versions. I guess I could mention the ones that matter in the paper. I will consider it.

2019-06-17 13:25 UTC, hongsups commented on papers/Hongsup_Shin/Hongsup_Shin.rst
> +   First 17 days of model performance (efficiency) after deployment. Efficiency is computed as the ratio of precision between the ML flow and the random flow. The precision is computed as the proport
It varied daily but within the range of 3k-4k tests (samples).

2019-06-17 13:28 UTC, hongsups commented on papers/Hongsup_Shin/Hongsup_Shin.rst
> +It turns out engineers care more about failure signatures than simple binary labels. Even if we find many failures in test simulation, if many failures share fail signatures and we end up with very f
Yes! That's why I was showing the Fig. 2 to justify the use of binary classifier. The engineers want to maximize the unique count of failure signatures, and it can be achieved indirectly by finding more failures (binary label). I will elaborate this in the manuscript.

2019-06-17 13:48 UTC, hongsups commented on papers/Hongsup_Shin/Hongsup_Shin.rst
> +   When designing microprocessors, engineers must verify whether the proposed design, defined in hardware description language, do what is intended. Duering this verification process, engineers run s
@deniederhut I added specific information of the class imbalance (as @mepa also suggested). Also, rephrased the "often" according to your suggestion :)

2019-06-17 13:51 UTC, hongsups commented on papers/Hongsup_Shin/Hongsup_Shin.rst
> +   When designing microprocessors, engineers must verify whether the proposed design, defined in hardware description language, do what is intended. Duering this verification process, engineers run s
@deniederhut @mepa Btw, I am making adjustments to the manuscript while replying to your comments. I will make commits in batch so there can be delay between my answer here and actual change in manuscript.

2019-06-17 13:53 UTC, hongsupshin commented on papers/Hongsup_Shin/Hongsup_Shin.rst
> +Hardware verification is the process of checking that a given design correctly implements the specification, which are the technical descriptions of the computer's components and capabilities. It is
Thanks @mepa, I corrected typos and grammatical errors.

2019-06-17 14:00 UTC, hongsups commented on papers/Hongsup_Shin/Hongsup_Shin.rst
> +Hardware verification is the process of checking that a given design correctly implements the specification, which are the technical descriptions of the computer's components and capabilities. It is
@deniederhut I corrected the errors as you suggested. About the last one, the new sentence is: "Due to the exponentially-growing design complexity, the more widely used approach is the simulation-based testing, ..."

2019-06-17 18:19 UTC, hongsups commented on papers/Hongsup_Shin/Hongsup_Shin.rst
> +The ultimate goal of hardware verification is to have a (close-to) bug-free design. From the simulation-based testing perspective, this is an exploration problem where machine learning can be useful.
@deniederhut I rephrased the part about probabilistic methods and provided more details because I thought that part was somewhat vague (especially why it's challenging). Changed the rest according to the suggestion.

2019-06-17 23:24 UTC, hongsups commented on papers/Hongsup_Shin/Hongsup_Shin.rst
> +The ultimate goal of hardware verification is to have a (close-to) bug-free design. From the simulation-based testing perspective, this is an exploration problem where machine learning can be useful.
@mepa I wrote a short paragraph that describes what hardware bug means and also address a couple of general examples. The grammatical errors are fixed.

2019-06-17 23:27 UTC, hongsups commented on papers/Hongsup_Shin/Hongsup_Shin.rst
> +   Proportional relationship between the number of failures (x axis) and the number of unique fail signatures (UFS) on the y axis (mean and standard error from 100 random draws; among 250k simlated t
@deniederhut Fixed.

2019-06-18 02:43 UTC, deniederhut commented
Awesome! Please @ us when you are ready for us to have a second look 😄

2019-06-18 02:59 UTC, hongsups commented on papers/Hongsup_Shin/Hongsup_Shin.rst
> +In practice, a testbench is built to make the random simulation of tests efficient and be automated to a degree such as running a batch of tests regularly to explore random parts of the design. Once
@mepa Fixed the errors. Also added more detailed information about how a testbench works so that the readers have a better idea of how a test is generated.

2019-06-18 03:00 UTC, hongsups commented on papers/Hongsup_Shin/Hongsup_Shin.rst
> +In practice, a testbench is built to make the random simulation of tests efficient and be automated to a degree such as running a batch of tests regularly to explore random parts of the design. Once
@deniederhut Fixed and changed the wording.

2019-06-18 03:02 UTC, hongsups commented on papers/Hongsup_Shin/Hongsup_Shin.rst
> +This situation requires a unique approach. Since it is impossible to eliminate randomness in test generation, which makes it difficult to guide testbench, we can consider *filtering* the tests. By us
@deniederhut That's much better indeed. Thanks for the suggestion. Changed the wording.

2019-06-18 03:10 UTC, hongsups commented on papers/Hongsup_Shin/Hongsup_Shin.rst
> +I used both supervised and unsupervised models to address the severe class imbalance problem and used the union of the prediction from both models. With this approach, for a set of independent testin
@mepa 
- I added the details of the class imbalance (class ratio) to the very beginning when I first mention this. 
- Also added more details about the deployment ("The tool has been deployed in our internal cluster as a part of daily verification workflow, which is used by verification engineers in the production team.")
- Fixed the error.

2019-06-18 03:11 UTC, hongsups commented on papers/Hongsup_Shin/Hongsup_Shin.rst
> +I used both supervised and unsupervised models to address the severe class imbalance problem and used the union of the prediction from both models. With this approach, for a set of independent testin
@deniederhut Rephrased the sentence.

2019-06-18 03:17 UTC, hongsups commented
> Awesome! Please @ us when you are ready for us to have a second look 😄

Will do! I was using @ for every comment to reply mainly because I wasn't sure whether I should refer or not, but I will just use it once the manuscript is ready for the second look. I will also try to commit in batches. Thanks for the feedback :)

2019-06-18 13:46 UTC, hongsups commented on papers/Hongsup_Shin/Hongsup_Shin.rst
> +Simulation-based testing is run almost every day via testbench. Every simulated test and the result, such as whether the test has passed or failed (and its UFS), is stored in a database. ngineers pus
- Fixed the typos.
- I mention "data drift" first in the introduction (under "Simulation-based testing in practice") and there I added a description and some detail.
- After the "Data" section, I added a section called "Data preprocessing" to elaborate the process. This has information about the details (missing data handling, preprocessing, comparison between the raw and preprocessed data).

2019-06-18 15:05 UTC, hongsups commented on papers/Hongsup_Shin/Hongsup_Shin.rst
> +I used an ensemble of a supervised and an unsupervised learning model. Due to the severe class imbalance between passes and failures (near 99% pass and 1% failure ratio) in the training data, we can
Added the details about which algorithms I used and provided an intuition on why. "I used algorithms such as logistic regression and tree-based ensemble methods (random forest, gradient boosting, extra trees). The wininng algorithm was the logistic regression with l2 regularization, potentially because the preprocessed input data has high sparsity (more than 50%)."

2019-06-18 15:39 UTC, hongsups commented on papers/Hongsup_Shin/Hongsup_Shin.rst
> +For both supervised and unsupervised models, I used recall and precision as basic metric but also used more practical metrics. For the unsupervised, I treated the outliers and failures and computed t
Deleted the sentence because it's confusing. Why we can treat failures as outliers are described in the first paragraph in "Models": "For the unsupervised, because the majority of our training data is passed tests, it is possible to consider the failures as outliers or abnormalities."

2019-06-18 22:14 UTC, hongsups commented on papers/Hongsup_Shin/Hongsup_Shin.rst
> +**UFS recovery rate**: The number of UFS in tests predicted as failure divided by the total number of UFS we would have collected if we had run all tests. This is equivalent to recall score but inste
Fixed. Also provided more details about the metrics.

2019-06-18 22:20 UTC, hongsups commented on papers/Hongsup_Shin/Hongsup_Shin.rst
> +Other engineers and I wrote a Python script with in my group, which is a command-line tool that engineers can run without changing their main *random* flow. The script takes test candidates as input
Fixed.

2019-06-18 22:20 UTC, hongsups commented on papers/Hongsup_Shin/Hongsup_Shin.rst
> +   The effect of the number of tests that are provided to the models and the performance variability. Each vertical line represnets a single simulated run. Since we use the models to filter out the t
Fixed.

2019-06-18 22:21 UTC, hongsups commented on papers/Hongsup_Shin/Hongsup_Shin.rst
> +During the initial deployment stage, we retrained the models manually whenever we made major changes in tool for instance how we preprocess data or whenever the production engineers announced that th
Fixed.

2019-06-18 22:22 UTC, hongsups commented on papers/Hongsup_Shin/Hongsup_Shin.rst
> +All combinatorial scenarios were tested via simulation across multiple datasets (Fig. :ref:`Fig.5`). When the rolling window is too small (e.g., :math:`N=3`), performance was low in both UFS recovery
Fixed.

2019-06-18 22:22 UTC, hongsups commented on papers/Hongsup_Shin/Hongsup_Shin.rst
> +To address these issues, I have built a prototype that provide test candidates and filters out failure-prone tests instead of trying to guide the testbench itself, used both supervised and unsupervis
Fixed.

2019-06-18 22:23 UTC, hongsups commented
> This is a great paper! I really enjoyed reading about your approach. I've left a couple of inline comments about spelling and grammar -- I think I caught most of the mistakes, but you may want to run this through a spellchecker just to be sure.

Thank you so much :) I submitted with rush, so there were a lot of typos and errors. I will make sure I fix as many as possible. I am also running spellcheckers!

2019-06-18 22:26 UTC, hongsups commented on papers/Hongsup_Shin/Hongsup_Shin.rst
> +Simulation-based testing is run almost every day via testbench. Every simulated test and the result, such as whether the test has passed or failed (and its UFS), is stored in a database. ngineers pus
Fixed.

2019-06-18 22:27 UTC, hongsups commented on papers/Hongsup_Shin/Hongsup_Shin.rst
> +I used an ensemble of a supervised and an unsupervised learning model. Due to the severe class imbalance between passes and failures (near 99% pass and 1% failure ratio) in the training data, we can
Fixed.

2019-06-18 22:29 UTC, hongsups commented on papers/Hongsup_Shin/Hongsup_Shin.rst
> +For both supervised and unsupervised models, I used recall and precision as basic metric but also used more practical metrics. For the unsupervised, I treated the outliers and failures and computed t
- Fixed it to "metrics"
- I added description in the first paragraph under "Models" section: "For the unsupervised, because the majority of our training data is passed tests, it is possible to consider the failures as outliers or abnormalities. " and removed the sentence, "treated the outliers..."

2019-06-19 16:20 UTC, hongsups commented
@mepa @deniederhut Hi! I just uploaded the updated manuscript. It's ready for the second review. Btw, is the deadline June 25? Anyway, I will be frequently checking this page, so please feel free to leave any comments and questions. I will do my best to answer!

2019-06-20 12:39 UTC, deniederhut requested changes
This is looking really good! I've left some more phrasing suggestions. Also, it looks like your citations are missing DOIs. Could I ask you to add those in?

2019-06-20 12:39 UTC, deniederhut commented on papers/Hongsup_Shin/Hongsup_Shin.rst
> +Hardware verification is the process of checking that a given design correctly implements the specifications, which is the technical description of the computer's components and capabilities. It is r
"specifications, which are"

2019-06-20 12:39 UTC, deniederhut commented on papers/Hongsup_Shin/Hongsup_Shin.rst
> +The ultimate goal of hardware verification is to have a (close-to) failure-free design. From the simulation-based testing perspective, this is an exploration problem where machine learning can be use
"a few studies have adopted a probabilistic approach, but they failed"

2019-06-20 12:39 UTC, deniederhut commented on papers/Hongsup_Shin/Hongsup_Shin.rst
> +In practice, engineers build a testbench to house all the components that are needed for the verification process: test generator, interface, driver, monitor, model, and scoreboard. To run tests, ver
"input arguments to a function."

2019-06-20 12:39 UTC, deniederhut commented on papers/Hongsup_Shin/Hongsup_Shin.rst
> +Random generation of the test settings in the test generator is intended to run a batch of tests automatically almost daily to explore random parts of the design with efficiency. In practice, enginee
"in the test generator is used to run"

2019-06-20 12:39 UTC, deniederhut commented on papers/Hongsup_Shin/Hongsup_Shin.rst
> +This situation requires a unique approach. It is impossible to eliminate randomness in the test generation step, which makes it difficult to guide testbench to test specific input values or parts of
"the entire set of test candidates"

2019-06-20 12:39 UTC, deniederhut commented on papers/Hongsup_Shin/Hongsup_Shin.rst
> +I used an ensemble of a supervised and an unsupervised learning model. Due to the severe class imbalance between passes and failures (near 99% pass and 1% failure rate) in the training data, it is po
I don't typically see the word "union" used to describe a method for reducing values. Maybe we could say that it takes the max of the predictions? Or that it predicts failure if any component of the ensemble predicts failure?

2019-06-20 12:39 UTC, deniederhut commented on papers/Hongsup_Shin/Hongsup_Shin.rst
> +Due to the frequent changes in data generation process, I decided to use algorithms robust to frequent retraining and tuning (i.e., faster training time). I used a group of non-neural-net scikit-lear
> The winning algorithm was the logistic regression with L2 regularization

It's interesting how often the simple models perform the best 😄

2019-06-20 12:39 UTC, deniederhut commented on papers/Hongsup_Shin/Hongsup_Shin.rst
> +   \text{UFS recovery rate} = \frac{\mathrm{card}(S_{\hat{y}=1})}{\mathrm{card}(S_{y=1})},
Is there a reason you didn't use Jaccard similarity?

2019-06-20 12:39 UTC, deniederhut commented on papers/Hongsup_Shin/Hongsup_Shin.rst
> +For the *snapshot* dataset, the testing data (50% holdout data in 10 different sets; each set is generated independently) shows that the union predictions from the trained supervised and unsupervised
"achieved a UFS recovery rate"
"and an efficiency of"

> I ran a permutation test as a sanity check

I'm really glad you included this detail; I think permutation tests are underrated. Phil Stark used to joke about writing a book called "Permutation tests can be used for everything".

2019-06-20 12:39 UTC, deniederhut commented on papers/Hongsup_Shin/Hongsup_Shin.rst
> +After the deployment, model performance started showing high variability, sometimes very different from the pre-deployment model performance. Figure :ref:`Fig.4` shows the model performance of the fi
"scores were often larger than one"

2019-06-20 12:39 UTC, deniederhut commented on papers/Hongsup_Shin/Hongsup_Shin.rst
> +It is suspected that the fluctuation in model performance (Fig. :ref:`Fig.4`) might be related to the quality of the test candidates. This is because the test candidates were generated randomly in th
"lower than one or as high as four"

2019-06-20 12:57 UTC, hongsups commented
> This is looking really good! I've left some more phrasing suggestions. Also, it looks like your citations are missing DOIs. Could I ask you to add those in?

Thanks! Yes, I will add those.

2019-06-20 12:58 UTC, hongsups commented on papers/Hongsup_Shin/Hongsup_Shin.rst
> +Hardware verification is the process of checking that a given design correctly implements the specifications, which is the technical description of the computer's components and capabilities. It is r
Fixed.

2019-06-20 12:59 UTC, hongsups commented on papers/Hongsup_Shin/Hongsup_Shin.rst
> +The ultimate goal of hardware verification is to have a (close-to) failure-free design. From the simulation-based testing perspective, this is an exploration problem where machine learning can be use
Fixed.

2019-06-20 12:59 UTC, hongsups commented on papers/Hongsup_Shin/Hongsup_Shin.rst
> +In practice, engineers build a testbench to house all the components that are needed for the verification process: test generator, interface, driver, monitor, model, and scoreboard. To run tests, ver
Fixed.

2019-06-20 12:59 UTC, hongsups commented on papers/Hongsup_Shin/Hongsup_Shin.rst
> +Random generation of the test settings in the test generator is intended to run a batch of tests automatically almost daily to explore random parts of the design with efficiency. In practice, enginee
Fixed.

2019-06-20 13:01 UTC, hongsups commented on papers/Hongsup_Shin/Hongsup_Shin.rst
> +This situation requires a unique approach. It is impossible to eliminate randomness in the test generation step, which makes it difficult to guide testbench to test specific input values or parts of
For this one, I modified it to "the entire set of the input settings of test candidates" because I want to specify that the randomization is specifically for the input settings.

2019-06-20 13:09 UTC, hongsups commented on papers/Hongsup_Shin/Hongsup_Shin.rst
> +I used an ensemble of a supervised and an unsupervised learning model. Due to the severe class imbalance between passes and failures (near 99% pass and 1% failure rate) in the training data, it is po
@deniederhut  It's the latter. In this case, do you think it would be okay to keep using the word "union" throughout the paper (which is the case for the current version)?

I found that I use the word "union" for the very first time in the introduction (the "Post-deployment analysis" section). I added a description of what it means (since your question also means that I didn't clarify enough).

2019-06-20 13:19 UTC, hongsups commented on papers/Hongsup_Shin/Hongsup_Shin.rst
> +   \text{UFS recovery rate} = \frac{\mathrm{card}(S_{\hat{y}=1})}{\mathrm{card}(S_{y=1})},
@deniederhut Oh! I just realized that what I was computing is essentially the same as Jaccard similarity. The union would be the total set of UFS and the intersection would be the ones that are found by the models, which is a subset of the total set. 

I guess when I think of Jaccard similarity as a metric for arbitrary sets A and B, I often automatically assume |A - B| or |B - A| is non-zero, meaning A doesn't belong to B or vice versa. In this case, if we define the UFS recovery rate as Jaccard similarity, the set of UFS found by the models would completely belong to the total set of UFS, so I think that's why I used the current formula. I am also thinking that the current formula might be more straightforward to the audience than Jaccard similarity, so I would like to keep it as it is.

2019-06-20 13:21 UTC, hongsups commented on papers/Hongsup_Shin/Hongsup_Shin.rst
> +For the *snapshot* dataset, the testing data (50% holdout data in 10 different sets; each set is generated independently) shows that the union predictions from the trained supervised and unsupervised
Fixed. 

Haha, thanks. I found permutation tests easy to execute and also provides a good simple sanity check for any metrics.

2019-06-20 13:21 UTC, hongsups commented on papers/Hongsup_Shin/Hongsup_Shin.rst
> +After the deployment, model performance started showing high variability, sometimes very different from the pre-deployment model performance. Figure :ref:`Fig.4` shows the model performance of the fi
Fixed.

2019-06-20 13:21 UTC, hongsups commented on papers/Hongsup_Shin/Hongsup_Shin.rst
> +It is suspected that the fluctuation in model performance (Fig. :ref:`Fig.4`) might be related to the quality of the test candidates. This is because the test candidates were generated randomly in th
Fixed.

2019-06-20 13:23 UTC, hongsups commented
@deniederhut Thanks for the quick response, Dillon. I added the doi info and incorporated your feedback. Just updated the manuscript.

2019-06-21 19:53 UTC, hongsups commented
@deniederhut @mepa Hey all, I made a few minor changes to polish the manuscript. If you have any questions or comments, please let me know!

2019-06-22 03:09 UTC, deniederhut commented on papers/Hongsup_Shin/Hongsup_Shin.rst
> +I used an ensemble of a supervised and an unsupervised learning model. Due to the severe class imbalance between passes and failures (near 99% pass and 1% failure rate) in the training data, it is po
👍

2019-06-22 03:11 UTC, deniederhut commented on papers/Hongsup_Shin/Hongsup_Shin.rst
> +   \text{UFS recovery rate} = \frac{\mathrm{card}(S_{\hat{y}=1})}{\mathrm{card}(S_{y=1})},
Ah okay -- I had assumed that the sets would be non-overlapping.  Could I ask you to add this as a footnote to the formula?

2019-06-22 03:59 UTC, deniederhut requested changes
I think we're almost there! Just a few language suggestions in some of the new sections.

2019-06-22 03:59 UTC, deniederhut commented on papers/Hongsup_Shin/Hongsup_Shin.rst
> +   When designing microprocessors, engineers must verify whether the proposed design, defined in hardware description language, does what is intended. During this verification process, engineers run
"address the issue, such as identifying"

2019-06-22 03:59 UTC, deniederhut commented on papers/Hongsup_Shin/Hongsup_Shin.rst
> +In practice, engineers build a testbench to house all the components that are needed for the verification process: test generator, interface, driver, monitor, model, and scoreboard. To run tests, ver
"A test is identified as a failure"

2019-06-22 03:59 UTC, deniederhut commented on papers/Hongsup_Shin/Hongsup_Shin.rst
> +I used both supervised and unsupervised models to address the severe class imbalance problem and used the union of the prediction from both models. This means, a test is predicted as failure when at
"This means, a test is predicted to fail when at least one of the two models predict it will fail."

2019-06-22 03:59 UTC, deniederhut commented on papers/Hongsup_Shin/Hongsup_Shin.rst
> +The input data was preprocessed based on the domain knowledge of the verification engineers. In the raw data, roughly 70% of the data was missing. This is because when the value of an input setting i
"In the raw data, roughly 70% of the data was missing, which corresponds to input settings that were not modified from the defaults."

"Using a software analogy"

2019-06-22 03:59 UTC, deniederhut commented on papers/Hongsup_Shin/Hongsup_Shin.rst
> +To address the random-draw effect, it might be better to use these likelihood metrics. With these metrics, the test candidates can be ranked and the tool can choose the top candidates, which are more
"is very fast and doesn't cost much" or "is very fast and doesn't consume many resources"

2019-06-22 03:59 UTC, deniederhut commented on papers/Hongsup_Shin/Hongsup_Shin.rst
> +Since all scenarios have the same :math:`K=400`, it is possible to compare the unique failure signature (UFS) counts (the y axis in Fig. :ref:`Fig.7`) instead of the UFS recovery rate. Although the m
"it still consumes computational resources"

2019-06-22 04:43 UTC, hongsups commented on papers/Hongsup_Shin/Hongsup_Shin.rst
> +   When designing microprocessors, engineers must verify whether the proposed design, defined in hardware description language, does what is intended. During this verification process, engineers run
Fixed.

2019-06-22 04:43 UTC, hongsups commented on papers/Hongsup_Shin/Hongsup_Shin.rst
> +In practice, engineers build a testbench to house all the components that are needed for the verification process: test generator, interface, driver, monitor, model, and scoreboard. To run tests, ver
Fixed.

2019-06-22 04:44 UTC, hongsups commented on papers/Hongsup_Shin/Hongsup_Shin.rst
> +I used both supervised and unsupervised models to address the severe class imbalance problem and used the union of the prediction from both models. This means, a test is predicted as failure when at
Fixed.

2019-06-22 04:45 UTC, hongsups commented on papers/Hongsup_Shin/Hongsup_Shin.rst
> +The input data was preprocessed based on the domain knowledge of the verification engineers. In the raw data, roughly 70% of the data was missing. This is because when the value of an input setting i
Fixed.

2019-06-22 04:46 UTC, hongsups commented on papers/Hongsup_Shin/Hongsup_Shin.rst
> +To address the random-draw effect, it might be better to use these likelihood metrics. With these metrics, the test candidates can be ranked and the tool can choose the top candidates, which are more
Decide to go with the first suggestion! Fixed.

2019-06-22 04:46 UTC, hongsups commented on papers/Hongsup_Shin/Hongsup_Shin.rst
> +Since all scenarios have the same :math:`K=400`, it is possible to compare the unique failure signature (UFS) counts (the y axis in Fig. :ref:`Fig.7`) instead of the UFS recovery rate. Although the m
Fixed.

2019-06-22 04:48 UTC, hongsups commented
@deniederhut Thanks for another review! Just updated the manuscript based on your comments!

2019-06-22 14:39 UTC, deniederhut commented
Awesome! And just in case you missed this in the giant thread of comments:

https://github.com/scipy-conference/scipy_proceedings/pull/468#discussion_r296432110

2019-06-23 02:44 UTC, hongsups commented on papers/Hongsup_Shin/Hongsup_Shin.rst
> +   \text{UFS recovery rate} = \frac{\mathrm{card}(S_{\hat{y}=1})}{\mathrm{card}(S_{y=1})},
Ah I missed this. Added this as a footnote to the formula.

2019-06-23 02:44 UTC, hongsups commented
> Awesome! And just in case you missed this in the giant thread of comments:
> 
> [#468 (comment)](https://github.com/scipy-conference/scipy_proceedings/pull/468#discussion_r296432110)

@deniederhut Thanks for pointing it out! I missed it indeed. Just updated the manuscript with the footnote.

2019-06-23 21:19 UTC, mepa commented on papers/Hongsup_Shin/Hongsup_Shin.rst
> +   When designing microprocessors, engineers must verify whether the proposed design, defined in hardware description language, does what is intended. During this verification process, engineers run
- "and unsupervised (outlier detection) models"
- "does not interfere *with* the existing"
- "in the internal cluster" -> in which internal cluster?

2019-06-23 21:19 UTC, mepa commented on papers/Hongsup_Shin/Hongsup_Shin.rst
> +Hardware verification is the process of checking that a given design correctly implements the specifications, which is the technical description of the computer's components and capabilities. It is r
- what do "stimuli" mean in this context?
- "direct tests *toward* a certain direction", or "*in*"

Overall this paragraph is clear, informative, and motivates the approach taken in the paper. Really nice intro!

2019-06-23 21:19 UTC, mepa commented on papers/Hongsup_Shin/Hongsup_Shin.rst
> +   Overview of the prototype pipeline. Top: the existing workflow (randomized testing). Bottom: the complementary machine learning (ML) flow. In the final deployed version, approximately 1000 test ca
- "This corresponds to 10% of the number of tests"

2019-06-23 21:19 UTC, mepa commented on papers/Hongsup_Shin/Hongsup_Shin.rst
> +Hardware verification can be compared to unit testing in software engineering, especially since design functionalities are realized in hardware description language (HDL) like Verilog. Similar to sof
I like the analogy :)

2019-06-23 21:19 UTC, mepa commented on papers/Hongsup_Shin/Hongsup_Shin.rst
> +In practice, engineers build a testbench to house all the components that are needed for the verification process: test generator, interface, driver, monitor, model, and scoreboard. To run tests, ver
- "when the desirable output" --> remove the second "the"
- "or failure, *the* testbench ... of *the* failure"

Why do engineers want to see a large variety of failures? What does absence of variety imply?

2019-06-23 21:19 UTC, mepa commented on papers/Hongsup_Shin/Hongsup_Shin.rst
> +Random generation of the test settings in the test generator is intended to run a batch of tests automatically almost daily to explore random parts of the design with efficiency. In practice, enginee
- "which either turns a setting on and off"
- "Unfortunately, *the* testbench"
- "which value ended up getting chosen eventually"
- "which implies *that* the data"

It might be worth italicizing the sentence "This is why building a machine learning model is challenging..." as this is a key point.

2019-06-23 21:19 UTC, mepa commented on papers/Hongsup_Shin/Hongsup_Shin.rst
> +Simulation-based testing is run almost every day via a testbench. Every simulated test and the outcome (i.e., test success (pass or failure) and UFS if a test has failed) is stored in a database. To
- "Every simulated test and outcome"
- "two datasets *are*... *is* generated from"

Does the total number of features (i.e. columns, test settings, stimuli) change as the design (and testbench) matures?

2019-06-23 21:19 UTC, mepa commented on papers/Hongsup_Shin/Hongsup_Shin.rst
> +The input data was preprocessed based on the domain knowledge of the verification engineers. In the raw data, roughly 70% of the data was missing. This is because when the value of an input setting i
Would it make sense to also check for correlations and drop additional columns?

2019-06-23 21:19 UTC, mepa commented on papers/Hongsup_Shin/Hongsup_Shin.rst
> +Due to the frequent changes in data generation process, I decided to use algorithms robust to frequent retraining and tuning (i.e., faster training time). I used a group of non-neural-net scikit-lear
What does a null value mean in these tests? Is it that a particular stimulus is not possible/relevant/used for a particular test, so the field is empty?

2019-06-23 21:19 UTC, mepa commented on papers/Hongsup_Shin/Hongsup_Shin.rst
> +Engineers care more about the unique failure signatures than simple binary labels. When a number of failures are found in test simulation, if the majority have the same failure signatures, it means e
I asked a similar question above, but still not totally clear on why an engineer wants to maximize the variety of failures. Don't they ultimately want to minimize the total number of failures, or does high number of failures but with low variety indicate that the tests are not sufficiently probing the design?

2019-06-23 21:19 UTC, mepa commented on papers/Hongsup_Shin/Hongsup_Shin.rst
> +   First 17 days (3k-4k tests per day) of model performance (efficiency) after deployment. The performance fluctuates widely (all the way up to more than 5 then sometimes plummet to zero). Note that
Is the number of columns fixed, or can it fluctuate from day to day?

2019-06-23 21:19 UTC, mepa commented on papers/Hongsup_Shin/Hongsup_Shin.rst
> +Several productions engineers and I wrote Python and shell scripts to build a command-line tool that verification engineers can run without changing their main *random* flow. The script takes test ca
- "number of test candidates"
- "the computational resources"

What is the range or variance of number of test candidates around 1k and flagged tests around 400? Is there a lower bound below which evaluated model performance for a particular day is unstable?

2019-06-23 21:19 UTC, mepa commented on papers/Hongsup_Shin/Hongsup_Shin.rst
> +During the initial post-deployment period, the models were manually retrained whenever major changes were made either in the tool or in the design. To automate the retraining process, I tested ideas
- "To determine"

2019-06-23 21:19 UTC, mepa commented on papers/Hongsup_Shin/Hongsup_Shin.rst
> +The weight decay is related to how *fresh* the data is. If tests were generated more recently, they might be more important because the design then is more similar to the today's compared to older te
- "to the current day's"
- "Once the weights are computed, they are"
- "multiple tests are generated"
- "weight adjustment is added on top"

2019-06-23 21:19 UTC, mepa commented on papers/Hongsup_Shin/Hongsup_Shin.rst
> +It is suspected that the fluctuation in model performance (Fig. :ref:`Fig.4`) might be related to the quality of the test candidates. This is because the test candidates were generated randomly in th
Ok, this paragraph and Fig. 6 more or less answer my earlier question about the relationship between number of test candidates and model performance. Nice results.

2019-06-23 21:19 UTC, mepa commented on papers/Hongsup_Shin/Hongsup_Shin.rst
> +To address the random-draw effect, it might be better to use these likelihood metrics. With these metrics, the test candidates can be ranked and the tool can choose the top candidates, which are more
- "can simply choose the top" -> remove the second "the"

2019-06-23 21:19 UTC, mepa commented on papers/Hongsup_Shin/Hongsup_Shin.rst
> +This simulation was based on the 3k-4k tests that were run daily. To compare the model performance and the random-testing results, it was important to use the same set of tests for the simulation; th
What action is taken upon discovering a "new" UFS?

2019-06-23 21:19 UTC, mepa commented on papers/Hongsup_Shin/Hongsup_Shin.rst
> +To address these issues, this study shows a prototype that provides test candidates and filters out failure-prone tests instead of trying to guide the testbench itself. To work with the class imbalan
Could you please correct grammar and rephrase the last sentence for clarity? For example, I'm not sure what "machine learning engineering product" refers to.

Finally, a question just to ensure my understanding: Does the approach presented effectively down-sample test candidates yielding the same UFS, which are not valuable tests to run because once a particular UFS is known it can be fixed, no matter the number of times it is met?

2019-06-23 21:19 UTC, mepa commented on papers/Hongsup_Shin/Hongsup_Shin.rst
> +To address these issues, this study shows a prototype that provides test candidates and filters out failure-prone tests instead of trying to guide the testbench itself. To work with the class imbalan
@hongsups, this is an interesting paper and your investigation is quite thorough. I enjoyed reading about the post-deployment aspects which, I agree, are not as often presented but are crucial in building actual machine learning products.

2019-06-23 22:02 UTC, hongsups commented on papers/Hongsup_Shin/Hongsup_Shin.rst
> +   When designing microprocessors, engineers must verify whether the proposed design, defined in hardware description language, does what is intended. During this verification process, engineers run
Hi @mepa thanks for the review! I fixed the suggestions and for the last bullet point, it's the HPC that our production team uses, so I just rephrased it as "in an interval high performance computing (HPC) cluster"

2019-06-23 22:11 UTC, hongsups commented on papers/Hongsup_Shin/Hongsup_Shin.rst
> +Hardware verification is the process of checking that a given design correctly implements the specifications, which is the technical description of the computer's components and capabilities. It is r
- I added a sentence to provide the details on "stimuli". "These stimuli can be considered as arbitrary values that control certain functionalities of the design that were expressed in hardware description language such as whether to turn on or off a specific setting."
- Fixed. Used "toward"

2019-06-23 22:12 UTC, hongsups commented on papers/Hongsup_Shin/Hongsup_Shin.rst
> +   Overview of the prototype pipeline. Top: the existing workflow (randomized testing). Bottom: the complementary machine learning (ML) flow. In the final deployed version, approximately 1000 test ca
Fixed.

2019-06-23 22:14 UTC, hongsups commented on papers/Hongsup_Shin/Hongsup_Shin.rst
> +Hardware verification can be compared to unit testing in software engineering, especially since design functionalities are realized in hardware description language (HDL) like Verilog. Similar to sof
Thank you! :)

2019-06-23 22:22 UTC, hongsups commented on papers/Hongsup_Shin/Hongsup_Shin.rst
> +In practice, engineers build a testbench to house all the components that are needed for the verification process: test generator, interface, driver, monitor, model, and scoreboard. To run tests, ver
- Fixed.
- Really good question! I added a sentence to elaborate the reason at the end of the paragraph. "Having a larger variety of failures is important because it means the tests have explored various parts of the design and thus, it's likely to discover failures associated with rare edge cases or problems overlooked before."

2019-06-23 22:24 UTC, hongsups commented on papers/Hongsup_Shin/Hongsup_Shin.rst
> +Random generation of the test settings in the test generator is intended to run a batch of tests automatically almost daily to explore random parts of the design with efficiency. In practice, enginee
Fixed. And italicized the sentence. Good idea!

2019-06-23 22:49 UTC, hongsups commented on papers/Hongsup_Shin/Hongsup_Shin.rst
> +Simulation-based testing is run almost every day via a testbench. Every simulated test and the outcome (i.e., test success (pass or failure) and UFS if a test has failed) is stored in a database. To
- Fixed.
- This is also a really good question! I added explanation at the end of the "data preprocessing" because I think it is more related to how to handle the data if the settings don't match. Here's the description: "Whenever a change is made to the design, the set of the input settings may change. In this project, on average, less than 5 columns (including 0) were either added or removed every time the tests were run. When building a training dataset from tests across multiple days with different input settings, I used the union to include all. Here, to impute missing values from the settings absent in the past, I used the domain knowledge of the verification engineers. When preprocessing a set of new test candidates for prediction, I dropped the input settings that are absent in the feature set of the pre-trained models."

2019-06-23 22:54 UTC, hongsups commented on papers/Hongsup_Shin/Hongsup_Shin.rst
> +The input data was preprocessed based on the domain knowledge of the verification engineers. In the raw data, roughly 70% of the data was missing. This is because when the value of an input setting i
Yes, absolutely. My team is actually working on updating the preprocessing module and we indeed just implemented a correlation check. The current study only has a duplicate check, so I will not include it in the manuscript.

2019-06-23 23:00 UTC, hongsups commented on papers/Hongsup_Shin/Hongsup_Shin.rst
> +Due to the frequent changes in data generation process, I decided to use algorithms robust to frequent retraining and tuning (i.e., faster training time). I used a group of non-neural-net scikit-lear
So often if a setting is null, it means one of the two things:
- The setting is absent or turned off.
- The setting is not specified by users.
In the first case, this happened for binary columns ([0, 1]), so it was pretty straightforward to encode. For the second one, I had to ask the engineers to track down which specific default values their code uses because it is not specified because their tests were just using default values. Even for the first case, the engineers' default value matched to how I handled the data (because the columns have names such as "setting_A_on", etc.).

I added this information in the "data preprocessing" part as such:
"Using a software analogy, this is similar to not having to specify an input argument value in a function, if it already has a default value for that argument. The engineers were able to obtain the default values, which fixed the missing data issue."

If you think I need more clarification, please let me know!

2019-06-23 23:09 UTC, hongsups commented on papers/Hongsup_Shin/Hongsup_Shin.rst
> +Engineers care more about the unique failure signatures than simple binary labels. When a number of failures are found in test simulation, if the majority have the same failure signatures, it means e
I had the same question when I started working on this project but interestingly they actually want to introduce failures more because failures are bugs and they want to find more "new" bugs to fix them. And finding more unique failure signatures can help them discover novel failures. 

I edited the paragraph and added "the ultimate goal of verification is to find every possible type of failure (bug) to make the design bug-free. The more UFS engineers find, the more likely to find novel failures. Moreover, if we find more UFS by running fewer tests, it bring higher efficiency in the procedure." to elaborate.

2019-06-23 23:10 UTC, hongsups commented on papers/Hongsup_Shin/Hongsup_Shin.rst
> +   First 17 days (3k-4k tests per day) of model performance (efficiency) after deployment. The performance fluctuates widely (all the way up to more than 5 then sometimes plummet to zero). Note that
Fixed. Added some information in "data preprocessing"

2019-06-23 23:14 UTC, hongsups commented on papers/Hongsup_Shin/Hongsup_Shin.rst
> +During the initial post-deployment period, the models were manually retrained whenever major changes were made either in the tool or in the design. To automate the retraining process, I tested ideas
Fixed.

2019-06-23 23:15 UTC, hongsups commented on papers/Hongsup_Shin/Hongsup_Shin.rst
> +The weight decay is related to how *fresh* the data is. If tests were generated more recently, they might be more important because the design then is more similar to the today's compared to older te
Fixed.

2019-06-23 23:16 UTC, hongsups commented on papers/Hongsup_Shin/Hongsup_Shin.rst
> +Several productions engineers and I wrote Python and shell scripts to build a command-line tool that verification engineers can run without changing their main *random* flow. The script takes test ca
- Fixed.
- I just saw your comment below regarding Fig. 6. I will take it as the question answered. Thanks for many good question!

2019-06-23 23:17 UTC, hongsups commented on papers/Hongsup_Shin/Hongsup_Shin.rst
> +To address the random-draw effect, it might be better to use these likelihood metrics. With these metrics, the test candidates can be ranked and the tool can choose the top candidates, which are more
Fixed.

2019-06-23 23:19 UTC, hongsups commented on papers/Hongsup_Shin/Hongsup_Shin.rst
> +This simulation was based on the 3k-4k tests that were run daily. To compare the model performance and the random-testing results, it was important to use the same set of tests for the simulation; th
Once a new UFS is found, the rest of the process is very manual. Engineers have to check the failure log to locate the bug, find the cause and fix it. I am adding this information in the introduction: "Once a new UFS is found, engineers starts a debugging process to fix the failure."

2019-06-23 23:27 UTC, hongsups commented on papers/Hongsup_Shin/Hongsup_Shin.rst
> +To address these issues, this study shows a prototype that provides test candidates and filters out failure-prone tests instead of trying to guide the testbench itself. To work with the class imbalan
- Yes, you are correct. I added "This indicates, engineers can run fewer tests to retrieve similar number of unique failure signatures." in the first paragraph of Conclusions.

- I changed the last part of the Conclusions like this:
"In summary, this study proves that machine learning approach can be used for failure detection in hardware verification. It also provides an example to work under practical constraints and investigate performance-related issues in building actual machine learning products."

2019-06-23 23:29 UTC, hongsups commented on papers/Hongsup_Shin/Hongsup_Shin.rst
> +To address these issues, this study shows a prototype that provides test candidates and filters out failure-prone tests instead of trying to guide the testbench itself. To work with the class imbalan
@mepa Thanks for many excellent comments, Meghann! It's always such a rare opportunity to get feedback on my work from other data scientist, so I genuinely appreciate it!

2019-06-23 23:34 UTC, mepa commented on papers/Hongsup_Shin/Hongsup_Shin.rst
> +Due to the frequent changes in data generation process, I decided to use algorithms robust to frequent retraining and tuning (i.e., faster training time). I used a group of non-neural-net scikit-lear
I see. So the data *had* "more than 50%" sparsity, but you were able to fill in missing values based on gaining knowledge of the default values. Were the input data to the model completely dense then, or were there still missing values?

2019-06-23 23:39 UTC, hongsups commented
@mepa @deniederhut Hey y'all, I just updated the manuscript based on the recent review from @mepa. I noticed that my replies to @mepa's comments don't always appear in the main PR page but they do appear when I click the "View changes" button, so please keep this in mind. I think I answered every comment but if there's anything missing, please let me know. Thanks for working on this even during the weekend!

2019-06-24 04:43 UTC, mepa commented on papers/Hongsup_Shin/Hongsup_Shin.rst
> +In practice, engineers build a testbench to house all the components that are needed for the verification process: test generator, interface, driver, monitor, model, and scoreboard. To run tests, ver
Thanks, I think I now understand the reason verification engineers want to maximize UFS. Is it because various inputs/stimuli to tests can identify the same bug (UFS) in the HDL code, which assumedly requires just one fix? Hence, we want to find all unique bugs, and it's a waste of resources/time to create tests that identify the same UFS.

2019-06-24 04:43 UTC, mepa commented on papers/Hongsup_Shin/Hongsup_Shin.rst
> +To address these issues, this study shows a prototype that provides test candidates and filters out failure-prone tests instead of trying to guide the testbench itself. To work with the class imbalan
- "that **a** machine learning approach"

@hongsups Very glad for the opportunity to review your work!

2019-06-24 04:59 UTC, hongsups commented on papers/Hongsup_Shin/Hongsup_Shin.rst
> +To address these issues, this study shows a prototype that provides test candidates and filters out failure-prone tests instead of trying to guide the testbench itself. To work with the class imbalan
Fixed. Thank you!

2019-06-24 17:19 UTC, hongsups commented on papers/Hongsup_Shin/Hongsup_Shin.rst
> +Due to the frequent changes in data generation process, I decided to use algorithms robust to frequent retraining and tuning (i.e., faster training time). I used a group of non-neural-net scikit-lear
Ah, so when I meant 50% sparsity, it meant literally more than 50% were 0s. This was after the imputation. I will add this to the manuscript.

2019-06-25 02:20 UTC, deniederhut commented
Thanks for being so diligent about responding to our suggestions! 

@mepa do you feel this paper is ready for inclusion in the proceedings?

2019-06-25 23:28 UTC, mepa commented
@deniederhut yes, LGTM

2019-06-26 01:00 UTC, deniederhut approved these changes

2019-06-26 01:00 UTC, deniederhut commented
Sweet. Thanks everyone!

2019-06-26 01:31 UTC, hongsups commented
@deniederhut @mepa Thank you so much!

2019-07-03 13:25 UTC, merged