Paper: National Advancement of Data Science Education
scipy-conference/scipy_proceedings pull request #478
Opened 2019-05-23 04:39 UTC by amalbh1999

National Advancement of Data Science Education by Anthony Suen, Alan Liang and Amal Bhatnagar-- an exploration of expanding data science education across undergraduate institutions across the country by creating an introductory data science foundation course, scalable infrastructure, and modularizing content

2019-05-23 11:36 UTC, deniederhut commented
Hey! Thanks for submitting. It looks like your paper build is failing because there are no authors listed. You can see an example of how to do this [in the 00_vanderwalt example paper](https://raw.githubusercontent.com/scipy-conference/scipy_proceedings/2019/papers/00_vanderwalt/00_vanderwalt.rst)

2019-05-24 15:27 UTC, deniederhut commented
Hi! This paper needs to build at procbuild.scipy.org before it can be reviewed. Have you had a chance to fix the authors section?

2019-05-24 21:01 UTC, amalbh1999 commented
I fixed the authors issue. However, it now says "Build failed, no pdf can be found" under http://procbuild.scipy.org/. When I run ./make_paper.sh papers/Amal_Bhatnagar (for ./make_paper.sh papers/firstname_surname) in my terminal as given in the instructions, it gives the error "/bin/sh: pdflatex: command not found". I looked online for advice for similar situations but it still doesn't work.

2019-05-24 21:44 UTC, amalbh1999 commented
Fixed! It is up on procbuild.scipy.org.

2019-05-24 22:57 UTC, deniederhut commented
Hooray! I'm glad everything is working now. 

I have an email with some questions about local builds that seem to be missing from GitHub - I guess you deleted the comment? To answer the question you had, the error code you pasted probably has to do with a missing or incorrect installation of latex. The README has instructions for [completing the installation](https://github.com/scipy-conference/scipy_proceedings#requirements), but they're a bit sparse and sort of assume you are running Linux. Let me know if you still want help with this 🙂

2019-06-10 19:19 UTC, awalin commented
The author made strong and important points on cross-department collaboration.

2019-06-10 19:20 UTC, awalin approved these changes

2019-06-21 16:29 UTC, stargaser requested changes
@amalbh1999 I am one of the proceedings committee members, stepping in to give your paper some additional review. Thank you for this submission. I think it is nearly there. I am requesting some changes, mainly regarding references and citations, and some from proofreading of the manuscript.

- I found it odd to encounter in-text citations only at the end of Section 3. The paper would be improved by some more citations and links.
- For references, when DOIs are available, these should be included, per the guidelines for authors.
- I was often reminded of a paper from SciPy2018 -- after finishing my first read of this manuscript, I looked it up and realized it is also had Anthony Suen as first author. Please cite it (including DOI).
- For the links or references, please use references in square brackets followed by an underscore, in-text, and the same square-brackets reference in the references section. This will create a link in the PDF fore each reference. For examples, please see the [00_vanderwalt](https://raw.githubusercontent.com/scipy-conference/scipy_proceedings/2019/papers/00_vanderwalt/00_vanderwalt.rst) example paper, or even  [the 2018 submission](https://github.com/scipy-conference/scipy_proceedings/pull/418).

2019-06-21 16:29 UTC, stargaser commented on papers/Amal_Bhatnagar/NationalAdvancementofDataScience.rst
> +MacKenzie, Donald A. 1981. *Statistics in Britain: 1865-1930; The Social
not cited in the text

2019-06-21 16:29 UTC, stargaser commented on papers/Amal_Bhatnagar/NationalAdvancementofDataScience.rst
> +Hacking, Ian. 1996. Normal People. Pp. 59-71 in David Olson and Nancy
Not cited in the text.

2019-06-21 16:29 UTC, stargaser commented on papers/Amal_Bhatnagar/NationalAdvancementofDataScience.rst
> +Hicks, Marie. 2017. *Programmed Inequality: How Britain Discarded Women
Not cited in the text.

2019-06-21 16:29 UTC, stargaser commented on papers/Amal_Bhatnagar/NationalAdvancementofDataScience.rst
> +Light, Jennifer S. 1999. When computers were women. *Technology and
Not cited in the text.

2019-06-21 16:29 UTC, stargaser commented on papers/Amal_Bhatnagar/NationalAdvancementofDataScience.rst
> +Implementation of a data science course in a scalable way requires
While reading this section, I kept thinking back to [this paper from SciPy 2018](http://conference.scipy.org/proceedings/scipy2018/anthony_suen_laura_noren_alan_liang_andrea_tu.html). No wonder, the first author is also Anthony Suen! Please cite it in this section.

2019-06-21 16:29 UTC, stargaser commented on papers/Amal_Bhatnagar/NationalAdvancementofDataScience.rst
> +growing rapidly, but also largely simultaneous and in an uncoordinated
```suggestion
growing rapidly, but also largely simultaneously and in an uncoordinated
```

2019-06-21 16:29 UTC, stargaser commented on papers/Amal_Bhatnagar/NationalAdvancementofDataScience.rst
> +as the “Workshop on Theoretical Foundations of Data Science,” “The Park
Please, include links, or references if available, to these workshops -- where can a reader find more information?

2019-06-21 16:29 UTC, stargaser commented on papers/Amal_Bhatnagar/NationalAdvancementofDataScience.rst
> +broken down core topics including *1)* **Integrating and Serving across
It would help readability to break these out into bullet points.

2019-06-21 16:29 UTC, stargaser commented on papers/Amal_Bhatnagar/NationalAdvancementofDataScience.rst
> +to its system infrastructure and share them at the workshop. With
```suggestion
to its system infrastructure that were shared at the workshop. With
```

2019-06-21 16:29 UTC, stargaser commented on papers/Amal_Bhatnagar/NationalAdvancementofDataScience.rst
> +interested professors and instructors across the country 41 instructors
```suggestion
interested professors and instructors across the country. The workshop brought together 41 instructors
```
The organizers put out a call, and the 41 participants came to the workshop -- do I understand that correctly?

2019-06-21 16:29 UTC, stargaser commented on papers/Amal_Bhatnagar/NationalAdvancementofDataScience.rst
> +Science education forward at their institutions participants
```suggestion
Science education forward at their institutions. Participants
```

2019-06-21 16:29 UTC, stargaser commented on papers/Amal_Bhatnagar/NationalAdvancementofDataScience.rst
> +broken down core topics including *1)* **Integrating and Serving across
```suggestion
broken down into core topics including *1)* **Integrating and Serving across
```

2019-06-21 16:29 UTC, stargaser commented on papers/Amal_Bhatnagar/NationalAdvancementofDataScience.rst
> +include randomized controlled trials in Development Economics published
References to these examples would be good if they are available.

2019-06-21 16:29 UTC, stargaser commented on papers/Amal_Bhatnagar/NationalAdvancementofDataScience.rst
> +foundational data science course slows students learning and limits the
```suggestion
foundational data science course slows students' learning and limits the
```

2019-06-21 16:29 UTC, stargaser commented on papers/Amal_Bhatnagar/NationalAdvancementofDataScience.rst
> +including introductory Data Science course is accompanied by a series of
```suggestion
including introductory Data Science courses accompanied by a series of
```

2019-06-21 16:29 UTC, stargaser commented on papers/Amal_Bhatnagar/NationalAdvancementofDataScience.rst
> +for inserting in other type of (usually non data science) courses in
```suggestion
for inserting in other types of (usually non data science) courses in
```

2019-06-21 16:29 UTC, stargaser commented on papers/Amal_Bhatnagar/NationalAdvancementofDataScience.rst
> +faculty to encourage faculty to engage and innovate their curriculum.
```suggestion
faculty to encourage them to engage and innovate their curricula.
```
Please clarify: were these bootcamps open to faculty, but also to the grad students and postdocs mentioned in the next sentence? Perhaps should say "aimed at faculty" rather than just "open to faculty".

2019-06-21 16:29 UTC, stargaser commented on papers/Amal_Bhatnagar/NationalAdvancementofDataScience.rst
> +campus Learning Management Systems (LMS), eg Canvas. For institutions
I am not familiar with Canvas. Would you please include a link or a reference?

2019-06-21 16:29 UTC, stargaser commented on papers/Amal_Bhatnagar/NationalAdvancementofDataScience.rst
> +come with too many question marks for many institutions faculty to make
```suggestion
come with too many question marks for many institutions' faculty to make
```

2019-06-21 16:29 UTC, stargaser commented on papers/Amal_Bhatnagar/NationalAdvancementofDataScience.rst
> +open online course, or MOOC, version, which see more than 1,500 students
```suggestion
open online course, or MOOC, version, which sees more than 1,500 students
```

2019-06-21 16:29 UTC, stargaser commented on papers/Amal_Bhatnagar/NationalAdvancementofDataScience.rst
> +Implementation and integrating the new course to fit in the overall
```suggestion
Implementating and integrating the new course to fit in the overall
```

2019-06-21 16:29 UTC, stargaser commented on papers/Amal_Bhatnagar/NationalAdvancementofDataScience.rst
> +tailor it to fit in with the current institution curriculum will go a
```suggestion
tailor it to fit in with the current institutional curriculum will go a
```

2019-06-25 12:24 UTC, amalbh1999 commented on papers/Amal_Bhatnagar/NationalAdvancementofDataScience.rst
> +growing rapidly, but also largely simultaneous and in an uncoordinated
Edited, thank you!

2019-06-25 12:25 UTC, amalbh1999 commented on papers/Amal_Bhatnagar/NationalAdvancementofDataScience.rst
> +broken down core topics including *1)* **Integrating and Serving across
Edited

2019-06-25 12:27 UTC, amalbh1999 commented on papers/Amal_Bhatnagar/NationalAdvancementofDataScience.rst
> +to its system infrastructure and share them at the workshop. With
Edited

2019-06-25 12:28 UTC, amalbh1999 commented on papers/Amal_Bhatnagar/NationalAdvancementofDataScience.rst
> +interested professors and instructors across the country 41 instructors
Yes, that is correct. I edited it to be more clear. Thanks.

2019-06-25 12:28 UTC, amalbh1999 commented on papers/Amal_Bhatnagar/NationalAdvancementofDataScience.rst
> +Science education forward at their institutions participants
Edited.

2019-06-25 12:29 UTC, amalbh1999 commented on papers/Amal_Bhatnagar/NationalAdvancementofDataScience.rst
> +broken down core topics including *1)* **Integrating and Serving across
Edited

2019-06-25 12:29 UTC, amalbh1999 commented on papers/Amal_Bhatnagar/NationalAdvancementofDataScience.rst
> +foundational data science course slows students learning and limits the
Edited

2019-06-25 12:29 UTC, amalbh1999 commented on papers/Amal_Bhatnagar/NationalAdvancementofDataScience.rst
> +including introductory Data Science course is accompanied by a series of
Edited

2019-06-25 12:30 UTC, amalbh1999 commented on papers/Amal_Bhatnagar/NationalAdvancementofDataScience.rst
> +for inserting in other type of (usually non data science) courses in
Edited

2019-06-25 12:36 UTC, amalbh1999 commented on papers/Amal_Bhatnagar/NationalAdvancementofDataScience.rst
> +faculty to encourage faculty to engage and innovate their curriculum.
They were aimed at faculty (edited to make it more clear). Grad students and postdocs are mentioned to add another way how data science has been implemented

2019-06-25 12:37 UTC, amalbh1999 commented on papers/Amal_Bhatnagar/NationalAdvancementofDataScience.rst
> +come with too many question marks for many institutions faculty to make
Edited

2019-06-25 12:38 UTC, amalbh1999 commented on papers/Amal_Bhatnagar/NationalAdvancementofDataScience.rst
> +Implementation and integrating the new course to fit in the overall
Edited

2019-06-25 12:38 UTC, amalbh1999 commented on papers/Amal_Bhatnagar/NationalAdvancementofDataScience.rst
> +tailor it to fit in with the current institution curriculum will go a
Edited

2019-06-25 12:48 UTC, amalbh1999 commented on papers/Amal_Bhatnagar/NationalAdvancementofDataScience.rst
> +Light, Jennifer S. 1999. When computers were women. *Technology and
Thanks for the input on the citations. We are currently working on editing the paper on another platform and will upload the revised version to GitHub soon.

2019-06-26 03:59 UTC, amalbh1999 commented
We are in the process of editing the paper based on your comments and will upload it soon. Thanks

2019-06-26 13:54 UTC, awalin commented on papers/Amal_Bhatnagar/NationalAdvancementofDataScience.rst
> +Implementation and integrating the new course to fit in the overall
"Implementing"

2019-06-26 13:56 UTC, awalin commented
The paper needs an overall grammar and spell check but I really appreciate the idea behind this. One more thing to note is that, the curricula presented so far does not reflect much on anti-bias algorithms, and how to make Data science more inclusive. 'Bias and lack of fairness' in models is a big issue, and for a data science education that will be implemented in a broader population, this should be essential.

2019-07-03 02:01 UTC, deniederhut commented
Hi @amalbh1999 ! Were you able to respond to Dave's comments?

2019-07-04 06:38 UTC, amalbh1999 commented
We're having trouble converting the document. We're following the directions but are still getting errors as follows. Any help would be greatly appreciated. Thank you!

<img width="721" alt="Conversion Error 1" src="https://user-images.githubusercontent.com/34720104/60644605-79ed9700-9deb-11e9-9582-d68945c20d79.png">
<img width="698" alt="Conversion Error 2" src="https://user-images.githubusercontent.com/34720104/60644609-7c4ff100-9deb-11e9-8cf9-f3d7e8b1b80e.png">

2019-07-06 20:41 UTC, amalbh1999 commented
Hi @deniederhut @stargaser @awalin  Just following up on this. Do you have any advice on resolving the error from above?

2019-07-06 21:36 UTC, gforsyth commented
@amalbh1999 -- where are you seeing that error?  The current build at procbuild.scipy.org/ shows a successful build and I see what looks like the fully rendered draft here: http://procbuild.scipy.org/download/amalbh1999-2019

2019-07-06 21:45 UTC, amalbh1999 commented
@gforsyth Hi, the error occurs locally when converting the .rst to PDF format, specifically with ./make_paper.sh papers/firstname_surname . The draft on http://procbuild.scipy.org/download/amalbh1999-2019 is outdated and does not take into account our most recent edits. We would rather like to submit the version we are trying to upload to GitHub instead.

2019-07-06 21:48 UTC, gforsyth commented
Ahh. Ok. Can you commit and push the "broken" version? It will be much
easier to debug that way.

On Sat, Jul 6, 2019, 5:45 PM amalbh1999 <notifications@github.com> wrote:

> @gforsyth <https://github.com/gforsyth> Hi, the error occurs locally when
> converting the .rst to PDF format, specifically with ./make_paper.sh
> papers/firstname_surname . The draft on
> http://procbuild.scipy.org/download/amalbh1999-2019 is outdated and does
> not take into account our most recent edits. We would rather like to submit
> the version we are trying to upload to GitHub instead.
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub
> <https://github.com/scipy-conference/scipy_proceedings/pull/478?email_source=notifications&email_token=AA3OFR56GJ2TT7BMQQR3FP3P6EHAJA5CNFSM4HOZ4CKKYY3PNVWWK3TUL52HS4DFVREXG43VMVBW63LNMVXHJKTDN5WW2ZLOORPWSZGODZLAX4A#issuecomment-508955632>,
> or mute the thread
> <https://github.com/notifications/unsubscribe-auth/AA3OFRY5HRC6TV7DTCU7OCDP6EHAJANCNFSM4HOZ4CKA>
> .
>

2019-07-06 22:06 UTC, amalbh1999 commented
@gforsyth Just pushed it. It can be found above and https://github.com/scipy-conference/scipy_proceedings/pull/478/commits/03016fa0dca5bc3d20bb70e7d1b4569bb7f2bb42

2019-07-06 22:30 UTC, gforsyth commented on papers/Amal_Bhatnagar/AcceleratingtheAdvancementofDataScienceEducation.rst
> +(`*https://www.instructure.com/* `https://www.instructure.com/>`__), and
```suggestion
(`*https://www.instructure.com/*_ `<https://www.instructure.com/>`__), and
```

My RST is a bit rusty, but this should at least clear the error.

You can run `rst-lint` locally to find other issues if you first either

`pip install restructured-text`
or
`conda install -c conda-forge restructured-text`

2019-07-07 00:33 UTC, amalbh1999 commented
@gforsyth Thanks for your help so far. I ran rst-lint and keep getting two errors: 1) Explicit markup ends without a blank line; unexpected unindent, and 2) Inline emphasis start-string without end-string. I looked at online resources (like http://developer.mantidproject.org/Standards/DocumentationGuideForDevs.html#explicit-markup-ends-without-a-blank-line-unexpected-unindent) and other SciPy paper submissions' RST format to fix the errors but still can't seem to debug them. 

I just committed the most recent RST file.

2019-07-07 17:43 UTC, gforsyth reviewed
I've marked all the RST issues I could find and I can now build it locally.  The fatal error was coming from a composed unicode character in a reference last name. I've just removed the accent, which is terrible, but is the most expedient way to fix this.

2019-07-07 17:43 UTC, gforsyth commented on papers/Amal_Bhatnagar/AcceleratingtheAdvancementofDataScienceEducation.rst
> +thinking.*
```suggestion
thinking.
```

This `*` was unbalanced

2019-07-07 17:43 UTC, gforsyth commented on papers/Amal_Bhatnagar/AcceleratingtheAdvancementofDataScienceEducation.rst
> +science or statistics courses provide.*
```suggestion
science or statistics courses provide.
```

2019-07-07 17:43 UTC, gforsyth commented on papers/Amal_Bhatnagar/AcceleratingtheAdvancementofDataScienceEducation.rst
> +adopting institutions.  *
```suggestion
adopting institutions.*
```

2019-07-07 17:43 UTC, gforsyth commented on papers/Amal_Bhatnagar/AcceleratingtheAdvancementofDataScienceEducation.rst
> +Science with R. Retrieved from http://mdsr-book.github.io/
```suggestion
   Science with R. Retrieved from http://mdsr-book.github.io/	
```
All of these lines need to be indented or RST gets upset

2019-07-07 17:43 UTC, gforsyth commented on papers/Amal_Bhatnagar/AcceleratingtheAdvancementofDataScienceEducation.rst
> +and its consequences. Cambridge, MA: MIT Press.
```suggestion
   and its consequences. Cambridge, MA: MIT Press.	
```

2019-07-07 17:43 UTC, gforsyth commented on papers/Amal_Bhatnagar/AcceleratingtheAdvancementofDataScienceEducation.rst
> +statistical reasoning. Cambridge, MA: Harvard University Press.
```suggestion
   statistical reasoning. Cambridge, MA: Harvard University Press.	
```

2019-07-07 17:43 UTC, gforsyth commented on papers/Amal_Bhatnagar/AcceleratingtheAdvancementofDataScienceEducation.rst
> +police, and punish the poor. PICADOR.
```suggestion
   police, and punish the poor. PICADOR.	
```

2019-07-07 17:43 UTC, gforsyth commented on papers/Amal_Bhatnagar/AcceleratingtheAdvancementofDataScienceEducation.rst
> +Review, 38(1), supplement, 103-131. Retrieved from
```suggestion
   Review, 38(1), supplement, 103-131. Retrieved from
```

2019-07-07 17:43 UTC, gforsyth commented on papers/Amal_Bhatnagar/AcceleratingtheAdvancementofDataScienceEducation.rst
> +http://www.bruno-latour.fr/sites/default/files/46-TECHNOLOGY-DURABLE-GBpdf.pdf
```suggestion
   http://www.bruno-latour.fr/sites/default/files/46-TECHNOLOGY-DURABLE-GBpdf.pdf	
```

2019-07-07 17:43 UTC, gforsyth commented on papers/Amal_Bhatnagar/AcceleratingtheAdvancementofDataScienceEducation.rst
> +Sciences. (2018, May 02). Data Science for Undergraduates: Opportunities
```suggestion
   Sciences. (2018, May 02). Data Science for Undergraduates: Opportunities
```

2019-07-07 17:43 UTC, gforsyth commented on papers/Amal_Bhatnagar/AcceleratingtheAdvancementofDataScienceEducation.rst
> +and Options. Retrieved from https://doi.org/10.17226/25104
```suggestion
   and Options. Retrieved from https://doi.org/10.17226/25104	
```

2019-07-07 17:43 UTC, gforsyth commented on papers/Amal_Bhatnagar/AcceleratingtheAdvancementofDataScienceEducation.rst
> +reinforce racism. New York: New York University Press.
```suggestion
   reinforce racism. New York: New York University Press.	
```

2019-07-07 17:43 UTC, gforsyth commented on papers/Amal_Bhatnagar/AcceleratingtheAdvancementofDataScienceEducation.rst
> +inequality and threatens democracy. London: Penguin Books.
```suggestion
   inequality and threatens democracy. London: Penguin Books.	
```

2019-07-07 17:43 UTC, gforsyth commented on papers/Amal_Bhatnagar/AcceleratingtheAdvancementofDataScienceEducation.rst
> +Emergent challenges of computational agency. Colorado Technology Law
```suggestion
   Emergent challenges of computational agency. Colorado Technology Law
```

2019-07-07 17:43 UTC, gforsyth commented on papers/Amal_Bhatnagar/AcceleratingtheAdvancementofDataScienceEducation.rst
> +Journal, 203-218. Retrieved from
```suggestion
   Journal, 203-218. Retrieved from
```

2019-07-07 17:43 UTC, gforsyth commented on papers/Amal_Bhatnagar/AcceleratingtheAdvancementofDataScienceEducation.rst
> +https://ctlj.colorado.edu/wp-content/uploads/2015/08/Tufekci-final.pdf.
```suggestion
   https://ctlj.colorado.edu/wp-content/uploads/2015/08/Tufekci-final.pdf.	
```

2019-07-07 17:43 UTC, gforsyth commented on papers/Amal_Bhatnagar/AcceleratingtheAdvancementofDataScienceEducation.rst
> +.. [Desrosières 11] Desrosières, A. (2011). The politics of large numbers: A history of
```suggestion
.. [Desrosieres 11] Desrosieres, A. (2011). The politics of large numbers: A history of
```

This is terrible, but `pdflatex` has trouble with unicode and the most expedient way to handle it is to remove the composed character

2019-07-07 17:43 UTC, gforsyth commented on papers/Amal_Bhatnagar/AcceleratingtheAdvancementofDataScienceEducation.rst
> +inference [Bowker 08]_, [Desrosières 11]_, and the perpetuation
```suggestion
inference [Bowker 08]_, [Desrosieres 11]_, and the perpetuation
```

matching reference to below changes

2019-07-08 11:53 UTC, deniederhut commented
Hm... it looks like the server builds are currently failing because there are two .rst files in your paper directory. Had you meant to save your paper draft with two different file names?

2019-07-08 12:00 UTC, deniederhut commented on papers/Amal_Bhatnagar/AcceleratingtheAdvancementofDataScienceEducation.rst
> +.. [Desrosières 11] Desrosières, A. (2011). The politics of large numbers: A history of
I'm not so sure about this one. We should be able to build papers with è in them:

<img width="311" alt="Screenshot 2019-07-08 06 59 24" src="https://user-images.githubusercontent.com/6868396/60808513-1c8c7980-a14e-11e9-99a9-53bbe00ddaf7.png">

2019-07-08 18:09 UTC, amalbh1999 commented
Ah thank you so much for your help @deniederhut @gforsyth ! I was able to fix the errors in the paper. On http://procbuild.scipy.org/#, it still shows "08/07 18:05 Build failed, make_paper.sh did not succeed" even though I made and uploaded the PDF (https://github.com/amalbh1999/scipy_proceedings/blob/2019/papers/Amal_Bhatnagar/AcceleratingtheAdvancementofDataScienceEducation.pdf) 

Also, for some reason, the references and keywords isn't showing up in the PDF even though they are in the RST file. I committed the most recent RST file.

2019-07-08 18:26 UTC, stargaser commented
@amalbh1999 for your references to appear, the tags inside the square brackets cannot have spaces in them. Please change e.g. `[Baumer 17]` to `[Baumer17]`, both inside the text, and in the References section.

Please also:

- `git rm NationalAdvancementofDataScience.rst`
- `git rm AcceleratingtheAdvancementofDataScienceEducation.pdf`

2019-07-08 18:32 UTC, stargaser commented
For the keywords to show up: insert a blank line in between the line `.. class:: keyword`, and the line listing the keywords.

2019-07-09 11:23 UTC, deniederhut commented
Yeah, so two things:

1. the procbuild server creates the PDF for you, so there is no need to commit it; and,
2. the builds are still failing because you have two `.rst` files in your paper directory.

Right now you have `NationalAdvancementofDataScience.rst` and `AcceleratingtheAdvancementofDataScienceEducation.rst` checked in to this repository. The builds aren't starting because the server does not know which one to build and which one to ignore. You'll need to `git rm  papers/Amal_Bhatnagar/<the paper you want to get rid of>`, commit the change, and push it.

2019-07-10 03:14 UTC, deniederhut commented
Looks like everything is building - congrats!

2019-07-11 03:23 UTC, deniederhut commented
Hi @amalbh1999 ! Have you had a chance to respond to the reviewers' comments?

2019-07-11 14:44 UTC, amalbh1999 commented
Hi @deniederhut , yes, the most recent version that is on http://procbuild.scipy.org/ accounts for the reviewers' comments! We think it's ready for the proceedings. Thank you very much to the SciPy team for helping resolve the issues we were having.

2019-07-11 19:13 UTC, deniederhut commented
Awesome! @stargaser do you have time to take a second look at this?

2019-07-12 02:41 UTC, stargaser reviewed
@amalbh1999 thank you for the revised version responding to the reviewer comments, and for including the extra text on ethical considerations. The paper is very nearly ready to be merged -- there are just a few small bookkeeping matters:

1. I believe the PDF file needs to be removed; @deniederhut can confirm.
2. One in-text reference needs a space removed (in-line comment, it is `Noble18`).
3. One small grammar change

With at least the first two items addressed, we could label this submission as ready for publication.

2019-07-12 02:41 UTC, stargaser commented on papers/Amal_Bhatnagar/AcceleratingtheAdvancementofDataScienceEducation.rst
> +examines how such integration could work.*
```suggestion
examining how such integration could work.*
```

2019-07-12 02:41 UTC, stargaser commented on papers/Amal_Bhatnagar/AcceleratingtheAdvancementofDataScienceEducation.rst
> +[Noble 18]_, [ONeil18]_ are well known to scholars in the
```suggestion
[Noble18]_, [ONeil18]_ are well known to scholars in the
```

2019-07-13 04:19 UTC, amalbh1999 commented
@stargaser  @deniederhut I fixed all 3 points you mentioned! Please let me know if there's anything else I should do for the paper to be merged.

2019-07-13 05:10 UTC, stargaser approved these changes
Thank you @amalbh1999 for the changes. Looks good to me!

2019-07-13 12:36 UTC, deniederhut commented
Woohoo! Thanks everyone!

2019-07-13 15:54 UTC, merged