Initial pull request
scipy-conference/scipy_proceedings pull request #481
Opened 2019-05-23 06:55 UTC by mwickert

If you are creating this PR in order to submit a draft of your paper,
see http://procbuild.scipy.org/ for logs generated by the build
process.

See the [project readme](https://github.com/scipy-conference/scipy_proceedings#build-your-paper)
for more information.

2019-06-08 12:39 UTC, deniederhut commented
Hey @mwickert ! There are a lot of sections in your paper that have something like this:

> More writing TBD. 

Did you forget to push some commits with the new content?

2019-06-08 13:47 UTC, mwickert commented
I am working on it now and hope to have more gaps filled later today, and hopefully all completed Sunday evening.

Is this reasonable by you?

2019-06-08 23:17 UTC, deniederhut commented
Great! Just as a reminder, papers are supposed to have been complete by the submission deadline, which was a couple of weeks ago.
On Jun 8, 2019, 09:47 -0400, Mark Wickert <notifications@github.com>, wrote:
> I am working on it now and hope to have more gaps filled later today, and hopefully all completed Sunday evening.
> Is this reasonable by you?
> —
> You are receiving this because you commented.
> Reply to this email directly, view it on GitHub, or mute the thread.

2019-06-10 20:17 UTC, senolpiskin requested changes
Hey Mark, 

I am reviewing this paper for SciPy 2019. After a quick review, I think:

PDF files within the RST file are not viewed automatically.
Some of the links are not functioning correctly.
Youtube video is not available.

Could you please check these issues so that I can review extensively.

Regards,
Senol

2019-06-10 21:57 UTC, mwickert commented
Senol,

Working from the bottom up, I would not expect Youtube video to do anything at this point.

When you say links not functioning do you mean in the paper itself?

Finally as for viewing pdf file, I am not sure what else I need to do. I wrote two papers for the 2018 Scipy and I am using the same computer and GitHub configuration as I did in the past. The paper builds to pdf fine on my local machine. I assume that when I push to GitHub the build server should take over and build the pdf of the paper on the server.

Maybe Dillon can comment.

Mark

2019-06-11 01:59 UTC, deniederhut commented
Correct - the youtube link is a placeholder for when we have the recorded talk online after the conference.

As for rendering, @senolpiskin you can see the paper here http://procbuild.scipy.org/download/mwickert-2019 on the buildserver

2019-06-11 05:46 UTC, senolpiskin commented
Yes, I can see now. Thanks. I will send my comments soon.

2019-06-12 01:38 UTC, senolpiskin commented
Here is my review report:

The manuscript describes a 3D audio simulator that can be used in real-time applications for cognitive hearing science. The proposed software can be useful in many aspects of hearing applications. It is within the scope of the SciPy conference and the audience can be highly interested in reading the paper and using the corresponding codes. But, the paper needs several major changes as I have noted below:

The first concern is the language of the manuscript: There are many spelling and grammar mistakes that should be addressed. Furthermore, some statements are not clear. I have mentioned only a few of them although there are many others:

Please rephrase: "To that end this simulator
is integral to planned human subject testing where headphone
testing will be used to blind test subjects for their perception of
where a sound source is located."

Use a comma and rephrase: "To produce a synthesized 3D audio sound field starts with a
geometry."

Not clear and there are two "the": " For a given source location
(x, y,z) = (x1,−x2, x3) pointing at the the origin, we transform
from rectangular coordinates to cylindrical coordinates as shown
in Figure 1."

Please use more formal English: "This transformation is motivated by [Fitzpatrick],
and will be explained more fully in a later section. "
For instance, you could say "This transformation is motivated by [Fitzpatrick],
and explained in detail in section Section Name'."

Do you mean 'mentioned'?: "Note also the
second rectangular coordinate frame mention above is the notation
used by CIPIC."

Not clear, please check again and rephrase: "The 3D audio rendering provided by the simulator developed
in this paper, relies on the 1250 HRIR measurements were taken
using the geometrical configuration shown in Figure 2."

Please remove 'The': "For a source on the 1 m reference sphere, or further away, the there is no ..."

Please rephrase: "When the source is inside is the unit sphere sound parallax ..."

Please check for more. There are many others. I suggest a native English speaker revise the whole text.


Other than the language issues, I have some other suggestions. Please see below:

The abstract is repeated in the introduction section of the main text. That is unnecessary. Please remove that part from the introduction.

Define CIBIC abbreviation before its first usage. 

Please define the symbols of the mathematical variables such as azimuth angle, elevation,... in the text at the first usage.

What does it mean? "For a given source location
(x, y,z) = (x1,−x2, x3) pointing at the the origin" 
Please explain the equation in more detail. It is not very clear.

Use the same terminology throughout the whole manuscript: "we transform
from rectangular coordinates to cylindrical coordinates" and "convert from cylindrical coordinates
to cartesian"
Use either cartesian or rectangular, not both.

It is not clear what kind of analysis is performed in the section 'Spherical Head Model as a Simple Reference HRIR'. Are you reproducing any previous data here? Or comparing the results with some analytical solutions? If so, what is the error? If not, I suggest performing an error analysis of the results compared to some analytical solution.

I am suggesting re-review after these changes.

2019-06-12 04:09 UTC, mwickert commented
Senolpiskin,

Thank you for detailed comments. I appreciate the time you have taken to go through my writing, which I acknowledge was not proofed very well. I fact there are details in the spherical head model section that I feel must be added. 

I welcome your re-review. I hope to have a response late tomorrow or early Thursday.

2019-06-23 04:38 UTC, mwickert commented
@senolpiskin and @deniederhut
Heavily revised version of the original paper posted incrementally over the last 1+ week, now ready for a second review.

In the below I have interleaved by response to your original review.

Here is my review report: The manuscript describes a 3D audio simulator that can be used in real-time applications for cognitive hearing science. The proposed software can be useful in many aspects of hearing applications. It is within the scope of the SciPy conference and the audience can be highly interested in reading the paper and using the corresponding codes. But, the paper needs several major changes as I have noted below:

General Comment: The first concern is the language of the manuscript: There are many spelling and grammar mistakes that should be addressed. Furthermore, some statements are not clear. I have mentioned only a few of them although there are many others:

- Agree, I have made many edits

Specific Comments: Please rephrase: "To that end this simulator
is integral to planned human subject testing where headphone
testing will be used to blind test subjects for their perception of
where a sound source is located."

- Done

Use a comma and rephrase: "To produce a synthesized 3D audio sound field starts with a
geometry."

- Done; sentences reworked and the corresponding figure was reworked to make the two coordinate frames clear. Note the first frame is  

Not clear and there are two "the": " For a given source location
(x, y,z) = (x1,−x2, x3) pointing at the the origin, we transform
from rectangular coordinates to cylindrical coordinates as shown
in Figure 1."

- Done in the rework that also resolved ; What you reference above was indeed not clear, and when I went back to re-read things I concluded it was not correct 

Please use more formal English: "This transformation is motivated by [Fitzpatrick],
and will be explained more fully in a later section. "
For instance, you could say "This transformation is motivated by [Fitzpatrick],
and explained in detail in section Section Name'."

- Fixed

Do you mean 'mentioned'?: "Note also the
second rectangular coordinate frame mention above is the notation
used by CIPIC."

- Resolved; I likely had a typo here, but in my rewrite I changed the phrase to "The second system is referred to by CIPIC..."

Not clear, please check again and rephrase: "The 3D audio rendering provided by the simulator developed
in this paper, relies on the 1250 HRIR measurements were taken
using the geometrical configuration shown in Figure 2."

- Fixed; lots of rewrite in this area

Please remove 'The': "For a source on the 1 m reference sphere, or further away, the there is no ..."

- Fixed; This was an incorrect statement and is now stated correctly in this section of the paper

Please rephrase: "When the source is inside is the unit sphere sound parallax ..."

- Fixed/resolved; again this section of the paper has undergone a lot of rewrite. I have also now added Figure 6 to give a pictoral view of the parallax problem. There is not enough space to go through all of the equations behind the parallax correction, but the paper by Fitzpatrick is readily available. 

Please check for more. There are many others. I suggest a native English speaker revise the whole text.

- Resolved, I think; The first draft was written too quickly during a crunch time.

Other than the language issues, I have some other suggestions. Please see below:

The abstract is repeated in the introduction section of the main text. That is unnecessary. Please remove that part from the introduction.

- Duplication removed; this was carelessness on my part

Define CIBIC abbreviation before its first usage.

- Fixed; See the introduction. I though I had done this, but good that you caught it.

Please define the symbols of the mathematical variables such as azimuth angle, elevation,... in the text at the first usage.

- In the rewrite I have tried to make all variables clear and defined. Figure 1 for example now sets the stage for a large number of geometry related variables. I refer back to this figure later in the paper to help provide a visual as to how variables fit into the big picture. In the spherical head section some new variables get defined. The greek letter \theta gets used in multiple contexts, but the subscript is unique to the usage (I hope).

What does it mean? "For a given source location
(x, y,z) = (x1,−x2, x3) pointing at the the origin"
Please explain the equation in more detail. It is not very clear.

- Resolved; This was a confusing section. It has been rewritten and this equality no longer appears.

Use the same terminology throughout the whole manuscript: "we transform
from rectangular coordinates to cylindrical coordinates" and "convert from cylindrical coordinates
to cartesian"
Use either cartesian or rectangular, not both.

- Fixed; Cartesian is the dominant coordinate system employed, but CIPIC uses IPCS (really a spherical system, I have to interface with this) but now I try hard to make it clear that cylindrical coordinates are only used in the Jupyter notebook apps as a convenience for the user to position the audio source in what I think is a convenient way access localization when informally testing subjects.  

It is not clear what kind of analysis is performed in the section 'Spherical Head Model as a Simple Reference HRIR'. Are you reproducing any previous data here? Or comparing the results with some analytical solutions? If so, what is the error? If not, I suggest performing an error analysis of the results compared to some analytical solution.

- I am going to try to answer your questions first, then move on to justifying my approach. The references that I have provided in the spherical head model section of the paper are classics in my opinion. There are no closed-form analytical solutions for the geometries I am most interested in, but the paper by Duda and Martens has many plots and in particular my Figure 11 is very similar (not the same geometries) their Fig 6. This paper also has pseudo-code in their Appendix B, which is my function HRTF_sph() in the paper. I feel comfortable with HRIR results I have obtained. The Duda and Martens paper does provided every step they took from HRTF to HRIR, so some small differences are possible. At the end of the spherical head section I now include some comments on a listening test that was conducted.

Wrap-up: I am suggesting re-review after these changes.

- I am ready to move forward with the next round.

2019-06-27 20:40 UTC, stargaser commented
Hello @mwickert! I am one of the proceedings committee members, and I will complete a review of the current version, hopefully today, and definitely by tomorrow, to try to help wrap up your paper.

2019-06-28 16:53 UTC, stargaser requested changes
Thank you @mwickert for this interesting submission. The paper is in good shape, with plenty of technical details and figures. I have mostly made copy-editing suggestions inline. I am marking the review "changes requested" mainly for these. I have a couple more general suggestions:

After my first time through reading the paper, I went to the CIPIC site and read through most of [the tutorial there](https://www.ece.ucdavis.edu/cipic/spatial-sound/tutorial/). My field is astronomy and I found it very helpful to skim the tutorial.

A basic question stemming from my lack of experience in your field: On my first read-through, I was puzzled about the measurements on human subjects. I was wondering if the HRIR and HRTF functions depended on an individual's perception of a sound, like: does the human subject have to signal that they heard the sound? After reading the tutorial and some descriptions on the CIPIC site, I think I understand better, that it is the location, size, and shape of the ears (pinna) that vary among human subjects.

Since your paper is getting close to the page limit and there is not much room for adding some of this background, maybe the best thing to do is to refer the reader to the tutorial.

I am hopeful that it will not take you long to address these comments.

2019-06-28 16:53 UTC, stargaser commented on papers/mark_wickert/mark_wickert.rst
> +   studies and also for general 3D audio experimentation. The framework that the simulator is build
```suggestion
   studies and also for general 3D audio experimentation. The framework that the simulator is built 
```

2019-06-28 16:53 UTC, stargaser commented on papers/mark_wickert/mark_wickert.rst
> +   as a function of azimuth and elevation angles of the impinging sounds source.
```suggestion
   as a function of azimuth and elevation angles of the impinging sound's source.
```

2019-06-28 16:53 UTC, stargaser commented on papers/mark_wickert/mark_wickert.rst
> +source placed at say one meter from the head and then the subject is moved over a range of
```suggestion
source placed at e.g. one meter from the head and then the subject is moved over a range of 
```
"say" sounds too informal

2019-06-28 16:53 UTC, stargaser commented on papers/mark_wickert/mark_wickert.rst
> +surface. A frequency sweep of magnitude and phase is then the inverse Fourier transformed to obtain the HRIR.
```suggestion
surface. A frequency sweep of magnitude and phase is then inverse Fourier transformed to obtain the HRIR. 
```

2019-06-28 16:53 UTC, stargaser commented on papers/mark_wickert/mark_wickert.rst
> +rendering of the subjects shoulders and head. Note 3D rendering of a subject can be obtained using *photogrammetry*,
```suggestion
rendering of the subject's shoulders and head. 3D rendering of a subject can be obtained using *photogrammetry*, 
```

2019-06-28 16:53 UTC, stargaser commented on papers/mark_wickert/mark_wickert.rst
> +the intersection between the subjects  *mid-sagittal* or vertical *median plane* and the line
```suggestion
the intersection between the subject's  *mid-sagittal* or vertical *median plane* and the line 
```

2019-06-28 16:53 UTC, stargaser commented on papers/mark_wickert/mark_wickert.rst
> +the audio source about a subjects head. A secondary head-centered
```suggestion
the audio source about a subject's head. A secondary head-centered 
```

2019-06-28 16:53 UTC, stargaser commented on papers/mark_wickert/mark_wickert.rst
> +From the block diagram we see that for audio source is positioned at :math:`(x,y,z)` relative to the head
```suggestion
For an audio source positioned at :math:`(x,y,z)` relative to the head 
```
I found the phrase "From the block diagram we see that..." confusing, because the filter coefficients, the gain scaling, the parallax, etc. are not in Figure 4 at all.

2019-06-28 16:53 UTC, stargaser commented on papers/mark_wickert/mark_wickert.rst
> +are processed with at a sampling rate of :math:`f_s = 44.1` ksps, as this is rate used in forming the CIPIC
```suggestion
are processed with a sampling rate of :math:`f_s = 44.1` kHz, as this is rate used in forming the CIPIC 
```
I couldn't parse "ksps" and I wonder if "kcps" (kilo cycles per second) was intended. Later in the paper I see 44.1 kHz so I suggest it here.

2019-06-28 16:53 UTC, stargaser commented on papers/mark_wickert/mark_wickert.rst
> +touch the unit sphere, the required azimuth values will be shifted to locations either side of the
```suggestion
touch the unit sphere, the required azimuth values will be shifted to locations on either side of the 
```

2019-06-28 16:53 UTC, stargaser commented on papers/mark_wickert/mark_wickert.rst
> +that are closest to the intersection point
```suggestion
that are closest to the intersection points.
```

2019-06-28 16:53 UTC, stargaser commented on papers/mark_wickert/mark_wickert.rst
> +A total of 45 subjects are contained in the CIPIC HRIR database, both human and the mannequin *Kemar* [CIPICHRTF]_.
```suggestion
A total of 45 subjects are contained in the CIPIC HRIR database, both human and the mannequin KEMAR (Knowles Electronics Manikin for Auditory Research) [CIPICHRTF]_. 
```
(optional to spell out the acronym -- I would find it helpful)

2019-06-28 16:53 UTC, stargaser commented on papers/mark_wickert/mark_wickert.rst
> +The first and foremost purpose the 3D audio simulator is to to be able statically position an audio source
```suggestion
The first and foremost purpose the 3D audio simulator is to be able to statically position an audio source 
```

2019-06-28 16:53 UTC, stargaser commented on papers/mark_wickert/mark_wickert.rst
> +The calculations required to obtain Figure :label:`SCATTER` follow easily using the functions found in
```suggestion
The calculations required to obtain Figure :ref:`SCATTER` follow easily using the functions found in 
```

2019-06-28 16:53 UTC, stargaser commented on papers/mark_wickert/mark_wickert.rst
> +and differences. Coarse localization is similar between the two, bit the spherical model seems *sterile*. The fact that
```suggestion
and differences. Coarse localization is similar between the two, but the spherical model seems *sterile*. The fact that 
```
I haven't encountered "sterile" used to describe a model before. Does sterile mean the HRIR is mostly flat and lacks features that a measured HRIR typically contains?

2019-07-01 04:15 UTC, mwickert commented on papers/mark_wickert/mark_wickert.rst
> +   studies and also for general 3D audio experimentation. The framework that the simulator is build
Applied in 6/30/2019 10:15 MDT push.

2019-07-01 04:16 UTC, mwickert commented on papers/mark_wickert/mark_wickert.rst
> +   as a function of azimuth and elevation angles of the impinging sounds source.
Applied in 6/30/2019 10:15 MDT push.

2019-07-01 04:16 UTC, mwickert commented on papers/mark_wickert/mark_wickert.rst
> +source placed at say one meter from the head and then the subject is moved over a range of
Applied in 6/30/2019 10:15 MDT push.

2019-07-01 04:16 UTC, mwickert commented on papers/mark_wickert/mark_wickert.rst
> +surface. A frequency sweep of magnitude and phase is then the inverse Fourier transformed to obtain the HRIR.
Applied in 6/30/2019 10:15 MDT push.

2019-07-01 04:16 UTC, mwickert commented on papers/mark_wickert/mark_wickert.rst
> +rendering of the subjects shoulders and head. Note 3D rendering of a subject can be obtained using *photogrammetry*,
Applied in 6/30/2019 10:15 MDT push.

2019-07-01 04:16 UTC, mwickert commented on papers/mark_wickert/mark_wickert.rst
> +that are closest to the intersection point
Applied in 6/30/2019 10:15 MDT push.

2019-07-01 04:17 UTC, mwickert commented on papers/mark_wickert/mark_wickert.rst
> +A total of 45 subjects are contained in the CIPIC HRIR database, both human and the mannequin *Kemar* [CIPICHRTF]_.
Applied in 6/30/2019 10:15 MDT push.

2019-07-01 04:17 UTC, mwickert commented on papers/mark_wickert/mark_wickert.rst
> +The first and foremost purpose the 3D audio simulator is to to be able statically position an audio source
Applied in 6/30/2019 10:15 MDT push.

2019-07-01 04:17 UTC, mwickert commented on papers/mark_wickert/mark_wickert.rst
> +The calculations required to obtain Figure :label:`SCATTER` follow easily using the functions found in
Applied in 6/30/2019 10:15 MDT push.

2019-07-01 04:18 UTC, mwickert commented on papers/mark_wickert/mark_wickert.rst
> +and differences. Coarse localization is similar between the two, bit the spherical model seems *sterile*. The fact that
Applied in 6/30/2019 10:15 MDT push. Also added short phrase describing what is meant by sterile.

What remains is to respond to the general comments.

2019-07-01 04:26 UTC, mwickert commented on papers/mark_wickert/mark_wickert.rst
> +the intersection between the subjects  *mid-sagittal* or vertical *median plane* and the line
Applied in 6/30/2019 10:26 MDT push.

2019-07-01 04:26 UTC, mwickert commented on papers/mark_wickert/mark_wickert.rst
> +the audio source about a subjects head. A secondary head-centered
Applied in 6/30/2019 10:26 MDT push.

2019-07-01 04:27 UTC, mwickert commented on papers/mark_wickert/mark_wickert.rst
> +touch the unit sphere, the required azimuth values will be shifted to locations either side of the
Applied in 6/30/2019 10:26 MDT push.

2019-07-01 04:29 UTC, mwickert commented on papers/mark_wickert/mark_wickert.rst
> +are processed with at a sampling rate of :math:`f_s = 44.1` ksps, as this is rate used in forming the CIPIC
Applied in 6/30/2019 10:26 MDT push. The ksps is an abbreviation for kilo samples per second, you are correct in that just saying 44.1 kHz is consistent with the other reference to the sampling rate. Thanks for noticing this.

2019-07-01 04:32 UTC, mwickert commented on papers/mark_wickert/mark_wickert.rst
> +From the block diagram we see that for audio source is positioned at :math:`(x,y,z)` relative to the head
Applied in 6/30/2019 10:26 MDT push. Your comment about being confusing is good. I added this figure after the first review, because yes I think the parallax correction needs some explaining in this paper, without forcing the reader to jump to the Fitzpatrick reference. Again thanks helping me make this clearer.

2019-07-01 05:16 UTC, mwickert commented on papers/mark_wickert/mark_wickert.rst
> +source placed at say one meter from the head and then the subject is moved over a range of
@stargaser

I have done many small pushes, but the last one for tonight address the general comments by including a link to the HCI tutorial at UC-Davis that you have mentioned. The reference in in the introduction.

I still want to comment further on your general comments. You are correct that the HRTF/HRIR is a function of the subjects anthropometry. Our cognitive ability to localize sound is a learning process since birth. The main contribution of this paper is the apparatus for allowing human subjects to easily be evaluated for an HRFT/HRIR "fit". I am excited to move to this step in the research, but I have yet to experience this in a true clinical setting. I will have this running as a demo at the poster session.

2019-07-01 05:19 UTC, mwickert commented
@stargaser

I originally made this comment under one of you smaller comments, I want it to be at the end as a general comm ent, so it is posted a second time.

I have done many small pushes, but the last one for tonight address the general comments by including a link to the HCI tutorial at UC-Davis that you have mentioned. The reference in in the introduction.

I still want to comment further on your general comments. You are correct that the HRTF/HRIR is a function of the subjects anthropometry. Our cognitive ability to localize sound is a learning process since birth. The main contribution of this paper is the apparatus for allowing human subjects to easily be evaluated for an HRFT/HRIR "fit". I am excited to move to this step in the research, but I have yet to experience this in a true clinical setting. I will have this running as a demo at the poster session.

2019-07-01 15:13 UTC, senolpiskin commented
Mark,
I will send my second round review today or tomorrow. I think it will be the final one since the paper looks much better now.

2019-07-02 15:50 UTC, senolpiskin requested changes
The figures are of high quality and very informative. But the text needs some more editing. There are some confusing parts. I have quoted them below. Please consider rephrasing them:


"To finally render 3D audio requires selection of the appropriate
right/left filter coefficient set, and if needed range correction."
Does it mean: 'Rendering 3D audio requires a proper set of right/left filter coefficients and possibly the range correction.' ?

Not clear, please rephrase or make two sentences: " If
we simply want to position an audio source on the 1 m reference
sphere used by CIPIC, then the coefficient selection process is
simply picking the index into the database that is closest to the
corresponding IPCS angle pair, (φ,θ), of the source."

Not clear, please rephrase: "The approach
taken here follows [Fitzpatrick] using the primary cartesian coordinates to additionally perform parallax correction and source
range amplitude correction. "
Does it mean: 'Our approach follows the methodology of [Fitzpatrick] which uses the primary ...' ?

Not clear, please rephrase or make two sentences: "Source range correction accounts for
the fact that with a point source we have sound wave divergence,
thus the amplitude needs to be scaled inversely with radial distance
(inverse-squared ..."

Not clear, please rephrase or make two sentences: "The sound wave
amplitude correction factors self.tR and tL are obtained from
the parallax correction expression in [Fitzpatrick], and double as
the required range scale factors, GR and GL in (1) and (2)."

"Finally, solve
for the scattered wave, ˜ps(r,θi), by applying boundary conditions,
see [Beranek] for details, we superimpose the two solutions to
obtain
 ..."

Does it mean: 'Finally, we solve
for the scattered wave, ˜ps(r,θi), by applying boundary conditions
(see [Beranek] for details), we superimpose the two solutions to
obtain
 ...'

What does it mean the second plot coordinate? please be more specific: "The second
plot coordinate, due to axial symmetry, is w ..."

Not clear, please rephrase: "Note
in the spherical coordinates of the math model, it remains that ..."

Not clear, please rephrase or make two sentences: "The calculations required to obtain Figure 10 follow easily
using the functions found in scipy.special, e.g., for the
scattered field the calculation is:"

The sentences are not complete and vague: "Fig. 10: Using spherical harmonics [Beranek] to calculate the
pressure wave magnitude (shown here) and phase, using a plane wave
audio source arriving from the bottom of the figure."

"In signal processing the transfer function, H(f) = |H(f)|e
j∠H(f)
,
is a ratio of two complex numbers as a function frequency in Hz."
You can rewrite as: 'In signal processing, the transfer function, H(f) = |H(f)|e
j∠H(f)
,
is a ratio of two complex numbers as a function of frequency in Hz.'

Remove will: "Since
we are working with digital (discrete-time) signal processing, the
inverse discrete Fourier transform (IDFT) will is used here, as
opposed to the Fourier integral."
Does it mean: 'instead of Fourier integral'?

Please check for more, especially the sections after FIR Filter Coefficient Set Selection.

Another suggestion: The methodology can be confusing for those who are not very familiar in the field. So, would you think adding a brief flowchart of the methods section or the software that summarizes everything in a simpler way?

2019-07-02 18:01 UTC, stargaser reviewed
@mwickert thank you for the revisions, and for including the tutorial in the introduction. I found a few more typos or missing words upon resolving the previous copy-editing suggestions I had made -- these are inline.

I agree with @senolpiskin that some of the longer sentences could be split into two or otherwise rephrased. Since the paper is very close to the page limit, it would not be possible to add an explanatory flowchart without removing other parts of the manuscript; for my part, I won't require a flowchart for labeling the paper as ready.

We are getting very close to the planned pre-conference publication of the proceedings -- if it is possible to attend to the requests for re-wording, I am hopeful we can get this wrapped up. There will also be a post-conference merge; plus the current version is available on the procbuild server for people to view.

2019-07-02 18:01 UTC, stargaser commented on papers/mark_wickert/mark_wickert.rst
> +   studies and also for general 3D audio experimentation. The framework that the simulator is build
(I think this change didn't make it in)

2019-07-02 18:01 UTC, stargaser commented on papers/mark_wickert/mark_wickert.rst
> +The first and foremost purpose the 3D audio simulator is to be able to statically position an audio source
```suggestion
The first and foremost purpose of the 3D audio simulator is to be able to statically position an audio source 
```

2019-07-02 18:01 UTC, stargaser commented on papers/mark_wickert/mark_wickert.rst
> +:math:`f` is the operating frequency in Hz, :math:`r` is the distance fro the source to the
```suggestion
:math:`f` is the operating frequency in Hz, :math:`r` is the distance from the source to the 
```

2019-07-02 18:01 UTC, stargaser commented on papers/mark_wickert/mark_wickert.rst
> +center if the sphere, and one again :math:`R` is the sphere radius. Recall also that the
```suggestion
center of the sphere, and once again :math:`R` is the sphere radius. Recall also that the 
```

2019-07-02 19:30 UTC, mwickert commented
@stargaser @senolpiskin 

I have just had a quick look at both of your comments. I have been busy trying to get two posters completed to get printed before the 4th. I agree to the sentence break-up changes, but obviously have to get into it.  hope to get working on the changes ASAP.

@stargaser if you had your wishes, when do you want me to have my pushes complete?

2019-07-02 20:36 UTC, stargaser commented
@mwickert understood about needing to get your posters printed. My understanding is that @deniederhut will merge the PRs labeled "Ready" on Wednesday, July 4th, for the conference-ready version. Two weeks after that, the post-conference merge will be done.

Checking the 2018 branch, my own paper last year didn't make the pre-conference merge and was one of several merged a couple days after the conference.

If the in-line "suggestion" comments are helpful, I can make another pass of copy-editing. For those little things, it is fine just to resolve them as you fix them, and/or just put a thumbs-up emoji on the in-line comment. Or, even easier, you can use the "Commit suggestion" button. There's another button "Add suggestion to batch" to accept several of these into a single commit.

2019-07-02 20:51 UTC, mwickert commented
@stargaser 

Thanks for the hints. I want to do all my edits in my local version and then push. I will work on this  tonight and hopefully make the July 4th ~deadline.

2019-07-02 23:22 UTC, stargaser commented
My apologies -- I had originally written "Wednesday, July 4th" when looking at the 2018 calendar. I corrected the comment to say "Wednesday, July 3rd" for the pre-conference merge. (not what you wanted to hear, I'm sure...)

2019-07-03 00:40 UTC, mwickert commented
David,

I’m going to try after jazz gig is over this evening.

Mark Wickert

On Jul 2, 2019, at 5:22 PM, David Shupe <notifications@github.com<mailto:notifications@github.com>> wrote:


My apologies -- I had originally written "Wednesday, July 4th" when looking at the 2018 calendar. I corrected the comment to say "Wednesday, July 3rd" for the pre-conference merge. (not what you wanted to hear, I'm sure...)

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub<https://github.com/scipy-conference/scipy_proceedings/pull/481?email_source=notifications&email_token=AC74UBUH7A5FYA5K562X7FDP5PPJ3A5CNFSM4HO2O2U2YY3PNVWWK3TUL52HS4DFVREXG43VMVBW63LNMVXHJKTDN5WW2ZLOORPWSZGODZC2B4A#issuecomment-507879664>, or mute the thread<https://github.com/notifications/unsubscribe-auth/AC74UBULXIDIH22OLLT5UBLP5PPJ3ANCNFSM4HO2O2UQ>.

2019-07-03 03:49 UTC, mwickert commented on papers/mark_wickert/mark_wickert.rst
> +center if the sphere, and one again :math:`R` is the sphere radius. Recall also that the
Done, will see in next push

2019-07-03 03:50 UTC, mwickert commented on papers/mark_wickert/mark_wickert.rst
> +:math:`f` is the operating frequency in Hz, :math:`r` is the distance fro the source to the
Done, will see in next push

2019-07-03 03:51 UTC, mwickert commented on papers/mark_wickert/mark_wickert.rst
> +The first and foremost purpose the 3D audio simulator is to be able to statically position an audio source
Done, will see in next push

2019-07-03 05:43 UTC, mwickert commented
@stargaser and @senolpiskin 

I have applied all the changes requested by @stargazer. I have applied fixes for some of the @senolpiskin comments. It is too late after being up let night doing posters. I will return to this in the morning.

@seolpiskin responses thus far:

"To finally render 3D audio requires selection of the appropriate
right/left filter coefficient set, and if needed range correction."
Does it mean: 'Rendering 3D audio requires a proper set of right/left filter coefficients and possibly the range correction.' ?

- Your restating my sentence is correct and my original intent. I am happy with it as is. Are you?

Not clear, please rephrase or make two sentences: " If
we simply want to position an audio source on the 1 m reference
sphere used by CIPIC, then the coefficient selection process is
simply picking the index into the database that is closest to the
corresponding IPCS angle pair, (φ,θ), of the source."

- This sentence is reworded to be simpler that my first attempt. In sourece this is lines 231-233. I have left the old text in as an RST comment

"In signal processing the transfer function, H(f) = |H(f)|e
j∠H(f)
,
is a ratio of two complex numbers as a function frequency in Hz."
You can rewrite as: 'In signal processing, the transfer function, H(f) = |H(f)|e
j∠H(f)
,
is a ratio of two complex numbers as a function of frequency in Hz.'

- Done

Remove will: "Since
we are working with digital (discrete-time) signal processing, the
inverse discrete Fourier transform (IDFT) will is used here, as
opposed to the Fourier integral."
Does it mean: 'instead of Fourier integral'?

- I have removed will

Please check for more, especially the sections after FIR Filter Coefficient Set Selection.

- Thinking about this

Another suggestion: The methodology can be confusing for those who are not very familiar in the field. So, would you think adding a brief flowchart of the methods section or the software that summarizes everything in a simpler way?

- The paper is currently very close to the 8-page limit. If I removed code listings and instead showed flowcharts, this may be helpful to some. I suspect others may find the code and the embedded comments are better than a flowchart. I am content staying with code listings. Can @stargazer please provide an opinion on this one.

2019-07-03 14:16 UTC, mwickert commented
@senolpiskin and @stargaser 

Remaining changes + others I have found now addressed. See the below original comments with bullets my response.

Not clear, please rephrase: "The approach
taken here follows [Fitzpatrick] using the primary cartesian coordinates to additionally perform parallax correction and source
range amplitude correction. "
Does it mean: 'Our approach follows the methodology of [Fitzpatrick] which uses the primary ...' ?

- Your Does it mean is correct. I have reworded the sentence slightly. See source lines 240-242.

Not clear, please rephrase or make two sentences: "Source range correction accounts for
the fact that with a point source we have sound wave divergence,
thus the amplitude needs to be scaled inversely with radial distance
(inverse-squared ..."

- Reworded over source lines 242-245.

Not clear, please rephrase or make two sentences: "The sound wave
amplitude correction factors self.tR and tL are obtained from
the parallax correction expression in [Fitzpatrick], and double as
the required range scale factors, GR and GL in (1) and (2)."

- Reworded over source lines 404-405. The old version is an RST in the lines 407-409

"Finally, solve
for the scattered wave, ˜ps(r,θi), by applying boundary conditions,
see [Beranek] for details, we superimpose the two solutions to
obtain
..."

Does it mean: 'Finally, we solve
for the scattered wave, ˜ps(r,θi), by applying boundary conditions
(see [Beranek] for details), we superimpose the two solutions to
obtain
...'

- Reworded over source lines 495-496.

What does it mean the second plot coordinate? please be more specific: "The second
plot coordinate, due to axial symmetry, is w ..."

- Reworded over source lines 521-524.

Not clear, please rephrase: "Note
in the spherical coordinates of the math model, it remains that ..."

- This was dealt with in the above rewording over source lines 521-524.

Not clear, please rephrase or make two sentences: "The calculations required to obtain Figure 10 follow easily
using the functions found in scipy.special, e.g., for the
scattered field the calculation is:"

- Reworded over source lines 538-539.

The sentences are not complete and vague: "Fig. 10: Using spherical harmonics [Beranek] to calculate the
pressure wave magnitude (shown here) and phase, using a plane wave
audio source arriving from the bottom of the figure."

- Figure caption reworded in source lines 545-536. Figure modified to include a direction arrow.

2019-07-03 14:24 UTC, senolpiskin commented
Thanks for the changes, Mark. I don't have any other comment at this point.

2019-07-03 15:46 UTC, stargaser approved these changes
This revision looks good to me. Thanks @senolpiskin for your reviews, and @mwickert for getting the changes in!

2019-07-03 16:15 UTC, mwickert commented
@stargaser @senolpiskin 

Thanks to the both of you for working me through this. I look forward to meeting you both next week at the conference.

2019-07-10 03:26 UTC, merged