Paper: CAF Implementation on FPGA Using Python Tools
scipy-conference/scipy_proceedings pull request #482
Opened 2019-05-25 06:09 UTC by chiranthsiddappa

If you are creating this PR in order to submit a draft of your paper,
see http://procbuild.scipy.org/ for logs generated by the build
process.

See the [project readme](https://github.com/scipy-conference/scipy_proceedings#build-your-paper)
for more information.

2019-05-25 06:30 UTC, chiranthsiddappa commented
The shell script did not work for building, however this did:
`
python3 publisher/build_paper.py papers/chiranth_siddappa/
`
But I see that the build server is having difficulty building as well.

2019-06-05 17:31 UTC, nicoguaro commented
Should I add comments to the paper in this PR?

2019-06-05 18:28 UTC, chiranthsiddappa commented
Hi @nicoguaro ,

If there are some very specific changes, maybe an edit in the rst would suffice. But I believe we are to exchange and address comments here so that the public may include and view any comments as well as SciPy participants. I am of course following this thread myself.

2019-06-05 20:54 UTC, nicoguaro commented
The document is 10 pages long and the suggestion is to be no-longer than 8 pages.

2019-06-06 21:21 UTC, nicoguaro commented
Listings are not numbered but are referenced in the text. Also, the first three listings are too long to fit in the columns.

2019-06-08 16:29 UTC, nicoguaro commented
The link to the YouTube video leads to "This video is unavailable".

2019-06-10 03:52 UTC, chiranthsiddappa commented
I was able to fix the code listings to fit in the margins easily enough. I'm looking at Sphinx documentation to figure out how to get numerical code listings.

I could use some suggestions for sections to reduce down. It would seem that AXI compliance may be too specific, along with the simulation screenshot for the frequency shift and Vivado screenshot (currently Fig. 15 and 24).

2019-06-10 14:44 UTC, deniederhut commented
> The link to the YouTube video leads to "This video is unavailable". 

We'll go in later and add a link to the recording of Chiranth's talk from the conference. I had thought the placeholder went to a Monty Python skit, but maybe it got removed from YouTube?

2019-06-10 14:54 UTC, nicoguaro commented
> I could use some suggestions for sections to reduce down. It would seem that AXI compliance may be too specific, along with the simulation screenshot for the frequency shift and Vivado screenshot (currently Fig. 15 and 24).

I agree that this section may be too specific. Also, in general, I would say that there are too many figures (for the available space).

2019-06-13 00:23 UTC, deniederhut commented
Hi @chiranthsiddappa ! We had fewer reviewers complete a review for your paper than we were expecting, so I'll be stepping in to complete the review myself. Please expect comments from me some time in the next handful of days 🙂.

2019-06-15 13:05 UTC, deniederhut requested changes
I used to get asked a lot about the best way to program FPGAs from inside Python - now I can point people to your paper! Thanks for the submission! I think we'll want a few changes before we publish this:

1. This is currently over the page limit. I think you can trim the paper down by removing some of the less relevant details, reducing the verbiage (especially by combining some of your sentences together), and removing repeated statements.
2. The logical flow is a bit hard to follow. Some paragraphs span an entire page and contain several arguments. 
3. The citations section is missing information about journal titles, publication years, and authorship.

2019-06-15 13:05 UTC, deniederhut commented on papers/chiranth_siddappa/chiranth_siddappa.rst
> +However, the CAF is the joint time offset and frequency offset generalization.
You are not contradicting your previous statement, so we probably don't need the "however" here.

2019-06-15 13:05 UTC, deniederhut commented on papers/chiranth_siddappa/chiranth_siddappa.rst
> +The basic algorithm for calculating the complex ambiguity function for time difference of arrival and frequency offset
It would be helpful to include the acronym here as well, e.g. "calculating the complex ambiguity function (CAF)"

2019-06-15 13:05 UTC, deniederhut commented on papers/chiranth_siddappa/chiranth_siddappa.rst
> +The CAF was mainly used first for radar and sonar type processing for locating objects in a method known as active echo
"locating objects via a method" or "locating objects using a method"

2019-06-15 13:05 UTC, deniederhut commented on papers/chiranth_siddappa/chiranth_siddappa.rst
> +The CAF has many practical applications, the more traditional being the before-mentioned radar and sonar type systems.
"aforementioned"

2019-06-15 13:05 UTC, deniederhut commented on papers/chiranth_siddappa/chiranth_siddappa.rst
> +Another common use case is in image processing.
These should probably be one sentence

2019-06-15 13:05 UTC, deniederhut commented on papers/chiranth_siddappa/chiranth_siddappa.rst
> +This helped in my understanding of the use of the dot product in cross-correlations which is the basis of this project.
I might phrase this as "the use of cross-correlations in image processing provides the theoretical basis for our use in geolocation"

2019-06-15 13:05 UTC, deniederhut commented on papers/chiranth_siddappa/chiranth_siddappa.rst
> +cannot be reduced.
I might say "has yet to be simplified"

2019-06-15 13:05 UTC, deniederhut commented on papers/chiranth_siddappa/chiranth_siddappa.rst
> +Currently GPU's have been employed as the main workhorse but the use of the FPGA has always been an attractive and
Why are GPUs the most popular option? Why are FPGAs attractive?

2019-06-15 13:05 UTC, deniederhut commented on papers/chiranth_siddappa/chiranth_siddappa.rst
> +To geolocate a signal's location the Doppler is used to calculate a frequency difference of arrival (FDOA) which
This should probably be a new paragraph

2019-06-15 13:05 UTC, deniederhut commented on papers/chiranth_siddappa/chiranth_siddappa.rst
> +that the resulting HDL can also be produced to match necessary configurations.
Have we defined HDL yet?

2019-06-15 13:05 UTC, deniederhut commented on papers/chiranth_siddappa/chiranth_siddappa.rst
> +This became a project goal motivated off work done by other projects to be able to produce code in other languages
I'm not sure what this sentence means

2019-06-15 13:05 UTC, deniederhut commented on papers/chiranth_siddappa/chiranth_siddappa.rst
> +Thus, the solution provided must be able to be reconfigured based off of different needs.
This feels unrelated to the rest of the content of this paragraph. What solution? What needs? Reconfigure what?

2019-06-15 13:05 UTC, deniederhut commented on papers/chiranth_siddappa/chiranth_siddappa.rst
> +The processing for this system will be targeted to a PYNQ board by Xilinx, but has been designed such that it can be
I assume this is a particular manufacturer/model of FPGA?

2019-06-15 13:05 UTC, deniederhut commented on papers/chiranth_siddappa/chiranth_siddappa.rst
> +All Verilog HDL modules that are produced by the Python classes conform to the AXI bus standards of interfacing
Have you defined verilog?

2019-06-15 13:05 UTC, deniederhut commented on papers/chiranth_siddappa/chiranth_siddappa.rst
> +The main basis of this project then is to show a working implementation of digital design HDL modules implementing the
There are several sentences that state "the goal of this project is ..." or "the basis of this project is ...". We should probably cut these down to one of each, and they should be in the introduction.

2019-06-15 13:05 UTC, deniederhut commented on papers/chiranth_siddappa/chiranth_siddappa.rst
> +shifted would simply be the autocorrelation :cite:`ZiemerComm`. It is referred to as the captured signal in this context,
I might start a new paragraph here

2019-06-15 13:05 UTC, deniederhut commented on papers/chiranth_siddappa/chiranth_siddappa.rst
> +published to the package. This implementation is specific to this project in that it uses a sample size that is twice
What do you mean by "published to the package"?

2019-06-15 13:05 UTC, deniederhut commented on papers/chiranth_siddappa/chiranth_siddappa.rst
> +that of the reference signal for the computation. A sample output slice will be shown in the Experiments section for the
Is this important?

2019-06-15 13:05 UTC, deniederhut commented on papers/chiranth_siddappa/chiranth_siddappa.rst
> +back to the user based off provided build parameters shown in Listing :ref:`caf-listing`, described in a later
This reference is not resolving

2019-06-15 13:05 UTC, deniederhut commented on papers/chiranth_siddappa/chiranth_siddappa.rst
> +This performance allows for a RTOS to be run on the CPU.
Have we defined RTOS?

2019-06-15 13:05 UTC, deniederhut commented on papers/chiranth_siddappa/chiranth_siddappa.rst
> +This bitfile is generated through the Vivado Design Suite that is provided by Xilinx.
What is the relationship between vivado and verilog? Which one of these is your Python templating system interacting with?

2019-06-15 13:05 UTC, deniederhut commented on papers/chiranth_siddappa/chiranth_siddappa.rst
> +The Jupyter notebook itself is considered an interactive computing pool providing an interactive interface to do
You are repeating the word "interactive" here

2019-06-15 13:05 UTC, deniederhut commented on papers/chiranth_siddappa/chiranth_siddappa.rst
> +A code listing showing the inputs to the FreqShift Python class is shown in Listing :ref:`freq-shift-listing`. The
This reference is not resolving

2019-06-15 13:05 UTC, deniederhut commented on papers/chiranth_siddappa/chiranth_siddappa.rst
> +In Listing :ref:`caf-listing`, the Python class definition is provided for reference.
This reference is not resolving

2019-06-15 13:05 UTC, deniederhut commented on papers/chiranth_siddappa/chiranth_siddappa.rst
> +that has been released.
What python package? Released where?

2019-06-15 13:05 UTC, deniederhut commented on papers/chiranth_siddappa/chiranth_siddappa.rst
> +While working on this project, many design changes occurred and test verification was done by loading the output files
This feels superfluous

2019-06-15 13:05 UTC, deniederhut commented on papers/chiranth_siddappa/chiranth_siddappa.rst
> +As the description of the CAF itself was discussed previously, the rest of this document will walk through the steps
This paragraph feel superfluous

2019-06-15 13:05 UTC, deniederhut commented on papers/chiranth_siddappa/chiranth_siddappa.rst
> +The need for an analysis of quantization stems from the way that digital radio frequency systems are built. In order to
This is not a complete sentence

2019-06-15 13:05 UTC, deniederhut commented on papers/chiranth_siddappa/chiranth_siddappa.rst
> +Inspecting signals after quantization is important because when signals are reduced in size there is an inherent loss.
"there is information loss"

2019-06-15 13:05 UTC, deniederhut commented on papers/chiranth_siddappa/chiranth_siddappa.rst
> +When converting the signals, we must note that the values are signed.
Instead of using a whole sentence for this, you could modify line 277 to read "signed 12-bit signals".

2019-06-15 13:05 UTC, deniederhut commented on papers/chiranth_siddappa/chiranth_siddappa.rst
> +The operation of performing a complex multiply requires the use of complex numbers with real and imaginary parts. As an
I don't think we need to define what complex numbers are.

2019-06-15 13:05 UTC, deniederhut commented on papers/chiranth_siddappa/chiranth_siddappa.rst
> +It should be noted that no timing constraint violations were encountered during the implementation.
What is a timing constraint violation?

2019-06-15 13:05 UTC, deniederhut commented on papers/chiranth_siddappa/chiranth_siddappa.rst
> +It is important to note that when talking about the frequency provided as the sampling rate that it is not necessarily
You can simplify these three sentences into "The sampling frequency of the signal, 625kHz, is different from the clock frequency of the board, at 250MHz"

2019-06-15 13:05 UTC, deniederhut commented on papers/chiranth_siddappa/chiranth_siddappa.rst
> +       def __init__(self, freq_res, fs, n_bits,
What does the init method illustrate that is relevant to the paper?

2019-06-15 13:05 UTC, deniederhut commented on papers/chiranth_siddappa/chiranth_siddappa.rst
> +        def __init__(self, x, freq_res, fs, n_bits,
What does the init method illustrate that is relevant to the paper?

2019-06-15 13:05 UTC, deniederhut commented on papers/chiranth_siddappa/chiranth_siddappa.rst
> +In order to capture the full signal power with the dot product, it is necessary to store twice the length of the
I think you've stated this elsewhere

2019-06-15 13:05 UTC, deniederhut commented on papers/chiranth_siddappa/chiranth_siddappa.rst
> +reference. The other option is the CORDIC logic core provided by Xilinx which also would apply backpressure to the
What do you mean by "apply backpressure to the result"?

2019-06-15 13:05 UTC, deniederhut commented on papers/chiranth_siddappa/chiranth_siddappa.rst
> +An error was found in the way the cross correlation was being calculated during this part of the project that cause
This doesn't feel particularly relevant

2019-06-15 13:05 UTC, deniederhut commented on papers/chiranth_siddappa/caf.bib
> + @electronic{hartwellcaf,
This is not the correct way to cite a thesis

2019-06-15 13:05 UTC, deniederhut commented on papers/chiranth_siddappa/chiranth_siddappa.rst
> +.. [Atr03] P. Atreides. *How to catch a sandworm*,
You probably don't want to include a fake paper in your references section - this was just a placeholder for the demo .rst paper.

2019-06-15 13:05 UTC, deniederhut commented on papers/chiranth_siddappa/caf.bib
> + @electronic{gpsgov,
This is not the correct way to cite technical papers, nor regulations from a government body.

2019-06-15 13:05 UTC, deniederhut commented on papers/chiranth_siddappa/caf.bib
> + @electronic{abacus,
I can't find this paper - can you provide more information in the citation?

2019-06-15 13:05 UTC, deniederhut commented on papers/chiranth_siddappa/caf.bib
> +@electronic{dds,
This is not the correct way to cite a periodical.

2019-06-15 13:05 UTC, deniederhut commented on papers/chiranth_siddappa/abstract.txt
> +modules to target multiple devices.
I don't believe this paper describes how you are capable of targeting multiple devices.

2019-06-16 04:27 UTC, chiranthsiddappa commented on papers/chiranth_siddappa/chiranth_siddappa.rst
> +This bitfile is generated through the Vivado Design Suite that is provided by Xilinx.
The templating system is writing out Verilog code. Then, the Verilog modules are read by Vivado.
There used to be a section on this which might have helped but it was recommended earlier that this might be too domain specific. Should the full process be described further?

2019-06-16 06:23 UTC, chiranthsiddappa commented on papers/chiranth_siddappa/chiranth_siddappa.rst
> +This performance allows for a RTOS to be run on the CPU.
I'm going to avoid using term RTOS since the distribution of Ubuntu that is used in the examples from Xilinx doesn't use a real-time kernel.

2019-06-16 06:50 UTC, chiranthsiddappa commented on papers/chiranth_siddappa/chiranth_siddappa.rst
> +The need for an analysis of quantization stems from the way that digital radio frequency systems are built. In order to
I'll just remove this sentence because the following sentence is sufficient to convey why quantization is necessary.

2019-06-16 06:51 UTC, chiranthsiddappa commented on papers/chiranth_siddappa/caf.bib
> + @electronic{abacus,
A hunt for the original source has commenced.

2019-06-18 02:54 UTC, deniederhut commented
👀 you've been making a lot of commits! Is this ready for me to take a second look?

2019-06-18 03:52 UTC, chiranthsiddappa commented
@deniederhut Thanks for the review! I have a few remaining items to address at this time. 

If you have some time to provide a little more feedback though, I was wondering what could make the statement of "synthesized to any target device" more clear throughout the paper..

2019-06-21 11:45 UTC, deniederhut commented
Sure thing! It would be nice to know which devices specifically, and sort of a general, hand-wavy explanation as to what the major differences are between devices that your library is capable of abstracting over (e.g. can abstract of different I/O setups, but not different instruction sets).

2019-06-25 02:03 UTC, deniederhut commented
Just checking in - the approval deadline is tomorrow. Have you had time to make the final changes you mentioned? Or should I re-review as-is?

2019-06-25 16:16 UTC, chiranthsiddappa commented
> Just checking in - the approval deadline is tomorrow. Have you had time to make the final changes you mentioned? Or should I re-review as-is?

I will make the final changes today. It won't be very drastic from the current draft.

2019-06-26 02:20 UTC, deniederhut requested changes
This is shaping up nicely! I really enjoyed reading the more detailed sections on your implementation of arithmetic functions.

It looks like the citations sections still needs some work, and I think the introduction could be reorganized a bit to make things more clear. It would be good to trim down the abstract a bit as well, since this paper is currently over the 8 page limit.

2019-06-26 02:20 UTC, deniederhut commented on papers/chiranth_siddappa/abstract.txt
> +The purpose of this project is to provide a geolocation solution by generating code for the complex ambiguity function
This abstract is pretty long -- typically they are 4-8 sentences.

2019-06-26 02:20 UTC, deniederhut commented on papers/chiranth_siddappa/chiranth_siddappa.rst
> +:institution: University of Colorado Colorado Springs
It looks like you are missing the `:corresponding:` tag here

2019-06-26 02:20 UTC, deniederhut commented on papers/chiranth_siddappa/chiranth_siddappa.rst
> +The basic algorithm for calculating the complex ambiguity function for time difference of arrival and frequency offset (CAF)
Some readers might not know what a complex ambiguity function is. Here, you use it to define your problem space before you define what it is. It might make it easier for others to follow your paper if your introduction describes:

1. What people were trying to do (tell how far away something is)
2. Other approaches to doing this, and what was good or bad about them (e.g. false positives)
3. Briefly, what CAF is, and how it relates to previous solutions

2019-06-26 02:20 UTC, deniederhut commented on papers/chiranth_siddappa/chiranth_siddappa.rst
> +The main motivator for this project comes from the use of the CAF at the author's workplace where the field of work is
This sentence could be simplified to read "This project is concerned with satellite communication."

2019-06-26 02:20 UTC, deniederhut commented on papers/chiranth_siddappa/chiranth_siddappa.rst
> +but comes with much higher up front design cost :cite:`Hennessy`.
Why is the design cost higher? Because of the number of configuration options?

2019-06-26 02:20 UTC, deniederhut commented on papers/chiranth_siddappa/chiranth_siddappa.rst
> +The captured signals will be different for every use case, which motivates the need to ensure
What do you mean by this? That every satellite needs its own fpga implementation?

2019-06-26 02:20 UTC, deniederhut commented on papers/chiranth_siddappa/chiranth_siddappa.rst
> +In this implementation, the frequency offset is created by a signal generator and a complex multiply module that are
I might start a new paragraph here

2019-06-26 02:20 UTC, deniederhut commented on papers/chiranth_siddappa/chiranth_siddappa.rst
> +An example CAF surface is provided in Fig. :ref:`caf-surface-example` showing how the energy of the signal is spread over
I might start a new paragraph here

2019-06-26 02:20 UTC, deniederhut commented on papers/chiranth_siddappa/chiranth_siddappa.rst
> +made on PyPI :cite:`caf-verilog-pypi`.
🎉

2019-06-29 01:10 UTC, deniederhut commented
Hi @chiranthsiddappa ! Is this ready for me to have another read?

2019-06-30 00:34 UTC, chiranthsiddappa commented on papers/chiranth_siddappa/chiranth_siddappa.rst
> +The basic algorithm for calculating the complex ambiguity function for time difference of arrival and frequency offset (CAF)
I think I was able to address this by moving some of the writing from the abstract into the introduction. The only thing is I haven't run across any other actual approach, although the method is often referred to simply as an "ambiguity function". But the equation is the same. There are other implementations that might be worth mentioning, like matlab and the Python method included in the package.

2019-06-30 00:40 UTC, chiranthsiddappa commented
Hi @deniederhut ,
I was able to make the rest of the changes, so it's ready for another review!

2019-06-30 22:40 UTC, deniederhut approved these changes

2019-06-30 22:40 UTC, deniederhut commented
This looks really good! Thanks for all the hard work you put in editing this paper with me, and thanks for submitting to SciPy!

2019-07-03 13:43 UTC, merged