Paper: Software Engineering as Research Method
scipy-conference/scipy_proceedings pull request #554
Opened 2020-05-29 12:57 UTC by sbenthall

@MridulS and I expect to be making some additions over the course of the review period.

2020-06-17 14:35 UTC, sbenthall commented
Are there reviewers assigned for this article?

2020-06-18 01:22 UTC, deniederhut commented
Yes -- reviewers were assigned to your paper on 31 May.

2020-06-18 19:01 UTC, davclark commented
@sbenthall shared a link to this submission, so while I'm not a randomly assigned reviewer, I'll add a few notes in case they are useful.

First, I think this paper situates a useful case study within a broader high-impact domain (economic prediction). The specific case is almost certainly novel (as @sbenthall is a member of the research project), and to my knowlege the general framing is likewise tying together major long-term trends in science - tracing back to the introduction of the use of computers in science, as well as recent thinking in the philosophy of science - in a way that I've not seen in the Scientific Python community.

As a fan of Papert, I find myself yearning for a clearer statement of a thesis, and I think it's a claim that Papert made in *Mindstorms* - that academia desperately needs to include individuals who can make increasingly siloed knowledge intelligible to a broader community. But, I wouldn't push hard for this if the authors are happy with how they've organized their main points.

Also - hi @deniederhut!

2020-06-18 21:20 UTC, mepa commented
Hi @sbenthall. None of the assigned reviewers have responded to our invitation to review so I will be stepping in to help review your submission. This is a topic that truly interests me and I look forward to reading in detail. I'll complete the review this weekend. Please note that @deniederhut will soon announce an extension of the initial review deadline, which was today, to give reviewers a bit more time.

@davclark, thank you for jumping in with your comments!

2020-06-19 02:13 UTC, deniederhut commented
Hey @sbenthall ! Thanks to some awesome behind the scenes work by @stargaser, we now have experimental support for publishing papers with ORCIDs. If you have one and would like to add it to your paper, it's as simple as adding an `:orcid:` tag under your name in the paper header. [You can see an example of how to do this in the `00_vanderwalt` example paper](https://raw.githubusercontent.com/scipy-conference/scipy_proceedings/2020/papers/00_vanderwalt/00_vanderwalt.rst). If you don't have one, no worries! You can still publish your paper as is.

2020-06-19 18:46 UTC, sbenthall commented
@mepa Thank you for reviewing!

@davclark Thanks for your comment! My copy of _Mindstorms_ is locked away at the moment, but I will try to clarify his thesis in a later draft. The constructionism vs. computational thinking frame is taken from Barba's piece here:

https://lorenabarba.com/blog/computational-thinking-i-do-not-think-it-means-what-you-think-it-means/

which is cited but I wonder if it could be better worked in. Maybe a more complete piece analyzing Papert's connection to scientific programming would be a good topic for a different, standalone piece.

@deniederhut I've added my ORCID. Thanks for the heads up. @MridulS might add his too.

2020-06-21 19:03 UTC, mepa reviewed
Sebastian and Mridul, I enjoyed reading your paper! My comments are minor - mainly requests for clarifications, typo corrections, etc.

2020-06-21 19:03 UTC, mepa commented on papers/sebastian_benthall/sebastian_benthall.rst
> +physical world. :cite:`resnick1990lego`.
`world.` <-- period not needed

2020-06-21 19:03 UTC, mepa commented on papers/sebastian_benthall/sebastian_benthall.rst
> +complex and agent-based systems, and the Python ABM toolkit
- `Python agent-based modeling (ABM) toolkit`?
- It may be helpful to the uninitiated reader to give a concrete example of a "complex" or "agent-based" system that NetLogo is used to study. 
- `and the Python` ->  `and *in* the Python`

2020-06-21 19:03 UTC, mepa commented on papers/sebastian_benthall/sebastian_benthall.rst
> +   method.
I think it becomes more clear later in the text, but would it be possible here in the abstract to clarify (1) what are the opportunities being missed by members of the three roles when there is a lack in software engineering skills, and (2) why is depending solely on research software engineers insufficient (if I'm interpreting that correctly)?

2020-06-21 19:03 UTC, mepa commented on papers/sebastian_benthall/sebastian_benthall.rst
> +then-dominant representative agent (RA) based paradigm [#]
`paradigm [#]_` (missing the trailing underscore so it prints as "[#]" in the pdf)

2020-06-21 19:03 UTC, mepa commented on papers/sebastian_benthall/sebastian_benthall.rst
> +However, in Econ-ARK models, agents that optimize their
`agents optimize their` (remove "that")

2020-06-21 19:03 UTC, mepa commented on papers/sebastian_benthall/sebastian_benthall.rst
> +**Example**. An paradigmatic, simple example of the kind
`An` --> `A`

2020-06-21 19:03 UTC, mepa commented on papers/sebastian_benthall/sebastian_benthall.rst
> +period, :math:`m` are the market resources available to
`is the amount of market resources`?

2020-06-21 19:03 UTC, mepa commented on papers/sebastian_benthall/sebastian_benthall.rst
> +study models that have been published by researchers in Python
I would move `in Python` to clarify meaning: `have been published in Python by researchers`

2020-06-21 19:03 UTC, mepa commented on papers/sebastian_benthall/sebastian_benthall.rst
> +complicates the software architecture of the toolkit
This left me wondering how the blending of roles "complicates the software architecture of the toolkit", so it may be nice to add a few words summarizing how, or a phrase like `as described in the next section`.

2020-06-21 19:03 UTC, mepa commented on papers/sebastian_benthall/sebastian_benthall.rst
> +kinds of contributions are rarely considered first-order research contributions. Researchers work within a complex field of economic capital incentives (such as
I agree this is a problem, and not only in economics!

2020-06-21 19:03 UTC, mepa commented on papers/sebastian_benthall/sebastian_benthall.rst
> +the creation of assignments with Jupyter notebooks. :cite:`hamrick2016creatin` :cite:`blank2019nbgrader`
- `hamrick2016creating` (missing the "g", so it's rendered in the pdf as `[?]`)
- I think the period should go after the citations.

2020-06-21 19:03 UTC, mepa commented on papers/sebastian_benthall/sebastian_benthall.rst
> +and yet these are researcher increasingly need to learn and
`and yet researchers increasingly need to learn and use these in order to`

2020-06-21 19:03 UTC, mepa commented on papers/sebastian_benthall/sebastian_benthall.rst
> +or at another workplace.
This is a well-stated point.

2020-06-21 19:03 UTC, mepa commented on papers/sebastian_benthall/sebastian_benthall.rst
> +Noteably, both technical solutions, which have been developed only
`Notably` (remove the "e")

2020-06-21 19:03 UTC, mepa commented on papers/sebastian_benthall/sebastian_benthall.rst
> +setting up a local coding environment. :cite:`kim_2018`
Period goes after citation.

2020-06-21 19:03 UTC, mepa commented on papers/sebastian_benthall/sebastian_benthall.rst
> +new discoveries are integrated into the core software library--
Leave spaces around `--` in both cases? I'm not sure what is proper punctuation, but consistency between the two would be good.

2020-06-21 19:03 UTC, mepa commented on papers/sebastian_benthall/sebastian_benthall.rst
> +The Econ-ARK infrastructure is built around creating a sustainable community with respect to various different use cases and the challenges of creating sustainable scientific software. We discuss som
`Researchers, Publishers, Pedagogues, and Software Engineers` (since these are "roles")

2020-06-21 19:03 UTC, mepa commented on papers/sebastian_benthall/sebastian_benthall.rst
> +**Decoupling scientific content from code** A lot of scientific code is written as part of academic research projects where the incentives aren't closely aligned with those of creating scientific sof
- Add a period after "code"
- `overlap of the researcher, publisher, and software engineer roles` (all singular)
- Please rephrase the last sentence and/or break into two sentences as the meaning is not clear.

2020-06-21 19:03 UTC, mepa commented on papers/sebastian_benthall/sebastian_benthall.rst
> +**Reproducible builds of scientific content**, Reproducibility crisis has been plaguing academic research for some time and the current ecosystem of software packaging and distribution certainly does
- Add a period after "content"
- `...still requires...` (add "s")
- `pre-built`
- `"one-click" (via commands)` (if I understand correctly, this means to say that artifacts are generated not by actual "clicks" of a button but via a command issued in a terminal, notebook, etc.)

2020-06-21 19:03 UTC, mepa commented on papers/sebastian_benthall/sebastian_benthall.rst
> +**Pedagogy Teaching resources**  To keep the wheels turning in a research discipline we require effective pedagogical resources, especially in domains which are increasingly using scientific software
- `Pedagogy/Teaching resources.` (add "/" and period, or correct as necessary)
- `The reproducibility crisis...`
- `...your local environment. But luckily...`
- `...teaching courses that depend heavily on scientific software.`
- `...used MyBinder (publicly and privately hosted)...`
- `...especially for students who...`

2020-06-21 19:03 UTC, mepa commented on papers/sebastian_benthall/sebastian_benthall.rst
> +was accompanying by an online Dashboard [#]_ that allowed users
`accompanying` --> `accompanied`

2020-06-21 19:03 UTC, mepa commented on papers/sebastian_benthall/sebastian_benthall.rst
> +.. [#] \url{https://mybinder.org/v2/gh/econ-ark/Pandemic/master?urlpath=voila%2Frender%2FCode%2FPython%2Fdashboard.ipynb}
I don't think you need `\url` and curly brackets (check the rendered pdf)

2020-06-21 19:03 UTC, mepa commented on papers/sebastian_benthall/sebastian_benthall.rst
> +software, as many computational models are not being presented
"impact that domains specific research software" <-- meaning unclear; impact that does what?

2020-06-21 19:03 UTC, mepa commented on papers/sebastian_benthall/sebastian_benthall.rst
> +  Initial decisions like hard coding variables (which happens in a lot of academic research projects) in the code while creating the research artifact could lead away from creating a well defined reu
- `To tackle this...` (remove "and" and start a new sentence)
- `...and maintain the research artifacts...` (remove "we")

2020-06-21 19:03 UTC, mepa commented on papers/sebastian_benthall/sebastian_benthall.rst
> +  This decoupling exercise also helps with reproducibility part of research projects as it gives other researchers necessary tools to examine the research artifacts. The decoupling can also be extend
- `...helps with the reproducibility part...` (add "the")
- `...gives other researchers the necessary tools...` (add "the")

2020-06-21 19:03 UTC, mepa commented on papers/sebastian_benthall/sebastian_benthall.rst
> +on Mathematical Methods", Econometrics, or other methods
remove stray quotes

2020-06-22 20:38 UTC, sbenthall commented
Thank you very much @mepa 
I'll make the necessary edits this week.

2020-06-26 13:59 UTC, deniederhut commented
Hi @sbenthall ! Have you had a chance to incorporate this review into your submission?

2020-06-26 16:53 UTC, sbenthall commented
@deniederhut I was just able to get to this today. I've pushed the edits based on @mepa 's review.

A couple of the more substantive recommendations (the example of an ABM, the question about how the roles complicated the architecture) I've made notes about but may not be able to resolve quickly.

Will there be another review?

2020-06-27 16:25 UTC, deniederhut commented
> Will there be another review?

The expectation is that this is more of an ongoing process of collaboration with Meghann to get this paper ready for print by 2 July.

2020-06-29 12:45 UTC, deniederhut commented
Hi @mepa ! Are you happy with the updates to the paper?

2020-07-01 03:31 UTC, mepa commented on papers/sebastian_benthall/sebastian_benthall.rst
> +   software engineering.
please check grammar of this sentence

2020-07-01 04:42 UTC, mepa reviewed
Thanks for the changes, @sbenthall. Sorry I'm just getting around to addressing them. 

I've added a few more comments in this second review, and plan to read the pdf end-to-end tomorrow evening to check for potential final changes. It's looking good!

2020-07-01 04:42 UTC, mepa commented on papers/sebastian_benthall/sebastian_benthall.rst
> +   method.
Thanks for making the changes! The abstract sounds great, with the minor correction of the sentence noted above.

2020-07-01 04:42 UTC, mepa commented on papers/sebastian_benthall/sebastian_benthall.rst
> +.. Example of ABM
Thanks, I'll keep an eye out for this addition and review it if you get a chance to write up an example of ABM.

2020-07-01 04:42 UTC, mepa commented on papers/sebastian_benthall/sebastian_benthall.rst
> +then-dominant representative agent (RA) based paradigm [#]_
It renders correctly now! Please add a period to complete the sentence :)

2020-07-01 04:42 UTC, mepa commented on papers/sebastian_benthall/sebastian_benthall.rst
> +(The recent case of UK COVID microsimulation code :cite:`covidsim2020`,
remove comma

2020-07-01 04:42 UTC, mepa commented on papers/sebastian_benthall/sebastian_benthall.rst
> +correct incentives).
period inside parentheses

2020-07-01 04:42 UTC, mepa commented on papers/sebastian_benthall/sebastian_benthall.rst
> +Initiatives like Journal of Open Source Software (JOSS) helps to align
Initiatives...help (remove 's')

2020-07-01 04:42 UTC, mepa commented on papers/sebastian_benthall/sebastian_benthall.rst
> +"technical debt" :cite: `kruchten2012technical`. An illustraiont
- this isn't rendering correctly in the pdf (one can download and check from [here](http://procbuild.scipy.org/))
- `illustration`

Also, this sentence/example strikes a cord for me. I sometimes see the tendency in industry, also. Good software engineering practices (or an effort toward them), even in the research phase of a project, seem to enable more accurate and easier tech transfer of research artifacts, and more fluid collaboration between teammates.

2020-07-01 04:42 UTC, mepa commented on papers/sebastian_benthall/sebastian_benthall.rst
> +environment required for teaching courses that depend heavily
...heavily *on* scientific...

2020-07-01 04:42 UTC, mepa commented on papers/sebastian_benthall/sebastian_benthall.rst
> +was accompanied by an online Dashboard [#]_ that allowed users
allows? (present tense since the dashboard still exists)

2020-07-01 04:42 UTC, mepa commented on papers/sebastian_benthall/sebastian_benthall.rst
>  to change parameters of the model and visualized their impact
visualize?

2020-07-02 21:41 UTC, sbenthall commented on papers/sebastian_benthall/sebastian_benthall.rst
> +"technical debt" :cite: `kruchten2012technical`. An illustraiont
Yes!

2020-07-02 23:21 UTC, sbenthall commented
Hello.

Thanks for these additional edits, @mepa.

I've addressed your comments. I also did my own editing pass for punctuation, style, etc. These are all in the latest commit.

2020-07-03 02:32 UTC, mepa commented on papers/sebastian_benthall/sebastian_benthall.rst
> +A primary goal of its flagship software library, HARK
remove comma

2020-07-03 02:32 UTC, mepa commented on papers/sebastian_benthall/sebastian_benthall.rst
> +the mathematically optimal amount to save. :cite:`carroll2011solution`
period after citation

2020-07-03 02:33 UTC, mepa commented on papers/sebastian_benthall/sebastian_benthall.rst
> +vision of the software's potential. :cite:`crouch2013software`
period after citation

2020-07-03 02:33 UTC, mepa commented on papers/sebastian_benthall/sebastian_benthall.rst
> +Preliminery efforts towards such a journal have been
Preliminary

2020-07-03 02:38 UTC, mepa commented on papers/sebastian_benthall/sebastian_benthall.rst
> +also enables the use of empirical data and model fitting techniques,
enable

2020-07-03 02:45 UTC, mepa commented on papers/sebastian_benthall/sebastian_benthall.rst
> +practices (software versioning, CI, testing).
spell out "continuous integration"?

2020-07-03 02:47 UTC, mepa commented on papers/sebastian_benthall/sebastian_benthall.rst
> +reconceived as a scientific method, as opposed to a peripheral skill.
great punch line! :)

2020-07-03 02:52 UTC, mepa commented
LGTM, @sbenthall. I really enjoyed reading this paper! I added a few minor edit comments as I read through it one last time, but I'm happy with the paper as is.

FYI, @deniederhut

2020-07-03 02:53 UTC, mepa commented on papers/sebastian_benthall/sebastian_benthall.rst
> +.. Example of ABM
💯

2020-07-03 14:27 UTC, sbenthall commented
Thanks again @mepa 

@deniederhut may I make the edits suggested by @mepa even though it's past the deadline?

2020-07-03 18:50 UTC, mepa commented
> @deniederhut may I make the edits suggested by @mepa even though it's past the deadline?

Yes, please feel free to make the changes today (tomorrow at the latest), @sbenthall. Thanks!

2020-07-05 14:52 UTC, deniederhut requested changes
Hey @sbenthall ! Sorry to to bring this up so late in the process, but it looks like you didn't finish the reference section?

2020-07-05 14:52 UTC, deniederhut commented on papers/sebastian_benthall/mybib.bib
> +  year={2017}
Looks like this is missing a url

2020-07-05 14:52 UTC, deniederhut commented on papers/sebastian_benthall/mybib.bib
> +  journal={Lorena A. Barba Group},
I'm not used to seeing a blog post referenced as a journal. Was this meant to be a link to the website?

2020-07-05 14:52 UTC, deniederhut commented on papers/sebastian_benthall/mybib.bib
> +@misc{benthall_2019, title={US Research Software Sustainability Institute}, url={http://urssi.us/blog/2019/02/25/software-incubator-workshop-a-synthesis/}, journal={US Research Software Sustainabilit
Is this a journal or a blog?

2020-07-05 14:52 UTC, deniederhut commented on papers/sebastian_benthall/mybib.bib
> +  title={nbgrader: A tool for creating and grading assignments in the Jupyter Notebook},
This is missing a DOI

2020-07-05 14:52 UTC, deniederhut commented on papers/sebastian_benthall/mybib.bib
> +  title={Biopython: freely available Python tools for computational molecular biology and bioinformatics},
This is also missing a DOI

2020-07-05 14:52 UTC, deniederhut commented on papers/sebastian_benthall/mybib.bib
> +  title={The Econ-ARK and HARK: Open Source Tools for Computational Economics},
Was this the SciPy paper? If so, this should be an in-proceedings, with proceedings title, editors, doi, etc.

2020-07-06 00:28 UTC, sbenthall commented
Yikes! Sorry--I took this July 4th weekend off.
I'll work on this now.

2020-07-06 00:38 UTC, sbenthall commented on papers/sebastian_benthall/mybib.bib
> +  journal={Lorena A. Barba Group},
I think for this and the other blog post reference, I used a citation generator that uses the 'journal' field to refer to the publication venue, which in this case is the blog title.

I believe this is common practice? Though there are other errors in this reference, and there should be a URL

2020-07-06 19:07 UTC, sbenthall commented
Edits are in.

2020-07-07 00:00 UTC, deniederhut commented on papers/sebastian_benthall/mybib.bib
> +  title={Statistical modeling: The two cultures (with comments and a rejoinder by the author)},
I think this one still needs a DOI

2020-07-07 00:03 UTC, deniederhut commented on papers/sebastian_benthall/mybib.bib
> +  author={Carroll, Christopher D and White, Matthew N},
is this missing a journal?

2020-07-07 00:03 UTC, deniederhut commented on papers/sebastian_benthall/mybib.bib
> +  author={Carroll, Christopher D and Crawley, Edmund and Slacalek, Jiri and White, Matthew N},
is this also missing a journal?

2020-07-07 00:04 UTC, deniederhut commented on papers/sebastian_benthall/mybib.bib
> +  journal={Computing in Science \& Engineering},
I think this one is also missing a DOI

2020-07-07 00:05 UTC, deniederhut commented on papers/sebastian_benthall/mybib.bib
> +  author={Dalle, Jean-Michel and Rousseau, Guillaume},
I think this too is missing a DOI

2020-07-07 00:08 UTC, MridulS commented on papers/sebastian_benthall/mybib.bib
> +  title={Statistical modeling: The two cultures (with comments and a rejoinder by the author)},
for ref: doi:10.1214/ss/1009213726

2020-07-07 00:11 UTC, MridulS commented on papers/sebastian_benthall/mybib.bib
> +  author={Carroll, Christopher D and White, Matthew N},
This is a reference to a course, https://safe-frankfurt.de/fileadmin/user_upload/editor_common/Events/Chris_Carrol_Syllabus.pdf . What should we put in here?

2020-07-07 00:11 UTC, MridulS commented on papers/sebastian_benthall/mybib.bib
> +  author={Carroll, Christopher D and Crawley, Edmund and Slacalek, Jiri and White, Matthew N},
This isn't published yet, it's in the review process.

2020-07-07 00:13 UTC, MridulS commented on papers/sebastian_benthall/mybib.bib
> +  journal={Computing in Science \& Engineering},
for ref: doi.org/10.1109/MCSE.2013.133

2020-07-07 00:14 UTC, MridulS commented on papers/sebastian_benthall/mybib.bib
> +  author={Dalle, Jean-Michel and Rousseau, Guillaume},
for ref: doi:10.1049/ic:20040262

2020-07-07 00:25 UTC, deniederhut commented
Also, it looks like the editor names and some other info is missing in the rendered pdf. Our expectation is that they will look something like this:

<img width="278" alt="Screenshot 2020-07-06 19 22 59" src="https://user-images.githubusercontent.com/6868396/86674448-504aeb00-bfbe-11ea-89b2-5412ed5bbea3.png">

2020-07-07 00:25 UTC, deniederhut commented on papers/sebastian_benthall/mybib.bib
> +  author={Carroll, Christopher D and Crawley, Edmund and Slacalek, Jiri and White, Matthew N},
That's okay. Could we add the journal name and something like `in review` for the year?

2020-07-07 00:26 UTC, deniederhut commented on papers/sebastian_benthall/mybib.bib
> +  author={Carroll, Christopher D and White, Matthew N},
Okay. I think I'm thrown off by seeing all of these listed as articles. Would it make sense to use `@misc` for these kinds of bibfile entries?

2020-07-07 00:28 UTC, MridulS commented on papers/sebastian_benthall/mybib.bib
> +  author={Carroll, Christopher D and White, Matthew N},
Sure `@misc`= sounds good.

2020-07-07 17:26 UTC, sbenthall commented
@deniederhut can you point to an example of a scipy paper that has it's reference to another scipy paper correctly bibtexed?

2020-07-10 00:25 UTC, deniederhut commented
Sure, the screencap is from the rendered pdf of https://github.com/scipy-conference/scipy_proceedings/pull/570/files#diff-543a34787bd14e4ee6f7aa23dcdd1226R177

2020-07-10 13:19 UTC, sbenthall commented
Perfect. Thank you! I'll correct all those references now. Thanks for your patience.

2020-07-10 13:32 UTC, sbenthall commented
I see that BibTex marks up the capitalization of titles.
Is that expected?

2020-07-10 14:29 UTC, sbenthall commented
Ah! The proceedings website generates the correct BibTex. fantastic.

2020-07-10 15:03 UTC, sbenthall commented
Should be good now. sorry for the delay

2020-07-10 21:10 UTC, deniederhut commented on papers/sebastian_benthall/mybib.bib
> +  title={Statistical modeling: The two cultures (with comments and a rejoinder by the author)},
Did we add this?

2020-07-10 21:11 UTC, deniederhut commented on papers/sebastian_benthall/mybib.bib
> +  author={Donoho, David},
I think this is missing a DOI

2020-07-10 21:12 UTC, deniederhut commented on papers/sebastian_benthall/mybib.bib
> +  author={Guzdial, Mark},
I think this is also missing a DOI

2020-07-10 21:12 UTC, deniederhut commented on papers/sebastian_benthall/mybib.bib
> +  author={Hamrick, Jessica B},
May also be missing a DOI

2020-07-10 21:12 UTC, deniederhut commented
No worries! I think the references are still missing some DOIs though.

2020-07-10 21:49 UTC, sbenthall commented
I've now gone through all the references, looked them up on CrossRef, and added a DOI if there wasn't one.

2020-07-14 14:10 UTC, sbenthall commented on papers/sebastian_benthall/mybib.bib
> +  author={Guzdial, Mark},
There was indeed a DOI for this. I've added it now.

2020-07-15 02:52 UTC, deniederhut commented
Sweet - thanks for going through all the references!

2020-07-15 02:55 UTC, deniederhut approved these changes

2020-07-15 02:55 UTC, merged

2020-07-15 19:59 UTC, sbenthall commented
Thanks so much, @deniederhut !!

2020-07-15 20:00 UTC, sbenthall commented
May I ask how often the proceedings site gets updated?
http://conference.scipy.org/proceedings/scipy2020/