Paper: Submission 106: Boost-histogram: High-Performance Histograms as Objects
scipy-conference/scipy_proceedings pull request #557
Opened 2020-05-29 20:22 UTC by henryiii

Submitting draft of paper.

A few of the coauthors may be doing a more in-depth review and making some final corrections in the next few days.

CC @HDembinski, @JPivarski, @LovelyBuggies.

2020-05-31 19:14 UTC, HDembinski commented on papers/henry_schreiner/00_main.rst
> +In conclusion, boost-histogram provides a powerful abstraction for histograms as a collection of axes with an accumulator-backed storage. Filling and manipulating histograms is simple and natural, wh
Suggested replacement of the last, very long sentence:

At the same time, Boost.Histogram in C++ is continuously improved and expanded with new features, from which boost-histogram benefits nearly automatically. The shared code-base with C++ allows Python to profit, while boost-histogram in C++ is profiting from ideas feed back from Python, creating a win-win situation for all parties.

2020-05-31 19:15 UTC, HDembinski commented on papers/henry_schreiner/00_main.rst
> +In conclusion, boost-histogram provides a powerful abstraction for histograms as a collection of axes with an accumulator-backed storage. Filling and manipulating histograms is simple and natural, wh
That's my only comment, everything else looks good!

2020-06-08 16:35 UTC, henryiii commented
The current author order is random, I'm reordering by contribution (also happens to be alphabetical after corresponding author - I think corresponding author has to be first?). Just a heads up (it's the only change).

2020-06-11 12:05 UTC, LovelyBuggies approved these changes

2020-06-19 02:15 UTC, deniederhut commented
Hey @henryiii ! Thanks to some awesome behind the scenes work by @stargaser, we now have experimental support for publishing papers with ORCIDs. If you have one and would like to add it to your paper, it's as simple as adding an `:orcid:` tag under your name in the paper header. [You can see an example of how to do this in the `00_vanderwalt` example paper](https://raw.githubusercontent.com/scipy-conference/scipy_proceedings/2020/papers/00_vanderwalt/00_vanderwalt.rst). If you don't have one, no worries! You can still publish your paper as is.

2020-06-19 02:34 UTC, deniederhut commented
Also, just to check in with you real quick -- it looks like none of the reviewers assigned to this paper have been able to complete a review. One of the chairs will step in to review your submission this weekend, and you'll have some feedback by Monday morning.

2020-06-19 03:11 UTC, henryiii commented
@HDembinski, I added your ORCID since it was easy to find, @jpivarski and @LovelyBuggies., I don't know yours if you have one.

2020-06-19 09:30 UTC, HDembinski commented
Ok

2020-06-21 13:06 UTC, jpivarski commented
> @HDembinski, I added your ORCID since it was easy to find, @jpivarski and @LovelyBuggies., I don't know yours if you have one.

This is my OrcId: https://orcid.org/0000-0002-6649-343X

Thanks!

2020-06-21 17:50 UTC, henryiii reviewed
Thanks, Nino!

2020-06-22 05:48 UTC, deniederhut requested changes
I had no idea my life was missing a dedicated histogram object until I read this paper, and now it seems completely obvious. This was really great -- thanks for submitting!

I've left a few inline comments about grammar/spelling. It might also be nice to add a few sentences about a popular algorithm that makes extensive use of histograms to motivate the performance section. My expectation is that several people in your audience will only have ever used histograms for plotting.

2020-06-22 05:48 UTC, deniederhut commented on papers/henry_schreiner/00_main.rst
> +    Histograms that can be filled, manipulated, sliced, and projected as
Is there a reason we are capitalizing 'histogram' here?

2020-06-22 05:48 UTC, deniederhut commented on papers/henry_schreiner/00_main.rst
> +    provided interesting and distribution and design challenges with useful
There might be one too many 'and's here

2020-06-22 05:48 UTC, deniederhut commented on papers/henry_schreiner/00_main.rst
> +.. [#] https://scikit-hep.org
![image](https://user-images.githubusercontent.com/6868396/85249748-3cc64e80-b41a-11ea-98a4-72fd6727da14.png)

Rad logo!

2020-06-22 05:48 UTC, deniederhut commented on papers/henry_schreiner/00_main.rst
> +In the High Energy Physics (HEP) community, histogramming is vital to most of our analysis. As part of building tools in Python to provide a friendly and powerful alternative to the ROOT C++ analysis
'relegated' feels a bit negative. Maybe we could say something like '(discussed briefly below)'?

2020-06-22 05:48 UTC, deniederhut commented on papers/henry_schreiner/00_main.rst
> +Almost as important as defining what a histogram is limiting what a histogram is not. Notice the missing item above: a histogram, in this definition, is not a plot or a visual aid. It is not a plot a
Could we cite matplotlib here? https://matplotlib.org/3.2.1/citing.html

2020-06-22 05:48 UTC, deniederhut commented on papers/henry_schreiner/00_main.rst
> +The first area identified was **Design**; here many popular libraries fell short. Histograms need to be represented as an object, rather than a collection of NumPy arrays, in order to naturally manip
Designing intuitive interfaces is hard. Instead of saying other libraries 'fell short', could we focus on the innovations in boost-histogram? E.g. "downsampling bins on raw numpy arrays is a bit tedious and prone to off-by-one errors; we solved this problem by doing X".

2020-06-22 05:48 UTC, deniederhut commented on papers/henry_schreiner/00_main.rst
> +The first area identified was **Design**; here many popular libraries fell short. Histograms need to be represented as an object, rather than a collection of NumPy arrays, in order to naturally manip
I'm not a physicist, and some of the vocabulary here is unfamiliar. Is 'live data taking conditions' the same thing as 'streaming data'?

'extra information to assist the user' == 'metadata'?

'You should be able easily sum histograms, such as from different threads.' -- I'm not sure what this means

2020-06-22 05:48 UTC, deniederhut commented on papers/henry_schreiner/00_main.rst
> +The third area identified was **Performance**; when dealing with very large datasets that will not fit in memory, the filling performance becomes critical. High performance filling is also useful in
'high performance' or 'highly performant'?

2020-06-22 05:48 UTC, deniederhut commented on papers/henry_schreiner/00_main.rst
> +The fourth and final area identified was **Distribution**. A great library is not useful if no one can install it; it is especially important that students and inexperienced users be able to install
We have two sentences here that start with 'It also needed'

2020-06-22 05:48 UTC, deniederhut commented on papers/henry_schreiner/00_main.rst
> +About a year ago, a new C++14 library was proposed to the Boost C++ libraries called Boost.Histogram; it was unanimously accepted and released as part of the Boost C++ libraries version 1.70 after th
Yay collaboration! Is there a citation for the existing boost.histogram library?

2020-06-22 05:48 UTC, deniederhut commented on papers/henry_schreiner/00_main.rst
> +You can access ``ax`` as ``hist.axes[0]``. Note that boost-histogram is not plotting; this is simply using the simple access to histogram properties and existing matplotlib functionality. A similar e
Seems like there is at least one too many 'simple's in this sentence

2020-06-22 05:48 UTC, deniederhut commented on papers/henry_schreiner/00_main.rst
> +You need to provide both directions in the transform, so that boost-histogram can add values to bins and find bin edges. Note: don't actually use exactly this code; there is a ``bh.axis.transform.log
> Note: don't actually use exactly this code

🙏

2020-06-22 05:48 UTC, deniederhut commented on papers/henry_schreiner/00_main.rst
> +This way of thinking can radically change how you design for a problem. Instead of running a series of histograms over a piece of data every time you want a new selection, instead you can build a lar
There are one too many 'instead's here, and if we keep this same sentence structure we'll also want to swap out that semicolon for a colon.

2020-06-22 05:48 UTC, deniederhut commented on papers/henry_schreiner/00_main.rst
> +The future for histogramming in Python is bright. At least three more projects are being developed on top or using boost-histogram. **Hist** [#]_ is a histogram front-end for analysts, much like Pand
I think there are one too many "Summer"s here

2020-06-22 14:33 UTC, henryiii commented on papers/henry_schreiner/00_main.rst
> +    Histograms that can be filled, manipulated, sliced, and projected as
Usually, but not exactly here. :)

2020-06-22 14:33 UTC, henryiii commented on papers/henry_schreiner/00_main.rst
> +.. [#] https://scikit-hep.org
Thanks!

2020-06-22 14:35 UTC, henryiii commented on papers/henry_schreiner/00_main.rst
> +Almost as important as defining what a histogram is limiting what a histogram is not. Notice the missing item above: a histogram, in this definition, is not a plot or a visual aid. It is not a plot a
I really thought I had, somehow it got missed. Thanks!

2020-06-22 14:37 UTC, henryiii commented on papers/henry_schreiner/00_main.rst
> +You can access ``ax`` as ``hist.axes[0]``. Note that boost-histogram is not plotting; this is simply using the simple access to histogram properties and existing matplotlib functionality. A similar e
I've asked @HDembinski, we cite Boost as a whole, but maybe we could cite the Histogram package separately. I've seen at least one or two Boost libraries with their own citations.

2020-06-22 14:37 UTC, henryiii commented on papers/henry_schreiner/00_main.rst
> +About a year ago, a new C++14 library was proposed to the Boost C++ libraries called Boost.Histogram; it was unanimously accepted and released as part of the Boost C++ libraries version 1.70 after th
I've asked @HDembinski, we cite Boost as a whole, but maybe we could cite the Histogram package separately. I've seen at least one or two Boost libraries with their own citations.

2020-06-22 14:38 UTC, henryiii commented on papers/henry_schreiner/00_main.rst
> +You need to provide both directions in the transform, so that boost-histogram can add values to bins and find bin edges. Note: don't actually use exactly this code; there is a ``bh.axis.transform.log
👍

2020-06-22 14:47 UTC, henryiii commented on papers/henry_schreiner/00_main.rst
> +This way of thinking can radically change how you design for a problem. Instead of running a series of histograms over a piece of data every time you want a new selection, instead you can build a lar
See if this is better; I still have the semicolon.

2020-06-23 00:49 UTC, deniederhut commented on papers/henry_schreiner/00_main.rst
> +This way of thinking can radically change how you design for a problem. Instead of running a series of histograms over a piece of data every time you want a new selection, instead you can build a lar
Yeah, so semicolons are typically used to join two independent clauses, and that last clause (about pandas) is subordinate to "instead of running a series": a clause which is also pretty far away. The comparison to pandas -- which I gather is that the productivity gain of going from several numpy arrays to boost histogram is similar to going from a collection of numpy arrays to a feature rich table -- is never stated explicitly, which might not be helping you make the point you want to make most effectively.

Maybe we can sidestep the punctuation issue by thinking about even better ways to express your argument here. What did a tabular data workflow look like before tables? What does it look like now? What does a bag-of-numpy-arrays workflow look like? How much simpler is it now?

2020-06-23 03:06 UTC, henryiii commented on papers/henry_schreiner/00_main.rst
> +This way of thinking can radically change how you design for a problem. Instead of running a series of histograms over a piece of data every time you want a new selection, instead you can build a lar
I tried a minor rewrite of this paragraph, is that better? I'm trying to compare it to the `.xs` and `.groupby` selectors, such as the usage in my post here: <https://iscinumpy.gitlab.io/post/johns-hopkins-covid/> - Building a histogram with axes for later selection is very much like that sort of usage in Pandas.

2020-06-23 22:15 UTC, henryiii commented on papers/henry_schreiner/00_main.rst
> +About a year ago, a new C++14 library was proposed to the Boost C++ libraries called Boost.Histogram; it was unanimously accepted and released as part of the Boost C++ libraries version 1.70 after th
@HDembinski is happy with just the overall Boost citation, as that covers Boost.Histogram.

2020-06-25 13:42 UTC, deniederhut commented on papers/henry_schreiner/00_main.rst
> +About a year ago, a new C++14 library was proposed to the Boost C++ libraries called Boost.Histogram; it was unanimously accepted and released as part of the Boost C++ libraries version 1.70 after th
👍

2020-06-25 13:53 UTC, deniederhut commented on papers/henry_schreiner/00_main.rst
> +This way of thinking can radically change how you design for a problem. Instead of running a series of histograms over a piece of data every time you want a new selection, instead you can build a lar
This looks a lot more readable to me. Thanks!

2020-06-25 13:56 UTC, deniederhut commented
Have you had some time to think up a good motivating example or use case? I think it will help make this submission even more interesting/understandable to a general audience.

2020-06-25 14:05 UTC, henryiii commented
> Have you had some time to think up a good motivating example or use case? I think it will help make this submission even more interesting/understandable to a general audience.

I added https://github.com/scipy-conference/scipy_proceedings/pull/557/commits/f799bd310ac9b52de19692718d554c141d9c5f46 with that in mind, is something like that what you are thinking of?

2020-06-25 14:06 UTC, henryiii commented
Or were you thinking of a more fleshed out "user story" at the beginning?

2020-06-25 14:40 UTC, deniederhut commented
Yeah, I think I was imagining something that links this to one or more applications or end goals. E.g. something like 

> understanding x real-thing-in-the-world requires solving y system, but y is mathematically intractable, so ... [then a miracle occurs] ... storing the exact probability mass functions would require z exabytes of memory, so instead we approximate them via this phenomenally well-engineered library called boost-histogram. This is one specific example, but boost-histogram can be applied to any task that involves estimating distributions, including [non-exhaustive, but broad list of application domains].

Does that make sense?

2020-06-30 13:38 UTC, deniederhut commented
Hi everyone! Friendly reminder that the open review period ends 2 July -- the committee will be making final decisions on each paper this Friday.

2020-07-02 12:39 UTC, deniederhut commented
Hi @henryiii ! Have you had some time to think up a good motivating example or use case?

2020-07-02 12:41 UTC, henryiii commented
I have 1-2 ideas. I'll try to either add one or post 1-2 here in a couple of hours.

2020-07-02 17:51 UTC, henryiii commented
@deniederhut I've added a motivation section, with an example, is that better?

2020-07-02 22:46 UTC, stargaser commented
Hi @henryiii, I'm one of the conference co-chairs doing some formatting checks. The one small item I found is hyperlinks not appearing for some of the DOIs in the reference section. I'll try to add some suggestions inline, borrowing from some of the other papers, a little later today.

2020-07-02 23:22 UTC, stargaser reviewed
Some suggestions about the DOIs in the reference list, made in-line.

2020-07-02 23:22 UTC, stargaser commented on papers/henry_schreiner/00_main.rst
> +        `DOI:10.1109/MCSE.2011.37 <https://doi.org/10.1109/MCSE.2011.37>`
```suggestion
        `DOI:10.1109/MCSE.2011.37 <https://doi.org/10.1109/MCSE.2011.37>`_
```

2020-07-02 23:22 UTC, stargaser commented on papers/henry_schreiner/00_main.rst
> +        Computing in Science & Engineering, vol. 9, no. 3, 90-95 (2007).
Please add the DOI for matplotlib per https://www.scipy.org/citing.html#matplotlib which is https://doi.org/10.1109/MCSE.2007.55

2020-07-02 23:22 UTC, stargaser commented on papers/henry_schreiner/00_main.rst
> +        Nature Methods, in press. DOI:10.1038/s41592-019-0686-2
```suggestion
        Nature Methods, in press. `DOI:10.1038/s41592-019-0686-2 <https://doi.org/10.1038/s41592-019-0686-2>`_
```

2020-07-02 23:22 UTC, stargaser commented on papers/henry_schreiner/00_main.rst
> +        DOI:10.1051/epjconf/201921406005
```suggestion
        `DOI:10.1051/epjconf/201921406005 <https://doi.org/10.1051/epjconf/201921406005>`_
```

2020-07-02 23:22 UTC, stargaser commented on papers/henry_schreiner/00_main.rst
> +        `DOI:10.1145/2833157.2833162 <https://doi.org/10.1145/2833157.2833162>`
```suggestion
        `DOI:10.1145/2833157.2833162 <https://doi.org/10.1145/2833157.2833162>`_
```

2020-07-02 23:22 UTC, stargaser commented on papers/henry_schreiner/00_main.rst
> +        DOI:10.5281/zenodo.3814709
```suggestion
        `DOI:10.5281/zenodo.3814709 <https://doi.org/10.5281/zenodo.3814709>`_
```

2020-07-02 23:48 UTC, henryiii commented
Thanks! I've cleaned up the references a bit, and made sure all the links click through.

2020-07-03 12:59 UTC, deniederhut commented
> I've added a motivation section

🙌 great example! Thanks -- this is exactly what I was hoping for.

2020-07-03 12:59 UTC, deniederhut approved these changes

2020-07-05 14:56 UTC, merged