Paper: Submission 92
scipy-conference/scipy_proceedings pull request #560
Opened 2020-05-29 22:12 UTC by rkube

If you are creating this PR in order to submit a draft of your paper,
see http://procbuild.scipy.org/ for logs generated by the build
process.

See the [project readme](https://github.com/scipy-conference/scipy_proceedings#build-your-paper)
for more information.

2020-05-30 22:11 UTC, deniederhut commented
> Files changed: 411 

That a lot of new files. How many of these are necessary to build the paper?

2020-05-30 22:57 UTC, rkube commented
About 10. This PR includes the data files to generate the plots for reproducibility. I'll make a new PR with only the files to generate the paper.

Sent from my mobile. Please excuse the brevity.

> On May 30, 2020, at 6:11 PM, Dillon Niederhut <notifications@github.com> wrote:
> 
> ﻿
> Files changed: 411
> 
> That a lot of new files. How many of these are necessary to build the paper?
> 
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub, or unsubscribe.

2020-06-01 00:55 UTC, deniederhut commented
🤔  well we don't want to discourage reproducibility, but the branches with papers aren't a very visible place for them either. Would it make sense to have those files in a repository under your account and then link to it from the paper?

2020-06-01 13:50 UTC, rkube commented
The dataset is relocated to zenodo and referenced in the article. Do I need to update the pull-request or is the latest push to my fork automatically applied?

2020-06-01 23:50 UTC, deniederhut commented
Awesome! Thanks for doing that. The pull request references the most recent commit on your branch, so we should be good to go. One question - had you meant to move the .py files too?

2020-06-02 12:58 UTC, rkube commented
Sorry about that, I usually keep those in git too - force of habit. The pull request should have only the article rst file and the necessary png included.

2020-06-19 02:18 UTC, deniederhut commented
Hey @rkube ! Thanks to some awesome behind the scenes work by @stargaser, we now have experimental support for publishing papers with ORCIDs. If you have one and would like to add it to your paper, it's as simple as adding an `:orcid:` tag under your name in the paper header. [You can see an example of how to do this in the `00_vanderwalt` example paper](https://raw.githubusercontent.com/scipy-conference/scipy_proceedings/2020/papers/00_vanderwalt/00_vanderwalt.rst). If you don't have one, no worries! You can still publish your paper as is.

2020-06-19 02:40 UTC, deniederhut commented
Also, it looks like none of the reviewers assigned to your paper have been able to complete their review yet. We'll assign one of the chairs to this paper, and make sure you get some feedback over the weekend.

2020-06-21 00:35 UTC, deniederhut reviewed
Thanks for submitting this paper! It's been an interesting read. I'm not finished with the review, but I need to stop and cook dinner and figured I would go ahead and publish my thoughts so far.

2020-06-21 00:35 UTC, deniederhut commented on papers/ralph_kube/kube.rst
> +engineering, and even economics to achieve the goal of developing an unlimited, clean energy source.
Is this referring to funding the research?

2020-06-21 00:35 UTC, deniederhut commented on papers/ralph_kube/kube.rst
> +[Men15]_. With a plethora of scientific disciplines at its foundation, scientific workflows in MFE vary
If the goal of this sentence is to motivate the variability in computational requirements, it might be more effective to name some of these disciplines, or better yet, describe some of the workflows.

2020-06-21 00:35 UTC, deniederhut commented on papers/ralph_kube/kube.rst
> +But before we begin, what is the goal of magnetic fusion energy research? If you could harvest the
Personally, I'm not a fan of rhetorical questions in papers. If the intention is to motivate a discussion of the benefits of fusion power, it might be better to open the paper with a discussion of the current state of the planet's energy requirements, how that energy is provided, and at what cost. E.g.

1. The current state of things
2. What is wrong with that current state of things
3. The solution to those wrong things
4. How your software library helps that solution

2020-06-21 00:35 UTC, deniederhut commented on papers/ralph_kube/kube.rst
> +environmentally friendly energy source. Nuclear fusion reactions are the opposite to nuclear fission
Are they opposites? I understood that these reactions in practice involve two very different kinds of chemicals.

2020-06-21 00:35 UTC, deniederhut commented on papers/ralph_kube/kube.rst
> +magnitude than for a chemical reaction that occurs when burning fossil fuels. Fuel for fusion
I'm guessing you are referring to a redox reaction here?

2020-06-21 00:35 UTC, deniederhut commented on papers/ralph_kube/kube.rst
> +reactions are readily extracted from sea water, which is available in near-infinite quantities. All
I don't think you mean to say 'infinite' here; water on earth is quite finite. Could we try something like 'readily-available'? Or that the amount consumed would be negligible compared to the available quantity?

2020-06-21 00:35 UTC, deniederhut commented on papers/ralph_kube/kube.rst
> +this means that fusion energy is also inherently safe. Since the energy yield of a fusion reaction
I don't understand this point about fusion reactions being 'inherently safe'. Don't we put these in bombs?

2020-06-21 00:35 UTC, deniederhut commented on papers/ralph_kube/kube.rst
> +GW of fusion power, enough to power about 700,000 homes, just 2 kg of fusion plasma would need to be
I don't know that most people can easily visualize 700,000 homes. Could we put this in terms of a city or a country?

2020-06-21 00:35 UTC, deniederhut commented on papers/ralph_kube/kube.rst
> +To fuse positively charged atoms into one heavier one enormous energies are required. For the most
This sentence might be simplified to "Enormous energy is required to fuse two atoms together".

2020-06-21 00:35 UTC, deniederhut commented on papers/ralph_kube/kube.rst
> +feasible fusion reactions, temperatures upwards of 100 million degrees are required. Such a requirement
Does this mean economically feasible?

2020-06-21 00:35 UTC, deniederhut commented on papers/ralph_kube/kube.rst
> +feasible fusion reactions, temperatures upwards of 100 million degrees are required. Such a requirement
Do you mean 100 million degrees Celsius? Or 100 million Kelvin?

2020-06-21 00:35 UTC, deniederhut commented on papers/ralph_kube/kube.rst
> +amount of plasma would leak out of the vessel, the accompanying temperature drop would stop any
Isn't there still a risk of a material heated to 100 million degrees reacting with anything outside of the containment field?

2020-06-21 00:35 UTC, deniederhut commented on papers/ralph_kube/kube.rst
> +pose and danger.
I think you wanted 'any' here.

2020-06-21 00:35 UTC, deniederhut commented on papers/ralph_kube/kube.rst
> +The best performing plasma confinement devices, tokamaks, are donut shaped. Medium-sized tokamaks,
Is there a goal to listing out the medium-sized ones, but not the small or large?

2020-06-21 00:35 UTC, deniederhut commented on papers/ralph_kube/kube.rst
> +[TCV]_ have a major radius R=1-1.5m and a minor radius a=0.2-0.7m. In experiments at these
What do major and minor refer to in this context? Can we assume the radius is measured from the center of the torus?

2020-06-21 00:35 UTC, deniederhut commented on papers/ralph_kube/kube.rst
> +experimental workflow, about 10-30 ``shots`` are performed on a given day where each shot lasts for
Have we defined what a 'shot' is?

2020-06-21 00:35 UTC, deniederhut commented on papers/ralph_kube/kube.rst
> +A common diagnostic in magnetic fusion experiments are so-called Electron Cyclotron Emission Imaging
'A common diagnostic is' or 'Common diagnostics are'

2020-06-21 00:35 UTC, deniederhut commented on papers/ralph_kube/kube.rst
> +allows one to infer their temperature as a function of radius. Modern ECEI systems, such as the one installed
Is the point here to ensure that the measured temperature is the same as the intended temperature? Or that the temperature across space and/or over time? Is this for safety? For reactor efficiency? Both?

2020-06-21 00:35 UTC, deniederhut commented on papers/ralph_kube/kube.rst
> +The best performing plasma confinement devices, tokamaks, are donut shaped. Medium-sized tokamaks,
Could we add the full description for 'tokamak' here? (I gather it's an acronym from the Russian).

2020-06-21 00:35 UTC, deniederhut commented on papers/ralph_kube/kube.rst
> +``Delta`` aims to perform advanced data analysis in near real-time in order to inform decisions in
I feel like we're missing a strong linking statement here. We've seen one experimental workflow, which is measuring temperature. Does delta provide analysis for that specific kind of temperature measurement? For all temperature measurements on tokamak-type reactors? Is the temperature measurement one specific example of the 100 diagnostic tests used on reactors, and Delta is a solution for all of them?

2020-06-21 00:35 UTC, deniederhut commented on papers/ralph_kube/kube.rst
> +control require data on a millisecond time scale. This time scale is a hard constraint and limits
This distinction makes sense to me, but I feel like I am missing the use case motivating their existence. E.g. the real-time systems monitor containment breaches so they can shut down the reaction in real-time, whereas the batch jobs are plugged into an economic model that decides whether we can generate energy with these settings at a competitive price point.

2020-06-21 00:35 UTC, deniederhut commented on papers/ralph_kube/kube.rst
> +hand serves scientific discovery. The data and the analysis methods are selected on a per-case
Aren't all of the analyses serving scientific discovery?

2020-06-21 00:35 UTC, deniederhut commented on papers/ralph_kube/kube.rst
> +measurements as well as scientists opinions were used as input for the ``optometrist`` algorithm
Measurements about what? Opinions about what? (also, 'opinion' might be taken to imply 'uninformed' -- 'judgment' might be more accurate here?)

Have we defined the 'optometrist' algorithm?

2020-06-21 00:35 UTC, deniederhut commented on papers/ralph_kube/kube.rst
> +fusion performance [Bal17]_.  With ``Delta`` we aim to provide a framework that allows to implement
How is the improvement measured? E.g. if we are doing a local search with small steps over a cost landscape, what contributes to that cost?

2020-06-21 22:14 UTC, cyrush commented
Hi everyone, I read the paper and working on my review -- I hope to have it posted to github shortly.

2020-06-21 22:47 UTC, cyrush commented
Authors, thank you for this paper -- I enjoyed learning about your work!

Here is my review:

This paper describes Delta, a Python framework that streams experimental data from diagnostics at the KSTAR Tokamak to NERSC's Cori HPC cluster for near real time analysis. Delta leverages ADIOS to both stream data between KSTAR and NERSC and to help distribute the data for processing on Cori. The analysis is orchestrated with mpi4py using a futures interface to dispatch Cython kernels.   

Authors provide basic background about magnetically confined fusion and details about their workflow for spectral analysis of signals from an ECEI diagnostic.

They then provide an in-depth discussion of the design of their system and explore its performance. As the authors note, the performance of a system with so many pieces can be difficult to understand. To help with this they first measure independent parts of the workflow and use those to guide their expectations for the overall system performance.  

There is a lot to unpack with the graphs from the overall system performance. Authors did a good job presenting this info, but I have a few questions:

- For Figs 7-9, was the load imbalance at the start explained by components of the workflow itself? It seems the distribution of the STFTs is a limiter? If you do have a better understanding of this, it would be great to have a little more context to understand if this was expected or unexplained based on your experience.

- Also, you note: "We believe the long execution time is in part explained by MPI Comm Overhead". I appreciate this is hard to deconvolve the contributions here, but is there any more context you can offer? I assume MPI Comm Overhead includes serialization, etc?


This is a strong paper and should be included in the SciPy 2020 proceedings.
The authors demonstrate the system is viable, describe future directions, and showed they are paying attention to nuances they encountered along the way. 

Overall this paper provides a great exemplar for considerations about streaming analysis between an experimental facility and a HPC analysis resource. This type of workflow is often described optimistically as critically important future direction for HPC -- sharing real experiences and solutions helps the HPC community understand what will be viable.  

I will add a few comments about small typos or places where I found the wording a bit confusing.

Thanks again for distilling this work into this paper!

2020-06-21 22:48 UTC, cyrush commented on papers/ralph_kube/kube.rst
> +measurements as well as scientists opinions were used as input for the ``optometrist`` algorithm
Also wanted to have some context or a ref for the 'optometrist' algorithm

2020-06-21 22:49 UTC, cyrush commented on papers/ralph_kube/kube.rst
> +:math:`s_{ch}` and details on how to calculate data normalization are stored in the ``ECEI``
minor typo: framwork-wide -> framework-wide

2020-06-21 22:50 UTC, cyrush commented on papers/ralph_kube/kube.rst
> +The Electron Cyclotron Emission Imgaging diagnostic installed in KSTAR measures the electron
minor typo: Imgaging -> Imaging

2020-06-21 22:51 UTC, cyrush commented on papers/ralph_kube/kube.rst
> +been analyzed and stored. In order to minimize data communication, ``submit`` launches ``calc_and_store``
These two scenarios contrast each other, using "on the other hand" twice makes this hard to parse.

To clarify, maybe state: We implemented it this way to avoid ...

2020-06-21 22:51 UTC, cyrush commented on papers/ralph_kube/kube.rst
> +to arrive at avarying times for the three scenarios.
t avarying ==> at varying

2020-06-21 22:52 UTC, cyrush commented on papers/ralph_kube/kube.rst
> +choose to use two PoolExecutors. The first executor is used to execute shor Fourier Transformations
minor typo: execute shor Fourier ==> execute short Fourier

2020-06-21 22:53 UTC, cyrush commented on papers/ralph_kube/kube.rst
> +data is immediately stored.  This allows to submit a large number of analysis task in parallel in a
minor wording: This allows to submit a large number ==> allows us to submit large number -- or -- allows submission of a large number

2020-06-21 22:55 UTC, cyrush commented
@rkube @deniederhut I finished adding my comments, happy to participate in followup dialog as necessary -- just pulse through github.

2020-06-22 04:43 UTC, deniederhut requested changes
Hey there! I really like the description of the software library, and care taken in balancing the demands of a usable data processing API and the inherently multi-threaded nature of the task at hand. For me, after reading this paper, I'm still not sure I understand the use case for the near-real-time system presented here. It might help to spend more time with concrete examples of the problem this library addresses specifically, and less time on the status of fusion energy generally.

2020-06-22 04:43 UTC, deniederhut commented on papers/ralph_kube/kube.rst
> +We are designing the ``Delta`` framework in a bottom-up approach, tailoring it to facilitate a
Was this mean to be past tense? Or is this library still being developed?

2020-06-22 04:43 UTC, deniederhut commented on papers/ralph_kube/kube.rst
> +specific deployment platform in mind. While plasma diagnostics operated at fusion experiments
Does it make sense to name the deployment platform here?

2020-06-22 04:43 UTC, deniederhut commented on papers/ralph_kube/kube.rst
> +nodes to compute node and compute node interconnects and their network security policies.
It's not clear to me where the boundaries are between the noun groups here -- does 'compute node interconnects' belong with speed or security policies?

2020-06-22 04:43 UTC, deniederhut commented on papers/ralph_kube/kube.rst
> +Furthermore granted allocations of compute time for research projects make it impractical to start
Ooh yes, this feels like an important constraint.

2020-06-22 04:43 UTC, deniederhut commented on papers/ralph_kube/kube.rst
> +Designed with a specific application in mind, we implement ``Delta`` for streaming data from KSTAR
Do we need 'Designed with a specific application in mind' here?

2020-06-22 04:43 UTC, deniederhut commented on papers/ralph_kube/kube.rst
> +Xeon Phi "Knight's Landing" (KNL) nodes and ranks 13 on the Top500 list. Figure :ref:`fig-topo`
Woot woot! Could we add a link here to the list you are referencing?

2020-06-22 04:43 UTC, deniederhut commented on papers/ralph_kube/kube.rst
> +their respective Data Transfer Node (DTN). DTNs are servers dedicated to performing data transfers
"[Data Transfer Node]s are servers dedicated to performing data transfers" doesn't seem to be adding a lot of additional information.

2020-06-22 04:43 UTC, deniederhut commented on papers/ralph_kube/kube.rst
> +    +---------------+--------------------+----------+--------------------------+
In the rendered pdf, it looks like the table borders are extending into the adjacent text column

2020-06-22 04:43 UTC, deniederhut commented on papers/ralph_kube/kube.rst
> +hits when touching the file system. Data transfers can of course be facilitated using traditional
Is there a tradeoff here between performance and the risk of data loss? Or is that not really a relevant consideration for the near-real-time use case?

2020-06-22 04:43 UTC, deniederhut commented on papers/ralph_kube/kube.rst
> +the change of a single line in a configuration file.
🎉

2020-06-22 04:43 UTC, deniederhut commented on papers/ralph_kube/kube.rst
> +``middleman``, and a ``processor``. Each is implemented as a separate python script which needs to
Do we mean to say 'script' here? Would this be more accurately described as separate workers? Separate programs?

2020-06-22 04:43 UTC, deniederhut commented on papers/ralph_kube/kube.rst
> +running. The middleman forwards the received data to the processor. The processor receives the data,
There's not a lot of info about the middleman portion of the program. Is this doing some sort of name resolution or service discovery?

2020-06-22 04:43 UTC, deniederhut commented on papers/ralph_kube/kube.rst
> +                          for ch_it in self.get_dispatch_sequence()]
It looks like the last line of code here goes beyond the margin of the page -- maybe we could move the 'for' part of this comprehension leftward to align with the opening bracket?

2020-06-22 04:43 UTC, deniederhut commented on papers/ralph_kube/kube.rst
> +details are stored in the ``transport_tx`` section. Moving all diagnostic-dependent transformations
This feels like a misplaced modifier. It might be more clear to say something like: 'Because all of the data transformations are inside the loader class, the generator appears to be agnostic about what kind of diagnostic data it gets. However, the number of data batches is different for each diagnostic, and so must be included in the generator configuration.'

2020-06-22 04:43 UTC, deniederhut commented on papers/ralph_kube/kube.rst
> +       writer.BeginStep()
There's some style inconsistency in the code samples -- I'm looking at the use of camelcase method names in this one here. Is there a reason we're not following pep8?

2020-06-22 04:43 UTC, deniederhut commented on papers/ralph_kube/kube.rst
> +      reader.Open()
Should this be `a2_reader.Open()`?

2020-06-22 04:43 UTC, deniederhut commented on papers/ralph_kube/kube.rst
> +Executing the analysis tasks after the Fourier transformation further reduces inter-dependencies in
I'm not sure that 'interdependencies' requires a hyphen.

2020-06-22 04:43 UTC, deniederhut commented on papers/ralph_kube/kube.rst
> +``Delta`` relies on the ``futures`` interface defined in PEP 3148 to launch data analysis kernels on
Could we add a link to the pep in question?

2020-06-22 04:43 UTC, deniederhut commented on papers/ralph_kube/kube.rst
> +dask-distributed cluster was deployed on multiple nodes we observed a significant slowdown due to
Can we quantify the extent of this performance degradation? Or are those data not available?

2020-06-22 04:43 UTC, deniederhut commented on papers/ralph_kube/kube.rst
> +function of the ``task_ecei`` class. The specific kernel to be called is configured in the constructor:
This is a super pedantic comment for me to make, but `__new__` is the instance constructor, not `__init__`.

2020-06-22 04:43 UTC, deniederhut commented on papers/ralph_kube/kube.rst
> +diagnostic also allows to collectively execute diagnostic-specific pre-transformations that are best
I think we are missing a word between 'allows' and 'to' here.

2020-06-22 04:43 UTC, deniederhut commented on papers/ralph_kube/kube.rst
> +   pca.fit(X)
If I'm understanding your point correctly, the scikit-learn equivalent of `calc_and_store` might be `fit_transform`.

2020-06-22 04:43 UTC, deniederhut commented on papers/ralph_kube/kube.rst
> +workflow at hand, the complex composition of the framework requires to understand the performance of
I think we're missing a word between 'requires' and 'to'

2020-06-22 04:43 UTC, deniederhut commented on papers/ralph_kube/kube.rst
> +may be sensitive to the individual components interact with one another For example, even though the
'how the individual components interact' or maybe ' to the individual components interacting'?

2020-06-22 04:43 UTC, deniederhut commented on papers/ralph_kube/kube.rst
> +threads, a fast data stream ingested by the processor may negatively afftect the performance of the
'affect'?

2020-06-22 04:43 UTC, deniederhut commented on papers/ralph_kube/kube.rst
> +Foreshadowed in the code-example above, ``Delta`` implements data analysis routines as computational
'Foreshadow' is a literary device typically reserved for works of fiction. Did we mean to say something like "As seen in code example [number]"?

2020-06-22 04:43 UTC, deniederhut commented on papers/ralph_kube/kube.rst
> +          for idx in prange(num_idx, schedule=static):
Would you mind adding the imports required for the code example? I'm worried some readers might not know where prange and nogil are coming from.

2020-06-22 04:43 UTC, deniederhut commented on papers/ralph_kube/kube.rst
> +      return(result)
Why are there parens in the return statement here?

2020-06-22 04:43 UTC, deniederhut commented on papers/ralph_kube/kube.rst
> +analysis resources is useful, it may not be practical to do so by default. A possible way to implement
The current pdf renders just over 8 pages -- the first line on the 9th page is around here.

2020-06-26 14:08 UTC, deniederhut commented
Hi @rkube ! How are the paper revisions coming along?

2020-06-26 15:11 UTC, rkube commented on papers/ralph_kube/kube.rst
> +engineering, and even economics to achieve the goal of developing an unlimited, clean energy source.
To develope fusion as a power source it needs to be economically competitive i.e. priced cheaper than alternatives like gas, wind, or solar.

Changes to the paper:
Research on magnetic fusion energy combines physics, engineering, and even economics to deploy a virtually unlimited, clean, and competitively priced energy source to the grid.

2020-06-26 15:28 UTC, rkube commented on papers/ralph_kube/kube.rst
> +[Men15]_. With a plethora of scientific disciplines at its foundation, scientific workflows in MFE vary
This is indeed the intended effect of the sentence. In order to avoid unnecessary distractions we removed

"With a plethora of scientific disciplines at its foundation, scientific workflows in MFE vary
significantly by the amount of data and computational time they require."

and replaced it with
"We introduce ``Delta`` - the aDaptive nEar-reaL Time Analysis framework - and show how it
can be used to stream data from an experiment to a remote high performance computing (HPC) resource.
There, Delta executes a routine spectral analysis workflow in near real-time. By making data analysis
results available in near real-time, Delta allows  scientists to make more informed decisions on follow-up
experiments and could accelerate scientific discovery."

2020-06-26 15:31 UTC, rkube commented on papers/ralph_kube/kube.rst
> +But before we begin, what is the goal of magnetic fusion energy research? If you could harvest the
Delta allows to perform analysis that is typically performed post-shot in a batch-wise manner in near real-time
directly after an experiment has concluded. By introducing the physical principles of fusion we can segue to the
tokamak and discuss its experimental cadence. This is linked to how real-time streaming analysis improves over
post-shot batch analysis. 

Exploring the need from fusion based on mankinds energy requirements is an interesting topic
and has been done in f.ex.

https://arxiv.org/abs/1912.06289
https://www.sciencedirect.com/science/article/pii/S2211467X19301257

But this discussion would be too much for the article.


Changes to the article:
We replaced the hypothetical question with
"To illustrate use-cases for Delta, we start with a primer of fusion energy,
introduce tokamak devices that are used to perform fusion experiments and a diagnostic that is installed in many tokamaks."

2020-06-26 15:33 UTC, rkube commented on papers/ralph_kube/kube.rst
> +environmentally friendly energy source. Nuclear fusion reactions are the opposite to nuclear fission
Both fission and fusion yield energy by converting nuclear binding energy of the reactants to kinetic energy of
the products. In a fusion reaction, light reactants, such as D and T form a heavy product, He. 
In a fission reaction, heavy reactants, f.ex. U235, forms lighter products. In this sense they run opposite to
one another. Fusion reactions can only involve elements lighter than iron and fission reactions can only involve
elements heavier than iron.

Changes to the paper:
Fusion reactions release energy when two light nuclei merge into a heavier one. As part of the
reaction, nuclear binding energy of the reactants is converted into kinetic energy of the products.
Fission reactions on the other hand, which power todays nuclear power plants, release binding energy
when a heavy nucleus decays into lighter products.

2020-06-26 15:35 UTC, rkube commented on papers/ralph_kube/kube.rst
> +magnitude than for a chemical reaction that occurs when burning fossil fuels. Fuel for fusion
We refer to the difference in magnitude of the energy scale of nuclear and any chemical reactions, including redox reactions.
Characteristic energies of the nuclear binding energy are MeV while chemical bonds are typically eV.
Thus nuclear reactions release multiple times the energy of chemical reactions.


Changes to the paper:
Typical energies involved in nuclear reactions are measured in MeV, multiple orders of magnitude larger than the 
characteristic eV energy scale for chemical reactions. Thus, the energy yield for a nuclear reaction is much larger than
for chemical reaction, which occur when fossil fuels are burnt.

2020-06-26 15:41 UTC, rkube commented on papers/ralph_kube/kube.rst
> +reactions are readily extracted from sea water, which is available in near-infinite quantities. All
Changes to the paper:
"Fuel for fusion reactions is readily extracted from sea-water, which is available in virtually inexhaustible quantities"

2020-06-26 15:54 UTC, rkube commented on papers/ralph_kube/kube.rst
> +this means that fusion energy is also inherently safe. Since the energy yield of a fusion reaction
Yes, nuclear bombs often rely on fusion-based primers. But in order to sustain nuclear fusion reactions
one needs to confine the reactants at about 100 million degrees. Both, the requirement for active confinement,
the temperature requirement, and the fact that only a minute amount of fusion fuel is present in any experiment/reactor
eliminate the possibility of uncontrolled chain reactions, which are a big problem for fission.

Changes to the paper:
We removed the sentence as this is not central to the article.

2020-06-26 15:56 UTC, rkube commented on papers/ralph_kube/kube.rst
> +GW of fusion power, enough to power about 700,000 homes, just 2 kg of fusion plasma would need to be
Energy usage statistics quickly become very involved. Average energy consumption in the residential
sector and for family homes is quiet well mapped: https://www.eia.gov/tools/faqs/faq.php?id=96&t=3
Comparing to larger composite units, such as cities or countries, becomes very involved due to factors such as,
composition of the industrial sector in that unit, relative composition in terms of residential/commercial/industrial sector,
different seasonal variability of the sectors, etc.  As such, these comparisons are rarely made. 
The DOE explains a GW through several examples: https://www.energy.gov/eere/articles/how-much-power-1-gigawatt
Common to all of these is that they use units of something that is visualizable, such as a wind turbine, 
a horse, a car. Also, one could make the argument that most people, including myself, have no feel for the
energy usage of an entire city or a country. We feel that using 700,000 homes brings home the message that 1 GW 
is quiet a lot of energy.

2020-06-26 15:56 UTC, rkube commented on papers/ralph_kube/kube.rst
> +To fuse positively charged atoms into one heavier one enormous energies are required. For the most
Change to article:
"To fuse two nuclei into a heavier one requires enormous energies."

2020-06-26 15:58 UTC, rkube commented on papers/ralph_kube/kube.rst
> +feasible fusion reactions, temperatures upwards of 100 million degrees are required. Such a requirement
It means Deuterium-Tritium fusion, as introduced in a previous paragraph. Other fuel cycles,
such as Deuterium-Deuterium of proton-Boron, need to operate at even higher temperatures but have other potential benefits over D-T fusion. Most currently envisioned fusion power plants aim to use a  D-T fuel cycle.

Changes to the paper:
For the most feasible fusion reaction, Deuterium-Tritium, temperatures upwards of 100 million degrees Kelvin are required.

2020-06-26 15:59 UTC, rkube commented on papers/ralph_kube/kube.rst
> +feasible fusion reactions, temperatures upwards of 100 million degrees are required. Such a requirement
At 100 million degrees the distinction between C and K amounts to less than 0.001% :)

We added Kelvin.

2020-06-26 16:00 UTC, rkube commented on papers/ralph_kube/kube.rst
> +amount of plasma would leak out of the vessel, the accompanying temperature drop would stop any
Of course magnetic confinement is not perfect and particles and heat escape continuously. The leaking plasma erodes material surfaces, which in turn releases impurities into the plasma which may alter the properties of plasma transport. Both, plasma-surface interactions in reactor relevant conditions and effects of impurities on plasma transport  are research areas by itself.  But at any time, only a minute amount of plasma, about a gram, is confined by the magnetic field. There is not simply enough thermal energy stored in the plasma to cause damages to structures other than the confinement vessel. 

Changes to the paper:
At the same time there are only a few grams of plasma confined and it does not have enough stored energy to cause
damages other than to the structure of the confinement vessel.

2020-06-26 16:01 UTC, rkube commented on papers/ralph_kube/kube.rst
> +pose and danger.
I don't understand this comment.

2020-06-26 16:01 UTC, rkube commented on papers/ralph_kube/kube.rst
> +The best performing plasma confinement devices, tokamaks, are donut shaped. Medium-sized tokamaks,
For one, smaller tokamaks don't have ECEI diagnostics installed.
Secondly, large tokamaks don't exist yet. ITER will be the first large (reactor-scale) tokamak
and is currently under construction, with the first plasma discharges scheduled for 2025.
Thirdly, the highest impact research is performed on medium-sized tokamaks and those are the
research groups we are mostly in contact with.
Finally, the experimental schedule of running 20-30 shots a day refers to medium-sized tokamaks. 
Experiments at smaller devices or other kinds of devices may follow a different cadence.

Changes to the paper:
To avoid confusion we removed "medium-sized".

2020-06-26 16:04 UTC, rkube commented on papers/ralph_kube/kube.rst
> +[TCV]_ have a major radius R=1-1.5m and a minor radius a=0.2-0.7m. In experiments at these
Major and minor radius are well-defined quantities in a toroidal geometry: https://en.wikipedia.org/wiki/Torus

Changes to the article:
"The best performing plasma confinement devices, tokamaks, have a toroidal shape, similar to a donut."

2020-06-26 16:05 UTC, rkube commented on papers/ralph_kube/kube.rst
> +experimental workflow, about 10-30 ``shots`` are performed on a given day where each shot lasts for
Changes to the paper:
"20-30 plasma discharges, so-called shots, "

2020-06-26 16:05 UTC, rkube commented on papers/ralph_kube/kube.rst
> +A common diagnostic in magnetic fusion experiments are so-called Electron Cyclotron Emission Imaging
Good catch, thanks. We replaced "are" with "is"

Changes to the paper:
A common diagnostic in magnetic fusion experiments is a so-called Electron Cyclotron Emission Imaging

2020-06-26 16:06 UTC, rkube commented on papers/ralph_kube/kube.rst
> +allows one to infer their temperature as a function of radius. Modern ECEI systems, such as the one installed
As a fundamental thermodynamic quantity, physical descriptions of a plasma often use temperatures. Knowing the temperature allows to estimate plasma performance, understand plasma dynamics and allows to compare experiment to theory.

"...as a function of radius. Physical models of the plasma describe it partially through the temperature.
This measurement allows to compare the experiment such models."

2020-06-26 16:07 UTC, rkube commented on papers/ralph_kube/kube.rst
> +The best performing plasma confinement devices, tokamaks, are donut shaped. Medium-sized tokamaks,
Changes to the paper:
...tokamak (a transliteration of the Russian acronym for toroidal chamber with magnetic coils), are donut shaped...

2020-06-26 16:12 UTC, rkube commented on papers/ralph_kube/kube.rst
> +``Delta`` aims to perform advanced data analysis in near real-time in order to inform decisions in
The goal of delta is to perform inter-shot near real-time analysis of large datasets.
Temperature measurements from ECE are one example where we would like to use delta. There are many other diagnostics installed in tokamaks, see for example a panorama of the outer vessel wall of the DIII-D tokamak: https://i.redd.it/c1u49xr3wr201.png

ECE data produces a lot of data, analyzing it in between shots and gain scientific insight is the
challenge. Delta can help here. Delta is certainly not the solution to all of them, but a step in what we think is the right direction.

Changes to the paper:
"...producing data streams upwards of 500 MB/sec.

Analyzing large datasets, as produced by ECE diagnostics in between shots and generating actionable information in time for the next shot is a challenging task. The ``Delta`` framework aims to facilitate the analysis of such large datasets in near real-time."

2020-06-26 16:13 UTC, rkube commented on papers/ralph_kube/kube.rst
> +hand serves scientific discovery. The data and the analysis methods are selected on a per-case
Real-time control systems involve the control of actuators for plasma confinement. Of course those
systems are also continuously worked on they can be seen as more of an engineering problem set.
Here we use the term ``scientific discovery`` more in a plasma physics sense. That is, the goal is
to gain insight in properties of the confined plasma.

2020-06-26 16:15 UTC, rkube commented on papers/ralph_kube/kube.rst
> +measurements as well as scientists opinions were used as input for the ``optometrist`` algorithm
The reference is Bal17, given at the end of the sentence.

Many measurements are performed on fusion experiments, by hundreds or even thousands sensors installed in
10-100 different diagnostics (depending on the size and extent of the facility)
These may be broadly grouped into 
https://www.cambridge.org/core/books/principles-of-plasma diagnostics/93578947341481B0F9169D598D535E76
 magnetic diagnostics, particle flux based diagnostics (Langmuir probes etc),
refractive-index based measurements such as phase-contrast imaging methods, 
diagnostics measuring EM emissions from free electrons such as ECEI,  
diagnostics measuring EM radiation from bound electrons, such as gas-puff imaging, 
diagnostics based on scattering of electromagnetic radiation such as Thomson scattering,
neutral atom diagnostics, such as lithium beam spectroscopy,
and fast ion diagnostics, such as the collective thomson scattering diagnostic developed for ITER.

Expert judgements of a plasma shot typically include measurements on energy confinement times, plasma stability, and potential damage to the vacuum vessel, see the discussion on page 3 in Bal17.

For the C-2U machine, on which the optometrist workflow was performed, over 1000 parameters can be configured. Improvement is judged by scientists, based on multiple measurements of the last plasma shot. There is  no fixed evaluation metric. The article does not specify exactly what contributes to the metric. But commonly confinement times and main ion species temperature are relevant for high fusion performance.

The intention of this sentence is to refer to a workflow that depends on a large number of data analysis being performed in-between shots so that scientists can make better decisions on how to  tune parameters for the next discharge. 


Changes to the paper:
As an example of the workflows that we wish to facilitate with ``Delta`` we refer to a series of
experiments performed at the TAE facility [Bal17]_. There, the so-called ``optometrist`` algorithm was
used as a stochastic optimizer in conjunction with expert judgement of domain scientists to assess
the performance of a just concluded plasma shot and optimize the machine parameters as to increase
the performance in the following shot. By making advanced data analysis results available in near
real-time to domain scientists, ``Delta`` will allow to improve such workflows at experimental fusion 
facilities.

2020-06-26 16:16 UTC, rkube commented on papers/ralph_kube/kube.rst
> +fusion performance [Bal17]_.  With ``Delta`` we aim to provide a framework that allows to implement
Please see the reply above.

2020-06-26 16:16 UTC, rkube commented on papers/ralph_kube/kube.rst
> +:math:`s_{ch}` and details on how to calculate data normalization are stored in the ``ECEI``
Thanks 👍

2020-06-26 16:18 UTC, rkube commented on papers/ralph_kube/kube.rst
> +been analyzed and stored. In order to minimize data communication, ``submit`` launches ``calc_and_store``
removed the second instance of "on the other hand"

2020-06-26 16:19 UTC, rkube commented on papers/ralph_kube/kube.rst
> +choose to use two PoolExecutors. The first executor is used to execute shor Fourier Transformations
Fixed

2020-06-26 16:19 UTC, rkube commented on papers/ralph_kube/kube.rst
> +data is immediately stored.  This allows to submit a large number of analysis task in parallel in a
fixed

2020-06-26 16:21 UTC, rkube commented on papers/ralph_kube/kube.rst
> +We are designing the ``Delta`` framework in a bottom-up approach, tailoring it to facilitate a
We are still working on it. Current work involves making delta adaptive, by selecting what to send for in-depth analysis and adding compression. We are also working on supporting data from other diagnostics to allow multi-diagnostic workflows.

2020-06-26 16:23 UTC, rkube commented on papers/ralph_kube/kube.rst
> +specific deployment platform in mind. While plasma diagnostics operated at fusion experiments
We removed the phrase from the sentence.

2020-06-26 16:24 UTC, rkube commented on papers/ralph_kube/kube.rst
> +nodes to compute node and compute node interconnects and their network security policies.
Interconnect is the technical term for the technology that connects the compute nodes:
https://docs.nersc.gov/systems/cori/#interconnect
https://docs.nersc.gov/systems/cori/interconnect/

2020-06-26 16:25 UTC, rkube commented on papers/ralph_kube/kube.rst
> +Designed with a specific application in mind, we implement ``Delta`` for streaming data from KSTAR
Removed the phrase.

2020-06-26 16:27 UTC, rkube commented on papers/ralph_kube/kube.rst
> +Xeon Phi "Knight's Landing" (KNL) nodes and ranks 13 on the Top500 list. Figure :ref:`fig-topo`
Done. A new top500 list is out, Cori is ranks 16 now.

2020-06-26 16:31 UTC, rkube commented on papers/ralph_kube/kube.rst
> +their respective Data Transfer Node (DTN). DTNs are servers dedicated to performing data transfers
We added the definition from esnet to the article:

DTNs are servers deployed and configured specifically for transferring data over networks.

http://es.net/science-engagement/technical-and-consulting-services/data-transfer-nodes/

2020-06-26 16:34 UTC, rkube commented on papers/ralph_kube/kube.rst
> +    +---------------+--------------------+----------+--------------------------+
I checked the pdf, it looks fine:

<img width="517" alt="Screen Shot 2020-06-26 at 12 33 47 PM" src="https://user-images.githubusercontent.com/5389898/85880042-5b756e00-b7a9-11ea-995b-592d49ac4de9.png">

2020-06-26 16:43 UTC, rkube commented on papers/ralph_kube/kube.rst
> +hits when touching the file system. Data transfers can of course be facilitated using traditional
It's actually a big consideration. As described in [Xie12], I/O performance on HPC systems can vary quiet a lot. This motivates the use of an adaptable I/O middleware. The same is true for data streaming, but can be even worse since streaming is done over a network connection and not spatially located as disk I/O. In a sense, what we want from the middleware is to be in between UDP (fast, no ACKs, packet loss) and TCP(slow, ACKs no packet loss).

2020-06-26 16:44 UTC, rkube commented on papers/ralph_kube/kube.rst
> +``middleman``, and a ``processor``. Each is implemented as a separate python script which needs to
Changed to program.

2020-06-26 16:46 UTC, rkube commented on papers/ralph_kube/kube.rst
> +running. The middleman forwards the received data to the processor. The processor receives the data,
The implementation of the middleman is just the receive logic of the processor and  the send logic of the generator. ADIOS needs the IP address and a port when streaming, so there is no resolution or service discovery necessary.

2020-06-26 16:47 UTC, rkube commented on papers/ralph_kube/kube.rst
> +                          for ch_it in self.get_dispatch_sequence()]
done

2020-06-26 16:49 UTC, rkube commented on papers/ralph_kube/kube.rst
> +details are stored in the ``transport_tx`` section. Moving all diagnostic-dependent transformations
Thanks, I adopted your suggestion.

2020-06-26 17:01 UTC, rkube commented on papers/ralph_kube/kube.rst
> +       writer.BeginStep()
BeginStep() is a wrapper around the corresponding ADIOS2 routine.
ADIOS2 uses CamelCase.

2020-06-26 17:01 UTC, rkube commented on papers/ralph_kube/kube.rst
> +      reader.Open()
Good catch, thanks.

2020-06-26 17:02 UTC, rkube commented on papers/ralph_kube/kube.rst
> +Executing the analysis tasks after the Fourier transformation further reduces inter-dependencies in
I removed the hyphen.

2020-06-26 17:03 UTC, rkube commented on papers/ralph_kube/kube.rst
> +``Delta`` relies on the ``futures`` interface defined in PEP 3148 to launch data analysis kernels on
I added the reference.

2020-06-26 17:04 UTC, rkube commented on papers/ralph_kube/kube.rst
> +dask-distributed cluster was deployed on multiple nodes we observed a significant slowdown due to
Unfortunately that data is not available. I tried dask with earlier versions and the performance logs are not comparable with the current ones.

2020-06-26 17:06 UTC, rkube commented on papers/ralph_kube/kube.rst
> +function of the ``task_ecei`` class. The specific kernel to be called is configured in the constructor:
I did not know that. Changed "constructor" to "objects initialization"

2020-06-26 17:07 UTC, rkube commented on papers/ralph_kube/kube.rst
> +diagnostic also allows to collectively execute diagnostic-specific pre-transformations that are best
I fixed the sentence.

2020-06-26 17:08 UTC, rkube commented on papers/ralph_kube/kube.rst
> +   pca.fit(X)
Right, let's use fit_transform.

2020-06-26 17:08 UTC, rkube commented on papers/ralph_kube/kube.rst
> +workflow at hand, the complex composition of the framework requires to understand the performance of
Inserted "us"

2020-06-26 17:09 UTC, rkube commented on papers/ralph_kube/kube.rst
> +may be sensitive to the individual components interact with one another For example, even though the
Changed  to "interacting"

2020-06-26 17:10 UTC, rkube commented on papers/ralph_kube/kube.rst
> +threads, a fast data stream ingested by the processor may negatively afftect the performance of the
affect

2020-06-26 17:10 UTC, rkube commented on papers/ralph_kube/kube.rst
> +Foreshadowed in the code-example above, ``Delta`` implements data analysis routines as computational
It reads "As seen in the code example above" now

2020-06-26 17:32 UTC, rkube commented on papers/ralph_kube/kube.rst
> +          for idx in prange(num_idx, schedule=static):
I added the imports

2020-06-26 17:32 UTC, rkube commented on papers/ralph_kube/kube.rst
> +      return(result)
I removed the parentheses

2020-06-28 18:32 UTC, deniederhut commented on .gitignore
> +.giignore
To make the commit history easier for us to manage, we ask that authors not modify any files outside of their paper's directory.

2020-06-28 20:01 UTC, deniederhut commented on papers/ralph_kube/kube.rst
> +[Men15]_. We introduce ``Delta`` - the aDaptive nEar-reaL Time Analysis framework - and show how it
The reference to plasmapy and OMFIT feels a bit disconnected here. Could we say explicitly that Delta is a Python package to make the parallel more obvious? Maybe something like "We introduce another Python library for fusion energy research, Delta..."

2020-06-28 20:01 UTC, deniederhut commented on papers/ralph_kube/kube.rst
> +To illustrate use-cases for Delta, we start with a primer of fusion energy, introduce tokamak
The last clause here is missing a parallel verb. I.e. we have 

```
start with ... energy,
VP

introduce tokamak... experiments,
VP

a diagnostic... tokamaks
NP
```

Maybe something like "... fusion experiments, and describe a diagnostic..."

2020-06-28 20:01 UTC, deniederhut commented on papers/ralph_kube/kube.rst
> +two light nuclei merge into a heavier one. As part of the reaction, nuclear binding energy of the
"the nuclear binding energy"

2020-06-28 20:01 UTC, deniederhut commented on papers/ralph_kube/kube.rst
> +reactants is converted into kinetic energy of the products. Fission reactions on the other hand,
"the kinetic energy"

2020-06-28 20:01 UTC, deniederhut commented on papers/ralph_kube/kube.rst
> +cause no more than local damage to the plasma vessel.
GitHub isn't letting me add to the comment chain here https://github.com/scipy-conference/scipy_proceedings/pull/560#discussion_r446268596, but this comment specifically:

> the fact that only a minute amount of fusion fuel is present in any experiment/reactor
eliminate the possibility of uncontrolled chain reactions, which are a big problem for fission.

really helped me understand the intended contrast. It wasn't clear to me from the paper itself that the comparison was to fission reactors, and specifically with the amount of fuel required to be co-located inside a fission reactor chamber.

2020-06-28 20:01 UTC, deniederhut commented on papers/ralph_kube/kube.rst
> +fusion power, enough to power about 700,000 homes, just 2 kg of fusion plasma would need to be
Following up from https://github.com/scipy-conference/scipy_proceedings/pull/560#discussion_r446269495.

It's interesting to hear that estimating the energy requirements of a city is an unsolved problem, but I'm still not sure that people are used to thinking in terms of hundreds of thousands of houses. I can, however, visualize a city the size of Austin, or a city the size of Houston. Is there a comparison like that we could make?

2020-06-28 20:01 UTC, deniederhut commented on papers/ralph_kube/kube.rst
> +To fuse positively charged atoms into one heavier requires enormous energy. For the most feasible
Re: https://github.com/scipy-conference/scipy_proceedings/pull/560#discussion_r446272351

the original line was "pose and danger." and probably should have been "pose any danger"

2020-06-28 20:01 UTC, deniederhut commented on papers/ralph_kube/kube.rst
> +it does not have enough stored energy to cause damages other than to the structure of the
"damage"

2020-06-28 20:01 UTC, deniederhut commented on papers/ralph_kube/kube.rst
> +partially through the temperature. This measurement allows to compare the experiment such models.
"allows one to compare" or "allows comparison of"

"experimental results to such models" or "experimental results against such models"

2020-06-28 20:01 UTC, deniederhut commented on papers/ralph_kube/kube.rst
> +the performance in the following shot. By making advanced data analysis results available in near
Am I correct in my understanding that this is the central thesis of the paper? If so, then in the general framework of:

1. The current state of the field
2. A significant problem in the field
3. What a solution would need to look like
4. How delta provides that solution

This paper might look like:

1. ?
2. ?
3. a solution would need to incorporate large amounts of data, and produce a solution or recommendation within minutes
4. Delta provides that solution by parallelizing the analysis of large amounts of streaming data across an HPC center

Missing a strong problem statement is going to make it more difficult to motivate the existence of this library to a general reader. What were people doing before Delta? Did they ignore this temperature data when designing experiments? Or did they have to wait 24 hours for the batch processing jobs to finish? What is the high-level cost of either scenario? E.g is the current state of the world that lots of experiments are not tuned properly and do not produce useful data? Or is the current state of the world that long iteration time between experiments is a significant barrier to developing stable viable fusion energy solutions?

2020-06-28 20:01 UTC, deniederhut commented on papers/ralph_kube/kube.rst
> +We are designing the ``Delta`` framework in a bottom-up approach, tailoring it to facilitate a
👍

2020-06-28 20:01 UTC, deniederhut commented on papers/ralph_kube/kube.rst
> +hand serves scientific discovery. The data and the analysis methods are selected on a per-case
That make sense. Could we say that explicitly? E.g. instead of "scientific discover", use "validate models for confined plasma" or "understand high energy plasmas"?

2020-06-28 20:05 UTC, deniederhut commented on papers/ralph_kube/kube.rst
> +measurements as well as scientists opinions were used as input for the ``optometrist`` algorithm
> The reference is Bal17, given at the end of the sentence.

Sure. The audience for these papers is more general than physicists however, so it is helpful to define industry-standard terms or algorithms where possible.

2020-06-28 20:09 UTC, deniederhut commented on papers/ralph_kube/kube.rst
> +nodes to compute node and compute node interconnects and their network security policies.
Hm. So I gloss this sentence as saying there are three differences listed in HPC environments:

1. the speed of network links between data-transfer nodes to compute node
2. compute node interconnects
3. network security policies

But I'm not sure that's correct. Some punctuation (like commas, for example) will help readers like me parse the grammar of this sentence more easily.

2020-06-28 20:30 UTC, deniederhut requested changes
Thanks for all of your edits! I've caught a few minor grammar and punctuation things, and have only one substantial question about the argument outlined here. Let me know if any of this doesn't make sense -- I'm happy to hop on a call to discuss.

2020-06-28 20:30 UTC, deniederhut commented on papers/ralph_kube/kube.rst
> +       writer.BeginStep()
👍

2020-06-28 20:30 UTC, deniederhut commented on papers/ralph_kube/kube.rst
> +dask-distributed cluster was deployed on multiple nodes we observed a significant slowdown due to
👍

2020-06-28 20:30 UTC, deniederhut commented on papers/ralph_kube/kube.rst
> +    +---------------+--------------------+----------+--------------------------+
I think you and I are looking at different tables. I mean this one:

<img width="430" alt="Screenshot 2020-06-28 15 15 41" src="https://user-images.githubusercontent.com/6868396/85957368-73d4bc80-b952-11ea-96bb-95ca672990e8.png">

2020-06-28 20:30 UTC, deniederhut commented on papers/ralph_kube/kube.rst
> +          for idx in prange(num_idx, schedule=static):
I'm still not seeing where nogil is imported.

2020-06-28 20:30 UTC, deniederhut commented on papers/ralph_kube/kube.rst
> +may be sensitive to the individual components interacting with one another For example, even though the
I think we're missing a period between 'one another' and 'For example'

2020-06-30 13:41 UTC, deniederhut commented
Hi everyone! Friendly reminder that the open review period ends 2 July -- the committee will be making final decisions on each paper this Friday.

2020-07-01 13:02 UTC, rkube commented on papers/ralph_kube/kube.rst
> +control require data on a millisecond time scale. This time scale is a hard constraint and limits
The batch jobs are usually scientific discovery, i.e. physics. Economic models of depend of course on data from experiments, but they usually consume much "higher-level" data than provided by the diagnostics.

2020-07-01 13:08 UTC, rkube commented on papers/ralph_kube/kube.rst
> +[Men15]_. We introduce ``Delta`` - the aDaptive nEar-reaL Time Analysis framework - and show how it
Ok.

2020-07-01 13:09 UTC, rkube commented on papers/ralph_kube/kube.rst
> +To illustrate use-cases for Delta, we start with a primer of fusion energy, introduce tokamak
Added "describe" in front of diagnostic

2020-07-01 13:09 UTC, rkube commented on papers/ralph_kube/kube.rst
> +two light nuclei merge into a heavier one. As part of the reaction, nuclear binding energy of the
Added "the"

2020-07-01 13:10 UTC, rkube commented on papers/ralph_kube/kube.rst
> +two light nuclei merge into a heavier one. As part of the reaction, nuclear binding energy of the
The product still has binding energy, only a fraction is converted.

2020-07-01 13:10 UTC, rkube commented on papers/ralph_kube/kube.rst
> +reactants is converted into kinetic energy of the products. Fission reactions on the other hand,
see above.

2020-07-01 13:12 UTC, rkube commented on papers/ralph_kube/kube.rst
> +fusion power, enough to power about 700,000 homes, just 2 kg of fusion plasma would need to be
I've googled it and there is little information. I also feel not comfortable developing my own model to make this comparison. Unless you can provide me with a concrete example you suggest to add I prefer to go along with explanations that I can reference to.

2020-07-01 13:12 UTC, rkube commented on papers/ralph_kube/kube.rst
> +it does not have enough stored energy to cause damages other than to the structure of the
ok

2020-07-01 13:13 UTC, rkube commented on papers/ralph_kube/kube.rst
> +partially through the temperature. This measurement allows to compare the experiment such models.
ok

2020-07-01 13:17 UTC, rkube commented on papers/ralph_kube/kube.rst
> +the performance in the following shot. By making advanced data analysis results available in near
Before Delta, people typically obtain data manually and perform data analysis mostly selective. This is done in time-frames longer than the typical experimental cadence. Delta aims to automate large data analysis tasks and allows to offload it to HPC. We show that we can perform such a task faster than the typical shot cadence.

We explain this in the paragraph before table 1:

Analyzing large datasets, as produced by ECE diagnostics in between shots and generating actionable
information in time for the next shot is a challenging task. The ``Delta`` framework aims to
facilitate the analysis of such large datasets in near real-time." This use-case falls in between
two other common data analysis workflows in fusion energy research, listed in Tab. :ref:`timescale`.
Real-time control systems for plasma control require data on a millisecond time scale. This time
scale is a hard constraint and limits the amount of data the algorithms can ingest. Post-shot batch
analysis of measurements on the other hand serves scientific discovery. The data and the analysis
methods are selected on a per-case basis. By providing timely analysis results of plasma
measurements to the experimentalists, they can make more informed decisions about the next plasma
shot. As an example of the workflows that we wish to facilitate with ``Delta`` we refer to a series of
experiments performed at the TAE facility [Bal17]_. There, the so-called ``optometrist`` algorithm was
used as a stochastic optimizer in conjunction with expert judgement of domain scientists to assess
the performance of a just concluded plasma shot and optimize the machine parameters as to increase
the performance in the following shot. By making advanced data analysis results available in near
real-time to domain scientists, ``Delta`` will allow to improve such workflows at experimental fusion 
facilities.

2020-07-01 13:25 UTC, rkube commented on papers/ralph_kube/kube.rst
> +may be sensitive to the individual components interacting with one another For example, even though the
Added the period.

2020-07-02 12:00 UTC, rkube commented
Hi, I'm confused. Did I answer all comments? For some comments I couldn't find a text field to write a reply on.

2020-07-02 12:10 UTC, deniederhut commented on .gitignore
> +.gitignore
Please don't modify files outside of your paper's directory

2020-07-02 12:10 UTC, deniederhut commented on papers/ralph_kube/kube.rst
> +the performance in the following shot. By making advanced data analysis results available in near
Yeah, so the problem statement that you copied here is very general: "analyze large dataset quickly'. Delta is not a solution for every large data problem -- it has a very specific use case, which I would like to see described in the paper in concrete terms. The paragraph that you copied into the comments here does not address the questions I listed earlier, like "what did people do before delta".

2020-07-02 12:10 UTC, deniederhut commented on papers/ralph_kube/kube.rst
> +analysis of measurements on the other hand serves scientific discovery. The data and the analysis
I'd prefer a description more specific than 'scientific discovery'. Presumably these experiments are not answering questions about plate tectonics or protein binding affinities.

2020-07-02 12:10 UTC, deniederhut commented on papers/ralph_kube/kube.rst
> +reactants is converted into kinetic energy of the products. Fission reactions on the other hand,
My point was that the noun required an article to be grammatically correct. Currently the sentence reads:

> As part of the reaction, a fraction of the reactants nuclear binding energy reactants is converted into kinetic energy of the products.

- 'reactants' requires an apostrophe to be possessive
- one too many 'reactants'
- should this be 'kinetic energy in the products'?

2020-07-02 12:32 UTC, deniederhut commented on papers/ralph_kube/kube.rst
> +fusion power, enough to power about 700,000 homes, just 2 kg of fusion plasma would need to be
Okay yeah this harder than I thought it would be. City reports tend to list dwelling units or households, neither of which is a home.

2020-07-02 12:35 UTC, deniederhut requested changes
This is looking a lot better! I still think there are some improvements to be made with some more explicit and concrete language.

2020-07-02 13:09 UTC, rkube commented
1. Yeah, so the problem statement that you copied here is very general: "analyze large dataset quickly'. Delta is not a solution for every large data problem -- it has a very specific use case, which I would like to see described in the paper in concrete terms. The paragraph that you copied into the comments here does not address the questions I listed earlier, like "what did people do before delta".

---------------------------------------------------------------------------------------------------


In the abstract we write:
"We present ``Delta``, a Python framework that connects magnetic fusion experiments to
high-performance computing (HPC) facilities in order leverage advanced data analysis for near
real-time decisions....
With this approach we perform a common spectral analysis suite on imaging measurements more than 100
times faster than with a single-core implementation."

I think this clearly sets the boundaries on what we do with Delta - Doing a specific analysis on data from a specific diagnostic, installed in a magnetic fusion experiment. 


Throughout the article we strive to explain this in certain terms:

* The introduction is designed to motivate the use-case for Delta. See line 71ff:
"To illustrate use-cases for Delta, we start with a primer of fusion energy, introduce tokamak
devices that are used to perform fusion experiments and describe a diagnostic that is installed in
many tokamaks. "

* We also state explicitly that it is desired to make informed decisions on a time-scale faster than the experimental cadence: 
"By providing timely analysis results of plasma measurements to the experimentalists, they can make more informed decisions about the next plasma shot."
The workflow that features the optometrist algorithm is listed as a use-case why this is important in the next sentence, see also Bal17.

The whole "meat" of the article revolves around how we stream the data and perform the ECEi analysis in a fast way. The "Performance analysis" section discusses these aspects in detail.

We also conclude with 
"We demonstrate that ``Delta`` can facilitate near real-time analysis of high-velocity streaming
data. In our experiments we achieved streaming rates of about 350 MByte/sec and execute a spectral
analysis workflow on ECEI measurements in less than 4 minutes."
This is exactly what we want asked for in the paragraph I copied: 
"The ``Delta`` framework aims to facilitate the analysis of such large datasets in near real-time."
We show that Delta performs the analysis faster than the shot cadence.


In no way do we sell Delta as a do every large data problem. We only mention generalizing Delta in the conclusions:
line. 823: "Thirdly, the framework will be generalized in order to facilitate more data analysis tasks."



To address your concern about batch analysis, I changed the text in line 125ff to
"The data and the analysis
methods are selected on a per-case basis and are often performed manually hours, days, weeks, months,
or years after an experiment has concluded. A goal of Delta is to facilitate scientific discovery at
time-scale faster than the experimental cadence. Providing timely analysis results of plasma
measurements to experimentalists aids them in making informed decisions about the next plasma
shot."

The article now explicitly states that the experimental cadence is a few minutes:
Line 108:  "After a cool-down phase of 
a few minutes (tokamaks contain cryogenic components) the device is ready for the next shot. "



2. I'd prefer a description more specific than 'scientific discovery'. Presumably these experiments are not answering questions about plate tectonics or protein binding affinities.


----------------
Our introduction reads: "Research on magnetic fusion energy combines physics, engineering, and even economics to deploy a
virtually unlimited, clean, and competitively priced energy source to the grid."

As such, experimental analysis touches plasma physics, particle physics (fast ion populations with E_kin~O(10keV), some diagnostics), chemistry (plasma-surface interactions), radiation physics (fast neutron population resulting in material activation), optics (diagnostics, wave-guides), quantum physics (motional stark effect for diagnostics), engineering (EE for diagnostics, ME for device structure, cryogenic components, economics (developing fusion as a competitive power source). 
Here I probably forgot many fields.

I simply am not aware of a better term than scientific discovery as an umbrella term. 

I also disagree that a reader would get the impression that experiments on fusion research would answer questions about plate tectonics or protein binding affinities after reading our article.

2020-07-02 13:40 UTC, rkube commented on .gitignore
> +.gitignore
I still don't understand what I'm supposed to do here.

2020-07-02 15:44 UTC, rkube commented on papers/ralph_kube/kube.rst
> +analysis of measurements on the other hand serves scientific discovery. The data and the analysis
This article is about data analysis in fusion experiments and we use the term "scientific discovery" in this context. 

Our introduction reads: "Research on magnetic fusion energy combines physics, engineering, and even economics to deploy a
virtually unlimited, clean, and competitively priced energy source to the grid."

As such, experimental analysis touches plasma physics, particle physics (fast ion populations with E_kin~O(10keV), some diagnostics), chemistry (plasma-surface interactions), radiation physics (fast neutron population resulting in material activation), optics (diagnostics, wave-guides), quantum physics (motional stark effect for diagnostics), engineering (EE for diagnostics, ME for device structure, cryogenic components, economics (developing fusion as a competitive power source).
Here I probably forgot many fields.

I simply am not aware of a better term than scientific discovery as an umbrella term.
Can you please make a suggestion for a better term?

2020-07-02 15:48 UTC, rkube commented on papers/ralph_kube/kube.rst
> +nodes to compute node and compute node interconnects and their network security policies.
You are correct. I changed the punctuation in the sentence.

2020-07-02 15:49 UTC, rkube commented on papers/ralph_kube/kube.rst
> +reactants is converted into kinetic energy of the products. Fission reactions on the other hand,
removed a recatants

2020-07-02 21:00 UTC, cbcunc requested changes
Minor updates to citations requested as part of final proceedings committee walk-through.

2020-07-02 21:00 UTC, cbcunc commented on papers/ralph_kube/kube.rst
> +  def kernel_coherence_64_cy(cnp.ndarray[cnp.complex128_t,
Code sample need to remain within column boundaries.

2020-07-02 21:00 UTC, cbcunc commented on papers/ralph_kube/kube.rst
> +.. [Zen] https://doi.org/10.5281/zenodo.3871700
Include full citation with DOI.

2020-07-02 21:00 UTC, cbcunc commented on papers/ralph_kube/kube.rst
> +.. [Git] https://github.com/rkube/delta
Include full citation.

2020-07-02 21:00 UTC, cbcunc commented on papers/ralph_kube/kube.rst
> +.. [dask] https://dask.org
Include a full citation to the Dask paper: https://conference.scipy.org/proceedings/scipy2015/pdfs/matthew_rocklin.pdf

2020-07-02 21:00 UTC, cbcunc commented on papers/ralph_kube/kube.rst
> +.. [mpi4py] https://mpi4py.readthedocs.io/en/stable/
Provide a full citation to eh Mpi4Py paper: LisandroDalc ́ın,RodrigoPaz,andMarioStorti.MPIforpython.JournalofParallelandDis-tributedComputing,65(9):1108–1115,200

2020-07-02 21:00 UTC, cbcunc commented on papers/ralph_kube/kube.rst
> +.. [PEP3148] https://www.python.org/dev/peps/pep-3148/
Please provide a full citation for the PEP.

2020-07-02 21:00 UTC, cbcunc commented on papers/ralph_kube/kube.rst
> +.. [Liu14] Q. Liu, J. Logan, Y. Tian et al. *Hello ADIOS: the challenges and lessons of developing leadership class I/O frameworks*
Please provide the DOI: doi:10.1002/cpe.3125

2020-07-02 21:00 UTC, cbcunc commented on papers/ralph_kube/kube.rst
> +.. [adios] https://adios2.readthedocs.io/en/latest/index.html
Please provide a full citation.

2020-07-02 21:00 UTC, cbcunc commented on papers/ralph_kube/kube.rst
> +.. [iperf] https://iperf.fr
Please provide a full citation.

2020-07-02 21:00 UTC, cbcunc commented on papers/ralph_kube/kube.rst
> +.. [nerscdtn] https://docs.nersc.gov/systems/dtn/
Please provide a full citation.

2020-07-02 21:00 UTC, cbcunc commented on papers/ralph_kube/kube.rst
> +.. [dtn] http://es.net/science-engagement/technical-and-consulting-services/data-transfer-nodes/
Please provide a full citation.

2020-07-02 21:00 UTC, cbcunc commented on papers/ralph_kube/kube.rst
> +.. [top500] https://www.top500.org/lists/top500/list/2020/06/?page=1
Please provide a full citation.

2020-07-02 21:00 UTC, cbcunc commented on papers/ralph_kube/kube.rst
> +.. [cori] https://docs.nersc.gov/systems/cori/
Please provide a full citation.

2020-07-02 21:00 UTC, cbcunc commented on papers/ralph_kube/kube.rst
> +.. [TCV] https://www.epfl.ch/research/domains/swiss-plasma-center/research/tcv/research_tcv_tokamak/
Please provide a full citation.

2020-07-02 21:00 UTC, cbcunc commented on papers/ralph_kube/kube.rst
> +.. [MAST] Mega Amp Spherical Tokamak https://ccfe.ukaea.uk/research/mast-upgrade/
Please provide a full citation.

2020-07-02 21:00 UTC, cbcunc commented on papers/ralph_kube/kube.rst
> +.. [AUG] ASDEX Upgrade https://www.ipp.mpg.de/16195/asdex
Please provide a full citation.

2020-07-02 21:00 UTC, cbcunc commented on papers/ralph_kube/kube.rst
> +.. [KSTAR] KSTAR Tokamak https://www.nfri.re.kr/kor/index
Please provide a full citation.

2020-07-02 21:00 UTC, cbcunc commented on papers/ralph_kube/kube.rst
> +.. [NSTX] NSTX https://www.pppl.gov/nstx
Please provide a full citation.

2020-07-02 21:00 UTC, cbcunc commented on papers/ralph_kube/kube.rst
> +.. [D3D] DIII-D http://www.ga.com/diii-d
Please provide a full citation.

2020-07-02 21:00 UTC, cbcunc commented on papers/ralph_kube/kube.rst
> +.. [PPY] https://www.plasmapy.org
Please provide a full citation.

2020-07-02 21:06 UTC, cbcunc requested changes
Do not include a .gitignore in the PR.

2020-07-02 21:12 UTC, rkube commented on papers/ralph_kube/kube.rst
> +.. [Zen] https://doi.org/10.5281/zenodo.3871700
http://hdl.handle.net/11858/00-001M-0000-0013-557A-5

There is no DOI.

2020-07-02 21:12 UTC, rkube commented on papers/ralph_kube/kube.rst
> +.. [Git] https://github.com/rkube/delta
http://hdl.handle.net/11858/00-001M-0000-0013-557A-5

There is no DOI.

2020-07-02 21:15 UTC, rkube commented on papers/ralph_kube/kube.rst
> +.. [dask] https://dask.org
I added the link,

2020-07-02 21:17 UTC, rkube commented on papers/ralph_kube/kube.rst
> +.. [mpi4py] https://mpi4py.readthedocs.io/en/stable/
Thanks for the paper, I added it to the reference.

2020-07-02 21:19 UTC, rkube commented on papers/ralph_kube/kube.rst
> +.. [PEP3148] https://www.python.org/dev/peps/pep-3148/
How does the full citation for a PEP look like?

2020-07-02 21:20 UTC, rkube commented on papers/ralph_kube/kube.rst
> +.. [Liu14] Q. Liu, J. Logan, Y. Tian et al. *Hello ADIOS: the challenges and lessons of developing leadership class I/O frameworks*
Ok.

2020-07-02 21:21 UTC, rkube commented on papers/ralph_kube/kube.rst
> +.. [adios] https://adios2.readthedocs.io/en/latest/index.html
What information is missing?

2020-07-02 21:21 UTC, rkube commented on papers/ralph_kube/kube.rst
> +.. [iperf] https://iperf.fr
What information is missing?

2020-07-02 21:21 UTC, rkube commented on papers/ralph_kube/kube.rst
> +.. [nerscdtn] https://docs.nersc.gov/systems/dtn/
What information is missing?

2020-07-02 21:22 UTC, rkube commented on papers/ralph_kube/kube.rst
> +.. [dtn] http://es.net/science-engagement/technical-and-consulting-services/data-transfer-nodes/
what information is missing?

2020-07-02 21:24 UTC, rkube commented on papers/ralph_kube/kube.rst
> +.. [top500] https://www.top500.org/lists/top500/list/2020/06/?page=1
I added a DOI to a encyclopedia entry that defines the top500 list. Is this sufficient?

2020-07-02 21:25 UTC, rkube commented on papers/ralph_kube/kube.rst
> +.. [cori] https://docs.nersc.gov/systems/cori/
What information is missing?

2020-07-02 21:27 UTC, cbcunc requested changes
Please do not include a .gitignore in the PR. We cannot assemble the proceedings if files exist outside of the papers/ namespace.

2020-07-02 21:30 UTC, cbcunc commented on papers/ralph_kube/kube.rst
> +.. [PEP3148] https://www.python.org/dev/peps/pep-3148/
https://tex.stackexchange.com/questions/532049/how-to-cite-python-pep

2020-07-02 21:32 UTC, cbcunc commented on papers/ralph_kube/kube.rst
> +.. [adios] https://adios2.readthedocs.io/en/latest/index.html
https://www.mendeley.com/guides/web-citation-guide

2020-07-02 21:32 UTC, cbcunc commented on papers/ralph_kube/kube.rst
> +.. [iperf] https://iperf.fr
https://www.mendeley.com/guides/web-citation-guide

2020-07-02 21:32 UTC, cbcunc commented on papers/ralph_kube/kube.rst
> +.. [nerscdtn] https://docs.nersc.gov/systems/dtn/
https://www.mendeley.com/guides/web-citation-guide

2020-07-02 21:32 UTC, cbcunc commented on papers/ralph_kube/kube.rst
> +.. [dtn] http://es.net/science-engagement/technical-and-consulting-services/data-transfer-nodes/
https://www.mendeley.com/guides/web-citation-guide

2020-07-02 21:33 UTC, cbcunc commented on papers/ralph_kube/kube.rst
> +.. [top500] https://www.top500.org/lists/top500/list/2020/06/?page=1
No. https://www.mendeley.com/guides/web-citation-guide

2020-07-02 21:33 UTC, cbcunc commented on papers/ralph_kube/kube.rst
> +.. [cori] https://docs.nersc.gov/systems/cori/
https://www.mendeley.com/guides/web-citation-guide

2020-07-02 21:37 UTC, rkube commented on papers/ralph_kube/kube.rst
> +.. [TCV] https://www.epfl.ch/research/domains/swiss-plasma-center/research/tcv/research_tcv_tokamak/
Added full citation.

2020-07-02 21:37 UTC, rkube commented on papers/ralph_kube/kube.rst
> +.. [MAST] Mega Amp Spherical Tokamak https://ccfe.ukaea.uk/research/mast-upgrade/
Added full citation

2020-07-02 21:37 UTC, rkube commented on papers/ralph_kube/kube.rst
> +.. [AUG] ASDEX Upgrade https://www.ipp.mpg.de/16195/asdex
Added full citation

2020-07-02 21:37 UTC, rkube commented on papers/ralph_kube/kube.rst
> +.. [KSTAR] KSTAR Tokamak https://www.nfri.re.kr/kor/index
Added full citation

2020-07-02 21:37 UTC, rkube commented on papers/ralph_kube/kube.rst
> +.. [NSTX] NSTX https://www.pppl.gov/nstx
Added ful Citation

2020-07-02 21:37 UTC, rkube commented on papers/ralph_kube/kube.rst
> +.. [D3D] DIII-D http://www.ga.com/diii-d
Added full citation

2020-07-02 21:37 UTC, rkube commented on papers/ralph_kube/kube.rst
> +.. [PPY] https://www.plasmapy.org
Added full citation.

2020-07-02 22:14 UTC, rkube commented on papers/ralph_kube/kube.rst
> +.. [cori] https://docs.nersc.gov/systems/cori/
Ok. Author and date published are not available.

2020-07-02 22:16 UTC, rkube commented on papers/ralph_kube/kube.rst
> +.. [top500] https://www.top500.org/lists/top500/list/2020/06/?page=1
Added the tweet where the list is announced as a reference.

2020-07-02 22:17 UTC, rkube commented on papers/ralph_kube/kube.rst
> +.. [nerscdtn] https://docs.nersc.gov/systems/dtn/
Ok. Date published and author are not available for this website.

2020-07-02 22:23 UTC, rkube commented on papers/ralph_kube/kube.rst
> +.. [iperf] https://iperf.fr
Added the full citation

2020-07-02 22:23 UTC, rkube commented on papers/ralph_kube/kube.rst
> +.. [adios] https://adios2.readthedocs.io/en/latest/index.html
Added full citation for ADios2

2020-07-02 22:23 UTC, rkube commented on papers/ralph_kube/kube.rst
> +.. [dtn] http://es.net/science-engagement/technical-and-consulting-services/data-transfer-nodes/
Added full citation for DTN.

2020-07-02 22:43 UTC, rkube commented on papers/ralph_kube/kube.rst
> +  def kernel_coherence_64_cy(cnp.ndarray[cnp.complex128_t,
Reformatted the code.

2020-07-02 22:45 UTC, rkube commented
I hope the new changes sufficiently address all issues that have been raised now.

2020-07-03 00:57 UTC, cbcunc commented on papers/ralph_kube/kube.rst
> +  def kernel_coherence_64_cy(cnp.ndarray[cnp.complex128_t,
Thanks for the updates. You're getting close. Take a look at the rendered code in the *second* column on page 6 to see how it still overflows the column boundary. You fixed column one. We just need the same for column two.

Also, all the web citations appear fixed except for [Git] the citation for delta itself.

Take care of these two issue and I can approve the paper for publication. Thanks again for our assistance.

2020-07-03 02:40 UTC, rkube commented
Thanks, I fixed the citation and aligned the code with the column boundary.

2020-07-03 13:35 UTC, deniederhut commented on .gitignore
> -.DS_Store
This commit has now deleted the .gitignore file that was already in the repository. Please do not make changes to any files outside of your own paper directory.

2020-07-03 13:42 UTC, deniederhut commented on papers/ralph_kube/kube.rst
> +analysis of measurements on the other hand serves scientific discovery. The data and the analysis
> Our introduction reads: "Research on magnetic fusion energy combines physics, engineering, and even economics to deploy a virtually unlimited, clean, and competitively priced energy source to the grid."

This describes a motivation for fusion research -- why people want to do it. It does not describe the research questions addressed in the experiments that your software facilitates.

> As such, experimental analysis touches plasma physics, particle physics...

I'm not seeing where this is described in the paper.

> Can you please make a suggestion for a better term?

Haha I wish I could help! But I don't know what you are endeavoring to learn from these experiments! 

Let's take CERN as an example. If someone asked me what the LHC is for, it wouldn't be informative for me to say 'scientific discovery'. It would be more helpful to say something like 'discovering the composition of subatomic particles and their interactions, to answer questions about fundamental forces like gravity'. Does that analogy help?

2020-07-03 13:52 UTC, deniederhut commented on papers/ralph_kube/kube.rst
> +the performance in the following shot. By making advanced data analysis results available in near
It looks like you've responded to this in a different comment thread, but I'll keep my reply here for continuity. You wrote:

> The whole "meat" of the article revolves around how we stream the data and perform the ECEi analysis in a fast way.  ...

Yes, 100% agree. At no point do I feel like the capabilities of delta are incorrectly stated. I'm asking for context. 

Let's take air travel as an example. I can say that modern advances in aviation have created vehicles that regularly attain 700 mph airspeed velocity. That is technically correct, but isn't relating the consequences of speed.

Context might look like this: It used to take an entire week to travel from New York to Los Angeles. Modern advances in aviation have reduced this to about 4 hours.

2020-07-03 13:54 UTC, deniederhut commented on papers/ralph_kube/kube.rst
> +analysis resources is useful, it may not be practical to do so by default. A possible way to implement
This paper is still over the 8 page limit for content.

2020-07-03 15:30 UTC, rkube commented on papers/ralph_kube/kube.rst
> +analysis of measurements on the other hand serves scientific discovery. The data and the analysis
We are giving a "mission statement" for fusion energy in the introduction. The term scientific discovery is used to distinguish the objective of data analysis from measurements without time-constraints to those with time constraints. I wouldn't be surprised if CERN would make the same distinciont: Very short time-scale time constraints for real-time control of machine actuators and no time constraints for scientific discovery within particle physics. Not all data analysis done at CERN serves the task to "discovering the composition of subatomic particles and their interactions, to answer questions about fundamental forces like gravity". The same in fusion.

2020-07-03 15:31 UTC, rkube commented on papers/ralph_kube/kube.rst
> +the performance in the following shot. By making advanced data analysis results available in near
Context might look like this: It used to take an entire week to travel from New York to Los Angeles. Modern advances in aviation have reduced this to about 4 hours.

-----
This is what we describe in the abstract, last sentence:
"With this ap- proach we perform a common spectral analysis suite on imaging measurements more than 100 times faster than with a single-core implementation"

2020-07-03 16:14 UTC, rkube commented on .gitignore
> -.DS_Store
I do not understand this comment.

2020-07-03 20:16 UTC, cbcunc commented on papers/ralph_kube/kube.rst
> +  def kernel_coherence_64_cy(cnp.ndarray[cnp.complex128_t,
Hi, @rkube,thank you so much for your updates. The proceedings committee has decided to accept your paper for pre-conference publication. However, if you want to get in one last cosmetic change before publication on Sunday, it would help your article and the proceedings as a whole look more professional. If you look on page 5 of the rendered paper (http://procbuild.scipy.org/download/rkube-2020 and you may need to refresh your browser to see the change), you will see that the top line of the code example in column one still overflows the column. If you were to change:

```python
fft_future = self.executor_fft.submit(stft, data,
                                      **kwargs)
```

to:

```python
fft_future = self.executor_fft.submit(stft,
                                      data,
                                      **kwargs)
```

then I think it would fit.

The paper will be published without the change and there may be opportunity for further changes after publication. However, I want you to have the opportunity to have the best looking paper in time for the conference.

2020-07-05 14:05 UTC, deniederhut requested changes
Please do not modify files outside of your own paper directory.

2020-07-05 14:05 UTC, deniederhut commented on .gitignore
> -.DS_Store
You have deleted the .gitignore for the whole repository, then committed that deletion. If we merge this PR, the change you committed -- deleting .gitignore -- will delete this file for everyone.

2020-07-05 20:12 UTC, rkube commented
> You have deleted the .gitignore for the whole repository, then committed that deletion. If we 
> merge this PR, the change you committed -- deleting .gitignore -- will delete this file for everyone.

I see. What do you need from me to fix this?

2020-07-06 21:50 UTC, rkube commented
Hi. Can you please let me know how I can fix the gitignore issue? I don't know git enough to fix this myself. Thank you.

2020-07-07 00:18 UTC, deniederhut commented
> I don't know git enough

😅 if it's any consolation, I think everyone feels that they don't know git well enough. Probably the easiest thing to do is grab our original version, then add and commit it. The code will look something like this:

```
git checkout origin/2020 .gitignore
git add .gitignore
git commit -m "adding back .gitignore like a boss"
git push origin 2020
```

2020-07-07 00:41 UTC, rkube commented
> > I don't know git enough
> 
> 😅 if it's any consolation, I think everyone feels that they don't know git well enough. Probably the easiest thing to do is grab our original version, then add and commit it. The code will look something like this:
> 
> ```
> git checkout origin/2020 .gitignore
> git add .gitignore
> git commit -m "adding back .gitignore like a boss"
> git push origin 2020
> ```

Ok, got it.  Can you please try again?

2020-07-08 12:34 UTC, rkube commented
Hi. Did you have a chance to see if you can merge this pull-request now? I tried fixing the .gitignore issue as you instructed and it would be great to see the paper in the proceedings.
Thanks, Ralph

2020-07-09 15:37 UTC, rkube commented
@deniederhut @cbcunc Hi, can you please take another look and see if this PR can be merged now?
Thanks, Ralph

2020-07-10 00:39 UTC, deniederhut commented
<img width="271" alt="Screenshot 2020-07-09 19 38 10" src="https://user-images.githubusercontent.com/6868396/87103880-df087380-c21b-11ea-9a69-2ddaa86953c3.png">

😂😂😂 thanks for indulging my silliness. I think this is good to go!

2020-07-10 00:40 UTC, deniederhut approved these changes

2020-07-10 00:41 UTC, merged