Christensen-Prototype to Production Paper
scipy-conference/scipy_proceedings pull request #562
Opened 2020-05-29 23:55 UTC by sdc50

If you are creating this PR in order to submit a draft of your paper,
see http://procbuild.scipy.org/ for logs generated by the build
process.

See the [project readme](https://github.com/scipy-conference/scipy_proceedings#build-your-paper)
for more information.

2020-06-03 13:36 UTC, alberto-antonietti commented
Hi @sdc50 I am going to review your paper.

2020-06-08 01:40 UTC, rainwoodman commented
Hi @sdc50 and @alberto-antonietti, I will also be a reviewer.

2020-06-08 02:25 UTC, rainwoodman reviewed
A few very high level comments after an overall read of the draft. 

1. How does the framework deal with continued development and maintenance?
I suggest the authors add some discussion on this issue because it's usually believed to be the engineering cost of post-production an be huge. Is it possible that the scientific production is different, as the term of a product is usually very short?

2. Flow of source code (and best practice). The authors seem to suggest that copying the notebook as-is into a brokeh service as the current practice. Are there alternatives? 

I suggest the authors expand the discussion on this issue and share their experiences with the community.  Reusing code developed inside a notebook has always been challenging, since usually a notebook is developed in a programming model that relies on a global scope, while traditional reusable code typically prefer to limit the scope of variables to units of functions. So either the notebooks shall be drafted differently (functions), or some refactoring is necessary before the reuse, or perhaps the framework the can digest code that uses a global scope, or can even pick a sequence of notebook cells and run them on a live Jupyter kernel, then export the results. 

3. Please add reference and description (and comparison if possible) to existing frameworks that provide a similar functionality. Such a section will greatly help the growth of the sector in the community.

2020-06-08 02:25 UTC, rainwoodman commented on papers/scott_christensen/paper.rst
> +.. figure:: notebook.png
Presumably there are also stages for data-cleaning, summarzing, etc (customary in scientific workflows) before the data is ready for presentation in the panel? These are note shown in the figure. The text in the paragraph above is not clear if these steps are supposed to be part of the notebook. 

If the lack of code preamples is due to difficulty in showing code in a screenshot, consider pasting the coe in as a code block in the .rst file.

2020-06-08 18:35 UTC, sdc50 commented on papers/scott_christensen/paper.rst
> +.. figure:: notebook.png
@rainwoodman Thank you for the feedback. I appreciate your perspective on how to make our research more interesting and useable by the community. We will work on addressing your suggestions and push some update soon.

2020-06-16 17:14 UTC, alberto-antonietti requested changes
Thank you for the impressive work done in the development of Panel and the integration of different tools to generate an effective pipeline from prototyping (Jupyter notebooks) to production tools (Bokeh/Tethys).

I have added some in-line comments and suggestions that could help in refining the paper.

I agree with @rainwoodman , it is important to add References. Both to similar works and to reference the different libraries used.

I am not very familiar with web app developments, therefore a point that is not very clear to me is how the deployment of a Jupyter Notebook to Panel works. In the same way, how does the transitioning from Panel to Bokeh/Tethys happens? It would be useful to add a schematic representing the different steps of the process, from a Jupyter Notebook to the final polished Tethys web app.

2020-06-16 17:14 UTC, alberto-antonietti commented on papers/scott_christensen/paper.rst
> +   web apps, Panel, Tethys Platform, Holoviz
`Jupyter notebook` can be another relevant keyword

2020-06-16 17:14 UTC, alberto-antonietti commented on papers/scott_christensen/paper.rst
> +The next section provides some background on the core tools that are leveraged and enhanced to create the rapid prototyping capability. That is followed by the Methods section which will describe how
```suggestion
The next section provides some background on the core tools that are leveraged and enhanced to create the rapid prototyping capability. That is followed by the Methods section which describes how those core tools were enhanced and chained together to create a pipeline of tools for taking a prototype to production. The Results section describes how those tools were used to create a sample web application to analyze and explore COVID-19 data. Finally, the conclusion provides some discussion and suggests future work that can continue to enhance the proposed integrated pipeline.
```

2020-06-16 17:14 UTC, alberto-antonietti commented on papers/scott_christensen/paper.rst
> +Jupyter notebooks are a commonly used as a starting point for scientific workflows because it is an open source tool that integrates code, interactive visualizations, and documentation in a sharable
```suggestion
Jupyter notebooks are a commonly used as a starting point for scientific workflows because they are open source tools that integrate code, interactive visualizations, and documentation in a sharable and reproducible way. The notebook environment is ideal for quickly iterating and prototyping scripts and visualizations.
```

2020-06-16 17:14 UTC, alberto-antonietti commented on papers/scott_christensen/paper.rst
> +The Holoviz tool stack while providing many interactive widgets and plots lacked the flexibility in controlling the layout and in integrating other elements into a dashboard. We collaborated with the
```suggestion
The Holoviz tool stack, while providing many interactive widgets and plots, lacked the flexibility in controlling the layout and in integrating other elements into a dashboard. We collaborated with the Holoviz team at Anaconda to add a new library to the Holoviz stack called Panel. Panel allows much more control over how elements are organized. It provides several tools for controlling layout including nested rows and columns, grids, tabs, and widget boxes (Fig. :ref:`fig1`). Panel continues to be actively developed and had gained wide community support; thus, additional features continue to be added.
```

2020-06-16 17:14 UTC, alberto-antonietti commented on papers/scott_christensen/paper.rst
> +Additionally, Panel also provides Pipelines, which supports creating multi-step workflows :ref:`fig2`. Many scientific workflows require various stages of user interaction/input and pipelines allows
```suggestion
Additionally, Panel also provides Pipelines, which supports creating multi-step workflows (Fig. :ref:`fig2`). Many scientific workflows require various stages of user interaction/input and Pipelines allows multiple dashboards and visualizations to be strung together in sequence to support these types of workflows.
```

2020-06-16 17:14 UTC, alberto-antonietti commented on papers/scott_christensen/paper.rst
> +.. figure:: panel_pipeline.png
This figure is not completely clear to me. 
It could be more useful to have two panels, one representing the visualization at Stage 1 and another one at Stage 2.
What is the meaning of` 0.0*0.0 = 0.0` and `0.0^0.0 = 1.0`?

2020-06-16 17:14 UTC, alberto-antonietti commented on papers/scott_christensen/paper.rst
> +By integrating Panel apps into git Tethys, we can then leverage the many tools that Tethys provides including user management and permissions, easy database serialization, and the powerful compute AP
What is the DoD research HPC system? Is that accessible by anyone?

2020-06-16 17:14 UTC, alberto-antonietti commented on papers/scott_christensen/paper.rst
> +We have now created several web applications for complex numerical modeling workflows and data analysis. As an example case we will demonstrate how an interactive visualization exploration dashboard
Could you specify what COVID-19 data is it possible to visualize (e.g., cases, deaths, tests performed, etc.)? Which is the database used as source?

2020-06-19 02:19 UTC, deniederhut commented
Hey @sdc50 ! Thanks to some awesome behind the scenes work by @stargaser, we now have experimental support for publishing papers with ORCIDs. If you have one and would like to add it to your paper, it's as simple as adding an `:orcid:` tag under your name in the paper header. [You can see an example of how to do this in the `00_vanderwalt` example paper](https://raw.githubusercontent.com/scipy-conference/scipy_proceedings/2020/papers/00_vanderwalt/00_vanderwalt.rst). If you don't have one, no worries! You can still publish your paper as is.

2020-06-25 13:14 UTC, deniederhut commented
Hi @sdc50 ! Have you had a chance to incorporate the reviewers' comments into your paper?

2020-06-29 14:44 UTC, deniederhut commented
Hi @sdc50 ! I think we're still waiting to hear back from you on your revision progress.

2020-06-30 13:42 UTC, deniederhut commented
Hi everyone! Friendly reminder that the open review period ends 2 July -- the committee will be making final decisions on each paper this Friday.

2020-07-03 19:43 UTC, cbcunc requested changes
The changes requested by the reviewers in the comments must be addressed before this paper will be considered for merging into the proceedings.

2020-07-10 00:44 UTC, deniederhut commented
Thank you @rainwoodman and @alberto-antonietti for your reviews on this paper! I know it takes a lot of time and and a lot of effort to do this. Since we haven't heard back from the author, I'm closing this PR.

2020-07-10 00:44 UTC, closed without merging