Paper: Zain
scipy-conference/scipy_proceedings pull request #568
Opened 2020-05-30 03:39 UTC by Micky774

If you are creating this PR in order to submit a draft of your paper,
see http://procbuild.scipy.org/ for logs generated by the build
process.

See the [project readme](https://github.com/scipy-conference/scipy_proceedings#build-your-paper)
for more information.

2020-05-30 19:42 UTC, deniederhut commented on papers/zain/zain.rst
> +.. figure:: of_Ex.png
Hi! It looks like the current built is crashing because the filename has a lowercase e, like `of_ex.png`. Would you mind updating this?

2020-05-30 20:14 UTC, Micky774 commented on papers/zain/zain.rst
> +.. figure:: of_Ex.png
Updated!

2020-05-30 21:26 UTC, deniederhut commented on papers/zain/zain.rst
> +.. figure:: of_Ex.png
Thanks!

2020-06-12 18:11 UTC, saketkc commented
Hi @Micky774, I will be reviewing your paper! I will leave my comments below over the weekend. Thanks!

2020-06-15 01:52 UTC, snikumbh commented
Hi @Micky774, I look forward to reviewing your paper. Comments coming very soon. Thanks :)

2020-06-15 17:21 UTC, Micky774 commented
Looking forward to working with you all!

2020-06-19 02:23 UTC, deniederhut commented
Hey @Micky774 ! Thanks to some awesome behind the scenes work by @stargaser, we now have experimental support for publishing papers with ORCIDs. If you have one and would like to add it to your paper, it's as simple as adding an `:orcid:` tag under your name in the paper header. [You can see an example of how to do this in the `00_vanderwalt` example paper](https://raw.githubusercontent.com/scipy-conference/scipy_proceedings/2020/papers/00_vanderwalt/00_vanderwalt.rst). If you don't have one, no worries! You can still publish your paper as is.

2020-06-20 22:56 UTC, deniederhut commented
Hi @saketkc and @snikumbh ! How are your reviews coming along?

2020-06-21 19:43 UTC, saketkc requested changes
Hi @Micky774, thanks for submitting the full paper. I learned a lot in the process. Most of my comments appear inline. But a general comment: the paper can be improved to make it an easier read. In particular, the text needs to be organized so that the methods and results are clearly distinguished. At places the paper goes into too many details which I believe can all be combined into a smaller section. The general idea should be to give an overview of the methods first before showing the results and then elaborating on the underlying ideas in the methods in a new section. 

Happy to answer any questions you or other authors might have after reading my comments. Just one last general comment, please consider citing all software you are using. I was a bit discouraged to see particularly that Scipy's citation was missing.

Thanks,
Saket

2020-06-21 19:43 UTC, saketkc commented on papers/zain/zain.rst
> +tasks such as classification and clustering, and whatever else experts may deem necessary. Furthermore,
Consider changing "whatever else" => "any other tasks"

2020-06-21 19:43 UTC, saketkc commented on papers/zain/zain.rst
> +applications to ciliary waveform analysis are novel: cilia exhibit subtle, rotational, non-linear
It is not clear if this statement implies that application to ciliarly waveform analysis are novel because of their subtle/rotational/non-linear motion or just in general. The authors do point out Lu 2018 and Quinn 2015 (both from the same group). I believe the reader can benefit from clarifying that clustering and classification in this setting is more nuanced because of the particular properties attached with it (rotational/non-linear motion for example). This is also highlighted in the statement that appears later "While attempts have been made at addressing this problem,"

2020-06-21 19:43 UTC, saketkc commented on papers/zain/zain.rst
> +we avoid using labeled data in order to free the model from systematic assumptions naturally imposed by
It would be useful to briefly describe what "labeled data" is in this context. Disease state, abnormal mobility etc.

2020-06-21 19:43 UTC, saketkc commented on papers/zain/zain.rst
> +ROI maps nor a labelled dataset as training data. While clinicians acknowledge the existence of
"labelled" => "labeled"

2020-06-21 19:43 UTC, saketkc commented on papers/zain/zain.rst
> +Fully Convolutional DenseNets and LSTM networks :cite:`lu_stacked_2018`.  Densely Connected
Consider citing LSTM publication as well (DenseNet already cited).

2020-06-21 19:43 UTC, saketkc commented on papers/zain/zain.rst
> +Fully Convolutional DenseNets and LSTM networks :cite:`lu_stacked_2018`.  Densely Connected
Ideally, Lu 2018 should be followed by the citation rather than at the end of statement.

2020-06-21 19:43 UTC, saketkc commented on papers/zain/zain.rst
> +Methods
The Methods section as it currently stands is just a paragraph long. The Results section on the other hand is long. But it also appears that part of the Results section is actually Methods. The authors should consider reorganizing the text in these two sections. The focus of the Methods section should be to describe the details of the architecture, its working and how parameters/hyperparameters were chosen. The Results section should focus on the evaluation of this model on their dataset.

2020-06-21 19:43 UTC, saketkc commented on papers/zain/zain.rst
> +Our proposed model is divided into three modules: preprocessing, appearance, and dynamics.
The authors might consider adding a flowchart that explains the three modules briefly as Figure 1.

2020-06-21 19:43 UTC, saketkc commented on papers/zain/zain.rst
> +latent space. The dynamics module employs another VAE to learn a representation from this compressed
The way the dynamics sections is described here, it seems it is another appearance section as only the VAE part is described but the dynamics part of this module is missing.

2020-06-21 19:43 UTC, saketkc commented on papers/zain/zain.rst
> +Results
As mentioned in an earlier comment, the authors should consider reorganizing the text to separate the methods from results. A lot of the content in the next few sections belongs to Methods in my opinion.

2020-06-21 19:43 UTC, saketkc commented on papers/zain/zain.rst
> +- generate segmentation masks that distinguish spatial regions containing cilia from background noise and
- before generate seems unnecessary.

2020-06-21 19:43 UTC, saketkc commented on papers/zain/zain.rst
> +We aim to build upon these studies by developing a fully unsupervised approach to characterizing
I am a bit unsure about claiming this to be fully unsupervised approach given the segmentation task does use ground truth masks and microscopy data for training where the ground truth masks are generated manually. How about calling it a "minimally supervised" or semi-supervised approach. This would also mean that the title of the paper be changed accordingly. I am sure the authors have given it a thought so it might make sense to explain the rationale for calling it fully unsupervised. This could be done, for example, by justifying that the trained segmentation module is generalizable.

2020-06-21 19:43 UTC, saketkc commented on papers/zain/zain.rst
> +systems of equations. Among Farneback, Horn-Schunck, and Lucas-Kanade optical flow computation algorithms,
Farneback, Horn-Schunck, and Lucas-Kanade  are all missing citations (HS81 citation appears later, but should be ideally moved here).

2020-06-21 19:43 UTC, saketkc commented on papers/zain/zain.rst
> +.. figure:: of_ex.png
Consider improving the image quality (higher dpi, bolder/bigger fonts).

2020-06-21 19:43 UTC, saketkc commented on papers/zain/zain.rst
> +:ref:`of` shows an example of healthy cilia and its mid-cycle optical flow where vector magnitude
At the least this statement should not begin with a citation (Consider adding 'Figure'). Also this is probably the first "Result" in this section with the rest being more suitably part of the "Methods" section.

2020-06-21 19:43 UTC, saketkc commented on papers/zain/zain.rst
> +(AE). A general autoencoder (AE) attempts to learn a low-dimensional representation of the data by
AE abbreviation doesn't need to be defined twice.

2020-06-21 19:43 UTC, saketkc commented on papers/zain/zain.rst
> +by learanble weights :math:`\theta`.The encoder is tasked with taking the original data input and
Add space before "The encoder"

2020-06-21 19:43 UTC, saketkc commented on papers/zain/zain.rst
> +we omit the technical details while referring you to :cite:`doersch2016tutorial` for further reading. Instead, we provide
"you to" => "the readers to".

2020-06-21 19:43 UTC, saketkc commented on papers/zain/zain.rst
> +	L_\theta(x)=\|x-D_\theta(E_\theta(x))\|^2
End equation with a '.' (applies elsewhere too where it is end of a statement).

2020-06-21 19:43 UTC, saketkc commented on papers/zain/zain.rst
> +	L_\theta(x)=\|x-D_\theta(z)\|^2
End with a '.'.

2020-06-21 19:43 UTC, saketkc commented on papers/zain/zain.rst
> +point should be able to be reasonably decoded as a point in the starting data space. To break that down,
Shorten "should be able to be " => "can be". Also, a lot of content in this section should be moved to the "Methods" seciton.

2020-06-21 19:43 UTC, saketkc commented on papers/zain/zain.rst
> +	L_\theta(x)=\|x-D_\theta(z)\|^2+\operatorname{KL}(q_\theta(z|x) \,\|\, p(z))
End with a .

2020-06-21 19:43 UTC, saketkc commented on papers/zain/zain.rst
> +are modeled using a Gated Recurrent Unit (GRU:cite:`Cho2014LearningPR`) and a Long Short-Term Memory
The cite here is not being parsed properly. LSTM can be cited early on (See my previous comments). The LSTM abbreviation also should appear earlier.

2020-06-21 19:43 UTC, saketkc commented on papers/zain/zain.rst
> +We train our FCDN-103 model, written in PyTorch, with an Adam optimizer and cross-entropy
Please cite Pytorch. This applies to all the software libraries you are using. Please.

2020-06-21 19:43 UTC, saketkc commented on papers/zain/zain.rst
> +generated optical flow fields using SciPy's signal and ndimage packages.
Please cite Scipy.

2020-06-21 19:43 UTC, saketkc commented on papers/zain/zain.rst
> +we used the NumPy library to efficiently sample a fixed number of frames from each video.
Cite NumPy.

2020-06-22 00:57 UTC, snikumbh reviewed
Hi @Micky774 and co-authors,

Congratulations on the full paper submission. I enjoyed reading the paper. Here are some suggestions towards improving the paper further.

I found that the general idea of the paper -- the problem and the proposed solution -- is put forth well. However, some important aspects of the paper need work. 
1. The paper is a good read in parts and details. Meaning that, each paragraph or portion of text explains the technicalities well individually. Proper sectioning/structuring would be very helpful to clearly convey the overall goal and status of the work. For instance, the relative work section could end with a subsection clearly delineating the contributions of this work.
2. A proper, complete methods section giving details of all modules at once in respective subsections can help the reader. Beginning this section with a flow diagram pictorially explaining the modules would be very beneficial. 
3. All figure legends can be expanded with some more text/details of what the user should observe/note in the figure. Also, one could use this space to explain all acronyms appearing in the figure.
4. After the results section, conclude with a discussion on the current status of project implementation, attained results, future work. Some details from technical discussion section could be moved to the results section (see individual comments).

Further comments inline.
Please feel free to ask if something is not clear.

2020-06-22 00:57 UTC, snikumbh commented on papers/zain/zain.rst
> +be supplemented or replaced for this task. Our proposed model is divided into three modules:
"replacing" the expert can be debatable. Given the results and the conclusion section text, once the complete pipeline is implemented and thoroughly tested to perform satisfactorily, this could be discussed.

2020-06-22 00:57 UTC, snikumbh commented on papers/zain/zain.rst
> +semantically meaningful patterns and phenotypes that fall outside current clinical thinking. Furthermore,
change "... discover potentially semantically ..." to "... discover potential semantically meaningful patterns ..."

2020-06-22 00:57 UTC, snikumbh commented on papers/zain/zain.rst
> +and clustering on the latent space should be meaningful for those studying ciliary motion and its connection to ciliopathies.
I am not sure if I understood the role of "interpolation" here. Did you mean interpretation by any chance?

2020-06-22 00:57 UTC, snikumbh commented on papers/zain/zain.rst
> +determine the beat pattern. The authors used autoregressive (AR) representations of optical
The sentence beginning with "Likewise, ..." should also be phrased in the past tense because that is something the earlier work considered/did (if I understood correctly).

2020-06-22 00:57 UTC, snikumbh commented on papers/zain/zain.rst
> +phenotypes with specific ciliopathies and genetic mutations :cite:`quinn2015automated`.
I think you mean the inability to observe complex non-linear relationships in data in general?

2020-06-22 00:57 UTC, snikumbh commented on papers/zain/zain.rst
> +motion) to a representational learning task to generate meaningful, low dimensional representations
consistently hyphenated --> low-dimensional

2020-06-22 00:57 UTC, snikumbh commented on papers/zain/zain.rst
> +with the original video data as additional channels to each frame to form an augmented video.
How does the quality of prediction of the segmentation masks affect the results downstream? Has this been studied yet?

2020-06-22 00:57 UTC, snikumbh commented on papers/zain/zain.rst
> +latent space. The dynamics module employs another VAE to learn a representation from this compressed
This is the first usage of the acronym VAE, please define it here.

2020-06-22 00:57 UTC, snikumbh commented on papers/zain/zain.rst
> +mask to be used in subsequent modules. We draw upon prior supervised segmentation literature to implement
Using the few ground truth segmentation masks to predict segmentation masks for all samples in the data for further use downstream, qualifies as a semi-supervised approach instead of unsupervised. While I agree that this is the case only for the preprocessing module, if the downstream performance is heavily dependent on this, the authors should consider calling their approach semi-supervised.

2020-06-22 00:57 UTC, snikumbh commented on papers/zain/zain.rst
> +the appearance module. Our architecture, shown in :ref:`dense`, consists of dense blocks, transition
It is not clear which parts of FCDenseNet architecture are modified.

2020-06-22 00:57 UTC, snikumbh commented on papers/zain/zain.rst
> +temporal coherence assumes that a pixel's neighbors likely exhibit similar motion over gradual time.
Consider numbering the assumptions for more readability instead of a single long sentence.

2020-06-22 00:57 UTC, snikumbh commented on papers/zain/zain.rst
> +motion :cite:`horn_determining_1981`.
A curious reader would wonder, why are the other algorithms not suitable or why was the Horn-Shunck algorithm chosen?
What is the modification in the Horn-Schunck algorithm?

2020-06-22 00:57 UTC, snikumbh commented on papers/zain/zain.rst
> +the encoder, and the decoder. Suppose that the starting dataset is a collection of n-dimensional points,
This paragraph can be subsectioned as brief introduction to AEs and VAEs.

2020-06-22 00:57 UTC, snikumbh commented on papers/zain/zain.rst
> +in that there's no guarantee that the decoder doesn't degenerate to setting :math:`\sigma` arbitrarily
typo? "results" --> "result"

2020-06-22 00:57 UTC, snikumbh commented on papers/zain/zain.rst
> +distribution. This is implemented by imposing a KL-Divergence loss between the posterior distributions
First instance of KL-Divergence usage so define the acronym as "Kullback–Leibler".

2020-06-22 00:57 UTC, snikumbh commented on papers/zain/zain.rst
> +between apparent patterns in this space as and semantically meaningful patterns in the
"apparent patterns in this space" --> consider replacing "this" with the space you are referring to for more clarity.

2020-06-22 00:57 UTC, snikumbh commented on papers/zain/zain.rst
> +(LSTM:cite:`LSTM1999`) unit, respectively. They are types of recurrent neural networks (RNN) with
The acronym RNN is already defined above, so can be omitted here.

2020-06-22 00:57 UTC, snikumbh commented on papers/zain/zain.rst
> +The dynamics decoder LSTM :math:`D_\text{dyn}` starts from from a latent dynamics vector as its hidden
typo: from appears twice

2020-06-22 00:57 UTC, snikumbh commented on papers/zain/zain.rst
> +to ensure that we may complete backpropogation, since :math:`\mu,\sigma` are dependent on weights
typo: backprop_o_gation --> backprop_a_gation

2020-06-22 00:57 UTC, snikumbh commented on papers/zain/zain.rst
> +and the remaining :math:`k` frames in each sequence is minimized with back-propagation.
previous usage of backpropagation appeared w/o a hyphen

2020-06-22 00:57 UTC, snikumbh commented on papers/zain/zain.rst
> +and FCDN-103 generated mask (right); the predicted masks cover more concise areas of cilia
This information is suitable for the results section.

2020-06-22 00:57 UTC, snikumbh commented on papers/zain/zain.rst
> +The modular approach to its design ensures portability and adaptability to all sorts of projects.
"all sorts of projects" --> other projects.

2020-06-22 01:01 UTC, Micky774 commented
Thank you both for your feedback! We'll be taking a detailed look at it and responding soon!

2020-06-23 21:56 UTC, Micky774 commented on papers/zain/zain.rst
> +tasks such as classification and clustering, and whatever else experts may deem necessary. Furthermore,
Changed, thanks

2020-06-23 21:59 UTC, Micky774 commented on papers/zain/zain.rst
> +we avoid using labeled data in order to free the model from systematic assumptions naturally imposed by
Attempted a fix. Let me know if you think it's worth diving into more detail regarding labeled data. Thanks

2020-06-23 22:00 UTC, Micky774 commented on papers/zain/zain.rst
> +ROI maps nor a labelled dataset as training data. While clinicians acknowledge the existence of
Fixed

2020-06-23 22:03 UTC, Micky774 commented on papers/zain/zain.rst
> +Fully Convolutional DenseNets and LSTM networks :cite:`lu_stacked_2018`.  Densely Connected
Updated. Moved DenseNet initial citation as well to maintain consistency.

2020-06-23 22:13 UTC, Micky774 commented on papers/zain/zain.rst
> +- generate segmentation masks that distinguish spatial regions containing cilia from background noise and
Changed

2020-06-23 22:28 UTC, Micky774 commented on papers/zain/zain.rst
> +:ref:`of` shows an example of healthy cilia and its mid-cycle optical flow where vector magnitude
Added 'Figure' before citation. Keeping conversation open pending restructuring of methods/results

2020-06-23 22:30 UTC, Micky774 commented on papers/zain/zain.rst
> +(AE). A general autoencoder (AE) attempts to learn a low-dimensional representation of the data by
Fixed

2020-06-23 22:30 UTC, Micky774 commented on papers/zain/zain.rst
> +by learanble weights :math:`\theta`.The encoder is tasked with taking the original data input and
Fixed

2020-06-23 22:32 UTC, Micky774 commented on papers/zain/zain.rst
> +we omit the technical details while referring you to :cite:`doersch2016tutorial` for further reading. Instead, we provide
Fixed

2020-06-23 22:33 UTC, Micky774 commented on papers/zain/zain.rst
> +	L_\theta(x)=\|x-D_\theta(E_\theta(x))\|^2
Fixed

2020-06-23 22:33 UTC, Micky774 commented on papers/zain/zain.rst
> +	L_\theta(x)=\|x-D_\theta(z)\|^2
Fixed

2020-06-23 22:35 UTC, Micky774 commented on papers/zain/zain.rst
> +point should be able to be reasonably decoded as a point in the starting data space. To break that down,
Updated wording.

2020-06-23 22:35 UTC, Micky774 commented on papers/zain/zain.rst
> +	L_\theta(x)=\|x-D_\theta(z)\|^2+\operatorname{KL}(q_\theta(z|x) \,\|\, p(z))
Fixed

2020-06-23 22:37 UTC, Micky774 commented on papers/zain/zain.rst
> +are modeled using a Gated Recurrent Unit (GRU:cite:`Cho2014LearningPR`) and a Long Short-Term Memory
Updated and fixed, in tandem with previous comment.

2020-06-23 22:44 UTC, Micky774 commented on papers/zain/zain.rst
> +We train our FCDN-103 model, written in PyTorch, with an Adam optimizer and cross-entropy
Fixed

2020-06-23 22:44 UTC, Micky774 commented on papers/zain/zain.rst
> +generated optical flow fields using SciPy's signal and ndimage packages.
Fixed

2020-06-23 22:44 UTC, Micky774 commented on papers/zain/zain.rst
> +we used the NumPy library to efficiently sample a fixed number of frames from each video.
Fixed

2020-06-23 22:46 UTC, Micky774 commented on papers/zain/zain.rst
> +be supplemented or replaced for this task. Our proposed model is divided into three modules:
Agreed. Initially the statement was meant to convey the idea of shifting the _focus_ of expert labor rather than necessarily replacing it, though "supplemented" sufficiently conveys that I think. Removed "replaced"

2020-06-23 22:47 UTC, Micky774 commented on papers/zain/zain.rst
> +semantically meaningful patterns and phenotypes that fall outside current clinical thinking. Furthermore,
Changed

2020-06-23 22:51 UTC, Micky774 commented on papers/zain/zain.rst
> +determine the beat pattern. The authors used autoregressive (AR) representations of optical
Rewrote sentence to incorporate suggestion as well as (hopefully) clarify the role of the referenced authors.

2020-06-23 22:52 UTC, Micky774 commented on papers/zain/zain.rst
> +motion) to a representational learning task to generate meaningful, low dimensional representations
Fixed

2020-06-23 22:57 UTC, Micky774 commented on papers/zain/zain.rst
> +with the original video data as additional channels to each frame to form an augmented video.
Nope. A very good question, which I've now included in the further research section (as well as a couple similar questions)

2020-06-23 22:58 UTC, Micky774 commented on papers/zain/zain.rst
> +with the original video data as additional channels to each frame to form an augmented video.
Let me know whether or not this sufficiently resolves the conversation, thanks!

2020-06-23 23:03 UTC, Micky774 commented on papers/zain/zain.rst
> +temporal coherence assumes that a pixel's neighbors likely exhibit similar motion over gradual time.
Changed

2020-06-23 23:04 UTC, Micky774 commented on papers/zain/zain.rst
> +in that there's no guarantee that the decoder doesn't degenerate to setting :math:`\sigma` arbitrarily
Yup, fixed, thanks!

2020-06-23 23:07 UTC, Micky774 commented on papers/zain/zain.rst
> +distribution. This is implemented by imposing a KL-Divergence loss between the posterior distributions
Fixed. Also updated KL-Divergence to KL Divergence to stay consistent with literature.

2020-06-23 23:08 UTC, Micky774 commented on papers/zain/zain.rst
> +between apparent patterns in this space as and semantically meaningful patterns in the
Changed

2020-06-23 23:09 UTC, Micky774 commented on papers/zain/zain.rst
> +(LSTM:cite:`LSTM1999`) unit, respectively. They are types of recurrent neural networks (RNN) with
Fixed

2020-06-23 23:10 UTC, Micky774 commented on papers/zain/zain.rst
> +The dynamics decoder LSTM :math:`D_\text{dyn}` starts from from a latent dynamics vector as its hidden
Fixed

2020-06-23 23:11 UTC, Micky774 commented on papers/zain/zain.rst
> +to ensure that we may complete backpropogation, since :math:`\mu,\sigma` are dependent on weights
Fixed. One day I will get that word right on the first try. Thanks!

2020-06-23 23:11 UTC, Micky774 commented on papers/zain/zain.rst
> +and the remaining :math:`k` frames in each sequence is minimized with back-propagation.
Fixed

2020-06-23 23:12 UTC, Micky774 commented on papers/zain/zain.rst
> +The modular approach to its design ensures portability and adaptability to all sorts of projects.
Changed

2020-06-24 14:37 UTC, snoiarao commented on papers/zain/zain.rst
> +the appearance module. Our architecture, shown in :ref:`dense`, consists of dense blocks, transition
Sorry, ambiguous wording. Fixed

2020-06-24 14:55 UTC, snoiarao commented on papers/zain/zain.rst
> +systems of equations. Among Farneback, Horn-Schunck, and Lucas-Kanade optical flow computation algorithms,
Fixed

2020-06-24 15:04 UTC, snoiarao commented on papers/zain/zain.rst
> +motion :cite:`horn_determining_1981`.
There is a brief explanation in the 'Technical Discussion: Implementation Details' subsection, but it will be moved up once Methods section is restructured. Will update once moved

2020-06-25 15:29 UTC, Micky774 commented on papers/zain/zain.rst
> +and clustering on the latent space should be meaningful for those studying ciliary motion and its connection to ciliopathies.
Ah that's a vestige of an older version of this paper, good catch. Originally we were going to do more with interpolation on the latent space, but decided to focus instead on a VampPrior based approach which doesn't ensure meaningful interpolation. Updating.

2020-06-25 15:32 UTC, Micky774 commented on papers/zain/zain.rst
> +phenotypes with specific ciliopathies and genetic mutations :cite:`quinn2015automated`.
Sure, but that section was heavily contextualized as specifically looking at the case of ciliopathies, as the statement was also supported by the referenced material, so I don't know whether it'd be appropriate to generalize the statement. Do you think it's necessary or worthwhile?

2020-06-25 15:36 UTC, Micky774 commented on papers/zain/zain.rst
> +Our proposed model is divided into three modules: preprocessing, appearance, and dynamics.
Working on that, will update when added.

2020-06-25 15:37 UTC, Micky774 commented on papers/zain/zain.rst
> +.. figure:: of_ex.png
Improved size of the specific image, as well as changing it to a vertical stack to better fit the columns. Updating font size on a couple other images as well.

2020-06-25 15:39 UTC, Micky774 commented
Also, does anyone know how to add/change the corresponding author? I can't quite figure it out on the rst side of things

2020-06-25 19:11 UTC, Micky774 commented on papers/zain/zain.rst
> +Our proposed model is divided into three modules: preprocessing, appearance, and dynamics.
Added

2020-06-25 19:18 UTC, snoiarao commented on papers/zain/zain.rst
> +Methods
Restructured such that Methods contains most of prior Results section; let us know if this requires further structural changes!

2020-06-25 19:23 UTC, snoiarao commented on papers/zain/zain.rst
> +:ref:`of` shows an example of healthy cilia and its mid-cycle optical flow where vector magnitude
Moved paragraph and figure to results section

2020-06-25 19:23 UTC, snoiarao commented on papers/zain/zain.rst
> +Results
Restructured!

2020-06-25 19:24 UTC, snoiarao commented on papers/zain/zain.rst
> +motion :cite:`horn_determining_1981`.
Moved explanation of optical flow to methods section

2020-06-25 19:24 UTC, snoiarao commented on papers/zain/zain.rst
> +and FCDN-103 generated mask (right); the predicted masks cover more concise areas of cilia
moved to results

2020-06-25 21:10 UTC, Micky774 commented on papers/zain/zain.rst
> +the encoder, and the decoder. Suppose that the starting dataset is a collection of n-dimensional points,
Changed the section structure to hopefully organize content more clearly.

2020-06-25 21:15 UTC, Micky774 commented on papers/zain/zain.rst
> +latent space. The dynamics module employs another VAE to learn a representation from this compressed
VAE definition has been updated. Added some more explanation regarding the dynamics module. Let me know if you think it suffices, or if it needs more. Thanks!

2020-06-25 22:10 UTC, Micky774 commented on papers/zain/zain.rst
> +mask to be used in subsequent modules. We draw upon prior supervised segmentation literature to implement
Added section addressing this point, as well as changed the title to "Towards ..." to more clearly communicate the lack of a fully unsupervised network.

2020-06-25 22:14 UTC, Micky774 commented on papers/zain/zain.rst
> +We aim to build upon these studies by developing a fully unsupervised approach to characterizing
Added clarification in the preprocessing methodology section addressing the supervised nature of the current segmentation, as well as changed the title to "Towards ..." to more clearly communicate the lack of a fully unsupervised network. I think it would be okay to leave the section you highlighted as is since it specifies that we "aim to..." develop a fully unsupervised approach. Let me know your thoughts, and whether you think that anything further needs to be done. Thanks!

2020-06-26 00:15 UTC, Micky774 commented
@deniederhut It seems that our paper is failing to build on the scipy server, though it builds locally perfectly fine. Any idea what the issue may be?

2020-06-26 14:22 UTC, Micky774 commented on papers/zain/zain.rst
> +applications to ciliary waveform analysis are novel: cilia exhibit subtle, rotational, non-linear
Updated that portion to clarify the difficulty in immediately applying those techniques, rather than saying the application itself is novel. We really want to talk about the fact that you can't quite obviously "plug 'n chug" a good solution by applying generic clustering algorithms, so I think that's better conveyed now.

2020-06-26 16:13 UTC, deniederhut commented
👀

Looks like latex is tripping on this author name: `Çaglar G{\"u}lçehre` Here's the actual error:

```
! Package inputenc Error: Unicode char �G (U+4A)
(inputenc)                not set up for use with LaTeX.

See the inputenc package documentation for explanation.
Type  H <return>  for immediate help.
 ...                                              
                                                  
l.24 ...[CvM�G{\etalchar{+}}14]{Cho2014LearningPR}
```

I can look into this later. Until we get this resolved, you might want to swap out the Ç for C.

2020-06-26 17:05 UTC, snikumbh commented
Simply use `{\c{C}}aglar G{\"{u}}l{\c{c}}ehre` from the bibtex entry at DBLP:

> @article{DBLP:journals/corr/ChoMGBSB14,
  author    = {Kyunghyun Cho and
               Bart van Merrienboer and
               {\c{C}}aglar G{\"{u}}l{\c{c}}ehre and
               Fethi Bougares and
               Holger Schwenk and
               Yoshua Bengio},
  title     = {Learning Phrase Representations using {RNN} Encoder-Decoder for Statistical
               Machine Translation},
  journal   = {CoRR},
  volume    = {abs/1406.1078},
  year      = {2014},
  url       = {http://arxiv.org/abs/1406.1078},
  archivePrefix = {arXiv},
  eprint    = {1406.1078},
  timestamp = {Mon, 13 Aug 2018 16:46:44 +0200},
  biburl    = {https://dblp.org/rec/journals/corr/ChoMGBSB14.bib},
  bibsource = {dblp computer science bibliography, https://dblp.org}
}

2020-06-26 19:27 UTC, Micky774 commented
Thank you both very much! All seems good now.

2020-06-28 05:55 UTC, Micky774 commented
@saketkc @snikumbh I believe all your comments have either been fully adopted/resolved or at least addressed and are being kept open pending your input. Let me know if there's anything else you'd like us to change!

2020-06-30 01:19 UTC, deniederhut commented
Hi @snikumbh and @saketkc ! Are you happy with the updates made to the paper?

2020-06-30 07:02 UTC, saketkc commented
I am happy with the changes @Micky774 and @deniederhut. The authors have addressed all my comments (including the title!) and I would like to applaud them for their efforts! I agree, the content and quality of paper has tremendously improved.

 I just have a couple of final recommendations:
 - I would suggest the authors consider open sourcing their work. A link to a repository would add a lot of value to the paper. (I understand this might not be possible)
- The figures seem to have been generated using matplotlib, in which case matplotlib needs a [citation](https://www.scipy.org/citing.html#matplotlib)

Congrats @Micky774, @snoiarao, @nssafir, @lizchenx and all the other authors - Great work!

2020-06-30 11:56 UTC, snikumbh commented on papers/zain/zain.rst
> +phenotypes with specific ciliopathies and genetic mutations :cite:`quinn2015automated`.
I see. Then, leaving that way is fine.

2020-06-30 12:03 UTC, snikumbh commented
Happy with all the updates! 
Congratulations to the authors/contributors!

2020-06-30 16:34 UTC, Micky774 commented
> I just have a couple of final recommendations:
> 
> * I would suggest the authors consider open sourcing their work. A link to a repository would add a lot of value to the paper. (I understand this might not be possible)
> * The figures seem to have been generated using matplotlib, in which case matplotlib needs a [citation](https://www.scipy.org/citing.html#matplotlib)

Both have been changed! Our public repository is hyperlinked at the end of our results section, along with a matplotlib acknowledgment and citation. Thanks for point that out!

2020-07-02 13:32 UTC, deniederhut commented
@Micky774 it looks like some of these references are missing DOIs. Could I ask you to add those in?

2020-07-02 19:31 UTC, Micky774 commented
Updated to add DOIs to those that have them

2020-07-04 01:57 UTC, mepa requested changes
Hi @Micky774, I'm a conference proceedings co-chair doing a final review of formatting. I noticed a few specific DOIs missing. Could you please add those, plus check for any other references where DOIs are missing and add them in?

2020-07-04 01:57 UTC, mepa commented on papers/zain/mybib.bib
> +@misc{Cho2014LearningPR,
Please add DOI 10.3115/v1/D14-1179

2020-07-04 01:57 UTC, mepa commented on papers/zain/mybib.bib
> +@conference{fu_extracting_2004,
Please add DOI https://citeseerx.ist.psu.edu/viewdoc/summary?doi=10.1.1.185.1179

2020-07-04 01:57 UTC, mepa commented on papers/zain/mybib.bib
> +@INPROCEEDINGS{LSTM1999,
https://doi.org/10.1162/089976600300015015

2020-07-04 02:04 UTC, Micky774 commented
Updated, thank you for pointing those out!

2020-07-04 02:09 UTC, Micky774 commented
As far as I know, some sources don't have DOIs, or at least I couldn't find any for them. Specifically some arXiv preprints and software citations such as Pytorch. I have very little experience with this so please let me know if they indeed also need/have DOIs. Thank you very much for your help.

2020-07-04 15:54 UTC, mepa commented on papers/zain/mybib.bib
> +@article{huang_densely_2018,
DOI: 10.1109/CVPR.2017.243

2020-07-04 15:55 UTC, mepa commented on papers/zain/mybib.bib
> +@article{resnet,
DOI: 10.1109/CVPR.2016.90

2020-07-04 15:58 UTC, mepa commented on papers/zain/mybib.bib
> +@article{jegou_one_2017,
DOI: 10.1109/CVPRW.2017.156

2020-07-04 16:00 UTC, mepa commented on papers/zain/mybib.bib
> +@article{introVAE,
DOI: 10.1561/2200000056

2020-07-04 16:06 UTC, mepa commented on papers/zain/mybib.bib
> +@article{Numpy2011,
DOI: 10.1109/MCSE.2011.37

2020-07-04 16:14 UTC, mepa commented
Hi, @Micky774. Thanks for updating  so quickly.

I also did not find a DOI for the PyTorch paper, but found a few more for some of the arXiv papers. I did this by copying/pasting the title to a web search and looking at the top few hits. @deniederhut may know if there's a better way?

In any case, after those changes it looks like this paper is good to go. Great job!

2020-07-04 16:17 UTC, mepa approved these changes

2020-07-04 16:18 UTC, Micky774 commented
@mepa Added in the new set of DOIs. Gotcha, I'll try to be more careful about looking through those sources and finding their associated DOIs. I appreciate all your help, and thank you very much!

2020-07-05 15:10 UTC, merged