Paper: Compyle: Python once, HPC anywhere!
scipy-conference/scipy_proceedings pull request #569
Opened 2020-05-30 04:26 UTC by prabhuramachandran

This is a draft of the paper and should be complete in a few more days.

2020-06-03 11:24 UTC, serge-sans-paille commented
Hi, I'm @serge-sans-paille, I'll be reviewing your paper, trying to provide valuable feedbacks!

2020-06-03 11:34 UTC, serge-sans-paille commented
Some early thoughts after a first scan of the paper: it seems important to mention that compyle introduces extra operators (`Map`, `Reduce`, `Scan`) and that it optimized a DSL based on the combination of these operators with elements wise operations. Maybe discuss the advantage and limitation of the approach.

This approach is *very* similar to this academic work:  https://ctnzr.io/papers/PPoPP-2011.pdf

2020-06-03 13:06 UTC, prabhuramachandran commented
@serge-sans-paille -- thank you!  We are still working on the paper and should wrap it up by this weekend.  Thanks for the reference!  Very useful indeed.

2020-06-07 15:49 UTC, prabhuramachandran commented
@serge-sans-paille -- Thanks for your patience! The paper should now be ready for review.  We've incorporated your suggested reference as well.

2020-06-18 01:50 UTC, govarguz commented
Dear @prabhuramachandran, dear @adityapb, 
compyle aims to port a python prototype code to a multi-core and GPU environment based on main parallel-mediated algorithms. As it is the case of `map`, `reduce` and `scan`. The focus of compyle is to effectively port a python proof-of-concept code to HPC-environments, which is a relevant functionality nowadays that the use of e.g. GPUs is more accessible than in the past. The example you have chosen is also relevant, although a 3D MD Lennard-Jones code would provide more insight and more realistic performance numbers and a comparison for the potential users-base. You could in principle compare it to some of the MD packages with a python mediated interface like, [E++](https://github.com/espressopp/espressopp) or [HooMD](https://github.com/glotzerlab/hoomd-blue).
In this direction, I would suggest to add two plots:
 
1. Strong scaling ( N particles remain fixed, number of processors increase form 8,16...till for example 128) comparison with only CPUs (here I am not sure if communications between nodes is also built, please remark this in the Ms.). 

2. Weak scaling (N number of particles vary and the number of processors remain fix ) comparison of both codes, as well, Compyle PoC and E++ (or HooMD).

The available plots are already quite illustrative comparing cython serial, CUDA and OpneCL. However, in my opinion adding points 1 and 2, would provide an enhanced discussion on how this programming paradigm compares to "a certain package" with a python interface.

2020-06-18 02:51 UTC, deniederhut commented
Hi @serge-sans-paille ! Have you had a chance to look through the paper since the most recent changes?

2020-06-18 07:46 UTC, serge-sans-paille requested changes

2020-06-18 07:46 UTC, serge-sans-paille commented on papers/compyle_pr_ab/compyle.rst
> +GPUs. There are also libraries like Pythran_ that transpile a subset of Python
Pythran is a compiler, not a library :-)

2020-06-18 07:46 UTC, serge-sans-paille commented on papers/compyle_pr_ab/compyle.rst
> +Of these, Numba has matured a great deal and is both easy to use and
Cython should be mentioned in this paragraph too. Especially as it provides some loop parallelism directives.

2020-06-18 07:46 UTC, serge-sans-paille commented on papers/compyle_pr_ab/compyle.rst
> +grew out of a project that pre-dates numba, the real reason that compyle
nit: consistent capitalization of compyle and numba.

2020-06-18 07:46 UTC, serge-sans-paille commented on papers/compyle_pr_ab/compyle.rst
> +then resorting to tools like numba to extract even more performance. Numba is
Maybe mention that going to numba / cython means devectorizing to make the looping explicit?

2020-06-18 07:46 UTC, serge-sans-paille commented on papers/compyle_pr_ab/compyle.rst
> +also a loss of the typical conveniences with high-level Python.
Maybe argument that low-level Python still has some pros versus a lower-level language here?

2020-06-18 07:46 UTC, serge-sans-paille commented on papers/compyle_pr_ab/compyle.rst
> +
based on these restrictions, it appears compyle is more of a DSL for computation kernels embed into a restricted subset of Python. This is very different from what the title advertised, maybe change the title to reflect that concept?

2020-06-18 07:46 UTC, serge-sans-paille commented on papers/compyle_pr_ab/compyle.rst
> +using Cython for the OpenCL and CUDA backends using the NNPS algorithm and
I have difficulties parsing this sentence :-)

2020-06-18 07:46 UTC, serge-sans-paille commented on papers/compyle_pr_ab/compyle.rst
> +scope of compyle at this point.
Explain why: there's no way compyle - generated code would run on the interpreter, etc

2020-06-19 02:23 UTC, deniederhut commented
Hey @prabhuramachandran  ! Thanks to some awesome behind the scenes work by @stargaser, we now have experimental support for publishing papers with ORCIDs. If you have one and would like to add it to your paper, it's as simple as adding an `:orcid:` tag under your name in the paper header. [You can see an example of how to do this in the `00_vanderwalt` example paper](https://raw.githubusercontent.com/scipy-conference/scipy_proceedings/2020/papers/00_vanderwalt/00_vanderwalt.rst). If you don't have one, no worries! You can still publish your paper as is.

2020-06-19 13:20 UTC, prabhuramachandran commented
Hi @deniederhut -- thanks for this!  We will add our ORCIDs as we address the reviewer comments this weekend.

2020-06-20 12:47 UTC, prabhuramachandran commented
Dear @govarguz,

Thank you for going over our submission and for your comments!  Our responses are inline below.

> Dear @prabhuramachandran, dear @adityapb,
> compyle aims to port a python prototype code to a multi-core and GPU environment based on main parallel-mediated algorithms. As it is the case of `map`, `reduce` and `scan`. The focus of compyle is to effectively port a python proof-of-concept code to HPC-environments, which is a relevant functionality nowadays that the use of e.g. GPUs is more accessible than in the past. The example you have chosen is also relevant, although a 3D MD Lennard-Jones code would provide more insight and more realistic performance numbers and a comparison for the potential users-base. You could in principle compare it to some of the MD packages with a python mediated interface like, [E++](https://github.com/espressopp/espressopp) or [HooMD](https://github.com/glotzerlab/hoomd-blue).

Thank you for the suggestion.  Our own work is not in the area of molecular dynamics.  Our only goal was to take a non-trivial problem and demonstrate how we are able to write from scratch a pure Python solution that immediately runs on CPUs and GPUs.  We also picked a 2D problem just to keep things simple and in line with the simple paper we cited. We do not have much experience with the two packages you have mentioned.  We will try to see if we are quickly able to get a working example.  One issue is that many of these packages are fairly complex so getting an apples to apples comparison is probably going to take a bit of time.  

> In this direction, I would suggest to add two plots:
> 
> 1. Strong scaling ( N particles remain fixed, number of processors increase form 8,16...till for example 128) comparison with only CPUs (here I am not sure if communications between nodes is also built, please remark this in the Ms.).

Our package by itself does not handle distributed computing at all.  We do have a separate package for this but that is not ready yet.  Given this, I am not sure how we can demonstrate scale up with 128 processors.

> 2. Weak scaling (N number of particles vary and the number of processors remain fix ) comparison of both codes, as well, Compyle PoC and E++ (or HooMD).
> 

We can try to do this.

> The available plots are already quite illustrative comparing cython serial, CUDA and OpneCL. However, in my opinion adding points 1 and 2, would provide an enhanced discussion on how this programming paradigm compares to "a certain package" with a python interface.

We agree that this would be a useful comparison and will try to at least address a simple comparison even if we are not able to do everything suggested.

2020-06-20 17:49 UTC, prabhuramachandran commented on papers/compyle_pr_ab/compyle.rst
> +GPUs. There are also libraries like Pythran_ that transpile a subset of Python
Sorry, fixed.

2020-06-20 17:49 UTC, prabhuramachandran commented on papers/compyle_pr_ab/compyle.rst
> +Of these, Numba has matured a great deal and is both easy to use and
Done, thanks.

2020-06-20 17:49 UTC, prabhuramachandran commented on papers/compyle_pr_ab/compyle.rst
> +grew out of a project that pre-dates numba, the real reason that compyle
I've tried to fix this over the entire manuscript.

2020-06-20 17:49 UTC, prabhuramachandran commented on papers/compyle_pr_ab/compyle.rst
> +then resorting to tools like numba to extract even more performance. Numba is
I have added a remark to note this.

2020-06-20 17:50 UTC, prabhuramachandran commented on papers/compyle_pr_ab/compyle.rst
> +also a loss of the typical conveniences with high-level Python.
I have tried to add a little text to elaborate your comment in the text.

2020-06-20 17:52 UTC, prabhuramachandran commented on papers/compyle_pr_ab/compyle.rst
> +
I do agree I am not quite sure I should call it a DSL since really it is strictly a Python subset and all the code is valid Python.  I agree that the title is bombastic and have changed it to "Compyle: a Pythonic DSL for parallel computing".  I hope that works.

2020-06-20 17:52 UTC, prabhuramachandran commented on papers/compyle_pr_ab/compyle.rst
> +using Cython for the OpenCL and CUDA backends using the NNPS algorithm and
Hopefully I've fixed that.

2020-06-20 17:52 UTC, prabhuramachandran commented on papers/compyle_pr_ab/compyle.rst
> +scope of compyle at this point.
I have attempted to but am not sure if what I've done is good enough.

2020-06-20 17:53 UTC, prabhuramachandran commented
@serge-sans-paille -- thanks for your comments!  I have tried to address all of them, I have left comments and not resolved the comments (I'm not sure if that is what I am supposed to do).  Please let me know if it looks better now.  Thanks.

2020-06-20 22:55 UTC, deniederhut commented
>  I have left comments and not resolved the comments (I'm not sure if that is what I am supposed to do)

🤷‍♀️ different reviewers have different preferences, so this is not something we have prescribed a rule for.

2020-06-21 22:53 UTC, grlee77 commented on papers/compyle_pr_ab/compyle.rst
> +requires to in order to write parallel programs. These are the element-wise
seem like a typo is making this sentence hard to read
maybe change "requires to in order to write" to "requires when writing" ?

2020-06-21 23:02 UTC, grlee77 commented on papers/compyle_pr_ab/compyle.rst
> +- Generates either Cython or ANSI C code depending on the backend and this
I think this Cython, or CUDA/OpenCL C source code vs. a more opaque intermediate representation is attractive when things don't work as expected and one may want to manually check the generated code. Also, most scientific programmers are much more likely to be familiar with C than LLVM IR or assembly code.

I didn't see anywhere in the manuscript or online docs where it is stated how the user can view the transpiled C or Cython code? I tried some manual tinkering with the Elementwise examples provided and found that one can access a `.tp.get_code()` attribute. I would make a brief mention in the paper that there is a method by which the user can retrieve the transpiled code and document the public API for this in the online docs.

2020-06-22 05:20 UTC, serge-sans-paille commented on papers/compyle_pr_ab/compyle.rst
> +
Great! Being a strict subset of Python make it an *eDSL*, an *Embedded DSL*

2020-06-22 07:49 UTC, prabhuramachandran commented on papers/compyle_pr_ab/compyle.rst
> +
Well, to be honest, I do not like the word DSL as it seems like jargon.  The word is itself imprecise.  So I find that the word doesn't really improve understanding or make anything clearer.  Is NumPy a DSL for scientific computing?  Does knowing that it is a DSL help anyone who may want to use it?  I am not so sure.   Do you think this works: "Compyle: a Python package for parallel computing"?  I agree that the original title is not great but am not entirely happy with throwing in the word DSL or eDSL.

2020-06-22 07:51 UTC, prabhuramachandran commented on papers/compyle_pr_ab/compyle.rst
> +- Generates either Cython or ANSI C code depending on the backend and this
Thanks for pointing this out.  This is something we have wanted to improve but it has fallen by the wayside.  The complete Cython files are written inside `~/.compyle/source` but not the GPU code.  We are wondering if we should have an environment variable to help do this so it prints it out?  Could you let us know of your thoughts on this?  A method is surely something we should expose cleanly and document but anything else you would find useful?

2020-06-22 13:39 UTC, grlee77 commented on papers/compyle_pr_ab/compyle.rst
> +- Generates either Cython or ANSI C code depending on the backend and this
CuPy has [some environment variables](https://docs-cupy.chainer.org/en/stable/reference/environment.html#environment-variables) related to this type of thing which I have found useful:
- `CUPY_DUMP_CUDA_SOURCE_ON_ERROR` causes the source to be printed to the terminal if there is an error during compilation.
- `CUPY_CACHE_SAVE_CUDA_SOURCE` causes the `.cu` source to be cached in addition to the `.cubin` files that are always cached.

2020-06-22 14:03 UTC, grlee77 commented
Also, can you double-check figure 3? I find it surprising that the CUDA and OpenCL results are aligned so exactly. When I ran `examples/molecular_dynamics/peformance_comparison.py` locally, I got:

![linear_speedup_opencl_cuda_cython](https://user-images.githubusercontent.com/6528957/85296246-1a125500-b46f-11ea-8883-cf4a77dcb88a.png)

i.e. comparable, but not identical performance

2020-06-23 21:32 UTC, adityapb commented
> Also, can you double-check figure 3? I find it surprising that the CUDA and OpenCL results are aligned so exactly. When I ran `examples/molecular_dynamics/peformance_comparison.py` locally, I got:
> 
> ![linear_speedup_opencl_cuda_cython](https://user-images.githubusercontent.com/6528957/85296246-1a125500-b46f-11ea-8883-cf4a77dcb88a.png)
> 
> i.e. comparable, but not identical performance

Hi @grlee77, the plot you have generated is using the `O(N)` algorithm. Figure 3 shows the speedup using the simple `O(N^2)` implementation. For getting the result corresponding to figure 3, you can run the following:

```
python performance_comparison.py --nnps simple
```

I have double checked the plot generated using the above command and I am getting the same result.

The `O(N)` comparison is showed in figure 4 which is quite similar to what you have generated. I think I'll perhaps add more details of how each of the results can be reproduced in the README of the molecular_dynamics example.

2020-06-27 12:27 UTC, prabhuramachandran commented
Dear @govarguz,

> 1. Strong scaling ( N particles remain fixed, number of processors increase form 8,16...till for example 128) comparison with only CPUs (here I am not sure if communications between nodes is also built, please remark this in the Ms.).
> 2. Weak scaling (N number of particles vary and the number of processors remain fix ) comparison of both codes, as well, Compyle PoC and E++ (or HooMD).

Thanks for your suggestions, as I had mentioned earlier, doing 1 is a bit difficult currently. @adityapb has implemented a 3D version of the code and has compared the results of HooMD and our code and added the plots for this.  Our code is about 2x faster than HooMD on a GPU.  Since we weren't sure if we had made a mistake he has also verified that the results are indeed similar for a smaller problem as well.  All of these have been added to the manuscript.  We hope this addresses the main concern of a reasonable and fair comparison.  The paper has exceeded 8 pages right now so if this is a problem we can try to compress it a bit.

2020-06-27 12:39 UTC, prabhuramachandran commented on papers/compyle_pr_ab/compyle.rst
> +
I've changed it to "Compyle: a Python package for parallel computing" and mention eDSL in the abstract.  I hope this is OK.

2020-06-27 12:41 UTC, prabhuramachandran commented on papers/compyle_pr_ab/compyle.rst
> +- Generates either Cython or ANSI C code depending on the backend and this
Thanks for the suggestion!  That is very useful.  We will address some of these in our next release.  Hopefully we will be able to cut a new release before SciPy starts.

2020-06-27 12:42 UTC, prabhuramachandran commented on papers/compyle_pr_ab/compyle.rst
> +- Generates either Cython or ANSI C code depending on the backend and this
Also you could do `.tp.source` to get the source but it isn't as clean as I would like.  We will address this as well in the next release (and update the docs as well).

2020-06-27 12:42 UTC, prabhuramachandran commented
@deniederhut -- I believe we've addressed the major issues and suggestions raised thus far.

2020-06-27 12:43 UTC, govarguz commented
Dear @prabhuramachandran, @adityapb,

good to hear about the reached speed-up! I am going through the new _Ms._ version in this weekend and submit my latest reviews by tomorrow. 
Write to you soon!
Horacio.

2020-06-27 12:46 UTC, prabhuramachandran commented
@govarguz -- Thank you!  BTW, I think a head-to-head comparison is never fair, so we are just happy that we are in the same ballpark (being faster is nice).  Our intention is not to claim anything special -- just that it is possible to get good performance.  We hope the text does not suggest that we are taking a potshot at HooMD.

2020-06-27 12:47 UTC, govarguz commented
Agreed!

2020-06-28 23:27 UTC, govarguz approved these changes

2020-06-28 23:27 UTC, govarguz commented on papers/compyle_pr_ab/compyle.rst
> +   Cython, and OpenCL and CUDA for GPU devices. Users write low-level code in
here the term "low-level" may cause confusion, why note single core or "not parallelized"

2020-06-28 23:27 UTC, govarguz commented on papers/compyle_pr_ab/compyle.rst
> +   CPUs and GPGPUs allowing simulations with millions of particles. A 3D
A 3D MD code , instead of just "3D"  perhaps MD can be defined a bit upper when molecular dynamics appears first in the text.

2020-06-28 23:27 UTC, govarguz commented on papers/compyle_pr_ab/compyle.rst
> +implementation to be about 2x faster than HooMD. Figures :ref:`hoomd-pe` and
I would move both plots, KE and PE to an appendix section within the article.

2020-06-29 06:32 UTC, grlee77 commented on papers/compyle_pr_ab/compyle.rst
> +implementation to be about 2x faster than HooMD. Figures :ref:`hoomd-pe` and
Yes, although it is good to know that the results are similar, I don't think the energy levels are important to the main point of the paper.

2020-06-29 06:36 UTC, grlee77 commented
> Hi @grlee77, the plot you have generated is using the O(N) algorithm. Figure 3 shows the speedup using the simple O(N^2) > implementation. For getting the result corresponding to figure 3, you can run the following:
> 
> python performance_comparison.py --nnps simple
> 
> I have double checked the plot generated using the above command and I am getting the same result.

Okay, I ran that one and I got curves that were more similar, but still not exactly overlapping. I suppose it is probably just some difference in the hardware used. I suppose if they are so closely overlapping you could change the "x" marker on the blue line to an "o" or some other symbol that would be more visible in the overlapped plot, but it is not a big deal either way.

2020-06-29 06:54 UTC, grlee77 commented
One other related library that may be worth mentioning is [Reikna](http://reikna.publicfields.net/en/latest/). I have never looked at it in detail, but my impression is that it also allows GPGPU programming via templated code that gets translated to either PyOpenCL or PyCUDA kernels. In that respect it has some similarity to the current project, but it does not have any equivalent of Compyle's Cython code generation capability. 

Overall my impression of the paper is favorable. I think the writing is good and the library seems to fill a niche in being able to transpile common code to Cython, OpenCL or CUDA. I am not aware of another tool for that. There are limitations to what can be done, but I think the authors did a good job of pointing those out and making clear what the tool can and cannot do.

I did try running the provided examples and the code worked as advertised.

2020-06-30 01:22 UTC, deniederhut commented
Sweet! Do I understand correctly that there are just a few suggested changes left?

2020-06-30 03:36 UTC, prabhuramachandran commented
@deniederhut -- yes, there are a few suggestions that we will get to in a day or two, does that work?

2020-06-30 03:37 UTC, prabhuramachandran commented on papers/compyle_pr_ab/compyle.rst
> +implementation to be about 2x faster than HooMD. Figures :ref:`hoomd-pe` and
Since these are tangential to the paper anyway, can we skip these two plots and just mention that the values are close in the text?

2020-06-30 13:59 UTC, deniederhut commented
The open review period ends in two days. We'll probably want to make those changes quickly so your reviewers have time to take a final look at the paper.

2020-06-30 15:01 UTC, grlee77 commented on papers/compyle_pr_ab/compyle.rst
> +implementation to be about 2x faster than HooMD. Figures :ref:`hoomd-pe` and
That sound fine to me, especially given that the example script to recreate the result is now in the repository.

2020-07-01 08:25 UTC, prabhuramachandran commented on papers/compyle_pr_ab/compyle.rst
> +requires to in order to write parallel programs. These are the element-wise
This is now fixed.

2020-07-01 08:27 UTC, prabhuramachandran commented on papers/compyle_pr_ab/compyle.rst
> +   Cython, and OpenCL and CUDA for GPU devices. Users write low-level code in
I've made this more precise to "Users write code in a restricted subset of Python that is automatically ...".  I believe this should clarify it.

2020-07-01 08:29 UTC, prabhuramachandran commented on papers/compyle_pr_ab/compyle.rst
> +   CPUs and GPGPUs allowing simulations with millions of particles. A 3D
Done, thanks.

2020-07-01 08:29 UTC, prabhuramachandran commented on papers/compyle_pr_ab/compyle.rst
> +implementation to be about 2x faster than HooMD. Figures :ref:`hoomd-pe` and
Yes, the energy plot code was not there earlier and we just merged a PR that does this.

2020-07-01 08:56 UTC, prabhuramachandran commented
Thanks all, I have pushed the last set of changes which address the remaining comments and also cites Reikna.  We also added a link to the colab notebook if readers wish to try the examples with a GPU. We also added a small acknowledgments section at the end which I felt was necessary.  Thank you all for your patience and feedback!
@deniederhut -- I think at this point the manuscript is mostly done.

2020-07-01 11:49 UTC, govarguz commented
The Ms. has interesting points and it is applicable. However, I think there might be a tiny addition to make, while keeping the example of MD. Compyle, can be a serious tool for the MD-method development community. In particular for the proof-of-concept methods that may try to be easily parallelizable. Hence, I strongly suggest to add a line in the _future work_ or _conclusions_ section which is citing a couple of article in this regard. Such as: DOI: 10.1016/j.cpc.2018.12.017 and  https://doi.org/10.1039/C4SM02344G. And I agree the Ms. is mostly done!

2020-07-01 12:24 UTC, prabhuramachandran commented
@govarguz -- I am not sure I would be comfortable doing that as I am not an expert on MD. The point of the MD example was just to pick a non-trivial example that required a scan.  We could have used a more fluid-centric example which is up my alley but ends up making the code more complex.  The intent was not to suggest anything specific be done in the area of MD-method development (maybe MD folks have enough tools and don't need another one, I do not know).  I do know that there are many many good MD codes that are available (I'm told everyone has their favorite).  So it would be inappropriate for us to suggest anything to the community without being a part of it. In this particular case, I would essentially be paraphrasing your words and your experience, which I am not sure we should do. We are definitely very happy if Compyle proves useful for MD-method development but what we are getting at is that Compyle is potentially useful to many other folks too.   I am not sure if I am communicating this clearly here.

2020-07-01 13:00 UTC, govarguz commented
@prabhuramachandran , sure, I see your point. And exchanging final ideas is the aim of this review.
 For sure compyle can be useful for many folks. However, my suggestions is exactly in those lines to name a few of those communities. As for example, the MD-method-development (in general as you picked the MD example!) by showing some of the perspective methods developments (in a proof-of-concept fashion). In addition, to my eyes scientific pythonic tools may reach a lot of communities are open-source.
I don't want you to rephrase my text, but cite a community that can potentially profit of Compyle, give it a little visibility, through a couple of citations.

2020-07-01 13:29 UTC, prabhuramachandran commented
OK, that makes sense.  In any case, it helps to know that this may be useful in the MD domain (am happy to take your word for it).  I've added the reference and made a few edits to have everything fit in 8 pages.  I hope that works.

2020-07-02 13:34 UTC, deniederhut commented on papers/compyle_pr_ab/references.bib
> +  author    = {Prabhu Ramachandran},
@prabhuramachandran could I ask you to add the DOI for this reference? http://conference.scipy.org/proceedings/scipy2016/prabhu_ramachandran_pysph.html

2020-07-02 18:01 UTC, prabhuramachandran commented on papers/compyle_pr_ab/references.bib
> +  author    = {Prabhu Ramachandran},
Thanks for catching that!  I had an older reference entry.  This is now fixed.

2020-07-02 22:20 UTC, cbcunc approved these changes
Passes final proceedings committee walk-through.

2020-07-03 14:07 UTC, prabhuramachandran commented
I am just pushing a change for some grammatical errors I found.

2020-07-05 15:12 UTC, merged