Paper: Spectral Analysis of Mitochondrial Dynamics: A Graph-Theoretic Approach to Understanding Subcellular Pathology
scipy-conference/scipy_proceedings pull request #571
Opened 2020-05-30 06:26 UTC by Marcdh3

If you are creating this PR in order to submit a draft of your paper,
see http://procbuild.scipy.org/ for logs generated by the build
process.

See the [project readme](https://github.com/scipy-conference/scipy_proceedings#build-your-paper)
for more information.

2020-06-17 18:02 UTC, mengksun commented
Hi Marcus & Meekil,

I have been assigned by the Scipy Committee to review your paper in the next few days. :) I find it really interesting & look forward to working with you!

Cheers,
Kay

2020-06-19 02:24 UTC, deniederhut commented
Hey @Marcdh3  ! Thanks to some awesome behind the scenes work by @stargaser, we now have experimental support for publishing papers with ORCIDs. If you have one and would like to add it to your paper, it's as simple as adding an `:orcid:` tag under your name in the paper header. [You can see an example of how to do this in the `00_vanderwalt` example paper](https://raw.githubusercontent.com/scipy-conference/scipy_proceedings/2020/papers/00_vanderwalt/00_vanderwalt.rst). If you don't have one, no worries! You can still publish your paper as is.

2020-06-19 11:04 UTC, josephmje reviewed
Hi @Marcdh3 . I am one of the reviewers of this paper.

I think this is an interesting paper that is appropriate for publication in SciPy 2020's proceedings. The background literature review was great and really helped me, someone not in the field, understand the paper's focus. I made a few comments in my initial pass, some that might improve clarity and others were just minor grammar/style corrections. In general, I found some of the sentences were too long and required re-reading to make sure I understood the point. I am happy to clarify these in a second pass

2020-06-19 11:04 UTC, josephmje commented on papers/marcus_hill/paper.rst
> +Modeling organellar morphologies can provide valuable insight into the health of human cells. Structural changes inside the cell are useful indicators of a cell’s response to viral or bacterial invad
> approach with the results of exhaustive **graph-theoretic** analyses over

2020-06-19 11:04 UTC, josephmje commented on papers/marcus_hill/paper.rst
> +Morphological perturbations of organellar structures inside cells are useful for characterizing infection patterns and, ultimately, developing therapies. In particular, tuberculosis, an infectious di
> resistance to **current** antibacterial treatment regimens.

2020-06-19 11:04 UTC, josephmje commented on papers/marcus_hill/paper.rst
> +Assessment of mitochondrial dynamics via time-lapse microscopy has been studied from various scientific perspectives, and the commonality between the most widely-used approaches is the usage of fluor
This is a really long sentence that I think needs to be simplified

> Assessment of mitochondrial dynamics via time-lapse microscopy has been studied from various scientific perspectives, and the commonality between the most widely-used approaches is the usage of fluorescent confocal imagery to capture the spatial changes in mitochondrial structures as they undergo either hyperfusion or fragmentation as the result of the cell being exposed to specific drug treatments.

2020-06-19 11:04 UTC, josephmje commented on papers/marcus_hill/paper.rst
> +Assessment of mitochondrial dynamics via time-lapse microscopy has been studied from various scientific perspectives, and the commonality between the most widely-used approaches is the usage of fluor
Here, are hyperfusion and fragmentation the morphologically significant events that are being discussed?

> Song et. al. :cite:`song08` proposed a methodology to analyze mitochondrial dynamics by quantifying the number of mitochondria present in the cell, and measuring their lengths after morphologically significant events to confirm that hyperfusion or fragmentation occurred.

2020-06-19 11:04 UTC, josephmje commented on papers/marcus_hill/paper.rst
> +Assessment of mitochondrial dynamics via time-lapse microscopy has been studied from various scientific perspectives, and the commonality between the most widely-used approaches is the usage of fluor
> FRAP approaches can be jeopardized by the motility of mitochondria and its environment; unexpected movement from mitochondria, or even the entire cell, can disrupt a FRAP **analysis,** requiring the sample being assessed to be discarded.

2020-06-19 11:04 UTC, josephmje commented on papers/marcus_hill/paper.rst
> +   Anomalous frames from an LLO video that corresponds to time points indicated by the temporal anomaly detection technique. These frames correspond with the signal plot in figure 1.
It might help here to caption each figure with the frame numbers.

2020-06-19 11:04 UTC, josephmje commented on papers/marcus_hill/paper.rst
> +   Image on the left shows the initial spatial location of the bounding box, and the image on the right shows the spatial location andsize of the bounding box on the final frame of an mdivi video. Th
> **and size** of the bounding box on the final frame of an mdivi video. This

2020-06-19 11:04 UTC, josephmje commented on papers/marcus_hill/paper.rst
> +Assessment of mitochondrial dynamics via time-lapse microscopy has been studied from various scientific perspectives, and the commonality between the most widely-used approaches is the usage of fluor
Here and throughout, there doesn't need to be a period after et. **et al.** instead of **et. al.**

2020-06-19 11:04 UTC, josephmje commented on papers/marcus_hill/paper.rst
> +Modeling mitochondria is no trivial task; these organelles are amorphous, spatially diffuse structures, and their lack of rigidity renders traditional shape-based, parametric modeling techniques inef
It might be helpful here or earlier on to quickly explain what's meant by the term "dynamics". Feel free to ignore if its a widely used term in the field.

2020-06-20 17:08 UTC, mattb112885 commented
Hello Marcus & Meekail, I am also reviewing this paper and look forward to working with you!

I agree with @josephmje that this is an interesting paper and is appropriate for publication. I will be leaving specific comments below.

2020-06-20 17:12 UTC, mattb112885 commented on papers/marcus_hill/paper.rst
> +OrNet utilizes a probabilistic approach, involving Gaussian mixture models (GMMs), to construct mitochondrial cluster graphs. :cite:`durden18, fazli20` GMMs were utilized to determine spatial regions
What does it mean for a cluster to be normally distributed -- what metric is normally distributed? The distance between the individual mitochondria?

2020-06-20 17:24 UTC, mattb112885 commented on papers/marcus_hill/paper.rst
> +We first evaluated the temporal anomaly detection methodology by plotting the eigenvalue spectrum and outlier signal for each cell. Next, we evaluated the video frames that corresponded with each ano
morpholgoy --> morphology

To be clear -- are the images you are showing in the figure showing multiple mitochondria in a single cell? Or are they a single mitochondria? What is the level of magnification/size scale of the images?

2020-06-20 17:26 UTC, mattb112885 commented on papers/marcus_hill/paper.rst
> +Our spatial anomaly detection methodology was evaluated by inspecting the regions highlighted by the bounding boxes in each cell type. The effectiveness of this approach was demonstrated through asse
Minor nitpick: "LLO" is capitalized in some places and not in others.

2020-06-20 17:28 UTC, mattb112885 commented on papers/marcus_hill/paper.rst
> +Both the temporal and spatial anomaly detection methodologies have proven effective in quantitatively characterizing mitochondrial dynamics, however, the extent of their effectiveness is largely depe
Are the default values in the code above what you used in the examples in this paper? You may want to make that explicit.

2020-06-20 17:30 UTC, mattb112885 commented on papers/marcus_hill/paper.rst
> +Morphological perturbations of organellar structures inside cells are useful for characterizing infection patterns and, ultimately, developing therapies. In particular, tuberculosis, an infectious di
_Mycobacterium tuberulosis_ should be italicized.

2020-06-20 17:32 UTC, mattb112885 commented on papers/marcus_hill/paper.rst
> +By modeling the spatiotemporal relationships of mitochondria as a dynamic social network, the graph states could be represented as laplacian matrices. A laplacian matrix is a useful representation of
laplacian --> Laplacian

2020-06-20 17:39 UTC, mattb112885 commented on papers/marcus_hill/paper.rst
> +Unexpectedly, we noticed anomalous behavior was indicated in a subset of our control videos. This was not anticipated because the control cells were not exposed to any stimuli, and their mitochondria
Do you think it will be possible in the future to develop a method to separate morphological changes from changes due to movement?

2020-06-20 17:39 UTC, mattb112885 commented on papers/marcus_hill/paper.rst
> +Our spatial anomaly detection methodology was evaluated by inspecting the regions highlighted by the bounding boxes in each cell type. The effectiveness of this approach was demonstrated through asse
Can you show an example of the mdivi anomolous frames as well?

2020-06-20 17:41 UTC, mattb112885 commented on papers/marcus_hill/paper.rst
> +The morphology of mitochondria is perturbed in distinct ways by the presence of bacterial or viral infections in the cell, and modeling these structural changes can aid in understanding both the infe
_Mycobacterium tuberculosis_ should be italicized here, too.

2020-06-20 17:43 UTC, mattb112885 commented on papers/marcus_hill/paper.rst
> +The morphology of mitochondria is perturbed in distinct ways by the presence of bacterial or viral infections in the cell, and modeling these structural changes can aid in understanding both the infe
Could this also be useful to apply to other organelles, or specific tagged proteins in a cell?

2020-06-20 17:44 UTC, mattb112885 commented on papers/marcus_hill/paper.rst
> +Anomalous morphological behavior can be defined as spatial regions shifting suddenly, or major structural changes taking place in the underlying social network: edges being dropped or formed, nodes a
Do the clusters identified in a GMM overlap?

2020-06-20 17:47 UTC, mattb112885 requested changes
Thanks again for the submission, it was generally a very interesting approach! Here are my specific comments.

2020-06-21 16:09 UTC, mengksun commented on papers/marcus_hill/paper.rst
> +Morphological perturbations of organellar structures inside cells are useful for characterizing infection patterns and, ultimately, developing therapies. In particular, tuberculosis, an infectious di
This part is very interesting and laid out the reason why the work is importatn. To make it more clear to a wide audience, "genetic screens"- can you make it clear whether the changes are permanent in the host who has had infection history or is the change temporary in mitochondira of invaded cells and only detectable when infection is active? Surely, this would impact the screen process and how cells are screened?

2020-06-21 16:11 UTC, mengksun commented on papers/marcus_hill/paper.rst
> +Modeling mitochondria is no trivial task; these organelles are amorphous, spatially diffuse structures, and their lack of rigidity renders traditional shape-based, parametric modeling techniques inef
Does "dynamics" mean change over time? Mobility over time?

2020-06-21 16:26 UTC, mengksun requested changes
Overall the paper is very clear on what the issue in current field of TB cell anomaly detection is and why the new technique is novel and unique and able to solve the automatic image detection problem with cloudy/hazy images of mitochondria movement. However I felt I did not fully understand the image examples and a stronger case can definitely be made by including a video showing control vs. test (anomaly/infected cells) and some explanation for audience/reviewers to better judget the effectiveness of the technique.

2020-06-21 16:26 UTC, mengksun commented on papers/marcus_hill/paper.rst
> +Eigendecomposition of a social network results in a number of eigenvalue vectors and eigenvector matrices that correspond to the number of graph states that comprise the network. Because these vector
"then it is considered an outlier"-> why do you need to remove outliers? Is the normal distribution assumption valid? what caused the outliers and how often do you see them in your analysis? I cannot figure this our from your results/discussion section and it seems that the setting a good threshold is key to the success of the analysis, more like an art and dependent on the analyst? How did you select those?

2020-06-21 16:26 UTC, mengksun commented on papers/marcus_hill/paper.rst
> +
Perhaps worth adding an introduction about the code before jumping straight into the code (felt a bit abrupt to the reader).. something like "below is our Python code implementation of the algorithm Temporal Anomaly Detection". Same can be applied to other sections right before the code...

2020-06-21 16:26 UTC, mengksun commented on papers/marcus_hill/paper.rst
> +   Image on the left shows the initial spatial location of the bounding box, and the image on the right shows the spatial location andsize of the bounding box on the final frame of an mdivi video. Th
I am not sure what I am looking at. Is there a scale bar in the microscopy image? what is the size of mitochondria? Am I looking at a cluster of thousands of mitrocondrias and each red dot is a mitochondria?

2020-06-22 15:37 UTC, Marcdh3 commented
Thank you everyone for taking the time to review this paper; we definitely appreciate all of the detailed feedback! We will be working on addressing every comment as quickly as possible.

2020-06-29 15:30 UTC, Marcdh3 commented on papers/marcus_hill/paper.rst
> +Modeling organellar morphologies can provide valuable insight into the health of human cells. Structural changes inside the cell are useful indicators of a cell’s response to viral or bacterial invad
It is now corrected.

2020-06-29 15:32 UTC, Marcdh3 commented on papers/marcus_hill/paper.rst
> +Morphological perturbations of organellar structures inside cells are useful for characterizing infection patterns and, ultimately, developing therapies. In particular, tuberculosis, an infectious di
Good catch. Fixed.

2020-06-29 15:33 UTC, Marcdh3 commented on papers/marcus_hill/paper.rst
> +Assessment of mitochondrial dynamics via time-lapse microscopy has been studied from various scientific perspectives, and the commonality between the most widely-used approaches is the usage of fluor
Yes, the hyperfusion and fragmentation are the events being discussed. We've updated the introduction to better explain the dynamics involved.

2020-06-29 15:34 UTC, Marcdh3 commented on papers/marcus_hill/paper.rst
> +   Anomalous frames from an LLO video that corresponds to time points indicated by the temporal anomaly detection technique. These frames correspond with the signal plot in figure 1.
Frame numbers are now added.

2020-06-29 15:34 UTC, Marcdh3 commented on papers/marcus_hill/paper.rst
> +   Image on the left shows the initial spatial location of the bounding box, and the image on the right shows the spatial location andsize of the bounding box on the final frame of an mdivi video. Th
Thanks for catching this. It has now been updated.

2020-06-29 15:34 UTC, Marcdh3 commented on papers/marcus_hill/paper.rst
> +Assessment of mitochondrial dynamics via time-lapse microscopy has been studied from various scientific perspectives, and the commonality between the most widely-used approaches is the usage of fluor
All of these are now changed.

2020-06-29 15:36 UTC, Marcdh3 commented on papers/marcus_hill/paper.rst
> +OrNet utilizes a probabilistic approach, involving Gaussian mixture models (GMMs), to construct mitochondrial cluster graphs. :cite:`durden18, fazli20` GMMs were utilized to determine spatial regions
We were trying to convey that the spatial locations of mitochondrial clusters are normally distributed throughout the cell. We've updated the paper to make this more clear in a few places.

2020-06-29 15:37 UTC, Marcdh3 commented on papers/marcus_hill/paper.rst
> +Our spatial anomaly detection methodology was evaluated by inspecting the regions highlighted by the bounding boxes in each cell type. The effectiveness of this approach was demonstrated through asse
Fixed.

2020-06-29 15:38 UTC, Marcdh3 commented on papers/marcus_hill/paper.rst
> +Both the temporal and spatial anomaly detection methodologies have proven effective in quantitatively characterizing mitochondrial dynamics, however, the extent of their effectiveness is largely depe
We've now made explicit mentions of the parameter values used in our experiments.

2020-06-29 15:38 UTC, Marcdh3 commented on papers/marcus_hill/paper.rst
> +By modeling the spatiotemporal relationships of mitochondria as a dynamic social network, the graph states could be represented as laplacian matrices. A laplacian matrix is a useful representation of
Fixed.

2020-06-29 15:38 UTC, Marcdh3 commented on papers/marcus_hill/paper.rst
> +The morphology of mitochondria is perturbed in distinct ways by the presence of bacterial or viral infections in the cell, and modeling these structural changes can aid in understanding both the infe
Fixed.

2020-06-29 15:40 UTC, Marcdh3 commented on papers/marcus_hill/paper.rst
> +Assessment of mitochondrial dynamics via time-lapse microscopy has been studied from various scientific perspectives, and the commonality between the most widely-used approaches is the usage of fluor
We've made some changes to this section to add clarity to the paper.

2020-06-29 15:40 UTC, Marcdh3 commented on papers/marcus_hill/paper.rst
> +Assessment of mitochondrial dynamics via time-lapse microscopy has been studied from various scientific perspectives, and the commonality between the most widely-used approaches is the usage of fluor
Fixed.

2020-06-29 15:41 UTC, Marcdh3 commented on papers/marcus_hill/paper.rst
> +Modeling mitochondria is no trivial task; these organelles are amorphous, spatially diffuse structures, and their lack of rigidity renders traditional shape-based, parametric modeling techniques inef
We have added more information to clarify what dynamics mean in this context.

2020-06-29 15:43 UTC, Marcdh3 commented on papers/marcus_hill/paper.rst
> +We first evaluated the temporal anomaly detection methodology by plotting the eigenvalue spectrum and outlier signal for each cell. Next, we evaluated the video frames that corresponded with each ano
Fixed the typo. Yes, each image depicts a single cell with a large number of mitochondria present. Each "dot" is a single mitochondrion. We've added more information regarding the scale of the objects shown in the imagery.

2020-06-29 15:45 UTC, Marcdh3 commented on papers/marcus_hill/paper.rst
> +Anomalous morphological behavior can be defined as spatial regions shifting suddenly, or major structural changes taking place in the underlying social network: edges being dropped or formed, nodes a
Yes, some cluster regions denoted by the GMM do overlap. We have now included more information to make this clear to the audience.

2020-06-29 15:46 UTC, Marcdh3 commented on papers/marcus_hill/paper.rst
> +Morphological perturbations of organellar structures inside cells are useful for characterizing infection patterns and, ultimately, developing therapies. In particular, tuberculosis, an infectious di
We've added a statement to make it clear these are more permanent structural changes, and not temporary.

2020-06-29 15:47 UTC, Marcdh3 commented on papers/marcus_hill/paper.rst
> +Modeling mitochondria is no trivial task; these organelles are amorphous, spatially diffuse structures, and their lack of rigidity renders traditional shape-based, parametric modeling techniques inef
It refers to the shape of the mitochondria. We've added more information to clarify what dynamics mean in the context of this paper.

2020-06-29 16:09 UTC, Marcdh3 commented on papers/marcus_hill/paper.rst
> +
Added some statements to introduce the code.

2020-06-29 16:11 UTC, Marcdh3 commented on papers/marcus_hill/paper.rst
> +   Image on the left shows the initial spatial location of the bounding box, and the image on the right shows the spatial location andsize of the bounding box on the final frame of an mdivi video. Th
Each image depicts a single cell, and each red "dot" depicts and individual mitochondrion. We've added more information to the data section of the paper regarding the scale of the mitochondria.

2020-06-29 16:45 UTC, Marcdh3 commented on papers/marcus_hill/paper.rst
> +The morphology of mitochondria is perturbed in distinct ways by the presence of bacterial or viral infections in the cell, and modeling these structural changes can aid in understanding both the infe
Yes, that is an overall goal of the OrNet (Organellar Networks) project, and was discussed in more detail in a prior [work](https://conference.scipy.org/proceedings/scipy2018/pdfs/Andrew_Durden.pdf).

2020-06-29 16:48 UTC, Marcdh3 commented on papers/marcus_hill/paper.rst
> +Eigendecomposition of a social network results in a number of eigenvalue vectors and eigenvector matrices that correspond to the number of graph states that comprise the network. Because these vector
Our approach does not remove the outliers, but actually record them as time points where anomalous morphological activity is occurring (i.e. a fission or fusion event). The normal distribution assumption is valid and was explored in detail in a [prior work](https://conference.scipy.org/proceedings/scipy2018/pdfs/Andrew_Durden.pdf), so we've added more references to it. Also, we have added more information regarding ways to select good parameters in the discussion section.

2020-06-29 16:52 UTC, Marcdh3 commented on papers/marcus_hill/paper.rst
> +Unexpectedly, we noticed anomalous behavior was indicated in a subset of our control videos. This was not anticipated because the control cells were not exposed to any stimuli, and their mitochondria
Potentially with a different methodology, but not with our current temporal anomaly detection technique.

2020-06-29 16:57 UTC, Marcdh3 commented
As of now, I believe all of the changes requested have been implemented.

2020-06-30 01:25 UTC, deniederhut commented
Excellent! @josephmje @mengksun and @mattb112885 are you happy with the updates to the paper?

2020-06-30 14:04 UTC, deniederhut commented
Hi everyone! Friendly reminder that the open review period ends 2 July -- the committee will be making final decisions on each paper this Friday.

2020-07-01 15:19 UTC, josephmje reviewed
Thanks for your hard work in addressing all of the changes @Marcdh3 . I left a few more minor comments after another read. Other than those, it's looking great!

2020-07-01 15:19 UTC, josephmje commented on papers/marcus_hill/paper.rst
> +Perturbations of organellar structures within a cell are useful indicators of the cell’s response to viral or bacterial invaders. Of the various organelles, mitochondria are meaningful to model becau
infections that **can be leveraged** to develop tests

2020-07-01 15:19 UTC, josephmje commented on papers/marcus_hill/paper.rst
> +Perturbations of organellar structures within a cell are useful indicators of the cell’s response to viral or bacterial invaders. Of the various organelles, mitochondria are meaningful to model becau
techniques  that  are  more  automated  and  **utilize**

2020-07-01 15:19 UTC, josephmje commented on papers/marcus_hill/paper.rst
> +Perturbations of organellar structures within a cell are useful indicators of the cell’s response to viral or bacterial invaders. Of the various organelles, mitochondria are meaningful to model becau
diffuse structures that **render** traditional

2020-07-01 15:19 UTC, josephmje commented on papers/marcus_hill/paper.rst
> +in cell before and after a fission event. :label:`dynamics`
this line appears in the introduction paragraph instead of with the figure

2020-07-01 15:19 UTC, josephmje commented on papers/marcus_hill/paper.rst
> +in cell before and after a fission event. :label:`dynamics`
also, Figure 1 isn't referenced anywhere in the text

2020-07-01 15:19 UTC, josephmje commented on papers/marcus_hill/paper.rst
> +In our efforts to demonstrate the morphological spectrum that mitochondria undergoes, we have amassed a collection of confocal imaging videos of live HeLa cells fluorescently tagged with the protein
n  our  efforts  to  demonstrate  the  morphological  spectrum  that mitochondria **undergo**

2020-07-01 15:19 UTC, josephmje commented on papers/marcus_hill/paper.rst
> +.. figure:: figures/mdivi_boxes.png
should the ordering of figures 2 and 3 be switched?

2020-07-01 17:22 UTC, Marcdh3 commented on papers/marcus_hill/paper.rst
> +Perturbations of organellar structures within a cell are useful indicators of the cell’s response to viral or bacterial invaders. Of the various organelles, mitochondria are meaningful to model becau
All of these are now fixed.

2020-07-01 17:22 UTC, Marcdh3 commented on papers/marcus_hill/paper.rst
> +In our efforts to demonstrate the morphological spectrum that mitochondria undergoes, we have amassed a collection of confocal imaging videos of live HeLa cells fluorescently tagged with the protein
Fixed.

2020-07-01 17:25 UTC, Marcdh3 commented on papers/marcus_hill/paper.rst
> +.. figure:: figures/mdivi_boxes.png
Figure 2 and Figure 3 correspond to the temporal anomaly detection and spatial anomaly detection sections, respectively. I can see that the references to the figures that are later in the paper makes it appear that they should be switched, so I added figure references in both of the earlier sections to clear things up.

2020-07-01 17:27 UTC, Marcdh3 commented on papers/marcus_hill/paper.rst
> +in cell before and after a fission event. :label:`dynamics`
I fixed the line that was appearing with the introduction instead of with the figure as intended, and added a reference to Figure 1 in the introduction.

2020-07-01 17:28 UTC, Marcdh3 commented
@josephmje The latest changes have now been addressed. Thanks for your great feedback!

2020-07-05 15:15 UTC, merged