Paper: CNN Based ToF Image Processing
scipy-conference/scipy_proceedings pull request #625
Opened 2021-05-26 12:20 UTC by tamaslevente

If you are creating this PR in order to submit a draft of your paper,
see http://procbuild.scipy.org/ for logs generated by the build
process.

See the [project readme](https://github.com/scipy-conference/scipy_proceedings#build-your-paper)
for more information.

*Editor*:  

*Reviewers*:

2021-05-26 12:20 UTC, scoobies commented
Hi!, I'm @scoobies, a friendly bot.

Type ```@scoobies help``` to discover how I can help you.

2021-05-26 13:42 UTC, deniederhut commented
@scoobies assign @cbcunc as editor

2021-05-26 13:42 UTC, scoobies commented
Assigned! @cbcunc is now the editor

2021-05-30 18:29 UTC, cbcunc commented
Editor’s initial quickie look-over:

- [x] Make sure the paper builds on procbuild
- [x] Make sure that the sections are filled in
- [x] Make sure 8 pages or less exclusive of references

2021-05-31 13:18 UTC, deniederhut commented
@scoobies add @cocoaaa to reviewers

2021-05-31 13:18 UTC, scoobies commented
@cocoaaa added to the reviewers list!

2021-06-05 10:51 UTC, deniederhut commented
@scoobies add @shubhamsharma1609 to reviewers

2021-06-05 10:51 UTC, scoobies commented
@shubhamsharma1609 added to the reviewers list!

2021-06-07 23:38 UTC, deniederhut commented
We've been having difficulty finding reviewers for some papers, so to make sure everyone has enough time to do their reviews, we will be bumping the deadline for the initial review back to June 17th.

2021-06-10 19:21 UTC, shubhamsharma1609 reviewed
The Abstract  portion is incomplete and is not making any sense,kindly complete the Abstract part. Further,the sub-sections are also incomplete having no description.Kindly complete the portions so that they can be reviewed.

2021-06-18 11:59 UTC, deniederhut commented
Hey @cocoaaa and @shubhamsharma1609! Have you had a chance to review this paper? We were expecting to see some feedback by yesterday.

2021-06-19 08:50 UTC, shubhamsharma1609 requested changes
Overall the concept presented in the paper is really great and the results are presented in a clear manner. In addition,I would like to suggest some changes :

1) In the diagram : **exemplification of ToF camera**,please label shutter on the lens and then the subsequent reflections at the shutter as per the pulse diagram as it will increase readability.

2) Under **low level ToF Image processing** sub section, it would be better to include some code as per the description to further exemplify the work.

3) Under the  **Low level ToF image pre-processing - Tofsmooth** sub-section, the x-axis of the graphs mention analyzed data is an ambiguous term as there are no units (if you are mentioning analyzed data and by that you mean no.of images) then clearly mention no. of images in brackets as the x -axis title.

4) Please include some example code in the **volumetric estimates sub-section** which gives a clear idea about the implementation.

5) In the conclusion, it is mentioned **In this report**,kindly replace the word **report** by **paper**. Also kindly take care of some grammatical errors(very few) to increase clarity.

It would be great to see some more code snippets in the sub-sections that illustrate the work.Overall the paper seems to fit to be included.

2021-06-19 08:52 UTC, shubhamsharma1609 commented
> Hey @cocoaaa and @shubhamsharma1609! Have you had a chance to review this paper? We were expecting to see some feedback by yesterday.

Hi @deniederhut !!!!
Apologies for the delay.I have reviewed the paper and have suggested some changes.

2021-06-21 09:49 UTC, tamaslevente commented
Thanks  @shubhamsharma1609 for the constructive review!

@benjaminkelenyi : could you please handle 1?
@molnarszilard : could you please look for 2-3?
@AlexPop104 : please make sure to include some pseudo code (with an appropriate formatting) for 4.
@Funderburger : please have a look for the common terminology through the paper (e.g. paper vs report)

Once you are done, I will proofread the paper again (hopefully this week).

2021-06-23 10:36 UTC, deniederhut commented
@scoobies mark needs more review

2021-06-23 10:37 UTC, deniederhut commented
@tamaslevente to give everyone more time to respond to their reviews, we've pushed back the deadline for authors' final revisions to July 1st

2021-06-25 18:50 UTC, cbcunc commented
@scoobies check references

2021-06-25 18:56 UTC, scoobies commented
```
Reference check summary (note 'MISSING' DOIs are suggestions that need verification):

OK DOIs

- 10.1109/LRA.2020.2969936 is OK
- 10.1109/ICRA.2011.5980567 is OK
- 10.1109/ICCV.2019.00133 is OK
- 10.1109/CVPR.2017.106 is OK
- 10.1117/12.2586057 is OK
- 10.1177/1729881416657746 is OK
- 10.1109/ACCESS.2020.2982196 is OK

MISSING DOIs

- 10.1109/cvpr.2017.16 may be a valid DOI for title: PointNet: Deep Learning on Point Sets for 3D Classification and Segmentation
- 10.1109/iros45743.2020.9340916 may be a valid DOI for title: Pc-nbv: A point cloud based deep network for efficient next best view planning
- 10.1016/j.rcim.2020.102057 may be a valid DOI for title: Augmented reality integration into MES for connected workers

INVALID DOIs

- https://doi.org/10.1016/j.neucom.2015.06.112 is INVALID because of 'https://doi.org/' prefix
```

2021-06-29 13:38 UTC, deniederhut commented
@tamaslevente have you finished addressing the reviewers' comments?

2021-06-29 13:39 UTC, deniederhut commented
@scoobies mark pending comment

2021-06-30 00:33 UTC, stargaser commented on papers/trai/trai.rst
> +Last years the evolution of deep neurThe applications targeted are rangingfrom persond detection, counting, activity analysis to volumetricmeasurements,  mapping  and  navigation  with  mobile  agent
I have a printout of an earlier version that I began marking up. I think some part of this first line has been mixed in with later parts.

```suggestion
In recent years the evolution of deep neural networks has affected the way in which Time of Flight (ToF) images are 
processed. Images from ToF cameras are usually obtained as synchronized depth and infrared (IR) image pairs. 
```

2021-06-30 10:45 UTC, tamaslevente commented
> @tamaslevente have you finished addressing the reviewers' comments?

Thanks for the follow up/suggested DOIs. Now each of them seem to be valid.

2021-06-30 13:17 UTC, deniederhut commented
Awesome! @shubhamsharma1609 do you feel this paper is now ready for inclusion in the proceedings?

2021-06-30 18:51 UTC, shubhamsharma1609 commented
> Awesome! @shubhamsharma1609 do you feel this paper is now ready for inclusion in the proceedings?

@deniederhut I think it is fair enough to go ahead. Approved from my side.

2021-07-01 00:11 UTC, deniederhut commented on papers/trai/.vscode/settings.json
> +{
Did you mean to commit this?

2021-07-01 05:41 UTC, tamaslevente reviewed
@AlexPop104 Please remove this extra vscode dir. Tx!

2021-07-01 10:55 UTC, deniederhut commented on papers/trai/trai.rst
> +    def compute_volume_ortho(pcd,dmin,dman,votes,seg,thresh):
So sorry! One more thing -- in the rendered PDF, some of these code lines are extending beyond the column width:

<img width="390" alt="Screen Shot 2021-07-01 at 5 51 04 AM" src="https://user-images.githubusercontent.com/6868396/124113035-94859580-da30-11eb-9e80-8f5409aa2714.png">

we might need to make a few changes like, e.g.

```python
def compute_volume_ortho(
    pcd, dmin, dman, votes, seg, thresh
):
```

2021-07-01 11:27 UTC, tamaslevente commented on papers/trai/trai.rst
> +    def compute_volume_ortho(pcd,dmin,dman,votes,seg,thresh):
@AlexPop104 please make some abbreviation in these lines. Tx!

2021-07-02 18:47 UTC, cbcunc commented
@scoobies check references

2021-07-02 18:47 UTC, deniederhut commented on papers/trai/trai.rst
> +    def compute_volume_ortho(pcd,dmin,dman,votes,seg,thresh):
Thanks!

2021-07-02 18:48 UTC, scoobies commented
```
Reference check summary (note 'MISSING' DOIs are suggestions that need verification):

OK DOIs

- 10.1109/LRA.2020.2969936 is OK
- 10.1109/ICRA.2011.5980567 is OK
- 10.1109/ICCV.2019.00133 is OK
- 10.1109/CVPR.2017.106 is OK
- 10.1117/12.2586057 is OK
- 10.1109/cvpr.2017.16 is OK
- 10.1016/j.neucom.2015.06.112 is OK
- 10.1177/1729881416657746 is OK
- 10.1109/ACCESS.2020.2982196 is OK
- 10.1109/iros45743.2020.9340916 is OK
- 10.1109/TPAMI.2019.2931577 is OK
- 10.1016/j.rcim.2020.102057 is OK

MISSING DOIs

- None

INVALID DOIs

- None
```

2021-07-02 18:57 UTC, cbcunc commented
@scoobies mark ready

2021-07-05 16:00 UTC, merged