Paper: Cell Tracking in 3D using deep learning segmentations
scipy-conference/scipy_proceedings pull request #627
Opened 2021-05-27 15:07 UTC by kapoorlab

If you are creating this PR in order to submit a draft of your paper,
see http://procbuild.scipy.org/ for logs generated by the build
process.

See the [project readme](https://github.com/scipy-conference/scipy_proceedings#build-your-paper)
for more information.

*Editor*:  

*Reviewers*:

2021-05-27 15:08 UTC, scoobies commented
Hi!, I'm @scoobies, a friendly bot.

Type ```@scoobies help``` to discover how I can help you.

2021-05-27 15:46 UTC, deniederhut commented
@scoobies assign @stargaser as editor

2021-05-27 15:46 UTC, scoobies commented
Assigned! @stargaser is now the editor

2021-06-07 11:06 UTC, deniederhut commented
@scoobies add @NickleDave to reviewers

2021-06-07 11:06 UTC, scoobies commented
@NickleDave added to the reviewers list!

2021-06-07 23:38 UTC, deniederhut commented
We've been having difficulty finding reviewers for some papers, so to make sure everyone has enough time to do their reviews, we will be bumping the deadline for the initial review back to June 17th.

2021-06-09 15:41 UTC, stargaser commented
scoobies add @davekits to reviewers

2021-06-09 15:49 UTC, stargaser commented
@scoobies add @davekits to reviewers

2021-06-09 15:49 UTC, scoobies commented
@davekits added to the reviewers list!

2021-06-10 21:40 UTC, kapoorlab commented
@scoobies help

2021-06-10 21:40 UTC, scoobies commented
Hello @kapoorlab, here are the things you can ask me to do:

```

# List all available commands
@scoobies help

# Show our community Code of Conduct and Guidelines
@scoobies code of conduct

# Add to this issue's reviewers list
@scoobies add @username to reviewers

# Remove from this issue's reviewers list
@scoobies remove @username from reviewers

# Assign a user as the editor of this submission
@scoobies assign @username as editor

# Remove the editor assigned to this submission
@scoobies remove editor

# Add a user to this issue's assignees list
@scoobies add assignee: @username

# Remove a user from this issue's assignees list
@scoobies remove assignee: @username

# Builds paper
@scoobies build paper

# Checks build status
@scoobies build status

# Check the references of the paper for missing DOIs
# Optionally, it can be run on a non-default branch 
@scoobies check references
@scoobies check references from custom-branch-name

# Label issue with: paper
@scoobies mark paper

# Label issue with: needs-review. Remove labels: unready, needs-more-review, pending-comment, ready
@scoobies mark needs review

# Label issue with: needs-more-review. Remove labels: unready, needs-review, pending-comment, ready
@scoobies mark needs more review

# Label issue with: pending-comment. Remove labels: unready, needs-review, needs-more-review, ready
@scoobies mark pending comment

# Label issue with: ready. Remove labels: unready, needs-review, needs-more-review, pending-comment
@scoobies mark ready

# Label issue with: unready. Remove labels: needs-review, needs-more-review, pending-comment, ready
@scoobies mark not ready

# Label issue with: does_not_build:server
@scoobies mark server fail

# Remove labels: does_not_build:server
@scoobies mark server success

```

2021-06-10 21:41 UTC, kapoorlab commented
@scoobies build paper

2021-06-10 21:41 UTC, scoobies commented
building paper...

2021-06-10 21:41 UTC, scoobies commented
{"data"=>{"info"=>"Build for paper kapoorlab-2021 scheduled.  Note that builds are only executed if the current build attempt is more than 5 minutes old."}, "status"=>"success"}

2021-06-11 21:56 UTC, stargaser commented
Hey @NickleDave, @davekits just a friendly reminder that the initial review deadline is next week.

2021-06-12 15:07 UTC, NickleDave commented
@stargaser thank you for the reminder

👋 hi @kapoorlab looking forward to reading and working with you on the review.

This is on my to-do list, will get it done by Wednesday night at the latest

2021-06-12 22:55 UTC, kapoorlab commented
@NickleDave Thank you so much, looking forward to your review :)

2021-06-17 23:25 UTC, NickleDave requested changes
Hi @kapoorlab thank you for your submission. I enjoyed reading and learning about your proposed algorithm and the software you've developed.

My initial assessment is that this is a very solid contribution. I think we can work together to have the paper in a place where I can recommend including it in the proceedings by the final deadline.

I've begun adding comments throughout. I need to finish going through, but I wanted to get the process started, to give you a chance to address my suggested revisions (and so I actually meet the initial deadline :angel: )

2021-06-17 23:25 UTC, NickleDave commented on papers/varun_kapoor/00_varunclaudia.rst
> +Live-cell imaging is a highly used technique to study cell migration and dynamics over time. Although many computational tools have been developed during the past years to automatically detect and tr
I'd suggest rephrasing to make it clear the main problem you are addressing.

Perhaps change

> However, automated analysis of fluorescently membrane-labelled cells can be highly challenging 

to

> These existing tools are challenged when tracking fluorescently labeled membranes of cells, due to cells' irregular shape, ...

2021-06-17 23:25 UTC, NickleDave commented on papers/varun_kapoor/00_varunclaudia.rst
> +Quantitative analysis to study morphogenesis requires an accurate image analysis workflow. Such a workflow entails volumetric (3D) imaging of cells via fluorescence microscopy, accurate detection and
> Quantitative analysis to study morphogenesis requires an accurate image analysis workflow.

I might start with a simpler sentence that's less intimidating to non-experts (like me).

What is morphogenesis?
Doesn't any quantitative analysis require an accurate image analysis workflow?

Maybe say something like:
> Quantitative analysis of imaging data requires accuracy. For example, morphogenesis, [definition here], entails volumetric (3D) imaging of cells ...

2021-06-17 23:25 UTC, NickleDave commented on papers/varun_kapoor/00_varunclaudia.rst
> +Our dataset is comprised of epithelial cells of mouse embryonic mammary glands with membrane labelling. These cells are highly irregular in shape and have a low signal-to-noise ratio to obtain an acc
It's a bit confusing to start this paragraph talking about the dataset. How about something like this?
> To address the issues with existing segmentation algorithms just described, we developed Vollseg. In brief ... [rest of paragraph here] ... and U-Net networks. We benchmark our segmentation result on a challenging dataset comprised of epithelial cells of mouse embryonic mammary glands with membrane labelling. These cells are highly irregular in shape and have a low signal-to-noise ratio to obtain an accurate segmentation only based on the boundary information. Using this dataset, we obtain different metrics showing that our approach is able to obtain shape approximation for the overlapping cells that go beyond the star convex shape."

2021-06-17 23:25 UTC, NickleDave commented on papers/varun_kapoor/00_varunclaudia.rst
> +We used fluorescent microscopy images of mouse embryonic mammary glands stabilized in an ex vivo culture previously collected in the laboratory of Dr. S. Fre at Institut Curie. All images were acquir
I'm not sure you need to provide a lengthy justification for image restoration here?
I think it's fine to just say:
> We acquired images of pixel size (22, 512, 512) with calibration of (3, 0.52, 0.52) micrometer. Lastly we performed unsupervised image denoising (cite) on our dataset, an algorithm we chose based on its performance compared to other methods (cite more)

2021-06-17 23:25 UTC, NickleDave commented on papers/varun_kapoor/00_varunclaudia.rst
> +Post-restoration of the 3D images, we developed a method to perform the segmentation of the cells using deep learning techniques, as it was shown by Rasse et al. that conventional computer vision and
I would move this language to the introduction, to the place where you originally cite this paper.
> as it was shown by Rasse et al. that conventional computer vision and machine learning based techniques alone will almost always lead to sub-optimal segmentation :cite:`Rasse2020`

It's more explicit than the passing mention of the paper you have there now and helps motivate your development of the method.


I'm not sure you need higher-level comments like this now that you're already describing the method :slightly_smiling_face:

2021-06-17 23:25 UTC, NickleDave commented on papers/varun_kapoor/00_varunclaudia.rst
> +Post-restoration of the 3D images, we developed a method to perform the segmentation of the cells using deep learning techniques, as it was shown by Rasse et al. that conventional computer vision and
> (computed using skimage)

I would spell out the entire name "scikit-image" and include a citation here, to the paper and to the DOI of the specific version of `skimage` that you used

2021-06-17 23:25 UTC, NickleDave commented on papers/varun_kapoor/00_varunclaudia.rst
> +Post-restoration of the 3D images, we developed a method to perform the segmentation of the cells using deep learning techniques, as it was shown by Rasse et al. that conventional computer vision and
re: section names, I'd suggest changing the section name "Segmentation" to something like "Dataset Preparation". At least at the start of the paragraph here it sounds like you are describing steps you took to prepare the data for training and evaluating your algorithm. Not sure if there's a more precise term to use -- I thought of "munging" or "canonicolization" :/

2021-06-17 23:25 UTC, NickleDave commented on papers/varun_kapoor/00_varunclaudia.rst
> +Post-restoration of the 3D images, we developed a method to perform the segmentation of the cells using deep learning techniques, as it was shown by Rasse et al. that conventional computer vision and
Before this sentence

> Stardist predicts object instances based on probability threshold and non maximal suppression threshold to merge overlapping predictions. These parameters can be automatically determined using the optimize threshold program that we provide with the segmentation package.

I'd suggest adding a new section, e.g. "Parameter Tuning" or "Parameter Selection"

2021-06-17 23:25 UTC, NickleDave commented on papers/varun_kapoor/00_varunclaudia.rst
> +Accuracy of segmentation results is assesed by comparing the obtained labels to the gold standard ground truth (GT) labels. Most commonly used metric is to compute intersection over union (IOU) score
I'd suggest making this sentence the start of a new section named something like "Performance Metrics"

2021-06-17 23:25 UTC, NickleDave commented on papers/varun_kapoor/00_varunclaudia.rst
> +The software package we provide comes with training and prediction notebooks for training the base U-Net and Stardist networks on your own dataset. We provide jupyter notebooks to do so on local GPU
I think you intend this sentence ("The software package...") to be the start of a new sub-section within "Methods", where you walk through the process in detail, before you get to the "Results" section?

If so, I would add a new sub-section title here, e.g. "Walkthrough" (or if you prefer "Protocol" like you say in the abstract) and then making the following section headers one level lower, i.e. "Walkthrough" will be a level two heading and "Network Training..." would be level 3

```rst
Methods
-----------

...

Walkthrough
**************

The software package we provide comes with training and prediction notebooks for training the base U-Net and Stardist networks on your own dataset. We provide jupyter notebooks to do so on local GPU servers and also on Google Colab.

======================
Network Training
======================
```

2021-06-17 23:25 UTC, NickleDave commented on papers/varun_kapoor/00_varunclaudia.rst
> +Accuracy of segmentation results is assesed by comparing the obtained labels to the gold standard ground truth (GT) labels. Most commonly used metric is to compute intersection over union (IOU) score
Perhaps remove the phrase "gold standard"

> Accuracy of segmentation results is assesed by comparing the obtained labels to the gold standard ground truth (GT) labels.

"ground truth" has a technical meaning that is appropriate here but to me "gold standard" is more of a comment on why a certain approach is used. In this context I think it's clear you'd want to use the "gold standard" approach.

2021-06-17 23:25 UTC, NickleDave commented on papers/varun_kapoor/00_varunclaudia.rst
> +Accuracy of segmentation results is assesed by comparing the obtained labels to the gold standard ground truth (GT) labels. Most commonly used metric is to compute intersection over union (IOU) score
> Most commonly used metric is to compute intersection over union (IOU) score between the predicted and the GT label image.

Insert "The" before "most"

2021-06-17 23:25 UTC, NickleDave commented on papers/varun_kapoor/00_varunclaudia.rst
> +.. figure:: Figures/Seg_pipe.png
Consider moving this figure to the first page if possible and referencing it in the second paragraph when you describe what is unique about your method

I think it would help make your contribution clearer to a reader

2021-06-18 12:01 UTC, deniederhut commented
@scoobies mark needs more review

2021-06-19 06:07 UTC, kapoorlab commented
@NickleDave Thank you so much. I will work on your comments over the weekend and make all the necessary changes you asked for by Sunday night :). Thank you so much for making our contribution nicer.

2021-06-20 10:55 UTC, kapoorlab commented on papers/varun_kapoor/00_varunclaudia.rst
> +Live-cell imaging is a highly used technique to study cell migration and dynamics over time. Although many computational tools have been developed during the past years to automatically detect and tr
Hi there, I changed the abstract to: 

> These existing tools are challenged when tracking fluorescently labelled membranes of cells due to cell's irregular shape, variability in size and dynamic movement across Z planes making it difficult to detect and track them.

2021-06-20 11:01 UTC, kapoorlab commented on papers/varun_kapoor/00_varunclaudia.rst
> +Quantitative analysis to study morphogenesis requires an accurate image analysis workflow. Such a workflow entails volumetric (3D) imaging of cells via fluorescence microscopy, accurate detection and
I changed the statement to

> Quantitative analysis of imaging data requires accuracy. For example, morphogenesis, a process of shaping an organism by embryological process of cell diffrentiation, entails volumetric (3D) imaging of cells inside the tissue. To analyse the data an accurate image analysis workflow is required.

2021-06-20 11:11 UTC, kapoorlab commented on papers/varun_kapoor/00_varunclaudia.rst
> +Our dataset is comprised of epithelial cells of mouse embryonic mammary glands with membrane labelling. These cells are highly irregular in shape and have a low signal-to-noise ratio to obtain an acc
Changed this paragraph to 

> To address the issues with existing segmentation algorithms just described, we developed Vollseg. In brief we use Stardist in 3D to obtain a star convex shape approximation for the cells and extract the cell centroids from these polygons. We also train a 3D U-Net model to obtain a semantic segmentation map of the cells. We then perform a marker controlled watershed on the probability map of Stardist using the U-Net segmentation as a mask image to prevent the overflow of segmentation regions. To avoid the error of sub-optimal seeding we developed a seed pooling approach taking advantage of strength of both the Stardist and U-Net networks. We benchmark our segmentation result on a challenging dataset comprised of epithelial cells of mouse embryonic mammary glands with membrane labelling. These cells are highly irregular in shape and have a low signal-to-noise ratio to obtain an accurate segmentation only based on the boundary information. Using this dataset, we obtain different metrics showing that our approach is able to obtain shape approximation for the overlapping cells that go beyond the star convex shape.

2021-06-20 11:19 UTC, kapoorlab commented on papers/varun_kapoor/00_varunclaudia.rst
> +We used fluorescent microscopy images of mouse embryonic mammary glands stabilized in an ex vivo culture previously collected in the laboratory of Dr. S. Fre at Institut Curie. All images were acquir
Changed this paragraph to 

> We acquired images of pixel size (22, 512, 512) with calibration of (3, 0.52, 0.52) micrometer. 
The quality at which these images are acquired is determined by the spatial resolution of the used optical device, desired temporal resolution, duration of the experiment and depth of the acquired Z-stacks. We perform unsupervised image denoising :cite:`krull2019` on our dataset, an algorithm we chose based on its performance compared to other methods :cite:`Richardson72`, :cite:`Lucy74` and due to lack of having training data needed for supervised learning algorithms :cite:`Weigert2017`.

2021-06-20 11:46 UTC, kapoorlab commented on papers/varun_kapoor/00_varunclaudia.rst
> +Post-restoration of the 3D images, we developed a method to perform the segmentation of the cells using deep learning techniques, as it was shown by Rasse et al. that conventional computer vision and
Moved the statement to introduction appending it to the original statement there to now say

> It was shown in :cite:`Rasse2020` that conventional computer vision and machine learning based techniques alone will almost always lead to sub-optimal segmentation and that methods based on deep learning have improved the accuracy of segmentation for natural and biomedical images alike.

Added citation of scikit-image version 0.18x, am not sure if I found the right DOI for it though, I cite the paper mentioned here: https://scikit-image.org/

2021-06-20 11:50 UTC, kapoorlab commented on papers/varun_kapoor/00_varunclaudia.rst
> +Post-restoration of the 3D images, we developed a method to perform the segmentation of the cells using deep learning techniques, as it was shown by Rasse et al. that conventional computer vision and
Since the section before Segmentation is already called Preparation of  the dataset, I just merged the two sections into on and before making the statement about stardist I added a section called Parameter Tuning.

2021-06-20 11:57 UTC, kapoorlab commented on papers/varun_kapoor/00_varunclaudia.rst
> +Accuracy of segmentation results is assesed by comparing the obtained labels to the gold standard ground truth (GT) labels. Most commonly used metric is to compute intersection over union (IOU) score
Added the section performance metrics and remove the gold standard words as it is really the ground truth labels that we want to compare the segmentation results with. So in that case I thought it was most appropriate to remove the gold standard and just call it ground truth labels. 

Inserted The before most.

2021-06-20 12:13 UTC, kapoorlab commented on papers/varun_kapoor/00_varunclaudia.rst
> +The software package we provide comes with training and prediction notebooks for training the base U-Net and Stardist networks on your own dataset. We provide jupyter notebooks to do so on local GPU
Yeah, I called it protocol instead of walkthrough because it is commonly used terminology in biological sciences.
I redid the sectioning as you mentioned with the levels as you said.

2021-06-20 12:28 UTC, kapoorlab commented on papers/varun_kapoor/00_varunclaudia.rst
> +.. figure:: Figures/Seg_pipe.png
I was able to move the figure to the second page in introduction and make a reference to it in the second paragraph where I describe the method. Somehow the compiler does not place the figure on page 1, would that be acceptable? I will just commit my new paper and ask scoobies to build it to see if everything is in order. Looking forward to hearing from you :)

2021-06-20 12:29 UTC, kapoorlab commented
@scoobies build paper

2021-06-20 12:29 UTC, scoobies commented
building paper...

2021-06-20 12:29 UTC, scoobies commented
{"data"=>{"info"=>"Build for paper kapoorlab-2021 scheduled.  Note that builds are only executed if the current build attempt is more than 5 minutes old."}, "status"=>"success"}

2021-06-20 12:34 UTC, kapoorlab commented
@scoobies build paper

2021-06-20 12:34 UTC, scoobies commented
building paper...

2021-06-20 12:34 UTC, scoobies commented
{"data"=>{"info"=>"Build for paper kapoorlab-2021 scheduled.  Note that builds are only executed if the current build attempt is more than 5 minutes old."}, "status"=>"success"}

2021-06-21 10:04 UTC, kapoorlab commented on papers/varun_kapoor/00_varunclaudia.rst
> +Quantitative analysis to study morphogenesis requires an accurate image analysis workflow. Such a workflow entails volumetric (3D) imaging of cells via fluorescence microscopy, accurate detection and
Actually maybe we can exclude mentioning morphogenesis here and just use cell migration instead and change the statement to this instead:

> Live-cell imaging is a highly used technique to study cell migration and dynamics over time. The image analysis workflow of volumetric (3D) imaging of cells via fluorescence microscopy starts with an accurate detection and segmentation of cells followed by cell tracking and track analysis.

2021-06-21 10:06 UTC, kapoorlab commented on papers/varun_kapoor/00_varunclaudia.rst
> +We used fluorescent microscopy images of mouse embryonic mammary glands stabilized in an ex vivo culture previously collected in the laboratory of Dr. S. Fre at Institut Curie. All images were acquir
I removed the mention of supervised learning algorithm and change this paragraph to say the following:

>  We acquired images of pixel size (22, 512, 512) with calibration of (3, 0.52, 0.52) micrometer. 
The quality at which these images are acquired is determined by the spatial resolution of the used optical device, desired temporal resolution, duration of the experiment and depth of the acquired Z-stacks. We perform unsupervised image denoising :cite:`krull2019` on our dataset, an algorithm we chose based on its performance compared to other methods :cite:`Richardson72`, :cite:`Lucy74`.

2021-06-21 10:12 UTC, kapoorlab commented on papers/varun_kapoor/00_varunclaudia.rst
> +Post-restoration of the 3D images, we developed a method to perform the segmentation of the cells using deep learning techniques, as it was shown by Rasse et al. that conventional computer vision and
Shall we call this Parameter Setting instead? since its not a manual choice of parameters and we are determining it via computing iou scores of the prediction and the validation dataset. Then I keep the title of segmentation and the text then looks as



> Parameter Setting
*****************
Stardist predicts object instances based on probability threshold and non maximal suppression threshold to merge overlapping predictions. These parameters can be automatically determined using the optimize threshold program that we provide with the segmentation package. Higher values of the probability threshold yield fewer object instances, but avoids false positives. Higher values of the overlap threshold would lead to oversegmentation. We used 32 Z-stacks to determine the optimal parameters of probability threshold of 0.76 and non maximal suppression threshold of 0.3. 

Segmentation
*****************
As illustrated in Figure :ref:`algorithm`, we first obtain the centroids of the star convex approximated cell shapes and create a seed pool with these centroid locations.

2021-06-21 10:14 UTC, kapoorlab commented on papers/varun_kapoor/00_varunclaudia.rst
> +The software package we provide comes with training and prediction notebooks for training the base U-Net and Stardist networks on your own dataset. We provide jupyter notebooks to do so on local GPU
I changed protocol to Detailed Procedure to distinguish it from a more technical usage of protocol in the field of biological sciences.

2021-06-21 10:15 UTC, kapoorlab commented
@scoobies build paper

2021-06-21 10:15 UTC, scoobies commented
building paper...

2021-06-21 10:15 UTC, scoobies commented
{"data"=>{"info"=>"Build for paper kapoorlab-2021 scheduled.  Note that builds are only executed if the current build attempt is more than 5 minutes old."}, "status"=>"success"}

2021-06-22 19:23 UTC, kapoorlab commented
@deniederhut I added our poster in the presentation folder as a pdf file.

2021-06-23 10:38 UTC, deniederhut commented
@kapoorlab to give everyone more time to respond to their reviews, we've pushed back the deadline for authors' final revisions to July 1st

2021-06-27 21:53 UTC, stargaser commented
@NickleDave thank you for reviewing this paper. Do the revisions made by @kapoorlab address the issues you raised in your review?

2021-06-27 22:01 UTC, stargaser commented
@scoobies check references

2021-06-27 22:02 UTC, scoobies commented
```
Reference check summary (note 'MISSING' DOIs are suggestions that need verification):

OK DOIs

- 10.7717/peerj.453 is OK
- 10.1038/nmeth.1228 is OK
- 10.1364/JOSA.62.000055 is OK
- 10.1101/236463 is OK
- 10.1101/2020.01.17.910562 is OK
- 10.1038/s41592-019-0582-9 is OK
- 10.1038/s41592-018-0216-7 is OK
- 10.3389/fbioe.2020.558880 is OK
- 10.1101/2020.09.10.276980 is OK
- 10.1101/gad.322818.118 is OK
- 10.1109/WACV45572.2020.9093435 is OK
- 10.1007/978-3-030-00934-2_30 is OK

MISSING DOIs

- 10.1086/111605 may be a valid DOI for title: An iterative technique for the rectification of observed distributions
- 10.1109/isbi.2019.8759242 may be a valid DOI for title: CNN-based Preprocessing to Optimize Watershed-based Cell Segmentation in 3D Confocal Microscopy Images
- 10.1201/9781482277234-12 may be a valid DOI for title: The Morphological Approach to Segmentation: The Watershed Transformation
- 10.1109/cvpr.2019.00223 may be a valid DOI for title: Noise2void-learning denoising from single noisy images

INVALID DOIs

- https://doi.org/10.1002/nav.3800020109 is INVALID because of 'https://doi.org/' prefix
- https://doi.org/10.1016/j.ymeth.2016.09.016 is INVALID because of 'https://doi.org/' prefix
```

2021-06-27 22:08 UTC, stargaser commented
@kapoorlab here are some items from an editorial check:

- not overruning margins on code blocks: good
- DOIs in references: mostly good, a few may need to be added or revised, please see previous comment for the DOI check
- Not modifying files outside the papers directory: this definitely needs attention as there are many top-level files and files in the `publisher` directory that are modified in this pull request. Those files must be removed before we can merge and publish this contribution.

2021-06-28 04:52 UTC, kapoorlab commented
@stargaser thanks for checks. I corrected the doi's and removed the conflicting files from the publisher folder. I pushed my changes. Does everything look okay now?

2021-06-29 13:13 UTC, stargaser commented on papers/varun_kapoor/vkc.bib
> + url = {https://doi.org/10.7717/peerj.453},
here and elsewhere in the references, the `url` item is not needed when the `doi` item is present. The `doi` item generates a URL in the paper PDF.

2021-06-29 13:22 UTC, stargaser commented
Thanks @kapoorlab for updating the DOIs. In some of the references, the `url` item with the same information can be removed as it makes an extra link in the paper PDF.

Thanks also for removing the `publisher` subdirectory. There are still some top-level files in the pull request that need removal before merging: `README.md`, `requirements.txt`, `review_criteria.md`, `scipy.proc.json`.

I see you've included the poster PDF in this pull request. I need to check with @deniederhut and the other co-chairs about that.

2021-06-29 13:41 UTC, deniederhut commented
> I see you've included the poster PDF in this pull request. 

As long as the required metadata is there, this is okay

2021-06-29 13:42 UTC, deniederhut commented
@scoobies mark pending comment

2021-06-29 14:44 UTC, kapoorlab commented on papers/varun_kapoor/vkc.bib
> + url = {https://doi.org/10.7717/peerj.453},
I removed the urls's from the citations that had doi's included. Making a push

2021-06-29 14:50 UTC, kapoorlab commented
@stargaser I removed the other files form the top level directory and updated the bib file. Is the pull request compatible now?

2021-06-29 14:54 UTC, kapoorlab commented
@deniederhut I received an email about the poster as well where I was supposed to send the link to the poster, I put the link from my github, where the poster is. Would that be fine of shall I do it some other way?

2021-06-30 00:50 UTC, stargaser commented
My apologies @kapoorlab, I should have said that the files in the top-level directory should not differ from those on the scipy_proceedings `2021` branch so that they do not appear in the "Files Changed" tab here on the pull request.

If your remote for the `scipy-conference/scipy_proceedings` repository is named `upstream`, then I think you can get these with
```
git fetch upstream
git checkout upstream/2021 README.md
```
and so on for those top-level files; then you can commit them.

Regarding the poster itself, adding it to this repository is for upload to Zenodo and including a link to it in the SciPy proceedings. I don't know what the instructions are for displaying your poster at the conference.

2021-06-30 03:13 UTC, NickleDave commented
> @NickleDave thank you for reviewing this paper. Do the revisions made by @kapoorlab address the issues you raised in your review?

Hi @stargaser sorry I missed this.

Yes, I have verified that the revisions made by @kapoorlab address the issues I raised in review. Thank you @kapoorlab !

2021-06-30 03:14 UTC, NickleDave approved these changes

2021-06-30 06:25 UTC, kapoorlab commented
@NickleDave Thank you for reviewing the paper, yes your review was helpful in structuring it correctly. Thank you for approving the changes. @stargaser I did the git fetches and got it all in sync. Poster instructions came to in separate emails with a form to fill where you need to provide the poster link, which is why I put the poster in here and then we all will present it in gather town.

2021-06-30 13:20 UTC, deniederhut commented
> I put the link from my github, where the poster is. Would that be fine of shall I do it some other way?

That should be okay? You can check in with Madicken and Matt if you aren't sure.

2021-06-30 17:45 UTC, stargaser commented
@kapoolab thank you for fetching the top-level `README.md` and committing it. Would you please do the same for top-level `review_criteria.md`, `requirements.txt` and `scipy_proc.json`? These files still appear in the "Files changed" tab.

2021-06-30 17:46 UTC, stargaser commented
@kapoorlab  thank you for fetching the top-level README.md and committing it. Would you please do the same for top-level review_criteria.md, requirements.txt and scipy_proc.json? These files still appear in the "Files changed" tab.

2021-06-30 19:25 UTC, kapoorlab commented
@stargaser thank you for pointing this out now I think now it should be fine. My pull request should be mergable with the main branch. Let me know if this is not the case.

2021-07-02 18:51 UTC, deniederhut commented
Hi there! It looks your poster pdf is missing some metadata (in the presentations directory). We don't need to fix this for the paper, but we'll need to fix it to publish the rendered poster. You can see instructions for how to do that here: https://github.com/scipy-conference/scipy_proceedings#instructions-for-slides

2021-07-02 20:59 UTC, kapoorlab commented
@deniederhut I added the info.json file in the poster directory. It should be okay now. Many thanks.

2021-07-02 21:04 UTC, stargaser commented
@scoobies mark ready

2021-07-05 16:01 UTC, merged