Paper: CLAIMED, a visual and scalable component library for Trusted AI
scipy-conference/scipy_proceedings pull request #628
Opened 2021-05-27 15:44 UTC by fatkaratekid

I am submitting a full paper, as mentioned in the email titled: "Invitation to submit a full paper for SciPy 2021"

The paper builds successfully on my machine.

-------

If you are creating this PR in order to submit a draft of your paper,
see http://procbuild.scipy.org/ for logs generated by the build
process.

See the [project readme](https://github.com/scipy-conference/scipy_proceedings#build-your-paper)
for more information.

*Editor*:  

*Reviewers*:

2021-05-27 15:44 UTC, scoobies commented
Hi!, I'm @scoobies, a friendly bot.

Type ```@scoobies help``` to discover how I can help you.

2021-05-27 15:55 UTC, deniederhut commented
@scoobies assign @deniederhut as editor

2021-05-27 15:55 UTC, scoobies commented
Assigned! @deniederhut is now the editor

2021-06-07 11:09 UTC, deniederhut commented
@scoobies add @stsievert to reviewers

2021-06-07 11:09 UTC, scoobies commented
@stsievert added to the reviewers list!

2021-06-07 23:39 UTC, deniederhut commented
We've been having difficulty finding reviewers for some papers, so to make sure everyone has enough time to do their reviews, we will be bumping the deadline for the initial review back to June 17th.

2021-06-09 11:18 UTC, deniederhut commented
@scoobies add @cmarmo to reviewers

2021-06-09 11:18 UTC, scoobies commented
@cmarmo added to the reviewers list!

2021-06-12 01:32 UTC, deniederhut commented
Hi @stsievert and @cmarmo ! Friendly reminder that the initial review deadline is next week

2021-06-15 21:51 UTC, stsievert reviewed
Thanks for the submission @fatkaratekid! This looks like an interesting tool to manage machine learning (ML) pipelines. IIUC, default pipeline components help with model training, interpretation, fairness, and robustness (through Tensorflow, LIME, AI360 and ART respectively). CLAIMED pipelines are created with JupyterLab and can be executed on a Kubernetes cluster/Docker Swarm.

Some questions I have are below:

1. What's required to run this software locally?
2. Why doesn't the abstract only mention the problem CLAIMED solves and the features CLAIMED provides? Someone who picks up this paper will care most about the features of the software, not the underlying building blocks. Generally, it took a while to understand this paper because I got distracted by the underlying building blocks (Kubernetes, Tensorflow, etc).
3. I'm still not certain about what this software is capable of. What pipeline components are included by default? Can I develop a custom component? e.g., what if I want to use PyTorch instead of Tensorflow?

I also have some more context-specific comments:

2021-06-15 21:51 UTC, stsievert commented on papers/ivan_nesic/claimed.rst
> +   Therefore we provide an entirely open source, reusable component framework, visual editor and execution engine for production grade machine learning on top of Kubernetes, a joint effort between IB
> We explain how we’ve created a COVID-19 deep learning classification pipeline based on CT scans. We use the toolkit to highlight parts of the images which have been crucial for the model’s decisions. We detect bias against age and gender and finally, show how to deploy the model to KFServing to share it across different hospital data centers of the Swiss Personalized Health Network.

That's a lot of words to say "To exemplify the use of CLAIMED, we show a toy workflow to train, debug and deploy of a deep learning model that determines if CT scans are positive for COVID-19."

When I first read this abstract, I expected to see detailed experiments on age and gender, detailed experiments on COVID-19 image classification (that had reasonable accuracy), and detailed experiments on deployment (including config scripts).

2021-06-15 21:51 UTC, stsievert commented on papers/ivan_nesic/claimed.rst
> +.. figure:: elyra_pipeline.png
This figure is not readable. I can't determine the function of any of the blocks. It might be more clear to have a simpler and readable workflow (as expressed on *[AI Pipelines](https://elyra.readthedocs.io/en/stable/user_guide/pipelines.html)*).

2021-06-15 21:51 UTC, stsievert commented on papers/ivan_nesic/claimed.rst
> +Introduction
I think good introductions give solid reasoning for the software tool. What problem would you like to address, and why is your software necessary? What users would find it useful?

I find an answer to that question a lot more valuable in the introduction then "what is our software built from?"

2021-06-15 21:51 UTC, stsievert commented on papers/ivan_nesic/claimed.rst
> +Containerization and Kubernetes
Why are these sections in the introduction? Do they introduce your software and explain why your software is necessary?

Generally, I care a lot more about what your software can be used for and what features it has. After I understand the problem, I'll look into how the software is built.

2021-06-15 21:51 UTC, stsievert commented on papers/ivan_nesic/claimed.rst
> +   Therefore we provide an entirely open source, reusable component framework, visual editor and execution engine for production grade machine learning on top of Kubernetes, a joint effort between IB
> an entirely open source, reusable component framework, visual editor and execution engine

What does your software do, or what actions are possible with your software? I'm not sure why I'd care about a "visual editor," "reusable component framework" or "execution engine."

Why do you mention Jupyter notebooks, ElyraAI, KubeFlow, Kubernetes and JupyterLab in the abstract? What *features* do they add to your tool?

2021-06-15 21:51 UTC, stsievert commented on papers/ivan_nesic/claimed.rst
> +Pipeline Components
Is this section it explanation of a particular set of components? Or is a list of every set of components? I'd appreciate both; isn't the pipeline the core feature of your software?

2021-06-15 21:51 UTC, stsievert commented on papers/ivan_nesic/claimed.rst
> +series of non-linear feature space transformations - sounds scary, but
Style nit: I'd remove this sentence. A "non-linear feature space transformation" does not "sound scary" to me.

2021-06-15 21:51 UTC, stsievert commented on papers/ivan_nesic/claimed.rst
> +AI Fairness and Bias
> It turns out that it isn’t that simple.
> Fairness assessment and bias detection is an art on it’s own.

Citations needed.

2021-06-15 21:51 UTC, stsievert commented on papers/ivan_nesic/claimed.rst
> +Introduction
The subsections in the intro are below:

* Containerization and Kubernetes
* Deep Learning with TensorFlow
* Kubeflow
* ElyraAI
* JupyterLab
* AI Explainability
* AI Fairness and Bias
* AI Adversarial Robustness

Which sections describe core features of your library? Which sections describe the implementation of those core features?

2021-06-16 13:21 UTC, cmarmo reviewed
Dear @fatkaratekid, thanks for your submission.
As stressed in your paper, automation in Machine Learning as in any other data processing task is a guarantee of reproducibility.
Having a background in astronomy and scientific data processing I particularly value the effort of building standardized pipelines using open tools.
While I am not an expert in Machine Learning, I have some general comments about this proceeding paper.
1) Sections from "Containerization and Kubernetes" to "AI Adversarial Robustness" don't belong to the Introduction. Their titles (then the subsection contents) are not consistent: sometimes the tool is presented together with the issue it is meant to solve (eg "Containerization and Kubernetes"), sometimes only the tool ("JupyterLab"), sometimes only the issue to be addressed ("AI Adversarial Robustness"). It is important to cite in this context which tool is used, but in my understanding this is more a section describing general pipeline steps. Giving more consistent structure to the subsections will help the reader in understanding how your application can be reused.
2) I suggest to avoid 'useless words' and sentences like 'just', 'really', 'very', ... they add no information to the text and do not feel objectives, in the majority of cases. I have deleted some in my inline suggestions. The text will gain in clarity.

2021-06-16 13:21 UTC, cmarmo commented on papers/ivan_nesic/claimed.rst
> +experience went into it. The system can run on public, on-prem or on
```suggestion
experience went into it. The system can run on public, on-premises or on
```
I am in favor of avoiding abridged words when possible (see also below), for clarity.

2021-06-16 13:21 UTC, cmarmo commented on papers/ivan_nesic/claimed.rst
> +CNCF [cncf]_ by Google, which means a lot of Google’s know-how and years of
I believe this is the first occurrence of the CNCF acronym: do you mind giving the extended definition here? Thanks.

2021-06-16 13:21 UTC, cmarmo commented on papers/ivan_nesic/claimed.rst
> +RedHat, IBM is now 3rd largest committer to Kubernetes [ibmcncf]_.
I find the sentence too compact: Kubernetes is strategic to IBM because it is the 3rd largest committer, or because it moved all Watson services to Kubernetes? Or it became largest committer because they moved to Kubernetes... or ...
Do you mind expanding the sentence? This will clarify the cause - effect relations. Thanks.

2021-06-16 13:21 UTC, cmarmo commented on papers/ivan_nesic/claimed.rst
> +It is the second incarnation of the Google Brain project’s scalable
```suggestion
TensorFlow is the second incarnation of the Google Brain project’s scalable
```

2021-06-16 13:21 UTC, cmarmo commented on papers/ivan_nesic/claimed.rst
> +**E**\ TL and **D**\ ata Science which runs on top of ElyraAI capable of
I am a bit uncomfortable with this acronym ETL used to define the main acronym CLAIMED: I understand ETL is meant to be a very known acronym, perhaps a footnote expanding ETL could be added? IBM itself propose a nice [explanatory page](https://www.ibm.com/cloud/learn/etl) about ETL.

2021-06-16 13:21 UTC, cmarmo commented on papers/ivan_nesic/claimed.rst
> +usability side, both eager and graph modes are supported. Meaning
If I understand correctly eager execution is specific to TensorFlow, for non expert readers it could be useful to have a note explaining what eager execution is (the [TensorFlow documentation](https://www.tensorflow.org/guide/eager) is quite clear itself).

2021-06-16 13:21 UTC, cmarmo commented on papers/ivan_nesic/claimed.rst
> +black box. Technically (and mathematically) deep learning models are a
Feel free to choose between ''Technically" and "mathematically", the two of them are redundant.

2021-06-16 13:21 UTC, cmarmo commented on papers/ivan_nesic/claimed.rst
> +techniques exist to look over a deep learning model’s shoulder. The one
This is a suggestion to avoid unnecessary words and subjective claims.
```suggestion
series of non-linear feature space transformations, it is hard to understand the
individual processing steps a deep learning network performs.
Techniques exist to look over a deep learning model’s shoulder. The one
```

2021-06-16 13:21 UTC, cmarmo commented on papers/ivan_nesic/claimed.rst
> +isn’t in the required format. It’s just a folder full of images and
There is no need to refer to a standard that is not followed by the actual data, especially if this standard is not documented.
A simple description of the data structure will be enough and will improve readability
```suggestion
The raw images are contained in a folder and
```

2021-06-16 13:21 UTC, cmarmo commented on papers/ivan_nesic/claimed.rst
> +   De facto standard in folder structure for image classification data. :label:`imgdir`
As per comment ~below~ above
```suggestion
   Final folder structure for image classification data. :label:`imgdir`
```

2021-06-16 13:21 UTC, cmarmo commented on papers/ivan_nesic/claimed.rst
> +it’s own. Training a deep learning image classification model requires a
> Understanding, defining and training deep learning models is an art on its own. Luckily ...

This sentence appears twice in the text, literally. In both cases, is it really necessary?

2021-06-16 17:04 UTC, stsievert commented on papers/ivan_nesic/claimed.rst
> +**E**\ TL and **D**\ ata Science which runs on top of ElyraAI capable of
I'd appreciate a better definition of ETL; I'm unfamiliar with that acronym.

2021-06-17 11:21 UTC, deniederhut commented
@scoobies mark pending comment

2021-06-17 13:38 UTC, fatkaratekid commented on papers/ivan_nesic/claimed.rst
> +experience went into it. The system can run on public, on-prem or on
This really does make sense, and I am a proponent of it myself. The only issue with the proposed change is that the industry standard for the term is **on-premise**, which rubs some grammar people the wrong way. In that camp, the consensus is we should use **on-premises**. Finally, most people from both camps tend to at least tolerate **on-prem**.
Adam Fowler had some thoughts on it too ([link](https://www.adamfowlerit.com/2017/04/premise-vs-premises-cares/)) and, based on the last update from a linguist in the comment section, it's even alright for us to use the term **on-premise**. It's a conundrum.

The other one is clear (the one below).

2021-06-17 14:35 UTC, cmarmo commented on papers/ivan_nesic/claimed.rst
> +experience went into it. The system can run on public, on-prem or on
Even without being an expert, when I read 'on-premises' or 'on-premise' I can guess the meaning if I know a bit of English, because I have a full word to understand. With 'on-prem' I need to search for it on internet, because this is an abbreviation... that's what I did and I learn something, thanks for that...
To quote your reference "On-Premise vs On-Premises – Who Cares?", both are closer to plain English then 'on-prem', in my opinion.

2021-06-21 09:30 UTC, fatkaratekid commented on papers/ivan_nesic/claimed.rst
> +black box. Technically (and mathematically) deep learning models are a
Fixed in  35ca321

2021-06-21 09:36 UTC, fatkaratekid commented on papers/ivan_nesic/claimed.rst
> +series of non-linear feature space transformations - sounds scary, but
This should be good now, fixed in 4c0858f, or check the newer commit 35ca321.

2021-06-21 09:41 UTC, fatkaratekid commented on papers/ivan_nesic/claimed.rst
> +Containerization and Kubernetes
This is fixed in 65f7ac0a. I hope it is good now, but additional input is always welcome.

2021-06-21 09:48 UTC, fatkaratekid commented on papers/ivan_nesic/claimed.rst
> +Introduction
The introduction has been modified to better answer suggested questions and make it more readable (commit 65f7ac0a).

2021-06-21 10:00 UTC, fatkaratekid commented on papers/ivan_nesic/claimed.rst
> +   Therefore we provide an entirely open source, reusable component framework, visual editor and execution engine for production grade machine learning on top of Kubernetes, a joint effort between IB
This was addressed as of this commit 9cb2543.

2021-06-21 10:06 UTC, fatkaratekid commented on papers/ivan_nesic/claimed.rst
> +CNCF [cncf]_ by Google, which means a lot of Google’s know-how and years of
Added full definition in this commit 2c8b80e

2021-06-21 11:31 UTC, romeokienzler commented
Meghann Agarwal (@mepa)
    Chris Calloway (@cbcunc)
    Dillon Niederhut (@deniederhut)
    David Shupe (@stargaser)

Do you have an example on a table in rst which successfully compiles in latex, the following doesn't work:

.. table:: Requirements for execution engines. KF: Kubeflow, AF: Airflow, SM: Snakemake
================== == == ===== == ==== ======== =====
Requirement        KF AF Slurm SM Qsub HTCondor Reana
================== == == ===== == ==== ======== =====
Kubernetes Support X  X  O     X  O    X        X
GPU support        X  X  X     X  X    X        X
Component Library  X  O  O     O  O    O        O
Reproducibility    X  X  O     X  O    X        X
Data Lineage       X  O  O     O  O    O        X
================== == == ===== == ==== ======== =====

it gives me:

(/home/romeokienzler/gitco/scipy_proceedings/texlive/texlive/2021/texmf-dist/te
x/latex/psnfss/t1pcr.fd)
! Argument of \@xverbatim has an extra }.
<inserted text> 
                \par 
l.487 backrefs: }
                 
!  ==> Fatal error occurred, no output PDF file produced!
Transcript written on paper.log.

You can reproduce by  
git checkout 33f0b906609d10c38958351b6c5a3a7b5cec51a4 
on https://github.com/fatkaratekid/scipy_proceedings

2021-06-21 12:00 UTC, fatkaratekid commented on papers/ivan_nesic/claimed.rst
> +**E**\ TL and **D**\ ata Science which runs on top of ElyraAI capable of
How does this look to you 6021b270?

2021-06-21 12:55 UTC, fatkaratekid commented on papers/ivan_nesic/claimed.rst
> +usability side, both eager and graph modes are supported. Meaning
I hope this explains it better da6bc79c

2021-06-21 13:00 UTC, fatkaratekid commented
@romeokienzler 
Based on the examples from the repo, it seems it should look like this:
```
.. table:: This is the caption for the materials table. :label:`mtable`

   +------------+----------------+
   | Material   | Units          |
   +============+================+
   | Stone      | 3              |
   +------------+----------------+
   | Water      | 12             |
   +------------+----------------+
   | Cement     | :math:`\alpha` |
   +------------+----------------+
```

or this for a wide table
```
.. table:: This is the caption for the wide table.
   :class: w

   +--------+----+------+------+------+------+--------+
   | This   | is |  a   | very | very | wide | table  |
   +--------+----+------+------+------+------+--------+
```

I am not sure if there is a better way.

2021-06-21 13:08 UTC, fatkaratekid commented on papers/ivan_nesic/claimed.rst
> +.. figure:: elyra_pipeline.png
Just to understand correctly, you suggest the image should contain explanations like on the Elyra page you provided?
e.g. like this
![image](https://user-images.githubusercontent.com/2835130/122767013-77b7c800-d2a2-11eb-860f-4a20e35b5655.png)

2021-06-21 13:23 UTC, romeokienzler commented on papers/ivan_nesic/claimed.rst
> +RedHat, IBM is now 3rd largest committer to Kubernetes [ibmcncf]_.
Thanks! Let me put the following in if you are ok: 
For IBM, Kubernetes is also strategic. This is mainly because Kubernetes enables the hybrid cloud scenario backed by an
open source common runtime capable of transparently moving workload across different on-prem, remote and cloud data centers seamlessly. Besides acting as a Kubernetes runtime provider in the cloud and - through the aquisition of RedHat - becoming the major vendor for on-prem Kubernetes, IBM is now able to deliver software solution on top of Kubernetes, making them run everywhere. Therefore, IBM joined CNCF,  moved all Watson Services to Kubernetes and aquired RedHat. This makes IBM the 3rd largest committer to Kubernetes.

2021-06-21 13:28 UTC, fatkaratekid commented on papers/ivan_nesic/claimed.rst
> +experience went into it. The system can run on public, on-prem or on
thank you, changed to on-premises

2021-06-21 13:29 UTC, fatkaratekid commented on papers/ivan_nesic/claimed.rst
> +CNCF [cncf]_ by Google, which means a lot of Google’s know-how and years of
thanks for pointing it out

2021-06-21 13:29 UTC, fatkaratekid commented on papers/ivan_nesic/claimed.rst
> +It is the second incarnation of the Google Brain project’s scalable
much clearer, thanks

2021-06-21 13:31 UTC, fatkaratekid commented on papers/ivan_nesic/claimed.rst
> +black box. Technically (and mathematically) deep learning models are a
Thanks for pointing it out!

2021-06-21 15:00 UTC, romeokienzler commented
> `` .. table:: This is the caption for the materials table. :label:`mtable` ``

this also breaks the build

2021-06-21 15:07 UTC, romeokienzler commented on papers/ivan_nesic/claimed.rst
> +.. figure:: elyra_pipeline.png
I think it is too small. I've zoomed in and stripped away unnecessary parts - can you please have a [look](https://github.com/fatkaratekid/scipy_proceedings/commit/cb1332a6a970b8bdbd0f449cd53c08ca40c4ae15) now?

2021-06-21 16:51 UTC, fatkaratekid commented on papers/ivan_nesic/claimed.rst
> +isn’t in the required format. It’s just a folder full of images and
Thanks for taking the time to make these suggestions. I have rewritten the whole part to make it more readable. Please take a look at this commit e0ccca0

I hope it is now clear that we want to convert the data into the structure that can be consumed by TF's API.

2021-06-21 16:54 UTC, fatkaratekid commented on papers/ivan_nesic/claimed.rst
> +   De facto standard in folder structure for image classification data. :label:`imgdir`
This has been resolved by the same commit as the one above e0ccca0

2021-06-21 17:07 UTC, fatkaratekid commented on papers/ivan_nesic/claimed.rst
> +isn’t in the required format. It’s just a folder full of images and
A small modification to the text also done by the commit 6ccb03b

2021-06-21 19:18 UTC, romeokienzler commented on papers/ivan_nesic/claimed.rst
> +.. figure:: elyra_pipeline.png
commit cb1332a6a970b8bdbd0f449cd53c08ca40c4ae15

2021-06-21 19:23 UTC, romeokienzler commented on papers/ivan_nesic/claimed.rst
> +Pipeline Components
This section exemplifies each (currently existing) category with at least one component which has been used for this particular pipelines. There exist more components not part of this pipeline. The core feature of our software is threefold.

- the CLAIMED component library
- Elyra (which is developed in open source by the IBM team I'm working with) with it's capability to use CLAIMED to create a pipeline and push it to KubeFlow
- the pipeline itself

2021-06-21 19:30 UTC, romeokienzler commented on papers/ivan_nesic/claimed.rst
> +AI Fairness and Bias
removed artistic expressions in commit 7f77346902d39ff3e37e0b71fe7ba495b972d0d3

please let me know if this is what you've imagined

2021-06-21 19:35 UTC, romeokienzler commented on papers/ivan_nesic/claimed.rst
> +RedHat, IBM is now 3rd largest committer to Kubernetes [ibmcncf]_.
added to document in commit b76ef663e9fc7edffb5fa2b0b2f11a1632cf9c0b

2021-06-21 19:36 UTC, romeokienzler commented on papers/ivan_nesic/claimed.rst
> +it’s own. Training a deep learning image classification model requires a
addressed by 7f77346902d39ff3e37e0b71fe7ba495b972d0d3

2021-06-21 20:14 UTC, fatkaratekid commented
@deniederhut and @stsievert, thank you both for your feedback and your contribution. It really helped us a lot to turn this into a better paper. While we give you time to make sure we have addressed all of the points you have raised, we will go through the paper again and make sure that it flows correctly. After the review period is over or as soon as we have addressed all the issues, we will send the paper for the proofreading and make those final adjustments.

2021-06-23 10:40 UTC, deniederhut commented
@fatkaratekid to give everyone more time to respond to their reviews, we've pushed back the deadline for authors' final revisions to July 1st

2021-06-23 19:05 UTC, romeokienzler commented
@deniederhut, @cmarmo and @stsievert I think we are in good shape now - would you be able to have a 2nd look at the document please? @fatkaratekid

2021-06-25 18:50 UTC, cbcunc commented
@scoobies check references

2021-06-25 18:55 UTC, scoobies commented
Checking the BibTeX entries failed with the following error: 
```
Couldn't find bibliography entry
```

2021-06-27 22:04 UTC, deniederhut requested changes
At least four of the entries in the bibliography are citing a website instead of the appropriate paper. Please look through your references list and check the rest of the entries.

2021-06-27 22:04 UTC, deniederhut commented on papers/ivan_nesic/claimed.rst
> +.. [aif360] AI Fairness 360 Toolkit, https://github.com/Trusted-AI/AIF360. Last accessed 18 Feb 2021
Please cite this software: https://github.com/Trusted-AI/AIF360#citing-aif360

2021-06-27 22:04 UTC, deniederhut commented on papers/ivan_nesic/claimed.rst
> +.. [aix360] AI Explainability 360 Toolkit, https://github.com/Trusted-AI/AIX360 Last accessed 18 Feb 2021
Please cite this software: https://github.com/Trusted-AI/AIX360#citing-ai-explainability-360

2021-06-27 22:04 UTC, deniederhut commented on papers/ivan_nesic/claimed.rst
> +.. [jupyter] JupyterLab, https://jupyter.org/. Last accessed 18 Feb 2021
Please cite this software: https://github.com/jupyter/jupyter/issues/190#issuecomment-721264013

2021-06-27 22:04 UTC, deniederhut commented on papers/ivan_nesic/claimed.rst
> +.. [katib] Katib, https://github.com/kubeflow/katib. Last accessed 18 Feb 2021
Please cite this software: https://github.com/kubeflow/katib#citation

2021-06-28 13:54 UTC, fatkaratekid commented
@deniederhut work on all the mentioned issues. For some of these it is really hard (I dare to say impossible) to find a publication with a DOI or at least arXiv. But we'll give our best for sure. Thanks for pointing it out.

2021-06-28 13:55 UTC, fatkaratekid commented on papers/ivan_nesic/claimed.rst
> +.. [katib] Katib, https://github.com/kubeflow/katib. Last accessed 18 Feb 2021
done

2021-06-28 14:17 UTC, fatkaratekid commented on papers/ivan_nesic/claimed.rst
> +.. [jupyter] JupyterLab, https://jupyter.org/. Last accessed 18 Feb 2021
For Jupyter they recommend this Zenodo DOI: 10.5281/zenodo.4539666 at this link https://jupyterbook.org/cite.html. Maybe we should go for this one, it respects the contributors' wishes. It is not aesthetically nice as your suggestion though.

2021-06-28 14:39 UTC, fatkaratekid commented on papers/ivan_nesic/claimed.rst
> +.. [jupyter] JupyterLab, https://jupyter.org/. Last accessed 18 Feb 2021
thanks for the ref

2021-06-28 14:40 UTC, fatkaratekid commented on papers/ivan_nesic/claimed.rst
> +.. [aix360] AI Explainability 360 Toolkit, https://github.com/Trusted-AI/AIX360 Last accessed 18 Feb 2021
fix it, thanks

2021-06-28 21:24 UTC, cmarmo reviewed
Thanks a lot to the authors for your work on the proceeding: I find it clearer and easier to read, now.
I still have some comments about its first part, that I have detailed below.
I have not found the time to recheck the use case and the conclusions. I will do it ASAP. Sorry for that.

2021-06-28 21:24 UTC, cmarmo commented on papers/ivan_nesic/claimed.rst
> +   For this purpose, we made use of a publicly available CT scans dataset [covidata]_
Computed Tomography (CT) scans... ?

2021-06-28 21:24 UTC, cmarmo commented on papers/ivan_nesic/claimed.rst
> +or Cromwell [cromwell]_.
This is an impressive list of tools, but I'm missing the information about why they are needed.
The answer is indeed in the next paragraph.
Perhaps it could be of help to clarify the production requirements first, then list the number of available tools. This will show how complex the picture is because of the requirements and how useful is a tool like the one you propose.

2021-06-28 21:24 UTC, cmarmo commented on papers/ivan_nesic/claimed.rst
> +Technology breakdown
I like the choice for the title of this section.
My understanding is that a list of critical concepts for the implementation will follow: containerization, deep learning, ..., explainability, fairness.
Do you mind making more explicit what types of technology breakdown are covered by Kubeflow, Elyra, JupyterLab? In particular, is JupyterLab covering a technology breakdown or its place is more in the implementation part, among the requirements? As listed here
https://github.com/scipy-conference/scipy_proceedings/blob/e03cec9ff666247c8dff59bac975358198ea567d/papers/ivan_nesic/claimed.rst#L304-L316

2021-06-28 21:24 UTC, cmarmo commented on papers/ivan_nesic/claimed.rst
> +Kubernetes.
May I suggest to short sentences for readability?
Something like (I'm using github suggestions to make the diff explicit, not to feed you with my words... :) )
```suggestion
IBM acts as a Kubernetes runtime provider in the cloud and - 
through the acquisition of RedHat - has become the major vendor for 
on-premises Kubernetes. IBM is now able to deliver software solutions
- so called "Cloud Paks" - on top of Kubernetes, making them run everywhere.
Therefore, IBM joined CNCF [ibmcncf]_, and moved all Watson Services to Kubernetes.
This makes IBM the 3rd largest committer to Kubernetes.
```

2021-06-29 08:05 UTC, romeokienzler commented on papers/ivan_nesic/claimed.rst
> +   For this purpose, we made use of a publicly available CT scans dataset [covidata]_
thanks, fixed in 1f4d6f9459c2a7a4a2ba955ae34bacf28ba29323

2021-06-29 13:46 UTC, deniederhut commented
> For some of these it is really hard (I dare to say impossible) to find a publication with a DOI or at least arXiv.

Yeah, totally -- not everyone writes publications about their software, and even recent conference papers don't always get DOIs. You won't be able to find a good citation for everything, but we want to make our best effort, because it's important to recognize and celebrate the good work that others do.

2021-06-29 14:20 UTC, romeokienzler commented on papers/ivan_nesic/claimed.rst
> +or Cromwell [cromwell]_.
Thanks a lot for the suggestion. We've addressed your comment in 34778253a0fac2000650dd4bee1f8823e6a7f89d

2021-06-29 14:33 UTC, romeokienzler commented on papers/ivan_nesic/claimed.rst
> +Kubernetes.
Thanks, we've shortened in 9fbd4aee47d5ee0b5aae58376bbf659d7cef0aa5 to 

IBM acts as a Kubernetes runtime provider in the cloud and - 
through the acquisition of RedHat - has become the major vendor for 
on-premises Kubernetes. IBM is now able to deliver software solutions - so 
called "Cloud Paks" - on top of Kubernetes, making them run everywhere **(hybrid cloud)**.
Therefore, IBM joined CNCF [ibmcncf]_, and moved all Watson Services to Kubernetes.
This makes IBM the 3rd largest committer to Kubernetes.
**Not only for IBM but also for us, Kubernetes enables the hybrid cloud scenario of 
transparently moving workload
across different on-premises, remote and cloud data centers seamlessly.**

Just added "hybrid cloud" to your suggestion and a sentence at the bottom to close the loop of requirements to our use case as well.

2021-06-29 16:47 UTC, romeokienzler commented on papers/ivan_nesic/claimed.rst
> +Technology breakdown
Thanks a lot, we addressed your concerns in c39b989e070c5ca8d1e5dc35c7e7aa2a418d534e - please let us know it it fits to what you had in mind

2021-06-29 17:30 UTC, cmarmo approved these changes
@fatkaratekid @romeokienzler thanks a lot for your work.
Two nitpicks and one typo, are my last comments.
Looking forward to see your contribution published.

2021-06-29 17:30 UTC, cmarmo commented on papers/ivan_nesic/claimed.rst
> +component - in the example, we just used it to change to format of the
```suggestion
component - in the example, we used it to change to format of the
```

2021-06-29 17:30 UTC, cmarmo commented on papers/ivan_nesic/claimed.rst
> +simply specifying a column name and a function that is to be applied.
```suggestion
specifying a column name and a function that is to be applied.
```

2021-06-29 17:30 UTC, cmarmo commented on papers/ivan_nesic/claimed.rst
> +C3 already suports publishing components to Machine Learning Exchange (MLX) [mlx]_, an open source
```suggestion
C3 already supports publishing components to Machine Learning Exchange (MLX) [mlx]_, an open source
```

2021-06-29 17:36 UTC, romeokienzler commented on papers/ivan_nesic/claimed.rst
> +C3 already suports publishing components to Machine Learning Exchange (MLX) [mlx]_, an open source
sorry for that! fixed in 4c88ad49c34d4fcf39b600e31add50d8e2d56c91

2021-06-29 17:36 UTC, romeokienzler commented on papers/ivan_nesic/claimed.rst
> +component - in the example, we just used it to change to format of the
thanks! fixed in 4c88ad49c34d4fcf39b600e31add50d8e2d56c91

2021-06-29 17:36 UTC, romeokienzler commented on papers/ivan_nesic/claimed.rst
> +simply specifying a column name and a function that is to be applied.
thanks! fixed in 4c88ad49c34d4fcf39b600e31add50d8e2d56c91

2021-06-30 10:59 UTC, fatkaratekid commented
@scoobies check references

2021-06-30 11:00 UTC, scoobies commented
```
Reference check summary (note 'MISSING' DOIs are suggestions that need verification):

OK DOIs

- 10.3233/978-1-61499-649-1-87 is OK
- 10.1093/nar/gky379 is OK
- 10.1051/epjconf/201921406034 is OK
- 10.1093/bioinformatics/bts480 is OK
- 10.1109/ITHET.2017.8067827 is OK
- 10.1109/PDSW-DISCS.2018.00011 is OK
- 10.1109/SEAA51224.2020.00036 is OK

MISSING DOIs

- 10.1007/10968987_3 may be a valid DOI for title: SLURM: Simple Linux Utility for Resource Management
- 10.1007/978-3-030-19504-5_13 may be a valid DOI for title: Citizen Data Scientist: A Design Science Research Method for the Conduct of Data Science Projects

INVALID DOIs

- None
```

2021-06-30 11:07 UTC, fatkaratekid commented
I checked the 'missing' two and they are valid.

2021-06-30 13:22 UTC, deniederhut commented
Awesome! @stsievert do you feel this paper is now ready for inclusion in the proceedings?

2021-07-03 18:06 UTC, deniederhut approved these changes

2021-07-03 18:07 UTC, deniederhut commented
@scoobies mark ready

2021-07-05 16:01 UTC, merged

2021-07-06 15:21 UTC, fatkaratekid commented
@deniederhut Is it still possible to make minor modifications (fix typos and some reference formatting for instance )? If yes, I suppose this is to be done with a PR?