ADI Paper Submission: 1st Draft
scipy-conference/scipy_proceedings pull request #631
Opened 2021-05-28 16:21 UTC by cristina-suteu

Added first draft of Analog Devices, Inc. paper

title: Using Python for Analysis and Verification of Mixed-mode Signal
Chains for Analog Signal Acquisition

authors: Mark Thoren, Cristina Suteu

Signed-off-by: Cristina Suteu <cristina.suteu@analog.com>

If you are creating this PR in order to submit a draft of your paper,
see http://procbuild.scipy.org/ for logs generated by the build
process.

See the [project readme](https://github.com/scipy-conference/scipy_proceedings#build-your-paper)
for more information.

*Editor*:  

*Reviewers*:

2021-05-28 16:22 UTC, scoobies commented
Hi!, I'm @scoobies, a friendly bot.

Type ```@scoobies help``` to discover how I can help you.

2021-05-29 00:29 UTC, deniederhut commented
@scoobies assign @stargaser as editor

2021-05-29 00:29 UTC, scoobies commented
Assigned! @stargaser is now the editor

2021-05-29 14:03 UTC, deniederhut commented
@scoobies build status

2021-05-29 14:03 UTC, scoobies commented
{"cristina-suteu-2021"=>{"data"=>{"build_output"=>"[*] Updating proceedings build tools in {self.master_repo_path}...\nAlready up to date.\n[*] Check out paper repository...\nCloning into '/tmp/tmpfbx22cwy'...\nMoving proceedings build tools to temp directory...\n[*] Build the paper...\nBuilding: adi_sdg\nTraceback (most recent call last):\n  File \"publisher/build_paper.py\", line 237, in <module>\n    build_paper(paper_id)\n  File \"publisher/build_paper.py\", line 222, in build_paper\n    rst2tex(in_path, out_path)\n  File \"publisher/build_paper.py\", line 92, in rst2tex\n    settings_overrides=settings)\n  File \"/procbuild_env/lib/python3.6/site-packages/docutils/core.py\", line 416, in publish_string\n    enable_exit_status=enable_exit_status)\n  File \"/procbuild_env/lib/python3.6/site-packages/docutils/core.py\", line 664, in publish_programmatically\n    output = pub.publish(enable_exit_status=enable_exit_status)\n  File \"/procbuild_env/lib/python3.6/site-packages/docutils/core.py\", line 219, in publish\n    output = self.writer.write(self.document, self.destination)\n  File \"/procbuild_env/lib/python3.6/site-packages/docutils/writers/__init__.py\", line 80, in write\n    self.translate()\n  File \"/procbuild_env/lib/python3.6/site-packages/docutils/writers/latex2e/__init__.py\", line 242, in translate\n    self.document.walkabout(visitor)\n  File \"/procbuild_env/lib/python3.6/site-packages/docutils/nodes.py\", line 174, in walkabout\n    if child.walkabout(visitor):\n  File \"/procbuild_env/lib/python3.6/site-packages/docutils/nodes.py\", line 174, in walkabout\n    if child.walkabout(visitor):\n  File \"/procbuild_env/lib/python3.6/site-packages/docutils/nodes.py\", line 174, in walkabout\n    if child.walkabout(visitor):\n  File \"/procbuild_env/lib/python3.6/site-packages/docutils/nodes.py\", line 166, in walkabout\n    visitor.dispatch_visit(self)\n  File \"/procbuild_env/lib/python3.6/site-packages/docutils/nodes.py\", line 1882, in dispatch_visit\n    return method(node)\n  File \"/tmp/tmpfbx22cwy/publisher/writer/__init__.py\", line 436, in visit_literal_block\n    lexer = get_lexer_by_name(node.attributes['language'])\n  File \"/procbuild_env/lib/python3.6/site-packages/pygments/lexers/__init__.py\", line 118, in get_lexer_by_name\n    raise ClassNotFound('no lexer for alias %r found' % _alias)\npygments.util.ClassNotFound: no lexer for alias 'ipython3' found\nError building paper /tmp/tmpfbx22cwy/papers/adi_sdg. Aborting.\n[X] Error code 1\nA build error occurred during the self.run_make_paper_script step.", "build_pdf_path"=>"", "build_status"=>"Build failed, make_paper.sh did not succeed", "build_timestamp"=>"29/05 14:02"}, "status"=>"fail"}}

2021-05-29 14:05 UTC, deniederhut commented
> no lexer for alias 'ipython3'

This probably means that one or more of the code blocks should have `python` instead of `ipython3`

2021-05-31 14:29 UTC, deniederhut commented
@scoobies add @nfcastro to reviewers

2021-05-31 14:29 UTC, scoobies commented
@nfcastro added to the reviewers list!

2021-05-31 14:31 UTC, deniederhut commented
Hi @cristina-suteu ! Have you had a chance to look at the code block coloration issue yet?

2021-05-31 14:36 UTC, nfcastro commented
Dear all,

Looks like I will be reviewing you contribution. I will get back to you with my comments as soon as possible.

2021-05-31 15:21 UTC, mthoren-adi commented
> Dear all,
> 
> Looks like I will be reviewing you contribution. I will get back to you with my comments as soon as possible.

Hi @nfcastro , @deniederhut,
@cristina-suteu  and I are indeed looking into the code coloration issue (and have a fix, along with some other minor fixes) and will push an update shortly.

2021-05-31 19:34 UTC, deniederhut commented
Thanks!

On May 31, 2021, ivan-marroquin ***@***.***> wrote:
> > Dear all,
> >
> > Looks like I will be reviewing you contribution. I will get back to
> > you with my comments as soon as possible.
> >
>
> Hi @nfcastro <https://github.com/nfcastro> , @deniederhut
> <https://github.com/deniederhut>,
> @cristina-suteu <https://github.com/cristina-suteu> and I are indeed
> looking into the code coloration issue (and have a fix, along with
> some other minor fixes) and will push an update shortly.
>

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub
<https://github.com/scipy-
conference/scipy_proceedings/pull/631#issuecomment-851556839>, or
unsubscribe <https://github.com/notifications/unsubscribe-
auth/ABUM3LECBDJJJFMN3WTVFSLTQOSRJANCNFSM45W75FDA>.

2021-06-02 13:34 UTC, deniederhut commented
@scoobies add @matthewfeickert to reviewers

2021-06-02 13:34 UTC, scoobies commented
@matthewfeickert added to the reviewers list!

2021-06-03 21:45 UTC, stargaser commented
@cristina-suteu @mthoren-adi  I checked out your branch and was able to build it locally after making a number of edits. These fall into three categories:

1. markup for authors (names, emails, institutions) 
2. markup for the title and the reference section
3. unicode characters for "square root" and "sigma"

Have you already made those changes? I could push my edited `.rst` file to a branch in my own area if that would be helpful. We would like to get this paper to compile on the build server.

2021-06-06 15:30 UTC, mthoren-adi commented
@stargaser , 
> Have you already made those changes? I could push my edited `.rst` file to a branch in my own area if that would be helpful. We would like to get this paper to compile on the build server.

That would indeed be super helpful!

Any comments on the content so far?

Also - we have our eyes on the schedule (June 24 final decision?) We are still doing some analog debug of our noise generator (hence the note on Figure 3).

2021-06-06 20:53 UTC, stargaser commented
I pushed a branch with the updated `.rst` file and it is available at https://github.com/stargaser/scipy_proceedings/blob/paper_adi/papers/adi_sdg/adi_scipycon_pynotebook.rst

2021-06-06 21:30 UTC, stargaser commented
A diff is better: https://github.com/cristina-suteu/scipy_proceedings/compare/2021...stargaser:paper_adi 

For the Unicode √Hz I put simply `sqrt(Hz)` but one would want LaTeX math markup. That would be a refinement -- we want to get the paper building so that the reviewers can look at the PDF, to make comments on the content.

2021-06-07 23:40 UTC, deniederhut commented
We've been having difficulty finding reviewers for some papers, so to make sure everyone has enough time to do their reviews, we will be bumping the deadline for the initial review back to June 17th.

2021-06-08 13:31 UTC, cristina-suteu commented
@stargaser thank you for your edits. I've pushed the updated version of the .rst file, with the edits you made. Let us know it there's any other issue.

2021-06-08 17:11 UTC, stargaser commented
@scoobies build status

2021-06-08 17:12 UTC, scoobies commented
{"cristina-suteu-2021"=>{"data"=>{"build_output"=>"[*] Updating proceedings build tools in {self.master_repo_path}...\nAlready up to date.\n[*] Check out paper repository...\nCloning into '/tmp/tmpcn7h0sbk'...\nMoving proceedings build tools to temp directory...\n[*] Build the paper...\n/tmp/tmpcn7h0sbk/publisher/writer/__init__.py:288: RuntimeWarning: Title set twice--ignored. Could be due to ReSTerror.)\n  warnings.warn(RuntimeWarning('Title set twice--ignored. '\nBuilding: adi_sdg\nTraceback (most recent call last):\n  File \"publisher/build_paper.py\", line 237, in <module>\n    build_paper(paper_id)\n  File \"publisher/build_paper.py\", line 222, in build_paper\n    rst2tex(in_path, out_path)\n  File \"publisher/build_paper.py\", line 92, in rst2tex\n    settings_overrides=settings)\n  File \"/procbuild_env/lib/python3.6/site-packages/docutils/core.py\", line 416, in publish_string\n    enable_exit_status=enable_exit_status)\n  File \"/procbuild_env/lib/python3.6/site-packages/docutils/core.py\", line 664, in publish_programmatically\n    output = pub.publish(enable_exit_status=enable_exit_status)\n  File \"/procbuild_env/lib/python3.6/site-packages/docutils/core.py\", line 219, in publish\n    output = self.writer.write(self.document, self.destination)\n  File \"/procbuild_env/lib/python3.6/site-packages/docutils/writers/__init__.py\", line 80, in write\n    self.translate()\n  File \"/procbuild_env/lib/python3.6/site-packages/docutils/writers/latex2e/__init__.py\", line 242, in translate\n    self.document.walkabout(visitor)\n  File \"/procbuild_env/lib/python3.6/site-packages/docutils/nodes.py\", line 187, in walkabout\n    visitor.dispatch_departure(self)\n  File \"/procbuild_env/lib/python3.6/site-packages/docutils/nodes.py\", line 1895, in dispatch_departure\n    return method(node)\n  File \"/tmp/tmpcn7h0sbk/publisher/writer/__init__.py\", line 175, in depart_document\n    corr_emails.append(self.author_emails[n])\nIndexError: list index out of range\nError building paper /tmp/tmpcn7h0sbk/papers/adi_sdg. Aborting.\n[X] Error code 1\nA build error occurred during the self.run_make_paper_script step.", "build_pdf_path"=>"", "build_status"=>"Build failed, make_paper.sh did not succeed", "build_timestamp"=>"07/06 23:45"}, "status"=>"fail"}}

2021-06-08 19:01 UTC, stargaser commented
@scoobies build status

2021-06-08 19:01 UTC, scoobies commented
{"cristina-suteu-2021"=>{"data"=>{"build_output"=>"[*] Updating proceedings build tools in {self.master_repo_path}...\nFrom https://github.com/scipy-conference/scipy_proceedings\n   750ad71..dbe4240  2021       -> origin/2021\nUpdating 750ad71..dbe4240\nFast-forward\n README.md | 6 +++---\n 1 file changed, 3 insertions(+), 3 deletions(-)\n[*] Check out paper repository...\nCloning into '/tmp/tmpib0zqt70'...\nMoving proceedings build tools to temp directory...\n[*] Build the paper...\nBuilding: adi_sdg\n*** Warning: /tmp/tmpib0zqt70/publisher/../output/adi_sdg/paper_stats.json does not exist.\n", "build_pdf_path"=>"/procbuild/procbuild/../cache/cristina-suteu-2021.pdf", "build_status"=>"success", "build_timestamp"=>"08/06 18:57"}, "status"=>"success"}}

2021-06-08 19:58 UTC, stargaser commented
@cristina-suteu thanks for the changes. The paper builds now and the symbols (especially for square roots) look good. The PDF is available [here](https://procbuild.scipy.org/download/cristina-suteu-2021); I just had to press the refresh button on the procbuild.scipy.org page.

Editorially speaking, the paper is 10.5 pages and our page limit is 8, not incuding references. There are many figures in the paper and the formatting needs some attention; I also suspect a few can be removed. The code snippets should be formatted to fit inside a single columns without overflow. The reviewers may have some recommendations of what can be removed.

For the schedule, we've reset the review due date to June 17th as noted here already.

2021-06-10 02:26 UTC, mthoren-adi commented
@stargaser  Thanks for the comments - all noted. We'll start in on the cleanup shortly. And there are indeed several passages that can be trimmed back or deleted.

2021-06-11 21:58 UTC, stargaser commented
Hi @nfcastro,  @matthewfeickert just a friendly reminder that the initial review deadline is next week.

2021-06-11 22:37 UTC, nfcastro commented
Thanks for the reminder, @stargaser - it's not forgotten

2021-06-14 07:36 UTC, matthewfeickert commented
Thanks for your submission of your paper @cristina-suteu.

I have multiple comments and revisions that I think need to be addressed before it could be published, so I will focus on those here so that they can be addressed for another review.
My comments will focus on different areas from the [Suggested Review Criteria for SciPy Proceedings](https://github.com/scipy-conference/scipy_proceedings/blob/2021/review_criteria.md) and I will try to rank them in order of importance of addressing for revision.
As the paper will require large revisions I will refrain from making line by line comments until a revised draft is available.

I am a physicist and not an expert in electronics and signal processing, so my comments will focus on the structure and narrative of the paper.

## Length

> The compiled version should be no longer than 8 pages, including figures, source code, appendices. References are excluded from this limit.

The current draft is 11 pages long with only 7 references, so 3 full pages of the paper will need to be removed.
This qualifies as a substantial rewrite of the paper, so I'd encourage you to try to refocus on what ideas you're trying to communicate.

## Written Quality

The paper suffers from formatting and writing issues throughout that make the paper difficult to follow:

- The paper should strive to clearly communicate work done or new ideas with a clear narrative. At the moment, the paper reads more like a running summary of the examples mentioned in the introduction without a clear narrative.
This is not meant to detract from the work or the quality of the examples, but simply point out that the form of a paper should be cohesive.
- The paper has self notes to the authors that were not removed before submission, and placeholder text that was not revised. Examples: The text "verify" on page 3, the text "DO NOT OMIT THIS" at the bottom of page 8, and "Figure X" on page 2. Please proofread the paper before the next submission.
- Jargon is used throughout the paper. There are instances where terms have not been defined (ADC is defined, but DAC is not) and there are also instances in which jargon is uses with no reference or context (e.g. `rpi-ad7124-8-all-diff-cs0-int25`). This happens repeatedly and makes it very difficult to follow the paper.
- In mathematical equations do not mix code and mathematics. For example, do not use `np.sqrt` when you mean to use typeset a radical sign in mathematics.
- Cleaner typesetting of mathematical formula would be appreciated outside of an inline environment. If referring to a mathematical equation it should be typeset by itself, and if referring to mathematical variables (like `N`) they should be typeset in a way to distinguish them from the rest of the text body.
- All code that is uses in the paper should be properly referenced. There are no citations to any code used, though many of them have papers and clear citation guidelines on their websites.
- Some code is mentioned by file name and linked to in a GitHub repository. However, the links are not permalinks to specific Git commit hashes and so are not sufficient for reference. A much preferable solution would be to archive the source code on Zendo (https://zenodo.org/) and receive a DOI for the source code which can be cited. Additionally, instead of trying to describe the actions of individual scripts by file name it would be preferable to describe the results of code rather then the running of it.
- Any data that is presented should be made clear if it is data that was taken from another source (and cited appropriately), simulation produced for an example, or if it is arbitrarily constructed data that exists only for example purposes. The data described on page 7 and shown in Figure 21 are an example of this.
- Use of "etc." should be avoided. In most cases in a scientific paper any list of items or conditions that are being iterated through will not be obvious/mundane enough or long enough to warrant the use of "etc.". Clearly state what you mean in terms of limitations or uncertainties.
- Acronyms should be spelled out upon first mention and they should be mentioned by their full name first with the acronym in parentheses after. For example, "analog to digital converter (ADC)".
- Punctuation should be used consistently. An en dash (&ndash;) is used to connect ranges of numbers or words. An em dash (&mdash;) is used to separate a sentence into distinct sections or to communicate an aside and can be an alternative to using commas or parentheses to separate an independent clause.
En dashes should not be used when a comma or colon is required.
These definitions are very short and incomplete ones for the sake of illustrating their different usage. Please look up better and fuller definitions and examples in your favorite writing reference as I am by no means a trusted reference.

## Figures

- All figures have figure captions that are too short and are essentially plot titles.
A figure caption should provide the necessary context and detail to a reader for them to understand the importance of the figure to the text and the details of the figure, without describing every detail of the figure or simply duplicating the text of the paper.
As there are many figures throughout the paper and all of them need revised figure captions I would recommend selecting only those figures that are critical to the paper's narrative, improving their captions, and removing all other figures.
This will necessarily drastically change the paper's content.

- It appears that not all of the figures in the paper were made by the authors.
For example, Figures 5, 8, 9, 10, 16, 17, 20, and 22 all seem to be screenshots of figures from other work that is not cited, or contain elements from other work.
All figures and elements taken from other work, even work by the authors, must be properly cited in the text and not just as listed references.

- Figures overlap with text throughout the paper making it hard to read.
Each figure should be formatted so that it cleanly exists in the confines of its column.

- There are multiple figures that are screenshots of the `matplotlib` interactive gui. Unless there is something shown in the gui window that is mentioned in the figure caption it would be preferable to save the figure itself out instead of taking a screenshot. This will help focus the figure on the contents, provide a higher resolution image, and make the point of the figure more understandable.

- Figures that contain multiple subfigures or subplots should indicate the contents of each.

## Verifiability

As was mentioned before, it would be beneficial if the source code was archived on Zenodo so that a DOI can be issued for it. Ideally both a GitHub release of the code and the Zenodo DOI should be cited in the references, though at least one is required. Similarly, all data used in examples not generated by the user must be cited.

## Code Snippets

- Code snippets should be formatted to fit inside a single column without overflow. At the moment all code segments do not fit inside their column width and run into other text or figures.

- Code segments should ideally be given a listing number in a similar fashion to how tables or figures are given numbers. This allows for easier referencing in the text and for the reader.

- Code snippets should be short and illustrative. Longer pieces of code should have their source reference cited. For example, the code shown on pages 2 and 3 should either be reduced to the most relevant sections or it should be removed and cited instead.

2021-06-14 20:25 UTC, mthoren-adi commented
Hi @matthewfeickert , thank you for the thorough review and constructive criticism. We'll address the length and structure / narrative first, ASAP. This submission was originally accepted as a poster, so if it doesn't hold up as a paper within the next review cycle, we can revert back to poster only.

2021-06-14 22:33 UTC, matthewfeickert commented
> We'll address the length and structure / narrative first, ASAP. This submission was originally accepted as a poster, so if it doesn't hold up as a paper within the next review cycle, we can revert back to poster only.

Sounds good @mthoren-adi! Let us know where we can help. :+1:

2021-06-17 11:43 UTC, deniederhut commented
@scoobies mark needs more review

2021-06-17 17:27 UTC, nfcastro commented
Thanks for your submission of your paper @cristina-suteu.

Like @matthewfeickert, I am a  physicist so I make a similar disclaimer. I will try to repeat @matthewfeickert comments, but I agree to them.

Shall you require further input at this stage, don't hesitate to ask for it.

## Written Quality

- I will postpone more detailed comments for a later stage (i.e. after the rewritting required to keep the paper within the limits);
- please focus on the message you want to pass rather than listing examples;
- use a proper typesetfor all equations;
- the formatting needs to be worked out: figures are unbalanced in size and often go out of the margings (and the same applies to the code examples);
- please avoid the use of jargon.

## Technical Content

- The technical and computational content is adequate;
- The work is within the scope of the conference.


## Verifiability

- I subscribe to @matthewfeickert comment on the code availability and proper citation.


### Length

- A significant re-writting will be required to keep the paper within limits. In an attempt to help, I have the following suggestions:

-- consider if all the figures are really needed (and show only the plot, avoiding the menu which appears in some of them)
-- avoid showing the full code and focus on relevant snippets
-- evaluate if you need all the examples being given

### Figures

- Several captions missing or require being expanded.
- Some figures are too small to be readable (and some are unnecessarily large)

2021-06-17 17:43 UTC, stargaser commented
@scoobies mark pending comment

2021-06-17 17:44 UTC, stargaser commented
Many thanks for your reviews, @matthewfeickert and @nfcastro.

2021-06-21 20:23 UTC, mthoren-adi commented
Hi @nfcastro , @matthewfeickert , we're making progress on the rewrite and should have the pull request updated within a day.

2021-06-22 16:34 UTC, cristina-suteu commented
Hello @nfcastro, @matthewfeickert. PR updated with our next iteration. We rearranged things to improve the narrative flow, and addressed most of the concerns.
If the content meets your requirements and is headed in the right direction, we will address the following remaining items:
Length Still spills over to 9 pages - more concise language in a few locations will fix that.
Figure captions - more detail
Figure sizing / scaling
Figure citations - some do come from datasheets, we'll reference those.
Figures themselves - legibility on Figure 1, 4, 17 (axis labels), 21 (axis labels), 22 (axis labels)
Matplotlib figures - retake as saved graphic, or at least trim extraneous information.
References to code - we'll include a specific git commit, and look at Zendo (not familiar with Zendo, but looks straightforward.)
Again, if this does **not** hold up as a paper, no problem to do as a poster only (which we're working on simultaneously). We have several additional outlets for this, both internally, and as public-facing educational material.

2021-06-23 10:46 UTC, deniederhut commented
@cristina-suteu to give everyone more time to respond to their reviews, we've pushed back the deadline for authors' final revisions to July 1st

@nfcastro and @matthewfeickert -- have Cristina's updates addressed the items in your review?

2021-06-23 10:47 UTC, nfcastro commented
@deniederhut : I will try to give feedback by tomorrow.

2021-06-25 14:56 UTC, nfcastro commented
Dear @cristina-suteu 

I find the paper to be significantly improved, but the text has not yet a fully coherent message since in several places examples are listed without much context. Maybe you could drop some of the examples and focus on the message you would like to convey?

Please find my detailed comments below:

- Figures, in general, would benefit from some uniformization in style and the same applies to its captions (always end with .; some captions are still a bit criptic). And I'm not sure that you need all the figures.
- Fig. 3 is too small to be readable. Consider if you need to to keep it and, if yes, increase the size of it.
- p.2, left column: the second list of items doesn't seem to be properly aligned ("σ is the standard..." is not a separate item, but the continuation of the previous, right?).
- Fig 7 would benefit from some improvement (only the figure and not the menu should be shown). Same for Fig. 9.
- Section "Expressing ADC Noise as a Density" should be improved since now it's more a list of items than a real section with a description for the reader. For example (but there are more of these), in p.4, left column: "Do not omit this resistor." (in bold) looks a bit out of the blue to me. Please motivate it better.
- Fig. 20 is way too small.
- p.7: the code is not yet fitting within the column.
- the conclusion could be improved.

I hope you find these comments useful.

2021-06-28 15:23 UTC, cristina-suteu commented
thanks for your comments @nfcastro. we'll update the paper and have a new version up within a couple of days

2021-06-28 17:34 UTC, matthewfeickert commented
> @nfcastro and @matthewfeickert -- have Cristina's updates addressed the items in your review?

I'll review tonight but my guess is that @nfcastro's comments will capture most of my thoughts.

2021-06-29 06:45 UTC, matthewfeickert commented
Hi @deniederhut (and sorry all for the delay). Essentially all of my comments and revision suggestion that I [posted in my first review](https://github.com/scipy-conference/scipy_proceedings/pull/631#issuecomment-860457853) have not been addressed in the revision. If the authors want to address these issues then I'm happy to review it again, but given that this paper still needs substantial work I'd suggest that they maybe consider their proposed poster

> Again, if this does not hold up as a paper, no problem to do as a poster only (which we're working on simultaneously). We have several additional outlets for this, both internally, and as public-facing educational material.

instead. I appreciate that time is short here and that it might not be feasible for the authors to attempt to address all comments and revisions in the time remaining. If any of my comments aren't clear or are too vague my apologies &mdash; that's on me &mdash; I will do my best to clarify.

2021-06-29 13:54 UTC, cristina-suteu commented
Hi, @matthewfeickert. We're having another go at addressing the final issues and have another version of the paper up within two days. If that will not fit the requirements, then we'll stick to our original poster idea. Thanks @matthewfeickert, @nfcastro for your comments.

2021-06-29 16:36 UTC, stargaser commented
We're looking forward to the next revision, @cristina-suteu.  I recommend to address comments in priority order as laid out by the reviewers since it might not be possible to get to all of them.

Perhaps the message is that ADCs are now thermal-noise-limited and these are the appropriate techniques to use with them?

2021-07-01 16:10 UTC, cristina-suteu commented
hello, @matthewfeickert  @nfcastro. @mthoren-adi and I have reviewed our paper and updated it based on your suggestions. We hope that we have addressed most of the issues.

2021-07-02 17:15 UTC, mthoren-adi commented
Hello reviewers, I see that the build system indicates success with a date of July 2, but the PDF doesn't seem to reflect the updates. We were able to build locally, perhaps there's a delay?

2021-07-02 21:20 UTC, stargaser commented
@mthoren-adi we rebuilt all the papers this morning after an unplanned server downtime. I see changes in the PDF, are these not what you see after building locally?

2021-07-02 21:38 UTC, mthoren-adi commented
@stargaser , looks good now! A couple of hours ago it was showing the old version (PR was updated yesterday.)
Thanks!

2021-07-03 03:33 UTC, stargaser reviewed
The paper is much improved. There are still some issues with citing software and properly citing figures that are drawn from datasheets. I've made comments in-line for those.

The proceedings co-chairs discussed the state of this paper today. We appreciate the efforts made by the authors. The paper has come together late for the pre-conference publication, but remaining issues can be addressed for the final conference proceedings which will be published by end of July. Let me note that this happened to my own SciPy paper in 2018 so it is not something to be alarmed about.

2021-07-03 03:33 UTC, stargaser commented on papers/adi_sdg/adi_scipycon_pynotebook.rst
> +   AD7124 output noise. PGA-gain=1(left), PGA-gain=128(right)
Please explicitly cite here the AD7124 datasheet. I found it at https://www.analog.com/media/en/technical-documentation/data-sheets/ad7124-8.pdf

2021-07-03 03:33 UTC, stargaser commented on papers/adi_sdg/adi_scipycon_pynotebook.rst
> +Modeling the noise of a thermal-noise limited ADC’s is straightforward. If the noise is “well behaved” (Gaussian, as it is in Figure :ref:`ad7124hist`) and constant across the ADC’s input span, the A
Please cite Numpy per https://www.scipy.org/citing.html#numpy

2021-07-03 03:33 UTC, stargaser commented on papers/adi_sdg/adi_scipycon_pynotebook.rst
> +The AD7124 device driver falls under the industry-standard Industrial Input-Output (IIO) framework, which has a well-established software API (including Python bindings). Application code can run loc
I don't think there is a doi for the pyadi-iio package but I think a URL reference is appropriate, either to https://wiki.analog.com/resources/tools-software/linux-software/pyadi-iio or to the repository https://github.com/analogdevicesinc/pyadi-iio

2021-07-03 03:33 UTC, stargaser commented on papers/adi_sdg/adi_scipycon_pynotebook.rst
> +   Initial Warmup.
The time order of the curves is top to bottom, right? It would help to expand the caption though now I see this is explained in the text.

2021-07-03 03:33 UTC, stargaser commented on papers/adi_sdg/adi_scipycon_pynotebook.rst
> +ADC datasheets typically do not include a noise densitcy specification, but expressing the ADC's noise as a density allows it to be directly compared to the noise at the output of the last element in
typo "densitcy" -> "density"

2021-07-03 03:33 UTC, stargaser commented on papers/adi_sdg/adi_scipycon_pynotebook.rst
> +While Scopy is useful for single, visual measurements, the functionality can be replicated easily with the scipy.signal.periodogram function. Raw data is collected from an ADALM2000 using the libm2k
Please cite SciPy per https://www.scipy.org/citing.html#scipy-the-library

2021-07-03 03:33 UTC, stargaser commented on papers/adi_sdg/adi_scipycon_pynotebook.rst
> +LTspice is a freely available, general-purpose analog circuit simulator that can be applied to signal chain design. It can perform transient analysis, frequency-domain analysis (AC sweep), and noise
I don't think there is a DOI for LTspice, so perhaps a URL reference to https://www.analog.com/en/design-center/design-tools-and-calculators/ltspice-simulator.html is appropriate?

2021-07-03 03:33 UTC, stargaser commented on papers/adi_sdg/adi_scipycon_pynotebook.rst
> +This function can be verified by controlling one ADALM2000 through a libm2k script, and verifying the noise profile with a second ADALM2000 and the spectrum analyzer in the Scopy GUI. The Push Noise
Scopy is introduced here but I am not sure what it is or if a software citation is needed?

2021-07-03 03:33 UTC, stargaser commented on papers/adi_sdg/adi_scipycon_pynotebook.rst
> +   AD7124-8 10Hz notch filter.
This figure and the next two come from the AD7124 datasheet -- please cite that explicitly.

2021-07-03 03:33 UTC, stargaser commented on papers/adi_sdg/adi_scipycon_pynotebook.rst
> +   LTC2057 noise spectrum.
Is this figure taken from the LTC2057 datasheet?

2021-07-03 03:33 UTC, stargaser commented on papers/adi_sdg/adi_scipycon_pynotebook.rst
> +While Scopy is useful for single, visual measurements, the functionality can be replicated easily with the scipy.signal.periodogram function. Raw data is collected from an ADALM2000 using the libm2k
I don't think there is a DOI for libm2k so a URL reference to https://analogdevicesinc.github.io/libm2k/index.html would be appropriate.

2021-07-03 03:33 UTC, stargaser commented on papers/adi_sdg/adi_scipycon_pynotebook.rst
> +And finally, the frequency response can be calculalted using NumPy’s freqz function, as seen in the AD7124 Frequency Response code block. The response is shown in Figure :ref:`fltresp`.
typo "calculalted" -> "calculated"

2021-07-07 16:18 UTC, cristina-suteu commented
With this version, we addressed the citation and typo issues. Please let us know if there's anything else that requires changing. Thank you all for your comments and reviews. @stargaser , @matthewfeickert @nfcastro

2021-07-08 14:43 UTC, nfcastro commented
Dear @cristina-suteu 

I find this version to be very much improved. I have a few minor comments but other than that, I'm happy with the current draft.

- make sure that all the math expressions in the main text have the proper format (e.g. in p.1 (2**N)-1 is still not fixed)
- make sure that basic typographical rules are followed (e.g. a space before the brackets - c.f. with the caption of fig 2)
- all captions should end with "." (not happening e.g. in fig 2 and fig 15)

2021-07-09 13:57 UTC, cristina-suteu commented
Hello, @nfcastro. Thank you for your latest suggestions.  We just updated the paper based on these. Let us know if there's anything else we need to do.

2021-07-09 14:31 UTC, nfcastro commented
Looks fine to me.

2021-07-11 00:53 UTC, matthewfeickert requested changes
Thanks for your revisions to your submission @cristina-suteu and for bringing it in line with the length recommendations.

Unfortunately, there are still a significant number of serious problems in both presentation, formatting, and grammar that still remain unaddressed. I already stated many of these problems in [my first review](https://github.com/scipy-conference/scipy_proceedings/pull/631/#issuecomment-860457853), so please make sure that you read and address all of the comments with either a correction or a response to the review.

As is noted in the [SciPy proceedings Instructions for Authors](https://github.com/scipy-conference/scipy_proceedings/blob/f2e651d06cb1642248706a7294eb2bb932665531/README.md#instructions-for-authors)

> Authors should respond to all the reviewers' comments.
>
> Authors should default to modifying their papers in response to reviewers' comments.
>
> Authors may not agree with the reviewers comments or may not wish to implement the suggested changes. In those cases, the authors and reviewers should attempt to discuss this in the PR's comment sections. It is important to remember in these cases that we expect all communication between authors and reviewers to be civil and respectful.

and, to be clear, I do not want to insert myself as the `n+1` author on your submission &mdash; this is your work and you should present it in the manner that you want as is your full right as author &mdash; so I truly understand and welcome any disagreement you may have over my comments and requested changes, but I would like you to address them and so far they have not been responded to or addressed with revisions.

In addition, I think this submission should be reframed from a paper to a "tutorial" or a "set of examples". As it currently stands, it is not written in the scope and style of an academic paper or a community white paper. This by itself it not bad, and can be accepted at SciPy, but it should be made clear to the reader what the scope and purpose of the submission is.

As is mentioned in the text itself,

> The techniques detailed in this paper are, individually, nothing new

so I'd suggest that to avoid rewriting the entire submission to reflect the style of a paper that you present it as a tutorial instead.

In addition to all of my comments in my first review I will present some additional general changes and then comment in the document on specific lines.

## Written Quality

- Material the is referenced and cited in the paper should be cited at its first appearance. It does not need to be cited multiple times.
- Citation of references should happen in relevant text but the citation should not occur so that it is typeset on top of the figure number.

## Figures

I will remphasize that all figure captions should be sufficient explanations of the. At the moment none of the figure captions fulfill this purpose.

- All figure text should be legible and high enough resolution to be viewed without having to zoom in on a screen.

- All figures that include plots need labeled axes and, if needed, legends.

## Code Snippets

- Code snippets should be formatted to fit inside a single column without overflow.

- Code snippets should include all relevant imports for code used within.

- All code snippets shown in the paper should be valid Python syntax such that they are runnable.


Again, if there is anything that is unclear in my comments or requested changes please ask me to give more information and context. I am more than happy to do so, and as a reviewer it is the very least that I can do to help the authors.

2021-07-11 00:53 UTC, matthewfeickert commented on papers/adi_sdg/adi_scipycon_pynotebook.rst
> +Accurate, precise, and low-noise sensor measurements are essential before any machine can learn about (or artificial-intelligently make decisions about) the physical world. Modern, highly integrated
Nowhere in the text is machine learning discussed at all, so why is it being brought up in the abstract?

2021-07-11 00:53 UTC, matthewfeickert commented on papers/adi_sdg/adi_scipycon_pynotebook.rst
> +As the industry continues to push the physical limits, one thing that can be stated with certainty is this: there is always room for improvement in analog and mixed signal components for instrumentat
Acronyms like "ADC" should be written out in full _before_ their acronym representation is given.

2021-07-11 00:53 UTC, matthewfeickert commented on papers/adi_sdg/adi_scipycon_pynotebook.rst
> +This paper details the analysis and verification of such a signal acquisition system, focusing on noise. Individual signal chain elements will first be modelled in LTspice and Python / SciPy, then ve
* LTspice and SciPy should be cited here, not later in the paper.
* "IIO" is defined later on page 2, but it should be defined here now in its first use.

2021-07-11 00:53 UTC, matthewfeickert commented on papers/adi_sdg/adi_scipycon_pynotebook.rst
> +   :label:`mixmode`
* As mentioned in the general comments, the caption here is literally the same as the section title and contains no useful information about the figure presented. Figure captions need to provide relevant context.
* Most of the contents of the figure are never referenced in the text and are never explained. If most of the figure is not actually needed to communicate the relevant information then a simpler figure might want to be used. If all of the figure contents are useful and relevant then they should be addressed in the text.

2021-07-11 00:53 UTC, matthewfeickert commented on papers/adi_sdg/adi_scipycon_pynotebook.rst
> +If the sensor’s signal will eventually reside on, or at least take a trip through a computer, an ADC will be involved somewhere along the way. There are numerous background references on analog to di
`N` should be typeset as it is in the equation as well.
```suggestion
If the sensor’s signal will eventually reside on, or at least take a trip through a computer, an ADC will be involved somewhere along the way. There are numerous background references on analog to digital converters available [1]_ , and most readers will have a sense that an analog to digital converter samples an input signal at some point in time (or measures the average of a signal over some observation time), and produces a numerical representation of that signal - most often as a binary number with some value between zero and :math:`2^N - 1` where :math:`N` is the number of bits in the output word.
```

2021-07-11 00:53 UTC, matthewfeickert commented on papers/adi_sdg/adi_scipycon_pynotebook.rst
> +While there are several noise sources in Figure :ref:`mixmode`, one that is often either ignored, or over-emphasized, is the number of bits in the ADC's digital output. Historically, an ADC's "number
> often either ignored, or over-emphasized

Both ignored _and_ over-emphasized? This seems confusing, unless the electronics community is deeply divided on this point. Can you clarify?

> 16-bit converter was obviously 4 times better

This is just a suggestion, but in general it is best to steer clear of the word "obviously" in technical writing.

> "number of bits"
> ...
> “number of bits”

Use consistent formatting of text throughout the submission. So here use a consistent style of quotation marks.

2021-07-11 00:53 UTC, matthewfeickert commented on papers/adi_sdg/adi_scipycon_pynotebook.rst
> +.. figure:: ad7124_histograms.png
The figure captions that are included with the screenshot in `ad7124_histograms.png` need to be removed. They reference figure numbers that are not the same as the figure number of the image and are illegibly small.

2021-07-11 00:53 UTC, matthewfeickert commented on papers/adi_sdg/adi_scipycon_pynotebook.rst
> +   AD7124 output noise. PGA-gain=1 (left), PGA-gain=128 (right).
I would suggest citing the reference material source of the figures here in the caption.

2021-07-11 00:53 UTC, matthewfeickert commented on papers/adi_sdg/adi_scipycon_pynotebook.rst
> +As with any signal chain, one noise source within an ADC often dominates. Thus, if a noiseless signal is applied an N-bit ADC:
> Thus, if a noiseless signal is applied an N-bit ADC:

This is grammatically incorrect.

2021-07-11 00:53 UTC, matthewfeickert commented on papers/adi_sdg/adi_scipycon_pynotebook.rst
> +   :math:`20\log(V_{in}(p-p)/(\sigma/\sqrt{8}))`, where:
It should be made explicitly clear given the general audience that this is `p_signal` and `p_noise`.

2021-07-11 00:53 UTC, matthewfeickert commented on papers/adi_sdg/adi_scipycon_pynotebook.rst
> +   :math:`V_{in}(p-p)` is the full-scale input signal
You should additionally define all symbols used.

2021-07-11 00:53 UTC, matthewfeickert commented on papers/adi_sdg/adi_scipycon_pynotebook.rst
> +Very high resolution converters, such as the AD7124-8 that will be used as an example shortly, are rarely limited by quantization noise; thermal noise dominates in all of the gain / bandwidth setting
> Figure :ref:`ad7124hist` [4]_

Placing the citation reference like this results in it being typeset as looking like `Figure 2^4`, which is very undesirable for a reader. Please either do something like

> Figure :ref:`ad7124hist`, from Ref. [4]_, 

or cite the reference in the figure caption.

> ... below shows

I would avoid the use of "below". The figure is on a separate page and including directionality doesn't improve the information at all, especially for a 2-column paper where the conecpt of "below" can become confusing in the text.

2021-07-11 00:53 UTC, matthewfeickert commented on papers/adi_sdg/adi_scipycon_pynotebook.rst
> +Modeling the noise of a thermal-noise limited ADC’s is straightforward. If the noise is “well behaved” (Gaussian, as it is in Figure :ref:`ad7124hist`) and constant across the ADC’s input span, the A
> random.normal function

Can you typeset this as code? Like `random.normal` but using the proper RST syntax.

2021-07-11 00:53 UTC, matthewfeickert commented on papers/adi_sdg/adi_scipycon_pynotebook.rst
> +.. figure:: full_setup_overview.png
* This figure has a text box around "AD7124-8-PMDZ" which should be removed.
* `Pyadi-iio` and `Libiio` have underlines applied to them indicating the text editor thinks they are misspelled. These should be removed.
* The "N" in "Network connection" is italicised while the rest of the word is not. Keep all text in the same font style.
* All items in the figure with the exception of the ADLM2000 have an itentifying label next to them. The figure should make all items clear.

2021-07-11 00:53 UTC, matthewfeickert commented on papers/adi_sdg/adi_scipycon_pynotebook.rst
> +.. figure:: ad7124_warmup.png
* The figure would benefit greatly from a legend as multiple sources of data are being plotted with no labelling to distinguish them.
* The figure is made with `matplotlib` but the axis titles are added after the fact with some editor that degrades the figure quality due to compression artifacts and font mismatch. As the figure was made in Python using `matplotlib` can the figure be remade with the legend and axes labels?

2021-07-11 00:53 UTC, matthewfeickert commented on papers/adi_sdg/adi_scipycon_pynotebook.rst
> +Any part used when building a signal acquisition system will contaminate the original signal with additive noise. Amplifier and sensor manufacturers will include noise as a data sheet specification.
> nV/:math:`\sqrt{Hz}

Minor comment, but you can use `mathrm` to make the `Hz` properly typeset here.

> (or 20,000,000nV/g)

I'd suggest removing this and just sticking with one unit of measure.

2021-07-11 00:53 UTC, matthewfeickert commented on papers/adi_sdg/adi_scipycon_pynotebook.rst
> +:math:`e_{RMS} = \sigma`
Does this need to be on its own line?

2021-07-11 00:53 UTC, matthewfeickert commented on papers/adi_sdg/adi_scipycon_pynotebook.rst
> +This is now an easy comparison, since the ADC input noise is now
This bit of text ins't really clear. Please revise it so that the narrative flow is easily followed.

2021-07-11 00:53 UTC, matthewfeickert commented on papers/adi_sdg/adi_scipycon_pynotebook.rst
> +“Increase signal chain gain just to the point where the noise of the last stage before the ADC is a bit higher than the ADC noise… then **STOP**. Don’t bother increasing the signal chain gain any mor
> “Increase signal chain gain just to the point where the noise of the last stage before the ADC is a bit higher than the ADC noise… then **STOP**.

What are you quoting from here? If it is text then it needs to be cited. If it is trying to indicate a conversational style with the reader this isn't coming across well. I also don't think that the text benefits much from the use of bold all caps **STOP**.

2021-07-11 00:53 UTC, matthewfeickert commented on papers/adi_sdg/adi_scipycon_pynotebook.rst
> +This runs counter to historical advice to “fill” the ADC’s input range. There may be benefit to using more of an ADC’s input range IF there are steps or discontinuities in the ADC’s transfer function
> historical advice

What does "historical" mean here? Is this a citeable piece of information? Not everyone reading this submission at SciPy will have a shared concept of history so it is better to be explicit about what this means.

> input range IF there

Does the "IF" need to be all caps?

2021-07-11 00:53 UTC, matthewfeickert commented on papers/adi_sdg/adi_scipycon_pynotebook.rst
> +.. figure:: ad7124_filter_resp_measured.png
* This figure is missing units of frequency. All axes that show unit-ful quantities need units.
* Same comment as previously RE: axes labels and replotting the image in `matplotlib`.

2021-07-11 00:53 UTC, matthewfeickert commented on papers/adi_sdg/adi_scipycon_pynotebook.rst
> +        send_sinewave(my_siggen, freq) # Set output freq
Where is `send_sinewave` coming from?

2021-07-11 00:53 UTC, matthewfeickert commented on papers/adi_sdg/adi_scipycon_pynotebook.rst
> +        data = capture_data(my_ad7124) # Grab data
Where is `capture_data` coming from?

2021-07-11 00:53 UTC, matthewfeickert commented on papers/adi_sdg/adi_scipycon_pynotebook.rst
> +    plt.show()
Should include all relevant imports for `numpy` and `matplotlib`.

2021-07-11 00:53 UTC, matthewfeickert commented on papers/adi_sdg/adi_scipycon_pynotebook.rst
> +.. figure:: rev_eng_filters_all.png
The axes labels are "tap number" and "tap value" but "tap" has never been defined in the text and it is unclear what the units of "tap value" are.

2021-07-11 00:53 UTC, matthewfeickert commented on papers/adi_sdg/adi_scipycon_pynotebook.rst
> +.. figure:: ad7124_calculated_50_60_fresp.png
Both axes are missing units of frequency.

2021-07-11 00:53 UTC, matthewfeickert commented on papers/adi_sdg/adi_scipycon_pynotebook.rst
> +All sensors, no matter how perfect, have some maximum input value (and a corresponding maximum output - which may be a voltage, current, resistance, or even dial position) and a finite noise floor -
> Rsensor in the diagram below

Given the figure number here instead of saying "below".

2021-07-11 00:53 UTC, matthewfeickert commented on papers/adi_sdg/adi_scipycon_pynotebook.rst
> +Under the analyzer settings shown, the ADALM2000 noise floor is <<40µV/:math:`\sqrt{Hz}`, well below the 1.27 mV/:math:`\sqrt{Hz}`>> of the noise source.
If you're going to use the `<<` and `>>` to indicate "significantly less/greater than" put them inside of the proper math environment so they get typeset correctly. Otherwise please write out what you mean, as the render as is doesn't properly convey the meaning of the symbols.

2021-07-11 00:53 UTC, matthewfeickert commented on papers/adi_sdg/adi_scipycon_pynotebook.rst
> +        vsd += np.sqrt(psd)
This is invalid Python code and will raise an `IndentationError`. Please reformat it.

2021-07-11 00:53 UTC, matthewfeickert commented on papers/adi_sdg/adi_scipycon_pynotebook.rst
> +LTspice [11]_  is a freely available, general-purpose analog circuit simulator that can be applied to signal chain design. It can perform transient analysis, frequency-domain analysis (AC sweep), and
Cite LTspcie the first time it is referenced in the text, not now.
```suggestion
LTspice  is a freely available, general-purpose analog circuit simulator that can be applied to signal chain design. It can perform transient analysis, frequency-domain analysis (AC sweep), and noise analysis, the results of which can be exported and incorporated into mixed signal models using Python.
```

2021-07-11 00:53 UTC, matthewfeickert commented on papers/adi_sdg/adi_scipycon_pynotebook.rst
> +Figure :ref:`ngltspice` ciruit’s noise is fairly trivial to model, given that it is constant for some bandwidth (in which a signal of interest would lie), above which it rolls off with approximately
Use a consistent capitalization scheme for referencing figures, so make this

```suggestion
Figure :ref:`ngltspice` ciruit’s noise is fairly trivial to model, given that it is constant for some bandwidth (in which a signal of interest would lie), above which it rolls off with approximately a first order lowpass response. Where this technique comes in handy is modeling non-flat noise floors, either due to higher order analog filtering, or active elements themselves. The classic example is the “noise mountain” that often exists in autozero amplifiers such as the LTC2057, as seen in Figure :ref:`ltc2057nsd` [12]_ .
```

2021-07-11 00:53 UTC, matthewfeickert commented on papers/adi_sdg/adi_scipycon_pynotebook.rst
> +While that mountain looks daunting, it may not be a problem if it is suppressed in either the analog or digital domains.
This one sentence is not a paragraph. Please join it with relevant text.

2021-07-11 00:53 UTC, matthewfeickert commented on papers/adi_sdg/adi_scipycon_pynotebook.rst
> +.. code-block:: python
Add imports of all external code

2021-07-11 00:53 UTC, matthewfeickert commented on papers/adi_sdg/adi_scipycon_pynotebook.rst
> +  # DC in first element.
This comment is unclear. Please clarify or remove.

2021-07-11 00:53 UTC, matthewfeickert commented on papers/adi_sdg/adi_scipycon_pynotebook.rst
> +  #          " Should be close to nothing")
This commented out code should be removed.

2021-07-11 00:53 UTC, matthewfeickert commented on papers/adi_sdg/adi_scipycon_pynotebook.rst
> +This function can be verified by controlling one ADALM2000 through a libm2k [10]_  script, and verifying the noise profile with a second ADALM2000 and the spectrum analyzer in the Scopy [8]_  GUI. Th
Scopy has already been cited at this point in the text, so no need to cite again.
```suggestion
This function can be verified by controlling one ADALM2000 through a libm2k [10]_  script, and verifying the noise profile with a second ADALM2000 and the spectrum analyzer in the Scopy  GUI. The Push Noise Time-series to ADALM2000 code snippet generates four "bands" of 1mV/:math:`\sqrt{Hz}` noise on the ADALM2000 W2 output (with a sinewave on W1, for double-checking functionality.)
```

2021-07-11 00:53 UTC, matthewfeickert commented on papers/adi_sdg/adi_scipycon_pynotebook.rst
> +.. -----------------------------------------------------|
This should be in a single column, not split across two.

2021-07-11 00:53 UTC, matthewfeickert commented on papers/adi_sdg/adi_scipycon_pynotebook.rst
> +The rolloff above ~20kHz is the SINC rolloff of the DAC. If the DAC is capable of a higher sample rate, the time series data can be upsampled and filtered by an interpolating filter. [13]_
As typeset, this line and the following line of text get separated and appear as 1 sentence paragraphs. Please reformat them so they appear joined with relevant text.

2021-07-11 00:53 UTC, matthewfeickert commented on papers/adi_sdg/adi_scipycon_pynotebook.rst
> +.. figure:: ad7124_noise_blast.png
This figure is very difficult to read and should ideally be split into two separate subfigures. Please reformat so that the the figure is legible.

2021-07-11 00:53 UTC, matthewfeickert commented on papers/adi_sdg/adi_scipycon_pynotebook.rst
> +The ADALM2000 noise generator can be used to validate this result. Setting the test noise generator to generate a band of 1000µV/:math:`\sqrt{Hz}` should result in a total noise of about 5.69mVRMS, a
> in figure :ref:`noiseblast` Note the

capitalize and missing a period, so something like this:
```suggestion
The ADALM2000 noise generator can be used to validate this result. Setting the test noise generator to generate a band of 1000µV/:math:`\sqrt{Hz}` should result in a total noise of about 5.69mVRMS, and measured results are approximately 5.1mVRMS total noise. The oscilloscope capture of the ADC input signal is plotted next to the ADC output data below, in Figure :ref:`noiseblast`. Note the measured peak-to-peak noise of 426mV, while the ADC peak-to-peak noise is about 26mV. While such a high noise level is (hopefully) unrealistic in an actual precision signal chain, this exercise demonstrates that the the ADC’s internal filter can be relied on to act as the primary bandwidth limiting, and hence noise reducing, element in a signal chain.
```

2021-07-11 00:53 UTC, matthewfeickert commented on papers/adi_sdg/adi_scipycon_pynotebook.rst
> +References
References that are of websites that don't include a permanent archive or DOI should have a date accessed associated with them.

2021-07-13 01:51 UTC, mthoren-adi commented
Hi @matthewfeickert ,

We completely understand. My gut feel at this point, given that the conference is underway, would be to withdraw this paper. While the formatting and grammar can be fixed, it is the presentation and reframing as a tutorial (which I agree with entirely) that would take too much time, and even then may be marginal.

We have several tutorials in development that will spin out of this work (in addition to the released one in the references.) We'll keep those in mind for a possible tutorial in the future.

Lastly - we appreciate your, and @nfcastro 's , @stargaser 's time in reviewing this. We'll be much more calibrated for future submissions.

-Mark

2021-07-13 18:56 UTC, stargaser commented
@mthoren-adi let me note here that the proceedings co-chairs looked over this paper at our last meeting. We accept a broad range of papers and there was a consensus that this style of contribution is acceptable for a SciPy proceedings paper, but the paper may need some more editing for clarity, formatting and typos.

2021-07-13 19:53 UTC, matthewfeickert commented
@mthoren-adi Let me also echo everything that @stargaser said. 

>  it is the presentation and reframing as a tutorial (which I agree with entirely) that would take too much time, and even then may be marginal.

I really think that this part of the revision would be literally editing a few words. I don't want you to rewrite the whole thing at all, I was just more suggesting a search and replace of "paper" with "tutorial" for the most part. I'm sorry as I think I made my intentions there unclear!

2021-07-14 17:56 UTC, mthoren-adi commented
Understood @matthewfeickert  and @stargaser ! I spoke with Cristina this morning, we will give this one more go.

2021-07-20 13:39 UTC, deniederhut commented
Hi @cristina-suteu ! How are the revisions coming along?

2021-07-20 14:57 UTC, mthoren-adi commented on papers/adi_sdg/adi_scipycon_pynotebook.rst
> +This function can be verified by controlling one ADALM2000 through a libm2k script, and verifying the noise profile with a second ADALM2000 and the spectrum analyzer in the Scopy GUI. The Push Noise
Referenced https://wiki.analog.com/university/tools/m2k/scopy

2021-07-20 15:01 UTC, mthoren-adi commented on papers/adi_sdg/adi_scipycon_pynotebook.rst
> +While Scopy is useful for single, visual measurements, the functionality can be replicated easily with the scipy.signal.periodogram function. Raw data is collected from an ADALM2000 using the libm2k
We referenced https://wiki.analog.com/university/tools/m2k/libm2k/libm2k. We use the wiki as the main "launch pad", with links to source and other documentation.

2021-07-20 15:14 UTC, mthoren-adi commented on papers/adi_sdg/adi_scipycon_pynotebook.rst
> +While there are several noise sources in Figure :ref:`mixmode`, one that is often either ignored, or over-emphasized, is the number of bits in the ADC's digital output. Historically, an ADC's "number
Indeed, there is a historical divide. To draw an analogy - it's similar to moving from an 8-bit integer, to 16-bit, to floating point. Usually, you don't have to think about quantization error of a floating point number, because its so small it doesn't matter. Convincing electrical engineers of this sometimes requires a couple of tangible examples (like the AD7124 or similar high-resolution converter.)

Will address quotation marks.

2021-07-20 16:41 UTC, mthoren-adi commented
Hi @deniederhut , We pushed an update this morning addressing the majority of the issues, but noted some remaining issues. We'll aim for one more update today.

2021-07-21 00:38 UTC, deniederhut commented
Okay cool! Thanks for spending some more time on this!

2021-07-21 08:14 UTC, cristina-suteu commented
Hello @deniederhut , we updated our paper, addressing the remaining issues. Should we change the title of this pull request to say Tutorial instead of paper? 

@mthoren-adi and I would like to thank everyone who took their time to review our work @nfcastro @matthewfeickert @stargaser

2021-07-21 11:11 UTC, deniederhut commented
> Should we change the title of this pull request to say Tutorial instead of paper?

No, procbuild uses that to filter PRs.

@matthewfeickert would you have time to take another look at the paper?

2021-07-21 18:57 UTC, matthewfeickert commented
> would you have time to take another look at the paper?

I won't have time until Friday evening at the earliest.

@cristina-suteu Just taking a glance at the build https://procbuild.scipy.org/download/cristina-suteu-2021 I can see some typesetting issues on the first page, so if you can go through and check the paper for typesetting errors and fix them before Friday that would be great.

2021-07-22 14:00 UTC, deniederhut commented
This week-end will be fine, thanks!

@stargaser will you have time to take a final look at this early next week, so we can get everything published by the 31st?

2021-07-22 14:18 UTC, stargaser commented
Yes, I will take a final look early next week.

Making a quick read-through just now, I found only one typo on page 2 and I can't see the typesetting issue @matthewfeickert referred to on the first page. I'll go note the p. 2 one inline. Given the nature of conference proceedings, with tight schedule constraints and page limits, we can't expect perfection.

2021-07-22 14:23 UTC, stargaser commented on papers/adi_sdg/adi_scipycon_pynotebook.rst
> +-  results in a gaussian distribution of "many" output codes, then a **thermal noise source dominates**. The Signal to Noise Ratio is no greater than:
```suggestion
-  results in a gaussian distribution of "many" output codes, then **thermal noise source dominates**. The Signal to Noise Ratio is no greater than: 
```

the one typo I found.

2021-07-22 14:34 UTC, mthoren-adi commented on papers/adi_sdg/adi_scipycon_pynotebook.rst
> +-  results in a gaussian distribution of "many" output codes, then a **thermal noise source dominates**. The Signal to Noise Ratio is no greater than:
Thank you @stargaser , I was also struggling to find the typesetting issue. The one thing that stood out was numerical references that showed up as superscript, but there are other papers following this convention. Is numerical acceptable? If not, I can switch to abbreviations.
We'll fix the typo ASAP, (given timezone issues)
I've probably said this too much but if it's not close enough to perfect, we can withdraw (and perhaps to a hands-on workshop in the future.) But - we'd be happy to have it included.

2021-07-22 14:54 UTC, stargaser commented on papers/adi_sdg/adi_scipycon_pynotebook.rst
> +-  results in a gaussian distribution of "many" output codes, then a **thermal noise source dominates**. The Signal to Noise Ratio is no greater than:
I have to ask the co-chairs about the numerical references. Do you have a link to a SciPy proceedings paper @mthoren-adi where these are used? The alphabetical style is used in the example paper but I feel like we don't demand that level of uniformity.

2021-07-22 15:00 UTC, mthoren-adi commented on papers/adi_sdg/adi_scipycon_pynotebook.rst
> +-  results in a gaussian distribution of "many" output codes, then a **thermal noise source dominates**. The Signal to Noise Ratio is no greater than:
@stargaser  This is the one I had located (not exhaustive search):
https://github.com/scipy-conference/scipy_proceedings/blob/2021/papers/lm_cognitive/Scipy2021_ConfPaper_061821.rst

2021-07-22 15:04 UTC, stargaser commented on papers/adi_sdg/adi_scipycon_pynotebook.rst
> +-  results in a gaussian distribution of "many" output codes, then a **thermal noise source dominates**. The Signal to Noise Ratio is no greater than:
Thanks, that's plenty good enough for me! We've accepted a paper with numerical references. So we can say they are acceptable.

2021-07-22 15:32 UTC, stargaser commented
To be explicit: I don't see this paper being rejected. One reviewer is satisfied with it. The co-chairs have said they would accept it. Some paragraphs and equations could be formatted in a more consistent style (and these have been noted already). Those are nice-to-haves but they are not showstoppers that would prevent acceptance of the paper.

2021-07-22 15:36 UTC, scoobies commented
I think one of the equations has a typo so it says "math:X" instead of "X"
or something?

On Thu, Jul 22, 2021, 10:32 David Shupe ***@***.***> wrote:

> To be explicit: I don't see this paper being rejected. One reviewer is
> satisfied with it. The co-chairs have said they would accept it. Some
> paragraphs and equations could be formatted in a more consistent style (and
> these have been noted already). Those are nice-to-haves but they are not
> showstoppers that would prevent acceptance of the paper.
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub
> <https://github.com/scipy-conference/scipy_proceedings/pull/631#issuecomment-885008313>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/ATD6NPA72SVC5UZP75RD67TTZA2ZJANCNFSM45W75FDA>
> .
>

2021-07-22 16:08 UTC, stargaser reviewed
I made a pass for formatting and typesetting issues. 

Can the spaces between numerical references and periods or commas be removed?

2021-07-22 16:08 UTC, stargaser commented on papers/adi_sdg/adi_scipycon_pynotebook.rst
> +This tutorial is in extension of Converter Connectivity Tutorial [1]_ and associated code and simulation files [2]_ . A representative signal chain will be analyzed and tested, focusing on noise. Ind
Oh, now I see the typesetting issues on the first page. There are spaces between the reference and the periods and commas, in three places. Can the spaces be taken out?

2021-07-22 16:08 UTC, stargaser commented on papers/adi_sdg/adi_scipycon_pynotebook.rst
> +Figure :ref:`10hznotch` from Ref. [8]_  shows the AD7124-8’s 10Hz notch filters. Various combinations of Higher order SINC3 and SINC4 filters are also available.
```suggestion
Figure :ref:`10hznotch` from Ref. [8]_  shows the AD7124-8’s 10Hz notch filters. Various combinations of higher-order SINC3 and SINC4 filters are also available. 
```

2021-07-22 16:08 UTC, stargaser commented on papers/adi_sdg/adi_scipycon_pynotebook.rst
> +K is Boltzmann’s constant (1.38e-23 J/K)
Stylistically, it would be nice for the symbols to be formatted in math mode.
```suggestion
:math:`K` is Boltzmann’s constant (1.38e-23 J/K)
```
here and for the other symbols.

2021-07-22 16:08 UTC, stargaser commented on papers/adi_sdg/adi_scipycon_pynotebook.rst
> +Figure :ref:`ngltspice` circuit’s noise is fairly trivial to model, given that it is constant for some bandwidth (in which a signal of interest would lie), above which it rolls off with approximately
At the end here, is another instance of a space between the numerical citation and the period.

2021-07-22 16:08 UTC, stargaser commented on papers/adi_sdg/adi_scipycon_pynotebook.rst
> +fc is the cutoff frequency of the filter. If broadband noise, from "DC to daylight", is applied to the inputs of both a 1KHz, first-order lowpass filter and 1.57kHz brickwall lowpass filter, the tota
```suggestion
:math:`fc` is the cutoff frequency of the filter. If broadband noise, from "DC to daylight", is applied to the inputs of both a 1KHz, first-order lowpass filter and 1.57kHz brickwall lowpass filter, the total noise power at the outputs will be the same.
```

2021-07-22 16:08 UTC, stargaser commented on papers/adi_sdg/adi_scipycon_pynotebook.rst
> +.. code-block:: python
Yes, I see that `import numpy as np` is needed, at least the first time it is used.

2021-07-22 16:08 UTC, stargaser commented on papers/adi_sdg/adi_scipycon_pynotebook.rst
> +ADCp-p is the peak-to-peak input range of the ADC
```suggestion
:math:`ADCp-p` is the peak-to-peak input range of the ADC
```

2021-07-22 16:08 UTC, stargaser commented on papers/adi_sdg/adi_scipycon_pynotebook.rst
> +This tutorial is in extension of Converter Connectivity Tutorial [1]_ and associated code and simulation files [2]_ . A representative signal chain will be analyzed and tested, focusing on noise. Ind
a couple instances here where there's a space between the reference and the comma or period.

2021-07-22 17:25 UTC, mthoren-adi commented on papers/adi_sdg/adi_scipycon_pynotebook.rst
> +This tutorial is in extension of Converter Connectivity Tutorial [1]_ and associated code and simulation files [2]_ . A representative signal chain will be analyzed and tested, focusing on noise. Ind
Fixed

2021-07-22 17:25 UTC, mthoren-adi commented on papers/adi_sdg/adi_scipycon_pynotebook.rst
> +Figure :ref:`10hznotch` from Ref. [8]_  shows the AD7124-8’s 10Hz notch filters. Various combinations of Higher order SINC3 and SINC4 filters are also available.
Done

2021-07-22 17:25 UTC, mthoren-adi commented on papers/adi_sdg/adi_scipycon_pynotebook.rst
> +K is Boltzmann’s constant (1.38e-23 J/K)
Done

2021-07-22 17:25 UTC, mthoren-adi commented on papers/adi_sdg/adi_scipycon_pynotebook.rst
> +Figure :ref:`ngltspice` circuit’s noise is fairly trivial to model, given that it is constant for some bandwidth (in which a signal of interest would lie), above which it rolls off with approximately
Done

2021-07-22 17:26 UTC, mthoren-adi commented on papers/adi_sdg/adi_scipycon_pynotebook.rst
> +fc is the cutoff frequency of the filter. If broadband noise, from "DC to daylight", is applied to the inputs of both a 1KHz, first-order lowpass filter and 1.57kHz brickwall lowpass filter, the tota
Done

2021-07-22 17:27 UTC, mthoren-adi commented on papers/adi_sdg/adi_scipycon_pynotebook.rst
> +ADCp-p is the peak-to-peak input range of the ADC
Done

2021-07-22 17:28 UTC, mthoren-adi commented on papers/adi_sdg/adi_scipycon_pynotebook.rst
> +This tutorial is in extension of Converter Connectivity Tutorial [1]_ and associated code and simulation files [2]_ . A representative signal chain will be analyzed and tested, focusing on noise. Ind
Done.

2021-07-23 17:32 UTC, mthoren-adi commented
Hi @stargaser , @matthewfeickert , looks like the latest commits are reflected in https://procbuild.scipy.org/download/cristina-suteu-2021, just want to make sure everything's all set for your final review. Thanks!

2021-07-24 18:55 UTC, matthewfeickert requested changes
Thanks for your work and revisions to the submission @cristina-suteu and @mthoren-adi. :+1: I think that they have improved the quality quite a bit and I only have some minor final comments that should be very easy to implement, some of which are just pointing out things that were already brought up in previous reviews. After these are in I can give my approval.

2021-07-24 18:55 UTC, matthewfeickert commented on papers/adi_sdg/adi_scipycon_pynotebook.rst
> +   In a mixed-mode signal chain, some physical phenomenon such as temperature, light intensity, pH, force, or torque is converted to an electrical parameter (resistance, current, or directly to volta
The first sentence of this paragraph is cut off and by itself given the placement of the figure immediately after. It makes it seems like you're trying to have a 1 sentence paragraph to start a section, which shouldn't happen. It would be nice if when you locally build the PDF while proofreading to see if you can move the figure command around so that the text doesn't suffer.

2021-07-24 18:55 UTC, matthewfeickert commented on papers/adi_sdg/adi_scipycon_pynotebook.rst
> +"The input noise of one stage should be somewhat lower than the output noise of the preceding stage"
Needs a period.

```suggestion
"The input noise of one stage should be somewhat lower than the output noise of the preceding stage."
```

2021-07-24 18:55 UTC, matthewfeickert commented on papers/adi_sdg/adi_scipycon_pynotebook.rst
> +As with any signal chain, one noise source within an ADC often dominates. Thus, if a noiseless signal is applied to an N-bit ADC:
to have the following bullet points start in "results in" this "is" needs to be removed to have the grammar work.

```suggestion
As with any signal chain, one noise source within an ADC often dominates. Thus, if a noiseless signal applied to an N-bit ADC:
```

2021-07-24 18:55 UTC, matthewfeickert commented on papers/adi_sdg/adi_scipycon_pynotebook.rst
> +    # See AD7124 datasheet for noise levels per mode
As you use NumPy you should either add a `import numpy as np`, or, as you use `numpy` and `matplotlib.pyplot` code in multiple code snippets without importing either you could note in the text itself that all code examples are assumed to be run in an enviornment in which

```python
import numpy as np
import matplotlib.pyplot as plt
```

have already been run. I personally think the 1 or 2 lines added to each code snippet to import externals is worth it, but that's up to you.

2021-07-24 18:55 UTC, matthewfeickert commented on papers/adi_sdg/adi_scipycon_pynotebook.rst
> +The AD7124 device driver falls under the industry-standard Industrial Input-Output (IIO) framework, which has a well-established software API (including Python bindings). Application code can run loc
You already defined IIO, so don't redefine it again. Also in the text (figure captions shouldn't be relied upon in the main text) you haven't talked about a Raspberry Pi yet, so don't use the abbreviation for the name without it.

```suggestion
The AD7124 device driver falls under the industry-standard IIO framework, which has a well-established software API (including Python bindings). Application code can run locally (on the Raspberry Pi) or on a remote machine via network, serial, or USB connection. Furthermore, the pyadi-iio [10]_ abstraction layer takes care of much of the boilerplate setup required for interfacing with IIO devices, greatly simplifying the software interface. The AD7124-8 Basic Data Capture code block illustrates how to open a connection to the AD7124-8, configure it, capture a block of data, then close the connection.
```

2021-07-24 18:55 UTC, matthewfeickert commented on papers/adi_sdg/adi_scipycon_pynotebook.rst
> +   AD7124-8 Data captures with 1.25mV input. Lower trace shows "wander" after initial power-up. Upper trace shows stable readings after a half-hour warmup time.
Same comments here RE: figures and isolated sentences, but if it isn't easy to fix then don't worry about it.

2021-07-24 18:55 UTC, matthewfeickert commented on papers/adi_sdg/adi_scipycon_pynotebook.rst
> +   Bias Circuit for input noise measurement. A resistor divider imposes a 1.25mV signal across the AD7124-8's input, overcoming the 15µV maximum offset voltage.
Make sure that figure captions are still full sentences like normal prose and that standard capitalization rules of writing are followed.

2021-07-24 18:55 UTC, matthewfeickert commented on papers/adi_sdg/adi_scipycon_pynotebook.rst
> +   AD7124-8 Data captures with 1.25mV input. Lower trace shows "wander" after initial power-up. Upper trace shows stable readings after a half-hour warmup time.
Make sure that figure captions are still full sentences like normal prose and that standard capitalization rules of writing are followed.

2021-07-24 18:55 UTC, matthewfeickert commented on papers/adi_sdg/adi_scipycon_pynotebook.rst
> +An ADC’s internal noise will necessarily appear somewhere between DC and half the sample rate. Ideally this noise is flat, or at least predictably shaped. In fact, since the ADC’s total noise is spre
Don't need a colon here

```suggestion
An ADC’s internal noise will necessarily appear somewhere between DC and half the sample rate. Ideally this noise is flat, or at least predictably shaped. In fact, since the ADC’s total noise is spread out across a known bandwidth, it can be converted to a noise density that can be directly compared to other elements in the signal chain. Precision converters typically have total noise given directly, in volts RMS: :math:`e_{RMS} = \sigma` , where :math:`e_{RMS}` is the total RMS noise, calculated from the standard deviation of a grounded-input histogram of codes.
```

2021-07-24 18:55 UTC, matthewfeickert commented on papers/adi_sdg/adi_scipycon_pynotebook.rst
> +   AD7124 - m2k Connections for Filter Response Measurement. The 1k resistor protects the AD7124-8 if a malfunction occurs, as the m2k output range is -5V to +5V, beyond the -0.3V to 3.6V absolute ma
Make sure that figure captions are still full sentences like normal prose and that standard capitalization rules of writing are followed.

2021-07-24 18:55 UTC, matthewfeickert commented on papers/adi_sdg/adi_scipycon_pynotebook.rst
> +  plt.show()
c.f. earlier comment RE: `numpy` and `matplotlib` imports

2021-07-24 18:55 UTC, matthewfeickert commented on papers/adi_sdg/adi_scipycon_pynotebook.rst
> +The simultaneous 50Hz/60Hz rejection filter shown in Figure :ref:`5060hzflt` , from Ref. [8]_ is a nontrivial example. This filter is intended to strongly reject noise from A.C. power lines, which is
Remove extra spaces

```suggestion
The simultaneous 50Hz/60Hz rejection filter shown in Figure :ref:`5060hzflt`, from Ref. [8]_ is a nontrivial example. This filter is intended to strongly reject noise from A.C. power lines, which is either 50Hz (as in Europe) or 60Hz (as in the United States).
```

2021-07-24 18:55 UTC, matthewfeickert commented on papers/adi_sdg/adi_scipycon_pynotebook.rst
> +.. figure:: media/ad7124_filter_10.png
This image file still has the original reference's figure number and caption in the screenshot. The original reference's figure number and caption should be removed like you did for the other images you screenshotted from the reference.

2021-07-24 18:55 UTC, matthewfeickert commented on papers/adi_sdg/adi_scipycon_pynotebook.rst
> +.. code-block:: python
c.f. earlier comments RE: `numpy` imports.

2021-07-24 18:55 UTC, matthewfeickert commented on papers/adi_sdg/adi_scipycon_pynotebook.rst
> +   Generated Filter Impulse Responses. Repeatedly convolving rectangular impulses produces triangular, then "Gaussian-like" impulse responses.
Make sure that figure captions are still full sentences like normal prose and that standard capitalization rules of writing are followed.

2021-07-24 18:55 UTC, matthewfeickert commented on papers/adi_sdg/adi_scipycon_pynotebook.rst
> +   Calculated 50/60Hz Rejection Filter Response. The composite response in the frequency domain is the product of the individual 50Hz and 60Hz filters.
Make sure that figure captions are still full sentences like normal prose and that standard capitalization rules of writing are followed.

2021-07-24 18:55 UTC, matthewfeickert commented on papers/adi_sdg/adi_scipycon_pynotebook.rst
> +.. code-block:: python
c.f. earlier comments RE: `numpy` imports.

2021-07-24 18:55 UTC, matthewfeickert commented on papers/adi_sdg/adi_scipycon_pynotebook.rst
> +A sensor’s datasheet may specify a low output impedance (often close to zero ohms), but this is likely a buffer stage - which eases interfacing to downstream circuits, but does not eliminate noise du
Units are capitalized.

```suggestion
A sensor’s datasheet may specify a low output impedance (often close to zero Ohms), but this is likely a buffer stage - which eases interfacing to downstream circuits, but does not eliminate noise due to impedances earlier in the signal chain.
```

2021-07-24 18:55 UTC, matthewfeickert commented on papers/adi_sdg/adi_scipycon_pynotebook.rst
> +   Conceptual Sensor with Buffered Output. Noise is buffered along with the signal.
Make sure that figure captions are still full sentences like normal prose and that standard capitalization rules of writing are followed.

2021-07-24 18:55 UTC, matthewfeickert commented on papers/adi_sdg/adi_scipycon_pynotebook.rst
> +   Laboratory Noise Source. A 1M resistor serves as a noise generator, which is then amplified to a usable level by a low-noise operational amplifier.
Make sure that figure captions are still full sentences like normal prose and that standard capitalization rules of writing are followed.

2021-07-24 18:55 UTC, matthewfeickert commented on papers/adi_sdg/adi_scipycon_pynotebook.rst
> +.. code-block:: python
c.f. earlier comments RE: `numpy` imports.

2021-07-24 18:55 UTC, matthewfeickert commented on papers/adi_sdg/adi_scipycon_pynotebook.rst
> +   Noise Generator Output, showing a usable noise bandwidth of approximately 10kHz.
Make sure that figure captions are still full sentences like normal prose and that standard capitalization rules of writing are followed.

2021-07-24 18:55 UTC, matthewfeickert commented on papers/adi_sdg/adi_scipycon_pynotebook.rst
> +   LTC2057, G=+10 output noise simulation. LTspice provides simple tools for integrating noise, but results of any simulation can be exported and imported into Python for further analysis.
> G=+10

You haven't defined `G` in the text anywhere and it isn't visually defined in the image. Please define all terms used.

2021-07-24 18:55 UTC, matthewfeickert commented on papers/adi_sdg/adi_scipycon_pynotebook.rst
> +Where: :math:`fc` is the cutoff frequency of the filter. If broadband noise, from "DC to daylight", is applied to the inputs of both a 1KHz, first-order lowpass filter and 1.57kHz brickwall lowpass f
Don't need a colon here

```suggestion
Where :math:`fc` is the cutoff frequency of the filter. If broadband noise, from "DC to daylight", is applied to the inputs of both a 1KHz, first-order lowpass filter and 1.57kHz brickwall lowpass filter, the total noise power at the outputs will be the same.
```

2021-07-24 18:55 UTC, matthewfeickert commented on papers/adi_sdg/adi_scipycon_pynotebook.rst
> +The ADALM2000 noise generator can be used to validate this result. Setting the test noise generator to generate a band of 1000µV/:math:`\sqrt{Hz}` should result in a total noise of about 5.69mVRMS, a
Remove excess space.

```suggestion
The ADALM2000 noise generator can be used to validate this result. Setting the test noise generator to generate a band of 1000µV/:math:`\sqrt{Hz}` should result in a total noise of about 5.69mVRMS, and measured results are approximately 5.1mVRMS total noise. The oscilloscope capture of the ADC input signal is plotted next to the ADC output data, in Figure :ref:`noiseblast`. Note the measured peak-to-peak noise of 426mV, while the ADC peak-to-peak noise is about 26mV. While such a high noise level is (hopefully) unrealistic in an actual precision signal chain, this exercise demonstrates that the ADC’s internal filter can be relied on to act as the primary bandwidth limiting, and hence noise reducing, element in a signal chain.
```

2021-07-24 18:55 UTC, matthewfeickert commented on papers/adi_sdg/adi_scipycon_pynotebook.rst
> +.. [10] "pyadi-iio: Device Specific Python Interfaces For IIO Drivers",https://wiki.analog.com/resources/tools-software/linux-software/pyadi-iio, accessed 1 July, 2021.
Use consistent formatting for the URLs in references and make sure hyperlinks and DOIs properly link out / are rendered.

```suggestion
.. [2] Analog Devices Education Tools Repository https://doi.org/10.5281/zenodo.5105696

.. [3] Pauli Virtanen, Ralf Gommers et al. (2020) SciPy 1.0: Fundamental Algorithms for Scientific Computing in Python. Nature Methods, 17(3), 261-272.

.. [4] "LTspice Simulator", https://www.analog.com/en/design-center/design-tools-and-calculators/ltspice-simulator.html, accessed 1 July, 2021.

.. [5] Smith, Steven W, The Scientist & Engineer's Guide to Digital Signal Processing, https://www.analog.com/en/education/education-library/scientist_engineers_guide.html, accessed 1 July, 2021.

.. [6] Man, Ching, "Quantization Noise: An Expanded Derivation of the Equation, SNR = 6.02 N + 1.76", https://www.analog.com/media/en/training-seminars/tutorials/MT-229.pdf, accessed 1 July, 2021.

.. [7] Kester, Walt, "Taking the Mystery out of the Infamous Formula, "SNR = 6.02N + 1.76dB"" Analog Devices Tutorial, 2009, https://www.analog.com/media/en/training-seminars/tutorials/MT-001.pdf, accessed 1 July, 2021.

.. [8] "AD7124-8 Rev E" https://www.analog.com/media/en/technical-documentation/data-sheets/ad7124-8.pdf, accessed 1 July, 2021.



.. [9] Charles R. Harris, K. Jarrod Millman, et al. Array programming with NumPy, Nature, 585, 357–362 (2020)
       DOI:10.1038/s41586-020-2649-2

.. [10] "pyadi-iio: Device Specific Python Interfaces For IIO Drivers", https://wiki.analog.com/resources/tools-software/linux-software/pyadi-iio, accessed 1 July, 2021.
```

2021-07-24 18:55 UTC, matthewfeickert commented on papers/adi_sdg/adi_scipycon_pynotebook.rst
> +.. code-block:: python
c.f. comments RE: `numpy` imports

2021-07-24 18:55 UTC, matthewfeickert commented on papers/adi_sdg/adi_scipycon_pynotebook.rst
> +.. code-block:: python
c.f. comments RE: `numpy` imports

2021-07-24 18:55 UTC, matthewfeickert commented on papers/adi_sdg/adi_scipycon_pynotebook.rst
> +.. code-block:: python
c.f. comments RE: `numpy` imports

2021-07-24 19:45 UTC, mthoren-adi commented
Thank you @matthewfeickert , I've applied your explicit suggestions, and should be able to hit the rest by tomorrow morning. Will let you know when done.

2021-07-25 02:42 UTC, mthoren-adi commented
Hi @matthewfeickert , All comments should be addressed. Also a few edits and figure scaling here and there to avoid code snippets split across columns or pages.

2021-07-26 03:39 UTC, matthewfeickert approved these changes
Thanks for the quick revision work @mthoren-adi @cristina-suteu. I either forgot to flag this missing period or it got missed in your last edits, but if you add that this all LGTM now. Thanks very much for your work on this and I hope that you had a great SciPy!

2021-07-26 03:39 UTC, matthewfeickert commented on papers/adi_sdg/adi_scipycon_pynotebook.rst
> +All sensors, no matter how perfect, have some maximum input value (and a corresponding maximum output - which may be a voltage, current, resistance, or even dial position) and a finite noise floor -
```suggestion
All sensors, no matter how perfect, have some maximum input value (and a corresponding maximum output - which may be a voltage, current, resistance, or even dial position) and a finite noise floor - "wiggles" at the output that exist even if the input is perfectly still. At some point, a sensor with an electrical output will include an element with a finite resistance (or more generally, impedance) represented by Rsensor in Figure :ref:`genericsensor`. This represents one fundamental noise limit that cannot be improved upon - this resistance will produce, at a minimum:
```

2021-07-26 14:55 UTC, mthoren-adi commented
@matthewfeickert and… approved  :)

2021-07-26 15:40 UTC, stargaser commented
Looks good to me. Thanks, everyone, for all the effort in preparing and reviewing this paper.

2021-07-26 15:40 UTC, stargaser commented
@scoobies mark ready

2021-08-01 15:49 UTC, merged