Paper: PyCID: A Python Library for Causal Influence Diagrams
scipy-conference/scipy_proceedings pull request #632
Opened 2021-05-28 21:55 UTC by Jamesfox1

If you are creating this PR in order to submit a draft of your paper,
see http://procbuild.scipy.org/ for logs generated by the build
process.

See the [project readme](https://github.com/scipy-conference/scipy_proceedings#build-your-paper)
for more information.

*Editor*:  

*Reviewers*:

2021-05-28 21:55 UTC, scoobies commented
Hi!, I'm @scoobies, a friendly bot.

Type ```@scoobies help``` to discover how I can help you.

2021-05-28 21:57 UTC, Jamesfox1 commented
@scoobies help

2021-05-28 21:57 UTC, scoobies commented
Hello @Jamesfox1, here are the things you can ask me to do:

```

# List all available commands
@scoobies help

# Show our community Code of Conduct and Guidelines
@scoobies code of conduct

# Assign a user as the reviewer N of this submission (where N=1,2...)
@scoobies assign @username as reviewer 2

# Remove the user assigned as reviewer N of this submission (where N=1,2...)
@scoobies remove reviewer 2

# Add to this issue's reviewers list
@scoobies add @username to reviewers

# Remove from this issue's reviewers list
@scoobies remove @username from reviewers

# Assign a user as the editor of this submission
@scoobies assign @username as editor

# Remove the editor assigned to this submission
@scoobies remove editor

# Send an invitation to a user to collaborate in the review
@scoobies invite @username

# Add a user to this issue's assignees list
@scoobies add assignee: @username

# Remove a user from this issue's assignees list
@scoobies remove assignee: @username

# Builds paper
@scoobies build paper

# Checks build status
@scoobies build status

# Check the references of the paper for missing DOIs
# Optionally, it can be run on a non-default branch 
@scoobies check references
@scoobies check references from custom-branch-name

# Label issue with: paper
@scoobies mark paper

# Label issue with: needs-review. Remove labels: unready, needs-more-review, pending-comment, ready
@scoobies mark needs review

# Label issue with: needs-more-review. Remove labels: unready, needs-review, pending-comment, ready
@scoobies mark needs more review

# Label issue with: pending-comment. Remove labels: unready, needs-review, needs-more-review, ready
@scoobies mark pending comment

# Label issue with: ready. Remove labels: unready, needs-review, needs-more-review, pending-comment
@scoobies mark ready

# Label issue with: unready. Remove labels: needs-review, needs-more-review, pending-comment, ready
@scoobies mark not ready

# Label issue with: does_not_build:server
@scoobies mark server fail

# Remove labels: does_not_build:server
@scoobies mark server success

```

2021-05-29 00:30 UTC, deniederhut commented
@scoobies assign @deniederhut as editor

2021-05-29 00:30 UTC, scoobies commented
Assigned! @deniederhut is now the editor

2021-06-12 01:33 UTC, deniederhut commented
@scoobies add @deniederhut to reviewers

2021-06-12 01:33 UTC, scoobies commented
@deniederhut added to the reviewers list!

2021-06-12 01:36 UTC, deniederhut commented
Hey @Jamesfox1 ! We've had a hard time finding reviewers for this paper, so I'll be stepping in to provide feedback. I should have some comments for you this weekend.

2021-06-12 23:23 UTC, deniederhut requested changes
I really enjoyed reading this paper! It sounds like this library is really filling a missing need, and your examples late in the paper were both illustrative and timely.

I've left a few inline comments which mostly concern formatting, technical terminology, and references. The one non-trivial area where I see room for growth is in the introduction / background. A lot of conference attendees may not be familiar with causal inference (this could be their first exposure!), and I'm worried that they'll see the introduction and assume this paper isn't for them. It might help to spend some more time right at the beginning to motivate why this practice matters, and to spend some time giving readers good intuitions about what this tool does and how.

2021-06-12 23:23 UTC, deniederhut commented on papers/.vscode/settings.json
> +{
Please don't modify the repo outside of your paper's directory

2021-06-12 23:23 UTC, deniederhut commented on papers/james_fox/.vscode/settings.json
> +{
Did you mean to commit this?

2021-06-12 23:23 UTC, deniederhut commented on papers/james_fox/mybib.bib
> +@inproceedings{ankan2015pgmpy,
You can find the citation for this paper here: https://conference.scipy.org/proceedings/scipy2015/bib/ankur_ankan.bib

2021-06-12 23:23 UTC, deniederhut commented on papers/james_fox/mybib.bib
> +@article{everitt2019reward,
We would prefer the journal citation for this paper

2021-06-12 23:23 UTC, deniederhut commented on papers/james_fox/mybib.bib
> +@inproceedings{holtman2020towards,
This is missing a DOI

2021-06-12 23:23 UTC, deniederhut commented on papers/james_fox/mybib.bib
> +@article{kusner2017counterfactual,
We would prefer the conference citation for this paper

2021-06-12 23:23 UTC, deniederhut commented on papers/james_fox/mybib.bib
> +@article{howard2005influence,
This is missing a DOI

2021-06-12 23:23 UTC, deniederhut commented on papers/james_fox/mybib.bib
> +@article{borgonovo2016sensitivity,
This is missing a DOI

2021-06-12 23:23 UTC, deniederhut commented on papers/james_fox/mybib.bib
> +@techreport{hagberg2008exploring,
Was this a SciPy paper? http://conference.scipy.org/proceedings/scipy2008/paper_2/

2021-06-12 23:23 UTC, deniederhut commented on papers/james_fox/mybib.bib
> +@article{hunter2007matplotlib,
This is missing a DOI

2021-06-12 23:23 UTC, deniederhut commented on papers/james_fox/mybib.bib
> +@Article{harris2020array,
This is missing a DOI

2021-06-12 23:23 UTC, deniederhut commented on papers/james_fox/mybib.bib
> + month= sep,
I don't think we need the month, but presumably this should be `{September}`?

2021-06-12 23:23 UTC, deniederhut commented on papers/james_fox/pycid.rst
> +:institution: University of Oxford
I think we're missing a `:corresponding:` tag here

2021-06-12 23:23 UTC, deniederhut commented on papers/james_fox/pycid.rst
> +      U1=lambda d1, d2: agent1_payoff[d1_domain.index(d1),
These lines are a couple of characters over the column width. We might need to do something like

```python
U1=lambda d1, d2: agent1_payoff[
    d1_domain.index(d1), d2_domain.index(d2)
],
```

2021-06-12 23:23 UTC, deniederhut commented on papers/james_fox/pycid.rst
> +In this paper, we have demonstrated the usefulness of *PyCID* by focusing on causal influence diagrams; however, this library is also well suited for working with statistical influence diagrams. The
This is roughly where the 8 page mark is in the rendered pdf. Are they are a couple of sentences we could remove / shorten somewhere to stay within the limit?

2021-06-12 23:23 UTC, deniederhut commented on papers/james_fox/pycid.rst
> +Influence-diagrams (IDs) are used to represent and analyse decision making situations under uncertainty (:cite:`howard2005influence`, :cite:`miller1976development`). Like Bayesian Networks, IDs have
You can expect your audience at SciPy to be generally scientifically literate, but possibly unaware of things like causal inference or path analysis. Domain specific terms should be defined when they are used. 

You may also find it helpful to include a concrete example to ground your readers' intuition about what is being represented. Can you make a causal influence model that describes whether or not I buy an ice cream at the corner store? What is my utility node in that context? What is my decision rule? Which nodes are random or conditioned on other nodes?

2021-06-12 23:23 UTC, deniederhut commented on papers/james_fox/pycid.rst
> +Statistical and causal IDs have already shown promise for a wide variety of applications from the design of AI systems with safe and fair incentives (:cite:`everitt2021agent`, :cite:`carey2020incenti
Same comment as above - what does it mean to "show promise for ... medical decision-making"? What does causal inference give us that a doctor doesn't? Why would someone prefer a hospital that uses this tool? Why would someone use this tool for their own decision-making?

Could we include links to reference sites for pyAgrum and PySMILE? I've found three different python packages named pysmile on github, and none of them appear to be the one you mean.

2021-06-12 23:23 UTC, deniederhut commented on papers/james_fox/pycid.rst
> +Consequently, this paper introduces *PyCID* [#]_, a Python library built upon *pgmpy* and *NetworkX* :cite:`hagberg2008exploring`, that concentrates on this need for an implementation of IDs and IMs
Could we include definitions or examples for interventions and incentives? I think everyone will have a folk understanding of what these mean, but you are using them here as technical terms.

2021-06-12 23:23 UTC, deniederhut commented on papers/james_fox/pycid.rst
> +The next section will describe *PyCID*'s architecture along with installation instructions and some necessary background knowledge. We then move to showcasing some of *PyCID*'s features through appli
Did I miss what the MA stands for in MACIDs?

2021-06-12 23:23 UTC, deniederhut commented on papers/james_fox/pycid.rst
> +.. figure:: pycid.PNG
I don't know how helpful a graphic of the file layout is. This might be a place where we can trim the content down a bit to stay within the page limits?

2021-06-12 23:23 UTC, deniederhut commented on papers/james_fox/pycid.rst
> +*PyCID*'s base class is ``CausalBayesianNetwork``. This class inherits from *pgmpy*'s ``BayesianModel`` and represents a *causal Bayesian network*. Concretely, it extends ``BayesianModel`` by adding
This is a minor quibble, but abstract/concrete are technical terms in object-oriented programming. Maybe we could say "specifically", or "in particular"?

2021-06-12 23:23 UTC, deniederhut commented on papers/james_fox/pycid.rst
> +The */Core* folder
Typically, I see the organization of Python packages described in terms of modules and import paths, not folders. E.g. something like "The pycid.core module contains classes for instantiating causal bayesian networks and assigning probability distributions to their nodes... The pycid.analyze model contains functions for determining the effect of causal interventions on previously defined networks... etc".

2021-06-12 23:23 UTC, deniederhut commented on papers/james_fox/pycid.rst
> +Finally, *tests/* houses unit tests for all functions and public class methods; it contains a bash script `check-code.sh` for ensuring that all unit tests pass with *pytest*, for checking linting wit
I don't know how helpful it is to describe the testing practices here, but if you do, please cite pep8 (https://www.python.org/dev/peps/pep-0008/), pep 484 (https://www.python.org/dev/peps/pep-0484/), and pytest (https://github.com/pytest-dev/pytest/blob/main/CITATION)

2021-06-12 23:23 UTC, deniederhut commented on papers/james_fox/pycid.rst
> +Consider a simple 3 node CID where an agent's utility :math:`U` depends on their decision selected at :math:`D` and the value of a random chance variable :math:`X`. Also, assume that the agent can ob
This is super nitpicky, but technically that is an initializer, not a constructor.

2021-06-12 23:23 UTC, deniederhut commented on papers/james_fox/pycid.rst
> +
Also super nitpicky, but please include an `import pycid` in this first code example

2021-06-12 23:23 UTC, deniederhut commented on papers/james_fox/pycid.rst
> +      cid.add_cpds(U=lambda x, d: pycid.noisy_copy(d, \
I'm not sure we need this backslash here

2021-06-12 23:23 UTC, deniederhut commented on papers/james_fox/pycid.rst
> +With RI, we showed that implementing CIDs in *PyCID* can aid the design of fairer systems. With ICI, we demonstrate how *PyCID* can be used to help design safer AI systems. First, we can use analogou
> With RI, we showed that implementing CIDs in *PyCID* can aid the design of fairer systems. With ICI, we demonstrate how *PyCID* can be used to help design safer AI systems.

Given how closely linked these sentences are, would it make sense to have a stronger conjunction than proximity? Like, a semicolon or something?

2021-06-12 23:23 UTC, deniederhut commented on papers/james_fox/pycid.rst
> +**Hospital procurement example:** A hospital employs an AI system to automate a procurement process. A company wants to tender a contract to the hospital for the supply of some medical equipment. Bef
Probably we want either "of high quality" or "of high, and not poor".

2021-06-12 23:23 UTC, deniederhut commented on papers/james_fox/pycid.rst
> +In this paper, we have demonstrated the usefulness of *PyCID* by focusing on causal influence diagrams; however, this library is also well suited for working with statistical influence diagrams. The
Do we want to have a link to the causal incentives working group here?

2021-06-12 23:23 UTC, deniederhut commented on papers/james_fox/pycid.rst
> +We can now *solve* this CIM by finding the agent's optimal decision rule for :math:`D`:
What solver is PyCID using?

2021-06-12 23:24 UTC, deniederhut commented
@scoobies mark needs more review

2021-06-14 19:22 UTC, Jamesfox1 commented
> I really enjoyed reading this paper! It sounds like this library is really filling a missing need, and your examples late in the paper were both illustrative and timely.
> 
> I've left a few inline comments which mostly concern formatting, technical terminology, and references. The one non-trivial area where I see room for growth is in the introduction / background. A lot of conference attendees may not be familiar with causal inference (this could be their first exposure!), and I'm worried that they'll see the introduction and assume this paper isn't for them. It might help to spend some more time right at the beginning to motivate why this practice matters, and to spend some time giving readers good intuitions about what this tool does and how.

Many thanks for your detailed comments and suggestions Dillon. I'm going to work through them now. For your more general comment, you're right. I'm now going to include a basic example of an Influence Diagram in the introduction!

2021-06-14 19:23 UTC, Jamesfox1 commented on papers/james_fox/mybib.bib
> +@inproceedings{ankan2015pgmpy,
Thanks!

2021-06-14 19:23 UTC, Jamesfox1 commented on papers/james_fox/.vscode/settings.json
> +{
No, sorry!

2021-06-17 19:26 UTC, Jamesfox1 commented on papers/james_fox/pycid.rst
> +We can now *solve* this CIM by finding the agent's optimal decision rule for :math:`D`:
We wrote it - have clarified that it's a CID class method

2021-06-23 10:47 UTC, deniederhut commented
@Jamesfox1 to give everyone more time to respond to their reviews, we've pushed back the deadline for authors' final revisions to July 1st. How are the revisions coming along?

2021-06-23 17:26 UTC, Jamesfox1 commented on papers/james_fox/pycid.rst
> +Influence-diagrams (IDs) are used to represent and analyse decision making situations under uncertainty (:cite:`howard2005influence`, :cite:`miller1976development`). Like Bayesian Networks, IDs have
I have now incorporated a simple example into the introduction, which is then threaded through the first few sections. I have also (as far aas I can tell) now defined all new terms as and when they are used

2021-06-23 17:27 UTC, Jamesfox1 commented on papers/james_fox/pycid.rst
> +Statistical and causal IDs have already shown promise for a wide variety of applications from the design of AI systems with safe and fair incentives (:cite:`everitt2021agent`, :cite:`carey2020incenti
I have hopefully now addressed these questions

2021-06-23 17:27 UTC, Jamesfox1 commented on papers/james_fox/pycid.rst
> +Consequently, this paper introduces *PyCID* [#]_, a Python library built upon *pgmpy* and *NetworkX* :cite:`hagberg2008exploring`, that concentrates on this need for an implementation of IDs and IMs
done (and provided examples)

2021-06-23 17:28 UTC, Jamesfox1 commented on papers/james_fox/pycid.rst
> +The next section will describe *PyCID*'s architecture along with installation instructions and some necessary background knowledge. We then move to showcasing some of *PyCID*'s features through appli
Thanks! - It means "multi-agent"! I have edited this

2021-06-23 17:28 UTC, Jamesfox1 commented on papers/james_fox/pycid.rst
> +.. figure:: pycid.PNG
It's currently still included, say if you think it should still be removed

2021-06-23 17:28 UTC, Jamesfox1 commented on papers/james_fox/pycid.rst
> +The */Core* folder
I've made this change

2021-06-23 17:29 UTC, Jamesfox1 commented
@scoobies build paper

2021-06-23 17:29 UTC, scoobies commented
building paper...

2021-06-23 17:29 UTC, scoobies commented
{"data"=>{"info"=>"Build for paper Jamesfox1-2021 scheduled.  Note that builds are only executed if the current build attempt is more than 5 minutes old."}, "status"=>"success"}

2021-06-23 17:33 UTC, Jamesfox1 commented
> @Jamesfox1 to give everyone more time to respond to their reviews, we've pushed back the deadline for authors' final revisions to July 1st. How are the revisions coming along?

Thanks! I've pushed the revisions - hopefully I've addressed all of your suggestions? The main changes are:
1) adding example into the introduction
2) threading that example into the first few sections.
3) adding the actual definitions of VoI and VoC
4) structure of the library is explained in terms of modules and import paths now rather than files and folders 
5) tried to define any concept as soon as soon as it is introduced.

2021-06-25 14:57 UTC, deniederhut commented
Awesome! I'll take another look this week-end

2021-06-27 21:37 UTC, deniederhut requested changes
Thanks for making all those changes @Jamesfox1 ! I think I've found one more typo, but otherwise we should be good to go

2021-06-27 21:37 UTC, deniederhut commented on papers/james_fox/pycid.rst
> +In the Prisoner's dilemma, there is only one NE and this involves both player's defecting. We can then find that the expected utility for each agent is -2 under this NE joint policy profile:
I think we either want "both players defecting" or "both players' defections" here.

2021-06-27 21:38 UTC, deniederhut commented
@scoobies check references

2021-06-27 21:39 UTC, scoobies commented
```
Reference check summary (note 'MISSING' DOIs are suggestions that need verification):

OK DOIs

- 10.1017/CBO9780511808432 is OK
- 10.25080/Majora-7b98e3ed-001 is OK
- 10.1007/978-3-030-52152-3_21 is OK
- 10.1287/deca.1050.0020 is OK
- 10.1016/j.ejor.2015.06.032 is OK
- 10.1109/MCSE.2007.55 is OK
- 10.1038/s41586-020-2649-2 is OK

MISSING DOIs

- 10.1007/978-3-540-39879-0_9 may be a valid DOI for title: Real-world applications of influence diagrams
- 10.1016/s0899-8256(02)00544-4 may be a valid DOI for title: Multi-agent influence diagrams for representing and solving games
- 10.1007/s11229-021-03141-4 may be a valid DOI for title: Reward tampering problems and solutions in reinforcement learning: A causal influence diagram perspective
- 10.21236/ada026379 may be a valid DOI for title: Development of automated aids for decision analysis
- 10.2307/j.ctv173f1fh.6 may be a valid DOI for title: Equilibrium points in n-person games
- 10.1609/aaai.v34i03.5628 may be a valid DOI for title: Asymptotically unambitious artificial general intelligence

INVALID DOIs

- None
```

2021-06-27 21:42 UTC, deniederhut commented
👀  scoobies found a lot more DOIs than I did -- would mind checking if those are correct, and adding them to the bibfile if appropriate?

2021-06-27 21:42 UTC, deniederhut commented
@scoobies mark pending comment

2021-06-29 11:08 UTC, Jamesfox1 commented
@scoobies build paper

2021-06-29 11:08 UTC, scoobies commented
building paper...

2021-06-29 11:08 UTC, scoobies commented
{"data"=>{"info"=>"Build for paper Jamesfox1-2021 scheduled.  Note that builds are only executed if the current build attempt is more than 5 minutes old."}, "status"=>"success"}

2021-06-29 11:08 UTC, Jamesfox1 commented
@scoobies check references

2021-06-29 11:10 UTC, Jamesfox1 commented
> 👀 scoobies found a lot more DOIs than I did -- would mind checking if those are correct, and adding them to the bibfile if appropriate?

Thanks - added!

2021-06-29 11:10 UTC, scoobies commented
```
Reference check summary (note 'MISSING' DOIs are suggestions that need verification):

OK DOIs

- 10.1017/CBO9780511808432 is OK
- 10.1007/978-3-540-39879-0_9 is OK
- 10.25080/Majora-7b98e3ed-001 is OK
- 10.1007/s11229-021-03141-4 is OK
- 10.1007/978-3-030-52152-3_21 is OK
- 10.1287/deca.1050.0020 is OK
- 10.1016/j.ejor.2015.06.032 is OK
- 10.21236/ada026379 is OK
- 10.2307/j.ctv173f1fh.6 is OK
- 10.1609/aaai.v34i03.5628 is OK
- 10.1109/MCSE.2007.55 is OK
- 10.1038/s41586-020-2649-2 is OK

MISSING DOIs

- None

INVALID DOIs

- 10.1016/s0899-82560200544-4 is INVALID
```

2021-06-29 14:11 UTC, deniederhut commented
> 10.1016/s0899-82560200544-4 is INVALID

Hm not sure what's going on with scoobies there, but that one resolves on doi.org just fine.

2021-06-29 14:12 UTC, deniederhut approved these changes
Thanks for making all those changes! I think we're good to go

2021-06-29 14:13 UTC, deniederhut commented
@scoobies mark ready

2021-07-05 16:04 UTC, merged