my paper -- this does not compile yet
scipy-conference/scipy_proceedings pull request #638
Opened 2021-05-29 06:22 UTC by n33lima

If you are creating this PR in order to submit a draft of your paper,
see http://procbuild.scipy.org/ for logs generated by the build
process.

See the [project readme](https://github.com/scipy-conference/scipy_proceedings#build-your-paper)
for more information.

*Editor*:  

*Reviewers*:

2021-05-29 06:22 UTC, scoobies commented
Hi!, I'm @scoobies, a friendly bot.

Type ```@scoobies help``` to discover how I can help you.

2021-05-29 06:23 UTC, n33lima commented
@scoobies help

2021-05-29 06:23 UTC, scoobies commented
Hello @n33lima, here are the things you can ask me to do:

```

# List all available commands
@scoobies help

# Show our community Code of Conduct and Guidelines
@scoobies code of conduct

# Assign a user as the reviewer N of this submission (where N=1,2...)
@scoobies assign @username as reviewer 2

# Remove the user assigned as reviewer N of this submission (where N=1,2...)
@scoobies remove reviewer 2

# Add to this issue's reviewers list
@scoobies add @username to reviewers

# Remove from this issue's reviewers list
@scoobies remove @username from reviewers

# Assign a user as the editor of this submission
@scoobies assign @username as editor

# Remove the editor assigned to this submission
@scoobies remove editor

# Send an invitation to a user to collaborate in the review
@scoobies invite @username

# Add a user to this issue's assignees list
@scoobies add assignee: @username

# Remove a user from this issue's assignees list
@scoobies remove assignee: @username

# Builds paper
@scoobies build paper

# Checks build status
@scoobies build status

# Check the references of the paper for missing DOIs
# Optionally, it can be run on a non-default branch 
@scoobies check references
@scoobies check references from custom-branch-name

# Label issue with: paper
@scoobies mark paper

# Label issue with: needs-review. Remove labels: unready, needs-more-review, pending-comment, ready
@scoobies mark needs review

# Label issue with: needs-more-review. Remove labels: unready, needs-review, pending-comment, ready
@scoobies mark needs more review

# Label issue with: pending-comment. Remove labels: unready, needs-review, needs-more-review, ready
@scoobies mark pending comment

# Label issue with: ready. Remove labels: unready, needs-review, needs-more-review, pending-comment
@scoobies mark ready

# Label issue with: unready. Remove labels: needs-review, needs-more-review, pending-comment, ready
@scoobies mark not ready

# Label issue with: does_not_build:server
@scoobies mark server fail

# Remove labels: does_not_build:server
@scoobies mark server success

```

2021-05-29 13:09 UTC, deniederhut commented
@scoobies assign @cbcunc as editor

2021-05-29 13:09 UTC, scoobies commented
Assigned! @cbcunc is now the editor

2021-05-29 14:05 UTC, deniederhut commented
@scoobies build status

2021-05-29 14:05 UTC, scoobies commented
{"n33lima-2021"=>{"data"=>{"build_output"=>"[*] Updating proceedings build tools in {self.master_repo_path}...\nAlready up to date.\n[*] Check out paper repository...\nCloning into '/tmp/tmp7jab6wg2'...\nMoving proceedings build tools to temp directory...\n[*] Build the paper...\n<string>:69: (WARNING/2) Explicit markup ends without a blank line; unexpected unindent.\nBuilding: neelima_pulagam\n*** Warning: /tmp/tmp7jab6wg2/publisher/../output/neelima_pulagam/paper_stats.json does not exist.\nPDFLaTeX error output:\n================================================================================\nThis is pdfTeX, Version 3.14159265-2.6-1.40.18 (TeX Live 2017/Debian) (preloaded format=pdflatex)\n restricted \\write18 enabled.\nentering extended mode\n(./paper.tex\nLaTeX2e <2017-04-15>\nBabel <3.18> and hyphenation patterns for 3 language(s) loaded.\n(./IEEEtran.cls\nDocument Class: IEEEtran 2015/08/26 V1.8b by Michael Shell\n-- See the \"IEEEtran_HOWTO\" manual for usage information.\n-- http://www.michaelshell.org/tex/ieeetran/\n(/usr/share/texlive/texmf-dist/tex/latex/psnfss/ot1ppl.fd)\n-- Using IEEE Computer Society mode.\n-- Using 8.5in x 11in (letter) paper.\n-- Using PDF output.\n-- This is a 10 point document.\n) (/usr/share/texlive/texmf-dist/tex/latex/cmap/cmap.sty)\n(/usr/share/texlive/texmf-dist/tex/latex/base/ifthen.sty)\n(/usr/share/texlive/texmf-dist/tex/latex/base/fontenc.sty\n(/usr/share/texlive/texmf-dist/tex/latex/base/t1enc.def)\n(/usr/share/texlive/texmf-dist/tex/latex/psnfss/t1ppl.fd)<<t1.cmap>>)\n(/usr/share/texlive/texmf-dist/tex/latex/base/inputenc.sty\n(/usr/share/texlive/texmf-dist/tex/latex/base/utf8.def\n(/usr/share/texlive/texmf-dist/tex/latex/base/t1enc.dfu)\n(/usr/share/texlive/texmf-dist/tex/latex/base/ot1enc.dfu)\n(/usr/share/texlive/texmf-dist/tex/latex/base/omsenc.dfu)))\n(/usr/share/texlive/texmf-dist/tex/latex/graphics/color.sty\n(/usr/share/texlive/texmf-dist/tex/latex/graphics-cfg/color.cfg)\n(/usr/share/texlive/texmf-dist/tex/latex/graphics-def/pdftex.def)) (./scipy.sty\n (./status.sty (./draftwatermark.sty (./everypage.sty)\n(/usr/share/texlive/texmf-dist/tex/latex/graphics/graphicx.sty\n(/usr/share/texlive/texmf-dist/tex/latex/graphics/keyval.sty)\n(/usr/share/texlive/texmf-dist/tex/latex/graphics/graphics.sty\n(/usr/share/texlive/texmf-dist/tex/latex/graphics/trig.sty)\n(/usr/share/texlive/texmf-dist/tex/latex/graphics-cfg/graphics.cfg)))))\n(/usr/share/texlive/texmf-dist/tex/latex/psnfss/mathptmx.sty)\n(/usr/share/texlive/texmf-dist/tex/latex/psnfss/helvet.sty)\n(/usr/share/texlive/texmf-dist/tex/latex/psnfss/courier.sty)\n(/usr/share/texlive/texmf-dist/tex/latex/amsmath/amsmath.sty\nFor additional information on amsmath, use the `?' option.\n(/usr/share/texlive/texmf-dist/tex/latex/amsmath/amstext.sty\n(/usr/share/texlive/texmf-dist/tex/latex/amsmath/amsgen.sty))\n(/usr/share/texlive/texmf-dist/tex/latex/amsmath/amsbsy.sty)\n(/usr/share/texlive/texmf-dist/tex/latex/amsmath/amsopn.sty))\n(/usr/share/texlive/texmf-dist/tex/latex/amsfonts/amsfonts.sty)\n(/usr/share/texlive/texmf-dist/tex/latex/amsfonts/amssymb.sty)\n(/usr/share/texlive/texmf-dist/tex/latex/tools/bm.sty)\n(/usr/share/texlive/texmf-dist/tex/latex/hyperref/hyperref.sty\n(/usr/share/texlive/texmf-dist/tex/generic/oberdiek/hobsub-hyperref.sty\n(/usr/share/texlive/texmf-dist/tex/generic/oberdiek/hobsub-generic.sty))\n(/usr/share/texlive/texmf-dist/tex/generic/ifxetex/ifxetex.sty)\n(/usr/share/texlive/texmf-dist/tex/latex/oberdiek/auxhook.sty)\n(/usr/share/texlive/texmf-dist/tex/latex/oberdiek/kvoptions.sty)\n(/usr/share/texlive/texmf-dist/tex/latex/hyperref/pd1enc.def)\n(/usr/share/texlive/texmf-dist/tex/latex/latexconfig/hyperref.cfg)\n(/usr/share/texlive/texmf-dist/tex/latex/url/url.sty))\n(/usr/share/texlive/texmf-dist/tex/latex/hyperref/hpdftex.def\n(/usr/share/texlive/texmf-dist/tex/latex/oberdiek/rerunfilecheck.sty))\n\nPackage hyperref Warning: Option `pdftex' has already been used,\n(hyperref)                setting the option has no effect on input line 43.\n\n(/usr/share/texlive/texmf-dist/tex/latex/tools/longtable.sty)\n(/usr/share/texlive/texmf-dist/tex/latex/multirow/multirow.sty)\n(/usr/share/texlive/texmf-dist/tex/latex/base/textcomp.sty\n(/usr/share/texlive/texmf-dist/tex/latex/base/ts1enc.def\n(/usr/share/texlive/texmf-dist/tex/latex/base/ts1enc.dfu)))\n(/usr/share/texlive/texmf-dist/tex/latex/upquote/upquote.sty)\n(/usr/share/texlive/texmf-dist/tex/latex/fancyvrb/fancyvrb.sty\nStyle option: `fancyvrb' v2.7a, with DG/SPQR fixes, and firstline=lastline fix \n<2008/02/07> (tvz)))\nNo file paper.aux.\n(/usr/share/texlive/texmf-dist/tex/latex/base/ts1cmr.fd)\n(/usr/share/texlive/texmf-dist/tex/latex/psnfss/t1ptm.fd)\n-- Lines per column: 61 (exact).\n(/usr/share/texlive/texmf-dist/tex/context/base/mkii/supp-pdf.mkii\n[Loading MPS to PDF converter (version 2006.09.02).]\n) (/usr/share/texlive/texmf-dist/tex/latex/oberdiek/epstopdf-base.sty\n(/usr/share/texlive/texmf-dist/tex/latex/oberdiek/grfext.sty)\n(/usr/share/texlive/texmf-dist/tex/latex/latexconfig/epstopdf-sys.cfg))\n(/usr/share/texlive/texmf-dist/tex/latex/hyperref/nameref.sty\n(/usr/share/texlive/texmf-dist/tex/generic/oberdiek/gettitlestring.sty))\n(/usr/share/texlive/texmf-dist/tex/latex/psnfss/t1phv.fd)\n(/usr/share/texlive/texmf-dist/tex/latex/psnfss/ot1ztmcm.fd)<<ot1.cmap>>\n(/usr/share/texlive/texmf-dist/tex/latex/psnfss/omlztmcm.fd)<<oml.cmap>>\n(/usr/share/texlive/texmf-dist/tex/latex/psnfss/omsztmcm.fd)<<oms.cmap>>\n(/usr/share/texlive/texmf-dist/tex/latex/psnfss/omxztmcm.fd)<<omx.cmap>>\n(/usr/share/texlive/texmf-dist/tex/latex/psnfss/ot1ptm.fd)\n(/usr/share/texlive/texmf-dist/tex/latex/psnfss/upzd.fd)\n(/usr/share/texlive/texmf-dist/tex/latex/psnfss/ts1ptm.fd) (./page_numbers.tex)\n(/usr/share/texlive/texmf-dist/tex/latex/psnfss/t1pcr.fd) [1{/var/lib/texmf/fon\nts/map/pdftex/updmap/pdftex.map}] [2] [3]\n\n! Package inputenc Error: Unicode char σ (U+3C3)\n(inputenc)                not set up for use with LaTeX.\n\nSee the inputenc package documentation for explanation.\nType  H <return>  for immediate help.\n ...                                              \n                                                  \nl.289 where  σ\n                is the non linear activation function and  is the weight mat...\n!  ==> Fatal error occurred, no output PDF file produced!\nTranscript written on paper.log.\n\n================================================================================\n[X] Paper build failed.\nA build error occurred during the self.retrieve_pdf step.", "build_pdf_path"=>"", "build_status"=>"Build failed, no pdf can be found", "build_timestamp"=>"29/05 14:02"}, "status"=>"fail"}}

2021-05-29 14:15 UTC, deniederhut commented
Looks like the use of sigma might be tripping up the typesetter. You might try putting it in a dedicated math block, or try declaring the character as in [this s/o question](https://tex.stackexchange.com/questions/373811/cant-get-unicode-to-work-in-title-inputenc-unicode-char-not-set-up-for-use-w).

2021-05-29 14:19 UTC, n33lima commented
I'm actually in the middle of debugging the error right now, I think I'll have it figured out soon!

2021-05-29 14:26 UTC, deniederhut commented
Awesome!

On May 29, 2021, ivan-marroquin ***@***.***> wrote:
> I'm actually in the middle of debugging the error right now, I think
> I'll have it figured out soon!
>

—
You are receiving this because you commented.
Reply to this email directly, view it on GitHub
<https://github.com/scipy-
conference/scipy_proceedings/pull/638#issuecomment-850841174>, or
unsubscribe <https://github.com/notifications/unsubscribe-
auth/ABUM3LFRAGJNSJXK4ZYKEPLTQDZX3ANCNFSM45X7CWPA>.

2021-05-30 16:48 UTC, n33lima commented
@scoobies build status

2021-05-30 16:48 UTC, scoobies commented
{"n33lima-2021"=>{"data"=>{"build_output"=>"[*] Updating proceedings build tools in {self.master_repo_path}...\nAlready up to date.\n[*] Check out paper repository...\nCloning into '/tmp/tmp7jab6wg2'...\nMoving proceedings build tools to temp directory...\n[*] Build the paper...\n<string>:69: (WARNING/2) Explicit markup ends without a blank line; unexpected unindent.\nBuilding: neelima_pulagam\n*** Warning: /tmp/tmp7jab6wg2/publisher/../output/neelima_pulagam/paper_stats.json does not exist.\nPDFLaTeX error output:\n================================================================================\nThis is pdfTeX, Version 3.14159265-2.6-1.40.18 (TeX Live 2017/Debian) (preloaded format=pdflatex)\n restricted \\write18 enabled.\nentering extended mode\n(./paper.tex\nLaTeX2e <2017-04-15>\nBabel <3.18> and hyphenation patterns for 3 language(s) loaded.\n(./IEEEtran.cls\nDocument Class: IEEEtran 2015/08/26 V1.8b by Michael Shell\n-- See the \"IEEEtran_HOWTO\" manual for usage information.\n-- http://www.michaelshell.org/tex/ieeetran/\n(/usr/share/texlive/texmf-dist/tex/latex/psnfss/ot1ppl.fd)\n-- Using IEEE Computer Society mode.\n-- Using 8.5in x 11in (letter) paper.\n-- Using PDF output.\n-- This is a 10 point document.\n) (/usr/share/texlive/texmf-dist/tex/latex/cmap/cmap.sty)\n(/usr/share/texlive/texmf-dist/tex/latex/base/ifthen.sty)\n(/usr/share/texlive/texmf-dist/tex/latex/base/fontenc.sty\n(/usr/share/texlive/texmf-dist/tex/latex/base/t1enc.def)\n(/usr/share/texlive/texmf-dist/tex/latex/psnfss/t1ppl.fd)<<t1.cmap>>)\n(/usr/share/texlive/texmf-dist/tex/latex/base/inputenc.sty\n(/usr/share/texlive/texmf-dist/tex/latex/base/utf8.def\n(/usr/share/texlive/texmf-dist/tex/latex/base/t1enc.dfu)\n(/usr/share/texlive/texmf-dist/tex/latex/base/ot1enc.dfu)\n(/usr/share/texlive/texmf-dist/tex/latex/base/omsenc.dfu)))\n(/usr/share/texlive/texmf-dist/tex/latex/graphics/color.sty\n(/usr/share/texlive/texmf-dist/tex/latex/graphics-cfg/color.cfg)\n(/usr/share/texlive/texmf-dist/tex/latex/graphics-def/pdftex.def)) (./scipy.sty\n (./status.sty (./draftwatermark.sty (./everypage.sty)\n(/usr/share/texlive/texmf-dist/tex/latex/graphics/graphicx.sty\n(/usr/share/texlive/texmf-dist/tex/latex/graphics/keyval.sty)\n(/usr/share/texlive/texmf-dist/tex/latex/graphics/graphics.sty\n(/usr/share/texlive/texmf-dist/tex/latex/graphics/trig.sty)\n(/usr/share/texlive/texmf-dist/tex/latex/graphics-cfg/graphics.cfg)))))\n(/usr/share/texlive/texmf-dist/tex/latex/psnfss/mathptmx.sty)\n(/usr/share/texlive/texmf-dist/tex/latex/psnfss/helvet.sty)\n(/usr/share/texlive/texmf-dist/tex/latex/psnfss/courier.sty)\n(/usr/share/texlive/texmf-dist/tex/latex/amsmath/amsmath.sty\nFor additional information on amsmath, use the `?' option.\n(/usr/share/texlive/texmf-dist/tex/latex/amsmath/amstext.sty\n(/usr/share/texlive/texmf-dist/tex/latex/amsmath/amsgen.sty))\n(/usr/share/texlive/texmf-dist/tex/latex/amsmath/amsbsy.sty)\n(/usr/share/texlive/texmf-dist/tex/latex/amsmath/amsopn.sty))\n(/usr/share/texlive/texmf-dist/tex/latex/amsfonts/amsfonts.sty)\n(/usr/share/texlive/texmf-dist/tex/latex/amsfonts/amssymb.sty)\n(/usr/share/texlive/texmf-dist/tex/latex/tools/bm.sty)\n(/usr/share/texlive/texmf-dist/tex/latex/hyperref/hyperref.sty\n(/usr/share/texlive/texmf-dist/tex/generic/oberdiek/hobsub-hyperref.sty\n(/usr/share/texlive/texmf-dist/tex/generic/oberdiek/hobsub-generic.sty))\n(/usr/share/texlive/texmf-dist/tex/generic/ifxetex/ifxetex.sty)\n(/usr/share/texlive/texmf-dist/tex/latex/oberdiek/auxhook.sty)\n(/usr/share/texlive/texmf-dist/tex/latex/oberdiek/kvoptions.sty)\n(/usr/share/texlive/texmf-dist/tex/latex/hyperref/pd1enc.def)\n(/usr/share/texlive/texmf-dist/tex/latex/latexconfig/hyperref.cfg)\n(/usr/share/texlive/texmf-dist/tex/latex/url/url.sty))\n(/usr/share/texlive/texmf-dist/tex/latex/hyperref/hpdftex.def\n(/usr/share/texlive/texmf-dist/tex/latex/oberdiek/rerunfilecheck.sty))\n\nPackage hyperref Warning: Option `pdftex' has already been used,\n(hyperref)                setting the option has no effect on input line 43.\n\n(/usr/share/texlive/texmf-dist/tex/latex/tools/longtable.sty)\n(/usr/share/texlive/texmf-dist/tex/latex/multirow/multirow.sty)\n(/usr/share/texlive/texmf-dist/tex/latex/base/textcomp.sty\n(/usr/share/texlive/texmf-dist/tex/latex/base/ts1enc.def\n(/usr/share/texlive/texmf-dist/tex/latex/base/ts1enc.dfu)))\n(/usr/share/texlive/texmf-dist/tex/latex/upquote/upquote.sty)\n(/usr/share/texlive/texmf-dist/tex/latex/fancyvrb/fancyvrb.sty\nStyle option: `fancyvrb' v2.7a, with DG/SPQR fixes, and firstline=lastline fix \n<2008/02/07> (tvz)))\nNo file paper.aux.\n(/usr/share/texlive/texmf-dist/tex/latex/base/ts1cmr.fd)\n(/usr/share/texlive/texmf-dist/tex/latex/psnfss/t1ptm.fd)\n-- Lines per column: 61 (exact).\n(/usr/share/texlive/texmf-dist/tex/context/base/mkii/supp-pdf.mkii\n[Loading MPS to PDF converter (version 2006.09.02).]\n) (/usr/share/texlive/texmf-dist/tex/latex/oberdiek/epstopdf-base.sty\n(/usr/share/texlive/texmf-dist/tex/latex/oberdiek/grfext.sty)\n(/usr/share/texlive/texmf-dist/tex/latex/latexconfig/epstopdf-sys.cfg))\n(/usr/share/texlive/texmf-dist/tex/latex/hyperref/nameref.sty\n(/usr/share/texlive/texmf-dist/tex/generic/oberdiek/gettitlestring.sty))\n(/usr/share/texlive/texmf-dist/tex/latex/psnfss/t1phv.fd)\n(/usr/share/texlive/texmf-dist/tex/latex/psnfss/ot1ztmcm.fd)<<ot1.cmap>>\n(/usr/share/texlive/texmf-dist/tex/latex/psnfss/omlztmcm.fd)<<oml.cmap>>\n(/usr/share/texlive/texmf-dist/tex/latex/psnfss/omsztmcm.fd)<<oms.cmap>>\n(/usr/share/texlive/texmf-dist/tex/latex/psnfss/omxztmcm.fd)<<omx.cmap>>\n(/usr/share/texlive/texmf-dist/tex/latex/psnfss/ot1ptm.fd)\n(/usr/share/texlive/texmf-dist/tex/latex/psnfss/upzd.fd)\n(/usr/share/texlive/texmf-dist/tex/latex/psnfss/ts1ptm.fd) (./page_numbers.tex)\n(/usr/share/texlive/texmf-dist/tex/latex/psnfss/t1pcr.fd) [1{/var/lib/texmf/fon\nts/map/pdftex/updmap/pdftex.map}] [2] [3]\n\n! Package inputenc Error: Unicode char σ (U+3C3)\n(inputenc)                not set up for use with LaTeX.\n\nSee the inputenc package documentation for explanation.\nType  H <return>  for immediate help.\n ...                                              \n                                                  \nl.289 where  σ\n                is the non linear activation function and  is the weight mat...\n!  ==> Fatal error occurred, no output PDF file produced!\nTranscript written on paper.log.\n\n================================================================================\n[X] Paper build failed.\nA build error occurred during the self.retrieve_pdf step.", "build_pdf_path"=>"", "build_status"=>"Build failed, no pdf can be found", "build_timestamp"=>"29/05 14:02"}, "status"=>"fail"}}

2021-05-30 16:50 UTC, n33lima commented
@scoobies build paper

2021-05-30 16:50 UTC, scoobies commented
building paper...

2021-05-30 16:50 UTC, scoobies commented
{"data"=>{"info"=>"Build for paper n33lima-2021 scheduled.  Note that builds are only executed if the current build attempt is more than 5 minutes old."}, "status"=>"success"}

2021-05-30 18:22 UTC, cbcunc commented
Editor’s initial quickie look-over:

- [x] Make sure the paper builds on procbuild
- [ ] Make sure that the sections are filled in
- [x] Make sure 8 pages or less exclusive of references

I see bib files but I don’t see a list of references in the build.

2021-05-30 19:35 UTC, n33lima commented
@cbcunc  I'm having an issue with the ':bibliography: references' line in my paper.rst file. I tried a few different things to debut it and even tried just using the mybib.bib (example in 00_bibderwalt file) and tried to see if referencing that would work but it is keeps throwing an error. it doesn't like the one line referencing the bibliography.

2021-05-30 21:54 UTC, deniederhut commented
I don't see an error reported on the build server. What's the error
you're seeing locally?

On May 30, 2021, ivan-marroquin ***@***.***> wrote:
> @cbcunc <https://github.com/cbcunc> I'm having an issue with the
> ':bibliography: references' line in my paper.rst file. I tried a few
> different things to debut it and even tried just using the mybib.bib
> (example in 00_bibderwalt file) and tried to see if referencing that
> would work but it is keeps throwing an error. it doesn't like the one
> line referencing the bibliography.
>

—
You are receiving this because you commented.
Reply to this email directly, view it on GitHub
<https://github.com/scipy-
conference/scipy_proceedings/pull/638#issuecomment-851049844>, or
unsubscribe <https://github.com/notifications/unsubscribe-
auth/ABUM3LAM4MBE5WTH4XA7423TQKHPJANCNFSM45X7CWPA>.

2021-05-30 22:06 UTC, n33lima commented
Building: neelima_pulagam
PDFLaTeX error output:
================================================================================
This is pdfTeX, Version 3.141592653-2.6-1.40.22 (TeX Live 2021) (preloaded format=pdflatex)
 restricted \write18 enabled.
entering extended mode
(./paper.tex
LaTeX2e <2020-10-01> patch level 4
L3 programming layer <2021-02-18>
(/usr/local/texlive/2021/texmf-dist/tex/latex/IEEEtran/IEEEtran.cls
Document Class: IEEEtran 2015/08/26 V1.8b by Michael Shell
-- See the "IEEEtran_HOWTO" manual for usage information.
-- http://www.michaelshell.org/tex/ieeetran/
(/usr/local/texlive/2021/texmf-dist/tex/latex/psnfss/ot1ppl.fd)
-- Using IEEE Computer Society mode.
-- Using 8.5in x 11in (letter) paper.
[paper.log](https://github.com/scipy-conference/scipy_proceedings/files/6566977/paper.log)
) (/usr/local/texlive/2021/texmf-dist/tex/latex/cmap/cmap.sty)
(/usr/local/texlive/2021/texmf-dist/tex/latex/base/ifthen.sty)
(/usr/local/texlive/2021/texmf-dist/tex/latex/base/fontenc.sty
(/usr/local/texlive/2021/texmf-dist/tex/latex/psnfss/t1ppl.fd)<<t1.cmap>>)
(/usr/local/texlive/2021/texmf-dist/tex/latex/base/inputenc.sty)
(/usr/local/texlive/2021/texmf-dist/tex/latex/amsmath/amsmath.sty
For additional information on amsmath, use the `?' option.
(/usr/local/texlive/2021/texmf-dist/tex/latex/amsmath/amstext.sty
(/usr/local/texlive/2021/texmf-dist/tex/latex/amsmath/amsgen.sty))
(/usr/local/texlive/2021/texmf-dist/tex/latex/amsmath/amsbsy.sty)
(/usr/local/texlive/2021/texmf-dist/tex/latex/amsmath/amsopn.sty))
(/usr/local/texlive/2021/texmf-dist/tex/latex/booktabs/booktabs.sty)
(/usr/local/texlive/2021/texmf-dist/tex/latex/caption/caption.sty
(/usr/local/texlive/2021/texmf-dist/tex/latex/caption/caption3.sty
(/usr/local/texlive/2021/texmf-dist/tex/latex/graphics/keyval.sty))

Package caption Warning: Unknown document class (or package),
(caption)                standard defaults will be used.
See the caption package documentation for explanation.

) (/usr/local/texlive/2021/texmf-dist/tex/latex/float/float.sty)
(/usr/local/texlive/2021/texmf-dist/tex/latex/tools/longtable.sty)
(/usr/local/texlive/2021/texmf-dist/tex/latex/caption/ltcaption.sty)
(/usr/local/texlive/2021/texmf-dist/tex/latex/tools/array.sty) (./scipy.sty
(./status.sty
(/usr/local/texlive/2021/texmf-dist/tex/latex/draftwatermark/draftwatermark.sty
(/usr/local/texlive/2021/texmf-dist/tex/latex/kvoptions/kvoptions.sty
(/usr/local/texlive/2021/texmf-dist/tex/generic/ltxcmds/ltxcmds.sty)
(/usr/local/texlive/2021/texmf-dist/tex/generic/kvsetkeys/kvsetkeys.sty))
(/usr/local/texlive/2021/texmf-dist/tex/latex/graphics/graphicx.sty
(/usr/local/texlive/2021/texmf-dist/tex/latex/graphics/graphics.sty
(/usr/local/texlive/2021/texmf-dist/tex/latex/graphics/trig.sty)
(/usr/local/texlive/2021/texmf-dist/tex/latex/graphics-cfg/graphics.cfg)
(/usr/local/texlive/2021/texmf-dist/tex/latex/graphics-def/pdftex.def)))
(/usr/local/texlive/2021/texmf-dist/tex/latex/graphics/color.sty
(/usr/local/texlive/2021/texmf-dist/tex/latex/graphics-cfg/color.cfg))))
(/usr/local/texlive/2021/texmf-dist/tex/latex/psnfss/mathptmx.sty)
(/usr/local/texlive/2021/texmf-dist/tex/latex/psnfss/helvet.sty)
(/usr/local/texlive/2021/texmf-dist/tex/latex/psnfss/courier.sty)
(/usr/local/texlive/2021/texmf-dist/tex/latex/amsfonts/amsfonts.sty)
(/usr/local/texlive/2021/texmf-dist/tex/latex/amsfonts/amssymb.sty)
(/usr/local/texlive/2021/texmf-dist/tex/latex/tools/bm.sty)
(/usr/local/texlive/2021/texmf-dist/tex/latex/hyperref/hyperref.sty
(/usr/local/texlive/2021/texmf-dist/tex/generic/iftex/iftex.sty)
(/usr/local/texlive/2021/texmf-dist/tex/generic/pdftexcmds/pdftexcmds.sty
(/usr/local/texlive/2021/texmf-dist/tex/generic/infwarerr/infwarerr.sty))
(/usr/local/texlive/2021/texmf-dist/tex/generic/kvdefinekeys/kvdefinekeys.sty)
(/usr/local/texlive/2021/texmf-dist/tex/generic/pdfescape/pdfescape.sty)
(/usr/local/texlive/2021/texmf-dist/tex/latex/hycolor/hycolor.sty)
(/usr/local/texlive/2021/texmf-dist/tex/latex/letltxmacro/letltxmacro.sty)
(/usr/local/texlive/2021/texmf-dist/tex/latex/auxhook/auxhook.sty)
(/usr/local/texlive/2021/texmf-dist/tex/latex/hyperref/pd1enc.def)
(/usr/local/texlive/2021/texmf-dist/tex/latex/hyperref/hyperref-langpatches.def
) (/usr/local/texlive/2021/texmf-dist/tex/generic/intcalc/intcalc.sty)
(/usr/local/texlive/2021/texmf-dist/tex/generic/etexcmds/etexcmds.sty)
(/usr/local/texlive/2021/texmf-dist/tex/latex/hyperref/puenc.def)
(/usr/local/texlive/2021/texmf-dist/tex/latex/url/url.sty)
(/usr/local/texlive/2021/texmf-dist/tex/generic/bitset/bitset.sty
(/usr/local/texlive/2021/texmf-dist/tex/generic/bigintcalc/bigintcalc.sty))
(/usr/local/texlive/2021/texmf-dist/tex/latex/base/atbegshi-ltx.sty))
(/usr/local/texlive/2021/texmf-dist/tex/latex/hyperref/hpdftex.def
(/usr/local/texlive/2021/texmf-dist/tex/latex/base/atveryend-ltx.sty)
(/usr/local/texlive/2021/texmf-dist/tex/latex/rerunfilecheck/rerunfilecheck.sty

(/usr/local/texlive/2021/texmf-dist/tex/generic/uniquecounter/uniquecounter.sty
)))

Package hyperref Warning: Option `pdftex' has already been used,
(hyperref)                setting the option has no effect on input line 43.

(/usr/local/texlive/2021/texmf-dist/tex/latex/multirow/multirow.sty)
(/usr/local/texlive/2021/texmf-dist/tex/latex/base/textcomp.sty)
(/usr/local/texlive/2021/texmf-dist/tex/latex/upquote/upquote.sty)
(/usr/local/texlive/2021/texmf-dist/tex/latex/fancyvrb/fancyvrb.sty))
(/usr/local/texlive/2021/texmf-dist/tex/latex/psnfss/t1ptm.fd)
(/usr/local/texlive/2021/texmf-dist/tex/latex/l3backend/l3backend-pdftex.def)
(./paper.aux)
-- Lines per column: 61 (exact).
(/usr/local/texlive/2021/texmf-dist/tex/context/base/mkii/supp-pdf.mkii
[Loading MPS to PDF converter (version 2006.09.02).]
) (/usr/local/texlive/2021/texmf-dist/tex/latex/epstopdf-pkg/epstopdf-base.sty
(/usr/local/texlive/2021/texmf-dist/tex/latex/latexconfig/epstopdf-sys.cfg))
(/usr/local/texlive/2021/texmf-dist/tex/latex/hyperref/nameref.sty
(/usr/local/texlive/2021/texmf-dist/tex/latex/refcount/refcount.sty)
(/usr/local/texlive/2021/texmf-dist/tex/generic/gettitlestring/gettitlestring.s
ty)) (./paper.out) (./paper.out)
(/usr/local/texlive/2021/texmf-dist/tex/latex/psnfss/t1phv.fd)
(/usr/local/texlive/2021/texmf-dist/tex/latex/psnfss/ot1ztmcm.fd)<<ot1.cmap>>
(/usr/local/texlive/2021/texmf-dist/tex/latex/psnfss/omlztmcm.fd)<<oml.cmap>>
(/usr/local/texlive/2021/texmf-dist/tex/latex/psnfss/omsztmcm.fd)<<oms.cmap>>
(/usr/local/texlive/2021/texmf-dist/tex/latex/psnfss/omxztmcm.fd)<<omx.cmap>>
(/usr/local/texlive/2021/texmf-dist/tex/latex/psnfss/ot1ptm.fd)
(/usr/local/texlive/2021/texmf-dist/tex/latex/psnfss/upzd.fd)
(/usr/local/texlive/2021/texmf-dist/tex/latex/psnfss/ts1ptm.fd)
(./page_numbers.tex)

LaTeX Warning: Citation `Ramond_2019' on page 1 undefined on input line 168.


LaTeX Warning: Citation `Delogu2013' on page 1 undefined on input line 170.


LaTeX Warning: Citation `Delogu2013' on page 1 undefined on input line 170.


LaTeX Warning: Citation `durden18' on page 1 undefined on input line 172.


LaTeX Warning: Citation `oei_2019' on page 1 undefined on input line 172.


LaTeX Warning: Citation `yao_2019' on page 1 undefined on input line 172.


LaTeX Warning: Citation `Reishi_2018' on page 1 undefined on input line 172.


LaTeX Warning: Citation `Ramond_2019' on page 1 undefined on input line 172.


LaTeX Warning: No positions in optional float specifier.
               Default added (so using `tbp') on input line 176.


LaTeX Warning: No positions in optional float specifier.
               Default added (so using `tbp') on input line 178.


LaTeX Warning: No positions in optional float specifier.
               Default added (so using `tbp') on input line 180.

[1{/usr/local/texlive/2021/texmf-var/fonts/map/pdftex/updmap/pdftex.map}]

LaTeX Warning: Citation `Ramond_2019' on page 2 undefined on input line 194.


LaTeX Warning: Citation `Karbowski_2003' on page 2 undefined on input line 194.



LaTeX Warning: Citation `Karbowski [...]

2021-05-30 22:08 UTC, n33lima commented
That's the error I'm seeing. It's only throwing an error for the bibliography line.

2021-05-31 14:08 UTC, deniederhut commented
Okay so I've dug around a bit in the logs and everything looks okay on the server. I can build your paper locally too. I would guess that you have an old `.bbl` file hanging around that is messing up your local compiles. Could you try deleting the whole `output` directory, then re-running the `make_paper` command?

2021-06-01 17:32 UTC, n33lima commented
That worked! Thank you so much!!

2021-06-01 18:32 UTC, n33lima commented
@scoobies build paper

2021-06-01 18:32 UTC, scoobies commented
building paper...

2021-06-01 18:32 UTC, scoobies commented
{"data"=>{"info"=>"Build for paper n33lima-2021 scheduled.  Note that builds are only executed if the current build attempt is more than 5 minutes old."}, "status"=>"success"}

2021-06-07 11:17 UTC, deniederhut commented
@scoobies add @alberto-antonietti to reviewers

2021-06-07 11:17 UTC, scoobies commented
@alberto-antonietti added to the reviewers list!

2021-06-07 23:43 UTC, deniederhut commented
We've been having difficulty finding reviewers for some papers, so to make sure everyone has enough time to do their reviews, we will be bumping the deadline for the initial review back to June 17th.

2021-06-18 12:05 UTC, deniederhut commented
Hi @alberto-antonietti! Have you had a chance to review this paper? We were expecting to see your comments yesterday.

2021-06-18 13:38 UTC, alberto-antonietti commented
Hi @deniederhut, sorry for the delay! I am posting my review right now.

2021-06-18 15:05 UTC, alberto-antonietti commented
Thank you @n33lima for your contribution to SciPy! I read your paper and it is very good work, congratulations!

I have some comments that I believe could improve it.

Major issues:
1) You have reported the results just in terms of accuracy, since you are doing two sets of binary classifications you could also add sensitivity and specificity (and also F1-score, if you want).
2) From Table 1, it appears that the accuracy obtained with GNN is lower than standard methods in both cases (Llo vs Control and LLo vs Mdivi). Which is therefore the advantage of using the GNN? Just the possibility of using fewer training samples (since you did downsampling for those methods). Could you show that the traditional methods are not performing as well as GNN if you do not use SMOTE but just downsample the dataset to have class balance?
3) The details that you are providing for the implementation of the GNN are not sufficient to re-build the same architecture. It would be great if you can publish your code (e.g., in a GitHub repository) and then add a link in the paper, so who would re-use your method will be facilitated in this. 

There are other issues that I am going to report as a code review, since they are more specific.

I look forward to seeing the updates!

2021-06-18 15:40 UTC, alberto-antonietti requested changes
See major comments on the PR discussion.

2021-06-18 15:40 UTC, alberto-antonietti commented on papers/neelima_pulagam/paper.rst
> +Characterizing dynamic sub-cellular morphologies in response to perturbation remains a challenging and important problem. Many organelles are anisotropic and difficult to segment, and few methods exi
> Characterizing dynamic sub-cellular morphologies in response to perturbation

What do you mean with "perturbation"?

2021-06-18 15:40 UTC, alberto-antonietti commented on papers/neelima_pulagam/paper.rst
> +Tuberculosis causes structural changes to the mitochondria of cells that have been infected. :cite:`Delogu2013`.This ancient disease, although curable and treatable, can be fatal when not diagnosed p
TB, Mtb, etc. please define all the acronym at the first occurrence. I suggest to avoid using the acronym when they are used less than 2-3 times in the text (e.g., TB - 2 times, Mtb, 1 time, etc.).

2021-06-18 15:40 UTC, alberto-antonietti commented on papers/neelima_pulagam/paper.rst
> +Recent advancements in fluorescence microscopy and biomedical imaging have offered new ways to analyze these pathogens and their effects on cell health :cite:`durden18`. Previous studies have propose
What do you mean by "niche"? Is it a specific biology term? 

> :cite:`Reishi_2018

 is missing

2021-06-18 15:40 UTC, alberto-antonietti commented on papers/neelima_pulagam/paper.rst
> +Mitochondria are double-membrane organelles that act as the powerhouse of the cell because they generate a high amount of ATP from high-energy molecules and modulate programmed cell death pathways :c
> These morphologies ,fission
misplaced comma

Please add a brief explanation about what fission and fusion are and how their visual differences.

2021-06-18 15:40 UTC, alberto-antonietti commented on papers/neelima_pulagam/paper.rst
> +Mitochondria are double-membrane organelles that act as the powerhouse of the cell because they generate a high amount of ATP from high-energy molecules and modulate programmed cell death pathways :c
mtDNA see previous comment on acronyms

2021-06-18 15:40 UTC, alberto-antonietti commented on papers/neelima_pulagam/paper.rst
> +Anomalies in a cell’s dynamics are very telling of the health of a cell and could be a result of toxic conditions. In recent studies, it has been shown that pathogens attack the host by disturbing th
> :cite:`Reishi_2018`.

Missing reference

2021-06-18 15:40 UTC, alberto-antonietti commented on papers/neelima_pulagam/paper.rst
> +Advancements to microscopy and deep learning has led way to a new generation of cell and cell morphologies classification techniques. More recently, image based analyses have advanced past single cel
Please define CNN

2021-06-18 15:40 UTC, alberto-antonietti commented on papers/neelima_pulagam/paper.rst
> +Transfer learning has also given rise to novel advancements and shows much promise in cell classification tasks :cite:`Moran_2018`. :cite:`Moran_2018` utilizes a hybrid between generative adversarial
Why is the problem multi-class? Isn't it a binary classification?

2021-06-18 15:40 UTC, alberto-antonietti commented on papers/neelima_pulagam/paper.rst
> +Another transfer learning method that deals specifically with classifying organelle morphology is :cite:`Li_2021`. This approach applies CNNs and their advantages of automatic feature engineering and
> , all of

extra space

2021-06-18 15:40 UTC, alberto-antonietti commented on papers/neelima_pulagam/paper.rst
> +Graph machine learning has been drawing increasing attention in recent years due to its versatility and numerous applications especially in biomedical research.Graphs offer a unique way to represent
> research.Graphs

> entities(vertices)

> elationships(edges)

missing spaces

2021-06-18 15:40 UTC, alberto-antonietti commented on papers/neelima_pulagam/paper.rst
> +Graph machine learning has been drawing increasing attention in recent years due to its versatility and numerous applications especially in biomedical research.Graphs offer a unique way to represent
> :cite:`Perozzi_2014`

missing citation

2021-06-18 15:40 UTC, alberto-antonietti commented on papers/neelima_pulagam/paper.rst
> +For the context of our problem we utilize graph convolution operations defined by graph convolutional networks in :cite:`Kipf_2016` and a GCS layer operations used to build graph neural networks with
Please define ARMA

2021-06-18 15:40 UTC, alberto-antonietti commented on papers/neelima_pulagam/paper.rst
> +The data consists of a series of live confocal imaging videos that portray the various mitochondrial morphologies in HeLA cells. For visualization purposes, the cell was transfected with the DsRed2-M
Figures are never referenced in the text, please ensure that all figures are called at least one time in the main body text.

2021-06-18 15:40 UTC, alberto-antonietti commented on papers/neelima_pulagam/paper.rst
> +From the 114 videos, we take the last frame and create node features for each single cell video. The dataset we used to train and test our methods contains a node feature matrix and an adjacency matr
Could you please clarify why you choose the last frame of the video? Would it be OK also to choose another frame of the video (after the event)?

2021-06-18 15:40 UTC, alberto-antonietti commented on papers/neelima_pulagam/paper.rst
> +After the data preprocessing, there are 114 feature matrices of the shape [N,N,5] where N is the number of nodes in the mitochondrial cluster and a fully connected adjacency matrix of shape [N,N] tha
> fusion even,

typo

2021-06-18 15:40 UTC, alberto-antonietti commented on papers/neelima_pulagam/paper.rst
> +To contextualize the empirical results, we split the problem up into two different binary classification problems. One problem is to differentiate between the fusion and fission events, i.e categoriz
> i.e

i.e.,

2021-06-18 15:40 UTC, alberto-antonietti commented on papers/neelima_pulagam/paper.rst
> +   The first, middle and last frames on a control cell with no chemical exposure.
Please add in the legend information about the cell that is depicted and the color given by which transfecting protein.

2021-06-18 15:40 UTC, alberto-antonietti commented on papers/neelima_pulagam/paper.rst
> +.. figure:: control.png
Please add a scalebar to Figures 1, 2 and 3.

2021-06-18 15:40 UTC, alberto-antonietti commented on papers/neelima_pulagam/paper.rst
> +.. figure:: llo.png
This figure can be hardly seen, would it be possible to use a white background instead of the black one? Or increase the contrast, just for the sake of visualization, stating the transformation applied in the legend.

2021-06-18 15:40 UTC, alberto-antonietti commented on papers/neelima_pulagam/paper.rst
> +.. figure:: mdivi.png
This figure can be hardly seen, would it be possible to use a white background instead of the black one? Or increase the contrast, just for the sake of visualization, stating the transformation applied in the legend.

2021-06-18 15:40 UTC, alberto-antonietti commented on papers/neelima_pulagam/paper.rst
> +where :math:`sigma` is the non linear activation function that can be ReLU, sigmoid or hyperbolic tangent (tanh) functions. W and V are trainable parameters. Each GCS layer is localized in the node s
> :math:`sigma`

:math:`\sigma`

2021-06-18 15:40 UTC, alberto-antonietti commented on papers/neelima_pulagam/paper.rst
> +where :math:`\sigma` s the non linear activation function and :math:`W^{(t)}` is the weight matrix at t-th neural network layer.
please explain what `L` is.

2021-06-18 15:40 UTC, alberto-antonietti commented on papers/neelima_pulagam/paper.rst
> +.. figure:: Key.png
Please increase the font size of the text present.

Also, please align vertically all the arrows.

2021-06-18 15:40 UTC, alberto-antonietti commented on papers/neelima_pulagam/paper.rst
> +.. figure:: GCS.png
Please increase the font size of the text present.

Also, please align vertically all the arrows.

2021-06-18 15:40 UTC, alberto-antonietti commented on papers/neelima_pulagam/paper.rst
> +This approach deals with finding a good graph representation by using a method similar tob bag of nodes. Because the available number of graphs for each class are limited, we created a graph feature
> tob bag

typo

2021-06-18 15:40 UTC, alberto-antonietti commented on papers/neelima_pulagam/paper.rst
> +We test the performance of our methods on two different classification tasks: (i) categorize between the last frame images of mitochondria that have been exposed to toxin listeriolysin (class llo) an
> (ii)categorize

Missing space

2021-06-18 15:40 UTC, alberto-antonietti commented on papers/neelima_pulagam/paper.rst
> +Due to the class imbalance and relatively small size of the dataset, (llo had 54 instances, mdivi had 31 instances and control had 29 instances) we had to downsample the llo which was the majority cl
Why did you choose to downsample instead of using SMOTE?

2021-06-18 15:40 UTC, alberto-antonietti commented on papers/neelima_pulagam/paper.rst
> +.. table:: Results of the models for the two binary classification problems. :label:`rtable`
Please add in the table caption that these are accuracies.

2021-06-18 15:40 UTC, alberto-antonietti commented on papers/neelima_pulagam/paper.rst
> +   | Max-kNN              |     0.565       |     0.578       |
Why is the Max-kNN having values lower than the Mean?

2021-06-18 15:40 UTC, alberto-antonietti commented on papers/neelima_pulagam/paper.rst
> +and 10 training instances. The Mdivi-Llo also had 44 instances of each class in the training set and had a test set consisting of 7 mdivi instances and 10 llo. The number of instances slightly differ
> Similarly to the GNN approach the frames cohen for training and test set for each run were randomly subsampeld each time.

What are the frames cohen?

2021-06-21 15:03 UTC, n33lima commented
Hi @alberto-antonietti, thank you for the comments! I am currently working through the changes and make those fixes!

2021-06-23 10:56 UTC, deniederhut commented
@scoobies mark needs more review

2021-06-23 10:56 UTC, deniederhut commented
@n33lima to give everyone more time to respond to their reviews, we've pushed back the deadline for authors' final revisions to July 1st

2021-06-25 18:49 UTC, cbcunc commented
@scoobies check references

2021-06-25 18:53 UTC, scoobies commented
```
Reference check summary (note 'MISSING' DOIs are suggestions that need verification):

OK DOIs

- 10.25080/Majora-4af1f417-000 is OK
- 10.1109/tpami.2021.3054830 is OK
- 10.25080/Majora-342d178e-00d is OK
- 10.1093/plphys/kiab223 is OK
- 10.1109/JBHI.2018.2878878 is OK
- DOI10.5772/intechopen.73036 is OK
- 10.1145/2623330.2623732 is OK
- arXiv1409.1556v6 is OK
- 10.21105/joss.01983 is OK

MISSING DOIs

- 10.1109/cvpr.2016.308 may be a valid DOI for title: Rethinking the Inception Architecture for Computer Vision
- 10.1109/cvpr.2016.90 may be a valid DOI for title: Deep Residual Learning for Image Recognition

INVALID DOIs

- "https://doi.org/10.1109/MCI.2020.3039072" is INVALID because of 'https://doi.org/' prefix
- https://doi.org/10.1038/sj.cdd.4401260 is INVALID because of 'https://doi.org/' prefix
- 10.3389/fimmu.2019.02461. is INVALID
- https://doi.org/10.1016/j.mad.2020.111212 is INVALID because of 'https://doi.org/' prefix
- "https://doi.org/10.1371/journal.pone.0213626" is INVALID because of 'https://doi.org/' prefix
- "https://doi.org/10.4084/MJHID.2013.070" is INVALID because of 'https://doi.org/' prefix
- "https://doi.org/10.1038/s41598-019-50010-" is INVALID because of 'https://doi.org/' prefix
- https://doi.org/10.1613/jair.953 is INVALID because of 'https://doi.org/' prefix
```

2021-06-29 14:22 UTC, deniederhut commented
Hi @n33lima ! Have you had a chance to respond to your reviewers' suggestions?

2021-06-29 14:22 UTC, deniederhut commented
@scoobies mark pending comment

2021-06-29 15:10 UTC, n33lima commented
Hi @deniederhut! I apologize for the delay! I'm still working through some changes. Most of them are minor changes but there is one comment that is taking a bit longer than expected. I'll push my changes today.

2021-07-01 11:16 UTC, deniederhut commented
Thanks! It looks like some of your references are still missing DOIs, or have them formatted incorrectly (see comment here: https://github.com/scipy-conference/scipy_proceedings/pull/638#issuecomment-868767870). Would you mind taking a look at those?

2021-07-01 12:20 UTC, n33lima commented
Hi @deniederhut! Yes I intend to do that and the changes of the first comment by @alberto-antonietti that I am still working on but almost finished with. I'll push both of those today asap.

2021-07-02 02:08 UTC, n33lima commented
@scoobies check references

2021-07-02 02:10 UTC, scoobies commented
```
Reference check summary (note 'MISSING' DOIs are suggestions that need verification):

OK DOIs

- 10.25080/Majora-4af1f417-000 is OK
- 10.1109/TPAMI.2021.3054830 is OK
- 10.25080/Majora-342d178e-00d is OK
- 10.1093/plphys/kiab223 is OK
- 10.1016/j.media.2019.06.014 is OK
- 10.1109/JBHI.2018.2878878 is OK
- 10.1016/j.aiopen.2021.01.001 is OK
- 10.5772/intechopen.73036 is OK
- 10.1038/sj.cdd.4401260 is OK
- 10.1016/j.mad.2020.111212 is OK
- 10.1371/journal.pone.0213626 is OK
- 10.4084/MJHID.2013.070 is OK
- 10.1038/s41598-019-50010-9 is OK
- 10.1613/jair.953 is OK
- 10.1145/2623330.2623732 is OK
- 10.1109/CVPR.2016.308 is OK
- 10.1109/CVPR.2016.90 is OK
- 10.1109/CVPR.2017.243 is OK
- 10.21105/joss.01983 is OK
- 10.1145/2623330.2623732 is OK

MISSING DOIs

- None

INVALID DOIs

- 10.3389/fimmu.2019.02461. is INVALID
```

2021-07-02 03:55 UTC, n33lima commented
@scoobies build paper

2021-07-02 03:55 UTC, scoobies commented
building paper...

2021-07-02 03:56 UTC, scoobies commented
{"data"=>{"info"=>"Build for paper n33lima-2021 scheduled.  Note that builds are only executed if the current build attempt is more than 5 minutes old."}, "status"=>"success"}

2021-07-02 04:03 UTC, n33lima commented
building paper...

2021-07-02 04:04 UTC, n33lima commented
@scoobies build paper

2021-07-02 04:04 UTC, scoobies commented
building paper...

2021-07-02 04:04 UTC, scoobies commented
{"data"=>{"info"=>"Build for paper n33lima-2021 scheduled.  Note that builds are only executed if the current build attempt is more than 5 minutes old."}, "status"=>"success"}

2021-07-02 04:08 UTC, n33lima commented
I finished making all the changes! I also fixed the references so there shouldn't be any issues this time.

2021-07-02 04:14 UTC, n33lima commented
@alberto-antonietti Thank you very much again for the helpful comments!

2021-07-02 04:23 UTC, n33lima commented on papers/neelima_pulagam/paper.rst
> +.. figure:: llo.png
So this was an issue I couldn't really fix because the images I show are the raw data. Each sequence portrays a single cell at different time steps to show a morphological event.

2021-07-02 18:59 UTC, cbcunc commented
@scoobies check references

2021-07-02 19:00 UTC, scoobies commented
```
Reference check summary (note 'MISSING' DOIs are suggestions that need verification):

OK DOIs

- 10.25080/Majora-4af1f417-000 is OK
- 10.1109/TPAMI.2021.3054830 is OK
- 10.25080/Majora-342d178e-00d is OK
- 10.1093/plphys/kiab223 is OK
- 10.1016/j.media.2019.06.014 is OK
- 10.1109/JBHI.2018.2878878 is OK
- 10.1016/j.aiopen.2021.01.001 is OK
- 10.5772/intechopen.73036 is OK
- 10.1038/sj.cdd.4401260 is OK
- 10.3389/fimmu.2019.02461 is OK
- 10.1016/j.mad.2020.111212 is OK
- 10.1371/journal.pone.0213626 is OK
- 10.4084/MJHID.2013.070 is OK
- 10.1038/s41598-019-50010-9 is OK
- 10.1613/jair.953 is OK
- 10.1145/2623330.2623732 is OK
- 10.1109/CVPR.2016.308 is OK
- 10.1109/CVPR.2016.90 is OK
- 10.1109/CVPR.2017.243 is OK
- 10.21105/joss.01983 is OK
- 10.1145/2623330.2623732 is OK

MISSING DOIs

- None

INVALID DOIs

- None
```

2021-07-02 19:03 UTC, cbcunc commented
@scoobies mark ready

2021-07-05 16:11 UTC, merged