Initial submission : PyBMRB: Data visualization tool for BioMagResBank
scipy-conference/scipy_proceedings pull request #641
Opened 2021-05-31 10:07 UTC by kumar-physics

I apologize for the delay. I know I missed the deadline. This method of writing paper in a GitHub is new to me and it took time to understand the workflow.  I request you to accept my paper. 

Thanks,
Kumaran

2021-05-31 10:07 UTC, scoobies commented
Hi!, I'm @scoobies, a friendly bot.

Type ```@scoobies help``` to discover how I can help you.

2021-05-31 21:21 UTC, kumar-physics commented
@scoobies help

I am not sure whether I followed the workflow correctly to submit the paper. May I know whether my paper is considered for review. Once again I apologize for late submission. Thanks

2021-06-01 23:56 UTC, deniederhut commented
@scoobies assign @mepa as editor

2021-06-01 23:56 UTC, scoobies commented
Assigned! @mepa is now the editor

2021-06-03 19:56 UTC, mepa commented
> I am not sure whether I followed the workflow correctly to submit the paper. May I know whether my paper is considered for review. Once again I apologize for late submission. Thanks

Hi @kumar-physics, thanks for your submission. I see the successfully compiled paper on the [build server page](https://procbuild.scipy.org/), so all looks well. Please continue to proofread and make any planned updates as soon as possible since reviewers, once assigned, may have a bit less time for reviewing due to the late submission.

2021-06-04 21:33 UTC, kumar-physics commented
Thanks for your feedback. I have corrected few more typo and committed my first revision

2021-06-07 11:15 UTC, deniederhut commented
@scoobies add @tkoyama010 to reviewers

2021-06-07 11:15 UTC, scoobies commented
@tkoyama010 added to the reviewers list!

2021-06-07 23:44 UTC, deniederhut commented
We've been having difficulty finding reviewers for some papers, so to make sure everyone has enough time to do their reviews, we will be bumping the deadline for the initial review back to June 17th.

2021-06-09 12:35 UTC, tkoyama010 commented
Thanks for your invitation. I will review as soon as possible.

2021-06-09 14:59 UTC, tkoyama010 reviewed
@kumar-physics Awesome paper! I checked the contents and following.
- [x] no typos
- [x] no missing references

Please resolve the comment.

2021-06-09 14:59 UTC, tkoyama010 commented on papers/kumaran_baskaran/00_bibderwalt.rst
> +In response to the demise of DEVise, BMRB developed graphic libraries in Python (PyBMRB)  that utilize more modern interactive visualization tools, such as the Plotly visualization tool kit, to repro
We need to [cite Plotly](https://plotly.com/chart-studio-help/citations/).

2021-06-09 14:59 UTC, tkoyama010 commented on papers/kumaran_baskaran/00_bibderwalt.rst
> +   The Biological Magnetic Resonance Data Bank (BioMagResBank or BMRB https://bmrb.io), founded in 1988, is the international, open archive for data generated by Nuclear Magnetic Resonance (NMR) spec
Can we cite Jupyterlab which is the newer version of Jupyter Notebook? (I could not find the citation of it)

2021-06-10 01:11 UTC, tkoyama010 approved these changes

2021-06-10 01:12 UTC, tkoyama010 commented
@kumar-physics  Thanks for changes. LGTM.

2021-06-11 12:58 UTC, deniederhut commented
@scoobies mark needs more review

2021-06-29 14:28 UTC, deniederhut commented
@scoobies check references

2021-06-29 14:29 UTC, scoobies commented
Checking the BibTeX entries failed with the following error: 
```
Couldn't find bibliography entry
```

2021-06-29 14:30 UTC, deniederhut requested changes

2021-06-29 14:30 UTC, deniederhut commented on publisher/build_paper.py
> +    out_file = os.path.join(out_path,'draft.sty')
Please do not modify files outside of your paper directory

2021-06-29 17:55 UTC, kumar-physics commented on publisher/build_paper.py
> +    out_file = os.path.join(out_path,'draft.sty')
Sorry. It wasn't working on my system, so I tweaked a bit.

2021-06-29 17:56 UTC, kumar-physics commented on publisher/build_paper.py
> +    out_file = os.path.join(out_path,'draft.sty')
Should I do anything to fix this.. or its already fixed?

2021-06-30 13:38 UTC, deniederhut commented on publisher/build_paper.py
> +    out_file = os.path.join(out_path,'draft.sty')
I'd like you to undo this change. If authors modify the build system it causes giant merge conflicts when we try to publish.

2021-06-30 13:55 UTC, kumar-physics commented
Done.  build_paper.py restored to its original

2021-06-30 13:55 UTC, kumar-physics commented on publisher/build_paper.py
> +    out_file = os.path.join(out_path,'draft.sty')
Done. build_paper.py restored.

2021-07-01 00:09 UTC, deniederhut commented on publisher/build_paper.py
> +    out_file = os.path.join(out_path,'draft.sty')
Thanks!

2021-07-01 00:09 UTC, deniederhut approved these changes

2021-07-02 19:07 UTC, mepa commented
@scoobies mark ready

2021-07-02 21:52 UTC, mepa commented on papers/kumaran_baskaran/mybib.bib
> +        abstract = {It is increasingly necessary for researchers in all fields to write computer code, and in order to reproduce research results, it is important that this code is published. We pres
Please add
```
doi = {10.3233/978-1-61499-649-1-87}
```

2021-07-03 11:11 UTC, kumar-physics commented on papers/kumaran_baskaran/mybib.bib
> +        abstract = {It is increasingly necessary for researchers in all fields to write computer code, and in order to reproduce research results, it is important that this code is published. We pres
added

2021-07-05 16:13 UTC, merged