How PDFrw and fillable forms improves throughput at a Covid-19 Vaccine Clinic
scipy-conference/scipy_proceedings pull request #643
Opened 2021-06-08 21:36 UTC by summerswallow-whi

My apologies on the tardiness on this submission. Though not an excuse, I never received any reminder emails after the acceptance email so it fell off the radar. I only happened on this site last Friday and immediately worked to get this draft ready. I hope it is not too late to go through the publication process, but if it is too late I understand.

2021-06-08 21:36 UTC, scoobies commented
Hi!, I'm @scoobies, a friendly bot.

Type ```@scoobies help``` to discover how I can help you.

2021-06-11 19:10 UTC, cbcunc commented
@scoobies assign @cbcunc as editor

2021-06-11 19:10 UTC, scoobies commented
Assigned! @cbcunc is now the editor

2021-06-11 19:11 UTC, cbcunc commented
@scoobies add assignee: @cbcunc

2021-06-11 19:11 UTC, scoobies commented
@cbcunc added as assignee.

2021-06-11 19:12 UTC, cbcunc commented
@scoobies mark paper

2021-06-11 19:12 UTC, cbcunc commented
@scoobies mark needs review

2021-06-11 19:14 UTC, cbcunc commented
@scoobies add @cbcunc to reviewers

2021-06-11 19:14 UTC, scoobies commented
I can't find the reviewers list

2021-06-11 19:49 UTC, cbcunc commented
@scoobies assign @cbcunc as reviewer 1

2021-06-11 19:51 UTC, cbcunc commented
@scoobies add @cbcunc to reviewers

2021-06-11 19:51 UTC, scoobies commented
I can't find the reviewers list

2021-06-11 19:52 UTC, cbcunc commented
@scoobies help

2021-06-11 19:52 UTC, scoobies commented
Hello @cbcunc, here are the things you can ask me to do:

```

# List all available commands
@scoobies help

# Show our community Code of Conduct and Guidelines
@scoobies code of conduct

# Add to this issue's reviewers list
@scoobies add @username to reviewers

# Remove from this issue's reviewers list
@scoobies remove @username from reviewers

# Assign a user as the editor of this submission
@scoobies assign @username as editor

# Remove the editor assigned to this submission
@scoobies remove editor

# Add a user to this issue's assignees list
@scoobies add assignee: @username

# Remove a user from this issue's assignees list
@scoobies remove assignee: @username

# Builds paper
@scoobies build paper

# Checks build status
@scoobies build status

# Check the references of the paper for missing DOIs
# Optionally, it can be run on a non-default branch 
@scoobies check references
@scoobies check references from custom-branch-name

# Label issue with: paper
@scoobies mark paper

# Label issue with: needs-review. Remove labels: unready, needs-more-review, pending-comment, ready
@scoobies mark needs review

# Label issue with: needs-more-review. Remove labels: unready, needs-review, pending-comment, ready
@scoobies mark needs more review

# Label issue with: pending-comment. Remove labels: unready, needs-review, needs-more-review, ready
@scoobies mark pending comment

# Label issue with: ready. Remove labels: unready, needs-review, needs-more-review, pending-comment
@scoobies mark ready

# Label issue with: unready. Remove labels: needs-review, needs-more-review, pending-comment, ready
@scoobies mark not ready

# Label issue with: does_not_build:server
@scoobies mark server fail

# Remove labels: does_not_build:server
@scoobies mark server success

```

2021-06-11 20:03 UTC, cbcunc commented
@scoobies add @cbcunc to reviewers

2021-06-11 20:03 UTC, scoobies commented
@cbcunc added to the reviewers list!

2021-06-11 20:05 UTC, cbcunc commented
Editor’s initial quickie look-over:

- [ ] Make sure the paper builds on procbuild
- [ ] Make sure that the sections are filled in
- [ ] Make sure 8 pages or less exclusive of references

2021-06-11 20:06 UTC, cbcunc commented
@scoobies check references

2021-06-11 20:07 UTC, scoobies commented
```
Reference check summary (note 'MISSING' DOIs are suggestions that need verification):

OK DOIs

- None

MISSING DOIs

- None

INVALID DOIs

- None
```

2021-06-11 20:19 UTC, cbcunc commented on papers/111_lu/paper.rst
> +completely tech ignorant would have had extreme difficulty.
s/tech/technologically/

2021-06-11 20:27 UTC, cbcunc commented on papers/111_lu/paper.rst
> +:cite:`kpbs` and caught the attention of the state who asked WestPACE's sister
State of what? The State of California (should be capitalized)? And the state didn't ask, but I would assume "caught the attention of public health officials with the State of California who asked."

2021-06-11 20:49 UTC, summerswallow-whi commented on papers/111_lu/paper.rst
> +:cite:`kpbs` and caught the attention of the state who asked WestPACE's sister
Good point. I will clarify

2021-06-12 01:20 UTC, deniederhut commented
Hey @summerswallow-whi, sorry for the delayed reply. The committee has decided to accept this late submission, given the extenuating circumstances. We don't expect to be able to find reviewers for this paper at this short notice, so we will be assigning one of the co-chairs to review this paper. Happy SciPy!

2021-06-21 15:06 UTC, summerswallow-whi commented
@cbcunc In case it got lost in the shuffle, I made the changes you requested last week. Is there anything else?

2021-06-22 23:14 UTC, cbcunc requested changes
This completes a first review of a late paper. This paper is extremely problematic. It is too informal. It is riddled with first and second person sentences. There are multiple incomplete sentences. It is based on blog posts. Other than the outdated PDF spec with no DOI, there are no enduring citations. I usually take a couple of hours to review longer papers. This review took over a day for a five page paper. There isn't a single sentence in this paper that doesn't need rewriting. You may try to whip it into shape. But I don't think it looks good for final acceptance with 103 suggested edits. Please note the final review comment on build_paper.py. Papers are not allowed to modify files outside their own directory. You are not allowed to change the publisher machinery used to build the proceedings. If that alone is not addressed, this paper cannot be accepted.

2021-06-22 23:14 UTC, cbcunc commented on papers/111_lu/paper.rst
> +As a personal anecdote, when vaccinations were open to all people 65 and older,
Ordinarily I would find a personal anecdote very odd in a journal paper. However, this is an extraordinary circumstance. But please consider not speaking in the first person. First of all, two authors are listen on the paper, so we don't know who "I" is. Consider revising this paragraph to be more of an observation and less of a diary. Maybe finding a citation which describes this common experience could help to make it less of a personal story.

2021-06-22 23:14 UTC, cbcunc commented on papers/111_lu/paper.rst
> +the deploying a pop-up (POD) :cite:`pod`.
POD does not need to be enclosed in parentheses again after already being described at the beginning of the paragraph.

2021-06-22 23:14 UTC, cbcunc commented on papers/111_lu/paper.rst
> +This paper gives a little more background in the effort. Next the overall
background **of** the effort

2021-06-22 23:14 UTC, cbcunc commented on papers/111_lu/paper.rst
> +the county to provide them. As it turns out the freezer was a great challenge
As it **turned** out... (consistent tense).

2021-06-22 23:14 UTC, cbcunc commented on papers/111_lu/paper.rst
> +because at this time freezers were in high demand because of their need in
at **that** time

2021-06-22 23:14 UTC, cbcunc commented on papers/111_lu/paper.rst
> +because at this time freezers were in high demand because of their need in
...bceause of **the** need **for** storing the vaccine.

2021-06-22 23:14 UTC, cbcunc commented on papers/111_lu/paper.rst
> +from freezers that were available. One that had capacity to far exceed the
One **freezer** ~~that~~ had the capacity...

2021-06-22 23:14 UTC, cbcunc commented on papers/111_lu/paper.rst
> +the county to provide them. As it turns out the freezer was a great challenge
What county?

2021-06-22 23:14 UTC, cbcunc commented on papers/111_lu/paper.rst
> +with the local 2-1-1 organization (a non-profit that is a resource and
(a non-profit ~~that is a~~ resource and  information hub ~~that~~ connect~~s~~**ing** people with community, health and disaster services~~.~~).

Remove the period inside the parentheses.

2021-06-22 23:14 UTC, cbcunc commented on papers/111_lu/paper.rst
> +completely tech ignorant would have had extreme difficulty.
s/tech/technologically/

2021-06-22 23:14 UTC, cbcunc commented on papers/111_lu/paper.rst
> +:cite:`kpbs` and caught the attention of the state who asked WestPACE's sister
State of what? The State of California (should be capitalized)? And the state didn't ask, but I would assume "caught the attention of public health officials with the State of California who asked."

2021-06-22 23:14 UTC, cbcunc commented on papers/111_lu/paper.rst
> +To meet the needs of seniors, the West family of non-profits partnered
Consider saying "elderly" instead of "seniors." Not all senior citizens are elderly. And refer to them as "senior citizens" instead of "seniors" which is overly informal. In fact, the tone of the entire paper is a bit too informal.

2021-06-22 23:14 UTC, cbcunc commented on papers/111_lu/paper.rst
> +the non-tech savvy senior and partnered with ride sharing services to provide
the ~~non-tech savvy senior~~ technologically inexperienced elderly population

2021-06-22 23:14 UTC, cbcunc commented on papers/111_lu/paper.rst
> +transportation to and rom the vaccination site.
..to and **from**....

2021-06-22 23:14 UTC, cbcunc commented on papers/111_lu/paper.rst
> +Though this is a  technical paper this background describes the real impact
**Alt**~~T~~hough this is a  technical paper**,** this background describes

(Comma after clause)

2021-06-22 23:14 UTC, cbcunc commented on papers/111_lu/paper.rst
> +With the goal of providing a senior friendly vaccine experience, Gary and Mary
senior-friendly

(hyphen indicates compound adjective)

2021-06-22 23:14 UTC, cbcunc commented on papers/111_lu/paper.rst
> +West PACE which stood up a small senior oriented covid vaccine clinic desires
West PACE**,** which stood up a small senior oriented covid vaccine clinic**,** desire~~s~~d

(Commas around clause and consistent tense)

2021-06-22 23:14 UTC, cbcunc commented on papers/111_lu/paper.rst
> +vaccine experience. Furthermore as a non-profit and volunteer effort,
> Furthermore  as  a  non-profit  andvolunteer  effort,  consideration  as  to  cost  and  manpower.

This "sentence" has no verb.

2021-06-22 23:14 UTC, cbcunc commented on papers/111_lu/paper.rst
> +compliant computer infrastructure were not well established. Even the large medical practices had
Even ~~the~~ large medical practices had difficulty maintaining a senior**-** friendly environment during the early days of the  vaccine roll out ~~where~~ **when** demand far exceeded capacity.

(Not sure this assertion as fact doesn't require a citation.)

2021-06-22 23:14 UTC, cbcunc commented on papers/111_lu/paper.rst
> +to mitigate the amount of paperwork a frail senior is subjected to. Quite a lot
the amount of paperwork **to which** a frail senior is subjected~~ to~~.

2021-06-22 23:14 UTC, cbcunc commented on papers/111_lu/paper.rst
> +of data is repeatedly asked for to make appointments, on consent forms and in
data ~~is repeatedly asked for~~ **is requested repeatedly** to make appointments, on consent forms**,** and in reminder cards.

(Eliminate combination split infinitive / dangling participle / preposition stranding. Add Oxford comma.)

2021-06-22 23:14 UTC, cbcunc commented on papers/111_lu/paper.rst
> +to mitigate the amount of paperwork a frail senior is subjected to. Quite a lot
Consider quantifying "quite a lot." As the form interpreter, perhaps you have a count of repeated form fields.

2021-06-22 23:14 UTC, cbcunc commented on papers/111_lu/paper.rst
> +Privacy and compliance is an important aspect of setting up a vaccine clinic
Privacy and compliance ~~is~~**are** ~~an~~ important aspect**s**

2021-06-22 23:14 UTC, cbcunc commented on papers/111_lu/paper.rst
> +and information infrastructure for it. The key aspect ensuring privacy that
The key aspect ensuring ~~privacy that conforms~~ compliance ~~to~~ with HIPPA privacy requirements

2021-06-22 23:14 UTC, cbcunc commented on papers/111_lu/paper.rst
> +Information (PHI). For electronic systems, that means all data containing PHI
For electronic systems~~,~~ that

(No comma)

2021-06-22 23:14 UTC, cbcunc commented on papers/111_lu/paper.rst
> +should be encrypted when at rest and encrypted when in transit. For paper
should be encrypted **both** ~~when~~ at rest and ~~encrypted when~~ in transit.

2021-06-22 23:14 UTC, cbcunc commented on papers/111_lu/paper.rst
> +must be not be left in the open and when unattended be in a locked room or
when unattended **must** be in a locked room

2021-06-22 23:14 UTC, cbcunc commented on papers/111_lu/paper.rst
> +infrastructure the appropriate Business Associate Agreements must be in place.
the appropriate Business Associate Agreements (BAA) must be in place.

(BAAs are referenced by acronym later in the paper.)

Consider a reference defining Business Associate Agreements.

2021-06-22 23:14 UTC, cbcunc commented on papers/111_lu/paper.rst
> +Figure :ref:`fig:infrastructure` shows at high level the user experience and
shows  a~~t~~  high  level  **view of** the user experience

2021-06-22 23:14 UTC, cbcunc commented on papers/111_lu/paper.rst
> +information flow. One of the great diffulties for seniors especially those with
One ~~of the great diffulties~~ **difficulty** for ~~seniors~~ **the elderly,** especially those with
few people around them to help**,** is the challenge of making **vaccine** appointments.

(Add commas around subordinate clause)

2021-06-22 23:14 UTC, cbcunc commented on papers/111_lu/paper.rst
> +the systems were set up in a hurry, many are not well designed and confusing.
Because the **appointment** systems were set up in a hurry

2021-06-22 23:14 UTC, cbcunc commented on papers/111_lu/paper.rst
> +In our pipeline, the senior or senior's caregiver would telephone the 2-1-1
the ~~senior or senior's caregiver~~ **person seeking a vaccine or a caregiver**

2021-06-22 23:14 UTC, cbcunc commented on papers/111_lu/paper.rst
> +the State. However, from the time the data is ingested from the State's
state

(not capitalized here)

2021-06-22 23:14 UTC, cbcunc commented on papers/111_lu/paper.rst
> +entered into appointment system managed by the California Department of Public Health.
entered into **the** appointment system

2021-06-22 23:14 UTC, cbcunc commented on papers/111_lu/paper.rst
> +The information is downloaded the  appointment system prior to the next day's clinic and processed
The information is downloaded **from** the appointment system

2021-06-22 23:14 UTC, cbcunc commented on papers/111_lu/paper.rst
> +A forms packet is generated for each senior and consolidated into a few PDF
generated for each ~~senior~~ **patient**

2021-06-22 23:14 UTC, cbcunc commented on papers/111_lu/paper.rst
> +A forms packet is generated for each senior and consolidated into a few PDF
A forms packet is generated for each patient**,** ~~and~~ consolidated into a few PDF files**,** and delivered to volunteers at the clinic who print the forms.

(Fix run-on sentence)

2021-06-22 23:14 UTC, cbcunc commented on papers/111_lu/paper.rst
> +files and delivered to volunteers at the clinic who print the forms. These form
These form packets include a consent form, county health forms**,** and CDC provided vaccine cards.

(Oxford comma)

2021-06-22 23:14 UTC, cbcunc commented on papers/111_lu/paper.rst
> +When the senior arrives at the clinic, their forms are pulled, a volunteer
When the ~~senior~~ **patient** arrives at the clinic, their forms are pulled, a volunteer reviews the question with the ~~senior~~ **patient,** and corrects any errors.

(Oxford comma)

2021-06-22 23:14 UTC, cbcunc commented on papers/111_lu/paper.rst
> +reviews the question with the senior and corrects any errors. Once the
Once the information is validated**,** the ~~senior~~ **patient**  is directed as to which forms to sign. 

(Comma)

2021-06-22 23:14 UTC, cbcunc commented on papers/111_lu/paper.rst
> +information is validated the senior is directed as to which forms to sign. As a
As a result**,** neither the ~~senior~~ **patient** nor the volunteer needs to fill the information.

(Comma)

2021-06-22 23:14 UTC, cbcunc commented on papers/111_lu/paper.rst
> +was crucial for maintain a good throughput of patients during peak times.
was crucial **to** ~~for~~ maintain a good throughput

2021-06-22 23:14 UTC, cbcunc commented on papers/111_lu/paper.rst
> +Generally, most seniors experience less than five minute delay between arrival
Generally, most ~~seniors~~ **patients* experience*d* less than five minute delay between arrival at the clinic and administration of the vaccine.

(Consistent tense; consistent parts of speech)

2021-06-22 23:14 UTC, cbcunc commented on papers/111_lu/paper.rst
> +The reader may wonder why a pure electronic form system wasn't used. Many
~~The reader may wonder why a pure electronic form system wasn't used.~~ **While m**~~M~~any
commercial services do provide electronic form filling with electronic
signature**,**~~. The reason for adopting~~ **our system adopted** paper **for reasons of** ~~is simply the~ cost and ~~to provide~~ a trail for downstream audits

2021-06-22 23:14 UTC, cbcunc commented on papers/111_lu/paper.rst
> +and in transit as required by HIPAA in handling Protected Health
and in transit as required by HIPAA in handling ~~Protected Health Information~~ **PHI**.

(Acronym already established and used earlier in the paper.)

2021-06-22 23:14 UTC, cbcunc commented on papers/111_lu/paper.rst
> +Information. The processing center is cloud based but we were able to
The processing center is cloud**-**based,**,** but ~~we were able leverage our~~ existing BAA**s** with the cloud services **were leveraged*. in order to meet HIPAA requirements.

(compound word with hyphen; needs comma; and avoid first person.)

2021-06-22 23:14 UTC, cbcunc commented on papers/111_lu/paper.rst
> +Setting up most of the systems in the pipeline faced challenges. Surprisingly,
Four sentences in a row tell me there are challenges. Make it one.

2021-06-22 23:14 UTC, cbcunc commented on papers/111_lu/paper.rst
> +is a simple one, implementation is full of challenges as many common
**the** implementation

2021-06-22 23:14 UTC, cbcunc commented on papers/111_lu/paper.rst
> +programmatic PDF tools do not properly work with filled forms. To meet
~~To meet the challenges,~~ **The** PDF forms have repeated fields ~~with~~ **using the** same ~~name~~ **text**,
checkboxes**,** and radio buttons ~~are used~~.

(Comma)

2021-06-22 23:14 UTC, cbcunc commented on papers/111_lu/paper.rst
> +however, the *Medium* blog post by Vivsvaan Sharma :cite:`sharma` is a good
No single source provides a complete answer~~,~~**.** ~~h~~**H**owever, ~~the~~ **a** *Medium* blog post

Compound sentence; split in two.

2021-06-22 23:14 UTC, cbcunc commented on papers/111_lu/paper.rst
> +starting place. The blog post is long on python practices and a bit short on
~~The blog post is long on python practices and a bit short on PDF details.~~

This sentence is an unnecessary value judgment that will be evident to anyone reading the post. Eliminate it. And Python, when not referring to the executable name, is capitalized.

2021-06-22 23:14 UTC, cbcunc commented on papers/111_lu/paper.rst
> +PDF details. Another useful resource is the PDF 1.7 specification :cite:`pdf`
Another useful resource is the PDF 1.7 specification [pdf08]**.** ~~but it  is  well  over  750  pages!~~

(Comma before interjection, but eliminate it because a) most specifications are long, and b) avoid exclamations.)

2021-06-22 23:14 UTC, cbcunc commented on papers/111_lu/paper.rst
> +but it is well over 750 pages! Since the deployment of the vaccine clinic, the
Since the deployment of the vaccine clinic, the
details of the form filling be  found at our blog :cite:`whblog`~~,~~**.** ~~the
nitty-gritty details can be found there.~~

(dangling clause)

Ordinarily, the details of what is described in a paper should be in the paper, not not deferred to an ephemeral blog post. This may affect the acceptance of this paper.

2021-06-22 23:14 UTC, cbcunc commented on papers/111_lu/paper.rst
> +nitty-gritty details can be found there. The code is in the process of being
The code is in the process of being made open source and can be found...

The code must be open source for these proceedings. The license file at the Github link indicates that it is already open source, and so this should be made explicit.

2021-06-22 23:14 UTC, cbcunc commented on papers/111_lu/paper.rst
> +use the ``from`` directive in order to shorten the code lines so they can
use the ``from`` ~~directive~~ **keyword**

Python has keywords, not directives. While fully qualified namespaces are used in your code as posted on Github, It is not necessary to explain here. Just eliminate this sentence. You've already mentioned that they are used in the examples of the paper.

2021-06-22 23:14 UTC, cbcunc commented on papers/111_lu/paper.rst
> +post, you will find a snippet of code which might look like the
It either does or doesn't look like the code in the blog. Which is it? Similar?

2021-06-22 23:14 UTC, cbcunc commented on papers/111_lu/paper.rst
> +The type of ``annotation['/T']`` is ``pdfString`` while some sources use
~~w~~**W**hile some sources

(Start new sentence.)

2021-06-22 23:14 UTC, cbcunc commented on papers/111_lu/paper.rst
> +[1:-1] to extract the string from ``pdfString`` the ``.to_unicode()``
the string from ``pdfString``**,** the ``.to_unicode()`` method

(Comma needed)

2021-06-22 23:14 UTC, cbcunc commented on papers/111_lu/paper.rst
> +specification § 12.5.6.19 all fillable forms use widget annotation,
According to the PDF 1.7 specification § 12.5.6.19**,** all fillable forms

(Comma needed)

2021-06-22 23:14 UTC, cbcunc commented on papers/111_lu/paper.rst
> +so the check for the ``annotation['/SubType']`` filters the annotation
~~So t~~ **T**he check for ~~the~~ ``annotation['/SubType']`` filters the annotationto only widget annotations.

(Start a new sentence.)

2021-06-22 23:14 UTC, cbcunc commented on papers/111_lu/paper.rst
> +To set the value, first we need to create a ``PDFString`` with
To set the value, first we need to create a ``PDFString`` with
our value ~~with~~ **using** the ``encode`` method**,** then update the ``annotation`` as
shown in this code snippet.

(Comma needed)

2021-06-22 23:14 UTC, cbcunc commented on papers/111_lu/paper.rst
> +This converts your ``value`` into a ``PdfString`` and updates the
This converts ~~your~~``value`` into a ``PdfString`` and updates the
``annotation``**,** creating a value for. ``annotation['/V'``].

(Needs comma)

2021-06-22 23:14 UTC, cbcunc commented on papers/111_lu/paper.rst
> +As mentioned above, this won't quite do it. At the top level of your
~~As mentioned above, this won't quite do it.~~

I don't see anything above of what won't quite do what. Eliminate this sentence.

2021-06-22 23:14 UTC, cbcunc commented on papers/111_lu/paper.rst
> +``PdfReader`` object ``pdf`` you also need to set the
At the top level of ~~your~~ **the** ``PdfReader`` object ``pdf``**,** ~~you also need to~~ set the ``NeedAppearances`` property in the interactive ~~from~~ form dictionary,
``AcroForm`` (See § 12.7,2).

(Avoid second person, needs comma, fix spelling)

2021-06-22 23:14 UTC, cbcunc commented on papers/111_lu/paper.rst
> +So combining the code snippets provided a simple method for filling
~~So c~~**C**ombining the code snippets provided

2021-06-22 23:14 UTC, cbcunc commented on papers/111_lu/paper.rst
> +So what happened to the ``Name`` field. Turns out whenever the multiple
~~So what happened to the ``Name`` field. Turns out w~~**W**henever ~~the~~ multiple
fields occur with the same name the situation is more complicated.

2021-06-22 23:14 UTC, cbcunc commented on papers/111_lu/paper.rst
> +It should be noted that ``Name`` now appears twice, once for each
~~It should be noted that~~ ``Name`` now appears twice,

2021-06-22 23:14 UTC, cbcunc commented on papers/111_lu/paper.rst
> +twice, but this has no impact since it is overwriting the default value
but this has no impact ~since~~ because it is overwriting the default value
with the same value ~~while keeping the code simple~~.

2021-06-22 23:14 UTC, cbcunc commented on papers/111_lu/paper.rst
> +Finding Your Way Around PDFrw and fillable forms
Finding Your Way Around PDFrw and ~~f~~**F**illable ~~f~~**F**orms

(Consistent title casing.)

2021-06-22 23:14 UTC, cbcunc commented on papers/111_lu/paper.rst
> +In accordance to §12.7.4.2.3 the you can set the checkbox state as
In accordance to §12.7.4.2.3**,** ~~the you can~~ set the checkbox state as
follows:

(Comma needed)

2021-06-22 23:14 UTC, cbcunc commented on papers/111_lu/paper.rst
> +``Yes``, but doesn't need to be. The easiest solution if you designed
The easiest solution ~~if you designed
the form or can use Adobe Acrobat~~ **is** to edit the form ~~is~~ to ensure that the export value of the checkbox is ``Yes`

(Avoid second person)

2021-06-22 23:14 UTC, cbcunc commented on papers/111_lu/paper.rst
> +be set to ``Yes``. However, you may not have the luxury and upon closer
However, you may not have the luxury and upon closer
inspection of a form where the export value is not set to ``Yes.`` You
will see that the ``/V`` and ``/AS`` fields are set to the export value
not ``Yes``.

(Super confusing. Not sure the first sentence parses. Reword for clarity. And avoid second person.)

2021-06-22 23:14 UTC, cbcunc commented on papers/111_lu/paper.rst
> +If you are using the form not only for automatic filling but also for manual
If ~~you are using~~ the form **is used** not only for automatic filling but also for manual
filling**,** ~~you may wish~~ **it is preferable for** the box to be checked as a default.

(Avoid second person.)

2021-06-22 23:14 UTC, cbcunc commented on papers/111_lu/paper.rst
> +filling you may wish the box to be checked as a default. In that case, while
In that case, while
the code does work, ~~we feel the~~ the best solution is to delete the ``/V`` as
well as the ``/AS``\ field from the dictionary.

(Avoid first person.)

2021-06-22 23:14 UTC, cbcunc commented on papers/111_lu/paper.rst
> +well as the ``/AS``\ field from the dictionary. If you do not have Acrobat and
If ~~you do not have Acrobat and~~
can not find the export value, ~~you can~~ discover it by looking at appearance
dictionary ``/AP`` and specifically at the ``/N`` field.

(Avoid second person.)

2021-06-22 23:14 UTC, cbcunc commented on papers/111_lu/paper.rst
> +dictionary ``/AP`` and specifically at the ``/N`` field. Each annotation has up
Each annotation has up
to 3 appearances in ~~it's~~ **its** appearance dictionary**:**``/N``, ``/R`` and ``/D``,
standing for *normal*, *rollover*, and *down* (§12.5.5).

("It's" is a contraction of "it is." "Its" is a possessive. Add colon.)

2021-06-22 23:14 UTC, cbcunc commented on papers/111_lu/paper.rst
> +standing for *normal*, *rollover*, and *down* (§12.5.5). The latter two has to
The latter two ~~has~~ **have** to
do with appearance in interacting with the mouse~~,~~**. T**~~t~~he normal appearance has to
do with how the form is printed.

(Subject/verb agreement; Divide compound sentence in two.)

2021-06-22 23:14 UTC, cbcunc commented on papers/111_lu/paper.rst
> +do with how the form is printed. Details on how to generalize the code to an
Details on how to generalize the code to an
~~abritry~~ **arbitrary** export value ~~can be~~ **are** in our blog :cite:`whblog`.

Again, you are deferring what should be in the paper to an ephemeral blog post. If the detail is not important to the paper, omit it.

2021-06-22 23:14 UTC, cbcunc commented on papers/111_lu/paper.rst
> +are sufficient. However, in the interest of not leaving a partial
However, in the interest of not leaving a partial
solution. We'll take this topic further and address filling in all other
form fields.

(The first sentence is incomplete. Avoid first person. Reword.)

2021-06-22 23:14 UTC, cbcunc commented on papers/111_lu/paper.rst
> +same name, you need only update each once, but it can't hurt to apply
~~you need~~ only update each once

(Avoid second person)

2021-06-22 23:14 UTC, cbcunc commented on papers/111_lu/paper.rst
> +the same update multiple times if it simplifies your code.
simplifies ~~your~~ **the** code.

(Avoid second person)

2021-06-22 23:14 UTC, cbcunc commented on papers/111_lu/paper.rst
> +corresponding export value, we need to look again to the ``/N`` field of
In order to identify the kid with its
corresponding export value, ~~we need to~~ look again

(Avoid first person)

2021-06-22 23:14 UTC, cbcunc commented on papers/111_lu/paper.rst
> +We code it as separate helpers, but of course, you could combine the
We code it as separate helpers, but of course, you could combine the
code into one function.

(Reword without first or second person.)

2021-06-22 23:14 UTC, cbcunc commented on papers/111_lu/paper.rst
> +To set the combo box, you simply need to set the value to the export
To set the combo box, ~~you~~ simply ~~need to~~ set the value to the export
value.

(Avoid second person.)

2021-06-22 23:14 UTC, cbcunc commented on papers/111_lu/paper.rst
> +Putting it all together
Be consistent in title casing. Either all caps in all titles, of just first word caps. But be consistent.

2021-06-22 23:14 UTC, cbcunc commented on papers/111_lu/paper.rst
> +Now that we have shown how to fill in all the specific types of form
Here are two incomplete sentences, one with first person. Reword if this was even trying to say anything.

2021-06-22 23:14 UTC, cbcunc commented on papers/111_lu/paper.rst
> +which probably should not be filled programatically). Let's put this all
~~Let's put this all together.~~

(Let's not use first person. Just eliminate the sentence as it serves no purpose.)

2021-06-22 23:14 UTC, cbcunc commented on papers/111_lu/paper.rst
> +together. If you have access to the forms themselves, you will know what
~~If you have access to~~ **Examining** the forms themselves~~, you will know~~ **will show** what
type of form field each corresponds to each label.

(Avoid second person.)

2021-06-22 23:14 UTC, cbcunc commented on papers/111_lu/paper.rst
> +'''''''''''''''''''''''''''''''''''''''''''''
The style sheet renders the ticks as an inline title followed by a colon. It looks strange on the page. How about just starting a new title second by underlining with tildes?

2021-06-22 23:14 UTC, cbcunc commented on papers/111_lu/paper.rst
> +our annotation, ``/Btn``, ``/Tx``, ``/Ch`` and ``/Sig``, respectively.
our annotation~~,~~**:** ``/Btn``, ``/Tx``, ``/Ch`` and ``/Sig``, respectively.

(Replace comma with colon.)

2021-06-22 23:14 UTC, cbcunc commented on papers/111_lu/paper.rst
> +We will omit the signature type as we do not support filling in
~~We will o~~**O**mit the signature type as ~~we do not support~~ filling in
signature**s is unsupported.

(Avoid first person.)

2021-06-22 23:14 UTC, cbcunc commented on papers/111_lu/paper.rst
> +To distinguish the types of buttons and choices, we can examine the form
To distinguish the types of buttons and choices, ~~we can~~ examine the form
flags ``/Ff`` field.

(Avoid first person.)

2021-06-22 23:14 UTC, cbcunc commented on papers/111_lu/paper.rst
> +For completeness, we should present a text\_form filler helper.
For completeness, ~~we should present~~ **use** a text\_form filler helper.

(Avoid first person.)

2021-06-22 23:14 UTC, cbcunc commented on papers/111_lu/paper.rst
> +So now we have all the building blocks to put an automatic form filler
Reword this without first person.

2021-06-22 23:14 UTC, cbcunc commented on papers/111_lu/paper.rst
> +associated with each other. For instance, if I had John Doe entered in
Reword this without first person.

2021-06-22 23:14 UTC, cbcunc commented on papers/111_lu/paper.rst
> +One solution is to "flatten" the each PDF file. This is equivalent to
One solution is to "flatten" ~~the~~ each PDF file.

2021-06-22 23:14 UTC, cbcunc commented on papers/111_lu/paper.rst
> +In our use case of the vaccine clinic, we have the same form being
In ~~our~~ **the** use case of the vaccine clinic, ~~we have~~ the same form ~~being~~ **is**
filled out for multiple patients.


(Avoid first person)

2021-06-22 23:14 UTC, cbcunc commented on papers/111_lu/paper.rst
> +filled out for multiple patients. So to combine a batch of these
~~So t~~**T**o combine a batch of these
requires all form field names to be different.

2021-06-22 23:14 UTC, cbcunc commented on papers/111_lu/paper.rst
> +requires all form field names to be different. The solution is quite
The solution is quite
simple~~,~~**. I**~~i~~n the process of filling out the form using the code above, ~~we
can also~~ rename (set) the value of ``/T``.

(Split compound sentence; avoid first person)

2021-06-22 23:14 UTC, cbcunc commented on papers/111_lu/paper.rst
> +So all you have to do is supply a unique suffix to each form. In our
~~So all you have to do~~ **All that is needed** is **to** supply a unique suffix to each form. In ~~our
case, ~~we~~ simply number the batch so the suffix is just a sequential
number.

(Avoid first and second persons. As you can see, the person is not even consistent. It reads like multiple personalities.)

2021-06-22 23:14 UTC, cbcunc commented on papers/111_lu/paper.rst
> +Combining the files
Consistent title casing, please.

2021-06-22 23:14 UTC, cbcunc commented on papers/111_lu/paper.rst
> +While you don't lose the form data per se, you lose rendering
While ~you don't lose the~~ form data **isn't lost** per se, ~~you lose~~ rendering information **is lost** and hence the combined PDF fails to show the fields.


(Avoid second person)

2021-06-22 23:14 UTC, cbcunc commented on papers/111_lu/paper.rst
> +If one examines, these source code, the second parameter is set to the
If one examines, these source code, the second parameter is set to the
attribute ``trailer``, so assuming ``acro_form`` contains the
interactive forms ``PdfDict`` ~~you can~~ **it may be** set ~~it~~ by
``writer.trailer.Root.AcroForm = acro_form``.

(Avoid second person.)

2021-06-22 23:14 UTC, cbcunc commented on papers/111_lu/paper.rst
> +A complete functional version of this PDF form filler can be found in our
~~can~~ **may** be found  in ~~our github~~ **the WestHealth Github~~ repository.

(As you've repeatedly pointed out. Is it necessary to keep repeated this?)

2021-06-22 23:14 UTC, cbcunc commented on publisher/build_paper.py
> +    out_file= os.path.join(out_path,'draft.sty')
Your paper is not allow to modify any files in the repository outside of your paper directory. This paper will not be accepted unless this is corrected.

2021-06-22 23:14 UTC, cbcunc commented on papers/111_lu/ourbib.bib
> +@article{press,
Needs date.

2021-06-22 23:16 UTC, cbcunc commented
@scoobies mark needs more review

2021-06-22 23:20 UTC, cbcunc commented
> @cbcunc In case it got lost in the shuffle, I made the changes you requested last week. Is there anything else?

I see you made one out of over twenty changes requested at the time. The review is now complete with 103 changes requested. Please see the review summary here: https://github.com/scipy-conference/scipy_proceedings/pull/643#pullrequestreview-682196817 This paper will need a lot of work before July 1 in order to be accepted.

2021-06-22 23:23 UTC, summerswallow-whi commented
My apologies. I did not see those review summaries. I will work on it right away.

2021-06-22 23:34 UTC, summerswallow-whi commented on publisher/build_paper.py
> +    out_file= os.path.join(out_path,'draft.sty')
Sorry about this. For some reason shutil.copy was not working right. It should not have ended up in the pull request. My bad there.

2021-06-22 23:50 UTC, summerswallow-whi commented on papers/111_lu/paper.rst
> +As a personal anecdote, when vaccinations were open to all people 65 and older,
Rewritten - Note, I'm making these comments as I correct so they won't be reflected until the next commit.

2021-06-22 23:51 UTC, summerswallow-whi commented on papers/111_lu/paper.rst
> +completely tech ignorant would have had extreme difficulty.
Moot. Part of rewritten text.

2021-06-22 23:51 UTC, summerswallow-whi commented on papers/111_lu/paper.rst
> +the deploying a pop-up (POD) :cite:`pod`.
Done

2021-06-22 23:51 UTC, summerswallow-whi commented on papers/111_lu/paper.rst
> +This paper gives a little more background in the effort. Next the overall
Done

2021-06-22 23:52 UTC, summerswallow-whi commented on papers/111_lu/paper.rst
> +because at this time freezers were in high demand because of their need in
Done

2021-06-22 23:52 UTC, summerswallow-whi commented on papers/111_lu/paper.rst
> +because at this time freezers were in high demand because of their need in
Done

2021-06-22 23:54 UTC, summerswallow-whi commented on papers/111_lu/paper.rst
> +from freezers that were available. One that had capacity to far exceed the
Sentence rewritten

2021-06-22 23:59 UTC, summerswallow-whi commented on papers/111_lu/paper.rst
> +To meet the needs of seniors, the West family of non-profits partnered
I'll change to senior citizens if you insist, but in our sector they are referred to as seniors. See westhealth.org westpace.org.

2021-06-23 00:00 UTC, summerswallow-whi commented on papers/111_lu/paper.rst
> +with the local 2-1-1 organization (a non-profit that is a resource and
Done

2021-06-23 00:08 UTC, summerswallow-whi commented on papers/111_lu/paper.rst
> +transportation to and rom the vaccination site.
fixed

2021-06-23 00:09 UTC, summerswallow-whi commented on papers/111_lu/paper.rst
> +To meet the needs of seniors, the West family of non-profits partnered
I'll try varying it throughout the text on a pass after I get your initial changes in.

2021-06-23 00:13 UTC, summerswallow-whi commented on papers/111_lu/paper.rst
> +Though this is a  technical paper this background describes the real impact
Done

2021-06-23 00:14 UTC, summerswallow-whi commented on papers/111_lu/paper.rst
> +vaccine experience. Furthermore as a non-profit and volunteer effort,
Fixed

2021-06-23 00:16 UTC, summerswallow-whi commented on papers/111_lu/paper.rst
> +compliant computer infrastructure were not well established. Even the large medical practices had
TODO: See if I can find a supporting citation

2021-06-23 00:16 UTC, summerswallow-whi commented on papers/111_lu/paper.rst
> +With the goal of providing a senior friendly vaccine experience, Gary and Mary
Done

2021-06-23 00:18 UTC, summerswallow-whi commented on papers/111_lu/paper.rst
> +West PACE which stood up a small senior oriented covid vaccine clinic desires
done

2021-06-23 00:18 UTC, summerswallow-whi commented on papers/111_lu/paper.rst
> +to mitigate the amount of paperwork a frail senior is subjected to. Quite a lot
done

2021-06-23 00:20 UTC, summerswallow-whi commented on papers/111_lu/paper.rst
> +to mitigate the amount of paperwork a frail senior is subjected to. Quite a lot
Elaborated upon

2021-06-23 00:22 UTC, summerswallow-whi commented on papers/111_lu/paper.rst
> +of data is repeatedly asked for to make appointments, on consent forms and in
rewritten

2021-06-23 00:22 UTC, summerswallow-whi commented on papers/111_lu/paper.rst
> +Privacy and compliance is an important aspect of setting up a vaccine clinic
done

2021-06-23 00:24 UTC, summerswallow-whi commented on papers/111_lu/paper.rst
> +and information infrastructure for it. The key aspect ensuring privacy that
done

2021-06-23 00:25 UTC, summerswallow-whi commented on papers/111_lu/paper.rst
> +Information (PHI). For electronic systems, that means all data containing PHI
i did. Made the change, but not sure if the comma should be removed.

2021-06-23 00:25 UTC, summerswallow-whi commented on papers/111_lu/paper.rst
> +must be not be left in the open and when unattended be in a locked room or
done

2021-06-23 00:26 UTC, summerswallow-whi commented on papers/111_lu/paper.rst
> +infrastructure the appropriate Business Associate Agreements must be in place.
TODO: Find reference to BAA

2021-06-23 00:26 UTC, summerswallow-whi commented on papers/111_lu/paper.rst
> +Figure :ref:`fig:infrastructure` shows at high level the user experience and
done

2021-06-23 00:28 UTC, summerswallow-whi commented on papers/111_lu/paper.rst
> +information flow. One of the great diffulties for seniors especially those with
done

2021-06-23 00:30 UTC, summerswallow-whi commented on papers/111_lu/paper.rst
> +the systems were set up in a hurry, many are not well designed and confusing.
done

2021-06-23 00:30 UTC, summerswallow-whi commented on papers/111_lu/paper.rst
> +In our pipeline, the senior or senior's caregiver would telephone the 2-1-1
done

2021-06-23 00:30 UTC, summerswallow-whi commented on papers/111_lu/paper.rst
> +entered into appointment system managed by the California Department of Public Health.
done

2021-06-23 00:30 UTC, summerswallow-whi commented on papers/111_lu/paper.rst
> +The information is downloaded the  appointment system prior to the next day's clinic and processed
done

2021-06-23 00:32 UTC, summerswallow-whi commented on papers/111_lu/paper.rst
> +A forms packet is generated for each senior and consolidated into a few PDF
rewritten

2021-06-23 00:33 UTC, summerswallow-whi commented on papers/111_lu/paper.rst
> +files and delivered to volunteers at the clinic who print the forms. These form
done

2021-06-23 00:35 UTC, summerswallow-whi commented on papers/111_lu/paper.rst
> +information is validated the senior is directed as to which forms to sign. As a
done

2021-06-23 00:35 UTC, summerswallow-whi commented on papers/111_lu/paper.rst
> +was crucial for maintain a good throughput of patients during peak times.
done

2021-06-23 00:36 UTC, summerswallow-whi commented on papers/111_lu/paper.rst
> +Generally, most seniors experience less than five minute delay between arrival
reworded

2021-06-23 00:38 UTC, summerswallow-whi commented on papers/111_lu/paper.rst
> +The reader may wonder why a pure electronic form system wasn't used. Many
reworded

2021-06-23 00:39 UTC, summerswallow-whi commented on papers/111_lu/paper.rst
> +the State. However, from the time the data is ingested from the State's
done

2021-06-23 00:40 UTC, summerswallow-whi commented on papers/111_lu/paper.rst
> +and in transit as required by HIPAA in handling Protected Health
done

2021-06-23 00:41 UTC, summerswallow-whi commented on papers/111_lu/paper.rst
> +Information. The processing center is cloud based but we were able to
done

2021-06-23 00:45 UTC, cbcunc commented on papers/111_lu/paper.rst
> +As a personal anecdote, when vaccinations were open to all people 65 and older,
Thanks. I was wondering. I kept getting emails saying "Done" and I couldn't find the commits.

2021-06-23 00:49 UTC, summerswallow-whi commented on papers/111_lu/paper.rst
> +Setting up most of the systems in the pipeline faced challenges. Surprisingly,
Assuming you are starting with this sentence and the next paragraph. Condensing

2021-06-23 00:49 UTC, summerswallow-whi commented on papers/111_lu/paper.rst
> +is a simple one, implementation is full of challenges as many common
moot. removed with edit

2021-06-23 00:50 UTC, summerswallow-whi commented on papers/111_lu/paper.rst
> +programmatic PDF tools do not properly work with filled forms. To meet
Paragraph removed. Incorporated elsewhere

2021-06-23 00:50 UTC, summerswallow-whi commented on papers/111_lu/paper.rst
> +however, the *Medium* blog post by Vivsvaan Sharma :cite:`sharma` is a good
done

2021-06-23 00:51 UTC, summerswallow-whi commented on papers/111_lu/paper.rst
> +starting place. The blog post is long on python practices and a bit short on
done

2021-06-23 00:52 UTC, summerswallow-whi commented on papers/111_lu/paper.rst
> +PDF details. Another useful resource is the PDF 1.7 specification :cite:`pdf`
ok

2021-06-23 00:53 UTC, summerswallow-whi commented on papers/111_lu/paper.rst
> +nitty-gritty details can be found there. The code is in the process of being
It is now open. Was not at the time of the writing.

2021-06-23 00:58 UTC, summerswallow-whi commented on papers/111_lu/paper.rst
> +use the ``from`` directive in order to shorten the code lines so they can
deleted

2021-06-23 00:58 UTC, summerswallow-whi commented on papers/111_lu/paper.rst
> +Finding Your Way Around PDFrw and fillable forms
my oversight

2021-06-23 01:00 UTC, summerswallow-whi commented on papers/111_lu/paper.rst
> +post, you will find a snippet of code which might look like the
Rewritten for clarity

2021-06-23 01:03 UTC, summerswallow-whi commented on papers/111_lu/paper.rst
> +[1:-1] to extract the string from ``pdfString`` the ``.to_unicode()``
done

2021-06-23 01:06 UTC, summerswallow-whi commented on papers/111_lu/paper.rst
> +specification § 12.5.6.19 all fillable forms use widget annotation,
done

2021-06-23 01:07 UTC, summerswallow-whi commented on papers/111_lu/paper.rst
> +so the check for the ``annotation['/SubType']`` filters the annotation
done

2021-06-23 01:07 UTC, summerswallow-whi commented on papers/111_lu/paper.rst
> +To set the value, first we need to create a ``PDFString`` with
moot. rewrote to eliminate first person.

2021-06-23 01:09 UTC, summerswallow-whi commented on papers/111_lu/paper.rst
> +To set the value, first we need to create a ``PDFString`` with
done

2021-06-23 01:09 UTC, summerswallow-whi commented on papers/111_lu/paper.rst
> +This converts your ``value`` into a ``PdfString`` and updates the
done

2021-06-23 01:11 UTC, summerswallow-whi commented on papers/111_lu/paper.rst
> +``PdfReader`` object ``pdf`` you also need to set the
rewrote a little.

2021-06-23 01:13 UTC, summerswallow-whi commented on papers/111_lu/paper.rst
> +So combining the code snippets provided a simple method for filling
done

2021-06-23 01:13 UTC, summerswallow-whi commented on papers/111_lu/paper.rst
> +So what happened to the ``Name`` field. Turns out whenever the multiple
done

2021-06-23 01:14 UTC, summerswallow-whi commented on papers/111_lu/paper.rst
> +It should be noted that ``Name`` now appears twice, once for each
done

2021-06-23 01:14 UTC, summerswallow-whi commented on papers/111_lu/paper.rst
> +twice, but this has no impact since it is overwriting the default value
done

2021-06-23 01:15 UTC, summerswallow-whi commented on papers/111_lu/paper.rst
> +In accordance to §12.7.4.2.3 the you can set the checkbox state as
done

2021-06-23 01:16 UTC, summerswallow-whi commented on papers/111_lu/paper.rst
> +``Yes``, but doesn't need to be. The easiest solution if you designed
done

2021-06-23 01:19 UTC, summerswallow-whi commented on papers/111_lu/paper.rst
> +be set to ``Yes``. However, you may not have the luxury and upon closer
completely rewrote for clarity

2021-06-23 01:23 UTC, summerswallow-whi commented on papers/111_lu/paper.rst
> +If you are using the form not only for automatic filling but also for manual
rewritten

2021-06-23 01:23 UTC, summerswallow-whi commented on papers/111_lu/paper.rst
> +filling you may wish the box to be checked as a default. In that case, while
done

2021-06-23 01:25 UTC, summerswallow-whi commented on papers/111_lu/paper.rst
> +well as the ``/AS``\ field from the dictionary. If you do not have Acrobat and
rewrote it

2021-06-23 01:26 UTC, summerswallow-whi commented on papers/111_lu/paper.rst
> +dictionary ``/AP`` and specifically at the ``/N`` field. Each annotation has up
done

2021-06-23 01:27 UTC, summerswallow-whi commented on papers/111_lu/paper.rst
> +standing for *normal*, *rollover*, and *down* (§12.5.5). The latter two has to
done

2021-06-23 01:27 UTC, summerswallow-whi commented on papers/111_lu/paper.rst
> +do with how the form is printed. Details on how to generalize the code to an
Not important. Omitted

2021-06-23 01:30 UTC, summerswallow-whi commented on papers/111_lu/paper.rst
> +are sufficient. However, in the interest of not leaving a partial
rewritten

2021-06-23 01:31 UTC, summerswallow-whi commented on papers/111_lu/paper.rst
> +same name, you need only update each once, but it can't hurt to apply
done

2021-06-23 01:35 UTC, summerswallow-whi commented on papers/111_lu/paper.rst
> +corresponding export value, we need to look again to the ``/N`` field of
rewritten

2021-06-23 01:36 UTC, summerswallow-whi commented on papers/111_lu/paper.rst
> +To set the combo box, you simply need to set the value to the export
done

2021-06-23 01:39 UTC, summerswallow-whi commented on papers/111_lu/paper.rst
> +We code it as separate helpers, but of course, you could combine the
done

2021-06-23 01:39 UTC, summerswallow-whi commented on papers/111_lu/paper.rst
> +Putting it all together
done

2021-06-23 01:45 UTC, summerswallow-whi commented on papers/111_lu/paper.rst
> +together. If you have access to the forms themselves, you will know what
Rewrote whole paragraph.

2021-06-23 01:47 UTC, summerswallow-whi commented on papers/111_lu/paper.rst
> +'''''''''''''''''''''''''''''''''''''''''''''
Just combined with the previous paragraph

2021-06-23 01:50 UTC, summerswallow-whi commented on papers/111_lu/paper.rst
> +our annotation, ``/Btn``, ``/Tx``, ``/Ch`` and ``/Sig``, respectively.
done

2021-06-23 01:50 UTC, summerswallow-whi commented on papers/111_lu/paper.rst
> +We will omit the signature type as we do not support filling in
moot rewritten

2021-06-23 01:51 UTC, summerswallow-whi commented on papers/111_lu/paper.rst
> +To distinguish the types of buttons and choices, we can examine the form
done

2021-06-23 01:54 UTC, summerswallow-whi commented on papers/111_lu/paper.rst
> +So now we have all the building blocks to put an automatic form filler
done. also removed unneeded reference to github repo. Leave it to the end

2021-06-23 01:56 UTC, summerswallow-whi commented on papers/111_lu/paper.rst
> +One solution is to "flatten" the each PDF file. This is equivalent to
done

2021-06-23 02:04 UTC, summerswallow-whi commented on papers/111_lu/paper.rst
> +In our use case of the vaccine clinic, we have the same form being
rewritten

2021-06-23 02:04 UTC, summerswallow-whi commented on papers/111_lu/paper.rst
> +filled out for multiple patients. So to combine a batch of these
done

2021-06-23 02:05 UTC, summerswallow-whi commented on papers/111_lu/paper.rst
> +requires all form field names to be different. The solution is quite
done

2021-06-23 02:05 UTC, summerswallow-whi commented on papers/111_lu/paper.rst
> +So all you have to do is supply a unique suffix to each form. In our
completely rewritten

2021-06-23 02:06 UTC, summerswallow-whi commented on papers/111_lu/paper.rst
> +Combining the files
done but do you capitalize 'the' in titles?

2021-06-23 02:08 UTC, summerswallow-whi commented on papers/111_lu/paper.rst
> +If one examines, these source code, the second parameter is set to the
rewritten

2021-06-23 02:11 UTC, summerswallow-whi commented on papers/111_lu/paper.rst
> +A complete functional version of this PDF form filler can be found in our
left full reference here removed earlier references.

2021-06-23 02:36 UTC, summerswallow-whi commented on papers/111_lu/paper.rst
> +should be encrypted when at rest and encrypted when in transit. For paper
This is why I marked them before the commit. I missed this one.

2021-06-23 04:02 UTC, summerswallow-whi commented
I will give another read on grammar and look for first and second person issues. I will see if my co author will have time to also give another proofread. 

I added two references. One is a news article and the reference to BAA and cloud computing is in a medical journal. Turns out most medical articles rely on PubMed to identify digital copies and not DOI. As for the other references, I guess part of the point is that there is very little documentation out there other than the spec there really isn't anything concrete out there otherwise I wouldn't have had to write this code.

As for the use of seniors, I will try to vary the usage, but I disagree that seniors is informal. I just checked a few journal articles in the New England Journal of Medicine which refer to those 65 and older as seniors. The use of the word senior is pervasive in the first half of the paper and I will endeavor to reduce the occurrences..

2021-06-23 04:02 UTC, summerswallow-whi commented on papers/111_lu/ourbib.bib
> +@article{press,
Date was added

2021-06-23 04:04 UTC, summerswallow-whi commented on papers/111_lu/paper.rst
> +compliant computer infrastructure were not well established. Even the large medical practices had
Obviously this is the kind of thing found in a contemporaneous news article. (In fact not hard to find as it was a pervasive problem at the time). So I included a local one.

2021-06-23 11:03 UTC, deniederhut commented
@summerswallow-whi to give everyone more time to respond to their reviews, we've pushed back the deadline for authors' final revisions to July 1st

2021-06-25 18:32 UTC, cbcunc commented
> As for the use of seniors, I will try to vary the usage, but I disagree that seniors is informal. I just checked a few journal articles in the New England Journal of Medicine which refer to those 65 and older as seniors. The use of the word senior is pervasive in the first half of the paper and I will endeavor to reduce the occurrences..

It's also the not all senior citizens are elderly and incapable. I'm a senior citizen. I'm not elderly yet. But I think referring to "seniors" is  informal in the same sense as referring to "millenials."

2021-06-25 18:43 UTC, cbcunc commented
@scoobies check references

2021-06-25 18:47 UTC, scoobies commented
```
Reference check summary (note 'MISSING' DOIs are suggestions that need verification):

OK DOIs

- None

MISSING DOIs

- None

INVALID DOIs

- None
```

2021-06-26 14:59 UTC, summerswallow-whi commented
@cbcunc. My coauthor went through a major rewrite to address the informality. I did many passes to try to catch any lingering grammar issues. Per your wishes references to 'seniors' are drastically reduced if not eliminated out right. Added a few more references. I think this is ready for another review. I am monitoring this, so if you see any systematic issues please comment here and I'll try to address it before you review further. Thank you

2021-06-29 16:43 UTC, summerswallow-whi commented
@cbcunc Just checking in is there anything you need me to do on this?

2021-06-30 13:39 UTC, deniederhut commented
Hi @cbcunc ! Do you feel this paper is now ready for inclusion in the proceedings?

2021-07-01 20:22 UTC, cbcunc approved these changes

2021-07-01 20:23 UTC, cbcunc commented
@scoobies mark ready

2021-07-05 16:14 UTC, merged