Paper: Enabling Active Learning Pedagogy and Insight Mining with a Grammar of Model Analysis
scipy-conference/scipy_proceedings pull request #681
Opened 2022-05-04 15:26 UTC by zdelrosario

If you are creating this PR in order to submit a draft of your paper,
see http://procbuild.scipy.org/ for logs generated by the build
process.

See the [project readme](https://github.com/scipy-conference/scipy_proceedings#build-your-paper)
for more information.

*Editor*:  

*Reviewers*:

2022-05-08 23:07 UTC, deniederhut commented
Congrats on being the first person to open a paper PR for the 2022 conference!

2022-05-29 19:57 UTC, deniederhut commented
@scoobies mark paper

2022-05-29 19:57 UTC, deniederhut commented
@scoobies mark needs review

2022-05-29 19:58 UTC, deniederhut commented
@scoobies build status

2022-05-29 19:58 UTC, scoobies commented
{"zdelrosario-2022"=>{"data"=>{"build_output"=>"[*] Updating proceedings build tools in {self.master_repo_path}...\nAlready up to date.\n[*] Check out paper repository...\nCloning into '/tmp/tmp7yxj31jg'...\nMoving proceedings build tools to temp directory...\n[*] Build the paper...\nBuilding: zachary_delrosario\n*** Warning: /tmp/tmp7yxj31jg/publisher/../output/zachary_delrosario/paper_stats.json does not exist.\n", "build_pdf_path"=>"/procbuild/procbuild/../cache/zdelrosario-2022.pdf", "build_status"=>"success", "build_timestamp"=>"25/05 02:44"}, "status"=>"success"}}

2022-05-29 20:01 UTC, deniederhut commented
@scoobies assign @cbcunc as editor

2022-05-29 20:01 UTC, scoobies commented
Assigned! @cbcunc is now the editor

2022-06-02 00:08 UTC, cbcunc commented
Editor confirms paper builds.

2022-06-07 02:29 UTC, deniederhut commented
Hi! We've moved the deadline for first reviews back one week, to June 16th, to give us a little more time to find reviewers for all the papers this year. You can see the updated full timeline at https://github.com/scipy-conference/scipy_proceedings#timeline-for-2022.

2022-06-12 01:19 UTC, cbcunc commented
@scoobies add @cbcunc to reviewers

2022-06-12 01:19 UTC, scoobies commented
@cbcunc added to the reviewers list!

2022-06-15 03:28 UTC, cbcunc requested changes
Overall this is an excellent paper about an excellent package, the kind of paper we like to see in the SciPy Proceedings. I was pleased to review it. Please make the requested changes, which are mostly cosmetic.

2022-06-15 03:28 UTC, cbcunc commented on papers/zachary_delrosario/paper.rst
> +		        df_corr=gr.df_make(var1="y", var2="z", corr=0.5)
This line overflows the column. Suggest stacking arguments to `df_make`. According to review criteria, "Code snippets should be formatted to fit inside a single column without overflow. Please make sure to check the build server's copy of your paper; it's the authoritative view of how your paper will appear." https://github.com/scipy-conference/scipy_proceedings/blob/master/review_criteria.md

2022-06-15 03:28 UTC, cbcunc commented on papers/zachary_delrosario/paper.rst
> +As mentioned above, concise grama syntax is desirable to *encourage sound analysis practices*. Grama is designed to support higher-level learning outcomes :cite:`bloom1956taxonomy`; for instance, rat
Comma within quotes after "evaluate." https://www.grammarly.com/blog/quotation-marks/

2022-06-15 03:28 UTC, cbcunc commented on papers/zachary_delrosario/paper.rst
> +As mentioned above, concise grama syntax is desirable to *encourage sound analysis practices*. Grama is designed to support higher-level learning outcomes :cite:`bloom1956taxonomy`; for instance, rat
Comma after "e.g." Parentheses suggested. https://www.aje.com/arc/editing-tip-using-eg-and-ie/

2022-06-15 03:28 UTC, cbcunc commented on papers/zachary_delrosario/paper.rst
> +Generating a parameter sweep similar to Figure :ref:`example-sweep` with standard Python libraries requires a considerable amount of boilerplate code, manual coordination of model information, and ex
Period rather than colon. Period rather than semicolon.

2022-06-15 03:28 UTC, cbcunc commented on papers/zachary_delrosario/paper.rst
> +Modern engineering relies on scientific computing. Computational advances enable faster analysis and design cycles by reducing the need for physical experiments; for instance, finite-element analysis
Divide run-on into three sentences: "Computational advances enable faster analysis and design cycles by reducing the need for physical experiments. For instance, finite-element analysis enables computational study of aerodynamic flutter, and Reynolds-averaged Navier-Stokes simulation supports the simulation of jet engines. Both of these are enabling technologies that support the design of modern aircraft [KN05]."

2022-06-15 03:28 UTC, cbcunc commented on papers/zachary_delrosario/paper.rst
> +Modern engineering relies on scientific computing. Computational advances enable faster analysis and design cycles by reducing the need for physical experiments; for instance, finite-element analysis
Comma after "e.g." Parentheses suggested. https://www.aje.com/arc/editing-tip-using-eg-and-ie/

2022-06-15 03:28 UTC, cbcunc commented on papers/zachary_delrosario/paper.rst
> +Grama was originally developed to support model analysis under uncertainty; in particular, to enable *active learning* :cite:`freeman2014active`---a form of teaching characterized by active student e
Use either the `.. unicode::` directive or bars to represent the em dashes. https://docutils.sourceforge.io/FAQ.html#how-can-i-represent-esoteric-characters-e-g-character-entities-in-a-document (Also, don't trim the spaces surrounding the em dashes.)

2022-06-15 03:28 UTC, cbcunc commented on papers/zachary_delrosario/paper.rst
> +As mentioned above, concise grama syntax is desirable to *encourage sound analysis practices*. Grama is designed to support higher-level learning outcomes :cite:`bloom1956taxonomy`; for instance, rat
Divide into two sentences: "As mentioned above, concise grama syntax is desirable to *encourage sound analysis practices*. Grama is designed to support higher-level learning outcomes [Blo56]. For instance, rather than focusing on *applying* programming constructs to generate model results, grama is intended to help users *study* model results ("evaluate," according to Bloom's Taxonomy)."

2022-06-15 03:28 UTC, cbcunc commented on papers/zachary_delrosario/paper.rst
> +    for i, x in enumerate(np.linspace(x_lo, x_up, num=nx)):
This line overflows the column. Suggest stacking arguments to `enumerate`. According to review criteria, "Code snippets should be formatted to fit inside a single column without overflow. Please make sure to check the build server's copy of your paper; it's the authoritative view of how your paper will appear." https://github.com/scipy-conference/scipy_proceedings/blob/master/review_criteria.md

2022-06-15 03:28 UTC, cbcunc commented on papers/zachary_delrosario/paper.rst
> +The ability to write low-level programming constructs---such as the loops above---is an obviously worthy learning outcome in a course on scientific computing. However, not all courses should focus on
Use either the `.. unicode::` directive or bars to represent the em dashes. https://docutils.sourceforge.io/FAQ.html#how-can-i-represent-esoteric-characters-e-g-character-entities-in-a-document (Also, don't trim the spaces surrounding the em dashes.)

2022-06-15 03:28 UTC, cbcunc commented on papers/zachary_delrosario/paper.rst
> +For example, the following code is unmodified from a student report [#]_. The original author implemented an ordinary differential equation model to simulate the track time ``"finish_time"`` of an el
Possibly use the `:code:` role for identifiers instead of quotes: https://docutils.sourceforge.io/docs/ref/rst/roles.html#code

2022-06-15 03:28 UTC, cbcunc commented on papers/zachary_delrosario/paper.rst
> +The parameter sweep shown in Figure :ref:`example-sweep` gives an overall impression of the effect of input ``"GR"`` on the output ``"finish_time"``---this particular input tends to dominate the resu
Possibly use the `:code:` role for identifiers instead of quotes: https://docutils.sourceforge.io/docs/ref/rst/roles.html#code

2022-06-15 03:28 UTC, cbcunc commented on papers/zachary_delrosario/paper.rst
> +The parameter sweep shown in Figure :ref:`example-sweep` gives an overall impression of the effect of input ``"GR"`` on the output ``"finish_time"``---this particular input tends to dominate the resu
Divide into two sentences: "The parameter sweep shown in Figure 3 gives an overall impression of the effect of input `GR` on the output `finish_time`. This particular input tends to dominate the results."

2022-06-15 03:28 UTC, cbcunc commented on papers/zachary_delrosario/paper.rst
> +This final case study illustrates how grama supports exploratory model analysis. This iterative process is a computational approach to mining insights into physical systems. We illustrate the approac
Eliminate first person, particularly the royal "we." "The following use case illustrates the approach by considering the design of boat hull cross-sections"

2022-06-15 03:28 UTC, cbcunc commented on papers/zachary_delrosario/paper.rst
> +Naval engineers analyze the stability of a boat design by constructing a *moment curve*, such as the one pictured in Figure :ref:`moment-curve`. This curve depicts the net moment due to buoyancy at v
"Note that" repeated twice in the same sentennce. Rephrase: "Note that a boat may not have an unlimited range of stability as Figure 6 exhibits an angle of vanishing stability (AVS) beyond which the boat does not recover to upright."

2022-06-15 03:28 UTC, cbcunc commented on papers/zachary_delrosario/paper.rst
> +Generation and post-processing of the moment curve are implemented in the grama model :code:`md_performance` [#]_. This model parameterizes a 2d boat hull via its height :code:`H`, width :code:`W`, s
'The negative of the moment curve slope at upright, as well as the mass and AVS angle," is a sentence *fragment* following a semicolon. What are you trying to say?

2022-06-15 03:28 UTC, cbcunc commented on papers/zachary_delrosario/paper.rst
> +The EMA process begins by generating data from the model; however, the generation of a moment curve is a nontrivial calculation. One should exercise care in choosing an initial sample of designs to a
There is a repeated pattern in this paper of combining two sentences into one compound sentence with a semicolon when two sentences would be more readable.

2022-06-15 03:28 UTC, cbcunc commented on papers/zachary_delrosario/paper.rst
> +.. csv-table:: Accuracy (:math:`R^2`) estimated via k-fold cross validation of gaussian process model. :label:`kcv`
I don't know what can be done about it,  but the csv-table directive is bleeding over into the other column. There are `widths` and `width` options for the directive. https://docutils.sourceforge.io/docs/ref/rst/directives.html#csv-table-1

2022-06-15 03:28 UTC, cbcunc commented on papers/zachary_delrosario/paper.rst
> +The parameter sweeps Figure :ref:`fit-sweep` of show a consistent and strong effect of :code:`f_com` on the :code:`stability_mean` of the boat; note that all the sweeps across :code:`f_com` for :code
I believe the word "of" is transpsed ut of place in, "The parameter sweeps Figure 8 of show." I think you meant, "The parameter sweeps of Figure 8 show.:

2022-06-15 03:28 UTC, cbcunc commented on papers/zachary_delrosario/references.bib
> +@article{hokanson2018projection,
Please include DOI:10.1137/17M1117690 (taken from your source code).

2022-06-15 03:28 UTC, cbcunc commented on papers/zachary_delrosario/paper.rst
> +A different analysis of the boat hull :code:`angle` data helps develop useful insights. We pursue an active subspace analysis of the data to reduce the dimensionality of the input space by identifyin
Why is "Reference" capitalized and what does it mean here? Does is refer to Hokanson and Constantine? If so, say "Hokanson and Constantine" instead.

2022-06-15 03:28 UTC, cbcunc commented on papers/zachary_delrosario/paper.rst
> +A different analysis of the boat hull :code:`angle` data helps develop useful insights. We pursue an active subspace analysis of the data to reduce the dimensionality of the input space by identifyin
Semicolon used to join two disparate sentences into a less readable compound.

2022-06-15 03:28 UTC, cbcunc commented on papers/zachary_delrosario/paper.rst
> +The subspace weights are reported in Table :ref:`weights` below. Note that the leading direction :code:`1` is dominated by the displacement ratio :code:`d` and COM location :code:`f_com`; essentially
Omit the word "below" as the table is rendered above the paragraph on the page.

2022-06-15 03:28 UTC, cbcunc commented on papers/zachary_delrosario/paper.rst
> +The subspace weights are reported in Table :ref:`weights` below. Note that the leading direction :code:`1` is dominated by the displacement ratio :code:`d` and COM location :code:`f_com`; essentially
Unnecessary semicolon used to join two sentences into a less readable compound.

2022-06-15 03:28 UTC, cbcunc commented on papers/zachary_delrosario/paper.rst
> +Using the subspace weights in Table :ref:`weights` to produce a 2d projection of the feature space enables visualizing all boat geometries in a single plot. Figure :ref:`2d-projection` reveals that t
Semicolon used to join two disparate sentences into a less readable compound.

2022-06-15 03:28 UTC, cbcunc commented on papers/zachary_delrosario/paper.rst
> +We presented grama---a grammar of model analysis with a Python implementation. This grammar is designed to support an active learning approach to teaching sound scientific modeling practices. We demo
Em dash is not an interjection here. Less clunky expression omitting royal "we": "Grama represents a Python implementation of a grammar for model analysis."

2022-06-15 03:28 UTC, cbcunc commented on papers/zachary_delrosario/paper.rst
> +We presented grama---a grammar of model analysis with a Python implementation. This grammar is designed to support an active learning approach to teaching sound scientific modeling practices. We demo
Change, "This grammar is designed to support," to active voice: "The grammar design supports."

2022-06-15 03:28 UTC, cbcunc commented on papers/zachary_delrosario/paper.rst
> +We presented grama---a grammar of model analysis with a Python implementation. This grammar is designed to support an active learning approach to teaching sound scientific modeling practices. We demo
Omit royal "we." "Two case studies demonstrate the teaching benefits of grama: [...]"

2022-06-15 03:28 UTC, cbcunc commented on papers/zachary_delrosario/paper.rst
> +We presented grama---a grammar of model analysis with a Python implementation. This grammar is designed to support an active learning approach to teaching sound scientific modeling practices. We demo
Omit, "We also discussed how," and simply say "Grama can be used for exploratory model analysis (EMA)."

2022-06-15 03:28 UTC, cbcunc commented on papers/zachary_delrosario/paper.rst
> +We presented grama---a grammar of model analysis with a Python implementation. This grammar is designed to support an active learning approach to teaching sound scientific modeling practices. We demo
Use either the .. unicode:: directive or bars to represent the em dash before "an exploratory procedure [...]." https://docutils.sourceforge.io/FAQ.html#how-can-i-represent-esoteric-characters-e-g-character-entities-in-a-document (Also, don't trim the spaces surrounding the em dashes.)

2022-06-15 03:28 UTC, cbcunc commented on papers/zachary_delrosario/paper.rst
> +We presented grama---a grammar of model analysis with a Python implementation. This grammar is designed to support an active learning approach to teaching sound scientific modeling practices. We demo
Lose the royal "we." "A case study of boat hull design stability demonstrated EMA."

2022-06-15 03:28 UTC, cbcunc commented on papers/zachary_delrosario/paper.rst
> +We presented grama---a grammar of model analysis with a Python implementation. This grammar is designed to support an active learning approach to teaching sound scientific modeling practices. We demo
Lose the semicolon, start a new sentence, and lose the royal "we." "In particular, grama examples explored and explained the relationship between boat design parameters and two metrics of stability."

2022-06-15 03:28 UTC, cbcunc commented on papers/zachary_delrosario/paper.rst
> +Several ideas from the grama project are of interest to other practitioners and developers in scientific computing. Grama was designed to support model analysis *under uncertainty*; however, the **da
Lose the semicolon and make two sentences.

2022-06-15 03:28 UTC, cbcunc commented on papers/zachary_delrosario/paper.rst
> +Finally, exploratory model analysis holds benefits for both learners and practitioners of scientific modeling. EMA is an alternative to derivation for the activities in an active learning approach; r
Lose the semicolon in a rather long and convoluted compound run-on sentence. "Finally, exploratory model analysis holds benefits for both learners and practitioners of scientific modeling. EMA is an alternative to derivation for the activities in an active learning approach. Rather than structuring courses around deriving and
implementing scientific models, course exercises could have students explore the behavior of a pre-implemented model to better understand physical phenomena."

2022-06-15 03:28 UTC, cbcunc commented on papers/zachary_delrosario/references.bib
> +@inproceedings{aggarwal2021qualitative,
Provide the permanent URL: https://peer.asee.org/38421

2022-06-15 03:28 UTC, cbcunc commented on papers/zachary_delrosario/references.bib
> +@article{mckinney2011pandas,
This paper is cited a lot, even though it is not archived by SC11. The best URL for it is from a for-profit content farm (https://www.researchgate.net/publication/265194455_pandas_a_Foundational_Python_Library_for_Data_Analysis_and_Statistics). The Proceedings Committee prefers that Python packages are cited by DOI where available. And Pandas has a DOI: https://pandas.pydata.org/about/citing.html

2022-06-15 03:28 UTC, cbcunc commented on papers/zachary_delrosario/references.bib
> +@inproceedings{sagiroglu2013big,
DOI: [10.1109/CTS.2013.6567202](https://doi.org/10.1109/CTS.2013.6567202)
URL: https://ieeexplore.ieee.org/document/6567202

2022-06-15 03:28 UTC, cbcunc commented on papers/zachary_delrosario/references.bib
> +@techreport{slotnick2014cfd,
URL: https://ntrs.nasa.gov/citations/20140003093

2022-06-15 03:28 UTC, cbcunc commented on papers/zachary_delrosario/references.bib
> +  title={Tidy data},
Each word in article title at DOI is capitalized.

2022-06-15 03:28 UTC, cbcunc commented on papers/zachary_delrosario/references.bib
> +  title={pandas: a foundational Python library for data analysis and statistics},
Each work in article title at URL above is capitalized.

2022-06-15 03:28 UTC, cbcunc commented on papers/zachary_delrosario/references.bib
> +  booktitle={2013 international conference on collaboration technologies and systems (CTS)},
Capitalize name of conference.

2022-06-15 03:28 UTC, cbcunc commented on papers/zachary_delrosario/references.bib
> +  title={Big data: A review},
Each word in article title at DOI is capitalized.

2022-06-15 03:28 UTC, cbcunc commented on papers/zachary_delrosario/references.bib
> +  title={CFD vision 2030 study: a path to revolutionary computational aerosciences},
Each word in title at the URL above is capitalized.

2022-06-15 03:28 UTC, cbcunc commented on papers/zachary_delrosario/references.bib
> +@article{mittal2015survey,
DOI: 10.1145/2788396
URL: https://dl.acm.org/doi/10.1145/2788396

2022-06-15 03:28 UTC, cbcunc commented on papers/zachary_delrosario/references.bib
> +  title={A survey of CPU-GPU heterogeneous computing techniques},
Each word in title at DOI is capitalized.

2022-06-15 03:28 UTC, cbcunc commented on papers/zachary_delrosario/references.bib
> +@article{zdr2021allowables,
The Proceeding Committee requires DOIs wherever possible. I tried to look up the ones where they were omitted and included them in comments below. I may have missed some.

Also, all book citations should have ISBN numbers. I did not look those up for you.

2022-06-15 03:28 UTC, cbcunc commented on papers/zachary_delrosario/references.bib
> +@inproceedings{bauer2012legion,
DOI: 10.1109/SC.2012.71
URL: https://ieeexplore.ieee.org/document/6468504

2022-06-15 03:28 UTC, cbcunc commented on papers/zachary_delrosario/references.bib
> +  title={Computational approaches for aerospace design: the pursuit of excellence},
WIley has capitalized every word in the book title.

2022-06-15 03:28 UTC, cbcunc commented on papers/zachary_delrosario/references.bib
> +@article{esmaily2020benchmark,
DOI: 10.1016/j.ijmultiphaseflow.2020.103410
URL: https://www.sciencedirect.com/science/article/abs/pii/S030193222030519X

2022-06-15 03:28 UTC, cbcunc commented on papers/zachary_delrosario/references.bib
> +@article{maeda2022integrated,
DOI: 10.48550/arXiv.2202.02319
URL: https://arxiv.org/abs/2202.02319
(meh pre-print)

2022-06-15 03:28 UTC, cbcunc commented on papers/zachary_delrosario/references.bib
> +  url="https://medium.com/@lorenaabarba/computational-thinking-i-do-not-think-it-means-what-you-think-it-means-6d39e854fa90",
Original URL: https://lorenabarba.com/blog/computational-thinking-i-do-not-think-it-means-what-you-think-it-means/

2022-06-15 03:28 UTC, cbcunc commented on papers/zachary_delrosario/references.bib
> +  author={Hassan Kibirige and Greg Lamp and Jan Katins and gdowding and austin and matthias-k and Tyler Funnell and Florian Finkernagel and Jonas Arnfred and Dan Blanchard and et al.},
Separate author names with commas instead of "and."

2022-06-15 03:28 UTC, cbcunc commented on papers/zachary_delrosario/references.bib
> +@article{kuzba2019pyceterisparibus,
DOI: 10.21105/joss.01389
URL: https://joss.theoj.org/papers/10.21105/joss.01389

2022-06-15 03:28 UTC, cbcunc commented on papers/zachary_delrosario/references.bib
> +  url = {https://cran.r-project.org/web/packages/ceterisParibus/index.html},
It says right on the CRAN page: "Please use the canonical form https://cran.r-project.org/package=ceterisParibus to link to this page."

2022-06-15 03:28 UTC, cbcunc commented on papers/zachary_delrosario/references.bib
> +  title={Probabilistic techniques in exposure assessment: a handbook for dealing with variability and uncertainty in models and inputs},
Springer capitalizes all the word in this title.

2022-06-15 03:28 UTC, cbcunc commented on papers/zachary_delrosario/references.bib
> +@article{bloom1956taxonomy,
This is a book, not an article. ISBN: 978-0679302117

2022-06-15 03:28 UTC, cbcunc commented on papers/zachary_delrosario/references.bib
> +@book{larsson2000yacht,
ISBN:  ‎ 978-0071826402

2022-06-15 03:28 UTC, cbcunc commented on papers/zachary_delrosario/references.bib
> +  year={2000},
Latest (4th) edition is 2014

2022-06-15 03:28 UTC, cbcunc commented on papers/zachary_delrosario/references.bib
> +@book{rasmussen2006gp,
ISBN: 978-0262182539

This book is also available from MIT Open Access under an electronic ISBN:

@book{10.7551/mitpress/3206.001.0001,
    author = {Rasmussen, Carl Edward and Williams, Christopher K. I.},
    title = "{Gaussian Processes for Machine Learning}",
    publisher = {The MIT Press},
    year = {2005},
    month = {11},
    isbn = {9780262256834},
    doi = {10.7551/mitpress/3206.001.0001},
    url = {https://doi.org/10.7551/mitpress/3206.001.0001},
}

2022-06-15 03:28 UTC, cbcunc commented on papers/zachary_delrosario/references.bib
> +  title = {Gaussian processes for machine learning},
MIT Press also capitalized every word in the title.

2022-06-15 03:28 UTC, cbcunc commented on papers/zachary_delrosario/references.bib
> +@book{james2013introduction,
ISBN: 978-1461471370

Also available online: https://www.statlearning.com/
(See link to PDF at bottom)

2022-06-15 03:28 UTC, cbcunc commented on papers/zachary_delrosario/references.bib
> +  title={An introduction to statistical learning},
Full title: An Introduction to Statistical Learning: with Applications in R

2022-06-15 03:28 UTC, cbcunc commented on papers/zachary_delrosario/references.bib
> +@inproceedings{delRosario2017,
DOI: 10.2514/6.2017-1090
URL: https://arc.aiaa.org/doi/10.2514/6.2017-1090

2022-06-15 03:28 UTC, cbcunc commented on papers/zachary_delrosario/references.bib
> +@BOOK{constantine2015,
DOI: 10.1137/1.9781611973860
ISBN: 978-1-61197-385-3

2022-06-15 03:28 UTC, cbcunc commented on papers/zachary_delrosario/references.bib
> +  URL= {https://speakerdeck.com/jennybc/object-of-type-closure-is-not-subsettable?slide=1},
URL: https://rstd.io/debugging

2022-06-15 03:28 UTC, cbcunc commented on papers/zachary_delrosario/references.bib
> +@unpublished{bryan2020closure,
You wouldn't conosider this @inproceedings?

2022-06-16 00:04 UTC, deniederhut commented
@scoobies mark pending comment

2022-06-16 00:04 UTC, deniederhut commented
Thanks Chris!

2022-06-24 00:30 UTC, deniederhut commented
Hi @zdelrosario ! Have you had a chance to respond to your reviewers comments?

2022-06-27 20:51 UTC, zdelrosario commented
@deniederhut apologies I let this sit for so long! I've made my revisions

@cbcunc many thanks for the very thorough review! I've made all of the requested changes. The only exception is the edition of Larsson and Eliasson that I'm referencing. I only own the 2nd edition, so that's the specific text I chose to reference.

2022-06-29 19:26 UTC, cbcunc commented
Authors, please respond to review comments with changes or comments which resolve the conversation. Final acceptance decisions are July 4.

2022-07-01 12:15 UTC, zdelrosario commented on papers/zachary_delrosario/paper.rst
> +		        df_corr=gr.df_make(var1="y", var2="z", corr=0.5)
resolved by 047f5fc219420bdcdaf00c7e6794b5888aa5204b

2022-07-01 12:15 UTC, zdelrosario commented on papers/zachary_delrosario/paper.rst
> +As mentioned above, concise grama syntax is desirable to *encourage sound analysis practices*. Grama is designed to support higher-level learning outcomes :cite:`bloom1956taxonomy`; for instance, rat
resolved by 629b2414b155015d51886ce947db4f1803464ed0

2022-07-01 12:16 UTC, zdelrosario commented on papers/zachary_delrosario/paper.rst
> +As mentioned above, concise grama syntax is desirable to *encourage sound analysis practices*. Grama is designed to support higher-level learning outcomes :cite:`bloom1956taxonomy`; for instance, rat
resolved by adbf40cd4e364ed0f111af7d748190b528410c48

2022-07-01 12:16 UTC, zdelrosario commented on papers/zachary_delrosario/paper.rst
> +Generating a parameter sweep similar to Figure :ref:`example-sweep` with standard Python libraries requires a considerable amount of boilerplate code, manual coordination of model information, and ex
resolved by 4f6eecd47c1b3ceeb4430f127b6216e9dc1024ae

2022-07-01 12:16 UTC, zdelrosario commented on papers/zachary_delrosario/paper.rst
> +Modern engineering relies on scientific computing. Computational advances enable faster analysis and design cycles by reducing the need for physical experiments; for instance, finite-element analysis
resolved by 06c48499818ade4b6f74000bdf774a216376787e

2022-07-01 12:17 UTC, zdelrosario commented on papers/zachary_delrosario/paper.rst
> +Modern engineering relies on scientific computing. Computational advances enable faster analysis and design cycles by reducing the need for physical experiments; for instance, finite-element analysis
resolved by b4f581822e5b5f43bc1961e02c96dd9ba06089b9

2022-07-01 12:17 UTC, zdelrosario commented on papers/zachary_delrosario/paper.rst
> +Grama was originally developed to support model analysis under uncertainty; in particular, to enable *active learning* :cite:`freeman2014active`---a form of teaching characterized by active student e
resolved by 11ff13b71aa89c0bf5731f4d31bdf6a861a48062

2022-07-01 12:17 UTC, zdelrosario commented on papers/zachary_delrosario/paper.rst
> +    for i, x in enumerate(np.linspace(x_lo, x_up, num=nx)):
resolved by 45c6b53b749dd0b8e6d4e1c90f84e6e849af20f5

2022-07-01 12:23 UTC, zdelrosario commented on papers/zachary_delrosario/paper.rst
> +As mentioned above, concise grama syntax is desirable to *encourage sound analysis practices*. Grama is designed to support higher-level learning outcomes :cite:`bloom1956taxonomy`; for instance, rat
resolved by https://github.com/zdelrosario/scipy_proceedings/commit/4f6eecd47c1b3ceeb4430f127b6216e9dc1024ae

2022-07-01 12:24 UTC, zdelrosario commented on papers/zachary_delrosario/paper.rst
> +The ability to write low-level programming constructs---such as the loops above---is an obviously worthy learning outcome in a course on scientific computing. However, not all courses should focus on
resolved by 11ff13b71aa89c0bf5731f4d31bdf6a861a48062

2022-07-01 12:24 UTC, zdelrosario commented on papers/zachary_delrosario/paper.rst
> +For example, the following code is unmodified from a student report [#]_. The original author implemented an ordinary differential equation model to simulate the track time ``"finish_time"`` of an el
resolved by bb3e10c5c54ebd74b0f9cf8db6e7e5ceb8329afa

2022-07-01 12:24 UTC, zdelrosario commented on papers/zachary_delrosario/paper.rst
> +The parameter sweep shown in Figure :ref:`example-sweep` gives an overall impression of the effect of input ``"GR"`` on the output ``"finish_time"``---this particular input tends to dominate the resu
resolved by 33e2fabf9ed2a19b8f00e84a375278dc168f21cf

2022-07-01 12:24 UTC, zdelrosario commented on papers/zachary_delrosario/paper.rst
> +The parameter sweep shown in Figure :ref:`example-sweep` gives an overall impression of the effect of input ``"GR"`` on the output ``"finish_time"``---this particular input tends to dominate the resu
resolved by 2dce6e3e775d6333f66b05fb8d0c7fdc359f884e

2022-07-01 12:25 UTC, zdelrosario commented on papers/zachary_delrosario/paper.rst
> +This final case study illustrates how grama supports exploratory model analysis. This iterative process is a computational approach to mining insights into physical systems. We illustrate the approac
resolved by 8f3c495d5e0e1af166d0aafd89a610837c3e86d5

2022-07-01 12:25 UTC, zdelrosario commented on papers/zachary_delrosario/paper.rst
> +Naval engineers analyze the stability of a boat design by constructing a *moment curve*, such as the one pictured in Figure :ref:`moment-curve`. This curve depicts the net moment due to buoyancy at v
resolved by 609486b0cf28df2ef612659df495d93045eeb7e9

2022-07-01 12:25 UTC, zdelrosario commented on papers/zachary_delrosario/paper.rst
> +Generation and post-processing of the moment curve are implemented in the grama model :code:`md_performance` [#]_. This model parameterizes a 2d boat hull via its height :code:`H`, width :code:`W`, s
resolved by 95bfbd78e7bb4d189d146c8ee1284fc011f0414b

2022-07-01 12:28 UTC, zdelrosario commented on papers/zachary_delrosario/paper.rst
> +The EMA process begins by generating data from the model; however, the generation of a moment curve is a nontrivial calculation. One should exercise care in choosing an initial sample of designs to a
resolved by d800c5f0e8ccd3b6467d76a7473250e8dc7f0536 and https://github.com/zdelrosario/scipy_proceedings/commit/5cf0ccbb596159bf7ecd22394487527209f42862

2022-07-01 12:28 UTC, zdelrosario commented on papers/zachary_delrosario/paper.rst
> +The parameter sweeps Figure :ref:`fit-sweep` of show a consistent and strong effect of :code:`f_com` on the :code:`stability_mean` of the boat; note that all the sweeps across :code:`f_com` for :code
resolved by eb777b59dad713118f566e99688604aefb51a584

2022-07-01 12:28 UTC, zdelrosario commented on papers/zachary_delrosario/references.bib
> +@article{hokanson2018projection,
resolved by 4a0615a29c15f20556e0e38fcc71af59d912a9ea

2022-07-01 12:29 UTC, zdelrosario commented on papers/zachary_delrosario/paper.rst
> +A different analysis of the boat hull :code:`angle` data helps develop useful insights. We pursue an active subspace analysis of the data to reduce the dimensionality of the input space by identifyin
resolved by 1cf2a7fbda5b30dd7208b2914d013dea85f686f7

2022-07-01 12:29 UTC, zdelrosario commented on papers/zachary_delrosario/paper.rst
> +A different analysis of the boat hull :code:`angle` data helps develop useful insights. We pursue an active subspace analysis of the data to reduce the dimensionality of the input space by identifyin
resolved by 133050430f330f89306e727e8dd14c8f6748d8f9

2022-07-01 12:29 UTC, zdelrosario commented on papers/zachary_delrosario/paper.rst
> +The subspace weights are reported in Table :ref:`weights` below. Note that the leading direction :code:`1` is dominated by the displacement ratio :code:`d` and COM location :code:`f_com`; essentially
resolved by 0f49a75410761c3b94694859b5f75b261a8da1b1

2022-07-01 12:30 UTC, zdelrosario commented on papers/zachary_delrosario/paper.rst
> +The subspace weights are reported in Table :ref:`weights` below. Note that the leading direction :code:`1` is dominated by the displacement ratio :code:`d` and COM location :code:`f_com`; essentially
resolved by 6bd01c33ca6b6ee5dd4946492a5b069cbdf8c634

2022-07-01 12:30 UTC, zdelrosario commented on papers/zachary_delrosario/paper.rst
> +Using the subspace weights in Table :ref:`weights` to produce a 2d projection of the feature space enables visualizing all boat geometries in a single plot. Figure :ref:`2d-projection` reveals that t
resolved by 52b53c4d79cd047bcbb0507e1302c6123f28709f

2022-07-01 12:30 UTC, zdelrosario commented on papers/zachary_delrosario/paper.rst
> +We presented grama---a grammar of model analysis with a Python implementation. This grammar is designed to support an active learning approach to teaching sound scientific modeling practices. We demo
resolved by b419c791659d78df9a2a8694842ddf4fad55b7cb

2022-07-01 12:31 UTC, zdelrosario commented on papers/zachary_delrosario/paper.rst
> +We presented grama---a grammar of model analysis with a Python implementation. This grammar is designed to support an active learning approach to teaching sound scientific modeling practices. We demo
resolved by 14ca5f1d8111527cbc2c9e32f478ed1605d77b55

2022-07-01 12:32 UTC, zdelrosario commented on papers/zachary_delrosario/paper.rst
> +We presented grama---a grammar of model analysis with a Python implementation. This grammar is designed to support an active learning approach to teaching sound scientific modeling practices. We demo
resolved by https://github.com/zdelrosario/scipy_proceedings/commit/14ca5f1d8111527cbc2c9e32f478ed1605d77b55

2022-07-01 12:32 UTC, zdelrosario commented on papers/zachary_delrosario/paper.rst
> +We presented grama---a grammar of model analysis with a Python implementation. This grammar is designed to support an active learning approach to teaching sound scientific modeling practices. We demo
resolved by 11ff13b71aa89c0bf5731f4d31bdf6a861a48062

2022-07-01 12:33 UTC, zdelrosario commented on papers/zachary_delrosario/paper.rst
> +We presented grama---a grammar of model analysis with a Python implementation. This grammar is designed to support an active learning approach to teaching sound scientific modeling practices. We demo
resolved by https://github.com/zdelrosario/scipy_proceedings/commit/14ca5f1d8111527cbc2c9e32f478ed1605d77b55

2022-07-01 12:33 UTC, zdelrosario commented on papers/zachary_delrosario/paper.rst
> +We presented grama---a grammar of model analysis with a Python implementation. This grammar is designed to support an active learning approach to teaching sound scientific modeling practices. We demo
resolved by https://github.com/zdelrosario/scipy_proceedings/commit/14ca5f1d8111527cbc2c9e32f478ed1605d77b55

2022-07-01 12:33 UTC, zdelrosario commented on papers/zachary_delrosario/paper.rst
> +Several ideas from the grama project are of interest to other practitioners and developers in scientific computing. Grama was designed to support model analysis *under uncertainty*; however, the **da
resolved by https://github.com/zdelrosario/scipy_proceedings/commit/de17d61ea39b070c8e885f46f3f236d857a7203e

2022-07-01 12:33 UTC, zdelrosario commented on papers/zachary_delrosario/paper.rst
> +Finally, exploratory model analysis holds benefits for both learners and practitioners of scientific modeling. EMA is an alternative to derivation for the activities in an active learning approach; r
resolved by https://github.com/zdelrosario/scipy_proceedings/commit/68eb11aeba88fe23da56a903cc445df158de477f

2022-07-01 12:34 UTC, zdelrosario commented on papers/zachary_delrosario/references.bib
> +@inproceedings{aggarwal2021qualitative,
resolved by https://github.com/zdelrosario/scipy_proceedings/commit/444ca487d09cfb7675873609330360f873b52c53

2022-07-01 12:35 UTC, zdelrosario commented on papers/zachary_delrosario/references.bib
> +@article{mckinney2011pandas,
resolved by https://github.com/zdelrosario/scipy_proceedings/commit/3b2c6d04ccf2e7c7205ca401d13660df3a45617f

2022-07-01 12:35 UTC, zdelrosario commented on papers/zachary_delrosario/references.bib
> +@inproceedings{sagiroglu2013big,
resolved by https://github.com/zdelrosario/scipy_proceedings/commit/2308344b0b86464827271bacf0b25efd04e36518

2022-07-01 12:35 UTC, zdelrosario commented on papers/zachary_delrosario/references.bib
> +@techreport{slotnick2014cfd,
resolved by https://github.com/zdelrosario/scipy_proceedings/commit/2308344b0b86464827271bacf0b25efd04e36518

2022-07-01 12:36 UTC, zdelrosario commented on papers/zachary_delrosario/references.bib
> +  title={Tidy data},
resolved by https://github.com/zdelrosario/scipy_proceedings/commit/7f354c21651904612e9a0949cdc51a434968b11f

2022-07-01 12:36 UTC, zdelrosario commented on papers/zachary_delrosario/references.bib
> +  title={pandas: a foundational Python library for data analysis and statistics},
obviated by https://github.com/zdelrosario/scipy_proceedings/commit/3b2c6d04ccf2e7c7205ca401d13660df3a45617f

2022-07-01 12:36 UTC, zdelrosario commented on papers/zachary_delrosario/references.bib
> +  booktitle={2013 international conference on collaboration technologies and systems (CTS)},
resolved by https://github.com/zdelrosario/scipy_proceedings/commit/f57f014410642fc753d0e848127a03a3844954b9

2022-07-01 12:37 UTC, zdelrosario commented on papers/zachary_delrosario/references.bib
> +  title={Big data: A review},
resolved by https://github.com/zdelrosario/scipy_proceedings/commit/edb840eec99ec9451940c044a4dcebba231613f0

2022-07-01 12:37 UTC, zdelrosario commented on papers/zachary_delrosario/references.bib
> +  title={CFD vision 2030 study: a path to revolutionary computational aerosciences},
resolved by https://github.com/zdelrosario/scipy_proceedings/commit/e136a38cef2e55f9dfd9564b9bd04b375c268717

2022-07-01 12:37 UTC, zdelrosario commented on papers/zachary_delrosario/references.bib
> +@article{mittal2015survey,
resolved by https://github.com/zdelrosario/scipy_proceedings/commit/abd6787d60699e325d144e56c42e18b2d8ea7820

2022-07-01 12:37 UTC, zdelrosario commented on papers/zachary_delrosario/references.bib
> +  title={A survey of CPU-GPU heterogeneous computing techniques},
resolved by https://github.com/zdelrosario/scipy_proceedings/commit/47bcebe4232be36ec1de3059625ac37a256179c1

2022-07-01 12:39 UTC, zdelrosario commented on papers/zachary_delrosario/references.bib
> +@article{zdr2021allowables,
5598936e1c8681ccb7835bfe53c11ca4e76ec379

2022-07-01 12:39 UTC, zdelrosario commented on papers/zachary_delrosario/references.bib
> +@inproceedings{bauer2012legion,
resolved by https://github.com/zdelrosario/scipy_proceedings/commit/1a872f9b7ec01bed7eae13a5c3f8b88fe5eb4cbe

2022-07-01 12:40 UTC, zdelrosario commented on papers/zachary_delrosario/references.bib
> +  title={Computational approaches for aerospace design: the pursuit of excellence},
resolved by https://github.com/zdelrosario/scipy_proceedings/commit/f86649c6dbedab06f9c83526355eea3f78423a98

2022-07-01 12:40 UTC, zdelrosario commented on papers/zachary_delrosario/references.bib
> +@article{esmaily2020benchmark,
resolved by https://github.com/zdelrosario/scipy_proceedings/commit/6992e38188fd9075a57a2c29b0913546cf847111

2022-07-01 12:40 UTC, zdelrosario commented on papers/zachary_delrosario/references.bib
> +@article{maeda2022integrated,
resolved by https://github.com/zdelrosario/scipy_proceedings/commit/6992e38188fd9075a57a2c29b0913546cf847111

2022-07-01 12:41 UTC, zdelrosario commented on papers/zachary_delrosario/references.bib
> +  url="https://medium.com/@lorenaabarba/computational-thinking-i-do-not-think-it-means-what-you-think-it-means-6d39e854fa90",
resolved by https://github.com/zdelrosario/scipy_proceedings/commit/d9d407c56508e18bd2b9b39781ca04e818ca3f8e

2022-07-01 12:41 UTC, zdelrosario commented on papers/zachary_delrosario/references.bib
> +  author={Hassan Kibirige and Greg Lamp and Jan Katins and gdowding and austin and matthias-k and Tyler Funnell and Florian Finkernagel and Jonas Arnfred and Dan Blanchard and et al.},
resolved by https://github.com/zdelrosario/scipy_proceedings/commit/abb0562250bdd2f01b8574459ec175516872b177

2022-07-01 12:41 UTC, zdelrosario commented on papers/zachary_delrosario/references.bib
> +@article{kuzba2019pyceterisparibus,
resolved by https://github.com/zdelrosario/scipy_proceedings/commit/b254d02ab77c261a5d18be4e4390d98911d157dc

2022-07-01 12:42 UTC, zdelrosario commented on papers/zachary_delrosario/references.bib
> +  url = {https://cran.r-project.org/web/packages/ceterisParibus/index.html},
resolved by https://github.com/zdelrosario/scipy_proceedings/commit/b254d02ab77c261a5d18be4e4390d98911d157dc

2022-07-01 12:42 UTC, zdelrosario commented on papers/zachary_delrosario/references.bib
> +  title={Probabilistic techniques in exposure assessment: a handbook for dealing with variability and uncertainty in models and inputs},
resolved by https://github.com/zdelrosario/scipy_proceedings/commit/ebf32a0db9bd60c8c8b1b656260c3745db9acc30

2022-07-01 12:42 UTC, zdelrosario commented on papers/zachary_delrosario/references.bib
> +@article{bloom1956taxonomy,
resolved by https://github.com/zdelrosario/scipy_proceedings/commit/1508b59ebe316270e6ec46510483a764ad0e298e

2022-07-01 12:42 UTC, zdelrosario commented on papers/zachary_delrosario/references.bib
> +@book{larsson2000yacht,
resolved by https://github.com/zdelrosario/scipy_proceedings/commit/769baaa06a8db4db7fe14c324981fc61528e87c5

2022-07-01 12:43 UTC, zdelrosario commented on papers/zachary_delrosario/references.bib
> +  year={2000},
reference of 2nd ed is intentional

2022-07-01 12:43 UTC, zdelrosario commented on papers/zachary_delrosario/references.bib
> +@book{rasmussen2006gp,
resolved by https://github.com/zdelrosario/scipy_proceedings/commit/affdc98586321f96253c0465ff0dda5cca27fd69

2022-07-01 12:43 UTC, zdelrosario commented on papers/zachary_delrosario/references.bib
> +  title = {Gaussian processes for machine learning},
resolved by https://github.com/zdelrosario/scipy_proceedings/commit/affdc98586321f96253c0465ff0dda5cca27fd69

2022-07-01 12:43 UTC, zdelrosario commented on papers/zachary_delrosario/references.bib
> +@book{james2013introduction,
resolved by https://github.com/zdelrosario/scipy_proceedings/commit/e2d19a3b75db1cc4052ad9dc7d888e2a35ba3d21

2022-07-01 12:44 UTC, zdelrosario commented on papers/zachary_delrosario/references.bib
> +  title={An introduction to statistical learning},
resolved by https://github.com/zdelrosario/scipy_proceedings/commit/5461f7e13fe0a8d1d9dc37f1d44d6ead30e62e53

2022-07-01 12:44 UTC, zdelrosario commented on papers/zachary_delrosario/references.bib
> +@inproceedings{delRosario2017,
resolved by https://github.com/zdelrosario/scipy_proceedings/commit/ef0548ec059c3f0e349985a842027865ea6f0647

2022-07-01 12:44 UTC, zdelrosario commented on papers/zachary_delrosario/references.bib
> +@BOOK{constantine2015,
resolved by https://github.com/zdelrosario/scipy_proceedings/commit/769baaa06a8db4db7fe14c324981fc61528e87c5

2022-07-01 12:44 UTC, zdelrosario commented on papers/zachary_delrosario/references.bib
> +  URL= {https://speakerdeck.com/jennybc/object-of-type-closure-is-not-subsettable?slide=1},
resolved by https://github.com/zdelrosario/scipy_proceedings/commit/c6606ed3d053ba43db0f166d47205afdce0a9fba

2022-07-01 12:45 UTC, zdelrosario commented on papers/zachary_delrosario/references.bib
> +@unpublished{bryan2020closure,
resolved by https://github.com/zdelrosario/scipy_proceedings/commit/572e88967859bff14fac526c2929410a7d46d553

2022-07-01 12:45 UTC, zdelrosario commented on papers/zachary_delrosario/paper.rst
> +.. csv-table:: Accuracy (:math:`R^2`) estimated via k-fold cross validation of gaussian process model. :label:`kcv`
resolved by fe0a8094c943eefc197b14a7faf57d4b21e7c80b

2022-07-04 19:25 UTC, deniederhut commented
@cbcunc is this paper now ready for inclusion in the proceedings?

2022-07-08 19:08 UTC, cbcunc approved these changes

2022-07-08 19:09 UTC, cbcunc commented
@scoobies mark ready

2022-07-08 22:38 UTC, deniederhut requested changes

2022-07-08 22:38 UTC, deniederhut commented on papers/zachary_delrosario/paper.rst
> +Modern engineering relies on scientific computing. Computational advances enable faster analysis and design cycles by reducing the need for physical experiments. For instance, finite-element analysis
@zdelrosario it looks like these references aren't rendering properly in the compiled pdf?

<img width="370" alt="Screen Shot 2022-07-08 at 5 34 30 PM" src="https://user-images.githubusercontent.com/6868396/178078686-c8790d34-00bc-4833-9159-ebcbbd818736.png">

2022-07-08 22:38 UTC, deniederhut commented
@scoobies mark pending comment

2022-07-09 13:10 UTC, zdelrosario commented on papers/zachary_delrosario/paper.rst
> +Modern engineering relies on scientific computing. Computational advances enable faster analysis and design cycles by reducing the need for physical experiments. For instance, finite-element analysis
@deniederhut hmm, not sure how to debug this, as the references render correctly in my local build:

<img width="469" alt="Screen Shot 2022-07-09 at 9 07 28 AM" src="https://user-images.githubusercontent.com/6273681/178107142-00f5c641-9f54-4a66-a7c6-c3f0dc004f0e.png">

Is there a way for me to read the build log on the server? I can't find a way to access that from the [paper bot](https://procbuild.scipy.org/#).

2022-07-10 21:13 UTC, deniederhut commented on papers/zachary_delrosario/paper.rst
> +Modern engineering relies on scientific computing. Computational advances enable faster analysis and design cycles by reducing the need for physical experiments. For instance, finite-element analysis
You can go to https://procbuild.scipy.org/status/zdelrosario-2022 but I would bet it won't be very helpful. Do you have files locally that are not checked in? Are you clearing the `output` folder before rebuilding your paper locally?

2022-07-10 23:19 UTC, zdelrosario commented on papers/zachary_delrosario/paper.rst
> +Modern engineering relies on scientific computing. Computational advances enable faster analysis and design cycles by reducing the need for physical experiments. For instance, finite-element analysis
You were right! Clearing the output folder let me reproduce the bug locally. That helped me catch a multiply-defined label. Just re-ran the build, and references appear to be building correctly.

2022-07-11 12:59 UTC, deniederhut commented
@scoobies check references

2022-07-11 13:00 UTC, scoobies commented
```
Reference check summary (note 'MISSING' DOIs are suggestions that need verification):

OK DOIs

- 10.2514/1.J059578 is OK
- 10.1073/pnas.1319030111 is OK
- 10.21105/joss.01686 is OK
- 10.18637/jss.v059.i10 is OK
- 10.5281/zenodo.3509134 is OK
- 10.25080/Majora-92bf1922-00a is OK
- 10.21105/joss.02462 is OK
- 10.1109/CTS.2013.6567202 is OK
- 10.1145/2788396 is OK
- 10.1109/SC.2012.71 is OK
- 10.1016/j.ijmultiphaseflow.2020.103410 is OK
- 10.48550/arXiv.2202.02319 is OK
- 10.5281/zenodo.4636791 is OK
- 10.21105/joss.01389 is OK
- 10.2307/1270363 is OK
- 10.1214/17-AOS1629 is OK
- 10.7551/mitpress/3206.001.0001 is OK
- 10.2514/6.2017-1090 is OK
- 10.1137/1.9781611973860 is OK
- 10.1137/17M1117690 is OK

MISSING DOIs

- None

INVALID DOIs

- None
```

2022-07-11 13:05 UTC, deniederhut approved these changes
Thanks for fixing those!

2022-07-11 13:05 UTC, deniederhut commented
@scoobies mark ready

2022-07-11 13:06 UTC, merged