Paper: Utilizing SciPy and other open source packages to provide a powerful API for materials manipulation in the Schrödinger Materials Suite
scipy-conference/scipy_proceedings pull request #685
Opened 2022-05-16 12:49 UTC by afonari

If you are creating this PR in order to submit a draft of your paper,
see http://procbuild.scipy.org/ for logs generated by the build
process.

See the [project readme](https://github.com/scipy-conference/scipy_proceedings#build-your-paper)
for more information.

*Editor*:  

*Reviewers*:

2022-05-16 12:49 UTC, scoobies commented
Hi!, I'm @scoobies, a friendly bot.

Type ```@scoobies help``` to discover how I can help you.

2022-05-29 20:04 UTC, deniederhut commented
@scoobies mark paper

2022-05-29 20:04 UTC, deniederhut commented
@scoobies mark needs review

2022-05-29 20:05 UTC, deniederhut commented
@scoobies build status

2022-05-29 20:05 UTC, scoobies commented
{"afonari-2022-local"=>{"data"=>{"build_output"=>"[*] Updating proceedings build tools in {self.master_repo_path}...\nAlready up to date.\n[*] Check out paper repository...\nCloning into '/tmp/tmpepe6gvde'...\nMoving proceedings build tools to temp directory...\n[*] Build the paper...\nBuilding: alexandr_fonari\n*** Warning: /tmp/tmpepe6gvde/publisher/../output/alexandr_fonari/paper_stats.json does not exist.\n", "build_pdf_path"=>"/procbuild/procbuild/../cache/afonari-2022-local.pdf", "build_status"=>"success", "build_timestamp"=>"26/05 14:52"}, "status"=>"success"}}

2022-05-29 20:05 UTC, deniederhut commented
@scoobies assign @mepa as editor

2022-05-29 20:05 UTC, scoobies commented
Assigned! @mepa is now the editor

2022-05-31 00:39 UTC, deniederhut commented
@scoobies add @bdice to reviewers

2022-05-31 00:39 UTC, scoobies commented
@bdice added to the reviewers list!

2022-06-01 11:54 UTC, deniederhut commented
@scoobies add @wdzhou to reviewers

2022-06-01 11:54 UTC, scoobies commented
@wdzhou added to the reviewers list!

2022-06-05 02:17 UTC, bdice commented
@afonari To make this paper easier to review / provide feedback in GitHub, would you be able to split each sentence onto its own line?  There are long paragraphs in many places where I only want to comment on one sentence. This is also called [semantic linefeeds](https://ramshankar.org/blog/posts/2019/semantic-line-breaks/). (I just want line breaks at the ends of sentences, you don't need to break after every comma as some style guides suggest.)

If the authors are hesitant to reformat in this way, I can leave all my feedback for each paragraph in a comment on the line for that paragraph. It will just be harder to iterate and point out specific features of the text.

2022-06-05 16:00 UTC, afonari commented
Sure, will fix soon.

2022-06-06 22:41 UTC, afonari commented
Should be good now.

2022-06-07 02:30 UTC, deniederhut commented
Hi! We've moved the deadline for first reviews back one week, to June 16th, to give us a little more time to find reviewers for all the papers this year. You can see the updated full timeline at https://github.com/scipy-conference/scipy_proceedings#timeline-for-2022.

2022-06-07 05:49 UTC, bdice reviewed
@afonari First, thanks for contributing this paper! I finished a first round of feedback. My high level thoughts and some lower-level edits can be found in the attached comments.

My broad feedback is that this paper has a lot of potential to be useful and interesting to readers, and would benefit from increased depth and flavor in a few key areas: more background information about what the Schrodinger Materials Suite is and how it relates to the SciPy ecosystem, more details about the use cases (which are exciting topics!) with an emphasis on scientific computing, more descriptions of how Schrodinger/SciPy tools are used together, more figures, more code snippets, and especially more links for readers to find the software, documentation, and code examples to get started.

I felt a little confused about which pieces of this paper are describing proprietary tools (vs. open source tools) and who develops each of them. I would appreciate greater clarity about that information when introducing the names of each program/library. I only have experience with using open source MD simulation engines, and I know very little about proprietary tools in this space or how well they interact with the SciPy ecosystem. I suspect many readers may have a similar lack of background knowledge about Schrodinger, what its software does (just simulation? or also tasks like analysis, job submission, and machine learning?), and how it can be used in conjunction with free and open source software in the SciPy ecosystem.

2022-06-07 05:49 UTC, bdice commented on papers/alexandr_fonari/alexandr_fonari.rst
> + Both formats allow description of the positional disorder (one example being a solvent molecule not having a stable position within the cell can be described by two or more sets of coordinates).
What does "both formats" refer to? CIF and PDB? The previous reference also listed mmCIF, so I am unsure what this means.
```suggestion
Both formats allow description of the positional disorder (for example, a solvent molecule without a stable position within the cell which can be described by multiple sets of coordinates).
```

2022-06-07 05:49 UTC, bdice commented on papers/alexandr_fonari/alexandr_fonari.rst
> +All these nuances present non-trivial technical challenges.
```suggestion
All these nuances present nontrivial technical challenges.
```

2022-06-07 05:49 UTC, bdice commented on papers/alexandr_fonari/alexandr_fonari.rst
> +Thus, it has been a continuous effort by Schrödinger (at least 39 commits went into this project) and others to correctly read and convert periodic structures in OpenBabel.
"39 commits": There may be a better way to quantify the effort here. Commit sizes vary wildly from person to person and can be easily distorted by merges / squashes / etc. I would consider measuring this in another way such as hours, lines of code, or number of pull requests. You might even say it two ways, like "39 commits and 2 weeks of work."

2022-06-07 05:49 UTC, bdice commented on papers/alexandr_fonari/alexandr_fonari.rst
> +By version 3.1.1 (the most recent at writing time), this effort resulted in very few (if any) known cases where OpenBabel reads incorrect structure from the experimental data.
"very few (if any)": Are there incorrect cases known to you, or not? This statement is supposed to be celebrating a successful effort but I am having trouble determining the extent to which the problem is solved (or not solved). If there is room for the community to engage and improve this code, what is needed?

2022-06-07 05:49 UTC, bdice commented on papers/alexandr_fonari/alexandr_fonari.rst
> +By version 3.1.1 (the most recent at writing time), this effort resulted in very few (if any) known cases where OpenBabel reads incorrect structure from the experimental data.
```suggestion
By version 3.1.1 (the most recent at writing time), this effort resulted in very few (if any) known cases where OpenBabel reads an incorrect structure from the experimental data.
```

2022-06-07 05:49 UTC, bdice commented on papers/alexandr_fonari/alexandr_fonari.rst
> + Both formats allow description of the positional disorder (one example being a solvent molecule not having a stable position within the cell can be described by two or more sets of coordinates).
Can you remove the leading spaces in lines like this one? It looks like a few of these were added when the paragraphs were broken up.

2022-06-07 05:49 UTC, bdice commented on papers/alexandr_fonari/alexandr_fonari.rst
> +Such catalysts may prove critical in electrocatalysis for the fuel cell applications [TM]_.
```suggestion
Such catalysts may prove critical in electrocatalysis for fuel cell applications [TM]_.
```

2022-06-07 05:49 UTC, bdice commented on papers/alexandr_fonari/alexandr_fonari.rst
> +We have implemented a job queuing system on top of the most used queuing systems (SLURM, torque, etc.) and exposed a Python API to submit and monitor jobs.
Seems like TORQUE is supposed to be capitalized ([Wikipedia](https://en.wikipedia.org/wiki/TORQUE)). Is it worth listing all supported schedulers instead of just saying "etc."? (PBS? LSF?)

Are only HPC / cluster schedulers supported? Are cloud scheduling systems supported? For examples of the kinds of systems I'm thinking about, [Parsl](https://parsl.readthedocs.io/en/stable/) lists its support like this:
> Parsl supports various target resources including clouds (e.g., Amazon Web Services and Google Cloud), clusters (e.g., using Slurm, Torque/PBS, HTCondor, Cobalt), and container orchestration systems (e.g., Kubernetes).

```suggestion
We have implemented a job queuing system on top of the most used queuing systems (SLURM, TORQUE, etc.) and exposed a Python API to submit and monitor jobs.
```

2022-06-07 05:49 UTC, bdice commented on papers/alexandr_fonari/alexandr_fonari.rst
> +If a job fails (and can not be restarted), all its children (if any) will not start, thus saving queuing and computational time (some examples of workflows are provided below).
Rewrite:
```suggestion
If a job fails and cannot be restarted, all its children (if any) will be canceled, thus saving queuing and computational time (some examples of workflows are provided below).
```

2022-06-07 05:49 UTC, bdice commented on papers/alexandr_fonari/alexandr_fonari.rst
> +If a job fails (and can not be restarted), all its children (if any) will not start, thus saving queuing and computational time (some examples of workflows are provided below).
A job failure means that its children cannot start. Is this always the behavior that users would want on failure? Can random failures or misconfigured software cause the exploration to miss some structures? It may deserve some clarification of what a "failure" means in this context.

2022-06-07 05:49 UTC, bdice commented on papers/alexandr_fonari/alexandr_fonari.rst
> +There, using Desmond code [Desmond]_ we computed the glass transition temperature (Tg) of 315 polymers and compared the results with experimental measurements [Bicerano]_.
There are a few places where articles (the, a, an) are missing in the paper.

Can we write `Tg` in math font, with the `g` in subscript? In LaTeX it would be `$T_g$` but I can't remember how to format that in this document.
```suggestion
There, using the Desmond code [Desmond]_ we computed the glass transition temperature (Tg) of 315 polymers and compared the results with experimental measurements [Bicerano]_.
```

2022-06-07 05:49 UTC, bdice commented on papers/alexandr_fonari/alexandr_fonari.rst
> +Whereas for the materials simulations (QM, periodic DFT, classical MD) Python, even with SciPy/NumPy can be slow, SciPy and related packages provide sophisticated numerical function optimization and
This sentence is awkwardly phrased. I might try rewriting it in multiple sentences and avoid the broad statement that "Python is slow." The speed of the Python interpreter is a topic with a lot of nuance, and there are many valid objections to the claim that Python is slow (use NumPy, use PyPy, etc.). Moreover, many popular materials simulation engines have Python bindings, which make fast (compiled C++/CUDA) code transparently accessible to the user.

```suggestion
Materials simulation engines for QM, periodic DFT, and classical MD are frequently written in languages other than Python, with compiled code that is tuned for parallel CPU or GPU hardware.
Some of these simulation codes have Python bindings that combine the engine's high performance with Python's ease of use.
Meanwhile, packages such as SciPy and NumPy provide sophisticated numerical function optimization and fitting capabilities.
Below, we describe examples of how the Schrödinger suite can be used to combine materials simulations with popular optimization routines in the SciPy ecosystem.
```

2022-06-07 05:49 UTC, bdice commented on papers/alexandr_fonari/alexandr_fonari.rst
> +The stress strain curve is obtained from a series of consequent MD simulations on deformed cells (cell deformations are defined by strain type and deformation step).
I think the word "consequent" is unnecessary here unless it has a technical meaning that I don't know. It's already described as "a series of..."
```suggestion
The stress strain curve is obtained from a series of MD simulations on deformed cells (cell deformations are defined by strain type and deformation step).
```

2022-06-07 05:49 UTC, bdice commented on papers/alexandr_fonari/alexandr_fonari.rst
> +Another area where scipy.optimize is used is fitting of the bulk energies at different cell volumes (compressed and expanded) in order to obtain bulk modulus and equation of state (EOS) of a material
Try to use code font for package names like `scipy.optimize`.

2022-06-07 05:49 UTC, bdice commented on papers/alexandr_fonari/alexandr_fonari.rst
> +Another area where scipy.optimize is used is fitting of the bulk energies at different cell volumes (compressed and expanded) in order to obtain bulk modulus and equation of state (EOS) of a material
```suggestion
The ``scipy.optimize`` package is used for a least-squares fit of the bulk energies at different cell volumes (compressed and expanded) in order to obtain the bulk modulus and equation of state (EOS) of a material.
```

2022-06-07 05:49 UTC, bdice commented on papers/alexandr_fonari/alexandr_fonari.rst
> +Technically, it is a least squares method.
This sentence disrupts the flow of the preceding and following sentences. Maybe combine with the previous sentence? See comment above.
```suggestion
```

2022-06-07 05:49 UTC, bdice commented on papers/alexandr_fonari/alexandr_fonari.rst
> +Technically, it is a constrained minimization with boundary conditions (as implemented in ``scipy.optimize.minimize``) of a function related to the stress strain curve.
Starting this sentence with "Technically," may sound a bit rude (as if you're correcting someone else), and is not necessary for the flow of the sentence. I recommend removing it:
```suggestion
The package ``scipy.optimize.minimize`` is used for a constrained minimization with boundary conditions of a function related to the stress strain curve.
```

2022-06-07 05:49 UTC, bdice commented on papers/alexandr_fonari/alexandr_fonari.rst
> +This is also an example of the loosely coupled (embarrassingly parallel) jobs.
This section of the paper feels like an overview of many computational materials science workflows with its general statements about high-throughput / embarrassingly parallel workflows. I was hoping for more detailed content -- are there more details that can be extracted from the cited papers to make this section more interesting for a scientific computing audience? (I haven't had the chance to read those cited papers yet, but I am guessing they are focused towards a scientific / materials community, rather than a scientific computing community. There may be room to expand here with novel information not contained in the cited papers.)

In my first read through the paper, I started to wonder at this point about how the key phrases in the title of the paper would be addressed, since this is about 2/3 of the way through the paper's contents. Specifically, I was hoping to hear more about a few topics:
- **"utilizing SciPy"** -- The examples thus far have used least squares function minimization. It would be nice to have broader examples with more details about why those use cases are interesting/complex from an algorithmic _or_ scientific perspective.
- "other open source packages" -- only SciPy has been mentioned at this point, I think? Some open source simulation engines may have been mentioned but were not a focus. This is partially addressed when `lmfit` is mentioned below, but it would be nice to have more examples like that.
- "powerful API" -- there have been no descriptions of the Schrodinger suite's API design or what constitutes a "powerful" API
- "materials manipulation" -- this phrase has the best match for the content in the paper thus far, with descriptions of stress/strain, bulk modulus/EOS, and powder diffraction in this section

The paper is only 4 pages at present, so there's lots of room to zoom in on some of these topics with more interesting details. This section on "use cases" has a lot of potential and I believe it should be the highlight of the paper. Share more code snippets, figures, formulas, anything to add flavor to the scientific problem or computational approaches enabled by combining the SciPy ecosystem with this Schrodinger suite of simulation tools!

2022-06-07 05:49 UTC, bdice commented on papers/alexandr_fonari/alexandr_fonari.rst
> +This is also an example of the loosely coupled (embarrassingly parallel) jobs.
Additionally: have the authors contributed to the open source packages used for this work? That would be another great source of content to add, if upstream contributions (or even proposed improvements) have been made.

2022-06-07 05:49 UTC, bdice commented on papers/alexandr_fonari/alexandr_fonari.rst
> +Powder diffraction is widely used in drug discovery to assess purity of the material and discover known or unknown crystal polymorphs that could form [Powder]_.
This sentence is awkward at the end of the paragraph. I think it would be sensible to define powder diffraction at the beginning of this paragraph.

2022-06-07 05:49 UTC, bdice commented on papers/alexandr_fonari/alexandr_fonari.rst
> +In the Schrödinger suite, benchmark data for small molecules and finite systems can be obtained using QM DFT molecular Jaguar code, for periodic systems, QE used, for larger polymeric and similar sys
This sentence is awkward and long. Try rephrasing. Suggestion:
```suggestion
In the Schrödinger suite, benchmark data can be obtained using a few different tools.
The QM DFT molecular Jaguar code is used for small molecules and finite systems.
Periodic systems are simulated with Quantum ESPRESSO.
Lastly, larger polymeric and similar systems use the Desmond molecular dynamics code.
```

2022-06-07 05:49 UTC, bdice commented on papers/alexandr_fonari/alexandr_fonari.rst
> +Element descriptors (such as atomic weight, number of valence electrons in s-, p- and d-shells, electronegativity), structure descriptors (such as density, volume per atom, and packing fraction descr
I believe it's common practice to italicize the letters _s_, _p_, _d_, _f_ when referring to orbitals.

2022-06-07 05:49 UTC, bdice commented on papers/alexandr_fonari/alexandr_fonari.rst
> +Element descriptors (such as atomic weight, number of valence electrons in s-, p- and d-shells, electronegativity), structure descriptors (such as density, volume per atom, and packing fraction descr
This isn't a complete sentence. It could be a bulleted list, or it could be transformed into a sentence like:
```suggestion
These descriptors include elemental features such as atomic weight, number of valence electrons in s-, p- and d-shells, or electronegativity; structural features such as density, volume per atom, and packing fraction descriptors from matminer [Matminer]_; intercalation descriptors such as cation and anion counts, crystal packing fraction, average neighbor ionicity [Sendek]_; and three-dimensional smooth overlap of atomic positions (SOAP) descriptors implemented in DScribe [DScribe]_.
```

2022-06-07 05:49 UTC, bdice commented on papers/alexandr_fonari/alexandr_fonari.rst
> +Using these descriptors and kernel regression methods to train the model, as implemented in scikit-learn [SkLearn]_, we were able to train a model that successfully predicted bulk modulus of a set of
Tons of questions here -- the reader would benefit from knowing a lot more.
- Is this describing a paper that should be cited?
- Why kernel ridge regression?
- Were all the features necessary? Are some features irrelevant?
- What does it mean to have a successful prediction of the bulk modulus? How was the quality of the result assessed?
- Were other methods used for comparison?
- What role does the Schrödinger software suite play in this example, if any? (It sounds like these features all come from tools like rdkit / matminer / DScribe and the analysis is done with scikit-learn.)

2022-06-07 05:49 UTC, bdice commented on papers/alexandr_fonari/alexandr_fonari.rst
> +.. figure:: fig_al.jpg
This figure's text is too small to read without zooming the PDF. I would consider making it a full-width figure instead of only one column.

Can the figure resolution also be improved? It looks like the content is fuzzy even at full resolution.

2022-06-07 05:49 UTC, bdice commented on papers/alexandr_fonari/alexandr_fonari.rst
> +In this approach, machine learning and DFT are combined.
Should this section cite research papers or review articles in the field of ML + DFT for property prediction? I have a few references I would suggest, but they may be 3 years old and may not reflect the current state of the field.

2022-06-07 05:49 UTC, bdice commented on papers/alexandr_fonari/alexandr_fonari.rst
> +Recently, we implemented a workflow that employs active learning (AL) for intelligent and iterative identification of promising materials candidates within a large dataset [Abroshan]_.
"promising materials candidates" -- what kind of properties being considered? It says "multiple properties" below but only lists "hole transport layer." Not all properties are equally easy to predict with machine learning.

2022-06-07 05:49 UTC, bdice commented on papers/alexandr_fonari/alexandr_fonari.rst
> +There we used descriptors as implemented in rdkit to featurize the chemical structures.
I suggest writing the name as RDKit, in line with the package's documentation rather than its import name. Additionally, this sentence is a little redundant ("used descriptors ... to featurize").
```suggestion
We used RDKit to compute descriptors for the chemical structures.
```

2022-06-07 05:49 UTC, bdice commented on papers/alexandr_fonari/alexandr_fonari.rst
> +Bayesian optimization is employed to tune the hyperparameters of the model.
Verb tense and voice is inconsistent in many areas of the paper:
> There we used descriptors ...

(past tense, active voice)

> Bayesian optimization is employed ...

(present tense, passive voice)

This is a broad problem so I won't comment heavily on it, but I would recommend reading through the paper and editing for consistency throughout.

2022-06-07 05:49 UTC, bdice commented on papers/alexandr_fonari/alexandr_fonari.rst
> +Multiple properties are  scaled and combined into a single score value.
```suggestion
Multiple properties are scaled and combined into a single score value.
```

2022-06-07 05:49 UTC, bdice commented on papers/alexandr_fonari/alexandr_fonari.rst
> +In this particular study, for a dataset of ~9,000 molecules, the AL workflow determined the top candidates for hole (positively charged carrier) transport layer  by evaluating 550 molecules in 10 ite
I'd put this sentence much higher in the paragraph. It explains the scope and purpose of the study.
```suggestion
In this particular study, for a dataset of ~9,000 molecules, the AL workflow determined the top candidates for hole (positively charged carrier) transport layer by evaluating 550 molecules in 10 iterations using DFT calculations.
```

2022-06-07 05:49 UTC, bdice commented on papers/alexandr_fonari/alexandr_fonari.rst
> +Performing DFT calculations for all of the 9,000 molecules in the dataset would increase the computational cost by a factor of 15 versus the AL workflow.
Was the full dataset of 9000 molecules computed, to validate that the active learning algorithms didn't reject any samples that were in fact good candidates? More broadly, it would be helpful to discuss lessons learned from this experiment. What struggles were faced? From what you discovered (or from other research you cite), what classes of problems in materials engineering would you say are a good / bad fit for active learning?

2022-06-07 05:49 UTC, bdice commented on papers/alexandr_fonari/alexandr_fonari.rst
> +These descriptors generated on the initial subset of structures are given as vectors to an algorithm based on Random Forest as implemented in scikit-learn.
Was this a random forest classifier or a random forest regressor? Give more details about the model and optimization strategies. Consider a code snippet or figure that demonstrates the results.

2022-06-07 05:49 UTC, bdice commented on papers/alexandr_fonari/alexandr_fonari.rst
> +We present several examples of how Schrödinger Materials Suite incorporates open source software packages.
I am unsure exactly what this sentence is intending to mean. Is "incorporates" the right word? Or is it more accurate to describe this as an integration with the SciPy ecosystem, through common data structures (e.g. NumPy arrays)?

More generally, I don't fully understand what the Schrödinger software does after reading this paper. It sounds like scientists are leveraging open source software as a part of their discovery/exploration of materials design spaces but I am having trouble identifying the boundary/interface where (proprietary?) Schrodinger software begins and open source software from the SciPy ecosystem ends. I was hoping to get more clarity on this while reading through the paper, but I didn't find what I was looking for.

After a bit of reading and internet searches beyond this paper, it seems that Jaguar and Desmond are proprietary commercial simulation codes developed by Schrodinger (or developed by DE Shaw Research? Unclear from a quick glance) and Quantum Espresso is an open source simulation engine ([GPLv2](https://www.quantum-espresso.org/Doc/pw_user_guide/node5.html)). I have a few questions that may help to provide clarity about the primary topics mentioned in this paper's title.

1. Do all the codes mentioned above have Python bindings?
2. Are those Python APIs provided by the "Schrödinger Materials Suite" in some unified manner, or are the Python bindings provided by each package (and thus probably feel different from one another)?
3. How similar or different are the Python APIs for the various workflows / use cases described in this paper? Code snippets or documentation references would be very helpful.
4. Do these codes use standard data structures like NumPy arrays to transfer information to other packages in the SciPy ecosystem, or do users need to save/load/parse files to share data between packages?
5. Do users of "Schrödinger Materials Suite" have access to open source code examples in the documentation or an examples repository that demonstrate interactions with the SciPy ecosystem? Are codes publicly available for replicating any of the studies described in this paper?
6. Is the API of the "Schrödinger Materials Suite" designed to align with common API paradigms of packages like NumPy/SciPy/scikit-learn? What does the API look and feel like? Is it functional? Object oriented? Client/server?
7. Where can users find basic information and documentation on the "Schrödinger Materials Suite"? There should be links to these resources in the text or footnotes of the first page of the paper.

2022-06-07 05:49 UTC, bdice commented on papers/alexandr_fonari/alexandr_fonari.rst
> +We hope that this report will inspire other scientific companies to give back to the open source community in order to improve the computational materials field and make science more reproducible.
These last sentences are very nice. I also hope that all researchers (academic or industry) in this field continue contributing to shared open source efforts to accelerate scientific discovery and reproducibility! ❤️

2022-06-07 05:49 UTC, bdice commented on papers/alexandr_fonari/alexandr_fonari.rst
> +References
I strongly recommend using a BibTeX file and citing references that way. See example here: https://github.com/scipy-conference/scipy_proceedings/tree/2022/papers/00_bibderwalt

The formatting of the bibliography is a little strange, and I think it's because this isn't using BibTeX for citations. Compare formatting:

Another draft paper submitted to the proceedings using BibTeX:
![image](https://user-images.githubusercontent.com/3943761/172303728-4096fed0-35e6-4bfe-af2b-c5fc8d41d7d0.png)

This paper (notice how the number of initials-with-periods in the author's name determines the horizontal offset!?):
![image](https://user-images.githubusercontent.com/3943761/172303835-1570bdc2-306c-4464-b44a-7243cbc544d9.png)

2022-06-07 05:52 UTC, bdice commented on papers/alexandr_fonari/alexandr_fonari.rst
> +In the Schrödinger suite this was implemented as a part of the EOS workflow, fitting is performed on the the results obtained from a series of QE calculations performed on the original and compressed
```suggestion
In the Schrödinger suite this was implemented as a part of the EOS workflow, fitting is performed on the results obtained from a series of QE calculations performed on the original and compressed/expanded (deformed) cells.
```

2022-06-07 14:23 UTC, wdzhou commented on papers/alexandr_fonari/alexandr_fonari.rst
> +Tools for computational materials discovery can be facilitated by utilizing existing libraries that cover the fundamental mathematics used in the calculations in an optimized fashion.
It would be more helpful for the readers if you could describe what is computational materials discovery and its impact briefly.

2022-06-07 14:23 UTC, wdzhou commented on papers/alexandr_fonari/alexandr_fonari.rst
> +Every step of this workflow can benefit from open source code.
Could you list a few open source codes as example?

2022-06-07 14:25 UTC, wdzhou commented
@afonari Hi, This is @wdzhou.  I am just back from vacation and will try my best to catch up the review work in the next 2 days.

2022-06-08 01:38 UTC, deniederhut commented
@scoobies mark needs more review

2022-06-08 19:35 UTC, wdzhou requested changes
Hi, Here is some of my thoughts on your paper.  Overall, it is a great work on the material simulation.

2022-06-08 19:35 UTC, wdzhou commented on papers/alexandr_fonari/alexandr_fonari.rst
> +Thus, it has been a continuous effort by Schrödinger (at least 39 commits went into this project) and others to correctly read and convert periodic structures in OpenBabel.
Could you use Schrödinger project or Schrödinger library instead?  My first response to see Schrödinger is the Schrödinger who had the cat.   Thanks.

2022-06-08 19:35 UTC, wdzhou commented on papers/alexandr_fonari/alexandr_fonari.rst
> +The enumlib library implements algorithms for such a systematic enumeration of periodic structures [Enumlib]_.
Is `enumlib` a specific software library?  If so, it is better to have a reference to it just behind `enumlib library`.  The reference could be a paper about it or its webpage.

2022-06-08 19:35 UTC, wdzhou commented on papers/alexandr_fonari/alexandr_fonari.rst
> +We generated a set of stable doped Pt/transition metal/nitrogen surfaces using periodic enumeration.
Do you have a paper/article to report this study?

2022-06-08 19:35 UTC, wdzhou commented on papers/alexandr_fonari/alexandr_fonari.rst
> +In order to be able to run a massively parallel screening of materials a highly scalable and stable queuing system (job scheduler) is required.
`In order to be able to run a massively parallel screening of materials a highly scalable and stable queuing system (job scheduler) is required.`

It is better to add a comma between `materials` and `a`.

2022-06-08 19:40 UTC, wdzhou requested changes
Another 2 comments.

2022-06-08 19:40 UTC, wdzhou commented on papers/alexandr_fonari/alexandr_fonari.rst
> +As an example, organic light-emitting diodes (OLEDs) are fabricated using a stepwise process, where layers are deposited on top of previous layers.
I suggest to put a `by` before using, such that

We implemented molecular deposition and evaporation workflows `by` using the Desmond MD.

2022-06-08 19:40 UTC, wdzhou commented on papers/alexandr_fonari/alexandr_fonari.rst
> +In order to train a model, benchmark data from calculations and/or experimental data is required.
Here, does **calculations data** mean **simulation data**?

2022-06-10 04:29 UTC, bdice commented on papers/alexandr_fonari/alexandr_fonari.rst
> +Thus, it has been a continuous effort by Schrödinger (at least 39 commits went into this project) and others to correctly read and convert periodic structures in OpenBabel.
Good idea @wdzhou. "Schrödinger, Inc." might be the clearest.

2022-06-10 11:40 UTC, afonari commented on papers/alexandr_fonari/alexandr_fonari.rst
> + Both formats allow description of the positional disorder (one example being a solvent molecule not having a stable position within the cell can be described by two or more sets of coordinates).
- Removed leading spaces in couple of places.
 - Included above suggestion. The sentence is now:

PBD, CIF and mmCIF formats allow description of the positional disorder (for example, a solvent molecule without a stable position within the cell which can be described by multiple sets of coordinates).

2022-06-10 11:41 UTC, afonari commented on papers/alexandr_fonari/alexandr_fonari.rst
> +Thus, it has been a continuous effort by Schrödinger (at least 39 commits went into this project) and others to correctly read and convert periodic structures in OpenBabel.
Fixed, sentence is now:

Thus, it has been a continuous effort by Schrödinger, Inc. (at least 39 commits and several weeks of work went into this project) and others to correctly read and convert periodic structures in OpenBabel.

2022-06-10 11:41 UTC, afonari commented on papers/alexandr_fonari/alexandr_fonari.rst
> +All these nuances present non-trivial technical challenges.
Fixed, thanks.

2022-06-10 11:49 UTC, afonari commented on papers/alexandr_fonari/alexandr_fonari.rst
> +Such catalysts may prove critical in electrocatalysis for the fuel cell applications [TM]_.
Thanks, fixed.

2022-06-10 12:08 UTC, afonari commented on papers/alexandr_fonari/alexandr_fonari.rst
> +We have implemented a job queuing system on top of the most used queuing systems (SLURM, torque, etc.) and exposed a Python API to submit and monitor jobs.
Good point. Updated sentences to:

We have implemented a job queuing system on top of the most used queuing systems (LSF, PBS, SGE, SLURM, TORQUE, UGE) and exposed a Python API to submit and monitor jobs.
Cloud is also supported by means of a virtual cluster configured with SLURM. This allows to submit a large number of jobs, limited only by SLURM scheduling capabilities and cloud resources.

2022-06-10 12:27 UTC, afonari commented on papers/alexandr_fonari/alexandr_fonari.rst
> +If a job fails (and can not be restarted), all its children (if any) will not start, thus saving queuing and computational time (some examples of workflows are provided below).
Sure, expanded to:

There could be several reasons for a job to fail and there are several restart/recovery mechanisms in place. The lowest level is the restart mechanism (in SLURM it is called *requeue*) by the queuing system itself. This is triggered when a node goes down for some reason. On the cloud, preemptible instances (nodes) can go offline at any moment. On top of that, each individual workflow implements its own way to deal with failures. For example, in case when the simulation is not converging to a requested energy accuracy, it is wasteful to blindly restart the calculation without changing some input parameters. However, in the case of full disk space failure, it is reasonable to try restart with hopes to get a node with more empty disk space. If a job fails (and can not be restarted), all its children (if any) will not start, thus saving queuing and computational time (some examples of workflows are provided below).

2022-06-10 13:32 UTC, afonari commented on papers/alexandr_fonari/alexandr_fonari.rst
> +There, using Desmond code [Desmond]_ we computed the glass transition temperature (Tg) of 315 polymers and compared the results with experimental measurements [Bicerano]_.
> There are a few places where articles (the, a, an) are missing in the paper.

Will try to catch more of those.

> Can we write Tg in math font, with the g in subscript? In LaTeX it would be $T_g$ but I can't remember how to format that in this document.

Yes, fixed:
```
:math:`T_g`
```

2022-06-10 13:37 UTC, afonari commented on papers/alexandr_fonari/alexandr_fonari.rst
> +Whereas for the materials simulations (QM, periodic DFT, classical MD) Python, even with SciPy/NumPy can be slow, SciPy and related packages provide sophisticated numerical function optimization and
Great, thanks, it is now:

Materials simulation engines for QM, periodic DFT, and classical MD (backends) are frequently written in compiled languages with enabled parallelization for CPU or GPU hardware.
These backends are called from Python workflows using job queuing system described above.
Meanwhile, packages such as SciPy and NumPy provide sophisticated numerical function optimization and fitting capabilities.
Below, we describe examples of how the Schrödinger suite can be used to combine materials simulations with popular optimization routines in the SciPy ecosystem.

2022-06-10 13:40 UTC, afonari commented on papers/alexandr_fonari/alexandr_fonari.rst
> +The stress strain curve is obtained from a series of consequent MD simulations on deformed cells (cell deformations are defined by strain type and deformation step).
Fixed.

2022-06-10 13:40 UTC, afonari commented on papers/alexandr_fonari/alexandr_fonari.rst
> +Another area where scipy.optimize is used is fitting of the bulk energies at different cell volumes (compressed and expanded) in order to obtain bulk modulus and equation of state (EOS) of a material
> Try to use code font for package names like scipy.optimize.

Yes, thanks.

2022-06-10 13:41 UTC, afonari commented on papers/alexandr_fonari/alexandr_fonari.rst
> +Technically, it is a least squares method.
Yes, removed.

2022-06-10 13:44 UTC, afonari commented on papers/alexandr_fonari/alexandr_fonari.rst
> +Technically, it is a constrained minimization with boundary conditions (as implemented in ``scipy.optimize.minimize``) of a function related to the stress strain curve.
Thanks, fixed.

2022-06-10 13:52 UTC, afonari commented on papers/alexandr_fonari/alexandr_fonari.rst
> +Powder diffraction is widely used in drug discovery to assess purity of the material and discover known or unknown crystal polymorphs that could form [Powder]_.
Re-arranged:

Experimental structure refinement from powder diffraction is another example where more complex optimization is used.
Powder diffraction is a widely used method in drug discovery to assess purity of the material and discover known or unknown crystal polymorphs that could form [Powder]_.
In particular, fitting of the experimental powder diffraction intensity peaks to the indexed peaks (Pawley refinement) [Jansen]_.

2022-06-10 14:01 UTC, afonari commented on papers/alexandr_fonari/alexandr_fonari.rst
> +Element descriptors (such as atomic weight, number of valence electrons in s-, p- and d-shells, electronegativity), structure descriptors (such as density, volume per atom, and packing fraction descr
Went with bulleted list.

2022-06-10 14:01 UTC, afonari commented on papers/alexandr_fonari/alexandr_fonari.rst
> +Element descriptors (such as atomic weight, number of valence electrons in s-, p- and d-shells, electronegativity), structure descriptors (such as density, volume per atom, and packing fraction descr
> I believe it's common practice to italicize the letters s, p, d, f when referring to orbitals.

Fixed.

2022-06-10 14:07 UTC, afonari commented on papers/alexandr_fonari/alexandr_fonari.rst
> +In the Schrödinger suite, benchmark data for small molecules and finite systems can be obtained using QM DFT molecular Jaguar code, for periodic systems, QE used, for larger polymeric and similar sys
Thanks, fixed.

2022-06-10 14:16 UTC, afonari commented
Thanks a lot for the reviews! I'm going through them little by little.

2022-06-11 20:25 UTC, deniederhut commented
@scoobies mark pending comment

2022-06-13 12:14 UTC, afonari commented on papers/alexandr_fonari/alexandr_fonari.rst
> +There we used descriptors as implemented in rdkit to featurize the chemical structures.
Fixed and using RDKit everywhere.

2022-06-13 12:22 UTC, afonari commented on papers/alexandr_fonari/alexandr_fonari.rst
> +In this approach, machine learning and DFT are combined.
Added:

.. [Vasudevan] R. Vasudevan, et al., *Machine learning for materials design and discovery.*, Journal of Applied Physics 129(7): 070401 (2021).

.. [Schleder] G. R. Schleder, et al., *From DFT to machine learning: recent approaches to materials science–a review*, Journal of Physics: Materials 2(3): 032001 (2019).

Let me know if any other good ones. Resolving for now.

2022-06-13 12:23 UTC, afonari commented on papers/alexandr_fonari/alexandr_fonari.rst
> +Bayesian optimization is employed to tune the hyperparameters of the model.
Yes, someone with better English will hopefully join as a co-author, and fix these =)

Leaving unresolved for now.

2022-06-13 12:53 UTC, afonari commented on papers/alexandr_fonari/alexandr_fonari.rst
> +Recently, we implemented a workflow that employs active learning (AL) for intelligent and iterative identification of promising materials candidates within a large dataset [Abroshan]_.
Re-wrote this section. Properties that were evaluated are:

MPO score was computed based on two properties: hole reorganization energy and oxidation potential of the material.

2022-06-13 12:53 UTC, afonari commented on papers/alexandr_fonari/alexandr_fonari.rst
> +In this particular study, for a dataset of ~9,000 molecules, the AL workflow determined the top candidates for hole (positively charged carrier) transport layer  by evaluating 550 molecules in 10 ite
Fixed.

2022-06-13 12:58 UTC, afonari commented on papers/alexandr_fonari/alexandr_fonari.rst
> +In the Schrödinger suite this was implemented as a part of the EOS workflow, fitting is performed on the the results obtained from a series of QE calculations performed on the original and compressed
Fixed.

2022-06-13 13:04 UTC, afonari commented on papers/alexandr_fonari/alexandr_fonari.rst
> +As an example, organic light-emitting diodes (OLEDs) are fabricated using a stepwise process, where layers are deposited on top of previous layers.
Fixed.

2022-06-13 13:05 UTC, afonari commented on papers/alexandr_fonari/alexandr_fonari.rst
> +In order to train a model, benchmark data from calculations and/or experimental data is required.
Yes, replaced calculations with simulation.

2022-06-13 13:06 UTC, afonari commented on papers/alexandr_fonari/alexandr_fonari.rst
> +In order to be able to run a massively parallel screening of materials a highly scalable and stable queuing system (job scheduler) is required.
Thanks, fixed.

2022-06-13 13:08 UTC, afonari commented on papers/alexandr_fonari/alexandr_fonari.rst
> +The enumlib library implements algorithms for such a systematic enumeration of periodic structures [Enumlib]_.
Moved the reference. It is referencing:

.. [Enumlib] G. LW Hart, and R. W. Forcade. *Algorithm for generating derivative structures*, Physical Review B 77 (22): 224115 (2008). https://github.com/msg-byu/enumlib/

2022-06-13 13:19 UTC, afonari commented on papers/alexandr_fonari/alexandr_fonari.rst
> +We generated a set of stable doped Pt/transition metal/nitrogen surfaces using periodic enumeration.
Yes, moved existing reference up a bit:

.. [TM] T. Mustard, et al. *Surface reactivity and stability of core-shell solid catalysts from ab initio combinatorial calculations*, ABSTRACTS OF PAPERS OF THE AMERICAN CHEMICAL SOCIETY. 258. (2019).

2022-06-13 13:24 UTC, afonari commented on papers/alexandr_fonari/alexandr_fonari.rst
> +We hope that this report will inspire other scientific companies to give back to the open source community in order to improve the computational materials field and make science more reproducible.
We are trying to do our part and actually increase the amount of open source contributions. See for example: https://www.schrodinger.com/user-announcement/schrodinger-extends-materials-science-capabilities-through-integration-quantum

2022-06-13 21:55 UTC, afonari commented on papers/alexandr_fonari/alexandr_fonari.rst
> +.. figure:: fig_al.jpg
Figures is now much higher quality (300 DPI), in my tests it is zooming in nicely, resolving.

2022-06-13 22:13 UTC, afonari commented on papers/alexandr_fonari/alexandr_fonari.rst
> +Every step of this workflow can benefit from open source code.
Sure, added:

There are several of open source packages that allow to generate a large number of structures, run calculation in high throughput manner and analyze the results.
pymatgen allows to generate and analyze periodic structures [pymatgen]_.
It can generate inputs and read outputs of several packages, such as Quantum ESPRESSO (QE), VASP, Gaussian, etc.
To run and manage workflows' jobs in a high-throughput manner, open source packages such as Custodian [pymatgen]_ and AiiDA [aiida]_ can be used.

2022-06-14 00:44 UTC, deniederhut commented
@scoobies mark pending comment

2022-06-23 02:32 UTC, bdice commented
@afonari Hi! Looks like you're still iterating on things, but please let me know if/when you're ready for a second round of review! 👍

2022-06-23 12:28 UTC, afonari commented
> @afonari Hi! Looks like you're still iterating on things, but please let me know if/when you're ready for a second round of review! 👍

Sure, thanks.

@deniederhut I cannot build PDF anymore on the build server, can you please help (sorry if I broke it).

2022-06-23 13:21 UTC, wdzhou commented
> > @afonari Hi! Looks like you're still iterating on things, but please let me know if/when you're ready for a second round of review! +1
> 
> Sure, thanks.
> 
> @deniederhut I cannot build PDF anymore on the build server, can you please help (sorry if I broke it).

I read your current edition from https://github.com/afonari/scipy_proceedings/blob/2022-local/papers/alexandr_fonari/alexandr_fonari.rst.  It looks pretty good in terms of format.

2022-06-24 00:36 UTC, deniederhut commented
@scoobies build status

2022-06-24 00:36 UTC, scoobies commented
{"afonari-2022-local"=>{"data"=>{"build_output"=>"[*] Updating proceedings build tools in {self.master_repo_path}...\nAlready up to date.\n[*] Check out paper repository...\nCloning into '/tmp/tmp4fveag_s'...\nMoving proceedings build tools to temp directory...\n[*] Build the paper...\nBuilding: alexandr_fonari\n*** Warning: /tmp/tmp4fveag_s/publisher/../output/alexandr_fonari/paper_stats.json does not exist.\nPDFLaTeX error output:\n================================================================================\nThis is pdfTeX, Version 3.14159265-2.6-1.40.18 (TeX Live 2017/Debian) (preloaded format=pdflatex)\n restricted \\write18 enabled.\nentering extended mode\n(./paper.tex\nLaTeX2e <2017-04-15>\nBabel <3.18> and hyphenation patterns for 3 language(s) loaded.\n(./IEEEtran.cls\nDocument Class: IEEEtran 2015/08/26 V1.8b by Michael Shell\n-- See the \"IEEEtran_HOWTO\" manual for usage information.\n-- http://www.michaelshell.org/tex/ieeetran/\n(/usr/share/texlive/texmf-dist/tex/latex/psnfss/ot1ppl.fd)\n-- Using IEEE Computer Society mode.\n-- Using 8.5in x 11in (letter) paper.\n-- Using PDF output.\n-- This is a 10 point document.\n) (/usr/share/texlive/texmf-dist/tex/latex/cmap/cmap.sty)\n(/usr/share/texlive/texmf-dist/tex/latex/base/ifthen.sty)\n(/usr/share/texlive/texmf-dist/tex/latex/base/fontenc.sty\n(/usr/share/texlive/texmf-dist/tex/latex/base/t1enc.def)\n(/usr/share/texlive/texmf-dist/tex/latex/psnfss/t1ppl.fd)<<t1.cmap>>)\n(/usr/share/texlive/texmf-dist/tex/latex/base/inputenc.sty\n(/usr/share/texlive/texmf-dist/tex/latex/base/utf8.def\n(/usr/share/texlive/texmf-dist/tex/latex/base/t1enc.dfu)\n(/usr/share/texlive/texmf-dist/tex/latex/base/ot1enc.dfu)\n(/usr/share/texlive/texmf-dist/tex/latex/base/omsenc.dfu)))\n(/usr/share/texlive/texmf-dist/tex/latex/amsmath/amsmath.sty\nFor additional information on amsmath, use the `?' option.\n(/usr/share/texlive/texmf-dist/tex/latex/amsmath/amstext.sty\n(/usr/share/texlive/texmf-dist/tex/latex/amsmath/amsgen.sty))\n(/usr/share/texlive/texmf-dist/tex/latex/amsmath/amsbsy.sty)\n(/usr/share/texlive/texmf-dist/tex/latex/amsmath/amsopn.sty))\n(/usr/share/texlive/texmf-dist/tex/latex/caption/caption.sty\n(/usr/share/texlive/texmf-dist/tex/latex/caption/caption3.sty\n(/usr/share/texlive/texmf-dist/tex/latex/graphics/keyval.sty))\n\nPackage caption Warning: Unsupported document class (or package) detected,\n(caption)                usage of the caption package is not recommended.\nSee the caption package documentation for explanation.\n\n) (/usr/share/texlive/texmf-dist/tex/latex/float/float.sty) (./scipy.sty\n(./status.sty (./draftwatermark.sty (./everypage.sty)\n(/usr/share/texlive/texmf-dist/tex/latex/graphics/graphicx.sty\n(/usr/share/texlive/texmf-dist/tex/latex/graphics/graphics.sty\n(/usr/share/texlive/texmf-dist/tex/latex/graphics/trig.sty)\n(/usr/share/texlive/texmf-dist/tex/latex/graphics-cfg/graphics.cfg)\n(/usr/share/texlive/texmf-dist/tex/latex/graphics-def/pdftex.def)))\n(/usr/share/texlive/texmf-dist/tex/latex/graphics/color.sty\n(/usr/share/texlive/texmf-dist/tex/latex/graphics-cfg/color.cfg))))\n(/usr/share/texlive/texmf-dist/tex/latex/psnfss/mathptmx.sty)\n(/usr/share/texlive/texmf-dist/tex/latex/psnfss/helvet.sty)\n(/usr/share/texlive/texmf-dist/tex/latex/psnfss/courier.sty)\n(/usr/share/texlive/texmf-dist/tex/latex/amsfonts/amsfonts.sty)\n(/usr/share/texlive/texmf-dist/tex/latex/amsfonts/amssymb.sty)\n(/usr/share/texlive/texmf-dist/tex/latex/tools/bm.sty)\n(/usr/share/texlive/texmf-dist/tex/latex/hyperref/hyperref.sty\n(/usr/share/texlive/texmf-dist/tex/generic/oberdiek/hobsub-hyperref.sty\n(/usr/share/texlive/texmf-dist/tex/generic/oberdiek/hobsub-generic.sty))\n(/usr/share/texlive/texmf-dist/tex/generic/ifxetex/ifxetex.sty)\n(/usr/share/texlive/texmf-dist/tex/latex/oberdiek/auxhook.sty)\n(/usr/share/texlive/texmf-dist/tex/latex/oberdiek/kvoptions.sty)\n(/usr/share/texlive/texmf-dist/tex/latex/hyperref/pd1enc.def)\n(/usr/share/texlive/texmf-dist/tex/latex/latexconfig/hyperref.cfg)\n(/usr/share/texlive/texmf-dist/tex/latex/url/url.sty))\n(/usr/share/texlive/texmf-dist/tex/latex/hyperref/hpdftex.def\n(/usr/share/texlive/texmf-dist/tex/latex/oberdiek/rerunfilecheck.sty))\n\nPackage hyperref Warning: Option `pdftex' has already been used,\n(hyperref)                setting the option has no effect on input line 43.\n\n(/usr/share/texlive/texmf-dist/tex/latex/tools/longtable.sty)\n(/usr/share/texlive/texmf-dist/tex/latex/multirow/multirow.sty)\n(/usr/share/texlive/texmf-dist/tex/latex/booktabs/booktabs.sty)\n(/usr/share/texlive/texmf-dist/tex/latex/base/textcomp.sty\n(/usr/share/texlive/texmf-dist/tex/latex/base/ts1enc.def\n(/usr/share/texlive/texmf-dist/tex/latex/base/ts1enc.dfu)))\n(/usr/share/texlive/texmf-dist/tex/latex/upquote/upquote.sty)\n(/usr/share/texlive/texmf-dist/tex/latex/fancyvrb/fancyvrb.sty\nStyle option: `fancyvrb' v2.7a, with DG/SPQR fixes, and firstline=lastline fix \n<2008/02/07> (tvz)))\nNo file paper.aux.\n(/usr/share/texlive/texmf-dist/tex/latex/base/ts1cmr.fd)\n(/usr/share/texlive/texmf-dist/tex/latex/psnfss/t1ptm.fd)\n-- Lines per column: 61 (exact).\n(/usr/share/texlive/texmf-dist/tex/latex/caption/ltcaption.sty)\n(/usr/share/texlive/texmf-dist/tex/context/base/mkii/supp-pdf.mkii\n[Loading MPS to PDF converter (version 2006.09.02).]\n) (/usr/share/texlive/texmf-dist/tex/latex/oberdiek/epstopdf-base.sty\n(/usr/share/texlive/texmf-dist/tex/latex/oberdiek/grfext.sty)\n(/usr/share/texlive/texmf-dist/tex/latex/latexconfig/epstopdf-sys.cfg))\n(/usr/share/texlive/texmf-dist/tex/latex/hyperref/nameref.sty\n(/usr/share/texlive/texmf-dist/tex/generic/oberdiek/gettitlestring.sty))\n(/usr/share/texlive/texmf-dist/tex/latex/psnfss/t1phv.fd)\n(/usr/share/texlive/texmf-dist/tex/latex/psnfss/ot1ztmcm.fd)<<ot1.cmap>>\n(/usr/share/texlive/texmf-dist/tex/latex/psnfss/omlztmcm.fd)<<oml.cmap>>\n(/usr/share/texlive/texmf-dist/tex/latex/psnfss/omsztmcm.fd)<<oms.cmap>>\n(/usr/share/texlive/texmf-dist/tex/latex/psnfss/omxztmcm.fd)<<omx.cmap>>\n(/usr/share/texlive/texmf-dist/tex/latex/psnfss/ot1ptm.fd)\n(/usr/share/texlive/texmf-dist/tex/latex/psnfss/upzd.fd)\n(/usr/share/texlive/texmf-dist/tex/latex/psnfss/ts1ptm.fd) (./page_numbers.tex)\n\nUnderfull \\hbox (badness 2970) in paragraph at lines 157--159\n\\T1/phv/b/n/8.03 Abstract\\T1/phv/m/n/8.03 ---The use of sev-eral open source sc\ni-en-tific pack-ages in the\n\nLaTeX Warning: Reference `fig1' on page 1 undefined on input line 166.\n\n\nLaTeX Warning: No positions in optional float specifier.\n               Default added (so using `tbp') on input line 167.\n\n\nLaTeX Warning: Citation `Schr' on page 1 undefined on input line 175.\n\n\nLaTeX Warning: Citation `Jaguar' on page 1 undefined on input line 178.\n\n\nLaTeX Warning: Citation `QE' on page 1 undefined on input line 179.\n\n\nLaTeX Warning: Citation `Desmond' on page 1 undefined on input line 180.\n\n\nLaTeX Warning: Reference `fig2' on page 1 undefined on input line 182.\n\n\nLaTeX Warning: Citation `pymatgen' on page 1 undefined on input line 187.\n\n\nLaTeX Warning: Citation `pymatgen' on page 1 undefined on input line 189.\n\n\nLaTeX Warning: Citation `AiiDA' on page 1 undefined on input line 189.\n\n\nLaTeX Warning: No positions in optional float specifier.\n               Default added (so using `tbp') on input line 189.\n\n\nLaTeX Warning: Citation `Obabel' on page 1 undefined on input line 198.\n\n\nLaTeX Warning: Citation `RDKit' on page 1 undefined on input line 198.\n\n\nLaTeX Warning: Citation `Formats' on page 1 undefined on input line 199.\n\n\nLaTeX Warning: Citation `CSD' on page 1 undefined on input line 205.\n\n\nLaTeX Warning: Citation `Grph' on page 1 undefined on input line 205.\n\n[1{/var/lib/texmf/fonts/map/pdftex/updmap/pdftex.map}]\n\nLaTeX Warning: Citation `Enumlib' on page 2 undefined on input line 215.\n\n\nLaTeX Warning: Citation `TM' on page 2 undefined on input line 218.\n\n\nUnderfull \\vbox (badness 10000) has occurred while \\output is active\n\ [...]

2022-06-24 00:39 UTC, deniederhut commented on papers/alexandr_fonari/alexandr_fonari.rst
> +Obtained calculated yield of 10% *vs.* experimental value within 9-18% range (Figure :ref:`fig_stress_strain`) [Convex]_.
```suggestion
Obtained calculated yield of 10% *vs.* experimental value within 9-18% range (Figure :ref:`fig_stress_strain` ) [Convex]_.
```

2022-06-24 00:39 UTC, deniederhut commented on papers/alexandr_fonari/alexandr_fonari.rst
> +Obtained calculated yield of 10% *vs.* experimental value within 9-18% range (Figure :ref:`fig_stress_strain`) [Convex]_.
rst can be pretty fussy about whitespace 😞

2022-06-24 00:40 UTC, deniederhut commented
> (sorry if I broke it)

Haha nothing broken -- no need to worry! Just a little syntax issue.

2022-06-24 13:17 UTC, afonari commented on papers/alexandr_fonari/alexandr_fonari.rst
> +Obtained calculated yield of 10% *vs.* experimental value within 9-18% range (Figure :ref:`fig_stress_strain`) [Convex]_.
Great, thanks!

2022-06-24 13:36 UTC, afonari commented on papers/alexandr_fonari/alexandr_fonari.rst
> +Tools for computational materials discovery can be facilitated by utilizing existing libraries that cover the fundamental mathematics used in the calculations in an optimized fashion.
Yes, expanded the introduction added couple of figures.

2022-06-24 13:44 UTC, afonari commented on papers/alexandr_fonari/alexandr_fonari.rst
> +Bayesian optimization is employed to tune the hyperparameters of the model.
English was reviewed and fixed in many places.

2022-06-24 15:24 UTC, afonari commented on papers/alexandr_fonari/alexandr_fonari.rst
> +We present several examples of how Schrödinger Materials Suite incorporates open source software packages.
> I am unsure exactly what this sentence is intending to mean. Is "incorporates" the right word? Or is it more accurate to describe this as an integration with the SciPy ecosystem, through common data structures (e.g. NumPy arrays)?

Added a short description of the structure object to the Materials import and generation section:

From file, structure is read in a structure object through which atomic coordinates (as a NumPy array) and chemical information of the material can be accessed and updated.
Structure object is similar to the one implemented in open source packages such as pymatgen [pymatgen]_ and ASE [ase]_.
All the structure manipulations during the workflows are done using structure object interface.

> More generally, I don't fully understand what the Schrödinger software does after reading this paper. It sounds like scientists are leveraging open source software as a part of their discovery/exploration of materials design spaces but I am having trouble identifying the boundary/interface where (proprietary?) Schrodinger software begins and open source software from the SciPy ecosystem ends. I was hoping to get more clarity on this while reading through the paper, but I didn't find what I was looking for.

Introduction and workflows examples were expanded with figures and text.

> After a bit of reading and internet searches beyond this paper, it seems that Jaguar and Desmond are proprietary commercial simulation codes developed by Schrodinger (or developed by DE Shaw Research? Unclear from a quick glance) and Quantum Espresso is an open source simulation engine (GPLv2). I have a few questions that may help to provide clarity about the primary topics mentioned in this paper's title.

Yes, when introducing each package added if it is open source or proprietary and if it has python bindings.

> Do all the codes mentioned above have Python bindings?

Added if python bindings are present or not for each open source package.

> Are those Python APIs provided by the "Schrödinger Materials Suite" in some unified manner, or are the Python bindings provided by each package (and thus probably feel different from one another)?
> How similar or different are the Python APIs for the various workflows / use cases described in this paper? Code snippets or documentation references would be very helpful.

Expanded on general workflow flow:

As can be seen from above a workflow is usually some sort of structure modification through the structure object with a subsequent call to a backend code and analysis of its output (input for the next iteration depends on the output of the previous iteration is some workflows) after it successful (or not) exit.
Due to the large chemical and manipulation space of the materials, sometimes it very tricky to keep code for all workflows follow the same code logic.

Also provided a snippet for structure deformation using pymatgen (I can't provide snippet using Schrodinger API):

An example of deformation applied to a structure in pymatgen:

.. code-block:: python

   deform = Deformation([[1.0, 0.02, 0.02], [0.0, 1.0, 0.0], [0.0, 0.0, 1.0]])
   lattice = Lattice([
      [3.8401979337, 0.00, 0.00],
      [1.9200989668, 3.3257101909, 0.00],
      [0.00, -2.2171384943, 3.1355090603],
   ])
   structure = Structure(lattice, ["Si", "Si"], [[0, 0, 0], [0.75, 0.5, 0.75]])

   strained_structure = deform.apply_to_structure(structure)

> Do these codes use standard data structures like NumPy arrays to transfer information to other packages in the SciPy ecosystem, or do users need to save/load/parse files to share data between packages?

Added description of the structure object and pymatgen structure snippet.

> Do users of "Schrödinger Materials Suite" have access to open source code examples in the documentation or an examples repository that demonstrate interactions with the SciPy ecosystem?

There is internal documentation that is only available for exisiting customers. Not sure if it is worth mentioning in the paper.

> Are codes publicly available for replicating any of the studies described in this paper?

No, but we publish algorithms that were used/implemented, added:

For every workflow and/or functionality, some sort of peer reviewed material (publication, conference presentation) is created where implemented algorithms are described to facilitate reproducibility.

> Is the API of the "Schrödinger Materials Suite" designed to align with common API paradigms of packages like NumPy/SciPy/scikit-learn? What does the API look and feel like? Is it functional? Object oriented? Client/server?

A little bit of this is in the structure object description (see above). Also added a code snippet for pymatgen structure object.

> Where can users find basic information and documentation on the "Schrödinger Materials Suite"? There should be links to these resources in the text or footnotes of the first page of the paper.

Added link to the website to ref 1.

Resolving this for now.

2022-06-24 15:28 UTC, afonari commented
@scoobies build status

2022-06-24 15:28 UTC, scoobies commented
{"afonari-2022-local"=>{"data"=>{"build_output"=>"[*] Updating proceedings build tools in {self.master_repo_path}...\nAlready up to date.\n[*] Check out paper repository...\nCloning into '/tmp/tmpo7siw8qg'...\nMoving proceedings build tools to temp directory...\n[*] Build the paper...\n<string>:71: (ERROR/3) Unknown target name: \"qeschema\".\nBuilding: alexandr_fonari\nTraceback (most recent call last):\n  File \"publisher/build_paper.py\", line 237, in <module>\n    build_paper(paper_id)\n  File \"publisher/build_paper.py\", line 222, in build_paper\n    rst2tex(in_path, out_path)\n  File \"publisher/build_paper.py\", line 92, in rst2tex\n    settings_overrides=settings)\n  File \"/procbuild_env/lib/python3.6/site-packages/docutils/core.py\", line 416, in publish_string\n    enable_exit_status=enable_exit_status)\n  File \"/procbuild_env/lib/python3.6/site-packages/docutils/core.py\", line 664, in publish_programmatically\n    output = pub.publish(enable_exit_status=enable_exit_status)\n  File \"/procbuild_env/lib/python3.6/site-packages/docutils/core.py\", line 218, in publish\n    self.apply_transforms()\n  File \"/procbuild_env/lib/python3.6/site-packages/docutils/core.py\", line 199, in apply_transforms\n    self.document.transformer.apply_transforms()\n  File \"/procbuild_env/lib/python3.6/site-packages/docutils/transforms/__init__.py\", line 171, in apply_transforms\n    transform.apply(**kwargs)\n  File \"/procbuild_env/lib/python3.6/site-packages/docutils/transforms/references.py\", line 846, in apply\n    self.document.walk(visitor)\n  File \"/procbuild_env/lib/python3.6/site-packages/docutils/nodes.py\", line 138, in walk\n    if child.walk(visitor):\n  File \"/procbuild_env/lib/python3.6/site-packages/docutils/nodes.py\", line 138, in walk\n    if child.walk(visitor):\n  File \"/procbuild_env/lib/python3.6/site-packages/docutils/nodes.py\", line 138, in walk\n    if child.walk(visitor):\n  [Previous line repeated 1 more time]\n  File \"/procbuild_env/lib/python3.6/site-packages/docutils/nodes.py\", line 130, in walk\n    visitor.dispatch_visit(self)\n  File \"/procbuild_env/lib/python3.6/site-packages/docutils/nodes.py\", line 1882, in dispatch_visit\n    return method(node)\n  File \"/procbuild_env/lib/python3.6/site-packages/docutils/transforms/references.py\", line 897, in visit_reference\n    base_node=node)\n  File \"/procbuild_env/lib/python3.6/site-packages/docutils/utils/__init__.py\", line 228, in error\n    return self.system_message(self.ERROR_LEVEL, *args, **kwargs)\n  File \"/procbuild_env/lib/python3.6/site-packages/docutils/utils/__init__.py\", line 194, in system_message\n    raise SystemMessage(msg, level)\ndocutils.utils.SystemMessage: <string>:71: (ERROR/3) Unknown target name: \"qeschema\".\nError building paper /tmp/tmpo7siw8qg/papers/alexandr_fonari. Aborting.\n[X] Error code 1\nA build error occurred during the self.run_make_paper_script step.", "build_pdf_path"=>"", "build_status"=>"Build failed, make_paper.sh did not succeed", "build_timestamp"=>"24/06 15:26"}, "status"=>"fail"}}

2022-06-24 15:29 UTC, afonari commented
@scoobies build status

2022-06-24 15:29 UTC, scoobies commented
{"afonari-2022-local"=>{"data"=>{"build_output"=>"[*] Updating proceedings build tools in {self.master_repo_path}...\nAlready up to date.\n[*] Check out paper repository...\nCloning into '/tmp/tmpsf1y9gtn'...\nMoving proceedings build tools to temp directory...\n[*] Build the paper...\n<string>:71: (ERROR/3) Unknown target name: \"qeschema\".\nBuilding: alexandr_fonari\nTraceback (most recent call last):\n  File \"publisher/build_paper.py\", line 237, in <module>\n    build_paper(paper_id)\n  File \"publisher/build_paper.py\", line 222, in build_paper\n    rst2tex(in_path, out_path)\n  File \"publisher/build_paper.py\", line 92, in rst2tex\n    settings_overrides=settings)\n  File \"/procbuild_env/lib/python3.6/site-packages/docutils/core.py\", line 416, in publish_string\n    enable_exit_status=enable_exit_status)\n  File \"/procbuild_env/lib/python3.6/site-packages/docutils/core.py\", line 664, in publish_programmatically\n    output = pub.publish(enable_exit_status=enable_exit_status)\n  File \"/procbuild_env/lib/python3.6/site-packages/docutils/core.py\", line 218, in publish\n    self.apply_transforms()\n  File \"/procbuild_env/lib/python3.6/site-packages/docutils/core.py\", line 199, in apply_transforms\n    self.document.transformer.apply_transforms()\n  File \"/procbuild_env/lib/python3.6/site-packages/docutils/transforms/__init__.py\", line 171, in apply_transforms\n    transform.apply(**kwargs)\n  File \"/procbuild_env/lib/python3.6/site-packages/docutils/transforms/references.py\", line 846, in apply\n    self.document.walk(visitor)\n  File \"/procbuild_env/lib/python3.6/site-packages/docutils/nodes.py\", line 138, in walk\n    if child.walk(visitor):\n  File \"/procbuild_env/lib/python3.6/site-packages/docutils/nodes.py\", line 138, in walk\n    if child.walk(visitor):\n  File \"/procbuild_env/lib/python3.6/site-packages/docutils/nodes.py\", line 138, in walk\n    if child.walk(visitor):\n  [Previous line repeated 1 more time]\n  File \"/procbuild_env/lib/python3.6/site-packages/docutils/nodes.py\", line 130, in walk\n    visitor.dispatch_visit(self)\n  File \"/procbuild_env/lib/python3.6/site-packages/docutils/nodes.py\", line 1882, in dispatch_visit\n    return method(node)\n  File \"/procbuild_env/lib/python3.6/site-packages/docutils/transforms/references.py\", line 897, in visit_reference\n    base_node=node)\n  File \"/procbuild_env/lib/python3.6/site-packages/docutils/utils/__init__.py\", line 228, in error\n    return self.system_message(self.ERROR_LEVEL, *args, **kwargs)\n  File \"/procbuild_env/lib/python3.6/site-packages/docutils/utils/__init__.py\", line 194, in system_message\n    raise SystemMessage(msg, level)\ndocutils.utils.SystemMessage: <string>:71: (ERROR/3) Unknown target name: \"qeschema\".\nError building paper /tmp/tmpsf1y9gtn/papers/alexandr_fonari. Aborting.\n[X] Error code 1\nA build error occurred during the self.run_make_paper_script step.", "build_pdf_path"=>"", "build_status"=>"Build failed, make_paper.sh did not succeed", "build_timestamp"=>"24/06 15:29"}, "status"=>"fail"}}

2022-06-25 12:24 UTC, afonari commented on papers/alexandr_fonari/alexandr_fonari.rst
> +Using these descriptors and kernel regression methods to train the model, as implemented in scikit-learn [SkLearn]_, we were able to train a model that successfully predicted bulk modulus of a set of
I rushed a bit, I'm referring to an unfinished paper in this section. All valid questions. Replaced with:

We are currently training models that use these descriptors to predict properties, such as bulk modulus, of a set of Li-containing battery related compounds [Chandrasekaran]_.
Several methods to generate model will be compared, such as kernel regression methods (as implemented in the open source scikit-learn code [SkLearn]_) and AutoQSAR.

2022-06-25 12:40 UTC, afonari commented on papers/alexandr_fonari/alexandr_fonari.rst
> +Performing DFT calculations for all of the 9,000 molecules in the dataset would increase the computational cost by a factor of 15 versus the AL workflow.
> Was the full dataset of 9000 molecules computed, to validate that the active learning algorithms didn't reject any samples that were in fact good candidates?

Confirmed with the authors that model was validated, added:

Resulting model was validated by randomly picking a molecule from the dataset, computing properties with DFT and comparing those to the predicted values.

>  More broadly, it would be helpful to discuss lessons learned from this experiment. What struggles were faced? From what you discovered (or from other research you cite), what classes of problems in materials engineering would you say are a good / bad fit for active learning?

We really have only one data point for now, added:

It seems that AL approach can be useful in the cases where problem space is broad (like chemical space), but there are many clusters of similar items (similar molecules).
In this case, benchmark data is only needed for few representatives of each cluster.
We are currently working on applying this approach to train models for predicting physical properties of soft materials (polymers).

2022-06-25 13:06 UTC, afonari commented on papers/alexandr_fonari/alexandr_fonari.rst
> +These descriptors generated on the initial subset of structures are given as vectors to an algorithm based on Random Forest as implemented in scikit-learn.
> Was this a random forest classifier or a random forest regressor?

Good point, it was Random Forest Regressor, mentioned in the paper added a ref with the direct link to SK RFR docs.

> Give more details about the model and optimization strategies. Consider a code snippet or figure that demonstrates the results.

Added a figure with explanations:

Figure :ref:`figalplot` (A) displays MPO scores for the HTL dataset estimated by AL as a function of hole reorganization energies that are separately calculated for all the materials.
This figure indicates that there are many materials in the dataset with desired low hole reorganization energies but are not suitable for HTL due to their improper oxidation potentials, suggesting that MPO is important to evaluate the optoelectronic performance of the materials.
Figure :ref:`figalplot` (B) presents MPO scores of the materials used in the training dataset of AL, demonstrating that the feedback loop in the AL workflow efficiently guides the data collection as the size of the training set increases.

2022-06-25 13:07 UTC, afonari commented
@scoobies build status

2022-06-25 13:07 UTC, scoobies commented
{"afonari-2022-local"=>{"data"=>{"build_output"=>"[*] Updating proceedings build tools in {self.master_repo_path}...\nAlready up to date.\n[*] Check out paper repository...\nCloning into '/tmp/tmpp_hk8ntq'...\nMoving proceedings build tools to temp directory...\n[*] Build the paper...\n<string>:293: (ERROR/3) Figure caption must be a paragraph or empty comment.\n\n.. figure:: fig_al_plot.png\n   :align: center\n   :figclass: w\n\n   (A) MPO score of all materials in the HTL dataset and (B) those used in the training set as a function of the hole reorganization energy (:math:`\\lambda_h`). Active learning workflow for the design and discovery of novel optoelectronics molecules. :label:`figalplot`\n\nBuilding: alexandr_fonari\nTraceback (most recent call last):\n  File \"publisher/build_paper.py\", line 237, in <module>\n    build_paper(paper_id)\n  File \"publisher/build_paper.py\", line 222, in build_paper\n    rst2tex(in_path, out_path)\n  File \"publisher/build_paper.py\", line 92, in rst2tex\n    settings_overrides=settings)\n  File \"/procbuild_env/lib/python3.6/site-packages/docutils/core.py\", line 416, in publish_string\n    enable_exit_status=enable_exit_status)\n  File \"/procbuild_env/lib/python3.6/site-packages/docutils/core.py\", line 664, in publish_programmatically\n    output = pub.publish(enable_exit_status=enable_exit_status)\n  File \"/procbuild_env/lib/python3.6/site-packages/docutils/core.py\", line 217, in publish\n    self.settings)\n  File \"/procbuild_env/lib/python3.6/site-packages/docutils/readers/__init__.py\", line 72, in read\n    self.parse()\n  File \"/procbuild_env/lib/python3.6/site-packages/docutils/readers/__init__.py\", line 78, in parse\n    self.parser.parse(self.input, document)\n  File \"/procbuild_env/lib/python3.6/site-packages/docutils/parsers/rst/__init__.py\", line 191, in parse\n    self.statemachine.run(inputlines, document, inliner=self.inliner)\n  File \"/procbuild_env/lib/python3.6/site-packages/docutils/parsers/rst/states.py\", line 171, in run\n    input_source=document['source'])\n  File \"/procbuild_env/lib/python3.6/site-packages/docutils/statemachine.py\", line 239, in run\n    context, state, transitions)\n  File \"/procbuild_env/lib/python3.6/site-packages/docutils/statemachine.py\", line 460, in check_line\n    return method(match, context, next_state)\n  File \"/procbuild_env/lib/python3.6/site-packages/docutils/parsers/rst/states.py\", line 2988, in text\n    self.section(title.lstrip(), source, style, lineno + 1, messages)\n  File \"/procbuild_env/lib/python3.6/site-packages/docutils/parsers/rst/states.py\", line 327, in section\n    self.new_subsection(title, lineno, messages)\n  File \"/procbuild_env/lib/python3.6/site-packages/docutils/parsers/rst/states.py\", line 395, in new_subsection\n    node=section_node, match_titles=True)\n  File \"/procbuild_env/lib/python3.6/site-packages/docutils/parsers/rst/states.py\", line 282, in nested_parse\n    node=node, match_titles=match_titles)\n  File \"/procbuild_env/lib/python3.6/site-packages/docutils/parsers/rst/states.py\", line 196, in run\n    results = StateMachineWS.run(self, input_lines, input_offset)\n  File \"/procbuild_env/lib/python3.6/site-packages/docutils/statemachine.py\", line 239, in run\n    context, state, transitions)\n  File \"/procbuild_env/lib/python3.6/site-packages/docutils/statemachine.py\", line 460, in check_line\n    return method(match, context, next_state)\n  File \"/procbuild_env/lib/python3.6/site-packages/docutils/parsers/rst/states.py\", line 2753, in underline\n    self.section(title, source, style, lineno - 1, messages)\n  File \"/procbuild_env/lib/python3.6/site-packages/docutils/parsers/rst/states.py\", line 327, in section\n    self.new_subsection(title, lineno, messages)\n  File \"/procbuild_env/lib/python3.6/site-packages/docutils/parsers/rst/states.py\", line 395, in new_subsection\n    node=section_node, match_titles=True)\n  File \"/procbuild_env/lib/python3.6/site-packages/docutils/parsers/rst/states.py\", line 282, in nested_parse\n    node=node, match_titles=match_titles)\n  File \"/procbuild_env/lib/python3.6/site-packages/docutils/parsers/rst/states.py\", line 196, in run\n    results = StateMachineWS.run(self, input_lines, input_offset)\n  File \"/procbuild_env/lib/python3.6/site-packages/docutils/statemachine.py\", line 239, in run\n    context, state, transitions)\n  File \"/procbuild_env/lib/python3.6/site-packages/docutils/statemachine.py\", line 460, in check_line\n    return method(match, context, next_state)\n  File \"/procbuild_env/lib/python3.6/site-packages/docutils/parsers/rst/states.py\", line 2326, in explicit_markup\n    nodelist, blank_finish = self.explicit_construct(match)\n  File \"/procbuild_env/lib/python3.6/site-packages/docutils/parsers/rst/states.py\", line 2338, in explicit_construct\n    return method(self, expmatch)\n  File \"/procbuild_env/lib/python3.6/site-packages/docutils/parsers/rst/states.py\", line 2081, in directive\n    directive_class, match, type_name, option_presets)\n  File \"/procbuild_env/lib/python3.6/site-packages/docutils/parsers/rst/states.py\", line 2130, in run_directive\n    result = directive_instance.run()\n  File \"/procbuild_env/lib/python3.6/site-packages/docutils/parsers/rst/directives/images.py\", line 160, in run\n    line=self.lineno)\n  File \"/procbuild_env/lib/python3.6/site-packages/docutils/utils/__init__.py\", line 228, in error\n    return self.system_message(self.ERROR_LEVEL, *args, **kwargs)\n  File \"/procbuild_env/lib/python3.6/site-packages/docutils/utils/__init__.py\", line 194, in system_message\n    raise SystemMessage(msg, level)\ndocutils.utils.SystemMessage: <string>:293: (ERROR/3) Figure caption must be a paragraph or empty comment.\n\n.. figure:: fig_al_plot.png\n   :align: center\n   :figclass: w\n\n   (A) MPO score of all materials in the HTL dataset and (B) those used in the training set as a function of the hole reorganization energy (:math:`\\lambda_h`). Active learning workflow for the design and discovery of novel optoelectronics molecules. :label:`figalplot`\n\nError building paper /tmp/tmpp_hk8ntq/papers/alexandr_fonari. Aborting.\n[X] Error code 1\nA build error occurred during the self.run_make_paper_script step.", "build_pdf_path"=>"", "build_status"=>"Build failed, make_paper.sh did not succeed", "build_timestamp"=>"25/06 13:07"}, "status"=>"fail"}}

2022-06-25 13:09 UTC, afonari commented
@scoobies build status

2022-06-25 13:09 UTC, scoobies commented
{"afonari-2022-local"=>{"data"=>{"build_output"=>"[*] Updating proceedings build tools in {self.master_repo_path}...\nAlready up to date.\n[*] Check out paper repository...\nCloning into '/tmp/tmpp_hk8ntq'...\nMoving proceedings build tools to temp directory...\n[*] Build the paper...\n<string>:293: (ERROR/3) Figure caption must be a paragraph or empty comment.\n\n.. figure:: fig_al_plot.png\n   :align: center\n   :figclass: w\n\n   (A) MPO score of all materials in the HTL dataset and (B) those used in the training set as a function of the hole reorganization energy (:math:`\\lambda_h`). Active learning workflow for the design and discovery of novel optoelectronics molecules. :label:`figalplot`\n\nBuilding: alexandr_fonari\nTraceback (most recent call last):\n  File \"publisher/build_paper.py\", line 237, in <module>\n    build_paper(paper_id)\n  File \"publisher/build_paper.py\", line 222, in build_paper\n    rst2tex(in_path, out_path)\n  File \"publisher/build_paper.py\", line 92, in rst2tex\n    settings_overrides=settings)\n  File \"/procbuild_env/lib/python3.6/site-packages/docutils/core.py\", line 416, in publish_string\n    enable_exit_status=enable_exit_status)\n  File \"/procbuild_env/lib/python3.6/site-packages/docutils/core.py\", line 664, in publish_programmatically\n    output = pub.publish(enable_exit_status=enable_exit_status)\n  File \"/procbuild_env/lib/python3.6/site-packages/docutils/core.py\", line 217, in publish\n    self.settings)\n  File \"/procbuild_env/lib/python3.6/site-packages/docutils/readers/__init__.py\", line 72, in read\n    self.parse()\n  File \"/procbuild_env/lib/python3.6/site-packages/docutils/readers/__init__.py\", line 78, in parse\n    self.parser.parse(self.input, document)\n  File \"/procbuild_env/lib/python3.6/site-packages/docutils/parsers/rst/__init__.py\", line 191, in parse\n    self.statemachine.run(inputlines, document, inliner=self.inliner)\n  File \"/procbuild_env/lib/python3.6/site-packages/docutils/parsers/rst/states.py\", line 171, in run\n    input_source=document['source'])\n  File \"/procbuild_env/lib/python3.6/site-packages/docutils/statemachine.py\", line 239, in run\n    context, state, transitions)\n  File \"/procbuild_env/lib/python3.6/site-packages/docutils/statemachine.py\", line 460, in check_line\n    return method(match, context, next_state)\n  File \"/procbuild_env/lib/python3.6/site-packages/docutils/parsers/rst/states.py\", line 2988, in text\n    self.section(title.lstrip(), source, style, lineno + 1, messages)\n  File \"/procbuild_env/lib/python3.6/site-packages/docutils/parsers/rst/states.py\", line 327, in section\n    self.new_subsection(title, lineno, messages)\n  File \"/procbuild_env/lib/python3.6/site-packages/docutils/parsers/rst/states.py\", line 395, in new_subsection\n    node=section_node, match_titles=True)\n  File \"/procbuild_env/lib/python3.6/site-packages/docutils/parsers/rst/states.py\", line 282, in nested_parse\n    node=node, match_titles=match_titles)\n  File \"/procbuild_env/lib/python3.6/site-packages/docutils/parsers/rst/states.py\", line 196, in run\n    results = StateMachineWS.run(self, input_lines, input_offset)\n  File \"/procbuild_env/lib/python3.6/site-packages/docutils/statemachine.py\", line 239, in run\n    context, state, transitions)\n  File \"/procbuild_env/lib/python3.6/site-packages/docutils/statemachine.py\", line 460, in check_line\n    return method(match, context, next_state)\n  File \"/procbuild_env/lib/python3.6/site-packages/docutils/parsers/rst/states.py\", line 2753, in underline\n    self.section(title, source, style, lineno - 1, messages)\n  File \"/procbuild_env/lib/python3.6/site-packages/docutils/parsers/rst/states.py\", line 327, in section\n    self.new_subsection(title, lineno, messages)\n  File \"/procbuild_env/lib/python3.6/site-packages/docutils/parsers/rst/states.py\", line 395, in new_subsection\n    node=section_node, match_titles=True)\n  File \"/procbuild_env/lib/python3.6/site-packages/docutils/parsers/rst/states.py\", line 282, in nested_parse\n    node=node, match_titles=match_titles)\n  File \"/procbuild_env/lib/python3.6/site-packages/docutils/parsers/rst/states.py\", line 196, in run\n    results = StateMachineWS.run(self, input_lines, input_offset)\n  File \"/procbuild_env/lib/python3.6/site-packages/docutils/statemachine.py\", line 239, in run\n    context, state, transitions)\n  File \"/procbuild_env/lib/python3.6/site-packages/docutils/statemachine.py\", line 460, in check_line\n    return method(match, context, next_state)\n  File \"/procbuild_env/lib/python3.6/site-packages/docutils/parsers/rst/states.py\", line 2326, in explicit_markup\n    nodelist, blank_finish = self.explicit_construct(match)\n  File \"/procbuild_env/lib/python3.6/site-packages/docutils/parsers/rst/states.py\", line 2338, in explicit_construct\n    return method(self, expmatch)\n  File \"/procbuild_env/lib/python3.6/site-packages/docutils/parsers/rst/states.py\", line 2081, in directive\n    directive_class, match, type_name, option_presets)\n  File \"/procbuild_env/lib/python3.6/site-packages/docutils/parsers/rst/states.py\", line 2130, in run_directive\n    result = directive_instance.run()\n  File \"/procbuild_env/lib/python3.6/site-packages/docutils/parsers/rst/directives/images.py\", line 160, in run\n    line=self.lineno)\n  File \"/procbuild_env/lib/python3.6/site-packages/docutils/utils/__init__.py\", line 228, in error\n    return self.system_message(self.ERROR_LEVEL, *args, **kwargs)\n  File \"/procbuild_env/lib/python3.6/site-packages/docutils/utils/__init__.py\", line 194, in system_message\n    raise SystemMessage(msg, level)\ndocutils.utils.SystemMessage: <string>:293: (ERROR/3) Figure caption must be a paragraph or empty comment.\n\n.. figure:: fig_al_plot.png\n   :align: center\n   :figclass: w\n\n   (A) MPO score of all materials in the HTL dataset and (B) those used in the training set as a function of the hole reorganization energy (:math:`\\lambda_h`). Active learning workflow for the design and discovery of novel optoelectronics molecules. :label:`figalplot`\n\nError building paper /tmp/tmpp_hk8ntq/papers/alexandr_fonari. Aborting.\n[X] Error code 1\nA build error occurred during the self.run_make_paper_script step.", "build_pdf_path"=>"", "build_status"=>"Build failed, make_paper.sh did not succeed", "build_timestamp"=>"25/06 13:07"}, "status"=>"fail"}}

2022-06-25 13:10 UTC, afonari commented
@scoobies build status

2022-06-25 13:10 UTC, scoobies commented
{"afonari-2022-local"=>{"data"=>{"build_output"=>"[*] Updating proceedings build tools in {self.master_repo_path}...\nAlready up to date.\n[*] Check out paper repository...\nCloning into '/tmp/tmp84g0jw5s'...\nMoving proceedings build tools to temp directory...\n[*] Build the paper...\n<string>:293: (ERROR/3) Figure caption must be a paragraph or empty comment.\n\n.. figure:: fig_al_plot.png\n   :align: center\n   :figclass: w\n\n   (A) MPO score of all materials in the HTL dataset and (B) those used in the training set as a function of the hole reorganization energy (:math:`\\lambda_h`). :label:`figalplot`\n\nBuilding: alexandr_fonari\nTraceback (most recent call last):\n  File \"publisher/build_paper.py\", line 237, in <module>\n    build_paper(paper_id)\n  File \"publisher/build_paper.py\", line 222, in build_paper\n    rst2tex(in_path, out_path)\n  File \"publisher/build_paper.py\", line 92, in rst2tex\n    settings_overrides=settings)\n  File \"/procbuild_env/lib/python3.6/site-packages/docutils/core.py\", line 416, in publish_string\n    enable_exit_status=enable_exit_status)\n  File \"/procbuild_env/lib/python3.6/site-packages/docutils/core.py\", line 664, in publish_programmatically\n    output = pub.publish(enable_exit_status=enable_exit_status)\n  File \"/procbuild_env/lib/python3.6/site-packages/docutils/core.py\", line 217, in publish\n    self.settings)\n  File \"/procbuild_env/lib/python3.6/site-packages/docutils/readers/__init__.py\", line 72, in read\n    self.parse()\n  File \"/procbuild_env/lib/python3.6/site-packages/docutils/readers/__init__.py\", line 78, in parse\n    self.parser.parse(self.input, document)\n  File \"/procbuild_env/lib/python3.6/site-packages/docutils/parsers/rst/__init__.py\", line 191, in parse\n    self.statemachine.run(inputlines, document, inliner=self.inliner)\n  File \"/procbuild_env/lib/python3.6/site-packages/docutils/parsers/rst/states.py\", line 171, in run\n    input_source=document['source'])\n  File \"/procbuild_env/lib/python3.6/site-packages/docutils/statemachine.py\", line 239, in run\n    context, state, transitions)\n  File \"/procbuild_env/lib/python3.6/site-packages/docutils/statemachine.py\", line 460, in check_line\n    return method(match, context, next_state)\n  File \"/procbuild_env/lib/python3.6/site-packages/docutils/parsers/rst/states.py\", line 2988, in text\n    self.section(title.lstrip(), source, style, lineno + 1, messages)\n  File \"/procbuild_env/lib/python3.6/site-packages/docutils/parsers/rst/states.py\", line 327, in section\n    self.new_subsection(title, lineno, messages)\n  File \"/procbuild_env/lib/python3.6/site-packages/docutils/parsers/rst/states.py\", line 395, in new_subsection\n    node=section_node, match_titles=True)\n  File \"/procbuild_env/lib/python3.6/site-packages/docutils/parsers/rst/states.py\", line 282, in nested_parse\n    node=node, match_titles=match_titles)\n  File \"/procbuild_env/lib/python3.6/site-packages/docutils/parsers/rst/states.py\", line 196, in run\n    results = StateMachineWS.run(self, input_lines, input_offset)\n  File \"/procbuild_env/lib/python3.6/site-packages/docutils/statemachine.py\", line 239, in run\n    context, state, transitions)\n  File \"/procbuild_env/lib/python3.6/site-packages/docutils/statemachine.py\", line 460, in check_line\n    return method(match, context, next_state)\n  File \"/procbuild_env/lib/python3.6/site-packages/docutils/parsers/rst/states.py\", line 2753, in underline\n    self.section(title, source, style, lineno - 1, messages)\n  File \"/procbuild_env/lib/python3.6/site-packages/docutils/parsers/rst/states.py\", line 327, in section\n    self.new_subsection(title, lineno, messages)\n  File \"/procbuild_env/lib/python3.6/site-packages/docutils/parsers/rst/states.py\", line 395, in new_subsection\n    node=section_node, match_titles=True)\n  File \"/procbuild_env/lib/python3.6/site-packages/docutils/parsers/rst/states.py\", line 282, in nested_parse\n    node=node, match_titles=match_titles)\n  File \"/procbuild_env/lib/python3.6/site-packages/docutils/parsers/rst/states.py\", line 196, in run\n    results = StateMachineWS.run(self, input_lines, input_offset)\n  File \"/procbuild_env/lib/python3.6/site-packages/docutils/statemachine.py\", line 239, in run\n    context, state, transitions)\n  File \"/procbuild_env/lib/python3.6/site-packages/docutils/statemachine.py\", line 460, in check_line\n    return method(match, context, next_state)\n  File \"/procbuild_env/lib/python3.6/site-packages/docutils/parsers/rst/states.py\", line 2326, in explicit_markup\n    nodelist, blank_finish = self.explicit_construct(match)\n  File \"/procbuild_env/lib/python3.6/site-packages/docutils/parsers/rst/states.py\", line 2338, in explicit_construct\n    return method(self, expmatch)\n  File \"/procbuild_env/lib/python3.6/site-packages/docutils/parsers/rst/states.py\", line 2081, in directive\n    directive_class, match, type_name, option_presets)\n  File \"/procbuild_env/lib/python3.6/site-packages/docutils/parsers/rst/states.py\", line 2130, in run_directive\n    result = directive_instance.run()\n  File \"/procbuild_env/lib/python3.6/site-packages/docutils/parsers/rst/directives/images.py\", line 160, in run\n    line=self.lineno)\n  File \"/procbuild_env/lib/python3.6/site-packages/docutils/utils/__init__.py\", line 228, in error\n    return self.system_message(self.ERROR_LEVEL, *args, **kwargs)\n  File \"/procbuild_env/lib/python3.6/site-packages/docutils/utils/__init__.py\", line 194, in system_message\n    raise SystemMessage(msg, level)\ndocutils.utils.SystemMessage: <string>:293: (ERROR/3) Figure caption must be a paragraph or empty comment.\n\n.. figure:: fig_al_plot.png\n   :align: center\n   :figclass: w\n\n   (A) MPO score of all materials in the HTL dataset and (B) those used in the training set as a function of the hole reorganization energy (:math:`\\lambda_h`). :label:`figalplot`\n\nError building paper /tmp/tmp84g0jw5s/papers/alexandr_fonari. Aborting.\n[X] Error code 1\nA build error occurred during the self.run_make_paper_script step.", "build_pdf_path"=>"", "build_status"=>"Build failed, make_paper.sh did not succeed", "build_timestamp"=>"25/06 13:09"}, "status"=>"fail"}}

2022-06-25 13:15 UTC, afonari commented
@scoobies build status

2022-06-25 13:15 UTC, scoobies commented
{"afonari-2022-local"=>{"data"=>{"build_output"=>"[*] Updating proceedings build tools in {self.master_repo_path}...\nAlready up to date.\n[*] Check out paper repository...\nCloning into '/tmp/tmp0npv78mq'...\nMoving proceedings build tools to temp directory...\n[*] Build the paper...\n<string>:293: (ERROR/3) Figure caption must be a paragraph or empty comment.\n\n.. figure:: fig_al_plot.png\n   :align: center\n   :figclass: w\n\n   (A) MPO score of all materials in the HTL dataset and (B) those used in the training set as a function of the hole reorganization energy (:math:`\\lambda_h`). :label:`figalplot`\n\nBuilding: alexandr_fonari\nTraceback (most recent call last):\n  File \"publisher/build_paper.py\", line 237, in <module>\n    build_paper(paper_id)\n  File \"publisher/build_paper.py\", line 222, in build_paper\n    rst2tex(in_path, out_path)\n  File \"publisher/build_paper.py\", line 92, in rst2tex\n    settings_overrides=settings)\n  File \"/procbuild_env/lib/python3.6/site-packages/docutils/core.py\", line 416, in publish_string\n    enable_exit_status=enable_exit_status)\n  File \"/procbuild_env/lib/python3.6/site-packages/docutils/core.py\", line 664, in publish_programmatically\n    output = pub.publish(enable_exit_status=enable_exit_status)\n  File \"/procbuild_env/lib/python3.6/site-packages/docutils/core.py\", line 217, in publish\n    self.settings)\n  File \"/procbuild_env/lib/python3.6/site-packages/docutils/readers/__init__.py\", line 72, in read\n    self.parse()\n  File \"/procbuild_env/lib/python3.6/site-packages/docutils/readers/__init__.py\", line 78, in parse\n    self.parser.parse(self.input, document)\n  File \"/procbuild_env/lib/python3.6/site-packages/docutils/parsers/rst/__init__.py\", line 191, in parse\n    self.statemachine.run(inputlines, document, inliner=self.inliner)\n  File \"/procbuild_env/lib/python3.6/site-packages/docutils/parsers/rst/states.py\", line 171, in run\n    input_source=document['source'])\n  File \"/procbuild_env/lib/python3.6/site-packages/docutils/statemachine.py\", line 239, in run\n    context, state, transitions)\n  File \"/procbuild_env/lib/python3.6/site-packages/docutils/statemachine.py\", line 460, in check_line\n    return method(match, context, next_state)\n  File \"/procbuild_env/lib/python3.6/site-packages/docutils/parsers/rst/states.py\", line 2988, in text\n    self.section(title.lstrip(), source, style, lineno + 1, messages)\n  File \"/procbuild_env/lib/python3.6/site-packages/docutils/parsers/rst/states.py\", line 327, in section\n    self.new_subsection(title, lineno, messages)\n  File \"/procbuild_env/lib/python3.6/site-packages/docutils/parsers/rst/states.py\", line 395, in new_subsection\n    node=section_node, match_titles=True)\n  File \"/procbuild_env/lib/python3.6/site-packages/docutils/parsers/rst/states.py\", line 282, in nested_parse\n    node=node, match_titles=match_titles)\n  File \"/procbuild_env/lib/python3.6/site-packages/docutils/parsers/rst/states.py\", line 196, in run\n    results = StateMachineWS.run(self, input_lines, input_offset)\n  File \"/procbuild_env/lib/python3.6/site-packages/docutils/statemachine.py\", line 239, in run\n    context, state, transitions)\n  File \"/procbuild_env/lib/python3.6/site-packages/docutils/statemachine.py\", line 460, in check_line\n    return method(match, context, next_state)\n  File \"/procbuild_env/lib/python3.6/site-packages/docutils/parsers/rst/states.py\", line 2753, in underline\n    self.section(title, source, style, lineno - 1, messages)\n  File \"/procbuild_env/lib/python3.6/site-packages/docutils/parsers/rst/states.py\", line 327, in section\n    self.new_subsection(title, lineno, messages)\n  File \"/procbuild_env/lib/python3.6/site-packages/docutils/parsers/rst/states.py\", line 395, in new_subsection\n    node=section_node, match_titles=True)\n  File \"/procbuild_env/lib/python3.6/site-packages/docutils/parsers/rst/states.py\", line 282, in nested_parse\n    node=node, match_titles=match_titles)\n  File \"/procbuild_env/lib/python3.6/site-packages/docutils/parsers/rst/states.py\", line 196, in run\n    results = StateMachineWS.run(self, input_lines, input_offset)\n  File \"/procbuild_env/lib/python3.6/site-packages/docutils/statemachine.py\", line 239, in run\n    context, state, transitions)\n  File \"/procbuild_env/lib/python3.6/site-packages/docutils/statemachine.py\", line 460, in check_line\n    return method(match, context, next_state)\n  File \"/procbuild_env/lib/python3.6/site-packages/docutils/parsers/rst/states.py\", line 2326, in explicit_markup\n    nodelist, blank_finish = self.explicit_construct(match)\n  File \"/procbuild_env/lib/python3.6/site-packages/docutils/parsers/rst/states.py\", line 2338, in explicit_construct\n    return method(self, expmatch)\n  File \"/procbuild_env/lib/python3.6/site-packages/docutils/parsers/rst/states.py\", line 2081, in directive\n    directive_class, match, type_name, option_presets)\n  File \"/procbuild_env/lib/python3.6/site-packages/docutils/parsers/rst/states.py\", line 2130, in run_directive\n    result = directive_instance.run()\n  File \"/procbuild_env/lib/python3.6/site-packages/docutils/parsers/rst/directives/images.py\", line 160, in run\n    line=self.lineno)\n  File \"/procbuild_env/lib/python3.6/site-packages/docutils/utils/__init__.py\", line 228, in error\n    return self.system_message(self.ERROR_LEVEL, *args, **kwargs)\n  File \"/procbuild_env/lib/python3.6/site-packages/docutils/utils/__init__.py\", line 194, in system_message\n    raise SystemMessage(msg, level)\ndocutils.utils.SystemMessage: <string>:293: (ERROR/3) Figure caption must be a paragraph or empty comment.\n\n.. figure:: fig_al_plot.png\n   :align: center\n   :figclass: w\n\n   (A) MPO score of all materials in the HTL dataset and (B) those used in the training set as a function of the hole reorganization energy (:math:`\\lambda_h`). :label:`figalplot`\n\nError building paper /tmp/tmp0npv78mq/papers/alexandr_fonari. Aborting.\n[X] Error code 1\nA build error occurred during the self.run_make_paper_script step.", "build_pdf_path"=>"", "build_status"=>"Build failed, make_paper.sh did not succeed", "build_timestamp"=>"25/06 13:15"}, "status"=>"fail"}}

2022-06-25 14:00 UTC, afonari commented on papers/alexandr_fonari/alexandr_fonari.rst
> +This is also an example of the loosely coupled (embarrassingly parallel) jobs.
> "utilizing SciPy" -- The examples thus far have used least squares function minimization. It would be nice to have broader examples with more details about why those use cases are interesting/complex from an algorithmic or scientific perspective.

Extended with figures and description of the stress strain wokflow.

> "other open source packages" -- only SciPy has been mentioned at this point, I think? Some open source simulation engines may have been mentioned but were not a focus. This is partially addressed when lmfit is mentioned below, but it would be nice to have more examples like that.

Packages mentioned with some description: enumlib, scikit learn (AL part), Openbabel (disorder part)

> "powerful API" -- there have been no descriptions of the Schrodinger suite's API design or what constitutes a "powerful" API

Provided examples if similar API from pymatgen. Unfortunately I can't share Schrodinger API explicitly.

2022-06-25 14:02 UTC, afonari commented
Extended with reviewers comments, added figures. Thanks! Ready for the next round of review.

2022-06-26 04:16 UTC, bdice commented
Thank you @afonari! You’ve done a great job with comment responses, I really appreciate that. I will read those responses and take another pass of review on Monday. 👍

2022-06-27 15:56 UTC, bdice reviewed
This paper is dramatically improved! Very nice work @afonari on the revisions. The scientific content has become more detailed and useful. Also the connection between the Materials Science Suite and open-source software in the SciPy ecosystem is much clearer.

I have a number of suggestions, mostly for improved wording and small clarifications -- please feel free to adapt my suggested wording where you see fit. I plan to approve this after some of these changes can be applied. It would still be nice to have the bibliography in BibTeX, which would improve its formatting in the paper.

2022-06-27 15:56 UTC, bdice commented on papers/alexandr_fonari/alexandr_fonari.rst
> +For example, the main simulation engine for molecular quantum mechanics is Jaguar [Jaguar]_ proprietary code.
```suggestion
For example, the main simulation engine for molecular quantum mechanics is the Jaguar [Jaguar]_ proprietary code.
```

2022-06-27 15:56 UTC, bdice commented on papers/alexandr_fonari/alexandr_fonari.rst
> +Proprietary classical molecular dynamics code Desmond (distributed by Schrödinger, Inc.) [Desmond]_ is used to obtain physical properties of soft materials, surfaces and polymers.
```suggestion
The proprietary classical molecular dynamics code Desmond (distributed by Schrödinger, Inc.) [Desmond]_ is used to obtain physical properties of soft materials, surfaces and polymers.
```

2022-06-27 15:56 UTC, bdice commented on papers/alexandr_fonari/alexandr_fonari.rst
> +For periodic quantum mechanics, the main simulation engine is Quantum ESPRESSO (QE) [QE]_ open source code.
```suggestion
For periodic quantum mechanics, the main simulation engine is the open source code Quantum ESPRESSO (QE) [QE]_.
```

2022-06-27 15:56 UTC, bdice commented on papers/alexandr_fonari/alexandr_fonari.rst
> +One of the co-authors of this proceedings (A. Fonari) contributes to the QE code in order to make integration with the Materials suite more seamless and less error-prone.
If "Materials Suite" is the proper name of the software, capitalize both words.
```suggestion
One of the co-authors of this proceedings (A. Fonari) contributes to the QE code in order to make integration with the Materials Science Suite more seamless and less error-prone.
```

2022-06-27 15:56 UTC, bdice commented on papers/alexandr_fonari/alexandr_fonari.rst
> +Also there is a push to use portable ``XML`` format as the input/output format for QE, this has been implemented in the Python open source qeschema code [qeschema]_.
This might be clearer:
```suggestion
As part of this integration, support for using the portable ``XML`` format for input and output in QE has been implemented in the open source Python package qeschema [qeschema]_.
```

2022-06-27 15:56 UTC, bdice commented on papers/alexandr_fonari/alexandr_fonari.rst
> +The various workflows are implemented mainly in Python (some of them described below), calling on proprietary or open-source code where appropriate, again, to improve the performance of the software
```suggestion
The various workflows are implemented mainly in Python (some of them described below), calling on proprietary or open-source code where appropriate to improve the performance of the software and reduce overall maintenance.
```

2022-06-27 15:56 UTC, bdice commented on papers/alexandr_fonari/alexandr_fonari.rst
> +For example, pymatgen open source package [pymatgen]_ facilitates generation and analysis of periodic structures.
```suggestion
For example, the open source package pymatgen [pymatgen]_ facilitates generation and analysis of periodic structures.
```

2022-06-27 15:56 UTC, bdice commented on papers/alexandr_fonari/alexandr_fonari.rst
> +It can generate inputs and read outputs of several packages, such as QE and also commercial VASP and Gaussian codes, etc.
```suggestion
It can generate inputs for and read outputs of QE, the commercial codes VASP and Gaussian, and several other formats.
```

2022-06-27 15:56 UTC, bdice commented on papers/alexandr_fonari/alexandr_fonari.rst
> +One consideration of note is that PBD, CIF and mmCIF structure formats allow description of the positional disorder (for example, a solvent molecule without a stable position within the cell which ca
```suggestion
One consideration of note is that PDB, CIF and mmCIF structure formats allow description of the positional disorder (for example, a solvent molecule without a stable position within the cell which can be described by multiple sets of coordinates).
```

2022-06-27 15:56 UTC, bdice commented on papers/alexandr_fonari/alexandr_fonari.rst
> +          """
I would condense this for simplicity.
```suggestion
          """Create a periodic structure."""
```

2022-06-27 15:56 UTC, bdice commented on papers/alexandr_fonari/alexandr_fonari.rst
> +Another complication is that experimental data spans an interval of almost a century, one of the oldest crystal structures deposited in the Cambridge Structural Database (CSD) [CSD]_, dates to 1924 [
```suggestion
Another complication is that experimental data spans an interval of almost a century: one of the oldest crystal structures deposited in the Cambridge Structural Database (CSD) [CSD]_ dates to 1924 [Grph]_.
```

2022-06-27 15:56 UTC, bdice commented on papers/alexandr_fonari/alexandr_fonari.rst
> +By version 3.1.1 (the most recent at writing time), there are no known structures read incorrectly by OpenBabel that the authors are aware of.
```suggestion
By version 3.1.1 (the most recent at writing time), the authors are not aware of any structures read incorrectly by OpenBabel.
```

2022-06-27 15:56 UTC, bdice commented on papers/alexandr_fonari/alexandr_fonari.rst
> +Open source enumlib library [Enumlib]_ implements algorithms for such a systematic enumeration of periodic structures.
```suggestion
The open source library enumlib [Enumlib]_ implements algorithms for such a systematic enumeration of periodic structures.
```

2022-06-27 15:56 UTC, bdice commented on papers/alexandr_fonari/alexandr_fonari.rst
> +enumlib consists of several Fortran binaries and Python scripts that can be run as a subprocess (no Python bindings).
I usually try to respect package authors' preference of capitalization while also avoiding starting sentences with lowercased words. This helps solve both problems:
```suggestion
The enumlib package consists of several Fortran binaries and Python scripts that can be run as a subprocess (no Python bindings).
```

2022-06-27 15:56 UTC, bdice commented on papers/alexandr_fonari/alexandr_fonari.rst
> +This allows the user to generate a large set of symmetrically nonequivalent materials with different compositions (e.g. doping or defect concentration).
There's some inconsistency in the paper about whether _e.g._ is italicized or not. Please choose one way and make it consistent. (Same for i.e. and other Latin abbreviations, as appropriate.)

2022-06-27 15:56 UTC, bdice commented on papers/alexandr_fonari/alexandr_fonari.rst
> +For example, in case when the simulation is not converging to a requested energy accuracy, it is wasteful to blindly restart the calculation without changing some input parameters.
```suggestion
For example, if the simulation is not converging to a requested energy accuracy, it is wasteful to blindly restart the calculation without changing some input parameters.
```

2022-06-27 15:56 UTC, bdice commented on papers/alexandr_fonari/alexandr_fonari.rst
> +However, in the case of full disk space failure, it is reasonable to try restart with hopes to get a node with more empty disk space.
```suggestion
However, in the case of a failure due to full disk space, it is reasonable to try restart with hopes to get a node with more empty disk space.
```

2022-06-27 15:56 UTC, bdice commented on papers/alexandr_fonari/alexandr_fonari.rst
> +If a job fails (and can not be restarted), all its children (if any) will not start, thus saving queuing and computational time.
```suggestion
If a job fails (and cannot be restarted), all its children (if any) will not start, thus saving queuing and computational time.
```

2022-06-27 15:56 UTC, bdice commented on papers/alexandr_fonari/alexandr_fonari.rst
> +As can be seen from above a workflow is usually some sort of structure modification through the structure object with a subsequent call to a backend code and analysis of its output (input for the nex
```suggestion
As can be seen from above, a workflow is usually some sort of structure modification through the structure object with a subsequent call to a backend code and analysis of its output if it succeeds.
Input for the next iteration depends on the output of the previous iteration in some workflows.
```

2022-06-27 15:56 UTC, bdice commented on papers/alexandr_fonari/alexandr_fonari.rst
> +Due to the large chemical and manipulation space of the materials, sometimes it very tricky to keep code for all workflows follow the same code logic.
I tried to improve the wording in this sentence, but I had difficulty determining the purpose of this sentence. It feels somewhat obvious that different workflows will have different code logic, but maybe there's a more interesting discussion about what _can_ be shared and the ways that this software helps unify disparate workflows.
```suggestion
Due to the large chemical and manipulation space of the materials, sometimes it is difficult to use the same program logic for all workflows.
```

2022-06-27 15:56 UTC, bdice commented on papers/alexandr_fonari/alexandr_fonari.rst
> +For every workflow and/or functionality, some sort of peer reviewed material (publication, conference presentation) is created where implemented algorithms are described to facilitate reproducibility
Clarify what set of functionality you're describing. All of the Materials Science Suite?
```suggestion
For every workflow and/or functionality in the Materials Science Suite, some sort of peer reviewed material (publication, conference presentation) is created where implemented algorithms are described to facilitate reproducibility.
```

2022-06-27 15:56 UTC, bdice commented on papers/alexandr_fonari/alexandr_fonari.rst
> +   Left: The uniaxial stress/strain curve of a polymer calculated using Desmond through the stress strain workflow, grey band indicates inflection point (yield)). Right: Constant strain simulation wi
Improved wording in caption. Would it be possible to remove the gray background from the first image, and remove the green background from the second image? The backgrounds are somewhat visually distracting and don't appear to mean anything.
```suggestion
   Left: The uniaxial stress/strain curve of a polymer calculated using Desmond through the stress strain workflow. The dark grey band indicates an inflection that marks the yield point. Right: Constant strain simulation with convex analysis indicates elongation at yield. The red curve shows simulated stress versus strain. The blue curve shows convex analysis. :label:`fig4`
```

2022-06-27 15:56 UTC, bdice commented on papers/alexandr_fonari/alexandr_fonari.rst
> +
I would remove this blank line for consistency - there are no blank lines later in the snippet.
```suggestion
```

2022-06-27 15:56 UTC, bdice commented on papers/alexandr_fonari/alexandr_fonari.rst
> +   deform = Deformation([
At the top, could you show the imports being used? Something like:
```python
from pymatgen.analysis.elasticity.strain import Deformation
from pymatgen.core.lattice import Lattice
from pymatgen.core.structure import Structure
```

2022-06-27 15:56 UTC, bdice commented on papers/alexandr_fonari/alexandr_fonari.rst
> +Thus, all the deformation jobs can be submitted in parallel, greatly facilitating high-throughput runs.
```suggestion
Thus, all the deformation jobs can be submitted in parallel, facilitating high-throughput runs.
```

2022-06-27 15:56 UTC, bdice commented on papers/alexandr_fonari/alexandr_fonari.rst
> +Here we employed the open source ``lmfit`` package [Lmfit]_ to perform a minimization of the multivariable Voigt-like function that represents the entire diffraction spectrum.
Some package names are in `code font` but not all. I would try to be consistent in how the names are written. It seems like most have not used code font, so I'd adjust this one to match (use plain font).

2022-06-27 15:56 UTC, bdice commented on papers/alexandr_fonari/alexandr_fonari.rst
> +This allows the user to refine (optimize) unit cell parameters coming from the indexing data as a result goodness of fit (:math:`R`-factor) between experimental and simulated spectrum is reported.
Is this supposed to be two separate sentences?
```suggestion
This allows the user to refine (optimize) unit cell parameters coming from the indexing data.
Goodness of fit (:math:`R`-factor) between experimental and simulated spectrum is reported.
```

2022-06-27 15:56 UTC, bdice commented on papers/alexandr_fonari/alexandr_fonari.rst
> +- small molecules and finite systems -  Jaguar
This list isn't rendering like you wanted. It may need an empty line above and below the list.
```suggestion

- small molecules and finite systems -  Jaguar
```

2022-06-27 15:56 UTC, bdice commented on papers/alexandr_fonari/alexandr_fonari.rst
> +There are several techniques to generate the model, spawning from linear or non-linear fitting to neural networks, open source DeepChem [DeepChem]_ and AutoQSAR [AutoQSAR]_ from the Schrödinger suite
This sentence didn't quite make sense to me. I attempted to rewrite it.
```suggestion
There are several techniques to generate the model, such as linear or non-linear fitting to neural networks.
Tools include the open source DeepChem [DeepChem]_ and AutoQSAR [AutoQSAR]_ from the Schrödinger suite.
```

2022-06-27 15:56 UTC, bdice commented on papers/alexandr_fonari/alexandr_fonari.rst
> +- elemental features such as atomic weight, number of valence electrons in *s*, *p* and *d*-shells, electronegativity
```suggestion
- elemental features such as atomic weight, number of valence electrons in *s*, *p*, and *d*-shells, and electronegativity
```

2022-06-27 15:56 UTC, bdice commented on papers/alexandr_fonari/alexandr_fonari.rst
> +- intercalation descriptors such as cation and anion counts, crystal packing fraction, average neighbor ionicity [Sendek]_ implemented in the Schrödinger suite
```suggestion
- intercalation descriptors such as cation and anion counts, crystal packing fraction, and average neighbor ionicity [Sendek]_ implemented in the Schrödinger suite
```

2022-06-27 15:56 UTC, bdice commented on papers/alexandr_fonari/alexandr_fonari.rst
> +Several methods to generate model will be compared, such as kernel regression methods (as implemented in the open source scikit-learn code [SkLearn]_) and AutoQSAR.
Is it a method to generate a model -- or just a model?
```suggestion
Several models will be compared, such as kernel regression methods (as implemented in the open source scikit-learn code [SkLearn]_) and AutoQSAR.
```

2022-06-27 15:56 UTC, bdice commented on papers/alexandr_fonari/alexandr_fonari.rst
> +   A: MPO score of all materials in the HTL dataset. B: Those used in the training set as a function of the hole reorganization energy - :math:`\lambda_h`. :label:`figalplot`
The scatter plots are very dense with a lot of overlapping data points. I wonder if the marker size could be reduced, or if partially transparent points would help indicate regions of high density.

```suggestion
   A: MPO score of all materials in the HTL dataset. B: Those used in the training set as a function of the hole reorganization energy (:math:`\lambda_h`). :label:`figalplot`
```

2022-06-27 15:56 UTC, bdice commented on papers/alexandr_fonari/alexandr_fonari.rst
> +.. [Schr] Schrödinger Release (2021). Schrödinger Release 2021-2: Materials Science Suite. New York, NY: Schrödinger, LLC. http://www.schrodinger.com/materials/
This link redirects. I would try to use the most current redirections, and use `https` for all URLs if supported by the website.
```suggestion
.. [Schr] Schrödinger Release (2021). Schrödinger Release 2021-2: Materials Science Suite. New York, NY: Schrödinger, LLC. https://www.schrodinger.com/platform/materials-science
```

2022-06-27 15:56 UTC, bdice commented on papers/alexandr_fonari/alexandr_fonari.rst
> +.. [RDKit] G. Landrum. *RDKit: A software suite for cheminformatics, computational chemistry, and predictive modeling*, (2013). http://www.rdkit.org/
Prefer `https` where supported.
```suggestion
.. [RDKit] G. Landrum. *RDKit: A software suite for cheminformatics, computational chemistry, and predictive modeling*, (2013). https://www.rdkit.org/
```

2022-06-27 15:56 UTC, bdice commented on papers/alexandr_fonari/alexandr_fonari.rst
> +   Left: The uniaxial stress/strain curve of a polymer calculated using Desmond through the stress strain workflow, grey band indicates inflection point (yield)). Right: Constant strain simulation wi
The right figure says "Main axis: Axis c" at the top but I don't know what that means. The fonts are also a little small on the right figure.

2022-06-28 04:47 UTC, wdzhou reviewed
Hi, @afonari,  this edition is really in a good shape now.  I can only make a few comments so far.  All of the are minor.

2022-06-28 04:47 UTC, wdzhou commented on papers/alexandr_fonari/alexandr_fonari.rst
> +Experimental periodic structures of materials, mainly coming from single crystal X-ray diffraction, are distributed in CIF (Crystallographic Information File), PDB (Protein Data Bank) and lately mmCI
@afonari This is just a question, but not a request for change.  Why do you use `Experimental periodic structure` here?  In my field, people usually do not use `experimental`.

2022-06-28 04:47 UTC, wdzhou commented on papers/alexandr_fonari/alexandr_fonari.rst
> +Correctly reading experimental structures is of significant importance, since the rest of the materials discovery workflow depends on it.
Since you used `Experimental periodic structures ` above, maybe it is better to still use `experimental periodic structure` or `periodic structure` here.  At least in the neutron diffraction experiments, people rarely use `experimental structure`.

2022-06-28 04:47 UTC, wdzhou commented on papers/alexandr_fonari/alexandr_fonari.rst
> +All the structure manipulations during the workflows are done using structure object interface.
It is better to add a `by` between `done` and `using`. 

All the structure manipulations during the workflows are done `by` using structure object interface.

2022-06-28 04:47 UTC, wdzhou commented on papers/alexandr_fonari/alexandr_fonari.rst
> +All the structure manipulations during the workflows are done using structure object interface.
Do you mean that the manipulation are done by using the structure object interface to some specific crystal library?

2022-06-28 04:47 UTC, wdzhou commented on papers/alexandr_fonari/alexandr_fonari.rst
> +In general, non-periodic molecular formats are simpler to handle because they only contain atom coordinates and no cell or symmetry information.
You may replace `and no cell ..` with `but no cell ...`.

2022-06-28 04:47 UTC, wdzhou commented on papers/alexandr_fonari/alexandr_fonari.rst
> +Such catalysts may prove critical in electrocatalysis for fuel cell applications.
Do you have any paper reporting catalyst with fuel cell?  It will make your statement stronger.

2022-06-28 04:47 UTC, wdzhou commented on papers/alexandr_fonari/alexandr_fonari.rst
> +There could be several reasons for a job to fail and there are several restart and recovery mechanisms in place.
It may be better to separate it into two sentences.   One is the cause/situation.  The other is the solution.

2022-06-29 23:44 UTC, afonari commented on papers/alexandr_fonari/alexandr_fonari.rst
> +For example, the main simulation engine for molecular quantum mechanics is Jaguar [Jaguar]_ proprietary code.
Fixed.

2022-06-29 23:49 UTC, afonari commented on papers/alexandr_fonari/alexandr_fonari.rst
> +One consideration of note is that PBD, CIF and mmCIF structure formats allow description of the positional disorder (for example, a solvent molecule without a stable position within the cell which ca
Nice one, thanks, fixed.

2022-06-29 23:52 UTC, afonari commented on papers/alexandr_fonari/alexandr_fonari.rst
> +This allows the user to generate a large set of symmetrically nonequivalent materials with different compositions (e.g. doping or defect concentration).
Removed italic everywhere.

2022-06-29 23:56 UTC, afonari commented on papers/alexandr_fonari/alexandr_fonari.rst
> +For every workflow and/or functionality, some sort of peer reviewed material (publication, conference presentation) is created where implemented algorithms are described to facilitate reproducibility
Yes, thanks.

2022-06-29 23:58 UTC, afonari commented on papers/alexandr_fonari/alexandr_fonari.rst
> +
Added spaces between all the calls.

2022-06-30 00:01 UTC, afonari commented on papers/alexandr_fonari/alexandr_fonari.rst
> +   deform = Deformation([
Sure, fixed.

2022-06-30 00:03 UTC, afonari commented on papers/alexandr_fonari/alexandr_fonari.rst
> +Here we employed the open source ``lmfit`` package [Lmfit]_ to perform a minimization of the multivariable Voigt-like function that represents the entire diffraction spectrum.
Fixed, code fond are now only:
XML, requeue, scipy.optimize.minimize, scipy.optimize

2022-06-30 00:07 UTC, afonari commented on papers/alexandr_fonari/alexandr_fonari.rst
> +This allows the user to refine (optimize) unit cell parameters coming from the indexing data as a result goodness of fit (:math:`R`-factor) between experimental and simulated spectrum is reported.
Rewrote as:

This allows the user to refine (optimize) unit cell parameters coming from the indexing data and as the result, goodness of fit (:math:`R`-factor) between experimental and simulated spectrum is minimized.
===
The idea is that get better matching between indexed and experimental parameters. The better the matching the smaller is the R factor.

2022-06-30 00:07 UTC, afonari commented on papers/alexandr_fonari/alexandr_fonari.rst
> +- small molecules and finite systems -  Jaguar
Ah, thanks.

2022-06-30 00:08 UTC, afonari commented on papers/alexandr_fonari/alexandr_fonari.rst
> +There are several techniques to generate the model, spawning from linear or non-linear fitting to neural networks, open source DeepChem [DeepChem]_ and AutoQSAR [AutoQSAR]_ from the Schrödinger suite
Sure, looks better.

2022-06-30 00:11 UTC, afonari commented on papers/alexandr_fonari/alexandr_fonari.rst
> +Several methods to generate model will be compared, such as kernel regression methods (as implemented in the open source scikit-learn code [SkLearn]_) and AutoQSAR.
"models" is correct, fixed.

2022-06-30 00:13 UTC, afonari commented on papers/alexandr_fonari/alexandr_fonari.rst
> +.. [RDKit] G. Landrum. *RDKit: A software suite for cheminformatics, computational chemistry, and predictive modeling*, (2013). http://www.rdkit.org/
Thanks, ensured no "http:" present.

2022-06-30 00:22 UTC, afonari commented on papers/alexandr_fonari/alexandr_fonari.rst
> +Experimental periodic structures of materials, mainly coming from single crystal X-ray diffraction, are distributed in CIF (Crystallographic Information File), PDB (Protein Data Bank) and lately mmCI
I see, yes, experimental sounds like structure is experimental (not tested or something). Changed to:

Periodic structures of materials, mainly coming from single crystal X-ray/neutron diffraction experiments, are distributed in CIF (Crystallographic Information File), PDB (Protein Data Bank) and lately mmCIF formats [Formats]_.

2022-06-30 00:23 UTC, afonari commented on papers/alexandr_fonari/alexandr_fonari.rst
> +Experimental periodic structures of materials, mainly coming from single crystal X-ray diffraction, are distributed in CIF (Crystallographic Information File), PDB (Protein Data Bank) and lately mmCI
Also updated this sentence:

Structure refinement from powder diffraction experiment is another example where more complex optimization is used.

2022-06-30 00:26 UTC, afonari commented on papers/alexandr_fonari/alexandr_fonari.rst
> +All the structure manipulations during the workflows are done using structure object interface.
Fixed grammar.

> Do you mean that the manipulation are done by using the structure object interface to some specific crystal library?

I meant structure modification, by for example strain, updated sentence to:

All the structure manipulations during the workflows are done by using structure object interface (see structure deformation example below).

2022-06-30 00:26 UTC, afonari commented on papers/alexandr_fonari/alexandr_fonari.rst
> +Such catalysts may prove critical in electrocatalysis for fuel cell applications.
Unfortunately, no.

2022-06-30 00:52 UTC, afonari commented on papers/alexandr_fonari/alexandr_fonari.rst
> +There could be several reasons for a job to fail and there are several restart and recovery mechanisms in place.
Sure, replaced with:

There could be several reasons for a job to fail. Depending on the reason of failure, there are several restart and recovery mechanisms in place.

2022-06-30 02:19 UTC, deniederhut commented
Thanks for all those revisions Alexander! @bdice and @wdzhou, do you feel this paper is now ready for inclusion in the proceedings?

2022-06-30 04:37 UTC, bdice approved these changes
@deniederhut I approve this for inclusion in the Proceedings! Thanks @afonari for your dedication to the paper and review process.

2022-06-30 11:48 UTC, wdzhou commented
@deniederhut I think the paper is well written and thus approve it in the Proceedings.  Thanks @afonari for making great effort on the paper.

2022-06-30 11:49 UTC, wdzhou approved these changes
The paper is in good shape!

2022-06-30 12:42 UTC, afonari commented
Thanks everyone! Wow it was a group effort!

@deniederhut I still have time till July 6th to fix things right?

2022-07-01 01:09 UTC, deniederhut commented
I believe July 4th is the last day for author changes.

2022-07-01 17:43 UTC, mepa commented
@scoobies check references

2022-07-01 17:43 UTC, scoobies commented
Checking the BibTeX entries failed with the following error: 
```
Couldn't find bibliography entry
```

2022-07-01 21:05 UTC, afonari commented
@scoobies build status

2022-07-01 21:05 UTC, scoobies commented
{"afonari-2022-local"=>{"data"=>{"build_output"=>"[*] Updating proceedings build tools in {self.master_repo_path}...\nAlready up to date.\n[*] Check out paper repository...\nCloning into '/tmp/tmpb8k9tfws'...\nMoving proceedings build tools to temp directory...\n[*] Build the paper...\nBuilding: alexandr_fonari\n*** Warning: /tmp/tmpb8k9tfws/publisher/../output/alexandr_fonari/paper_stats.json does not exist.\nPDFLaTeX error output:\n================================================================================\nTraceback (most recent call last):\n  File \"publisher/build_paper.py\", line 237, in <module>\n    build_paper(paper_id)\n  File \"publisher/build_paper.py\", line 223, in build_paper\n    pdflatex_stdout = tex2pdf(out_path)\n  File \"publisher/build_paper.py\", line 116, in tex2pdf\n    out, retry = tex2pdf_singlepass(out_path)\n  File \"publisher/build_paper.py\", line 152, in tex2pdf_singlepass\n    print(out.decode('utf-8'))\nUnicodeDecodeError: 'utf-8' codec can't decode byte 0xe4 in position 9000: invalid continuation byte\nError building paper /tmp/tmpb8k9tfws/papers/alexandr_fonari. Aborting.\n[X] Error code 1\nA build error occurred during the self.run_make_paper_script step.", "build_pdf_path"=>"", "build_status"=>"Build failed, make_paper.sh did not succeed", "build_timestamp"=>"01/07 21:03"}, "status"=>"fail"}}

2022-07-01 21:08 UTC, afonari commented
@scoobies build status

2022-07-01 21:08 UTC, scoobies commented
{"afonari-2022-local"=>{"data"=>{"build_output"=>"[*] Updating proceedings build tools in {self.master_repo_path}...\nAlready up to date.\n[*] Check out paper repository...\nCloning into '/tmp/tmpb8k9tfws'...\nMoving proceedings build tools to temp directory...\n[*] Build the paper...\nBuilding: alexandr_fonari\n*** Warning: /tmp/tmpb8k9tfws/publisher/../output/alexandr_fonari/paper_stats.json does not exist.\nPDFLaTeX error output:\n================================================================================\nTraceback (most recent call last):\n  File \"publisher/build_paper.py\", line 237, in <module>\n    build_paper(paper_id)\n  File \"publisher/build_paper.py\", line 223, in build_paper\n    pdflatex_stdout = tex2pdf(out_path)\n  File \"publisher/build_paper.py\", line 116, in tex2pdf\n    out, retry = tex2pdf_singlepass(out_path)\n  File \"publisher/build_paper.py\", line 152, in tex2pdf_singlepass\n    print(out.decode('utf-8'))\nUnicodeDecodeError: 'utf-8' codec can't decode byte 0xe4 in position 9000: invalid continuation byte\nError building paper /tmp/tmpb8k9tfws/papers/alexandr_fonari. Aborting.\n[X] Error code 1\nA build error occurred during the self.run_make_paper_script step.", "build_pdf_path"=>"", "build_status"=>"Build failed, make_paper.sh did not succeed", "build_timestamp"=>"01/07 21:03"}, "status"=>"fail"}}

2022-07-01 21:10 UTC, afonari commented
@scoobies build status

2022-07-01 21:11 UTC, scoobies commented
{"afonari-2022-local"=>{"data"=>{"build_output"=>"[*] Updating proceedings build tools in {self.master_repo_path}...\nAlready up to date.\n[*] Check out paper repository...\nCloning into '/tmp/tmp9flril__'...\nMoving proceedings build tools to temp directory...\n[*] Build the paper...\nBuilding: alexandr_fonari\n*** Warning: /tmp/tmp9flril__/publisher/../output/alexandr_fonari/paper_stats.json does not exist.\nPDFLaTeX error output:\n================================================================================\nTraceback (most recent call last):\n  File \"publisher/build_paper.py\", line 237, in <module>\n    build_paper(paper_id)\n  File \"publisher/build_paper.py\", line 223, in build_paper\n    pdflatex_stdout = tex2pdf(out_path)\n  File \"publisher/build_paper.py\", line 116, in tex2pdf\n    out, retry = tex2pdf_singlepass(out_path)\n  File \"publisher/build_paper.py\", line 152, in tex2pdf_singlepass\n    print(out.decode('utf-8'))\nUnicodeDecodeError: 'utf-8' codec can't decode byte 0xe4 in position 9000: invalid continuation byte\nError building paper /tmp/tmp9flril__/papers/alexandr_fonari. Aborting.\n[X] Error code 1\nA build error occurred during the self.run_make_paper_script step.", "build_pdf_path"=>"", "build_status"=>"Build failed, make_paper.sh did not succeed", "build_timestamp"=>"01/07 21:10"}, "status"=>"fail"}}

2022-07-01 21:13 UTC, afonari commented
@scoobies build status

2022-07-01 21:13 UTC, scoobies commented
{"afonari-2022-local"=>{"data"=>{"build_output"=>"[*] Updating proceedings build tools in {self.master_repo_path}...\nAlready up to date.\n[*] Check out paper repository...\nCloning into '/tmp/tmp6wo94i6t'...\nMoving proceedings build tools to temp directory...\n[*] Build the paper...\nBuilding: alexandr_fonari\n*** Warning: /tmp/tmp6wo94i6t/publisher/../output/alexandr_fonari/paper_stats.json does not exist.\nPDFLaTeX error output:\n================================================================================\nTraceback (most recent call last):\n  File \"publisher/build_paper.py\", line 237, in <module>\n    build_paper(paper_id)\n  File \"publisher/build_paper.py\", line 223, in build_paper\n    pdflatex_stdout = tex2pdf(out_path)\n  File \"publisher/build_paper.py\", line 116, in tex2pdf\n    out, retry = tex2pdf_singlepass(out_path)\n  File \"publisher/build_paper.py\", line 152, in tex2pdf_singlepass\n    print(out.decode('utf-8'))\nUnicodeDecodeError: 'utf-8' codec can't decode byte 0xe4 in position 9000: invalid continuation byte\nError building paper /tmp/tmp6wo94i6t/papers/alexandr_fonari. Aborting.\n[X] Error code 1\nA build error occurred during the self.run_make_paper_script step.", "build_pdf_path"=>"", "build_status"=>"Build failed, make_paper.sh did not succeed", "build_timestamp"=>"01/07 21:13"}, "status"=>"fail"}}

2022-07-01 21:16 UTC, afonari commented
@scoobies build status

2022-07-01 21:16 UTC, scoobies commented
{"afonari-2022-local"=>{"data"=>{"build_output"=>"[*] Updating proceedings build tools in {self.master_repo_path}...\nAlready up to date.\n[*] Check out paper repository...\nCloning into '/tmp/tmpijllh4jv'...\nMoving proceedings build tools to temp directory...\n[*] Build the paper...\nBuilding: alexandr_fonari\n*** Warning: /tmp/tmpijllh4jv/publisher/../output/alexandr_fonari/paper_stats.json does not exist.\nPDFLaTeX error output:\n================================================================================\nThis is pdfTeX, Version 3.14159265-2.6-1.40.18 (TeX Live 2017/Debian) (preloaded format=pdflatex)\n restricted \\write18 enabled.\nentering extended mode\n(./paper.tex\nLaTeX2e <2017-04-15>\nBabel <3.18> and hyphenation patterns for 3 language(s) loaded.\n(./IEEEtran.cls\nDocument Class: IEEEtran 2015/08/26 V1.8b by Michael Shell\n-- See the \"IEEEtran_HOWTO\" manual for usage information.\n-- http://www.michaelshell.org/tex/ieeetran/\n(/usr/share/texlive/texmf-dist/tex/latex/psnfss/ot1ppl.fd)\n-- Using IEEE Computer Society mode.\n-- Using 8.5in x 11in (letter) paper.\n-- Using PDF output.\n-- This is a 10 point document.\n) (/usr/share/texlive/texmf-dist/tex/latex/cmap/cmap.sty)\n(/usr/share/texlive/texmf-dist/tex/latex/base/ifthen.sty)\n(/usr/share/texlive/texmf-dist/tex/latex/base/fontenc.sty\n(/usr/share/texlive/texmf-dist/tex/latex/base/t1enc.def)\n(/usr/share/texlive/texmf-dist/tex/latex/psnfss/t1ppl.fd)<<t1.cmap>>)\n(/usr/share/texlive/texmf-dist/tex/latex/base/inputenc.sty\n(/usr/share/texlive/texmf-dist/tex/latex/base/utf8.def\n(/usr/share/texlive/texmf-dist/tex/latex/base/t1enc.dfu)\n(/usr/share/texlive/texmf-dist/tex/latex/base/ot1enc.dfu)\n(/usr/share/texlive/texmf-dist/tex/latex/base/omsenc.dfu)))\n(/usr/share/texlive/texmf-dist/tex/latex/amsmath/amsmath.sty\nFor additional information on amsmath, use the `?' option.\n(/usr/share/texlive/texmf-dist/tex/latex/amsmath/amstext.sty\n(/usr/share/texlive/texmf-dist/tex/latex/amsmath/amsgen.sty))\n(/usr/share/texlive/texmf-dist/tex/latex/amsmath/amsbsy.sty)\n(/usr/share/texlive/texmf-dist/tex/latex/amsmath/amsopn.sty))\n(/usr/share/texlive/texmf-dist/tex/latex/caption/caption.sty\n(/usr/share/texlive/texmf-dist/tex/latex/caption/caption3.sty\n(/usr/share/texlive/texmf-dist/tex/latex/graphics/keyval.sty))\n\nPackage caption Warning: Unsupported document class (or package) detected,\n(caption)                usage of the caption package is not recommended.\nSee the caption package documentation for explanation.\n\n) (/usr/share/texlive/texmf-dist/tex/latex/float/float.sty) (./scipy.sty\n(./status.sty (./draftwatermark.sty (./everypage.sty)\n(/usr/share/texlive/texmf-dist/tex/latex/graphics/graphicx.sty\n(/usr/share/texlive/texmf-dist/tex/latex/graphics/graphics.sty\n(/usr/share/texlive/texmf-dist/tex/latex/graphics/trig.sty)\n(/usr/share/texlive/texmf-dist/tex/latex/graphics-cfg/graphics.cfg)\n(/usr/share/texlive/texmf-dist/tex/latex/graphics-def/pdftex.def)))\n(/usr/share/texlive/texmf-dist/tex/latex/graphics/color.sty\n(/usr/share/texlive/texmf-dist/tex/latex/graphics-cfg/color.cfg))))\n(/usr/share/texlive/texmf-dist/tex/latex/psnfss/mathptmx.sty)\n(/usr/share/texlive/texmf-dist/tex/latex/psnfss/helvet.sty)\n(/usr/share/texlive/texmf-dist/tex/latex/psnfss/courier.sty)\n(/usr/share/texlive/texmf-dist/tex/latex/amsfonts/amsfonts.sty)\n(/usr/share/texlive/texmf-dist/tex/latex/amsfonts/amssymb.sty)\n(/usr/share/texlive/texmf-dist/tex/latex/tools/bm.sty)\n(/usr/share/texlive/texmf-dist/tex/latex/hyperref/hyperref.sty\n(/usr/share/texlive/texmf-dist/tex/generic/oberdiek/hobsub-hyperref.sty\n(/usr/share/texlive/texmf-dist/tex/generic/oberdiek/hobsub-generic.sty))\n(/usr/share/texlive/texmf-dist/tex/generic/ifxetex/ifxetex.sty)\n(/usr/share/texlive/texmf-dist/tex/latex/oberdiek/auxhook.sty)\n(/usr/share/texlive/texmf-dist/tex/latex/oberdiek/kvoptions.sty)\n(/usr/share/texlive/texmf-dist/tex/latex/hyperref/pd1enc.def)\n(/usr/share/texlive/texmf-dist/tex/latex/latexconfig/hyperref.cfg)\n(/usr/share/texlive/texmf-dist/tex/latex/url/url.sty))\n(/usr/share/texlive/texmf-dist/tex/latex/hyperref/hpdftex.def\n(/usr/share/texlive/texmf-dist/tex/latex/oberdiek/rerunfilecheck.sty))\n\nPackage hyperref Warning: Option `pdftex' has already been used,\n(hyperref)                setting the option has no effect on input line 43.\n\n(/usr/share/texlive/texmf-dist/tex/latex/tools/longtable.sty)\n(/usr/share/texlive/texmf-dist/tex/latex/multirow/multirow.sty)\n(/usr/share/texlive/texmf-dist/tex/latex/booktabs/booktabs.sty)\n(/usr/share/texlive/texmf-dist/tex/latex/base/textcomp.sty\n(/usr/share/texlive/texmf-dist/tex/latex/base/ts1enc.def\n(/usr/share/texlive/texmf-dist/tex/latex/base/ts1enc.dfu)))\n(/usr/share/texlive/texmf-dist/tex/latex/upquote/upquote.sty)\n(/usr/share/texlive/texmf-dist/tex/latex/fancyvrb/fancyvrb.sty\nStyle option: `fancyvrb' v2.7a, with DG/SPQR fixes, and firstline=lastline fix \n<2008/02/07> (tvz))) (./paper.aux)\n(/usr/share/texlive/texmf-dist/tex/latex/base/ts1cmr.fd)\n(/usr/share/texlive/texmf-dist/tex/latex/psnfss/t1ptm.fd)\n-- Lines per column: 61 (exact).\n(/usr/share/texlive/texmf-dist/tex/latex/caption/ltcaption.sty)\n(/usr/share/texlive/texmf-dist/tex/context/base/mkii/supp-pdf.mkii\n[Loading MPS to PDF converter (version 2006.09.02).]\n) (/usr/share/texlive/texmf-dist/tex/latex/oberdiek/epstopdf-base.sty\n(/usr/share/texlive/texmf-dist/tex/latex/oberdiek/grfext.sty)\n(/usr/share/texlive/texmf-dist/tex/latex/latexconfig/epstopdf-sys.cfg))\n(/usr/share/texlive/texmf-dist/tex/latex/hyperref/nameref.sty\n(/usr/share/texlive/texmf-dist/tex/generic/oberdiek/gettitlestring.sty))\n(./paper.out) (./paper.out)\n(/usr/share/texlive/texmf-dist/tex/latex/psnfss/t1phv.fd)\n(/usr/share/texlive/texmf-dist/tex/latex/psnfss/ot1ztmcm.fd)<<ot1.cmap>>\n(/usr/share/texlive/texmf-dist/tex/latex/psnfss/omlztmcm.fd)<<oml.cmap>>\n(/usr/share/texlive/texmf-dist/tex/latex/psnfss/omsztmcm.fd)<<oms.cmap>>\n(/usr/share/texlive/texmf-dist/tex/latex/psnfss/omxztmcm.fd)<<omx.cmap>>\n(/usr/share/texlive/texmf-dist/tex/latex/psnfss/ot1ptm.fd)\n(/usr/share/texlive/texmf-dist/tex/latex/psnfss/upzd.fd)\n(/usr/share/texlive/texmf-dist/tex/latex/psnfss/ts1ptm.fd) (./page_numbers.tex)\n\nUnderfull \\hbox (badness 2970) in paragraph at lines 157--159\n\\T1/phv/b/n/8.03 Abstract\\T1/phv/m/n/8.03 ---The use of sev-eral open source sc\ni-en-tific pack-ages in the\n\nLaTeX Warning: No positions in optional float specifier.\n               Default added (so using `tbp') on input line 167.\n\n\nLaTeX Warning: Citation `Desmond' on page 1 undefined on input line 179.\n\n(/usr/share/texlive/texmf-dist/tex/latex/psnfss/t1pcr.fd)\n\nLaTeX Warning: Citation `pymatgen' on page 1 undefined on input line 189.\n\n\nLaTeX Warning: Citation `pymatgen' on page 1 undefined on input line 191.\n\n\nLaTeX Warning: No positions in optional float specifier.\n               Default added (so using `tbp') on input line 191.\n\n\nLaTeX Warning: Citation `Obabel' on page 1 undefined on input line 200.\n\n\nLaTeX Warning: Citation `Formats' on page 1 undefined on input line 201.\n\n\nLaTeX Warning: Citation `pymatgen' on page 1 undefined on input line 206.\n\n[1{/var/lib/texmf/fonts/map/pdftex/updmap/pdftex.map}]\nUnderfull \\vbox (badness 1072) has occurred while \\output is active\n\nLaTeX Warning: Citation `TM' on page 2 undefined on input line 232.\n\n\nUnderfull \\vbox (badness 10000) has occurred while \\output is active [2 <./fig_\nscheme.png> <./fig_product.png>]\n\nLaTeX Warning: No positions in optional float specifier.\n               Default added (so using `tbp') on input line 247.\n\n\nLaTeX Warning: Citation `CScreen' on page 3 undefined on input line 261.\n\n\nLaTeX Warning: Citation `Scipy' on page 3 undefined on input line 268.\n\n\nLaTeX Warning: Citation `Deposition' on page 3 undefined on input line 273.\n\n\nLaTeX Warning: Citation `Patrone' on page 3 undefined on input line 290.\n\n\nLaTeX Warning: No positions in option [...]

2022-07-01 21:22 UTC, afonari commented
@scoobies build status

2022-07-01 21:22 UTC, scoobies commented
{"afonari-2022-local"=>{"data"=>{"build_output"=>"[*] Updating proceedings build tools in {self.master_repo_path}...\nAlready up to date.\n[*] Check out paper repository...\nCloning into '/tmp/tmpo4af_va5'...\nMoving proceedings build tools to temp directory...\n[*] Build the paper...\nBuilding: alexandr_fonari\n*** Warning: /tmp/tmpo4af_va5/publisher/../output/alexandr_fonari/paper_stats.json does not exist.\nPDFLaTeX error output:\n================================================================================\nThis is pdfTeX, Version 3.14159265-2.6-1.40.18 (TeX Live 2017/Debian) (preloaded format=pdflatex)\n restricted \\write18 enabled.\nentering extended mode\n(./paper.tex\nLaTeX2e <2017-04-15>\nBabel <3.18> and hyphenation patterns for 3 language(s) loaded.\n(./IEEEtran.cls\nDocument Class: IEEEtran 2015/08/26 V1.8b by Michael Shell\n-- See the \"IEEEtran_HOWTO\" manual for usage information.\n-- http://www.michaelshell.org/tex/ieeetran/\n(/usr/share/texlive/texmf-dist/tex/latex/psnfss/ot1ppl.fd)\n-- Using IEEE Computer Society mode.\n-- Using 8.5in x 11in (letter) paper.\n-- Using PDF output.\n-- This is a 10 point document.\n) (/usr/share/texlive/texmf-dist/tex/latex/cmap/cmap.sty)\n(/usr/share/texlive/texmf-dist/tex/latex/base/ifthen.sty)\n(/usr/share/texlive/texmf-dist/tex/latex/base/fontenc.sty\n(/usr/share/texlive/texmf-dist/tex/latex/base/t1enc.def)\n(/usr/share/texlive/texmf-dist/tex/latex/psnfss/t1ppl.fd)<<t1.cmap>>)\n(/usr/share/texlive/texmf-dist/tex/latex/base/inputenc.sty\n(/usr/share/texlive/texmf-dist/tex/latex/base/utf8.def\n(/usr/share/texlive/texmf-dist/tex/latex/base/t1enc.dfu)\n(/usr/share/texlive/texmf-dist/tex/latex/base/ot1enc.dfu)\n(/usr/share/texlive/texmf-dist/tex/latex/base/omsenc.dfu)))\n(/usr/share/texlive/texmf-dist/tex/latex/amsmath/amsmath.sty\nFor additional information on amsmath, use the `?' option.\n(/usr/share/texlive/texmf-dist/tex/latex/amsmath/amstext.sty\n(/usr/share/texlive/texmf-dist/tex/latex/amsmath/amsgen.sty))\n(/usr/share/texlive/texmf-dist/tex/latex/amsmath/amsbsy.sty)\n(/usr/share/texlive/texmf-dist/tex/latex/amsmath/amsopn.sty))\n(/usr/share/texlive/texmf-dist/tex/latex/caption/caption.sty\n(/usr/share/texlive/texmf-dist/tex/latex/caption/caption3.sty\n(/usr/share/texlive/texmf-dist/tex/latex/graphics/keyval.sty))\n\nPackage caption Warning: Unsupported document class (or package) detected,\n(caption)                usage of the caption package is not recommended.\nSee the caption package documentation for explanation.\n\n) (/usr/share/texlive/texmf-dist/tex/latex/float/float.sty) (./scipy.sty\n(./status.sty (./draftwatermark.sty (./everypage.sty)\n(/usr/share/texlive/texmf-dist/tex/latex/graphics/graphicx.sty\n(/usr/share/texlive/texmf-dist/tex/latex/graphics/graphics.sty\n(/usr/share/texlive/texmf-dist/tex/latex/graphics/trig.sty)\n(/usr/share/texlive/texmf-dist/tex/latex/graphics-cfg/graphics.cfg)\n(/usr/share/texlive/texmf-dist/tex/latex/graphics-def/pdftex.def)))\n(/usr/share/texlive/texmf-dist/tex/latex/graphics/color.sty\n(/usr/share/texlive/texmf-dist/tex/latex/graphics-cfg/color.cfg))))\n(/usr/share/texlive/texmf-dist/tex/latex/psnfss/mathptmx.sty)\n(/usr/share/texlive/texmf-dist/tex/latex/psnfss/helvet.sty)\n(/usr/share/texlive/texmf-dist/tex/latex/psnfss/courier.sty)\n(/usr/share/texlive/texmf-dist/tex/latex/amsfonts/amsfonts.sty)\n(/usr/share/texlive/texmf-dist/tex/latex/amsfonts/amssymb.sty)\n(/usr/share/texlive/texmf-dist/tex/latex/tools/bm.sty)\n(/usr/share/texlive/texmf-dist/tex/latex/hyperref/hyperref.sty\n(/usr/share/texlive/texmf-dist/tex/generic/oberdiek/hobsub-hyperref.sty\n(/usr/share/texlive/texmf-dist/tex/generic/oberdiek/hobsub-generic.sty))\n(/usr/share/texlive/texmf-dist/tex/generic/ifxetex/ifxetex.sty)\n(/usr/share/texlive/texmf-dist/tex/latex/oberdiek/auxhook.sty)\n(/usr/share/texlive/texmf-dist/tex/latex/oberdiek/kvoptions.sty)\n(/usr/share/texlive/texmf-dist/tex/latex/hyperref/pd1enc.def)\n(/usr/share/texlive/texmf-dist/tex/latex/latexconfig/hyperref.cfg)\n(/usr/share/texlive/texmf-dist/tex/latex/url/url.sty))\n(/usr/share/texlive/texmf-dist/tex/latex/hyperref/hpdftex.def\n(/usr/share/texlive/texmf-dist/tex/latex/oberdiek/rerunfilecheck.sty))\n\nPackage hyperref Warning: Option `pdftex' has already been used,\n(hyperref)                setting the option has no effect on input line 43.\n\n(/usr/share/texlive/texmf-dist/tex/latex/tools/longtable.sty)\n(/usr/share/texlive/texmf-dist/tex/latex/multirow/multirow.sty)\n(/usr/share/texlive/texmf-dist/tex/latex/booktabs/booktabs.sty)\n(/usr/share/texlive/texmf-dist/tex/latex/base/textcomp.sty\n(/usr/share/texlive/texmf-dist/tex/latex/base/ts1enc.def\n(/usr/share/texlive/texmf-dist/tex/latex/base/ts1enc.dfu)))\n(/usr/share/texlive/texmf-dist/tex/latex/upquote/upquote.sty)\n(/usr/share/texlive/texmf-dist/tex/latex/fancyvrb/fancyvrb.sty\nStyle option: `fancyvrb' v2.7a, with DG/SPQR fixes, and firstline=lastline fix \n<2008/02/07> (tvz))) (./paper.aux)\n(/usr/share/texlive/texmf-dist/tex/latex/base/ts1cmr.fd)\n(/usr/share/texlive/texmf-dist/tex/latex/psnfss/t1ptm.fd)\n-- Lines per column: 61 (exact).\n(/usr/share/texlive/texmf-dist/tex/latex/caption/ltcaption.sty)\n(/usr/share/texlive/texmf-dist/tex/context/base/mkii/supp-pdf.mkii\n[Loading MPS to PDF converter (version 2006.09.02).]\n) (/usr/share/texlive/texmf-dist/tex/latex/oberdiek/epstopdf-base.sty\n(/usr/share/texlive/texmf-dist/tex/latex/oberdiek/grfext.sty)\n(/usr/share/texlive/texmf-dist/tex/latex/latexconfig/epstopdf-sys.cfg))\n(/usr/share/texlive/texmf-dist/tex/latex/hyperref/nameref.sty\n(/usr/share/texlive/texmf-dist/tex/generic/oberdiek/gettitlestring.sty))\n(./paper.out) (./paper.out)\n(/usr/share/texlive/texmf-dist/tex/latex/psnfss/t1phv.fd)\n(/usr/share/texlive/texmf-dist/tex/latex/psnfss/ot1ztmcm.fd)<<ot1.cmap>>\n(/usr/share/texlive/texmf-dist/tex/latex/psnfss/omlztmcm.fd)<<oml.cmap>>\n(/usr/share/texlive/texmf-dist/tex/latex/psnfss/omsztmcm.fd)<<oms.cmap>>\n(/usr/share/texlive/texmf-dist/tex/latex/psnfss/omxztmcm.fd)<<omx.cmap>>\n(/usr/share/texlive/texmf-dist/tex/latex/psnfss/ot1ptm.fd)\n(/usr/share/texlive/texmf-dist/tex/latex/psnfss/upzd.fd)\n(/usr/share/texlive/texmf-dist/tex/latex/psnfss/ts1ptm.fd) (./page_numbers.tex)\n\nUnderfull \\hbox (badness 2970) in paragraph at lines 157--159\n\\T1/phv/b/n/8.03 Abstract\\T1/phv/m/n/8.03 ---The use of sev-eral open source sc\ni-en-tific pack-ages in the\n\nLaTeX Warning: No positions in optional float specifier.\n               Default added (so using `tbp') on input line 167.\n\n\nLaTeX Warning: Citation `Desmond' on page 1 undefined on input line 179.\n\n(/usr/share/texlive/texmf-dist/tex/latex/psnfss/t1pcr.fd)\n\nLaTeX Warning: Citation `pymatgen' on page 1 undefined on input line 189.\n\n\nLaTeX Warning: Citation `pymatgen' on page 1 undefined on input line 191.\n\n\nLaTeX Warning: No positions in optional float specifier.\n               Default added (so using `tbp') on input line 191.\n\n\nLaTeX Warning: Citation `Obabel' on page 1 undefined on input line 200.\n\n\nLaTeX Warning: Citation `Formats' on page 1 undefined on input line 201.\n\n\nLaTeX Warning: Citation `pymatgen' on page 1 undefined on input line 206.\n\n[1{/var/lib/texmf/fonts/map/pdftex/updmap/pdftex.map}]\nUnderfull \\vbox (badness 1072) has occurred while \\output is active\n\nLaTeX Warning: Citation `TM' on page 2 undefined on input line 232.\n\n\nUnderfull \\vbox (badness 10000) has occurred while \\output is active [2 <./fig_\nscheme.png> <./fig_product.png>]\n\nLaTeX Warning: No positions in optional float specifier.\n               Default added (so using `tbp') on input line 247.\n\n\nLaTeX Warning: Citation `CScreen' on page 3 undefined on input line 261.\n\n\nLaTeX Warning: Citation `Scipy' on page 3 undefined on input line 268.\n\n\nLaTeX Warning: Citation `Deposition' on page 3 undefined on input line 273.\n\n\nLaTeX Warning: Citation `Patrone' on page 3 undefined on input line 290.\n\n\nLaTeX Warning: No positions in option [...]

2022-07-01 21:24 UTC, afonari commented
@scoobies build status

2022-07-01 21:24 UTC, scoobies commented
{"afonari-2022-local"=>{"data"=>{"build_output"=>"[*] Updating proceedings build tools in {self.master_repo_path}...\nAlready up to date.\n[*] Check out paper repository...\nCloning into '/tmp/tmps8i_c7k5'...\nMoving proceedings build tools to temp directory...\n[*] Build the paper...\nBuilding: alexandr_fonari\n*** Warning: /tmp/tmps8i_c7k5/publisher/../output/alexandr_fonari/paper_stats.json does not exist.\nPDFLaTeX error output:\n================================================================================\nThis is pdfTeX, Version 3.14159265-2.6-1.40.18 (TeX Live 2017/Debian) (preloaded format=pdflatex)\n restricted \\write18 enabled.\nentering extended mode\n(./paper.tex\nLaTeX2e <2017-04-15>\nBabel <3.18> and hyphenation patterns for 3 language(s) loaded.\n(./IEEEtran.cls\nDocument Class: IEEEtran 2015/08/26 V1.8b by Michael Shell\n-- See the \"IEEEtran_HOWTO\" manual for usage information.\n-- http://www.michaelshell.org/tex/ieeetran/\n(/usr/share/texlive/texmf-dist/tex/latex/psnfss/ot1ppl.fd)\n-- Using IEEE Computer Society mode.\n-- Using 8.5in x 11in (letter) paper.\n-- Using PDF output.\n-- This is a 10 point document.\n) (/usr/share/texlive/texmf-dist/tex/latex/cmap/cmap.sty)\n(/usr/share/texlive/texmf-dist/tex/latex/base/ifthen.sty)\n(/usr/share/texlive/texmf-dist/tex/latex/base/fontenc.sty\n(/usr/share/texlive/texmf-dist/tex/latex/base/t1enc.def)\n(/usr/share/texlive/texmf-dist/tex/latex/psnfss/t1ppl.fd)<<t1.cmap>>)\n(/usr/share/texlive/texmf-dist/tex/latex/base/inputenc.sty\n(/usr/share/texlive/texmf-dist/tex/latex/base/utf8.def\n(/usr/share/texlive/texmf-dist/tex/latex/base/t1enc.dfu)\n(/usr/share/texlive/texmf-dist/tex/latex/base/ot1enc.dfu)\n(/usr/share/texlive/texmf-dist/tex/latex/base/omsenc.dfu)))\n(/usr/share/texlive/texmf-dist/tex/latex/amsmath/amsmath.sty\nFor additional information on amsmath, use the `?' option.\n(/usr/share/texlive/texmf-dist/tex/latex/amsmath/amstext.sty\n(/usr/share/texlive/texmf-dist/tex/latex/amsmath/amsgen.sty))\n(/usr/share/texlive/texmf-dist/tex/latex/amsmath/amsbsy.sty)\n(/usr/share/texlive/texmf-dist/tex/latex/amsmath/amsopn.sty))\n(/usr/share/texlive/texmf-dist/tex/latex/caption/caption.sty\n(/usr/share/texlive/texmf-dist/tex/latex/caption/caption3.sty\n(/usr/share/texlive/texmf-dist/tex/latex/graphics/keyval.sty))\n\nPackage caption Warning: Unsupported document class (or package) detected,\n(caption)                usage of the caption package is not recommended.\nSee the caption package documentation for explanation.\n\n) (/usr/share/texlive/texmf-dist/tex/latex/float/float.sty) (./scipy.sty\n(./status.sty (./draftwatermark.sty (./everypage.sty)\n(/usr/share/texlive/texmf-dist/tex/latex/graphics/graphicx.sty\n(/usr/share/texlive/texmf-dist/tex/latex/graphics/graphics.sty\n(/usr/share/texlive/texmf-dist/tex/latex/graphics/trig.sty)\n(/usr/share/texlive/texmf-dist/tex/latex/graphics-cfg/graphics.cfg)\n(/usr/share/texlive/texmf-dist/tex/latex/graphics-def/pdftex.def)))\n(/usr/share/texlive/texmf-dist/tex/latex/graphics/color.sty\n(/usr/share/texlive/texmf-dist/tex/latex/graphics-cfg/color.cfg))))\n(/usr/share/texlive/texmf-dist/tex/latex/psnfss/mathptmx.sty)\n(/usr/share/texlive/texmf-dist/tex/latex/psnfss/helvet.sty)\n(/usr/share/texlive/texmf-dist/tex/latex/psnfss/courier.sty)\n(/usr/share/texlive/texmf-dist/tex/latex/amsfonts/amsfonts.sty)\n(/usr/share/texlive/texmf-dist/tex/latex/amsfonts/amssymb.sty)\n(/usr/share/texlive/texmf-dist/tex/latex/tools/bm.sty)\n(/usr/share/texlive/texmf-dist/tex/latex/hyperref/hyperref.sty\n(/usr/share/texlive/texmf-dist/tex/generic/oberdiek/hobsub-hyperref.sty\n(/usr/share/texlive/texmf-dist/tex/generic/oberdiek/hobsub-generic.sty))\n(/usr/share/texlive/texmf-dist/tex/generic/ifxetex/ifxetex.sty)\n(/usr/share/texlive/texmf-dist/tex/latex/oberdiek/auxhook.sty)\n(/usr/share/texlive/texmf-dist/tex/latex/oberdiek/kvoptions.sty)\n(/usr/share/texlive/texmf-dist/tex/latex/hyperref/pd1enc.def)\n(/usr/share/texlive/texmf-dist/tex/latex/latexconfig/hyperref.cfg)\n(/usr/share/texlive/texmf-dist/tex/latex/url/url.sty))\n(/usr/share/texlive/texmf-dist/tex/latex/hyperref/hpdftex.def\n(/usr/share/texlive/texmf-dist/tex/latex/oberdiek/rerunfilecheck.sty))\n\nPackage hyperref Warning: Option `pdftex' has already been used,\n(hyperref)                setting the option has no effect on input line 43.\n\n(/usr/share/texlive/texmf-dist/tex/latex/tools/longtable.sty)\n(/usr/share/texlive/texmf-dist/tex/latex/multirow/multirow.sty)\n(/usr/share/texlive/texmf-dist/tex/latex/booktabs/booktabs.sty)\n(/usr/share/texlive/texmf-dist/tex/latex/base/textcomp.sty\n(/usr/share/texlive/texmf-dist/tex/latex/base/ts1enc.def\n(/usr/share/texlive/texmf-dist/tex/latex/base/ts1enc.dfu)))\n(/usr/share/texlive/texmf-dist/tex/latex/upquote/upquote.sty)\n(/usr/share/texlive/texmf-dist/tex/latex/fancyvrb/fancyvrb.sty\nStyle option: `fancyvrb' v2.7a, with DG/SPQR fixes, and firstline=lastline fix \n<2008/02/07> (tvz))) (./paper.aux)\n(/usr/share/texlive/texmf-dist/tex/latex/base/ts1cmr.fd)\n(/usr/share/texlive/texmf-dist/tex/latex/psnfss/t1ptm.fd)\n-- Lines per column: 61 (exact).\n(/usr/share/texlive/texmf-dist/tex/latex/caption/ltcaption.sty)\n(/usr/share/texlive/texmf-dist/tex/context/base/mkii/supp-pdf.mkii\n[Loading MPS to PDF converter (version 2006.09.02).]\n) (/usr/share/texlive/texmf-dist/tex/latex/oberdiek/epstopdf-base.sty\n(/usr/share/texlive/texmf-dist/tex/latex/oberdiek/grfext.sty)\n(/usr/share/texlive/texmf-dist/tex/latex/latexconfig/epstopdf-sys.cfg))\n(/usr/share/texlive/texmf-dist/tex/latex/hyperref/nameref.sty\n(/usr/share/texlive/texmf-dist/tex/generic/oberdiek/gettitlestring.sty))\n(./paper.out) (./paper.out)\n(/usr/share/texlive/texmf-dist/tex/latex/psnfss/t1phv.fd)\n(/usr/share/texlive/texmf-dist/tex/latex/psnfss/ot1ztmcm.fd)<<ot1.cmap>>\n(/usr/share/texlive/texmf-dist/tex/latex/psnfss/omlztmcm.fd)<<oml.cmap>>\n(/usr/share/texlive/texmf-dist/tex/latex/psnfss/omsztmcm.fd)<<oms.cmap>>\n(/usr/share/texlive/texmf-dist/tex/latex/psnfss/omxztmcm.fd)<<omx.cmap>>\n(/usr/share/texlive/texmf-dist/tex/latex/psnfss/ot1ptm.fd)\n(/usr/share/texlive/texmf-dist/tex/latex/psnfss/upzd.fd)\n(/usr/share/texlive/texmf-dist/tex/latex/psnfss/ts1ptm.fd) (./page_numbers.tex)\n\nUnderfull \\hbox (badness 2970) in paragraph at lines 157--159\n\\T1/phv/b/n/8.03 Abstract\\T1/phv/m/n/8.03 ---The use of sev-eral open source sc\ni-en-tific pack-ages in the\n\nLaTeX Warning: No positions in optional float specifier.\n               Default added (so using `tbp') on input line 167.\n\n(/usr/share/texlive/texmf-dist/tex/latex/psnfss/t1pcr.fd)\n\nLaTeX Warning: No positions in optional float specifier.\n               Default added (so using `tbp') on input line 191.\n\n\nLaTeX Warning: Citation `Formats' on page 1 undefined on input line 201.\n\n[1{/var/lib/texmf/fonts/map/pdftex/updmap/pdftex.map}]\nUnderfull \\vbox (badness 1072) has occurred while \\output is active\nUnderfull \\vbox (badness 10000) has occurred while \\output is active [2 <./fig_\nscheme.png> <./fig_product.png>]\n\nLaTeX Warning: No positions in optional float specifier.\n               Default added (so using `tbp') on input line 247.\n\n\nLaTeX Warning: Citation `Scipy' on page 3 undefined on input line 268.\n\n\nLaTeX Warning: Citation `Deposition' on page 3 undefined on input line 273.\n\n\nLaTeX Warning: No positions in optional float specifier.\n               Default added (so using `tbp') on input line 295.\n\n\nUnderfull \\hbox (badness 10000) in paragraph at lines 290--298\n[]\\T1/ptm/m/n/9.53561 Recently we im-ple-mented con-vex anal-y-sis of\n\nUnderfull \\hbox (badness 7963) in paragraph at lines 290--298\n\\T1/ptm/m/n/9.53561 the stress strain curve (as de-scribed here [[]]).\n\nUnderfull \\hbox (badness 2057) in paragraph at lines 290--298\n\\T1/pcr/m/n/9.53561 scipy.optimize.minimize \\T1/ptm/m/n/9.53561 is used for a c\non-strained\n[3 <./fig_job_scheme.png>]\n\nLaTeX Warning: Citation `Matminer' on page 4 undefined on input  [...]

2022-07-01 21:25 UTC, afonari commented
@scoobies build status

2022-07-01 21:25 UTC, scoobies commented
{"afonari-2022-local"=>{"data"=>{"build_output"=>"[*] Updating proceedings build tools in {self.master_repo_path}...\nAlready up to date.\n[*] Check out paper repository...\nCloning into '/tmp/tmps8i_c7k5'...\nMoving proceedings build tools to temp directory...\n[*] Build the paper...\nBuilding: alexandr_fonari\n*** Warning: /tmp/tmps8i_c7k5/publisher/../output/alexandr_fonari/paper_stats.json does not exist.\nPDFLaTeX error output:\n================================================================================\nThis is pdfTeX, Version 3.14159265-2.6-1.40.18 (TeX Live 2017/Debian) (preloaded format=pdflatex)\n restricted \\write18 enabled.\nentering extended mode\n(./paper.tex\nLaTeX2e <2017-04-15>\nBabel <3.18> and hyphenation patterns for 3 language(s) loaded.\n(./IEEEtran.cls\nDocument Class: IEEEtran 2015/08/26 V1.8b by Michael Shell\n-- See the \"IEEEtran_HOWTO\" manual for usage information.\n-- http://www.michaelshell.org/tex/ieeetran/\n(/usr/share/texlive/texmf-dist/tex/latex/psnfss/ot1ppl.fd)\n-- Using IEEE Computer Society mode.\n-- Using 8.5in x 11in (letter) paper.\n-- Using PDF output.\n-- This is a 10 point document.\n) (/usr/share/texlive/texmf-dist/tex/latex/cmap/cmap.sty)\n(/usr/share/texlive/texmf-dist/tex/latex/base/ifthen.sty)\n(/usr/share/texlive/texmf-dist/tex/latex/base/fontenc.sty\n(/usr/share/texlive/texmf-dist/tex/latex/base/t1enc.def)\n(/usr/share/texlive/texmf-dist/tex/latex/psnfss/t1ppl.fd)<<t1.cmap>>)\n(/usr/share/texlive/texmf-dist/tex/latex/base/inputenc.sty\n(/usr/share/texlive/texmf-dist/tex/latex/base/utf8.def\n(/usr/share/texlive/texmf-dist/tex/latex/base/t1enc.dfu)\n(/usr/share/texlive/texmf-dist/tex/latex/base/ot1enc.dfu)\n(/usr/share/texlive/texmf-dist/tex/latex/base/omsenc.dfu)))\n(/usr/share/texlive/texmf-dist/tex/latex/amsmath/amsmath.sty\nFor additional information on amsmath, use the `?' option.\n(/usr/share/texlive/texmf-dist/tex/latex/amsmath/amstext.sty\n(/usr/share/texlive/texmf-dist/tex/latex/amsmath/amsgen.sty))\n(/usr/share/texlive/texmf-dist/tex/latex/amsmath/amsbsy.sty)\n(/usr/share/texlive/texmf-dist/tex/latex/amsmath/amsopn.sty))\n(/usr/share/texlive/texmf-dist/tex/latex/caption/caption.sty\n(/usr/share/texlive/texmf-dist/tex/latex/caption/caption3.sty\n(/usr/share/texlive/texmf-dist/tex/latex/graphics/keyval.sty))\n\nPackage caption Warning: Unsupported document class (or package) detected,\n(caption)                usage of the caption package is not recommended.\nSee the caption package documentation for explanation.\n\n) (/usr/share/texlive/texmf-dist/tex/latex/float/float.sty) (./scipy.sty\n(./status.sty (./draftwatermark.sty (./everypage.sty)\n(/usr/share/texlive/texmf-dist/tex/latex/graphics/graphicx.sty\n(/usr/share/texlive/texmf-dist/tex/latex/graphics/graphics.sty\n(/usr/share/texlive/texmf-dist/tex/latex/graphics/trig.sty)\n(/usr/share/texlive/texmf-dist/tex/latex/graphics-cfg/graphics.cfg)\n(/usr/share/texlive/texmf-dist/tex/latex/graphics-def/pdftex.def)))\n(/usr/share/texlive/texmf-dist/tex/latex/graphics/color.sty\n(/usr/share/texlive/texmf-dist/tex/latex/graphics-cfg/color.cfg))))\n(/usr/share/texlive/texmf-dist/tex/latex/psnfss/mathptmx.sty)\n(/usr/share/texlive/texmf-dist/tex/latex/psnfss/helvet.sty)\n(/usr/share/texlive/texmf-dist/tex/latex/psnfss/courier.sty)\n(/usr/share/texlive/texmf-dist/tex/latex/amsfonts/amsfonts.sty)\n(/usr/share/texlive/texmf-dist/tex/latex/amsfonts/amssymb.sty)\n(/usr/share/texlive/texmf-dist/tex/latex/tools/bm.sty)\n(/usr/share/texlive/texmf-dist/tex/latex/hyperref/hyperref.sty\n(/usr/share/texlive/texmf-dist/tex/generic/oberdiek/hobsub-hyperref.sty\n(/usr/share/texlive/texmf-dist/tex/generic/oberdiek/hobsub-generic.sty))\n(/usr/share/texlive/texmf-dist/tex/generic/ifxetex/ifxetex.sty)\n(/usr/share/texlive/texmf-dist/tex/latex/oberdiek/auxhook.sty)\n(/usr/share/texlive/texmf-dist/tex/latex/oberdiek/kvoptions.sty)\n(/usr/share/texlive/texmf-dist/tex/latex/hyperref/pd1enc.def)\n(/usr/share/texlive/texmf-dist/tex/latex/latexconfig/hyperref.cfg)\n(/usr/share/texlive/texmf-dist/tex/latex/url/url.sty))\n(/usr/share/texlive/texmf-dist/tex/latex/hyperref/hpdftex.def\n(/usr/share/texlive/texmf-dist/tex/latex/oberdiek/rerunfilecheck.sty))\n\nPackage hyperref Warning: Option `pdftex' has already been used,\n(hyperref)                setting the option has no effect on input line 43.\n\n(/usr/share/texlive/texmf-dist/tex/latex/tools/longtable.sty)\n(/usr/share/texlive/texmf-dist/tex/latex/multirow/multirow.sty)\n(/usr/share/texlive/texmf-dist/tex/latex/booktabs/booktabs.sty)\n(/usr/share/texlive/texmf-dist/tex/latex/base/textcomp.sty\n(/usr/share/texlive/texmf-dist/tex/latex/base/ts1enc.def\n(/usr/share/texlive/texmf-dist/tex/latex/base/ts1enc.dfu)))\n(/usr/share/texlive/texmf-dist/tex/latex/upquote/upquote.sty)\n(/usr/share/texlive/texmf-dist/tex/latex/fancyvrb/fancyvrb.sty\nStyle option: `fancyvrb' v2.7a, with DG/SPQR fixes, and firstline=lastline fix \n<2008/02/07> (tvz))) (./paper.aux)\n(/usr/share/texlive/texmf-dist/tex/latex/base/ts1cmr.fd)\n(/usr/share/texlive/texmf-dist/tex/latex/psnfss/t1ptm.fd)\n-- Lines per column: 61 (exact).\n(/usr/share/texlive/texmf-dist/tex/latex/caption/ltcaption.sty)\n(/usr/share/texlive/texmf-dist/tex/context/base/mkii/supp-pdf.mkii\n[Loading MPS to PDF converter (version 2006.09.02).]\n) (/usr/share/texlive/texmf-dist/tex/latex/oberdiek/epstopdf-base.sty\n(/usr/share/texlive/texmf-dist/tex/latex/oberdiek/grfext.sty)\n(/usr/share/texlive/texmf-dist/tex/latex/latexconfig/epstopdf-sys.cfg))\n(/usr/share/texlive/texmf-dist/tex/latex/hyperref/nameref.sty\n(/usr/share/texlive/texmf-dist/tex/generic/oberdiek/gettitlestring.sty))\n(./paper.out) (./paper.out)\n(/usr/share/texlive/texmf-dist/tex/latex/psnfss/t1phv.fd)\n(/usr/share/texlive/texmf-dist/tex/latex/psnfss/ot1ztmcm.fd)<<ot1.cmap>>\n(/usr/share/texlive/texmf-dist/tex/latex/psnfss/omlztmcm.fd)<<oml.cmap>>\n(/usr/share/texlive/texmf-dist/tex/latex/psnfss/omsztmcm.fd)<<oms.cmap>>\n(/usr/share/texlive/texmf-dist/tex/latex/psnfss/omxztmcm.fd)<<omx.cmap>>\n(/usr/share/texlive/texmf-dist/tex/latex/psnfss/ot1ptm.fd)\n(/usr/share/texlive/texmf-dist/tex/latex/psnfss/upzd.fd)\n(/usr/share/texlive/texmf-dist/tex/latex/psnfss/ts1ptm.fd) (./page_numbers.tex)\n\nUnderfull \\hbox (badness 2970) in paragraph at lines 157--159\n\\T1/phv/b/n/8.03 Abstract\\T1/phv/m/n/8.03 ---The use of sev-eral open source sc\ni-en-tific pack-ages in the\n\nLaTeX Warning: No positions in optional float specifier.\n               Default added (so using `tbp') on input line 167.\n\n(/usr/share/texlive/texmf-dist/tex/latex/psnfss/t1pcr.fd)\n\nLaTeX Warning: No positions in optional float specifier.\n               Default added (so using `tbp') on input line 191.\n\n\nLaTeX Warning: Citation `Formats' on page 1 undefined on input line 201.\n\n[1{/var/lib/texmf/fonts/map/pdftex/updmap/pdftex.map}]\nUnderfull \\vbox (badness 1072) has occurred while \\output is active\nUnderfull \\vbox (badness 10000) has occurred while \\output is active [2 <./fig_\nscheme.png> <./fig_product.png>]\n\nLaTeX Warning: No positions in optional float specifier.\n               Default added (so using `tbp') on input line 247.\n\n\nLaTeX Warning: Citation `Scipy' on page 3 undefined on input line 268.\n\n\nLaTeX Warning: Citation `Deposition' on page 3 undefined on input line 273.\n\n\nLaTeX Warning: No positions in optional float specifier.\n               Default added (so using `tbp') on input line 295.\n\n\nUnderfull \\hbox (badness 10000) in paragraph at lines 290--298\n[]\\T1/ptm/m/n/9.53561 Recently we im-ple-mented con-vex anal-y-sis of\n\nUnderfull \\hbox (badness 7963) in paragraph at lines 290--298\n\\T1/ptm/m/n/9.53561 the stress strain curve (as de-scribed here [[]]).\n\nUnderfull \\hbox (badness 2057) in paragraph at lines 290--298\n\\T1/pcr/m/n/9.53561 scipy.optimize.minimize \\T1/ptm/m/n/9.53561 is used for a c\non-strained\n[3 <./fig_job_scheme.png>]\n\nLaTeX Warning: Citation `Matminer' on page 4 undefined on input  [...]

2022-07-01 21:27 UTC, afonari commented
@scoobies check references

2022-07-01 21:27 UTC, scoobies commented
```
Reference check summary (note 'MISSING' DOIs are suggestions that need verification):

OK DOIs

- 10.3389/fchem.2021.800370 is OK
- 10.3389/fchem.2021.800371 is OK
- 10.1103/RevModPhys.65.599 is OK
- 10.1088/2515-7639/ab084b is OK
- 10.1063/5.0043300 is OK
- 10.1016/j.cpc.2019.106949 is OK
- 10.1016/j.commatsci.2018.05.018 is OK
- 10.4155/fmc-2016-0093 is OK
- 10.1038/s43586-021-00074-7 is OK
- 10.1107/S0021889891012104 is OK
- 10.2514/6.2018-0927 is OK
- 10.1038/s41592-019-0686-2 is OK
- 10.1109/SC.2014.9 is OK
- 10.1021/acsapm.0c00524 is OK
- 10.1021/acs.jpca.9b10998 is OK
- 10.1002/qua.24481 is OK
- 10.1088/1361-648X/aa8f79 is OK
- 10.1103/PhysRevB.77.224115 is OK
- 10.1107/S2052520616003954 is OK
- 10.1088/1361-648X/aa680e is OK
- 10.1002/0471721204.ch8 is OK
- 10.5281/ZENODO.6605135 is OK
- 10.1186/1758-2946-3-33 is OK
- 10.1038/s41597-020-00638-4 is OK
- 10.1016/j.commatsci.2012.10.028 is OK

MISSING DOIs

- 10.1039/c6ee02697d may be a valid DOI for title: Holistic computational structure screening of more than 12000 candidates for solid lithium-ion conductor materials

INVALID DOIs

- None
```

2022-07-01 21:28 UTC, afonari commented on papers/alexandr_fonari/alexandr_fonari.rst
> +   A: MPO score of all materials in the HTL dataset. B: Those used in the training set as a function of the hole reorganization energy - :math:`\lambda_h`. :label:`figalplot`
Fixed.

2022-07-01 21:29 UTC, afonari commented on papers/alexandr_fonari/alexandr_fonari.rst
> +   A: MPO score of all materials in the HTL dataset. B: Those used in the training set as a function of the hole reorganization energy - :math:`\lambda_h`. :label:`figalplot`
> I wonder if the marker size could be reduced, or if partially transparent points would help indicate regions of high density.

Will ask the author, but lower probability, resolving for now.

2022-07-01 21:33 UTC, afonari commented on papers/alexandr_fonari/alexandr_fonari.rst
> +Due to the large chemical and manipulation space of the materials, sometimes it very tricky to keep code for all workflows follow the same code logic.
Updated the sentence, thanks. I see what you are suggesting, will think about this, resolving for now.

2022-07-01 22:23 UTC, afonari commented on papers/alexandr_fonari/alexandr_fonari.rst
> +References
Switched to bibtex.

2022-07-01 22:24 UTC, afonari commented on papers/alexandr_fonari/alexandr_fonari.rst
> +   Left: The uniaxial stress/strain curve of a polymer calculated using Desmond through the stress strain workflow, grey band indicates inflection point (yield)). Right: Constant strain simulation wi
Updated the figure, updated the label, thanks.

2022-07-02 10:17 UTC, afonari commented
@scoobies check references

2022-07-02 10:18 UTC, scoobies commented
```
Reference check summary (note 'MISSING' DOIs are suggestions that need verification):

OK DOIs

- 10.3389/fchem.2021.800370 is OK
- 10.3389/fchem.2021.800371 is OK
- 10.1103/RevModPhys.65.599 is OK
- 10.1088/2515-7639/ab084b is OK
- 10.1063/5.0043300 is OK
- 10.1016/j.cpc.2019.106949 is OK
- 10.1039/c6ee02697d is OK
- 10.1016/j.commatsci.2018.05.018 is OK
- 10.4155/fmc-2016-0093 is OK
- 10.1038/s43586-021-00074-7 is OK
- 10.1107/S0021889891012104 is OK
- 10.2514/6.2018-0927 is OK
- 10.1038/s41592-019-0686-2 is OK
- 10.1109/SC.2014.9 is OK
- 10.1021/acsapm.0c00524 is OK
- 10.1021/acs.jpca.9b10998 is OK
- 10.1002/qua.24481 is OK
- 10.1088/1361-648X/aa8f79 is OK
- 10.1103/PhysRevB.77.224115 is OK
- 10.1107/S2052520616003954 is OK
- 10.1088/1361-648X/aa680e is OK
- 10.1002/0471721204.ch8 is OK
- 10.5281/ZENODO.6605135 is OK
- 10.1186/1758-2946-3-33 is OK
- 10.1038/s41597-020-00638-4 is OK
- 10.1016/j.commatsci.2012.10.028 is OK

MISSING DOIs

- None

INVALID DOIs

- None
```

2022-07-03 07:32 UTC, mepa commented
Hi @afonari, thanks so much for converting the refs to bibtex and for checking the references. The formatting and references look good to me. Please consider [citing numpy](https://numpy.org/citing-numpy/), if you feel it's appropriate.

And thanks to @bdice and @wdzhou for the thorough and courteous reviews of this paper!

2022-07-03 07:33 UTC, mepa commented
@scoobies mark ready

2022-07-03 21:25 UTC, afonari commented
> Please consider citing numpy, if you feel it's appropriate.

Sure, done.

2022-07-03 21:25 UTC, afonari commented
@scoobies check references

2022-07-03 21:26 UTC, scoobies commented
```
Reference check summary (note 'MISSING' DOIs are suggestions that need verification):

OK DOIs

- 10.3389/fchem.2021.800370 is OK
- 10.3389/fchem.2021.800371 is OK
- 10.1103/RevModPhys.65.599 is OK
- 10.1088/2515-7639/ab084b is OK
- 10.1063/5.0043300 is OK
- 10.1016/j.cpc.2019.106949 is OK
- 10.1039/c6ee02697d is OK
- 10.1016/j.commatsci.2018.05.018 is OK
- 10.4155/fmc-2016-0093 is OK
- 10.1038/s43586-021-00074-7 is OK
- 10.1107/S0021889891012104 is OK
- 10.2514/6.2018-0927 is OK
- 10.1038/s41592-019-0686-2 is OK
- 10.1109/SC.2014.9 is OK
- 10.1021/acsapm.0c00524 is OK
- 10.1021/acs.jpca.9b10998 is OK
- 10.1002/qua.24481 is OK
- 10.1088/1361-648X/aa8f79 is OK
- 10.1103/PhysRevB.77.224115 is OK
- 10.1107/S2052520616003954 is OK
- 10.1088/1361-648X/aa680e is OK
- 10.1002/0471721204.ch8 is OK
- 10.5281/ZENODO.6605135 is OK
- 10.1186/1758-2946-3-33 is OK
- 10.1038/s41597-020-00638-4 is OK
- 10.1016/j.commatsci.2012.10.028 is OK
- 10.1038/s41586-020-2649-2 is OK

MISSING DOIs

- None

INVALID DOIs

- None
```

2022-07-06 12:09 UTC, merged