DRAFT: Paper: GeoCAT
scipy-conference/scipy_proceedings pull request #686
Opened 2022-05-17 16:09 UTC by erogluorhan

Draft for now, aimed at generating the PDF only.

If you are creating this PR in order to submit a draft of your paper,
see http://procbuild.scipy.org/ for logs generated by the build
process.

See the [project readme](https://github.com/scipy-conference/scipy_proceedings#build-your-paper)
for more information.

*Editor*:  

*Reviewers*:

2022-05-17 16:09 UTC, scoobies commented
Hi!, I'm @scoobies, a friendly bot.

Type ```@scoobies help``` to discover how I can help you.

2022-05-29 20:06 UTC, deniederhut commented
@scoobies mark paper

2022-05-29 20:06 UTC, deniederhut commented
@scoobies build status

2022-05-29 20:06 UTC, scoobies commented
{"erogluorhan-2022"=>{"data"=>{"build_output"=>"[*] Updating proceedings build tools in {self.master_repo_path}...\nAlready up to date.\n[*] Check out paper repository...\nCloning into '/tmp/tmpa02xgi3u'...\nMoving proceedings build tools to temp directory...\n[*] Build the paper...\nBuilding: orhan_eroglu\n*** Warning: /tmp/tmpa02xgi3u/publisher/../output/orhan_eroglu/paper_stats.json does not exist.\n", "build_pdf_path"=>"/procbuild/procbuild/../cache/erogluorhan-2022.pdf", "build_status"=>"success", "build_timestamp"=>"28/05 15:46"}, "status"=>"success"}}

2022-05-29 20:06 UTC, deniederhut commented
@scoobies mark needs review

2022-05-29 20:06 UTC, deniederhut commented
@scoobies assign @cbcunc as editor

2022-05-29 20:06 UTC, scoobies commented
Assigned! @cbcunc is now the editor

2022-05-31 15:36 UTC, mepa commented
@scoobies add @RBhupi to reviewers

2022-05-31 15:36 UTC, scoobies commented
@RBhupi added to the reviewers list!

2022-06-02 00:07 UTC, cbcunc commented
Editor confirms paper builds.

2022-06-07 02:31 UTC, deniederhut commented
Hi! We've moved the deadline for first reviews back one week, to June 16th, to give us a little more time to find reviewers for all the papers this year. You can see the updated full timeline at https://github.com/scipy-conference/scipy_proceedings#timeline-for-2022.

2022-06-08 01:29 UTC, deniederhut commented
@scoobies add @TomNicholas to reviewers

2022-06-08 01:29 UTC, scoobies commented
@TomNicholas added to the reviewers list!

2022-06-08 05:20 UTC, RBhupi commented on papers/orhan_eroglu/00_geocat.rst
> +Replicating NCL’s computational routines in Python, (2) training and support for
The geoCAT blog posts and documentation suggest that a lot of development has been made in achieving the first goal of geoCAT. In the following section (GeoCAT Software), please consider providing more quantitative details of the development since the ‘Pivot to python’. For example, 'the WRF functions, interpolation, and plotting functions are 100% completed while functions in the categories of thermodynamics are x of y finished'.  A quantitative measure of the progress of GeoCAT should give a good idea of what has been achieved and what remains. This will also help identify and discuss the specific topics where GeoCAT needs support from the python community.

2022-06-11 20:26 UTC, deniederhut commented
@scoobies mark needs more review

2022-06-12 04:57 UTC, RBhupi requested changes
The paper discusses the development of the python GeoCAT toolkit established to provide a python alternative to NCL users in the geoscience community. The authors provided an overview of their CI/CD practices, documentation, and source code links, as well as a description of the geoCAT components, and community engagement efforts. The geoCAT blog posts and documentation suggest that a lot of development has been made in achieving the first goal of GeoCAT. The paper also shows NCL-like plotting ability with examples. 
Other developers in the SciPy community, will value the specific examples of learning experiences of the GeoCAT team while porting the NCL to python. Overall the paper is well written however, the sections “Introduction” and  “GeoCAT Software” will benefit from more specific and concrete words and details in the description of the tools. Please check the specific comments.

2022-06-12 04:57 UTC, RBhupi commented on papers/orhan_eroglu/00_geocat.rst
> +GeoCAT-examples (and GeoCAT-viz)
Why is geoCAT-example considered as a tool while it is actually the documentation of geoCAT tools?

2022-06-12 04:57 UTC, RBhupi commented on papers/orhan_eroglu/00_geocat.rst
> +WRF-Python
Why is WRF-Python not part of Fig 3?

2022-06-12 04:57 UTC, RBhupi commented on papers/orhan_eroglu/00_geocat.rst
> +However, there are others that are implemented in Fortran but wrapped up
NumPy is superfast for most computations. Any reason to choose FORTRAN for some task?

2022-06-12 04:57 UTC, RBhupi commented on papers/orhan_eroglu/00_geocat.rst
> +- Meteorological variables such as relative humidity, dew-point temperature,
'Meteorological variables' Did you mean 'Meteorological functions' to compute the listed variables?

2022-06-12 04:57 UTC, RBhupi commented on papers/orhan_eroglu/00_geocat.rst
> +LOC requirements for most of the visualization examples to comparable
As stated above the Matplotlib and Cartopy (M&C) takes 100s of LOC while NCL and GeoCAT only take 10s. Providing LOC count for M&C, NCL, and Geocat for the shown examples will strengthen this argument.

2022-06-12 04:57 UTC, RBhupi commented on papers/orhan_eroglu/00_geocat.rst
> +GeoCAT has created several, now-established, Python tools that are hosted and
This sentence can be broken into two or be shortened. Consider "GeoCAT has six(or seven) Python tools for geoscientific computation and visualization which are built on Pangeo packages such as Xarray, and Dass, as well as Jupyter Notebooks."

2022-06-12 04:57 UTC, RBhupi commented on papers/orhan_eroglu/00_geocat.rst
> +machine codes in order to get faster executions wherever possible.
The above paragraph is trying to explain too many technical aspects of several tools and dependencies, but it is difficult to comprehend by the non-developers. Therefore, I may have misunderstood this completely. Consider adding a diagram to make this paragraph more readable.

2022-06-12 04:57 UTC, RBhupi commented on papers/orhan_eroglu/00_geocat.rst
> +   GeoCAT project structure with all of the software tools
The tool GeoCAT-datafiles is not explained in the paper.

2022-06-12 05:57 UTC, RBhupi commented on papers/orhan_eroglu/00_geocat.rst
> +.. figure:: figures/fig3_structure.png
I think this flowchart is complicated due to the groupings of the tools that don't group together nicely. I assume, GeoCAT-datafiles is IO, not visualization, and GeoCAT-examples are applications of the python tools, they are not tools themselves. Most example scripts have NCL-like Read-Compute-Visualize structure. See if the attached call graph makes sense 
![GeoCAT1](https://user-images.githubusercontent.com/2460536/173217819-48d0e0aa-df2b-4286-8dcc-c7c124903366.png)

2022-06-16 00:06 UTC, deniederhut commented
Hey @TomNicholas ! Friendly reminder that reviews are due tomorrow

2022-06-17 04:50 UTC, TomNicholas reviewed
Thanks to the authors for this contribution, I'm sure GeoCAT will be useful to many users on a regular basis.

I've made a few specific comments, but overall I think the manuscript is clear, representative, and detailed.

2022-06-17 04:50 UTC, TomNicholas commented on papers/orhan_eroglu/00_geocat.rst
> +supporting Xarray and NumPy data arrays. Therefore, the GeoCAT functions can
**Minor nitpick**: This is not quite accurate - technically there is no such object as a "Dask DataArray". 

Rather, `xarray.DataArray` objects can wrap either `dask.Array` objects or `numpy.ndarray` objects. A "chunked xarray DataArray" is an example of the former. The portmanteau "DataArray" is only used to describe xarray objects, and means something different from "data array", which could be referring to any number of types.

This distinction can be important as other parts of the ecosystem work a little differently - there is for example a "Dask Dataframe". It also matters when one wants to start composing with other array types - as for example we do with [`pint-xarray`](https://github.com/xarray-contrib/pint-xarray).

It would be more correct to speak of "dask-backed xarray DataArrays", "dask arrays", or "numpy arrays".

2022-06-17 04:50 UTC, TomNicholas commented on papers/orhan_eroglu/00_geocat.rst
> +that are directly related to the software development lifecycle are publicly
It would be nice to define the term "open development" earlier in the manuscript, because I was distracted wondering exactly what it meant (and if it was different from open-source) until I got here.

2022-06-17 04:50 UTC, TomNicholas commented on papers/orhan_eroglu/00_geocat.rst
> +inform the community. The annual Scientific Computing with Python (SciPy)
Grammar - should be "the GeoCAT team has presented at" or similar.

2022-06-17 04:50 UTC, TomNicholas commented on papers/orhan_eroglu/00_geocat.rst
> +GeoCAT has created the Xarray-based Uxarray package :cite:`uxarrayrepo` to
Do you want to add uxarray to [xarray's ecosystem list?!](https://github.com/pydata/xarray/blob/main/doc/ecosystem.rst)

2022-06-17 04:50 UTC, TomNicholas commented on papers/orhan_eroglu/00_geocat.rst
> +for big data geoscience) packages such as Xarray :cite:`xarray17`, Dask
I would separate out the sentence about pangeo to make this text clearer. 

"GeoCAT builds upon (or arguably is a member of) the Pangeo ecosystem. In particular it relies upon xarray, ..."

2022-06-17 04:50 UTC, TomNicholas commented on papers/orhan_eroglu/00_geocat.rst
> +data (e.g. ~3 km data rendered within a few tens of seconds to a few minutes on
I would like to know more about how you do interactive plotting of high-resolution datasets. How does this work? Are the values to be displayed lazily re-computed with dask.delayed objects? Can matplotlib actually handle large images?

This is a space in which there are lots of exciting new tools (e.g. datashader and the holoviews ecosystem), but you only mention matplotlib as a plotting backend.

2022-06-17 04:50 UTC, TomNicholas commented on papers/orhan_eroglu/00_geocat.rst
> +  heat index, saturation vapor pressure, and more
This functionality seems like it would have significant crossover with [MetPy](https://github.com/Unidata/MetPy). Is there scope for joining forces there?

2022-06-17 04:50 UTC, TomNicholas commented on papers/orhan_eroglu/00_geocat.rst
> +However, there are others that are implemented in Fortran but wrapped up
Presumably wrapping existing fortran functions so that they could be called from python (using [f2py](https://numpy.org/doc/stable/f2py/index.html)) was easier than re-implementing those functions in python.

2022-06-17 04:50 UTC, TomNicholas commented on papers/orhan_eroglu/00_geocat.rst
> +examples as well as improtant infrastructural changes were made available
This is great - do you have links to the output of those summer projects?

2022-06-18 01:57 UTC, deniederhut commented
Thanks Tom!

2022-06-18 01:57 UTC, deniederhut commented
@scoobies mark pending comment

2022-06-23 19:03 UTC, erogluorhan commented
Hi @RBhupi and @TomNicholas , thank you very much for your great review! We are currently reading through your comments and will soon provide our revisions and responses here.

2022-06-24 21:08 UTC, cbcunc requested changes

2022-06-24 21:08 UTC, cbcunc commented on papers/orhan_eroglu/references.bib
> +@misc{pivot19,
Please include a DOI for each citation wherever humanly possible.

2022-06-26 13:23 UTC, erogluorhan commented on papers/orhan_eroglu/00_geocat.rst
> +Replicating NCL’s computational routines in Python, (2) training and support for
Thanks very much for this suggestion! Please see this [commit] in which we attempted to address the recommended additions.

2022-06-26 13:49 UTC, erogluorhan commented on papers/orhan_eroglu/00_geocat.rst
> +GeoCAT-examples (and GeoCAT-viz)
GeoCAT-examples is not actually the documentation of the GeoCAT tools. Instead, it is the visualization component of the GeoCAT umbrella, and it not only houses more than 140 plotting scripts and several GeoCAT-comp example visualizations, but also provides high level wrapper functions on top of matplotlib and cartopy with the help of GeoCAT-viz. We thought we put this decription clearly int the paper, but please let us know if you think some specific statements from the manuscript leads the reader to think GeoCAT-examples is for GeoCAT documentation.

2022-06-26 14:13 UTC, erogluorhan commented on papers/orhan_eroglu/00_geocat.rst
> +However, there are others that are implemented in Fortran but wrapped up
Thanks, @TomNicholas, that was exactly how we initially approached some of the implementation cases. @RBhupi , to make this clarified, we added some details in this [commit](https://github.com/scipy-conference/scipy_proceedings/pull/686/commits/58f440bbc5dbd5d53542bccc461deb6f8f3ba2ab). Please let us know if that suffice or not.

2022-06-26 14:18 UTC, erogluorhan commented on papers/orhan_eroglu/00_geocat.rst
> +- Meteorological variables such as relative humidity, dew-point temperature,
Thanks for catching this! Now corrected to "Meteorological variable computations"

2022-06-26 16:33 UTC, RBhupi approved these changes
Nice! Now, these statements are more concrete.

2022-06-26 16:33 UTC, RBhupi approved these changes

2022-06-26 16:34 UTC, RBhupi approved these changes

2022-06-28 14:58 UTC, erogluorhan commented on papers/orhan_eroglu/00_geocat.rst
> +   GeoCAT project structure with all of the software tools
Added now, please see the commit [c02e915](https://github.com/scipy-conference/scipy_proceedings/pull/686/commits/c02e9151cc2760792622996aa8a95874470ae87f) (We originally thought it was a lightweight data storage and access tool, and we shouldn't add it to the manuscript, but we agree it is best to mention it shortly for the sake of comprehension).

2022-06-28 14:59 UTC, erogluorhan commented on papers/orhan_eroglu/00_geocat.rst
> +GeoCAT has created several, now-established, Python tools that are hosted and
Thanks for the suggestion, we made changes as recommended.

2022-06-28 15:07 UTC, RBhupi commented on papers/orhan_eroglu/00_geocat.rst
> +GeoCAT has seven Python tools for geoscientific computation and visualization,
GeoCAT Python tools for geoscientific computation and visualization are built on cornerstone Pangeo :cite:`pangeo18` packages such as Xarray :cite:`xarray17`, and Dask :cite:`dask15`, as well as Jupyter Notebooks.

2022-06-29 19:24 UTC, cbcunc commented
Reviewers, please give your final recommendations. The deadline for final review comments is tomorrow.

Authors, please respond to review comments with changes or comments which resolve the conversation. Final acceptance decisions are July 4.

2022-06-29 20:18 UTC, erogluorhan commented on papers/orhan_eroglu/00_geocat.rst
> +supporting Xarray and NumPy data arrays. Therefore, the GeoCAT functions can
Thanks very much for catching this and providing a thorough clarification! We addressed this suggestion; please let us know if you suggest further terminology clarification here.

2022-06-29 20:27 UTC, erogluorhan commented on papers/orhan_eroglu/00_geocat.rst
> +that are directly related to the software development lifecycle are publicly
Thanks! We now moved the definition to the abstract, and we believe both parts (abstract and open development section) now can provide better understanding.

2022-06-29 20:35 UTC, erogluorhan commented on papers/orhan_eroglu/00_geocat.rst
> +inform the community. The annual Scientific Computing with Python (SciPy)
Fixed now, thanks!

2022-06-29 20:37 UTC, erogluorhan commented on papers/orhan_eroglu/00_geocat.rst
> +GeoCAT has created the Xarray-based Uxarray package :cite:`uxarrayrepo` to
That would be great! Even GeoCAT-comp could be a good candidate to be listed there.

2022-06-29 20:42 UTC, erogluorhan commented on papers/orhan_eroglu/00_geocat.rst
> +for big data geoscience) packages such as Xarray :cite:`xarray17`, Dask
Tried to address this, also combining with @RBhupi 's previous recommendation. Please let us know if the current structure of sentences does not work.

2022-06-29 21:01 UTC, erogluorhan commented on papers/orhan_eroglu/00_geocat.rst
> +data (e.g. ~3 km data rendered within a few tens of seconds to a few minutes on
We achieved this via Datashader and Holoviews actually. Our original plan was to put a separate section to this manuscript about that visualization work actually. Let us see if we can put together such a section during this review cycle. Would that be acceptable for you?

In the meantime, to clarify: The one significant work was for visualizing unstructured MPAS data. with Matplotlib, we were required to run much costly Delaunay triangulation on a set of about 43M data points that ended up  taking forever without an output. We made use of the connectivity (face-to-node connectivity) information that comes from the MPAS dataset and constructed Datashader triangular meshes and got them rendered. It was very much efficient (e.g. took a few minutes on a decent laptop, even without any Dask parallelization).

We put some of this details into the manuscript now to address your questions here, but it'd be great oto have a specific section and maybe visualization about this work if time permits.

2022-06-30 16:01 UTC, erogluorhan commented on papers/orhan_eroglu/00_geocat.rst
> +  heat index, saturation vapor pressure, and more
Thanks for bringing this to attention! Yes, we are aware of this, and we have even joined forces to some extent so far: e.g. we migrated our own skewt parameters calculation to MetPy as we thought it was a better address for that, and we used a few functions from MetPy such as one dimensional interpolation to solve a more problem-specific case (hybrid to pressure level interpolation) etc. 

Further collaboration would definitely be possible and useful for the community though.

2022-06-30 19:26 UTC, erogluorhan commented on papers/orhan_eroglu/00_geocat.rst
> +examples as well as improtant infrastructural changes were made available
Thanks for asking! 

We have now added the references to the SIParCS efforts' publications at AMS and AGU. Other than that, the actual contributions of our past SIParCS interns have been deployed in our tools such as GeoCAT-comp and GeoCAT-examples. Since they are many, we can't think of an easy way to providing links to them; however, checking the GitHub records and stats to our repositories for dates between May and August for years 2020, 2021, and 2022 can show what contributions were made by our interns. We can also find a few NCAR presentations our interns gave at the end of their internship. We didn't think it'd be good to put them into the manuscript, but please let us know if you' d like to  see them (We can provide in this conversation).

2022-06-30 21:43 UTC, erogluorhan commented on papers/orhan_eroglu/references.bib
> +@misc{pivot19,
Thanks very much for reminding this! We have added several DOIs now. Please see the [6abdf11](https://github.com/scipy-conference/scipy_proceedings/pull/686/commits/6abdf113d11bc168b0369bf71e55ca5674b4b1f5) commit to see those added.

2022-06-30 23:04 UTC, RBhupi commented
Thank you Co-Chairs @mepa @cbcunc @deniederhut @stargaser for inviting me to review the paper.

Independent Review Report
=========================

Reviewer: Bhupendra A. Raut

Department/Center/Division: Northwestern-Argonne Institute of Science and Engineering.

Institution/University/Company: Northwestern University.

Field of interest/expertise: Tropical Meteorology, Radar, and Sattelite Data Analysis.

Country: USA


Article reviewed:  The Geoscience Community Analysis Toolkit: An Open Development, Community Driven Toolkit in the Scientific Python Ecosystem


GENERAL EVALUATION
------------------
The paper presents the current status of the python GeoCAT toolkit, established to provide a python alternative to NCL users in the geoscience community. The paper is relevant to the SciPy topics and contains some new details relevant to the geoscience community. The presentation is clear, and the length of the paper and figure captions are as per Scipy guidelines. The title and the abstract are pertinent and readable.
The authors provided an overview of the geoCAT components, plotting ability with examples, and community engagement efforts. The authors are already making relevant changes suggested by the reviewers. This paper can be the beginning of the collaboration between GeoCAT and the MetPy community. Therefore, I recommend the publication of the paper in the SciPy-2022 proceedings.

- Quality of the approach: meets
- Quality of the writing: meets
- Quality of the figures/tables: meets


SPECIFIC EVALUATION
-------------------

For the following questions, please respond with 'yes' or 'no'.  If you answer 'no',  please provide a brief, one- to two-sentence explanation.

 - Is the code made publicly available and does the article  sufficiently describe how to access it?   
   > 'yes'

- Does the article present the problem in an appropriate context?
  Specifically, does it:

  - explain why the problem is important, 
  >yes
  - describe in which situations it arises,
  >yes
  - outline relevant previous work, 
  >yes
  - provide background information for non-experts
  > yes

- Is the content of the paper accessible to a computational scientist
  with no specific knowledge in the given field? 
  >yes

- Does the paper describe a well-formulated scientific or technical
  achievement? 
  >Yes. The project is ongoing and requires community engagement to achieve some of the objectives.

- Are the technical and scientific decisions well-motivated and
  clearly explained?
  > yes

- Are the code examples (if any) sound, clear, and well-written?
  > No code examples in the paper.

- Is the paper factually correct?
  > yes

- Is the language and grammar of sufficient quality?
  > yes

- Are the conclusions justified?
  > yes

- Is prior work properly and fully cited?
  > yes

- Should any part of the article be shortened or expanded? Please explain.
  > No.
- In your view, is the paper fit for publication in the conference proceedings?
  > yes 
- Please suggest specific improvements and indicate whether you think the article needs a significant rewrite (rather than a minor revision).
  > No

2022-07-01 12:57 UTC, erogluorhan commented on papers/orhan_eroglu/00_geocat.rst
> +LOC requirements for most of the visualization examples to comparable
Thanks for asking this! We have now added text to make a comparison. 

FYI: Taylor diagram scripts in GeoCAT-examples, for instance, were never implemented by using directly the M&C functions (i.e. they were implemented using our GeoCAT-viz functions). Almost all of the others are the same (GeoCAT-viz and GeoCAT-examples efforts were simultaneously born as the result of a multiple day hacakthon in 2020). Therefore, giving an exact number for replicated NCL examples using direct M&C codes is not easy, but we did our best to give a good example of where it would end up if we did. 

Please let us know if it requires further examples/clarification.

2022-07-01 16:56 UTC, erogluorhan commented on papers/orhan_eroglu/00_geocat.rst
> +machine codes in order to get faster executions wherever possible.
We have added Fig 1 (the newer first figure in the paper) in an attempt to ease the understanding of the roles of those technologies. We hope it helps a bit.

2022-07-01 21:22 UTC, cbcunc commented
@TomNicholas Your final review comments are due today. Do you mark this as resolved or not?

2022-07-01 21:24 UTC, cbcunc commented on papers/orhan_eroglu/references.bib
> +@misc{pivot19,
We still need either a DOI, an ISSN, or a URL for all citations. Final edits are due July 4.

2022-07-02 13:56 UTC, erogluorhan commented on papers/orhan_eroglu/00_geocat.rst
> +.. figure:: figures/fig3_structure.png
You're right; thanks for catching this! We updated the flowchart (also to address the lack of WRF-Python and UXarray from the flowchart)

2022-07-02 13:57 UTC, erogluorhan commented on papers/orhan_eroglu/00_geocat.rst
> +WRF-Python
Now updated the Figure (it's now Figure 4) and added WRF-Python as well as Project Raijin.

2022-07-02 14:17 UTC, erogluorhan commented on papers/orhan_eroglu/references.bib
> +@misc{pivot19,
Hi, there are a few types of citations in our bibliography. 

- For all of the online sources, we are providing URLs, and for some fo them, we are also providing DOIs.  

- For proceedings and journal papers, we are using however their bibtex comes from Google Scholar. For many of these types of publications, neither Google Scholar nor the publishers themselves seem to be providing DOI or ISSN. For example:

 ```
@inproceedings{clyne2021project,
   title={Project Raijin: Community Geoscience Analysis Tools for Unstructured Grids},
   author={Clyne, John and Eroglu, Orhan and Medeiros, Brian and Zarzycki, Colin M},
   booktitle={AGU Fall Meeting 2021},
   year={2021},
   organization={AGU}
 }
```

[AGU](https://agu.confex.com/agu/fm21/meetingapp.cgi/Paper/901711) does not provide any ISSN or DOI for this proceedings publication as far as we know. 

Therefore, we are struggling to address "either a DOI, an ISSN, or a URL for all citations".

Could you please clarify, or maybe exemplify this from a specific citation from our manuscript?

2022-07-02 16:59 UTC, TomNicholas commented on papers/orhan_eroglu/00_geocat.rst
> +data (e.g. ~3 km data rendered within a few tens of seconds to a few minutes on
That's interesting, thank you. I think it would be nice to devote a section to this if you have time, but the paper is also fine without a dedicated section.

2022-07-02 17:00 UTC, TomNicholas commented
Hi, I'm happy that all of my comments have been addressed.

2022-07-06 11:00 UTC, deniederhut commented
@cbcunc GitHub shows that you are still requesting changes on the paper. Is it ready for publication?

2022-07-08 19:07 UTC, cbcunc approved these changes

2022-07-08 19:08 UTC, cbcunc commented
@scoobies mark ready

2022-07-08 22:47 UTC, deniederhut requested changes
Would you mind taking a second pass over your references section? Some of these look incomplete or incorrect. I'm pretty sure SciPy hasn't published 130 volumes yet 😉

2022-07-08 22:47 UTC, deniederhut commented on papers/orhan_eroglu/references.bib
> +@article{xarray17,
Is this missing a DOI?

2022-07-08 22:47 UTC, deniederhut commented on papers/orhan_eroglu/references.bib
> +@inproceedings{dask15,
This isn't correct. You can find the full citation here https://conference.scipy.org/proceedings/scipy2015/matthew_rocklin.html

2022-07-08 22:47 UTC, deniederhut commented on papers/orhan_eroglu/references.bib
> + @misc{matplotlib,
matplotlib has a preferred citation - https://matplotlib.org/stable/users/project/citing.html

2022-07-08 22:47 UTC, deniederhut commented
@scoobies mark pending comment

2022-07-09 02:05 UTC, erogluorhan commented on papers/orhan_eroglu/references.bib
> +@article{xarray17,
Added the DOI; thanks!

2022-07-09 02:16 UTC, erogluorhan commented on papers/orhan_eroglu/references.bib
> +@inproceedings{dask15,
Fixed it now; thanks very much!

2022-07-09 02:22 UTC, erogluorhan commented on papers/orhan_eroglu/references.bib
> + @misc{matplotlib,
Thanks! Fixed this.

2022-07-09 03:23 UTC, erogluorhan commented
> Would you mind taking a second pass over your references section? Some of these look incomplete or incorrect. I'm pretty sure SciPy hasn't published 130 volumes yet 😉

Thanks very much! We have addressed all of the inline suggestions as well as we have passed over our references again and converted some of them to the way that their owners suggest to cite (e.g. Cartopy, Sphinx, Pooch).

So, we believe it should be good to go now.

2022-07-10 21:25 UTC, deniederhut commented
@erogluorhan thanks for updating those! It looks like we're still missing DOIs for the numba and dyamond papers though?

2022-07-10 23:04 UTC, erogluorhan commented
> @erogluorhan thanks for updating those! It looks like we're still missing DOIs for the numba and dyamond papers though?

Added now, thanks!

2022-07-11 13:01 UTC, deniederhut approved these changes
Thanks for adding those!

2022-07-11 13:01 UTC, deniederhut commented
@scoobies mark ready

2022-07-11 13:08 UTC, merged

2022-07-11 15:45 UTC, erogluorhan commented
Thanks very much, @deniederhut et al., for your great reviews that helped us improve our paper throughout!