Added poster
scipy-conference/scipy_proceedings pull request #688
Opened 2022-05-19 11:53 UTC by idomic

If you are creating this PR in order to submit a draft of your paper,
see http://procbuild.scipy.org/ for logs generated by the build
process.

See the [project readme](https://github.com/scipy-conference/scipy_proceedings#build-your-paper)
for more information.

*Editor*:  Ido 

*Reviewers*:

2022-05-19 11:53 UTC, scoobies commented
Hi!, I'm @scoobies, a friendly bot.

Type ```@scoobies help``` to discover how I can help you.

2022-05-29 20:43 UTC, deniederhut commented
@idomic is this a full paper that you would like to have included in the proceedings? Or a poster that you would like to have archived?

2022-06-01 02:22 UTC, idomic commented
@deniederhut this is the paper to include, it's sort of a self guided tutorial on achieving best practices. Is there anything I need to change?

2022-06-03 01:10 UTC, deniederhut commented
Yup you will need to follow the instructions here for submitting papers to the proceedings : https://github.com/scipy-conference/scipy_proceedings#instructions-for-authors

We're expecting a new directory with your name in the `papers` directory, which should have a .rst file there and any supporting files for tables or images. I see a lot of other stuff, like notebooks and idea project files, which we can't publish. You can see an example of how to structure your submission here: https://github.com/scipy-conference/scipy_proceedings/tree/2022/papers/00_bibderwalt

2022-06-03 01:12 UTC, deniederhut commented
@scoobies mark paper

2022-06-03 01:12 UTC, deniederhut commented
@scoobies build paper

2022-06-03 01:12 UTC, scoobies commented
building paper...

2022-06-03 01:12 UTC, scoobies commented
{"data"=>{"info"=>"Build for paper idomic-2022 scheduled.  Note that builds are only executed if the current build attempt is more than 5 minutes old."}, "status"=>"success"}

2022-06-03 01:13 UTC, deniederhut commented
It looks like this paper is only two pages long, and that there are no references -- is that right?

2022-06-04 21:44 UTC, deniederhut commented
@idomic just following up -- have you had a chance to clean up the extra files in your submission? Thanks!

2022-06-04 21:44 UTC, deniederhut commented
@scoobies mark needs review

2022-06-04 21:45 UTC, deniederhut commented
@scoobies assign @mepa as editor

2022-06-04 21:45 UTC, scoobies commented
Assigned! @mepa is now the editor

2022-06-04 21:51 UTC, idomic commented
@deniederhut On it!

2022-06-04 22:21 UTC, deniederhut commented
Thanks!

2022-06-05 16:23 UTC, govarguz commented
Dear all, I agree on reviewing this paper!

2022-06-05 20:10 UTC, idomic commented
> It looks like this paper is only two pages long, and that there are no references -- is that right?

Yes that's correct it's a self explanatory workshop, there are references in the end (section 9).
Also there's a jupyter notebook that users can leverage and run locally.

2022-06-07 02:38 UTC, deniederhut commented
Thanks Horacio!

2022-06-07 02:38 UTC, deniederhut commented
@scoobies add @govarguz to reviewers

2022-06-07 02:38 UTC, scoobies commented
@govarguz added to the reviewers list!

2022-06-07 02:44 UTC, deniederhut commented
> Yes that's correct it's a self explanatory workshop, there are references in the end (section 9).
Also there's a jupyter notebook that users can leverage and run locally.

The only output of the publication system is a PDF of your paper and html page with the abstract that we post online -- the jupyter notebooks and anything else will be ignored. Please remove any materials that are not needed to compile the paper.

2022-06-07 02:44 UTC, deniederhut commented
We've moved the deadline for first reviews back one week, to June 16th, to give us a little more time to find reviewers for all the papers this year. You can see the updated full timeline at https://github.com/scipy-conference/scipy_proceedings#timeline-for-2022.

2022-06-08 01:30 UTC, deniederhut commented
@scoobies add @kajayi to reviewers

2022-06-08 01:30 UTC, scoobies commented
@kajayi added to the reviewers list!

2022-06-11 20:27 UTC, deniederhut commented
@idomic have you had a chance to clean out the extra files?

2022-06-11 21:37 UTC, idomic commented
Yes I'm adding a few references and diagrams since it won't be the
interactive notebook I thought. I'll push a new rst for review mid week.

On Sat, Jun 11, 2022, 16:27 Dillon Niederhut ***@***.***>
wrote:

> @idomic <https://github.com/idomic> have you had a chance to clean out
> the extra files?
>
> —
> Reply to this email directly, view it on GitHub
> <https://github.com/scipy-conference/scipy_proceedings/pull/688#issuecomment-1152992811>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/ACYPJOMV4QVNOBHAVTZX2M3VOTZD3ANCNFSM5WL6VEAA>
> .
> You are receiving this because you were mentioned.Message ID:
> ***@***.***>
>

2022-06-14 19:04 UTC, idomic commented
@deniederhut 

* I've started building the paper again, having some difficulties on mac, it's showing me some missing latex dependencies.
* I'm now at a point where I don't have this error but for some reason the paper isn't generated, it's outputting building and no paper.pdf.

Does it work if I'm saving the notebook as a pdf and commit it?
Also is there a way to keep the notebook so it's more interactive? Even if I'm adding images and diagrams it's way better if users can run it.

2022-06-15 00:09 UTC, deniederhut commented
> Also is there a way to keep the notebook so it's more interactive?

We aren't really set up for that, unfortunately. The proceedings is published as a static PDF. Maybe you could add a link in the paper to a binder instance or something?

> Does it work if I'm saving the notebook as a pdf and commit it?

Sorry -- we'll need the source file to compile the proceedings.

> it's outputting building and no paper.pdf.

Hard to be sure what's happening there without more info. Is there output you can share? Or could you push your recent changes to this branch so I can pull them down and debug locally?

2022-06-15 01:46 UTC, idomic commented
A binder link is a great idea!

On the changes, I'm trying to build the existing `.rst` even before the changes, the output of `./make_paper.sh papers/ido_michael/` is `Building: ido_michael` and that's it, when I'm looking for the final .pdf it's not there

2022-06-15 01:52 UTC, idomic commented
Alright, I found where it outputs the .pdf, it's just in a different directory than what I was expecting. I'm adding the missing links and diagrams.

2022-06-15 18:51 UTC, idomic commented
@deniederhut I've added the rest of the edits, the paper should be 4 pages long with more diagrams and links. Let me know if anything's missing.

2022-06-16 00:09 UTC, deniederhut commented
Glad it was an easy fix! @govarguz and @kajayi -- friendly reminder that initial reviews are due tomorrow

2022-06-16 21:42 UTC, kajayi commented on papers/ido_michael/index.rst
> +^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
Consider putting this into a separate Markdown cell

2022-06-16 21:42 UTC, kajayi commented on papers/ido_michael/index.rst
> +.. image:: images/new-task-attached.png
Needs a caption

2022-06-16 21:42 UTC, kajayi commented on papers/ido_michael/index.rst
> +training data so we can train our new model so we change the
```suggestion
training data so we can train our new model, so we change the
```

2022-06-16 21:42 UTC, kajayi commented on papers/ido_michael/index.rst
> +any dependency, so let’s tell Ploomber that it should execute after
```suggestion
any dependencies, so let’s tell Ploomber that it should execute after
```

2022-06-16 21:43 UTC, kajayi commented on papers/ido_michael/index.rst
> +.. image:: images/new-task.png
Needs caption

2022-06-16 21:43 UTC, kajayi commented on papers/ido_michael/index.rst
> +Open ``playground/pipeline.yaml`` and add the following lines at the end
```suggestion
First, we modify the ``pipeline.yaml`` file and add a new task:

Open ``playground/pipeline.yaml`` and add the following lines at the end:
```

2022-06-16 21:43 UTC, kajayi commented on papers/ido_michael/index.rst
> +Let’s see how.
```suggestion
Soorgeon extracted and declared the dependencies for us, but if we want
to modify the existing pipeline, we need to declare such dependencies manually.
Let’s see how.
```

2022-06-16 21:43 UTC, kajayi commented on papers/ido_michael/index.rst
> +regressor.
```suggestion
The arrows in the diagram represent input/output dependencies and depict the 
execution order. For example, the first task (``load``) loads
some data, then ``clean`` uses such data as input and processes it, then
``train-test-split`` splits our dataset into training and test sets. Finally,
we use those datasets to train a linear regression and a random forest
regressor.
```

2022-06-16 21:43 UTC, kajayi commented on papers/ido_michael/index.rst
> +.. image:: images/executed-pipeline.png
Needs caption

2022-06-16 21:43 UTC, kajayi commented on papers/ido_michael/index.rst
> +   Image('playground/pipeline.png')
Delete?

2022-06-16 21:43 UTC, kajayi commented on papers/ido_michael/index.rst
> +are crucial to us before training the model.
```suggestion
are crucial for training the model.
```

2022-06-16 21:43 UTC, kajayi commented on papers/ido_michael/index.rst
> +as well as the quality we expect. For instance, in the first test we're checking
```suggestion
and has the quality we expect. For instance, in the first test we're checking
```

2022-06-16 21:43 UTC, kajayi commented on papers/ido_michael/index.rst
> +.. image:: images/post-build-artifacts.png
Needs a caption

2022-06-16 21:43 UTC, kajayi commented on papers/ido_michael/index.rst
> +executed notebooks, data files and trained model.
```suggestion
Navigate to ``playground/output/`` and you’ll see all the outputs&mdash;the
executed notebooks, data files and trained model:
```

2022-06-16 21:43 UTC, kajayi commented on papers/ido_michael/index.rst
> +.. image:: images/build-output.png
Needs a caption

2022-06-16 21:43 UTC, kajayi commented on papers/ido_michael/index.rst
> +and what's the partial percentage of the overall pipeline execution runtime.
```suggestion
We can see which tasks ran during this command, how long they took to execute,
and the contributions of each task to the overall pipeline execution runtime.
```

2022-06-16 21:43 UTC, kajayi commented on papers/ido_michael/index.rst
> +.. image:: images/status-output.png
Needs a caption

2022-06-16 21:43 UTC, kajayi commented on papers/ido_michael/index.rst
> +of each other!).
```suggestion
notebook. It even detected that the last two tasks
(``linear-regression`` and ``random-forest-regressor``) are independent
of each other!
```

2022-06-16 21:43 UTC, kajayi commented on papers/ido_michael/index.rst
> +.. image:: images/pipeline-step-2.png
Needs a caption

2022-06-16 21:43 UTC, kajayi commented on papers/ido_michael/index.rst
> +task was executed or failed.
```suggestion
This command will generate the plot below for us, which will allow us to stay up to date
with changes that are happening in our pipeline and get the current status of
tasks that were executed or failed to execute.
```

2022-06-16 21:44 UTC, kajayi commented on papers/ido_michael/index.rst
> +is by ploting the pipeline (note that we’re now using ``ploomber``, which
```suggestion
is by plotting the pipeline (note that we’re now using ``ploomber``, which
```

2022-06-16 21:44 UTC, kajayi commented on papers/ido_michael/index.rst
> +identified based on our H2 Markdown headings.
```suggestion
identified based on our H2 Markdown headings:
```

2022-06-16 21:44 UTC, kajayi commented on papers/ido_michael/index.rst
> +and we'll see that now we have multiple python tasks which are ready for production:
```suggestion
After running the refactor command, we can take a look at the local directory
and see that we now have multiple python tasks that are ready for production:
```

2022-06-16 21:44 UTC, kajayi commented on papers/ido_michael/index.rst
> +it into smaller tasks the way they see fit.
```suggestion
it into smaller tasks as they see fit.
```

2022-06-16 21:44 UTC, kajayi commented on papers/ido_michael/index.rst
> +It does that by scanning the markdown in the notebook and analyzing the headers,
```suggestion
It does that by scanning the markdown in the notebook and analyzing the headers;
```

2022-06-16 21:44 UTC, kajayi commented on papers/ido_michael/index.rst
> +pipeline. Soorgeon statically analyze your code, clean up unnecessary imports,
```suggestion
pipeline. Soorgeon statically analyzes your code, cleans up unnecessary imports,
```

2022-06-16 21:44 UTC, kajayi commented on papers/ido_michael/index.rst
> +applying these ideas for data analysis requires extra work: multiple
```suggestion
applying these ideas for data analysis requires extra work&mdash;multiple
```

2022-06-16 21:44 UTC, kajayi commented on papers/ido_michael/index.rst
> +Arbitrary execution order is a prevalent problem: A `recent
```suggestion
Arbitrary execution order is a prevalent problem: a `recent
```

2022-06-16 21:44 UTC, kajayi commented on papers/ido_michael/index.rst
> +However, this convenience comes at a cost: if we are not careful about
```suggestion
However, this convenience comes at a cost&mdash; if we are not careful about
```

2022-06-16 21:46 UTC, kajayi commented on papers/ido_michael/index.rst
> +7. Incremental builds
```suggestion
8. Incremental builds
```

2022-06-16 21:56 UTC, kajayi commented on papers/ido_michael/index.rst
> +^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
Consider putting this into a separate Markdown cell

2022-06-16 21:59 UTC, kajayi commented on papers/ido_michael/index.rst
> +    assert 'pkl' in upstream['train-test-split']['X_test']
Consider putting this into a separate Markdown cell

2022-06-16 22:00 UTC, kajayi commented on papers/ido_michael/index.rst
> +    assert len(df) == 11085
Consider putting this into a separate Markdown cell

2022-06-16 22:10 UTC, kajayi commented
Hello, I have reviewed the paper and it (initially) looks good overall.  I added a number of line comments to the PR. (I didn't realize they would show up in the conversation like this!)   This paper definitely will be of interest to the SciPy community. 

I went through the tutorial online and got a CalledProcessError on Step 9 ("Parallel execution + Ploomber cloud execution"). That step is not shown in the paper, so maybe you meant to remove it from the demo?  

I also tried to complete the tutorial locally, but got an error on step 5--that error is likely due to the way I handle environments on my local machine. (I use the nb_conda_kernels extension from the base environment and specify the desired conda environment as the kernel for each notebook.) I don't know if you have to do anything about that, but I thought you should know just FYI. 

Let me know if you have any questions!

2022-06-16 22:14 UTC, kajayi commented on papers/ido_michael/index.rst
> +    assert not df['HouseAge'].isnull().values.any()
Is "values" needed here (i.e., would `df['HouseAge'].isnull().any()` work)?

2022-06-16 22:21 UTC, kajayi requested changes
Added comments to index.rst

2022-06-16 23:26 UTC, deniederhut commented
@scoobies mark needs more review

2022-06-19 22:23 UTC, deniederhut commented
@scoobies remove @govarguz from reviewers

2022-06-19 22:23 UTC, scoobies commented
@govarguz removed from the reviewers list!

2022-06-19 22:23 UTC, deniederhut commented
@scoobies mark pending comment

2022-06-20 12:48 UTC, idomic commented on papers/ido_michael/index.rst
> +    assert not df['HouseAge'].isnull().values.any()
It's not, removed it.

2022-06-20 15:45 UTC, idomic commented
Thanks for reviewing @kajayi fixed comments and added the missing section!

2022-06-27 04:22 UTC, deniederhut commented
Hi @kajayi ! Do you feel this paper is now ready to be included in the proceedings?

2022-06-28 22:11 UTC, kajayi commented
> Hi @kajayi ! Do you feel this paper is now ready to be included in the proceedings?

Hi @deniederhut !  There are still a few unresolved suggestions in the paper, but they are all minor, so I believe this paper is ready to be included in the proceedings whether the suggestions are resolved or not.  I will incorporate its teachings into my own work where I can--thank you for the tutorial @idomic !

2022-06-29 00:36 UTC, deniederhut commented
> There are still a few unresolved suggestions in the paper

Sorry I missed this! @idomic would you mind responding to the remaining comments?

2022-07-01 01:10 UTC, deniederhut commented
@idomic have you had a chance to work on the rest of the review comments?

2022-07-01 13:32 UTC, idomic commented
@deniederhut I'll do it over this weekend. I probably missed those comments.

2022-07-01 17:41 UTC, mepa commented
@scoobies check references

2022-07-01 17:42 UTC, scoobies commented
Checking the BibTeX entries failed with the following error: 
```
Couldn't find bibliography entry
```

2022-07-04 19:06 UTC, mepa commented
Hi @idomic, thanks for your contribution! Could you please check the rendered pdf and fix any lines that bleed into the next column by adding newlines at appropriate places in the code: https://procbuild.scipy.org/download/idomic-2022

@cbcunc, @deniederhut, @stargaser - this paper includes hypertext links in lieu of a references section with citations.

2022-07-04 19:37 UTC, deniederhut commented
Thanks for the heads-up Meghann. It seems like the paper should at least be citing the Jupyter project -- maybe also scikit-learn?

2022-07-04 21:54 UTC, idomic commented
@deniederhut fixed pending changes (it's all in the commit)

2022-07-05 04:38 UTC, mepa commented on papers/ido_michael/index.rst
> +   X_train = pickle.loads(Path(upstream['train-test-split']['X_train']).read_bytes())
This section is running off the page

<img width="423" alt="Screen Shot 2022-07-04 at 11 26 15 PM" src="https://user-images.githubusercontent.com/4421561/177249299-4d455a3c-028c-47e0-9322-16a09d495216.png">

Something like the following _might_ work
```
   y_train = pickle.loads(
       Path(upstream['train-test-split']['y_train']).read_bytes())
   y_test = pickle.loads(
       Path(upstream['train-test-split']['y_test']).read_bytes())
   X_test = pickle.loads(
       Path(upstream['train-test-split']['X_test']).read_bytes())
   X_train = pickle.loads(
       Path(upstream['train-test-split']['X_train']).read_bytes())
```

2022-07-05 04:38 UTC, mepa commented on papers/ido_michael/index.rst
> +Open ``playground/tasks/gradient-boosting-regressor.py`` as a notebook by right-clicking on it and then ``Open With`` -> ``Notebook`` and add the following code:
<img width="417" alt="Screen Shot 2022-07-04 at 11 30 21 PM" src="https://user-images.githubusercontent.com/4421561/177249715-160ed243-81a6-46aa-8ee8-1460f482d86c.png">

Maybe put ``playground/tasks/gradient-boosting-regressor.py`` on its own line so it doesn't run into the margin?

2022-07-05 04:38 UTC, mepa commented on papers/ido_michael/index.rst
> +Open ``playground/tasks/gradient-boosting-regressor.py`` as a notebook by right-clicking on it and then ``Open With`` -> ``Notebook``:
Maybe put ``playground/tasks/gradient-boosting-regressor.py`` on its own line to avoid bleeding into the margin?

2022-07-07 05:25 UTC, mepa commented
@scoobies build paper

2022-07-07 05:25 UTC, scoobies commented
building paper...

2022-07-07 05:25 UTC, scoobies commented
{"data"=>{"info"=>"Build for paper idomic-2022 scheduled.  Note that builds are only executed if the current build attempt is more than 5 minutes old."}, "status"=>"success"}

2022-07-07 05:31 UTC, mepa commented on papers/ido_michael/index.rst
> +   X_train = pickle.loads(Path(upstream['train-test-split']['X_train']).read_bytes())
Let's please try this instead
```
y_train = pickle.loads(Path(
    upstream['train-test-split']['y_train']).read_bytes())
y_test = pickle.loads(Path(
    upstream['train-test-split']['y_test']).read_bytes())
X_test = pickle.loads(Path(
    upstream['train-test-split']['X_test']).read_bytes())
X_train = pickle.loads(Path(
    upstream['train-test-split']['X_train']).read_bytes())
```

2022-07-07 05:40 UTC, mepa commented on papers/ido_michael/index.rst
> +Open ``playground/tasks/gradient-boosting-regressor.py`` as a notebook by right-clicking on it and then ``Open With`` -> ``Notebook`` and add the following code:
<img width="550" alt="Screen Shot 2022-07-07 at 12 35 35 AM" src="https://user-images.githubusercontent.com/4421561/177699607-e6dafd05-322e-4546-a0ba-694e2e82a3e5.png">


Ah, sorry, the newline didn't work like I hoped. Maybe the following will work better
```
Open

.. code:: sh
   playground/tasks/gradient-boosting-regressor.py

as a notebook by right-clicking on
```

2022-07-07 05:42 UTC, mepa commented on papers/ido_michael/index.rst
> +Open ``playground/tasks/gradient-boosting-regressor.py`` as a notebook by right-clicking on it and then ``Open With`` -> ``Notebook``:
We can try the same approach here, too, if it works in the [other case](https://github.com/scipy-conference/scipy_proceedings/pull/688#discussion_r915477513).

2022-07-08 19:02 UTC, cbcunc commented
@scoobies mark ready

2022-07-08 19:03 UTC, cbcunc commented
@scoobies mark pending-comment

2022-07-08 19:05 UTC, cbcunc commented
@scoobies mark pending comment

2022-07-08 19:05 UTC, mepa commented
Hi @idomic, thanks for trying those changes. Could we please try the latest formatting changes I suggested? Also, I'm just guessing at what will work. It may be more efficient (quicker to get the paper accepting into the proceedings) if you can please do the following.

1. After committing your changes, build the output by commenting
```
@scoobies build paper
```
or by clicking the button next to your paper at https://procbuild.scipy.org/.

2. After the paper build, check the generated pdf at https://procbuild.scipy.org/download/idomic-2022 to ensure that the formatting looks good (e.g., no overflow into the margin or next column).

2022-07-11 00:43 UTC, idomic commented
@mepa done, I think it looks better now!

2022-07-11 02:24 UTC, mepa commented
@scoobies build paper

2022-07-11 02:24 UTC, scoobies commented
building paper...

2022-07-11 02:24 UTC, scoobies commented
{"data"=>{"info"=>"Build for paper idomic-2022 scheduled.  Note that builds are only executed if the current build attempt is more than 5 minutes old."}, "status"=>"success"}

2022-07-11 02:38 UTC, mepa commented
Thanks, @idomic - that worked! There are other long urls in the paper that could be wrapped in code cells in the same way as you did for `playground/tasks/gradient-boosting-regressor.py`, if you feel like fiddling with it before the final proceedings is published around July 30th. Anyhow, I'll go ahead and mark this paper as ready to include in the proceedings. Thanks for the contribution and best wishes on tomorrow's Ploomber tutorial!

2022-07-11 02:38 UTC, mepa commented
@scoobies mark ready

2022-07-11 13:09 UTC, merged