Auto detect paper name if only one paper.
scipy-conference/scipy_proceedings pull request #691
Opened 2022-05-24 07:46 UTC by Carreau

If there is a single paper in papers (excluding the examples from
stefan).

I _think_ that might make it a bit easier to use

If you are creating this PR in order to submit a draft of your paper,
see http://procbuild.scipy.org/ for logs generated by the build
process.

See the [project readme](https://github.com/scipy-conference/scipy_proceedings#build-your-paper)
for more information.

*Editor*:  

*Reviewers*:

2022-05-24 07:46 UTC, scoobies commented
Hi!, I'm @scoobies, a friendly bot.

Type ```@scoobies help``` to discover how I can help you.

2023-06-09 16:28 UTC, cbcunc requested changes

2023-06-09 16:28 UTC, cbcunc commented on publisher/build_paper.py
> +        pths = [p for p in pths if p.name not in {"00_bibderwalt", "00_vanderwalt"}]
This is no longer the correct list of papers to exclude. Check .publisher.conf.excludes.

2023-06-09 16:28 UTC, cbcunc commented on make_paper.sh
> -if [[ ! -d $DIR ]]; then
Why remove this?

2023-06-12 07:47 UTC, Carreau commented on make_paper.sh
> -if [[ ! -d $DIR ]]; then
Because this is now handled on `publisher/build_paper.py` and that's the point of this PR, to not have to pass a folder name, but autodetect when possible.

2023-06-12 07:47 UTC, Carreau commented on publisher/build_paper.py
> +        pths = [p for p in pths if p.name not in {"00_bibderwalt", "00_vanderwalt"}]
Thanks, this PR is a bit over a year old, and I'm not publishing or coming this year. Feel free to reuse the code, but I'm unlikely to work actively on this. 

I'm going to turn this back into a draft. Feel free to reuse the code or close it.

2023-11-29 10:11 UTC, closed without merging