Paper: Low-Level Feature Extraction for Cilia Segmentation
scipy-conference/scipy_proceedings pull request #699
Opened 2022-05-27 03:29 UTC by ENM185

If you are creating this PR in order to submit a draft of your paper,
see http://procbuild.scipy.org/ for logs generated by the build
process.

See the [project readme](https://github.com/scipy-conference/scipy_proceedings#build-your-paper)
for more information.

*Editor*:  

*Reviewers*:

2022-05-27 03:29 UTC, scoobies commented
Hi!, I'm @scoobies, a friendly bot.

Type ```@scoobies help``` to discover how I can help you.

2022-05-27 03:47 UTC, ENM185 commented
Note: the build will fail until #694 is merged due to missing LaTeX packages.

2022-05-27 21:37 UTC, deniederhut commented
Hi @ENM185 ! Would it work if we added something like

```
.. raw:: latex

   \usepackage{booktabs}
```

to your paper? We try to avoid modifying the build system for individual papers.

2022-05-27 21:47 UTC, ENM185 commented
Hey @deniederhut! We've attempted this, but `usepackage` seems to only work in the preamble, and I don't believe there's a way to modify the preamble of the generated .tex from within the papers directory.

2022-05-29 20:45 UTC, deniederhut commented
Mkay I can take a look.

2022-05-29 20:46 UTC, deniederhut commented
@scoobies mark paper

2022-05-29 20:46 UTC, deniederhut commented
@scoobies build status

2022-05-29 20:46 UTC, scoobies commented
{"quinngroup-2022-211"=>{"data"=>{"build_output"=>"[*] Updating proceedings build tools in {self.master_repo_path}...\nAlready up to date.\n[*] Check out paper repository...\nCloning into '/tmp/tmptaqnx0lh'...\nMoving proceedings build tools to temp directory...\n[*] Build the paper...\nBuilding: zain_miller\n*** Warning: /tmp/tmptaqnx0lh/publisher/../output/zain_miller/paper_stats.json does not exist.\nPDFLaTeX error output:\n================================================================================\nThis is pdfTeX, Version 3.14159265-2.6-1.40.18 (TeX Live 2017/Debian) (preloaded format=pdflatex)\n restricted \\write18 enabled.\nentering extended mode\n(./paper.tex\nLaTeX2e <2017-04-15>\nBabel <3.18> and hyphenation patterns for 3 language(s) loaded.\n(./IEEEtran.cls\nDocument Class: IEEEtran 2015/08/26 V1.8b by Michael Shell\n-- See the \"IEEEtran_HOWTO\" manual for usage information.\n-- http://www.michaelshell.org/tex/ieeetran/\n(/usr/share/texlive/texmf-dist/tex/latex/psnfss/ot1ppl.fd)\n-- Using IEEE Computer Society mode.\n-- Using 8.5in x 11in (letter) paper.\n-- Using PDF output.\n-- This is a 10 point document.\n) (/usr/share/texlive/texmf-dist/tex/latex/cmap/cmap.sty)\n(/usr/share/texlive/texmf-dist/tex/latex/base/ifthen.sty)\n(/usr/share/texlive/texmf-dist/tex/latex/base/fontenc.sty\n(/usr/share/texlive/texmf-dist/tex/latex/base/t1enc.def)\n(/usr/share/texlive/texmf-dist/tex/latex/psnfss/t1ppl.fd)<<t1.cmap>>)\n(/usr/share/texlive/texmf-dist/tex/latex/base/inputenc.sty\n(/usr/share/texlive/texmf-dist/tex/latex/base/utf8.def\n(/usr/share/texlive/texmf-dist/tex/latex/base/t1enc.dfu)\n(/usr/share/texlive/texmf-dist/tex/latex/base/ot1enc.dfu)\n(/usr/share/texlive/texmf-dist/tex/latex/base/omsenc.dfu)))\n(/usr/share/texlive/texmf-dist/tex/latex/amsmath/amsmath.sty\nFor additional information on amsmath, use the `?' option.\n(/usr/share/texlive/texmf-dist/tex/latex/amsmath/amstext.sty\n(/usr/share/texlive/texmf-dist/tex/latex/amsmath/amsgen.sty))\n(/usr/share/texlive/texmf-dist/tex/latex/amsmath/amsbsy.sty)\n(/usr/share/texlive/texmf-dist/tex/latex/amsmath/amsopn.sty))\n(/usr/share/texlive/texmf-dist/tex/latex/caption/caption.sty\n(/usr/share/texlive/texmf-dist/tex/latex/caption/caption3.sty\n(/usr/share/texlive/texmf-dist/tex/latex/graphics/keyval.sty))\n\nPackage caption Warning: Unsupported document class (or package) detected,\n(caption)                usage of the caption package is not recommended.\nSee the caption package documentation for explanation.\n\n) (/usr/share/texlive/texmf-dist/tex/latex/float/float.sty) (./scipy.sty\n(./status.sty (./draftwatermark.sty (./everypage.sty)\n(/usr/share/texlive/texmf-dist/tex/latex/graphics/graphicx.sty\n(/usr/share/texlive/texmf-dist/tex/latex/graphics/graphics.sty\n(/usr/share/texlive/texmf-dist/tex/latex/graphics/trig.sty)\n(/usr/share/texlive/texmf-dist/tex/latex/graphics-cfg/graphics.cfg)\n(/usr/share/texlive/texmf-dist/tex/latex/graphics-def/pdftex.def)))\n(/usr/share/texlive/texmf-dist/tex/latex/graphics/color.sty\n(/usr/share/texlive/texmf-dist/tex/latex/graphics-cfg/color.cfg))))\n(/usr/share/texlive/texmf-dist/tex/latex/psnfss/mathptmx.sty)\n(/usr/share/texlive/texmf-dist/tex/latex/psnfss/helvet.sty)\n(/usr/share/texlive/texmf-dist/tex/latex/psnfss/courier.sty)\n(/usr/share/texlive/texmf-dist/tex/latex/amsfonts/amsfonts.sty)\n(/usr/share/texlive/texmf-dist/tex/latex/amsfonts/amssymb.sty)\n(/usr/share/texlive/texmf-dist/tex/latex/tools/bm.sty)\n(/usr/share/texlive/texmf-dist/tex/latex/hyperref/hyperref.sty\n(/usr/share/texlive/texmf-dist/tex/generic/oberdiek/hobsub-hyperref.sty\n(/usr/share/texlive/texmf-dist/tex/generic/oberdiek/hobsub-generic.sty))\n(/usr/share/texlive/texmf-dist/tex/generic/ifxetex/ifxetex.sty)\n(/usr/share/texlive/texmf-dist/tex/latex/oberdiek/auxhook.sty)\n(/usr/share/texlive/texmf-dist/tex/latex/oberdiek/kvoptions.sty)\n(/usr/share/texlive/texmf-dist/tex/latex/hyperref/pd1enc.def)\n(/usr/share/texlive/texmf-dist/tex/latex/latexconfig/hyperref.cfg)\n(/usr/share/texlive/texmf-dist/tex/latex/url/url.sty))\n(/usr/share/texlive/texmf-dist/tex/latex/hyperref/hpdftex.def\n(/usr/share/texlive/texmf-dist/tex/latex/oberdiek/rerunfilecheck.sty))\n\nPackage hyperref Warning: Option `pdftex' has already been used,\n(hyperref)                setting the option has no effect on input line 43.\n\n(/usr/share/texlive/texmf-dist/tex/latex/tools/longtable.sty)\n(/usr/share/texlive/texmf-dist/tex/latex/multirow/multirow.sty)\n(/usr/share/texlive/texmf-dist/tex/latex/base/textcomp.sty\n(/usr/share/texlive/texmf-dist/tex/latex/base/ts1enc.def\n(/usr/share/texlive/texmf-dist/tex/latex/base/ts1enc.dfu)))\n(/usr/share/texlive/texmf-dist/tex/latex/upquote/upquote.sty)\n(/usr/share/texlive/texmf-dist/tex/latex/fancyvrb/fancyvrb.sty\nStyle option: `fancyvrb' v2.7a, with DG/SPQR fixes, and firstline=lastline fix \n<2008/02/07> (tvz)))\nNo file paper.aux.\n(/usr/share/texlive/texmf-dist/tex/latex/base/ts1cmr.fd)\n(/usr/share/texlive/texmf-dist/tex/latex/psnfss/t1ptm.fd)\n-- Lines per column: 61 (exact).\n(/usr/share/texlive/texmf-dist/tex/latex/caption/ltcaption.sty)\n(/usr/share/texlive/texmf-dist/tex/context/base/mkii/supp-pdf.mkii\n[Loading MPS to PDF converter (version 2006.09.02).]\n) (/usr/share/texlive/texmf-dist/tex/latex/oberdiek/epstopdf-base.sty\n(/usr/share/texlive/texmf-dist/tex/latex/oberdiek/grfext.sty)\n(/usr/share/texlive/texmf-dist/tex/latex/latexconfig/epstopdf-sys.cfg))\n(/usr/share/texlive/texmf-dist/tex/latex/hyperref/nameref.sty\n(/usr/share/texlive/texmf-dist/tex/generic/oberdiek/gettitlestring.sty))\n(/usr/share/texlive/texmf-dist/tex/latex/psnfss/t1phv.fd)\n(/usr/share/texlive/texmf-dist/tex/latex/psnfss/ot1ztmcm.fd)<<ot1.cmap>>\n(/usr/share/texlive/texmf-dist/tex/latex/psnfss/omlztmcm.fd)<<oml.cmap>>\n(/usr/share/texlive/texmf-dist/tex/latex/psnfss/omsztmcm.fd)<<oms.cmap>>\n(/usr/share/texlive/texmf-dist/tex/latex/psnfss/omxztmcm.fd)<<omx.cmap>>\n(/usr/share/texlive/texmf-dist/tex/latex/psnfss/ot1ptm.fd)\n(/usr/share/texlive/texmf-dist/tex/latex/psnfss/upzd.fd)\n(/usr/share/texlive/texmf-dist/tex/latex/psnfss/ts1ptm.fd) (./page_numbers.tex)\n\nLaTeX Warning: Citation `li2018composite' on page 1 undefined on input line 161\n.\n\n\nLaTeX Warning: Citation `quinn2015automated' on page 1 undefined on input line \n161.\n\n\nLaTeX Warning: Citation `ishikawa2017axoneme' on page 1 undefined on input line\n 170.\n\n\nLaTeX Warning: Citation `li2018composite' on page 1 undefined on input line 176\n.\n\n\nLaTeX Warning: Citation `quinn2015automated' on page 1 undefined on input line \n176.\n\n\nLaTeX Warning: Citation `cilia' on page 1 undefined on input line 183.\n\n\nLaTeX Warning: No positions in optional float specifier.\n               Default added (so using `tbp') on input line 195.\n\n\nLaTeX Warning: Citation `doornbos2021cell' on page 1 undefined on input line 20\n2.\n\n\nLaTeX Warning: Citation `quinn2015automated' on page 1 undefined on input line \n213.\n\n\nLaTeX Warning: Citation `cilia' on page 1 undefined on input line 213.\n\n\nLaTeX Warning: Citation `doornbos2021cell' on page 1 undefined on input line 21\n6.\n\n[1{/var/lib/texmf/fonts/map/pdftex/updmap/pdftex.map} <./sample_cilia.png>]\n\nLaTeX Warning: Citation `charles' on page 2 undefined on input line 236.\n\n\nLaTeX Warning: Citation `charles' on page 2 undefined on input line 246.\n\n\nLaTeX Warning: No positions in optional float specifier.\n               Default added (so using `tbp') on input line 251.\n\n\nLaTeX Warning: Reference `fig:unet' on page 2 undefined on input line 258.\n\n\nLaTeX Warning: Citation `unet' on page 2 undefined on input line 259.\n\n\nLaTeX Warning: Citation `unet' on page 2 undefined on input line 275.\n\n\nLaTeX Warning: Citation `charles' on page 2 undefined on input line 277.\n\n[2 <./unet.png>]\n\nLaTeX Warning: Citation `zca' on page 3 undefined on input line 369.\n\n\nLaTeX Warning: Reference `fig:zcaeps' on page 3 undefined on input line 400.\n\n\nLaTeX Warning [...]

2022-05-29 20:46 UTC, deniederhut commented
@scoobies mark server fail

2022-05-29 20:47 UTC, deniederhut commented
@scoobies assign @cbcunc as editor

2022-05-29 20:47 UTC, scoobies commented
Assigned! @cbcunc is now the editor

2022-06-02 11:32 UTC, deniederhut commented
@scoobies add @ojemebo to reviewers

2022-06-02 11:32 UTC, scoobies commented
@ojemebo added to the reviewers list!

2022-06-02 12:53 UTC, Micky774 commented
@deniederhut @ojemebo is a member of our lab -- would this be a conflict of interest?

2022-06-03 00:50 UTC, deniederhut commented
@Micky774 Blessing emailed me about the same concern -- we'll reshuffle our reviewer list

2022-06-03 00:53 UTC, deniederhut commented
@scoobies remove @ojemebo from reviewers

2022-06-03 00:53 UTC, scoobies commented
@ojemebo removed from the reviewers list!

2022-06-03 01:01 UTC, deniederhut commented
@scoobies build paper

2022-06-03 01:01 UTC, scoobies commented
building paper...

2022-06-03 01:01 UTC, scoobies commented
{"data"=>{"info"=>"Build for paper quinngroup-2022-211 scheduled.  Note that builds are only executed if the current build attempt is more than 5 minutes old."}, "status"=>"success"}

2022-06-03 01:02 UTC, deniederhut commented
@scoobies build status

2022-06-03 01:02 UTC, scoobies commented
{"quinngroup-2022-211"=>{"data"=>{"build_output"=>"[*] Updating proceedings build tools in {self.master_repo_path}...\nFrom https://github.com/scipy-conference/scipy_proceedings\n   253b124..4850b25  2022       -> origin/2022\nUpdating 253b124..4850b25\nFast-forward\n publisher/Makefile                      |  6 ++++--\n publisher/_static/scipy.sty             |  1 +\n publisher/_templates/slides.html.tmpl   | 16 ++++++++--------\n publisher/_templates/slides.tex.tmpl    |  8 ++++----\n publisher/_templates/students.html.tmpl | 17 -----------------\n publisher/_templates/students.tex.tmpl  | 13 -------------\n publisher/build_papers.py               |  2 +-\n publisher/mail/_mailer.py               |  6 ++++++\n publisher/xreftools.py                  |  8 +++++++-\n 9 files changed, 31 insertions(+), 46 deletions(-)\n[*] Check out paper repository...\nCloning into '/tmp/tmpxl1l7avs'...\nMoving proceedings build tools to temp directory...\n[*] Build the paper...\nBuilding: zain_miller\n*** Warning: /tmp/tmpxl1l7avs/publisher/../output/zain_miller/paper_stats.json does not exist.\n", "build_pdf_path"=>"/procbuild/procbuild/../cache/quinngroup-2022-211.pdf", "build_status"=>"success", "build_timestamp"=>"03/06 01:01"}, "status"=>"success"}}

2022-06-03 01:02 UTC, deniederhut commented
rad

2022-06-03 01:03 UTC, deniederhut commented
@scoobies mark server success

2022-06-03 01:03 UTC, deniederhut commented
@scoobies mark needs review

2022-06-03 21:20 UTC, cbcunc commented
Editor confirms paper builds.

2022-06-07 02:50 UTC, deniederhut commented
Hi! We've moved the deadline for first reviews back one week, to June 16th, to give us a little more time to find reviewers for all the papers this year. You can see the updated full timeline at https://github.com/scipy-conference/scipy_proceedings#timeline-for-2022.

2022-06-12 01:22 UTC, cbcunc commented
@scoobies add @cbcunc to reviewers

2022-06-12 01:22 UTC, scoobies commented
@cbcunc added to the reviewers list!

2022-06-23 20:06 UTC, Micky774 commented
Hello @deniederhut @cbcunc, I just wanted to check what the current expected timeline is -- we're a week past the extended deadline for the initial complete review and I just want to make sure there's nothing on our ended that you two are waiting on. Thanks for the help :)

2022-06-24 01:52 UTC, deniederhut commented
Hey @Micky774 ! Sorry for the delay -- I think we're just waiting for Chris to have some availability.

2022-06-24 20:06 UTC, cbcunc reviewed
Generally a well-organized paper. But many cosmetic changes (commented) are needed to come up to Proceeding standards. Citations are weak.

2022-06-24 20:06 UTC, cbcunc commented on papers/zain_miller/paper.rst
> +   Cilia are organelles found on the surface of some cells in the human body that sweep rhythmically to transport substances. Dysfunction of ciliary motion is often indicative of diseases known as ci
The first person "we" is used 49 times in this paper. The first person possessive "our" is used 16 times. While there as some who argue that this informality should become acceptable (largely, those who are guilty of it) and has slowly crept into some disciplines, this practice is still unprofessionally nonobjective. I would challenge you to please reframe your sentences to put the emphasis on the subject matter rather than on yourselves. The Proceedings Committee is considering making this a formal style requirement for next year.

2022-06-24 20:06 UTC, cbcunc commented on papers/zain_miller/paper.rst
> +understanding ciliopathies; however, this is generally an
Another practice I would encourage you to revise, is the use of a semicolon to construct a run-on sentence. Start a new sentence at "however" (and possibly strive to use active voice).

2022-06-24 20:06 UTC, cbcunc commented on papers/zain_miller/paper.rst
> +the potential to reduce magnitude of work required by an expert
reduce *the* magnitude

2022-06-24 20:06 UTC, cbcunc commented on papers/zain_miller/paper.rst
> +to a CNN based Long Short-Term Memory (LSTM) time-series model for
Hyphenate "CNN-based."

2022-06-24 20:06 UTC, cbcunc commented on papers/zain_miller/paper.rst
> +human error. Hence, Zain et. al. (2020) discuss the construction of a
"Et" is not an abbreviation. "Al." is. The correct usage is "et al" with no period after "et". There are seven instances in this paper to correct. https://www.scribbr.com/citing-sources/et-al/

2022-06-24 20:06 UTC, cbcunc commented on papers/zain_miller/paper.rst
> +model in the same way — as an upstream to an CNN/LSTM classification
Please use either the .. unicode:: directive or bars to represent the em dashes for portability. https://docutils.sourceforge.io/FAQ.html#how-can-i-represent-esoteric-characters-e-g-character-entities-in-a-document

2022-06-24 20:06 UTC, cbcunc commented on papers/zain_miller/paper.rst
> +reducing the number of channels, and at each stage, the up-sampled image
Run-on sentence. Please start a new sentence with "And at each stage."

2022-06-24 20:06 UTC, cbcunc commented on papers/zain_miller/paper.rst
> +background and ambient cells) as well as inconsistent shape and
Oxford comma needed before "as well as."

2022-06-24 20:06 UTC, cbcunc commented on papers/zain_miller/paper.rst
> +features in the image through various means, therefore optimization of
Run-on sentence. Start a new sentence with "Therefore, optimization of..."

2022-06-24 20:06 UTC, cbcunc commented on papers/zain_miller/paper.rst
> +“whitnening” is actually not a proper whitening since it doesn’t
Run-on sentence. Start a new sentence with "However, it serves". Also, please omit "(this can be easily verified by the reader)." It's condescending. Provide a citation for assertions.

2022-06-24 20:06 UTC, cbcunc commented on papers/zain_miller/paper.rst
> +SAEs—and indeed, *all* AEs—are at risk of a degenerate solution wherein
Please use either the .. unicode:: directive or bars to represent the em dashes for portability *and surround it with spaces*. https://docutils.sourceforge.io/FAQ.html#how-can-i-represent-esoteric-characters-e-g-character-entities-in-a-document

2022-06-24 20:06 UTC, cbcunc commented on papers/zain_miller/paper.rst
> +the training process. We note that this model—the composite
Use commas instead of emdashes here.

2022-06-24 20:06 UTC, cbcunc commented on papers/zain_miller/paper.rst
> +other models did not produce similar results until about 10-40 epochs
Change "until about 10-40 epochs in" to "until after about 10-40 epochs."

2022-06-24 20:06 UTC, cbcunc commented on papers/zain_miller/paper.rst
> +methods—Zero-Phase PCA Sphering (ZCA) and Sparse Autoencoders (SAE)—for
Use commas instead of emdashes here.

2022-06-24 20:06 UTC, cbcunc commented on papers/zain_miller/paper.rst
> +evaluate the feasibility of low-level feature extraction in improving
"Feasibility for" instead of "Feasibility in."

2022-06-24 20:06 UTC, cbcunc commented on papers/zain_miller/paper.rst
> +attract some attention. While regular CNNs are proficient at filtering,
This is quite the run-on sentence. For a start, end one sentence at "for features."

2022-06-24 20:06 UTC, cbcunc commented on papers/zain_miller/paper.rst
> +kernel, affect the final output — instead, SCS activations are dictated
Run-on. Start a new sentence at "instead."

2022-06-24 20:06 UTC, cbcunc commented on papers/zain_miller/paper.rst
> +layers — this way the model is a true generalization of the canonical
Run-on. Start a new sentence at "this way."

2022-06-24 20:06 UTC, cbcunc commented on papers/zain_miller/refs.bib
> +@article{zca,
This is a master's thesis. Please provide a complete citation.

2022-06-24 20:06 UTC, cbcunc commented on papers/zain_miller/refs.bib
> +@inproceedings{cilia,
Provide DOI for *all* citations. This one should be easy.

2022-06-24 20:06 UTC, cbcunc commented on papers/zain_miller/refs.bib
> +  pages={299ra124--299ra124},
Please use either the .. unicode:: directive or bars to represent the en dashes for portability. https://docutils.sourceforge.io/FAQ.html#how-can-i-represent-esoteric-characters-e-g-character-entities-in-a-document

2022-06-24 20:06 UTC, cbcunc commented on papers/zain_miller/refs.bib
> +  pages={1677--1689},
Please use either the .. unicode:: directive or bars to represent the en dashes for portability. https://docutils.sourceforge.io/FAQ.html#how-can-i-represent-esoteric-characters-e-g-character-entities-in-a-document

2022-06-24 20:07 UTC, cbcunc requested changes
Changes requested in previous review.

2022-06-27 04:29 UTC, deniederhut commented on papers/zain_miller/refs.bib
> +  pages={299ra124--299ra124},
I think we're injecting a redefinition into the rst files for this -- https://github.com/scipy-conference/scipy_proceedings/blob/632099a7e62d192a5d66156dc70547fd9f35cb81/publisher/build_paper.py#L40

2022-06-27 04:30 UTC, deniederhut commented
@scoobies mark pending comment

2022-06-29 19:19 UTC, cbcunc commented
@ENM185, @Micky774, please respond to review comments with changes or comments which resolve the conversation. Final acceptance decisions are July 4.

2022-07-01 20:52 UTC, ENM185 commented on papers/zain_miller/paper.rst
> +understanding ciliopathies; however, this is generally an
Starting a new sentence here. Which verb are you referring to being in the passive voice here? Or do you just mean in general?

2022-07-02 01:18 UTC, ENM185 commented on papers/zain_miller/refs.bib
> +@inproceedings{cilia,
What do you recommend doing for the SCS citation? It's relatively novel and still doesn't have any full papers published.

2022-07-04 19:32 UTC, deniederhut commented
@cbcunc do you feel this paper is now ready for inclusion in the proceedings?

2022-07-06 11:01 UTC, deniederhut commented
@cbcunc GitHub shows that you are still requesting changes on this paper -- is it ready for publication?

2022-07-08 18:51 UTC, cbcunc approved these changes

2022-07-08 18:51 UTC, cbcunc commented
@scoobies mark ready

2022-07-09 00:07 UTC, deniederhut requested changes

2022-07-09 00:07 UTC, deniederhut commented on papers/zain_miller/refs.bib
> +@article{SBD,
There are three very similar links in this reference (and a few others). Could we keep the DOI, but drop any redundant URLs?
<img width="373" alt="Screen Shot 2022-07-08 at 7 02 11 PM" src="https://user-images.githubusercontent.com/6868396/178083578-2c3fb5b9-0c50-4892-9ecd-5e4926ead657.png">

2022-07-09 00:07 UTC, deniederhut commented on papers/zain_miller/paper.rst
> +:corresponding:
Is it okay if we choose one corresponding author? Two don't render very well in our system:
<img width="386" alt="Screen Shot 2022-07-08 at 7 00 23 PM" src="https://user-images.githubusercontent.com/6868396/178083642-d8a3eed7-ac1d-4d4d-bbde-4834d77c7c62.png">

2022-07-09 00:08 UTC, deniederhut commented
@scoobies mark pending comment

2022-07-09 00:39 UTC, Micky774 commented
@deniederhut Should be good now

2022-07-10 21:34 UTC, deniederhut approved these changes
Thanks for making those changes!

2022-07-10 21:35 UTC, deniederhut commented
@scoobies mark ready

2022-07-10 21:50 UTC, merged