Paper: Temporal Word Embeddings Analysis for Disease Prevention
scipy-conference/scipy_proceedings pull request #701
Opened 2022-05-27 15:40 UTC by ahy69195

If you are creating this PR in order to submit a draft of your paper,
see http://procbuild.scipy.org/ for logs generated by the build
process.

See the [project readme](https://github.com/scipy-conference/scipy_proceedings#build-your-paper)
for more information.

*Editor*:  

*Reviewers*:

2022-05-27 15:40 UTC, scoobies commented
Hi!, I'm @scoobies, a friendly bot.

Type ```@scoobies help``` to discover how I can help you.

2022-05-27 20:30 UTC, mepa commented
Hi @ahy69195! Looks like your `environment` folder got pushed to the branch. Could you please delete it from this PR?

2022-05-29 00:40 UTC, mepa commented on papers/nathan_jacobi_ivan_mo_albert_you/paper.rst
> +Human languages experience continual changes to their semantic structures. Natural language processing techniques allow us to examine these semantic alterations through methods such as word embedding
Could you please try removing the space between `:cite:` and the label reference in the above paragraph, and in all instances throughout the file (there are 14 total)?

I think that might fix the error seen in the build server logs:
```
! LaTeX Error: Something's wrong--perhaps a missing \item.
```

2022-05-29 04:16 UTC, imoiwm commented on papers/nathan_jacobi_ivan_mo_albert_you/paper.rst
> +Human languages experience continual changes to their semantic structures. Natural language processing techniques allow us to examine these semantic alterations through methods such as word embedding
Hi Meghann,

I removed every space that I saw for :label:, :cite:, :ref:, and :math: tags and their references and didn't see anything I missed when I looked back over afterwards. However, it still seems that our make paper script isn't able to generate a PDF- an issue we were also having with our local copy. We attempted to troubleshoot this for a couple hours and were wondering if you had any more insight. Thank you for the quick suggestion!

2022-05-29 14:30 UTC, mepa commented on papers/nathan_jacobi_ivan_mo_albert_you/paper.rst
> +dimensions :math:`*V* \times *V*`. Following the generation of each of these co-occurrence matrices, a :math:`*V* \times *V*`` dimensioned Positive Pointwise Mutual Information
```suggestion
dimensions :math:`*V* \times *V*`. Following the generation of each of these co-occurrence matrices, a :math:`*V* \times *V*` dimensioned Positive Pointwise Mutual Information
```
Remove extra backtic (this won't affect the build, but I noticed it while looking)

2022-05-29 14:30 UTC, mepa commented on papers/nathan_jacobi_ivan_mo_albert_you/paper.rst
> ++----------------------+-------------+-------------+--------------+----------------+-------------+
Format the table as follows to get the table caption and associated label. Also, this particular table won't fit within one column, so one can specify to make it wide with `:class: w` (see the example paper in `papers/00_bibderwalt`).
```
.. table:: Five closest words of hand-selected terms compared between word2vec and dynamic word embeddings generated by our model :label:`compare`
   :class: w

   +----------------------+-------------+-------------+--------------+----------------+-------------+
   | Word                 | 1st closest | 2nd closest | 3rd closest  | 4th closest    | 5th closest |
   +======================+=============+=============+==============+================+=============+
   | gymnastics (dwe)     | olympics    | olympic     | nowadays     | medal          | everytime   |
   +----------------------+-------------+-------------+--------------+----------------+-------------+
   | gymnastics (w2v)     | downfall    | empire      | swept        | qualifying     | heel        |
   +----------------------+-------------+-------------+--------------+----------------+-------------+
   | sanders (dwe)        | bernie      | democratic  | nominated    | demsinphilly   | obama       |
   +----------------------+-------------+-------------+--------------+----------------+-------------+
   | sanders (w2v)        | wikileaks   | agencies    | podesta      | infowars       | israeli     |
   +----------------------+-------------+-------------+--------------+----------------+-------------+
   | username (dwe)       | snapchat    | profile     | instagram    | deleted        | comment     |
   +----------------------+-------------+-------------+--------------+----------------+-------------+
   | username (w2v)       | discipline  | writer      | seals        | merit          | nanti       |
   +----------------------+-------------+-------------+--------------+----------------+-------------+
```

2022-05-29 14:30 UTC, mepa commented on papers/nathan_jacobi_ivan_mo_albert_you/paper.rst
> ++-----------------------------------------+-------------------------+----------------------+
Reformat table.  You may also want to shorten `Number of Shared Closest Words` so the column isn't so wide.

2022-05-29 14:30 UTC, mepa commented on papers/nathan_jacobi_ivan_mo_albert_you/paper.rst
> ++------------+------------+-------------------+-------------+
Reformat table.

2022-05-29 14:30 UTC, mepa commented on papers/nathan_jacobi_ivan_mo_albert_you/paper.rst
> ++------------+------------+-------------------+-------------+
Reformat table.

2022-05-29 14:30 UTC, mepa commented on papers/nathan_jacobi_ivan_mo_albert_you/paper.rst
> +Two dimensional representations of embeddings, generated by UMAP, can be seen in figure :ref:`plot0` and figure :ref:`plot17`. Figure :ref:`plot0` represents the embedding generated for the first tim
The current build error seems to be caused by the underscore in `zoomed_plot0`? Replacing this with `zoomedplot0` and similarly updating all other labels with underscores (i.e., `hiv_plot` and `med_plot`) allowed me to compile the paper locally.

2022-05-29 14:30 UTC, mepa commented on papers/nathan_jacobi_ivan_mo_albert_you/paper.rst
> +   Zoomed in 2D Embeddings of Outlying Cluster in Time Bucket 0. :label:`zoomed_plot0`
```suggestion
   Zoomed in 2D Embeddings of Outlying Cluster in Time Bucket 0. :label:`zoomedplot0`
```

2022-05-29 14:30 UTC, mepa commented on papers/nathan_jacobi_ivan_mo_albert_you/paper.rst
> +The results of clustering led to semantic shifts of medical related terms and HIV related terms having higher incidences than other terms in 2 clusters each: clusters 3 and 7 for HIV terms, and clust
- `med_plot` -> `medplot`
- `hiv_plot` -> `hivplot`

2022-05-29 14:30 UTC, mepa commented on papers/nathan_jacobi_ivan_mo_albert_you/paper.rst
> +   Bar Graph Showing KMeans Clustering Distribution of HIVl Terms against All Terms :label:`hiv_plot`
```suggestion
   Bar Graph Showing KMeans Clustering Distribution of HIVl Terms against All Terms :label:`hivplot`
```

2022-05-29 14:30 UTC, mepa commented on papers/nathan_jacobi_ivan_mo_albert_you/paper.rst
> +   Bar Graph Showing KMeans Clustering Distribution of Medical Terms against All Terms :label:`med_plot`
```suggestion
   Bar Graph Showing KMeans Clustering Distribution of Medical Terms against All Terms :label:`medplot`
```

2022-05-29 14:35 UTC, mepa commented on papers/nathan_jacobi_ivan_mo_albert_you/paper.rst
> +Human languages experience continual changes to their semantic structures. Natural language processing techniques allow us to examine these semantic alterations through methods such as word embedding
Hi @imoiwm, sorry it took some hours to troubleshoot! I believe the current error will be fixed by removing underscores from labels. Please see my specific inline comments. 

I also mentioned table formatting changes, but you should be able to generate a PDF even without making those.

Anyway, let's hope it will work this time around 🤞.

2022-05-29 20:48 UTC, deniederhut commented
@scoobies mark paper

2022-05-29 20:49 UTC, deniederhut commented
@scoobies build status

2022-05-29 20:49 UTC, scoobies commented
{"ahy69195-2022"=>{"data"=>{"build_output"=>"[*] Updating proceedings build tools in {self.master_repo_path}...\nAlready up to date.\n[*] Check out paper repository...\nCloning into '/tmp/tmpryupk6hg'...\nMoving proceedings build tools to temp directory...\n[*] Build the paper...\nBuilding: nathan_jacobi_ivan_mo_albert_you\n*** Warning: /tmp/tmpryupk6hg/publisher/../output/nathan_jacobi_ivan_mo_albert_you/paper_stats.json does not exist.\nPDFLaTeX error output:\n================================================================================\nThis is pdfTeX, Version 3.14159265-2.6-1.40.18 (TeX Live 2017/Debian) (preloaded format=pdflatex)\n restricted \\write18 enabled.\nentering extended mode\n(./paper.tex\nLaTeX2e <2017-04-15>\nBabel <3.18> and hyphenation patterns for 3 language(s) loaded.\n(./IEEEtran.cls\nDocument Class: IEEEtran 2015/08/26 V1.8b by Michael Shell\n-- See the \"IEEEtran_HOWTO\" manual for usage information.\n-- http://www.michaelshell.org/tex/ieeetran/\n(/usr/share/texlive/texmf-dist/tex/latex/psnfss/ot1ppl.fd)\n-- Using IEEE Computer Society mode.\n-- Using 8.5in x 11in (letter) paper.\n-- Using PDF output.\n-- This is a 10 point document.\n) (/usr/share/texlive/texmf-dist/tex/latex/cmap/cmap.sty)\n(/usr/share/texlive/texmf-dist/tex/latex/base/ifthen.sty)\n(/usr/share/texlive/texmf-dist/tex/latex/base/fontenc.sty\n(/usr/share/texlive/texmf-dist/tex/latex/base/t1enc.def)\n(/usr/share/texlive/texmf-dist/tex/latex/psnfss/t1ppl.fd)<<t1.cmap>>)\n(/usr/share/texlive/texmf-dist/tex/latex/base/inputenc.sty\n(/usr/share/texlive/texmf-dist/tex/latex/base/utf8.def\n(/usr/share/texlive/texmf-dist/tex/latex/base/t1enc.dfu)\n(/usr/share/texlive/texmf-dist/tex/latex/base/ot1enc.dfu)\n(/usr/share/texlive/texmf-dist/tex/latex/base/omsenc.dfu)))\n(/usr/share/texlive/texmf-dist/tex/latex/amsmath/amsmath.sty\nFor additional information on amsmath, use the `?' option.\n(/usr/share/texlive/texmf-dist/tex/latex/amsmath/amstext.sty\n(/usr/share/texlive/texmf-dist/tex/latex/amsmath/amsgen.sty))\n(/usr/share/texlive/texmf-dist/tex/latex/amsmath/amsbsy.sty)\n(/usr/share/texlive/texmf-dist/tex/latex/amsmath/amsopn.sty))\n(/usr/share/texlive/texmf-dist/tex/latex/booktabs/booktabs.sty)\n(/usr/share/texlive/texmf-dist/tex/latex/caption/caption.sty\n(/usr/share/texlive/texmf-dist/tex/latex/caption/caption3.sty\n(/usr/share/texlive/texmf-dist/tex/latex/graphics/keyval.sty))\n\nPackage caption Warning: Unsupported document class (or package) detected,\n(caption)                usage of the caption package is not recommended.\nSee the caption package documentation for explanation.\n\n) (/usr/share/texlive/texmf-dist/tex/latex/float/float.sty)\n(/usr/share/texlive/texmf-dist/tex/latex/tools/longtable.sty)\n(/usr/share/texlive/texmf-dist/tex/latex/caption/ltcaption.sty)\n(/usr/share/texlive/texmf-dist/tex/latex/tools/array.sty) (./scipy.sty\n(./status.sty (./draftwatermark.sty (./everypage.sty)\n(/usr/share/texlive/texmf-dist/tex/latex/graphics/graphicx.sty\n(/usr/share/texlive/texmf-dist/tex/latex/graphics/graphics.sty\n(/usr/share/texlive/texmf-dist/tex/latex/graphics/trig.sty)\n(/usr/share/texlive/texmf-dist/tex/latex/graphics-cfg/graphics.cfg)\n(/usr/share/texlive/texmf-dist/tex/latex/graphics-def/pdftex.def)))\n(/usr/share/texlive/texmf-dist/tex/latex/graphics/color.sty\n(/usr/share/texlive/texmf-dist/tex/latex/graphics-cfg/color.cfg))))\n(/usr/share/texlive/texmf-dist/tex/latex/psnfss/mathptmx.sty)\n(/usr/share/texlive/texmf-dist/tex/latex/psnfss/helvet.sty)\n(/usr/share/texlive/texmf-dist/tex/latex/psnfss/courier.sty)\n(/usr/share/texlive/texmf-dist/tex/latex/amsfonts/amsfonts.sty)\n(/usr/share/texlive/texmf-dist/tex/latex/amsfonts/amssymb.sty)\n(/usr/share/texlive/texmf-dist/tex/latex/tools/bm.sty)\n(/usr/share/texlive/texmf-dist/tex/latex/hyperref/hyperref.sty\n(/usr/share/texlive/texmf-dist/tex/generic/oberdiek/hobsub-hyperref.sty\n(/usr/share/texlive/texmf-dist/tex/generic/oberdiek/hobsub-generic.sty))\n(/usr/share/texlive/texmf-dist/tex/generic/ifxetex/ifxetex.sty)\n(/usr/share/texlive/texmf-dist/tex/latex/oberdiek/auxhook.sty)\n(/usr/share/texlive/texmf-dist/tex/latex/oberdiek/kvoptions.sty)\n(/usr/share/texlive/texmf-dist/tex/latex/hyperref/pd1enc.def)\n(/usr/share/texlive/texmf-dist/tex/latex/latexconfig/hyperref.cfg)\n(/usr/share/texlive/texmf-dist/tex/latex/url/url.sty))\n(/usr/share/texlive/texmf-dist/tex/latex/hyperref/hpdftex.def\n(/usr/share/texlive/texmf-dist/tex/latex/oberdiek/rerunfilecheck.sty))\n\nPackage hyperref Warning: Option `pdftex' has already been used,\n(hyperref)                setting the option has no effect on input line 43.\n\n(/usr/share/texlive/texmf-dist/tex/latex/multirow/multirow.sty)\n(/usr/share/texlive/texmf-dist/tex/latex/base/textcomp.sty\n(/usr/share/texlive/texmf-dist/tex/latex/base/ts1enc.def\n(/usr/share/texlive/texmf-dist/tex/latex/base/ts1enc.dfu)))\n(/usr/share/texlive/texmf-dist/tex/latex/upquote/upquote.sty)\n(/usr/share/texlive/texmf-dist/tex/latex/fancyvrb/fancyvrb.sty\nStyle option: `fancyvrb' v2.7a, with DG/SPQR fixes, and firstline=lastline fix \n<2008/02/07> (tvz)))\nNo file paper.aux.\n(/usr/share/texlive/texmf-dist/tex/latex/base/ts1cmr.fd)\n(/usr/share/texlive/texmf-dist/tex/latex/psnfss/t1ptm.fd)\n-- Lines per column: 61 (exact).\n(/usr/share/texlive/texmf-dist/tex/context/base/mkii/supp-pdf.mkii\n[Loading MPS to PDF converter (version 2006.09.02).]\n) (/usr/share/texlive/texmf-dist/tex/latex/oberdiek/epstopdf-base.sty\n(/usr/share/texlive/texmf-dist/tex/latex/oberdiek/grfext.sty)\n(/usr/share/texlive/texmf-dist/tex/latex/latexconfig/epstopdf-sys.cfg))\n(/usr/share/texlive/texmf-dist/tex/latex/hyperref/nameref.sty\n(/usr/share/texlive/texmf-dist/tex/generic/oberdiek/gettitlestring.sty))\n(/usr/share/texlive/texmf-dist/tex/latex/psnfss/t1phv.fd)\n(/usr/share/texlive/texmf-dist/tex/latex/psnfss/ot1ztmcm.fd)<<ot1.cmap>>\n(/usr/share/texlive/texmf-dist/tex/latex/psnfss/omlztmcm.fd)<<oml.cmap>>\n(/usr/share/texlive/texmf-dist/tex/latex/psnfss/omsztmcm.fd)<<oms.cmap>>\n(/usr/share/texlive/texmf-dist/tex/latex/psnfss/omxztmcm.fd)<<omx.cmap>>\n(/usr/share/texlive/texmf-dist/tex/latex/psnfss/ot1ptm.fd)\n(/usr/share/texlive/texmf-dist/tex/latex/psnfss/upzd.fd)\n(/usr/share/texlive/texmf-dist/tex/latex/psnfss/ts1ptm.fd) (./page_numbers.tex)\n\nLaTeX Warning: Citation `vec13' on page 1 undefined on input line 184.\n\n\nLaTeX Warning: Citation `dia16' on page 1 undefined on input line 188.\n\n\nLaTeX Warning: Citation `dwe18' on page 1 undefined on input line 188.\n\n\nLaTeX Warning: Citation `oxy16' on page 1 undefined on input line 200.\n\n\nLaTeX Warning: Citation `sco18' on page 1 undefined on input line 200.\n\n\nLaTeX Warning: Citation `pol17' on page 1 undefined on input line 200.\n\n[1{/var/lib/texmf/fonts/map/pdftex/updmap/pdftex.map}]\n\nLaTeX Warning: Citation `vec13' on page 2 undefined on input line 209.\n\n\nLaTeX Warning: Citation `dwe18' on page 2 undefined on input line 217.\n\n\nLaTeX Warning: Citation `dwe18' on page 2 undefined on input line 220.\n\n\nLaTeX Warning: Citation `dwe18' on page 2 undefined on input line 222.\n\n\nOverfull \\hbox (42.46178pt too wide) detected at line 224\n\\OML/ztmcm/m/it/9.53561 A \\OT1/ztmcm/m/n/9.53561 = \\OML/ztmcm/m/it/9.53561 U\\OT\n1/ztmcm/m/n/9.53561 (\\OML/ztmcm/m/it/9.53561 t\\OT1/ztmcm/m/n/9.53561 )[]\\OML/zt\nmcm/m/it/9.53561 U\\OT1/ztmcm/m/n/9.53561 (\\OML/ztmcm/m/it/9.53561 t\\OT1/ztmcm/m\n/n/9.53561 ) + (\\OML/ztmcm/m/it/9.53561 ^^M \\OT1/ztmcm/m/n/9.53561 + \\OML/ztmcm\n/m/it/9.53561 ^^U \\OT1/ztmcm/m/n/9.53561 + 2\\OML/ztmcm/m/it/9.53561 ^^\\\\OT1/ztm\ncm/m/n/9.53561 )\\OML/ztmcm/m/it/9.53561 I; [] B \\OT1/ztmcm/m/n/9.53561 = \\OML/z\ntmcm/m/it/9.53561 Y\\OT1/ztmcm/m/n/9.53561 (\\OML/ztmcm/m/it/9.53561 t\\OT1/ztmcm/\nm/n/9.53561 )\\OML/ztmcm/m/it/9.53561 U\\OT1/ztmcm/m/n/9.53561 (\\OML/ztmcm/m/it/9\n.53561 t\\OT1/ztmcm/m/n/9.53561 ) + \\OML/ztmcm/m/it/9.53561 ^^MU\\OT1/ztmcm/m/n/9\n.53561 (\\OML/ztmcm/m/it/9.53561 t\\OT1/ztmcm/m/n/9.53561 ) + [...]

2022-05-29 20:49 UTC, deniederhut commented
@scoobies mark server fail

2022-05-29 20:49 UTC, deniederhut commented
@scoobies assign @deniederhut as editor

2022-05-29 20:49 UTC, scoobies commented
Assigned! @deniederhut is now the editor

2022-05-30 00:20 UTC, imoiwm commented on papers/nathan_jacobi_ivan_mo_albert_you/paper.rst
> +Human languages experience continual changes to their semantic structures. Natural language processing techniques allow us to examine these semantic alterations through methods such as word embedding
Hi @mepa, I made the changes regarding underscores, yet the paper still seems to fail when building. Also, I was unable to make the table formatting changes due to them causing more errors:

```
<string>:196: (WARNING/2) Content block expected for the "table" directive; none found.

.. table:: Five closest words of hand-selected terms compared between word2vec and dynamic word embeddings generated by our model :label:`compare`

<string>:214: (WARNING/2) Content block expected for the "table" directive; none found.

.. table:: The percentage and counts of our vocabulary sharing a given number of closest words (SCW for short) between word2vec and our model for time bucket #17. :label:`sharedclosest`

<string>:233: (WARNING/2) Block quote ends without a blank line; unexpected unindent.
<string>:310: (WARNING/2) Content block expected for the "table" directive; none found.

.. table:: Distribution of medical terms and all terms within k-means clusters :label:`medterm`

<string>:336: (WARNING/2) Content block expected for the "table" directive; none found.

.. table:: Distribution of HIV terms and all terms within k-means clusters :label:`hivterm`
```

When I don't include the table updates, only the block quote warning remains. I'm not sure of the cause, and we're still unable to build. 

```
<string>:233: (WARNING/2) Block quote ends without a blank line; unexpected unindent.
```

Finally, when I personally attempted to locally build the paper, I encountered a prompt to install the file ```tex\latex\ieeetran\IEEEtran.cls``` from the package ```ieeetran```. I'm unable to manually install this, and the issue still persisted after I confirmed I had installed everything from the ```requirements.txt``` file.

I opened an issue (https://github.com/scipy-conference/scipy_proceedings/issues/728) for this which repeats most, if not all, of this information as well.

Please let me know what you think if you're able. Thank you again for your quick support!

2022-06-01 02:53 UTC, deniederhut commented on papers/nathan_jacobi_ivan_mo_albert_you/paper.rst
> ++----------- ----+-------------------------+---------------------+
I think you're missing a dash here

2022-06-01 02:55 UTC, deniederhut commented
Hi @imoiwm ! Have you had a chance to add the table commands that Meghann pointed out were missing?

2022-06-01 03:45 UTC, imoiwm commented
Hi @deniederhut! I decided against adding the table commands for now since, while debugging my local build, they only contributed more errors (I'm not sure how to more directly reference it but I listed the errors in a previous comment linked here: https://github.com/scipy-conference/scipy_proceedings/pull/701#discussion_r884345944). 

I decided to leave them off in case another project member could build the paper without the commands and then look more into just the table commands.

Also, in your previous comment, where are we missing a dash? Sorry, I'm having some trouble understanding the diff log included.

Thank you so much for the comments and feedback too!

2022-06-02 11:45 UTC, deniederhut commented
Hi @imoiwm ! The `.. table:: ` commands that Meghann is talking about are part of the restructured text syntax for tables. I don't expect your paper will build correctly without them.

As for the dash, here's what I see on GitHub:

<img width="652" alt="Screen Shot 2022-06-02 at 6 40 59 AM" src="https://user-images.githubusercontent.com/6868396/171621729-1186b5a3-0ac9-4967-a3bb-88697a19ea0f.png">

You will notice in line 209, the bottom line of the table is not continuous. This is the source of the "block quote ends with a blank line" error.

I believe Meghann and I have both gotten your paper to compile locally by making these two changes -- adding the missing dashed line and adding the table commands. Please make these changes and push them to GitHub. We can't include this paper in the proceedings unless the paper compiles.

2022-06-02 11:45 UTC, deniederhut commented
@scoobies add @vidhi-am to reviewers

2022-06-02 11:45 UTC, scoobies commented
@vidhi-am added to the reviewers list!

2022-06-03 08:24 UTC, imoiwm commented
@deniederhut @mepa I implemented the changes mentioned, and I was able to at least create and view a PDF of our paper now! Although, I do need to click the "Build LaTeX Project" button on the ```.tex``` file created in VSCode as opposed to the ```make_paper.sh``` script going straight from ```.rst``` to ```.pdf``` (which I'm assuming is part of the issue with our PDF not being found on the build server either).

A lot of the issues with initially getting a PDF at all were coming from my VSCode setup not properly syncing up with the MiKTeX installation I had, so I had to locally download the console and install a lot of packages there. 

Unfortunately, I'm still having issues with the final build itself. When I don't include the ```.. table::``` commands in the ```.rst``` file, I'm able to load all of the tables locally. However, when I add back in the table commands, the first column header of each table goes missing and in place of the table captions are these error blocks (see images below).

1) First column header missing
![missingcolheader](https://user-images.githubusercontent.com/20688005/171817222-6237e1df-6029-4ef1-823b-b983e37c4370.PNG)

2) Error blocks in place of captions
![tableerrorpersist](https://user-images.githubusercontent.com/20688005/171815569-89a31ac5-24f5-488e-83f0-81f4de0051c9.PNG)

**I still haven't been able to get a PDF on the build server either.** Do you have any further suggestions in this case?

----------------------

Finally, looking ahead, I was wondering if you had any suggestions for improving the layout of our paper. When I remove the table commands and load all of the tables, there are some layout issues that I'm not sure of how to solve. The extra-wide table, an overlapping equation, and strangely-placed captions are the primary issues (depicted below, respectively).

1) Table is too wide
![toowidetable](https://user-images.githubusercontent.com/20688005/171815875-293bb9ea-ad1e-4f22-a8aa-e11c24ba2cf5.PNG)

2) Equation overlaps with next column
![overlappingeq](https://user-images.githubusercontent.com/20688005/171815869-9527ab26-11ef-429f-8ee1-3041e6a947a1.PNG)

3) Captions are placed far away from their tables
![confusinglayout](https://user-images.githubusercontent.com/20688005/171815860-4223f0a3-858b-441f-bcb6-c04c38a42bac.PNG)

Please let me know what you think. __Thank you both again for all of your help!__

2022-06-04 22:33 UTC, deniederhut commented
Hi @ahy69195 ! Your paper isn't building because you still have syntax errors in your file. Whitespace is significant in rst, so it matters that your table definitions are indented. Here is what your tables should look like:

```rst
.. table:: This is the caption for the materials table. :label:`mtable`

   +------------+----------------+
   | Material   | Units          |
   +============+================+
   | Stone      | 3              |
   +------------+----------------+
   | Water      | 12             |
   +------------+----------------+
   | Cement     | :math:`\alpha` |
   +------------+----------------+
```

Note the indentation! That table is taken from the example paper here https://raw.githubusercontent.com/scipy-conference/scipy_proceedings/2022/papers/00_bibderwalt/00_bibderwalt.rst, which also has an example of how to format a table that is wider than the text columns. When you fix the syntax errors, your captions will also be placed appropriately. Hope this helps!

2022-06-06 06:04 UTC, imoiwm commented
Hi @deniederhut ! I got the paper to build on the server, and I'm currently waiting to hear back from my peers on other revisions/updates to make. Otherwise, I believe we were able to get most necessary things working for now. Thank you again for all that you've done!

2022-06-07 02:52 UTC, deniederhut commented
@scoobies build paper

2022-06-07 02:52 UTC, scoobies commented
building paper...

2022-06-07 02:52 UTC, scoobies commented
{"data"=>{"info"=>"Build for paper ahy69195-2022 scheduled.  Note that builds are only executed if the current build attempt is more than 5 minutes old."}, "status"=>"success"}

2022-06-07 02:57 UTC, deniederhut commented
@scoobies build status

2022-06-07 02:57 UTC, scoobies commented
{"ahy69195-2022"=>{"data"=>{"build_output"=>"[*] Updating proceedings build tools in {self.master_repo_path}...\nFrom https://github.com/scipy-conference/scipy_proceedings\n   4850b25..632099a  2022       -> origin/2022\nUpdating 4850b25..632099a\nFast-forward\n README.md | 20 ++++++++++----------\n 1 file changed, 10 insertions(+), 10 deletions(-)\n[*] Check out paper repository...\nCloning into '/tmp/tmpdjblysnk'...\nMoving proceedings build tools to temp directory...\n[*] Build the paper...\nBuilding: nathan_jacobi_ivan_mo_albert_you\n*** Warning: /tmp/tmpdjblysnk/publisher/../output/nathan_jacobi_ivan_mo_albert_you/paper_stats.json does not exist.\n", "build_pdf_path"=>"/procbuild/procbuild/../cache/ahy69195-2022.pdf", "build_status"=>"success", "build_timestamp"=>"07/06 02:52"}, "status"=>"success"}}

2022-06-07 02:58 UTC, deniederhut commented
@scoobies mark server success

2022-06-07 02:59 UTC, deniederhut commented
@scoobies mark needs review

2022-06-07 02:59 UTC, deniederhut commented
Hi! We've moved the deadline for first reviews back one week, to June 16th, to give us a little more time to find reviewers for all the papers this year. You can see the updated full timeline at https://github.com/scipy-conference/scipy_proceedings#timeline-for-2022.

2022-06-10 17:20 UTC, deniederhut commented
@scoobies add @edrogers to reviewers

2022-06-10 17:20 UTC, scoobies commented
@edrogers added to the reviewers list!

2022-06-14 00:40 UTC, deniederhut commented
Hey @vidhi-am and @edrogers! How are the reviews coming along?

2022-06-14 01:57 UTC, edrogers commented
@deniederhut, actively reviewing now. Thanks for checking in!

2022-06-15 23:59 UTC, deniederhut commented
Hey @edrogers and @vidhi-am! Friendly reminder that reviews are due tomorrow

2022-06-16 04:09 UTC, edrogers requested changes
Thank you for submitting to the SciPy Proceedings!

I've read your paper carefully and have many comments, questions, and requests for changes. 

A few overall comments:

1. I'm worried about your methodology. Any time an analysis uses high-dimensional vectors for word embeddings, interpretation and evaluation can be tricky. When we use qualitative metrics, we risk hand-picking favorable examples to support our case. In this paper, I don't see sufficient quantitative methods used to evaluate the hypothesis. (See my notes below.)
2. I'm also specifically skeptical of your use of K-Means for a supervised learning problem. Given that you know *a priori* whether any given word is a medical or HIV/AIDS term, you should use these labels to maximize the performance of your model.
3. Overall, I'll point out that the approach here looks and feels very out-of-date with modern computational linguistics. The most recent citation among the references is from 2018, and the entire paper fails to mention transformers and self-attention, nor the embedding techniques they permit -- e.g., BERT. As of 2022, it's hard to see the Future Work section as complete without some discussion of how these new approaches could be harnessed.
4. As far as I can tell, you haven't made any code available for review. According to the [Suggested Review Criteria](https://github.com/scipy-conference/scipy_proceedings/blob/master/review_criteria.md), "Source code essential to the conclusions of the paper should be made available to the reader."

Thanks again for your submission. Happy to discuss any of these issues further.

2022-06-16 04:09 UTC, edrogers commented on papers/nathan_jacobi_ivan_mo_albert_you/paper.rst
> +The combined vocabulary *V* consisted of the top 10,000 words across *D* as well as an additional 8,156 medical terms that occurred within all data handled in scripts utilized the pandas Python packa
I think this sentence contains a syntax or typographical error. Can you double-check?

2022-06-16 04:09 UTC, edrogers commented on papers/nathan_jacobi_ivan_mo_albert_you/paper.rst
> +To study semantic shifts through time, the corpus was split into 18 temporal buckets, each spanning a 2 month period.
According to the [Suggested Review Criteria](https://github.com/scipy-conference/scipy_proceedings/blob/master/review_criteria.md):

> Prose should clearly and consistently communicate the narrative (e.g. consistent tense and person; use of active voice; etc)

It seems you're switching between active voice ("We hypothesize", "we create", "we predict", etc), and passive voice ("the corpus was split", "Common stop words were removed", etc)

2022-06-16 04:09 UTC, edrogers commented on papers/nathan_jacobi_ivan_mo_albert_you/paper.rst
> +Generating word embeddings can be done through 2 primary methods: continuous bag-of-words (CBOW) and skip-gram :cite:`vec13`.
There are, of course, other methods of generating word embeddings -- these two are merely the model architectures typically used to train a word2vec algorithm. I suggest rewording to clarify.

2022-06-16 04:09 UTC, edrogers commented on papers/nathan_jacobi_ivan_mo_albert_you/paper.rst
> +the second being a list of medical terms taken from a published list of terms taken from combining two medical spell check libraries.
Which medical spell check libraries, specifically? (Are they freely available?)

2022-06-16 04:09 UTC, edrogers commented on papers/nathan_jacobi_ivan_mo_albert_you/paper.rst
> +applied to each temporal bucket. Each time bucket First, co-occurrence matrices were created, with a window size w = 5. These matrices contained
> Each time bucket First, co-occurrence matrices were created,

☝️ Typo here

2022-06-16 04:09 UTC, edrogers commented on papers/nathan_jacobi_ivan_mo_albert_you/paper.rst
> +dimensions :math:`*V* \times *V*`. Following the generation of each of these co-occurrence matrices, a :math:`*V* \times *V*` dimensioned Positive Pointwise Mutual Information
It appears that, within a `:math:` block, you don't need the '*' characters.

2022-06-16 04:09 UTC, edrogers commented on papers/nathan_jacobi_ivan_mo_albert_you/paper.rst
> +   \text{PPMI}(t, L)_{w,c} = \text{max}\{\text{PMI}(D_t, L)_{w,c},0\},
Presumably, `L` is the context window size in this equation. Could you explicitly state what `L` is somewhere before or near this equation?

2022-06-16 04:09 UTC, edrogers commented on papers/nathan_jacobi_ivan_mo_albert_you/paper.rst
> +where w and c are two words in *V* Embeddings generated by word2vec utilize PMI matrices, where given embedding vectors utilize the following equation :cite:`dwe18`:
> words in *V* Embeddings generated

Missing punctuation here?

2022-06-16 04:09 UTC, edrogers commented on papers/nathan_jacobi_ivan_mo_albert_you/paper.rst
> +where w and c are two words in *V* Embeddings generated by word2vec utilize PMI matrices, where given embedding vectors utilize the following equation :cite:`dwe18`:
> Embeddings generated by word2vec utilize PMI matrices, where given embedding vectors utilize the following equation

I believe this approximation merely gives the "key idea" behind word2vec (and GloVe). Do the embeddings themselves utilize the equation? (Aren't they generated by a neural network with its own loss function?)

2022-06-16 04:09 UTC, edrogers commented on papers/nathan_jacobi_ivan_mo_albert_you/paper.rst
> +.. [#] The original equation uses W(t), but this acts as identical to U(t) in the code. We replaced it here to improve readability.
These footnotes do not have a matching mark in the above equations

2022-06-16 04:09 UTC, edrogers commented on papers/nathan_jacobi_ivan_mo_albert_you/paper.rst
> +   B = Y(t)U(t) + \gamma U(t) + \tau (U(t - 1) + U(t + 1))
`\gamma`, `\lambda`, and `\tau` are left undefined

2022-06-16 04:09 UTC, edrogers commented on papers/nathan_jacobi_ivan_mo_albert_you/paper.rst
> +The combined vocabulary *V* consisted of the top 10,000 words across *D* as well as an additional 8,156 medical terms that occurred within all data handled in scripts utilized the pandas Python packa
Here you define *V* as the combined vocabulary. In later portions, you use it to describe the size of the combined vocabulary. You should distinguish the vocabulary and its size by using "norm" notation: |*V*|

2022-06-16 04:09 UTC, edrogers commented on papers/nathan_jacobi_ivan_mo_albert_you/paper.rst
> +Following the generation of temporally aligned word embedding, they can be used for semantic shift analysis.
Syntax error here

2022-06-16 04:09 UTC, edrogers commented on papers/nathan_jacobi_ivan_mo_albert_you/paper.rst
> +Our initial solution involves determining patterns within medical related terms, as those words are semantically linked to a medical emergency such as this outbreak.
Does this mean that, after performing the temporal alignment procedure, the remainder of the work focuses only on the ~8k medical and HIV/AIDS specific terms in the corpora?

2022-06-16 04:09 UTC, edrogers commented on papers/nathan_jacobi_ivan_mo_albert_you/paper.rst
> +Additionally, the two dimensional representation of initial and next positions of each embedding were listed as features.
Why are the two dimensional representations of the positional embeddings included as features? By doing so, you won't be able to use that UMAP representation to visually inspect the performance of your subsequent clustering. (See, for example, from the [UMAP Guide](https://umap-learn.readthedocs.io/en/latest/clustering.html#traditional-clustering): "We can look at the results by coloring out UMAP embedded data by cluster membership.")

2022-06-16 04:09 UTC, edrogers commented on papers/nathan_jacobi_ivan_mo_albert_you/paper.rst
> +The data was then split into 80% training and 20% testing.
Do you actually perform this split? I don't see any analysis in the rest of the paper comparing the training set to the test set, but maybe I'm missing it.

2022-06-16 04:09 UTC, edrogers commented on papers/nathan_jacobi_ivan_mo_albert_you/paper.rst
> +Using these training data, K-means clustering was performed to try to classify each observation.
What are the target classes here? Are you attempting to make binary predictions as to whether a cluster has higher than average incidence rate of medical and HIV/AIDS related terms?

It seems that, given your data, this is a supervised learning problem, and a supervised learning approach would be more suitable to the task. Did you consider using any supervised approaches (eg., logistic regression, MLP, non-linear SVM)? If so, what motivated the choice to use K-means instead?

2022-06-16 04:09 UTC, edrogers commented on papers/nathan_jacobi_ivan_mo_albert_you/paper.rst
> +Several iterations with various parameters were attempted, but all led had converging inertia values of over 20,000.
> but all led had converging

Typo

2022-06-16 04:09 UTC, edrogers commented on papers/nathan_jacobi_ivan_mo_albert_you/paper.rst
> +Therefore features were reassessed, and embedding vectors were created again with dimension d = 10, yielding 14 features per observation.
I like that you've shared your initial struggle with the larger vector space above. However, it feels like this switch to a smaller space is buried under the previous explanation. 

Would you be willing to reword the explanation to include this 14 dimensional space, then follow it with something along the lines of "we additionally made attempts to use a larger vector space with d = 100, however K-means did not exhibit usable converging inertia in that case" or similar?

2022-06-16 04:09 UTC, edrogers commented on papers/nathan_jacobi_ivan_mo_albert_you/paper.rst
> +As the vectors do not lie within the same embedding space, the vectors cannot be directly compared. Instead, we compare shared nearby words between the vectors.
In a previous section, you detailed a sophisticated method of addressing the alignment problem between different temporal embeddings. Now you would like to align temporal embeddings with a static embedding. Could you harness the same approach by starting with a static embedding with a well-chosen value for d?

2022-06-16 04:09 UTC, edrogers commented on papers/nathan_jacobi_ivan_mo_albert_you/paper.rst
> +comparing the closest n = 15 words between the word2vec embeddings and the temporal embeddings.
Is the word2vec embedding here the one constructed from the New York Times corpus described in the last paragraph? It's unclear from the text. Wouldn't the distribution of SCW percent occurrences be highly dependent on the similarity or dissimilarity of the corpora used to create the embeddings?

2022-06-16 04:09 UTC, edrogers commented on papers/nathan_jacobi_ivan_mo_albert_you/paper.rst
> +.. table:: The percentage and counts of our vocabulary sharing a given number of closest words (SCW for short) between word2vec and our model for time bucket #17. :label:`sharedclosest`
1. Should the Percent Occurrences column add to 1? It appears to sum to less than 1.
2. It took me a minute to understand the "S" in "SCW" stood for "shared." Could you reword to have "shared closest words" immediately before "(SCW for short)"?

2022-06-16 04:09 UTC, edrogers commented on papers/nathan_jacobi_ivan_mo_albert_you/paper.rst
> +More examples such as this can be seen in table :ref:`compare`, where the top 5 nearest terms to a few selected terms are listed,
> to a few selected terms

How are those terms selected? This portion of the analysis is already very qualitative and, arguably, quite subjective. Could you explain the methodology for the selection here? If there isn't a rigorous method, you should introduce one. E.g., choose the vectors closest to your K-Means centroids.

2022-06-16 04:09 UTC, edrogers commented on papers/nathan_jacobi_ivan_mo_albert_you/paper.rst
> +A closer view of this outlying cluster, with labels (figure :ref:`zoomedplot0`), show that most terms appear to be hashtags or typos, that likely do not appear often or at all in the first temporal b
This figure (`zoomed_plot0.png`) is illegible. Is there anything that can be done? Some alternate means of representation?

2022-06-16 04:09 UTC, edrogers commented on papers/nathan_jacobi_ivan_mo_albert_you/paper.rst
> +Visual analysis shows an outlying cluster at the bottom of the first embedding space that becomes spread out and more integrated into the embeddings by the final embedding space.
Is this a trend that can be tracked over the course of each time-bucket, or merely just a fluctuation? Even if it is a consistent trend over time, could you be more precise in how it speaks to your hypothesis that the change in embedding over time can be indicative of disease outbreak?

2022-06-16 04:09 UTC, edrogers commented on papers/nathan_jacobi_ivan_mo_albert_you/paper.rst
> +The results of clustering led to semantic shifts of medical related terms and HIV related terms having higher incidences than other terms in 2 clusters each:
Do the higher incidences of these terms in each cluster exceed that which could be explained by random chance? That is, what is the statistical significance of the higher incidence of these terms in those clusters?

2022-06-16 04:09 UTC, edrogers commented on papers/nathan_jacobi_ivan_mo_albert_you/paper.rst
> +clusters 3 and 7 for HIV terms, and clusters 4 and 7 for medical related terms.
Here, you list the HIV term cluster numbers first and the medical term cluster numbers second; but immediately after, the plots and tables are listed in the reverse order. It would be helpful, I think, to be consistent.

2022-06-16 04:09 UTC, edrogers commented on papers/nathan_jacobi_ivan_mo_albert_you/paper.rst
> +This increased incidence rate of HIV and medical related terms in certain clusters leads us to hypothesize that semantic shifts of terms in future datasets can be clustered using the KMeans model,
> KMeans

In some places you hyphenate K-Means, in others you don't. I recommend being consistent.

2022-06-16 04:09 UTC, edrogers commented on papers/nathan_jacobi_ivan_mo_albert_you/paper.rst
> +Our results prove promising, as there was a statistically noticeable difference in clustering of semantic shifts in HIV and medical related terms compared to the full vocabulary.
Definitely remove the word "statistically" here unless you have statistics to argue this claim of "noticeable difference."

2022-06-16 04:09 UTC, edrogers commented on papers/nathan_jacobi_ivan_mo_albert_you/paper.rst
> +.. table:: Distribution of HIV terms and all terms within k-means clusters :label:`hivterm`
> k-means

Here, K-Means is not capitalized as it is elsewhere

2022-06-16 04:09 UTC, edrogers commented on papers/nathan_jacobi_ivan_mo_albert_you/paper.rst
> +However, there were various biases in our data that occurred, such as bots skewing data by repeating a plethora of tweets, misspellings, and hashtags, but initial results show a classifiable differen
> tweets

Elsewhere in this paper, Tweets is capitalized

2022-06-16 04:09 UTC, edrogers commented on papers/nathan_jacobi_ivan_mo_albert_you/mybib.bib
> +    title="HIV infection linked to injection use of oxymorphone in Indiana, 2014–2015",
This and many other entries in the bibliography change the case of the title of a work, sometimes confusingly. (E.g., "Hiv", "scott county, in, usa", etc.) Can you verify that each of these entries is correctly cited?

2022-06-16 04:09 UTC, edrogers commented on papers/nathan_jacobi_ivan_mo_albert_you/paper.rst
> +Additionally, modern hashtag terms will likely be the most common novel terms that we have no priori knowledge on.
> have no priori knowledge on.

Typo

2022-06-16 04:09 UTC, edrogers commented on papers/nathan_jacobi_ivan_mo_albert_you/paper.rst
> +Our data set is a corpus *D* of over 7 million Tweets collected from Scott County, Indiana from the dates January 1st, 2014 until January 17th, 2017.
Have you made this data set available publicly? Also, how did you select Tweets from one county?

2022-06-16 04:09 UTC, edrogers commented on papers/nathan_jacobi_ivan_mo_albert_you/mybib.bib
> + @misc{dva05,
This reference is not cited in the paper.

2022-06-16 04:09 UTC, edrogers commented on papers/nathan_jacobi_ivan_mo_albert_you/paper.rst
> +Additionally, we created a vocabulary of 227 HIV/AIDS specific medical terms to be used in analysis.
Is this vocabulary you created shared anywhere? Also, many medical terms are multi-word, (e.g., "Adverse reaction"). Did you take any steps to tokenize medical or HIV/AIDS terms differently?

2022-06-16 07:47 UTC, vidhi-am requested changes

2022-06-16 07:47 UTC, vidhi-am commented on papers/nathan_jacobi_ivan_mo_albert_you/paper.rst
> +To explore this idea, we generate a temporal word embedding model that allows us to study word semantics evolving over time.
"over time" is redundant.

2022-06-16 07:47 UTC, vidhi-am commented on papers/nathan_jacobi_ivan_mo_albert_you/paper.rst
> +This numerical vector space allows for quantitative analysis of semantics and contextual meanings, allowing for stronger machine learning models that utilize human language.
Not sure what stronger means here. Do you mean more robust?

2022-06-16 07:47 UTC, vidhi-am commented on papers/nathan_jacobi_ivan_mo_albert_you/paper.rst
> +the second being a list of medical terms taken from a published list of terms taken from combining two medical spell check libraries.
Adding a source would be useful.

2022-06-16 23:46 UTC, deniederhut commented
@scoobies mark pending comment

2022-06-17 12:54 UTC, vidhi-am commented
Hi Dillon
I have added some comments yesterday.
Best RegardsVidhi
    On Tuesday, 14 June, 2022, 06:10:43 am IST, Dillon Niederhut ***@***.***> wrote:  
 
 


Hey @vidhi-am and @edrogers! How are the reviews coming along?

—
Reply to this email directly, view it on GitHub, or unsubscribe.
You are receiving this because you were mentioned.Message ID: ***@***.***>

2022-06-19 17:48 UTC, njj67229 commented on papers/nathan_jacobi_ivan_mo_albert_you/paper.rst
> +Additionally, the two dimensional representation of initial and next positions of each embedding were listed as features.
Hi Ed, I'm making a large batch of changes right now, primarily to the methodology. The 2 dimensional UMAP reduction is no longer being used, and instead a 10 dimensional representation of the same vectors generated by our model are being used for initial and final position in the embedding space

2022-06-19 17:48 UTC, njj67229 commented on papers/nathan_jacobi_ivan_mo_albert_you/paper.rst
> +The data was then split into 80% training and 20% testing.
This split was made but was not used before the initial draft submission. We have updated the methodology now to include a neural network for predicting HIV terms, with that 20-80 split, this change will be pushed tonight.

2022-06-19 22:26 UTC, njj67229 commented on papers/nathan_jacobi_ivan_mo_albert_you/mybib.bib
> + @misc{dva05,
It will be added in the next push, currently used in drafts

2022-06-19 22:26 UTC, njj67229 commented on papers/nathan_jacobi_ivan_mo_albert_you/paper.rst
> +Additionally, we created a vocabulary of 227 HIV/AIDS specific medical terms to be used in analysis.
It will be in our repo, linking that to the paper as well

2022-06-24 01:19 UTC, deniederhut commented
Hi @ahy69195 ! Is this paper ready for re-review?

2022-06-24 01:58 UTC, njj67229 commented
Hi @deniederhut, we have been waiting for some final results from some neural nets we have been training, but all changes for re-review should be completed by tomorrow evening or Saturday evening. Sorry for the wait.

2022-06-27 03:25 UTC, deniederhut commented
Thanks for pushing those updates!

2022-06-27 03:26 UTC, deniederhut commented
@scoobies build status

2022-06-27 03:26 UTC, scoobies commented
{"ahy69195-2022"=>{"data"=>{"build_output"=>"[*] Updating proceedings build tools in {self.master_repo_path}...\nAlready up to date.\n[*] Check out paper repository...\nCloning into '/tmp/tmpgoyg50tv'...\nMoving proceedings build tools to temp directory...\n[*] Build the paper...\n<string>:171: (ERROR/3) Undefined substitution referenced: \"V\".\nBuilding: nathan_jacobi_ivan_mo_albert_you\nTraceback (most recent call last):\n  File \"publisher/build_paper.py\", line 237, in <module>\n    build_paper(paper_id)\n  File \"publisher/build_paper.py\", line 222, in build_paper\n    rst2tex(in_path, out_path)\n  File \"publisher/build_paper.py\", line 92, in rst2tex\n    settings_overrides=settings)\n  File \"/procbuild_env/lib/python3.6/site-packages/docutils/core.py\", line 416, in publish_string\n    enable_exit_status=enable_exit_status)\n  File \"/procbuild_env/lib/python3.6/site-packages/docutils/core.py\", line 664, in publish_programmatically\n    output = pub.publish(enable_exit_status=enable_exit_status)\n  File \"/procbuild_env/lib/python3.6/site-packages/docutils/core.py\", line 218, in publish\n    self.apply_transforms()\n  File \"/procbuild_env/lib/python3.6/site-packages/docutils/core.py\", line 199, in apply_transforms\n    self.document.transformer.apply_transforms()\n  File \"/procbuild_env/lib/python3.6/site-packages/docutils/transforms/__init__.py\", line 171, in apply_transforms\n    transform.apply(**kwargs)\n  File \"/procbuild_env/lib/python3.6/site-packages/docutils/transforms/references.py\", line 680, in apply\n    % refname, base_node=ref)\n  File \"/procbuild_env/lib/python3.6/site-packages/docutils/utils/__init__.py\", line 228, in error\n    return self.system_message(self.ERROR_LEVEL, *args, **kwargs)\n  File \"/procbuild_env/lib/python3.6/site-packages/docutils/utils/__init__.py\", line 194, in system_message\n    raise SystemMessage(msg, level)\ndocutils.utils.SystemMessage: <string>:171: (ERROR/3) Undefined substitution referenced: \"V\".\nError building paper /tmp/tmpgoyg50tv/papers/nathan_jacobi_ivan_mo_albert_you. Aborting.\n[X] Error code 1\nA build error occurred during the self.run_make_paper_script step.", "build_pdf_path"=>"", "build_status"=>"Build failed, make_paper.sh did not succeed", "build_timestamp"=>"27/06 03:14"}, "status"=>"fail"}}

2022-06-27 03:27 UTC, deniederhut commented on papers/nathan_jacobi_ivan_mo_albert_you/paper.rst
> +dimensions :math:`V \times V`. Following the generation of each of these co-occurrence matrices, a :math:`|V| \times |V|` dimensioned Positive Pointwise Mutual Information
From the build logs, it looks like this change might be causing a syntax issue in the rst conversion

2022-06-28 03:54 UTC, njj67229 commented on papers/nathan_jacobi_ivan_mo_albert_you/paper.rst
> +dimensions :math:`V \times V`. Following the generation of each of these co-occurrence matrices, a :math:`|V| \times |V|` dimensioned Positive Pointwise Mutual Information
Should be fixed now!

2022-06-28 04:14 UTC, njj67229 commented on papers/nathan_jacobi_ivan_mo_albert_you/paper.rst
> +clusters 3 and 7 for HIV terms, and clusters 4 and 7 for medical related terms.
Med terms have been dropped after expansion of the HIV terms

2022-06-28 04:15 UTC, njj67229 commented on papers/nathan_jacobi_ivan_mo_albert_you/paper.rst
> +Visual analysis shows an outlying cluster at the bottom of the first embedding space that becomes spread out and more integrated into the embeddings by the final embedding space.
After the distance metric for UMAP was changed from Euclidean to cosine similarity this drift/spreading out is not longer present in the representations

2022-06-28 04:28 UTC, njj67229 commented on papers/nathan_jacobi_ivan_mo_albert_you/paper.rst
> +The results of clustering led to semantic shifts of medical related terms and HIV related terms having higher incidences than other terms in 2 clusters each:
Working on a statistical measure for the claim, will be in the next push

2022-06-28 10:23 UTC, deniederhut commented
@ahy69195 awesome! Is this paper ready for re-review?

2022-06-28 10:30 UTC, njj67229 commented
It will be within the next 2 hours @deniederhut! Almost everything is fixed, outside of voicing and adding in the results for the neural networks, I'm writing up those results right now.

2022-06-28 10:39 UTC, deniederhut commented
@scoobies build status

2022-06-28 10:39 UTC, scoobies commented
{"ahy69195-2022"=>{"data"=>{"build_output"=>"[*] Updating proceedings build tools in {self.master_repo_path}...\nAlready up to date.\n[*] Check out paper repository...\nCloning into '/tmp/tmpje673vb8'...\nMoving proceedings build tools to temp directory...\n[*] Build the paper...\n<string>:171: (ERROR/3) Undefined substitution referenced: \"V\".\nBuilding: nathan_jacobi_ivan_mo_albert_you\nTraceback (most recent call last):\n  File \"publisher/build_paper.py\", line 237, in <module>\n    build_paper(paper_id)\n  File \"publisher/build_paper.py\", line 222, in build_paper\n    rst2tex(in_path, out_path)\n  File \"publisher/build_paper.py\", line 92, in rst2tex\n    settings_overrides=settings)\n  File \"/procbuild_env/lib/python3.6/site-packages/docutils/core.py\", line 416, in publish_string\n    enable_exit_status=enable_exit_status)\n  File \"/procbuild_env/lib/python3.6/site-packages/docutils/core.py\", line 664, in publish_programmatically\n    output = pub.publish(enable_exit_status=enable_exit_status)\n  File \"/procbuild_env/lib/python3.6/site-packages/docutils/core.py\", line 218, in publish\n    self.apply_transforms()\n  File \"/procbuild_env/lib/python3.6/site-packages/docutils/core.py\", line 199, in apply_transforms\n    self.document.transformer.apply_transforms()\n  File \"/procbuild_env/lib/python3.6/site-packages/docutils/transforms/__init__.py\", line 171, in apply_transforms\n    transform.apply(**kwargs)\n  File \"/procbuild_env/lib/python3.6/site-packages/docutils/transforms/references.py\", line 680, in apply\n    % refname, base_node=ref)\n  File \"/procbuild_env/lib/python3.6/site-packages/docutils/utils/__init__.py\", line 228, in error\n    return self.system_message(self.ERROR_LEVEL, *args, **kwargs)\n  File \"/procbuild_env/lib/python3.6/site-packages/docutils/utils/__init__.py\", line 194, in system_message\n    raise SystemMessage(msg, level)\ndocutils.utils.SystemMessage: <string>:171: (ERROR/3) Undefined substitution referenced: \"V\".\nError building paper /tmp/tmpje673vb8/papers/nathan_jacobi_ivan_mo_albert_you. Aborting.\n[X] Error code 1\nA build error occurred during the self.run_make_paper_script step.", "build_pdf_path"=>"", "build_status"=>"Build failed, make_paper.sh did not succeed", "build_timestamp"=>"28/06 10:26"}, "status"=>"fail"}}

2022-06-28 10:40 UTC, deniederhut commented
Looks like there are still some build issues?

2022-06-28 10:48 UTC, njj67229 commented
I'll try to resolve those now, sorry for the hold ups

2022-06-28 11:08 UTC, njj67229 commented
@deniederhut I've got to head into work but I'll meet with the other authors ASAP and get everything resolved with the build. Sorry again for the hold ups

2022-06-28 23:15 UTC, deniederhut commented
Looks like things are building again! 🎉

2022-06-29 02:31 UTC, njj67229 commented on papers/nathan_jacobi_ivan_mo_albert_you/paper.rst
> +the second being a list of medical terms taken from a published list of terms taken from combining two medical spell check libraries.
That vocabulary list has been removed

2022-06-29 10:42 UTC, deniederhut commented
Are we ready to have the reviewers take a second look?

2022-06-29 16:23 UTC, njj67229 commented
Hi @deniederhut, all the changes suggested by the reviewers have been implemented I believe, as well as some other changes. 

I have been trying to add in a table containing all the neural network results most of the morning but have been running into build issues doing so, but other than that, all should be ready to go in terms of suggestions. The next push will be the working table or a png of the table generated elsewhere if I can't get it to work. 

Thank you for all the patience through this, all three of us regularly working on this paper are all undergrads and haven't written a paper before, so it's definitely been a learning experience, but you have been very helpful in all of it.

2022-06-29 17:58 UTC, njj67229 commented
Alright @deniederhut, everything should be good now for review! Thank you again!

2022-06-29 23:52 UTC, deniederhut commented
> so it's definitely been a learning experience

Haha our build system is pretty finicky, so it's often a learning experience even for the experts! Sorry for all the syntax issues, and I'm glad I could help.

@vidhi-am and @edrogers, do you feel this paper is now ready to be included in the proceedings?

2022-06-29 23:54 UTC, deniederhut commented
@scoobies check references

2022-06-29 23:54 UTC, scoobies commented
```
Reference check summary (note 'MISSING' DOIs are suggestions that need verification):

OK DOIs

- 10.1056/NEJMoa1515195 is OK
- 10.18060/3911.0038 is OK
- 10.1097/qai.0000000000001098 is OK
- 10.48550/ARXIV.1301.3781 is OK
- 10.1145/3159652.3159703 is OK
- 10.48550/arXiv.1605.09096 is OK
- 10.3115/v1/D14-1162 is OK
- 10.15585/mmwr.mm6916a2 is OK
- 10.18653/v1/W19-1908 is OK
- 10.1162/COLI_a_00237 is OK
- 10.1017/atsip.2019.12 is OK
- 10.1057/s41599-019-0280-3 is OK
- 10.1613/jair.4135 is OK

MISSING DOIs

- None

INVALID DOIs

- 10.1016/s2352-30181830176-0 is INVALID
- 00.48550/ARXIV.1810.04805 is INVALID
```

2022-06-29 23:59 UTC, deniederhut commented
Two more requests from me:

1. Would you mind looking into those DOIs that scoobies things are invalid? I tried searching at doi.org and they didn't come up there either
2. Some of your citations have a DOI, and a URL which is a url-ified version of the DOI -- could you remove the redundant URLs?

2022-06-30 01:09 UTC, njj67229 commented
@scoobies check references

2022-06-30 01:09 UTC, scoobies commented
```
Reference check summary (note 'MISSING' DOIs are suggestions that need verification):

OK DOIs

- 10.1056/NEJMoa1515195 is OK
- 10.18060/3911.0038 is OK
- 10.1097/qai.0000000000001098 is OK
- 10.48550/ARXIV.1301.3781 is OK
- 10.1145/3159652.3159703 is OK
- 10.48550/arXiv.1605.09096 is OK
- 10.3115/v1/D14-1162 is OK
- 10.15585/mmwr.mm6916a2 is OK
- 10.18653/v1/N19-1423 is OK
- 10.18653/v1/W19-1908 is OK
- 10.1162/COLI_a_00237 is OK
- 10.1017/atsip.2019.12 is OK
- 10.1057/s41599-019-0280-3 is OK
- 10.1613/jair.4135 is OK

MISSING DOIs

- None

INVALID DOIs

- 10.1016/S2352-30181830176-0 is INVALID
```

2022-06-30 01:13 UTC, njj67229 commented
@scoobies check references

2022-06-30 01:14 UTC, scoobies commented
```
Reference check summary (note 'MISSING' DOIs are suggestions that need verification):

OK DOIs

- 10.1056/NEJMoa1515195 is OK
- 10.18060/3911.0038 is OK
- 10.1097/qai.0000000000001098 is OK
- 10.48550/ARXIV.1301.3781 is OK
- 10.1145/3159652.3159703 is OK
- 10.48550/arXiv.1605.09096 is OK
- 10.3115/v1/D14-1162 is OK
- 10.15585/mmwr.mm6916a2 is OK
- 10.18653/v1/N19-1423 is OK
- 10.18653/v1/W19-1908 is OK
- 10.1162/COLI_a_00237 is OK
- 10.1017/atsip.2019.12 is OK
- 10.1057/s41599-019-0280-3 is OK
- 10.1613/jair.4135 is OK

MISSING DOIs

- None

INVALID DOIs

- 10.1016/S2352-30181830176-0 is INVALID
```

2022-06-30 01:16 UTC, njj67229 commented
Not really sure what to do about that one, the DOI listed in the BibTeX is "10.1016/S2352-3018(18)30176-0" with parentheses around the 18 there, which is a working one when searched on doi.org

2022-06-30 01:17 UTC, njj67229 commented
@scoobies references

2022-06-30 01:19 UTC, njj67229 commented
@scoobies check references

2022-06-30 01:19 UTC, scoobies commented
```
Reference check summary (note 'MISSING' DOIs are suggestions that need verification):

OK DOIs

- 10.1056/NEJMoa1515195 is OK
- 10.18060/3911.0038 is OK
- 10.1097/qai.0000000000001098 is OK
- 10.48550/ARXIV.1301.3781 is OK
- 10.1145/3159652.3159703 is OK
- 10.48550/arXiv.1605.09096 is OK
- 10.3115/v1/D14-1162 is OK
- 10.15585/mmwr.mm6916a2 is OK
- 10.18653/v1/N19-1423 is OK
- 10.18653/v1/W19-1908 is OK
- 10.1162/COLI_a_00237 is OK
- 10.1017/atsip.2019.12 is OK
- 10.1057/s41599-019-0280-3 is OK
- 10.1613/jair.4135 is OK

MISSING DOIs

- None

INVALID DOIs

- https://doi.org/10.1016/S2352-3018(18)30176-0 is INVALID because of 'https://doi.org/' prefix
```

2022-06-30 01:23 UTC, njj67229 commented
I have used a separate URL for now and removed the line doi="10.1016/S2352-3018(18)30176-0" from sco18
If you have suggestions for resolutions let me know!

2022-06-30 01:23 UTC, njj67229 commented
@scoobies check references

2022-06-30 01:24 UTC, scoobies commented
```
Reference check summary (note 'MISSING' DOIs are suggestions that need verification):

OK DOIs

- 10.1056/NEJMoa1515195 is OK
- 10.18060/3911.0038 is OK
- 10.1097/qai.0000000000001098 is OK
- 10.48550/ARXIV.1301.3781 is OK
- 10.1145/3159652.3159703 is OK
- 10.48550/arXiv.1605.09096 is OK
- 10.3115/v1/D14-1162 is OK
- 10.15585/mmwr.mm6916a2 is OK
- 10.18653/v1/N19-1423 is OK
- 10.18653/v1/W19-1908 is OK
- 10.1162/COLI_a_00237 is OK
- 10.1017/atsip.2019.12 is OK
- 10.1057/s41599-019-0280-3 is OK
- 10.1613/jair.4135 is OK

MISSING DOIs

- 10.1016/s2352-3018(18)30176-0 may be a valid DOI for title: Dynamics of the HIV outbreak and response in Scott County, in, USA, 2011–15: A modelling study

INVALID DOIs

- None
```

2022-06-30 02:13 UTC, deniederhut commented
> the DOI listed in the BibTeX is "10.1016/S2352-3018(18)30176-0" with parentheses around the 18 there

Ahhh sorry for not noticing that. The validator we use seems to have trouble with parentheses -- this came up in a couple of the other papers too

2022-06-30 02:14 UTC, deniederhut commented
Mkay so just to make sure I am reading through the comment history correctly -- we are still waiting on one final table of results?

2022-06-30 02:19 UTC, njj67229 commented
Sorry to not clarify, the table has been added, everything should be good to go for review again

2022-06-30 02:20 UTC, deniederhut commented
Okay awesome! @vidhi-am and @edrogers, let us know what you think!

2022-07-02 03:01 UTC, edrogers requested changes
Thanks for taking on so many of the suggestions and continuing to improve this paper. I'm confident we can include it in the proceedings. Before we sign off on it though, I've noticed some remaining items I'd like to see addressed.

* There are still issues with lower-casing on the titles of many of your citations. There are actually 2 causes to this:
  * At least one of your `mybib.bib` entries has a simple typographical error: "Dynamics of the HIV outbreak and response in Scott County, in, USA." Note the state abbreviation for Indiana is incorrectly lower-cased. 
  * Even when you get your `mybib.bib` perfect, the build tools will incorrectly lower-case the titles in the bibliography by default anyway. This leads to the examples in your paper as it is currently rendered -- "cabell country, west virginia", "hiv or hcv infections", etc. It seems you'll have to use curly braces (as you successfully did with "A BERT-based universal model") to get things to capitalize as needed.
* Reviewing the repo you referenced, it's unclear exactly which words were included in the vocabulary of 15,000 words described in the text. As a result, I have a couple strong suggestions for your [Twitter Embedding Analysis repo](https://github.com/quinngroup/Twitter-Embedding-Analysis/):
  * Could you please add the `global_vocab_rand.csv` file you generated to that repo? It would help clarify which words were included in this analysis.
  * To give others a chance to reproduce your analysis, you should consider using [random.seed](https://docs.python.org/3.8/library/random.html#random.seed) to specify a seed when using random numbers to generate your vocabulary (as you did in [`preprocessing/build_vocab.py`](https://github.com/quinngroup/Twitter-Embedding-Analysis/blob/master/preprocessing/build_vocab.py))

Along with the above suggestions, I've also pointed out some other issues with the publication draft on a line-by-line basis below. Most of them are small, typographical concerns.

Thanks, and let me know if you have any questions about this.

2022-07-02 03:01 UTC, edrogers commented on papers/nathan_jacobi_ivan_mo_albert_you/paper.rst
> +Using the word embedding vectors generated for each temporal bucket, a 2 new data sets were created to use for determining patterns in the semantic shifts surrounding HIV outbreaks.
> a 2 new data sets

Typo

2022-07-02 03:01 UTC, edrogers commented on papers/nathan_jacobi_ivan_mo_albert_you/paper.rst
> +In addition to the change in the 100 dimensioned vector between each time bucket and it's next, the initial and next 10 dimensional embeddings were included from each, which were generated using the
>between each time bucket and it's next

Typo ("its")

2022-07-02 03:01 UTC, edrogers commented on papers/nathan_jacobi_ivan_mo_albert_you/paper.rst
> +In addition to the change in the 100 dimensioned vector between each time bucket and it's next, the initial and next 10 dimensional embeddings were included from each, which were generated using the
> the initial and next 10 dimensional embeddings

From the following sentences, I'm gathering that you included the initial and _final_ 10 dimensional embeddings (as opposed to the initial and "next").

2022-07-02 03:01 UTC, edrogers commented on papers/nathan_jacobi_ivan_mo_albert_you/paper.rst
> +The data set with the change in an embeddings vector, data_121, remained to contain the changes of the vectors, as well as the two dimensional representation of the vector for the initial and next ti
> The data set with the change in an embeddings vector, data_121, remained to contain the changes of the vectors, as well as the two dimensional representation of the vector for the initial and next time bucket generated by UMAP, rather than the 10 dimensional representation.

I'm not able to follow this sentence. Could it be reworded?

2022-07-02 03:01 UTC, edrogers commented on papers/nathan_jacobi_ivan_mo_albert_you/paper.rst
> +Seperate two dimensional UMAP representations were generated for use as a feature and for visual examination.
> Seperate

Typo

2022-07-02 03:01 UTC, edrogers commented on papers/nathan_jacobi_ivan_mo_albert_you/paper.rst
> +Inertia at convergence on clustering for k-means was reduced significantly after features were reassassed, as much as 86%, yielding significantly better results.
> reassassed

Typo

2022-07-02 03:01 UTC, edrogers commented on papers/nathan_jacobi_ivan_mo_albert_you/paper.rst
> +This split of data will be refered to as "mixed" data, as the terms are mixed between the splits. The second split of data split the 15,000 words into 80% training and 20% testing.
> refered

Typo

2022-07-02 03:01 UTC, edrogers commented on papers/nathan_jacobi_ivan_mo_albert_you/paper.rst
> +Pairs containing terms that were not present in the model generated vectors were omitted for that models similarity measurments.
> measurments

Typo

2022-07-02 03:01 UTC, edrogers commented on papers/nathan_jacobi_ivan_mo_albert_you/paper.rst
> +These UMAP represntations use cosine distance as their metric over Euclidian distance, leading to more dense clusters and more accurate represenations of nearby terms witin the embedding space.
> These UMAP **_represntations_** use cosine distance as their metric over Euclidian distance, leading to more dense clusters and more accurate **_represenations_** of nearby terms **_witin_** the embedding space.

Three different typos here

2022-07-02 03:01 UTC, edrogers commented on papers/nathan_jacobi_ivan_mo_albert_you/paper.rst
> +Following the same methodology for assessing the strength of embeddingss as we did for the SimLex-999 set, the Spearman's coefficients from this set yielded much better results than from the SimLex-9
> embeddingss

Typo

2022-07-02 03:01 UTC, edrogers commented on papers/nathan_jacobi_ivan_mo_albert_you/paper.rst
> +Additionally, we would like to resasses our embedding model to try and improve embeddings generated and understanding of the semantic shifts.
> resasses

Typo

2022-07-02 03:01 UTC, edrogers commented on papers/nathan_jacobi_ivan_mo_albert_you/paper.rst
> +This project has been ongoing for several years, and new models, such as the use of bidrectional encoders, as in BERT :cite:`bdt18`, have proven to have high performance. BERT based models have also
> bidrectional

Typo

2022-07-02 03:01 UTC, edrogers commented on papers/nathan_jacobi_ivan_mo_albert_you/paper.rst
> +This project has been ongoing for several years, and new models, such as the use of bidrectional encoders, as in BERT :cite:`bdt18`, have proven to have high performance. BERT based models have also
> clincal

Typo

2022-07-02 03:01 UTC, edrogers commented on papers/nathan_jacobi_ivan_mo_albert_you/paper.rst
> +The goal of these models, in addition was to correctly identifying terms we classified as related to the outbreak, was to discover new terms that shift in similar ways to the HIV terms we labeled.
This last sentence explains the goal of your neural network models. That's a great thing to include! I would recommend promoting it toward the top of this section.

2022-07-02 03:01 UTC, edrogers commented on papers/nathan_jacobi_ivan_mo_albert_you/paper.rst
> +The results of this baseline can be seen in table :ref:`menscores`.
> :ref:\`menscores\`

Was this meant to be in a separate table? As written, this reference is broken

2022-07-02 03:01 UTC, edrogers commented on papers/nathan_jacobi_ivan_mo_albert_you/paper.rst
> +.. table:: Results of the neural network run on the data_201 set. :label:`nn201`
If I'm reading this correctly, you've trained 8 NNs for 200 epochs each. 

If you'd like to demonstrate overfitting for any of these NNs, the best way to show this is with a plot of accuracy vs epoch # for both the train and test data set for each NN. See, for example: 

![1_0lDcZ7E872CDwrWCYkj9EQ](https://user-images.githubusercontent.com/207605/176974344-10824033-a588-461b-a1da-0d0ba681e2b7.jpg) 
Source: [towardsdatascience.com](https://towardsdatascience.com/useful-plots-to-diagnose-your-neural-network-521907fa2f45)

A separate plot for each of these 8 NNs would take too much space for this publication, though.

Alternatively, to best compare the performance of all 8 NNs, you might consider plotting the [ROC curve](https://scikit-learn.org/stable/auto_examples/model_selection/plot_roc.html) for each on a single plot.

2022-07-02 03:01 UTC, edrogers commented on papers/nathan_jacobi_ivan_mo_albert_you/paper.rst
> +Results of the data_201 set can be seen in :ref:`nn201`, and results of the data_121 set can be seen in :ref:`nn121`.
You should specify that these tables show metrics only for the data in the 20% testing split for each data set during training. Conclusions about overfitting are not really possible without looking at the metrics for both the training and testing splits.

2022-07-02 03:01 UTC, edrogers commented on papers/nathan_jacobi_ivan_mo_albert_you/paper.rst
> +The certainty threshold for the unmixed split in both was .01, and .1 for the mixed split in the data_201 results.
Why is the threshold different for the two different data sets?

2022-07-02 03:01 UTC, edrogers commented on papers/nathan_jacobi_ivan_mo_albert_you/paper.rst
> +we could begin examining and generating thresholds of what might be indicative of an outbreak.
> we

Typo. (capitalization)

2022-07-02 03:01 UTC, edrogers commented on papers/nathan_jacobi_ivan_mo_albert_you/paper.rst
> +4527 randomly selected terms with occurrences between 10 and 25 times were added to the vocabulary, bringing it to a total of 15,000 terms.
> 4527

Add a comma separator: 4,527

2022-07-02 03:01 UTC, edrogers commented on papers/nathan_jacobi_ivan_mo_albert_you/paper.rst
> +Common stop words were removed from the tweets using the NLTK Python Package, and each Tweet was then tokenized.
> Tweet

Typo. (capitalization)

2022-07-02 14:41 UTC, vidhi-am commented
@deniederhut My previous feedback was incorporated.

I agree with @edrogers feedback. I do not have additional suggestions. It's good to go once @edrogers feedback is incorporated.

2022-07-03 15:04 UTC, njj67229 commented on papers/nathan_jacobi_ivan_mo_albert_you/paper.rst
> +In addition to the change in the 100 dimensioned vector between each time bucket and it's next, the initial and next 10 dimensional embeddings were included from each, which were generated using the
I'll correct that, it is supposed to convey initial and next

2022-07-03 15:10 UTC, njj67229 commented on papers/nathan_jacobi_ivan_mo_albert_you/paper.rst
> +The data set with the change in an embeddings vector, data_121, remained to contain the changes of the vectors, as well as the two dimensional representation of the vector for the initial and next ti
How does this sound instead?

> The data set with the change in an embeddings vector, data_121, continued to contain the changes of vectors between each time bucket and its next. However, rather than the 10 dimensional position vectors for both time buckets, 2 dimensional positions were used instead, generated by UMAP from the 10 dimensioned vectors.

2022-07-03 15:20 UTC, njj67229 commented on papers/nathan_jacobi_ivan_mo_albert_you/paper.rst
> +Results of the data_201 set can be seen in :ref:`nn201`, and results of the data_121 set can be seen in :ref:`nn121`.
Removed the claim on overfitting, changed it to:
> It can be seen that the mixed term split of data led to a high rate of true positives, however it quickly became much more sensitive to terms outside of our target class on higher epochs, with false positives dropping to lower rates.

2022-07-03 15:22 UTC, njj67229 commented on papers/nathan_jacobi_ivan_mo_albert_you/paper.rst
> +The certainty threshold for the unmixed split in both was .01, and .1 for the mixed split in the data_201 results.
.01 on the mixed data set led to an extremely high percentage of the terms to be classified at HIV related, often upwards of 20000 false negatives. I'll make of note of the reasoning in there

2022-07-03 15:27 UTC, njj67229 commented on papers/nathan_jacobi_ivan_mo_albert_you/paper.rst
> +Common stop words were removed from the tweets using the NLTK Python Package, and each Tweet was then tokenized.
All references to tweet are now lowercase

2022-07-04 04:13 UTC, njj67229 commented
@scoobies check references

2022-07-04 04:13 UTC, scoobies commented
```
Reference check summary (note 'MISSING' DOIs are suggestions that need verification):

OK DOIs

- 10.1056/NEJMoa1515195 is OK
- 10.18060/3911.0038 is OK
- 10.1097/qai.0000000000001098 is OK
- 10.48550/ARXIV.1301.3781 is OK
- 10.1145/3159652.3159703 is OK
- 10.48550/arXiv.1605.09096 is OK
- 10.3115/v1/D14-1162 is OK
- 10.15585/mmwr.mm6916a2 is OK
- 10.18653/v1/N19-1423 is OK
- 10.18653/v1/W19-1908 is OK
- 10.1162/COLI_a_00237 is OK
- 10.1017/atsip.2019.12 is OK
- 10.1057/s41599-019-0280-3 is OK
- 10.1613/jair.4135 is OK

MISSING DOIs

- 10.1016/s2352-3018(18)30176-0 may be a valid DOI for title: Dynamics of the HIV outbreak and response in Scott County, IN, USA, 2011–15: A modelling study

INVALID DOIs

- None
```

2022-07-04 04:14 UTC, njj67229 commented
Alright, I believe that all these suggestions have been addressed in the paper now! Should be all good to go on my end. Thank you for all the suggestions and help through this writing process @vidhi-am and @edrogers, and thank you @deniederhut for all the help as well.

2022-07-04 18:18 UTC, edrogers requested changes
Thanks again for addressing many of the suggestions here. I have a few more notes, some of which are again small typos. (Do you have an editor with spell check available to you?)

One more serious concern I mention below is that your tables include incorrectly computed values. Please make sure to take a close look at this.

2022-07-04 18:18 UTC, edrogers commented on papers/nathan_jacobi_ivan_mo_albert_you/mybib.bib
> +@inproceedings{glv14,
FYI, the GloVe paper is no longer referenced in your paper. If that's intentional, you can drop it from your bib file.

2022-07-04 18:18 UTC, edrogers commented on papers/nathan_jacobi_ivan_mo_albert_you/mybib.bib
> +    author = "Felix Hill, Roi Reichart, Anna Korhonen",
FYI, the algorithm used to render references for your paper is doing something unexpected: it's trying to take author names that are listed as "Last_name, First_name" and unscramble them to "First_name Last_name" while preserving alphabetization by last name of first author. This unexpected behavior is going to run into errors for citations like this one where the authors are not cited last name first.

If you care to address this relatively minor issue, I think the simplest approach is to just give in and rewrite each author field to match the way you did for the original BERT paper:
```
    author = "Devlin, Jacob and Chang, Ming-Wei and Lee, Kenton and Toutanova, Kristina",
```
I.e.:
`"Last_name_1, First_name_or_initial_1 and Last_name_2, First_name_or_initial_2 and Last_name_3, First_name_or_initial_3"`

Whatever algorithm renders the references seems to parse this format correctly, stripping all the extra `and`s as necessary..

2022-07-04 18:18 UTC, edrogers commented on papers/nathan_jacobi_ivan_mo_albert_you/paper.rst
> +A vocabularfy dictionary was then generated for each of the 18 temporal buckets, containing each unique word and a count of its occurrences within its respective bucket.
> vocabularfy

Typo

2022-07-04 18:18 UTC, edrogers commented on papers/nathan_jacobi_ivan_mo_albert_you/paper.rst
> +Generating word embeddings is typically done through 2 primary methods: continuous bag-of-words (CBOW) and skip-gram, however many other various models exist :cite:`vec13`.
Generating word embeddings is no longer typically or primarily done through either of these 2 methods. When you specified `word2vec` embeddings, as you had before this most recent change, you were correct. But this most recent revision is incorrect.

2022-07-04 18:18 UTC, edrogers commented on papers/nathan_jacobi_ivan_mo_albert_you/paper.rst
> +This split of data will be reffered to as "mixed" data, as the terms are mixed between the splits. The second split of data split the 15,000 words into 80% training and 20% testing.
> reffered

Typo

2022-07-04 18:18 UTC, edrogers commented on papers/nathan_jacobi_ivan_mo_albert_you/paper.rst
> +It can be seen that the mixed term split of data led to a high rate of true positives, however it quickly became much more sensitive to terms outside of our target class on higher epochs, with false
When false positives are dropping, the model is not becoming more sensitive. It is becoming more specific. [Wikipedia: Sensitivity and specificity](https://en.wikipedia.org/wiki/Sensitivity_and_specificity).

2022-07-04 18:18 UTC, edrogers commented on papers/nathan_jacobi_ivan_mo_albert_you/paper.rst
> +However, rather than the 10 dimensional position vectors for both time buckets, 2 dimensional positions were used instead, generated by UMAP from the 10 dimensioned vectors.
Thank you for rewording this. I think it's much clearer now. A new question, though -- according to a comment you made in this review:

> Hi Ed, I'm making a large batch of changes right now, primarily to the methodology. The 2 dimensional UMAP reduction is no longer being used, and instead a 10 dimensional representation of the same vectors generated by our model are being used for initial and final position in the embedding space

Source: https://github.com/scipy-conference/scipy_proceedings/pull/701#discussion_r901138529

But this is contradicted by your text here. Just wanted to check that the text of the paper is up-to-date with your actual methodology.

2022-07-04 18:18 UTC, edrogers commented on papers/nathan_jacobi_ivan_mo_albert_you/paper.rst
> +   |   150  |  0.6915  |   0.0535  |  0.422  |  825 | 14602 | 34443 | 1330 |  0.7187  |   0.0451  | 0.3141 |  614 | 13006 | 36039 | 1341 |
Your computations in this table are incorrect and inconsistently computed. (!) How are you generating this table?

Take for example this row (150 Epochs of training on the "data_201" set with k-Means label):
|    |       |
|----|-------|
| TP | 825   |
| FP | 14602 |
| TN | 34443 |
| FN | 1330  |

| Metric    | Correctly Computed Value | Your Computed Value |
|-----------|--------------------------|---------------------|
| Accuracy  | 0.6888                   | 0.6915              |
| Precision | 0.0535                   | 0.0535              |
| Recall    | 0.3828                   | 0.422               |

Note that 2 of your 3 computations are wrong. This isn't the only case of errors of this nature in this table.

Please review the entire table. I'd _strongly_ recommend generating tables like this with code rather than using any by-hand methods.

2022-07-04 18:28 UTC, njj67229 commented on papers/nathan_jacobi_ivan_mo_albert_you/paper.rst
> +However, rather than the 10 dimensional position vectors for both time buckets, 2 dimensional positions were used instead, generated by UMAP from the 10 dimensioned vectors.
Yes, sorry we switched back to the 2 dimensional representations.

2022-07-04 19:01 UTC, njj67229 commented
@scoobies build status

2022-07-04 19:01 UTC, scoobies commented
{"ahy69195-2022"=>{"data"=>{"build_output"=>"[*] Updating proceedings build tools in {self.master_repo_path}...\nAlready up to date.\n[*] Check out paper repository...\nCloning into '/tmp/tmpf6dq3v1r'...\nMoving proceedings build tools to temp directory...\n[*] Build the paper...\nBuilding: nathan_jacobi_ivan_mo_albert_you\n*** Warning: /tmp/tmpf6dq3v1r/publisher/../output/nathan_jacobi_ivan_mo_albert_you/paper_stats.json does not exist.\n", "build_pdf_path"=>"/procbuild/procbuild/../cache/ahy69195-2022.pdf", "build_status"=>"success", "build_timestamp"=>"04/07 04:38"}, "status"=>"success"}}

2022-07-04 19:03 UTC, njj67229 commented
Alright, all changes outside of the table have been implemented, @ahy69195 is correcting that and it should be pushed shortly

2022-07-04 21:39 UTC, edrogers commented
Thank you for acting on our feedback. It's clear that you have done a lot of work here.

@deniederhut, this paper is now ready to be included in the proceedings.

2022-07-05 21:23 UTC, edrogers requested changes
@ahy69195, in your most recent commit, [331493e](https://github.com/scipy-conference/scipy_proceedings/pull/701/commits/331493ef5a25d8542d40c882ef77c8d016facaac), you introduced a number of miscalculations to the tables. With these new errors, the paper is no longer ready for inclusion in the proceedings. Can you revert this commit?

2022-07-05 21:29 UTC, ahy69195 commented
> 

We realized the reason some of the calculations were incorrect was because we accidentally wrote the incorrect 

TP | FP | TN | FN values for a few of the rows. Everything should be correct now as they all add up to 51000, and the values accuracy, precision, and recall calculated reflect the corrected TP, FP, etc.

2022-07-05 21:37 UTC, edrogers commented
The rows do not all add up to 51,000. Your most recent commit only changed your computed values for accuracy, precision, and recall. In that commit, you didn't make any changes to your values for TP, FP, TN, or FN.

2022-07-05 21:40 UTC, ahy69195 commented
Oh thank you, I didn't push the changes for the TP, FP, TN, and FN values, only the calculated values. I am doing that now.

2022-07-05 21:45 UTC, ahy69195 commented
It should be corrected now @edrogers

2022-07-05 22:42 UTC, edrogers requested changes
With these notably different results in your Neural Networks Performance tables, you'll need to rewrite your "Neural Network Results" section. Much of the text from before is no longer accurate. (E.g., "the mixed term split of data led to .... false positives dropping to lower rates.") The motivation for the different certainty thresholds between NNs trained on different datasets also may not make sense now that one of your `data_201` NNs is getting over-run with false positives as well.

2022-07-05 23:38 UTC, njj67229 commented
Hey @edrogers, I'm away from the computer for most of the evening, could I fix that in a few hours and push a little later tonight?

2022-07-06 03:41 UTC, njj67229 commented
Hi @edrogers, sorry for all the changes to the table here, the way the data was stored was a large mess to transpose into the tables in the paper. Additionally we had some communication errors stemming from my end on what certainty thresholds were to be used in the tables. Sorry again, and thank you for all the patience. The discussion regarding the tables should be accurate to the results in the table now. If there is anything else we can do for this please let us know. Thank you, and sorry to submit this change after the deadline, I hope that is ok.

2022-07-06 03:41 UTC, njj67229 commented
I will be by computer all day tomorrow and will be able to quickly respond to any changes requested. Thank you again.

2022-07-06 04:11 UTC, njj67229 commented
@scoobies build status

2022-07-06 04:11 UTC, scoobies commented
{"ahy69195-2022"=>{"data"=>{"build_output"=>"[*] Updating proceedings build tools in {self.master_repo_path}...\nAlready up to date.\n[*] Check out paper repository...\nCloning into '/tmp/tmpfikb42sa'...\nMoving proceedings build tools to temp directory...\n[*] Build the paper...\nBuilding: nathan_jacobi_ivan_mo_albert_you\n*** Warning: /tmp/tmpfikb42sa/publisher/../output/nathan_jacobi_ivan_mo_albert_you/paper_stats.json does not exist.\n", "build_pdf_path"=>"/procbuild/procbuild/../cache/ahy69195-2022.pdf", "build_status"=>"success", "build_timestamp"=>"06/07 02:26"}, "status"=>"success"}}

2022-07-06 04:11 UTC, njj67229 commented
@scoobies check references

2022-07-06 04:12 UTC, scoobies commented
```
Reference check summary (note 'MISSING' DOIs are suggestions that need verification):

OK DOIs

- 10.1056/NEJMoa1515195 is OK
- 10.18060/3911.0038 is OK
- 10.1097/qai.0000000000001098 is OK
- 10.48550/ARXIV.1301.3781 is OK
- 10.1145/3159652.3159703 is OK
- 10.48550/arXiv.1605.09096 is OK
- 10.15585/mmwr.mm6916a2 is OK
- 10.18653/v1/N19-1423 is OK
- 10.18653/v1/W19-1908 is OK
- 10.1162/COLI_a_00237 is OK
- 10.1017/atsip.2019.12 is OK
- 10.1057/s41599-019-0280-3 is OK
- 10.1613/jair.4135 is OK

MISSING DOIs

- 10.1016/s2352-3018(18)30176-0 may be a valid DOI for title: Dynamics of the HIV outbreak and response in Scott County, IN, USA, 2011–15: A modelling study

INVALID DOIs

- None
```

2022-07-06 13:19 UTC, edrogers commented
@njj67229 @ahy69195 Thank you for your responsiveness here. The most recent revision addresses the issues in the tables.

@deniederhut, this paper is once again ready to be included in the proceedings.

2022-07-06 13:23 UTC, deniederhut commented
Thanks @edrogers for being so responsive and for doing such a careful review of the paper!

2022-07-06 13:28 UTC, deniederhut approved these changes
Thanks everyone for your hard work on this paper!

2022-07-06 13:28 UTC, deniederhut commented
@scoobies mark ready

2022-07-06 13:30 UTC, merged