Paper: Asdf update
scipy-conference/scipy_proceedings pull request #704
Opened 2022-05-27 17:44 UTC by perrygreenfield

If you are creating this PR in order to submit a draft of your paper,
see http://procbuild.scipy.org/ for logs generated by the build
process.

See the [project readme](https://github.com/scipy-conference/scipy_proceedings#build-your-paper)
for more information.

*Editor*:  

*Reviewers*:

2022-05-27 17:44 UTC, scoobies commented
Hi!, I'm @scoobies, a friendly bot.

Type ```@scoobies help``` to discover how I can help you.

2022-05-29 20:52 UTC, deniederhut commented
@scoobies mark paper

2022-05-29 20:52 UTC, deniederhut commented
@scoobies build status

2022-05-29 20:52 UTC, scoobies commented
{"perrygreenfield-asdf_update"=>{"data"=>{"build_output"=>"[*] Updating proceedings build tools in {self.master_repo_path}...\nAlready up to date.\n[*] Check out paper repository...\nCloning into '/tmp/tmpy2ge6moj'...\nMoving proceedings build tools to temp directory...\n[*] Build the paper...\nBuilding: 00_greenfield\n*** Warning: /tmp/tmpy2ge6moj/publisher/../output/00_greenfield/paper_stats.json does not exist.\n", "build_pdf_path"=>"/procbuild/procbuild/../cache/perrygreenfield-asdf_update.pdf", "build_status"=>"success", "build_timestamp"=>"27/05 17:45"}, "status"=>"success"}}

2022-05-29 20:52 UTC, deniederhut commented
@scoobies mark needs review

2022-05-29 20:53 UTC, deniederhut commented
@scoobies assign @cbcunc as editor

2022-05-29 20:53 UTC, scoobies commented
Assigned! @cbcunc is now the editor

2022-06-02 00:02 UTC, cbcunc commented
Editor confirms paper builds.

2022-06-02 00:03 UTC, cbcunc commented on papers/00_greenfield/00_greenfield.rst
> +The Advanced Scientific Data Format (ADSF): An Update
Acronym (ASDF) is misspelled (ADSF) in title.

2022-06-02 00:16 UTC, deniederhut commented
@scoobies add @jamilgafur to reviewers

2022-06-02 00:16 UTC, scoobies commented
@jamilgafur added to the reviewers list!

2022-06-02 13:13 UTC, perrygreenfield commented on papers/00_greenfield/00_greenfield.rst
> +The Advanced Scientific Data Format (ADSF): An Update
I think that was corrected in the update made on Monday, but I will check again.

2022-06-03 19:14 UTC, mepa commented
@scoobies add @maruthinh to reviewers

2022-06-03 19:14 UTC, scoobies commented
@maruthinh added to the reviewers list!

2022-06-07 02:53 UTC, deniederhut commented
Hi! We've moved the deadline for first reviews back one week, to June 16th, to give us a little more time to find reviewers for all the papers this year. You can see the updated full timeline at https://github.com/scipy-conference/scipy_proceedings#timeline-for-2022.

2022-06-07 13:08 UTC, perrygreenfield commented
Have I been assigned any to review? I don’t see any signs in my email, but perhaps I missed it.

Thanks, Perry


> On Jun 6, 2022, at 10:53 PM, Dillon Niederhut ***@***.***> wrote:
> 
> 
> Hi! We've moved the deadline for first reviews back one week, to June 16th, to give us a little more time to find reviewers for all the papers this year. You can see the updated full timeline at https://github.com/scipy-conference/scipy_proceedings#timeline-for-2022.
> 
> —
> Reply to this email directly, view it on GitHub, or unsubscribe.
> You are receiving this because you authored the thread.
>

2022-06-08 01:43 UTC, deniederhut commented
Hi @perrygreenfield ! No, we haven't assigned you to review any papers. Would you like us to?

2022-06-13 23:44 UTC, cbcunc commented
@jamilgafur, @maruthinh First review is due June 16.

2022-06-13 23:47 UTC, cbcunc commented on papers/00_greenfield/00_greenfield.rst
> +The Advanced Scientific Data Format (ADSF): An Update
@perrygreenfield I don't see that this was fixed.

2022-06-14 13:22 UTC, perrygreenfield commented on papers/00_greenfield/00_greenfield.rst
> +The Advanced Scientific Data Format (ADSF): An Update
Hmmm, you are right. I just corrected it.

2022-06-14 13:24 UTC, perrygreenfield commented
@deniderhut No, you don't need to assign a review. I was just making sure I hadn't missed any assignments. Thanks.

2022-06-16 17:22 UTC, maruthinh commented
The paper reads well. The authors have carried out an interesting work concerning human dynamics. The authors have built a Python package to generate attributed synthetic populations for understanding human dynamics. This work helps policymakers in planning and creating more livable spaces for humans.

2022-06-16 17:24 UTC, perrygreenfield commented
This looks misdirected to the wrong paper.

> On Jun 16, 2022, at 1:22 PM, Maruthi NH ***@***.***> wrote:
> 
> 
> The paper reads well. The authors have carried out an interesting work concerning human dynamics. The authors have built a Python package to generate attributed synthetic populations for understanding human dynamics. This work helps policymakers in planning and creating more livable spaces for humans.
> 
> —
> Reply to this email directly, view it on GitHub, or unsubscribe.
> You are receiving this because you were mentioned.
>

2022-06-16 17:31 UTC, maruthinh commented
Oh yes. Sorry, I read the last paper that appeared on the list. Just by reading Asdf, I didn't understand it. I shall review the correct paper.

2022-06-16 18:05 UTC, maruthinh commented
In this paper, the authors have reported an update on The Advanced Scientific Data Format (ASDF). This is a relatively new data format developed by Space Telescope Science Institute. Although mostly used by astronomers, this interesting data format can be used by others as well. The paper discusses many changes/improvements made to the ASDF. It also discusses the roadmap for further developments.

2022-06-16 23:07 UTC, deniederhut commented
@scoobies remove @jamilgafur from reviewers

2022-06-16 23:07 UTC, scoobies commented
@jamilgafur removed from the reviewers list!

2022-06-18 03:29 UTC, CodeToLearnScience commented on papers/00_greenfield/00_greenfield.rst
> +We will give an example of amore advanced use case that illustrates some
a more

2022-06-18 03:29 UTC, CodeToLearnScience commented on papers/00_greenfield/00_greenfield.rst
> +|
delete?

2022-06-18 03:29 UTC, CodeToLearnScience commented on papers/00_greenfield/00_greenfield.rst
> +write, the attribute can written into the tree with a null value
now on write should be now on?

delete write?

2022-06-18 15:25 UTC, deniederhut commented
@scoobies mark pending comment

2022-06-20 14:51 UTC, perrygreenfield commented on papers/00_greenfield/00_greenfield.rst
> +|
You mean delete these two sentences but leave in the heading?

2022-06-24 01:21 UTC, deniederhut commented
Hi @perrygreenfield ! Have you had a chance to respond to the reviewers comments?

2022-06-24 14:14 UTC, perrygreenfield commented on papers/00_greenfield/00_greenfield.rst
> +write, the attribute can written into the tree with a null value
If that seems clearer. The intent was that writing out the ASDF object in memory would render None values as a YAML null value, so the original wording was to convey that None was converted to null when written out rather when set as None in the object tree. Do you mean "from now on"?

2022-06-24 14:21 UTC, perrygreenfield commented
I was waiting on a clarification on one of the comments ("delete?") and I just asked for another one (regarding "now on" instead of "now on write")

2022-06-24 20:54 UTC, cbcunc requested changes

2022-06-24 20:54 UTC, cbcunc commented on papers/00_greenfield/00_greenfield.rst
> +.. [Atr03] P. Atreides. *How to catch a sandworm*,
Remove this one. LOL.

2022-06-24 20:56 UTC, cbcunc requested changes

2022-06-24 20:56 UTC, cbcunc commented on papers/00_greenfield/00_greenfield.rst
> +- ASDF Standard: https://asdf-standard.readthedocs.io/en/1.0.2/
Use latest: https://asdf-standard.readthedocs.io/en/latest/

2022-06-27 13:15 UTC, perrygreenfield commented on papers/00_greenfield/00_greenfield.rst
> +.. [Atr03] P. Atreides. *How to catch a sandworm*,
Ah, finally caught :-)

2022-06-27 13:20 UTC, perrygreenfield commented on papers/00_greenfield/00_greenfield.rst
> +write, the attribute can written into the tree with a null value
This is my revised wording: and now when 
written, the attribute appears in the YAML tree with a null value
if the Python value is ``None`` and the schema permits null values.

2022-06-27 13:21 UTC, perrygreenfield commented on papers/00_greenfield/00_greenfield.rst
> +- ASDF Standard: https://asdf-standard.readthedocs.io/en/1.0.2/
Done

2022-06-27 13:22 UTC, perrygreenfield commented on papers/00_greenfield/00_greenfield.rst
> +|
In the absence of any further clarification I removed the two sentences.

2022-06-29 00:42 UTC, deniederhut commented
@maruthinh how do the recent revisions look?

2022-06-29 19:15 UTC, cbcunc commented
Reviewers, please give your final recommendations. The deadline for final review comments is tomorrow.

Authors, please respond to review comments with changes or comments which resolve the conversation. Final acceptance decisions are July 4.

2022-06-29 19:20 UTC, perrygreenfield commented
Note that I just corrected the associated organization for the second author. He is no longer at STScI, but the work was done there.

2022-06-30 17:23 UTC, maruthinh commented
> @maruthinh how do the recent revisions look?

Looks fine. 

> @maruthinh how do the recent revisions look?

Looks fine

2022-06-30 17:24 UTC, maruthinh commented
> @maruthinh how do the recent revisions look?

Looks fine.

2022-07-04 19:38 UTC, deniederhut commented
@cbcunc can we mark this paper as ready?

2022-07-06 11:05 UTC, deniederhut commented
@cbcunc GitHub shows that you are still requesting changes on this paper -- is it ready for publication?

2022-07-06 11:20 UTC, perrygreenfield commented
I think the latest version pushed to the PR is ready. The changes are pretty minor.

2022-07-08 18:49 UTC, cbcunc approved these changes

2022-07-08 18:49 UTC, cbcunc commented
@scoobies mark ready

2022-07-09 00:11 UTC, deniederhut requested changes

2022-07-09 00:11 UTC, deniederhut commented on papers/00_greenfield/00_greenfield.rst
> +.. [Gre15] P. Greenfield, M. Droettboom, E. Bray.
The formatting of the DOI fields is inconsistent between references:

<img width="383" alt="Screen Shot 2022-07-08 at 7 09 54 PM" src="https://user-images.githubusercontent.com/6868396/178083803-d4124da5-a4c0-4c2b-868f-ed9758884280.png">

Would you mind formatting them following the guidelines in https://www.crossref.org/display-guidelines/?

2022-07-09 00:11 UTC, deniederhut commented
@scoobies mark pending comment

2022-07-11 18:51 UTC, perrygreenfield commented on papers/00_greenfield/00_greenfield.rst
> +.. [Gre15] P. Greenfield, M. Droettboom, E. Bray.
I must ask if it is too late now to make these changes since I see it is not listed in the proceedings?

2022-07-11 20:59 UTC, cbcunc commented on papers/00_greenfield/00_greenfield.rst
> +.. [Gre15] P. Greenfield, M. Droettboom, E. Bray.
@perrygreenfield The PR is still open for you to make changes. The posted proceedings are the pre-conference proceedings. It will not be finalized until later this month. Please go ahead and make the requested changes and they will be merged and then published. Thank you for your help.

2022-07-11 23:39 UTC, perrygreenfield commented
OK, I'll take care of it tonight or tomorrow.

2022-07-12 16:29 UTC, perrygreenfield commented on papers/00_greenfield/00_greenfield.rst
> +.. [Gre15] P. Greenfield, M. Droettboom, E. Bray.
I believe I have made the necessary changes, but let me know if these are sufficient.

2022-07-18 03:36 UTC, mpetroff commented on papers/00_greenfield/00_greenfield.rst
> +:institution: Space Telescope Science Insitute
Insitute > Institute

2022-07-18 13:13 UTC, perrygreenfield commented on papers/00_greenfield/00_greenfield.rst
> +:institution: Space Telescope Science Insitute
Fixed.

2022-07-20 11:55 UTC, deniederhut commented
@perrygreenfield thanks for making the formats consistent! This is currently in the rendered PDF

<img width="381" alt="Screen Shot 2022-07-20 at 6 52 19 AM" src="https://user-images.githubusercontent.com/6868396/179975798-3ceece10-7acb-4b43-8d3a-1e95e0464044.png">


I assume not on purpose?

2022-07-20 13:11 UTC, perrygreenfield commented
@deniederhut of course that is on purpose! Well, maybe not. Thanks for catching that. That an extra blank line generates that is a bit surprising. I've corrected that and hope nothing else has crept in.

2022-07-21 17:46 UTC, perrygreenfield commented
Is there any risk that this is not going to meet the deadline?

2022-07-25 23:25 UTC, deniederhut commented
> Is there any risk that this is not going to meet the deadline?

Nope we'll get everything settled in time.

2022-07-25 23:27 UTC, deniederhut approved these changes
> That an extra blank line generates that is a bit surprising

rst is real finicky about whitespace. Thanks for fixing it!

2022-07-25 23:28 UTC, deniederhut commented
@scoobies mark ready

2022-07-25 23:28 UTC, merged