PR for A Novel Pipeline for Cell Instance Segmentation, Tracking and Motility Classification of Toxoplasma Gondii in 3D Space
scipy-conference/scipy_proceedings pull request #707
Opened 2022-05-27 19:42 UTC by salirezav

If you are creating this PR in order to submit a draft of your paper,
see http://procbuild.scipy.org/ for logs generated by the build
process.

See the [project readme](https://github.com/scipy-conference/scipy_proceedings#build-your-paper)
for more information.

*Editor*:  

*Reviewers*:

2022-05-27 19:42 UTC, scoobies commented
Hi!, I'm @scoobies, a friendly bot.

Type ```@scoobies help``` to discover how I can help you.

2022-05-29 20:56 UTC, deniederhut commented
@scoobies mark paper

2022-05-29 20:56 UTC, deniederhut commented
@scoobies build status

2022-05-29 20:56 UTC, scoobies commented
{"salirezav-2022"=>{"data"=>{"build_output"=>"[*] Updating proceedings build tools in {self.master_repo_path}...\nAlready up to date.\n[*] Check out paper repository...\nCloning into '/tmp/tmpop6sk13s'...\nMoving proceedings build tools to temp directory...\n[*] Build the paper...\nBuilding: alireza_vaezi\n*** Warning: /tmp/tmpop6sk13s/publisher/../output/alireza_vaezi/paper_stats.json does not exist.\n", "build_pdf_path"=>"/procbuild/procbuild/../cache/salirezav-2022.pdf", "build_status"=>"success", "build_timestamp"=>"27/05 19:57"}, "status"=>"success"}}

2022-05-29 20:56 UTC, deniederhut commented
@scoobies mark needs review

2022-05-29 20:56 UTC, deniederhut commented
@scoobies assign @mepa as editor

2022-05-29 20:56 UTC, scoobies commented
Assigned! @mepa is now the editor

2022-06-02 11:31 UTC, deniederhut commented
@scoobies add @sharyxx to reviewers

2022-06-02 11:31 UTC, scoobies commented
@sharyxx added to the reviewers list!

2022-06-03 04:45 UTC, mepa commented on papers/alireza_vaezi/paper.rst
> +The rest of this paper is structured as follows: After briefly reviewing the literature in Related Work, we move on to thoroughly describe the details of our work in the Method section. Following tha
Hi @salirezav! I don't see a corresponding Method section below. Are you planning to push that soon?

2022-06-06 13:09 UTC, mepa commented on papers/alireza_vaezi/paper.rst
> +The rest of this paper is structured as follows: After briefly reviewing the literature in Related Work, we move on to thoroughly describe the details of our work in the Method section. Following tha
Hi! Could you please give an update on when the Method and Results sections will be complete? This will help reviewers be able to plan time for reviewing!

2022-06-06 15:00 UTC, salirezav commented
Dear Meghann,

I believe it requires between 10 to 14 days to complete. I apologize for
the delayed reply.

Sincerely,
Seyed Alireza Vaezi

On Mon, Jun 6, 2022, 9:09 AM Meghann Agarwal ***@***.***>
wrote:

> ***@***.**** commented on this pull request.
> ------------------------------
>
> In papers/alireza_vaezi/paper.rst
> <https://github.com/scipy-conference/scipy_proceedings/pull/707#discussion_r890131638>
> :
>
> > +   Toxoplasma, Segmentation, Napari
> +
> +Introduction
> +------------
> +Quantitative cell research often requires the measurement of different cell properties including the size, shape, and motility. This step is facilitated using the segmentation of imaged cells. Using fluorescent markers, computational tools can be used to complete segmentation and identify cell features and positions over time. 2D measurements of cells can be useful, but the more difficult task of deriving 3D information from cell images is vital for metrics such as motility and volumetric qualities. Toxoplasmosis is an infection caused by the intracellular parasite Toxoplasma gondii. T. gondii is one of the most successful parasites and at least one-third of the world's population is infected with the parasite. Although Toxoplasmosis is generally benign in healthy individuals, the infection has fatal implications in fetuses and immunocompromised individuals :cite:`saadatnia2012review` . T. gondii's virulence is directly linked to its lytic cycle which is comprised of invasion, replication, egress, and motility. Studying the motility of T. gondii is crucial in understanding its lytic cycle to develop potential treatments.
> +
> +For this reason, we present a novel pipeline to detect, segment, track, and classify the motility pattern of T. gondii in 3D space. Our pipeline is easy to use for users with limited knowledge in programming, Machine Learning, or Computer Vision technicalities. We also aimed to make it applicable in a broader scope of applications right off the shelf.
> +
> +Most of the state-of-the-art pipelines are restricted to 2D space which is not a true representative of the actual motion of the organism. Many require knowledge and expertise in programming or Machine Learning and Deep Learning models and frameworks, limiting the demographic of users that can use them. All of the pipelines solely include a subset of the aforementioned modules (i.e. detection, segmentation, tracking, and classification). And many of them rely on the user to train their own model hand-tailored for their specific application. This demands high levels of experience and skill in ML/DL and consequently undermines the possibility and feasibility of quickly utilizing an off-the-shelf pipeline and still getting good results.
> +
> +To address these we present our pipeline that segments T. gondii cells in 3D microscopic images, tracks their trajectories, and classifies the motion patterns observed throughout the 3D frames. Our pipeline is comprised of four modules: pre-processing, segmentation, tracking, and classification. We developed our pipeline as a plugin for Napari - an open-source fast and interactive image viewer for Python designed for browsing, annotating, and analyzing large multi-dimensional images. Having our pipeline implemented as a part of Napari not only provides a user-friendly design but also gives more advanced users the possibility to attach and execute their custom code and even interact with the steps of the pipeline if needed. The preprocessing module is equipped with basic and extra filters and functionalities to aid in the preparation of the input data. Our pipeline gives its users the advantage of utilizing the functionalities that PlantSeg, VollSeg, and CellPose provide. These functionalities can be chosen in the pre-processing, detection, and segmentation steps. This brings forth a huge variety of algorithms and pre-build models to select from, making our pipeline a great fit for a greater scope of applications other than Toxoplasma gondii.
> +
> +PlantSeg uses a variant of 3D U-Net, called Residual 3D U-Net, for preprocessing and segmentation of multiple cell types :cite:`plantseg`. PlantSeg performs best among Deep Learning algorithms for 3D Instance Segmentation and is very robust against image noise :cite:`Kar2021.06.09.447748`. The segmentation module also includes the optional use of CellPose :cite:`stringer2021cellpose`. CellPose is a generalized segmentation algorithm trained on a wide range of cell types and is the first step toward increased optionality in our pipeline. The Cell Tracking module consolidates the cell particles across the z-axis to materialize cells in 3D space and estimates centroids for each cell. The tracking module is also responsible for extracting the trajectories of cells based on the movements of centroids throughout consecutive video frames, which is eventually the input of the motion classifier module.
> +
> +
> +The rest of this paper is structured as follows: After briefly reviewing the literature in Related Work, we move on to thoroughly describe the details of our work in the Method section. Following that, the Results section depicts the results of comprehensive tests of our plugin on T. gondii cells.
>
> Hi! Could you please give an update on when the Method and Results
> sections will be complete? This will help reviewers be able to plan time
> for reviewing!
>
> —
> Reply to this email directly, view it on GitHub
> <https://github.com/scipy-conference/scipy_proceedings/pull/707#discussion_r890131638>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/ABJJNX666BYICSOEZV625CDVNX2BHANCNFSM5XFHBTJA>
> .
> You are receiving this because you were mentioned.Message ID:
> ***@***.***>
>

2022-06-07 02:54 UTC, deniederhut commented
Hi! We've moved the deadline for first reviews back one week, to June 16th, to give us a little more time to find reviewers for all the papers this year. You can see the updated full timeline at https://github.com/scipy-conference/scipy_proceedings#timeline-for-2022.

2022-06-11 21:25 UTC, deniederhut commented
Hi @salirezav ! Friendly reminder that the deadline for a completed first draft (including the methods section) was May 27th. If we don't have enough time to review the paper, it may not make it into the proceedings.

2022-06-12 20:11 UTC, salirezav commented
Hello Dillon,

Thank you for the reminder. My team and I are doing our best to finish and
update the methodology section in a few days. We aim to complete it earlier
than 16th so the reviewers have enough time to read it.

Sincerely,
Seyed Alireza Vaezi

On Sat, Jun 11, 2022, 5:25 PM Dillon Niederhut ***@***.***>
wrote:

> Hi @salirezav <https://github.com/salirezav> ! Friendly reminder that the
> deadline for a completed first draft (including the methods section) was
> May 27th. If we don't have enough time to review the paper, it may not make
> it into the proceedings.
>
> —
> Reply to this email directly, view it on GitHub
> <https://github.com/scipy-conference/scipy_proceedings/pull/707#issuecomment-1153000495>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/ABJJNX3UYKUVGLG4RKHUZF3VOT74FANCNFSM5XFHBTJA>
> .
> You are receiving this because you were mentioned.Message ID:
> ***@***.***>
>

2022-06-16 00:17 UTC, deniederhut commented
Hey @salirezav ! Is this paper ready for review?

2022-06-16 02:55 UTC, salirezav commented
Hey @deniederhut !
Yes, everything else is added and the paper is ready for review.
Thank you for your patience and please accept my apologies for the misunderstanding that caused this lateness.

Best,
Alireza

2022-06-16 23:55 UTC, deniederhut commented
Awesome! @sharyxx this paper is now ready for you!

2022-06-24 01:37 UTC, mepa commented
Hi @sharyxx, have you had a chance to start reviewing this paper?

2022-07-06 12:17 UTC, deniederhut commented
@salirezav sorry for the delay here -- we've been reaching out to your reviewer via email but haven't seen a review or a timeline for providing one. If they haven't left a review by the end of the week, one of us (the editors) will step in.

2022-07-08 13:04 UTC, deniederhut commented
@scoobies remove @sharyxx from reviewers

2022-07-08 13:04 UTC, scoobies commented
@sharyxx removed from the reviewers list!

2022-07-08 21:10 UTC, deniederhut commented
@scoobies add @mepa to reviewers

2022-07-08 21:10 UTC, scoobies commented
@mepa added to the reviewers list!

2022-07-10 17:32 UTC, mepa reviewed
Hi @salirezav! Thanks for your contribution, and for your patience in waiting for a review. I've made a first pass of the paper focusing mostly on readability aspects, and will await your reply before making a second one.  I'll try to be quick with the follow-up so we can get through the process in plenty of time for the final publishing of the conference proceedings around July 30th (see the timeline at https://github.com/scipy-conference/scipy_proceedings).

2022-07-10 17:32 UTC, mepa commented on papers/alireza_vaezi/paper.rst
> +   Toxoplasma gondii is the parasitic protozoan that causes disseminated toxoplasmosis, a disease that is estimated to infect around one-third of the world's population. While the disease is commonly
- "which are not a true representative" -> either "which are not true representatives" or "which are not a true representation"? (grammar)
- "segmenting, tracking, and classification of" -> "segmenting, tracking, and classifying"? (to make "segmenting" and "classifying" match)
- "with considerable results" -> it's not clear what this means; perhaps the phrase could be re-written or dropped altogether?

2022-07-10 17:32 UTC, mepa commented on papers/alireza_vaezi/paper.rst
> +Quantitative cell research often requires the measurement of different cell properties including the size, shape, and motility. This step is facilitated using the segmentation of imaged cells. Using
- "including the size, shape, and motility" -> "including size, shape, and motility" (either remove "the" or substitute with "their")
- "the segmentation" -> "segmentation" ("the" not needed here)
- "Using fluorescent markers" -> "With fluorescent markers" (too much usage of "use" in the sentence)
- "Toxoplasmosis is an infection..." -> start a new paragraph here (since a new topic starts)
- "T. gondii is one of the most successful parasites and at least one-third of the world's population is infected with the parasite." -> "T. gondii is one of the most successful parasites, **infecting at least one-third of the world's population**." (more clearly connect "success" to "infecting")
- "...understanding its lytic cycle to develop potential treatments" -> maybe "...understanding its lytic cycle **in order** to develop potential treatments"

2022-07-10 17:32 UTC, mepa commented on papers/alireza_vaezi/paper.rst
> +For this reason, we present a novel pipeline to detect, segment, track, and classify the motility pattern of T. gondii in 3D space. Our pipeline is easy to use for users with limited knowledge in pro
```suggestion
For this reason, we present a novel pipeline to detect, segment, track, and classify the motility pattern of T. gondii in 3D space. Our pipeline is easy to use for studying T. gondii and also can be used in a broader scope of applications right off the shelf. 
```

2022-07-10 17:32 UTC, mepa commented on papers/alireza_vaezi/paper.rst
> +Most of the state-of-the-art pipelines are restricted to 2D space which is not a true representative of the actual motion of the organism. Many require knowledge and expertise in programming or Machi
```suggestion
Most of the state-of-the-art pipelines are restricted to 2D space which is not a true representative of the actual motion of the organism. Many of them require knowledge and expertise in programming, or in machine learning (ML) and deep learning (DL) models and frameworks, thus limiting the demographic of users that can use them. All of them solely include a subset of the aforementioned modules (i.e. detection, segmentation, tracking, and classification). Many pipelines rely on the user to train their own model, hand-tailored for their specific application. This demands high levels of experience and skill in ML/DL and consequently undermines the possibility and feasibility of quickly utilizing an off-the-shelf pipeline and still getting good results.
```

Do you have citation(s) to add to this paragraph so readers know exactly which pipelines you're referring to, or somewhere where they can read about them?

2022-07-10 17:32 UTC, mepa commented on papers/alireza_vaezi/paper.rst
> +To address these we present our pipeline that segments T. gondii cells in 3D microscopic images, tracks their trajectories, and classifies the motion patterns observed throughout the 3D frames. Our p
- Please cite Napari: https://napari.org/#citing-napari
- "PlantSeg, VollSeg, and CellPose" - these are mentioned with no context about what they are or where they come from
- "pre-build" -> pre-built
- There have been three mentions so far of applying this pipeline to a greater/broader/etc. scope of applications, without any mention as to what those applications are. Please consider listing some examples with one of the earlier statements.

2022-07-10 17:32 UTC, mepa commented on papers/alireza_vaezi/paper.rst
> +PlantSeg uses a variant of 3D U-Net, called Residual 3D U-Net, for preprocessing and segmentation of multiple cell types :cite:`plantseg`. PlantSeg performs best among Deep Learning algorithms for 3D
Consider moving this paragraph before the one that references "state-of-the-art pipelines" and adding an introductory sentence about the topic, e.g., commonly used tools in quantitative cell research. Also, are "pipelines" and the referenced Python packages one and the same, or is a pipeline a composition of packages, or something else?

2022-07-10 17:32 UTC, mepa commented on papers/alireza_vaezi/paper.rst
> +The rest of this paper is structured as follows: After briefly reviewing the literature in Related Work, we move on to thoroughly describe the details of our work in the Method section. Following tha
- "thoroughly" seems subjective and superfluous - consider removing it?

2022-07-10 17:32 UTC, mepa commented on papers/alireza_vaezi/paper.rst
> +The recent solutions in generalized and automated segmentation tools are focused on 2D cell images. Segmentation of cellular structures in 2D is important but not representative of realistic environm
- "Z-axis" -> z-axis
- "tracking without that factor is a disservice to the research integrity" - is it possible to quantify this statement? What specific effects do not tracking the third dimension have on "research integrity"? Why is tracking in 2D not a valid approximation?

2022-07-10 17:32 UTC, mepa commented on papers/alireza_vaezi/paper.rst
> +Fazli et al. :cite:`fazli2018unsupervised` studies the motility patterns of T. gondii and provides a computational pipeline for identifying motility phenotypes of T. gondii in an unsupervised, data-d
- "NummPy" -> NumPy
- Please consider citing SciPy scientific stack libraries, if you feel its relevant. See the following:
  - https://numpy.org/citing-numpy/
  - https://scipy.org/citing-scipy/
  - https://scikit-learn.org/stable/about.html#citing-scikit-learn
  - https://matplotlib.org/stable/users/project/citing.html
- "In their last work" -> "In their latest work"

2022-07-10 17:32 UTC, mepa commented on papers/alireza_vaezi/paper.rst
> +While combining open source tools is not a novel architecture, little has been done to integrate 3D cell tracking tools. Fazeli et al. :cite:`fazeli2020automated` motivated by the same interest in pr
- "motivated by the same interest in providing better tools to non-software professionals" - would it be worth including something about this objective in the paragraph above starting with "For this reason"? It seems to be a main objective of the work described in this paper.
- Stardist and TrackMate - add citations?
- ZeroCostDL4Mic - citation?

2022-07-10 17:32 UTC, mepa commented on papers/alireza_vaezi/paper.bib
> +  copyright = {http://creativecommons.org/licenses/by/4.0/},
Please include the DOI 
```
doi = {10.7554/eLife.59187},
url = {https://doi.org/10.7554/eLife.59187},
```

2022-07-10 17:32 UTC, mepa commented on papers/alireza_vaezi/paper.rst
> +Wen et al. :cite:`Wen2021-bn` combines multiple existing new technologies including deep learning and presents 3DeeCellTracker. 3DeeCellTracker segments and tracks cells on 3D time-lapse images. Usin
```suggestion
Wen et al. :cite:`Wen2021-bn` combines multiple existing new technologies including deep learning and presents 3DeeCellTracker. 3DeeCellTracker segments and tracks cells on 3D time-lapse images. Using a small subset of their dataset they train the deep learning architecture 3D U-Net for segmentation. For tracking, a combination of two strategies was used to increase accuracy: local cell region strategies, and spatial pattern strategy. Kapoor et al. :cite:`kapoor2021cell` presents VollSeg that uses deep learning methods to segment, track, and analyze cells in 3D with irregular shape and intensity distribution. It is a Jupyter Notebook-based Python package and also has a UI in Napari. For tracking, a custom tracking code is developed based on Trackmate.
```

2022-07-10 17:32 UTC, mepa commented on papers/alireza_vaezi/paper.rst
> +TSeg is developed as a plugin for Napari - a fast and interactive multi-dimensional image viewer for python that allows volumetric viewing of 3D images [cite napari website]. Plugins enable developer
- "[cite napari website]" - were you planning to add this?

2022-07-10 17:32 UTC, mepa commented on papers/alireza_vaezi/paper.rst
> +To classify the motility pattern of T. gondii in 3D space in an unsupervised fashion we implement and use the method that Fazli et. al. introduced :cite:`fazli2019lightweight`. In that work, they use
Consider breaking up the last sentence in two (it's very long). K-means (should be lower-case "m") and the sentence starting "The reason being" can be re-phrased for clarity. Also, please introduce the abbreviation right after the word it abbreviates, e.g., "autoregressive (AR) model", before using it in later text.

2022-07-10 17:32 UTC, mepa commented on papers/alireza_vaezi/paper.rst
> +Future work on our pipeline will include the expanding of implemented algorithms and completely automated setup scripting. In order to currently run the pipeline, conda must be installed with Plantse
Please re-work this paragraph to be grammatically correct.

2022-07-10 17:32 UTC, mepa commented
@scoobies check references

2022-07-10 17:33 UTC, scoobies commented
```
Reference check summary (note 'MISSING' DOIs are suggestions that need verification):

OK DOIs

- 10.1101/2021.06.09.447748 is OK
- 10.7554/eLife.57613 is OK

MISSING DOIs

- 10.12688/f1000research.27019.1 may be a valid DOI for title: Automated cell tracking using StarDist and TrackMate
- 10.1109/isbi.2018.8363735 may be a valid DOI for title: Unsupervised discovery of toxoplasma gondii motility phenotypes
- 10.1109/dsaa.2019.00056 may be a valid DOI for title: Lightweight and scalable particle tracking and motion clustering of 3D cell trajectories
- 10.25080/majora-1b6fd038-014 may be a valid DOI for title: Cell Tracking in 3D using deep learning segmentations
- 10.1101/2020.02.02.931238 may be a valid DOI for title: Cellpose: a generalist algorithm for cellular segmentation

INVALID DOIs

- None
```

2022-07-10 17:36 UTC, mepa commented
@salirezav , please also add any missing DOIs (see the above output) and check through the references in detail to make sure everything is cited correctly.

2022-07-10 21:51 UTC, deniederhut commented
@scoobies mark pending comment

2022-07-11 02:23 UTC, mepa commented
@scoobies build paper

2022-07-11 02:23 UTC, scoobies commented
building paper...

2022-07-11 02:24 UTC, scoobies commented
{"data"=>{"info"=>"Build for paper salirezav-2022 scheduled.  Note that builds are only executed if the current build attempt is more than 5 minutes old."}, "status"=>"success"}

2022-07-14 03:04 UTC, salirezav commented on papers/alireza_vaezi/paper.rst
> +   Toxoplasma gondii is the parasitic protozoan that causes disseminated toxoplasmosis, a disease that is estimated to infect around one-third of the world's population. While the disease is commonly
Done! Thank you very much for the suggestions.

2022-07-14 04:51 UTC, salirezav commented on papers/alireza_vaezi/paper.rst
> +To classify the motility pattern of T. gondii in 3D space in an unsupervised fashion we implement and use the method that Fazli et. al. introduced :cite:`fazli2019lightweight`. In that work, they use
Done! Much appreciated!

2022-07-14 04:59 UTC, salirezav commented on papers/alireza_vaezi/paper.rst
> +TSeg is developed as a plugin for Napari - a fast and interactive multi-dimensional image viewer for python that allows volumetric viewing of 3D images [cite napari website]. Plugins enable developer
Yes. I replaced them.

2022-07-14 04:59 UTC, salirezav commented on papers/alireza_vaezi/paper.rst
> +Quantitative cell research often requires the measurement of different cell properties including the size, shape, and motility. This step is facilitated using the segmentation of imaged cells. Using
Done!

2022-07-14 16:14 UTC, salirezav commented on papers/alireza_vaezi/paper.rst
> +Fazli et al. :cite:`fazli2018unsupervised` studies the motility patterns of T. gondii and provides a computational pipeline for identifying motility phenotypes of T. gondii in an unsupervised, data-d
Done.

2022-07-15 06:23 UTC, salirezav commented on papers/alireza_vaezi/paper.bib
> +  copyright = {http://creativecommons.org/licenses/by/4.0/},
Done.

2022-07-15 06:26 UTC, salirezav commented on papers/alireza_vaezi/paper.rst
> +The rest of this paper is structured as follows: After briefly reviewing the literature in Related Work, we move on to thoroughly describe the details of our work in the Method section. Following tha
Done.

2022-07-17 16:21 UTC, mepa commented
Hi @salirezav, could you please revert the merge from upstream to your fork (https://github.com/scipy-conference/scipy_proceedings/pull/707/commits/85e64ccf7d6d4549077e669d6c6ed9f3593f3196)? We won't be able to merge this PR in to the proceedings if those upstream changes are in your fork.

2022-07-17 18:40 UTC, mepa commented on papers/alireza_vaezi/paper.rst
> +Future work on our pipeline will include the expanding of implemented algorithms and completely automated setup scripting. In order to currently run the pipeline, conda must be installed with Plantse
```suggestion
Future work on our pipeline will include the expanding of implemented algorithms and completely automated setup scripting. In order to currently run the pipeline, conda must be installed with Plantseg and cellpose environments installed if needed. Ideally, a script should be created to spawn these resources without any additional actions from the end user. Our pipeline aims to be easy-to-use by any microscopy researcher, not just those studying T. gondii. Thus, templates for scripting new segmentation algorithms into the pipeline would make the tool easier to customize. Even segmentation tools that perform suboptimally in comparison to cellpose and Plantseg should be "plug-in" options for research use. Stardust and computationally non-intensive segmentation would create a flexible tool for researchers without access to GPU machines. 
```
Does the above capture the intended meaning of "by any party of microscopy researcher"?

2022-07-17 18:52 UTC, mepa commented
@scoobies check references

2022-07-17 18:53 UTC, scoobies commented
```
Reference check summary (note 'MISSING' DOIs are suggestions that need verification):

OK DOIs

- 10.1016/j.eswa.2014.12.045 is OK
- 10.1002/vis.245 is OK
- 10.1016/j.patcog.2018.02.017 is OK
- 10.1007/978-3-642-20795-2_8 is OK
- 10.1520/SSMS20180033 is OK
- 10.1109/5.156471 is OK
- 10.1007/978-3-540-28640-0_7 is OK
- 10.1016/j.jvlc.2008.01.002 is OK
- 10.1145/1088622.1088639 is OK
- 10.1155/2014/286856 is OK
- 10.1007/BF02626996 is OK
- 10.1109/ICFHR.2016.0068 is OK
- 10.1109/ICCV.1998.710772 is OK
- 10.1109/TMI.2016.2621185 is OK
- 10.1117/12.844207 is OK
- 10.1109/34.41371 is OK
- 10.1016/j.neuroimage.2006.01.015 is OK
- 10.1017/S1431927620018243 is OK
- 10.1109/TMI.2014.2366792 is OK
- 10.1186/s40537-016-0043-6 is OK
- 10.1109/CVPR.2009.5206866 is OK
- 10.1109/CVPR.2015.7298824 is OK
- 10.1109/TPAMI.2018.2846566 is OK
- 10.1186/s42490-019-0003-2 is OK
- 10.1109/MMSP.2018.8547095 is OK
- 10.1109/RusAutoCon49822.2020.9208097 is OK
- 10.31399/asm.cp.istfa2020p0172 is OK
- 10.1007/s11263-009-0275-4 is OK

MISSING DOIs

- 10.31399/asm.cp.istfa2019p0256 may be a valid DOI for title: A Review on Automatic Bill of Material Generation and Visual Inspection on PCBs
- 10.1007/978-3-642-15561-1_31 may be a valid DOI for title: What, Where and How Many? Combining Object Detectors and CRFs
- 10.1109/host49136.2021.9702286 may be a valid DOI for title: A Comparison of Neural Networks for PCB Component Segmentation
- 10.1007/978-3-319-10602-1_48 may be a valid DOI for title: Microsoft coco: Common objects in context

INVALID DOIs

- 10.1016/S0378-47540200031-9 is INVALID
- 10.1016/S0146-664X7280017-0 is INVALID
```

2022-07-17 18:56 UTC, mepa requested changes

2022-07-17 18:56 UTC, mepa commented on papers/alireza_vaezi/paper.bib
> +  organization = {IEEE}
doi={10.1109/BigData.2018.8622403}}

2022-07-17 18:56 UTC, mepa commented on papers/alireza_vaezi/paper.bib
> +  publisher = {Taylor \& Francis}
doi = {10.3109/00365548.2012.693197},

2022-07-20 12:01 UTC, deniederhut commented
Hi @salirezav have you had a chance to look at Meghann and Chris's comments?

2022-07-20 19:51 UTC, salirezav commented
> 

Hi
Yes, I did view and make the necessary changes. But I'm on vacation right now I'll be able to fix the PR ishue hopefully tomorrow night.

2022-07-27 04:50 UTC, mepa commented on papers/alireza_vaezi/paper.bib
> +  organization = {IEEE}
Hey @salirezav, could you please add the DOI to this reference?

2022-07-27 04:51 UTC, mepa commented on papers/alireza_vaezi/paper.bib
> +  publisher = {Taylor \& Francis}
This reference looks like it also needs a DOI.

2022-07-27 06:30 UTC, mepa reviewed
@salirezav , thanks for the changes made thus far! Please have another look at my comments, specifically about DOIs. Once those changes are incorporated I think this is paper is ready for inclusion in the proceedings, @deniederhut.

2022-07-27 06:30 UTC, mepa commented on papers/alireza_vaezi/paper.rst
> +Ireland) cooled to -70oC and driven by NIS Elements software (Nikon Instruments, Melville, NY) as part of related research by Dr. Gary Ward :cite:`10.1371/journal.pone.0085763`. The camera was set to
- :cite:`10.1371/journal.pone.0085763` - this citation should refer to an entry in the references, not a DOI

2022-07-28 23:53 UTC, deniederhut commented
@salirezav friendly warning that we're publishing the finalized version of the proceedings this weekend. Please finish your changes before then.

Also, @mepa has warned me that there are some shenanigans in your git history that might cause disruptions to the other papers. If you don't feel comfortable editing a change history by hand (i.e. with git rebase -e) I can take care of it. That's going to require either me force-pushing to this branch, or closing this PR and opening a new one with a different change history -- so please don't be alarmed if this doesn't get merged. We'll still get your paper into the proceedings!

2022-07-29 20:21 UTC, salirezav commented on papers/alireza_vaezi/paper.bib
> +  organization = {IEEE}
Done. Thanks.

2022-07-29 20:22 UTC, salirezav commented on papers/alireza_vaezi/paper.bib
> +  publisher = {Taylor \& Francis}
Corrected.

2022-07-29 20:23 UTC, salirezav commented
> Hi @salirezav have you had a chance to look at Meghann and Chris's comments?

Hi. Yes. I corrected the paper according to the comments. However, I lost some of my work because of a git problem and I had to re-do some of the corrections. I am finalizing everything now.

2022-07-29 20:24 UTC, salirezav commented
> @salirezav friendly warning that we're publishing the finalized version of the proceedings this weekend. Please finish your changes before then.
> 
> Also, @mepa has warned me that there are some shenanigans in your git history that might cause disruptions to the other papers. If you don't feel comfortable editing a change history by hand (i.e. with git rebase -e) I can take care of it. That's going to require either me force-pushing to this branch, or closing this PR and opening a new one with a different change history -- so please don't be alarmed if this doesn't get merged. We'll still get your paper into the proceedings!

Hi. Thank you for the reminder. I am finalizing everything now.

2022-07-29 23:45 UTC, salirezav commented on papers/alireza_vaezi/paper.rst
> +Ireland) cooled to -70oC and driven by NIS Elements software (Nikon Instruments, Melville, NY) as part of related research by Dr. Gary Ward :cite:`10.1371/journal.pone.0085763`. The camera was set to
> @salirezav friendly warning that we're publishing the finalized version of the proceedings this weekend. Please finish your changes before then.
> 
> Also, @mepa has warned me that there are some shenanigans in your git history that might cause disruptions to the other papers. If you don't feel comfortable editing a change history by hand (i.e. with git rebase -e) I can take care of it. That's going to require either me force-pushing to this branch, or closing this PR and opening a new one with a different change history -- so please don't be alarmed if this doesn't get merged. We'll still get your paper into the proceedings!

Hi. Thank you very much for the reminder. I am finalizing things and changes will be done and submitted before midnight.

I performed `git revert -m` on the problematic merge commits a few days ago, but I don't know if it solved the problem. I am going to do a `git rebase -e` as well. Please let me know if it resolves the issue.

2022-07-30 00:14 UTC, salirezav commented on papers/alireza_vaezi/paper.rst
> +The recent solutions in generalized and automated segmentation tools are focused on 2D cell images. Segmentation of cellular structures in 2D is important but not representative of realistic environm
Sorry about that! My teammate was a bit dramatic in here!

2022-07-30 03:22 UTC, salirezav commented
Hi all.

I appreciate everyone's help and patience. I have made all the changes and the final version of this paper is ready.
Unfortunately it looks like I was unable to fix the merge conflicts. I appreciate it if someone would help me fix it on my end, or please do it on your end and let me know about the next steps.

Thank you!

2022-07-30 17:46 UTC, mepa commented on papers/alireza_vaezi/paper.rst
> +While combining open source tools is not a novel architecture, little has been done to integrate 3D cell tracking tools. Fazeli et al. :cite:`fazeli2020automated` motivated by the same interest in pr
Hey @salirezav, it looks like the paper currently isn't building because there needs to be a space between a citation and the next word. Like this:
```suggestion
While combining open source tools is not a novel architecture, little has been done to integrate 3D cell tracking tools. Fazeli et al. :cite:`fazeli2020automated` motivated by the same interest in providing better tools to non-software professionals created a 2D cell tracking pipeline. This pipeline combines Stardist :cite:`Weigert_2020` and TrackMate :cite:`TINEVEZ201780` for automated cell tracking. This pipeline begins with the user loading cell images and centroid approximations to the ZeroCostDL4Mic :cite:`von2021democratising` platform. ZeroCostDL4Mic is a deep learning training tool for those with no coding expertise. Once the platform is trained and masks for the training set are made for hand-drawn annotations, the training set can be input to Stardist. Stardist performs automated object detection using Euclidean distance to probabilistically determine cell pixels versus background pixels. Lastly, Trackmate uses segmentation images to track labels between timeframes and display analytics. 
```

2022-07-30 17:57 UTC, mepa commented on papers/alireza_vaezi/paper.rst
> +To address these we present TSeg. It segments T. gondii cells in 3D microscopic images, tracks their trajectories, and classifies the motion patterns observed throughout the 3D frames. TSeg is compri
Please add a reference for the following citation in `paper.bib`:
```
:cite:`sofroniew_nicholas_2022_6598542`
```

It doesn't appear in the bibliography, so is getting rendered in the pdf as `[?]`. 

<img width="460" alt="Screen Shot 2022-07-30 at 7 54 19 PM" src="https://user-images.githubusercontent.com/4421561/181935733-9738e10a-8e8c-448b-bd9b-063ec4930ed1.png">

2022-07-30 18:00 UTC, mepa commented on papers/alireza_vaezi/paper.rst
> +Ireland) cooled to -70oC and driven by NIS Elements software (Nikon Instruments, Melville, NY) as part of related research by Dr. Gary Ward :cite:`10.1371/journal.pone.0085763`. The camera was set to
Thanks for fixing the citation. It looks good now!

2022-07-30 18:01 UTC, mepa commented on papers/alireza_vaezi/paper.bib
> +  publisher = {Taylor \& Francis}
Thanks!

2022-07-30 18:13 UTC, mepa approved these changes
This paper needs just a couple more fixes, along with the rebasing that @deniederhut has kindly offered to help with, and then it's good to be merged in with the proceedings. Thanks for all your work on this, @salirezav ! I'll mark it "approved" since I'm traveling and may not be able to check in again before publishing, but please do make those two fixes as soon as you can.

2022-07-30 18:17 UTC, salirezav commented on papers/alireza_vaezi/paper.rst
> +To address these we present TSeg. It segments T. gondii cells in 3D microscopic images, tracks their trajectories, and classifies the motion patterns observed throughout the 3D frames. TSeg is compri
Thanks for noticing. Fixed!

2022-07-30 18:18 UTC, salirezav commented on papers/alireza_vaezi/paper.rst
> +While combining open source tools is not a novel architecture, little has been done to integrate 3D cell tracking tools. Fazeli et al. :cite:`fazeli2020automated` motivated by the same interest in pr
Thanks! Corrected int the last commit.

2022-07-30 18:19 UTC, salirezav commented
> This paper needs just a couple more fixes, along with the rebasing that @deniederhut has kindly offered to help with, and then it's good to be merged in with the proceedings. Thanks for all your work on this, @salirezav ! I'll mark it "approved" since I'm traveling and may not be able to check in again before publishing, but please do make those two fixes as soon as you can.

Hi! I just committed all the required fixes!
Thank you for all your help!

2022-08-01 02:09 UTC, merged