Initial overleaf to .rst conversion
scipy-conference/scipy_proceedings pull request #708
Opened 2022-05-27 19:55 UTC by cmgodwin

If you are creating this PR in order to submit a draft of your paper,
see http://procbuild.scipy.org/ for logs generated by the build
process.

See the [project readme](https://github.com/scipy-conference/scipy_proceedings#build-your-paper)
for more information.

*Editor*:  

*Reviewers*:

2022-05-27 19:55 UTC, scoobies commented
Hi!, I'm @scoobies, a friendly bot.

Type ```@scoobies help``` to discover how I can help you.

2022-05-29 20:57 UTC, deniederhut commented
@scoobies mark paper

2022-05-29 20:57 UTC, deniederhut commented
@scoobies build status

2022-05-29 20:57 UTC, scoobies commented
{"cmgodwin-2022"=>{"data"=>{"build_output"=>"[*] Updating proceedings build tools in {self.master_repo_path}...\nAlready up to date.\n[*] Check out paper repository...\nCloning into '/tmp/tmptjrf14_l'...\nMoving proceedings build tools to temp directory...\n[*] Build the paper...\nBuilding: godwin_zain\n*** Warning: /tmp/tmptjrf14_l/publisher/../output/godwin_zain/paper_stats.json does not exist.\n", "build_pdf_path"=>"/procbuild/procbuild/../cache/cmgodwin-2022.pdf", "build_status"=>"success", "build_timestamp"=>"27/05 20:34"}, "status"=>"success"}}

2022-05-29 20:58 UTC, deniederhut commented
@scoobies mark needs review

2022-05-29 20:58 UTC, deniederhut commented
@scoobies assign @cbcunc as editor

2022-05-29 20:58 UTC, scoobies commented
Assigned! @cbcunc is now the editor

2022-06-02 00:00 UTC, cbcunc commented
Editor confirms paper builds.

2022-06-03 00:20 UTC, deniederhut commented
@scoobies add @hongsups to reviewers

2022-06-03 00:20 UTC, scoobies commented
@hongsups added to the reviewers list!

2022-06-03 15:35 UTC, hongsups commented
@cbcunc Hi Chris! My name is Hongsup Shin and it's my pleasure to review your manuscript. I will finish my first review before the 9th (hopefully sooner), as the committee suggested.

Quick question: it seems like the manuscript (https://github.com/scipy-conference/scipy_proceedings/pull/708/files#diff-02b578aab478a48b13624ba16b3d6c173b429c8205d4eedb7c4e98ed1f71ef07 `paper.rst`) ends at the method section in this version. Are you still in the process of uploading the full manuscript? If that's the case, would it be better for me to start the review once you finish it? Please let me know if I missed anything.

2022-06-03 16:16 UTC, cmgodwin commented
> @cbcunc Hi Chris! My name is Hongsup Shin and it's my pleasure to review your manuscript. I will finish my first review before the 9th (hopefully sooner), as the committee suggested.
> 
> Quick question: it seems like the manuscript (https://github.com/scipy-conference/scipy_proceedings/pull/708/files#diff-02b578aab478a48b13624ba16b3d6c173b429c8205d4eedb7c4e98ed1f71ef07 `paper.rst`) ends at the method section in this version. Are you still in the process of uploading the full manuscript? If that's the case, would it be better for me to start the review once you finish it? Please let me know if I missed anything.

Yes, sorry about that! It is cut short at the Methods section, and I plan to update it over the course of the weekend--there will be Experiments and Discussion sections coming soon. I also still need to add some figures that I reference at points in the document. What is there now is mostly final, so feel free to start on the review, but it would be fine if you'd prefer to wait until I upload the rest. Thanks and sorry again for the delay!

2022-06-03 17:05 UTC, hongsups commented
Sounds good. I will just start the review when everything is ready. FYI, I am traveling next week for a conference so I might not be able to finish everything in time but I will do my best.

2022-06-03 19:16 UTC, mepa commented
@scoobies add @iNeil77 to reviewers

2022-06-03 19:16 UTC, scoobies commented
@iNeil77 added to the reviewers list!

2022-06-07 02:55 UTC, deniederhut commented
Hi! We've moved the deadline for first reviews back one week, to June 16th, to give us a little more time to find reviewers for all the papers this year. You can see the updated full timeline at https://github.com/scipy-conference/scipy_proceedings#timeline-for-2022.

2022-06-11 21:26 UTC, deniederhut commented
Hi @cmgodwin ! Friendly reminder that the deadline to submit a completed first draft was May 27th. If the reviewers don't have enough time to look at your paper, it may not make it into the proceedings.

2022-06-13 06:08 UTC, cmgodwin commented
My apologies again for the delay! If anyone has time left to give it a look, the paper has now been updated with the experiments, discussion, and conclusion.

2022-06-13 23:42 UTC, cbcunc commented
@hongsups, @iNeil77 First review is due June 16.

2022-06-16 19:17 UTC, hongsups reviewed
Hi,

Thanks for the manuscript. I think it's really interesting that you combined the VAE element with the typical supervised-learning-based active learning.

My main critique is that the evidence you provided to reach your conclusions is somewhat weak. I made several comments about it, and so I hope it is addressed in the next revision.

2022-06-16 19:17 UTC, hongsupshin commented on papers/godwin_zain/paper.rst
> +label it. Active learning (AL) responds to this issue by selecting
Can you provide a quick example for this?

2022-06-16 19:17 UTC, hongsupshin commented on papers/godwin_zain/paper.rst
> +which unlabeled data are best to label next. Standard approaches
Citation for AL

2022-06-16 19:17 UTC, hongsupshin commented on papers/godwin_zain/paper.rst
> +into standard AL. We test this on various AL methods using a ResNet
What is the motivation for combining the two techniques? What's the benefit?

2022-06-16 19:17 UTC, hongsupshin commented on papers/godwin_zain/paper.rst
> +variational autoencoder (VAE).
Can you provide a summary of your findings?

2022-06-16 19:17 UTC, hongsupshin commented on papers/godwin_zain/paper.rst
> +for unsupervised representation learning. Our main contributions are
Have you tried other unsupervised representation learning methods other than VAE?

2022-06-16 19:17 UTC, hongsupshin commented on papers/godwin_zain/paper.rst
> +Settles (:cite:`settles2009active`) provides a review of
If you're going to mention all 3 and focus on the last one, maybe it's better to explain why the pool-based method is used as a de facto AL method.

2022-06-16 19:17 UTC, hongsupshin commented on papers/godwin_zain/paper.rst
> +learning (AL). In a typical AL setting, there is a set of labeled
Citation

2022-06-16 19:17 UTC, hongsupshin commented on papers/godwin_zain/paper.rst
> +others (:cite:`wang2016cost,sener2018active,smailagic2018medal,yoo2019learning`).
Can you provide more examples of the "others"?

2022-06-16 19:17 UTC, hongsupshin commented on papers/godwin_zain/paper.rst
> +resulting accuracy graphs. This is utilized in many AL papers to show
What kind of heuristics and how are they different from typical model performance metrics? What's the motivation?

2022-06-16 19:17 UTC, hongsupshin commented on papers/godwin_zain/paper.rst
> +encourage that very similar samples are not successively selected.
This is an interesting point but you may want to to elaborate a little bit such as an example of representativeness measure. Also, apologies for nitpicking but the last part of the sentence sounds a bit confusing: are we trying to avoid similar samples at all or just to avoid selecting them successively?

2022-06-16 19:17 UTC, hongsupshin commented on papers/godwin_zain/paper.rst
> +learning rate 0.001 and momentum 0.9. We train on the MNIST dataset (:cite:`deng2012mnist`),
What's the logic behind this hyperparameter selection?

2022-06-16 19:17 UTC, hongsupshin commented on papers/godwin_zain/paper.rst
> +new points to label. This is implemented by training for 10 epochs
What's the logic behind this strategy (aka train until 100% accuracy)?

2022-06-16 19:17 UTC, hongsupshin commented on papers/godwin_zain/paper.rst
> +optimizer with learning rate 0.001 and weight decay 0.005.
Can you assess the runtime/training time with hardware information?

2022-06-16 19:17 UTC, hongsupshin commented on papers/godwin_zain/paper.rst
> +accuracy measurements. The VAE used for the experiment is trained
What's the model architecture of the VAE?

2022-06-16 19:17 UTC, hongsups commented on papers/godwin_zain/paper.rst
> +learning rate 0.001 and momentum 0.9. We train on the MNIST dataset (:cite:`deng2012mnist`),
Can you justify your choice of using MNIST dataset as a benchmark dataset to validate your hypothesis? Since you mentioned a biomedical imaging example to motivate the readers, I strongly feel that you'd need a benchmark dataset that is more realistic and has an element such as severe class imbalance. Also, it would be much better if you use multiple benchmark datasets to assess how generalizable your results are.

2022-06-16 19:17 UTC, hongsups commented on papers/godwin_zain/paper.rst
> +results, while Figure :ref:`lp` shows the loss prediction results. In both
Both figures need error bars. Also I strongly recommend that the authors note that the values are average in the figures.

2022-06-16 19:17 UTC, hongsups commented on papers/godwin_zain/paper.rst
> +features. As the labeled set grows in size over the course of active
I honestly think this is a bit far fetched argument, especially for the core-set where the performance dropped immediately and was consistently worse most of the times.

It would be also interesting to see how exactly VAE is adding values for increased accuracy (or even for decreased). There are several error analysis techniques where you can investigate the model behavior in greater detail. Your argument was that VAE provides representational features in addition to what the task model might not be able to capture, so it would be nice to have more explanation and interpretations of what those features are.

2022-06-16 19:17 UTC, hongsups commented on papers/godwin_zain/paper.rst
> +the entirety of the active learning process.
Did you run a statistical analysis to verify the difference in accuracy between the non-VAE and VAE models is significant?

2022-06-16 19:17 UTC, hongsups commented on papers/godwin_zain/paper.rst
> +and the predicted loss, resulting in a boost to active learning.
Again, it would be nice to see more investigative work on what these features are.

2022-06-16 19:17 UTC, hongsups commented on papers/godwin_zain/paper.rst
> +vector concatenation, an operation we denote with the symbol
Can you elaborate on VAE training process? What's the threshold for reconstruction error to stop training?

2022-06-16 23:56 UTC, deniederhut commented
Thanks Hongsup!

2022-06-16 23:56 UTC, deniederhut commented
@scoobies mark needs more review

2022-06-19 21:29 UTC, iNeil77 reviewed
Thanks for the submission! The attempt to augment the acquisition function with unsupervised features is an interesting idea. However, since the work reports a negative result, I feel that stronger base lining or even deeper insights into the reasons why it didn't work would have strengthened it. One low-hanging fruit I can think of is showing some low-dimensional plot of the AL acquired points in the VAE Gaussian space.

2022-06-19 21:29 UTC, iNeil77 commented on papers/godwin_zain/paper.rst
> +takes a holistic approach of ranking all available unlabeled points
Might be preferable to use the prevailing technical term of “Acquisition Function” here

2022-06-19 21:29 UTC, iNeil77 commented on papers/godwin_zain/paper.rst
> +Settles (:cite:`settles2009active`) provides a review of
+1

2022-06-19 21:29 UTC, iNeil77 commented on papers/godwin_zain/paper.rst
> +data. This method is now more commonly used in combination with a
I feel this part would be more complete if you could mention the uncertainty (cite a few examples, such as BALD) and diversity (cite CoreSet, etc) separately before mentioning how they may be combined.

2022-06-19 21:29 UTC, iNeil77 commented on papers/godwin_zain/paper.rst
> +additional features will constitute representative and previously
It is not at all clear why a Gaussian prior is the best choice for such unsupervised embeddings. Maybe add a few sentences or cite a few works to justify.

2022-06-19 21:29 UTC, iNeil77 commented on papers/godwin_zain/paper.rst
> +compare the performance of the core-set and loss prediction heuristics
In the CoreSet + VAE setting, I feel there might be stronger baselines to compare against. Since it is using a combination of diversity and task-agnostic embedding as the objective, maybe VAAL (https://arxiv.org/abs/1904.00370) is a good baseline to compare against.

2022-06-19 21:29 UTC, iNeil77 commented on papers/godwin_zain/paper.rst
> +Boosting Task-Based Active Learning with Task-Agnostic Information Using a Variational Autoencoder
Might be useful to change the title to use some word other than Boosting (which has other meanings in model ensembling)

2022-06-19 22:41 UTC, deniederhut commented
Thanks Indraneil!

2022-06-19 22:41 UTC, deniederhut commented
@scoobies mark pending comment

2022-06-24 01:23 UTC, deniederhut commented
@cmgodwin have you had a chance to respond to the reviewers comments?

2022-06-24 20:47 UTC, cbcunc requested changes

2022-06-24 20:47 UTC, cbcunc commented on papers/godwin_zain/references.bib
> +@inproceedings{sener2018active,
All citations need a DOI number.

2022-06-29 19:14 UTC, cbcunc commented
Reviewers, please give your final recommendations. The deadline for final review comments is tomorrow.

Authors, please respond to review comments with changes or comments which resolve the conversation. Final acceptance decisions are July 4.

2022-06-29 19:33 UTC, cmgodwin commented
Thank you to @hongsups  and @iNeil77  for the thorough reviews, I found them to be of great help. My apologies for the slow pace of response -- as an update I am working to implement improvements according to your comments, especially with regard to improved analysis of the VAE spaces, providing more thorough statistical analysis, and experimenting on more relevant datasets.

2022-07-05 12:05 UTC, cmgodwin commented
I have uploaded a significant overhaul of the experiments along with many of the requested changes. I don't think I managed to get them all in, but I hope I hope I did a bit to fix the major concerns. Either way, thank you again to @hongsups and @iNeil77 for your suggestions

2022-07-08 18:35 UTC, cbcunc approved these changes

2022-07-08 18:35 UTC, cbcunc commented
@scoobies mark ready

2022-07-09 00:35 UTC, merged