Paper: RocketPy: Combining Open-Source and Scientific Libraries to Make the Space Sector More Modern and Accessible
scipy-conference/scipy_proceedings pull request #710
Opened 2022-05-27 21:36 UTC by MrGribel

If you are creating this PR in order to submit a draft of your paper,
see http://procbuild.scipy.org/ for logs generated by the build
process.

See the [project readme](https://github.com/scipy-conference/scipy_proceedings#build-your-paper)
for more information.

*Editor*:  

*Reviewers*:

2022-05-27 21:36 UTC, scoobies commented
Hi!, I'm @scoobies, a friendly bot.

Type ```@scoobies help``` to discover how I can help you.

2022-05-28 07:04 UTC, giovaniceotto commented
@scoobies help

2022-05-28 07:04 UTC, scoobies commented
Hello @giovaniceotto, here are the things you can ask me to do:

```

# List all available commands
@scoobies help

# Show our community Code of Conduct and Guidelines
@scoobies code of conduct

# Add to this issue's reviewers list
@scoobies add @username to reviewers

# Remove from this issue's reviewers list
@scoobies remove @username from reviewers

# Assign a user as the editor of this submission
@scoobies assign @username as editor

# Remove the editor assigned to this submission
@scoobies remove editor

# Add a user to this issue's assignees list
@scoobies add assignee: @username

# Remove a user from this issue's assignees list
@scoobies remove assignee: @username

# Builds paper
@scoobies build paper

# Checks build status
@scoobies build status

# Check the references of the paper for missing DOIs
# Optionally, it can be run on a non-default branch 
@scoobies check references
@scoobies check references from custom-branch-name

# Label issue with: paper
@scoobies mark paper

# Label issue with: needs-review. Remove labels: unready, needs-more-review, pending-comment, ready
@scoobies mark needs review

# Label issue with: needs-more-review. Remove labels: unready, needs-review, pending-comment, ready
@scoobies mark needs more review

# Label issue with: pending-comment. Remove labels: unready, needs-review, needs-more-review, ready
@scoobies mark pending comment

# Label issue with: ready. Remove labels: unready, needs-review, needs-more-review, pending-comment
@scoobies mark ready

# Label issue with: unready. Remove labels: needs-review, needs-more-review, pending-comment, ready
@scoobies mark not ready

# Label issue with: does_not_build:server
@scoobies mark server fail

# Remove labels: does_not_build:server
@scoobies mark server success

```

2022-05-28 07:04 UTC, giovaniceotto commented
@scoobies build status

2022-05-28 07:04 UTC, scoobies commented
{"MrGribel-2022"=>{"data"=>{"build_output"=>"[*] Updating proceedings build tools in {self.master_repo_path}...\nAlready up to date.\n[*] Check out paper repository...\nCloning into '/tmp/tmpfmrtc18x'...\nMoving proceedings build tools to temp directory...\n[*] Build the paper...\nBuilding: rocketpy_team\n*** Warning: /tmp/tmpfmrtc18x/publisher/../output/rocketpy_team/paper_stats.json does not exist.\n", "build_pdf_path"=>"/procbuild/procbuild/../cache/MrGribel-2022.pdf", "build_status"=>"success", "build_timestamp"=>"28/05 06:58"}, "status"=>"success"}}

2022-05-28 07:05 UTC, giovaniceotto commented
@scoobies check references

2022-05-28 07:05 UTC, scoobies commented
```
Reference check summary (note 'MISSING' DOIs are suggestions that need verification):

OK DOIs

- 10.1137/0904010 is OK
- 10.3233/978-1-61499-649-1-87 is OK
- 10.5281/zenodo.4279966 is OK
- 10.1016/j.jsse.2018.01.002 is OK
- 10.1038/s41592-019-0686-2 is OK
- 10.1080/01621459.1966.10480892 is OK
- 10.1145/321607.321609 is OK

MISSING DOIs

- 10.1007/springerreference_29038 may be a valid DOI for title: Standard Atmosphere

INVALID DOIs

- 10.1061/ASCEAS.1943-5525.0001331 is INVALID
```

2022-05-29 20:59 UTC, deniederhut commented
@scoobies mark paper

2022-05-29 20:59 UTC, deniederhut commented
@scoobies build status

2022-05-29 20:59 UTC, scoobies commented
{"MrGribel-2022"=>{"data"=>{"build_output"=>"[*] Updating proceedings build tools in {self.master_repo_path}...\nAlready up to date.\n[*] Check out paper repository...\nCloning into '/tmp/tmpfmrtc18x'...\nMoving proceedings build tools to temp directory...\n[*] Build the paper...\nBuilding: rocketpy_team\n*** Warning: /tmp/tmpfmrtc18x/publisher/../output/rocketpy_team/paper_stats.json does not exist.\n", "build_pdf_path"=>"/procbuild/procbuild/../cache/MrGribel-2022.pdf", "build_status"=>"success", "build_timestamp"=>"28/05 06:58"}, "status"=>"success"}}

2022-05-29 21:00 UTC, deniederhut commented
@scoobies mark needs review

2022-05-29 21:00 UTC, deniederhut commented
@scoobies assign @deniederhut as editor

2022-05-29 21:00 UTC, scoobies commented
Assigned! @deniederhut is now the editor

2022-05-31 03:12 UTC, tkoyama010 commented
Hi. I am invited as a reviewer. nice to meet you.

2022-05-31 03:46 UTC, mepa commented
@scoobies add @tkoyama010 to reviewers

2022-05-31 03:46 UTC, scoobies commented
@tkoyama010 added to the reviewers list!

2022-06-02 03:01 UTC, giovaniceotto commented
> ```
> Reference check summary (note 'MISSING' DOIs are suggestions that need verification):
> 
> OK DOIs
> 
> - 10.1137/0904010 is OK
> - 10.3233/978-1-61499-649-1-87 is OK
> - 10.5281/zenodo.4279966 is OK
> - 10.1016/j.jsse.2018.01.002 is OK
> - 10.1038/s41592-019-0686-2 is OK
> - 10.1080/01621459.1966.10480892 is OK
> - 10.1145/321607.321609 is OK
> 
> MISSING DOIs
> 
> - 10.1007/springerreference_29038 may be a valid DOI for title: Standard Atmosphere
> 
> INVALID DOIs
> 
> - 10.1061/ASCEAS.1943-5525.0001331 is INVALID
> ```

I just want to clarify the missing and invalid DOIs reported by Scoobies.

Regarding the missing DOI, it has made a mistake since the suggested DOI does not lead to our referenced bibliography, which in this case is the ISO standard for the Standard Atmosphere, published in 1975. I have confirmed that this publication does not have a DOI.

Now, for the invalid DOI. Scoobies has made a mistake here again, I am not sure why. I would guess it may be a bug, since the original DOI has parentheses and Scoobies seem to not know about that. Here is the original DOI directly from our `.bib` file: `doi={10.1061/(ASCE)AS.1943-5525.0001331}`. This DOI does exist, as shown in the following GIF:

![PR #710 - Correct DOI](https://user-images.githubusercontent.com/572483/171543826-17a509dc-3ca1-4aa2-b1d4-efe44b6045bd.gif)

In summary, I believe all DOIs are ok!

2022-06-03 01:21 UTC, deniederhut commented
> In summary, I believe all DOIs are ok!

Haha you win! This is a pretty simple tool we use to ensure that we're providing proper attribution, but it isn't failsafe! I appreciate you going the extra mile to ensure that your citations are all correct

2022-06-05 08:16 UTC, tkoyama010 requested changes
RocketPy is a great library. The design is sophisticated and very easy to understand. I will definitely use it when I need calculations in this area. I have commented on the points I noticed about the grammar of the text and the naming conventions of the variables in the source code. I would appreciate your review and comments.

2022-06-05 08:16 UTC, tkoyama010 commented on papers/rocketpy_team/paper.rst
> +   However, rocketry is still a very inaccessible field, with a high knowledge entry-level and very specific terms.
```suggestion
   However, rocketry is still a very inaccessible field, with high knowledge of entry-level and concrete terms. 
```

2022-06-05 08:16 UTC, tkoyama010 commented on papers/rocketpy_team/paper.rst
> +In order to better understand the current work, some specific terms regarding the rocketry field are stated below:
```suggestion
To better understand the current work, some specific terms regarding the rocketry field are stated below: 
```

2022-06-05 08:16 UTC, tkoyama010 commented on papers/rocketpy_team/paper.rst
> +- Nozzle: Part of the rocket's engine that accelerate the exhaust gases
```suggestion
- Nozzle: Part of the rocket's engine that accelerates the exhaust gases
```

2022-06-05 08:16 UTC, tkoyama010 commented on papers/rocketpy_team/paper.rst
> +- Nosecone: The forward most section of a rocket, shaped for aerodynamics
```suggestion
- Nosecone: The forward-most section of a rocket, shaped for aerodynamics
```

2022-06-05 08:16 UTC, tkoyama010 commented on papers/rocketpy_team/paper.rst
> +The motion of the rocket is restricted to one dimension, which means that only the translation along the rail needs
```suggestion
The motion of the rocket is restricted to one dimension, which means that only the translation along with the rail needs 
```

2022-06-05 08:16 UTC, tkoyama010 commented on papers/rocketpy_team/paper.rst
> +or more parts joined by ropes. This phase ends in the point of impact.
```suggestion
or more parts joined by ropes. This phase ends at the point of impact.
```

2022-06-05 08:16 UTC, tkoyama010 commented on papers/rocketpy_team/paper.rst
> +Four main classes that organize the dataflow during the simulations: motor, rocket, environment, and flight
```suggestion
Four main classes organize the dataflow during the simulations: motor, rocket, environment, and flight
```

2022-06-05 08:16 UTC, tkoyama010 commented on papers/rocketpy_team/paper.rst
> +This first class acts as an input to the Rocket class where the user is also asked to define certain parameters of
```suggestion
This first-class acts as an input to the Rocket class where the user is also asked to define certain parameters of 
```

2022-06-05 08:16 UTC, tkoyama010 commented on papers/rocketpy_team/paper.rst
> +presented in multiple ways depending on the given arguments. If no argument is given, a matplotlib figure opens and a
```suggestion
presented in multiple ways depending on the given arguments. If no argument is given, a Matplotlib figure opens and the
```

2022-06-05 08:16 UTC, tkoyama010 commented on papers/rocketpy_team/paper.rst
> +definition of the rocket and its flight are presented, providing for more concise code.If an n-sized array is passed
```suggestion
definition of the rocket and its flight is presented, providing for more concise code. If an n-sized array is passed
```

2022-06-05 08:16 UTC, tkoyama010 commented on papers/rocketpy_team/paper.rst
> +It receives as inputs launch point coordinates, as well as the length of the launch rail, and then provide
```suggestion
It receives as inputs launch point coordinates, as well as the length of the launch rail, and then provides
```

2022-06-05 08:16 UTC, tkoyama010 commented on papers/rocketpy_team/paper.rst
> +RocketPy requires `datetime` library information specifying year, month,
```suggestion
RocketPy requires `datetime` library information specifying the year, month, 
```

2022-06-05 08:16 UTC, tkoyama010 commented on papers/rocketpy_team/paper.rst
> +the `datetime` object is given in standard UTC time, just as following:
```suggestion
the `datetime` object is given in standard UTC time, just as follows:
```

2022-06-05 08:16 UTC, tkoyama010 commented on papers/rocketpy_team/paper.rst
> +meteorological agencies public datasets, such as Wyoming Upper Air Soundings and European Centre for Medium-Range Weather Forecasts (ECMWF);
```suggestion
meteorological agencys' public datasets, such as Wyoming Upper-Air Soundings and European Centre for Medium-Range Weather Forecasts (ECMWF); 
```

2022-06-05 08:16 UTC, tkoyama010 commented on papers/rocketpy_team/paper.rst
> +or to set a customized atmospheric model based on user defined functions.
```suggestion
or to set a customized atmospheric model based on user-defined functions. 
```

2022-06-05 08:16 UTC, tkoyama010 commented on papers/rocketpy_team/paper.rst
> +As RocketPy supports integration with different meteorological agencies datasets, it allows for a
```suggestion
As RocketPy supports integration with different meteorological agencies' datasets, it allows for a 
```

2022-06-05 08:16 UTC, tkoyama010 commented on papers/rocketpy_team/paper.rst
> +a forecast with quarter degree equally spaced longitude/latitude grid with a temporal resolution of three hours.
```suggestion
a forecast with a quarter degree equally spaced longitude/latitude grid with a temporal resolution of three hours. 
```

2022-06-05 08:16 UTC, tkoyama010 commented on papers/rocketpy_team/paper.rst
> +It parses by using netCDF4 data management system, allowing for the retrieval of
```suggestion
It parses by using the netCDF4 data management system, allowing for the retrieval of 
```

2022-06-05 08:16 UTC, tkoyama010 commented on papers/rocketpy_team/paper.rst
> +Finally, plots of the evaluated parameters with respect to the altitude are all passed on to the mission
```suggestion
Finally, plots of the evaluated parameters concerning the altitude are all passed on to the mission 
```

2022-06-05 08:16 UTC, tkoyama010 commented on papers/rocketpy_team/paper.rst
> +internal ballistics simulators, such as OpenMotor :cite:`openMotor`, which can predict the produced thrust
```suggestion
internal ballistics simulators, such as OpenMotor :cite:`openMotor`, can predict the produced thrust 
```

2022-06-05 08:16 UTC, tkoyama010 commented on papers/rocketpy_team/paper.rst
> +physical attributes, such as mass and moments of inertia, the rocket object will be responsible to storage and
```suggestion
physical attributes, such as mass and moments of inertia, the rocket object will be responsible for storage and 
```

2022-06-05 08:16 UTC, tkoyama010 commented on papers/rocketpy_team/paper.rst
> +      elevation=1400)
If there are no problems with your policy, it is better to follow the variable naming conventions of [PEP8](https://github.com/python/peps/blob/9c23bd6804059006c67f4c703d8fcc3859f0875f/pep-0008.txt#L928-L938).
```suggestion
   env = Environment(
      railLength=5.2,
      latitude=32.990254,
      longitude=-106.974998,
      elevation=1400) 
```

2022-06-05 08:16 UTC, tkoyama010 commented on papers/rocketpy_team/paper.rst
> +   Env.info()
```suggestion
   env.setAtmosphericModel(
      type='Forecast', 
      file='GFS')
   env.info()
```

2022-06-05 08:16 UTC, tkoyama010 commented on papers/rocketpy_team/paper.rst
> +      interpolationMethod='linear')
```suggestion
   motor_name = SolidMotor(
      thrustSource='Motor_file.eng',
      burnOut=2,
      reshapeThrustCurve= False,
      grainNumber=5,
      grainSeparation=3/1000,
      grainOuterRadius=33/1000,
      grainInitialInnerRadius=15/1000,
      grainInitialHeight=120/1000,
      grainDensity= 1782.51,
      nozzleRadius=49.5/2000,
      throatRadius=21.5/2000,
      interpolationMethod='linear')
```

2022-06-05 08:16 UTC, tkoyama010 commented on papers/rocketpy_team/paper.rst
> +   )
```suggestion
   rocket_name = Rocket(
      motor=motor_name,
      radius=127 / 2000,
      mass=19.197 - 2.956,
      inertiaI=6.60,
      inertiaZ=0.0351,
      distanceRocketNozzle=-1.255,
      distanceRocketPropellant=-0.85704,
      powerOffDrag="data/rocket/powerOffDragCurve.csv",
      powerOnDrag="data/rocket/powerOnDragCurve.csv",
   )
```

2022-06-05 08:16 UTC, tkoyama010 commented on papers/rocketpy_team/paper.rst
> +of the rocket such as radius, mass, and moment of inertia in two different axis.
```suggestion
of the rocket such as radius, mass, and moment of inertia on two different axes.
```

2022-06-05 08:16 UTC, tkoyama010 commented on papers/rocketpy_team/paper.rst
> +.. Thus, all parts of the rocket must be defined considering its distance to the rockets CM
This is a comment out though.
```suggestion
.. Thus, all parts of the rocket must be defined considering their distance to the rockets CM
```

2022-06-05 08:16 UTC, tkoyama010 commented on papers/rocketpy_team/paper.rst
> +   )
```suggestion
   nosecone = RocketName.addNose(
      length=0.55829, kind="vonKarman", 
      distanceToCM=0.71971
   )
   fin_set = RocketName.addFins(
      4, span=0.100, rootChord=0.120, tipChord=0.040, 
      distanceToCM=-1.04956
   )
   tail = RocketName.addTail(
      topRadius=0.0635, bottomRadius=0.0435, length=0.060, 
      distanceToCM=-1.194656
   )
```

2022-06-05 08:16 UTC, tkoyama010 commented on papers/rocketpy_team/paper.rst
> +each of  these methods, the static margin is reevaluated.
```suggestion
each of these methods, the static margin is reevaluated.
```

2022-06-05 08:16 UTC, tkoyama010 commented on papers/rocketpy_team/paper.rst
> +Further on, these coefficients are used to calculate the center of pressure and subsequently the static margin. Inside
```suggestion
Further on, these coefficients are used to calculate the center of pressure and subsequently the static margin. In 
```

2022-06-05 08:16 UTC, tkoyama010 commented on papers/rocketpy_team/paper.rst
> +the electronics involved in the activation of the parachute are required. Most interesting of them is the *trigger* and
```suggestion
the electronics involved in the activation of the parachute are required. The most interesting of them is the *trigger* and
```

2022-06-05 08:16 UTC, tkoyama010 commented on papers/rocketpy_team/paper.rst
> +    return True if vel_z < 0 and height < 800 else False
```suggestion
   def parachuteTrigger(p, y):
       return True if vel_z < 0 and height < 800 else False
```

2022-06-05 08:16 UTC, tkoyama010 commented on papers/rocketpy_team/paper.rst
> +   ParachuteName = RocketName.addParachute(
```suggestion
   parachute_name = RocketName.addParachute(
```

2022-06-05 08:16 UTC, tkoyama010 commented on papers/rocketpy_team/paper.rst
> +   TestFlight = Flight(
```suggestion
   test_flight = Flight(
```

2022-06-05 08:16 UTC, tkoyama010 commented on papers/rocketpy_team/paper.rst
> +      environment=Env,
```suggestion
      rocket=rocket,
      environment=env,
```

2022-06-05 08:16 UTC, tkoyama010 commented on papers/rocketpy_team/paper.rst
> +nonstiff Adams method and the stiff BDF method, depending on the detected stiffness, perfectly handling both cases.
```suggestion
nonstiff Adams method and the stiff BDF method, depending on the detected stiffness, perfectly handle both cases.
```

2022-06-05 08:16 UTC, tkoyama010 commented on papers/rocketpy_team/paper.rst
> +discrete controllers, they may change some parameters in the rocket once they are called. On the other hand, parachute
```suggestion
discrete controllers, they may change some parameters in the rocket once they are called. On the other hand, a parachute
```

2022-06-05 08:16 UTC, tkoyama010 commented on papers/rocketpy_team/paper.rst
> +does not need to stop at. This allows the integration algorithm to use more optimized timesteps and significantly
```suggestion
does not need to stop. This allows the integration algorithm to use more optimized timesteps and significantly
```

2022-06-05 08:16 UTC, tkoyama010 commented on papers/rocketpy_team/paper.rst
> +==================================================
```suggestion
The adaptability of the Code and Accessibility
==============================================
```

2022-06-05 08:16 UTC, tkoyama010 commented on papers/rocketpy_team/paper.rst
> +RocketPy's development started in 2017, and since the beginning, certain requirements were kept on mind:
```suggestion
RocketPy's development started in 2017, and since the beginning, certain requirements were kept in mind:  
```

2022-06-05 08:16 UTC, tkoyama010 commented on papers/rocketpy_team/paper.rst
> +- Finally, the software should aim to be **accessible**. The source code was openly published on GitHub (https://github.com/Projeto-Jupiter/RocketPy), where the community started to be built and a gr
```suggestion
- Finally, the software should aim to be **accessible**. The source code was openly published on GitHub (https://github.com/Projeto-Jupiter/RocketPy), where the community started to be built and a group of developers, known as the RocketPy Team, are currently assigned as dedicated maintainers.
```

2022-06-05 08:16 UTC, tkoyama010 commented on papers/rocketpy_team/paper.rst
> +  computing enthusiasts alike; thus facilitating the access to high-quality simulation without a great level of specialization.
```suggestion
  computing enthusiasts alike; thus facilitating access to the high-quality simulation without a great level of specialization. 
```

2022-06-05 08:16 UTC, tkoyama010 commented on papers/rocketpy_team/paper.rst
> +1.  Apogee by Mass using Function helper class
```suggestion
1.  Apogee by Mass using a Function helper class
```

2022-06-05 08:16 UTC, tkoyama010 commented on papers/rocketpy_team/paper.rst
> +      wind_v=-5)
```suggestion
      env = Environment(....)

      env.setAtmosphericModel(type="CustomAtmosphere", 
      wind_v=-5)
```

2022-06-05 08:16 UTC, tkoyama010 commented on papers/rocketpy_team/paper.rst
> +         ......)
```suggestion
      motor_name = SolidMotor(.....)

      # Prepare Rocket
      rocket_name = Rocket(.....
         mass=mass,
         ......)
```

2022-06-05 08:16 UTC, tkoyama010 commented on papers/rocketpy_team/paper.rst
> +      Tail = RocketName.addTail(....)
```suggestion
      rocket_name.setRailButtons([0.2, -0.5])
      nose = RocketName.addNose(.....)
      fin_set = RocketName.addFins(....)
      tail = RocketName.addTail(....)
```

2022-06-05 08:16 UTC, tkoyama010 commented on papers/rocketpy_team/paper.rst
> +      TestFlight = Flight(.....)
```suggestion
      test_flight = Flight(.....)
```

2022-06-05 08:16 UTC, tkoyama010 commented on papers/rocketpy_team/paper.rst
> +      return TestFlight.apogee
```suggestion
      return test_flight.apogee
```

2022-06-05 08:16 UTC, tkoyama010 commented on papers/rocketpy_team/paper.rst
> +   apogeebymass.plot(8, 20, 20)
```suggestion
   apogee_by_mass = Function(apogee, inputs="Mass (kg)", 
   outputs="Estimated Apogee (m)")
   apogee_by_mass.plot(8, 20, 20)
```

2022-06-05 08:16 UTC, tkoyama010 commented on papers/rocketpy_team/paper.rst
> +We can assume the objects stated on [motor] and [rocket] sections and just add couple of variations on some input data
```suggestion
We can assume the objects stated in [motor] and [rocket] sections and just add a couple of variations on some input data 
```

2022-06-05 08:16 UTC, tkoyama010 commented on papers/rocketpy_team/paper.rst
> +      ExRocket.aerodynamicSurfaces.remove(FinSet)
```suggestion
      ex_rocket.aerodynamicSurfaces.remove(fin_set)
```

2022-06-05 08:16 UTC, tkoyama010 commented on papers/rocketpy_team/paper.rst
> +      FinSet = ExRocket.addFins(
```suggestion
      fin_set = ex_rocket.addFins(
```

2022-06-05 08:16 UTC, tkoyama010 commented on papers/rocketpy_team/paper.rst
> +      ExFlight = Flight(
```suggestion
      ex_flight = Flight(
```

2022-06-05 08:16 UTC, tkoyama010 commented on papers/rocketpy_team/paper.rst
> +         rocket=ExRocket,
```suggestion
         rocket=ex_rocket,
```

2022-06-05 08:16 UTC, tkoyama010 commented on papers/rocketpy_team/paper.rst
> +         environment=Env,
```suggestion
         environment=env,
```

2022-06-05 08:16 UTC, tkoyama010 commented on papers/rocketpy_team/paper.rst
> +      ExFlight.postProcess()
```suggestion
      ex_flight.postProcess()
```

2022-06-05 08:16 UTC, tkoyama010 commented on papers/rocketpy_team/paper.rst
> +         ExRocket.staticMargin(ExFlight.tFinal)
```suggestion
         ex_flight.attitudeAngle,
         ex_rocket.staticMargin(0),
         ex_rocket.staticMargin(ExFlight.outOfRailTime),
         ex_rocket.staticMargin(ExFlight.tFinal)
```

2022-06-05 08:16 UTC, tkoyama010 commented on papers/rocketpy_team/paper.rst
> +   Function.comparePlots(
Could you explain how can we import `Function` ?

2022-06-05 08:16 UTC, tkoyama010 commented on papers/rocketpy_team/paper.rst
> +respective standard deviation - are stored in a dictionary. The randomized set of inputs is then generated using
```suggestion
respective standard deviations - are stored in a dictionary. The randomized set of inputs is then generated using
```

2022-06-05 08:16 UTC, tkoyama010 commented on papers/rocketpy_team/paper.rst
> +      Tail = ExRocket.addTail(.....)
```suggestion
      # Prepare Environment
      env = Environment(.....)
      # Prepare Motor
      ex_motor = SolidMotor(.....)
      # Prepare Rocket
      ex_rocket = Rocket(.....)
      nose = ex_rocket.addNose(.....)
      fin_set = ex_rocket.addFins(....)
      tail = ex_rocket.addTail(.....)
```

2022-06-05 08:16 UTC, tkoyama010 commented on papers/rocketpy_team/paper.rst
> +        ExFlight = Flight(.....)
```suggestion
        ex_flight = Flight(.....)
```

2022-06-05 08:16 UTC, tkoyama010 commented on papers/rocketpy_team/paper.rst
> +        export_flight_data(s, ExFlight)
```suggestion
        export_flight_data(s, ex_flight)
```

2022-06-05 08:16 UTC, tkoyama010 commented on papers/rocketpy_team/paper.rst
> +Finally, it is also worth mentioning that all the information generated in the Monte Carlo simulation based on
```suggestion
Finally, it is also worth mentioning that all the information generated in the Monte Carlo simulation is based on
```

2022-06-05 08:16 UTC, tkoyama010 commented on papers/rocketpy_team/paper.rst
> +velocity are very hard to obtain or simply not available. Therefore, in order to make RocketPy more robust and easier to
```suggestion
velocity is very hard to obtain or simply not available. Therefore, in order to make RocketPy more robust and easier to
```

2022-06-05 08:16 UTC, tkoyama010 commented on papers/rocketpy_team/paper.rst
> +can occur due to convoluted nature of such expressions. Hence, to reduce the probability of such errors, there is a
```suggestion
can occur due to the convoluted nature of such expressions. Hence, to reduce the probability of such errors, there is a
```

2022-06-05 08:16 UTC, tkoyama010 commented on papers/rocketpy_team/paper.rst
> +which is an non-dimensional value and the result from both calculations should be the same:
```suggestion
which is a non-dimensional value and the result from both calculations should be the same:
```

2022-06-05 08:16 UTC, tkoyama010 commented on papers/rocketpy_team/paper.rst
> +of length, then such value must be devided by the relevant unit for comparison:
```suggestion
of length, then such value must be divided by the relevant unit for comparison: 
```

2022-06-05 08:16 UTC, tkoyama010 commented on papers/rocketpy_team/paper.rst
> +values was established after the publication of the experimental data by :cite:`ceotto2021rocketpy`.
```suggestion
values were established after the publication of the experimental data by :cite:`ceotto2021rocketpy`.
```

2022-06-05 08:16 UTC, tkoyama010 commented on papers/rocketpy_team/paper.rst
> +Rocketpy is an easy-to-use tool for simulating high-powered rocket trajectories built with SciPy and
```suggestion
RocketPy is an easy-to-use tool for simulating high-powered rocket trajectories built with SciPy and 
```

2022-06-05 08:16 UTC, tkoyama010 commented on papers/rocketpy_team/paper.rst
> +================
```suggestion
Acknowledgments
===============
```

2022-06-05 08:16 UTC, tkoyama010 commented on papers/rocketpy_team/paper.rst
> +the development the current publication, and also all members of Projeto Jupiter and the RocketPy Team
```suggestion
the development of the current publication, and also all members of Projeto Jupiter and the RocketPy Team 
```

2022-06-05 08:16 UTC, tkoyama010 commented on papers/rocketpy_team/paper.rst
> +who contributed in the making of the RocketPy library.
```suggestion
who contributed to the making of the RocketPy library.
```

2022-06-07 02:56 UTC, deniederhut commented
@scoobies mark needs more review

2022-06-07 02:57 UTC, deniederhut commented
Hi! We've moved the deadline for first reviews back one week, to June 16th, to give us a little more time to find reviewers for all the papers this year. You can see the updated full timeline at https://github.com/scipy-conference/scipy_proceedings#timeline-for-2022.

2022-06-07 22:09 UTC, giovaniceotto commented on papers/rocketpy_team/paper.rst
> +   Function.comparePlots(
Sure! We have made changes in [e94c194](https://github.com/scipy-conference/scipy_proceedings/pull/710/commits/e94c194296819bce6305e974004fa6ff3ad01956) to make it clear how each class is imported, including the Function class.

In summary, it's just `from rocketpy import Function, Environment, SolidMotor, Rocket, Flight`.

2022-06-07 22:12 UTC, tkoyama010 approved these changes
LGTM

2022-06-07 22:13 UTC, tkoyama010 commented on papers/rocketpy_team/paper.rst
> +   Function.comparePlots(
Thanks.

2022-06-11 21:28 UTC, deniederhut commented
@scoobies mark pending comment

2022-06-27 03:45 UTC, deniederhut commented on papers/rocketpy_team/paper.rst
> +       return True if vel_z < 0 and height < 800 else False
This line runs into the next column in the rendered pd -- would it be possible to shorten it?

<img width="421" alt="Screen Shot 2022-06-26 at 10 44 06 PM" src="https://user-images.githubusercontent.com/6868396/175856101-229819d5-473d-4e01-974b-6ba261d1f8f2.png">
f

2022-06-27 03:46 UTC, deniederhut commented on papers/rocketpy_team/paper.rst
> +      topRadius=0.0635, bottomRadius=0.0435, length=0.060,
Looks like this one is running a bit too long as well. If you're using a tool like black for formatting, you can try setting the default width to be less than 79 characters?

2022-06-27 03:52 UTC, deniederhut commented on papers/rocketpy_team/paper.rst
> +      # Define all classes and simulate with the current
These comments might also need to be a tad bit shorter

2022-06-28 22:54 UTC, deniederhut commented
Hey @MrGribel ! Looks like there are still a couple of formatting issues -- do you have time to take a look?

2022-06-29 04:07 UTC, MrGribel commented
Sure! We'll get right on it.

2022-06-30 02:54 UTC, Gui-FernandesBR commented
> Hey @MrGribel ! Looks like there are still a couple of formatting issues -- do you have time to take a look?

@deniederhut I  believe we addressed everything in the last commit, can you give a double check ?
Please let me know if there's anything we still must correct, I'll address asap!

2022-07-01 00:40 UTC, deniederhut commented
@scoobies check references

2022-07-01 00:41 UTC, scoobies commented
```
Reference check summary (note 'MISSING' DOIs are suggestions that need verification):

OK DOIs

- 10.1137/0904010 is OK
- 10.3233/978-1-61499-649-1-87 is OK
- 10.5281/zenodo.4279966 is OK
- 10.1016/j.jsse.2018.01.002 is OK
- 10.1038/s41592-019-0686-2 is OK
- 10.1080/01621459.1966.10480892 is OK
- 10.1145/321607.321609 is OK

MISSING DOIs

- 10.1007/springerreference_29038 may be a valid DOI for title: Standard Atmosphere

INVALID DOIs

- 10.1061/ASCEAS.1943-5525.0001331 is INVALID
```

2022-07-01 00:42 UTC, deniederhut commented on papers/rocketpy_team/references.bib
> +@book{rubinstein2016simulation,
I think we're missing 10.1002/9781118631980 as the DOI for this one?

2022-07-01 00:43 UTC, deniederhut commented on papers/rocketpy_team/references.bib
> +@book{piessens2012quadpack,
10.1007/978-3-642-61786-7

2022-07-01 00:48 UTC, deniederhut commented
Thanks for the format fixes @Gui-FernandesBR ! I think we still have two missing DOIs in the references section -- I left inline comments (you can ignore the report from scoobies about the missing and invalid ones).

2022-07-01 09:20 UTC, giovaniceotto commented on papers/rocketpy_team/references.bib
> +@book{piessens2012quadpack,
Adressed in [9eca023](https://github.com/scipy-conference/scipy_proceedings/pull/710/commits/9eca023af500a1e434dcd3303d233decf1ad31c8)

2022-07-01 09:22 UTC, giovaniceotto commented on papers/rocketpy_team/references.bib
> +@book{rubinstein2016simulation,
Addressed in [9eca023](https://github.com/scipy-conference/scipy_proceedings/pull/710/commits/9eca023af500a1e434dcd3303d233decf1ad31c8)

2022-07-02 00:48 UTC, deniederhut commented
@scoobies check references

2022-07-02 00:48 UTC, scoobies commented
```
Reference check summary (note 'MISSING' DOIs are suggestions that need verification):

OK DOIs

- 10.1137/0904010 is OK
- 10.3233/978-1-61499-649-1-87 is OK
- 10.5281/zenodo.4279966 is OK
- 10.1016/j.jsse.2018.01.002 is OK
- 10.1038/s41592-019-0686-2 is OK
- 10.1002/9781118631980 is OK
- 10.1080/01621459.1966.10480892 is OK
- 10.1007/978-3-642-61786-7 is OK
- 10.1145/321607.321609 is OK

MISSING DOIs

- 10.1007/springerreference_29038 may be a valid DOI for title: Standard Atmosphere

INVALID DOIs

- 10.1061/ASCEAS.1943-5525.0001331 is INVALID
```

2022-07-02 00:52 UTC, deniederhut commented
Thanks for adding those!

2022-07-02 00:52 UTC, deniederhut approved these changes
I think we're good to go here! Thanks everyone!

2022-07-02 00:52 UTC, deniederhut commented
@scoobies mark ready

2022-07-06 12:19 UTC, merged