Paper Catlett UCET
scipy-conference/scipy_proceedings pull request #712
Opened 2022-05-27 21:46 UTC by acatlett8

If you are creating this PR in order to submit a draft of your paper,
see http://procbuild.scipy.org/ for logs generated by the build
process.

See the [project readme](https://github.com/scipy-conference/scipy_proceedings#build-your-paper)
for more information.

*Editor*:  

*Reviewers*:

2022-05-27 21:46 UTC, scoobies commented
Hi!, I'm @scoobies, a friendly bot.

Type ```@scoobies help``` to discover how I can help you.

2022-05-29 21:02 UTC, deniederhut commented
@scoobies mark paper

2022-05-29 21:02 UTC, deniederhut commented
@scoobies build status

2022-05-29 21:02 UTC, scoobies commented
{"erdc-paper_catlett"=>{"data"=>{"build_output"=>"[*] Updating proceedings build tools in {self.master_repo_path}...\nAlready up to date.\n[*] Check out paper repository...\nCloning into '/tmp/tmp_ut2kxjw'...\nMoving proceedings build tools to temp directory...\n[*] Build the paper...\nBuilding: Catlett_Amanda\n*** Warning: /tmp/tmp_ut2kxjw/publisher/../output/Catlett_Amanda/paper_stats.json does not exist.\n", "build_pdf_path"=>"/procbuild/procbuild/../cache/erdc-paper_catlett.pdf", "build_status"=>"success", "build_timestamp"=>"29/05 01:34"}, "status"=>"success"}}

2022-05-29 21:03 UTC, deniederhut commented
@scoobies mark needs review

2022-05-29 21:03 UTC, deniederhut commented
@scoobies assign @cbcunc as editor

2022-05-29 21:03 UTC, scoobies commented
Assigned! @cbcunc is now the editor

2022-05-31 15:34 UTC, mepa commented
@scoobies add @KedoKudo to reviewers

2022-05-31 15:34 UTC, scoobies commented
@KedoKudo added to the reviewers list!

2022-06-01 23:57 UTC, cbcunc commented
Editor confirms paper builds.

2022-06-07 03:05 UTC, deniederhut commented
Hi! We've moved the deadline for first reviews back one week, to June 16th, to give us a little more time to find reviewers for all the papers this year. You can see the updated full timeline at https://github.com/scipy-conference/scipy_proceedings#timeline-for-2022.

2022-06-13 23:41 UTC, cbcunc commented
@KedoKudo First review is due June 16.

2022-06-14 15:34 UTC, KedoKudo requested changes
The overall writing is very good, and the description of the process of modernizing a 30+ years old application is both informative and educational.
In addition to the comments specific to certain paragraphs, I have a few more questions regarding the overall modernization process:

- Are there any efforts in adding unit tests for both the models as well as the UI aspect?  If so, what are the challenges and how did the development team manage to overcome them?

- What is the deployment strategy for this modernized web application?  Based on the content of the manuscript, it seems like the calculation and visualization are carried out by the same node.  A typical web app generally have the computing work done on the server side (dedicated worker nodes that can handle computational intensive workload) while the visualization is done at the client side (rendering reduced data and submit computing job to worker nodes).  Is this type of deployment already supported?  If so, how does it handle the authentication process, assuming that the computing resources requires some level of protection.

-  Are there any continuous integration (CI) and continuous deployment (CD) in place for the development of this web app?

2022-06-14 15:34 UTC, KedoKudo commented on papers/Catlett_Amanda/UCET.rst
> +scalable. The tools were expanded to a Graphical User Interface (GUI) so the implementation to a web-app would provide
Could the authors also summaries the long-term maintainability of the modernized web app in the following areas:
- user documentation and user documentation update policy
- developer documentation
- overall code complexity

2022-06-14 15:34 UTC, KedoKudo commented on papers/Catlett_Amanda/UCET.rst
> +- **bounds**: each input variable is defined with range values defined in the 1992 ACES user manual
Is the `1992 ACES user manual` distributed with the source code?  If not, I would recommend providing a reference or a link to this manual.

2022-06-15 00:16 UTC, deniederhut commented
@scoobies mark pending comment

2022-06-17 13:48 UTC, acatlett8 commented on papers/Catlett_Amanda/UCET.rst
> +scalable. The tools were expanded to a Graphical User Interface (GUI) so the implementation to a web-app would provide
Thanks for your comments! 
- We have some tests that are testing the Python is getting the same answers as the old FORTRAN. The biggest problem is getting the data output from the FORTRAN.  But we do not have any for the UI aspect. I was unaware that was a thing. This is something we will look into for sure
- UCET right now does not have HEAVY calculations. so right now we don't think there is a need to have multiple servers. We do need to discuss how we are deploying this on a website and will add that information
- We will write about plans for the CICD in a future works selection. 
- I will also add a section about the long-term maintainability for user documentation, user documentation update policy, developer documentation, overall code complexity

2022-06-17 13:49 UTC, acatlett8 commented on papers/Catlett_Amanda/UCET.rst
> +- **bounds**: each input variable is defined with range values defined in the 1992 ACES user manual
Yes! that was a failing on my part! I will put a reference to the manual!

2022-06-24 01:26 UTC, deniederhut commented
Hi @acatlett8 ! How are the paper revisions coming along?

2022-06-24 20:40 UTC, cbcunc requested changes

2022-06-24 20:40 UTC, cbcunc commented on papers/Catlett_Amanda/UCET.rst
> +.. [Leenknecht] David A. Leenknecht, Andre Szuwalski, and Ann R. Sherlock. 1992. Automated Coastal Engineering System -Technical Reference. Technical report.
Need better citation. URL would help. One like https://usace.contentdm.oclc.org/digital/collection/p266001coll1/id/2321/ if no DOI available.

2022-06-24 20:40 UTC, cbcunc commented on papers/Catlett_Amanda/UCET.rst
> +.. [shankar] N.J. Shankar, M.P.R. Jayaratne, Wave run-up and overtopping on smooth and rough slopes of coastal structures, Ocean Engineering, Volume 30, Issue 2, 2003, Pages 221-238, ISSN 0029-8018,
DOI is https://doi.org/10.1016/S0029-8018(02)00016-1

2022-06-24 20:42 UTC, cbcunc requested changes

2022-06-24 20:42 UTC, cbcunc commented on papers/Catlett_Amanda/UCET.rst
> +.. [shankar] N.J. Shankar, M.P.R. Jayaratne, Wave run-up and overtopping on smooth and rough slopes of coastal structures, Ocean Engineering, Volume 30, Issue 2, 2003, Pages 221-238, ISSN 0029-8018,
Why is there a terminal comma?

2022-06-24 21:36 UTC, acatlett8 commented on papers/Catlett_Amanda/UCET.rst
> +.. [shankar] N.J. Shankar, M.P.R. Jayaratne, Wave run-up and overtopping on smooth and rough slopes of coastal structures, Ocean Engineering, Volume 30, Issue 2, 2003, Pages 221-238, ISSN 0029-8018,
added DOI to shankar

2022-06-24 21:36 UTC, acatlett8 commented on papers/Catlett_Amanda/UCET.rst
> +.. [shankar] N.J. Shankar, M.P.R. Jayaratne, Wave run-up and overtopping on smooth and rough slopes of coastal structures, Ocean Engineering, Volume 30, Issue 2, 2003, Pages 221-238, ISSN 0029-8018,
changed DOI

2022-06-24 21:36 UTC, acatlett8 commented on papers/Catlett_Amanda/UCET.rst
> +.. [Leenknecht] David A. Leenknecht, Andre Szuwalski, and Ann R. Sherlock. 1992. Automated Coastal Engineering System -Technical Reference. Technical report.
added URL

2022-06-24 21:38 UTC, acatlett8 commented on papers/Catlett_Amanda/UCET.rst
> +scalable. The tools were expanded to a Graphical User Interface (GUI) so the implementation to a web-app would provide
I pushed some changes. Another author will be coming along to add information about CICD. I tried to add most of what you commented on under a new section called current state.

2022-06-28 13:47 UTC, acatlett8 commented
I thought I pushed this Friday. but apparently that did not happen. Still trying to figure out Git.

2022-06-29 00:51 UTC, deniederhut commented
No worries! Is this ready for re-review?

2022-06-29 13:16 UTC, acatlett8 commented
@deniederhut I think it is ready for re-review!!

2022-06-29 19:14 UTC, cbcunc commented
Reviewers, please give your final recommendations. The deadline for final review comments is tomorrow.

Authors, please respond to review comments with changes or comments which resolve the conversation. Final acceptance decisions are July 4.

2022-06-29 19:45 UTC, KedoKudo commented on papers/Catlett_Amanda/UCET.rst
> +.. [Leenknecht] David A. Leenknecht, Andre Szuwalski, and Ann R. Sherlock. 1992. Automated Coastal Engineering System -Technical Reference. Technical report.
@acatlett8 it seems like you most recent merge accidentally removed the URL that was added a few days ago. Please add it back.

2022-06-29 19:47 UTC, KedoKudo approved these changes
The URL for the first reference was removed during the last merge.  I would recommend adding it back if possible.

The rest of the paper looks good for this ongoing project.  I would recommend it for publishing.

2022-06-29 20:49 UTC, acatlett8 commented on papers/Catlett_Amanda/UCET.rst
> +.. [Leenknecht] David A. Leenknecht, Andre Szuwalski, and Ann R. Sherlock. 1992. Automated Coastal Engineering System -Technical Reference. Technical report.
thanks! I think I added it back!!

2022-06-29 20:51 UTC, KedoKudo approved these changes
Thanks for adding the url back.

2022-07-04 19:43 UTC, deniederhut commented
@cbcunc is this paper ready?

2022-07-06 11:09 UTC, deniederhut commented
@cbcunc github shows that you are still requesting changes on this paper -- is it ready for publication?

2022-07-08 18:33 UTC, cbcunc approved these changes

2022-07-08 18:33 UTC, cbcunc commented
@scoobies mark ready

2022-07-09 00:37 UTC, merged