Paper: pyDAMPF HV Guzman
scipy-conference/scipy_proceedings pull request #714
Opened 2022-05-27 23:11 UTC by govarguz

If you are creating this PR in order to submit a draft of your paper,
see http://procbuild.scipy.org/ for logs generated by the build
process.

See the [project readme](https://github.com/scipy-conference/scipy_proceedings#build-your-paper)
for more information.

*Editor*:  

*Reviewers*:

2022-05-27 23:11 UTC, scoobies commented
Hi!, I'm @scoobies, a friendly bot.

Type ```@scoobies help``` to discover how I can help you.

2022-05-29 01:01 UTC, mepa commented
Hi @govarguz, thanks for your submission! You may have noticed that the paper currently does not build (see https://procbuild.scipy.org/). This is because the build process expects papers to be formatted using reStructuredText. Please take a look at the [instructions for authors](https://github.com/scipy-conference/scipy_proceedings#instructions-for-authors) and reach out here if you have any questions about how to convert to that format.

2022-05-29 16:21 UTC, govarguz commented
Hi @mepa, we have a lot of questions on how to convert our .tex to .rst.  We have tested out pandoc and other tools and obtained always problems with the tables and figures... Could you have a look? Is there a way to add a line to the build process to build .tex, as well? Thanks!

2022-05-29 21:04 UTC, deniederhut commented
@scoobies mark paper

2022-05-29 21:04 UTC, deniederhut commented
@scoobies build status

2022-05-29 21:04 UTC, scoobies commented
{"govarguz-2022"=>{"data"=>{"build_output"=>"[*] Updating proceedings build tools in {self.master_repo_path}...\nAlready up to date.\n[*] Check out paper repository...\nCloning into '/tmp/tmpibf4p_ze'...\nMoving proceedings build tools to temp directory...\n[*] Build the paper...\nBuilding: pyDAMPF_HVGuzman\nTraceback (most recent call last):\n  File \"publisher/build_paper.py\", line 83, in rst2tex\n    rst, = glob.glob(os.path.join(in_path, '*.rst'))\nValueError: not enough values to unpack (expected 1, got 0)\n\nDuring handling of the above exception, another exception occurred:\n\nTraceback (most recent call last):\n  File \"publisher/build_paper.py\", line 237, in <module>\n    build_paper(paper_id)\n  File \"publisher/build_paper.py\", line 222, in build_paper\n    rst2tex(in_path, out_path)\n  File \"publisher/build_paper.py\", line 85, in rst2tex\n    raise RuntimeError(\"Found more than one input .rst--not sure which \"\nRuntimeError: Found more than one input .rst--not sure which one to use.\nError building paper /tmp/tmpibf4p_ze/papers/pyDAMPF_HVGuzman. Aborting.\n[X] Error code 1\nA build error occurred during the self.run_make_paper_script step.", "build_pdf_path"=>"", "build_status"=>"Build failed, make_paper.sh did not succeed", "build_timestamp"=>"29/05 19:54"}, "status"=>"fail"}}

2022-05-29 21:04 UTC, deniederhut commented
@scoobies mark server fail

2022-05-29 21:04 UTC, deniederhut commented
@scoobies assign @stargaser as editor

2022-05-29 21:04 UTC, scoobies commented
Assigned! @stargaser is now the editor

2022-05-29 22:22 UTC, deniederhut commented
> We have tested out pandoc and other tools and obtained always problems with the tables and figures

Yeah, tables in rst can be tricky. You should be able to keep the tables in latex -- there's an example of how to do this in the 00_vanderwalt paper -- and just worry about translating the other stuff.

> Is there a way to add a line to the build process to build .tex, as well?

Haha it will take more than one line, but yes we are working on that and should have it ready for the 2023 conference.

2022-05-30 23:57 UTC, mepa commented
> Hi @mepa, we have a lot of questions on how to convert our .tex to .rst. We have tested out pandoc and other tools and obtained always problems with the tables and figures... Could you have a look? Is there a way to add a line to the build process to build .tex, as well? Thanks!

Hi @govarguz, sure, we'll be glad to look! First, to make sure I understand the context, have you attempted converting to .rst and building the paper locally? I only see .tex and associated files on this branch (no .rst file, which is what the build process is expecting). If you haven't already, please take a look at the example papers referenced in https://github.com/scipy-conference/scipy_proceedings#instructions-for-authors for help with the conversion.

As for building .tex directly, that's not supported for the 2022 conference but adding that support is in the works. Please see https://github.com/scipy-conference/scipy_proceedings/issues/419 for more details.

2022-06-03 21:37 UTC, deniederhut commented
Hey @govarguz ! It looks like you might have a paper.rst file that didn't make it into your PR. Would you mind adding it? We'll need this to build the paper for the proceedings.

2022-06-04 00:27 UTC, govarguz commented
Sure, @deniederhut I am going to add it soon. Thanks for the heads-up!

2022-06-07 03:05 UTC, deniederhut commented
Hi! We've moved the deadline for first reviews back one week, to June 16th, to give us a little more time to find reviewers for all the papers this year. You can see the updated full timeline at https://github.com/scipy-conference/scipy_proceedings#timeline-for-2022.

2022-06-08 00:11 UTC, govarguz commented
Hi @deniederhut  and @mepa,  we have made our efforts to transform tex to rst. Could you have a look at it? Does it build any PDF. Thanks in advance for any further hint!

2022-06-08 00:12 UTC, govarguz commented
> > Hi @mepa, we have a lot of questions on how to convert our .tex to .rst. We have tested out pandoc and other tools and obtained always problems with the tables and figures... Could you have a look? Is there a way to add a line to the build process to build .tex, as well? Thanks!
> 
> Hi @govarguz, sure, we'll be glad to look! First, to make sure I understand the context, have you attempted converting to .rst and building the paper locally? I only see .tex and associated files on this branch (no .rst file, which is what the build process is expecting). If you haven't already, please take a look at the example papers referenced in https://github.com/scipy-conference/scipy_proceedings#instructions-for-authors for help with the conversion.
> 
> As for building .tex directly, that's not supported for the 2022 conference but adding that support is in the works. Please see #419 for more details.

Hi @mepa, yes indeed #419 for more details is required

2022-06-08 01:46 UTC, deniederhut commented
@scoobies build paper

2022-06-08 01:46 UTC, scoobies commented
building paper...

2022-06-08 01:46 UTC, scoobies commented
{"data"=>{"info"=>"Build for paper govarguz-2022 scheduled.  Note that builds are only executed if the current build attempt is more than 5 minutes old."}, "status"=>"success"}

2022-06-08 01:46 UTC, deniederhut commented
@scoobies build status

2022-06-08 01:46 UTC, scoobies commented
{"govarguz-2022"=>{"data"=>{"build_output"=>"[*] Updating proceedings build tools in {self.master_repo_path}...\nAlready up to date.\n[*] Check out paper repository...\nCloning into '/tmp/tmpa02lm4qa'...\nMoving proceedings build tools to temp directory...\n[*] Build the paper...\nBuilding: pyDAMPF_HVGuzman\nPDFLaTeX error output:\n================================================================================\nThis is pdfTeX, Version 3.14159265-2.6-1.40.18 (TeX Live 2017/Debian) (preloaded format=pdflatex)\n restricted \\write18 enabled.\nentering extended mode\n(./paper.tex\nLaTeX2e <2017-04-15>\nBabel <3.18> and hyphenation patterns for 3 language(s) loaded.\n(./IEEEtran.cls\nDocument Class: IEEEtran 2015/08/26 V1.8b by Michael Shell\n-- See the \"IEEEtran_HOWTO\" manual for usage information.\n-- http://www.michaelshell.org/tex/ieeetran/\n(/usr/share/texlive/texmf-dist/tex/latex/psnfss/ot1ppl.fd)\n-- Using IEEE Computer Society mode.\n-- Using 8.5in x 11in (letter) paper.\n-- Using PDF output.\n-- This is a 10 point document.\n) (/usr/share/texlive/texmf-dist/tex/latex/cmap/cmap.sty)\n(/usr/share/texlive/texmf-dist/tex/latex/base/ifthen.sty)\n(/usr/share/texlive/texmf-dist/tex/latex/base/fontenc.sty\n(/usr/share/texlive/texmf-dist/tex/latex/base/t1enc.def)\n(/usr/share/texlive/texmf-dist/tex/latex/psnfss/t1ppl.fd)<<t1.cmap>>)\n(/usr/share/texlive/texmf-dist/tex/latex/base/inputenc.sty\n(/usr/share/texlive/texmf-dist/tex/latex/base/utf8.def\n(/usr/share/texlive/texmf-dist/tex/latex/base/t1enc.dfu)\n(/usr/share/texlive/texmf-dist/tex/latex/base/ot1enc.dfu)\n(/usr/share/texlive/texmf-dist/tex/latex/base/omsenc.dfu)))\n(/usr/share/texlive/texmf-dist/tex/latex/amsmath/amsmath.sty\nFor additional information on amsmath, use the `?' option.\n(/usr/share/texlive/texmf-dist/tex/latex/amsmath/amstext.sty\n(/usr/share/texlive/texmf-dist/tex/latex/amsmath/amsgen.sty))\n(/usr/share/texlive/texmf-dist/tex/latex/amsmath/amsbsy.sty)\n(/usr/share/texlive/texmf-dist/tex/latex/amsmath/amsopn.sty))\n(/usr/share/texlive/texmf-dist/tex/latex/caption/caption.sty\n(/usr/share/texlive/texmf-dist/tex/latex/caption/caption3.sty\n(/usr/share/texlive/texmf-dist/tex/latex/graphics/keyval.sty))\n\nPackage caption Warning: Unsupported document class (or package) detected,\n(caption)                usage of the caption package is not recommended.\nSee the caption package documentation for explanation.\n\n) (/usr/share/texlive/texmf-dist/tex/latex/float/float.sty) (./scipy.sty\n(./status.sty (./draftwatermark.sty (./everypage.sty)\n(/usr/share/texlive/texmf-dist/tex/latex/graphics/graphicx.sty\n(/usr/share/texlive/texmf-dist/tex/latex/graphics/graphics.sty\n(/usr/share/texlive/texmf-dist/tex/latex/graphics/trig.sty)\n(/usr/share/texlive/texmf-dist/tex/latex/graphics-cfg/graphics.cfg)\n(/usr/share/texlive/texmf-dist/tex/latex/graphics-def/pdftex.def)))\n(/usr/share/texlive/texmf-dist/tex/latex/graphics/color.sty\n(/usr/share/texlive/texmf-dist/tex/latex/graphics-cfg/color.cfg))))\n(/usr/share/texlive/texmf-dist/tex/latex/psnfss/mathptmx.sty)\n(/usr/share/texlive/texmf-dist/tex/latex/psnfss/helvet.sty)\n(/usr/share/texlive/texmf-dist/tex/latex/psnfss/courier.sty)\n(/usr/share/texlive/texmf-dist/tex/latex/amsfonts/amsfonts.sty)\n(/usr/share/texlive/texmf-dist/tex/latex/amsfonts/amssymb.sty)\n(/usr/share/texlive/texmf-dist/tex/latex/tools/bm.sty)\n(/usr/share/texlive/texmf-dist/tex/latex/hyperref/hyperref.sty\n(/usr/share/texlive/texmf-dist/tex/generic/oberdiek/hobsub-hyperref.sty\n(/usr/share/texlive/texmf-dist/tex/generic/oberdiek/hobsub-generic.sty))\n(/usr/share/texlive/texmf-dist/tex/generic/ifxetex/ifxetex.sty)\n(/usr/share/texlive/texmf-dist/tex/latex/oberdiek/auxhook.sty)\n(/usr/share/texlive/texmf-dist/tex/latex/oberdiek/kvoptions.sty)\n(/usr/share/texlive/texmf-dist/tex/latex/hyperref/pd1enc.def)\n(/usr/share/texlive/texmf-dist/tex/latex/latexconfig/hyperref.cfg)\n(/usr/share/texlive/texmf-dist/tex/latex/url/url.sty))\n(/usr/share/texlive/texmf-dist/tex/latex/hyperref/hpdftex.def\n(/usr/share/texlive/texmf-dist/tex/latex/oberdiek/rerunfilecheck.sty))\n\nPackage hyperref Warning: Option `pdftex' has already been used,\n(hyperref)                setting the option has no effect on input line 43.\n\n(/usr/share/texlive/texmf-dist/tex/latex/tools/longtable.sty)\n(/usr/share/texlive/texmf-dist/tex/latex/multirow/multirow.sty)\n(/usr/share/texlive/texmf-dist/tex/latex/booktabs/booktabs.sty)\n(/usr/share/texlive/texmf-dist/tex/latex/base/textcomp.sty\n(/usr/share/texlive/texmf-dist/tex/latex/base/ts1enc.def\n(/usr/share/texlive/texmf-dist/tex/latex/base/ts1enc.dfu)))\n(/usr/share/texlive/texmf-dist/tex/latex/upquote/upquote.sty)\n(/usr/share/texlive/texmf-dist/tex/latex/fancyvrb/fancyvrb.sty\nStyle option: `fancyvrb' v2.7a, with DG/SPQR fixes, and firstline=lastline fix \n<2008/02/07> (tvz))) (./paper.aux)\n(/usr/share/texlive/texmf-dist/tex/latex/base/ts1cmr.fd)\n(/usr/share/texlive/texmf-dist/tex/latex/psnfss/t1ptm.fd)\n-- Lines per column: 61 (exact).\n(/usr/share/texlive/texmf-dist/tex/latex/caption/ltcaption.sty)\n(/usr/share/texlive/texmf-dist/tex/context/base/mkii/supp-pdf.mkii\n[Loading MPS to PDF converter (version 2006.09.02).]\n) (/usr/share/texlive/texmf-dist/tex/latex/oberdiek/epstopdf-base.sty\n(/usr/share/texlive/texmf-dist/tex/latex/oberdiek/grfext.sty)\n(/usr/share/texlive/texmf-dist/tex/latex/latexconfig/epstopdf-sys.cfg))\n(/usr/share/texlive/texmf-dist/tex/latex/hyperref/nameref.sty\n(/usr/share/texlive/texmf-dist/tex/generic/oberdiek/gettitlestring.sty))\n(./paper.out) (./paper.out)\n(/usr/share/texlive/texmf-dist/tex/latex/psnfss/t1phv.fd)\n(/usr/share/texlive/texmf-dist/tex/latex/psnfss/ot1ztmcm.fd)<<ot1.cmap>>\n(/usr/share/texlive/texmf-dist/tex/latex/psnfss/omlztmcm.fd)<<oml.cmap>>\n(/usr/share/texlive/texmf-dist/tex/latex/psnfss/omsztmcm.fd)<<oms.cmap>>\n(/usr/share/texlive/texmf-dist/tex/latex/psnfss/omxztmcm.fd)<<omx.cmap>>\n(/usr/share/texlive/texmf-dist/tex/latex/psnfss/ot1ptm.fd)\n(/usr/share/texlive/texmf-dist/tex/latex/psnfss/upzd.fd)\n(/usr/share/texlive/texmf-dist/tex/latex/psnfss/ts1ptm.fd) (./page_numbers.tex)\n\nLaTeX Warning: Citation `dForce' on page 1 undefined on input line 198.\n\n\nLaTeX Warning: Citation `Veda' on page 1 undefined on input line 198.\n\n\nLaTeX Warning: Citation `dForce' on page 1 undefined on input line 240.\n\n\nLaTeX Warning: Citation `Sader' on page 1 undefined on input line 242.\n\n[1{/var/lib/texmf/fonts/map/pdftex/updmap/pdftex.map}]\n(/usr/share/texlive/texmf-dist/tex/latex/psnfss/t1pcr.fd)\n(/usr/share/texlive/texmf-dist/tex/latex/psnfss/ts1pcr.fd)\n\nLaTeX Warning: Citation `f2py' on page 2 undefined on input line 312.\n\n[2]\n\nLaTeX Warning: No positions in optional float specifier.\n               Default added (so using `tbp') on input line 544.\n\n\nLaTeX Warning: No positions in optional float specifier.\n               Default added (so using `tbp') on input line 547.\n\n\nLaTeX Warning: No positions in optional float specifier.\n               Default added (so using `tbp') on input line 550.\n\n\nLaTeX Warning: No positions in optional float specifier.\n               Default added (so using `tbp') on input line 553.\n\n[3 <./casoa.png> <./casob.png> <./casoc.png>]\n\nLaTeX Warning: Citation `GarciaRev2021' on page 4 undefined on input line 578.\n\n\nLaTeX Warning: Citation `GuzmanScalingBJON2015' on page 4 undefined on input li\nne 581.\n\n\nLaTeX Warning: No positions in optional float specifier.\n               Default added (so using `tbp') on input line 589.\n\n\nLaTeX Warning: No positions in optional float specifier.\n               Default added (so using `tbp') on input line 592.\n\n\nLaTeX Warning: File `fig2bR3.png' not found on input line 592.\n\n\n! Package pdftex.def Error: File `fig2bR3.png' not found: using draft setting.\n\nSee the pdftex.def package documentation for explanation.\nType  H <return>  for immediate help.\n ...                                              \n            [...]

2022-06-08 01:47 UTC, deniederhut commented
> Error: File fig2bR3.png' not found

Looks like there might be a typo in the filename for this figure?

2022-06-09 10:58 UTC, govarguz commented
@deniederhut It is a pity it did not build like the original tex... but that's the result of using rst. Looking forward for the 2023 system with embedded .tex builds!

2022-06-10 08:38 UTC, govarguz commented
Hi @stargaser, could you update the label: "doesn't build". Check it [here](https://procbuild.scipy.org/# ) 
Thanks!

2022-06-10 15:36 UTC, stargaser commented
@scoobies help

2022-06-10 15:36 UTC, scoobies commented
Hello @stargaser, here are the things you can ask me to do:

```

# List all available commands
@scoobies help

# Show our community Code of Conduct and Guidelines
@scoobies code of conduct

# Add to this issue's reviewers list
@scoobies add @username to reviewers

# Remove from this issue's reviewers list
@scoobies remove @username from reviewers

# Assign a user as the editor of this submission
@scoobies assign @username as editor

# Remove the editor assigned to this submission
@scoobies remove editor

# Add a user to this issue's assignees list
@scoobies add assignee: @username

# Remove a user from this issue's assignees list
@scoobies remove assignee: @username

# Builds paper
@scoobies build paper

# Checks build status
@scoobies build status

# Check the references of the paper for missing DOIs
# Optionally, it can be run on a non-default branch 
@scoobies check references
@scoobies check references from custom-branch-name

# Label issue with: paper
@scoobies mark paper

# Label issue with: needs-review. Remove labels: unready, needs-more-review, pending-comment, ready
@scoobies mark needs review

# Label issue with: needs-more-review. Remove labels: unready, needs-review, pending-comment, ready
@scoobies mark needs more review

# Label issue with: pending-comment. Remove labels: unready, needs-review, needs-more-review, ready
@scoobies mark pending comment

# Label issue with: ready. Remove labels: unready, needs-review, needs-more-review, pending-comment
@scoobies mark ready

# Label issue with: unready. Remove labels: needs-review, needs-more-review, pending-comment, ready
@scoobies mark not ready

# Label issue with: does_not_build:server
@scoobies mark server fail

# Remove labels: does_not_build:server
@scoobies mark server success

```

2022-06-10 15:40 UTC, stargaser commented
@scoobies mark server success

2022-06-10 15:41 UTC, stargaser commented
@scoobies mark needs review

2022-06-14 09:34 UTC, govarguz commented
@scoobies (cc: @stargaser @mepa @deniederhut  ) add reviewers

2022-06-15 17:51 UTC, stargaser commented
@scoobies add @stargaser to reviewers

2022-06-15 17:51 UTC, scoobies commented
@stargaser added to the reviewers list!

2022-06-15 23:24 UTC, stargaser commented
Hi @govarguz, we haven't been able to find a reviewer for this paper so I'll be stepping in to review.

2022-06-15 23:26 UTC, govarguz commented
Hi @stargaser, good to hear you will be providing us a review on `pyDAMPF`

2022-06-17 23:26 UTC, stargaser requested changes
Thank you for this interesting paper. I am not familiar with Atomic Force Microscopy but I felt I could follow most of the paper.

Major comments:
* Figure numbering is out of sync with in-text references. I've made a few suggestions for syncing those.
* Some grammar errors are in the paper. One suggestion is to run the text through a tool like Grammarly.
* In most of the peak force figures 10, 11, 12, isn't 0% relative humidity excluded since E_s would be over 900 MPa?

2022-06-17 23:26 UTC, stargaser commented on papers/pyDAMPF_HVGuzman/pyDAMPF.rst
> +   pyDAMPF is a tool oriented to the Atomic Force Microscopy (AFM) community, which allows the simulation of the physical properties of materials under variable relative humidity (RH). In particular,
```suggestion
   pyDAMPF is a tool oriented to the Atomic Force Microscopy (AFM) community, which allows the simulation of the physical properties of materials under variable relative humidity (RH). In particular, pyDAMPF is mainly focused on the mechanical properties of polymeric hygroscopic nanofibers that play an essential role in designing tissue scaffolds for implants and filtering devices. Those mechanical properties have been mostly studied from a very coarse perspective reaching a micrometer scale. However, at the nanoscale, the mechanical response of polymeric fibers becomes cumbersome due to both experimental and theoretical challenges. For example, the response of polymeric fibers to RH demands advanced models that consider sub-nanometric changes in the local structure of each single polymer chain. From an experimental viewpoint, choosing the optimal cantilevers to scan the fibers under variable RH is not trivial.
```

2022-06-17 23:26 UTC, stargaser commented on papers/pyDAMPF_HVGuzman/pyDAMPF.rst
> +We present four scenarios comparing a total of seven cantilevers and the same sample, where we use as a test-case Poly-Vinyl Acetate (PVA) fiber. The first scenario (Figure `1 <#fig1a>`__\ (a)) illus
I think it will be necessary to cite figures with :ref:`fig1a` and so on
```suggestion
We present four scenarios comparing a total of seven cantilevers and the same sample, where we use as a test-case Poly-Vinyl Acetate (PVA) fiber. The first scenario (Figure :ref:`fig1a`) illustrates the difference between air and a moist environment. On the second one, a cantilever, only a very soft and stiff cantilever spring constants are compared (see Figure :ref:fig1b`). At the same time, the different volumes along the 30 cantilevers are depicted in Figure :ref:`fig1c`. A final and mostly very common comparison is scenario 4, by comparing one of the most sensitive parameters to the force of the tip’s radii (see Figure :ref:`fig1d`).
```

2022-06-17 23:26 UTC, stargaser commented on papers/pyDAMPF_HVGuzman/pyDAMPF.rst
> +In Figure `1 <#fig1a>`__, we show four scenarios to be tackled in this test-case for pyDAMPF. As described in the introduction, the first scenario (Figure `1 <#fig1a>`__\ (a)), compares between air a
Use :ref:`fig1a` throughout to number the figure captions and the text references consistently

2022-06-17 23:26 UTC, stargaser commented on papers/pyDAMPF_HVGuzman/pyDAMPF.rst
> +The AFM is widely used for mechanical properties mapping of matter :cite:`GarciaRev2021`. Hence, the first comparison of the four scenarios points out to the force response versus time according to a
To number the figure captions and in-text references in a consistent manner:
```
Figure :ref:`fig2a`
```

2022-06-17 23:26 UTC, stargaser commented on papers/pyDAMPF_HVGuzman/pyDAMPF.rst
> +In Figure `1 <#fig1a>`__, we show four scenarios to be tackled in this test-case for pyDAMPF. As described in the introduction, the first scenario (Figure `1 <#fig1a>`__\ (a)), compares between air a
Recommend to use for consistent figure numbering:
```
Figure :ref:`fig1a`
Figure :ref:`tab1`
```

2022-06-18 02:04 UTC, deniederhut commented
@scoobies mark pending comment

2022-06-21 14:53 UTC, govarguz commented on papers/pyDAMPF_HVGuzman/pyDAMPF.rst
> +In Figure `1 <#fig1a>`__, we show four scenarios to be tackled in this test-case for pyDAMPF. As described in the introduction, the first scenario (Figure `1 <#fig1a>`__\ (a)), compares between air a
@stargaser thanks for the suggestion, we have modified the referencing and captions and will commit the final version soon

2022-06-21 14:53 UTC, govarguz commented on papers/pyDAMPF_HVGuzman/pyDAMPF.rst
> +The AFM is widely used for mechanical properties mapping of matter :cite:`GarciaRev2021`. Hence, the first comparison of the four scenarios points out to the force response versus time according to a
@stargaser thanks for the suggestion, we have modified the referencing and captions and will commit the final version soon

2022-06-21 14:56 UTC, govarguz commented on papers/pyDAMPF_HVGuzman/pyDAMPF.rst
> +In Figure `1 <#fig1a>`__, we show four scenarios to be tackled in this test-case for pyDAMPF. As described in the introduction, the first scenario (Figure `1 <#fig1a>`__\ (a)), compares between air a
@stargaser thanks for the suggestion, we have modified the referencing and captions and will commit the final version soon

2022-06-23 11:07 UTC, govarguz commented
@deniederhut @stargaser  the revised version has been submitted. I thank already my student @willymenacho and my other collaborators for the celerity in the revision of the Ms.

2022-06-24 21:17 UTC, deniederhut commented
@scoobies build status

2022-06-24 21:17 UTC, scoobies commented
{"govarguz-2022"=>{"data"=>{"build_output"=>"[*] Updating proceedings build tools in {self.master_repo_path}...\nAlready up to date.\n[*] Check out paper repository...\nCloning into '/tmp/tmpziw_aage'...\nMoving proceedings build tools to temp directory...\n[*] Build the paper...\n<string>:245: (WARNING/2) Mismatch: both interpreted text role prefix and reference suffix.\n<string>:245: (WARNING/2) Mismatch: both interpreted text role prefix and reference suffix.\n<string>:245: (WARNING/2) Mismatch: both interpreted text role prefix and reference suffix.\n<string>:245: (WARNING/2) Mismatch: both interpreted text role prefix and reference suffix.\n<string>:251: (WARNING/2) Mismatch: both interpreted text role prefix and reference suffix.\n<string>:288: (WARNING/2) Mismatch: both interpreted text role prefix and reference suffix.\n<string>:288: (WARNING/2) Mismatch: both interpreted text role prefix and reference suffix.\n<string>:288: (WARNING/2) Mismatch: both interpreted text role prefix and reference suffix.\n<string>:288: (WARNING/2) Mismatch: both interpreted text role prefix and reference suffix.\n<string>:288: (WARNING/2) Mismatch: both interpreted text role prefix and reference suffix.\n<string>:288: (WARNING/2) Mismatch: both interpreted text role prefix and reference suffix.\n<string>:308: (WARNING/2) Mismatch: both interpreted text role prefix and reference suffix.\n<string>:308: (WARNING/2) Mismatch: both interpreted text role prefix and reference suffix.\n<string>:308: (WARNING/2) Mismatch: both interpreted text role prefix and reference suffix.\n<string>:308: (WARNING/2) Mismatch: both interpreted text role prefix and reference suffix.\n<string>:329: (WARNING/2) Mismatch: both interpreted text role prefix and reference suffix.\n<string>:329: (WARNING/2) Mismatch: both interpreted text role prefix and reference suffix.\n<string>:353: (WARNING/2) Mismatch: both interpreted text role prefix and reference suffix.\n<string>:353: (WARNING/2) Mismatch: both interpreted text role prefix and reference suffix.\n<string>:374: (WARNING/2) Mismatch: both interpreted text role prefix and reference suffix.\n<string>:374: (WARNING/2) Mismatch: both interpreted text role prefix and reference suffix.\n<string>:382: (WARNING/2) Mismatch: both interpreted text role prefix and reference suffix.\n<string>:397: (WARNING/2) Mismatch: both interpreted text role prefix and reference suffix.\n<string>:409: (WARNING/2) Mismatch: both interpreted text role prefix and reference suffix.\n<string>:414: (WARNING/2) Mismatch: both interpreted text role prefix and reference suffix.\n<string>:414: (WARNING/2) Mismatch: both interpreted text role prefix and reference suffix.\n<string>:414: (WARNING/2) Mismatch: both interpreted text role prefix and reference suffix.\n<string>:429: (WARNING/2) Mismatch: both interpreted text role prefix and reference suffix.\nBuilding: pyDAMPF_HVGuzman\nPDFLaTeX error output:\n================================================================================\nThis is pdfTeX, Version 3.14159265-2.6-1.40.18 (TeX Live 2017/Debian) (preloaded format=pdflatex)\n restricted \\write18 enabled.\nentering extended mode\n(./paper.tex\nLaTeX2e <2017-04-15>\nBabel <3.18> and hyphenation patterns for 3 language(s) loaded.\n(./IEEEtran.cls\nDocument Class: IEEEtran 2015/08/26 V1.8b by Michael Shell\n-- See the \"IEEEtran_HOWTO\" manual for usage information.\n-- http://www.michaelshell.org/tex/ieeetran/\n(/usr/share/texlive/texmf-dist/tex/latex/psnfss/ot1ppl.fd)\n-- Using IEEE Computer Society mode.\n-- Using 8.5in x 11in (letter) paper.\n-- Using PDF output.\n-- This is a 10 point document.\n) (/usr/share/texlive/texmf-dist/tex/latex/cmap/cmap.sty)\n(/usr/share/texlive/texmf-dist/tex/latex/base/ifthen.sty)\n(/usr/share/texlive/texmf-dist/tex/latex/base/fontenc.sty\n(/usr/share/texlive/texmf-dist/tex/latex/base/t1enc.def)\n(/usr/share/texlive/texmf-dist/tex/latex/psnfss/t1ppl.fd)<<t1.cmap>>)\n(/usr/share/texlive/texmf-dist/tex/latex/base/inputenc.sty\n(/usr/share/texlive/texmf-dist/tex/latex/base/utf8.def\n(/usr/share/texlive/texmf-dist/tex/latex/base/t1enc.dfu)\n(/usr/share/texlive/texmf-dist/tex/latex/base/ot1enc.dfu)\n(/usr/share/texlive/texmf-dist/tex/latex/base/omsenc.dfu)))\n(/usr/share/texlive/texmf-dist/tex/latex/amsmath/amsmath.sty\nFor additional information on amsmath, use the `?' option.\n(/usr/share/texlive/texmf-dist/tex/latex/amsmath/amstext.sty\n(/usr/share/texlive/texmf-dist/tex/latex/amsmath/amsgen.sty))\n(/usr/share/texlive/texmf-dist/tex/latex/amsmath/amsbsy.sty)\n(/usr/share/texlive/texmf-dist/tex/latex/amsmath/amsopn.sty))\n(/usr/share/texlive/texmf-dist/tex/latex/graphics/color.sty\n(/usr/share/texlive/texmf-dist/tex/latex/graphics-cfg/color.cfg)\n(/usr/share/texlive/texmf-dist/tex/latex/graphics-def/pdftex.def))\n(/usr/share/texlive/texmf-dist/tex/latex/caption/caption.sty\n(/usr/share/texlive/texmf-dist/tex/latex/caption/caption3.sty\n(/usr/share/texlive/texmf-dist/tex/latex/graphics/keyval.sty))\n\nPackage caption Warning: Unsupported document class (or package) detected,\n(caption)                usage of the caption package is not recommended.\nSee the caption package documentation for explanation.\n\n) (/usr/share/texlive/texmf-dist/tex/latex/float/float.sty) (./scipy.sty\n(./status.sty (./draftwatermark.sty (./everypage.sty)\n(/usr/share/texlive/texmf-dist/tex/latex/graphics/graphicx.sty\n(/usr/share/texlive/texmf-dist/tex/latex/graphics/graphics.sty\n(/usr/share/texlive/texmf-dist/tex/latex/graphics/trig.sty)\n(/usr/share/texlive/texmf-dist/tex/latex/graphics-cfg/graphics.cfg)))))\n(/usr/share/texlive/texmf-dist/tex/latex/psnfss/mathptmx.sty)\n(/usr/share/texlive/texmf-dist/tex/latex/psnfss/helvet.sty)\n(/usr/share/texlive/texmf-dist/tex/latex/psnfss/courier.sty)\n(/usr/share/texlive/texmf-dist/tex/latex/amsfonts/amsfonts.sty)\n(/usr/share/texlive/texmf-dist/tex/latex/amsfonts/amssymb.sty)\n(/usr/share/texlive/texmf-dist/tex/latex/tools/bm.sty)\n(/usr/share/texlive/texmf-dist/tex/latex/hyperref/hyperref.sty\n(/usr/share/texlive/texmf-dist/tex/generic/oberdiek/hobsub-hyperref.sty\n(/usr/share/texlive/texmf-dist/tex/generic/oberdiek/hobsub-generic.sty))\n(/usr/share/texlive/texmf-dist/tex/generic/ifxetex/ifxetex.sty)\n(/usr/share/texlive/texmf-dist/tex/latex/oberdiek/auxhook.sty)\n(/usr/share/texlive/texmf-dist/tex/latex/oberdiek/kvoptions.sty)\n(/usr/share/texlive/texmf-dist/tex/latex/hyperref/pd1enc.def)\n(/usr/share/texlive/texmf-dist/tex/latex/latexconfig/hyperref.cfg)\n(/usr/share/texlive/texmf-dist/tex/latex/url/url.sty))\n(/usr/share/texlive/texmf-dist/tex/latex/hyperref/hpdftex.def\n(/usr/share/texlive/texmf-dist/tex/latex/oberdiek/rerunfilecheck.sty))\n\nPackage hyperref Warning: Option `pdftex' has already been used,\n(hyperref)                setting the option has no effect on input line 43.\n\n(/usr/share/texlive/texmf-dist/tex/latex/tools/longtable.sty)\n(/usr/share/texlive/texmf-dist/tex/latex/multirow/multirow.sty)\n(/usr/share/texlive/texmf-dist/tex/latex/booktabs/booktabs.sty)\n(/usr/share/texlive/texmf-dist/tex/latex/base/textcomp.sty\n(/usr/share/texlive/texmf-dist/tex/latex/base/ts1enc.def\n(/usr/share/texlive/texmf-dist/tex/latex/base/ts1enc.dfu)))\n(/usr/share/texlive/texmf-dist/tex/latex/upquote/upquote.sty)\n(/usr/share/texlive/texmf-dist/tex/latex/fancyvrb/fancyvrb.sty\nStyle option: `fancyvrb' v2.7a, with DG/SPQR fixes, and firstline=lastline fix \n<2008/02/07> (tvz))) (./paper.aux)\n(/usr/share/texlive/texmf-dist/tex/latex/base/ts1cmr.fd)\n(/usr/share/texlive/texmf-dist/tex/latex/psnfss/t1ptm.fd)\n-- Lines per column: 61 (exact).\n(/usr/share/texlive/texmf-dist/tex/context/base/mkii/supp-pdf.mkii\n[Loading MPS to PDF converter (version 2006.09.02).]\n) (/usr/share/texlive/texmf-dist/tex/latex/oberdiek/epstopdf-base.sty\n(/usr/share/texlive/texmf-dist/tex/latex/oberdiek/grfext.sty)\n(/usr/share/texlive/texmf-dist/tex/latex/latexconfig/epstopdf-sys.cfg))\n(/usr/share/texlive/texmf-dist/tex/latex/captio [...]

2022-06-24 22:46 UTC, stargaser commented
Hi @govarguz and @willymenacho, thank you for your revised version. The paper is not building after the last commit. Would you please look into it?

2022-06-26 16:25 UTC, govarguz commented
Hi @stargaser, Hi @deniederhut, 
@willymenacho and myself had a look at it and now the .rst file compiles finely. We hope this is ready now for publication in the scipy proceedings 2022.

2022-06-30 15:33 UTC, stargaser commented
@scoobies check references

2022-06-30 15:34 UTC, scoobies commented
```
Reference check summary (note 'MISSING' DOIs are suggestions that need verification):

OK DOIs

- 10.1063/1.2938864 is OK
- 10.3762/bjnano.6.36 is OK
- 10.1063/1.2136418 is OK
- 10.1063/1.368002 is OK
- 10.1038/s41592-019-0686-2 is OK
- 10.1039/d0cs00318b is OK
- 10.3762/bjnano.8.98 is OK
- 10.1002/smll.201101247 is OK
- 10.1557/PROC-1185-II07-10 is OK
- 10.3762/bjnano.4.96 is OK
- 10.1021/nn4012835 is OK
- 10.1016/j.cpc.2018.12.017 is OK
- 10.1145/2038037.1941562 is OK

MISSING DOIs

- 10.25080/majora-342d178e-005 may be a valid DOI for title: Compyle: a Python package for parallel computing

INVALID DOIs

- None
```

2022-06-30 15:39 UTC, stargaser commented
@govarguz would you mind adding the one missing DOI for Compyle in the comment above this one?

2022-07-06 11:10 UTC, deniederhut commented
@stargaser is this paper now ready?

2022-07-06 16:17 UTC, stargaser commented
@scoobies mark ready

2022-07-09 00:41 UTC, deniederhut requested changes
@govarguz it looks like there are a lot of intermediate build system files that have made it into your PR somehow. Would you mind removing the following?

- paper.aux
- paper.bbl
- paper.blg
- paper.log
- paper.out
- paper.pdf
- paper_stats.json
- scipy.sty
- status.sty

2022-07-09 00:41 UTC, deniederhut commented
@scoobies mark pending comment

2022-07-10 21:37 UTC, deniederhut commented
Thanks! I'm still seeing paper.log and paper.tex -- could we remove those?

2022-07-11 13:03 UTC, deniederhut approved these changes
Thanks!

2022-07-11 13:03 UTC, deniederhut commented
@scoobies mark ready

2022-07-11 13:12 UTC, merged