Paper: Search for Extraterrestrial Intelligence: GPU Accelerated E.T. Search with TurboSETI
scipy-conference/scipy_proceedings pull request #722
Opened 2022-05-28 06:59 UTC by luigifcruz

If you are creating this PR in order to submit a draft of your paper,
see http://procbuild.scipy.org/ for logs generated by the build
process.

See the [project readme](https://github.com/scipy-conference/scipy_proceedings#build-your-paper)
for more information.

*Editor*:  

*Reviewers*:

2022-05-28 06:59 UTC, scoobies commented
Hi!, I'm @scoobies, a friendly bot.

Type ```@scoobies help``` to discover how I can help you.

2022-05-29 21:14 UTC, deniederhut commented
@scoobies mark paper

2022-05-29 21:15 UTC, deniederhut commented
@scoobies build status

2022-05-29 21:15 UTC, scoobies commented
{"luigifcruz-2022_lfc"=>{"data"=>{"build_output"=>"[*] Updating proceedings build tools in {self.master_repo_path}...\nAlready up to date.\n[*] Check out paper repository...\nCloning into '/tmp/tmpxeg8q024'...\nMoving proceedings build tools to temp directory...\n[*] Build the paper...\nBuilding: Luigi_Cruz\n*** Warning: /tmp/tmpxeg8q024/publisher/../output/Luigi_Cruz/paper_stats.json does not exist.\n", "build_pdf_path"=>"/procbuild/procbuild/../cache/luigifcruz-2022_lfc.pdf", "build_status"=>"success", "build_timestamp"=>"29/05 02:05"}, "status"=>"success"}}

2022-05-29 21:15 UTC, deniederhut commented
@scoobies mark needs review

2022-05-29 21:15 UTC, deniederhut commented
@scoobies assign @cbcunc as editor

2022-05-29 21:15 UTC, scoobies commented
Assigned! @cbcunc is now the editor

2022-06-01 23:55 UTC, cbcunc commented
Editor confirms paper builds.

2022-06-03 13:02 UTC, deniederhut commented
@scoobies add @m-maciejewski to reviewers

2022-06-03 13:02 UTC, scoobies commented
@m-maciejewski added to the reviewers list!

2022-06-07 03:09 UTC, deniederhut commented
Hi! We've moved the deadline for first reviews back one week, to June 16th, to give us a little more time to find reviewers for all the papers this year. You can see the updated full timeline at https://github.com/scipy-conference/scipy_proceedings#timeline-for-2022.

2022-06-13 23:40 UTC, cbcunc commented
@m-maciejewski First review is due June 16.

2022-06-16 12:18 UTC, m-maciejewski commented
@cbcunc I'm on it!

2022-06-16 15:10 UTC, m-maciejewski commented
Overall, a well-written abstract. Please take a look at the suggested comments. I'm open for discussing them in detail. I do hope, the review would improve the abstract!

2022-06-16 23:16 UTC, deniederhut commented
@m-maciejewski I'm not seeing any inline comments -- did you click the "submit review" button?

2022-06-17 07:42 UTC, m-maciejewski commented
@deniederhut You can see all my comments in this thread with `Pending` status. Alternatively, they are all available here: https://github.com/scipy-conference/scipy_proceedings/pull/722/files

2022-06-17 17:04 UTC, luigifcruz commented
Hi, @m-maciejewski! Thanks for reviewing our paper. We can't see your comments, I think you need to submit them for us to be able to see them.

2022-06-17 21:31 UTC, m-maciejewski commented
@luigifcruz what do you mean by submitting? Here is a pdf of this website, where you can immediately see my comments; please just scroll up this page
[review.pdf](https://github.com/scipy-conference/scipy_proceedings/files/8931400/review.pdf)
.

2022-06-17 21:37 UTC, luigifcruz commented
Hey @m-maciejewski! Yes, these comments are private to you. You need to submit the review to make it available to others. 

> Before you submit your review, your line comments are pending and only visible to you. You can edit pending comments anytime before you submit your review. To cancel a pending review, including all of its pending comments, scroll down to the end of the timeline on the Conversation tab, then click Cancel review.

You can find the documentation regarding this GitHub feature [here](https://docs.github.com/en/enterprise-server@3.1/pull-requests/collaborating-with-pull-requests/reviewing-changes-in-pull-requests/reviewing-proposed-changes-in-a-pull-request).

2022-06-18 02:14 UTC, deniederhut commented
Yup so @m-maciejewski  right now your comments look like this:

<img width="1087" alt="Screen Shot 2022-06-17 at 9 12 18 PM" src="https://user-images.githubusercontent.com/6868396/174418627-6c1ccfde-59a8-4417-9943-f8c5754e9e9d.png">

you'll need to click Finish Review, then Submit Review, which looks like this

<img width="1091" alt="Screen Shot 2022-06-17 at 9 13 00 PM" src="https://user-images.githubusercontent.com/6868396/174418649-31272a9f-8cb5-4288-87ea-f03740001620.png">

Let us know if you need any help!

2022-06-20 13:50 UTC, m-maciejewski commented on papers/Luigi_Cruz/paper.rst
> +Search for Extraterrestrial Intelligence: GPU Accelerated E.T. Search with TurboSETI
I'd suggest to expand the E.T. abbreviation as it might not be clear for the broader audience. Once the abbreviation is expanded, the title seems to repeat itself. How about: "GPU Accelerated Search for Extraterrestrial Intelligence with TurboSETI Package"?

2022-06-20 13:50 UTC, m-maciejewski commented on papers/Luigi_Cruz/paper.rst
> +A common technique adopted by the SETI community is monitoring electromagnetic radiation for signs of extraterrestrial technosignatures using ground-based radio observatories.
Please spell-out SETI as it appears for the first time.

2022-06-20 13:50 UTC, m-maciejewski commented on papers/Luigi_Cruz/paper.rst
> +A common technique adopted by the SETI community is monitoring electromagnetic radiation for signs of extraterrestrial technosignatures using ground-based radio observatories.
Does E.T. stand for "extraterrestrial technosignatures"?

2022-06-20 13:50 UTC, m-maciejewski commented on papers/Luigi_Cruz/paper.rst
> +Our goal was to improve the processing speeds by writing a GPU-accelerated backend in addition to the original CPU-based implementation of the de-doppler algorithm.
Please consider adding a sentence explaining why would one need the de-doppler algorithm

2022-06-20 13:50 UTC, m-maciejewski commented on papers/Luigi_Cruz/paper.rst
> +This search can be performed in equipment primarily built for this task, like the Allen Telescope Array (California, USA), renting observation time, or in the background while the primary user is con
Please split this sentence in two as it is hard to read in one go. E.g.,
This search can be performed in equipment primarily built for this task, like the Allen Telescope Array (California, USA).
The study is carried out either by renting observation time, or in the background while the primary user is conducting other observations.

2022-06-20 13:50 UTC, m-maciejewski commented on papers/Luigi_Cruz/paper.rst
> +Instead of using optics to concentrate light into an optical sensor, a radio-telescope operates by concentrating electromagnetic waves into an antenna using a large reflective structure called a “dis
Could you provide a reference to a "dish"?

2022-06-20 13:50 UTC, m-maciejewski commented on papers/Luigi_Cruz/paper.rst
> +This effect is then quantized by an analog-to-digital converter as RAW voltages and transmitted to a processing logic to extract useful information from it.
What do you mean by RAW voltage?

2022-06-20 13:50 UTC, m-maciejewski commented on papers/Luigi_Cruz/paper.rst
> +The data stream generated by a radio telescope can easily reach the rate of terabits per second.
What is the reaseon for data rate in the order of terabits per second? Explaining that would help the reader in diving deeper into your work.

2022-06-20 13:50 UTC, m-maciejewski commented on papers/Luigi_Cruz/paper.rst
> +To measure a potential signal's drift rate, TurboSETI uses a de-doppler algorithm to align the frequency axis according to a pre-set drift rate. Another algorithm called “hitsearch” is then utilized
Do you have a reference to the "hitsearch"?

2022-06-20 13:50 UTC, m-maciejewski commented on papers/Luigi_Cruz/paper.rst
> +Although being an offline operation, the processing speed of TurboSETI is in lockstep with the amount of science we can extract from each observation. Each filterbank file ingested by TurboSETI is of
Please try to avoid using jargon. I'd argue that one can't extract science from anything as it stands on its own ;-)
Instead, you may extract a meaningful insight, relevant information, etc.

2022-06-20 13:50 UTC, m-maciejewski commented on papers/Luigi_Cruz/paper.rst
> +Multiple methods were utilized in this effort to write a GPU-accelerated backend and optimize the CPU implementation of TurboSETI. In this section, we enumerate them.
Multiple methods -> Three, seperate approaches/methods were utilized

2022-06-20 13:50 UTC, m-maciejewski commented on papers/Luigi_Cruz/paper.rst
> +Although being an offline operation, the processing speed of TurboSETI is in lockstep with the amount of science we can extract from each observation. Each filterbank file ingested by TurboSETI is of
What do you mean by "near machine-level performance"?

2022-06-20 13:50 UTC, m-maciejewski commented on papers/Luigi_Cruz/paper.rst
> +This enabled us to share most of the code between the CPU and GPU-based implementations.
reuse most of the code?

2022-06-20 13:50 UTC, m-maciejewski commented on papers/Luigi_Cruz/paper.rst
> +By leveraging the power of LLVM’s Just-In-Time compiler, Numba can compile Python code into assembly code as well as apply SIMD acceleration instructions to achieve near machine-level speeds.
Please spell out the abbreviations

2022-06-20 13:50 UTC, m-maciejewski commented on papers/Luigi_Cruz/paper.rst
> +The original implementation of the software handled the input data as double-precision floating-point numbers. This behavior would cause all the mathematical operations to take significantly longer t
added precision - augmented/extended precision

2022-06-20 13:50 UTC, m-maciejewski commented on papers/Luigi_Cruz/paper.rst
> +Table :ref:`table:double-precision` indicates the processing times it took to process three different files in double-precision mode.
Please mention that the double-precision mode on CPU is your reference.

2022-06-20 13:50 UTC, m-maciejewski commented on papers/Luigi_Cruz/paper.rst
> +    | Double-Precision (float64)                                |
Single-Precision?

2022-06-20 13:50 UTC, m-maciejewski commented on papers/Luigi_Cruz/paper.rst
> +4. Conclusion
Please add  a comment on the outcome of your benchmark. What would be the recommended setup?

2022-06-20 13:51 UTC, m-maciejewski commented
I'm sorry for not submitting the review. I work daily on GitLab where this feature works differntly.

2022-06-21 14:12 UTC, deniederhut commented
No worries! Glad we got it figured out

2022-06-24 01:41 UTC, deniederhut commented
@scoobies mark pending comment

2022-06-24 20:30 UTC, cbcunc requested changes

2022-06-24 20:30 UTC, cbcunc commented on papers/Luigi_Cruz/reference.bib
> +@inproceedings{cupy_learningsys2017,
Needs a DOI (proceeding DOI will do).

2022-06-24 20:30 UTC, cbcunc commented on papers/Luigi_Cruz/reference.bib
> +‌@article{enriquez_2019,
Needs DOI.

2022-06-27 04:40 UTC, deniederhut commented
Hi @luigifcruz ! Have you had a chance to respond to the reviewers comments?

2022-06-27 23:31 UTC, luigifcruz commented on papers/Luigi_Cruz/reference.bib
> +‌@article{enriquez_2019,
Added on c1b642d0422e3f864c5c5036cb24daa1b3b5bb9d. Thanks!

2022-06-27 23:32 UTC, luigifcruz commented on papers/Luigi_Cruz/reference.bib
> +@inproceedings{cupy_learningsys2017,
I couldn't find the DOI of this publication. Their repository ([CITATIONS.md](https://github.com/kmaehashi/cupy/blob/master/CITATION.bib)) also doesn't have a DOI.

2022-06-28 00:20 UTC, luigifcruz commented
Thanks for the comments! I just pushed a new commit addressing the comments made by @cbcunc and @m-maciejewski. I hope the paper is now more informative.

2022-06-29 00:51 UTC, deniederhut commented
Awesome! @m-maciejewski do you feel this paper is now ready for inclusion in the proceedings?

2022-06-29 19:13 UTC, cbcunc commented
Reviewers, please give your final recommendations. The deadline for final review comments is tomorrow.

Authors, please respond to review comments with changes or comments which resolve the conversation. Final acceptance decisions are July 4.

2022-06-29 19:35 UTC, m-maciejewski commented on papers/Luigi_Cruz/paper.rst
> +Although being an offline operation, the processing speed of TurboSETI is in lockstep with the amount of science we can extract from each observation. Each voltage file ingested by TurboSETI is often
"amount of science we can extract from each observation" does not read well. Please use a more appropriate phrase.

2022-06-29 19:36 UTC, m-maciejewski commented
Dear authors, 
thank you for considering the comments.
I've just suggested a one tiny comment. Otherwise, the text reads very well - one can easily follow from one sentence to another. Well done!

2022-06-30 00:24 UTC, luigifcruz commented on papers/Luigi_Cruz/paper.rst
> +Although being an offline operation, the processing speed of TurboSETI is in lockstep with the amount of science we can extract from each observation. Each voltage file ingested by TurboSETI is often
Thanks for the comment. I rewrote the phrase using clearer language.

2022-07-01 22:03 UTC, cbcunc approved these changes

2022-07-01 22:03 UTC, cbcunc commented
@scoobies mark ready

2022-07-06 12:22 UTC, merged