[wip] Paper: Scikit-HEP
scipy-conference/scipy_proceedings pull request #726
Opened 2022-05-28 16:15 UTC by henryiii

If you are creating this PR in order to submit a draft of your paper,
see http://procbuild.scipy.org/ for logs generated by the build
process.

See the [project readme](https://github.com/scipy-conference/scipy_proceedings#build-your-paper)
for more information.

*Editor*:  

*Reviewers*:  

First draft. Tagging @jpivarski & @eduardo-rodrigues.

2022-05-28 16:15 UTC, scoobies commented
Hi!, I'm @scoobies, a friendly bot.

Type ```@scoobies help``` to discover how I can help you.

2022-05-28 22:40 UTC, eduardo-rodrigues commented
Hi @henryiii, thank you for tagging me. Time is really short and I have been largely offline after back-to-back trips. I also got a link to a reST file in your personal repo. I guess this one MR is the one we should now focus on?

2022-05-28 22:42 UTC, eduardo-rodrigues commented on papers/henry_schreiner/mybib.bib
> +    journal = "EPJ Web Conf.",
```suggestion
    journal = {EPJ Web of Conferences},
```

2022-05-28 22:43 UTC, eduardo-rodrigues commented on papers/henry_schreiner/henry_schreiner.rst
> +   packaging, ecosystem, high energy physics
I would add "community project" as that is key to us.

2022-05-28 22:45 UTC, eduardo-rodrigues commented on papers/henry_schreiner/henry_schreiner.rst
> +the largest machine in the world at CERN, the Large Hadron Collider (LHC), 27
```suggestion
the largest machine in the world, at CERN, the Large Hadron Collider (LHC), 27
```

2022-05-28 22:47 UTC, eduardo-rodrigues commented on papers/henry_schreiner/henry_schreiner.rst
> +project was released, making C++ the main language for HEP.  The ROOT project
```suggestion
project was released, making C++ the main language for HEP.  The ROOT project for an analysis toolkit (and framework)
```

2022-05-28 22:48 UTC, eduardo-rodrigues commented on papers/henry_schreiner/henry_schreiner.rst
> +project was released, making C++ the main language for HEP.  The ROOT project
```suggestion
project for an analysis toolkit (and framework) was released, making C++ the main language for HEP.  The ROOT project
```

2022-05-28 22:49 UTC, eduardo-rodrigues commented on papers/henry_schreiner/henry_schreiner.rst
> +also needed an "extension" languages; this is the language driving the
```suggestion
also needed an "extension language" - this is the language driving the
```

2022-05-28 22:49 UTC, eduardo-rodrigues commented on papers/henry_schreiner/henry_schreiner.rst
> +it was considered too much to ask Physicists to code in two language. Instead,
```suggestion
it was considered too much to ask Physicists to code in two languages. Instead,
```

2022-05-28 22:50 UTC, eduardo-rodrigues commented on papers/henry_schreiner/henry_schreiner.rst
> +using Python + Numba model instead, like Xenon1T :cite:`remenska2017giving,rousselle2021fast`.
```suggestion
using Python + Numba as an alternative, enhanced, model, like Xenon1T :cite:`remenska2017giving,rousselle2021fast`.
```

2022-05-28 22:51 UTC, eduardo-rodrigues commented on papers/henry_schreiner/henry_schreiner.rst
> +.. [#] Almost 20 years later ROOT's Python bindigns have been rewritten for
```suggestion
.. [#] Almost 20 years later ROOT's Python bindings have been rewritten for
```

2022-05-28 22:53 UTC, eduardo-rodrigues commented on papers/henry_schreiner/henry_schreiner.rst
> +   The Scikit-HEP ecosystem and affilated packages.
```suggestion
   The Scikit-HEP ecosystem and affiliated packages.
```

2022-05-28 22:55 UTC, eduardo-rodrigues commented on papers/henry_schreiner/henry_schreiner.rst
> +several rather popular packages that were useful in HEP spread around among
```suggestion
a handful of popular packages that were useful in HEP spread around among
```

2022-05-28 22:56 UTC, eduardo-rodrigues commented on papers/henry_schreiner/henry_schreiner.rst
> +different authors. ROOTPy had several packages that made the ROOT-Python bridge
```suggestion
different authors. The rootpy project had several packages that made the ROOT-Python bridge
```

2022-05-28 22:56 UTC, eduardo-rodrigues commented on papers/henry_schreiner/henry_schreiner.rst
> +a little easier, such as ``root-numpy`` and ``root-pandas`` packages. The
```suggestion
a little easier, such as the ``root-numpy`` and related ``root-pandas`` packages. The
```

2022-05-28 22:57 UTC, eduardo-rodrigues commented on papers/henry_schreiner/henry_schreiner.rst
> +MINUIT fitting library was integrated into ROOT, but the ``iminuit`` package :cite:`iminuit`
```suggestion
C++ MINUIT fitting library was integrated into ROOT, but the ``iminuit`` package :cite:`iminuit`
```

2022-05-28 22:58 UTC, eduardo-rodrigues commented on papers/henry_schreiner/henry_schreiner.rst
> +MINUIT fitting library was integrated into ROOT, but the ``iminuit`` package :cite:`iminuit`
Add the usual reference to MINUIT, see the paper at https://github.com/scikit-hep/iminuit/blob/develop/CITATION.rst? Seems best.

2022-05-28 22:59 UTC, eduardo-rodrigues commented on papers/henry_schreiner/henry_schreiner.rst
> +unit conversions, several useful statistical tools, and province recording
```suggestion
unit conversions, several useful statistical tools, and provenance recording
```

2022-05-28 23:07 UTC, eduardo-rodrigues commented on papers/henry_schreiner/henry_schreiner.rst
> +then-popular packages that were included in the ROOTPy org were happily
```suggestion
then-popular packages that were included in the rootpy organization were happily
```

2022-05-28 23:09 UTC, eduardo-rodrigues commented on papers/henry_schreiner/henry_schreiner.rst
> +for it's classes, like vectors. The other was AwkwardArray, which would grow to
```suggestion
for its classes, like vectors. The other was AwkwardArray, which would grow to
```

2022-05-28 23:10 UTC, eduardo-rodrigues commented on papers/henry_schreiner/henry_schreiner.rst
> +to jagged data structures. These are common in HEP; events have a variable
```suggestion
to jagged data structures. These are very common and relevant in HEP; events have a variable
```

2022-05-28 23:11 UTC, eduardo-rodrigues commented on papers/henry_schreiner/henry_schreiner.rst
> +it provides solutions that work natively in the Python ecosystem, which in this
```suggestion
it provides alternative solutions that work natively in the Python "Big Data" ecosystem, which in this
```

2022-05-28 23:13 UTC, eduardo-rodrigues commented on papers/henry_schreiner/henry_schreiner.rst
> +quickly expanded to include tools to read and validate "DEC" decay files, an
```suggestion
quickly expanded to include tools to read and validate "DEC" decay files, an
```

2022-05-28 23:14 UTC, eduardo-rodrigues commented on papers/henry_schreiner/henry_schreiner.rst
> +existing format.
```suggestion
existing text format used to configure simulations in HEP.
```

2022-05-28 23:15 UTC, eduardo-rodrigues commented on papers/henry_schreiner/henry_schreiner.rst
> +Several other useful HEP libraries were also written. Particle for accessing
```suggestion
Several other useful HEP libraries were also written.For example: Particle for accessing
```

2022-05-28 23:15 UTC, eduardo-rodrigues commented on papers/henry_schreiner/henry_schreiner.rst
> +   From the Analysis Ecosystem II Workshop.
```suggestion
   From the HEP Software Foundation Analysis Ecosystems II Workshop, May 2022.
```

2022-05-28 23:16 UTC, eduardo-rodrigues commented on papers/henry_schreiner/henry_schreiner.rst
> +In 2018, HEP physicist and programmer Hans Dembenski proposed a histogram
```suggestion
In 2018, HEP physicist and programmer Hans Dembinski proposed a histogram
```

2022-05-28 23:16 UTC, eduardo-rodrigues commented on papers/henry_schreiner/henry_schreiner.rst
> +projects such as this.
```suggestion
project packages such as this one.
```

2022-05-28 23:17 UTC, eduardo-rodrigues commented on papers/henry_schreiner/henry_schreiner.rst
> +them filled the requirements of HEP physicists, and most of them were not easy
```suggestion
them filled the requirements of HEP physicists fully, and most of them were not easy
```

2022-05-28 23:19 UTC, eduardo-rodrigues commented on papers/henry_schreiner/henry_schreiner.rst
> +packages over (mis)-using Cython for bindings; reduced maintenance, simpler
```suggestion
packages over (mis)-using Cython for bindings: reduced maintenance, simpler
```

2022-05-28 23:19 UTC, eduardo-rodrigues commented on papers/henry_schreiner/henry_schreiner.rst
> +the Scikit-HEP recommended binding tool. Scikit-HEP developers contributed a
```suggestion
the Scikit-HEP recommended binding tool. Scikit-HEP developers, notably Henry Schreiner, contributed a
```

2022-05-28 23:20 UTC, eduardo-rodrigues commented on papers/henry_schreiner/henry_schreiner.rst
> +complete CI redesign based on GitHub Actions, with over 70 jobs and expanded
```suggestion
complete CI redesign based on GitHub Actions, with over 70 jobs, and expanded
```

2022-05-28 23:22 UTC, eduardo-rodrigues commented on papers/henry_schreiner/henry_schreiner.rst
> +Scikit-HEP was becoming a "toolset", a collection of packages that worked together
```suggestion
Scikit-HEP had become a reasonably popular "toolset" for HEP analysis in Python, a collection of packages that worked together,
```

2022-05-28 23:23 UTC, eduardo-rodrigues commented on papers/henry_schreiner/henry_schreiner.rst
> +libraries for an physicist starting a new analysis.
```suggestion
libraries for a physicist starting a new analysis.
```

2022-05-28 23:24 UTC, eduardo-rodrigues commented on papers/henry_schreiner/henry_schreiner.rst
> +(see Fig. :ref:`fig-shells`).  Several other projects joined Scikit-HEP, like
```suggestion
(see Fig. :ref:`fig-shells`).  Several other projects or packages joined Scikit-HEP, like
```

2022-05-28 23:25 UTC, eduardo-rodrigues commented on papers/henry_schreiner/henry_schreiner.rst
> +iMinuit, a popular HEP and astrophysics fitting library, was probably the most
```suggestion
iMinuit, a popular HEP and astrophysics fitting library, probably the most
```

2022-05-28 23:25 UTC, eduardo-rodrigues commented on papers/henry_schreiner/henry_schreiner.rst
> +popular single package to join. PyHF and cabinetry also joined; these were
```suggestion
popular single package to have joined. PyHF and cabinetry also joined; these were
```

2022-05-28 23:28 UTC, eduardo-rodrigues commented on papers/henry_schreiner/henry_schreiner.rst
> +particular need, Scikit-HEP doesn't have to attempt to develop a package, but
```suggestion
particular need for the community. Scikit-HEP doesn't have to, or need to, attempt to develop a package that others are providing, but rather tries to ensure that the externally provided package
```

2022-05-28 23:29 UTC, eduardo-rodrigues commented on papers/henry_schreiner/henry_schreiner.rst
> +can just use the external one.
```suggestion
works well with the broader HEP ecosystem.
```

2022-05-28 23:29 UTC, eduardo-rodrigues commented on papers/henry_schreiner/henry_schreiner.rst
> +Scikit-HEP continued to grow with new packages as well. Vector manipulation,
```suggestion
Scikit-HEP continues to grow with new packages: for example, vector manipulation,
```

2022-05-28 23:30 UTC, eduardo-rodrigues commented on papers/henry_schreiner/henry_schreiner.rst
> +Histogramming was designed to be a collection of specialized packages
Need to put this in the same paragraph? Otherwise it does not overall read well.

2022-05-28 23:31 UTC, eduardo-rodrigues commented on papers/henry_schreiner/henry_schreiner.rst
> +One example of a package pulling together many components was
```suggestion
One example of a package pulling together many components is
```

2022-05-28 23:32 UTC, eduardo-rodrigues commented on papers/henry_schreiner/henry_schreiner.rst
> +``uproot-browswer``, a tool that combined uproot, hist, and Python libraries
```suggestion
``uproot-browser``, a tool that combines uproot, Hist, and Python libraries
```

2022-05-28 23:32 UTC, eduardo-rodrigues commented on papers/henry_schreiner/henry_schreiner.rst
> +The Scikit-HEP project started in 2016 and has grown to be a core component in
```suggestion
The Scikit-HEP project started in Autumn 2016 and has grown to be a core component in
```

2022-05-28 23:33 UTC, eduardo-rodrigues reviewed
Great effort! I left a few little suggestions. Hope that helps.
Am calling it a day - rather late over here.

2022-05-29 03:04 UTC, henryiii commented on papers/henry_schreiner/mybib.bib
> +    journal = "EPJ Web Conf.",
FYI, copied directly from https://scikit-hep.org/citing. :)

2022-05-29 03:05 UTC, henryiii commented on papers/henry_schreiner/henry_schreiner.rst
> +   packaging, ecosystem, high energy physics
This was copied from the submission, not sure if it needs to match.

2022-05-29 03:06 UTC, henryiii commented on papers/henry_schreiner/henry_schreiner.rst
> +the largest machine in the world at CERN, the Large Hadron Collider (LHC), 27
```suggestion
the largest machine in the world at CERN: the Large Hadron Collider (LHC), 27
```

2022-05-29 07:56 UTC, eduardo-rodrigues commented on papers/henry_schreiner/mybib.bib
> +    journal = "EPJ Web Conf.",
I know, one can find both writings. I made the change for consistency with the other 2 EPJ citations in the document, since consistency is important.

2022-05-29 07:57 UTC, eduardo-rodrigues commented on papers/henry_schreiner/henry_schreiner.rst
> +the largest machine in the world at CERN, the Large Hadron Collider (LHC), 27
Fine with me :).

2022-05-29 07:58 UTC, eduardo-rodrigues commented on papers/henry_schreiner/henry_schreiner.rst
> +   packaging, ecosystem, high energy physics
I would imagine we can update keywords, but OK also if you want to play it the safest.

2022-05-29 21:25 UTC, deniederhut commented
@scoobies mark paper

2022-05-29 21:27 UTC, deniederhut commented
@scoobies build paper

2022-05-29 21:27 UTC, scoobies commented
building paper...

2022-05-29 21:27 UTC, scoobies commented
{"data"=>{"info"=>"Build for paper henryiii-henry_schreiner_2022 scheduled.  Note that builds are only executed if the current build attempt is more than 5 minutes old."}, "status"=>"success"}

2022-05-29 21:30 UTC, deniederhut commented
@scoobies build status

2022-05-29 21:30 UTC, scoobies commented
{"henryiii-henry_schreiner_2022"=>{"data"=>{"build_output"=>"[*] Updating proceedings build tools in {self.master_repo_path}...\nAlready up to date.\n[*] Check out paper repository...\nCloning into '/tmp/tmp71f2sssg'...\nMoving proceedings build tools to temp directory...\n[*] Build the paper...\nBuilding: henry_schreiner\n*** Warning: /tmp/tmp71f2sssg/publisher/../output/henry_schreiner/paper_stats.json does not exist.\n", "build_pdf_path"=>"/procbuild/procbuild/../cache/henryiii-henry_schreiner_2022.pdf", "build_status"=>"success", "build_timestamp"=>"29/05 21:27"}, "status"=>"success"}}

2022-05-29 21:30 UTC, deniederhut commented
@scoobies mark needs review

2022-05-29 21:30 UTC, deniederhut commented
@scoobies assign @cbcunc as editor

2022-05-29 21:30 UTC, scoobies commented
Assigned! @cbcunc is now the editor

2022-06-01 23:52 UTC, cbcunc commented
@scoobies help

2022-06-01 23:52 UTC, scoobies commented
Hello @cbcunc, here are the things you can ask me to do:

```

# List all available commands
@scoobies help

# Show our community Code of Conduct and Guidelines
@scoobies code of conduct

# Add to this issue's reviewers list
@scoobies add @username to reviewers

# Remove from this issue's reviewers list
@scoobies remove @username from reviewers

# Assign a user as the editor of this submission
@scoobies assign @username as editor

# Remove the editor assigned to this submission
@scoobies remove editor

# Add a user to this issue's assignees list
@scoobies add assignee: @username

# Remove a user from this issue's assignees list
@scoobies remove assignee: @username

# Builds paper
@scoobies build paper

# Checks build status
@scoobies build status

# Check the references of the paper for missing DOIs
# Optionally, it can be run on a non-default branch 
@scoobies check references
@scoobies check references from custom-branch-name

# Label issue with: paper
@scoobies mark paper

# Label issue with: needs-review. Remove labels: unready, needs-more-review, pending-comment, ready
@scoobies mark needs review

# Label issue with: needs-more-review. Remove labels: unready, needs-review, pending-comment, ready
@scoobies mark needs more review

# Label issue with: pending-comment. Remove labels: unready, needs-review, needs-more-review, ready
@scoobies mark pending comment

# Label issue with: ready. Remove labels: unready, needs-review, needs-more-review, pending-comment
@scoobies mark ready

# Label issue with: unready. Remove labels: needs-review, needs-more-review, pending-comment, ready
@scoobies mark not ready

# Label issue with: does_not_build:server
@scoobies mark server fail

# Remove labels: does_not_build:server
@scoobies mark server success

```

2022-06-01 23:54 UTC, cbcunc commented
Editor confirms paper builds.

2022-06-07 03:10 UTC, deniederhut commented
Hi! We've moved the deadline for first reviews back one week, to June 16th, to give us a little more time to find reviewers for all the papers this year. You can see the updated full timeline at https://github.com/scipy-conference/scipy_proceedings#timeline-for-2022.

2022-06-10 17:22 UTC, deniederhut commented
@scoobies add @gcdeshpande to reviewers

2022-06-10 17:22 UTC, scoobies commented
@gcdeshpande added to the reviewers list!

2022-06-13 23:36 UTC, cbcunc commented
@scoobies add @gcdeshpande to reviewers

2022-06-13 23:37 UTC, scoobies commented
@gcdeshpande is already included in the reviewers list

2022-06-13 23:39 UTC, cbcunc commented
@gcdeshpande First review is due June 16.

2022-06-16 03:19 UTC, gcdeshpande commented
Dear @henryiii, I read the paper. The paper is very well written. I see that the paper has an analysis of only histograms. There are other aspects also such as modeling and simulation. I think the paper focuses on histogram libraries in the SciKit HEP ecosystem.

2022-06-19 22:15 UTC, deniederhut commented
@gcdeshpande typically reviewers leave some feedback and suggestions on how the paper might improve readability, avoid use of jargon, etc. You can see a full list of the review criteria here: https://github.com/scipy-conference/scipy_proceedings/blob/master/review_criteria.md. Is there anything else you would like to add to this review?

2022-06-24 20:26 UTC, cbcunc requested changes
All citations require DOI numbers per Proceeding Committee.

2022-06-28 11:08 UTC, deniederhut commented
Howdy! I haven't been able to get a hold of Gajendra over email, so I'll be stepping in to finish the review.  Sorry for the delay.

2022-06-28 11:08 UTC, deniederhut commented
@scoobies add @deniederhut to reviewers

2022-06-28 11:08 UTC, scoobies commented
@deniederhut added to the reviewers list!

2022-06-28 13:08 UTC, deniederhut reviewed
I'll need to come back to this review later -- sorry I couldn't knock it all out this morning! 

I've left some inline comments, but overall so far my impressions are that this paper could be improved with a clear audience, goal, and evidence. Who do you expect to read this ten years from now? What do you want them to learn? What evidence do you need to support that? "The use of Python exploded" is a view -- it is not evidence in favor of that view.

Also, I was really surprised to see you mention awkward array and boost-histogram and not cite the SciPy conference papers about them. I believe you authored one of them?

2022-06-28 13:08 UTC, deniederhut commented on papers/henry_schreiner/henry_schreiner.rst
> +   this talk, we will look key packages in the ecosystem, at how the collection
In this paper?

2022-06-28 13:08 UTC, deniederhut commented on papers/henry_schreiner/henry_schreiner.rst
> +Wide Web was invented at CERN in 1989 :cite:`leiner2009brief`. Today, we have
I'm not understanding the link between intense compute and WWW

2022-06-28 13:08 UTC, deniederhut commented on papers/henry_schreiner/henry_schreiner.rst
> +the largest machine in the world at CERN: the Large Hadron Collider (LHC), 27
I'm also not understanding the link between a large apparatus and intense compute. In general, this paragraph reads like a collection of disparate statements -- maybe more exposition is required? Or maybe this paragraph isn't needed?

2022-06-28 13:08 UTC, deniederhut commented on papers/henry_schreiner/henry_schreiner.rst
> +dataset in the world of exabyte scale :cite:`peters2011exabyte`.
Largest compared to what? Some other examples might help readers put this into context.

2022-06-28 13:08 UTC, deniederhut commented on papers/henry_schreiner/henry_schreiner.rst
> +HEP scientists have been interested in Python since 1993
I took a quick look at this reference -- it looks like it was a scientist, singular, in 1993? The paper itself seems to mark 2000 or 2001 as the point when other HEP scientists started using it?

2022-06-28 13:08 UTC, deniederhut commented on papers/henry_schreiner/henry_schreiner.rst
> +physicists started writing code in Python. It was not able to provide the
A physicist?

2022-06-28 13:08 UTC, deniederhut commented on papers/henry_schreiner/henry_schreiner.rst
> +performance required to become the main language for HEP.  In 1995, the ROOT
Like the previous paragraph, this reads less like a story or an argument, and more like a collection of disjointed statements. Who discovered that Python wasn't performant enough? What was the root of the problem? How did this lead to the development of root? If it's not worth writing this as an exposition, it probably isn't needed for the paper.

2022-06-28 13:08 UTC, deniederhut commented on papers/henry_schreiner/henry_schreiner.rst
> +also needed an "extension language" - this is the language driving the
I'm not sure I understand the distinction you are making between a language and an extension language.

2022-06-28 13:08 UTC, deniederhut commented on papers/henry_schreiner/henry_schreiner.rst
> +analysis. Python was rejected for this role due to being "exotic", and because
Can I have a reference for who called Python "exotic"?

2022-06-28 13:08 UTC, deniederhut commented on papers/henry_schreiner/henry_schreiner.rst
> +Python would start showing up a few years later in experiment frameworks as a
"a few years later" could be taken to mean 1997. Is this what you mean?

2022-06-28 13:08 UTC, deniederhut commented on papers/henry_schreiner/henry_schreiner.rst
> +were made of many configurable parts; the glueing together of the system was
Is this your personal experience of doing physics in the 90s?

2022-06-28 13:08 UTC, deniederhut commented on papers/henry_schreiner/mybib.bib
> +@article{generowicz2004reflection,
If this is an article, where is the journal title and volume?

2022-06-28 13:08 UTC, deniederhut commented on papers/henry_schreiner/henry_schreiner.rst
> +:cite:`generowicz2004reflection` that were not considered Pythonic, and still
I'm not seeing in this reference where the authors call ROOT's python library not pythonic.

2022-06-28 13:08 UTC, deniederhut commented on papers/henry_schreiner/henry_schreiner.rst
> +   easier Pythonizations, and installing ROOT in Conda is now much easier,
Is Pythonizations a word?

2022-06-28 13:08 UTC, deniederhut commented on papers/henry_schreiner/henry_schreiner.rst
> +   thanks in large part to efforts from Scikit-HEP developers.
Is this you?

2022-06-28 13:08 UTC, deniederhut commented on papers/henry_schreiner/henry_schreiner.rst
> +still consisted largely of ROOT, with Python sometimes showing up.
Am I understanding correctly that the paper this far is a summary of the contents in https://zenodo.org/record/6353621?

2022-06-28 13:08 UTC, deniederhut commented on papers/henry_schreiner/henry_schreiner.rst
> +By the mid 2010's, a marked change had occurred. Many students were coming in
What caused this change?

2022-06-28 13:08 UTC, deniederhut commented on papers/henry_schreiner/henry_schreiner.rst
> +were made driven by Python, with ROOT only being used for things that were not
"made driven"?

2022-06-28 13:08 UTC, deniederhut commented on papers/henry_schreiner/henry_schreiner.rst
> +growing Python data science ecosystem, like NumPy and Pandas. Several analyses
Several analyses like what?

2022-06-28 13:08 UTC, deniederhut commented on papers/henry_schreiner/henry_schreiner.rst
> +available in the Python ecosystem. Some of these were HEP specific: ROOT was
Generally speaking, dependent clauses should be related to and provide further information about the independent clause to which they are attached. "users needed to be able to read data files" is not "HEP specific".

2022-06-28 14:33 UTC, eduardo-rodrigues commented on papers/henry_schreiner/henry_schreiner.rst
> +growing Python data science ecosystem, like NumPy and Pandas. Several analyses
This refers to physics analyses done within the particle physics collaborations. We can expand as per my reply.

2022-06-28 14:34 UTC, eduardo-rodrigues commented on papers/henry_schreiner/henry_schreiner.rst
> +   this talk, we will look key packages in the ecosystem, at how the collection
This is the abstract of the presentation, hence "this talk". If that's accepted we should then replace with "In these proceedings".

2022-06-28 14:43 UTC, eduardo-rodrigues commented on papers/henry_schreiner/henry_schreiner.rst
> +   easier Pythonizations, and installing ROOT in Conda is now much easier,
A quick search online shows that very many people use the "word". It's not a word in the strict sense, yes, but is that a problem for SciPy proceedings, which tend to be technical anyway, with slang and where neologisms seem appropriate? If the "word" really sound unacceptable to you we could replace with "Python-ize", I guess.

2022-06-28 14:46 UTC, eduardo-rodrigues commented on papers/henry_schreiner/henry_schreiner.rst
> +   thanks in large part to efforts from Scikit-HEP developers.
Us and other co-organisation developers.

2022-06-28 14:48 UTC, eduardo-rodrigues commented on papers/henry_schreiner/mybib.bib
> +@article{generowicz2004reflection,
Oops, seems we forgot part of the info! The article comes from CERN, see https://cds.cern.ch/record/865620/.

Better use
```
@article{Lavrijsen:865620,
      author        = "Lavrijsen, W and Generowicz, J and Marino, M and Mato, P",
      title         = "{Reflection-Based Python-C++ Bindings}",
      year          = "2005",
      url           = "https://cds.cern.ch/record/865620",
      doi           = "10.5170/CERN-2005-002.441",
}
```
as seen at this link.

2022-06-29 00:28 UTC, deniederhut reviewed
Another batch of comments!

2022-06-29 00:28 UTC, deniederhut commented on papers/henry_schreiner/henry_schreiner.rst
> +In 2016, the ecosystem for Python in HEP was rather fragmented. There were
Do we mean fragmented? Or do we mean uncoordinated?

2022-06-29 00:28 UTC, deniederhut commented on papers/henry_schreiner/henry_schreiner.rst
> +a handful of popular packages that were useful in HEP spread around among
Why was this a problem or challenge?

2022-06-29 00:28 UTC, deniederhut commented on papers/henry_schreiner/henry_schreiner.rst
> +C++ MINUIT fitting library was integrated into ROOT, but the ``iminuit`` package :cite:`iminuit`
I am guessing the intention behind sharing this example is that there were two separate efforts to make MINUIT available in Python? Do we want to say more about that?

2022-06-29 00:28 UTC, deniederhut commented on papers/henry_schreiner/henry_schreiner.rst
> +Eduardo Rodrigues, a scientist working in the LHCb project at CERN for the
Did we define what LHCb is?

2022-06-29 00:28 UTC, deniederhut commented on papers/henry_schreiner/henry_schreiner.rst
> +that would provide a set to tools useful for physicists working on an analysis.
"analysis" is pretty generic -- presumably scikit-hep does something more specific?

2022-06-29 00:28 UTC, deniederhut commented on papers/henry_schreiner/henry_schreiner.rst
> +unit conversions, several useful statistical tools, and provenance recording
What kinds of statistical tools? Why was this not "transformational"?

2022-06-29 00:28 UTC, deniederhut commented on papers/henry_schreiner/henry_schreiner.rst
> +project was ending, with the primary author moving on, and so several of the
Did rootpy end? Or was management of it transferred?

2022-06-29 00:28 UTC, deniederhut commented on papers/henry_schreiner/henry_schreiner.rst
> +then-popular packages that were included in the rootpy organization were happily
Not popular anymore?

2022-06-29 00:28 UTC, deniederhut commented on papers/henry_schreiner/henry_schreiner.rst
> +transferred to Scikit-HEP. Several other existing HEP libraries, primarily
Several others like what?

2022-06-29 00:28 UTC, deniederhut commented on papers/henry_schreiner/henry_schreiner.rst
> +ROOT. It was a challenging compile, a huge "library", not very Pythonic,
Challenging "to" compile? Why is library in quotations?

2022-06-29 00:28 UTC, deniederhut commented on papers/henry_schreiner/henry_schreiner.rst
> +ROOT. It was a challenging compile, a huge "library", not very Pythonic,
Oh also, we've called it not Pythonic twice now and haven't really said why or on whose authority?

2022-06-29 00:28 UTC, deniederhut commented on papers/henry_schreiner/henry_schreiner.rst
> +and didn't play well with packaging. Many analyses started with a "convert data"
Do you mean that many ROOT analyses start by converting data? And this made it a barrier to using Python in HEP?

2022-06-29 00:28 UTC, deniederhut commented on papers/henry_schreiner/henry_schreiner.rst
> +later writer) that could remove the initial conversions step by simply
I'm guessing you mean that you could remove the initial conversion step by simply using uroot, and, separately, that it was simple to install?

2022-06-29 00:28 UTC, deniederhut commented on papers/henry_schreiner/henry_schreiner.rst
> +"nice" outputs, like NumPy arrays.
Why is nice in quotation marks?

2022-06-29 00:28 UTC, deniederhut commented on papers/henry_schreiner/henry_schreiner.rst
> +Uproot was not just a file format reader; it quickly split into three packages.
If it isn't just a file reader, why did you say so in the opening sentence of the last paragraph?

2022-06-29 00:28 UTC, deniederhut commented on papers/henry_schreiner/henry_schreiner.rst
> +for its classes, like vectors. The other was AwkwardArray, which would grow to
In _for its classes_, do you mean ROOT's classes? Is _vectors_ an example of a functionality, or a class? 

The audience here is likely to be familiar with NumPy arrays, but not with ROOT. What vector functionality was ROOT providing that wasn't available in NumPy?

2022-06-29 00:28 UTC, deniederhut commented on papers/henry_schreiner/henry_schreiner.rst
> +Uproot was not just a file format reader; it quickly split into three packages.
You say here that uproot split into three packages, but I think you only go on to name two of them?

2022-06-29 00:28 UTC, deniederhut commented on papers/henry_schreiner/henry_schreiner.rst
> +package allowed NumPy-like idioms for array-at-a-time manipulation and access
It doesn't allow them anymore?

2022-06-29 00:28 UTC, deniederhut commented on papers/henry_schreiner/henry_schreiner.rst
> +to jagged data structures. These are very common and relevant in HEP; events have a variable
The next three sentences all have multiple independent clauses joined with semicolons -- this might be a sign that we are missing a good linking structure between the ideas

2022-06-29 00:28 UTC, deniederhut commented on papers/henry_schreiner/henry_schreiner.rst
> +store such structures, computations on jagged structures have usually been
I don't think I understand this sentence. Tables in SQL are rectangular -- how are computations on variable-length data streams like SQL?

2022-06-29 00:28 UTC, deniederhut commented on papers/henry_schreiner/henry_schreiner.rst
> +Uproot was a huge hit with incoming HEP students; suddenly they could access
What did it mean to be a "huge hit"?

2022-06-29 00:28 UTC, deniederhut commented on papers/henry_schreiner/henry_schreiner.rst
> +rapidly growing machine learning frameworks. There were still some gaps and
Do we want to be explicit about the tools that were interoperable?

2022-06-29 00:28 UTC, deniederhut commented on papers/henry_schreiner/henry_schreiner.rst
> +HEP data using pip or conda, use tools they already knew like Pandas and the
I'm guessing you mean that they could access HEP data using libraries installed via pip or conda?

2022-06-29 00:28 UTC, deniederhut commented on papers/henry_schreiner/henry_schreiner.rst
> +pain points in the ecosystem, but an analysis without C++ or compiling ROOT was
I'm guessing you mean they did not need to interact with C++ directly? Also, I'm seeing the word "analysis" used a lot to describe the workflows served by this tool -- does this have a specific technical meaning in HEP that it doesn't have in other fields?

2022-06-29 00:28 UTC, deniederhut commented on papers/henry_schreiner/henry_schreiner.rst
> +finally possible. Scikit-HEP did not and does not intend to "replace" ROOT, but
Why is replace in quotation marks?

2022-06-29 00:28 UTC, deniederhut commented on papers/henry_schreiner/henry_schreiner.rst
> +it provides alternative solutions that work natively in the Python "Big Data" ecosystem, which in this
I'm having a hard time glossing this sentence: _it provides alternative solutions which was to remove the ROOT requirement_.

2022-06-29 00:28 UTC, deniederhut commented on papers/henry_schreiner/henry_schreiner.rst
> +Several other useful HEP libraries were also written.For example: Particle for accessing
More libraries, more better! Is there a reason we didn't list them with the rest of the tools at the top of this section?

2022-06-29 00:28 UTC, deniederhut commented on papers/henry_schreiner/henry_schreiner.rst
> +   The landscape of different libraries for Histograms in HEP.
What's the motivation behind using monthly active committers as opposed to some other metric, like commits or downloads?

2022-06-29 00:28 UTC, deniederhut commented on papers/henry_schreiner/henry_schreiner.rst
> +library to the Boost libraries, the most respected C++ library collection. It
"the most respected C++ library collection" is a pretty bold claim. Do we want to qualify this? Or provide some evidence for it?

2022-06-29 00:28 UTC, deniederhut commented on papers/henry_schreiner/henry_schreiner.rst
> +provided a histogram-as-an-object concept from HEP, but rethought histograms in
Can we clarify that we are talking about the proposal, and not Boost?

2022-06-29 00:28 UTC, deniederhut commented on papers/henry_schreiner/henry_schreiner.rst
> +provided a histogram-as-an-object concept from HEP, but rethought histograms in
If he was rethought histograms in C++14, what did the original thought look like?

2022-06-29 00:28 UTC, deniederhut commented on papers/henry_schreiner/henry_schreiner.rst
> +and work began on ``boost-histogram``. The IRIS-HEP grant had just started,
Did we define what IRIS-HEP is?

2022-06-29 00:28 UTC, deniederhut commented on papers/henry_schreiner/henry_schreiner.rst
> +them filled the requirements of HEP physicists fully, and most of them were not easy
Why was this?

2022-06-29 00:28 UTC, deniederhut commented on papers/henry_schreiner/henry_schreiner.rst
> +:ref:`fig-github-histogram`). The development of a library with compiled
We might need more detail about what this means for readers who haven't tried to package a python library with compiled dependencies.

2022-06-29 00:28 UTC, deniederhut commented on papers/henry_schreiner/henry_schreiner.rst
> +Python wheels possible, but there still were many challenges to making a new
I think we could rewrite _the wheel format made Python wheels possible_ to be more informative. 

What were the challenges in building libraries? What made the wheel format better for distributing binaries? Why was the manylinux specification important for supporting multiple architectures?

2022-06-29 00:28 UTC, deniederhut commented on papers/henry_schreiner/henry_schreiner.rst
> +library that could be used anywhere.
Are we going to see these challenges enumerated below?

2022-06-29 00:28 UTC, deniederhut commented on papers/henry_schreiner/henry_schreiner.rst
> +The boost-histogram library only depended on header-only components of the
I would guess that many people at SciPy will not know what a header file is.

2022-06-29 00:28 UTC, deniederhut commented on papers/henry_schreiner/henry_schreiner.rst
> +were packed into the SDist, and everything was possible using only setuptools,
Have we defined what an SDist is?

2022-06-29 00:28 UTC, deniederhut commented on papers/henry_schreiner/henry_schreiner.rst
> +In 2018, HEP physicist and programmer Hans Dembinski proposed a histogram
If the point of this section is to discuss advancements in building and packaging libraries, why do we start by talking about the large number of histogram libraries? That seems orthogonal to me?

2022-06-29 00:28 UTC, deniederhut commented on papers/henry_schreiner/henry_schreiner.rst
> +redistributable wheels requires a variety of techniques, even without shared
A variety of techniques like what? How do they vary?

2022-06-29 00:28 UTC, deniederhut commented on papers/henry_schreiner/henry_schreiner.rst
> +be merged into ``cibuildwheel``, which would become the build tool for all
What is cibuildwheel? Is it a part of scikit-hep?

2022-06-29 00:28 UTC, deniederhut commented on papers/henry_schreiner/henry_schreiner.rst
> +developments to pybind11. Pybind11 provided significant benefits to our
Have we explained what pybind11 is?

2022-06-29 00:28 UTC, deniederhut commented on papers/henry_schreiner/henry_schreiner.rst
> +packages over (mis)-using Cython for bindings: reduced maintenance, simpler
What does it mean to misuse Cython for C bindings?

2022-06-29 00:28 UTC, deniederhut commented on papers/henry_schreiner/henry_schreiner.rst
> +``iMinuit`` package was later moved to pybind11 as well, and pybind11 became
Moved to pybind11 from what?

2022-06-29 00:28 UTC, deniederhut commented on papers/henry_schreiner/henry_schreiner.rst
> +the Scikit-HEP recommended binding tool. Scikit-HEP developers, notably Henry Schreiner, contributed a
It feels weird to Dillon Niederhut to see people talk about themselves with their proper name. Maybe we could say _scikit-hep developers, including the authors, worked on the following improvements..._?

2022-06-29 00:28 UTC, deniederhut commented on papers/henry_schreiner/henry_schreiner.rst
> +variety of fixes and features to pybind11, including positional and keyword
This is a very long sentence, and some of these items could probably use an explanation.

2022-06-29 00:28 UTC, deniederhut commented on papers/henry_schreiner/henry_schreiner.rst
> +compiler support. We also helped improve all the example projects.
What does it mean to improve an example project?

2022-06-29 00:28 UTC, deniederhut commented on papers/henry_schreiner/henry_schreiner.rst
> +the Python-only code with compiled code, fixing some long-standing limitations
What limitations did it fix? What further developments did it enable?

2022-06-29 00:28 UTC, deniederhut commented on papers/henry_schreiner/henry_schreiner.rst
> +Scikit-HEP had become a reasonably popular "toolset" for HEP analysis in Python, a collection of packages that worked together,
Had become popular by what point in time? Popular by what definition?

2022-06-29 00:28 UTC, deniederhut commented on papers/henry_schreiner/henry_schreiner.rst
> +instead of a "toolkit" like ROOT, which is one monopackage that tries to
If this section is about improvements in building and packaging, why are we talking about a distinction between toolkits and toolsets?

2022-06-29 00:28 UTC, deniederhut commented on papers/henry_schreiner/henry_schreiner.rst
> +libraries. Scikit-HEP only needed to fill existing gaps, instead of covering
Why is not including ROOT relevant to the topic of this section? Why is it relevant that it was written in 1994?

2022-06-29 00:28 UTC, deniederhut commented on papers/henry_schreiner/henry_schreiner.rst
> +``scikit-hep`` package started to be pulled out into separate packages, and
Wait -- was scikit-hep a collection of packages? Or was it a single package that needed to be split up?

2022-06-29 00:28 UTC, deniederhut commented on papers/henry_schreiner/henry_schreiner.rst
> +instead simply was becoming a metapackage that would install a useful subset of
I think not everyone will know what a metapackage is

2022-06-29 04:27 UTC, henryiii commented
Thanks @deniederhut! I'll start addressing the comments tomorrow.

2022-06-29 11:43 UTC, eduardo-rodrigues commented
@deniederhut, I do not see a resolve button, which would be really useful to deal with trivialities where a simple answer with a possible rewording is enough. Is that meant to be this way? It makes it more difficult to contribute.

2022-06-29 11:47 UTC, eduardo-rodrigues commented on papers/henry_schreiner/henry_schreiner.rst
> +In 2016, the ecosystem for Python in HEP was rather fragmented. There were
Well, both. But IMO it is not a good idea to add "uncoordinated" because nobody really can have a coordination role. What happens with projects such as ours - Scikit-HEP - is that we effectively push more in some directions rather than others. That's been working really well because things are community-driven and community oriented, with discussions on designs and interests being in the open.

2022-06-29 11:49 UTC, eduardo-rodrigues commented on papers/henry_schreiner/henry_schreiner.rst
> +Eduardo Rodrigues, a scientist working in the LHCb project at CERN for the
We can easily refer to the LHCb experiment website - better use the public one https://lhcb-outreach.web.cern.ch/. In the first instance we can add a few word of the kind "the LHCb particle physics experiment at the CERN laboratory".

@henryiii, do you want me to make some edits or else I keep suggesting and you commit them all yourself?

2022-06-29 11:50 UTC, eduardo-rodrigues commented on papers/henry_schreiner/henry_schreiner.rst
> +instead simply was becoming a metapackage that would install a useful subset of
I think for a scientific conference proceedings we should not go and define concepts such as that. Anyone can check a dictionary (imagine the novelist not using "fancy words" that many may not know because they would have to define them ;-)).

2022-06-29 19:13 UTC, cbcunc commented
Reviewers, please give your final recommendations. The deadline for final review comments is tomorrow.

Authors, please respond to review comments with changes or comments which resolve the conversation. Final acceptance decisions are July 4.

@eduardo-rodrigues, I see a "Resolve conversation" button below each review comment. Is it not showing up for you?

2022-06-30 01:34 UTC, deniederhut commented on papers/henry_schreiner/henry_schreiner.rst
> +instead simply was becoming a metapackage that would install a useful subset of
Is your argument that knowing about science implies knowing about packaging? I would think those are orthogonal?

2022-06-30 01:36 UTC, deniederhut commented on papers/henry_schreiner/henry_schreiner.rst
> +instead simply was becoming a metapackage that would install a useful subset of
SciPy is a generalist audience, so we do ask authors to define field-specific terms -- you can see more about our paper critieria here: https://github.com/scipy-conference/scipy_proceedings/blob/master/review_criteria.md

2022-06-30 01:57 UTC, henryiii commented on papers/henry_schreiner/henry_schreiner.rst
> +   this talk, we will look key packages in the ecosystem, at how the collection
I'm trying "in these proceedings" here.

2022-06-30 02:01 UTC, deniederhut requested changes
Mkay I'm running out of steam, but I think you should have enough feedback to get started on some revisions to the paper. I look forward to seeing your changes!

2022-06-30 02:01 UTC, deniederhut commented on papers/henry_schreiner/henry_schreiner.rst
> +iMinuit, a popular HEP and astrophysics fitting library, probably the most
We have a dangling dependent clause here modifying iMinuit -- it might be nice to shorten simplify this a little bit.

2022-06-30 02:01 UTC, deniederhut commented on papers/henry_schreiner/henry_schreiner.rst
> +popular single package to have joined. PyHF and cabinetry also joined; these were
Most popular by what measure? Is that relevant to scikit-hep's growth? Did its popularity bring in other packages?

2022-06-30 02:01 UTC, deniederhut commented on papers/henry_schreiner/henry_schreiner.rst
> +Scikit-HEP was quickly becoming the center of Python focused analysis in HEP
I'm not sure that figure 1 shows how quickly the number of libraries associated with scikit-hep grew.

2022-06-30 02:01 UTC, deniederhut commented on papers/henry_schreiner/henry_schreiner.rst
> +larger frameworks built on Scikit-HEP packages.
To a reader who is not in HEP, I don't know how compelling it is to list out package names like this.

2022-06-30 02:01 UTC, deniederhut commented on papers/henry_schreiner/henry_schreiner.rst
> +maintainers. Scikit-HEP introduced an "affiliated" classification, which
Cool! What benefits / synergies did this provide?

2022-06-30 02:01 UTC, deniederhut commented on papers/henry_schreiner/henry_schreiner.rst
> +though that is currently not a requirement.  An affiliated package fills a
It feels like this could be a good place to mention other efforts at coordination, like:

- the array format standard (Oliphant)
- the table format standard that Gael floated a couple years ago
- coordination in the scientific python community at large, presented at this conference last year, Millman and van der Walt

2022-06-30 02:01 UTC, deniederhut commented on papers/henry_schreiner/henry_schreiner.rst
> +Scikit-HEP continues to grow with new packages: for example, vector manipulation,
This has been repeated pretty often -- is this the key point that you want people to take away from the paper?

2022-06-30 02:01 UTC, deniederhut commented on papers/henry_schreiner/henry_schreiner.rst
> +Mplhep added important matplotlib plot types and style for HEP usage.
Again, I'm not sure how compelling it is to list a bunch of library names.

2022-06-30 02:01 UTC, deniederhut commented on papers/henry_schreiner/henry_schreiner.rst
> +Histogramming was designed to be a collection of specialized packages
Why is it important that it was designed this way? Does having this design support the section topic of having a broad ecosystem?

2022-06-30 02:01 UTC, deniederhut commented on papers/henry_schreiner/henry_schreiner.rst
> +to be able to work with histograms. This ecosystem was build and is held
was built?

2022-06-30 02:01 UTC, deniederhut commented on papers/henry_schreiner/henry_schreiner.rst
> +typed Protocol, for a PlottableHistogram object. Producers of histograms, like
Protocols are cool! Do other things in scikit-hep use this strategy? Are protocols part of your strategy for having an ecosystem of tools that all play nicely together?

2022-06-30 02:01 UTC, deniederhut commented on papers/henry_schreiner/henry_schreiner.rst
> +follows this specification. UHI is not required at runtime, though it does
Wait, so this is a convention and not a protocol? Or am I misunderstanding?

2022-06-30 02:01 UTC, deniederhut commented on papers/henry_schreiner/henry_schreiner.rst
> +One example of a package pulling together many components is
Why is this important?

2022-06-30 02:01 UTC, deniederhut commented on papers/henry_schreiner/henry_schreiner.rst
> +``azure-wheel-helpers`` or the competing multibuild package, it was written in
How is being written in Python a requirement for having good practices?

2022-06-30 02:01 UTC, deniederhut commented on papers/henry_schreiner/henry_schreiner.rst
> +ones was our work on cibuildwheel. This was a Python package that supported
What did you add to cibuildwheel?

2022-06-30 02:01 UTC, deniederhut commented on papers/henry_schreiner/henry_schreiner.rst
> +requires a docker image, macOS requires the python.org Python, and Windows can
Is this true? I'm pretty sure I've built a package on linux without using docker.

2022-06-30 02:01 UTC, deniederhut commented on papers/henry_schreiner/henry_schreiner.rst
> +version. We merged our improvments to cibuildwheel, dropped
What improvements?

2022-06-30 02:01 UTC, deniederhut commented on papers/henry_schreiner/henry_schreiner.rst
> +Our continued contributions to cibuildwheel included a new TOML-based
When chaining together a bunch of dependent clauses like this, it's a good practice to keep the parts of speech the same -- say, always starting with a noun. So maybe _an override system... the ability to build directly..._. It's also a pretty long sentence, and it might be worth breaking this up into bullet points or something like that.

2022-06-30 02:01 UTC, deniederhut commented on papers/henry_schreiner/henry_schreiner.rst
> +python version requirements, better globbing support, and more. We also helped
If they matter, we can enumerate what the other capabilities are. If they don't matter, I don't see what we gain by adding _and more_.

2022-06-30 02:01 UTC, deniederhut commented on papers/henry_schreiner/henry_schreiner.rst
> +fully statically type the codebase, apply various checks and style controls,
We ❤ mypy

2022-06-30 02:01 UTC, deniederhut commented on papers/henry_schreiner/henry_schreiner.rst
> +We also have helped with ``build``, ``nox``, ``pyodide``, and many other packages.
Why is this important?

2022-06-30 02:02 UTC, deniederhut commented
@scoobies mark pending comment

2022-06-30 05:40 UTC, henryiii reviewed
Going to stop here for the night. Will push changes.

2022-06-30 05:40 UTC, henryiii commented on papers/henry_schreiner/henry_schreiner.rst
> +   packaging, ecosystem, high energy physics
Updated it unless others disagree.

2022-06-30 05:40 UTC, henryiii commented on papers/henry_schreiner/henry_schreiner.rst
> +Wide Web was invented at CERN in 1989 :cite:`leiner2009brief`. Today, we have
Filled this out a bit, could you see if it helps?

2022-06-30 05:40 UTC, henryiii commented on papers/henry_schreiner/henry_schreiner.rst
> +the largest machine in the world at CERN: the Large Hadron Collider (LHC), 27
Filled out a bit.

2022-06-30 05:40 UTC, henryiii commented on papers/henry_schreiner/henry_schreiner.rst
> +dataset in the world of exabyte scale :cite:`peters2011exabyte`.
Added a bit here + a reference.

2022-06-30 05:40 UTC, henryiii commented on papers/henry_schreiner/henry_schreiner.rst
> +HEP scientists have been interested in Python since 1993
He names at least two people using Python in HEP before he did.

2022-06-30 05:40 UTC, henryiii commented on papers/henry_schreiner/henry_schreiner.rst
> +performance required to become the main language for HEP.  In 1995, the ROOT
I've reworked this a bit.

2022-06-30 05:40 UTC, henryiii commented on papers/henry_schreiner/henry_schreiner.rst
> +also needed an "extension language" - this is the language driving the
I've avoided that term.

2022-06-30 05:40 UTC, henryiii commented on papers/henry_schreiner/henry_schreiner.rst
> +were made of many configurable parts; the glueing together of the system was
Added a citation. Though this is how many frameworks still work (LHCb, CMS, and Atlas all work this way today), and that's from personal experience (at least for LHCb and CMS).

2022-06-30 05:40 UTC, henryiii commented on papers/henry_schreiner/henry_schreiner.rst
> +:cite:`generowicz2004reflection` that were not considered Pythonic, and still
I think I missed it. It's a paper that explicitly calls the rewrite "more Pythonic", so the inverse can be applied (the original was not very Pythonic). Added.

2022-06-30 05:40 UTC, henryiii commented on papers/henry_schreiner/henry_schreiner.rst
> +still consisted largely of ROOT, with Python sometimes showing up.
Not entirely, but partially. I was hoping @jpivarski might have had some input on this part, as he has given nice summaries of this period before.

2022-06-30 05:40 UTC, henryiii commented on papers/henry_schreiner/henry_schreiner.rst
> +   easier Pythonizations, and installing ROOT in Conda is now much easier,
It's used in https://www.epj-conferences.org/articles/epjconf/abs/2020/21/epjconf_chep2020_06004/epjconf_chep2020_06004.html (which is now cited above)

2022-06-30 05:40 UTC, henryiii commented on papers/henry_schreiner/henry_schreiner.rst
> +   thanks in large part to efforts from Scikit-HEP developers.
Mostly Chris Burr, also from Scikit-HEP, along with me and some help from the ROOT team.

2022-06-30 05:40 UTC, henryiii commented on papers/henry_schreiner/henry_schreiner.rst
> +By the mid 2010's, a marked change had occurred. Many students were coming in
Isn't this the next sentence? The change was students were coming in with Python knowledge.

2022-06-30 05:40 UTC, henryiii commented on papers/henry_schreiner/henry_schreiner.rst
> +were made driven by Python, with ROOT only being used for things that were not
made -> performed makes this read better.

2022-06-30 05:40 UTC, henryiii commented on papers/henry_schreiner/henry_schreiner.rst
> +available in the Python ecosystem. Some of these were HEP specific: ROOT was
I guess I should repeat "ROOT"? Users need to read ROOT files.

2022-06-30 05:40 UTC, henryiii commented on papers/henry_schreiner/henry_schreiner.rst
> +a handful of popular packages that were useful in HEP spread around among
This is describing the current successful packages more than the failures (most of the packages mentioned here will go on to join Scikit-HEP). I'll try to clarify that the problem was authors were leaving and there was no continued or shared maintenance.

2022-06-30 05:40 UTC, henryiii commented on papers/henry_schreiner/henry_schreiner.rst
> +Eduardo Rodrigues, a scientist working in the LHCb project at CERN for the
I've done a first round, would you like to do a second follow-up?

2022-06-30 05:40 UTC, henryiii commented on papers/henry_schreiner/henry_schreiner.rst
> +that would provide a set to tools useful for physicists working on an analysis.
Not really. It was basically "SciPy for HEP", a grab bag of things needed for someone working on analysis (next line).

2022-06-30 05:40 UTC, henryiii commented on papers/henry_schreiner/henry_schreiner.rst
> +unit conversions, several useful statistical tools, and provenance recording
I'm going to drop the line after the -, I don't like it, sounds opinionated and doesn't really add anything. (I think uproot was where we started becoming "transformational", that is, having a major impact on analyses)

2022-06-30 05:40 UTC, henryiii commented on papers/henry_schreiner/henry_schreiner.rst
> +project was ending, with the primary author moving on, and so several of the
The package "rootpy" did end, it was not transferred. Much of what it developed (and the other two package that did get transferred, root-numpy and root-pandas) inspired the new "pythonic" PyROOT bindings (now referenced earlier), or our tools (mplhep).

2022-06-30 05:40 UTC, henryiii commented on papers/henry_schreiner/henry_schreiner.rst
> +transferred to Scikit-HEP. Several other existing HEP libraries, primarily
Added some.

2022-06-30 05:40 UTC, henryiii commented on papers/henry_schreiner/henry_schreiner.rst
> +then-popular packages that were included in the rootpy organization were happily
Added a footnote (for this and the above).

2022-06-30 05:40 UTC, henryiii commented on papers/henry_schreiner/henry_schreiner.rst
> +ROOT. It was a challenging compile, a huge "library", not very Pythonic,
The reference now linked the first time. :) And a simple snippet, of say writing a file, would be enough to convince anyone it's not like any Python seen elsewhere!

2022-06-30 05:40 UTC, henryiii commented on papers/henry_schreiner/henry_schreiner.rst
> +ROOT. It was a challenging compile, a huge "library", not very Pythonic,
I think it sort of works the first way, but I can say it that way too. I've reworking the reasons a bit here.

2022-06-30 05:40 UTC, henryiii commented on papers/henry_schreiner/henry_schreiner.rst
> +and didn't play well with packaging. Many analyses started with a "convert data"
Python analyses, but they had to read ROOT files since all the experiment data is in ROOT.

(if it's not clear, when I respond like this, I'm also editing the paper with something similar).

2022-06-30 05:40 UTC, henryiii commented on papers/henry_schreiner/henry_schreiner.rst
> +later writer) that could remove the initial conversions step by simply
Clarified partial from above, and also touched up here too - step was the wrong word, should have been environment.

2022-06-30 05:40 UTC, henryiii commented on papers/henry_schreiner/henry_schreiner.rst
> +"nice" outputs, like NumPy arrays.
Reworded.

2022-06-30 05:40 UTC, henryiii commented on papers/henry_schreiner/henry_schreiner.rst
> +Uproot was not just a file format reader; it quickly split into three packages.
The other is uproot. I reworded it to clarify that it produced two related packages.

2022-06-30 05:40 UTC, henryiii commented on papers/henry_schreiner/henry_schreiner.rst
> +Uproot was not just a file format reader; it quickly split into three packages.
Reworded this part.

2022-06-30 05:40 UTC, henryiii commented on papers/henry_schreiner/henry_schreiner.rst
> +for its classes, like vectors. The other was AwkwardArray, which would grow to
Clarified "spacial and Lorentz vectors".

2022-06-30 05:40 UTC, henryiii commented on papers/henry_schreiner/henry_schreiner.rst
> +package allowed NumPy-like idioms for array-at-a-time manipulation and access
Oops. Uproot-methods has been superseded (by Vector), but Awkward is still present.

2022-06-30 05:40 UTC, henryiii commented on papers/henry_schreiner/henry_schreiner.rst
> +to jagged data structures. These are very common and relevant in HEP; events have a variable
Reworked them a bit.

2022-06-30 05:40 UTC, henryiii commented on papers/henry_schreiner/henry_schreiner.rst
> +store such structures, computations on jagged structures have usually been
I've clarified it a bit, it's done via multiple tables with relative keys. "actors in a movie database", for example. I also added that pandas multindexing does this.

2022-06-30 05:40 UTC, henryiii commented on papers/henry_schreiner/henry_schreiner.rst
> +Uproot was a huge hit with incoming HEP students; suddenly they could access
@jpivarski might have plots or numbers? (also, Jim, I think a couple of plots from your most recent presentation might fit in this paper?)

2022-06-30 05:40 UTC, henryiii commented on papers/henry_schreiner/henry_schreiner.rst
> +HEP data using pip or conda, use tools they already knew like Pandas and the
Yes, added that.

2022-06-30 05:40 UTC, henryiii commented on papers/henry_schreiner/henry_schreiner.rst
> +rapidly growing machine learning frameworks. There were still some gaps and
If you are interoperable with NumPy, that's most tools (minus direct conversion with GPU libraries, but you aren't reading data directly in the GPU anyway).

2022-06-30 05:40 UTC, henryiii commented on papers/henry_schreiner/henry_schreiner.rst
> +pain points in the ecosystem, but an analysis without C++ or compiling ROOT was
An analysis is studying the recored data, as opposed to data acquisition or simulation, which is generally handled in a C++ framework configured with Python. Does that need to be specified somewhere?

2022-06-30 05:40 UTC, henryiii commented on papers/henry_schreiner/henry_schreiner.rst
> +finally possible. Scikit-HEP did not and does not intend to "replace" ROOT, but
I can remove them.

2022-06-30 05:40 UTC, henryiii commented on papers/henry_schreiner/henry_schreiner.rst
> +it provides alternative solutions that work natively in the Python "Big Data" ecosystem, which in this
I'll just remove that last part, doesn't add much.

2022-06-30 05:40 UTC, henryiii commented on papers/henry_schreiner/henry_schreiner.rst
> +Several other useful HEP libraries were also written.For example: Particle for accessing
The only other list was of tools that joined Scikit-HEP, not written to be a library in Scikit-HEP to begin with. Seems reasonable here?

2022-06-30 05:40 UTC, henryiii commented on papers/henry_schreiner/henry_schreiner.rst
> +   The landscape of different libraries for Histograms in HEP.
Ahh, I think this is one of the main plots I was thinking of. @jpivarski can probably comment best on the reasoning. Downloads is really hard to get (batch jobs on grid systems can inflate, or even just the normal mirroring issues on PyPI), and commits can be one person working really hard (or large vs. tiny commit style), but doesn't show general interest quite as well.

2022-06-30 06:26 UTC, eduardo-rodrigues commented
> Reviewers, please give your final recommendations. The deadline for final review comments is tomorrow.
> 
> Authors, please respond to review comments with changes or comments which resolve the conversation. Final acceptance decisions are July 4.
> 
> @eduardo-rodrigues, I see a "Resolve conversation" button below each review comment. Is it not showing up for you?

I'm afraid not. This is what I see:
![image](https://user-images.githubusercontent.com/5013581/176607427-702d3240-f208-46f8-afbb-92c2f0fec26a.png)
To be pragmatic and efficient I have been dropping suggestions as replies/comments and Henry can easily copy-and-paste. Thanks anyway.

2022-06-30 06:41 UTC, eduardo-rodrigues commented on papers/henry_schreiner/henry_schreiner.rst
> +instead simply was becoming a metapackage that would install a useful subset of
> Is your argument that knowing about science implies knowing about packaging? I would think those are orthogonal?

No, I would not say that at all.

Fair enough, having quidelines/criteria for homogeneity is good and we should comply.

2022-06-30 06:46 UTC, eduardo-rodrigues commented on papers/henry_schreiner/henry_schreiner.rst
> +size and scale of the data collected. The World Wide Web was invented at CERN in
```suggestion
size and scale of the data collected. The World Wide Web was invented at the CERN Physics laboratory in Switzerland in
```

2022-06-30 06:46 UTC, eduardo-rodrigues commented on papers/henry_schreiner/henry_schreiner.rst
> +1989 when scientists at CERN in the EU were trying to communicate results with
```suggestion
1989 when scientists in the EU were trying to communicate results with
```

2022-06-30 06:47 UTC, eduardo-rodrigues commented on papers/henry_schreiner/henry_schreiner.rst
> +scientist in the US :cite:`leiner2009brief`.  Today, we have the largest
```suggestion
scientist in the US, and vice-versa :cite:`leiner2009brief`.  Today, we have the largest
```

2022-06-30 06:47 UTC, eduardo-rodrigues commented on papers/henry_schreiner/henry_schreiner.rst
> +machine in the world at CERN: the Large Hadron Collider (LHC), 27 km in
```suggestion
scientific machine in the world, at CERN: the Large Hadron Collider (LHC), 27 km in
```

2022-06-30 08:46 UTC, eduardo-rodrigues commented on papers/henry_schreiner/henry_schreiner.rst
> +dataset in the world of exabyte scale :cite:`peters2011exabyte`, which is roughly
```suggestion
datasets in the world of exabyte scale :cite:`peters2011exabyte`, which is roughly
```

2022-06-30 09:47 UTC, eduardo-rodrigues commented on papers/henry_schreiner/henry_schreiner.rst
> +HEP scientists have been interested in Python since 1993
The author of the paper was a colleague of Guido in Amsterdam and was one of the first guinea pigs, hence his article.

To avoid any "worries" we could rephrase "HEP scientists have been interested in Python since 1993" as "HEP scientists started exploring Python circa 1993". Is that OK to both of you, in which case I assume Henry will commit the change?

2022-06-30 09:50 UTC, eduardo-rodrigues commented on papers/henry_schreiner/henry_schreiner.rst
> +like Xenon1T :cite:`remenska2017giving,rousselle2021fast`.
```suggestion
such as for example the Xenon1T experiment :cite:`remenska2017giving,rousselle2021fast`.
```

2022-06-30 09:51 UTC, eduardo-rodrigues commented on papers/henry_schreiner/henry_schreiner.rst
> +experiments like LHCb at CERN developing frameworks and user tools for
```suggestion
experiments like LHCb developing frameworks and user tools for
```

2022-06-30 09:52 UTC, eduardo-rodrigues commented on papers/henry_schreiner/henry_schreiner.rst
> +experiments like LHCb at CERN developing frameworks and user tools for
(Indeed no longer needed to specify "at CERN" since done above.)

2022-06-30 09:53 UTC, eduardo-rodrigues commented on papers/henry_schreiner/henry_schreiner.rst
> +growing Python data science ecosystem, like NumPy and Pandas. Several analyses
```suggestion
growing Python data science ecosystem, like NumPy and Pandas. Several HEP experiment analyses
```

2022-06-30 09:54 UTC, eduardo-rodrigues commented on papers/henry_schreiner/henry_schreiner.rst
> +growing Python data science ecosystem, like NumPy and Pandas. Several analyses
I made a suggested clarification. Kindly resolve if happy, @deniederhut.

2022-06-30 09:55 UTC, eduardo-rodrigues commented on papers/henry_schreiner/henry_schreiner.rst
> +available in the Python ecosystem. Some of these were HEP specific: ROOT was
Fair point, Henry. Yes.

2022-06-30 09:57 UTC, eduardo-rodrigues commented
Morning @henryiii, I've been making suggestions profiting from the time zone offset, such that we can converge quicker on a final text. Let me know if by change this is not helping you and I will stop. Otherwise I will try and continue in (my) afternoon.

2022-06-30 10:46 UTC, eduardo-rodrigues commented on papers/henry_schreiner/henry_schreiner.rst
> +available in the Python ecosystem. Some of these were HEP specific: ROOT was
```suggestion
available in the Python ecosystem. Some of these were HEP specific: ROOT is
```

2022-06-30 10:47 UTC, eduardo-rodrigues commented on papers/henry_schreiner/henry_schreiner.rst
> +was important, especially with complex models and excellent error estimation.
```suggestion
was important, especially with complex models and accurate error estimation.
```

2022-06-30 10:49 UTC, eduardo-rodrigues commented on papers/henry_schreiner/henry_schreiner.rst
> +Eduardo Rodrigues, a scientist working on the LHCb experiment at CERN for the
```suggestion
Eduardo Rodrigues, a scientist working on the LHCb experiment for the
```

2022-06-30 10:49 UTC, eduardo-rodrigues commented on papers/henry_schreiner/henry_schreiner.rst
> +that would provide a set to tools useful for physicists working on an analysis.
```suggestion
that would provide a set to tools useful for physicists working on HEP analysis.
```

2022-06-30 10:50 UTC, eduardo-rodrigues commented on papers/henry_schreiner/henry_schreiner.rst
> +unit conversions, several useful statistical tools, and provenance recording
```suggestion
HEP related units and conversions, several useful statistical tools, and provenance recording
```

2022-06-30 10:51 UTC, eduardo-rodrigues commented on papers/henry_schreiner/henry_schreiner.rst
> +project was ending, with the primary author moving on, and so several of the
@henryiii, we should either call ROOTPy or rootpy as the project. The former version is better and there are a couple of places to make uniform.

2022-06-30 10:53 UTC, eduardo-rodrigues commented on papers/henry_schreiner/henry_schreiner.rst
> +   release and then died. It was an insperation for the new PyROOT bindings,
```suggestion
   release and then died. It was an inspiration for the new PyROOT bindings,
```

2022-06-30 10:53 UTC, eduardo-rodrigues commented on papers/henry_schreiner/henry_schreiner.rst
> +   and influenced later Scikit-HEP packages like mplhep. The transferred
```suggestion
   and influenced later Scikit-HEP packages like ``mplhep``. The transferred
```

2022-06-30 10:54 UTC, eduardo-rodrigues commented on papers/henry_schreiner/henry_schreiner.rst
> +   and influenced later Scikit-HEP packages like mplhep. The transferred
@henryiii, some packages are not in double backslashes. Will you do a final read to catch remaining instances without?

2022-06-30 10:54 UTC, eduardo-rodrigues commented on papers/henry_schreiner/henry_schreiner.rst
> +joined, like IMinuit, Probfit, PyJet, and NumPythia. Some of these libraries
```suggestion
joined, like ``IMinuit``, ``Probfit``, ``PyJet``, and ``NumPythia``. Some of these libraries
```

2022-06-30 10:56 UTC, eduardo-rodrigues commented on papers/henry_schreiner/henry_schreiner.rst
> +This changed when Jim Pivarski introduced Uproot (originally envisioned as
```suggestion
This changed when Jim Pivarski introduced the ``Uproot`` package (originally envisioned as
```

2022-06-30 10:57 UTC, eduardo-rodrigues commented on papers/henry_schreiner/henry_schreiner.rst
> +One, uproot-methods, included Pythonic access to functionality provided by ROOT
```suggestion
One, ``uproot-methods``, included Pythonic access to functionality provided by ROOT
```

2022-06-30 10:58 UTC, eduardo-rodrigues commented on papers/henry_schreiner/henry_schreiner.rst
> +Several other useful HEP libraries were also written.For example: Particle for accessing
```suggestion
Several other useful HEP libraries were also written. For example, ``Particle`` for accessing
```

2022-06-30 10:59 UTC, eduardo-rodrigues commented on papers/henry_schreiner/henry_schreiner.rst
> +DecayLanguage originally provided tooling for decay definitions, but was
```suggestion
``DecayLanguage`` originally provided tooling for decay definitions, but was
```

2022-06-30 11:01 UTC, eduardo-rodrigues commented on papers/henry_schreiner/henry_schreiner.rst
> +as well as the broader Python ecosystem.
```suggestion
as well as the broader Python community.
```

2022-06-30 19:32 UTC, henryiii commented on papers/henry_schreiner/henry_schreiner.rst
> +library to the Boost libraries, the most respected C++ library collection. It
I've added a mention that many stdlib additions come from Boost. I was worried about adding that since the point isn't that Boost.Histogram expects to be added to the C++ standard.

2022-06-30 19:32 UTC, henryiii commented on papers/henry_schreiner/henry_schreiner.rst
> +redistributable wheels requires a variety of techniques, even without shared
Added some.

2022-06-30 19:32 UTC, henryiii commented on papers/henry_schreiner/henry_schreiner.rst
> +the Scikit-HEP recommended binding tool. Scikit-HEP developers, notably Henry Schreiner, contributed a
> It feels weird to Dillon Niederhut to see people talk about themselves with their proper name.

Best review comment. :). I think Eduardo actually reworded this, don't think I wrote it. But maybe Henry Schreiner did.

2022-06-30 19:32 UTC, henryiii commented on papers/henry_schreiner/henry_schreiner.rst
> +``iMinuit`` package was later moved to pybind11 as well, and pybind11 became
Cython.

2022-06-30 19:32 UTC, henryiii commented on papers/henry_schreiner/henry_schreiner.rst
> +developments to pybind11. Pybind11 provided significant benefits to our
Added

2022-06-30 19:32 UTC, henryiii commented on papers/henry_schreiner/henry_schreiner.rst
> +packages over (mis)-using Cython for bindings: reduced maintenance, simpler
Expanded.

2022-06-30 19:32 UTC, henryiii commented on papers/henry_schreiner/henry_schreiner.rst
> +compiler support. We also helped improve all the example projects.
Expanded a bit.

2022-06-30 19:32 UTC, henryiii commented on papers/henry_schreiner/henry_schreiner.rst
> +instead of a "toolkit" like ROOT, which is one monopackage that tries to
This should have been in the section below (header is one paragraph too low).

2022-06-30 19:32 UTC, henryiii commented on papers/henry_schreiner/henry_schreiner.rst
> +libraries. Scikit-HEP only needed to fill existing gaps, instead of covering
This ecosystem didn't exist then. But I think it's best just to remove the remark.

2022-06-30 19:32 UTC, henryiii commented on papers/henry_schreiner/henry_schreiner.rst
> +``scikit-hep`` package started to be pulled out into separate packages, and
Scikit-HEP was an organization, and `scikit-hep` was a pip-installable package in that origination. It was later turned into just a metapackage installing our core packages. Tried to clarify that here.

2022-06-30 19:32 UTC, henryiii commented on papers/henry_schreiner/henry_schreiner.rst
> +instead simply was becoming a metapackage that would install a useful subset of
I feel like it was defined immediately afterwards, but I've tried to clarify.

2022-06-30 19:32 UTC, henryiii commented on papers/henry_schreiner/henry_schreiner.rst
> +Scikit-HEP was quickly becoming the center of Python focused analysis in HEP
I've changed this to be a center of HEP specific Python software.

2022-06-30 19:32 UTC, henryiii commented on papers/henry_schreiner/henry_schreiner.rst
> +popular single package to have joined. PyHF and cabinetry also joined; these were
Changed to widely used.

2022-06-30 19:32 UTC, henryiii commented on papers/henry_schreiner/henry_schreiner.rst
> +iMinuit, a popular HEP and astrophysics fitting library, probably the most
Improved.

2022-06-30 19:32 UTC, henryiii commented on papers/henry_schreiner/henry_schreiner.rst
> +maintainers. Scikit-HEP introduced an "affiliated" classification, which
Expanded this a bit, but one of the purposes is to clarify that we don't need to develop things that affiliated packages already provide.

2022-06-30 19:32 UTC, henryiii commented on papers/henry_schreiner/henry_schreiner.rst
> +Mplhep added important matplotlib plot types and style for HEP usage.
I think both of these were actually covered elsewhere, I can just remove this paragraph.

2022-06-30 19:32 UTC, henryiii commented on papers/henry_schreiner/henry_schreiner.rst
> +typed Protocol, for a PlottableHistogram object. Producers of histograms, like
Yes, tried to highlight that a bit more. Jim does a better job of highlighting this in his talks.

2022-06-30 19:32 UTC, henryiii commented on papers/henry_schreiner/henry_schreiner.rst
> +follows this specification. UHI is not required at runtime, though it does
No, it's a Protocol. It's just that you don't need the Protocol at runtime, only at typecheck time. But the library has a few useful tools (mostly because PyROOT from the ROOT team doesn't support the Protocol, at least yet), so you'll actually see it as a runtime dependency of some of our libraries (mplhep uses it, specifically). Maybe this is entirely unneeded information, I'm just not wanting someone to look up mplhep and see UHI is required and not realize why.

I went the add more way rather than the remove some way here, but could switch.

2022-06-30 19:32 UTC, henryiii commented on papers/henry_schreiner/henry_schreiner.rst
> +One example of a package pulling together many components is
Added an intro sentence.

2022-06-30 19:32 UTC, henryiii commented on papers/henry_schreiner/henry_schreiner.rst
> +``azure-wheel-helpers`` or the competing multibuild package, it was written in
Expanded a bit: unit and integration tests, static checks, and independent of CI system.

2022-06-30 19:32 UTC, henryiii commented on papers/henry_schreiner/henry_schreiner.rst
> +requires a docker image, macOS requires the python.org Python, and Windows can
Was it redistributable? It's not easy or supported to make a wheel and process it into manylinux on an arbitrary system. There's an exact list of what is allowed; building on a different image could easily include something that is not supported across the "many linuxes".

2022-06-30 19:32 UTC, henryiii commented on papers/henry_schreiner/henry_schreiner.rst
> +version. We merged our improvments to cibuildwheel, dropped
Looked it up and added it.

2022-06-30 19:32 UTC, henryiii commented on papers/henry_schreiner/henry_schreiner.rst
> +We also have helped with ``build``, ``nox``, ``pyodide``, and many other packages.
Added a bit.

2022-06-30 19:32 UTC, henryiii commented on papers/henry_schreiner/henry_schreiner.rst
> +python version requirements, better globbing support, and more. We also helped
Avoided the "and more" with minor rewording. It's a little hard to pick out what I contributed vs. what I reviewed and helped with exactly. I've made 118 successful PRs to cibuildwheel. :)

2022-06-30 19:32 UTC, henryiii commented on papers/henry_schreiner/henry_schreiner.rst
> +project was ending, with the primary author moving on, and so several of the
Used ROOTPy. Should all package names be `fenced` or all be unfenced? I was sort-of fencing the first usage of a package name. I'll probably add pre-commit file just for my use to enforce a few conventions. ;)

2022-06-30 22:11 UTC, henryiii commented on papers/henry_schreiner/henry_schreiner.rst
> +project was ending, with the primary author moving on, and so several of the
Went with all plain. Though I wrote a little pre-commit utility to check for doing it the other way.

2022-06-30 22:12 UTC, henryiii commented on papers/henry_schreiner/henry_schreiner.rst
> +In 2018, HEP physicist and programmer Hans Dembinski proposed a histogram
Retitled it a bit.

2022-06-30 23:01 UTC, jpivarski commented on papers/henry_schreiner/henry_schreiner.rst
> +Uproot was a huge hit with incoming HEP students; suddenly they could access
Do you mean this plot?

[![image](https://user-images.githubusercontent.com/1852447/176791377-6dec3b4f-627d-42a9-8afb-b51c34afa032.png)](https://github.com/matthewfeickert/talk-doepy-python-exchange-2022/blob/main/figures/github-package-fullstudy-for-review.pdf)

It highlights the adoption of NumPy, Matplotlib, Pandas, and TensorFlow in HEP (in terms of "`import X`" matches in CMS physicist GitHub repos). Although Uproot and Awkward Array are on the plot and Uproot is at the same level of adoption as TensorFlow, there isn't an arrow pointing it out. It also comes with the cost of explaining how this study was performed, what the "ROOT" baseline is, and why other libraries weren't highlighted here. (The most popular in each category are shown, cut off for plot space.)

Is that something we want to include?

There are also pip download rates, which are a different kind of measure. This one could be good for Scikit-HEP overall.

[![image](https://user-images.githubusercontent.com/1852447/176791968-65f88629-5be3-48f5-9ba6-a91a3c5d8206.png)](https://github.com/matthewfeickert/talk-doepy-python-exchange-2022/blob/main/figures/pip-macwin-scikithep-log-by-package.pdf)

The lines don't cross because they are stacked time-histograms, and the largest contributors are on the top (because addition only shows up well on a log scale if the smallest addends are in the most magnified part of the log-scale).

2022-06-30 23:07 UTC, jpivarski commented on papers/henry_schreiner/henry_schreiner.rst
> +   The landscape of different libraries for Histograms in HEP.
The intention of the histogram plot is to show developer activity, not user activity. "Monthly unique committers" was chosen to show that this group of histogram libraries are in very active development, unlike the long-lived (and well-maintained) ROOT histograms, the rootpy project that was active too early (before Python was regularly used for analysis in HEP), and unlike the many small projects that sprung up around 2017 (when Python _was_ picked up for analysis in HEP).

That's why it has this metric.

User statistics would also be interesting, though usage is awaiting a bump that will come when Coffea users fully transition from Coffea histograms to hist. (I'm predicting the future here because Coffea developers are deliberately steering users toward hist, but it takes time for adoption to switch.)

2022-07-01 10:25 UTC, eduardo-rodrigues commented on papers/henry_schreiner/henry_schreiner.rst
> +Uproot was a huge hit with incoming HEP students; suddenly they could access
These are great plots. FWIW I think the top one is more suitable for these proceedings and wider audience. The bottom plot contains as-is too much information for the audience, though the fact 50 increase is something significant and at least worth mention in words. I let you decide if you prefer to add both or just one :-).

2022-07-01 16:08 UTC, jpivarski commented on papers/henry_schreiner/henry_schreiner.rst
> +HEP scientists have been interested in Python since 1993
The claim about HEP getting interested in Python around 2000 can also be justified by a plot, but maybe we're getting plot-heavy. (Is there a page limit?)

The following plot counts mentions of various languages in Computing in High Energy and nuclear Physics ([CHEP](https://www.jlab.org/conference/CHEP2023)) titles and abstracts, the primary conference for computing in HEP, which goes back to 1985.

[![image](https://user-images.githubusercontent.com/1852447/176929206-983297df-0bfc-4daf-8cdf-7ff9d118c4b5.png)](https://github.com/jpivarski-talks/2022-05-23-analysis-ux-python-hep/blob/main/PLOTS/chep-papers-language-2.pdf)

The big transition from Fortran to C++ in the late 90's is well-known, as was the major adoption of ROOT around 2003 (displacing alternatives that had been floating in the 90's). What isn't as well-known is that mentions of Python have been increasing linearly since then, at first for controlling C++ codebases, but from about 2017 onward, for analysis, too. The convergence on Python for scripting (as opposed to Tcl, Perl, etc.) was noticed and commented upon at the time, such as the slide above, summarizing the 2000 conference. (To say that "ROOT is the exception of the Python rule" was premature, as PyROOT started in 2004.)

But this might be too much emphasis on pre-history. I think we're justified in saying that physicists were interested and using Python from about 2000 onward, though only very recently (~2017) for data analysis.

2022-07-01 16:11 UTC, jpivarski commented on papers/henry_schreiner/henry_schreiner.rst
> +In 2016, the ecosystem for Python in HEP was rather fragmented. There were
I think the word "fragmented" applies. The situation was that physicists were developing tools in isolation, without knowing out the overlaps with other tools, and without making them interoperable. There is a kind of cohesion that can happen without centralized management—which describes the situation now and not the situation in 2016.

2022-07-01 16:14 UTC, jpivarski commented on papers/henry_schreiner/henry_schreiner.rst
> +pain points in the ecosystem, but an analysis without C++ or compiling ROOT was
We're talking about user analysis code (e.g. which particles should be identified as parts of the same decay as each other) written directly in C++ with a write-compile-run workflow and components that need to be binary-compatible to be used together. That was the situation HEP analysis was in before the analysis could be done directly in Python. (We didn't come from another scripting language, like IDL or something.)

2022-07-02 14:12 UTC, henryiii commented on papers/henry_schreiner/henry_schreiner.rst
> +HEP scientists have been interested in Python since 1993
ROOTPy was focused almost entirely on analysis, and in use ending around 2016. I used to use it in those years. I think the PyROOT helpers, ROOTPy/root-numpy/root-pandas and such were in use for those years. ROOTless (or at least less ROOT) analysis are what really took off around 2016/2017.

2022-07-02 14:12 UTC, henryiii commented on papers/henry_schreiner/henry_schreiner.rst
> +a few physicists started using Python. A year later, the ROOT project
```suggestion
a few physicists started exploring the use of Python. A year later, the ROOT project
```

2022-07-02 14:15 UTC, henryiii commented on papers/henry_schreiner/henry_schreiner.rst
> +rapidly growing machine learning frameworks. There were still some gaps and
Specified the Python buffer protocol and mentioned one more library (numpy).

2022-07-02 14:17 UTC, henryiii commented on papers/henry_schreiner/henry_schreiner.rst
> +pain points in the ecosystem, but an analysis without C++ or compiling ROOT was
Added a tiny bit more detail.

2022-07-02 14:19 UTC, henryiii commented on papers/henry_schreiner/henry_schreiner.rst
> +The boost-histogram library only depended on header-only components of the
Added a bit more detail after.

2022-07-02 14:25 UTC, henryiii commented on papers/henry_schreiner/henry_schreiner.rst
> +Histogramming was designed to be a collection of specialized packages
Tried to add a tiny bit more here.

2022-07-08 18:29 UTC, cbcunc commented
@deniederhut Were your requested changes addressed? I see comments from @henryiii and changes from @eduardo-rodrigues.

2022-07-18 16:01 UTC, henryiii commented
@cbcunc where is that sentence? I don't see it as an unaddressed GitHub comment above.

2022-07-19 15:58 UTC, deniederhut commented
@cbcunc sorry! I wasn't checking github during the conference -- I'll take another pass over the paper this week.

2022-07-26 01:00 UTC, deniederhut commented on papers/henry_schreiner/henry_schreiner.rst
> +   these proceedings, we will look key packages in the ecosystem, at how the
In this paper?

2022-07-26 01:45 UTC, deniederhut requested changes
Sorry for taking so long to get around to a re-review. Your edits so far have been awesome -- in particular all the additional information you've added to the paper. I do still see some grammar and spelling issues that could use some attention -- I've marked a few of them inline, but I'm sure I've missed others.

2022-07-26 01:45 UTC, deniederhut commented on papers/henry_schreiner/henry_schreiner.rst
> +   these proceedings, we will look key packages in the ecosystem, at how the
In this paper?

2022-07-26 01:45 UTC, deniederhut commented on papers/henry_schreiner/henry_schreiner.rst
> +   these proceedings, we will look key packages in the ecosystem, at how the
look at key packages?

2022-07-26 01:45 UTC, deniederhut commented on papers/henry_schreiner/henry_schreiner.rst
> +   ecosystem contributions made to packages like cibuildwheel, pybind11, nox,
This is a very long sentence -- it might be easier to parse if it were broken up?

2022-07-26 01:45 UTC, deniederhut commented on papers/henry_schreiner/henry_schreiner.rst
> +HEP scientists have been interested in Python since 1993
> I think we're justified in saying that physicists were interested and using Python from about 2000 onward, though only very recently (~2017) for data analysis.

Do we want to update the paper to say this instead?

2022-07-26 01:45 UTC, deniederhut commented on papers/henry_schreiner/henry_schreiner.rst
> +size and scale of the data collected. The World Wide Web was invented at the CERN Physics laboratory in Switzerland in
I think I'm still missing how inventing WWW is relevant to intense compute needs.

2022-07-26 01:45 UTC, deniederhut commented on papers/henry_schreiner/henry_schreiner.rst
> +for an analysis toolkit (and framework) was released, making C++ the main
Most of this paragraph is about ROOT and its centrality, not about python per se. Would it make sense to change the topic sentence to reflect this?

2022-07-26 01:45 UTC, deniederhut commented on papers/henry_schreiner/henry_schreiner.rst
> +were made of many configurable parts :cite:`LAMMEL199832`; the glueing together
This one sentence has a conjunction, a semi-colon, and an en-dash -- would it make sense to break this up?

2022-07-26 01:45 UTC, deniederhut commented on papers/henry_schreiner/henry_schreiner.rst
> +By the mid 2010's, a marked change had occurred. Many students were coming in
Yup I'm asking why

2022-07-26 01:45 UTC, deniederhut commented on papers/henry_schreiner/henry_schreiner.rst
> +were performed driven by Python, with ROOT only being used for things that were not
Probably we only want either _performed_ or _driven_?

2022-07-26 01:45 UTC, deniederhut commented on papers/henry_schreiner/henry_schreiner.rst
> +the data sizes, large portions of HEP data is "jagged" rather than rectangular,
S/V agreement

2022-07-26 01:45 UTC, deniederhut commented on papers/henry_schreiner/henry_schreiner.rst
> +the data sizes, large portions of HEP data is "jagged" rather than rectangular,
Sequences of independent clauses are typically delineated by semicolons, not commas.

2022-07-26 01:45 UTC, deniederhut commented on papers/henry_schreiner/henry_schreiner.rst
> +In 2016, the ecosystem for Python in HEP was rather fragmented. There were
> without knowing out the overlaps with other tools, and without making them interoperable

Cool, could we say this explicitly?

2022-07-26 01:45 UTC, deniederhut commented on papers/henry_schreiner/henry_schreiner.rst
> +University of Cincinnati, started working on a package called scikit-hep
Should this be scikit-HEP?

2022-07-26 01:45 UTC, deniederhut commented on papers/henry_schreiner/henry_schreiner.rst
> +Eduardo Rodrigues, a scientist working on the LHCb experiment for the
I think we should be explicit that Eduardo is one of the authors on this paper.

2022-07-26 01:45 UTC, deniederhut commented on papers/henry_schreiner/henry_schreiner.rst
> +It was challenging to compile, had many non-Python dependencies, was huge
Is huge referring to the compiled size or the large number of source files?

2022-07-26 01:45 UTC, deniederhut commented on papers/henry_schreiner/henry_schreiner.rst
> +functionality provided by ROOT for its core classes, like spacial and Lorentz
Should this be spatial?

2022-07-26 01:45 UTC, deniederhut commented on papers/henry_schreiner/henry_schreiner.rst
> +requirements, use tools they already knew that were compatible with the Python
I think we're missing a conjunction here?

2022-07-26 01:45 UTC, deniederhut commented on papers/henry_schreiner/henry_schreiner.rst
> +accessing the Particle Data Group (PDG) particle data in a simple and Pythonic
We've been throwing around this word _pythonic_ a lot. I think most people would take that to mean using python code idioms, like truthiness and generators. Is this what you mean? Or do you mean specifically that it doesn't return NumPy arrays and is hard to pip install?

If it's the latter, it might be worth using a different word. If the former, it might be nice to be explicit about what wasn't _pythonic_.

2022-07-26 01:45 UTC, deniederhut commented on papers/henry_schreiner/henry_schreiner.rst
> +Python binding, written in Boost::Python. Henry Schreiner proposed the creation
I think we should be explicit that this is one of the people writing this paper.

2022-07-26 01:45 UTC, deniederhut commented on papers/henry_schreiner/henry_schreiner.rst
> +packages and the manylinux specification and docker image had that allowed a
> and docker image had that allowed

I can't parse this -- what do you mean?

2022-07-26 01:45 UTC, deniederhut commented on papers/henry_schreiner/henry_schreiner.rst
> +were many challenges to making a library redistrubtable on all platforms.
> redistrubtable

not sure about the spelling on this one

2022-07-26 01:45 UTC, deniederhut commented on papers/henry_schreiner/henry_schreiner.rst
> +and keyword-only arguments, the option to prepending to the overload chain, and an API
Option of prepending? Or option to prepend?

2022-07-26 01:45 UTC, deniederhut commented on papers/henry_schreiner/henry_schreiner.rst
> +analysis like ROOT did. The original scikit-hep package had it's
it's -> its

2022-07-26 01:45 UTC, deniederhut commented on papers/henry_schreiner/henry_schreiner.rst
> +functionality was pulled out into existing or new separate packages like
_had its functionality was pulled_?

2022-07-26 07:35 UTC, eduardo-rodrigues commented on papers/henry_schreiner/henry_schreiner.rst
> +:email: eduardo.rodrigues@cern.ch
```suggestion
:email: eduardo.rodrigues@liverpool.ac.uk
```

2022-07-26 07:37 UTC, eduardo-rodrigues commented on papers/henry_schreiner/henry_schreiner.rst
> +were many challenges to making a library redistrubtable on all platforms.
```suggestion
were many challenges to making a library redistributable on all platforms.
```

2022-07-26 07:38 UTC, eduardo-rodrigues commented on papers/henry_schreiner/henry_schreiner.rst
> +and keyword-only arguments, the option to prepending to the overload chain, and an API
```suggestion
and keyword-only arguments, the option to prepend to the overload chain, and an API
```

2022-07-26 07:38 UTC, eduardo-rodrigues commented on papers/henry_schreiner/henry_schreiner.rst
> +analysis like ROOT did. The original scikit-hep package had it's
```suggestion
analysis like ROOT did. The original scikit-hep package had its
```

2022-07-26 07:39 UTC, eduardo-rodrigues commented on papers/henry_schreiner/henry_schreiner.rst
> +functionality was pulled out into existing or new separate packages like
```suggestion
functionality pulled out into existing or new separate packages such as
```

2022-07-26 07:40 UTC, eduardo-rodrigues commented on papers/henry_schreiner/henry_schreiner.rst
> +metapackage with no unique functionality on its own, but instead installs a
```suggestion
metapackage with no unique functionality on its own. Instead, it installs a
```

2022-07-26 07:42 UTC, eduardo-rodrigues commented on papers/henry_schreiner/henry_schreiner.rst
> +functionality provided by ROOT for its core classes, like spacial and Lorentz
```suggestion
functionality provided by ROOT for its core classes, like spatial and Lorentz
```

2022-07-26 07:45 UTC, eduardo-rodrigues commented
Thank you @deniederhut for the extra feedback. @henryiii, I had 5 minutes and dealt with a few easy bits. Just collect the suggestions and get those merged if happy with my changes. Thanks. And let me know if you fancy that I act on more.

2022-07-26 07:46 UTC, eduardo-rodrigues commented on papers/henry_schreiner/henry_schreiner.rst
> +   these proceedings, we will look key packages in the ecosystem, at how the
```suggestion
   this paper we will look at key packages in the ecosystem, at how the
```

2022-07-26 07:47 UTC, eduardo-rodrigues commented on papers/henry_schreiner/henry_schreiner.rst
> +   these proceedings, we will look key packages in the ecosystem, at how the
("Proceedings" seemed more appropriate to me for a conference write-up. But if the review team prefers paper, that's fine too, of course.)

2022-07-26 07:48 UTC, eduardo-rodrigues commented on papers/henry_schreiner/henry_schreiner.rst
> +were made of many configurable parts :cite:`LAMMEL199832`; the glueing together
```suggestion
were made of many configurable parts :cite:`LAMMEL199832`. The glueing together
```

2022-07-26 07:48 UTC, eduardo-rodrigues commented on papers/henry_schreiner/henry_schreiner.rst
> +of the system was done in Python - a model still popular today, though some
```suggestion
of the system was done in Python, a model still popular today, though some
```

2022-07-26 07:49 UTC, eduardo-rodrigues commented on papers/henry_schreiner/henry_schreiner.rst
> +were made of many configurable parts :cite:`LAMMEL199832`; the glueing together
Better break indeed. @henryiii, see if happy with the 2 little changes I'm suggesting.

2022-07-26 07:50 UTC, eduardo-rodrigues commented on papers/henry_schreiner/henry_schreiner.rst
> +were performed driven by Python, with ROOT only being used for things that were not
```suggestion
were performed in, or driven by, Python, with ROOT only being used for things that were not
```

2022-07-26 07:51 UTC, eduardo-rodrigues commented on papers/henry_schreiner/henry_schreiner.rst
> +were performed driven by Python, with ROOT only being used for things that were not
In fact the reality is *both*, meaning done in Python or driven by short Python scripts running C++. I adapted the sentence accordingly.

2022-07-28 23:34 UTC, deniederhut commented
@scoobies check references

2022-07-28 23:34 UTC, scoobies commented
```
Reference check summary (note 'MISSING' DOIs are suggestions that need verification):

OK DOIs

- 10.1051/epjconf/202024506028 is OK
- 10.5281/zenodo.3949207 is OK
- 10.5281/zenodo.6353621 is OK
- 10.5170/CERN-2005-002.441 is OK
- 10.1051/epjconf/202024506004 is OK

MISSING DOIs

- 10.1088/1742-6596/331/5/052015 may be a valid DOI for title: Exabyte scale storage at CERN
- 10.1051/epjconf/202024505023 may be a valid DOI for title: Awkward arrays in python, c++, and numba
- 10.1051/epjconf/202125103027 may be a valid DOI for title: Fast simulation of Time-of-Flight detectors at the LHC

INVALID DOIs

- https://doi.org/10.1016/S0010-4655(97)00150-1 is INVALID because of 'https://doi.org/' prefix
```

2022-07-28 23:38 UTC, deniederhut commented
@henryiii would you mind taking a second pass over your references section? It looks like some of them might be missing DOIs (scoobies isn't always right, so it's good to double check those recommendations).

Also, friendly warning that we'll be publishing the finalized proceedings this weekend. Please get your changes in before then!

2022-07-29 01:39 UTC, henryiii commented
I just returned from back-to-back conferences late yesterday (so first time back since SciPy), and will get to this (and the slides) next!

2022-07-29 01:42 UTC, henryiii commented on papers/henry_schreiner/henry_schreiner.rst
> +University of Cincinnati, started working on a package called scikit-hep
The package is `scikit-hep`, the org is Scikit-HEP. Unless you are NumPy, in which case we seem to be scikit-HEP.

2022-07-29 03:17 UTC, henryiii commented on papers/henry_schreiner/henry_schreiner.rst
> +   ecosystem contributions made to packages like cibuildwheel, pybind11, nox,
Broke it up a little.

2022-07-29 03:17 UTC, henryiii commented on papers/henry_schreiner/henry_schreiner.rst
> +size and scale of the data collected. The World Wide Web was invented at the CERN Physics laboratory in Switzerland in
Added "and data" to "trying to communicate results and datasets".

2022-07-29 03:17 UTC, henryiii commented on papers/henry_schreiner/henry_schreiner.rst
> +HEP scientists have been interested in Python since 1993
Tried reworking it again. The point of this paragraph is that ROOT was chosen over Python in 1995, which is not related to the growth of Python in the 2000's. Later that plot is included and there's a discussion of the adoption in the 20xx's.

2022-07-29 03:17 UTC, henryiii commented on papers/henry_schreiner/henry_schreiner.rst
> +for an analysis toolkit (and framework) was released, making C++ the main
Added a topic sentence at the beginning to clarify this is about the selection of languages that happened in the mid 90's.

2022-07-29 03:17 UTC, henryiii commented on papers/henry_schreiner/henry_schreiner.rst
> +By the mid 2010's, a marked change had occurred. Many students were coming in
Oh, okay.

2022-07-29 03:17 UTC, henryiii commented on papers/henry_schreiner/henry_schreiner.rst
> +Eduardo Rodrigues, a scientist working on the LHCb experiment for the
Sure, how should I word that?

2022-07-29 03:17 UTC, henryiii commented on papers/henry_schreiner/henry_schreiner.rst
> +It was challenging to compile, had many non-Python dependencies, was huge
Both? Though I was intending size (it still can't fit into a wheel on PyPI, the conda-forge version takes up a couple of GB when installed)

2022-07-29 03:17 UTC, henryiii commented on papers/henry_schreiner/henry_schreiner.rst
> +accessing the Particle Data Group (PDG) particle data in a simple and Pythonic
ROOT doesn't support Python idioms, like the various protocols (iterators, context managers, buffer protocol (for NumPy arrays), useful `__repr__`s - basically a 1:1 mapping of C++, no nice dunder methods were injected. Later, the new PyROOT bindings added these (well, technically a way to add these, not all that many pythonizations have been added last I checked).

Basically Pythonic == support for Python idioms, usually by adding dunder methods. And naming conventions, repr styles, etc. I think making this explicit somewhere would be best.

2022-07-29 03:17 UTC, henryiii commented on papers/henry_schreiner/henry_schreiner.rst
> +accessing the Particle Data Group (PDG) particle data in a simple and Pythonic
Added at the beginning.

2022-07-29 03:17 UTC, henryiii commented on papers/henry_schreiner/henry_schreiner.rst
> +packages and the manylinux specification and docker image had that allowed a
The `had` shouldn't be there.

2022-07-29 03:17 UTC, henryiii commented on papers/henry_schreiner/henry_schreiner.rst
> +By the mid 2010's, a marked change had occurred. Many students were coming in
Expanded a bit.

2022-07-29 03:20 UTC, henryiii commented
@scoobies check references

2022-07-29 03:20 UTC, scoobies commented
```
Reference check summary (note 'MISSING' DOIs are suggestions that need verification):

OK DOIs

- 10.1051/epjconf/202024506028 is OK
- 10.5281/zenodo.3949207 is OK
- 10.1088/1742-6596/331/5/052015 is OK
- 10.5281/zenodo.6353621 is OK
- 10.1051/epjconf/202024505023 is OK
- 10.1051/epjconf/202125103027 is OK
- 10.5170/CERN-2005-002.441 is OK
- 10.1051/epjconf/202024506004 is OK

MISSING DOIs

- None

INVALID DOIs

- 10.1016/S0010-46559700150-1 is INVALID
```

2022-07-29 03:23 UTC, henryiii commented
https://www.sciencedirect.com/science/article/abs/pii/S0010465597001501 seems to have an invalid DOI link.

2022-07-30 03:41 UTC, henryiii commented
Any further comments or comments on open threads? I fixed the invalid DOI.

2022-07-30 03:42 UTC, henryiii commented
@scoobies check references

2022-07-30 03:42 UTC, scoobies commented
```
Reference check summary (note 'MISSING' DOIs are suggestions that need verification):

OK DOIs

- 10.1051/epjconf/202024506028 is OK
- 10.5281/zenodo.3949207 is OK
- 10.1088/1742-6596/331/5/052015 is OK
- 10.5281/zenodo.6353621 is OK
- 10.1051/epjconf/202024505023 is OK
- 10.1051/epjconf/202125103027 is OK
- 10.5170/CERN-2005-002.441 is OK
- 10.1051/epjconf/202024506004 is OK

MISSING DOIs

- None

INVALID DOIs

- 10.1016/s0010-46559700150-1 is INVALID
```

2022-07-30 04:15 UTC, henryiii commented
Ahh, Scoobies doesn't understand `(` and `)` in a DOI, that's the problem, I think. It's actually valid.

2022-08-01 01:46 UTC, deniederhut approved these changes
Rock and roll

2022-08-01 01:46 UTC, merged