Paper: EEG-to-fMRI Neuroimaging Cross Modal Synthesis in Python
scipy-conference/scipy_proceedings pull request #801
Opened 2023-05-18 08:39 UTC by DCalhas

If you are creating this PR in order to submit a draft of your paper,
see http://procbuild.scipy.org/ for logs generated by the build
process.

See the [project readme](https://github.com/scipy-conference/scipy_proceedings#build-your-paper)
for more information.

*Editor*:  

*Reviewers*:

2023-06-03 14:55 UTC, deniederhut commented
@scoobies assign @cbcunc as editor

2023-06-03 14:55 UTC, scoobies commented
Assigned! @cbcunc is now the editor

2023-06-06 10:54 UTC, deniederhut commented
@scoobies add @NickleDave to reviewers

2023-06-06 10:54 UTC, scoobies commented
@NickleDave added to the reviewers list!

2023-06-06 10:54 UTC, deniederhut commented
@scoobies code of conduct

2023-06-06 10:54 UTC, scoobies commented
Our CoC: https://www.scipy2023.scipy.org/code-of-conduct

2023-06-06 10:54 UTC, scoobies commented
Reports of abusive or harassing behavior may be reported to scipy@enthought.com

2023-06-07 14:38 UTC, deniederhut commented
@scoobies add @vanessailana to reviewers

2023-06-07 14:38 UTC, scoobies commented
@vanessailana added to the reviewers list!

2023-06-07 17:00 UTC, cbcunc commented
Editor says paper is complete and builds. Awaiting review.

2023-06-23 16:43 UTC, NickleDave requested changes
Hi @DCalhas this is a really good draft, I think there's a just few high-level changes you can make that will help you communicate the impact of the package you've spent so much time developing. Please see my suggestion about the abstract in the metadata.yaml. I would start there and then perhaps make some changes in the intro accordingly. I'm happy to do another more fine-grained review to catch any typos I might have missed, but let's help you get a strong message across first. Just let me know if any of my comments are unclear, I'm happy to discuss here further! Thank you

2023-06-23 16:43 UTC, NickleDave commented on papers/david_calhas/metadata.yaml
> +   - Recently, EEG to fMRI synthesis has received notable attention by the neuroscience research community. It enables both neuroimaging cross modal synthesis from EEG records to a synthesized fMRI a
```suggestion
   - Recently, EEG to fMRI synthesis has received notable attention from the neuroscience research community. It enables both neuroimaging cross modal synthesis from EEG records to a synthesized fMRI and fMRI augmented EEG diagnostics. EEG to fMRI is a Python package that provides this functionality, being the first open source software enabling neuroimaging synthesis. This package was developed for neuroscience, machine learning, and health care communities. We give a description of the methodology implemented in the package, along with results reported in a previous study.
```
- [ ] things receive attention from communities not by communities

2023-06-23 16:43 UTC, NickleDave commented on papers/david_calhas/metadata.yaml
> +   - Recently, EEG to fMRI synthesis has received notable attention by the neuroscience research community. It enables both neuroimaging cross modal synthesis from EEG records to a synthesized fMRI a
My read of the abstract is that it does not make high-level background clear enough. I think you also want it to then show the critical gap in the literature that you are addressing. 

For example, how about something like this?  

"Electroencepholography (EEG) and functional magnetic resonance imaging (fMRI) are two ways of recording brain activity; the former provides good time resolution but poor spatial resolution, while the converse is true for the latter. Recently, deep neural network models have been developed that can synthesize fMRI activity from EEG signals, and vice versa. Because these generative models simulate data, they make it easier for neuroscientists to test ideas about how EEG and fMRI signals relate to each other, and what both signals tell us about how the brain controls behavior. To make it easier for researchers to access these models, and to standardize how they are used, we developed a Python package, EEG-to-fMRI..."

You might want to read this if you are not familiar with it already: https://journals.plos.org/ploscompbiol/article?id=10.1371/journal.pcbi.1005619. See in particular rule 5, "Tell a complete story in the abstract".

2023-06-23 16:43 UTC, NickleDave commented on papers/david_calhas/main.tex
> +Neuronal activity, usually measured through electroencephalography (EEG), is related to haemodynamical acitivity, measured through functional magnetic resonance imaging (fMRI). The first captures the
```suggestion
Neuronal activity, usually measured through electroencephalography (EEG), is related to haemodynamical activity, measured through functional magnetic resonance imaging (fMRI). The first captures the dynamics of the electrical field, whose source is located from the firing neurons' action potentials. In its turn, the second measures the blood supply dynamics. These two while being studied simultaneously \cite{shibasaki2008human,yu2016building,he2018spatialtemporaldo,rojas2018study,brechet2019capturing,daly2019electroencephalography,cury2020sparse,abreu2021eeg} differ in many aspects such as: temporal and spatial resolution, brain functions captured, recording and hardware cost. Recently, we have seen the contribution of multiple studies that target a mapping function able to provide a synthesized fMRI view from an EEG signal. Such a mapping could allow health care cost reductions and discoveries of new neuroscience insights on the relationship between these two modalities. Indeed, pathologies that require MRI scans diagnostics benefit from a lower cost EEG assessment, since availability of MRI hardware is very scarce \cite{ogbole2018survey}. As Python \cite{van1995python} becomes a hub for scientific development \cite{harris2020array,virtanen2020scipy,abadi2016tensorflow} we find the need to provide open source software that provides solutions for \textit{EEG to fMRI synthesis}, urgent, in order for third party scientific contributions coming from other laboratories to coexist and health care software integration to develop for diagnostic settings. To that end, we provide a description of the open source software \href{https://pypi.org/project/eeg-to-fmri/}{EEG-to-fMRI}, which originated from an academic scientific project funded by FCT, and make publicly available a github \href{https://github.com/eeg-to-fmri/eeg-to-fmri}{repository}.
```

2023-06-23 16:43 UTC, NickleDave commented on papers/david_calhas/main.tex
> +Neuronal activity, usually measured through electroencephalography (EEG), is related to haemodynamical acitivity, measured through functional magnetic resonance imaging (fMRI). The first captures the
- [ ] 'haemodynamical acitivity' -> 'activity'

2023-06-23 16:43 UTC, NickleDave commented on papers/david_calhas/main.tex
> +Neuronal activity, usually measured through electroencephalography (EEG), is related to haemodynamical acitivity, measured through functional magnetic resonance imaging (fMRI). The first captures the
- [ ] Define FCT before you use it as an acronym. Especially if they are you funding source!

2023-06-23 16:43 UTC, NickleDave commented on papers/david_calhas/main.tex
> +Neuronal activity, usually measured through electroencephalography (EEG), is related to haemodynamical acitivity, measured through functional magnetic resonance imaging (fMRI). The first captures the
> Recently, we have seen the contribution of multiple studies that target a mapping function able to provide a synthesized fMRI view from an EEG signal.

You are correct of course that a so-called neural network model is really just a mathematical function that does a mapping. But I would suggest making it clearer for a broader audience that you are talking about deep neural network models here 

"Recently we have seen several studies that use deep neural network models (cite e.g. Goodfellow textbook) to learn a mapping from EEG data to and from fMRI data. These are a type of generative model (cite a relevant review here -- I don't know the models off the top of my head and you never name them)"

2023-06-23 16:43 UTC, NickleDave commented on papers/david_calhas/figures/diagram.png
I think it would be really helpful to here to demonstrate where EEG data comes from. Could you replace the stick figure with some sort of illustration of EEG electrodes? Maybe you could use example data from MNE and cite them, e.g. https://mne.tools/stable/auto_examples/decoding/decoding_csp_eeg.html#ex-decoding-csp-eeg?

2023-06-23 16:43 UTC, NickleDave commented on papers/david_calhas/main.tex
> +The mapping function provided in this software is the one proposed by \cite{calhas2022eeg}. It consists on transforming the EEG from a channel by time representation to a channel by time frequency on
```suggestion
The mapping function provided in this software is the one proposed by \cite{calhas2022eeg}. It consists on transforming the EEG from a channel by time representation to a channel by time-frequency one, achieved using the short time Fourier transform \cite{allen1977short} by means of the fast Fourier transform (\href{https://docs.scipy.org/doc/scipy/reference/generated/scipy.fft.fft.html}{scipy.fft.fft}) available in the SciPy package. The latter corresponds to the second step of the diagram illustrated in \ref{fig:pipeline}. In the second step, this representation is then forward through a deep neural network (implemented as a \href{https://www.tensorflow.org/api_docs/python/tf/keras/Model}{tf.keras.Model}), with contributions ranging from Resnet blocks \cite{he2016deep}, an automated machine learning framework \cite{calhas2022automatic} and Fourier features \cite{tancik2020fourier}. Ultimately, this enables the prediction of an fMRI volume associated with a $26$ second segment of an EEG recording. 
```
- [ ] 'time frequency one' -> 'time-frequency one'
- [ ] 'the SciPy' -> 'the SciPy package'

2023-06-23 16:43 UTC, NickleDave commented on papers/david_calhas/main.tex
> +    \item \textit{models}: here you will find the code that implements the models for synthesis and classification. The synthesis models are located in the \textit{synthesizers.py}, where the class \
```suggestion
    \item \textit{models}: here you will find the code that implements the models for synthesis and classification. The synthesis models are located in the \textit{synthesizers.py}, where the class \textit{EEG\_to\_fMRI} is implemented. This class defines a \textit{tf.keras.Model}, composed of two encoders, one for the EEG and another for the fMRI. Additionally, there is a decoder that maps the latent EEG representation, that is the output of the EEG encoder, to the estimate of the fMRI volume associated. The fMRI encoder is defined in the \textit{fmri\_ae.py} file. The task would not be complete without the extrapolation of the synthesis model to a classification task. To that end, two linear classifiers are provided, the \textit{ViewLatentContrastiveClassifier} and the \textit{ViewLatentLikelihoodClassifier}, corresponding to a contrastive latent loss and a cross entropy error driven classification, respectively. The extrapolation is simply made by taking the output of the neural flow that comes from the EEG
```
- [ ] Please define "neural flow"
- [ ] Removed semi-colon from end of paragraph
```suggestion
    \item \textit{models}: here you will find the code that implements the models for synthesis and classification. The synthesis models are located in the \textit{synthesizers.py}, where the class \textit{EEG\_to\_fMRI} is implemented. This class defines a \textit{tf.keras.Model}, composed of two encoders, one for the EEG and another for the fMRI. Additionally, there is a decoder that maps the latent EEG representation, that is the output of the EEG encoder, to the estimate of the fMRI volume associated. The fMRI encoder is defined in the \textit{fmri\_ae.py} file. The task would not be complete without the extrapolation of the synthesis model to a classification task. To that end, two linear classifiers are provided, the \textit{ViewLatentContrastiveClassifier} and the \textit{ViewLatentLikelihoodClassifier}, corresponding to a contrastive latent loss and a cross entropy error driven classification, respectively. The extrapolation is simply made by taking the output of the neural flow that comes from the EEG.
```

2023-06-23 16:43 UTC, NickleDave commented on papers/david_calhas/main.tex
> +Ultimately, the goal of this package is to ensemble, in one package, the scientific contributions in the area of EEG to fMRI synthesis. Works such as \cite{calhas2022eeg} and \cite{liu2019convolution
```suggestion
Ultimately, the goal of this package is to collect, in one package, methods for EEG to fMRI synthesis. We would welcome contributions from authors of related work such as \cite{calhas2022eeg} and \cite{liu2019convolutional}. In the future, we plan to add a module or example folder with implementations of these approaches, so that other research groups can easily access them and reproduce key results. 
```
- [ ] "to ensemble" -> "to collect"
- [ ] "the scientific contributions in the area of" -> "methods for"
- [ ] see additional suggestions for re-wording

2023-06-23 16:43 UTC, NickleDave commented on papers/david_calhas/main.tex
> +Ultimately, the goal of this package is to ensemble, in one package, the scientific contributions in the area of EEG to fMRI synthesis. Works such as \cite{calhas2022eeg} and \cite{liu2019convolution
It's a bit confusing you say "Works such as \cite{calhas2022eeg} ... should address their contributions and proceed with pull requests for contributions" here even though you say in the intro that "The mapping function provided in this software is the one proposed by \cite{calhas2022eeg}."

Are there additional methods in your 2022 paper that are not implemented in eeg-to-fmri yet? Please specify.

2023-06-23 16:43 UTC, NickleDave commented on papers/david_calhas/main.tex
> +We also provide a compressed version of the dataset of \cite{dataset2022fribourg}. This example is based on a public available dataset that contains individuals diagnosed with schizophrenia and healt
```suggestion
We also provide a compressed version of the dataset of \cite{dataset2022fribourg}. This example is based on a publicly available dataset that contains individuals diagnosed with schizophrenia and healthy controls. The whole goal of the project is to be applied in an health care setting and to this end we employ an end to end software solution. The whole software package is able to synthesize fMRI and adapt to a classification setting, that given EEG recordings outputs a set of probabilities for each group of people considered in the dataset.
```
- [ ] "public available" -> "publicly available"
- [ ] "given EEG recordings it" -> "given EEG recordings outputs"

2023-06-23 16:43 UTC, NickleDave commented on papers/david_calhas/main.tex
> +    \item \textit{layers}: this module contains the layers which compose the synthesizer models. Five main types of layers should be considered. First, the \textit{TopographicalAttention} computes a
```suggestion
    \item \textit{layers}: this module contains the layers which compose the synthesizer models. It provides five main types of layers. First, the \textit{TopographicalAttention} computes a self attention mechanism in the channels dimension of the EEG \cite{calhas2022eeg} that allows the representation to be correctly processed by the convolutional blocks. Second, the \textit{ResnetBlock} \cite{he2016deep} implements a residual block composed of convolutional layers. This block allows efficient gradient propagation,  by tackling the vanishing gradient phenomena. Third, the \textit{FourierFeatures} layer projects \textit{cosines} functions of different shifts and biases to build a latent spectral basis for the prediction of the fMRI volume. Fourth, the \textit{DenseVariational} is an implementation of the \textit{tf.keras.layers.Dense} layer for two-dimensional inputs, whose weights are drawn from gaussian distributions. Last, but not least, we provide the \textit{DCT} based layers, which implement the discrete cosine transform \cite{ahmed1974discrete}. These layers are useful for alternative ways of decoding the latent representation of the EEG to produce the desired fMRI volume.
```
Please consider revising as suggested

2023-06-23 16:43 UTC, NickleDave commented on papers/david_calhas/main.tex
> +    \caption{Output of the predicted fMRI when given an EEG representation. Note that, due to the EEG encoder being optimized towards classifying the data according to the groups of individuals defin
Please specify what exactly in the figure shows that there is a change in the produced fMRI because of how the EEG encoder is optimized.

2023-06-26 19:51 UTC, cbcunc commented
@DCalhas We are beyond the final review deadline. Would you please address the review comments and resolve them? @NickleDave has provided many of his reviews as commit-able suggestions should you choose to accept them. Thank you.

2023-06-26 20:21 UTC, DCalhas commented
> @DCalhas We are beyond the final review deadline. Would you please address the review comments and resolve them? @NickleDave has provided many of his reviews as commit-able suggestions should you choose to accept them. Thank you.

First and foremost, I want to thank the incredible feedback given by @NickleDave (reviews like this warm my heart). I'm planning on submitting a reviewed version of the article with the suggestions on wednesday.

2023-06-28 14:27 UTC, DCalhas commented on papers/david_calhas/main.tex
> +Ultimately, the goal of this package is to ensemble, in one package, the scientific contributions in the area of EEG to fMRI synthesis. Works such as \cite{calhas2022eeg} and \cite{liu2019convolution
Initially I didn't want to target the Liu study, could maybe feel as if I was attacking them. The whole package contains the code of the calhas2022eeg and more.

2023-06-28 14:31 UTC, DCalhas commented on papers/david_calhas/main.tex
> +    \item \textit{layers}: this module contains the layers which compose the synthesizer models. Five main types of layers should be considered. First, the \textit{TopographicalAttention} computes a
I really appreciate the rephrasing! Thank you!

2023-06-28 15:58 UTC, DCalhas commented on papers/david_calhas/figures/diagram.png
I placed a 10-20 system of electrodes diagram between stick figure and the raw recordings. I think having the humanoid stick helps the interpretation of the figure.

2023-06-28 16:01 UTC, DCalhas commented
> Hi @DCalhas this is a really good draft, I think there's a just few high-level changes you can make that will help you communicate the impact of the package you've spent so much time developing. Please see my suggestion about the abstract in the metadata.yaml. I would start there and then perhaps make some changes in the intro accordingly. I'm happy to do another more fine-grained review to catch any typos I might have missed, but let's help you get a strong message across first. Just let me know if any of my comments are unclear, I'm happy to discuss here further! Thank you

Thank you again for the incredible feedback you gave me. If you think there are still critical things to address after the update, please let me know as I'll gladly address it. Also the commitable suggestions were an amazing way of giving feedback as it is just a click a away in a sense.

2023-07-03 01:53 UTC, cbcunc commented
@scoobies mark pending comment

2023-07-10 01:23 UTC, cbcunc commented
@NickleDave, @vanessailana Are you satisfied with the latest update from @DCalhas or do this need more review?

2023-07-14 23:49 UTC, NickleDave commented on papers/david_calhas/main.tex
> +The dependencies of each component are described in an \href{https://github.com/eeg-to-fmri/eeg-to-fmri/blob/main/project_UML.pdf}{UML diagram}. Overall to install the package, the user is required t
Please use `\texttt` instead of `\textit` here and throughout the rest of the paper when referring to pacakges, functions, etc., so that those names render in monospace instead of italics

2023-07-14 23:50 UTC, NickleDave commented
Thank you @DCalhas for your revisions that I think have really improved the paper.

Overall I think we can go ahead and accept.

But before we do that, there is one minor formatting issue throughout the paper.  
Can you please replace `\textit` around in-line code in the text with `\texttt` so that it renders in monospace font instead of italics? 
E.g., here: https://github.com/scipy-conference/scipy_proceedings/pull/801/files#r1264248679
I'm sorry I didn't ask you to do this before.

2023-07-17 08:23 UTC, DCalhas commented
> Thank you @DCalhas for your revisions that I think have really improved the paper.
> 
> Overall I think we can go ahead and accept.
> 
> But before we do that, there is one minor formatting issue throughout the paper. Can you please replace `\textit` around in-line code in the text with `\texttt` so that it renders in monospace font instead of italics? E.g., here: https://github.com/scipy-conference/scipy_proceedings/pull/801/files#r1264248679 I'm sorry I didn't ask you to do this before.

Perfect! Thank you for the feedback!

2023-07-23 21:14 UTC, cbcunc commented
@scoobies check references

2023-07-23 21:14 UTC, scoobies commented
```
Reference check summary (note 'MISSING' DOIs are suggestions that need verification):

OK DOIs

- 10.3389/fnins.2014.00258 is OK

MISSING DOIs

- 10.11604/pamj.2018.30.240.14000 may be a valid DOI for title: Survey of magnetic resonance imaging availability in West Africa
- 10.1016/j.clinph.2007.10.026 may be a valid DOI for title: Human brain mapping: hemodynamic response and electrophysiology
- 10.3389/fnhum.2016.00476 may be a valid DOI for title: Building an EEG-fMRI multi-modal brain graph: a concurrent EEG-fMRI study
- 10.3389/fnins.2019.01451 may be a valid DOI for title: A sparse EEG-informed fMRI model for hybrid EEG-fMRI neurofeedback prediction
- 10.1007/s00429-018-1674-5 may be a valid DOI for title: Spatial–temporal dynamics of gesture–speech integration: a simultaneous EEG-fMRI study
- 10.3389/fnins.2018.00235 may be a valid DOI for title: Study of resting-state functional connectivity networks using EEG electrodes position as seed
- 10.1038/s41598-019-45105-2 may be a valid DOI for title: Electroencephalography reflects the activity of sub-cortical brain regions during approach-withdrawal behaviour while listening to music
- 10.1007/s10548-020-00805-1 may be a valid DOI for title: EEG microstates predict concurrent fMRI dynamic functional connectivity states
- 10.1109/tassp.1977.1162950 may be a valid DOI for title: Short term spectral analysis, synthesis, and modification by discrete Fourier transform
- 10.1109/cvpr.2016.90 may be a valid DOI for title: Deep residual learning for image recognition
- 10.1016/b978-0-08-092534-9.50007-2 may be a valid DOI for title: Discrete cosine transform
- 10.1371/journal.pone.0130140 may be a valid DOI for title: On pixel-wise explanations for non-linear classifier decisions by layer-wise relevance propagation
- 10.1109/tip.2003.819861 may be a valid DOI for title: Image quality assessment: from error visibility to structural similarity
- 10.1109/ner.2019.8716994 may be a valid DOI for title: A convolutional neural network for transcoding simultaneously acquired EEG-fMRI data

INVALID DOIs

- doi:10.18112/openneuro.ds004000.v1.0.0 is INVALID (failed connection)
```

2023-07-23 21:24 UTC, cbcunc commented
@DCalhas Would you please fix the above missing and invalid DOIs? (I think the invalid one just needs the removal the `doi:` protocol in the BibTex.)

2023-07-23 21:25 UTC, cbcunc commented
@NickleDave Does this paper meet with your final review approval?

2023-07-23 21:29 UTC, NickleDave commented
Hi @cbcunc yes it definitely does meet my approval, sorry for not being clearer above

https://github.com/scipy-conference/scipy_proceedings/pull/801#issuecomment-1636566002

Thank you again @DCalhas

2023-07-28 08:54 UTC, DCalhas commented
Hi! Sorry for the delayed answer, but I was away last week. @cbcunc the references are fixed with the suggested dois.

2023-07-28 19:06 UTC, cbcunc commented
@scoobies mark ready

2023-08-05 23:46 UTC, deniederhut approved these changes
Thanks @NickleDave for helping us get this paper ready for publication! And thanks @DCalhas for joining us at SciPy this year!

![tenor-802226076](https://github.com/scipy-conference/scipy_proceedings/assets/6868396/86d7f9a6-a0f1-4dff-bfb7-0763283e6a4a)

2023-08-05 23:46 UTC, merged