Paper: aPhyloGeo-Covid: A web interface for phylogeographic analysis of SARS-CoV-2 variation using Neo4j and Snakemake
scipy-conference/scipy_proceedings pull request #813
Opened 2023-05-29 23:23 UTC by TahiriNadia

If you are creating this PR in order to submit a draft of your paper,
see http://procbuild.scipy.org/ for logs generated by the build
process.

See the [project readme](https://github.com/scipy-conference/scipy_proceedings#build-your-paper)
for more information.

*Editor*:  

*Reviewers*:

2023-05-31 12:43 UTC, deniederhut commented
@scoobies mark paper

2023-05-31 12:44 UTC, deniederhut commented
@scoobies mark needs review

2023-06-03 14:57 UTC, deniederhut commented
@scoobies assign @cbcunc as editor

2023-06-03 14:57 UTC, scoobies commented
Assigned! @cbcunc is now the editor

2023-06-07 16:21 UTC, deniederhut commented
@scoobies add @cmahapatra97 to reviewers

2023-06-07 16:22 UTC, scoobies commented
@cmahapatra97 added to the reviewers list!

2023-06-07 16:22 UTC, deniederhut commented
@scoobies code of conduct

2023-06-07 16:22 UTC, scoobies commented
Our CoC: https://www.scipy2023.scipy.org/code-of-conduct

2023-06-07 16:22 UTC, scoobies commented
Reports of abusive or harassing behavior may be reported to scipy@enthought.com

2023-06-07 16:59 UTC, cbcunc commented
Editor says paper is complete and builds. Awaiting review.

2023-06-08 13:05 UTC, deniederhut commented
@scoobies add @EngineerKhan to reviewers

2023-06-08 13:05 UTC, scoobies commented
@EngineerKhan added to the reviewers list!

2023-06-11 23:26 UTC, deniederhut commented
@scoobies add @ferchaure to reviewers

2023-06-11 23:26 UTC, scoobies commented
@ferchaure added to the reviewers list!

2023-06-17 15:55 UTC, ferchaure requested changes
Hi Nadia, Amazing and really interesting work.

The only required change is adding the reference for Numpy and Pandas.
I added a few additional comments 


Cheers,
Fer

2023-06-17 15:55 UTC, ferchaure commented on papers/nadia_tahiri/00_bibderwalt.rst
> +   phylogeographical studies. Presently, the database encompasses over 113,774 nodes and 194,381 relationships. Once the input dataset is determined. Additionally, aPhyloGeo-Covid provides a scalable
The sentence "Once the input dataset is determined." like that is unrelated to the rest of the paragraph

2023-06-17 15:55 UTC, ferchaure commented on papers/nadia_tahiri/00_bibderwalt.rst
> +:cite:`taylor2020intercontinental` :cite:`aziz2022phylogeography`. To bridge this gap, a novel algorithm applying sliding windows to scan the genetic sequence information related to their climatic co
maybe the editors know a better way to cite multiple works to get something like: [15-18] that looks better that the current way

2023-06-17 15:55 UTC, ferchaure commented on papers/nadia_tahiri/00_bibderwalt.rst
> +To enable efficient querying, configuration of analysis parameters, and output generation within the database, a driver object was established using the Neo4j Python driver to establish seamless conn
Here you call it "Plotly-dash" but in other places Dash-Plotly, it's a bit confusing.

2023-06-17 15:55 UTC, ferchaure commented on papers/nadia_tahiri/00_bibderwalt.rst
> +.. figure:: figure1.png
I know that this is a screenshot... but maybe the font could be increased in a easy way?

2023-06-17 15:55 UTC, ferchaure commented on papers/nadia_tahiri/00_bibderwalt.rst
> +Various tools and software were utilized to accomplish these analysis tasks, including Biopython :cite:`cock2009biopython`, raxml-ng :cite:`kozlov2019raxml`, fasttree :cite:`price2009fasttree`, and P
Important: add references for Numpy and Pandas

2023-06-17 15:55 UTC, ferchaure commented on papers/nadia_tahiri/00_bibderwalt.rst
> +.. figure:: figure5.png
Did you try with bigger dots or bars? it's tricky see the patters or differences just with little dots far way

2023-06-17 15:55 UTC, ferchaure commented on papers/nadia_tahiri/00_bibderwalt.rst
> +In addition of correlation analysis between correlation diversity of subfregment of gene and climate condition, we also inferred the ORF1a phylogeny and window regions 792-940 of ORF1a using the RAxM
add somewhere: horizontal gene transfer (HGT)

2023-06-17 15:55 UTC, ferchaure commented on papers/nadia_tahiri/00_bibderwalt.rst
> +In the third iteration, an HGT was identified from subtree UJS65740 to subtrees QLL26045, QPJ77309, QPN02498, QWP89176, UJW68561, and WAV10885, with an RF of 4 and a bipartition dissimilarity of 2.5.
I personally get confuse with this type of paragraph, maybe a table or something with a structure format could be more clear

2023-06-21 13:08 UTC, EngineerKhan commented
Same thoughts as @ferchaure. I am not an expert on the topic, so my opinion should be taken with a grain of salt. Here are some minor suggested changes, though:

- In the abstract, "a wide range of" is unnecessary.
- "Throughout the COVID-19 pandemic, researchers......" – this is a new section and can be in a new paragraph.
- "Climate data can be obtained from reputable sources such as NASA/POWER DailyGridded weather" – climate data of? Can add more clarity.
- "The challenges associated with data collection, extraction, and integration have hindered the advancement of phylogeographic research within the field. " – I think a reference can be added to this statement.
- "To tackle these challenges, we employed....." – it can also be taken in a new paragraph.
- "To address these challenges, we devised a phylogeographic...." should also be a new paragraph.
- Reference 26 needs to be improved to reflect the better citation of Pandas, like [this](https://conference.scipy.org/proceedings/scipy2010/pdfs/mckinney.pdf).
- "In the subsequent phylogeographical analysis phase, our modularized Snakemake workflow is utilized to
examine how genetic variation patterns within different SARS-CoV-2 variants align with geographic features." – Comment: This line sounds unnecessary for the introduction. Feel free to disagree.
- "from the SARS-CoV-2 Data Hub [7]" – is it the correct reference?
- "population density by country, positivity rates, vaccination rates, diabetes rates, aging data" – sounds like too much info for a general reader.
- " Moreover, the interactive visualization capabilities offered by the Plotly-dash library" – Suggestion: we can add the Plotly-dash library's reference as well.
- The first paragraph of "Data Integration" section contains a lot of attributes and can have a table to complement it.
- "An interactive platform using Dash-Plotly [27] was developped" – please mind the typo.
- "The integration of the Dash platform with the Neo4j graph database allows for seamless retrieval of pertinent data from interconnected nodes based on user-provided keywords related to lineages or locations." – minor: "the" before "seamless retrieval."
- "The aPhyloGeo-Covid offers two distinct approaches for selecting input datasets" – Suggestion: I think these two options would be better off in 2 subheadings rather than 2 numbered sentences.
- "Subsequently, the Neo4j database was queried to identify lineages" – "was" or "is"?
- QUERY: Can we caption the code snippets? @scoobies 
- Suggestion: Fig 2 and 3 can be separated.
- "and the Neighbor-Joining clustering method [31]. " – don't think [31] is the right reference for that method.


Some general observations:
- Majority of references are review/comparative studies.
- At times, it gets verbose.
- Too many figures (numbers) within the text. Some of them can be better represented in tables.
- Is page limit (ref included) 8 or 9? @scoobies

2023-06-21 22:06 UTC, cmahapatra97 commented
Hi Nadia, 

Very interesting tool development to study SARS-CoV-2 variation. 
I suggest adding some lines on the pros of this model regarding other developed tools based on Neo4J. For example see Laddada W, Zanni-Merk C, Soualmia LF. Analyzing SARS-CoV-2 Sequence Patterns by Semantic Trajectories. Stud Health Technol Inform. 2022 Jun 29;295:197-200. doi: 10.3233/SHTI220696. PMID: 35773842.

Cheers,
Chit

2023-06-22 21:22 UTC, TahiriNadia commented on papers/nadia_tahiri/00_bibderwalt.rst
> +   phylogeographical studies. Presently, the database encompasses over 113,774 nodes and 194,381 relationships. Once the input dataset is determined. Additionally, aPhyloGeo-Covid provides a scalable
Thank you, @ferchaure , for your comment and suggestions. We agree, and the appropriate modifications have been incorporated by deleting the sentence.

2023-06-22 21:28 UTC, TahiriNadia commented on papers/nadia_tahiri/00_bibderwalt.rst
> +:cite:`taylor2020intercontinental` :cite:`aziz2022phylogeography`. To bridge this gap, a novel algorithm applying sliding windows to scan the genetic sequence information related to their climatic co
Once again, thank you for raising this point, with which we agree. While we may not know how to accomplish it ourselves, we believe that @deniederhut t or @cbcunc might possess the knowledge and expertise to do so.

2023-06-24 14:37 UTC, WanlinLi2021 commented on papers/nadia_tahiri/00_bibderwalt.rst
> +To enable efficient querying, configuration of analysis parameters, and output generation within the database, a driver object was established using the Neo4j Python driver to establish seamless conn
Thank you for bringing this issue to my attention. We replaced "Plotly-dash" with "Dash-Plotly" to maintain consistency throughout the article.

2023-06-24 14:44 UTC, WanlinLi2021 commented on papers/nadia_tahiri/00_bibderwalt.rst
> +.. figure:: figure1.png
Thank you. We acknowledge that utilizing screenshots does not meet the desired image quality standards, lacks reader-friendliness, and fails to highlight key information effectively. Consequently, we have considered your suggestion and have re-created the images using Drawio to enhance the overall quality.

2023-06-24 15:13 UTC, WanlinLi2021 commented on papers/nadia_tahiri/00_bibderwalt.rst
> +Various tools and software were utilized to accomplish these analysis tasks, including Biopython :cite:`cock2009biopython`, raxml-ng :cite:`kozlov2019raxml`, fasttree :cite:`price2009fasttree`, and P
Thank you for bringing this issue to my attention. I appreciate your feedback. In response to your suggestion, we have now included references for Numpy and Pandas in the article.

2023-06-24 16:31 UTC, WanlinLi2021 commented on papers/nadia_tahiri/00_bibderwalt.rst
> +In addition of correlation analysis between correlation diversity of subfregment of gene and climate condition, we also inferred the ORF1a phylogeny and window regions 792-940 of ORF1a using the RAxM
Thank you for your suggestion. Yes, it is essential to clarify abbreviations before using them consistently throughout the text. In response to your feedback, we have added "horizontal gene transfer (HGT)" in the sentence where we initially introduced the concept of horizontal gene transfer.

2023-06-25 19:39 UTC, TahiriNadia commented
@scoobies build paper

2023-06-25 19:39 UTC, scoobies commented
building paper...

2023-06-25 19:39 UTC, scoobies commented
{"data"=>{"info"=>"Build for paper tahiri-lab-2023 scheduled.  Note that builds are only executed if the current build attempt is more than 5 minutes old."}, "status"=>"success"}

2023-06-26 01:17 UTC, WanlinLi2021 commented on papers/nadia_tahiri/00_bibderwalt.rst
> +In the third iteration, an HGT was identified from subtree UJS65740 to subtrees QLL26045, QPJ77309, QPN02498, QWP89176, UJW68561, and WAV10885, with an RF of 4 and a bipartition dissimilarity of 2.5.
Thank you for the observation. We greatly appreciate it. To ensure conciseness and clarity, we have revised the paragraph concerning transfer-recombination analysis (HGT). Additionally, we have included a table to enhance the clarity of the information presented.

2023-06-26 01:20 UTC, WanlinLi2021 commented on papers/nadia_tahiri/00_bibderwalt.rst
> +.. figure:: figure5.png
Thank you for your suggestion. We have improved the quality of this figure by increasing the size of the dots.

2023-06-26 01:20 UTC, TahiriNadia commented
> Same thoughts as @ferchaure. I am not an expert on the topic, so my opinion should be taken with a grain of salt. Here are some minor suggested changes, though:
> 
> * In the abstract, "a wide range of" is unnecessary.
> * "Throughout the COVID-19 pandemic, researchers......" – this is a new section and can be in a new paragraph.
> * "Climate data can be obtained from reputable sources such as NASA/POWER DailyGridded weather" – climate data of? Can add more clarity.
> * "The challenges associated with data collection, extraction, and integration have hindered the advancement of phylogeographic research within the field. " – I think a reference can be added to this statement.
> * "To tackle these challenges, we employed....." – it can also be taken in a new paragraph.
> * "To address these challenges, we devised a phylogeographic...." should also be a new paragraph.
> * Reference 26 needs to be improved to reflect the better citation of Pandas, like [this](https://conference.scipy.org/proceedings/scipy2010/pdfs/mckinney.pdf).
> * "In the subsequent phylogeographical analysis phase, our modularized Snakemake workflow is utilized to
>   examine how genetic variation patterns within different SARS-CoV-2 variants align with geographic features." – Comment: This line sounds unnecessary for the introduction. Feel free to disagree.
> * "from the SARS-CoV-2 Data Hub [7]" – is it the correct reference?
> * "population density by country, positivity rates, vaccination rates, diabetes rates, aging data" – sounds like too much info for a general reader.
> * " Moreover, the interactive visualization capabilities offered by the Plotly-dash library" – Suggestion: we can add the Plotly-dash library's reference as well.
> * The first paragraph of "Data Integration" section contains a lot of attributes and can have a table to complement it.
> * "An interactive platform using Dash-Plotly [27] was developped" – please mind the typo.
> * "The integration of the Dash platform with the Neo4j graph database allows for seamless retrieval of pertinent data from interconnected nodes based on user-provided keywords related to lineages or locations." – minor: "the" before "seamless retrieval."
> * "The aPhyloGeo-Covid offers two distinct approaches for selecting input datasets" – Suggestion: I think these two options would be better off in 2 subheadings rather than 2 numbered sentences.
> * "Subsequently, the Neo4j database was queried to identify lineages" – "was" or "is"?
> * QUERY: Can we caption the code snippets? @scoobies
> * Suggestion: Fig 2 and 3 can be separated.
> * "and the Neighbor-Joining clustering method [31]. " – don't think [31] is the right reference for that method.
> 
> Some general observations:
> 
> * Majority of references are review/comparative studies.
> * At times, it gets verbose.
> * Too many figures (numbers) within the text. Some of them can be better represented in tables.
> * Is page limit (ref included) 8 or 9? @scoobies

✅ In the abstract, "a wide range of" is unnecessary. 

Thank you for your suggestion. We agree that the phrase "a wide range of" is redundant. Therefore, we have removed it from the text. 

✅ "Throughout the COVID-19 pandemic, researchers......" – this is a new section and can be in a new paragraph. 

We appreciate the suggestion. We also believe that separating it into a new section will enhance clarity. We have taken your advice and incorporated the content into a new section. 

✅ "Climate data can be obtained from reputable sources such as NASA/POWER DailyGridded weather" – climate data of? Can add more clarity. 

Thank you for the suggestion. In order to enhance clarity when referring to the climate data, we have optimized the sentence as follows: "Daily climate data (e.g., humidity, wind speed, and temperature) for each location involved during the pandemic can be obtained from reputable sources such as NASA/POWER DailyGridded Weather." This revision aims to provide more clarity and guidance to readers. 

✅ "The challenges associated with data collection, extraction, and integration have hindered the advancement of phylogeographic research within the field. " – I think a reference can be added to this statement. 

Thank you for your suggestion. We greatly appreciate it. We have taken action by including two additional references to substantiate the information presented. 

✅ "To tackle these challenges, we employed....." – it can also be taken in a new paragraph. 

We appreciate the suggestion. We also believe that separating it into a new section will enhance clarity. We have taken your advice and incorporated the content into a new section, making it easier for readers to locate and understand. 

✅ "To address these challenges, we devised a phylogeographic...." should also be a new paragraph. 

We appreciate the suggestion. We have taken your advice and incorporated the content into a new section. 

✅ Reference 26 needs to be improved to reflect the better citation of Pandas, like [this](https://conference.scipy.org/proceedings/scipy2010/pdfs/mckinney.pdf). 

Thank you for bringing this issue to our attention. We appreciate your feedback. In response to your suggestion, we have now included this reference for Pandas in the article. 

✅ "In the subsequent phylogeographical analysis phase, our modularized Snakemake workflow is utilized to examine how genetic variation patterns within different SARS-CoV-2 variants align with geographic features." – Comment: This line sounds unnecessary for the introduction. Feel free to disagree. 

Thank you for your suggestion. Upon careful consideration, we have decided to retain this line, as it offers a comprehensive overview of the Snakemake section. We believe that including this line will assist readers in understanding the Snakemake portion before delving into the Methodology section. 

✅ "from the SARS-CoV-2 Data Hub [7]" – is it the correct reference? 

Thanks for the reminder. We agree and have added the reference given directly to the SARS-CoV-2 Data Hub website (https://www.ncbi.nlm.nih.gov/labs/virus/vssi/docs/participate/#how-to-cite-us). 

✅ "population density by country, positivity rates, vaccination rates, diabetes rates, aging data" – sounds like too much info for a general reader. 

Thank you for bringing this issue to our attention. In order to facilitate comprehension for general readers, we have divided the long sentences into concise lists. Additionally, we have included Table 1 to provide a clear and accessible representation of the information for easy understanding. 

✅ " Moreover, the interactive visualization capabilities offered by the Plotly-dash library" – Suggestion: we can add the Plotly-dash library's reference as well. 

I sincerely appreciate your suggestion. In response, we have added two references to support further the information provided. One of the references aligns with the suggestion provided by the Plotly Community (source: https://community.plotly.com/t/citing-plotly-and-dash-in-academic-papers/33045). Additionally, we have included a review of Dynamic Dashboards, which include the Dash-Plotly component. 

✅ The first paragraph of "Data Integration" section contains a lot of attributes and can have a table to complement it. 

Thank you for your suggestion. In order to enhance clarity and facilitate understanding, we have incorporated a table into this section. 

✅ "An interactive platform using Dash-Plotly [27] was developped" – please mind the typo. 

Thank you very much for the reminder. We apologize for this mistake. We should have used "developed". We have changed it accordingly. Thanks again. 

✅ "The integration of the Dash platform with the Neo4j graph database allows for seamless retrieval of pertinent data from interconnected nodes based on user-provided keywords related to lineages or locations." – minor: "the" before "seamless retrieval." 

Thank you for this note. We added "the" before "seamless retrieval." 

✅ "The aPhyloGeo-C [...]

2023-06-26 01:31 UTC, TahiriNadia commented
> Hi Nadia,
> 
> Very interesting tool development to study SARS-CoV-2 variation. I suggest adding some lines on the pros of this model regarding other developed tools based on Neo4J. For example see Laddada W, Zanni-Merk C, Soualmia LF. Analyzing SARS-CoV-2 Sequence Patterns by Semantic Trajectories. Stud Health Technol Inform. 2022 Jun 29;295:197-200. doi: 10.3233/SHTI220696. PMID: 35773842.
> 
> Cheers, Chit

Thank you, @cmahapatra97, for recommending this literature. The article is impressive with the application of Graph theory to mutation tracking. It highlights the advantages of Neo4j in relation analysis. Therefore, we have added a related discussion in the Introduction section.

2023-07-02 14:18 UTC, ferchaure approved these changes

2023-07-03 01:53 UTC, cbcunc commented
@scoobies mark pending comment

2023-07-04 06:06 UTC, EngineerKhan commented
Thanks a lot, @TahiriNadia for taking my suggestions positively. I was away on vacation, so apologies for the late reply/verification.

2023-07-23 21:12 UTC, cbcunc commented
@EngineerKhan does this paper meet your final review approval?

2023-07-23 21:13 UTC, cbcunc commented
@scoobies check references

2023-07-23 21:13 UTC, scoobies commented
Checking the BibTeX entries failed with the following error: 
```
Lexical or syntactical errors: 

@article{khan2021structurestitle={Structures of SARS-CoV-2 RNA-binding proteins and therapeutic targets},author={Khan, Muhammad Tahir and Irfan, Muhammad and Ahsan, Hina and Ahmed, Abrar and Kaushik, Aman Chandra and Khan, Anwar Sheed and Chinnasamy, Sathishkumar and Ali, Arif and Wei, Dong-Qing},journal={Intervirology},volume={64},number={2},pages={55--68},year={2021},publisher={Karger Publishers},doi=“
@article{ni2023structuraltitle={Structural insights into ribonucleoprotein dissociation by nucleocapsid protein interacting with non-structural protein 3 in SARS-CoV-2},author={Ni, Xincheng and Han, Yinze and Zhou, Renjie and Zhou, Yanmei and Lei, Jian},journal={Communications Biology},volume={6},number={1},pages={193},year={2023},publisher={Nature Publishing Group UK London},doi=“
@article{waterhouse2018swisstitle={SWISS-MODEL: homology modelling of protein structures and complexes},author={Waterhouse, Andrew and Bertoni, Martino and Bienert, Stefan and Studer, Gabriel and Tauriello, Gerardo and Gumienny, Rafal and Heer, Florian T and de Beer, Tjaart A P and Rempfer, Christine and Bordoli, Lorenza and others},journal={Nucleic acids research},volume={46},number={W1},pages={W296--W303},year={2018},publisher={Oxford University Press},doi=“
```

2023-07-23 21:21 UTC, cbcunc commented
@TahiriNadia Would you please fix the above BibTex DOI errors? I think they need to go inside curly braces rather than quotes?

2023-07-28 19:28 UTC, cbcunc commented
@scoobies check references

2023-07-28 19:29 UTC, scoobies commented
Checking the BibTeX entries failed with the following error: 
```
Lexical or syntactical errors: 

@article{khan2021structurestitle={Structures of SARS-CoV-2 RNA-binding proteins and therapeutic targets},author={Khan, Muhammad Tahir and Irfan, Muhammad and Ahsan, Hina and Ahmed, Abrar and Kaushik, Aman Chandra and Khan, Anwar Sheed and Chinnasamy, Sathishkumar and Ali, Arif and Wei, Dong-Qing},journal={Intervirology},volume={64},number={2},pages={55--68},year={2021},publisher={Karger Publishers},doi=“
@article{ni2023structuraltitle={Structural insights into ribonucleoprotein dissociation by nucleocapsid protein interacting with non-structural protein 3 in SARS-CoV-2},author={Ni, Xincheng and Han, Yinze and Zhou, Renjie and Zhou, Yanmei and Lei, Jian},journal={Communications Biology},volume={6},number={1},pages={193},year={2023},publisher={Nature Publishing Group UK London},doi=“
@article{waterhouse2018swisstitle={SWISS-MODEL: homology modelling of protein structures and complexes},author={Waterhouse, Andrew and Bertoni, Martino and Bienert, Stefan and Studer, Gabriel and Tauriello, Gerardo and Gumienny, Rafal and Heer, Florian T and de Beer, Tjaart A P and Rempfer, Christine and Bordoli, Lorenza and others},journal={Nucleic acids research},volume={46},number={W1},pages={W296--W303},year={2018},publisher={Oxford University Press},doi=“
```

2023-07-28 19:39 UTC, cbcunc commented
@TahiriNadia We figured out what's wrong with the DOIs. They are quoted with smart quotes instead of straight quotes. Would you please this? We are having a final review today and this is one of the few papers which are not ready,

2023-07-28 19:59 UTC, WanlinLi2021 commented
> @TahiriNadia We figured out what's wrong with the DOIs. They are quoted with smart quotes instead of straight quotes. Would you please this? We are having a final review today and this is one of the few papers which are not ready.

Thank you very much for the reminder. Sorry for not responding in time. I have made corrections to the QUOTES for these references.

2023-07-28 21:03 UTC, cbcunc commented
@scoobies check references

2023-07-28 21:03 UTC, scoobies commented
```
Reference check summary (note 'MISSING' DOIs are suggestions that need verification):

OK DOIs

- 10.1111/mec.15222 is OK
- 10.1073/pnas.2218012120 is OK
- 10.1111/tbed.14556 is OK
- 10.1111/mec.15991 is OK
- 10.1046/j.1365-294X.2003.02051.x is OK
- 10.12688/wellcomeopenres.16661.2 is OK
- 10.1093/nar/gku1207 is OK
- 10.46234/ccdcw2021.255 is OK
- 10.1016/j.heliyon.2021.e06625 is OK
- 10.1038/s41562-021-01122-8 is OK
- 10.1109/ICDEW.2012.31 is OK
- 10.5220/0006356003510356 is OK
- 10.1046/j.0962-1083.2001.01350.x is OK
- 10.1371/journal.pbio.0020442 is OK
- 10.1038/s41598-020-58743-8 is OK
- 10.3354/esr01188 is OK
- 10.25080/majora-212e5952-018 is OK
- 10.1016/0025-5564(81)90043-2 is OK
- 10.1093/bioinformatics/bty350 is OK
- 10.1093/nar/gkaa434 is OK
- 10.1016/j.future.2023.01.009 is OK
- 10.1038/s41592-021-01254-9 is OK
- 10.1093/bioinformatics/btp163 is OK
- 10.3153/AR19009 is OK
- 10.1145/1900008.1900067 is OK
- 10.1093/database/baab026 is OK
- 10.1007/978-1-4842-0022-3_9 is OK
- 10.1093/molbev/mst010 is OK
- 10.1016/j.sbi.2006.04.004 is OK
- 10.1007/s00453-007-9116-4 is OK
- 10.1093/oxfordjournals.molbev.a040454 is OK
- 10.1093/bioinformatics/btz305 is OK
- 10.1093/molbev/msp077 is OK
- 10.1007/978-3-030-78829-2_9 is OK
- 10.1159/000513686 is OK
- 10.1038/s42003-023-04570-2 is OK
- 10.1093/nar/gky427 is OK
- 10.1093/nar/gks485 is OK
- 10.1016/S0092-8674(00)00175-6 is OK
- 10.1186/s12862-020-01732-2 is OK
- 10.1093/nar/gkr735 is OK
- 10.1109/MCSE.2011.37 is OK
- 10.1007/978-1-4842-0241-8_5 is OK
- 10.1111/jbi.14481 is OK
- 10.1016/j.ympev.2011.12.007 is OK
- 10.1093/nar/gkw1065 is OK
- 10.25080/Majora-7ddc1dd1-012 is OK
- 10.25080/Majora-92bf1922-00a is OK
- 10.3233/SHTI220696 is OK

MISSING DOIs

- None

INVALID DOIs

- None
```

2023-07-28 21:04 UTC, cbcunc commented
@scoobies mark ready

2023-07-29 01:37 UTC, TahiriNadia commented
> @TahiriNadia Would you please fix the above BibTex DOI errors? I think they need to go inside curly braces rather than quotes?

Thank you, @cbcunc.

2023-08-05 23:35 UTC, deniederhut approved these changes
Thanks @cmahapatra97, @EngineerKhan, and @ferchaure for your help getting this paper ready for publication! And thanks to @TahiriNadia for joining us at SciPy this year (and many other years)!!!

![giphy-1806883251](https://github.com/scipy-conference/scipy_proceedings/assets/6868396/cffb5145-9c50-4145-b0b8-8408ff024e67)

2023-08-05 23:35 UTC, merged