Paper for the 'Fast Exploration of the Milky Way (or any other n-dimensional dataset)' talk
scipy-conference/scipy_proceedings pull request #815
Opened 2023-06-01 17:26 UTC by FrancescAlted

If you are creating this PR in order to submit a draft of your paper,
see http://procbuild.scipy.org/ for logs generated by the build
process.

See the [project readme](https://github.com/scipy-conference/scipy_proceedings#build-your-paper)
for more information.

*Editor*:  

*Reviewers*:

2023-06-03 14:57 UTC, deniederhut commented
@scoobies assign @mepa as editor

2023-06-03 14:57 UTC, scoobies commented
Assigned! @mepa is now the editor

2023-06-03 21:17 UTC, mepa commented
@scoobies build status

2023-06-03 21:17 UTC, scoobies commented
{"Blosc-2023"=>{"data"=>{"build_output"=>"[*] Updating proceedings build tools in {self.master_repo_path}...\nAlready up to date.\n[*] Check out paper repository...\nCloning into '/tmp/tmpml3tblzc'...\nMoving proceedings build tools to temp directory...\n[*] Build the paper...\nBuilding: Francesc_Alted\n*** Warning: /tmp/tmpml3tblzc/publisher/../output/Francesc_Alted/paper_stats.json does not exist.\n", "build_pdf_path"=>"/procbuild/procbuild/../cache/Blosc-2023.pdf", "build_status"=>"success", "build_timestamp"=>"02/06 22:09"}, "status"=>"success"}}

2023-06-03 21:17 UTC, mepa commented
@scoobies check references

2023-06-03 21:18 UTC, scoobies commented
```
Reference check summary (note 'MISSING' DOIs are suggestions that need verification):

OK DOIs

- 10.5281/zenodo.7971911 is OK

MISSING DOIs

- None

INVALID DOIs

- 10.5555/2220076.2220212 is INVALID
```

2023-06-05 07:47 UTC, mepa commented on papers/Francesc_Alted/Blosc2_NDim.rst
> +To be completed ...
Hi @FrancescAlted, do you have an estimate for when this will be completed?

2023-06-05 09:38 UTC, FrancescAlted commented on papers/Francesc_Alted/Blosc2_NDim.rst
> +To be completed ...
The visualization code is work in progress right now.  We will be working on it for the next 2 or 3 weeks or so.  Is that acceptable?

2023-06-06 00:17 UTC, mepa commented on papers/Francesc_Alted/Blosc2_NDim.rst
> +To be completed ...
Thanks. As long as reviewers have time to complete their comments it is fine. Here are the reviewer deadlines: https://github.com/scipy-conference/scipy_proceedings#reviewer-deadlines.

2023-06-06 22:03 UTC, deniederhut commented
@scoobies add @shaswatshah to reviewers

2023-06-06 22:03 UTC, scoobies commented
@shaswatshah added to the reviewers list!

2023-06-06 22:04 UTC, deniederhut commented
@scoobies code of conduct

2023-06-06 22:04 UTC, scoobies commented
Our CoC: https://www.scipy2023.scipy.org/code-of-conduct

2023-06-06 22:04 UTC, scoobies commented
Reports of abusive or harassing behavior may be reported to scipy@enthought.com

2023-06-09 22:28 UTC, deniederhut commented
@scoobies add @ankitvaibhava to reviewers

2023-06-09 22:28 UTC, scoobies commented
@ankitvaibhava added to the reviewers list!

2023-06-18 22:20 UTC, mepa commented
Hey @shaswatshah and @ankitvaibhava! A friendly reminder that your initial review is due Friday, June 23rd.

2023-06-23 18:55 UTC, shaswatshah commented on papers/Francesc_Alted/Blosc2_NDim.rst
> +Blosc2 NDim is a new feature of Blosc2 that allows to create and read n-dimensional datasets in an extremely efficient way thanks to a completely general n-dim 2-level partitioning, allowing to slice
```suggestion
Blosc2 NDim is a new feature of Blosc2 that allows one to create and read n-dimensional datasets in an extremely efficient way thanks to a completely general n-dim 2-level partitioning, letting one slice and dice arbitrary large (and compressed!) data in a more fine-grained way. Having a second partition provides more flexibility to fit different partitions at different CPU cache levels, making compression even more efficient.
```
nits: grammar for better readability

2023-06-23 18:56 UTC, shaswatshah commented on papers/Francesc_Alted/Blosc2_NDim.rst
> +Finding the right compression parameters for the data is probably the most difficult part of using a compression library. Which combination of code and filter would provide the best compression ratio
```suggestion
Finding the right compression parameters for the data is probably the most difficult part of using a compression library. Which combination of code and filters would provide the best compression ratio? Which one would provide the best compression/decompression speed?
```

2023-06-23 18:59 UTC, shaswatshah commented on papers/Francesc_Alted/Blosc2_NDim.rst
> +BTune is an AI tool for Blosc2 that automatically finds the optimal combination of compression parameters to suit the user needs. It uses a neural network that is trained on the most representative d
```suggestion
BTune is an AI tool for Blosc2 that automatically finds the optimal combination of compression parameters to suit user needs. It uses a neural network trained on representative datasets to be compressed to predict the best compression parameters based on the given tradeoff between compression ratio and compression/decompression speed.
```

2023-06-23 20:12 UTC, shaswatshah reviewed
This is pretty good shape. Left a few nits/suggestions about grammar.
However, I think this could benefit from a bit more detail on the NDim feature. For example, something along the lines of this excerpt from https://www.blosc.org/posts/blosc2-ndim-intro/
`With Blosc2 NDim we are taking this feature a step further and both partitions, known as chunks and blocks, are gaining multidimensional capabilities meaning that one can split some dataset (super-chunk in Blosc2 parlance) in such a n-dim cubes and sub-cubes:

/images/blosc2-ndim-intro/b2nd-2level-parts.png
With these more fine-grained cubes (aka partitions), it is possible to retrieve arbitrary n-dim slices more rapidly because you don't have to decompress all the data that is necessary for the more coarse-grained partitions typical in other libraries.

For example, for a 4-d array with a shape of (50, 100, 300, 250) with float64 items, we can choose a chunk with shape (10, 25, 50, 50) and a block with shape (3, 5, 10, 20) which makes for about 5 MB and 23 KB respectively. This way, a chunk fits comfortably on a L3 cache in most of modern CPUs, and a block in a L1 cache (we are tuning for speed here). `

2023-06-24 02:07 UTC, ankitvaibhava commented on papers/Francesc_Alted/Blosc2_NDim.rst
> +Using Blosc2 NDim As A Fast Explorer Of The Milky Way (Or Any Other NDim Dataset)
The title draws attention to the exploration of the milky way rather focus on the algorithm. I would suggest something like "Blosc2 NDim: A Blosc extension to assist the efficient exploration of the high dimensional datasets"

2023-06-24 03:13 UTC, ankitvaibhava requested changes
While I admire the effort made by the authors on this work, a lot of changes are needed. 
1. The authors have to decide whether it is the demonstration of Blosc2 Ndim on the Milky-way dataset or a review of Blosc2 Ndim itself since a section such as "support for multiple codecs ..." does not seem to be relevant here if they want to demonstrate Blosc2 Ndim on the milky-way dataset.
2. The paper needs to be reorganized as 1) an Introduction about the problem and challenges and why Blosc2 is needed, 2) What is "Blosc2 NDim" and how this work, explain the autotuning and filters here, 3) explaining the format of the dataset, an example of a milky-way image such as figure 2,  4) The code  5) The results and observation after the Blosc2 is applied on the dataset such as speedup, compression 6) conclusions.
3. A grammar check for the manuscript is required. 
4. Numbering and sub-numbering of sections is required.

2023-06-24 03:13 UTC, ashriva16 commented on papers/Francesc_Alted/Blosc2_NDim.rst
> +    N-dimensional datasets are widely used in many scientific fields. Quickly accessing subsets of these large datasets is critical for an efficient exploration experience. To achieve this goal, we h
Here in the "N-dimensional dataset," N is not defined (N ca"N-dimensional dataset," N is not defined (N can be 2 or 3, which is not large). Instead, use the term "high-dimensional" everywhere wherever "n-dimensional" is used.

2023-06-24 03:13 UTC, ashriva16 commented on papers/Francesc_Alted/Blosc2_NDim.rst
> +    N-dimensional datasets are widely used in many scientific fields. Quickly accessing subsets of these large datasets is critical for an efficient exploration experience. To achieve this goal, we h
My Suggestion is to rewrite the abstract. I have provided an example. I would suggest the authors to rewrite in a similar way.
Abstract:
Large dimensional datasets have been widely used in various engineering and scientific applications. Prompt access to the subsets of these datasets is crucial for an efficient exploration experience. To facilitate this experience, we have added support for large dimensional datasets to Blosc2, a compression and format library. The extension to the library can effectively support large dimensional sparse datasets by suppressing the zero elements and compressing the non-zero elements. In addition to this, the new two-level data partition used in Blosc2 reduces the need for decompressing unnecessary data, further accelerating slicing speed.

2023-06-24 03:13 UTC, ashriva16 commented on papers/Francesc_Alted/Blosc2_NDim.rst
> +    N-dimensional datasets are widely used in many scientific fields. Quickly accessing subsets of these large datasets is critical for an efficient exploration experience. To achieve this goal, we h
I do not understand the meaning of "suppress" used here. Does it mean compress or deletion?

2023-06-24 03:13 UTC, ashriva16 commented on papers/Francesc_Alted/Blosc2_NDim.rst
> +    The Blosc2 NDim layer enables the creation and reading of n-dimensional datasets in an extremely efficient manner. This is due to a completely general n-dim 2-level partitioning, which allows for
Again replace "n-dimensional" with "high dimensional"

2023-06-24 03:13 UTC, ashriva16 commented on papers/Francesc_Alted/Blosc2_NDim.rst
> +The exploration of n-dimensional datasets is a common practice in many areas of science. However, one of its drawbacks is that the explored datasets size can become very large, which will slow down t
Instead of "The exploration of n-dimensional datasets is a common practice in many areas of science. However, one of its drawbacks is that the explored datasets size can become very large, which will slow down the exploration process significantly" 

I will suggest the following: 
"The exploration of datasets that are high dimensional is a common practice in various fields of science. However, exploring such high-dimensional datasets is challenging when the memory size of the dataset is extremely large. This can slow down the data exploration process significantly"

2023-06-24 03:13 UTC, ashriva16 commented on papers/Francesc_Alted/Blosc2_NDim.rst
> +Blosc uses the blocking technique :cite:`FA10-starving-cpus` to minimize activity on the memory bus. The technique divides datasets into blocks small enough to fit in the caches of modern processors,
Mention the full form of SIMD, since used for the first time " single-instruction multiple-data streams (SIMD)"

2023-06-24 03:13 UTC, ashriva16 commented on papers/Francesc_Alted/Blosc2_NDim.rst
> +The Gaia dataset
I would suggest the name to be "Milky Way dataset" as the title. Later Gaia dataset can be mentioned

2023-06-24 03:13 UTC, ashriva16 commented on papers/Francesc_Alted/Blosc2_NDim.rst
> +However, we converted the tabular dataset into a sphere with a radius of 10,000 light years and framed it into a 3D array of shape (20,000, 20,000, 20,000). Each cell in the array represents a cube o
How did you arrive at the values (20,000, 20,000, 20,000)

2023-06-24 03:13 UTC, ashriva16 commented on papers/Francesc_Alted/Blosc2_NDim.rst
> +However, we converted the tabular dataset into a sphere with a radius of 10,000 light years and framed it into a 3D array of shape (20,000, 20,000, 20,000). Each cell in the array represents a cube o
Instead of " Each cell in the array represents a cube of 1 light year per side and contains the number of stars within it.", I would suggest "Each cell represents the number of stars present in a cube of size 1 light year"

2023-06-24 03:13 UTC, ashriva16 commented on papers/Francesc_Alted/Blosc2_NDim.rst
> +The number of stars is stored as a uint8, resulting in a total dataset size of 7.3 TB. However, compression can greatly reduce its size to 6.5 GB since the 3D array is very sparse. Blosc2 can compres
Suggest the rewrite of "The number of stars is stored as a uint8, resulting in a total dataset size of 7.3 TB." as "Ideally, if the total size of the 3-dimensional array, representing the number of stars, stored as a uint8 would be 7.3 TB."

2023-06-24 03:13 UTC, ashriva16 commented on papers/Francesc_Alted/Blosc2_NDim.rst
> +The number of stars is stored as a uint8, resulting in a total dataset size of 7.3 TB. However, compression can greatly reduce its size to 6.5 GB since the 3D array is very sparse. Blosc2 can compres
How did you arrive at value of "6.5 GB"?

2023-06-24 03:13 UTC, ashriva16 commented on papers/Francesc_Alted/Blosc2_NDim.rst
> +The number of stars is stored as a uint8, resulting in a total dataset size of 7.3 TB. However, compression can greatly reduce its size to 6.5 GB since the 3D array is very sparse. Blosc2 can compres
This paragraph is the result of the Bloc2 algorithm. Hence should be discussed after the Bloc2 algorithm is explained.

2023-06-24 03:13 UTC, ashriva16 commented on papers/Francesc_Alted/Blosc2_NDim.rst
> +In addition, we store other data about the stars in a separate table indexed with the position of each star (using PyTables). For demonstration purposes, we store the radial velocity, effective tempe
Again, please provide some detail about the Bloc2 algorithm. Or discuss the results in a section separate from the dataset section.

2023-06-24 03:13 UTC, ashriva16 commented on papers/Francesc_Alted/Blosc2_NDim.rst
> +In addition, we store other data about the stars in a separate table indexed with the position of each star (using PyTables). For demonstration purposes, we store the radial velocity, effective tempe
The values of compression do not make sense. The authors should explain here how many values were stored by the algorithm and how was did they arrive at the calculations.

2023-06-24 03:13 UTC, ashriva16 commented on papers/Francesc_Alted/Blosc2_NDim.rst
> +Figure :ref:`gaia-3d-dset` shows a 3D view of the Milky Way different type of stars. Each point is a star, and the color of each point represents the star's magnitude, with the brightest stars appear
This should be above the results

2023-06-24 03:13 UTC, ashriva16 commented on papers/Francesc_Alted/Blosc2_NDim.rst
> +One advantage of using a 3D array is the ability to utilize Blosc2 NDim's powerful slicing capabilities for quickly exploring parts of the dataset. For example, we could search for star clusters by e
This should be explained after Blosc2 NDIM explanation.

2023-06-24 03:13 UTC, ashriva16 commented on papers/Francesc_Alted/Blosc2_NDim.rst
> +Blosc2 NDim is a new feature of Blosc2 that allows to create and read n-dimensional datasets in an extremely efficient way thanks to a completely general n-dim 2-level partitioning, allowing to slice
"!" should not be used in an article. I suggest "allowing for slicing and dicing arbitrary large and compressed data"

2023-06-24 03:13 UTC, ashriva16 commented on papers/Francesc_Alted/Blosc2_NDim.rst
> +Automatic tuning of compression parameters
The tuning was not mentioned anywhere before. A line should be mentioned in the abstract about tuning using neural networks.

2023-06-24 03:13 UTC, ankitvaibhava commented on papers/Francesc_Alted/Blosc2_NDim.rst
> +Support for multiple codecs, filters, and other compression features
This section does not seem to be relevant to the paper. The author should mention somewhere how this is used for the Milky Way dataset.

2023-06-30 09:21 UTC, FrancescAlted commented on papers/Francesc_Alted/Blosc2_NDim.rst
> +Finding the right compression parameters for the data is probably the most difficult part of using a compression library. Which combination of code and filter would provide the best compression ratio
Addressed in 64e5ea67

2023-06-30 09:21 UTC, FrancescAlted commented on papers/Francesc_Alted/Blosc2_NDim.rst
> +BTune is an AI tool for Blosc2 that automatically finds the optimal combination of compression parameters to suit the user needs. It uses a neural network that is trained on the most representative d
Addressed in 64e5ea67

2023-06-30 10:59 UTC, FrancescAlted commented
> more detail on the NDim feature



> This is pretty good shape. Left a few nits/suggestions about grammar. However, I think this could benefit from a bit more detail on the NDim feature. For example, something along the lines of this excerpt from https://www.blosc.org/posts/blosc2-ndim-intro/ `With Blosc2 NDim we are taking this feature a step further and both partitions, known as chunks and blocks, are gaining multidimensional capabilities meaning that one can split some dataset (super-chunk in Blosc2 parlance) in such a n-dim cubes and sub-cubes:
> 
> /images/blosc2-ndim-intro/b2nd-2level-parts.png With these more fine-grained cubes (aka partitions), it is possible to retrieve arbitrary n-dim slices more rapidly because you don't have to decompress all the data that is necessary for the more coarse-grained partitions typical in other libraries.
> 
> For example, for a 4-d array with a shape of (50, 100, 300, 250) with float64 items, we can choose a chunk with shape (10, 25, 50, 50) and a block with shape (3, 5, 10, 20) which makes for about 5 MB and 23 KB respectively. This way, a chunk fits comfortably on a L3 cache in most of modern CPUs, and a block in a L1 cache (we are tuning for speed here). `

Good point.  Addressed in cd659cdf

2023-06-30 12:09 UTC, FrancescAlted commented
> While I admire the effort made by the authors on this work, a lot of changes are needed.
> 
> 1. The authors have to decide whether it is the demonstration of Blosc2 Ndim on the Milky-way dataset or a review of Blosc2 Ndim itself since a section such as "support for multiple codecs ..." does not seem to be relevant here if they want to demonstrate Blosc2 Ndim on the milky-way dataset.

Yes, that's a good point.  We still need to add a section on how to choose among different codecs for the Gaia dataset.  Hopefully we should find time for this soon.

> 2. The paper needs to be reorganized as 1) an Introduction about the problem and challenges and why Blosc2 is needed, 2) What is "Blosc2 NDim" and how this work, explain the autotuning and filters here, 3) explaining the format of the dataset, an example of a milky-way image such as figure 2,  4) The code  5) The results and observation after the Blosc2 is applied on the dataset such as speedup, compression 6) conclusions.

While I agree that our current structure can be improved, you are suggesting a pretty massive rewrite.  Still, I humbly think that the current version is good enough for demonstrating how Blosc2 can help in exploring big datasets.  But will keep your suggestions in our mind, and depending on time availability, will try to improve that.

> 3. A grammar check for the manuscript is required.

I think this should be done.

> 4. Numbering and sub-numbering of sections is required.

The example in https://github.com/scipy-conference/scipy_proceedings/blob/2023/papers/00_texderwalt/00_texderwalt.tex do not use numbering or sub-numbering, so why is it required?  Where is that stated?  At any rate, can you provide some examples on how to do it?

2023-06-30 12:13 UTC, FrancescAlted commented on papers/Francesc_Alted/Blosc2_NDim.rst
> +    N-dimensional datasets are widely used in many scientific fields. Quickly accessing subsets of these large datasets is critical for an efficient exploration experience. To achieve this goal, we h
> Here in the "N-dimensional dataset," N is not defined (N ca"N-dimensional dataset," N is not defined (N can be 2 or 3, which is not large). Instead, use the term "high-dimensional" everywhere wherever "n-dimensional" is used.

I think this depends on the area of use.  For example, high-dimensional in data science means something along these lines: [High-dimensional data refers to a dataset where the number of features f (or covariates) can be even larger than the number of observations N](https://www.sciencedirect.com/topics/computer-science/high-dimensional-data#:~:text=High%2Ddimensional%20data%20refers%20to,of%20observations%20N%20%5B105%5D.), which is not what we want to express.

2023-06-30 12:16 UTC, FrancescAlted commented on papers/Francesc_Alted/Blosc2_NDim.rst
> +The exploration of n-dimensional datasets is a common practice in many areas of science. However, one of its drawbacks is that the explored datasets size can become very large, which will slow down t
Ok.  Done in 3851456a

2023-06-30 12:21 UTC, FrancescAlted commented on papers/Francesc_Alted/Blosc2_NDim.rst
> +Blosc uses the blocking technique :cite:`FA10-starving-cpus` to minimize activity on the memory bus. The technique divides datasets into blocks small enough to fit in the caches of modern processors,
Fixed in 4d22d171

2023-06-30 12:23 UTC, FrancescAlted commented on papers/Francesc_Alted/Blosc2_NDim.rst
> +The Gaia dataset
Fixed in 4d5973ed

2023-06-30 12:25 UTC, FrancescAlted commented on papers/Francesc_Alted/Blosc2_NDim.rst
> +Blosc2 NDim is a new feature of Blosc2 that allows to create and read n-dimensional datasets in an extremely efficient way thanks to a completely general n-dim 2-level partitioning, allowing to slice
This has gone already

2023-06-30 12:27 UTC, FrancescAlted commented on papers/Francesc_Alted/Blosc2_NDim.rst
> +Support for multiple codecs, filters, and other compression features
That may be true.  However, I still do think there is value is describing the capabilities of the library, even if not everything is used in the data handling in the article.

2023-06-30 12:35 UTC, FrancescAlted commented on papers/Francesc_Alted/Blosc2_NDim.rst
> +Automatic tuning of compression parameters
Fair point.  Fixed in a6bf6340

2023-06-30 12:44 UTC, FrancescAlted commented on papers/Francesc_Alted/Blosc2_NDim.rst
> +    N-dimensional datasets are widely used in many scientific fields. Quickly accessing subsets of these large datasets is critical for an efficient exploration experience. To achieve this goal, we h
> My Suggestion is to rewrite the abstract. I have provided an example. I would suggest the authors to rewrite in a similar way.
> Abstract:
> Large dimensional datasets have been widely used in various engineering and scientific applications. Prompt access to the subsets of these datasets is crucial for an efficient exploration experience. To facilitate this experience, we have added support for large dimensional datasets to Blosc2, a compression and format library. The extension to the library can effectively support large dimensional sparse datasets by suppressing the zero elements and compressing the non-zero elements. In addition to this, the new two-level data partition used in Blosc2 reduces the need for decompressing unnecessary data, further accelerating slicing speed.

Ok.  I addressed that in 9751365d

2023-06-30 16:36 UTC, FrancescAlted commented on papers/Francesc_Alted/Blosc2_NDim.rst
> +Figure :ref:`gaia-3d-dset` shows a 3D view of the Milky Way different type of stars. Each point is a star, and the color of each point represents the star's magnitude, with the brightest stars appear
Agreed.  Fixed in 48d4341

2023-06-30 23:36 UTC, mepa commented
@scoobies mark pending comment

2023-07-14 20:38 UTC, deniederhut commented
Hey @shaswatshah and @ankitvaibhava! How are you feeling about the updates from the author?

2023-07-17 17:16 UTC, ankitvaibhava commented
I have gone throught the latest updates. I am satisfied by the replies from the authors. I think the paper is ready to be published.

2023-07-17 18:55 UTC, shaswatshah commented
Thanks for the in-depth revisions. The paper looks ready to me
PTAL @FrancescAlted

2023-07-22 11:31 UTC, mepa commented
@scoobies check references

2023-07-22 11:31 UTC, scoobies commented
```
Reference check summary (note 'MISSING' DOIs are suggestions that need verification):

OK DOIs

- 10.1109/MCSE.2010.51 is OK
- 10.5281/zenodo.7971911 is OK

MISSING DOIs

- None

INVALID DOIs

- None
```

2023-07-27 14:22 UTC, mepa commented
@scoobies mark ready

2023-08-06 18:27 UTC, deniederhut commented
@FrancescAlted the list of approved submissions I have from the program committee shows you were approved for a talk but not a poster -- is that correct?

2023-08-06 18:28 UTC, merged

2023-08-07 19:16 UTC, FrancescAlted commented
Yes, that's correct.  We did the poster anyway just in case online attendees would be interested on it :-)

2023-08-08 00:52 UTC, deniederhut commented
Okay thanks for clarifying. The proceedings are meant to be a record of what was accepted to and presented at the conference.