Paper: Emukit: A Python toolkit for decision making under uncertainty
scipy-conference/scipy_proceedings pull request #817
Opened 2023-06-02 13:30 UTC by apaleyes

Hi! This PR is the first draft of the paper about Emukit. I (@apaleyes) am a corresponding author, @mmahsereci was also actively involved in writing, and may chime in the discussions. Looking forward to the reviews, feedback and comments. Thanks!

*Editor*: @cbcunc

*Reviewers*: @cbcunc

2023-06-03 14:58 UTC, deniederhut commented
@scoobies assign @cbcunc as editor

2023-06-03 14:58 UTC, scoobies commented
Assigned! @cbcunc is now the editor

2023-06-07 16:16 UTC, deniederhut commented
@scoobies add @avnishks to reviewers

2023-06-07 16:16 UTC, scoobies commented
@avnishks added to the reviewers list!

2023-06-07 16:16 UTC, deniederhut commented
@scoobies code of conduct

2023-06-07 16:16 UTC, scoobies commented
Our CoC: https://www.scipy2023.scipy.org/code-of-conduct

2023-06-07 16:16 UTC, scoobies commented
Reports of abusive or harassing behavior may be reported to scipy@enthought.com

2023-06-07 16:59 UTC, cbcunc commented
Editor says paper is complete and builds. Awaiting review.

2023-06-26 19:41 UTC, cbcunc commented
@avnishks We are beyond the final review deadline. We thank you that you volunteered to review the paper. But I'm wondering if you are going to submit a review. The author also needs time to incorporate change to any review comments you submit. Thank you.

2023-07-03 01:56 UTC, cbcunc commented
@scoobies remove assignee: @avnishks

2023-07-03 01:56 UTC, scoobies commented
@avnishks removed from assignees.

2023-07-03 01:57 UTC, cbcunc commented
@scoobies remove @avnishks from reviewers

2023-07-03 01:57 UTC, scoobies commented
@avnishks removed from the reviewers list!

2023-07-06 01:07 UTC, cbcunc commented
@scoobies add @cbcunc to reviewers

2023-07-06 01:07 UTC, scoobies commented
@cbcunc added to the reviewers list!

2023-07-06 01:10 UTC, cbcunc commented
@apaleyes and  @mmahsereci,  I have taken over as reviewer of your paper to insure that it does receive the attention you deserve. I will be adding review comments in the next few days.

2023-07-06 07:59 UTC, apaleyes commented
thank you @cbcunc , we'll be watching out for your feedback

2023-07-09 19:35 UTC, cbcunc commented
@scoobies help

2023-07-09 19:35 UTC, scoobies commented
Hello @cbcunc, here are the things you can ask me to do:

```

# List all available commands
@scoobies help

# Show our community Code of Conduct and Guidelines
@scoobies code of conduct

# Add to this issue's reviewers list
@scoobies add @username to reviewers

# Remove from this issue's reviewers list
@scoobies remove @username from reviewers

# Assign a user as the editor of this submission
@scoobies assign @username as editor

# Remove the editor assigned to this submission
@scoobies remove editor

# Add a user to this issue's assignees list
@scoobies add assignee: @username

# Remove a user from this issue's assignees list
@scoobies remove assignee: @username

# Builds paper
@scoobies build paper

# Checks build status
@scoobies build status

# Check the references of the paper for missing DOIs
# Optionally, it can be run on a non-default branch 
@scoobies check references
@scoobies check references from branch custom-branch-name

# Label issue with: paper
@scoobies mark paper

# Label issue with: needs-review. Remove labels: unready, needs-more-review, pending-comment, ready
@scoobies mark needs review

# Label issue with: needs-more-review. Remove labels: unready, needs-review, pending-comment, ready
@scoobies mark needs more review

# Label issue with: pending-comment. Remove labels: unready, needs-review, needs-more-review, ready
@scoobies mark pending comment

# Label issue with: ready. Remove labels: unready, needs-review, needs-more-review, pending-comment
@scoobies mark ready

# Label issue with: unready. Remove labels: needs-review, needs-more-review, pending-comment, ready
@scoobies mark not ready

# Label issue with: does_not_build:server
@scoobies mark server fail

# Remove labels: does_not_build:server
@scoobies mark server success

```

2023-07-09 19:36 UTC, cbcunc commented
@scoobies check references

2023-07-09 19:36 UTC, scoobies commented
```
Reference check summary (note 'MISSING' DOIs are suggestions that need verification):

OK DOIs

- 10.21105/joss.02049 is OK
- 10.1103/PhysRevC.105.034910 is OK
- 10.1017/9781316681411 is OK
- 10.1137/16M1082469 is OK
- 10.1109/ICDAR.1995.598994 is OK
- 10.1093/biomet/asp028 is OK

MISSING DOIs

- 10.21105/joss.00431 may be a valid DOI for title: pyGPGO: Bayesian optimization for Python
- 10.1021/acs.jcim.1c00637.s001 may be a valid DOI for title: NEXTorch: a design and Bayesian optimization toolkit for chemical sciences and engineering
- 10.1002/ail2.24 may be a valid DOI for title: Good practices for Bayesian optimization of high dimensional structured spaces
- 10.1093/biomet/87.1.1 may be a valid DOI for title: Predicting the Output from a Complex Computer Code When Fast Approximations Are Available
- 10.2478/popets-2020-0060 may be a valid DOI for title: Automatic Discovery of Privacy–Utility Pareto Fronts
- 10.23919/acc.2017.7963143 may be a valid DOI for title: Altitude optimization of airborne wind energy systems: A Bayesian optimization approach
- 10.1039/d0sc06805e may be a valid DOI for title: Accelerating high-throughput virtual screening through molecular pool-based active learning
- 10.1186/s12918-014-0102-6 may be a valid DOI for title: A Bayesian active learning strategy for sequential experimental design in systems biology
- 10.1126/sciadv.aaz1708 may be a valid DOI for title: A Bayesian experimental autonomous researcher for mechanical design

INVALID DOIs

- https://doi.org/10.1111/1467-9868.00294 is INVALID because of 'https://doi.org/' prefix
- https://doi.org/10.1016/j.jspi.2009.08.006 is INVALID because of 'https://doi.org/' prefix
```

2023-07-09 19:39 UTC, cbcunc commented
@apaleyes  I am at the SciPy hotel early and devoting the afternoon to your paper. For a first step, please consult the report I ran above concerning missing and invalid DOIs. I'd like to get a clean references report. The proceedings committee does this for all paper submissions.

2023-07-10 01:00 UTC, cbcunc requested changes
Generally a well-structured paper of importance.

2023-07-10 01:00 UTC, cbcunc commented on papers/emukit/metadata.yaml
> +   - Emukit is a highly flexible Python toolkit for enriching decision making under uncertainty with statistical emulation. It is particularly pertinent to complex processes and simulations where dat
showcase the breadth of use cases in which the library ~~was already used~~ by the research community

showcase the breadth of use cases in which the library **already has been** by the research community

2023-07-10 01:00 UTC, cbcunc commented on papers/emukit/metadata.yaml
> +   - Emukit is a highly flexible Python toolkit for enriching decision making under uncertainty with statistical emulation. It is particularly pertinent to complex processes and simulations where dat
where data ~~is~~ scarce

where data **are** scarce

2023-07-10 01:00 UTC, cbcunc commented on papers/emukit/main.tex
> +Data selection is a major challenge in supervised machine learning (ML). Quite often when data is abundant, it is collected prior to the training process and provided statically, meaning that the mac
Quite often when data ~~is~~ abundant

Quite often when data **are** abundant

2023-07-10 01:00 UTC, cbcunc commented on papers/emukit/main.tex
> +Data selection is a major challenge in supervised machine learning (ML). Quite often when data is abundant, it is collected prior to the training process and provided statically, meaning that the mac
~~it is~~ collected prior to the training process

**data are** collected prior to the training process

Or possibly combine this and the above a comment into the less awkward:

Quite often when abundant, data are collected prior to the training process

2023-07-10 01:00 UTC, cbcunc commented on papers/emukit/main.tex
> +Data selection is a major challenge in supervised machine learning (ML). Quite often when data is abundant, it is collected prior to the training process and provided statically, meaning that the mac
if data ~~is~~ expensive and scarce

if data **are** expensive and scarce

2023-07-10 01:00 UTC, cbcunc commented on papers/emukit/main.tex
> +Data selection is a major challenge in supervised machine learning (ML). Quite often when data is abundant, it is collected prior to the training process and provided statically, meaning that the mac
Already this paper uses the passive voice a lot. If I had more time to review this paper, of if it were mine, I would highlight and rewrite all the instances. But please scan the paper for expressions like "are collected" or "it is beneficial" and turn them into active voices such as "data collection, when abundant, quite often occurs prior to the training process" or "careful dataset selection benefits, for example, maximally informing the ML model." In the interest of brevity, I will say no more about that for the rest of the review.

2023-07-10 01:00 UTC, cbcunc commented on papers/emukit/main.tex
> +Tasks where data is scarce usually involve a higher degree of expert knowledge on the modeling side since prior information, such as mechanical or physical knowledge about the system that is being mo
OK, I'm not going to bore you by highlighting every instance where revision should occur to acknowledge that "data" is a plural word in need of subject-verb agreement. I think you get the picture. It's the most common mistake in science papers and stands out like a sore thumb. Your paper subject deserves to be taken seriously and fixing this will avoid many readers disregarding it within the first few sentences. I'm sure there are grammatical revisionists attempting to overturn this, but we're not there yet. Thanks for indulging me as we attempt to professionalize our proceedings.

2023-07-10 01:00 UTC, cbcunc commented on papers/emukit/main.tex
> +Tasks where data is scarce usually involve a higher degree of expert knowledge on the modeling side since prior information, such as mechanical or physical knowledge about the system that is being mo
Sorry, had to jump in here to intercept *doubly* passive voice. Plus comma needed:

Tasks where data is scarce usually involve a higher degree of expert knowledge on the modeling side ~~since prior information~~, such as mechanical or physical knowledge about the system that is being modeled, ~~is aimed to be incorporated in the hope to get physically meaningful and more~~ accurate predictions on the task at hand.

Tasks where data is scarce usually involve a higher degree of expert knowledge on the modeling side, **because incorporating prior information**, such as mechanical or physical knowledge about the system that is being modeled, **aims for more physically meaningful and** accurate predictions on the task at hand.

2023-07-10 01:00 UTC, cbcunc commented on papers/emukit/main.tex
> +Tasks where data is scarce usually involve a higher degree of expert knowledge on the modeling side since prior information, such as mechanical or physical knowledge about the system that is being mo
Awkward: Not ~~seldom~~

Not **infrequently**

or to avoid a double negative entirely: occasionally.

2023-07-10 01:00 UTC, cbcunc commented on papers/emukit/main.tex
> +Data selection is a major challenge in supervised machine learning (ML). Quite often when data is abundant, it is collected prior to the training process and provided statically, meaning that the mac
Please examine this paper for every use of "can" and "cannot" to see if "may" and "may not" are more desirable. It won't be do in every case, but in most. I went through several instances throughout this paper and thought it would be better to couch this as a general comment than litter the review with many comments about it.

2023-07-10 01:00 UTC, cbcunc commented on papers/emukit/main.tex
> +\item In contrast to other packages, Emukit provides several active learning methods via \emph{subpackages that share a core implementation of the active learning loop}. This enables the user to pote
and ~~my allows~~

and **may allow**

2023-07-10 01:00 UTC, cbcunc commented on papers/emukit/main.tex
> +The remainder of the paper corroborates on the points above in greater detail. The following section briefly introduces the supported machine learning methods before Emukit's workflow and library str
the paper corroborates ~~on~~ the points above

the paper corroborates the points above

2023-07-10 01:00 UTC, cbcunc commented on papers/emukit/main.tex
> +\emph{Experimental design} \cite{Kennedy2000, Kennedy2001, Conti2009, Conti2010}, also known as Bayesian active learning, is a method that aims to collect data about a black-box function such that th
Split infinitive: It ~~has traditionally been~~ applied

It **traditionally has been** applied

although a more active voice would be preferred.

2023-07-10 01:00 UTC, cbcunc commented on papers/emukit/main.tex
> +The remainder of the paper corroborates on the points above in greater detail. The following section briefly introduces the supported machine learning methods before Emukit's workflow and library str
Emukit’s workflow and library structure ~~is~~ sketched

Emukit’s workflow and library structure **are** sketched

2023-07-10 01:00 UTC, cbcunc commented on papers/emukit/main.tex
> +\emph{Experimental design} \cite{Kennedy2000, Kennedy2001, Conti2009, Conti2010}, also known as Bayesian active learning, is a method that aims to collect data about a black-box function such that th
~~but also found~~

**but also has found**

2023-07-10 01:00 UTC, cbcunc commented on papers/emukit/main.tex
> +\emph{Experimental design} \cite{Kennedy2000, Kennedy2001, Conti2009, Conti2010}, also known as Bayesian active learning, is a method that aims to collect data about a black-box function such that th
Some ED methods~~, too,~~ obey

Some ED methods also obey

2023-07-10 01:00 UTC, cbcunc commented on papers/emukit/main.tex
> +Emukit is build on the realization that all three methods (BO, BQ, ED), albeit having different numerical aims and result objects, share the same algorithmic structure: A decision loop that computes
Don't capitalize in the middle of a sentence: share the same algorithmic structure: ~~A~~ decision loop that
computes the next node

share the same algorithmic structure: a decision loop that
computes the next node

2023-07-10 01:00 UTC, cbcunc commented on papers/emukit/main.tex
> +Emukit is build on the realization that all three methods (BO, BQ, ED), albeit having different numerical aims and result objects, share the same algorithmic structure: A decision loop that computes
Oxford command please: computes the next node based on the current model, evaluates the user function~~ and then updates the model accordingly~~

computes the next node based on the current model, evaluates the user function, and then updates the model accordingly

2023-07-10 01:00 UTC, cbcunc commented on papers/emukit/main.tex
> +Emukit is build on the realization that all three methods (BO, BQ, ED), albeit having different numerical aims and result objects, share the same algorithmic structure: A decision loop that computes
~~Further~~, especially BO and ED ~~can~~ use similar models while BQ is somewhat more restricted.

**Furthermore**, especially BO and ED **may** use similar models while BQ is somewhat more restricted.

2023-07-10 01:00 UTC, cbcunc commented on papers/emukit/main.tex
> +Emukit is build on the realization that all three methods (BO, BQ, ED), albeit having different numerical aims and result objects, share the same algorithmic structure: A decision loop that computes
I can't parse: Potential benefits of shared implementation, model and compute
among tasks are discussed in later sections. I'm just guessing you may have meant:

Potential benefits of shared implementation, model, and compute
**are** among **the** tasks are discussed in later sections.

2023-07-10 01:00 UTC, cbcunc commented on papers/emukit/main.tex
> +Decision making with statistical emulation consists of three parts. All starts with a \textit{task}, a high level goal that we are interested in achieving. It usually involves a complex process that
It usually involves a complex process that we aim to study and answer a question~~ about~~.

It usually involves a complex process that we aim to study and answer **about** a question.

Or better: It usually involves a complex process that we aim to study to answer a question.

Or better yet: It usually involves a complex process that we aim to study for answers. (Or: for an answer.)

2023-07-10 01:00 UTC, cbcunc commented on papers/emukit/main.tex
> +\textbf{Build the model.} Instead of constraining the user to certain model classes, Emukit provides the flexibility of using user-specified models. Generally speaking, Emukit does not provide modell
and suggests ~~to implement~~ a subset

and suggests **implementing** a subset

2023-07-10 01:00 UTC, cbcunc commented on papers/emukit/main.tex
> +\textbf{Build the model.} Instead of constraining the user to certain model classes, Emukit provides the flexibility of using user-specified models. Generally speaking, Emukit does not provide modell
In UK English, “modelling” (double “l”) is standard, but “modeling” (one “l”) is acceptable. In US English, “modeling” (one “l”) is correct. I would choose the commonality of "modeling." The Procedings is also a US publication. There are several instances of "modelling" through the paper. I was sensing some language differences and this confirms it. I will be respectful of that in my review.

2023-07-10 01:00 UTC, cbcunc commented on papers/emukit/main.tex
> +The common goal of all these methods is to learn a behavior of an \textit{objective function} - a black box expensive process that has certain \textit{parameters}. The knowledge about the objective f
The common goal of all these methods

The common goal of all **of** these methods

2023-07-10 01:00 UTC, cbcunc commented on papers/emukit/main.tex
> +The common goal of all these methods is to learn a behavior of an \textit{objective function} - a black box expensive process that has certain \textit{parameters}. The knowledge about the objective f
a ~~black box expensive~~ process

a **black-box-expensive** process

2023-07-10 01:00 UTC, cbcunc commented on papers/emukit/main.tex
> +\textbf{Model}. All Emukit loops need a probabilistic model. Emukit does not provide functionality to build models as there are already good modelling frameworks available in Python. Instead, it prov
interfacing ~~third part modelling~~ libraries

interfacing **third-party modeling** libraries

2023-07-10 01:00 UTC, cbcunc commented on papers/emukit/main.tex
> +\textbf{Model}. All Emukit loops need a probabilistic model. Emukit does not provide functionality to build models as there are already good modelling frameworks available in Python. Instead, it prov
Model wrappers ~~adopt~~ third-party models and implement one or more of the interfaces using specific modelling framework.

Model wrappers **adapt** third-party models and implement one or more of the interfaces using specific modelling framework.

(The proper terminology of component engineering patterns: interfaces, implement, adapts.)

2023-07-10 01:00 UTC, cbcunc commented on papers/emukit/main.tex
> +\textbf{Acquisition}. The acquisition is a function defined on the parameter space that produces continuous values. It represents a heuristic quantification of how valuable collecting a future point
exploration and ~~explotation~~

exploration and **exploitation**

2023-07-10 01:00 UTC, cbcunc commented on papers/emukit/main.tex
> +\textbf{Acquisition Optimiser}. The \texttt{AcquisitionOptimizer} optimises the acquisition function to find the point at which the acquisition is at a maximum. If available, the optimiser can use th
Omit second comma: Otherwise, it will either estimate the gradients numerically~~,~~ or use a gradient free optimisation.

2023-07-10 01:00 UTC, cbcunc commented on papers/emukit/main.tex
> +\textbf{User Function}. This is the component that represents the objective function. It can be evaluated by the user, or it can be passed into the loop and evaluated by Emukit.
Omit second comma: It can be evaluated by the user~~,~~ or it can be passed into the loop and evaluated by Emukit.

2023-07-10 01:00 UTC, cbcunc commented on papers/emukit/main.tex
> +This section describes Emukit's high level APIs for all main functions of the package: Bayesian optimisation, Bayesian quadrature, experimental design and multi-fidelity emulation. Unless stated othe
Just pointing this one out because it may be hard to spot:

data (an initial design of reasonable size with corresponding evaluations of the user function) ~~is~~

data (an initial design of reasonable size with corresponding evaluations of the user function) **are**

2023-07-10 01:00 UTC, cbcunc commented on papers/emukit/main.tex
> +# This utility method allows to
\# This utility method allows ~~to~~
\# ~~convert~~ data from different fidelities

\# This utility method allows **conversion**
\# **of** data from different fidelities

2023-07-10 01:00 UTC, cbcunc commented on papers/emukit/main.tex
> +Tasks where data is scarce usually involve a higher degree of expert knowledge on the modeling side since prior information, such as mechanical or physical knowledge about the system that is being mo
~~(S~~tatistical) emulator we refer to throughout this paper is an unrelated, albeit similar, term 

**The (s**tatistical) emulator we refer to throughout this paper is an unrelated, albeit similar, term

2023-07-10 01:00 UTC, cbcunc commented on papers/emukit/main.tex
> +In addition to the APIs discussed above, Emukit also provides basic support for sensitivity analysis and benchmarking. Further information about Emukit's functionality, including available implementa
Further information about Emukit's functionality, including available implementations of acquisition functions, multi-output models, support for constraints and cost functions, custom events in the outer loop~~, can~~ be found in library's website, documentation and tutorial notebooks.

Further information about Emukit's functionality, including available implementations of acquisition functions, multi-output models, support for constraints and cost functions, **and** custom events in the outer loop **may** be found in library's website, documentation and tutorial notebooks.

2023-07-10 01:00 UTC, cbcunc commented on papers/emukit/main.tex
> +Because of its flexibility Emukit allows researchers to rapidly experiment with decision making methods in its suite. In this section we discuss several research papers that leverage this fact to adv
This is a subjective suggestion:

"Because of its flexibility Emukit allows researchers to rapidly experiment with decision making methods in its suite. In thissection we discuss several research papers that leverage this fact to advance the field of decision making under uncertainty."

You make an assertion of what Emukit allows researchers to do. There is no citation for that and I allow that because a) I don't think we're likely to find such a citation because b) this is a self-citing paper. That is, there are many assertions in this paper without citation. Given that, it may be a stretch to use the word "fact" in the next sentence. I would use the world "advantage" instead.

2023-07-10 01:00 UTC, cbcunc commented on papers/emukit/main.tex
> +Optimisation of parameters in high dimensional structured data spaces is an increasingly important and challenging task. A common pattern is to use unsupervised learning methods to project parameters
Siivola et al. [26] ~~study~~

 Siivola et al. [26] **studied**

2023-07-10 01:00 UTC, cbcunc commented on papers/emukit/main.tex
> +Optimisation of parameters in high dimensional structured data spaces is an increasingly important and challenging task. A common pattern is to use unsupervised learning methods to project parameters
and the choice of acquisition function ~~are analysed~~

and the choice of acquisition function **were analyzed**

2023-07-10 01:00 UTC, cbcunc commented on papers/emukit/main.tex
> +In this section we describe several cases where Emukit was used to solve a problem in other scientific domains.
"In this section we describe several cases where Emukit was used to solve a problem in other scientific domains."

Other than what domain? Was a previous domain even specified? Did you mean "several domains" or "a few domains for examples?"

2023-07-10 01:00 UTC, cbcunc commented on papers/emukit/main.tex
> +Uhrenholt and Jensen used Emukit's Bayesian optimisation module to solve the problem of finding settings of a musical synthesizer to produce a given sound \cite{uhrenholt2019efficient}. A musical syn
The flexibility of Emukit allowed ~~to implement~~ this customization directly

The flexibility of Emukit allowed **the implemention** this customization directly

2023-07-10 01:00 UTC, cbcunc commented on papers/emukit/main.tex
> +Uhrenholt and Jensen used Emukit's Bayesian optimisation module to solve the problem of finding settings of a musical synthesizer to produce a given sound \cite{uhrenholt2019efficient}. A musical syn
"Emukit’s API also facilitated a fair comparison to standard Bayesian optimisation baseline."

To **a** standard Bayesian optimization baseline? To **the** standard Bayesian optimization baseline? To  standard Bayesian optimization baselines plural?

2023-07-10 01:00 UTC, cbcunc commented on papers/emukit/main.tex
> +Emukit puts a strong emphasis on plug-and-play construction of the decision making loop. All components interact via interfaces, and they require a common data format to communicate, which in Emukit
~~It ~~ can be potentially mitigated by using specialized libraries that allow Numpy to be run on GPU

**This** can be potentially mitigated by using specialized libraries that allow Numpy to be run on GPU,

2023-07-10 01:00 UTC, cbcunc commented on papers/emukit/main.tex
> +Emukit is built on a realisation that common methods for decision making under uncertainty -- such as Bayesian optimisation, Bayesian quadrature and experimental design -- follow the same iterative p
Emukit ~~was~~ successfully used

Emukit **has been** successfully used

2023-07-10 01:00 UTC, cbcunc commented on papers/emukit/main.tex
> +Emukit has multiple potential growth directions. Mitigation of limitations discussed earlier can improve user experience and overall quality of the library. Integration with other tools in scientific
New functionality, such as multi-objective Bayesian optimisation, ~~shall~~ expand library’s capabilities and give users new ways to do research with Emukit.

New functionality, such as multi-objective Bayesian optimisation, **would** expand library’s capabilities and give users new ways to do research with Emukit.

2023-07-10 01:00 UTC, cbcunc commented on papers/emukit/main.tex
> +We invite researchers and enthusiasts from any scientific or industrial domain to explore the potential of using Emukit for their applications, to contibute new functionality, and to take part in the
No first person.

~~We~~ are always open to feedback and comments about how the library could be improved.

**The authors** are always open to feedback and comments about how the library could be improved.

2023-07-10 01:09 UTC, cbcunc commented
@scoobies mark pending comment

2023-07-10 12:53 UTC, apaleyes commented
> @apaleyes I am at the SciPy hotel early and devoting the afternoon to your paper. For a first step, please consult the report I ran above concerning missing and invalid DOIs. I'd like to get a clean references report. The proceedings committee does this for all paper submissions.

thanks, that should now be fixed

2023-07-10 13:13 UTC, apaleyes commented
@cbcunc thanks for the review! To avoid too many "fixed" or "agreed" comments, we will simply mark the applied ones as resolved. With two exceptions: in cases when we'd like to have a conversation, and in cases where the comment is general and applies to the whole paper.

2023-07-10 13:16 UTC, apaleyes commented on papers/emukit/main.tex
> +Uhrenholt and Jensen used Emukit's Bayesian optimisation module to solve the problem of finding settings of a musical synthesizer to produce a given sound \cite{uhrenholt2019efficient}. A musical syn
changed to "Emukit's API also facilitated a fair comparison to the standard Bayesian optimisation used as a baseline"

2023-07-10 13:31 UTC, apaleyes commented on papers/emukit/main.tex
> +In this section we describe several cases where Emukit was used to solve a problem in other scientific domains.
changed to "In this section we describe several cases where Emukit was used to solve applied research problems."

2023-07-10 13:32 UTC, apaleyes commented on papers/emukit/main.tex
> +Uhrenholt and Jensen used Emukit's Bayesian optimisation module to solve the problem of finding settings of a musical synthesizer to produce a given sound \cite{uhrenholt2019efficient}. A musical syn
Personally, I'd say "allowed to implement this customization" is a bit better than "allowed the implementation of this customization". Can we keep this sentence as it is?

2023-07-10 13:34 UTC, apaleyes commented on papers/emukit/main.tex
> +Because of its flexibility Emukit allows researchers to rapidly experiment with decision making methods in its suite. In this section we discuss several research papers that leverage this fact to adv
Good point, changed "fact" to "advantage"

2023-07-10 13:39 UTC, apaleyes commented on papers/emukit/main.tex
> +The common goal of all these methods is to learn a behavior of an \textit{objective function} - a black box expensive process that has certain \textit{parameters}. The knowledge about the objective f
Why second hyphen? I agree with "black-box", but not sure about "black-box-expensive"

2023-07-10 13:44 UTC, apaleyes commented on papers/emukit/main.tex
> +\textbf{Build the model.} Instead of constraining the user to certain model classes, Emukit provides the flexibility of using user-specified models. Generally speaking, Emukit does not provide modell
No problem, changed all occurrences of "modelling" to "modeling".

Another common one is z-vs-s, as in optimi**s**ation, analy**s**ing etc. Coming from the UK we naturally prefer "s", but please let us know if that is a big issue.

2023-07-10 13:45 UTC, apaleyes commented on papers/emukit/main.tex
> +Decision making with statistical emulation consists of three parts. All starts with a \textit{task}, a high level goal that we are interested in achieving. It usually involves a complex process that
Went for "It usually involves a complex process that we aim to study to answer a question."

2023-07-10 13:48 UTC, apaleyes commented on papers/emukit/main.tex
> +Emukit is build on the realization that all three methods (BO, BQ, ED), albeit having different numerical aims and result objects, share the same algorithmic structure: A decision loop that computes
Rephrased to "Potential benefits of sharing implementation, model and compute between tasks are discussed in later sections." Does that read better?

2023-07-10 13:57 UTC, apaleyes commented on papers/emukit/main.tex
> +Data selection is a major challenge in supervised machine learning (ML). Quite often when data is abundant, it is collected prior to the training process and provided statically, meaning that the mac
went through the paper and replaced some of "can" with "may".

2023-07-10 13:58 UTC, apaleyes commented on papers/emukit/main.tex
> +Tasks where data is scarce usually involve a higher degree of expert knowledge on the modeling side since prior information, such as mechanical or physical knowledge about the system that is being mo
Went with simple "Often"

2023-07-10 14:06 UTC, apaleyes commented on papers/emukit/main.tex
> +Data selection is a major challenge in supervised machine learning (ML). Quite often when data is abundant, it is collected prior to the training process and provided statically, meaning that the mac
May I ask, just for my own knowledge, what's so wrong with passive voice? Is it just harder for readers to comprehend?

2023-07-10 14:07 UTC, apaleyes commented
@cbcunc most of the comments are addressed. Thanks for reading the paper so attentively!

I've left a comments on a few occasions where I'd like to discuss it further. The only two remaining efforts are plural/singular for "data" and the passive voice, which we shall also address shortly

2023-07-12 22:15 UTC, apaleyes commented on papers/emukit/main.tex
> +Tasks where data is scarce usually involve a higher degree of expert knowledge on the modeling side since prior information, such as mechanical or physical knowledge about the system that is being mo
appreciate the explanation, thanks! on a few occasions I've rephrased it, in other replaced singular to plural for data.

2023-07-12 22:19 UTC, apaleyes commented
@scoobies check references

2023-07-12 22:19 UTC, scoobies commented
```
Reference check summary (note 'MISSING' DOIs are suggestions that need verification):

OK DOIs

- 10.21105/joss.00431 is OK
- 10.1021/acs.jcim.1c00637.s001 is OK
- 10.1145/3292500.3330701 is OK
- 10.21105/joss.02049 is OK
- 10.1103/PhysRevC.105.034910 is OK
- 10.1002/ail2.24 is OK
- 10.1017/9781316681411 is OK
- 10.1137/16M1082469 is OK
- 10.1109/ICDAR.1995.598994 is OK
- 10.1111/1467-9868.00294 is OK
- 10.1093/biomet/asp028 is OK
- 10.1016/j.jspi.2009.08.006 is OK
- 10.1093/biomet/87.1.1 is OK
- 10.2478/popets-2020-0060 is OK
- 10.23919/acc.2017.7963143 is OK
- 10.1039/d0sc06805e is OK
- 10.1145/2833157.2833162 is OK
- 10.3390/ijerph18020530 is OK
- 10.1186/s12918-014-0102-6 is OK
- 10.1126/sciadv.aaz1708 is OK

MISSING DOIs

- None

INVALID DOIs

- None
```

2023-07-12 22:56 UTC, cbcunc commented on papers/emukit/main.tex
> +Data selection is a major challenge in supervised machine learning (ML). Quite often when data is abundant, it is collected prior to the training process and provided statically, meaning that the mac
https://www.google.com/search?q=passive%20voice%20considered%20evil

Many, many reasons. It's a general principle of good writing, **particularly** academic and scientific writing. We've always looked for it in the proceedings.

2023-07-12 22:58 UTC, cbcunc commented on papers/emukit/main.tex
> +Emukit is build on the realization that all three methods (BO, BQ, ED), albeit having different numerical aims and result objects, share the same algorithmic structure: A decision loop that computes
Even better in active voice: "In later sections we discuss the potential benefits of sharing implementation, model and compute between tasks."

2023-07-12 22:59 UTC, cbcunc commented on papers/emukit/main.tex
> +\textbf{Build the model.} Instead of constraining the user to certain model classes, Emukit provides the flexibility of using user-specified models. Generally speaking, Emukit does not provide modell
Probably not a huge issue. I did notice it. My preference would be US English in a US publication. But I won't die on that hill.

2023-07-12 23:02 UTC, cbcunc commented on papers/emukit/main.tex
> +The common goal of all these methods is to learn a behavior of an \textit{objective function} - a black box expensive process that has certain \textit{parameters}. The knowledge about the objective f
The whole phrase is a compound adjective. https://en.m.wikipedia.org/wiki/Compound_modifier

2023-07-12 23:03 UTC, cbcunc commented
I hope my answers helped. Thank you for your attention.

2023-07-16 01:44 UTC, cbcunc commented
@apaleyes Any changes in response to my replies to your comments above?

2023-07-17 13:35 UTC, apaleyes commented
@cbcunc i am happy to adjust, just need a few more days to find time to work on this. is that possible?

2023-07-17 13:37 UTC, apaleyes commented on papers/emukit/main.tex
> +The common goal of all these methods is to learn a behavior of an \textit{objective function} - a black box expensive process that has certain \textit{parameters}. The knowledge about the objective f
that would be a very stark difference with every other piece of documentation or writing about emukit. would it be ok if we stick to "black-box expensive function" please?

2023-07-17 13:37 UTC, apaleyes commented on papers/emukit/main.tex
> +\textbf{Build the model.} Instead of constraining the user to certain model classes, Emukit provides the flexibility of using user-specified models. Generally speaking, Emukit does not provide modell
thanks, i'll keep it as it is then

2023-07-17 13:37 UTC, apaleyes commented on papers/emukit/main.tex
> +Emukit is build on the realization that all three methods (BO, BQ, ED), albeit having different numerical aims and result objects, share the same algorithmic structure: A decision loop that computes
will use this one, thanks

2023-07-17 13:38 UTC, apaleyes commented on papers/emukit/main.tex
> +Data selection is a major challenge in supervised machine learning (ML). Quite often when data is abundant, it is collected prior to the training process and provided statically, meaning that the mac
i see. thanks for clarification. i have to admit i struggle a lot with identifying passive voice in the text, will probably look for some sort of automation to help me with this one

2023-07-17 13:39 UTC, apaleyes commented
> I hope my answers helped. Thank you for your attention.

helped a ton, really appreciated

2023-07-23 20:01 UTC, apaleyes commented
@cbcunc just wondering if you had another chance to look at the edits. I hopefully addressed all the comments. The last one was passive voice, and while some instances of it remain, I managed to rephrase many others. Hopefully it reads better now!

2023-07-23 20:27 UTC, cbcunc commented
@apaleyes Thanks for the lastest edits. I will go over the paper again soon.

2023-07-28 20:58 UTC, cbcunc commented
@scoobies mark ready

2023-07-28 20:59 UTC, cbcunc approved these changes

2023-08-06 18:27 UTC, merged