Paper: Data Reduction Network
scipy-conference/scipy_proceedings pull request #824
Opened 2023-06-02 23:41 UTC by summerswallow-whi

If you are creating this PR in order to submit a draft of your paper,
see http://procbuild.scipy.org/ for logs generated by the build
process.

See the [project readme](https://github.com/scipy-conference/scipy_proceedings#build-your-paper)
for more information.

*Editor*:  

*Reviewers*:

2023-06-03 15:03 UTC, deniederhut commented
@scoobies assign @cbcunc as editor

2023-06-03 15:03 UTC, scoobies commented
Assigned! @cbcunc is now the editor

2023-06-03 22:16 UTC, deniederhut commented
@scoobies build status

2023-06-03 22:16 UTC, scoobies commented
{"WestHealth-xu_et_al"=>{"data"=>{"build_output"=>"[*] Updating proceedings build tools in {self.master_repo_path}...\nAlready up to date.\n[*] Check out paper repository...\nCloning into '/tmp/tmpclr47sd4'...\nMoving proceedings build tools to temp directory...\n[*] Build the paper...\nBuilding: xu_etal\n*** Warning: /tmp/tmpclr47sd4/publisher/../output/xu_etal/paper_stats.json does not exist.\n*** Warning: /tmp/tmpclr47sd4/publisher/_build/toc.json does not exist.\n*** Warning: /tmp/tmpclr47sd4/publisher/_build/other.json does not exist.\nPDFLaTeX error output:\n================================================================================\nThis is pdfTeX, Version 3.14159265-2.6-1.40.20 (TeX Live 2019/Debian) (preloaded format=pdflatex)\n restricted \\write18 enabled.\nentering extended mode\n(./paper.tex\nLaTeX2e <2020-02-02> patch level 2\nL3 programming layer <2020-02-14> (./IEEEtran.cls\nDocument Class: IEEEtran 2015/08/26 V1.8b by Michael Shell\n-- See the \"IEEEtran_HOWTO\" manual for usage information.\n-- http://www.michaelshell.org/tex/ieeetran/\n(/usr/share/texlive/texmf-dist/tex/latex/psnfss/ot1ppl.fd)\n-- Using IEEE Computer Society mode.\n-- Using 8.5in x 11in (letter) paper.\n-- Using PDF output.\n-- This is a 10 point document.\n) (/usr/share/texlive/texmf-dist/tex/latex/cmap/cmap.sty)\n(/usr/share/texlive/texmf-dist/tex/latex/base/ifthen.sty)\n(/usr/share/texlive/texmf-dist/tex/latex/base/fontenc.sty\n(/usr/share/texlive/texmf-dist/tex/latex/psnfss/t1ppl.fd)<<t1.cmap>>)\n(/usr/share/texlive/texmf-dist/tex/latex/base/inputenc.sty)\n(/usr/share/texlive/texmf-dist/tex/latex/amsmath/amsmath.sty\nFor additional information on amsmath, use the `?' option.\n(/usr/share/texlive/texmf-dist/tex/latex/amsmath/amstext.sty\n(/usr/share/texlive/texmf-dist/tex/latex/amsmath/amsgen.sty))\n(/usr/share/texlive/texmf-dist/tex/latex/amsmath/amsbsy.sty)\n(/usr/share/texlive/texmf-dist/tex/latex/amsmath/amsopn.sty))\n(/usr/share/texlive/texmf-dist/tex/latex/booktabs/booktabs.sty)\n(/usr/share/texlive/texmf-dist/tex/latex/graphics/color.sty\n(/usr/share/texlive/texmf-dist/tex/latex/graphics-cfg/color.cfg)\n(/usr/share/texlive/texmf-dist/tex/latex/graphics-def/pdftex.def))\n(/usr/share/texlive/texmf-dist/tex/latex/caption/caption.sty\n(/usr/share/texlive/texmf-dist/tex/latex/caption/caption3.sty\n(/usr/share/texlive/texmf-dist/tex/latex/graphics/keyval.sty))\n\nPackage caption Warning: Unknown document class (or package),\n(caption)                standard defaults will be used.\nSee the caption package documentation for explanation.\n\n) (/usr/share/texlive/texmf-dist/tex/latex/float/float.sty)\n(/usr/share/texlive/texmf-dist/tex/latex/tools/longtable.sty)\n(/usr/share/texlive/texmf-dist/tex/latex/caption/ltcaption.sty)\n(/usr/share/texlive/texmf-dist/tex/latex/tools/array.sty) (./scipy.sty\n(./status.sty (./draftwatermark.sty (./everypage.sty)\n(/usr/share/texlive/texmf-dist/tex/latex/graphics/graphicx.sty\n(/usr/share/texlive/texmf-dist/tex/latex/graphics/graphics.sty\n(/usr/share/texlive/texmf-dist/tex/latex/graphics/trig.sty)\n(/usr/share/texlive/texmf-dist/tex/latex/graphics-cfg/graphics.cfg)))))\n(/usr/share/texlive/texmf-dist/tex/latex/psnfss/mathptmx.sty)\n(/usr/share/texlive/texmf-dist/tex/latex/psnfss/helvet.sty)\n(/usr/share/texlive/texmf-dist/tex/latex/psnfss/courier.sty)\n(/usr/share/texlive/texmf-dist/tex/latex/amsfonts/amsfonts.sty)\n(/usr/share/texlive/texmf-dist/tex/latex/amsfonts/amssymb.sty)\n(/usr/share/texlive/texmf-dist/tex/latex/tools/bm.sty)\n(/usr/share/texlive/texmf-dist/tex/latex/hyperref/hyperref.sty\n(/usr/share/texlive/texmf-dist/tex/generic/ltxcmds/ltxcmds.sty)\n(/usr/share/texlive/texmf-dist/tex/generic/iftex/iftex.sty)\n(/usr/share/texlive/texmf-dist/tex/latex/pdftexcmds/pdftexcmds.sty\n(/usr/share/texlive/texmf-dist/tex/generic/infwarerr/infwarerr.sty))\n(/usr/share/texlive/texmf-dist/tex/generic/kvsetkeys/kvsetkeys.sty)\n(/usr/share/texlive/texmf-dist/tex/generic/kvdefinekeys/kvdefinekeys.sty)\n(/usr/share/texlive/texmf-dist/tex/generic/pdfescape/pdfescape.sty)\n(/usr/share/texlive/texmf-dist/tex/latex/hycolor/hycolor.sty)\n(/usr/share/texlive/texmf-dist/tex/latex/letltxmacro/letltxmacro.sty)\n(/usr/share/texlive/texmf-dist/tex/latex/auxhook/auxhook.sty)\n(/usr/share/texlive/texmf-dist/tex/latex/kvoptions/kvoptions.sty)\n(/usr/share/texlive/texmf-dist/tex/latex/hyperref/pd1enc.def)\n(/usr/share/texlive/texmf-dist/tex/generic/intcalc/intcalc.sty)\n(/usr/share/texlive/texmf-dist/tex/generic/etexcmds/etexcmds.sty)\n(/usr/share/texlive/texmf-dist/tex/latex/url/url.sty)\n(/usr/share/texlive/texmf-dist/tex/generic/bitset/bitset.sty\n(/usr/share/texlive/texmf-dist/tex/generic/bigintcalc/bigintcalc.sty))\n(/usr/share/texlive/texmf-dist/tex/generic/atbegshi/atbegshi.sty))\n(/usr/share/texlive/texmf-dist/tex/latex/hyperref/hpdftex.def\n(/usr/share/texlive/texmf-dist/tex/latex/atveryend/atveryend.sty)\n(/usr/share/texlive/texmf-dist/tex/latex/rerunfilecheck/rerunfilecheck.sty\n(/usr/share/texlive/texmf-dist/tex/generic/uniquecounter/uniquecounter.sty)))\n\nPackage hyperref Warning: Option `pdftex' has already been used,\n(hyperref)                setting the option has no effect on input line 43.\n\n(/usr/share/texlive/texmf-dist/tex/latex/multirow/multirow.sty)\n(/usr/share/texlive/texmf-dist/tex/latex/base/textcomp.sty)\n(/usr/share/texlive/texmf-dist/tex/latex/upquote/upquote.sty)\n(/usr/share/texlive/texmf-dist/tex/latex/fancyvrb/fancyvrb.sty)\n(/usr/share/texlive/texmf-dist/tex/latex/algorithms/algorithm.sty))\n(/usr/share/texlive/texmf-dist/tex/latex/algorithmicx/algpseudocode.sty\n(/usr/share/texlive/texmf-dist/tex/latex/algorithmicx/algorithmicx.sty\nDocument Style algorithmicx 1.2 - a greatly improved `algorithmic' style\n)\nDocument Style - pseudocode environments for use with the `algorithmicx' style\n) (/usr/share/texlive/texmf-dist/tex/latex/l3backend/l3backend-pdfmode.def)\nNo file paper.aux.\n(/usr/share/texlive/texmf-dist/tex/latex/psnfss/t1ptm.fd)\n-- Lines per column: 61 (exact).\n(/usr/share/texlive/texmf-dist/tex/context/base/mkii/supp-pdf.mkii\n[Loading MPS to PDF converter (version 2006.09.02).]\n) (/usr/share/texlive/texmf-dist/tex/latex/epstopdf-pkg/epstopdf-base.sty\n(/usr/share/texlive/texmf-dist/tex/latex/latexconfig/epstopdf-sys.cfg))\n(/usr/share/texlive/texmf-dist/tex/latex/hyperref/nameref.sty\n(/usr/share/texlive/texmf-dist/tex/latex/refcount/refcount.sty)\n(/usr/share/texlive/texmf-dist/tex/generic/gettitlestring/gettitlestring.sty))\n(./page_numbers.tex) (/usr/share/texlive/texmf-dist/tex/latex/psnfss/t1phv.fd)\n(/usr/share/texlive/texmf-dist/tex/latex/psnfss/ot1ztmcm.fd)<<ot1.cmap>>\n(/usr/share/texlive/texmf-dist/tex/latex/psnfss/omlztmcm.fd)<<oml.cmap>>\n(/usr/share/texlive/texmf-dist/tex/latex/psnfss/omsztmcm.fd)<<oms.cmap>>\n(/usr/share/texlive/texmf-dist/tex/latex/psnfss/omxztmcm.fd)<<omx.cmap>>\n(/usr/share/texlive/texmf-dist/tex/latex/psnfss/ot1ptm.fd)\n(/usr/share/texlive/texmf-dist/tex/latex/psnfss/upzd.fd)\n(/usr/share/texlive/texmf-dist/tex/latex/psnfss/ts1ptm.fd)\n\nLaTeX Warning: Citation `Manyika2011BigDT' on page 1 undefined on input line 20\n0.\n\n(/usr/share/texlive/texmf-dist/tex/latex/psnfss/t1pcr.fd)\n\nLaTeX Warning: Citation `hernan2011simpsons' on page 1 undefined on input line \n202.\n\n\nLaTeX Warning: Citation `fayyad2002information' on page 1 undefined on input li\nne 204.\n\n\nLaTeX Warning: Citation `shneiderman1996eyes' on page 1 undefined on input line\n 204.\n\n\nLaTeX Warning: Citation `Wong1997MultivariateVU' on page 1 undefined on input l\nine 204.\n\n[1{/var/lib/texmf/fonts/map/pdftex/updmap/pdftex.map}]\n\nLaTeX Warning: Citation `wardlow2022perceptions' on page 2 undefined on input l\nine 210.\n\n\nLaTeX Warning: Citation `upton2000cobweb' on page 2 undefined on input line 210\n.\n\n\nLaTeX Warning: Citation `dijkstra1959note' on page 2 undefined on input line 21\n0.\n\n\nLaTeX Warning: No positions in optional float specifier.\n               Default adde [...]

2023-06-03 22:17 UTC, deniederhut commented
Looks like you might have forgotten to commit a file?

```
Error: File clique-eps-converted-to.pdf not found
```

2023-06-03 22:20 UTC, deniederhut commented
@scoobies mark server fail

2023-06-03 22:54 UTC, summerswallow-whi commented
@deniederhut Are you sure it is not a procbuild issue? I see three other papers exhibiting the same situation. In any case can someone assist in resolving the problem? Running make_paper.sh locally generates a PDF file. There doesn't appear to be any logs to access.  Also The reason it was posted in the issues was based on the instructions it seem to imply any issue with the PDF should be discussed there.

2023-06-03 23:00 UTC, summerswallow-whi commented
@deniederhut That's helpful. This was the original issue I had and reported https://github.com/scipy-conference/scipy_proceedings/issues/807. I thought I had omitted texlive-font-utils in my local build. Perhaps that is not a package included in the build engine.

I think it was necessary to process an eps file. Perhaps there is another file format I could use that avoids that if texlive-font-utils is not something you plan to include in the buildserver.

2023-06-03 23:06 UTC, summerswallow-whi commented
I found a potential work around with texlive-font-utils installed locally it generates as a by product clique-eps-converted-to.pdf file which I can then reference in the paper directly. It's a bit round about but for expediency I could certainly do that. However for general purpose. 

@deniederhut Do you plan to use texlive-font-utils in your build server? or should I just go about this workaround. At this point it isn't really much trouble for me to make the switch, but should editorial changes to drawings be asked it could be a bit cumbersome.

2023-06-05 00:10 UTC, deniederhut commented
Ah sorry, I saw that the issue was closed and thought that you had resolved this on your own. Yes we can add that package.

2023-06-05 00:11 UTC, deniederhut commented
Here's what that pdf looks like on a patched version of the build server 

[document.pdf](https://github.com/scipy-conference/scipy_proceedings/files/11647594/document.pdf)

2023-06-05 00:15 UTC, deniederhut commented
@scoobies mark server success

2023-06-05 17:03 UTC, summerswallow-whi commented
@deniederhut I had closed the issue thinking it was an oversight in my local build. It wasn't til you presented the logs that I know what it was. Thanks, paper looks correct!

2023-06-06 10:50 UTC, deniederhut commented
@scoobies add @Tolulade-A to reviewers

2023-06-06 10:50 UTC, scoobies commented
@Tolulade-A added to the reviewers list!

2023-06-06 10:50 UTC, deniederhut commented
@scoobies code of conduct

2023-06-06 10:50 UTC, scoobies commented
Our CoC: https://www.scipy2023.scipy.org/code-of-conduct

2023-06-06 10:50 UTC, scoobies commented
Reports of abusive or harassing behavior may be reported to scipy@enthought.com

2023-06-06 23:50 UTC, Tolulade-A commented
> @scoobies add @Tolulade-A to reviewers

Hello, I'm happy to be here to review.

Tolulade

2023-06-07 16:24 UTC, deniederhut commented
@scoobies add @jsingh811 to reviewers

2023-06-07 16:24 UTC, scoobies commented
@jsingh811 added to the reviewers list!

2023-06-07 16:59 UTC, cbcunc commented
Editor says paper is complete and builds. Awaiting review.

2023-06-07 17:36 UTC, summerswallow-whi commented
To reviewers, I await your comments. Either me or one of my co-authors will address your comments. Thank you

2023-06-21 01:08 UTC, Tolulade-A commented
Hello @summerswallow-whi 
I'm Tolulade Ademisoye, a ML Engineer, thanks for the opportunity to review your work. I'll commence shortly.

2023-06-23 22:52 UTC, Tolulade-A requested changes

2023-06-23 22:52 UTC, Tolulade-A commented on papers/xu_etal/drn.tex
> +Considering the computational demands associated with processing large survey data, strategies such as parallel processing or employing GPU-enhanced graph packages, like cugraph\cite{cugraph}, could
This paper is an interesting one, good work so far. 

Acronyms should be spelled out upon first mention - can you spell out GPU here @summerswallow-whi 

_Considering the computational demands associated with processing large survey data, strategies such as parallel processing or employing GPU-enhanced graph packages_

2023-06-23 22:52 UTC, Tolulade-A commented on papers/xu_etal/drn.tex
> +An example Jupyter notebook is available at our GitHub repository: https://github.com/Westhealth/scipy2023/. The efforts to build the method to a library is documented in the \texttt{README} file.
I'm unable to find this github repository (https://github.com/Westhealth/scipy2023/) for this paper where python was used for the sample dataset using drn. Is it somewhere ? @summerswallow-whi 

It's essential that the work should describe the development or use of python software for approaching a problem in a domain within the scope of the conference.

2023-06-23 23:12 UTC, summerswallow-whi commented on papers/xu_etal/drn.tex
> +An example Jupyter notebook is available at our GitHub repository: https://github.com/Westhealth/scipy2023/. The efforts to build the method to a library is documented in the \texttt{README} file.
Sorry. The principal author is out this week, but I will ensure it is up Monday. Typically we will want to insure anything on a public website is ready to be public facing.

2023-06-23 23:27 UTC, summerswallow-whi commented on papers/xu_etal/drn.tex
> +Considering the computational demands associated with processing large survey data, strategies such as parallel processing or employing GPU-enhanced graph packages, like cugraph\cite{cugraph}, could
I expanded the only two abbreviations I could find GPU and UCI. If this is satisfactory please resolve.

2023-06-24 00:08 UTC, jsingh811 reviewed
Thank you for putting this work together. It was an interesting read!

 I have left an inline suggestion. Other than that, as also pointed by the other review, the GitHub link is not functional. I would kindly request you to fix that before the paper is merged. 
Secondly, I felt that some other graph visualization tools could have been mentioned, cited, and compared to the proposed visualization tool. It was great to see cugraph being mentioned. Which other tools exist in the space? 

In general, the no. of references feel low and if there is scope, I would request you to add some. A low number of references may indicate a lack of sufficient evidence or a limited exploration of the existing literature, which I am sure is not the case here, but might weaken the credibility of the paper's findings from the reader's perspective.

2023-06-24 00:08 UTC, jsingh811 commented on papers/xu_etal/drn.tex
> +To distill insightful and actionable visualizations from large survey data, it is essential to balance the trade-off between simplicity and completeness, highlighting the most critical variables for
Since the proposed method relies on Prim's algorithm, it would be beneficial for the readers to find a one-liner description of what it means in addition to the citation.

2023-06-26 18:10 UTC, cbcunc commented on papers/xu_etal/drn.tex
> +To distill insightful and actionable visualizations from large survey data, it is essential to balance the trade-off between simplicity and completeness, highlighting the most critical variables for
@summerswallow-whi The final review deadline has passed. Would you please address and resolve this review comment?

2023-06-26 22:10 UTC, summerswallow-whi commented on papers/xu_etal/drn.tex
> +An example Jupyter notebook is available at our GitHub repository: https://github.com/Westhealth/scipy2023/. The efforts to build the method to a library is documented in the \texttt{README} file.
Link Is online

2023-06-26 22:17 UTC, summerswallow-whi commented on papers/xu_etal/drn.tex
> +To distill insightful and actionable visualizations from large survey data, it is essential to balance the trade-off between simplicity and completeness, highlighting the most critical variables for
Working on rephrasing this passage also connecting it more to python.

2023-06-26 22:38 UTC, summerswallow-whi commented on papers/xu_etal/drn.tex
> +To distill insightful and actionable visualizations from large survey data, it is essential to balance the trade-off between simplicity and completeness, highlighting the most critical variables for
I incorporated more explicit mention of `networkx` which is what we use to process the graphs though this is a technique of data reduction and does not rely explicitly on any particular graphics. The visualization of the graphs themselves is not tied to any specific package either. But if you think we need an explicit mention, I could include that we graphed using pyvis. 

Cugraph was mentioned as it is a graph processing library accelerated using gpu's (learned about it at Scipy2022) but I don't it isn't a graph visualization library.

I clarified the maximum spanning tree aspect. And though we selected prim's algorithm other MST algorithms can work. So I expanded a little more there. Let know if that addresses your concerns.

2023-06-26 22:38 UTC, summerswallow-whi commented on papers/xu_etal/drn.tex
> +To distill insightful and actionable visualizations from large survey data, it is essential to balance the trade-off between simplicity and completeness, highlighting the most critical variables for
@cbcunc Am I supposed to resolve it or the editor?

2023-06-28 22:03 UTC, summerswallow-whi commented
@jsingh811 @Tolulade-A I think I addressed all your concerned. If I don't hear anything. I'll resolve the open conversations.

@cbcunc I hope this is what I'm supposed to do. Please advise if this is not the right procedure

2023-06-29 09:17 UTC, Tolulade-A commented
hi @summerswallow-whi i can see that you made some changes and the github repo is live.

2023-07-03 01:50 UTC, cbcunc commented
@scoobies mark pending comment

2023-07-03 16:24 UTC, jsingh811 commented
@summerswallow-whi did you find room to add more references? That's all from my end. Thanks.

2023-07-03 18:18 UTC, summerswallow-whi commented
@jsingh811 Yes. I was able to find an additional reference.

2023-07-06 18:03 UTC, summerswallow-whi commented
@scoobies build status

2023-07-06 18:03 UTC, scoobies commented
{"WestHealth-xu_et_al"=>{"data"=>{"build_output"=>"[*] Updating proceedings build tools in {self.master_repo_path}...\nAlready up to date.\n[*] Check out paper repository...\nCloning into '/tmp/tmpjn5el_fr'...\nMoving proceedings build tools to temp directory...\n[*] Build the paper...\nBuilding: xu_etal\n*** Warning: /tmp/tmpjn5el_fr/publisher/../output/xu_etal/paper_stats.json does not exist.\n*** Warning: /tmp/tmpjn5el_fr/publisher/_build/toc.json does not exist.\n*** Warning: /tmp/tmpjn5el_fr/publisher/_build/other.json does not exist.\nPDFLaTeX error output:\n================================================================================\nThis is pdfTeX, Version 3.14159265-2.6-1.40.20 (TeX Live 2019/Debian) (preloaded format=pdflatex)\n restricted \\write18 enabled.\nentering extended mode\n(./paper.tex\nLaTeX2e <2020-02-02> patch level 2\nL3 programming layer <2020-02-14> (./IEEEtran.cls\nDocument Class: IEEEtran 2015/08/26 V1.8b by Michael Shell\n-- See the \"IEEEtran_HOWTO\" manual for usage information.\n-- http://www.michaelshell.org/tex/ieeetran/\n(/usr/share/texlive/texmf-dist/tex/latex/psnfss/ot1ppl.fd)\n-- Using IEEE Computer Society mode.\n-- Using 8.5in x 11in (letter) paper.\n-- Using PDF output.\n-- This is a 10 point document.\n) (/usr/share/texlive/texmf-dist/tex/latex/cmap/cmap.sty)\n(/usr/share/texlive/texmf-dist/tex/latex/base/ifthen.sty)\n(/usr/share/texlive/texmf-dist/tex/latex/base/fontenc.sty\n(/usr/share/texlive/texmf-dist/tex/latex/psnfss/t1ppl.fd)<<t1.cmap>>)\n(/usr/share/texlive/texmf-dist/tex/latex/base/inputenc.sty)\n(/usr/share/texlive/texmf-dist/tex/latex/amsmath/amsmath.sty\nFor additional information on amsmath, use the `?' option.\n(/usr/share/texlive/texmf-dist/tex/latex/amsmath/amstext.sty\n(/usr/share/texlive/texmf-dist/tex/latex/amsmath/amsgen.sty))\n(/usr/share/texlive/texmf-dist/tex/latex/amsmath/amsbsy.sty)\n(/usr/share/texlive/texmf-dist/tex/latex/amsmath/amsopn.sty))\n(/usr/share/texlive/texmf-dist/tex/latex/booktabs/booktabs.sty)\n(/usr/share/texlive/texmf-dist/tex/latex/graphics/color.sty\n(/usr/share/texlive/texmf-dist/tex/latex/graphics-cfg/color.cfg)\n(/usr/share/texlive/texmf-dist/tex/latex/graphics-def/pdftex.def))\n(/usr/share/texlive/texmf-dist/tex/latex/caption/caption.sty\n(/usr/share/texlive/texmf-dist/tex/latex/caption/caption3.sty\n(/usr/share/texlive/texmf-dist/tex/latex/graphics/keyval.sty))\n\nPackage caption Warning: Unknown document class (or package),\n(caption)                standard defaults will be used.\nSee the caption package documentation for explanation.\n\n) (/usr/share/texlive/texmf-dist/tex/latex/float/float.sty)\n(/usr/share/texlive/texmf-dist/tex/latex/tools/longtable.sty)\n(/usr/share/texlive/texmf-dist/tex/latex/caption/ltcaption.sty)\n(/usr/share/texlive/texmf-dist/tex/latex/tools/array.sty) (./scipy.sty\n(./status.sty (./draftwatermark.sty (./everypage.sty)\n(/usr/share/texlive/texmf-dist/tex/latex/graphics/graphicx.sty\n(/usr/share/texlive/texmf-dist/tex/latex/graphics/graphics.sty\n(/usr/share/texlive/texmf-dist/tex/latex/graphics/trig.sty)\n(/usr/share/texlive/texmf-dist/tex/latex/graphics-cfg/graphics.cfg)))))\n(/usr/share/texlive/texmf-dist/tex/latex/psnfss/mathptmx.sty)\n(/usr/share/texlive/texmf-dist/tex/latex/psnfss/helvet.sty)\n(/usr/share/texlive/texmf-dist/tex/latex/psnfss/courier.sty)\n(/usr/share/texlive/texmf-dist/tex/latex/amsfonts/amsfonts.sty)\n(/usr/share/texlive/texmf-dist/tex/latex/amsfonts/amssymb.sty)\n(/usr/share/texlive/texmf-dist/tex/latex/tools/bm.sty)\n(/usr/share/texlive/texmf-dist/tex/latex/hyperref/hyperref.sty\n(/usr/share/texlive/texmf-dist/tex/generic/ltxcmds/ltxcmds.sty)\n(/usr/share/texlive/texmf-dist/tex/generic/iftex/iftex.sty)\n(/usr/share/texlive/texmf-dist/tex/latex/pdftexcmds/pdftexcmds.sty\n(/usr/share/texlive/texmf-dist/tex/generic/infwarerr/infwarerr.sty))\n(/usr/share/texlive/texmf-dist/tex/generic/kvsetkeys/kvsetkeys.sty)\n(/usr/share/texlive/texmf-dist/tex/generic/kvdefinekeys/kvdefinekeys.sty)\n(/usr/share/texlive/texmf-dist/tex/generic/pdfescape/pdfescape.sty)\n(/usr/share/texlive/texmf-dist/tex/latex/hycolor/hycolor.sty)\n(/usr/share/texlive/texmf-dist/tex/latex/letltxmacro/letltxmacro.sty)\n(/usr/share/texlive/texmf-dist/tex/latex/auxhook/auxhook.sty)\n(/usr/share/texlive/texmf-dist/tex/latex/kvoptions/kvoptions.sty)\n(/usr/share/texlive/texmf-dist/tex/latex/hyperref/pd1enc.def)\n(/usr/share/texlive/texmf-dist/tex/generic/intcalc/intcalc.sty)\n(/usr/share/texlive/texmf-dist/tex/generic/etexcmds/etexcmds.sty)\n(/usr/share/texlive/texmf-dist/tex/latex/url/url.sty)\n(/usr/share/texlive/texmf-dist/tex/generic/bitset/bitset.sty\n(/usr/share/texlive/texmf-dist/tex/generic/bigintcalc/bigintcalc.sty))\n(/usr/share/texlive/texmf-dist/tex/generic/atbegshi/atbegshi.sty))\n(/usr/share/texlive/texmf-dist/tex/latex/hyperref/hpdftex.def\n(/usr/share/texlive/texmf-dist/tex/latex/atveryend/atveryend.sty)\n(/usr/share/texlive/texmf-dist/tex/latex/rerunfilecheck/rerunfilecheck.sty\n(/usr/share/texlive/texmf-dist/tex/generic/uniquecounter/uniquecounter.sty)))\n\nPackage hyperref Warning: Option `pdftex' has already been used,\n(hyperref)                setting the option has no effect on input line 43.\n\n(/usr/share/texlive/texmf-dist/tex/latex/multirow/multirow.sty)\n(/usr/share/texlive/texmf-dist/tex/latex/base/textcomp.sty)\n(/usr/share/texlive/texmf-dist/tex/latex/upquote/upquote.sty)\n(/usr/share/texlive/texmf-dist/tex/latex/fancyvrb/fancyvrb.sty)\n(/usr/share/texlive/texmf-dist/tex/latex/algorithms/algorithm.sty))\n(/usr/share/texlive/texmf-dist/tex/latex/algorithmicx/algpseudocode.sty\n(/usr/share/texlive/texmf-dist/tex/latex/algorithmicx/algorithmicx.sty\nDocument Style algorithmicx 1.2 - a greatly improved `algorithmic' style\n)\nDocument Style - pseudocode environments for use with the `algorithmicx' style\n) (/usr/share/texlive/texmf-dist/tex/latex/l3backend/l3backend-pdfmode.def)\nNo file paper.aux.\n(/usr/share/texlive/texmf-dist/tex/latex/psnfss/t1ptm.fd)\n-- Lines per column: 61 (exact).\n(/usr/share/texlive/texmf-dist/tex/context/base/mkii/supp-pdf.mkii\n[Loading MPS to PDF converter (version 2006.09.02).]\n) (/usr/share/texlive/texmf-dist/tex/latex/epstopdf-pkg/epstopdf-base.sty\n(/usr/share/texlive/texmf-dist/tex/latex/latexconfig/epstopdf-sys.cfg))\n(/usr/share/texlive/texmf-dist/tex/latex/hyperref/nameref.sty\n(/usr/share/texlive/texmf-dist/tex/latex/refcount/refcount.sty)\n(/usr/share/texlive/texmf-dist/tex/generic/gettitlestring/gettitlestring.sty))\n(./page_numbers.tex) (/usr/share/texlive/texmf-dist/tex/latex/psnfss/t1phv.fd)\n(/usr/share/texlive/texmf-dist/tex/latex/psnfss/ot1ztmcm.fd)<<ot1.cmap>>\n(/usr/share/texlive/texmf-dist/tex/latex/psnfss/omlztmcm.fd)<<oml.cmap>>\n(/usr/share/texlive/texmf-dist/tex/latex/psnfss/omsztmcm.fd)<<oms.cmap>>\n(/usr/share/texlive/texmf-dist/tex/latex/psnfss/omxztmcm.fd)<<omx.cmap>>\n(/usr/share/texlive/texmf-dist/tex/latex/psnfss/ot1ptm.fd)\n(/usr/share/texlive/texmf-dist/tex/latex/psnfss/upzd.fd)\n(/usr/share/texlive/texmf-dist/tex/latex/psnfss/ts1ptm.fd)\n\nLaTeX Warning: Citation `Manyika2011BigDT' on page 1 undefined on input line 20\n0.\n\n(/usr/share/texlive/texmf-dist/tex/latex/psnfss/t1pcr.fd)\n\nLaTeX Warning: Citation `hernan2011simpsons' on page 1 undefined on input line \n202.\n\n\nLaTeX Warning: Citation `fayyad2002information' on page 1 undefined on input li\nne 204.\n\n\nLaTeX Warning: Citation `shneiderman1996eyes' on page 1 undefined on input line\n 204.\n\n\nLaTeX Warning: Citation `Wong1997MultivariateVU' on page 1 undefined on input l\nine 204.\n\n[1{/var/lib/texmf/fonts/map/pdftex/updmap/pdftex.map}]\n\nLaTeX Warning: Citation `wardlow2022perceptions' on page 2 undefined on input l\nine 210.\n\n\nLaTeX Warning: Citation `upton2000cobweb' on page 2 undefined on input line 210\n.\n\n\nLaTeX Warning: No positions in optional float specifier.\n               Default added (so using `tbp') on input line 281.\n\n\nLaTeX Warning: No positions in optional float  [...]

2023-07-23 20:55 UTC, cbcunc commented
@Tolulade-A @jsingh811 does this paper have your final review approval?

2023-07-23 20:55 UTC, cbcunc commented
@scoobies help

2023-07-23 20:55 UTC, scoobies commented
Hello @cbcunc, here are the things you can ask me to do:

```

# List all available commands
@scoobies help

# Show our community Code of Conduct and Guidelines
@scoobies code of conduct

# Add to this issue's reviewers list
@scoobies add @username to reviewers

# Remove from this issue's reviewers list
@scoobies remove @username from reviewers

# Assign a user as the editor of this submission
@scoobies assign @username as editor

# Remove the editor assigned to this submission
@scoobies remove editor

# Add a user to this issue's assignees list
@scoobies add assignee: @username

# Remove a user from this issue's assignees list
@scoobies remove assignee: @username

# Builds paper
@scoobies build paper

# Checks build status
@scoobies build status

# Check the references of the paper for missing DOIs
# Optionally, it can be run on a non-default branch 
@scoobies check references
@scoobies check references from branch custom-branch-name

# Label issue with: paper
@scoobies mark paper

# Label issue with: needs-review. Remove labels: unready, needs-more-review, pending-comment, ready
@scoobies mark needs review

# Label issue with: needs-more-review. Remove labels: unready, needs-review, pending-comment, ready
@scoobies mark needs more review

# Label issue with: pending-comment. Remove labels: unready, needs-review, needs-more-review, ready
@scoobies mark pending comment

# Label issue with: ready. Remove labels: unready, needs-review, needs-more-review, pending-comment
@scoobies mark ready

# Label issue with: unready. Remove labels: needs-review, needs-more-review, pending-comment, ready
@scoobies mark not ready

# Label issue with: does_not_build:server
@scoobies mark server fail

# Remove labels: does_not_build:server
@scoobies mark server success

```

2023-07-23 20:57 UTC, cbcunc commented
@scoobies check references

2023-07-23 20:57 UTC, scoobies commented
```
Reference check summary (note 'MISSING' DOIs are suggestions that need verification):

OK DOIs

- 10.1017/CBO9780511808432 is OK
- 10.1089/tmj.2022.0378 is OK
- 10.1007/BF01386390 is OK
- 10.1093/ije/dyr041 is OK
- 10.1109/TKDE.2012.35 is OK
- 10.1111/1467-9884.00221 is OK

MISSING DOIs

- 10.1109/vl.1996.545307 may be a valid DOI for title: The eyes have it: A task by data type taxonomy for information visualizations
- 10.1109/visual.1997.663866 may be a valid DOI for title: Multivariate visualization using metric scaling

INVALID DOIs

- None
```

2023-07-23 20:58 UTC, cbcunc commented
@ summerswallow-whi  Would you please address the missing DOIs above?

2023-07-23 23:34 UTC, summerswallow-whi commented
@scoobies build status

2023-07-23 23:34 UTC, scoobies commented
{"WestHealth-xu_et_al"=>{"data"=>{"build_output"=>"[*] Updating proceedings build tools in {self.master_repo_path}...\nAlready up to date.\n[*] Check out paper repository...\nCloning into '/tmp/tmpnkgbgd7b'...\nMoving proceedings build tools to temp directory...\n[*] Build the paper...\nBuilding: xu_etal\n*** Warning: /tmp/tmpnkgbgd7b/publisher/../output/xu_etal/paper_stats.json does not exist.\n*** Warning: /tmp/tmpnkgbgd7b/publisher/_build/toc.json does not exist.\n*** Warning: /tmp/tmpnkgbgd7b/publisher/_build/other.json does not exist.\n", "build_pdf_path"=>"/procbuild/procbuild/../cache/WestHealth-xu_et_al.pdf", "build_status"=>"success", "build_timestamp"=>"23/07 23:30"}, "status"=>"success"}}

2023-07-23 23:38 UTC, summerswallow-whi commented
@scoobies check references

2023-07-23 23:38 UTC, scoobies commented
```
Reference check summary (note 'MISSING' DOIs are suggestions that need verification):

OK DOIs

- 10.1089/tmj.2022.0378 is OK
- 10.1109/VL.1996.545307 is OK
- 10.1109/VISUAL.1997.663866 is OK
- 10.1007/BF01386390 is OK
- 10.1093/ije/dyr041 is OK
- 10.1109/TKDE.2012.35 is OK
- 10.1111/1467-9884.00221 is OK

MISSING DOIs

- None

INVALID DOIs

- None
```

2023-07-24 00:18 UTC, summerswallow-whi commented
@cbcunc missing DOI's added

2023-07-24 03:24 UTC, jsingh811 approved these changes

2023-07-24 10:41 UTC, Tolulade-A commented
> @Tolulade-A @jsingh811 does this paper have your final review approval?

@cbcunc 

The updated codebase link isn't live yet https://github.com/Westhealth/scipy2023/ other than this for me, it's okay.

2023-07-24 11:40 UTC, summerswallow-whi commented
@Tolulade-A Apologies I had created the repository and included the code, but forgot to make it public. I have verified it should be accessible now to everyone

2023-07-24 11:51 UTC, Tolulade-A commented
I've taken a look and spotted it, thanks for clarifying @summerswallow-whi 

@cbcunc approved for me.

2023-07-28 19:06 UTC, cbcunc commented
@scoobies mark ready

2023-08-05 22:58 UTC, deniederhut approved these changes
Thanks @Tolulade-A and @jsingh811 for your help getting this paper ready for publication! And thanks @summerswallow-whi for joining us at SciPy this year!

![source-3507242686](https://github.com/scipy-conference/scipy_proceedings/assets/6868396/606ad9a4-cb5e-4b2e-9d31-23d076a92fc7)

2023-08-05 22:58 UTC, merged