Paper: vak: a neural network framework for researchers studying animal acoustic communication
scipy-conference/scipy_proceedings pull request #825
Opened 2023-06-03 01:31 UTC by NickleDave

Hi 👋 submitting this -- @yardencsGitHub is co-author, tagging him in here

---

If you are creating this PR in order to submit a draft of your paper,
see http://procbuild.scipy.org/ for logs generated by the build
process.

See the [project readme](https://github.com/scipy-conference/scipy_proceedings#build-your-paper)
for more information.

*Editor*:  

*Reviewers*:

2023-06-03 15:03 UTC, deniederhut commented
@scoobies assign @mepa as editor

2023-06-03 15:03 UTC, scoobies commented
Assigned! @mepa is now the editor

2023-06-03 15:06 UTC, NickleDave commented
I haven't been able to get the LaTeX build to work locally so I switched to rst

2023-06-03 21:26 UTC, mepa commented
@scoobies build status

2023-06-03 21:26 UTC, scoobies commented
{"NickleDave-paper-david-nicholson"=>{"data"=>{"build_output"=>"[*] Updating proceedings build tools in {self.master_repo_path}...\nAlready up to date.\n[*] Check out paper repository...\nCloning into '/tmp/tmp1pde3v6i'...\nMoving proceedings build tools to temp directory...\n[*] Build the paper...\nBuilding: david_nicholson\n*** Warning: /tmp/tmp1pde3v6i/publisher/../output/david_nicholson/paper_stats.json does not exist.\nPDFLaTeX error output:\n================================================================================\nThis is pdfTeX, Version 3.14159265-2.6-1.40.20 (TeX Live 2019/Debian) (preloaded format=pdflatex)\n restricted \\write18 enabled.\nentering extended mode\n(./paper.tex\nLaTeX2e <2020-02-02> patch level 2\nL3 programming layer <2020-02-14> (./IEEEtran.cls\nDocument Class: IEEEtran 2015/08/26 V1.8b by Michael Shell\n-- See the \"IEEEtran_HOWTO\" manual for usage information.\n-- http://www.michaelshell.org/tex/ieeetran/\n(/usr/share/texlive/texmf-dist/tex/latex/psnfss/ot1ppl.fd)\n-- Using IEEE Computer Society mode.\n-- Using 8.5in x 11in (letter) paper.\n-- Using PDF output.\n-- This is a 10 point document.\n) (/usr/share/texlive/texmf-dist/tex/latex/cmap/cmap.sty)\n(/usr/share/texlive/texmf-dist/tex/latex/base/ifthen.sty)\n(/usr/share/texlive/texmf-dist/tex/latex/base/fontenc.sty\n(/usr/share/texlive/texmf-dist/tex/latex/psnfss/t1ppl.fd)<<t1.cmap>>)\n(/usr/share/texlive/texmf-dist/tex/latex/base/inputenc.sty)\n(/usr/share/texlive/texmf-dist/tex/latex/amsmath/amsmath.sty\nFor additional information on amsmath, use the `?' option.\n(/usr/share/texlive/texmf-dist/tex/latex/amsmath/amstext.sty\n(/usr/share/texlive/texmf-dist/tex/latex/amsmath/amsgen.sty))\n(/usr/share/texlive/texmf-dist/tex/latex/amsmath/amsbsy.sty)\n(/usr/share/texlive/texmf-dist/tex/latex/amsmath/amsopn.sty))\n(/usr/share/texlive/texmf-dist/tex/latex/graphics/color.sty\n(/usr/share/texlive/texmf-dist/tex/latex/graphics-cfg/color.cfg)\n(/usr/share/texlive/texmf-dist/tex/latex/graphics-def/pdftex.def))\n(/usr/share/texlive/texmf-dist/tex/latex/caption/caption.sty\n(/usr/share/texlive/texmf-dist/tex/latex/caption/caption3.sty\n(/usr/share/texlive/texmf-dist/tex/latex/graphics/keyval.sty))\n\nPackage caption Warning: Unknown document class (or package),\n(caption)                standard defaults will be used.\nSee the caption package documentation for explanation.\n\n) (/usr/share/texlive/texmf-dist/tex/latex/float/float.sty) (./scipy.sty\n(./status.sty (./draftwatermark.sty (./everypage.sty)\n(/usr/share/texlive/texmf-dist/tex/latex/graphics/graphicx.sty\n(/usr/share/texlive/texmf-dist/tex/latex/graphics/graphics.sty\n(/usr/share/texlive/texmf-dist/tex/latex/graphics/trig.sty)\n(/usr/share/texlive/texmf-dist/tex/latex/graphics-cfg/graphics.cfg)))))\n(/usr/share/texlive/texmf-dist/tex/latex/psnfss/mathptmx.sty)\n(/usr/share/texlive/texmf-dist/tex/latex/psnfss/helvet.sty)\n(/usr/share/texlive/texmf-dist/tex/latex/psnfss/courier.sty)\n(/usr/share/texlive/texmf-dist/tex/latex/amsfonts/amsfonts.sty)\n(/usr/share/texlive/texmf-dist/tex/latex/amsfonts/amssymb.sty)\n(/usr/share/texlive/texmf-dist/tex/latex/tools/bm.sty)\n(/usr/share/texlive/texmf-dist/tex/latex/hyperref/hyperref.sty\n(/usr/share/texlive/texmf-dist/tex/generic/ltxcmds/ltxcmds.sty)\n(/usr/share/texlive/texmf-dist/tex/generic/iftex/iftex.sty)\n(/usr/share/texlive/texmf-dist/tex/latex/pdftexcmds/pdftexcmds.sty\n(/usr/share/texlive/texmf-dist/tex/generic/infwarerr/infwarerr.sty))\n(/usr/share/texlive/texmf-dist/tex/generic/kvsetkeys/kvsetkeys.sty)\n(/usr/share/texlive/texmf-dist/tex/generic/kvdefinekeys/kvdefinekeys.sty)\n(/usr/share/texlive/texmf-dist/tex/generic/pdfescape/pdfescape.sty)\n(/usr/share/texlive/texmf-dist/tex/latex/hycolor/hycolor.sty)\n(/usr/share/texlive/texmf-dist/tex/latex/letltxmacro/letltxmacro.sty)\n(/usr/share/texlive/texmf-dist/tex/latex/auxhook/auxhook.sty)\n(/usr/share/texlive/texmf-dist/tex/latex/kvoptions/kvoptions.sty)\n(/usr/share/texlive/texmf-dist/tex/latex/hyperref/pd1enc.def)\n(/usr/share/texlive/texmf-dist/tex/generic/intcalc/intcalc.sty)\n(/usr/share/texlive/texmf-dist/tex/generic/etexcmds/etexcmds.sty)\n(/usr/share/texlive/texmf-dist/tex/latex/url/url.sty)\n(/usr/share/texlive/texmf-dist/tex/generic/bitset/bitset.sty\n(/usr/share/texlive/texmf-dist/tex/generic/bigintcalc/bigintcalc.sty))\n(/usr/share/texlive/texmf-dist/tex/generic/atbegshi/atbegshi.sty))\n(/usr/share/texlive/texmf-dist/tex/latex/hyperref/hpdftex.def\n(/usr/share/texlive/texmf-dist/tex/latex/atveryend/atveryend.sty)\n(/usr/share/texlive/texmf-dist/tex/latex/rerunfilecheck/rerunfilecheck.sty\n(/usr/share/texlive/texmf-dist/tex/generic/uniquecounter/uniquecounter.sty)))\n\nPackage hyperref Warning: Option `pdftex' has already been used,\n(hyperref)                setting the option has no effect on input line 43.\n\n(/usr/share/texlive/texmf-dist/tex/latex/tools/longtable.sty)\n(/usr/share/texlive/texmf-dist/tex/latex/multirow/multirow.sty)\n(/usr/share/texlive/texmf-dist/tex/latex/booktabs/booktabs.sty)\n(/usr/share/texlive/texmf-dist/tex/latex/base/textcomp.sty)\n(/usr/share/texlive/texmf-dist/tex/latex/upquote/upquote.sty)\n(/usr/share/texlive/texmf-dist/tex/latex/fancyvrb/fancyvrb.sty)\n(/usr/share/texlive/texmf-dist/tex/latex/algorithms/algorithm.sty))\n(/usr/share/texlive/texmf-dist/tex/latex/algorithmicx/algpseudocode.sty\n(/usr/share/texlive/texmf-dist/tex/latex/algorithmicx/algorithmicx.sty\nDocument Style algorithmicx 1.2 - a greatly improved `algorithmic' style\n)\nDocument Style - pseudocode environments for use with the `algorithmicx' style\n) (/usr/share/texlive/texmf-dist/tex/latex/l3backend/l3backend-pdfmode.def)\nNo file paper.aux.\n(/usr/share/texlive/texmf-dist/tex/latex/psnfss/t1ptm.fd)\n-- Lines per column: 61 (exact).\n(/usr/share/texlive/texmf-dist/tex/context/base/mkii/supp-pdf.mkii\n[Loading MPS to PDF converter (version 2006.09.02).]\n) (/usr/share/texlive/texmf-dist/tex/latex/epstopdf-pkg/epstopdf-base.sty\n(/usr/share/texlive/texmf-dist/tex/latex/latexconfig/epstopdf-sys.cfg))\n(/usr/share/texlive/texmf-dist/tex/latex/caption/ltcaption.sty)\n(/usr/share/texlive/texmf-dist/tex/latex/hyperref/nameref.sty\n(/usr/share/texlive/texmf-dist/tex/latex/refcount/refcount.sty)\n(/usr/share/texlive/texmf-dist/tex/generic/gettitlestring/gettitlestring.sty))\n(/usr/share/texlive/texmf-dist/tex/latex/psnfss/t1phv.fd)\n(/usr/share/texlive/texmf-dist/tex/latex/psnfss/ot1ztmcm.fd)<<ot1.cmap>>\n(/usr/share/texlive/texmf-dist/tex/latex/psnfss/omlztmcm.fd)<<oml.cmap>>\n(/usr/share/texlive/texmf-dist/tex/latex/psnfss/omsztmcm.fd)<<oms.cmap>>\n(/usr/share/texlive/texmf-dist/tex/latex/psnfss/omxztmcm.fd)<<omx.cmap>>\n(/usr/share/texlive/texmf-dist/tex/latex/psnfss/ot1ptm.fd)\n(/usr/share/texlive/texmf-dist/tex/latex/psnfss/t1pcr.fd)\n(/usr/share/texlive/texmf-dist/tex/latex/psnfss/upzd.fd)\n(/usr/share/texlive/texmf-dist/tex/latex/psnfss/ts1ptm.fd) (./page_numbers.tex)\n\nLaTeX Warning: Citation `hauserFacultyLanguageWhat2002' on page 1 undefined on \ninput line 210.\n\n\nLaTeX Warning: Citation `doupeBIRDSONGHUMANSPEECH1999' on page 1 undefined on i\nnput line 211.\n\n\nLaTeX Warning: Citation `petkovBirdsPrimatesSpoken2012' on page 1 undefined on \ninput line 213.\n\n\nLaTeX Warning: Citation `vernesMultidimensionalNatureVocal2021' on page 1 undef\nined on input line 214.\n\n\nLaTeX Warning: Citation `wirthlinModularApproachVocal2019' on page 1 undefined \non input line 215.\n\n\nLaTeX Warning: Citation `martinsSoundProductionLearning2020' on page 1 undefine\nd on input line 216.\n\n\nLaTeX Warning: Citation `martinsVocalLearningContinuum2020' on page 1 undefined\n on input line 216.\n\n\nLaTeX Warning: Citation `hopp2012animal' on page 1 undefined on input line 217.\n\n\n\nLaTeX Warning: Citation `sainburgComputationalNeuroethologyVocal2021' on page 1\n undefined on input line 220.\n\n\nLaTeX Warning: Citation `stowellComputationalBioacousticsDeep2022' on page 1 un\ndefined on input line 220.\n\n\nLaT [...]

2023-06-03 22:12 UTC, mepa reviewed
Hi @NickleDave! A careful checking of backticks throughout the file plus a couple other changes should fix the build errors seen above.

2023-06-03 22:12 UTC, mepa commented on papers/david_nicholson/nicholson.rst
> +Both the TweetyNet model from :cite:`{cohenAutomatedAnnotationBirdsong2022`
```suggestion
Both the TweetyNet model from :cite:`cohenAutomatedAnnotationBirdsong2022`
```

2023-06-03 22:12 UTC, mepa commented on papers/david_nicholson/nicholson.rst
> +and the Deep Audio Segmenter (DAS) from :cite:`{steinfathFastAccurateAnnotation2021` are examples of such models,
```suggestion
and the Deep Audio Segmenter (DAS) from :cite:`steinfathFastAccurateAnnotation2021` are examples of such models,
```

2023-06-03 22:12 UTC, mepa commented on papers/david_nicholson/nicholson.rst
> +To address this need, we developed vak :cite:`nicholsonVak2022` (\url{https://github.com/vocalpy/vak`),
looks like there's a backtick here instead of a closing bracket

2023-06-03 22:12 UTC, mepa commented on papers/david_nicholson/nicholson.rst
> +To relate a model as declared with a ``ModelDefinition` to the machine learning tasks that we implement within the vak framework,
Add a backtick to ``ModelDefinition`?

2023-06-03 22:12 UTC, mepa commented on papers/david_nicholson/nicholson.rst
> +Finally the ``'annot_path'` column points to annotation files,
Please check backticks throughout this paragraph.

2023-06-03 22:15 UTC, mepa commented
@scoobies mark server fail

2023-06-04 13:40 UTC, NickleDave commented
Thank you @mepa for catching those formatting issues, my apologies for making you do the work of spotting them. I thought I had fixed them with Find-Replace but apparently not.

2023-06-04 13:51 UTC, mepa commented
No worries, @NickleDave. Thanks for fixing those.

2023-06-04 13:51 UTC, mepa commented
@scoobies mark server success

2023-06-04 13:52 UTC, mepa commented
@scoobies check references

2023-06-04 13:52 UTC, scoobies commented
```
Reference check summary (note 'MISSING' DOIs are suggestions that need verification):

OK DOIs

- 10.1101/2022.06.26.497684 is OK
- 10.1126/science.abc6588 is OK
- 10.1038/s41386-018-0303-6 is OK
- 10.5281/zenodo.7627197 is OK
- 10.1146/annurev.neuro.22.1.567 is OK
- 10.1007/s10071-015-0933-6 is OK
- 10.5281/zenodo.7859091 is OK
- 10.7554/eLife.67855 is OK
- 10.1126/science.298.5598.1569 is OK
- 10.1111/evo.14489 is OK
- 10.1109/MCSE.2007.55 is OK
- 10.1007/s10618-008-0122-1 is OK
- 10.5281/ZENODO.6249316 is OK
- 10.1111/brv.12160 is OK
- 10.1111/2041-210X.12433 is OK
- 10.1371/journal.pone.0159188 is OK
- 10.1007/s42991-021-00222-2 is OK
- 10.1145/1873951.1874254 is OK
- 10.1145/1873951.1874254 is OK
- 10.1371/journal.pcbi.1003052 is OK
- 10.1371/journal.pbio.3000672 is OK
- 10.7554/eLife.75691 is OK
- 10.6084/m9.figshare.4805749.v5 is OK
- 10.5281/zenodo.6808839 is OK
- 10.1101/2023.03.11.532197 is OK
- 10.3389/fnevo.2012.00012 is OK
- 10.1038/srep39419 is OK
- 10.1371/journal.pone.0278522 is OK
- 10.1101/2021.03.16.435625 is OK
- 10.1002/ece3.5418 is OK
- 10.3389/fnbeh.2021.811737 is OK
- 10.1371/journal.pcbi.1008228 is OK
- 10.1093/beheco/arz202 is OK
- 10.7554/eLife.68837 is OK
- 10.5281/zenodo.3509134 is OK
- 10.5281/zenodo.4030140 is OK
- 10.1007/978-3-030-86383-8_6 is OK
- 10.48550/arXiv.1706.03762 is OK
- 10.1098/rstb.2020.0236 is OK
- 10.1109/MCSE.2011.37 is OK
- 10.1016/j.neuron.2019.09.036 is OK
- 10.1016/j.anbehav.2021.12.012 is OK

MISSING DOIs

- 10.1016/j.neunet.2005.06.042 may be a valid DOI for title: Framewise Phoneme Classification with Bidirectional LSTM and Other Neural Network Architectures
- 10.1007/978-3-642-24797-2_2 may be a valid DOI for title: Supervised Sequence Labelling
- 10.25080/majora-629e541a-008 may be a valid DOI for title: Comparison of Machine Learning Methods Applied to Birdsong Element Classification
- 10.1371/journal.pone.0092584 may be a valid DOI for title: Semi-Automatic Classification of Birdsong Elements Using a Linear Support Vector Machine
- 10.1006/anbe.1999.1416 may be a valid DOI for title: A Procedure for an Automated Measurement of Song Similarity

INVALID DOIs

- None
```

2023-06-06 12:51 UTC, deniederhut commented
@scoobies add @tanya-akumu to reviewers

2023-06-06 12:51 UTC, scoobies commented
@tanya-akumu added to the reviewers list!

2023-06-06 12:51 UTC, deniederhut commented
@scoobies code of conduct

2023-06-06 12:51 UTC, scoobies commented
Our CoC: https://www.scipy2023.scipy.org/code-of-conduct

2023-06-06 12:51 UTC, scoobies commented
Reports of abusive or harassing behavior may be reported to scipy@enthought.com

2023-06-07 21:03 UTC, deniederhut commented
@scoobies add @nermeetadhillon to reviewers

2023-06-07 21:03 UTC, scoobies commented
@nermeetadhillon added to the reviewers list!

2023-06-18 22:23 UTC, mepa commented
Hey @tanya-akumu and @nermeetadhillon! A friendly reminder that your initial review is due Friday, June 23rd.

2023-06-18 23:50 UTC, tanya-akumu commented
Hi Meghan,

Thank for the reminder. I have been on vacation but I’m working on it this
week.

Kind regards,
Tanya

On Mon, 19 Jun 2023 at 07:24, Meghann Agarwal ***@***.***>
wrote:

> Hey @tanya-akumu <https://github.com/tanya-akumu> and @nermeetadhillon
> <https://github.com/nermeetadhillon>! A friendly reminder that your
> initial review is due Friday, June 23rd.
>
> —
> Reply to this email directly, view it on GitHub
> <https://github.com/scipy-conference/scipy_proceedings/pull/825#issuecomment-1596290336>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/AM3F6CDX7JNNK33FQ76KTSDXL55YDANCNFSM6AAAAAAYY6VWAE>
> .
> You are receiving this because you were mentioned.Message ID:
> ***@***.***>
>

2023-06-22 01:23 UTC, tanya-akumu commented on papers/david_nicholson/main.tex
> +To address this need, we developed vak \cite{nicholsonVak2022} (\url{https://github.com/vocalpy/vak}), a neural network framework designed for researchers studying animal acoustic communication. vak
is the term 'vak' an acronym? If so, can you spell it out?

2023-06-22 02:07 UTC, tanya-akumu reviewed
Some references do not appear on the pdf draft. An example is the crowsetta citation in line 32 of main.tex and the Bengalese finch song repository citation in line 372. The citations appear as[?] indicating a mismatch in the name referenced in the .bib file.

2023-06-22 02:07 UTC, tanya-akumu commented on papers/david_nicholson/main.tex
> +In addition to this torchvision-like API, vak provides a command-line interface that allows researchers to work with neural network models without requiring significant coding and deep learning exper
the crowsetta reference does not appear on the pdf draft. Perhaps a mismatch of the reference in the bib file?

2023-06-22 03:11 UTC, tanya-akumu requested changes
Some references do not appear on the pdf draft. An example is the crowsetta citation in line 32 of main.tex and the Bengalese finch song repository citation in line 372. The citations appear as[?] indicating a mismatch in the name referenced in the .bib file.

2023-06-22 03:11 UTC, tanya-akumu commented on papers/david_nicholson/main.tex
> +\subsection{Related work \label{subsec:related-work}}
The flow of this section is not clear to me as a reader who is not well versed with acoustic communications research. The first paragraph tries to differentiate between acoustic communication and bioacoustics with little background information for readers not in this space. Since the paper is focusing on methods for acoustic communications research, I suggest moving this comparison between bioacoustics and acoustic communication in the introduction section, building up on explaining the motivation for a framework for the latter. This way, the related section only focuses on the methods used for acoustic communications research and the specific gaps that vak is filling.

2023-06-22 03:11 UTC, tanya-akumu commented on papers/david_nicholson/main.tex
> +\section{Methods \label{sec:methods}}
The methods section is somewhat convoluted and focused on the highlighting the differences between vak 1.0 and the initial version. It would be helpful to have a flowchart figure that indicates the usage of vak 1.0. What does an acoustic researcher do with vak when they have a dataset of interest? The flow chart can show the process of applying the dataset, declaring a model, specifying the task and the expected outputs after to help in the high-level explanation of the API

2023-06-22 03:11 UTC, tanya-akumu commented on papers/david_nicholson/main.tex
> +For this we consider the TweetyNet model in Cohen et al (citet).
please add a citation for the TweenyModel referenced here

2023-06-22 03:11 UTC, tanya-akumu commented on papers/david_nicholson/main.tex
> +As in \cite{cohenAutomatedAnnotationBirdsong2022}, we generated learning curves for performance on the Bengalese finch song repository \cite{BengaleseFinchSong2017}, training separate models for each
Please add a correct citation with persistent DOI for the Bengalese dataset used in getting the results. The reference does not appear on the pdf paper.

2023-06-22 03:11 UTC, tanya-akumu commented on papers/david_nicholson/main.tex
> +\section{Results \label{sec:results}}
Can there be an experimental setup that describes the configurations you used to obtain the results? What parameters and hyperparameters did you use? Which datasets (including source) and models were used and how many runs were done etc. This will be helpful for someone who wants to replicate the results you got.

2023-06-22 03:11 UTC, tanya-akumu commented on papers/david_nicholson/main.tex
> +We compare the original model, that is trained on batches of spectrogram windows drawn at random from an entire training set, to another model that is trained on entire bouts. Thus the first is a \te
Are these two models of the same neural architecture? Were both models defined using the vak API and trained on different training sets? A description of the setup of these models will be helpful for the reader to follow on the achievement of the technical results

2023-06-22 03:11 UTC, tanya-akumu commented on papers/david_nicholson/main.tex
> +The configuration file follows the TOML format that has been adopted among others by Python and Rust. Commands through the CLI take the form of vak command configfile, e.g., \texttt{vak train gy6or6\
What is the full acronym for TOML? Please describe it as you did the CLI.

2023-06-22 03:11 UTC, tanya-akumu commented on papers/david_nicholson/main.tex
> +Here we presented vak, a neural network framework for researchers studying acoustic communication. In Section~\ref{sec:methods} we described its design and development. Then in Section~\ref{sec:resul
Given the increase in size in datasets and models, deep learning frameworks end up requiring computational resources for training. Are there any results that provide insights into the computational requirements, scalability, and practicality of the proposed framework? This could be in the form of training times which could help assess the feasibility and efficiency of the framework.

2023-06-26 20:10 UTC, NickleDave commented
Thank you so much @tanya-akumu for your review! Just letting you know I saw this and will be working on addressing your comments

2023-06-30 23:40 UTC, mepa commented
@scoobies remove @nermeetadhillon from reviewers

2023-06-30 23:40 UTC, scoobies commented
@nermeetadhillon removed from the reviewers list!

2023-06-30 23:41 UTC, mepa commented
@scoobies mark pending comment

2023-07-14 16:39 UTC, NickleDave commented on papers/david_nicholson/main.tex
> +To address this need, we developed vak \cite{nicholsonVak2022} (\url{https://github.com/vocalpy/vak}), a neural network framework designed for researchers studying animal acoustic communication. vak
It is not an acronym. I added an explanation in bc86432

2023-07-14 16:54 UTC, NickleDave commented on papers/david_nicholson/main.tex
> +The configuration file follows the TOML format that has been adopted among others by Python and Rust. Commands through the CLI take the form of vak command configfile, e.g., \texttt{vak train gy6or6\
Added in 638c56c

2023-07-14 20:44 UTC, deniederhut commented
Hey @tanya-akumu! How do you feel about the updates from the author?

2023-07-14 23:10 UTC, NickleDave commented
Thank you again @tanya-akumu for your thorough review.

I have completely revised the section on the API and the results to address your comments about [the lack of information about workflows in the description of the API](https://github.com/scipy-conference/scipy_proceedings/pull/825#discussion_r1237919163) and [the lack of experimental method in the results section](https://github.com/scipy-conference/scipy_proceedings/pull/825#discussion_r1237930445). The new experiments reported in the results section are meant to illustrate the API and typical workflows, and provide proof-of-concept evidence that the design of vak supports these intended workflows. I also included as much experimental detail as possible without going over the page limit. I have also created a repository with configuration files and scripts to assist with replicating these results, and I include a link at the top of the results.

I also made the following minor revisions:
- [x] explain the name "vak" https://github.com/scipy-conference/scipy_proceedings/pull/825#discussion_r1263929981
- [x] fix broken references
- [x] define TOML https://github.com/scipy-conference/scipy_proceedings/pull/825#discussion_r1263943406

Again I appreciate your helpful review

2023-07-15 20:53 UTC, NickleDave commented on papers/david_nicholson/main.tex
> +We compare the original model, that is trained on batches of spectrogram windows drawn at random from an entire training set, to another model that is trained on entire bouts. Thus the first is a \te
I removed this experiment in favor of others that better demonstrate the usage of the framework, as now described in the text

2023-07-15 20:56 UTC, NickleDave commented on papers/david_nicholson/main.tex
> +\section{Methods \label{sec:methods}}
> The methods section is somewhat convoluted and focused on the highlighting the differences between vak 1.0 and the initial version.

You are right that the description of the `models` module in particular focused too heavily on differences between version 1.0 and the initial version. Inn 9e397a8 I have revised to focus on how vak provides easy access to models and only mention in passing that this addresses limitations of the initial version.

> It would be helpful to have a flowchart figure that indicates the usage of vak 1.0. 

I have added such a flowchart and a description of workflows in 4833570 and 80480c5

2023-07-16 00:28 UTC, NickleDave commented
@scoobies build status

2023-07-16 00:28 UTC, scoobies commented
{"NickleDave-paper-david-nicholson"=>{"data"=>{"build_output"=>"[*] Updating proceedings build tools in {self.master_repo_path}...\nAlready up to date.\n[*] Check out paper repository...\nCloning into '/tmp/tmpc8ks7wao'...\nMoving proceedings build tools to temp directory...\n[*] Build the paper...\nBuilding: david_nicholson\n*** Warning: /tmp/tmpc8ks7wao/publisher/../output/david_nicholson/paper_stats.json does not exist.\nPDFLaTeX error output:\n================================================================================\nThis is pdfTeX, Version 3.14159265-2.6-1.40.20 (TeX Live 2019/Debian) (preloaded format=pdflatex)\n restricted \\write18 enabled.\nentering extended mode\n(./paper.tex\nLaTeX2e <2020-02-02> patch level 2\nL3 programming layer <2020-02-14> (./IEEEtran.cls\nDocument Class: IEEEtran 2015/08/26 V1.8b by Michael Shell\n-- See the \"IEEEtran_HOWTO\" manual for usage information.\n-- http://www.michaelshell.org/tex/ieeetran/\n(/usr/share/texlive/texmf-dist/tex/latex/psnfss/ot1ppl.fd)\n-- Using IEEE Computer Society mode.\n-- Using 8.5in x 11in (letter) paper.\n-- Using PDF output.\n-- This is a 10 point document.\n) (/usr/share/texlive/texmf-dist/tex/latex/cmap/cmap.sty)\n(/usr/share/texlive/texmf-dist/tex/latex/base/ifthen.sty)\n(/usr/share/texlive/texmf-dist/tex/latex/base/fontenc.sty\n(/usr/share/texlive/texmf-dist/tex/latex/psnfss/t1ppl.fd)<<t1.cmap>>)\n(/usr/share/texlive/texmf-dist/tex/latex/base/inputenc.sty)\n(/usr/share/texlive/texmf-dist/tex/latex/amsmath/amsmath.sty\nFor additional information on amsmath, use the `?' option.\n(/usr/share/texlive/texmf-dist/tex/latex/amsmath/amstext.sty\n(/usr/share/texlive/texmf-dist/tex/latex/amsmath/amsgen.sty))\n(/usr/share/texlive/texmf-dist/tex/latex/amsmath/amsbsy.sty)\n(/usr/share/texlive/texmf-dist/tex/latex/amsmath/amsopn.sty))\n(/usr/share/texlive/texmf-dist/tex/latex/graphics/color.sty\n(/usr/share/texlive/texmf-dist/tex/latex/graphics-cfg/color.cfg)\n(/usr/share/texlive/texmf-dist/tex/latex/graphics-def/pdftex.def))\n(/usr/share/texlive/texmf-dist/tex/latex/caption/caption.sty\n(/usr/share/texlive/texmf-dist/tex/latex/caption/caption3.sty\n(/usr/share/texlive/texmf-dist/tex/latex/graphics/keyval.sty))\n\nPackage caption Warning: Unknown document class (or package),\n(caption)                standard defaults will be used.\nSee the caption package documentation for explanation.\n\n) (/usr/share/texlive/texmf-dist/tex/latex/float/float.sty) (./scipy.sty\n(./status.sty (./draftwatermark.sty (./everypage.sty)\n(/usr/share/texlive/texmf-dist/tex/latex/graphics/graphicx.sty\n(/usr/share/texlive/texmf-dist/tex/latex/graphics/graphics.sty\n(/usr/share/texlive/texmf-dist/tex/latex/graphics/trig.sty)\n(/usr/share/texlive/texmf-dist/tex/latex/graphics-cfg/graphics.cfg)))))\n(/usr/share/texlive/texmf-dist/tex/latex/psnfss/mathptmx.sty)\n(/usr/share/texlive/texmf-dist/tex/latex/psnfss/helvet.sty)\n(/usr/share/texlive/texmf-dist/tex/latex/psnfss/courier.sty)\n(/usr/share/texlive/texmf-dist/tex/latex/amsfonts/amsfonts.sty)\n(/usr/share/texlive/texmf-dist/tex/latex/amsfonts/amssymb.sty)\n(/usr/share/texlive/texmf-dist/tex/latex/tools/bm.sty)\n(/usr/share/texlive/texmf-dist/tex/latex/hyperref/hyperref.sty\n(/usr/share/texlive/texmf-dist/tex/generic/ltxcmds/ltxcmds.sty)\n(/usr/share/texlive/texmf-dist/tex/generic/iftex/iftex.sty)\n(/usr/share/texlive/texmf-dist/tex/latex/pdftexcmds/pdftexcmds.sty\n(/usr/share/texlive/texmf-dist/tex/generic/infwarerr/infwarerr.sty))\n(/usr/share/texlive/texmf-dist/tex/generic/kvsetkeys/kvsetkeys.sty)\n(/usr/share/texlive/texmf-dist/tex/generic/kvdefinekeys/kvdefinekeys.sty)\n(/usr/share/texlive/texmf-dist/tex/generic/pdfescape/pdfescape.sty)\n(/usr/share/texlive/texmf-dist/tex/latex/hycolor/hycolor.sty)\n(/usr/share/texlive/texmf-dist/tex/latex/letltxmacro/letltxmacro.sty)\n(/usr/share/texlive/texmf-dist/tex/latex/auxhook/auxhook.sty)\n(/usr/share/texlive/texmf-dist/tex/latex/kvoptions/kvoptions.sty)\n(/usr/share/texlive/texmf-dist/tex/latex/hyperref/pd1enc.def)\n(/usr/share/texlive/texmf-dist/tex/generic/intcalc/intcalc.sty)\n(/usr/share/texlive/texmf-dist/tex/generic/etexcmds/etexcmds.sty)\n(/usr/share/texlive/texmf-dist/tex/latex/url/url.sty)\n(/usr/share/texlive/texmf-dist/tex/generic/bitset/bitset.sty\n(/usr/share/texlive/texmf-dist/tex/generic/bigintcalc/bigintcalc.sty))\n(/usr/share/texlive/texmf-dist/tex/generic/atbegshi/atbegshi.sty))\n(/usr/share/texlive/texmf-dist/tex/latex/hyperref/hpdftex.def\n(/usr/share/texlive/texmf-dist/tex/latex/atveryend/atveryend.sty)\n(/usr/share/texlive/texmf-dist/tex/latex/rerunfilecheck/rerunfilecheck.sty\n(/usr/share/texlive/texmf-dist/tex/generic/uniquecounter/uniquecounter.sty)))\n\nPackage hyperref Warning: Option `pdftex' has already been used,\n(hyperref)                setting the option has no effect on input line 43.\n\n(/usr/share/texlive/texmf-dist/tex/latex/tools/longtable.sty)\n(/usr/share/texlive/texmf-dist/tex/latex/multirow/multirow.sty)\n(/usr/share/texlive/texmf-dist/tex/latex/booktabs/booktabs.sty)\n(/usr/share/texlive/texmf-dist/tex/latex/base/textcomp.sty)\n(/usr/share/texlive/texmf-dist/tex/latex/upquote/upquote.sty)\n(/usr/share/texlive/texmf-dist/tex/latex/fancyvrb/fancyvrb.sty)\n(/usr/share/texlive/texmf-dist/tex/latex/algorithms/algorithm.sty))\n(/usr/share/texlive/texmf-dist/tex/latex/algorithmicx/algpseudocode.sty\n(/usr/share/texlive/texmf-dist/tex/latex/algorithmicx/algorithmicx.sty\nDocument Style algorithmicx 1.2 - a greatly improved `algorithmic' style\n)\nDocument Style - pseudocode environments for use with the `algorithmicx' style\n) (/usr/share/texlive/texmf-dist/tex/latex/l3backend/l3backend-pdfmode.def)\nNo file paper.aux.\n(/usr/share/texlive/texmf-dist/tex/latex/psnfss/t1ptm.fd)\n-- Lines per column: 61 (exact).\n(/usr/share/texlive/texmf-dist/tex/context/base/mkii/supp-pdf.mkii\n[Loading MPS to PDF converter (version 2006.09.02).]\n) (/usr/share/texlive/texmf-dist/tex/latex/epstopdf-pkg/epstopdf-base.sty\n(/usr/share/texlive/texmf-dist/tex/latex/latexconfig/epstopdf-sys.cfg))\n(/usr/share/texlive/texmf-dist/tex/latex/caption/ltcaption.sty)\n(/usr/share/texlive/texmf-dist/tex/latex/hyperref/nameref.sty\n(/usr/share/texlive/texmf-dist/tex/latex/refcount/refcount.sty)\n(/usr/share/texlive/texmf-dist/tex/generic/gettitlestring/gettitlestring.sty))\n(/usr/share/texlive/texmf-dist/tex/latex/psnfss/t1phv.fd)\n(/usr/share/texlive/texmf-dist/tex/latex/psnfss/ot1ztmcm.fd)<<ot1.cmap>>\n(/usr/share/texlive/texmf-dist/tex/latex/psnfss/omlztmcm.fd)<<oml.cmap>>\n(/usr/share/texlive/texmf-dist/tex/latex/psnfss/omsztmcm.fd)<<oms.cmap>>\n(/usr/share/texlive/texmf-dist/tex/latex/psnfss/omxztmcm.fd)<<omx.cmap>>\n(/usr/share/texlive/texmf-dist/tex/latex/psnfss/ot1ptm.fd)\n(/usr/share/texlive/texmf-dist/tex/latex/psnfss/t1pcr.fd)\n(/usr/share/texlive/texmf-dist/tex/latex/psnfss/upzd.fd)\n(/usr/share/texlive/texmf-dist/tex/latex/psnfss/ts1ptm.fd) (./page_numbers.tex)\n\nLaTeX Warning: Citation `hauserFacultyLanguageWhat2002' on page 1 undefined on \ninput line 213.\n\n\nLaTeX Warning: Citation `doupeBIRDSONGHUMANSPEECH1999' on page 1 undefined on i\nnput line 215.\n\n\nLaTeX Warning: Citation `petkovBirdsPrimatesSpoken2012' on page 1 undefined on \ninput line 217.\n\n\nLaTeX Warning: Citation `vernesMultidimensionalNatureVocal2021' on page 1 undef\nined on input line 217.\n\n\nLaTeX Warning: Citation `wirthlinModularApproachVocal2019' on page 1 undefined \non input line 217.\n\n\nLaTeX Warning: Citation `martinsSoundProductionLearning2020' on page 1 undefine\nd on input line 217.\n\n\nLaTeX Warning: Citation `martinsVocalLearningContinuum2020' on page 1 undefined\n on input line 217.\n\n\nLaTeX Warning: Citation `hopp2012animal' on page 1 undefined on input line 218.\n\n\n\nLaTeX Warning: Citation `sainburgComputationalNeuroethologyVocal2021' on page 1\n undefined on input line 221.\n\n\nLaTeX Warning: Citation `stowellComputationalBioacousticsDeep2022' on page 1 un\ndefined on input line 221.\n\n\nLaT [...]

2023-07-16 00:34 UTC, NickleDave commented
@scoobies build status

2023-07-16 00:34 UTC, scoobies commented
{"NickleDave-paper-david-nicholson"=>{"data"=>{"build_output"=>"[*] Updating proceedings build tools in {self.master_repo_path}...\nAlready up to date.\n[*] Check out paper repository...\nCloning into '/tmp/tmpn82ccl9i'...\nMoving proceedings build tools to temp directory...\n[*] Build the paper...\nBuilding: david_nicholson\n*** Warning: /tmp/tmpn82ccl9i/publisher/../output/david_nicholson/paper_stats.json does not exist.\nPDFLaTeX error output:\n================================================================================\nThis is pdfTeX, Version 3.14159265-2.6-1.40.20 (TeX Live 2019/Debian) (preloaded format=pdflatex)\n restricted \\write18 enabled.\nentering extended mode\n(./paper.tex\nLaTeX2e <2020-02-02> patch level 2\nL3 programming layer <2020-02-14> (./IEEEtran.cls\nDocument Class: IEEEtran 2015/08/26 V1.8b by Michael Shell\n-- See the \"IEEEtran_HOWTO\" manual for usage information.\n-- http://www.michaelshell.org/tex/ieeetran/\n(/usr/share/texlive/texmf-dist/tex/latex/psnfss/ot1ppl.fd)\n-- Using IEEE Computer Society mode.\n-- Using 8.5in x 11in (letter) paper.\n-- Using PDF output.\n-- This is a 10 point document.\n) (/usr/share/texlive/texmf-dist/tex/latex/cmap/cmap.sty)\n(/usr/share/texlive/texmf-dist/tex/latex/base/ifthen.sty)\n(/usr/share/texlive/texmf-dist/tex/latex/base/fontenc.sty\n(/usr/share/texlive/texmf-dist/tex/latex/psnfss/t1ppl.fd)<<t1.cmap>>)\n(/usr/share/texlive/texmf-dist/tex/latex/base/inputenc.sty)\n(/usr/share/texlive/texmf-dist/tex/latex/amsmath/amsmath.sty\nFor additional information on amsmath, use the `?' option.\n(/usr/share/texlive/texmf-dist/tex/latex/amsmath/amstext.sty\n(/usr/share/texlive/texmf-dist/tex/latex/amsmath/amsgen.sty))\n(/usr/share/texlive/texmf-dist/tex/latex/amsmath/amsbsy.sty)\n(/usr/share/texlive/texmf-dist/tex/latex/amsmath/amsopn.sty))\n(/usr/share/texlive/texmf-dist/tex/latex/graphics/color.sty\n(/usr/share/texlive/texmf-dist/tex/latex/graphics-cfg/color.cfg)\n(/usr/share/texlive/texmf-dist/tex/latex/graphics-def/pdftex.def))\n(/usr/share/texlive/texmf-dist/tex/latex/caption/caption.sty\n(/usr/share/texlive/texmf-dist/tex/latex/caption/caption3.sty\n(/usr/share/texlive/texmf-dist/tex/latex/graphics/keyval.sty))\n\nPackage caption Warning: Unknown document class (or package),\n(caption)                standard defaults will be used.\nSee the caption package documentation for explanation.\n\n) (/usr/share/texlive/texmf-dist/tex/latex/float/float.sty) (./scipy.sty\n(./status.sty (./draftwatermark.sty (./everypage.sty)\n(/usr/share/texlive/texmf-dist/tex/latex/graphics/graphicx.sty\n(/usr/share/texlive/texmf-dist/tex/latex/graphics/graphics.sty\n(/usr/share/texlive/texmf-dist/tex/latex/graphics/trig.sty)\n(/usr/share/texlive/texmf-dist/tex/latex/graphics-cfg/graphics.cfg)))))\n(/usr/share/texlive/texmf-dist/tex/latex/psnfss/mathptmx.sty)\n(/usr/share/texlive/texmf-dist/tex/latex/psnfss/helvet.sty)\n(/usr/share/texlive/texmf-dist/tex/latex/psnfss/courier.sty)\n(/usr/share/texlive/texmf-dist/tex/latex/amsfonts/amsfonts.sty)\n(/usr/share/texlive/texmf-dist/tex/latex/amsfonts/amssymb.sty)\n(/usr/share/texlive/texmf-dist/tex/latex/tools/bm.sty)\n(/usr/share/texlive/texmf-dist/tex/latex/hyperref/hyperref.sty\n(/usr/share/texlive/texmf-dist/tex/generic/ltxcmds/ltxcmds.sty)\n(/usr/share/texlive/texmf-dist/tex/generic/iftex/iftex.sty)\n(/usr/share/texlive/texmf-dist/tex/latex/pdftexcmds/pdftexcmds.sty\n(/usr/share/texlive/texmf-dist/tex/generic/infwarerr/infwarerr.sty))\n(/usr/share/texlive/texmf-dist/tex/generic/kvsetkeys/kvsetkeys.sty)\n(/usr/share/texlive/texmf-dist/tex/generic/kvdefinekeys/kvdefinekeys.sty)\n(/usr/share/texlive/texmf-dist/tex/generic/pdfescape/pdfescape.sty)\n(/usr/share/texlive/texmf-dist/tex/latex/hycolor/hycolor.sty)\n(/usr/share/texlive/texmf-dist/tex/latex/letltxmacro/letltxmacro.sty)\n(/usr/share/texlive/texmf-dist/tex/latex/auxhook/auxhook.sty)\n(/usr/share/texlive/texmf-dist/tex/latex/kvoptions/kvoptions.sty)\n(/usr/share/texlive/texmf-dist/tex/latex/hyperref/pd1enc.def)\n(/usr/share/texlive/texmf-dist/tex/generic/intcalc/intcalc.sty)\n(/usr/share/texlive/texmf-dist/tex/generic/etexcmds/etexcmds.sty)\n(/usr/share/texlive/texmf-dist/tex/latex/url/url.sty)\n(/usr/share/texlive/texmf-dist/tex/generic/bitset/bitset.sty\n(/usr/share/texlive/texmf-dist/tex/generic/bigintcalc/bigintcalc.sty))\n(/usr/share/texlive/texmf-dist/tex/generic/atbegshi/atbegshi.sty))\n(/usr/share/texlive/texmf-dist/tex/latex/hyperref/hpdftex.def\n(/usr/share/texlive/texmf-dist/tex/latex/atveryend/atveryend.sty)\n(/usr/share/texlive/texmf-dist/tex/latex/rerunfilecheck/rerunfilecheck.sty\n(/usr/share/texlive/texmf-dist/tex/generic/uniquecounter/uniquecounter.sty)))\n\nPackage hyperref Warning: Option `pdftex' has already been used,\n(hyperref)                setting the option has no effect on input line 43.\n\n(/usr/share/texlive/texmf-dist/tex/latex/tools/longtable.sty)\n(/usr/share/texlive/texmf-dist/tex/latex/multirow/multirow.sty)\n(/usr/share/texlive/texmf-dist/tex/latex/booktabs/booktabs.sty)\n(/usr/share/texlive/texmf-dist/tex/latex/base/textcomp.sty)\n(/usr/share/texlive/texmf-dist/tex/latex/upquote/upquote.sty)\n(/usr/share/texlive/texmf-dist/tex/latex/fancyvrb/fancyvrb.sty)\n(/usr/share/texlive/texmf-dist/tex/latex/algorithms/algorithm.sty))\n(/usr/share/texlive/texmf-dist/tex/latex/algorithmicx/algpseudocode.sty\n(/usr/share/texlive/texmf-dist/tex/latex/algorithmicx/algorithmicx.sty\nDocument Style algorithmicx 1.2 - a greatly improved `algorithmic' style\n)\nDocument Style - pseudocode environments for use with the `algorithmicx' style\n) (/usr/share/texlive/texmf-dist/tex/latex/l3backend/l3backend-pdfmode.def)\nNo file paper.aux.\n(/usr/share/texlive/texmf-dist/tex/latex/psnfss/t1ptm.fd)\n-- Lines per column: 61 (exact).\n(/usr/share/texlive/texmf-dist/tex/context/base/mkii/supp-pdf.mkii\n[Loading MPS to PDF converter (version 2006.09.02).]\n) (/usr/share/texlive/texmf-dist/tex/latex/epstopdf-pkg/epstopdf-base.sty\n(/usr/share/texlive/texmf-dist/tex/latex/latexconfig/epstopdf-sys.cfg))\n(/usr/share/texlive/texmf-dist/tex/latex/caption/ltcaption.sty)\n(/usr/share/texlive/texmf-dist/tex/latex/hyperref/nameref.sty\n(/usr/share/texlive/texmf-dist/tex/latex/refcount/refcount.sty)\n(/usr/share/texlive/texmf-dist/tex/generic/gettitlestring/gettitlestring.sty))\n(/usr/share/texlive/texmf-dist/tex/latex/psnfss/t1phv.fd)\n(/usr/share/texlive/texmf-dist/tex/latex/psnfss/ot1ztmcm.fd)<<ot1.cmap>>\n(/usr/share/texlive/texmf-dist/tex/latex/psnfss/omlztmcm.fd)<<oml.cmap>>\n(/usr/share/texlive/texmf-dist/tex/latex/psnfss/omsztmcm.fd)<<oms.cmap>>\n(/usr/share/texlive/texmf-dist/tex/latex/psnfss/omxztmcm.fd)<<omx.cmap>>\n(/usr/share/texlive/texmf-dist/tex/latex/psnfss/ot1ptm.fd)\n(/usr/share/texlive/texmf-dist/tex/latex/psnfss/t1pcr.fd)\n(/usr/share/texlive/texmf-dist/tex/latex/psnfss/upzd.fd)\n(/usr/share/texlive/texmf-dist/tex/latex/psnfss/ts1ptm.fd) (./page_numbers.tex)\n\nLaTeX Warning: Citation `hauserFacultyLanguageWhat2002' on page 1 undefined on \ninput line 213.\n\n\nLaTeX Warning: Citation `doupeBIRDSONGHUMANSPEECH1999' on page 1 undefined on i\nnput line 215.\n\n\nLaTeX Warning: Citation `petkovBirdsPrimatesSpoken2012' on page 1 undefined on \ninput line 217.\n\n\nLaTeX Warning: Citation `vernesMultidimensionalNatureVocal2021' on page 1 undef\nined on input line 217.\n\n\nLaTeX Warning: Citation `wirthlinModularApproachVocal2019' on page 1 undefined \non input line 217.\n\n\nLaTeX Warning: Citation `martinsSoundProductionLearning2020' on page 1 undefine\nd on input line 217.\n\n\nLaTeX Warning: Citation `martinsVocalLearningContinuum2020' on page 1 undefined\n on input line 217.\n\n\nLaTeX Warning: Citation `hopp2012animal' on page 1 undefined on input line 218.\n\n\n\nLaTeX Warning: Citation `sainburgComputationalNeuroethologyVocal2021' on page 1\n undefined on input line 221.\n\n\nLaTeX Warning: Citation `stowellComputationalBioacousticsDeep2022' on page 1 un\ndefined on input line 221.\n\n\nLaT [...]

2023-07-19 11:05 UTC, mepa commented
Hi @tanya-akumu, do you have a final recommendation for this paper? Is it now ready for inclusion in the proceedings?

2023-07-20 15:22 UTC, NickleDave commented
Hi again @tanya-akumu just following up on the pings from @mepa and @deniederhut -- I have made some final edits to fix up typos and tweak wording.

In case it got lost in the additional commits, I believe I have addressed all your comments as outlined in this reply:
https://github.com/scipy-conference/scipy_proceedings/pull/825#issuecomment-1636542496

The only thing I have not done is add information on training times as you suggest here: https://github.com/scipy-conference/scipy_proceedings/pull/825#discussion_r1237941419
You are totally right that this is important, and it is functionality that is built into vak, but there's just not a lot to learn from looking at the training times for the models we test here to demonstrate proof-of-concept functionality of the framework. If you feel it is absolutely vital I can try to squeeze those numbers in.

Thank you again for your review.

2023-07-20 16:13 UTC, tanya-akumu commented
Hi David,

I did get lost in the many commits 😄 Thanks for pointing me to the
specific commits. I will go through it and give feedback by end of
day tomorrow.

As for the training times, its not necessarily required for this paper
since demonstrates proof of concept. Its usually important if you claim
efficiency or compare different frameworks.

Kind regards,
Tanya

On Thu, 20 Jul 2023 at 18:23, David Nicholson ***@***.***>
wrote:

> Hi again @tanya-akumu <https://github.com/tanya-akumu> just following up
> on the pings from @mepa <https://github.com/mepa> and @deniederhut
> <https://github.com/deniederhut> -- I have made some final edits to fix
> up typos and tweak wording.
>
> In case it got lost in the additional commits, I believe I have addressed
> all your comments as outlined in this reply:
> #825 (comment)
> <https://github.com/scipy-conference/scipy_proceedings/pull/825#issuecomment-1636542496>
>
> The only thing I have not done is add information on training times as you
> suggest here: #825 (comment)
> <https://github.com/scipy-conference/scipy_proceedings/pull/825#discussion_r1237941419>
> You are totally right that this is important, and it is functionality that
> is built into vak, but there's just not a lot to learn from looking at the
> training times for the models we test here to demonstrate proof-of-concept
> functionality of the framework. If you feel it is absolutely vital I can
> try to squeeze those numbers in.
>
> Thank you again for your review.
>
> —
> Reply to this email directly, view it on GitHub
> <https://github.com/scipy-conference/scipy_proceedings/pull/825#issuecomment-1644127902>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/AM3F6CGFGTXLDH5MYRYSW4DXRFENXANCNFSM6AAAAAAYY6VWAE>
> .
> You are receiving this because you were mentioned.Message ID:
> ***@***.***>
>

2023-07-27 13:24 UTC, NickleDave commented
Hi @tanya-akumu I did fix some more minor typos and make tweaks to the figures for readability one last time, with input from my co-author @yardencsGitHub. It should be ready for your final review. Thank you again

2023-07-28 14:07 UTC, mepa commented
Hey @tanya-akumu! How is the paper looking after the authors' changes? Do you have further comments or do you feel this paper is ready for inclusion in the conference proceedings?

2023-07-28 14:14 UTC, tanya-akumu commented on papers/david_nicholson/main.tex
> +To address this need, we developed vak \cite{nicholsonVak2022} (\url{https://github.com/vocalpy/vak}), a neural network framework designed for researchers studying animal acoustic communication. vak
the explanation is clear.

2023-07-28 14:18 UTC, tanya-akumu approved these changes
The updates to the paper look fantastic. I do not have further comments. Great work @NickleDave and team!

2023-07-28 15:03 UTC, NickleDave commented
Thanks so much @tanya-akumu! Your review was very helpful

2023-07-28 15:19 UTC, mepa commented
@scoobies check references

2023-07-28 15:20 UTC, scoobies commented
```
Reference check summary (note 'MISSING' DOIs are suggestions that need verification):

OK DOIs

- 10.1101/2022.06.26.497684 is OK
- 10.1126/science.abc6588 is OK
- 10.1038/s41386-018-0303-6 is OK
- 10.5281/zenodo.7627197 is OK
- 10.1146/annurev.neuro.22.1.567 is OK
- 10.1007/s10071-015-0933-6 is OK
- 10.5281/zenodo.7859091 is OK
- 10.7554/eLife.67855 is OK
- 10.1126/science.298.5598.1569 is OK
- 10.1111/evo.14489 is OK
- 10.1109/MCSE.2007.55 is OK
- 10.1007/s10618-008-0122-1 is OK
- 10.5281/ZENODO.6249316 is OK
- 10.1111/brv.12160 is OK
- 10.1111/2041-210X.12433 is OK
- 10.1371/journal.pone.0159188 is OK
- 10.1007/s42991-021-00222-2 is OK
- 10.1145/1873951.1874254 is OK
- 10.1145/1873951.1874254 is OK
- 10.1371/journal.pcbi.1003052 is OK
- 10.1371/journal.pbio.3000672 is OK
- 10.7554/eLife.75691 is OK
- 10.6084/m9.figshare.4805749.v5 is OK
- 10.5281/zenodo.6808839 is OK
- 10.1101/2023.03.11.532197 is OK
- 10.3389/fnevo.2012.00012 is OK
- 10.1038/srep39419 is OK
- 10.1371/journal.pone.0278522 is OK
- 10.1101/2021.03.16.435625 is OK
- 10.1002/ece3.5418 is OK
- 10.3389/fnbeh.2021.811737 is OK
- 10.1371/journal.pcbi.1008228 is OK
- 10.1093/beheco/arz202 is OK
- 10.1523/JNEUROSCI.2448-08.2008 is OK
- 10.7554/eLife.68837 is OK
- 10.5281/zenodo.3509134 is OK
- 10.5281/zenodo.4030140 is OK
- 10.1007/978-3-030-86383-8_6 is OK
- 10.1098/rstb.2020.0236 is OK
- 10.1109/MCSE.2011.37 is OK
- 10.1016/j.neuron.2019.09.036 is OK
- 10.1101/2022.12.23.521425 is OK
- 10.5281/zenodo.7925888 is OK

MISSING DOIs

- 10.1016/j.neunet.2005.06.042 may be a valid DOI for title: Framewise Phoneme Classification with Bidirectional LSTM and Other Neural Network Architectures
- 10.1007/978-3-642-24797-2_2 may be a valid DOI for title: Supervised Sequence Labelling
- 10.25080/majora-629e541a-008 may be a valid DOI for title: Comparison of Machine Learning Methods Applied to Birdsong Element Classification
- 10.1038/nn.2336 may be a valid DOI for title: Adult Birdsong Is Actively Maintained by Error Correction
- 10.1073/pnas.1213622109 may be a valid DOI for title: Vocal Learning Is Constrained by the Statistics of Sensorimotor Experience
- 10.1371/journal.pone.0092584 may be a valid DOI for title: Semi-Automatic Classification of Birdsong Elements Using a Linear Support Vector Machine
- 10.1006/anbe.1999.1416 may be a valid DOI for title: A Procedure for an Automated Measurement of Song Similarity
- 10.1109/cvpr.2017.113 may be a valid DOI for title: Temporal convolutional networks for action segmentation and detection
- 10.1162/neco_a_01434 may be a valid DOI for title: Parametric UMAP embeddings for representation and semisupervised learning
- 10.21105/joss.05338 may be a valid DOI for title: Crowsetta: A Python tool to work with any format for annotating animal vocalizations and bioacoustics data.

INVALID DOIs

- None
```

2023-07-28 15:25 UTC, mepa commented
Hi @NickleDave, could you please verify the 'MISSING' DOIs listed in the scoobies comment above and add them if correct?

2023-07-29 18:17 UTC, mepa commented
@scoobies mark not ready

2023-07-30 17:01 UTC, NickleDave commented
@scoobies check references

2023-07-30 17:01 UTC, scoobies commented
```
Reference check summary (note 'MISSING' DOIs are suggestions that need verification):

OK DOIs

- 10.1101/2022.06.26.497684 is OK
- 10.1126/science.abc6588 is OK
- 10.1038/s41386-018-0303-6 is OK
- 10.5281/zenodo.7627197 is OK
- 10.1146/annurev.neuro.22.1.567 is OK
- 10.1007/s10071-015-0933-6 is OK
- 10.5281/zenodo.7859091 is OK
- 10.7554/eLife.67855 is OK
- 10.1016/j.neunet.2005.06.042 is OK
- 10.1007/978-3-642-24797-2_2 is OK
- 10.1126/science.298.5598.1569 is OK
- 10.1111/evo.14489 is OK
- 10.1109/MCSE.2007.55 is OK
- 10.1007/s10618-008-0122-1 is OK
- 10.5281/ZENODO.6249316 is OK
- 10.1111/brv.12160 is OK
- 10.1111/2041-210X.12433 is OK
- 10.1371/journal.pone.0159188 is OK
- 10.1007/s42991-021-00222-2 is OK
- 10.1145/1873951.1874254 is OK
- 10.1145/1873951.1874254 is OK
- 10.1371/journal.pcbi.1003052 is OK
- 10.1371/journal.pbio.3000672 is OK
- 10.7554/eLife.75691 is OK
- 10.6084/m9.figshare.4805749.v5 is OK
- 10.25080/Majora-629e541a-008 is OK
- 10.5281/zenodo.6808839 is OK
- 10.1101/2023.03.11.532197 is OK
- 10.3389/fnevo.2012.00012 is OK
- 10.1038/srep39419 is OK
- 10.1371/journal.pone.0278522 is OK
- 10.1101/2021.03.16.435625 is OK
- 10.1002/ece3.5418 is OK
- 10.3389/fnbeh.2021.811737 is OK
- 10.1371/journal.pcbi.1008228 is OK
- 10.1093/beheco/arz202 is OK
- 10.1038/nn.2336 is OK
- 10.1073/pnas.1213622109 is OK
- 10.1523/JNEUROSCI.2448-08.2008 is OK
- 10.7554/eLife.68837 is OK
- 10.1371/journal.pone.0092584 is OK
- 10.1006/anbe.1999.1416 is OK
- 10.5281/zenodo.3509134 is OK
- 10.5281/zenodo.4030140 is OK
- 10.1007/978-3-030-86383-8_6 is OK
- 10.1098/rstb.2020.0236 is OK
- 10.1109/MCSE.2011.37 is OK
- 10.1016/j.neuron.2019.09.036 is OK
- 10.1101/2022.12.23.521425 is OK
- 10.1109/cvpr.2017.113 is OK
- 10.1162/neco_a_01434 is OK
- 10.21105/joss.05338 is OK
- 10.5281/zenodo.7925888 is OK

MISSING DOIs

- None

INVALID DOIs

- None
```

2023-07-30 17:01 UTC, NickleDave commented
Ok @mepa I think I have fixed those DOIs, my apologies for being the hold up

2023-07-30 22:28 UTC, mepa commented
@scoobies build paper

2023-07-30 22:28 UTC, scoobies commented
building paper...

2023-07-30 22:28 UTC, scoobies commented
{"data"=>{"info"=>"Build for paper NickleDave-paper-david-nicholson scheduled.  Note that builds are only executed if the current build attempt is more than 5 minutes old."}, "status"=>"success"}

2023-07-30 22:46 UTC, mepa commented
> Ok @mepa I think I have fixed those DOIs, my apologies for being the hold up

Hi @NickleDave , no problem! Thanks for fixing those DOIs.

It looks like the pdf is longer able to build
- https://procbuild.scipy.org/download/NickleDave:paper-david-nicholson
- https://procbuild.scipy.org/status/NickleDave:paper-david-nicholson

I'll look into what may be the issue a little later, but it's something to do with [the most recent commit](https://github.com/scipy-conference/scipy_proceedings/pull/825/commits/e555a8f697913481ca593171c0c40a47962b4dbd).

2023-07-31 14:37 UTC, NickleDave commented
@scoobies build status

2023-07-31 14:37 UTC, scoobies commented
{"NickleDave-paper-david-nicholson"=>{"data"=>{"build_output"=>"[*] Updating proceedings build tools in {self.master_repo_path}...\nAlready up to date.\n[*] Check out paper repository...\nCloning into '/tmp/tmphbvtp0w3'...\nMoving proceedings build tools to temp directory...\n[*] Build the paper...\nBuilding: david_nicholson\n*** Warning: /tmp/tmphbvtp0w3/publisher/../output/david_nicholson/paper_stats.json does not exist.\nError compiling BiBTeX\nbibtex error output:\n================================================================================\nb'This is BibTeX, Version 0.99d (TeX Live 2019/Debian)\\nThe top-level auxiliary file: paper.aux\\nThe style file: ieeetr.bst\\nDatabase file #1: mybib.bib\\nWarning--I didn\\'t find a database entry for \"hauserFacultyLanguageWhat2002\"\\nWarning--I didn\\'t find a database entry for \"doupeBIRDSONGHUMANSPEECH1999\"\\nWarning--I didn\\'t find a database entry for \"wirthlinModularApproachVocal2019\"\\nWarning--I didn\\'t find a database entry for \"hopp2012animal\"\\nWarning--I didn\\'t find a database entry for \"sainburgComputationalNeuroethologyVocal2021\"\\nWarning--I didn\\'t find a database entry for \"stowellComputationalBioacousticsDeep2022\"\\nWarning--I didn\\'t find a database entry for \"cohen2022recent\"\\nWarning--I didn\\'t find a database entry for \"cohenAutomatedAnnotationBirdsong2022\"\\nWarning--I didn\\'t find a database entry for \"goffinetLowdimensionalLearnedFeature2021\"\\nWarning--I didn\\'t find a database entry for \"steinfathFastAccurateAnnotation2021\"\\nWarning--I didn\\'t find a database entry for \"sainburgFindingVisualizingQuantifying2020\"\\nWarning--I didn\\'t find a database entry for \"coffeyDeepSqueakDeepLearningbased2019\"\\nWarning--I didn\\'t find a database entry for \"nicholsonVak2022\"\\nWarning--I didn\\'t find a database entry for \"mcgregorSharedMechanismsAuditory2022\"\\nWarning--I didn\\'t find a database entry for \"provostImpactsFinetuningPhylogenetic2022\"\\nWarning--I didn\\'t find a database entry for \"kershenbaumAcousticSequencesNonhuman2016\"\\nWarning--I didn\\'t find a database entry for \"fukuzawaComputationalMethodsGeneralised2022\"\\nWarning--I didn\\'t find a database entry for \"steinfathFastAccurateAnnotation\"\\nWarning--I didn\\'t find a database entry for \"zandbergBirdSongComparison2022\"\\nWarning--I didn\\'t find a database entry for \"paszkeAutomaticDifferentiationPyTorch2017\"\\nWarning--I didn\\'t find a database entry for \"falconPyTorchLightning2023\"\\nWarning--I didn\\'t find a database entry for \"walt_numpy_2011\"\\nWarning--I didn\\'t find a database entry for \"harris2020array\"\\nWarning--I didn\\'t find a database entry for \"Hunter:2007\"\\nWarning--I didn\\'t find a database entry for \"thomas_a_caswell_2020_4030140\"\\nWarning--I didn\\'t find a database entry for \"team_pandas-devpandas_2020\"\\nWarning--I didn\\'t find a database entry for \"nicholson2023crowsetta\"\\nWarning--I didn\\'t find a database entry for \"torchvision2016\"\\nWarning--I didn\\'t find a database entry for \"lea2017temporal\"\\nWarning--I didn\\'t find a database entry for \"mcinnes2018umap\"\\nWarning--I didn\\'t find a database entry for \"sainburg2021parametric\"\\nWarning--empty publisher in dask_development_team_dask_2016\\nWarning--empty journal in nicholson_bengalese_2017\\n(There were 33 warnings)\\nThis is pdfTeX, Version 3.14159265-2.6-1.40.20 (TeX Live 2019/Debian) (preloaded format=pdflatex)\\n restricted \\\\write18 enabled.\\nentering extended mode\\n(./paper.tex\\nLaTeX2e <2020-02-02> patch level 2\\nL3 programming layer <2020-02-14> (./IEEEtran.cls\\nDocument Class: IEEEtran 2015/08/26 V1.8b by Michael Shell\\n-- See the \"IEEEtran_HOWTO\" manual for usage information.\\n-- http://www.michaelshell.org/tex/ieeetran/\\n(/usr/share/texlive/texmf-dist/tex/latex/psnfss/ot1ppl.fd)\\n-- Using IEEE Computer Society mode.\\n-- Using 8.5in x 11in (letter) paper.\\n-- Using PDF output.\\n-- This is a 10 point document.\\n) (/usr/share/texlive/texmf-dist/tex/latex/cmap/cmap.sty)\\n(/usr/share/texlive/texmf-dist/tex/latex/base/ifthen.sty)\\n(/usr/share/texlive/texmf-dist/tex/latex/base/fontenc.sty\\n(/usr/share/texlive/texmf-dist/tex/latex/psnfss/t1ppl.fd)<<t1.cmap>>)\\n(/usr/share/texlive/texmf-dist/tex/latex/base/inputenc.sty)\\n(/usr/share/texlive/texmf-dist/tex/latex/amsmath/amsmath.sty\\nFor additional information on amsmath, use the `?\\' option.\\n(/usr/share/texlive/texmf-dist/tex/latex/amsmath/amstext.sty\\n(/usr/share/texlive/texmf-dist/tex/latex/amsmath/amsgen.sty))\\n(/usr/share/texlive/texmf-dist/tex/latex/amsmath/amsbsy.sty)\\n(/usr/share/texlive/texmf-dist/tex/latex/amsmath/amsopn.sty))\\n(/usr/share/texlive/texmf-dist/tex/latex/caption/caption.sty\\n(/usr/share/texlive/texmf-dist/tex/latex/caption/caption3.sty\\n(/usr/share/texlive/texmf-dist/tex/latex/graphics/keyval.sty))\\n\\nPackage caption Warning: Unknown document class (or package),\\n(caption)                standard defaults will be used.\\nSee the caption package documentation for explanation.\\n\\n) (/usr/share/texlive/texmf-dist/tex/latex/float/float.sty) (./scipy.sty\\n(./status.sty (./draftwatermark.sty (./everypage.sty)\\n(/usr/share/texlive/texmf-dist/tex/latex/graphics/graphicx.sty\\n(/usr/share/texlive/texmf-dist/tex/latex/graphics/graphics.sty\\n(/usr/share/texlive/texmf-dist/tex/latex/graphics/trig.sty)\\n(/usr/share/texlive/texmf-dist/tex/latex/graphics-cfg/graphics.cfg)\\n(/usr/share/texlive/texmf-dist/tex/latex/graphics-def/pdftex.def)))\\n(/usr/share/texlive/texmf-dist/tex/latex/graphics/color.sty\\n(/usr/share/texlive/texmf-dist/tex/latex/graphics-cfg/color.cfg))))\\n(/usr/share/texlive/texmf-dist/tex/latex/psnfss/mathptmx.sty)\\n(/usr/share/texlive/texmf-dist/tex/latex/psnfss/helvet.sty)\\n(/usr/share/texlive/texmf-dist/tex/latex/psnfss/courier.sty)\\n(/usr/share/texlive/texmf-dist/tex/latex/amsfonts/amsfonts.sty)\\n(/usr/share/texlive/texmf-dist/tex/latex/amsfonts/amssymb.sty)\\n(/usr/share/texlive/texmf-dist/tex/latex/tools/bm.sty)\\n(/usr/share/texlive/texmf-dist/tex/latex/hyperref/hyperref.sty\\n(/usr/share/texlive/texmf-dist/tex/generic/ltxcmds/ltxcmds.sty)\\n(/usr/share/texlive/texmf-dist/tex/generic/iftex/iftex.sty)\\n(/usr/share/texlive/texmf-dist/tex/latex/pdftexcmds/pdftexcmds.sty\\n(/usr/share/texlive/texmf-dist/tex/generic/infwarerr/infwarerr.sty))\\n(/usr/share/texlive/texmf-dist/tex/generic/kvsetkeys/kvsetkeys.sty)\\n(/usr/share/texlive/texmf-dist/tex/generic/kvdefinekeys/kvdefinekeys.sty)\\n(/usr/share/texlive/texmf-dist/tex/generic/pdfescape/pdfescape.sty)\\n(/usr/share/texlive/texmf-dist/tex/latex/hycolor/hycolor.sty)\\n(/usr/share/texlive/texmf-dist/tex/latex/letltxmacro/letltxmacro.sty)\\n(/usr/share/texlive/texmf-dist/tex/latex/auxhook/auxhook.sty)\\n(/usr/share/texlive/texmf-dist/tex/latex/kvoptions/kvoptions.sty)\\n(/usr/share/texlive/texmf-dist/tex/latex/hyperref/pd1enc.def)\\n(/usr/share/texlive/texmf-dist/tex/generic/intcalc/intcalc.sty)\\n(/usr/share/texlive/texmf-dist/tex/generic/etexcmds/etexcmds.sty)\\n(/usr/share/texlive/texmf-dist/tex/latex/url/url.sty)\\n(/usr/share/texlive/texmf-dist/tex/generic/bitset/bitset.sty\\n(/usr/share/texlive/texmf-dist/tex/generic/bigintcalc/bigintcalc.sty))\\n(/usr/share/texlive/texmf-dist/tex/generic/atbegshi/atbegshi.sty))\\n(/usr/share/texlive/texmf-dist/tex/latex/hyperref/hpdftex.def\\n(/usr/share/texlive/texmf-dist/tex/latex/atveryend/atveryend.sty)\\n(/usr/share/texlive/texmf-dist/tex/latex/rerunfilecheck/rerunfilecheck.sty\\n(/usr/share/texlive/texmf-dist/tex/generic/uniquecounter/uniquecounter.sty)))\\n\\nPackage hyperref Warning: Option `pdftex\\' has already been used,\\n(hyperref)                setting the option has no effect on input line 43.\\n\\n(/usr/share/texlive/texmf-dist/tex/latex/tools/longtable.sty)\\n(/usr/share/texlive/texmf-dist/tex/latex/multirow/multirow.sty)\\n(/usr/share/texlive/texmf-dist/tex/latex/booktabs/booktabs.sty)\\n(/usr/share/texlive/texmf-dist/te [...]

2023-07-31 15:08 UTC, NickleDave commented
@mepa looks like Zotero changed all the citekeys when I re-exported the .bib with DOIs

I will just force push over that commit with a new one where I add the DOIs to the existing .bib file manually

2023-07-31 15:20 UTC, NickleDave commented
@scoobies check references

2023-07-31 15:20 UTC, scoobies commented
```
Reference check summary (note 'MISSING' DOIs are suggestions that need verification):

OK DOIs

- 10.1101/2022.06.26.497684 is OK
- 10.1126/science.abc6588 is OK
- 10.1038/s41386-018-0303-6 is OK
- 10.5281/zenodo.7627197 is OK
- 10.1146/annurev.neuro.22.1.567 is OK
- 10.1007/s10071-015-0933-6 is OK
- 10.5281/zenodo.7859091 is OK
- 10.7554/eLife.67855 is OK
- 10.1016/j.neunet.2005.06.042 is OK
- 10.1007/978-3-642-24797-2_2 is OK
- 10.1126/science.298.5598.1569 is OK
- 10.1111/evo.14489 is OK
- 10.1109/MCSE.2007.55 is OK
- 10.1007/s10618-008-0122-1 is OK
- 10.5281/ZENODO.6249316 is OK
- 10.1111/brv.12160 is OK
- 10.1111/2041-210X.12433 is OK
- 10.1371/journal.pone.0159188 is OK
- 10.1007/s42991-021-00222-2 is OK
- 10.1145/1873951.1874254 is OK
- 10.1145/1873951.1874254 is OK
- 10.1371/journal.pcbi.1003052 is OK
- 10.1371/journal.pbio.3000672 is OK
- 10.7554/eLife.75691 is OK
- 10.6084/m9.figshare.4805749.v5 is OK
- 10.25080/majora-629e541a-008 is OK
- 10.5281/zenodo.6808839 is OK
- 10.1101/2023.03.11.532197 is OK
- 10.3389/fnevo.2012.00012 is OK
- 10.1038/srep39419 is OK
- 10.1371/journal.pone.0278522 is OK
- 10.1101/2021.03.16.435625 is OK
- 10.1002/ece3.5418 is OK
- 10.3389/fnbeh.2021.811737 is OK
- 10.1371/journal.pcbi.1008228 is OK
- 10.1093/beheco/arz202 is OK
- 10.1038/nn.2336 is OK
- 10.1073/pnas.1213622109 is OK
- 10.1523/JNEUROSCI.2448-08.2008 is OK
- 10.7554/eLife.68837 is OK
- 10.1371/journal.pone.0092584 is OK
- 10.1006/anbe.1999.1416 is OK
- 10.5281/zenodo.3509134 is OK
- 10.5281/zenodo.4030140 is OK
- 10.1007/978-3-030-86383-8_6 is OK
- 10.1098/rstb.2020.0236 is OK
- 10.1109/MCSE.2011.37 is OK
- 10.1016/j.neuron.2019.09.036 is OK
- 10.1101/2022.12.23.521425 is OK
- 10.1109/cvpr.2017.113 is OK
- 10.1162/neco_a_01434 is OK
- 10.21105/joss.05338 is OK
- 10.5281/zenodo.7925888 is OK

MISSING DOIs

- None

INVALID DOIs

- None
```

2023-07-31 15:21 UTC, NickleDave commented
Ok @mepa I think we now have all the DOIs *and* an .rst + .bib that actually renders :sweat_smile:

2023-08-01 01:19 UTC, mepa commented
Great, thank you, @NickleDave !

2023-08-01 01:20 UTC, mepa commented
@scoobies mark ready

2023-08-05 22:54 UTC, deniederhut approved these changes
Thanks @tanya-akumu for your help getting this paper ready for publication! And thanks @NickleDave for joining us at SciPy this year!

![Thanks-gif-2873088886](https://github.com/scipy-conference/scipy_proceedings/assets/6868396/33f055a8-efae-4b76-953f-f3236b42509b)

2023-08-05 22:54 UTC, merged