Paper: Doing More with Less: How to Build an Affordable ML Infrastructure for Your Academic Research Lab
scipy-conference/scipy_proceedings pull request #826
Opened 2023-06-03 03:51 UTC by soham96

If you are creating this PR in order to submit a draft of your paper,
see http://procbuild.scipy.org/ for logs generated by the build
process.

See the [project readme](https://github.com/scipy-conference/scipy_proceedings#build-your-paper)
for more information.

*Editor*:  

*Reviewers*:

2023-06-03 15:04 UTC, deniederhut commented
@scoobies assign @deniederhut as editor

2023-06-03 15:04 UTC, scoobies commented
Assigned! @deniederhut is now the editor

2023-06-03 20:52 UTC, deniederhut commented
@scoobies build status

2023-06-03 20:52 UTC, scoobies commented
{"soham96-2023"=>{"data"=>{"build_output"=>"[*] Updating proceedings build tools in {self.master_repo_path}...\nAlready up to date.\n[*] Check out paper repository...\nCloning into '/tmp/tmp4tnf2znz'...\nMoving proceedings build tools to temp directory...\n[*] Build the paper...\nBuilding: vaidheeswaran_archana\n*** Warning: /tmp/tmp4tnf2znz/publisher/../output/vaidheeswaran_archana/paper_stats.json does not exist.\n*** Warning: /tmp/tmp4tnf2znz/publisher/_build/toc.json does not exist.\n*** Warning: /tmp/tmp4tnf2znz/publisher/_build/other.json does not exist.\nPDFLaTeX error output:\n================================================================================\nThis is pdfTeX, Version 3.14159265-2.6-1.40.20 (TeX Live 2019/Debian) (preloaded format=pdflatex)\n restricted \\write18 enabled.\nentering extended mode\n(./paper.tex\nLaTeX2e <2020-02-02> patch level 2\nL3 programming layer <2020-02-14> (./IEEEtran.cls\nDocument Class: IEEEtran 2015/08/26 V1.8b by Michael Shell\n-- See the \"IEEEtran_HOWTO\" manual for usage information.\n-- http://www.michaelshell.org/tex/ieeetran/\n(/usr/share/texlive/texmf-dist/tex/latex/psnfss/ot1ppl.fd)\n-- Using IEEE Computer Society mode.\n-- Using 8.5in x 11in (letter) paper.\n-- Using PDF output.\n-- This is a 10 point document.\n) (/usr/share/texlive/texmf-dist/tex/latex/cmap/cmap.sty)\n(/usr/share/texlive/texmf-dist/tex/latex/base/ifthen.sty)\n(/usr/share/texlive/texmf-dist/tex/latex/base/fontenc.sty\n(/usr/share/texlive/texmf-dist/tex/latex/psnfss/t1ppl.fd)<<t1.cmap>>)\n(/usr/share/texlive/texmf-dist/tex/latex/base/inputenc.sty)\n(/usr/share/texlive/texmf-dist/tex/latex/amsmath/amsmath.sty\nFor additional information on amsmath, use the `?' option.\n(/usr/share/texlive/texmf-dist/tex/latex/amsmath/amstext.sty\n(/usr/share/texlive/texmf-dist/tex/latex/amsmath/amsgen.sty))\n(/usr/share/texlive/texmf-dist/tex/latex/amsmath/amsbsy.sty)\n(/usr/share/texlive/texmf-dist/tex/latex/amsmath/amsopn.sty))\n(/usr/share/texlive/texmf-dist/tex/latex/booktabs/booktabs.sty)\n(/usr/share/texlive/texmf-dist/tex/latex/graphics/color.sty\n(/usr/share/texlive/texmf-dist/tex/latex/graphics-cfg/color.cfg)\n(/usr/share/texlive/texmf-dist/tex/latex/graphics-def/pdftex.def))\n(/usr/share/texlive/texmf-dist/tex/latex/caption/caption.sty\n(/usr/share/texlive/texmf-dist/tex/latex/caption/caption3.sty\n(/usr/share/texlive/texmf-dist/tex/latex/graphics/keyval.sty))\n\nPackage caption Warning: Unknown document class (or package),\n(caption)                standard defaults will be used.\nSee the caption package documentation for explanation.\n\n) (/usr/share/texlive/texmf-dist/tex/latex/float/float.sty)\n(/usr/share/texlive/texmf-dist/tex/latex/tools/longtable.sty)\n(/usr/share/texlive/texmf-dist/tex/latex/caption/ltcaption.sty)\n(/usr/share/texlive/texmf-dist/tex/latex/tools/array.sty) (./scipy.sty\n(./status.sty (./draftwatermark.sty (./everypage.sty)\n(/usr/share/texlive/texmf-dist/tex/latex/graphics/graphicx.sty\n(/usr/share/texlive/texmf-dist/tex/latex/graphics/graphics.sty\n(/usr/share/texlive/texmf-dist/tex/latex/graphics/trig.sty)\n(/usr/share/texlive/texmf-dist/tex/latex/graphics-cfg/graphics.cfg)))))\n(/usr/share/texlive/texmf-dist/tex/latex/psnfss/mathptmx.sty)\n(/usr/share/texlive/texmf-dist/tex/latex/psnfss/helvet.sty)\n(/usr/share/texlive/texmf-dist/tex/latex/psnfss/courier.sty)\n(/usr/share/texlive/texmf-dist/tex/latex/amsfonts/amsfonts.sty)\n(/usr/share/texlive/texmf-dist/tex/latex/amsfonts/amssymb.sty)\n(/usr/share/texlive/texmf-dist/tex/latex/tools/bm.sty)\n(/usr/share/texlive/texmf-dist/tex/latex/hyperref/hyperref.sty\n(/usr/share/texlive/texmf-dist/tex/generic/ltxcmds/ltxcmds.sty)\n(/usr/share/texlive/texmf-dist/tex/generic/iftex/iftex.sty)\n(/usr/share/texlive/texmf-dist/tex/latex/pdftexcmds/pdftexcmds.sty\n(/usr/share/texlive/texmf-dist/tex/generic/infwarerr/infwarerr.sty))\n(/usr/share/texlive/texmf-dist/tex/generic/kvsetkeys/kvsetkeys.sty)\n(/usr/share/texlive/texmf-dist/tex/generic/kvdefinekeys/kvdefinekeys.sty)\n(/usr/share/texlive/texmf-dist/tex/generic/pdfescape/pdfescape.sty)\n(/usr/share/texlive/texmf-dist/tex/latex/hycolor/hycolor.sty)\n(/usr/share/texlive/texmf-dist/tex/latex/letltxmacro/letltxmacro.sty)\n(/usr/share/texlive/texmf-dist/tex/latex/auxhook/auxhook.sty)\n(/usr/share/texlive/texmf-dist/tex/latex/kvoptions/kvoptions.sty)\n(/usr/share/texlive/texmf-dist/tex/latex/hyperref/pd1enc.def)\n(/usr/share/texlive/texmf-dist/tex/generic/intcalc/intcalc.sty)\n(/usr/share/texlive/texmf-dist/tex/generic/etexcmds/etexcmds.sty)\n(/usr/share/texlive/texmf-dist/tex/latex/url/url.sty)\n(/usr/share/texlive/texmf-dist/tex/generic/bitset/bitset.sty\n(/usr/share/texlive/texmf-dist/tex/generic/bigintcalc/bigintcalc.sty))\n(/usr/share/texlive/texmf-dist/tex/generic/atbegshi/atbegshi.sty))\n(/usr/share/texlive/texmf-dist/tex/latex/hyperref/hpdftex.def\n(/usr/share/texlive/texmf-dist/tex/latex/atveryend/atveryend.sty)\n(/usr/share/texlive/texmf-dist/tex/latex/rerunfilecheck/rerunfilecheck.sty\n(/usr/share/texlive/texmf-dist/tex/generic/uniquecounter/uniquecounter.sty)))\n\nPackage hyperref Warning: Option `pdftex' has already been used,\n(hyperref)                setting the option has no effect on input line 43.\n\n(/usr/share/texlive/texmf-dist/tex/latex/multirow/multirow.sty)\n(/usr/share/texlive/texmf-dist/tex/latex/base/textcomp.sty)\n(/usr/share/texlive/texmf-dist/tex/latex/upquote/upquote.sty)\n(/usr/share/texlive/texmf-dist/tex/latex/fancyvrb/fancyvrb.sty)\n(/usr/share/texlive/texmf-dist/tex/latex/algorithms/algorithm.sty))\n(/usr/share/texlive/texmf-dist/tex/latex/algorithmicx/algpseudocode.sty\n(/usr/share/texlive/texmf-dist/tex/latex/algorithmicx/algorithmicx.sty\nDocument Style algorithmicx 1.2 - a greatly improved `algorithmic' style\n)\nDocument Style - pseudocode environments for use with the `algorithmicx' style\n) (/usr/share/texlive/texmf-dist/tex/latex/l3backend/l3backend-pdfmode.def)\n(./paper.aux) (/usr/share/texlive/texmf-dist/tex/latex/psnfss/t1ptm.fd)\n-- Lines per column: 61 (exact).\n(/usr/share/texlive/texmf-dist/tex/context/base/mkii/supp-pdf.mkii\n[Loading MPS to PDF converter (version 2006.09.02).]\n) (/usr/share/texlive/texmf-dist/tex/latex/epstopdf-pkg/epstopdf-base.sty\n(/usr/share/texlive/texmf-dist/tex/latex/latexconfig/epstopdf-sys.cfg))\n(/usr/share/texlive/texmf-dist/tex/latex/hyperref/nameref.sty\n(/usr/share/texlive/texmf-dist/tex/latex/refcount/refcount.sty)\n(/usr/share/texlive/texmf-dist/tex/generic/gettitlestring/gettitlestring.sty))\n(./paper.out) (./paper.out) (./page_numbers.tex)\n(/usr/share/texlive/texmf-dist/tex/latex/psnfss/t1phv.fd)\n(/usr/share/texlive/texmf-dist/tex/latex/psnfss/ot1ztmcm.fd)<<ot1.cmap>>\n(/usr/share/texlive/texmf-dist/tex/latex/psnfss/omlztmcm.fd)<<oml.cmap>>\n(/usr/share/texlive/texmf-dist/tex/latex/psnfss/omsztmcm.fd)<<oms.cmap>>\n(/usr/share/texlive/texmf-dist/tex/latex/psnfss/omxztmcm.fd)<<omx.cmap>>\n(/usr/share/texlive/texmf-dist/tex/latex/psnfss/ot1ptm.fd)\n(/usr/share/texlive/texmf-dist/tex/latex/psnfss/upzd.fd)\n(/usr/share/texlive/texmf-dist/tex/latex/psnfss/ts1ptm.fd)\n\nPackage hyperref Warning: Difference (2) between bookmark levels is greater \n(hyperref)                than one, level fixed on input line 214.\n\n[1{/var/lib/texmf/fonts/map/pdftex/updmap/pdftex.map}]\nUnderfull \\hbox (badness 2134) in paragraph at lines 244--244\n []\\T1/phv/b/sc/11.04124 Proposed MLOps Ar-chi-tec-ture for Re-search\n[2] [3]\nUnderfull \\hbox (badness 2269) in paragraph at lines 326--326\n []\\T1/phv/b/n/9.53561 Case Study 1: Col-lab-o-ra-tive Re-search with Mul-ti-pl\ne Re-\n[4] (./paper.bbl\n\n! LaTeX Error: Something's wrong--perhaps a missing \\item.\n\nSee the LaTeX manual or LaTeX Companion for explanation.\nType  H <return>  for immediate help.\n ...                                              \n                                                  \nl.3 \\end{thebibliography}\n                         \n!  ==> Fatal error occurred, no output PDF file  [...]

2023-06-03 20:53 UTC, deniederhut commented
@soham96 looks like this is failing from an empty bibliography section

> `(./paper.bbl\n\n! LaTeX Error: Something's wrong--perhaps a missing \\item`

Was it your intention to not cite any prior work or tools?

2023-06-03 20:54 UTC, deniederhut commented
@scoobies mark server fail

2023-06-05 18:29 UTC, deniederhut commented
Hey @soham96 do you have any comments on the references section? We don't usually accept incomplete papers.

2023-06-06 12:49 UTC, soham96 commented
@deniederhut Apologies for my late reply and for the build/references error. I think I submitted the wrong latex version. I will fix it and send a PR in an hour.

2023-06-06 13:51 UTC, soham96 commented
@deniederhut I think I fixed the error. I am unable to build the project locally due to some issues with pdflatex in my environment so I am not sure if it has been fixed.

2023-06-06 22:05 UTC, deniederhut commented
@scoobies mark server success

2023-06-06 22:06 UTC, deniederhut commented
@scoobies check references

2023-06-06 22:06 UTC, scoobies commented
```
Reference check summary (note 'MISSING' DOIs are suggestions that need verification):

OK DOIs

- None

MISSING DOIs

- 10.1109/access.2023.3262138 may be a valid DOI for title: Machine learning operations (mlops): Overview, definition, and architecture

INVALID DOIs

- None
```

2023-06-06 22:06 UTC, deniederhut commented
@scoobies add @mmiji to reviewers

2023-06-06 22:06 UTC, scoobies commented
@mmiji added to the reviewers list!

2023-06-06 22:06 UTC, deniederhut commented
@scoobies code of conduct

2023-06-06 22:06 UTC, scoobies commented
Our CoC: https://www.scipy2023.scipy.org/code-of-conduct

2023-06-06 22:06 UTC, scoobies commented
Reports of abusive or harassing behavior may be reported to scipy@enthought.com

2023-06-08 13:04 UTC, deniederhut commented
@scoobies add @aditya14896 to reviewers

2023-06-08 13:04 UTC, scoobies commented
@aditya14896 added to the reviewers list!

2023-06-18 18:54 UTC, deniederhut commented
Hey @mmiji and @aditya14896! Friendly reminder that your initial review is due June 23

2023-06-20 18:12 UTC, mmiji commented
Hi @soham96 and @deniederhut ,

Please find my review below and let me know if you have any questions. 

### Summary 
This paper proposes an MLOps architecture for academics. It overviews several tools for MLOps and presents case studies to illustrate how the proposed architecture can be adapted to different scenarios.

### Overall Review
**Reject unless major revisions are made. The paper is a decent reference for some academics. However, there is a limited amount of technical content, novelty and impact, and verifiability. To accept this paper, there are a number of issues that should be addressed, as detailed below.** 

### Detailed Review (based on the SciPy's [suggested review criteria](https://github.com/scipy-conference/scipy_proceedings/blob/master/review_criteria.md)): 
- Written Quality: good
- Technical Content: limited. There is a lack of technical/computational content. It is unclear how the paper describes the development or use of python software, specifically, for approaching a problem in a domain within the scope of the conference. Suggestion: the SciPy community might benefit more from a detailed, quantitative comparison analysis to help guide academics in choosing specific tools over competitors. 
- Novelty and Impact: limited. It is unclear how the paper employs new or innovative methods or approaches to a problem. Similar suggestion as above, the impact is more limited because the paper assumes specific limitations and desires of academic labs, when in actuality many labs have greatly differing needs. Rather than suggesting just one or two tools per step in the MLOps pipeline, it would be more beneficial to overview the pros and cons of several of the most popular tools per step in the MLOps pipeline to help guide academics in choosing the right tools for their own labs. 
- Verifiability: limited. The case studies in this paper are described and discussed in a theoretical/anecdotal manner. Suggestion: It might help to incorporate/link to a tutorial detailing the case studies for the SciPy community to reference. 
- Other Requirements: needs work. Software does not appear to be formally cited properly in the pdf, might be a latex issue. Minor suggestion: some acronyms are not spelled out upon first mention, e.g. DVC. It would help to clarify because this acronym is not universal (e.g. searching “DVC” brings up Disney Vacation Club, Diablo Valley College, etc. before Data Version Control, which I am assuming is the intended meaning)
- Length: needs shortening if submitting to SciPy. The pdf is 11 pages, which is over the 8-page limit. Since a number of the suggestions involve adding content; it might help to cut out/drastically reduce some content and incorporate some figures/tables to save space. 
- Figures: N/A, no figures 
- Code Snippets: N/A, no code snippets

2023-06-20 20:08 UTC, aditya14896 commented
Hey Dillon,

Thanks for the reminder. The review is in progress! will update once ready.


On Sun, Jun 18, 2023 at 2:54 PM Dillon Niederhut ***@***.***>
wrote:

> Hey @mmiji <https://github.com/mmiji> and @aditya14896
> <https://github.com/aditya14896>! Friendly reminder that your initial
> review is due June 23
>
> —
> Reply to this email directly, view it on GitHub
> <https://github.com/scipy-conference/scipy_proceedings/pull/826#issuecomment-1596236562>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/AHDLITY5TJ263BDR5XYSJETXL5FFRANCNFSM6AAAAAAYZA4YBU>
> .
> You are receiving this because you were mentioned.Message ID:
> ***@***.***>
>

2023-06-24 02:40 UTC, aditya14896 requested changes

2023-06-24 02:40 UTC, aditya14896 commented on papers/vaidheeswaran_archana/metadata.yaml
> +title: MLOps for Research Labs -- latex edition
Please remove mention of "Latex Edition"

2023-06-24 02:40 UTC, aditya14896 commented on papers/vaidheeswaran_archana/metadata.yaml
> +   - In this paper, we propose an MLOps architecture for research labs. We then discuss a few scenarios where this architecture can be used.
The abstract can be made a bit more clear about what all this paper does

2023-06-24 02:40 UTC, aditya14896 commented on papers/vaidheeswaran_archana/main.tex
> +
The introduction to me seems too verbose around the same thoughts. It can be made crisp by ensuring a message is conveyed only once. 

Secondly, it would be nice to have references for processes that are standard in the Industry. 

Eg: When mentioning about "research lab's fundamental requirements and constraints" it would be good to reference it or explain it in paper so that a person who does not have exposure to research lab setting would be able to understand what is being referred to here.

2023-06-24 02:40 UTC, aditya14896 commented on papers/vaidheeswaran_archana/main.tex
> +The overarching goal of this paper is to demonstrate that with the right architecture and selection of tools, MLOps can be implemented affordably and effectively in a research setting, leading to imp
this line is not aligning with the abstract. The abstract says this paper proposes an architecture and not an inclination towards an ideology. update abstract maybe?

2023-06-24 02:40 UTC, aditya14896 commented on papers/vaidheeswaran_archana/main.tex
> +Machine Learning Operations (MLOps) plays a crucial role in enhancing the efficiency, reproducibility, and scalability of machine learning model deployment in industry settings. Yet, its adoption in
DRY(DO NOT REPEAT YOURSELF)

the line: "Yet, its adoption in research labs rem ..... collaboration." 


ALso, use of too many abstract terms like "few", "unique", "such envs"

2023-06-24 02:40 UTC, aditya14896 commented on papers/vaidheeswaran_archana/main.tex
> +In research labs, the primary focus is on improving model performance and innovation rather than deployment. Limited compute resources, which are often a constraint in research labs, necessitate an M
"In research labs, the primary focus is on improving model performance and innovation rather than deployment."

There needs to be strong reference or evidence to put that in a conference paper.

2023-06-24 02:40 UTC, aditya14896 commented on papers/vaidheeswaran_archana/main.tex
> +In the context of a research lab, the focus of MLOps shifts from deployment to efficient model management and versioning. This shift enables researchers to easily track, compare, and analyze their mo
Consider a situation where the research is oriented on efficient incremental training of ML model or deployment under low resource setups, such research labs would have a lot of focus on deployment. 

I do get your idea though, so I feel this can be better phrased to convey the message.

2023-06-24 02:40 UTC, aditya14896 commented on papers/vaidheeswaran_archana/main.tex
> +\subsubsection{Why MLOps is Essential for Research Labs \label{why-mlops}}
@deniederhut 
Nit: Are we not using numbering/serial numbers for each section and subsections?

2023-06-24 02:40 UTC, aditya14896 commented on papers/vaidheeswaran_archana/main.tex
> +
Overall: 
The above section has a lot of beneficial claims which must be backed by individual sections for either results or benchmarks or observations or through referencing a research paper. It would also be good to think about trade-offs if any.

2023-06-24 02:40 UTC, aditya14896 commented on papers/vaidheeswaran_archana/main.tex
> +Lastly, data security and ownership are paramount in research settings, where data might be private, confidential, or sensitive. MLOps systems must ensure robust data security, control access, and sa
You might want to consider following naming conventions like research paper standards and name this section to motivation or something similar

2023-06-24 02:40 UTC, aditya14896 commented on papers/vaidheeswaran_archana/main.tex
> +Given research labs' unique requirements and constraints, we propose an MLOps architecture tailored specifically for such settings. This architecture is built around the typical research project work
DRY: 
"Given research labs' unique requirements and constraints, we propose an MLOps architecture tailored specifically for such settings. This architecture is built around the typical research project workflow,"

2023-06-24 02:40 UTC, aditya14896 commented on papers/vaidheeswaran_archana/main.tex
> +
I think instead of going very wide on trying to cover a variety of problems it would be better to target a few major problems here and express MLOps solutioning components to it.

2023-06-24 02:40 UTC, aditya14896 commented on papers/vaidheeswaran_archana/main.tex
> +    \item Data Gathering and Analysis: The first step in the research project workflow involves acquiring and studying the data. The raw data undergoes a process of cleaning and preprocessing for sub
I think a major part of the process is Labelling and annotating data. 
There could also be cases where inter-annotation agreement is required and it seems to me it misses stages between data gathering and model creation

2023-06-24 02:40 UTC, aditya14896 commented on papers/vaidheeswaran_archana/main.tex
> +    \item Iteration: Iterative cycles form an integral part of the research process. Every step in these cycles - from data preparation, model training, and parameter tuning, to results analysis - sh
The whole ML Model process itself is iterative, Not sure if this needs to be a stage necessarily

2023-06-24 02:40 UTC, aditya14896 commented on papers/vaidheeswaran_archana/main.tex
> +    \item Model Deployment: Although not always necessary in a research setting, there might be instances where researchers want to deploy their model as a demonstration. This process should involve
I think there needs to be a stage to evaluate, Model drift analysis, a stage to test model against perturbations in data or tests on factors like multilingual data, performance testing, A/B testing etc..

2023-06-24 02:40 UTC, aditya14896 commented on papers/vaidheeswaran_archana/main.tex
> +    \item High-Performance Computing (HPC): Located centrally, the HPC is where researchers submit their training jobs. The HPC should be capable of fetching data from the data store.
HPC should be explained more

2023-06-24 02:40 UTC, aditya14896 commented on papers/vaidheeswaran_archana/main.tex
> +
This sections mentions a lot of tools: both open source and proprietary and must be cited/ added to the reference their links

2023-06-24 02:40 UTC, aditya14896 commented on papers/vaidheeswaran_archana/main.tex
> +LabelStudio provides diverse functionalities that support various labelling tasks, making it adaptable to various data types. Its flexibility, coupled with its extensibility due to the open-source na
I think when expressing an opinion its imperative to mention it as an opinion explicitly or otherwise it needs to be backed by real observations and results and comparison by tests.

2023-06-24 02:40 UTC, aditya14896 commented on papers/vaidheeswaran_archana/main.tex
> +MLFlow offers comprehensive tools for managing the end-to-end machine learning lifecycle. Its experiment tracking feature allows efficient logging and comparison of different runs, aiding reproducibi
since this is a paper, the sentences claiming results need to be certain about a product or service as this is a permanent document. If not, it must be mentioned as "not tested for X feature." 
Use of terms like "might" adds uncertainty for the reader and questions to the author

2023-06-24 02:40 UTC, aditya14896 commented on papers/vaidheeswaran_archana/main.tex
> +While DVC primarily excels in data versioning, it also offers model versioning and experiment tracking functionalities. It provides a lightweight solution for smaller projects or for teams primarily
When talking about different scale : small, broader scope of tracking etc..

It is important to give a reference of what is small scale, what is medium scale what is broader scale. etc..

2023-06-24 02:40 UTC, aditya14896 commented on papers/vaidheeswaran_archana/main.tex
> +Perfect is used for orchestrating tasks running on the HPC.
Typo:
I beleive the tool name is Prefect

2023-06-24 02:40 UTC, aditya14896 commented on papers/vaidheeswaran_archana/main.tex
> +\section{Implementation \label{implementation}}
it would be great to have an architecture image

2023-06-24 02:40 UTC, aditya14896 commented on papers/vaidheeswaran_archana/main.tex
> +
I strongly believe there should be a literature survey or related work section

2023-06-24 02:40 UTC, aditya14896 commented on papers/vaidheeswaran_archana/main.tex
> +For experiment tracking and model versioning, MLFlow and DVC can be used. While DVC excels in versioning data and models, MLFlow allows efficient logging and comparison of different runs. The setup o
DRY

2023-06-24 02:40 UTC, aditya14896 commented on papers/vaidheeswaran_archana/main.tex
> +For experiment tracking and model versioning, MLFlow and DVC can be used. While DVC excels in versioning data and models, MLFlow allows efficient logging and comparison of different runs. The setup o
Rather than mentioning terms like "clear" naming conventions. 
it would be better to mention an example or guideline for it.

2023-06-24 02:40 UTC, aditya14896 commented on papers/vaidheeswaran_archana/main.tex
> +
I highly recommend adding an Architecture which has process overview expressing which tool fits in which stage.

2023-06-24 02:40 UTC, aditya14896 commented on papers/vaidheeswaran_archana/main.tex
> +\subsection{Case Study 1: Collaborative Research with Multiple Researchers \label{case1}}
A Case Study is usually a real-life example and should not be a situation that is thought of to happen

2023-06-24 02:40 UTC, aditya14896 commented on papers/vaidheeswaran_archana/main.tex
> +\subsection{Case Study 1: Collaborative Research with Multiple Researchers \label{case1}}
Change the heading to Potential Use cases and their solutions maybe? no?

2023-06-24 02:40 UTC, aditya14896 commented on papers/vaidheeswaran_archana/main.tex
> +
This is also not a real-life example or mention of a real life research lab example and hence cant be a case study

2023-06-24 02:40 UTC, aditya14896 commented on papers/vaidheeswaran_archana/main.tex
> +    \item Continuous Deployment: Upon successfully completing a training job, another GitHub Action can be triggered to deploy the updated model to the deployment platform. Depending on the use case,
when giving an example, feel free to use one solution and not multiple for crispness, clarity and conciseness

2023-06-24 02:40 UTC, aditya14896 commented on papers/vaidheeswaran_archana/main.tex
> +With its active learning approach, data labelling tools like Prodigy provide an efficient and budget-friendly alternative. For Data Versioning, Pachyderm is an excellent option that provides a versio
pelase add references or links to these tools as well

2023-06-24 02:40 UTC, aditya14896 commented on papers/vaidheeswaran_archana/main.tex
> +The architecture we proposed addresses key aspects of MLOps, such as data labelling, data and model versioning, feature stores, experiment tracking, code repositories, CI/CD pipelines, and orchestrat
I think the conclusion needs to be rethought of as I did not feel the second paragraph of conclusion is true to what was actually covered as part of architecture.

2023-06-24 02:40 UTC, aditya14896 commented on papers/vaidheeswaran_archana/main.tex
> +We believe that this architecture is well-suited to aid research labs in managing their machine-learning projects effectively. However, with the evolving nature of machine learning research and the b
DRY:
This para has message that has been repeating throughout the paper and repeating in next para.

2023-06-24 02:53 UTC, aditya14896 commented
Overall, I agree with @mmiji 's review and have similar thoughts (based on the SciPy's [suggested review criteria](https://github.com/scipy-conference/scipy_proceedings/blob/master/review_criteria.md)):

Recommendation: 
Overall it is a Reject unless a major revision is published covering a practical solution and examples. Must address all the line comments provided. (Author to review each line comment for future revisions)

## Written Quality

Good. 

## Technical Content

- I think the content lacks technical background and technical real-life solutions to it. The paper is more theoretical. 
Lacks results and computational content. Does not express how a real package like Python or any other library was used and its results. For ex: by using X tool Y number of hours can be saved for Z job. 

## Novelty and Impact

The work is more about imparting knowledge and enlightening and advocating the stages and tools that can help achieve MLOPS. Does not introduce a new technique. 
The work is definitely relevant to scientific computing.  

## Verifiability

- Software descriptions are not accompanied by references or examples of representative source code. No source code involved or no architectural diagram.
- Analysis is not accompanied by a workflow description sufficient to reproduce the results.

### Length

Meets the content length limit and can be extended. 

### Figures

No figures and images.

### Code Snippets
- No code snippet leveraged.

2023-06-25 23:07 UTC, deniederhut commented
@scoobies mark pending comment

2023-06-26 16:22 UTC, soham96 commented
Hello. Thank you reviewers for your comments. I will make the changes you
requested and submit the paper again.

On Mon, Jun 26, 2023, 7:07 AM Dillon Niederhut ***@***.***>
wrote:

> @scoobies <https://github.com/scoobies> mark pending comment
>
> —
> Reply to this email directly, view it on GitHub
> <https://github.com/scipy-conference/scipy_proceedings/pull/826#issuecomment-1606310963>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/AEPDPH3D6BY5U2HJT6MRPJ3XNDAEFANCNFSM6AAAAAAYZA4YBU>
> .
> You are receiving this because you were mentioned.Message ID:
> ***@***.***>
>

2023-07-02 23:44 UTC, deniederhut requested changes
I'm surprised to see how little of the prior work around mlops shows up here. Chip Huyen has a whole book about it from Oreilly! https://huyenchip.com/mlops/

There is also:
- https://conference.scipy.org/proceedings/scipy2017/klaus_greff.html
- https://mlflow.org/
- https://www.prefect.io/
- https://www.ray.io/
- https://conference.scipy.org/proceedings/scipy2022/nathan_martindale.html

Some of these were debuted at SciPy!

2023-07-09 22:04 UTC, deniederhut commented
Hi @soham96 ! How are the revisions coming along?

2023-07-12 21:11 UTC, deniederhut commented
Hey @soham96 ! We're getting pretty close to the revision deadline. Do you have any updates to share?

2023-07-13 15:38 UTC, soham96 commented
hi @deniederhut, upon careful consideration, we have come to the realization that we lack the necessary time and resources to make the required revisions to this paper in order to meet the academic standards expected of any publication. We would like to thank the reviewers for the reviews and the time they have put in, and would like to respectfully withdraw our submission.

2023-07-16 10:33 UTC, deniederhut commented
Okay thanks for letting us know

2023-07-16 10:33 UTC, deniederhut commented
@scoobies mark not ready

2023-08-05 22:50 UTC, deniederhut commented
Thanks @mmiji and @aditya14896 for helping us review papers for the conference this year. Unfortunately this author has chosen to withdraw their submission, but I hope you still had a positive experience!

2023-08-05 22:50 UTC, closed without merging