Paper: Spatial Microsimulation and Activity Allocation in Python: An Update on the Likeness Toolkit
scipy-conference/scipy_proceedings pull request #834
Opened 2023-06-06 15:13 UTC by jGaboardi

If you are creating this PR in order to submit a draft of your paper,
see http://procbuild.scipy.org/ for logs generated by the build
process.

See the [project readme](https://github.com/scipy-conference/scipy_proceedings#build-your-paper)
for more information.

*Editor*:  

*Reviewers*:  

cc @jvtcl

2023-06-06 15:23 UTC, jGaboardi commented
@scoobies build status

2023-06-06 15:23 UTC, scoobies commented
{"jGaboardi-2023_tuccardi_paper"=>{"data"=>{"build_output"=>"[*] Updating proceedings build tools in {self.master_repo_path}...\nAlready up to date.\n[*] Check out paper repository...\nCloning into '/tmp/tmpdtwrueod'...\nMoving proceedings build tools to temp directory...\n[*] Build the paper...\nBuilding: james_gaboardi\n*** Warning: /tmp/tmpdtwrueod/publisher/../output/james_gaboardi/paper_stats.json does not exist.\n*** Warning: /tmp/tmpdtwrueod/publisher/_build/toc.json does not exist.\n*** Warning: /tmp/tmpdtwrueod/publisher/_build/other.json does not exist.\n", "build_pdf_path"=>"/procbuild/procbuild/../cache/jGaboardi-2023_tuccardi_paper.pdf", "build_status"=>"success", "build_timestamp"=>"06/06 15:16"}, "status"=>"success"}}

2023-06-06 15:24 UTC, jGaboardi commented
@scoobies check references

2023-06-06 15:24 UTC, scoobies commented
```
Reference check summary (note 'MISSING' DOIs are suggestions that need verification):

OK DOIs

- 10.1016/j.compenvurbsys.2017.05.004 is OK
- 10.5281/zenodo.7843975 is OK
- 10.5281/zenodo.7768810 is OK
- 10.1007/s12532-017-0130-5 is OK
- 10.1147/rd.471.0057 is OK
- 10.1016/j.compenvurbsys.2013.03.004 is OK
- 10.1111/gec3.12204 is OK
- 10.25080/majora-212e5952-014 is OK
- 10.25080/majora-212e5952-02d is OK
- 10.6084/m9.figshare.c.6139131.v2 is OK

MISSING DOIs

- 10.1016/j.epidem.2022.100632 may be a valid DOI for title: Assessing K-12 school reopenings under different COVID-19 Spread scenarios–United States, school year 2020/21: A retrospective modeling study
- 10.1109/wsc.2018.8632409 may be a valid DOI for title: Chisim: An agent-based simulation model of social interactions in a large urban area
- 10.1109/jstars.2018.2835377 may be a valid DOI for title: Building extraction at scale using convolutional neural network: Mapping of the United States

INVALID DOIs

- https://doi.org/10.1111/gean.12276 is INVALID because of 'https://doi.org/' prefix
- https://doi.org/10.1016/j.apgeog.2022.102844 is INVALID because of 'https://doi.org/' prefix
- 10.2172/1868508 is INVALID
```

2023-06-06 16:05 UTC, jGaboardi commented
@scoobies build status

2023-06-06 16:05 UTC, scoobies commented
{"jGaboardi-2023_tuccardi_paper"=>{"data"=>{"build_output"=>"[*] Updating proceedings build tools in {self.master_repo_path}...\nAlready up to date.\n[*] Check out paper repository...\nCloning into '/tmp/tmp7sexlv4i'...\nMoving proceedings build tools to temp directory...\n[*] Build the paper...\nBuilding: james_gaboardi\n*** Warning: /tmp/tmp7sexlv4i/publisher/../output/james_gaboardi/paper_stats.json does not exist.\n*** Warning: /tmp/tmp7sexlv4i/publisher/_build/toc.json does not exist.\n*** Warning: /tmp/tmp7sexlv4i/publisher/_build/other.json does not exist.\n", "build_pdf_path"=>"/procbuild/procbuild/../cache/jGaboardi-2023_tuccardi_paper.pdf", "build_status"=>"success", "build_timestamp"=>"06/06 16:04"}, "status"=>"success"}}

2023-06-06 16:05 UTC, jGaboardi commented
@scoobies check references

2023-06-06 16:05 UTC, scoobies commented
```
Reference check summary (note 'MISSING' DOIs are suggestions that need verification):

OK DOIs

- 10.1016/j.compenvurbsys.2017.05.004 is OK
- 10.5281/zenodo.7843975 is OK
- 10.5281/zenodo.7768810 is OK
- 10.1016/j.epidem.2022.100632 is OK
- 10.1007/s12532-017-0130-5 is OK
- 10.1147/rd.471.0057 is OK
- 10.1016/j.compenvurbsys.2013.03.004 is OK
- 10.1109/WSC.2018.8632409 is OK
- 10.1111/gec3.12204 is OK
- 10.1111/gean.12276 is OK
- 10.25080/majora-212e5952-014 is OK
- 10.25080/majora-212e5952-02d is OK
- 10.1016/j.apgeog.2022.102844 is OK
- 10.1109/JSTARS.2018.2835377 is OK
- 10.6084/m9.figshare.c.6139131.v2 is OK

MISSING DOIs

- None

INVALID DOIs

- 10.2172/1868508 is INVALID
```

2023-06-06 16:09 UTC, jGaboardi commented
> INVALID DOIs
> - 10.2172/1868508 is INVALID

`10.2172/1868508` is the correct DOI for *Foundational Science for Biopreparedness and Response*. See the bottom of page 2 [here](
https://science.osti.gov/-/media/Initiatives/pdf/Bioprepardeness_Roundtable_Report_092722.pdf).

2023-06-06 22:13 UTC, deniederhut commented
Haha I believe you

2023-06-06 22:13 UTC, deniederhut commented
@scoobies assign @mepa as editor

2023-06-06 22:13 UTC, scoobies commented
Assigned! @mepa is now the editor

2023-06-09 11:46 UTC, deniederhut commented
@scoobies add @ameyxd to reviewers

2023-06-09 11:46 UTC, scoobies commented
@ameyxd added to the reviewers list!

2023-06-09 11:48 UTC, deniederhut commented
@scoobies code of conduct

2023-06-09 11:48 UTC, scoobies commented
Our CoC: https://www.scipy2023.scipy.org/code-of-conduct

2023-06-09 11:48 UTC, scoobies commented
Reports of abusive or harassing behavior may be reported to scipy@enthought.com

2023-06-09 13:04 UTC, deniederhut commented
@scoobies add @kalyan678 to reviewers

2023-06-09 13:04 UTC, scoobies commented
@kalyan678 added to the reviewers list!

2023-06-18 22:28 UTC, mepa commented
Hey @ameyxd and @kalyan678! A friendly reminder that initial reviews are due Friday, June 23rd.

2023-06-19 07:37 UTC, kalyan678 commented
> Hey @ameyxd and @kalyan678! A friendly reminder that initial reviews are due Friday, June 23rd.

Hey @mepa - I appreciate the reminder. On it, I already am. Cheers!

2023-06-19 23:43 UTC, ameyxd commented
@mepa thanks for reminding. @jGaboardi happy to review 😄

2023-06-20 20:13 UTC, kalyan678 commented
Hello Everyone - I apologies for introducing myself so late. I'm sorry about that. Kalyan, a self-taught data scientist, analytics manager, and open-source enthusiast, has graced prestigious stages worldwide with his talks. He's also a valued mentor and reviewer for renowned conferences and hackathons, and actively contributes to the growth of open source communities.


Dear @mepa  @deniederhut - Thank you for giving me the opportunity to review your scientific paper. @jGaboardi - It was a pleasure to read and evaluate your work. I have thoroughly reviewed the paper and have added my comments accordingly.

I appreciate the efforts you have put into enhancing the Likeness toolkit and demonstrating its capabilities through the mobility validation exercise. Your research raises interesting questions and presents potential avenues for further development.

I have provided detailed comments and suggestions throughout the paper. Please refer to them and let me know if you have any questions. I hope you find my feedback helpful in advancing your research.

Once again, thank you for sharing your work with me. I look forward to any further discussions or iterations on the paper.

This brings my initial review to the end. Once again, many thanks!

Cheers
Kalyan

2023-06-20 21:03 UTC, jGaboardi commented
@kalyan678 Thank you completing your review! Perhaps you forgot to post your actual review comments?

2023-06-21 00:01 UTC, ameyxd requested changes
Overall, solid work with quality content. Hope to see revisions and review the next draft soon.

2023-06-21 00:01 UTC, ameyxd commented on papers/james_gaboardi/paper.tex
> +Agent-based models linking individual behavior to population dynamics are essential for understanding human security and social equity issues within human systems \cite{germann2022assessing, ozik2021
A clear definition or equivalent term for 'agent' would be appreciated in your introduction/overview. Perhaps mentioning 'agents' are 'simulated individuals' - could be obvious for the authors but not the reader.

2023-06-21 00:01 UTC, ameyxd commented on papers/james_gaboardi/paper.tex
> +Agent-based models linking individual behavior to population dynamics are essential for understanding human security and social equity issues within human systems \cite{germann2022assessing, ozik2021
A similar case can be made for another keyword - 'population dynamics' - to convey the purpose.

2023-06-21 00:01 UTC, ameyxd commented on papers/james_gaboardi/mybib.bib
> +  month        = {mar},
mar -> Mar

A general recommendation to check for and maintain consistency in month naming and periods after

2023-06-21 00:01 UTC, ameyxd commented on papers/james_gaboardi/mybib.bib
> +	month = sep,
sep -> Sept.

2023-06-21 00:01 UTC, ameyxd commented on papers/james_gaboardi/mybib.bib
> +    month={Sep}
sep -> Sept.

2023-06-21 00:01 UTC, ameyxd commented on papers/james_gaboardi/paper.tex
> +Foundational examples produced for Likeness have explored travel routing from home to anchor activities (e.g., work, school), POI occupancy characteristics \cite{likeness-scipy-paper-2022, likeness-s
I could not find the work associated with likeness_aag_2023. Is this published or currently under review? If so, please indicate in References.

2023-06-21 00:01 UTC, ameyxd commented on papers/james_gaboardi/paper.tex
> +discuss scaling our methods to larger areas of interest, as well as examines the performance of our activity allocation model relative to real-world POI demographics from digital trace data.
Please define or expand on the phrase 'digital trace data'.

2023-06-21 00:01 UTC, ameyxd commented on papers/james_gaboardi/paper.tex
> +Foundational examples produced for Likeness have explored travel routing from home to anchor activities (e.g., work, school), POI occupancy characteristics \cite{likeness-scipy-paper-2022, likeness-s
It may help to have a clear distinction between 'anchor' and 'non-anchor' POIs. For example, is 'home' considered anchor as implied from "anchor to non-anchor activities (e.g. social)..."?

2023-06-21 00:01 UTC, ameyxd commented on papers/james_gaboardi/paper.tex
> +In step with the creation of foundational examples for Likeness, we have developed an integrated workflow that scales the ecosystem (Figure~\ref{fig:ecosystem}) to support microsimulation for any met
I do not recommend starting with a preposition here. "Synchronous with" or similar may be better.

2023-06-21 00:01 UTC, ameyxd commented on papers/james_gaboardi/figures/ecosystem.tex
> +\begin{figure*}[htbp]
Please consider maintaining consistency in font styles used across all figures.

2023-06-21 00:01 UTC, ameyxd commented on papers/james_gaboardi/figures/ecosystem.tex
> +\fbox{\includegraphics[width=150mm]{figures/ecosystem.pdf}}
Dotted link from Agent Generation to '3' is undirected, is that missing an arrow? You could consider making it horizontal.

2023-06-21 00:01 UTC, ameyxd commented on papers/james_gaboardi/paper.tex
> +Figure~\ref{fig:parse-to-attribution} outlines the procedure for agent generation at the MSA level. As discussed in \cite{likeness-scipy-paper-2022}, the \texttt{livelike.acs.puma} class is the core
FIPS codes are not defined or explained. If relevant, please expand here.

2023-06-21 00:01 UTC, ameyxd commented on papers/james_gaboardi/paper.tex
> +Following the workflow described in Section~\nameref{section:likeness-expansion-scaling}, we demonstrate the current capabilities of Likeness and validate our activity allocation routine for Leon Cou
This is a general comment for the reference to sections: When using \nameref, try to number sections to reduce redundancy and verbosity, if the paper format allows for it (by setting \documentclass[conference] or by changing \setcounter). This goes for references to sections throughout the document.

2023-06-21 00:01 UTC, ameyxd commented on papers/james_gaboardi/paper.tex
> +The next stage in the workflow employs network analysis to model the cost of travel to these activities \cite{OpenStreetMap, osmnx_CEUS_2017, foti_generalized_2012} and allocate agents to POIs accord
Please expand on or mention the programming routines/libraries referenced here: PuLP, MILP, COIN-OR, etc.

2023-06-21 00:01 UTC, ameyxd commented on papers/james_gaboardi/mybib.bib
> +  author       = {John Forrest and
Please update author list with  proper names, or mention [Github profile] when applicable here.

2023-06-21 00:01 UTC, ameyxd commented on papers/james_gaboardi/paper.tex
> +The next stage in the workflow employs network analysis to model the cost of travel to these activities \cite{OpenStreetMap, osmnx_CEUS_2017, foti_generalized_2012} and allocate agents to POIs accord
```suggestion
The next stage in the workflow employs network analysis to model the cost of travel to these activities \cite{OpenStreetMap, osmnx_CEUS_2017, foti_generalized_2012} and allocate agents to POIs accordingly based on mathematical programming routines \cite{mitchell_pulp_2011, santos_mixed_2020, lougee_coin_2003, forrest_coinorcbc_2023}. In our first iteration of Likeness, both these tasks were accomplished within \texttt{actlike}. However, we concluded that the network modeling piece was specialized enough to be split from the \texttt{actlike} package, which led to the creation of \texttt{movelike}. With a push for varied modes of network traversal, three new modes of travel can now be modeled: walking, biking, public transit. However, modeling travel behavior via public transportation is less straightforward than for driving, biking, and walking networks due to stricter network topology, including factors like connectivity and directionality of routes. We have made our foray into modeling more realistic public transit behavior within \texttt{movelike} through the incorporation of the General Transit Feed Specification (GTFS)\footnote{https://gtfs.org/}. GTFS is a data specification that stipulates the required files, along with their structure and format\footnote{https://gtfs.org/schedule/reference/\#dataset-files}, for publishing, ingesting, and utilizing public transit datasets. The GTFS datasets can be obtained via services such as \textit{TransitFeeds}\footnote{https://transitfeeds.com/} and \textit{The Mobility Database Catalogs}\footnote{https://github.com/MobilityData/mobility-database-catalogs}. In our current iteration we utilize GTFS data feeds to implement a pseudo-transit network space by which agents can engage in limited traversal. This is accomplished through a mask of \textit{OpenStreetMap}\footnote{https://www.openstreetmap.org/} (OSM) street segments known to be associated with bus routes. The OSM network is masked by passing a (multi)polygon feature of buffered and unioned bus routes within the study area into \texttt{osmnx} \cite{osmnx_CEUS_2017}. This method demonstrates progression in representing public transit but certainly has room for improvement, which will be discussed in \nameref{section:dev-roadmap}.
```

2023-06-21 00:01 UTC, ameyxd commented on papers/james_gaboardi/paper.tex
> +The next stage in the workflow employs network analysis to model the cost of travel to these activities \cite{OpenStreetMap, osmnx_CEUS_2017, foti_generalized_2012} and allocate agents to POIs accord
Grammar and phrasing - 'made our foray', etc. 'first foray' is redundant - foray implies first attempt.

2023-06-21 00:01 UTC, ameyxd commented on papers/james_gaboardi/paper.tex
> +Following the workflow described in Section~\nameref{section:likeness-expansion-scaling}, we demonstrate the current capabilities of Likeness and validate our activity allocation routine for Leon Cou
```suggestion
Following the workflow described in Section~\nameref{section:likeness-expansion-scaling}, we demonstrate the current capabilities of Likeness and validate our activity allocation routine for Leon County, Florida. Leon County, whose primary city is Tallahassee, features a population of just under 300,000 residents, a compact urban footprint, and a diverse array of transportation modes (driving, transit, bike, walking). Our mobility validation exercise is based on grocery store visits from simulated home locations. Grocery stores provide a useful test case because they are both catchments for the general population and points of access to vital services including food and healthcare. We obtained grocery store visits from Foursquare's Research Visits feed, which provides footfall data attributed by demographic cohort (gender by age) for a variety of POI types\footnote{https://location.foursquare.com/places/docs/how-does-places-work}\textsuperscript{,}\footnote{https://location.foursquare.com/visits/docs/research-feed-schema}. 
```

2023-06-21 00:01 UTC, ameyxd commented on papers/james_gaboardi/paper.tex
> +Following the workflow described in Section~\nameref{section:likeness-expansion-scaling}, we demonstrate the current capabilities of Likeness and validate our activity allocation routine for Leon Cou
POI is defined.

2023-06-21 00:01 UTC, ameyxd commented on papers/james_gaboardi/paper.tex
> +We first simulated a single synthetic population for the Tallahassee Core-Based Statistical Area (CBSA), based on constraining variables including technical characteristics linked to sampling univers
```suggestion
We first simulated a single synthetic population for the Tallahassee Core-Based Statistical Area (CBSA), based on constraining variables including technical characteristics linked to sampling universe totals (i.e., population, housing units, households), as well as descriptive factors including demographics, socioeconomic status, housing, mobility, and worker and student characteristics. For the remainder of the analysis, we focused on Leon County alone, removing large outlying areas of the MSA (PUMA \texttt{1206300}). Agents\footnote{Agents less than 20 years old were not include in the Foursquare POI data, thus they are excluded from our analysis.} were generated on the Federal Emergency Management Agency's (FEMA) open USA Structures database \cite{yang2018building, usa_struct_2022}, based on the sampling of synthetic households to single-family residential, multi-family residential, mobile homes, and group quarters housing types.
```

2023-06-21 00:01 UTC, ameyxd commented on papers/james_gaboardi/paper.tex
> +Figure~\ref{fig:2x2_agents_hex} shows that Leon County's agent population is distributed unevenly relative to assigned travel modes. Because Leon County's infrastructure primarily supports travel by
The readability and analysis of Figure 4 could be improved by moving it to page 3.

2023-06-21 00:01 UTC, ameyxd commented on papers/james_gaboardi/paper.tex
> +After travel mode was assigned, four network cost matrices were calculated from origins (agents' residential locations) to destination POIs in \texttt{movelike}. Agents were then allocated to a singl
Please elaborate on the original Transportation Problem. Is it based on the GIS-T? The referenced citation is broad.

2023-06-21 00:01 UTC, ameyxd commented on papers/james_gaboardi/paper.tex
> +The large disparity in problem size seen in Table~\ref{tab:agents_counts_travel_mode} is even more pronounced in solution runtimes, shown in Table~\ref{tab:allocation_solution_runtime}, with optimal
In line with the suggestion to rearrange figures, consider showing Table 1 and Table 2 on the same page to highlight clear correlations in their content (high agent count corresponding to high runtime).

2023-06-21 00:01 UTC, ameyxd commented on papers/james_gaboardi/paper.tex
> +We also investigated local (POI-specific) within-destination correspondence in compositional characteristics based on gender/age cohorts in five-year intervals (until age 70, which is top-coded), in
Please cite Spearman correlation here.

2023-06-21 00:01 UTC, ameyxd commented on papers/james_gaboardi/paper.tex
> +Each of the three P-MEDM runs (one for each PUMA in the Tallahassee CBSA) resulted in a synthetic reconstruction of the ACS 90\% MOEs that conformed within 99\% of the published MOEs from the ACS SF
somewhat -> use more formal words like 'relatively' or 'moderately'

2023-06-21 00:01 UTC, ameyxd commented on papers/james_gaboardi/paper.tex
> +Each of the three P-MEDM runs (one for each PUMA in the Tallahassee CBSA) resulted in a synthetic reconstruction of the ACS 90\% MOEs that conformed within 99\% of the published MOEs from the ACS SF
Is there determined reasoning for why large population centers exhibit diminished performance? Can you mention that after concluding this sentence?

2023-06-21 00:01 UTC, ameyxd commented on papers/james_gaboardi/paper.tex
> +    \item The clearest \textbf{data-specific} challenge is temporal mismatch between the synthetic population (2019) and POI visit data (2023). We have yet to increment our ACS year due to sporadic i
Reason for emboldening 'data-specific' and 'model-specific'?

2023-06-21 00:01 UTC, ameyxd commented on papers/james_gaboardi/paper.tex
> +We found that overall, Likeness approximates travel to non-anchor (grocery store) POIs modestly well. However, contrasted with anchor activities (work/school) demonstrated in \cite{likeness-scipy-pap
confounded -> more formal 'negatively impacted' or 'negatively influenced'

2023-06-21 00:01 UTC, ameyxd commented on papers/james_gaboardi/paper.tex
> +    \item Going forward, we also hope to tighten our assumptions about the feasibility of POI access relative to the various travel modes. For example, in our current assignment process (Figure~\ref{
I do not see the purpose of having point 3 in this list, since it talks about potential changes you hope to make in future iterations. Consider having this as a conclusion of this section instead of a point.

2023-06-21 00:01 UTC, ameyxd commented on papers/james_gaboardi/paper.tex
> +This paper presented enhancements and scaling for the Likeness spatial microsimulation toolkit -- including implementing batched population synthesis runs and large-scale transportation network gener
The concluding statement is a bit vague. Please briefly point out one or two research questions that are evident from your initial exercise, and refrain from mentioning 'plan to tackle as our workflow develops' -> 'plan to answer in future work'.

2023-06-21 00:01 UTC, ameyxd commented on papers/james_gaboardi/paper.tex
> +    \item \textbf{Improving mobility modeling.} Realism in mobility modeling is a key area in which we are constantly striving for improvements, specifically transit. As stated previously in \nameref
Too subjective/informal, please rephrase the following: "Realism in mobility modeling is a key area in which we are constantly striving for improvements, specifically transit."

2023-06-21 00:01 UTC, ameyxd commented on papers/james_gaboardi/paper.tex
> +    \item \textbf{Optimization bottleneck.} As demonstrated in \nameref{section:results}, there is a clear hit in computational performance and runtime when solving  \texttt{actlike.ActivityAllocatio
Scalability issues are pretty common in simulation problems. I would like to see an additional sentence here, summarizing it and the general plan.

2023-06-21 00:01 UTC, ameyxd commented on papers/james_gaboardi/paper.tex
> +\bibliography{ mybib }
Overall, this is solid work, with quality content and descriptive diagrams/tables. It would benefit from the addition of some broader implications, insights, and details of the findings. Good job!

2023-06-21 00:01 UTC, ameyxd commented on papers/james_gaboardi/paper.tex
> +The next stage in the workflow employs network analysis to model the cost of travel to these activities \cite{OpenStreetMap, osmnx_CEUS_2017, foti_generalized_2012} and allocate agents to POIs accord
Please cite OpenStreetMap for all figures outside of footnotes.

2023-06-21 00:03 UTC, ameyxd commented
@jGaboardi Good work. Please @ me when you make changes to review - I am not being notified for this thread 👍🏽

2023-06-21 00:26 UTC, jGaboardi commented
> @jGaboardi Good work. Please @ me when you make changes to review - I am not being notified for this thread 👍🏽

@ameyxd Thank you for your detailed review! @jvtcl and I will go over you comments and respond.

2023-06-21 06:04 UTC, kalyan678 commented on papers/james_gaboardi/metadata.yaml
> +  - "Understanding human security and social equity issues within human systems requires large-scale models of population dynamics that simulate high-fidelity representations of individuals and acces
The abstract is well-written and informative. It provides a clear overview of the paper's purpose, methods, and findings. The only suggestion I would make is to break up the first sentence into two sentences, for better readability.

For example: 
- Understanding human security and social equity issues requires large-scale models of population dynamics that simulate high-fidelity representations of individuals and access to essential activities. Likeness is a Python toolkit that provides these capabilities for Oak Ridge National Laboratory's (ORNL) UrbanPop spatial microsimulation project.

- In this paper, we describe the expansion and scaling of Likeness capabilities to metropolitan areas in the United States. We then provide an integrated demonstration of our methods based on a case study of Leon County, FL. We perform validation exercises on 1) neighborhood demographic composition and 2) visits by demographic cohorts (gender/age) obtained from point of interest (POI) footfall data for essential services (grocery stores).

2023-06-21 06:04 UTC, kalyan678 commented on papers/james_gaboardi/paper.tex
> +Agent-based models linking individual behavior to population dynamics are essential for understanding human security and social equity issues within human systems \cite{germann2022assessing, ozik2021
The introduction of the paper provides a clear overview of the research topic and highlights the significance of agent-based models in understanding human security and social equity issues. Here are some suggestions to improve the different aspects of the introduction:

- The introduction is well-written and effectively communicates the main points. However, you could enhance the clarity and flow by breaking down the long sentences into shorter ones. Additionally, consider using more specific and concise language to avoid unnecessary repetition.
- Lastly, in the first sentence, you could add a bit more detail about what agent-based models are and why they are important. For example, you could say something like "Agent-based models are computer simulations that allow us to model the behavior of individual agents and how their interactions can give rise to complex system-level behavior."

2023-06-21 06:04 UTC, kalyan678 commented on papers/james_gaboardi/paper.tex
> +Foundational examples produced for Likeness have explored travel routing from home to anchor activities (e.g., work, school), POI occupancy characteristics \cite{likeness-scipy-paper-2022, likeness-s
Consider highlighting particular societal or scientific issues that can be solved using the developed methodologies, in my opinion, to further emphasize the paper's significance. Be sure to emphasize the insights that may be gained from the combination of synthetic populations, real-world data, and activity allocation in a variety of fields, including urban planning, public health, and disaster preparedness. I think this will help readers to find the introduction more interesting, informative, and appealing.

2023-06-21 06:04 UTC, kalyan678 commented on papers/james_gaboardi/paper.tex
> +Figure~\ref{fig:parse-to-attribution} outlines the procedure for agent generation at the MSA level. As discussed in \cite{likeness-scipy-paper-2022}, the \texttt{livelike.acs.puma} class is the core
- I think it would be good to provide more details about the validation exercises that conducted. For example, You could discuss the specific metrics that they used to measure the accuracy of the simulations, and they could provide more information about the results of the validation exercises.

2023-06-21 06:04 UTC, kalyan678 commented on papers/james_gaboardi/paper.tex
> +Finally -- and at the heart of it all -- expansion and scaling of the Likeness ecosystem led to the development of a new package for common utilities, \texttt{likeness-vitals}, which provides support
- The future use of the Likeness toolset has been outlined in clear terms, and I appreciated the thorough citations of pertinent academic works.
- Overall, I believe that we can simplify the language and sentence structure to make the content more accessible to readers. Break down complex sentences into smaller, more concise ones.

2023-06-21 06:04 UTC, kalyan678 commented on papers/james_gaboardi/paper.tex
> +Following the workflow described in Section~\nameref{section:likeness-expansion-scaling}, we demonstrate the current capabilities of Likeness and validate our activity allocation routine for Leon Cou
- Although you provided a reference to TransitFeeds data, I double-checked and discovered that "TransitFeeds data is not regularly updated. Find up-to-date GTFS Schedule data on the the Mobility Database catalogs." I do not see any such highlight in the paper.

2023-06-21 06:04 UTC, kalyan678 commented on papers/james_gaboardi/paper.tex
> +We first simulated a single synthetic population for the Tallahassee Core-Based Statistical Area (CBSA), based on constraining variables including technical characteristics linked to sampling univers
There are a few technical terms and acronyms that could be briefly explained or replaced with simpler language to improve understanding for a broader audience. For example, instead of "PUMA 1206300," you could mention that it refers to a specific geographical area.

2023-06-21 06:04 UTC, kalyan678 commented on papers/james_gaboardi/paper.tex
> +\subsubsection{Demographic Validation}
While the text provides detailed information about the methodology, it could benefit from providing a bit more context about the significance and real-world implications of the study. Explain why understanding travel behavior and infrastructure planning is important for urban areas like Leon County.

2023-06-21 06:04 UTC, kalyan678 commented on papers/james_gaboardi/paper.tex
> +Each of the three P-MEDM runs (one for each PUMA in the Tallahassee CBSA) resulted in a synthetic reconstruction of the ACS 90\% MOEs that conformed within 99\% of the published MOEs from the ACS SF
- It was difficult to grasp the main point here. My point here is break them down into shorter, more digestible sentences. For example, instead of "Each of the three P-MEDM runs (one for each PUMA in the Tallahassee CBSA) resulted in a synthetic reconstruction of the ACS 90% MOEs that conformed within 99% of the published MOEs from the ACS SF," you could say "Each of the three P-MEDM runs (one for each PUMA in the Tallahassee CBSA) resulted in a synthetic reconstruction of the ACS 90% MOEs. These reconstructions conformed within 99% of the published MOEs from the ACS SF." Let me know how that sounds?

2023-06-21 06:04 UTC, kalyan678 commented on papers/james_gaboardi/paper.tex
> +Our mobility simulation more realistically recreated between-destination demographics ($R^2$ = 0.74) than within-destination demographics ($R^2$ = 0.41) (Table~\ref{tab:demographic-validation}). Insp
- It would be really helpful if you can provide more details about the limitations and challenges faced during the mobility validation exercise and the modest success achieved. This will help readers understand the context and potential areas for improvement.

2023-06-21 06:04 UTC, kalyan678 commented on papers/james_gaboardi/paper.tex
> +    \item \textbf{Packaging schema.} A further consideration related to open-sourcing is whether we should migrate from a confederated toolkit schema where each module is a semi-independent Python pa
May be, it's good to elaborate on the benefits and considerations associated with migrating from a confederated toolkit schema to a monolithic Python package. Discuss the implications and potential advantages of each approach.

2023-06-21 06:04 UTC, kalyan678 commented on papers/james_gaboardi/figures/ecosystem.tex
> +\label{fig:ecosystem}
The Likeness ecosystem overview is pretty straightforward!

2023-06-21 06:04 UTC, kalyan678 commented on papers/james_gaboardi/figures/mode_assign_workflow.tex
> +\label{fig:mode_assign_workflow}
Decision tree is visually appealing and easy to follow. Keep up the good work!!

2023-06-21 06:04 UTC, kalyan678 commented on papers/james_gaboardi/paper.tex
> +\end{document}
Overall, the paper is well-written and informative. The quality of the writing is good. The content is well-structured and organized, making it easy to follow the flow of information. However, I feel some sentences and phrases could be simplified to enhance readability. Finally, the paper demonstrates a strong technical understanding and presents a detailed analysis of the research. It effectively communicates the objectives, methods, and results of the study.

2023-06-21 06:10 UTC, kalyan678 commented
> @kalyan678 Thank you completing your review! Perhaps you forgot to post your actual review comments?

@jGaboardi Sorry, my bad! I think you should see my comments now. Can you please confirm?

2023-06-21 14:29 UTC, ameyxd commented on papers/james_gaboardi/paper.tex
> +We first simulated a single synthetic population for the Tallahassee Core-Based Statistical Area (CBSA), based on constraining variables including technical characteristics linked to sampling univers
I disagree, perhaps add geographical area but don’t remove the PUMA. It is descriptive and helps people familiar with the topic quickly identify the region if they want to.

2023-06-21 14:32 UTC, ameyxd commented on papers/james_gaboardi/paper.tex
> +Foundational examples produced for Likeness have explored travel routing from home to anchor activities (e.g., work, school), POI occupancy characteristics \cite{likeness-scipy-paper-2022, likeness-s
I agree with this. The work is technically sound, but will benefit from highlighting the more obvious implications and insights to appeal to the general audience. @jGaboardi you can perhaps attend to this at the end of your abstract, Introduction and/or conclusion.

2023-06-21 17:00 UTC, jGaboardi commented
> > @kalyan678 Thank you completing your review! Perhaps you forgot to post your actual review comments?
> 
> @jGaboardi Sorry, my bad! I think you should see my comments now. Can you please confirm?

Yes, I can see. Thanks!

2023-06-21 18:36 UTC, kalyan678 commented
> > > @kalyan678 Thank you completing your review! Perhaps you forgot to post your actual review comments?
> > 
> > 
> > @jGaboardi Sorry, my bad! I think you should see my comments now. Can you please confirm?
> 
> Yes, I can see. Thanks!

@jGaboardi  Awesome!! Kindly @.. mention me when you make the modifications so that it will be easy for me to follow. Thanks!!

2023-06-21 21:25 UTC, jGaboardi commented
@ameyxd & @kalyan678, thanks so much for you detailed reviews. If you are both finished with comments at this time @jvtcl and I will go over them and respond in turn.

2023-06-23 14:54 UTC, jvtcl commented on papers/james_gaboardi/paper.tex
> +Agent-based models linking individual behavior to population dynamics are essential for understanding human security and social equity issues within human systems \cite{germann2022assessing, ozik2021
- [ ] @jvtcl to address this

2023-06-23 14:55 UTC, jvtcl commented on papers/james_gaboardi/mybib.bib
> +  month        = {mar},
- [ ] @jGaboardi to address this

2023-06-23 14:55 UTC, jvtcl commented on papers/james_gaboardi/mybib.bib
> +	month = sep,
- [ ] @jGaboardi to address this

2023-06-23 14:55 UTC, jvtcl commented on papers/james_gaboardi/mybib.bib
> +    month={Sep}
- [ ] @jGaboardi to address this

2023-06-23 14:56 UTC, jvtcl commented on papers/james_gaboardi/paper.tex
> +Foundational examples produced for Likeness have explored travel routing from home to anchor activities (e.g., work, school), POI occupancy characteristics \cite{likeness-scipy-paper-2022, likeness-s
- [ ] @jGaboardi to address this. I think there's a Zenodo for this? We might have just forgotten to add the BibTeX.

2023-06-23 14:56 UTC, jvtcl commented on papers/james_gaboardi/paper.tex
> +discuss scaling our methods to larger areas of interest, as well as examines the performance of our activity allocation model relative to real-world POI demographics from digital trace data.
- [ ] @jvtcl to address this.

2023-06-23 14:58 UTC, jvtcl commented on papers/james_gaboardi/paper.tex
> +Foundational examples produced for Likeness have explored travel routing from home to anchor activities (e.g., work, school), POI occupancy characteristics \cite{likeness-scipy-paper-2022, likeness-s
@ameyxd We consider home to be separate from anchor activities like school and work. We will clarify by using the terminology "home locations". 

- [ ] @jvtcl to address this.

2023-06-23 14:59 UTC, jvtcl commented on papers/james_gaboardi/paper.tex
> +In step with the creation of foundational examples for Likeness, we have developed an integrated workflow that scales the ecosystem (Figure~\ref{fig:ecosystem}) to support microsimulation for any met
- [ ] @jvtcl to address this.

2023-06-23 15:02 UTC, jvtcl commented on papers/james_gaboardi/figures/ecosystem.tex
> +\begin{figure*}[htbp]
@ameyxd We appreciate this comment, but this may be a challenge for us, as the figures were generated through various means, including PowerPoint, LucidChart, `matplotlib`, as well as Stamen Maps, which all use different font styles.

2023-06-23 15:03 UTC, jvtcl commented on papers/james_gaboardi/figures/ecosystem.tex
> +\fbox{\includegraphics[width=150mm]{figures/ecosystem.pdf}}
- [ ] @jvtcl to address this.

2023-06-23 15:04 UTC, jvtcl commented on papers/james_gaboardi/figures/ecosystem.tex
> +\fbox{\includegraphics[width=150mm]{figures/ecosystem.pdf}}
We also need to remove the asterisk from the "Activity Model" bubble. This was from an earlier version of the figure and no longer is needed.

2023-06-23 15:04 UTC, jvtcl commented on papers/james_gaboardi/paper.tex
> +Figure~\ref{fig:parse-to-attribution} outlines the procedure for agent generation at the MSA level. As discussed in \cite{likeness-scipy-paper-2022}, the \texttt{livelike.acs.puma} class is the core
- [ ] @jvtcl to address this.

2023-06-23 15:05 UTC, jvtcl commented on papers/james_gaboardi/paper.tex
> +Following the workflow described in Section~\nameref{section:likeness-expansion-scaling}, we demonstrate the current capabilities of Likeness and validate our activity allocation routine for Leon Cou
- [ ] @jGaboardi to address this.

2023-06-23 15:06 UTC, jvtcl commented on papers/james_gaboardi/paper.tex
> +The next stage in the workflow employs network analysis to model the cost of travel to these activities \cite{OpenStreetMap, osmnx_CEUS_2017, foti_generalized_2012} and allocate agents to POIs accord
- [ ] @jGaboardi to address this.

2023-06-23 15:06 UTC, jvtcl commented on papers/james_gaboardi/mybib.bib
> +  author       = {John Forrest and
- [ ] @jGaboardi to address this.

2023-06-23 15:07 UTC, jvtcl commented on papers/james_gaboardi/paper.tex
> +The next stage in the workflow employs network analysis to model the cost of travel to these activities \cite{OpenStreetMap, osmnx_CEUS_2017, foti_generalized_2012} and allocate agents to POIs accord
**- [ ] @jGaboardi to address this.**

2023-06-23 15:09 UTC, jvtcl commented on papers/james_gaboardi/paper.tex
> +Following the workflow described in Section~\nameref{section:likeness-expansion-scaling}, we demonstrate the current capabilities of Likeness and validate our activity allocation routine for Leon Cou
- [ ] @jGaboardi to address this.

2023-06-23 15:09 UTC, jvtcl commented on papers/james_gaboardi/paper.tex
> +We first simulated a single synthetic population for the Tallahassee Core-Based Statistical Area (CBSA), based on constraining variables including technical characteristics linked to sampling univers
- [ ] @jGaboardi to address this.

2023-06-23 15:09 UTC, jvtcl commented on papers/james_gaboardi/paper.tex
> +Figure~\ref{fig:2x2_agents_hex} shows that Leon County's agent population is distributed unevenly relative to assigned travel modes. Because Leon County's infrastructure primarily supports travel by
- [ ] @jGaboardi to address this.

2023-06-23 15:09 UTC, jvtcl commented on papers/james_gaboardi/paper.tex
> +After travel mode was assigned, four network cost matrices were calculated from origins (agents' residential locations) to destination POIs in \texttt{movelike}. Agents were then allocated to a singl
- [ ] @jGaboardi to address this.

2023-06-23 15:10 UTC, jvtcl commented on papers/james_gaboardi/paper.tex
> +The large disparity in problem size seen in Table~\ref{tab:agents_counts_travel_mode} is even more pronounced in solution runtimes, shown in Table~\ref{tab:allocation_solution_runtime}, with optimal
- [ ] @jGaboardi to address this.

2023-06-23 15:10 UTC, jvtcl commented on papers/james_gaboardi/paper.tex
> +We also investigated local (POI-specific) within-destination correspondence in compositional characteristics based on gender/age cohorts in five-year intervals (until age 70, which is top-coded), in
- [ ] @jvtcl to address this.

2023-06-23 15:10 UTC, jvtcl commented on papers/james_gaboardi/paper.tex
> +Each of the three P-MEDM runs (one for each PUMA in the Tallahassee CBSA) resulted in a synthetic reconstruction of the ACS 90\% MOEs that conformed within 99\% of the published MOEs from the ACS SF
- [ ] @jvtcl to address this.

2023-06-23 15:10 UTC, jvtcl commented on papers/james_gaboardi/paper.tex
> +Each of the three P-MEDM runs (one for each PUMA in the Tallahassee CBSA) resulted in a synthetic reconstruction of the ACS 90\% MOEs that conformed within 99\% of the published MOEs from the ACS SF
- [ ] @jvtcl to address this.

2023-06-23 15:11 UTC, jvtcl commented on papers/james_gaboardi/paper.tex
> +    \item The clearest \textbf{data-specific} challenge is temporal mismatch between the synthetic population (2019) and POI visit data (2023). We have yet to increment our ACS year due to sporadic i
@ameyxd We emboldened this text to highlight the subject of each item. We could also place this text before the descriptions if you think that would be clearer.

2023-06-23 15:11 UTC, jvtcl commented on papers/james_gaboardi/paper.tex
> +    \item The clearest \textbf{data-specific} challenge is temporal mismatch between the synthetic population (2019) and POI visit data (2023). We have yet to increment our ACS year due to sporadic i
- [ ] @jvtcl to address this.

2023-06-23 15:12 UTC, jvtcl commented on papers/james_gaboardi/paper.tex
> +We found that overall, Likeness approximates travel to non-anchor (grocery store) POIs modestly well. However, contrasted with anchor activities (work/school) demonstrated in \cite{likeness-scipy-pap
- [ ] @jvtcl to address this.

2023-06-23 15:13 UTC, jvtcl commented on papers/james_gaboardi/paper.tex
> +    \item Going forward, we also hope to tighten our assumptions about the feasibility of POI access relative to the various travel modes. For example, in our current assignment process (Figure~\ref{
@ameyxd We agree with this suggestion and will make the recommended changes. 

- [ ] @jvtcl to address this.

2023-06-23 15:13 UTC, jvtcl commented on papers/james_gaboardi/paper.tex
> +This paper presented enhancements and scaling for the Likeness spatial microsimulation toolkit -- including implementing batched population synthesis runs and large-scale transportation network gener
- [ ] @jvtcl to address this.

2023-06-23 15:13 UTC, jvtcl commented on papers/james_gaboardi/paper.tex
> +    \item \textbf{Improving mobility modeling.} Realism in mobility modeling is a key area in which we are constantly striving for improvements, specifically transit. As stated previously in \nameref
- [ ] @jGaboardi  to address this.

2023-06-23 15:15 UTC, jvtcl commented on papers/james_gaboardi/paper.tex
> +    \item \textbf{Optimization bottleneck.} As demonstrated in \nameref{section:results}, there is a clear hit in computational performance and runtime when solving  \texttt{actlike.ActivityAllocatio
- [ ] @jvtcl to discuss tooling for generating synthetic populations with national coverage.
- [ ] @jGaboardi to discuss challenges associated with scaling activity allocation and ways forward. Benefits of an engine like `HiGHS` towards this task?

2023-06-23 15:17 UTC, jvtcl commented on papers/james_gaboardi/paper.tex
> +The next stage in the workflow employs network analysis to model the cost of travel to these activities \cite{OpenStreetMap, osmnx_CEUS_2017, foti_generalized_2012} and allocate agents to POIs accord
@ameyxd Could you please clarify this point? Do you mean adding attribution to captions for figures that use OSM?

- [ ] @jGaboardi  to address this.

2023-06-23 15:17 UTC, jvtcl commented on papers/james_gaboardi/metadata.yaml
> +  - "Understanding human security and social equity issues within human systems requires large-scale models of population dynamics that simulate high-fidelity representations of individuals and acces
- [ ] @jvtcl to address this.

2023-06-23 15:18 UTC, jvtcl commented on papers/james_gaboardi/paper.tex
> +Agent-based models linking individual behavior to population dynamics are essential for understanding human security and social equity issues within human systems \cite{germann2022assessing, ozik2021
- [ ] @jvtcl to address this.

2023-06-23 15:18 UTC, jvtcl commented on papers/james_gaboardi/paper.tex
> +Foundational examples produced for Likeness have explored travel routing from home to anchor activities (e.g., work, school), POI occupancy characteristics \cite{likeness-scipy-paper-2022, likeness-s
- [ ] @jvtcl to address this.

2023-06-23 15:22 UTC, jvtcl commented on papers/james_gaboardi/paper.tex
> +Figure~\ref{fig:parse-to-attribution} outlines the procedure for agent generation at the MSA level. As discussed in \cite{likeness-scipy-paper-2022}, the \texttt{livelike.acs.puma} class is the core
- [ ] @jvtcl to add a citation for CCA [here] https://github.com/jGaboardi/scipy_proceedings/blob/f49ce084823d019f9c7458534a7211078f99f2c4/papers/james_gaboardi/paper.tex#L68.

@kalyan678 the highlighted text does not seem to match the section that you'd like us to update. Could you please point us to the lines in the text that need revision?

2023-06-23 15:23 UTC, jvtcl commented on papers/james_gaboardi/paper.tex
> +Finally -- and at the heart of it all -- expansion and scaling of the Likeness ecosystem led to the development of a new package for common utilities, \texttt{likeness-vitals}, which provides support
- [ ] @jvtcl to address this.

2023-06-23 15:23 UTC, jvtcl commented on papers/james_gaboardi/paper.tex
> +Following the workflow described in Section~\nameref{section:likeness-expansion-scaling}, we demonstrate the current capabilities of Likeness and validate our activity allocation routine for Leon Cou
- [x] @jGaboardi to address this.

2023-06-23 15:24 UTC, jvtcl commented on papers/james_gaboardi/paper.tex
> +We first simulated a single synthetic population for the Tallahassee Core-Based Statistical Area (CBSA), based on constraining variables including technical characteristics linked to sampling univers
- [ ] @jvtcl to clarify this.

2023-06-23 15:24 UTC, jvtcl commented on papers/james_gaboardi/paper.tex
> +\subsubsection{Demographic Validation}
- [ ] @jvtcl to address this.

2023-06-23 15:24 UTC, jvtcl commented on papers/james_gaboardi/paper.tex
> +Each of the three P-MEDM runs (one for each PUMA in the Tallahassee CBSA) resulted in a synthetic reconstruction of the ACS 90\% MOEs that conformed within 99\% of the published MOEs from the ACS SF
@kalyan678 We agree with this suggestion. 

- [ ] @jvtcl to address this.

2023-06-23 15:25 UTC, jvtcl commented on papers/james_gaboardi/paper.tex
> +Our mobility simulation more realistically recreated between-destination demographics ($R^2$ = 0.74) than within-destination demographics ($R^2$ = 0.41) (Table~\ref{tab:demographic-validation}). Insp
- [ ] @jvtcl to address this.

2023-06-23 15:25 UTC, jvtcl commented on papers/james_gaboardi/paper.tex
> +    \item \textbf{Packaging schema.} A further consideration related to open-sourcing is whether we should migrate from a confederated toolkit schema where each module is a semi-independent Python pa
- [ ] @jGaboardi to address this.

2023-06-23 15:26 UTC, jvtcl commented on papers/james_gaboardi/paper.tex
> +\end{document}
@kalyan678 We appreciate your comments and will address readability and discussion points you mentioned in your review.

2023-06-23 15:56 UTC, jGaboardi commented on papers/james_gaboardi/paper.tex
> +Following the workflow described in Section~\nameref{section:likeness-expansion-scaling}, we demonstrate the current capabilities of Likeness and validate our activity allocation routine for Leon Cou
@ameyxd W are not sure that the SciPy Proceedings allow for that and we could not find examples of that format in other submissions for this year. Perhaps we can get an editor's opinion on the matter? cc @mepa

2023-06-23 15:59 UTC, jGaboardi commented on papers/james_gaboardi/mybib.bib
> +  author       = {John Forrest and
All software references in the manuscript are the official recommended ones from respective packages. We do not think a change is needed.

2023-06-23 16:12 UTC, jGaboardi commented on papers/james_gaboardi/paper.tex
> +The next stage in the workflow employs network analysis to model the cost of travel to these activities \cite{OpenStreetMap, osmnx_CEUS_2017, foti_generalized_2012} and allocate agents to POIs accord
@ameyxd All plots that use OSM are already attributed within the figure themselves. Are you suggesting another layer of attritbution/citation?

2023-06-23 17:25 UTC, ameyxd commented on papers/james_gaboardi/paper.tex
> +The next stage in the workflow employs network analysis to model the cost of travel to these activities \cite{OpenStreetMap, osmnx_CEUS_2017, foti_generalized_2012} and allocate agents to POIs accord
I noticed that. You can disregard this - all OSM attributions in figures are good.

2023-06-26 23:23 UTC, jGaboardi commented on papers/james_gaboardi/mybib.bib
> +  month        = {mar},
@jvtcl This is completed locally in our ShareLeaf. Please mark as done. (I can't tick off your check box)

2023-06-26 23:23 UTC, jGaboardi commented on papers/james_gaboardi/mybib.bib
> +	month = sep,
@jvtcl Please mark as completed.

2023-06-26 23:23 UTC, jGaboardi commented on papers/james_gaboardi/mybib.bib
> +    month={Sep}
@jvtcl Please mark as completed.

2023-06-26 23:33 UTC, jGaboardi commented on papers/james_gaboardi/paper.tex
> +Foundational examples produced for Likeness have explored travel routing from home to anchor activities (e.g., work, school), POI occupancy characteristics \cite{likeness-scipy-paper-2022, likeness-s
We have a Zenodo DOI for it and it is listed in out references section:

> [7] J. D. Gaboardi and J. V. Tuccillo, “Spatial Microsimulation and ActivityAllocation  for  Examining  COVID-19  Vaccine  Access  Profiles,”  Mar.2023.

It is a conference presentation with designated DOI. However, the BiBteX style was omitting the `url` field. I updated the entry with a `howpublished` field that now shows the proper URL.

@jvtcl Please mark as completed.

2023-06-26 23:34 UTC, jGaboardi commented on papers/james_gaboardi/mybib.bib
> +  author       = {John Forrest and
@jvtcl Please mark as completed.

2023-06-26 23:36 UTC, jGaboardi commented on papers/james_gaboardi/paper.tex
> +Figure~\ref{fig:2x2_agents_hex} shows that Leon County's agent population is distributed unevenly relative to assigned travel modes. Because Leon County's infrastructure primarily supports travel by
After we address and resolve all text edits, etc. we will attempt to accommodate this suggestion. However, the typesetting is done within LaTeX and we have limited control over the resultant PDF output.

2023-06-26 23:37 UTC, jGaboardi commented on papers/james_gaboardi/paper.tex
> +The large disparity in problem size seen in Table~\ref{tab:agents_counts_travel_mode} is even more pronounced in solution runtimes, shown in Table~\ref{tab:allocation_solution_runtime}, with optimal
As [commented above](https://github.com/scipy-conference/scipy_proceedings/pull/834#discussion_r1242936515), we will attempt to accommodate this suggestion.

2023-06-26 23:53 UTC, ameyxd commented on papers/james_gaboardi/paper.tex
> +Figure~\ref{fig:2x2_agents_hex} shows that Leon County's agent population is distributed unevenly relative to assigned travel modes. Because Leon County's infrastructure primarily supports travel by
You may be able to force positions. It's okay if not. 👍🏽

2023-06-27 00:12 UTC, jGaboardi commented on papers/james_gaboardi/paper.tex
> +The next stage in the workflow employs network analysis to model the cost of travel to these activities \cite{OpenStreetMap, osmnx_CEUS_2017, foti_generalized_2012} and allocate agents to POIs accord
@jvtcl I expanded on this within a footnote in our internal ShareLeaf.

2023-06-27 00:37 UTC, jGaboardi commented on papers/james_gaboardi/paper.tex
> +After travel mode was assigned, four network cost matrices were calculated from origins (agents' residential locations) to destination POIs in \texttt{movelike}. Agents were then allocated to a singl
* I have added several more (and clearer) citation within our text and added some clarifying language.
* Here we are referring to and expanding on the [Hitchcock/Koopmans Transportation Problem](https://en.wikipedia.org/wiki/Transportation_theory_(mathematics)#Hitchcock_problem).
* @jvtcl Please mark as completed.

2023-06-27 00:58 UTC, jGaboardi commented on papers/james_gaboardi/paper.tex
> +    \item \textbf{Improving mobility modeling.} Realism in mobility modeling is a key area in which we are constantly striving for improvements, specifically transit. As stated previously in \nameref
* I have revised that sentence.
* @jvtcl Please mark as completed.

2023-06-27 01:19 UTC, jGaboardi commented on papers/james_gaboardi/paper.tex
> +    \item \textbf{Optimization bottleneck.} As demonstrated in \nameref{section:results}, there is a clear hit in computational performance and runtime when solving  \texttt{actlike.ActivityAllocatio
@jvtcl I have added some more explanatory language in for this. Please mark my portion as completed.

2023-06-27 01:29 UTC, jGaboardi commented on papers/james_gaboardi/paper.tex
> +Following the workflow described in Section~\nameref{section:likeness-expansion-scaling}, we demonstrate the current capabilities of Likeness and validate our activity allocation routine for Leon Cou
@kalyan678 

In that sentence we also provide a comment on The Mobility Database Catalogs and a footnote including a link to the GitHub Repo (should be footnote (8.)). Is there something more you are looking for here?

> The GTFS datasets can be obtained via services such as *TransitFeeds*[^7] and *The Mobility Database Catalogs*[^8].

> [^7]: https://transitfeeds.com/
> [^8]: https://github.com/MobilityData/mobility-database-catalogs

2023-06-27 01:36 UTC, jGaboardi commented on papers/james_gaboardi/paper.tex
> +    \item \textbf{Packaging schema.} A further consideration related to open-sourcing is whether we should migrate from a confederated toolkit schema where each module is a semi-independent Python pa
@jvtcl I have added some more explanatory language in for this. Please mark my portion as completed.

2023-06-30 23:45 UTC, mepa commented
@scoobies mark pending comment

2023-07-01 11:25 UTC, kalyan678 commented on papers/james_gaboardi/paper.tex
> +Figure~\ref{fig:parse-to-attribution} outlines the procedure for agent generation at the MSA level. As discussed in \cite{likeness-scipy-paper-2022}, the \texttt{livelike.acs.puma} class is the core
@jvtcl - Sorry for the confusion. I completely misplaced my comment.
I think you made a point in the abstract and on page 5 of the study about conducting validation exercises. These were the lines I was referring to. (We were also
limited to only one month of POI visit data, but we hope
to expand its scope for future validation exercises)

2023-07-01 11:36 UTC, kalyan678 commented on papers/james_gaboardi/paper.tex
> +We first simulated a single synthetic population for the Tallahassee Core-Based Statistical Area (CBSA), based on constraining variables including technical characteristics linked to sampling univers
I apologise for the confusion. It is not my intention to remove the PUMA. The goal is to add the geographical area rather than the code.

2023-07-01 11:47 UTC, kalyan678 commented on papers/james_gaboardi/paper.tex
> +Following the workflow described in Section~\nameref{section:likeness-expansion-scaling}, we demonstrate the current capabilities of Likeness and validate our activity allocation routine for Leon Cou
@jGaboardi Thank you for your clarification. I've seen the specifics, and I believe we're in good hands here :)

2023-07-03 15:50 UTC, jGaboardi commented on papers/james_gaboardi/paper.tex
> +Following the workflow described in Section~\nameref{section:likeness-expansion-scaling}, we demonstrate the current capabilities of Likeness and validate our activity allocation routine for Leon Cou
@jvtcl Please mark as completed.

2023-07-03 18:53 UTC, jvtcl commented on papers/james_gaboardi/paper.tex
> +Each of the three P-MEDM runs (one for each PUMA in the Tallahassee CBSA) resulted in a synthetic reconstruction of the ACS 90\% MOEs that conformed within 99\% of the published MOEs from the ACS SF
> * @jvtcl to address this.

We feel that we don't have enough evidence from this single case study to provide a well-defined reason for why this occurs. A few potential reasons (population density, diversity of travel modes) are provided in the text. We could explore this further in future work by repeating the case study analysis elsewhere.

2023-07-03 18:58 UTC, jvtcl commented on papers/james_gaboardi/paper.tex
> +We found that overall, Likeness approximates travel to non-anchor (grocery store) POIs modestly well. However, contrasted with anchor activities (work/school) demonstrated in \cite{likeness-scipy-pap
@ameyxd We are in favor of leaving the wording here as-is, since we are identifying [confounding factors](https://www.sciencedirect.com/topics/nursing-and-health-professions/confounding-variable) associated with the results of our integrated model.

2023-07-03 18:59 UTC, jvtcl commented on papers/james_gaboardi/paper.tex
> +We found that overall, Likeness approximates travel to non-anchor (grocery store) POIs modestly well. However, contrasted with anchor activities (work/school) demonstrated in \cite{likeness-scipy-pap
Ended up revising this sentence to: "Multiple confounding factors related to data inputs and model assumptions may have affected our results..."

2023-07-03 19:03 UTC, jvtcl commented on papers/james_gaboardi/paper.tex
> +    \item Going forward, we also hope to tighten our assumptions about the feasibility of POI access relative to the various travel modes. For example, in our current assignment process (Figure~\ref{
To address @ameyxd's comment below, I added a few research directions we could investigate, one of them being "behavioral factors (willingness to travel given cost and impedances)". 

I moved the paragraph as recommended here but it feels redundant with this point. @jGaboardi, would you mind looking this over?

2023-07-03 19:11 UTC, jvtcl commented on papers/james_gaboardi/paper.tex
> +Finally -- and at the heart of it all -- expansion and scaling of the Likeness ecosystem led to the development of a new package for common utilities, \texttt{likeness-vitals}, which provides support
I made a runthrough of the manuscript and broke up sentences where possible.

2023-07-03 19:16 UTC, jvtcl commented on papers/james_gaboardi/paper.tex
> +We first simulated a single synthetic population for the Tallahassee Core-Based Statistical Area (CBSA), based on constraining variables including technical characteristics linked to sampling univers
Added the [PUMA name](https://censusreporter.org/profiles/79500US1206300-apalachee-region-outside-leon-county-puma-fl/) as provided by Census.

2023-07-03 19:23 UTC, jvtcl commented on papers/james_gaboardi/paper.tex
> +Agent-based models linking individual behavior to population dynamics are essential for understanding human security and social equity issues within human systems \cite{germann2022assessing, ozik2021
- Generalized "agent-based model" to "synthetic population"
- Changed "human dynamics" -> "population dynamics" to match the text
- Added "microsimulation"

2023-07-03 19:27 UTC, jvtcl commented on papers/james_gaboardi/paper.tex
> +discuss scaling our methods to larger areas of interest, as well as examines the performance of our activity allocation model relative to real-world POI demographics from digital trace data.
I added a brief clarification that this refers to "anonymized mobile device" data.

2023-07-07 17:14 UTC, jGaboardi commented on papers/james_gaboardi/paper.tex
> +Following the workflow described in Section~\nameref{section:likeness-expansion-scaling}, we demonstrate the current capabilities of Likeness and validate our activity allocation routine for Leon Cou
We will retain our `\nameref` format that is compatible with the SciPy proceeding template unless specifically guided to do otherwise.

2023-07-07 20:56 UTC, jGaboardi commented on papers/james_gaboardi/figures/ecosystem.tex
> +\begin{figure*}[htbp]
Although it is a great suggestion, we were unable to accommodate this due to the varying software packages used for generation (as @jvtcl said before).

2023-07-07 20:56 UTC, jGaboardi commented on papers/james_gaboardi/paper.tex
> +The next stage in the workflow employs network analysis to model the cost of travel to these activities \cite{OpenStreetMap, osmnx_CEUS_2017, foti_generalized_2012} and allocate agents to POIs accord
@jvtcl please mark complete

2023-07-07 21:00 UTC, jGaboardi commented on papers/james_gaboardi/paper.tex
> +Figure~\ref{fig:2x2_agents_hex} shows that Leon County's agent population is distributed unevenly relative to assigned travel modes. Because Leon County's infrastructure primarily supports travel by
I spent some time trying to manually place the figures as suggested, but in doing so they both (a) didn't fit properly in the desired space; and (b) completely threw off the typesetting of the other figures & tables. We will leave as is.

* @jvtcl Please mark complete

2023-07-07 21:00 UTC, jGaboardi commented on papers/james_gaboardi/paper.tex
> +The large disparity in problem size seen in Table~\ref{tab:agents_counts_travel_mode} is even more pronounced in solution runtimes, shown in Table~\ref{tab:allocation_solution_runtime}, with optimal
See comment above --> https://github.com/scipy-conference/scipy_proceedings/pull/834#discussion_r1256470229

* @jvtcl Please mark complete

2023-07-07 21:01 UTC, jGaboardi commented on papers/james_gaboardi/paper.tex
> +    \item Going forward, we also hope to tighten our assumptions about the feasibility of POI access relative to the various travel modes. For example, in our current assignment process (Figure~\ref{
We have reworded and the adjusted text is now up in this PR.

* @jvtcl Please mark complete

2023-07-07 21:04 UTC, jGaboardi commented
@ameyxd & @kalyan678 

We (@jvtcl and I) have addressed your comments and implemented your suggestions where possible. Thank you both for the thorough and thoughtful reviews. Your efforts have made this manuscript a much better piece of scholarship.

2023-07-07 21:08 UTC, jGaboardi commented
@scoobies check references

2023-07-07 21:09 UTC, scoobies commented
```
Reference check summary (note 'MISSING' DOIs are suggestions that need verification):

OK DOIs

- 10.1016/j.compenvurbsys.2017.05.004 is OK
- 10.5281/zenodo.7843975 is OK
- 10.5281/zenodo.7768810 is OK
- 10.1162/0899766042321814 is OK
- 10.1007/s12532-017-0130-5 is OK
- 10.1002/sapm1941201224 is OK
- 10.1016/j.tbs.2015.03.002 is OK
- 10.2307/1907301 is OK
- 10.1147/rd.471.0057 is OK
- 10.1016/j.compenvurbsys.2013.03.004 is OK
- 10.1111/gec3.12204 is OK
- 10.1038/ncomms9166 is OK
- 10.25080/majora-212e5952-014 is OK
- 10.25080/majora-212e5952-02d is OK
- 10.6084/m9.figshare.c.6139131.v2 is OK
- 10.1007/s12061-015-9138-2 is OK
- 10.1080/01621459.1972.10481251 is OK

MISSING DOIs

- 10.1016/j.epidem.2022.100632 may be a valid DOI for title: Assessing K-12 school reopenings under different COVID-19 Spread scenarios–United States, school year 2020/21: A retrospective modeling study
- 10.1109/wsc.2018.8632409 may be a valid DOI for title: Chisim: An agent-based simulation model of social interactions in a large urban area
- 10.1109/jstars.2018.2835377 may be a valid DOI for title: Building extraction at scale using convolutional neural network: Mapping of the United States

INVALID DOIs

- https://doi.org/10.1111/gean.12276 is INVALID because of 'https://doi.org/' prefix
- https://doi.org/10.1016/j.apgeog.2022.102844 is INVALID because of 'https://doi.org/' prefix
- 10.2172/1868508 is INVALID
```

2023-07-07 21:23 UTC, jGaboardi commented
@scoobies check references

2023-07-07 21:24 UTC, scoobies commented
```
Reference check summary (note 'MISSING' DOIs are suggestions that need verification):

OK DOIs

- 10.1016/j.compenvurbsys.2017.05.004 is OK
- 10.5281/zenodo.7843975 is OK
- 10.5281/zenodo.7768810 is OK
- 10.1016/j.epidem.2022.100632 is OK
- 10.1162/0899766042321814 is OK
- 10.1007/s12532-017-0130-5 is OK
- 10.1002/sapm1941201224 is OK
- 10.1016/j.tbs.2015.03.002 is OK
- 10.2307/1907301 is OK
- 10.1147/rd.471.0057 is OK
- 10.1016/j.compenvurbsys.2013.03.004 is OK
- 10.1109/wsc.2018.8632409 is OK
- 10.1111/gec3.12204 is OK
- 10.1038/ncomms9166 is OK
- 10.25080/majora-212e5952-014 is OK
- 10.25080/majora-212e5952-02d is OK
- 10.1109/jstars.2018.2835377 is OK
- 10.6084/m9.figshare.c.6139131.v2 is OK
- 10.1007/s12061-015-9138-2 is OK
- 10.1080/01621459.1972.10481251 is OK

MISSING DOIs

- None

INVALID DOIs

- doi.org/10.1111/gean.12276 is INVALID because of 'doi.org/' prefix
- doi.org/10.1016/j.apgeog.2022.102844 is INVALID because of 'doi.org/' prefix
- 10.2172/1868508 is INVALID
```

2023-07-07 21:26 UTC, jGaboardi commented
@scoobies check references

2023-07-07 21:27 UTC, scoobies commented
```
Reference check summary (note 'MISSING' DOIs are suggestions that need verification):

OK DOIs

- 10.1016/j.compenvurbsys.2017.05.004 is OK
- 10.5281/zenodo.7843975 is OK
- 10.5281/zenodo.7768810 is OK
- 10.1016/j.epidem.2022.100632 is OK
- 10.1162/0899766042321814 is OK
- 10.1007/s12532-017-0130-5 is OK
- 10.1002/sapm1941201224 is OK
- 10.1016/j.tbs.2015.03.002 is OK
- 10.2307/1907301 is OK
- 10.1147/rd.471.0057 is OK
- 10.1016/j.compenvurbsys.2013.03.004 is OK
- 10.1109/wsc.2018.8632409 is OK
- 10.1111/gec3.12204 is OK
- 10.1038/ncomms9166 is OK
- 10.1111/gean.12276 is OK
- 10.25080/majora-212e5952-014 is OK
- 10.25080/majora-212e5952-02d is OK
- 10.1016/j.apgeog.2022.102844 is OK
- 10.1109/jstars.2018.2835377 is OK
- 10.6084/m9.figshare.c.6139131.v2 is OK
- 10.1007/s12061-015-9138-2 is OK
- 10.1080/01621459.1972.10481251 is OK

MISSING DOIs

- None

INVALID DOIs

- 10.2172/1868508 is INVALID
```

2023-07-11 02:17 UTC, ameyxd approved these changes
Looks good. Approved! Hope to see you this week @jGaboardi @jvtcl @mepa

2023-07-11 06:14 UTC, kalyan678 approved these changes
@jGaboardi @jvtcl - I'm glad to hear that you found my comments and suggestions helpful. I have reviewed the changes made to the paper, and it appears satisfactory to me. I wish you the best of luck with your paper and future endeavors. Perhaps we will have the opportunity to collaborate again in the future. Enjoy the conference, and although I'll be attending virtually, I hope we can connect and network. Cheers!!
I would like to express my sincere gratitude to the SciPy Team for providing this opportunity. @scoobies @deniederhut @mepa

2023-07-27 14:53 UTC, mepa commented
@scoobies check references

2023-07-27 14:53 UTC, scoobies commented
```
Reference check summary (note 'MISSING' DOIs are suggestions that need verification):

OK DOIs

- 10.1016/j.compenvurbsys.2017.05.004 is OK
- 10.5281/zenodo.7843975 is OK
- 10.5281/zenodo.7768810 is OK
- 10.1016/j.epidem.2022.100632 is OK
- 10.1162/0899766042321814 is OK
- 10.1007/s12532-017-0130-5 is OK
- 10.1002/sapm1941201224 is OK
- 10.1016/j.tbs.2015.03.002 is OK
- 10.2307/1907301 is OK
- 10.1147/rd.471.0057 is OK
- 10.1016/j.compenvurbsys.2013.03.004 is OK
- 10.1109/wsc.2018.8632409 is OK
- 10.1111/gec3.12204 is OK
- 10.1038/ncomms9166 is OK
- 10.1111/gean.12276 is OK
- 10.25080/majora-212e5952-014 is OK
- 10.25080/majora-212e5952-02d is OK
- 10.1016/j.apgeog.2022.102844 is OK
- 10.1109/jstars.2018.2835377 is OK
- 10.6084/m9.figshare.c.6139131.v2 is OK
- 10.1007/s12061-015-9138-2 is OK
- 10.1080/01621459.1972.10481251 is OK

MISSING DOIs

- None

INVALID DOIs

- 10.2172/1868508 is INVALID
```

2023-07-27 14:58 UTC, mepa commented
Hey @jGaboardi, could you please check and resolve the INVALID DOI found by scoobies above? It means that `10.2172/1868508` wasn't found on https://doi.org/.

2023-07-27 15:01 UTC, jGaboardi commented
> Hey @jGaboardi, could you please check and resolve the INVALID DOI found by scoobies above? It means that `10.2172/1868508` wasn't found on https://doi.org/.

Yeah, this was giving us trouble, but it's a real document and the correct DOI. See [thread above](https://github.com/scipy-conference/scipy_proceedings/pull/834#issuecomment-1579057790) which links to [this document](https://science.osti.gov/-/media/Initiatives/pdf/Bioprepardeness_Roundtable_Report_092722.pdf) – DOI is listed on the second page there.

2023-07-27 15:33 UTC, mepa commented
> > Hey @jGaboardi, could you please check and resolve the INVALID DOI found by scoobies above? It means that `10.2172/1868508` wasn't found on https://doi.org/.
> 
> Yeah, this was giving us trouble, but it's a real document and the correct DOI. See [thread above](https://github.com/scipy-conference/scipy_proceedings/pull/834#issuecomment-1579057790) which links to [this document](https://science.osti.gov/-/media/Initiatives/pdf/Bioprepardeness_Roundtable_Report_092722.pdf) – DOI is listed on the second page there.

Great, thanks for the links!

2023-07-27 15:33 UTC, mepa commented
@scoobies mark ready

2023-08-05 22:35 UTC, deniederhut approved these changes
Thanks @ameyxd and @kalyan678 for helping us review this paper for the conference!

![Thank-You-gif-Free-882682437](https://github.com/scipy-conference/scipy_proceedings/assets/6868396/2fa5aea9-d55c-4d13-beac-6733e9118a7b)

2023-08-05 22:35 UTC, merged

2023-08-06 16:57 UTC, jGaboardi commented
Thanks again everyone for all the great work. Without this time and effort our community wouldn't exist.

2023-08-06 18:38 UTC, kalyan678 commented
> Thanks @ameyxd and @kalyan678 for helping us review this paper for the conference!
> 
> ![Thank-You-gif-Free-882682437](https://user-images.githubusercontent.com/6868396/258611124-2fa5aea9-d55c-4d13-beac-6733e9118a7b.gif)

Thank you again for the opportunity. I look forward to contributing much more in the coming days!

Cheers Everyone :)

2023-08-07 15:33 UTC, ameyxd commented
It was great working with you, and nice to meet you @jGaboardi and @jvtcl! 

@deniederhut hope to see you around town in Houston, and happy to help for next year. ✌️

2023-08-08 00:55 UTC, deniederhut commented
I politely request that we wait until it cools down a bit before grabbing a beer 😅. And yes, @jGaboardi always has great stuff to share!