Chalk'it IFPEN poster proposal
scipy-conference/scipy_proceedings pull request #839
Opened 2023-06-28 01:40 UTC by bengaid

If you are creating this PR in order to submit a draft of your paper,
see http://procbuild.scipy.org/ for logs generated by the build
process.

See the [project readme](https://github.com/scipy-conference/scipy_proceedings#build-your-paper)
for more information.

*Editor*:  

*Reviewers*:

2023-06-28 07:57 UTC, bengaid commented
Update a link for the virtual poster as living website

2023-07-09 22:07 UTC, deniederhut requested changes
Please do not modify files outside of your own poster's directory

2023-07-09 22:08 UTC, deniederhut commented on presentations/posters/poster - Chalk’it dataflow and drag-and-drop Python dashboarding/README.md
> +Please visit <https://ifpen.github.io/chalk-it/> for living demo
This won't be visible to anyone. Would it make more sense to add it to the PDF?

2023-07-10 11:32 UTC, bengaid commented on presentations/posters/poster - Chalk’it dataflow and drag-and-drop Python dashboarding/README.md
> +Please visit <https://ifpen.github.io/chalk-it/> for living demo
Is it possible to use this website <https://ifpen.github.io/chalk-it/> as virtual poster, instead of the pdf ?

2023-07-10 23:54 UTC, deniederhut commented on presentations/posters/poster - Chalk’it dataflow and drag-and-drop Python dashboarding/README.md
> +Please visit <https://ifpen.github.io/chalk-it/> for living demo
For the conference itself I believe you are pretty unrestricted as to format. For archiving though (in the proceedings) we need a single file we can submit to Zenodo.

2023-07-11 13:04 UTC, bengaid commented on presentations/posters/poster - Chalk’it dataflow and drag-and-drop Python dashboarding/README.md
> +Please visit <https://ifpen.github.io/chalk-it/> for living demo
OK, in that case I will remove the README.md. Only the pdf would be to include in the proceedings

2023-07-11 13:12 UTC, bengaid commented
Pull request following review guidelines.

Hope it is fine now.

2023-07-14 20:58 UTC, deniederhut commented
I still see that you have deleted files outside of your poster directory?

<img width="276" alt="Screenshot 2023-07-14 at 3 56 04 PM" src="https://github.com/scipy-conference/scipy_proceedings/assets/6868396/38a37d27-f188-40f7-b56d-4a26e8956b54">

2023-07-26 01:12 UTC, deniederhut commented
@scoobies mark not ready

2023-08-05 22:35 UTC, closed without merging