Update readme with author workflow feedback
scipy-conference/scipy_proceedings pull request #898
Opened 2024-05-03 15:20 UTC by mepa

Changes to the author workflow steps based on feedback after performing a test paper submission.
Also adds a note for authors interested in submitting computational notebook(s) along with their paper on a trial basis for 2024.

2024-05-03 15:58 UTC, cbcunc requested changes

2024-05-03 15:58 UTC, cbcunc commented on README.md
> +git clone <scheme>github.com/<username>/scipy_proceedings
```suggestion
git clone <scheme>github.com/<username>/scipy_proceedings.git
```

2024-05-03 15:58 UTC, cbcunc commented on README.md
>     - If you want to alter the build system, do not include it in your
Please add text to the effect of
> Creating build system PRs is deprecated in 2024. Curvenote is the build system now.

Both here and at <#creating-build-system-prs>

2024-05-03 15:58 UTC, cbcunc commented on README.md
> +  - `git clone <scheme>github.com/<username>/scipy_proceedings`
```suggestion
  - `git clone <scheme>github.com/<username>/scipy_proceedings.git`
```

2024-05-03 16:24 UTC, mepa commented on README.md
>     - If you want to alter the build system, do not include it in your
Added the text to both places while also leaving the `dev` branch process instructions in case authors want to make changes to other areas in the scipy_proceedings repo. How does that look?

2024-05-07 17:18 UTC, rowanc1 commented on README.md
>  #### Author workflow steps
```suggestion
#### Author workflow steps

> [!NOTE]
> There is a [webinar on YouTube](https://www.youtube.com/watch?v=v97nJOCAWHI) that goes through the author submission process for 2024 submissions using [MyST Markdown](https://mystmd.org).

```

2024-05-07 17:18 UTC, rowanc1 commented on README.md
>  #### Author workflow steps
This looks like:

> [!NOTE]
> There is a [webinar on YouTube](https://www.youtube.com/watch?v=v97nJOCAWHI) that goes through the author submission process for 2024 submissions using [MyST Markdown](https://mystmd.org).

2024-05-07 17:32 UTC, rowanc1 commented on README.md
> +- Ensure that your PR title begins with `Paper:`.
I think this would be good to do here, the first process is manual: the editor should check (1) that the author was indeed invited to submit; (2) add the `paper` label; (3) rerun the github actions.

```suggestion
- Ensure that your PR title begins with `Paper:`. Note: for the **first** commit in your PR, an editor will add the `paper` label, which will start the GitHub actions.
```

2024-05-07 17:39 UTC, mepa commented on README.md
>     - If you want to alter the build system, do not include it in your
Changes discussed/approved during proceedings committee meeting

2024-05-07 17:45 UTC, merged