Gagnon keke tahiri 2024
scipy-conference/scipy_proceedings pull request #907
Opened 2024-05-25 19:35 UTC by JustGag

If you are creating this PR in order to submit a draft of your paper, please name your PR with `Paper: <title>`. An editor will then add a `paper` label and GitHub Actions will be run to check and build your paper.

See the [project readme](https://github.com/scipy-conference/scipy_proceedings#preview-your-paper) for more information.

_Editor_:  

_Reviewers_:

2024-05-27 08:11 UTC, stevejpurves commented on papers/Gagnon_Keke_Tahiri_2024/myst.yml
> +  id: scipy-2024-00_tex_template
@JustGag if you update your `id` as described in the comment this should get the submission check action running as expected

2024-05-27 08:12 UTC, stevejpurves commented on myst.yml
> +# See docs at: https://mystmd.org/guide/frontmatter
@JustGag seems like this file was added in error, best to remove it asap to avoid confusion on your local machine. It should definitely be removed prior to merging.

2024-05-27 12:10 UTC, rowanc1 requested changes
Hi @JustGag, could you please make a few changes to your PR for the preview to run?

- [ ] delete top level `myst.yml`
- [ ] remove changes to presentations folder
- [ ] Rename folder to remove `_2024` (all of the submissions in the folder will be for 2024!)
- [ ] Update `myst.yml` ID to match folder name (follow instructions in the comment)

Let us know if you need any help. Thanks!

2024-05-27 12:10 UTC, rowanc1 commented on presentations/lightning/example/.JOSE-lightning-talk.pdf.icloud
Could you please remove the changes to this folder and restore the original PDF?

2024-05-27 12:10 UTC, rowanc1 commented on papers/Gagnon_Keke_Tahiri_2024/myst.yml
> +  id: scipy-2024-00_tex_template
Please update this to an ID similar to, which should match the folder name!

```suggestion
  id: scipy-2024-gagnon_keke_tahiri
```

2024-05-27 12:10 UTC, rowanc1 commented on myst.yml
> +# See docs at: https://mystmd.org/guide/frontmatter
Please remove this file!

2024-05-30 21:32 UTC, hongsupshin commented
@JustGag @TahiriNadia Hi there, it seems like your team has created another PR https://github.com/scipy-conference/scipy_proceedings/pull/910 which seems to be a duplicate of this paper. If you're going to use the new PR, could you close this with your comment that confirms the decision, and modify the title of the new PR please?

2024-05-30 22:29 UTC, closed without merging

2024-05-30 22:29 UTC, JustGag commented
Error