Paper: AI Model Share -   subtitle: An Integrated Toolkit for Collaborative Machine Learning Model Development, Provenance Tracking, and Deployment in Python
scipy-conference/scipy_proceedings pull request #911
Opened 2024-05-30 18:35 UTC by hp2500

If you are creating this PR in order to submit a draft of your paper, please name your PR with `Paper: <title>`. An editor will then add a `paper` label and GitHub Actions will be run to check and build your paper.

See the [project readme](https://github.com/scipy-conference/scipy_proceedings#preview-your-paper) for more information.

_Editor_:  

_Reviewers_:

2024-05-30 20:24 UTC, rowanc1 commented
Hi @hp2500, thank you for your submission! Could you please restore the two templates (you have deleted those folders) so that your changes are only in the single folder (if this is easier to open a new PR, that is fine to, and we can close this one).

2024-05-30 20:25 UTC, rowanc1 commented on myst.yml
> +# See docs at: https://mystmd.org/guide/frontmatter
Can you also please remove this file, we only need the changes inside of your folder!

2024-05-30 20:37 UTC, hp2500 commented on myst.yml
> +# See docs at: https://mystmd.org/guide/frontmatter
Thanks for catching this. I think my latest commit should have fixed it.

2024-05-30 20:52 UTC, rowanc1 commented on myst.yml
> +# See docs at: https://mystmd.org/guide/frontmatter
Perfect, preview is up, looks great! I am still waiting on hearing back from the other proceeding chairs on the supporting document, but seeing it in there is helpful for everyone to get an understanding of it! (This is the first year we have focused on the web/html view rather than print only, so still making some editorial decisions!)

2024-05-31 21:51 UTC, hongsupshin commented
@hp2500 Hi Heinrich, thanks for your submission! I have a few questions about the supporting material you submitted. It seems like the main manuscript doesn’t refer the supporting material, and I am wondering what its purpose is. 

It also seems that the supporting material includes screenshots of your software and I would really appreciate what value they have regarding the manuscript. We would like the authors to be judicious about the use of supporting material because it is an extra burden for everyone including reviewers and proceeding chairs. 

If you can answer these questions, I would really appreciate it!

2024-05-31 22:16 UTC, hp2500 commented
Hi @hongsupshin , thanks for checking in!

We are referring to the SI in the manuscript. However, we had to manually include the references bc the \ref{} links didn't seem to work across documents. I am happy to add additional references wherever it might be useful.

The screenshots are indeed examples of the different functionalities of our software. We felt like a pure description might be a bit dry, so we tried to give the reader a better idea of what the different components look like. If you feel strongly about this I can remove the SI or attach the most important pieces to the main document. Alternatively, I can upload the SI to a separate repo and simply provide a link for those who are curious. 

Your guidance is much appreciated. Maybe the reviewers want to chime in on this, too? 

On a different note, can I continue to update the PR as we go or should I refrain from making changes before the reviewer's feedback is in?

2024-06-01 16:07 UTC, hongsupshin reviewed
@hp2500 Thanks for the prompt reply! (I am moving the conversation as a formal review)

Regarding the supporting material in general, I went to your website and I was wondering whether your team has online examples of the figures you shared in the supporting material. If this is the case, you can probably just cite the online material, which might be more useful then static figures (because it would be interactive and especially since you have many tutorials). 

If this already exists, you can consider this suggestion. But if it doesn't and you have to create additional material, let's just keep the supporting material with figures as is. I made a comment about one of the figures in the SI, so take a look and see if it makes sense. Thank you!

2024-06-01 16:07 UTC, hongsupshin commented on papers/heinrich_peters/figures/model.png
I think this figure has relatively low value and textual description might be enough.

2024-06-01 16:09 UTC, hongsupshin commented
> On a different note, can I continue to update the PR as we go or should I refrain from making changes before the reviewer's feedback is in?

We haven't assigned the reviewers yet, and it's likely that we will continue accepting papers until the end of next week, please keep updating your PR if needed!

2024-06-20 02:19 UTC, hongsupshin commented on papers/heinrich_peters/figures/model.png
@hp2500 Hi there, I haven't heard from you fore the last 3 weeks. Are you still working on the manuscript?

2024-06-20 02:19 UTC, hongsupshin commented
> > On a different note, can I continue to update the PR as we go or should I refrain from making changes before the reviewer's feedback is in?
> 
> We haven't assigned the reviewers yet, and it's likely that we will continue accepting papers until the end of next week, please keep updating your PR if needed!

We have reviewers assigned to this paper @hp2500 We haven't heard from you for the past 3 weeks. Can you give us an update about the status of the paper?

2024-06-20 03:56 UTC, hp2500 commented
> > > On a different note, can I continue to update the PR as we go or should I refrain from making changes before the reviewer's feedback is in?
> > 
> > 
> > We haven't assigned the reviewers yet, and it's likely that we will continue accepting papers until the end of next week, please keep updating your PR if needed!
> 
> We have reviewers assigned to this paper @hp2500 We haven't heard from you for the past 3 weeks. Can you give us an update about the status of the paper?

My apologies, @hongsupshin - I didn't realize you were holding off on reviews because of my comment. The paper has been ready since my latest commit.
By all means, feel free to start the review process. I would like to get it done without further delay and I am looking forward to the comments!

2024-06-25 01:42 UTC, ankurankan commented
Hi everyone, I am one of the reviewers. I have had a first look at the paper, and I believe it is already in very good shape. I have only a few minor comments as outlined below:

1. In the "Introduction" and "Related Work" sections, the authors mention that current existing tools are difficult to use and have a high barrier to entry, but do not provide any reasoning behind why this is the case and what exactly the main pain points are. I think adding the reasons explicitly (or a table of features) would make the argument stronger and also help in highlighting the features of AIMS.
2. There appears to be a typo in the "Collaborative Model Development" section at: "standardized leaderboards Experiments and Competitions." It seems there might be a missing period.
3. Writing class and function names such as ModelPlayground, input_type, etc., in italics would improve readability.

2024-06-27 01:11 UTC, hongsupshin commented
@ankurankan Hi, would you mind leaving the comments directly on the corresponding file? You can press the + button to leave a comment and this will start a former review.

2024-06-27 14:39 UTC, ankurankan commented on papers/heinrich_peters/main.tex
> +Machine learning (ML) is revolutionizing a wide range of research areas and industries, providing data-driven solutions to important societal problems. However, researchers and practitioners lack eas
This paragraph mentions that the current existing tools are difficult to use and have a high barrier to entry, but do not provide any reasoning behind why this is the case and what exactly the main pain points are. I think adding the reasons explicitly (or a table of features) would make the argument stronger and also help in highlighting the features of AIMS.

2024-06-27 14:39 UTC, ankurankan commented on papers/heinrich_peters/main.tex
> +\paragraph{Collaborative Model Development} A key feature of AIMS is its focus on collaborative model development and crowd-sourced model improvement, enabling teams to iterate quickly by allowing co
"standardized leaderboards Experiments and Competitions." It seems there might be a missing period.

2024-06-27 14:39 UTC, ankurankan commented on papers/heinrich_peters/main.tex
> +AIMS consists of three main components: an open-source Python library, user-owned cloud backend resources, and the AIMS website. The AIMS Python library is the main interface allowing users to set up
Writing class and function names such as ModelPlayground, input_type, etc., in italics would improve readability.

2024-07-14 22:44 UTC, cbcunc commented
@AmadiGabriel Good to meet you at SciPy. I am inviting you to review this paper. You were sent an invitation from GitHub to be a collaborator on this repository. Please accept the invitation. Your review should be in the form of GitHub review comments: https://docs.github.com/en/pull-requests/collaborating-with-pull-requests/reviewing-changes-in-pull-requests/commenting-on-a-pull-request

2024-07-21 23:12 UTC, AmadiGabriel requested changes
In a bid to democratising ML ecosystem and expanding it non-technical disciplines, AIMS is a laudable initiative which introduces a promising approach to addressing to ease-of-use toolkit for collaborative ML model development and deployment.

2024-07-21 23:12 UTC, AmadiGabriel commented on papers/heinrich_peters/main.tex
> +Machine learning (ML) is revolutionizing a wide range of research areas and industries, but many ML projects never progress past the proof-of-concept stage. To address this problem, we introduce Mode
"but many ML projects never progress past the proof-of-concept stage."
_The author has not concretely justified that ModelAI will ensure ML project advance beyond proof-of-concept stage. This could be the concluding sentence of the abstract if this was addressed._

"Furthermore, AIMS allows users to deploy ML models built in Scikit-Learn, TensorFlow Keras, PyTorch, and ONNX into live REST APIs and automatically generated web apps with minimal code."
_This statement can be rephrased to exclude the overuse of 'and'._

2024-07-21 23:12 UTC, AmadiGabriel commented on papers/heinrich_peters/main.tex
> +Machine learning (ML) is revolutionizing a wide range of research areas and industries, providing data-driven solutions to important societal problems. However, researchers and practitioners lack eas
"However, researchers and practitioners lack easy-to-use, structured pathways to collaboratively develop and rapidly deploy ML models. Traditionally, researchers have been using version-control systems like GitHub in combination with custom model evaluation and benchmarking experiments to ensure reproducibility and to compare models"

_The second sentence should precede the first and possibly then specify the limitation of version-control systems._

_you may wish to end the introduction by highlighting other subsections (e.g' the rest of the paper is as follows: related works is ... section two, model share AI is described in section three ... etc)_

_You may want to maintain some consistency, either use Model Share AI or AIMS._

2024-07-21 23:12 UTC, AmadiGabriel commented on papers/heinrich_peters/main.tex
> +\section{Related Work}
_I think 'work' should be plural._

2024-07-21 23:12 UTC, AmadiGabriel commented on papers/heinrich_peters/main.tex
> +Despite these important developments, there is a lack of open-source technologies providing users a simple, centralized way to find, analyze, download, and collaboratively improve trained ML models s
_there is an overuse of 'and' in this section and other sections of the paper. Could you do another review as this makes statements a bit convoluted._

"ease of use"
_you used it in this form in another section - 'ease-of-use', you may want to maintain consistency_

"With a strong focus on ease of use, AIMS provides a simple, yet versatile approach to these challenges."

_I believe you meant '...to addressing these challenges'_

2024-07-21 23:12 UTC, AmadiGabriel commented on papers/heinrich_peters/main.tex
> +\begin{figure}
_Figure 1 was not cross-referenced in the text. Kindly cross-reference all figures in the appropriate sections in the text._

_Instead of a model playground, could you provide a schematic that captures the entire workflow of AIMS? Where possible include, model evaluation, task types and public/private flow process._

2024-07-21 23:12 UTC, AmadiGabriel commented on papers/heinrich_peters/main.tex
> +\paragraph{Collaborative Model Development} A key feature of AIMS is its focus on collaborative model development and crowd-sourced model improvement, enabling teams to iterate quickly by allowing co
"(see section below)."

_you could consider including section numbering on the yaml file so that cross-referencing can be easily done as in this case._

2024-07-21 23:12 UTC, AmadiGabriel commented on papers/heinrich_peters/main.tex
> +\paragraph{Collaborative Model Development} A key feature of AIMS is its focus on collaborative model development and crowd-sourced model improvement, enabling teams to iterate quickly by allowing co
_Model evaluation is a key requirement for AIMS. increasingly, real life datasets are characterised by class-imbalance, with AUC considered a reliable metric for such dataset. Also, exclusion of artificially inflated performance scores, Adjusted R-2 may be more useful for competitions. Could this be considered for inclusion as part of the 'out of the box'?_

_Some clarifications to consider including in the text:
In the leadership board, which of the evaluation metrics takes precedence when the values are inconsistent. E.g. when MSE for version 1 is better than version 2, but R2 is otherwise?_

_How does AIMS account for randomness in algorithms and data-resampling in inspecting improvement on models?_

2024-07-21 23:12 UTC, AmadiGabriel commented on papers/heinrich_peters/main.tex
> +\paragraph{Instant Model Deployment} AIMS currently allows users to deploy ML models built in Scikit-Learn \citep{pedregosa_scikit-learn:_2011}, Tensorflow Keras \citep{abadi_tensorflow_2016, chollet
"into live rest APIs"
_capitalise 'REST'_

"ONNX (Open Neural Network Exchange) format"
_this could be introduced in the abstract and used consistently as an abbreviation, rather than the other way around._

2024-07-21 23:12 UTC, AmadiGabriel commented on papers/heinrich_peters/main.tex
> +Once a Model Playground Page is created, users can start submitting models to Experiments or Competitions and deploy models into the Model Playground’s REST API. A model submission includes a model o
"Detailed tutorials and documentation can be found in SI A."
_could you cross-reference this using a hyperlink and write it out in full?_

2024-07-21 23:12 UTC, AmadiGabriel commented on papers/heinrich_peters/main.tex
> +With its focus on ease of use, AIMS is uniquely positioned to realize several important missions with regard to model deployment. First, simplifying model deployment is essential because it lowers ba
_This should read 'firstly, and secondly' respectively._

_this would be a good place to justify the introductory  statement in the abstract which referred to 'projects never progressing past the proof-of-concept stage._

2024-07-21 23:12 UTC, AmadiGabriel commented on papers/heinrich_peters/main.tex
> +While AIMS provides a greatly simplified approach to collaborative model development and deployment, there are opportunities for further improvements. Firstly, it is important to strike the right bal
"This includes making the platform compatible with more advanced model types, task types, and ML frameworks. "
_It would be worth mentioning one or two examples here_

2024-07-21 23:12 UTC, AmadiGabriel commented on papers/heinrich_peters/main.tex
> +AIMS provides a versatile yet easy-to-use approach to collaborative model development, model metadata analytics, and model deployment. AIMS enables users to quickly find, analyze, download, and colla
"Compared to existing solutions, AIMS significantly lowers the barriers of entry to ML research, making it attractive to a large group of researchers, educators, and data scientists."

_I struggle to reconcile if AIMS is aimed at being made useful to non-technical users or if it is just making the deployed models available to non-technical users.
Could this be clarified in the paper?_

2024-07-21 23:12 UTC, AmadiGabriel commented on papers/heinrich_peters/main.tex
> +\section*{Acknowledgments}
_Could you use the CRediT provided by CurveNote in the yaml file or was this not sufficient?_

2024-07-26 18:32 UTC, cdlindsey commented
I would like to see more details on the support of experiments.  Can you store certain metrics?

2024-08-02 20:18 UTC, hp2500 commented on papers/heinrich_peters/main.tex
> +Machine learning (ML) is revolutionizing a wide range of research areas and industries, providing data-driven solutions to important societal problems. However, researchers and practitioners lack eas
Thank you for this suggestion. We have added a paragraph to the related work section, that explains how AIMS fits uniquely into the ecosystem of existing solutions.

2024-08-02 20:18 UTC, hp2500 commented on papers/heinrich_peters/main.tex
> +\paragraph{Collaborative Model Development} A key feature of AIMS is its focus on collaborative model development and crowd-sourced model improvement, enabling teams to iterate quickly by allowing co
Thank you for catching this. Fixed.

2024-08-02 20:18 UTC, hp2500 commented on papers/heinrich_peters/main.tex
> +AIMS consists of three main components: an open-source Python library, user-owned cloud backend resources, and the AIMS website. The AIMS Python library is the main interface allowing users to set up
This is a good suggestion. We have changed the manuscript accordingly.

2024-08-02 20:20 UTC, hp2500 commented on papers/heinrich_peters/main.tex
> +Machine learning (ML) is revolutionizing a wide range of research areas and industries, but many ML projects never progress past the proof-of-concept stage. To address this problem, we introduce Mode
Thank you for this suggestion. 
1) We have adjusted the concluding sentence. 
2) We have rephrased the sentence and removed "and".

2024-08-02 20:22 UTC, hp2500 commented on papers/heinrich_peters/main.tex
> +\section{Related Work}
Thank you for this observation. Since this refers to an overall body of work, we would prefer the more common singular.

2024-08-02 20:24 UTC, hp2500 commented on papers/heinrich_peters/main.tex
> +Despite these important developments, there is a lack of open-source technologies providing users a simple, centralized way to find, analyze, download, and collaboratively improve trained ML models s
In response to your comment, we have removed several occurrences of the word “and”.

We now consistently use “ease of use” without hyphens.

"I believe you meant '...to addressing these challenges'"
Thank you for catching this. We have rephrased this paragraph, so the original formulation has been replaced.

2024-08-02 20:24 UTC, hp2500 commented on papers/heinrich_peters/main.tex
> +\begin{figure}
Thank you for catching this. We now reference all figures in the text.

2024-08-02 20:26 UTC, hp2500 commented on papers/heinrich_peters/main.tex
> +Machine learning (ML) is revolutionizing a wide range of research areas and industries, providing data-driven solutions to important societal problems. However, researchers and practitioners lack eas
Thank you for this suggestion. We have adjusted the related work section to explains how AIMS uniquely fit into the ecosystem of existing solutions.

2024-08-02 20:29 UTC, hp2500 commented on papers/heinrich_peters/main.tex
> +\begin{figure}
Thank you for catching this. We now reference all figures in the text.

Thank you for your suggestion regarding ModelPlaygrounds. We include an overview of the AIMS workflow in Figures 3 and 4. While Figure 3 provides a high-level overview, Figure 4 includes the requested details (i.e., public vs private; evaluation, etc). At the same time. we believe it is helpful to see a separate overview of the different aspects of model playgrounds (the whole platform is structured around model playgrounds) at a glance, which is why we included Figure 1. In the absence of very strong objections on your end, we would prefer to keep the original figures.

2024-08-02 20:31 UTC, hp2500 commented on papers/heinrich_peters/main.tex
> +\paragraph{Collaborative Model Development} A key feature of AIMS is its focus on collaborative model development and crowd-sourced model improvement, enabling teams to iterate quickly by allowing co
This is a good suggestion. However, we have not seen any other papers use numbered titles and we did not find an option for numbered headers in the yaml file. Are there any official guidelines on this?

2024-08-02 20:38 UTC, hp2500 commented on papers/heinrich_peters/main.tex
> +\paragraph{Collaborative Model Development} A key feature of AIMS is its focus on collaborative model development and crowd-sourced model improvement, enabling teams to iterate quickly by allowing co
Re class imbalances: We wholeheartedly agree that this would be useful. Currently we use F1 scores as a metric that considers class imbalances. However, we agree that AUC should be added in the future.

Re leaderborad: This is a good observation. Users can order the leaderboard by any metric they specify. We have added a clarification in the text. 

Re randomness: Splits are performed by the user before setting up a model playground. Once this is done, contributors are free to manipulate the training set however they wish as the test data will remain constant. For users who wish to share random seeds and aspects of their training environment we recommend using “export_reproducibility_env()” to export this information to a json file that can be passed to the submit_model() method.

2024-08-02 20:39 UTC, hp2500 commented on papers/heinrich_peters/main.tex
> +\paragraph{Instant Model Deployment} AIMS currently allows users to deploy ML models built in Scikit-Learn \citep{pedregosa_scikit-learn:_2011}, Tensorflow Keras \citep{abadi_tensorflow_2016, chollet
Thank you for catching this. We have fixed the spelling of REST. 
We now spell out the first instance of each abbreviation in the abstract and the main manuscript. After that we now consistently use the abbreviation.

2024-08-02 20:42 UTC, hp2500 commented on papers/heinrich_peters/main.tex
> +While AIMS provides a greatly simplified approach to collaborative model development and deployment, there are opportunities for further improvements. Firstly, it is important to strike the right bal
Good point! We’ve added PySpark as an example.

2024-08-02 20:42 UTC, hp2500 commented on papers/heinrich_peters/main.tex
> +AIMS provides a versatile yet easy-to-use approach to collaborative model development, model metadata analytics, and model deployment. AIMS enables users to quickly find, analyze, download, and colla
Thnak you for pointing this out. Our goal is both. We want researchers with a basic understanding of python from all disciplines to be able to utilize AIMS to share their models with the world. Furthermore, we want non-technical end users to be able to interact with models through auto-generated web apps. We have made this more clear in the manuscript, especially at the end of the “Related Work” section.

2024-08-02 20:43 UTC, hp2500 commented on papers/heinrich_peters/main.tex
> +\section*{Acknowledgments}
We specify CRediT roles in the yaml file. However, it was also important to us to give a more detailed account of the contributions and thank our supporters, which is why we added the acknowledgments section. We have removed the CRediT roles from the acknowledgments section in order to avoid duplication.

2024-08-02 21:13 UTC, hp2500 commented on papers/heinrich_peters/main.tex
> +With its focus on ease of use, AIMS is uniquely positioned to realize several important missions with regard to model deployment. First, simplifying model deployment is essential because it lowers ba
We have adjusted the wording (firstly, and secondly) in line with your suggestion.
We also now refer back to "progressing past proof of concept". 
Thank you for the hint!

2024-08-02 21:37 UTC, hp2500 commented on papers/heinrich_peters/main.tex
> +Once a Model Playground Page is created, users can start submitting models to Experiments or Competitions and deploy models into the Model Playground’s REST API. A model submission includes a model o
We were not able to get the cross-reference with hyperlinks across documents to work in the myst version of latex, but we now spell out SI as Supplementary Information.

2024-08-02 22:26 UTC, hp2500 commented on papers/heinrich_peters/main.tex
> +Machine learning (ML) is revolutionizing a wide range of research areas and industries, providing data-driven solutions to important societal problems. However, researchers and practitioners lack eas
"The second sentence should precede the first and possibly then specify the limitation of version-control systems."
In line with the recommendation we have changed the order of the sentences and elaborated more on the limitations of traditional systems.

"you may wish to end the introduction by highlighting other subsections (e.g' the rest of the paper is as follows: related works is ... section two, model share AI is described in section three ... etc)"
Thank you for this recommendation. We have added the requested sentence. 

"You may want to maintain some consistency, either use Model Share AI or AIMS."
Thank you for pointing this out. We now spell out the name on the first occurrence and only use AIMS for the remainder of the manuscript.

2024-08-06 06:31 UTC, AmadiGabriel commented
> @AmadiGabriel Good to meet you at SciPy. I am inviting you to review this paper. You were sent an invitation from GitHub to be a collaborator on this repository. Please accept the invitation. Your review should be in the form of GitHub review comments: https://docs.github.com/en/pull-requests/collaborating-with-pull-requests/reviewing-changes-in-pull-requests/commenting-on-a-pull-request

@cbcunc The authors have made further improvements on the paper based on my comments. Kindly proceed with subsequent stages of the review process.

2024-08-07 02:16 UTC, hp2500 commented
> I would like to see more details on the support of experiments. Can you store certain metrics?

I am not sure I fully understand this question. The metrics are stored and can be queried by users through the Python library or on the AIMS website. In case you mean additional metrics, there is the possibility of submitting a dictionary of key-value pairs to the "custom_metadata" argument of the "submit_model" method.

2024-08-07 02:21 UTC, hp2500 commented
> I would like to see more details on the support of experiments. Can you store certain metrics?

The metrics are stored and can be queried by users through the Python library or on the AIMS website. In case you mean additional metrics, there is the possibility of submitting a dictionary of key-value pairs to the "custom_metadata" argument of the "submit_model" method. We now mention this in the "AIMS Workflow" section.

2024-09-05 14:40 UTC, hongsupshin approved these changes

2024-09-25 17:11 UTC, merged