Paper: Supporting Greater Interactivity in the IPython Visualization Ecosystem
scipy-conference/scipy_proceedings pull request #912
Opened 2024-05-30 19:23 UTC by WarmCyan

If you are creating this PR in order to submit a draft of your paper, please name your PR with `Paper: <title>`. An editor will then add a `paper` label and GitHub Actions will be run to check and build your paper.

See the [project readme](https://github.com/scipy-conference/scipy_proceedings#preview-your-paper) for more information.

_Editor_:  

_Reviewers_:

2024-05-30 20:12 UTC, rowanc1 commented on papers/nathan_martindale/myst.yml
> +        - https://www.energy.gov/doe-public-access-plan
I think that this is correct, but it doesn't seem to be working! I can try and investigate in the next day or so.

2024-05-30 22:29 UTC, fwkoch commented on papers/nathan_martindale/myst.yml
> +        - https://www.energy.gov/doe-public-access-plan
Yes, this is correct - the `link-resolves` check just isn't actually respecting these rules...

Keep this as-is, I'll fix up the check, then it should go green!

2024-05-31 07:39 UTC, rowanc1 commented on papers/nathan_martindale/myst.yml
> +        - https://www.energy.gov/doe-public-access-plan
Rerunning the checks made them go green! ✅ Thanks @fwkoch.

2024-07-02 08:49 UTC, ktzhao commented
It is a pleasure to review your paper. I have thoroughly enjoyed reading your work and find it innovative.

The paper follows a logical flow, explaining the importance of interactive visualization, the limitations of IPyWidgets, the benefits of IPyVuetify, and finally introducing IPyOverlay as a solution. It explains IPyWidgets, IPyVuetify, and how IPyOverlay addresses their limitations. The example use case effectively illustrates the library's practical application.

However, I noticed that some sentences are a little complex and may cause confusion for some readers. Simplifying these sentences by breaking them down into smaller parts could enhance readability and ensure that your key points are communicated clearly to a wider audience.

For instance,  in the Introduction section, the sentence: 
"This ability to interact with and visualize data plays a crucial role in many data science/analysis workflows by allowing users to manipulate and explore, thus enhancing comprehension, improving user engagement, and often providing a faster route to an intuitive understanding of the data."

Could be revised to:
“Interacting with and visualizing data is crucial in many data science /analysis workflows. It allows users to manipulate and explore data, which enhances understanding, improves engagement, and often leads to a quicker intuitive grasp of the data.”

Similarly, in the IPyWidgets section:
"Although there are limitations to using IPyWidgets alone, this library brings a lot of value to the scientific Python community and the data science Jupyter workflow with its ability to marry the two language ecosystems, each of which include many visualization tools and capabilities."

Could be revised to:
"IPyWidgets has limitations, but it's still a valuable tool for the scientific Python community and data science Jupyter workflows. It allows us to combine two language ecosystems with many visualization tools and capabilities."

2024-07-09 04:14 UTC, ritwit commented
The paper looks good to me. The writing is clear and concise. I can appreciate the utility of IPyOverlay.

I am not an expert in visualizations. But should there be more details on the implementation of the library? 

There is a minor rendering issue in the caption of `code 4`.

2024-07-13 23:53 UTC, cbcunc commented
> However, I noticed that some sentences are a little complex and may cause confusion for some readers. Simplifying these sentences by breaking them down into smaller parts could enhance readability and ensure that your key points are communicated clearly to a wider audience.

@ktzhao @ritwit If you would please, add line by line suggestions per the GitHub PR review process: https://docs.github.com/en/pull-requests/collaborating-with-pull-requests/reviewing-changes-in-pull-requests/commenting-on-a-pull-request

2024-07-16 01:31 UTC, JuanCab requested changes
This paper was genuinely interesting to read.  I had run into this issue of trying to have a matplotlib widget respond to show an inset of the region clicked, the authors went ahead and developed a solution! 

I like the fact that this paper doesn't try to operate in a vacuum by presenting IPyOverlay alone as a completed project. Instead, it provides a sufficient background into iPyWidgets, the challenges of details-on-demand GUI design presented by iPyWidgets and the development of both iPyVuetify and finally iPyOverlay as solutions to this GUI design goal.  This helps the reader really grasp not only what iPyOverlay is adding to the iPyWidgets ecosystem but also why those features are truly important for the development of better data exploration tools.

**Prose issues addressed in individual comments** 

The only consistent flaw in the prose in this paper is that the draft presented has a tendency toward wordy and run sentences.  In many cases, the run on sentence could easily have been broken up into distinct sentences, each presenting a distinct idea.  I tried to note as many of those wordy and run on sentences in the comments of my review.

**Prose issues not noted in individual comments** 

I did also run *proselint* on the existing draft and it caught 3 real issues, only one of which are likely worth addressing.  The correction worth addressing:

1. In line 148 of main.md: *proselint* suggests 'interact' instead of 'interact with each other' since the 'with each other' is implied and redundant.

The corrections that may not matter given the conversion of this document into HTML.

1. *proselint* noted inconsistent spacing after period (1 vs. 2 spaces).
2. *proselint* noted the use of straight quotes "" instead of quotes “”.

** Code review**

**Code Block 1**: No issues

**Code Block 2**: The use of ellipsis in the lines
```
parameter1 = ipw.FloatSlider(...)
parameter2 = ipw.IntText(...)
parameter3 = ipw.IntSlider(...)
```
and the mention of functions that were not actually in the provided in the event handler functions made the function untestable.  I  made changes to the code so that it can be run and would suggest something like
```
import ipywidgets as ipw

# initialize the widgets
graph1_out = ipw.Output()
graph2_out = ipw.Output()

parameter1 = ipw.FloatSlider(min=0, max=10, value=1)
parameter2 = ipw.IntText(min=0, max=10, value=1)
parameter3 = ipw.IntSlider(min=0, max=10, value=1)

# create the dashboard layout, combining all the widgets
dashboard = ipw.VBox([
    ipw.HBox([graph1_out, graph2_out]),
    ipw.HBox([parameter1, parameter2, parameter3]),
])
   
# event handler functions
def on_parameter1_change(change):
    graph1_out.clear_output(wait=True)
    with graph1_out:
        print(f"parameter 1 is {change['new']} and parameter 2 is {parameter2.value}.")
        
def on_parameter2_change(change):
    graph1_out.clear_output(wait=True)
    graph2_out.clear_output(wait=True)
    with graph1_out:
        print(f"parameter 1 is {parameter1.value} and parameter 2 is {change['new']}.")
    with graph2_out:
        print(f"parameter 2 is {change['new']} and parameter 3 is {parameter3.value}.")
        
def on_parameter3_change(change):
    graph2_out.clear_output(wait=True)
    with graph2_out:
        print(f"parameter 2 is {parameter2.value} and parameter 3 is {change['new']}.")

# attach event handlers
parameter1.observe(on_parameter1_change, names=["value"])
parameter2.observe(on_parameter2_change, names=["value"])
parameter3.observe(on_parameter3_change, names=["value"])

dashboard
```

Code Block 3: I would have included the code to display the button, which is shown in Figure 5 but not in the actual code.  Again, I made the changes myself and would suggest something like:
```
import traitlets
import ipyvuetify as v

class ColoredToggleButton(v.VuetifyTemplate):
    color1 = traitlets.Unicode("var(--md-light-blue-500)").tag(sync=True)
    color2 = traitlets.Unicode("#AA6688").tag(sync=True)
    state = traitlets.Bool(True).tag(sync=True)

    @traitlets.default("template")
    def _template(self):
        return """
        <template>
            <v-btn 
                width="300px"
                :color="state ? color1 : color2"
                @click="state = !state"
            >Press to change color!</v-btn>
        </template>
        """

button = ColoredToggleButton()

# Display button
button 
```
followed by a mention of that running 
```
button.color2 = "var(--md-green-600)"
```
will change the second color programmatically.

Code Block 4: I was disappointed that we were not provided with example iPyOverlay code both to show an example implementation of the Python package (although we were shown the Vue template for an overlay container in Code 4, I wasn't hable to test it with the code provided)

2024-07-16 01:31 UTC, JuanCab commented on papers/nathan_martindale/detailsondemand.png
If you truly want to reproduce "Inception" you should revise this figure to be consistent with the final draft of the paper... but I did think it a clever Figure to include!

2024-07-16 01:31 UTC, JuanCab commented on papers/nathan_martindale/ipywidgets_state.png
"Python" should be capitalized in the caption "JS model changes mirrored in Python attributes".

2024-07-16 01:31 UTC, JuanCab commented on papers/nathan_martindale/main.md
> +building interactive tooling. The general flow of interaction proposed by this
This mention of details on demand should really refer to the AUTHOR and not "a paper".
```suggestion
Details on demand is one piece of the "visual information-seeking mantra" of Schneiderman (1996)
 describing an overall design approach to building interactive tooling. 
 The general flow of interaction proposed by this
```

2024-07-16 01:31 UTC, JuanCab commented on papers/nathan_martindale/main.md
> +first ideally starts with broader aggregate visualizations: something to gain a sense
Redundant `first`
```suggestion
ideally starts with broader aggregate visualizations: something to gain a sense
```

2024-07-16 01:31 UTC, JuanCab commented on papers/nathan_martindale/main.md
> +identify their own areas of interest to hone in on with whatever zoom and filter
Redundant since user unlikely to identify other's areas of interest:
```suggestion
identify areas of interest to hone in on with whatever zoom and filter
```

2024-07-16 01:31 UTC, JuanCab commented on papers/nathan_martindale/main.md
> +similar. This selective detail capability provides a flexible user experience
I do not like the phrasing "pop-up window or similar" since it doesn't say "similar WHAT".  Maybe it would be better to say "in the form of something like a pop-up window or inset graph"?  I just find the current phrasing gets in the way to understanding the authors' meaning.

2024-07-16 01:31 UTC, JuanCab commented on papers/nathan_martindale/main.md
> +Jupyter Notebook/Jupyter Lab. A key challenge this framework has to overcome is
I don't think you need to specify both Jupyter Notebook and Jupyter Lab since Jupyter notebooks (the documents) run in different implementations of Jupyter (including Jupyter in VS Code).  I would suggest just
```suggestion
Jupyter Notebook. A key challenge this framework has to overcome is
```

2024-07-16 01:31 UTC, JuanCab commented on papers/nathan_martindale/main.md
> +synchronization problem discussed above. All of this has allowed many libraries
This is a pet peeve of mine, I don't think it is *necessary* to fix, but I do not like the use of spatial terms like "above" for prose, I prefer time terms like "previously".  But I do believe this spatial language is commonly accepted now, I suppose I should not fight it.
```suggestion
synchronization problem discussed previously. All of this has allowed many libraries
```

2024-07-16 01:31 UTC, JuanCab commented on papers/nathan_martindale/main.md
> +interactions or responsiveness can greatly enhance the capabilities of a tool.
You kind of wedge in "or responsiveness" in this sentence and it made it hard to follow.  Furthermore, you address this later in the text whereas this paragraph focuses exclusively on other interactions like mouse events, just keep it on that:
```suggestion
interactions can greatly enhance the capabilities of a tool.
```

2024-07-16 01:31 UTC, JuanCab commented on papers/nathan_martindale/main.md
> +notoriously complicated. Prototyping the component can be a slow process as
Can you provide a citation for "somewhat notoriously complicated"?  If it is "notorious" it suggests it is "well known" and thus should be citable.  If not, consider rewording this.  I think the existence of cookie-cutter templates definitely suggests this is a complex task.

2024-07-16 01:31 UTC, JuanCab commented on papers/nathan_martindale/main.md
> +than 70 premade material design UI widgets. Most of these components support a
Can you define "material design" or cite the term?

2024-07-16 01:31 UTC, JuanCab commented on papers/nathan_martindale/main.md
> +that can be observed. A simple example would be a textbox form input component.
Run on sentence with two ideas:  the support of extensive attributes/properties and multiple types of events to be observed.  Split it up:
```suggestion
functionality.  More importantly, each iPyVuetify widget generally has multiple types of events
that can be observed. A simple example would be a textbox form input component.
```

2024-07-16 01:31 UTC, JuanCab commented on papers/nathan_martindale/main.md
> +effective when the computation is delayed until the field loses focus or the
Here I think the proper word is "responsive" instead of "effective":
```suggestion
responsive when the computation is delayed until the field loses focus or the
```

2024-07-16 01:31 UTC, JuanCab commented on papers/nathan_martindale/main.md
> +IPyVuetify components make it easy to directly call functions across the
Can you tighten this a bit by stating 
```suggestion
IPyVuetify makes it easy to directly call functions across the
```

2024-07-16 01:31 UTC, JuanCab commented on papers/nathan_martindale/main.md
> +The dashboard includes a UMAP plot of signals embedded by the model under
Please define what I assume is an acronym, UMAP, the first time you use it.

2024-07-16 01:31 UTC, JuanCab commented on papers/nathan_martindale/main.md
> +data points are then clustered with DBSCAN. <!-- the key benefit from IPyOverlay
Please define DBSCAN the first time you use it.  I know the term is common enough in machine learning but the submissions to the SciPy proceedings are meant to be cross-disciplinary.  You may also want to link to the original 1996 by Ester, Kriegel, Sander, and Xu on the algorithm.

2024-07-16 01:31 UTC, JuanCab commented on papers/nathan_martindale/main.md
> +many libraries support basic tooltips with arbitrary textual content. Others
Again, several ideas in one run-on sentence that should be separated:
```suggestion
layout in which one widget is overlaid on top of another. Certain other libraries
have limited functionality for this within their own widget instances.  For
example Matplotlib and poorly can display an axes within another axes.  Furthermore,
many libraries support basic tooltips with arbitrary textual content. Others
```

2024-07-16 01:31 UTC, JuanCab commented on papers/nathan_martindale/main.md
> +container. A diagram demonstrating this design principle is shown in
I was confused by this sentence, specifically what is "this behavior"... Do you mean the ability to use the easier `HBox` and `VBox` grid layout or from the context of the sentence, the ability to have absolute positioning and (while you don't mention it) layers!  I would rework this to make it clear from the beginning what behavior you are referring to.

2024-07-16 01:31 UTC, JuanCab commented on papers/nathan_martindale/main.md
> +:caption: A simplified version of the Vue template for `OverlayContainer`. The `<div> tag with `v-for` reactively produces a `<div>` tag for each widget in the `children` list attribute within the Py
This caption gets mangled when rendered from MyST, I think you forgot to close the quote around the first `<div>` and that mucked it up, but check.

2024-07-16 01:31 UTC, JuanCab commented on papers/nathan_martindale/main.md
> +Unfortunately, in practice the functions necessary to do this for different
Missing a comma
```suggestion
Unfortunately, in practice, the functions necessary to do this for different
```

2024-07-16 01:31 UTC, JuanCab commented on papers/nathan_martindale/main.md
> +plotting libraries can vary substantially as a result of implementation differences, and
Again, two separate (albeit related) ideas in a sentence, so separate them:
```suggestion
plotting libraries can vary substantially as a result of implementation differences. Thus
```

2024-07-16 01:31 UTC, JuanCab commented on papers/nathan_martindale/main.md
> +A common feature in UI design across most platforms is the context menu.
Might be better to refer to "details on design" as a UI design paradigm/principle in this first sentence where it makes sense rather than wedging it the text later on in the paragraph.

2024-07-16 01:31 UTC, JuanCab commented on papers/nathan_martindale/main.md
> +visualization. IPyWidgets, one of the main drivers and the backbone that
I think this sentence is wordy and gets the same idea across without "one of the main drivers and"
```suggestion
visualization. IPyWidgets, the backbone that
```

2024-07-16 01:31 UTC, JuanCab commented on papers/nathan_martindale/references.bib
For some reason, when your references were rendered they same out a bit mangled, at least in my preview of the web page.  Notably:
1. authors were sometimes in LastName, FirstInitial format and sometimes FirstName LastName format.  Not sure if this can be easily fixed.
2. The reference for _matplotlib/ipympl: Release 0.9.4_ seems malformed with no space between the first authors First and Last names, one author referred to only as "Todd" and a reference to **npm-to-cdn-bot**.  You might want to check this reference and manually add it to your `references.bib`.  I am honestly not sure why this is listed in the references as I see no reference to it in the text or in your `references.bib`.

2024-07-16 18:18 UTC, WarmCyan commented on papers/nathan_martindale/main.md
> +:caption: A simplified version of the Vue template for `OverlayContainer`. The `<div> tag with `v-for` reactively produces a `<div>` tag for each widget in the `children` list attribute within the Py
I sure did, that fixed it, thanks! (@ritwit I assume this is what your comment was about as well?)

2024-07-16 18:52 UTC, WarmCyan commented
@JuanCab thanks for mentioning proselint, I didn't know this existed but I'll be making frequent use of it moving forward!

I updated programs 2 and 3 with your suggested changes, definitely agreed it's a lot nicer to be able to directly copy the snippet and have a functioning example in a notebook.

It's also a good point that we don't ever include an example of using ipyoverlay itself! I had previously been worried about running into the word count limit, but I think I'm quite a bit under. I've been wanting to work up a good concise example notebook for pop-out subplots to include in the repository itself, once I do that I'll add a code snippet for it in the paper

2024-07-17 06:06 UTC, ktzhao approved these changes

2024-07-26 14:29 UTC, WarmCyan commented on papers/nathan_martindale/detailsondemand.png
Will do, thanks!

2024-07-26 14:33 UTC, WarmCyan commented on papers/nathan_martindale/main.md
> +synchronization problem discussed above. All of this has allowed many libraries
Yeah that's totally fair, especially for like a PDF print I suppose "above" kinda loses any meaning if "above" is now an entirely different page! Fixed.

2024-07-26 14:40 UTC, WarmCyan commented on papers/nathan_martindale/main.md
> +notoriously complicated. Prototyping the component can be a slow process as
Alas, my citations would probably only consist of reddit programming memes :grinning: I do think this is a fairly commonly pointed out issue, but I don't really have a good formal reference for it, so point taken! I reworded it instead to briefly explain why it can be complicated:
```
JavaScript toolchains and dependency management can quickly become 
complicated with the number of packages, build system tools, and config files 
often necessary.
```

2024-07-26 14:41 UTC, WarmCyan commented on papers/nathan_martindale/main.md
> +than 70 premade material design UI widgets. Most of these components support a
Provided a reference to google's material design website

2024-07-26 18:09 UTC, cdlindsey commented on papers/nathan_martindale/main.md
> +version of these proceedings can explore a simple example of details on demand
Do we see this in the curvenote preview?  Is this going to be a separate file?

2024-07-26 18:18 UTC, cdlindsey commented on papers/nathan_martindale/main.md
> +```
This example is pretty generic.  Could you change the names to make it have more meaningful function.  This would be easier to understand.

2024-07-26 18:20 UTC, cdlindsey commented on papers/nathan_martindale/main.md
> +:::
The blue color in the bottom right arrow seems off.  Maybe you could make the bottom box a different shade of yellow and change the arrow as well.

2024-07-26 18:25 UTC, cdlindsey commented on papers/nathan_martindale/main.md
> +we briefly touch on here are AnyWidget, IPyReact, and IPyVuetify.
Gradio probably deserves a mention too.

2024-07-26 18:30 UTC, cdlindsey commented on papers/nathan_martindale/main.md
> +:::
As in "program 2", this would be more instructive if the buttons meant something.

2024-07-26 19:14 UTC, WarmCyan commented on papers/nathan_martindale/main.md
> +version of these proceedings can explore a simple example of details on demand
Yeah, the curvenote preview is the web version, so hovering over the "Figure 1" link pulls up a tooltip/details-on-demand example. That figure itself is then just a (almost recursive :grin:) screenshot of what hovering over the figure link looks like so that you still get the idea if reading on a non-web medium, like a PDF version of the paper.

2024-07-26 19:47 UTC, WarmCyan commented on papers/nathan_martindale/main.md
> +:::
As in the blue arrow color clashes with the shade of yellow we're using or as in that arrow shouldn't be blue?

Our intent was to show the two pathways of changes colored based on source, so:
1. Interacting with the HTML/JS causes changes to propagate from the JS view -> JS model -> python model (represented as yellow arrows the whole way to match the JS yellow) 
2. Modifying values from python propagates to the view in the other direction, so the pathway is python model -> JS model -> JS view (which we represented with blue arrows the whole way to match the python blue)

I'm assuming the oddness is having the python blue arrow between two yellow JS boxes, and the idea was to show that that communication is being caused by a change on the python side. Does that make more sense or is there maybe a better way to represent this?

2024-08-01 17:35 UTC, JuanCab approved these changes

2024-08-01 17:40 UTC, JuanCab approved these changes

2024-08-01 17:41 UTC, JuanCab commented
I apologize for the confusion, while I can review individual commits, apparently when I approve an individual commit, it just marks the entire PR as approved, not what I meant!

2024-08-01 17:46 UTC, JuanCab reviewed
I have gone through all the commits through August 1, 2024 17:45 UTC and they all look good.

2024-08-01 17:46 UTC, JuanCab commented on papers/nathan_martindale/main.md
> +A minimal code example using IPyOverlay's containers and connection lines is
Thank you for adding the code example!

2024-08-02 20:17 UTC, cdlindsey commented on papers/nathan_martindale/main.md
> +version of these proceedings can explore a simple example of details on demand
that makes sense, cool

2024-08-02 20:18 UTC, cdlindsey commented on papers/nathan_martindale/main.md
> +:::
gotcha, yeah, I guess a third color might be too confusing

2024-08-03 20:16 UTC, JuanCab commented on papers/nathan_martindale/main.md
> +:::
I'll note that for accessibility purposes (e.g. - usability by the color blind), the color should not be the only thing distinguishing the arrows if you want them to be distinct.  I don't have the figure here, but I thought I would mention it.

2024-08-05 19:33 UTC, WarmCyan commented on papers/nathan_martindale/references.bib
I addressed the ipympl citation as best I could, (and made it more obvious, in the text where I reference it I had only called it interactive matplotlib) I think zenodo just grabbed the full list of github contributors and not all of them have a full name listed anywhere, but I at least removed the bot and fixed one of the names that it hadn't gotten correct. 

I'm also not really sure what to do about 1, I'm assuming there's something wrong in the bibtex syntax somewhere in the auto-collected doi ref, but I'm not sure how to debug that

2024-08-05 19:42 UTC, WarmCyan commented on papers/nathan_martindale/main.md
> +```
Yeah that's a good point, I renamed things to try to make it more obvious that this is showing a pattern where you can have parameters that influence multiple graphs, or ipywidget outputs that are influenced by multiple inputs that can be shared or have crossover

2024-08-05 19:47 UTC, WarmCyan commented on papers/nathan_martindale/main.md
> +we briefly touch on here are AnyWidget, IPyReact, and IPyVuetify.
Gradio is a good suggestion, I looked into it and was kind of surprised to see it doesn't actually have any direct ipywidgets compatibility. It has its own set of communication mechanisms, and while it can render inside of a notebook, as far as I can tell it's still entirely distinct and can't use other ipywidgets

2024-08-05 19:55 UTC, WarmCyan commented on papers/nathan_martindale/main.md
> +:::
The figure was just supposed to show the visual distinction between the types of components available in both, so I just labeled them according to the library they came from. I updated the caption to highlight these are just widget samples

2024-08-05 20:43 UTC, JuanCab reviewed
I like the code changes, they do make things a little clearer and easier to follow.

2024-08-05 20:43 UTC, JuanCab commented on papers/nathan_martindale/references.bib
Maybe this is a Curvenote issue?

2024-08-05 20:43 UTC, JuanCab reviewed
I like the code changes, they do make things a little clearer and easier to follow.

2024-09-25 17:14 UTC, merged