Paper: Evaluating probabilistic forecasters with sktime - an easy-to-use, highly configurable framework for reproducible science
scipy-conference/scipy_proceedings pull request #915
Opened 2024-05-31 10:36 UTC by benHeid

If you are creating this PR in order to submit a draft of your paper, please name your PR with `Paper: <title>`. An editor will then add a `paper` label and GitHub Actions will be run to check and build your paper.

See the [project readme](https://github.com/scipy-conference/scipy_proceedings#preview-your-paper) for more information.

_Editor_: Meghann Agarwal @mepa

_Reviewers_: 
- Juan Cabanela @JuanCab
- James Lamb @jameslamb

2024-05-31 11:28 UTC, rowanc1 commented on papers/benchmarking/myst.yml
> +  subtitle: LaTeX edition
Hi @benHeid, can you please update these to the title of your paper! (removing the subtitle if not applicable).

2024-05-31 11:35 UTC, benHeid commented on papers/benchmarking/myst.yml
> +  subtitle: LaTeX edition
Done

2024-06-04 18:07 UTC, ameyxd commented
@benHeid thanks for your submission! Can you update the DOI for "kiraly2021designing"?

2024-06-09 15:22 UTC, benHeid commented
> @benHeid thanks for your submission! Can you update the DOI for "kiraly2021designing"? 

I added the dpi

2024-06-19 20:00 UTC, fwkoch commented on papers/benchmarking/main.tex
> +Additionally, the \texttt{R/fable} package \cite{hyndman2020package} has contributed similar concepts specifically tailored to forecasting, which \texttt{sktime} has expanded upon or adapted to fit w
I believe you are missing bibtex entries for the following cite ids: `hyndman2020package`, `garza2022statsforecast`, `loning2019sktime`, `hyndman2018`. Can you add these?

2024-06-19 20:15 UTC, fwkoch commented on papers/benchmarking/main.tex
> +The remainder of this paper is organized as follows: In Section \ref{methods}, we describe the forecasting methods and probabilistic wrappers used in our experiments. Section \ref{datasets} provides
These cross references (and others throughout your paper) are giving `??` in the built paper:
![image](https://github.com/scipy-conference/scipy_proceedings/assets/9453731/b897ff02-7a5c-4df1-a4a0-ad1cc1e2d8e9)

This is because `\ref` tries to create numbered references, but your sections are not numbered. You have two options:

1. Change `\ref` to `\nameref` - then you will have, for example, "In Section _Methods_, we describe..."

2. Enable section numbering in your `myst.yml`, resulting in "In Section _2_, we describe...":

  ```yaml
  # myst.yml
  project:
    ...
    numbering:
      sections: true
  ```

(Numbered sections may become the default later, but for now, taking this proactive step will fix your preview build.)

2024-06-19 23:33 UTC, rowanc1 commented on papers/benchmarking/main.tex
> +The remainder of this paper is organized as follows: In Section \ref{methods}, we describe the forecasting methods and probabilistic wrappers used in our experiments. Section \ref{datasets} provides
Thank you @fwkoch -- we should have turned that on in the default template, and will for next year. The final papers will have numbered sections.

@benHeid the second approach by @fwkoch above is the way to go! :)

2024-06-22 17:24 UTC, Smit-create commented
Hi all,
I am Smit and I am one of the reviewers of the paper. I will work on reviewing the paper and providing feedback/suggestions.

Thank you.

2024-06-28 18:40 UTC, mepa commented
Hi @Smit-create and @RoccoDAnt! In case a little extra time is needed, the initial complete review deadline has been extended to next [Wednesday, July 3rd](https://github.com/scipy-conference/scipy_proceedings/blob/2024/README.md#instructions-for-reviewers).

2024-07-03 16:21 UTC, mepa commented
> Hi @Smit-create and @RoccoDAnt! In case a little extra time is needed, the initial complete review deadline has been extended to next [Wednesday, July 3rd](https://github.com/scipy-conference/scipy_proceedings/blob/2024/README.md#instructions-for-reviewers).

Update: the Proceedings Committee has extended the initial complete review deadline to Monday, July 8th.

2024-07-05 01:30 UTC, davekits commented
My name is Kirtan, and I am one of the paper's reviewers.I will work on reviewing the paper and offering feedback.

2024-07-13 09:30 UTC, davekits commented
This presented methods are all probability wrappers, and pipeline composition.However, Is there a better name that we can find for this methodology compersion . The other things looks good.

2024-07-14 21:04 UTC, cbcunc commented
> This presented methods are all probability wrappers, and pipeline composition.However, Is there a better name that we can find for this methodology compersion . The other things looks good.

@davekits If you would please make your review in a form of a GitHub review that is actionable by the author: https://docs.github.com/en/pull-requests/collaborating-with-pull-requests/reviewing-changes-in-pull-requests/commenting-on-a-pull-request Thank you for your help.

2024-07-16 20:45 UTC, JuanCab requested changes
This paper was genuinely interesting although a bit challenging for me to read.  I am machine learning "adjacent" as a domain in that I am aware of a lot of ML ideas but have not actually used ML extensively outside of classwork. I am aware of some of the challenges in applying machine leaning techniques to time series data.

This paper provided a reasonable review of the `sktime` package for Python while demonstrating some of its capabilities through a set of three test cases covering different time spans and time scales. It is generally logically structured and its narrative makes sense.  That said, it does have a few (small) flaws that I believe should be addressed before the paper is accepted for the proceedings.  The most repeated flaw is the use of ML jargon. Given the audience of the SciPy Proceedings are cross-disciplinary and cover a wide range of programming domains, I believe the jargon needs to be explained after its first use.  I have noted all the cases of this issue I ran across in my review.  I tried to be a little "harder" during the introductory part of the paper since that is more likely to be read by someone to gauge if they could follow the rest of the paper.

The other issue is the authors' use of LaTeX or rather the issues Curvenote seems to be having with there LaTeX. The document seems to be having mis-rendering issues.  First, many references to sections of the paper being shown as "?" (which apparently was [already caught by another reviewer](https://github.com/scipy-conference/scipy_proceedings/pull/915/files#r1646652574) who suggested a fix to this problem).  Secondly, references to bibtex citations that got mangled (notably in line 28 of main.tex, there are three separate references to three different papers (Godahewa2021Australian, Godahewa2021Sunspot, and Godahewa2021USBirth) that are all referred to as Godahewa et al 2021 in the rendered paper. I have noted this issue with the references but understand it may be beyond the power of the authors to fix the rendering issue and that this may need to be addressed by Curvenote.  

I have tried to note all the cases of the above problems in this paper via individual comments.

There is also another issue in that GitHub's review system is not designed for documents with lines as long as those shown in this latex document, but that is not really the authors' fault.  It does make noting problems via the commenting interface a little bit tricky.

Finally, there were a LOT of figures related to benchmarking that were submitted with this pull request that are not referenced in the paper.  I assume as they are not necessarily particularly enlightening, they were dropped, but they should be removed from the pull request as well.  I have noted them with individual comments.

And while I have found a lot of "issues" with this paper I want to point out I really hope they are addressed, particularly the issues with jargon, because this paper describes a very interesting toolkit and if it had less jargon, it would be an excellent way to make more scientific programmers aware of the possibilities of time-series machine learning and prediction.

** Code review**

I was unable to test the code snippets shown in part because the `import` necessary to run them was not shown.  I did experiment and review the documentation for sktime to determine that the proper import line was `from sktime.forecasting.naive import NaiveForecaster` but even then without sample time-series data, I could NOT run the code to test it.  I strongly suggest the authors show the import statements at least and really they should provide a data file to test these code snippets with.

I've noted these issues in individual comments as well.

2024-07-16 20:45 UTC, JuanCab commented on papers/benchmarking/Figures/elec_T1_PinballLoss_mean.png
Not in paper, did you intend to include this?

2024-07-16 20:45 UTC, JuanCab commented on papers/benchmarking/Figures/elec_T1_IntervalWidth_mean.png
Not in paper, did you intend to include this?

2024-07-16 20:45 UTC, JuanCab commented on papers/benchmarking/Figures/elec_T1_EmpiricalCoverage_mean.png
Not in paper, did you intend to include this?

2024-07-16 20:45 UTC, JuanCab commented on papers/benchmarking/Figures/elec_T1_CRPS_mean.png
Not in paper, did you intend to include this?

2024-07-16 20:45 UTC, JuanCab commented on papers/benchmarking/Figures/elec_T1_AUCalibration_mean.png
Not in paper, did you intend to include this?

2024-07-16 20:45 UTC, JuanCab commented on papers/benchmarking/Figures/birth_runtime_secs.png
Not in paper, did you intend to include this?

2024-07-16 20:45 UTC, JuanCab commented on papers/benchmarking/Figures/birth_PinballLoss_mean.png
Not in paper, did you intend to include this?

2024-07-16 20:45 UTC, JuanCab commented on papers/benchmarking/Figures/birth_IntervalWidth_mean.png
Not in paper, did you intend to include this?

2024-07-16 20:45 UTC, JuanCab commented on papers/benchmarking/Figures/birth_EmpiricalCoverage_mean.png
Not in paper, did you intend to include this?

2024-07-16 20:45 UTC, JuanCab commented on papers/benchmarking/Figures/birth_CRPS_mean.png
Not in paper, did you intend to include this?

2024-07-16 20:45 UTC, JuanCab commented on papers/benchmarking/Figures/birth_AUCalibration_mean.png
Not in paper, did you intend to include this?

2024-07-16 20:45 UTC, JuanCab commented on papers/benchmarking/Figures/elec_T1_runtime_secs.png
Not in paper, did you intend to include this?

2024-07-16 20:45 UTC, JuanCab commented on papers/benchmarking/Figures/elec_T2_AUCalibration_mean.png
Not in paper, did you intend to include this?

2024-07-16 20:45 UTC, JuanCab commented on papers/benchmarking/Figures/elec_T2_CRPS_mean.png
Not in paper, did you intend to include this?

2024-07-16 20:45 UTC, JuanCab commented on papers/benchmarking/Figures/elec_T2_EmpiricalCoverage_mean.png
Not in paper, did you intend to include this?

2024-07-16 20:45 UTC, JuanCab commented on papers/benchmarking/Figures/elec_T2_IntervalWidth_mean.png
Not in paper, did you intend to include this?

2024-07-16 20:45 UTC, JuanCab commented on papers/benchmarking/Figures/elec_T2_PinballLoss_mean.png
Not in paper, did you intend to include this?

2024-07-16 20:45 UTC, JuanCab commented on papers/benchmarking/Figures/elec_T2_runtime_secs.png
Not in paper, did you intend to include this?

2024-07-16 20:45 UTC, JuanCab commented on papers/benchmarking/Figures/elec_T3_AUCalibration_mean.png
Not in paper, did you intend to include this?

2024-07-16 20:45 UTC, JuanCab commented on papers/benchmarking/Figures/elec_T3_CRPS_mean.png
Not in paper, did you intend to include this?

2024-07-16 20:45 UTC, JuanCab commented on papers/benchmarking/Figures/elec_T3_EmpiricalCoverage_mean.png
Not in paper, did you intend to include this?

2024-07-16 20:45 UTC, JuanCab commented on papers/benchmarking/Figures/elec_T3_PinballLoss_mean.png
Not in paper, did you intend to include this?

2024-07-16 20:45 UTC, JuanCab commented on papers/benchmarking/Figures/elec_T3_runtime_secs.png
Not in paper, did you intend to include this?

2024-07-16 20:45 UTC, JuanCab commented on papers/benchmarking/Figures/elec_T4_AUCalibration_mean.png
Not in paper, did you intend to include this?

2024-07-16 20:45 UTC, JuanCab commented on papers/benchmarking/Figures/elec_T4_CRPS_mean.png
Not in paper, did you intend to include this?

2024-07-16 20:45 UTC, JuanCab commented on papers/benchmarking/Figures/elec_T4_EmpiricalCoverage_mean.png
Not in paper, did you intend to include this?

2024-07-16 20:45 UTC, JuanCab commented on papers/benchmarking/Figures/elec_T4_IntervalWidth_mean.png
Not in paper, did you intend to include this?

2024-07-16 20:45 UTC, JuanCab commented on papers/benchmarking/Figures/elec_T4_PinballLoss_mean.png
Not in paper, did you intend to include this?

2024-07-16 20:45 UTC, JuanCab commented on papers/benchmarking/Figures/elec_T4_runtime_secs.png
Not in paper, did you intend to include this?

2024-07-16 20:45 UTC, JuanCab commented on papers/benchmarking/Figures/elec_T5_AUCalibration_mean.png
Not in paper, did you intend to include this?

2024-07-16 20:45 UTC, JuanCab commented on papers/benchmarking/Figures/elec_T5_CRPS_mean.png
Not in paper, did you intend to include this?

2024-07-16 20:45 UTC, JuanCab commented on papers/benchmarking/Figures/elec_T5_EmpiricalCoverage_mean.png
Not in paper, did you intend to include this?

2024-07-16 20:45 UTC, JuanCab commented on papers/benchmarking/Figures/elec_T5_IntervalWidth_mean.png
Not in paper, did you intend to include this?

2024-07-16 20:45 UTC, JuanCab commented on papers/benchmarking/Figures/elec_T5_PinballLoss_mean.png
Not in paper, did you intend to include this?

2024-07-16 20:45 UTC, JuanCab commented on papers/benchmarking/Figures/elec_T5_runtime_secs.png
Not in paper, did you intend to include this?

2024-07-16 20:45 UTC, JuanCab commented on papers/benchmarking/Figures/sunspot_AUCalibration_mean.png
Not in paper, did you intend to include this?

2024-07-16 20:45 UTC, JuanCab commented on papers/benchmarking/Figures/sunspot_CRPS_mean.png
Not in paper, did you intend to include this?

2024-07-16 20:45 UTC, JuanCab commented on papers/benchmarking/Figures/sunspot_EmpiricalCoverage_mean.png
Not in paper, did you intend to include this?

2024-07-16 20:45 UTC, JuanCab commented on papers/benchmarking/Figures/sunspot_IntervalWidth_mean.png
Not in paper, did you intend to include this?

2024-07-16 20:45 UTC, JuanCab commented on papers/benchmarking/Figures/sunspot_PinballLoss_mean.png
Not in paper, did you intend to include this?

2024-07-16 20:45 UTC, JuanCab commented on papers/benchmarking/Figures/sunspot_runtime_secs.png
Not in paper, did you intend to include this?

2024-07-16 20:45 UTC, JuanCab commented on papers/benchmarking/frog.jpg
Cute tree frog, but doesn't appear to be relevant except maybe as a mascot. :)

2024-07-16 20:45 UTC, JuanCab commented on papers/benchmarking/main.tex
> +Despite the critical importance of evaluating probabilistic forecasts in various domains, including finance, energy, healthcare, and climate science, no comprehensive software framework or interface
You make a statement here that "Similar issues are found in other benchmarking studies, where code availability is often limited or nonexistent."  This should include citations since you refer to other benchmarking studies, so you presumably can refer to them specifically.

2024-07-16 20:45 UTC, JuanCab commented on papers/benchmarking/main.tex
> +The key components of the reproducible benchmarking framework are:
Since you are referring to `sktime` specifically, I think you should state:
```suggestion
The key components of this reproducible benchmarking framework are:
```

2024-07-16 20:45 UTC, JuanCab commented on papers/benchmarking/main.tex
> +We conducted experiments on several common datasets, including Australian electricity demand \cite{Godahewa2021Australian}, sunspot activity \cite{Godahewa2021Sunspot}, and US births \cite{Godahewa20
The three references here to datasets are all getting rendered as "Godahewa *et al.* (2021) " instead of being rendered in some what that indicates they are separate references (e.g. Godahewa *et al.* (2021a), Godahewa *et al.* (2021b), etc.).  This is likely an issue that needs to be fixed with how Curvenote is rendering the references, but I bring it to the authors' attention.

2024-07-16 20:45 UTC, JuanCab commented on papers/benchmarking/main.tex
> +Our paper is accompanied by easily reusable code, and we invite the open research and open-source communities to contribute to extending our experiments or using our code to set up their own. As is o
I strongly contest this point that the paper has "easily reusable code" in it.  The code is missing imports and sample datasets to work with... simply put, the provided code can not be executed without substantial work by the reader.  The best solution of this would be to revise the code in the paper and possibly provide a downloadable code sample with a dataset.

Also, I do not believe "SciPy" should be printed in monospace font.

2024-07-16 20:45 UTC, JuanCab commented on papers/benchmarking/main.tex
> +which can be used to copy a full specification from a research paper and immediately construct the respective algorithm in a python environment, even if full code has not been shared by the author.
"Python" should be upper-case as it is a proper name for the programming language.

2024-07-16 20:45 UTC, JuanCab commented on papers/benchmarking/main.tex
> +The design principles of \texttt{sktime} draw inspiration from several established machine learning frameworks. Notably, \texttt{scikit-learn} in \texttt{python} \cite{pedregosa2011scikit}, \texttt{m
I do not believe Python (which should be uppercase), R, or Weka should be presented in mono-spaced font as they are not packages to be imported or used within the code but rather the names of entire programming languages (or in the case of Weka, a software environment).

2024-07-16 20:45 UTC, JuanCab commented on papers/benchmarking/main.tex
> +To enable easy replication of the experiments, we provide for each used forecaster, and wrapper the hyperparameters by providing the used python object instantiation in Table~\ref{tab:hyperparams}. T
Again, "Python" rather than "python" here.

2024-07-16 20:45 UTC, JuanCab commented on papers/benchmarking/main.tex
> +Forecasters are objects with \texttt{fit} and \texttt{predict} methods, allowing both endogenous and exogenous data to be passed. For example, the following code specifies a forecaster, fits it, and
Given the target audience of the SciPy Proceedings extends beyond the machine learning community, I would avoid jargon like "endogenous" and "exogenous" (especially since these terms are only used here) and just say "data influenced by either by other model variables and/or by external factors" or something else that gets the point across without the jargon.

2024-07-16 20:45 UTC, JuanCab commented on papers/benchmarking/main.tex
> +This design pattern is consistent across all forecasters in \texttt{sktime}, and called the "strategy pattern" in software engineering.
When you say "This design pattern" (the "strategy pattern") are you referring to the use of a consistent API across all forecaster classes or to the fact that it is possible to swap different forecaster classes (yes, they are related, but what is the 'design pattern', software engineering usually is not API specific, which makes me thing it is the ability to swap different forecasters that is the design pattern)... it is unclear what you refer to .

Also, this is improper latex for a quoted string, you should use 

``strategy pattern''

2024-07-16 20:45 UTC, JuanCab commented on papers/benchmarking/main.tex
> +Probabilistic forecasters are tagged with the \texttt{"capability:pred\_int"} tag. Currently, 45 of the 82 forecasters support probabilistic prediction modes, such as prediction intervals, quantile p
The concept of "tags" is not one that exists in other Python packages that I am aware of.  It might be useful to discuss tags more throughly either here or earlier when introducing `sktime`.

2024-07-16 20:45 UTC, JuanCab commented on papers/benchmarking/main.tex
> +More details can be found in the official tutorials.
I would provide a hyperlink to the official tutorials (I found the documentation with links to video tutorials and notebooks at [https://www.sktime.net/en/latest/users.html](https://www.sktime.net/en/latest/users.html)).

2024-07-16 20:45 UTC, JuanCab commented on papers/benchmarking/main.tex
> +Creating algorithms with compatible APIs is straightforward.
I don't believe there is a need for a blank line between this sentence and the next paragraph.  This sentence can function as the lead into that paragraph.

2024-07-16 20:45 UTC, JuanCab commented on papers/benchmarking/main.tex
> +\texttt{sktime} and \texttt{tsbootstrap} provide fill-in extension templates for creating algorithms in a compatible interface, which can be shared in a third-party code base and indexed by \texttt{s
Can you provide a hyperlink to the "fill-in extension templates" in the paper?

2024-07-16 20:45 UTC, JuanCab commented on papers/benchmarking/main.tex
> +which can be used to copy a full specification from a research paper and immediately construct the respective algorithm in a python environment, even if full code has not been shared by the author.
I didn't quite understand the importance of this `craft` feature.  It looks like it just takes a string and parses it into a function call.  What is the advantage of 
```
forecaster = NaiveForecaster(strategy="last", sp=12)
```
versus
```
forecaster = craft('NaiveForecaster(strategy="last", sp=12)')
```
They both end up creating the same object, right?  I think this needs to be clarified since I am clearly missing how this lets you "construct the respective algorithm [] even if full code has not been shared by the author."

2024-07-16 20:45 UTC, JuanCab commented on papers/benchmarking/main.tex
> +This method uses a window sliding and residual collection strategy.
Jargon: please define or use alternative phrasing for "window sliding" and "residual collection strategy".

2024-07-16 20:45 UTC, JuanCab commented on papers/benchmarking/main.tex
> +This creates a forecasting algorithm that first computes first differences, then deseasonalizes with periodicity 12, then applies the last-value-carry-forward method, reseasonalizes, and inverts the
This sentence is full of jargon "deseasonalize" and "reseasonlize" (which I can sort of understand from context) and the "last-value-carry-forward method" which being a specific method should not only be described but probably linked to a reference via a citation.

2024-07-16 20:45 UTC, JuanCab commented on papers/benchmarking/main.tex
> +For a detailed analysis of design patterns in AI framework packages and innovations in \texttt{sktime}, see\cite{kiraly2021designing}.
Typo (missing space before final reference):
```suggestion
For a detailed analysis of design patterns in AI framework packages and innovations in \texttt{sktime}, see \cite{kiraly2021designing}.
```

2024-07-16 20:45 UTC, JuanCab commented on papers/benchmarking/main.tex
> +Additionally, the \texttt{R/fable} package \cite{hyndman2020package} has contributed similar concepts specifically tailored to forecasting, which \texttt{sktime} has expanded upon or adapted to fit w
Give it refers to it as a package, it may make sense for "R/fable" to be monospaced.  The citation "hyndman2020package" doesn't work (as noted above, you don't appear to have included this reference in your bibtex).

2024-07-16 20:45 UTC, JuanCab commented on papers/benchmarking/main.tex
> +\end{itemize}
I think it makes more sense to, in the statement the line before the `itemize` list, to state the features `sktime` provides and then mention it also provides a unified interface to 3 other second and third party packages in the bulleted list.  It just seems odd otherwise to list `sktime` as being one of the packages it offers a unified interface to...  It also makes the followup statement after the list clearer.

Also, the references to `garza2022statsforecast` and `loning2019sktime` are missing from the provided bibtex.

2024-07-16 20:45 UTC, JuanCab commented on papers/benchmarking/main.tex
> +This hybrid use of \texttt{sktime} as a framework covering first-party (itself), second-party (\texttt{tsbootstrap}), and third-party (\texttt{statsmodels}, \texttt{statsforecast}) locations is signi
"Credit" for what?  "Credit for this effective integration"?  "Credit for working together"?

2024-07-16 20:45 UTC, JuanCab commented on papers/benchmarking/main.tex
> +Each forecaster is wrapped in a \texttt{Differencer} and a \texttt{Deseasonalizer} as preprocessing steps to improve stationarity. These preprocessors are necessary because some forecasters require t
Jargon: Explain "stationarity" or use alternative prose.

2024-07-16 20:45 UTC, JuanCab commented on papers/benchmarking/main.tex
> +All forecasters are point forecasters, combined with one of the probabilistic wrappers to generate prediction intervals and probabilistic forecasts.
Jargon: Please define "point forecasters".

2024-07-16 20:45 UTC, JuanCab commented on papers/benchmarking/main.tex
> +    \item \texttt{StatsForecastAutoTheta(sp)}: A variant of the Theta model \cite{Assimakopoulos2000} with automated parameter tuning, from the \texttt{statsforecast} library.
I *think* you may have meant:
```suggestion
    \item \texttt{StatsForecastAutoTheta(sp)}: A variant of the Theta model of \cite{Assimakopoulos2000} with automated parameter tuning, from the \texttt{statsforecast} library.
```

2024-07-16 20:45 UTC, JuanCab commented on papers/benchmarking/main.tex
> +    \item \texttt{BaggingForecaster(bootstrap\_transformer, forecaster)}: Provides probabilistic forecasts by bootstrapping time series and aggregating the bootstrap forecasts \cite{hyndman2018, berg
The reference to `hyndman2018` is missing from bibtex.

2024-07-16 20:45 UTC, JuanCab commented on papers/benchmarking/main.tex
> +    \item \texttt{ConformalIntervals(forecaster, strategy)}: Uses conformal prediction methods \cite{Stankeviciute2021} to produce non-parametric prediction intervals. Variants of the method are sele
Can you provide a reference for the "Bonferroni correction"?

2024-07-16 20:45 UTC, JuanCab commented on papers/benchmarking/main.tex
> +Bootstrapping methods generate multiple resampled datasets from the original time series data, which can be used as part of wrappers to estimate prediction intervals or predictive distributions. In t
Just wanted to note this is a nice case of where you explain Bootstrapping (jargon) in line with describing what it does.  More of this when you introduce jargon would be nice to those readers from outside the machine learning discipline.

2024-07-16 20:45 UTC, JuanCab commented on papers/benchmarking/main.tex
> +    \item \texttt{BlockDistributionBootstrap}: Generates bootstrapped samples by fitting a distribution to the residuals of a model and then generating new residuals from the fitted distribution. Thi
Can you clarify, are the generated residuals added to the data to simulate real/noisy data?  I'm guessing that is the case but it is unclear.

2024-07-16 20:45 UTC, JuanCab commented on papers/benchmarking/main.tex
> +    L(\hat{q}, y) = \frac{1}{k} \sum_{i=1}^k \max \left(\tau (y - \hat{q}_i), (1 - \tau_i) (\hat{q}_i - y)\right)
You are missing the subscript on the first tau:
```suggestion
    L(\hat{q}, y) = \frac{1}{k} \sum_{i=1}^k \max \left(\tau_i (y - \hat{q}_i), (1 - \tau_i) (\hat{q}_i - y)\right)
```

2024-07-16 20:45 UTC, JuanCab commented on papers/benchmarking/main.tex
> +    For quantile forecasts $\hat{q}_1, dots, \hat{q}_k$ at levels $\tau_1, \dots, \tau_k$ and an observation $y$, the Pinball Loss is defined as:
Missing backslash in math:
```suggestion
    For quantile forecasts $\hat{q}_1, \dots, \hat{q}_k$ at levels $\tau_1, \dots, \tau_k$ and an observation $y$, the Pinball Loss is defined as:
```

2024-07-16 20:45 UTC, JuanCab commented on papers/benchmarking/main.tex
> +    \item \texttt{IntervalWidth} - width of prediction intervals, or sharpness measures the concentration of the prediction intervals. More concentrated intervals indicate higher confidence in the fo
Jargon to clarify: "nominal symmetric coverage"

2024-07-16 20:45 UTC, JuanCab commented on papers/benchmarking/main.tex
> +    \item \texttt{EmpiricalCoverage} - Empirical coverage measures how much of the observations are within the predicted interval. It is computed as the proportion of observations that fall within th
Jargon to clarify: "nominal coverage"

2024-07-16 20:45 UTC, JuanCab commented on papers/benchmarking/main.tex
> +    \item runtime. Besides metrics that assess the quality of the forecast, average runtime for an individual fit/interence run is also reported. Runtime measures the computational efficiency of the
I believe runtime should be monospaced and followed by a – here but please double check.

2024-07-16 20:45 UTC, JuanCab commented on papers/benchmarking/main.tex
> +\end{table}
I suggest moving tables 1 and 2 to after the Experimental Setup section below.  They appeared here without the text to explain them before them...

Also, should the Sunspot Activity and US Births have had `step_length` of 395 or 365?  Just curious why they are different from `window_length` whereas in the Australian Electricity Demand the two parameters are the same.

2024-07-16 20:45 UTC, JuanCab commented on papers/benchmarking/main.tex
> +To enable easy replication of the experiments, we provide for each used forecaster, and wrapper the hyperparameters by providing the used python object instantiation in Table~\ref{tab:hyperparams}. T
There are two references to "hyperparameter" in this paragraph that seem to refer to multiple "hyperparameters".  Also, the sentence "These hyperparameter depend on the dataset, especially, the seasonal periodicity (sp) is chosen based on the dataset." reads strangely and I am not sure of your intent.  Can you clarify the prose?

2024-07-16 20:45 UTC, JuanCab commented on papers/benchmarking/main.tex
> +    \item \textbf{Australian Electricity Demand \cite{Godahewa2021Australian}}: Half-hourly electricity demand data for five series in Australia, useful for high-frequency data evaluation.
"five series" OF WHAT in Australia?  Not clear.

2024-07-16 20:45 UTC, JuanCab commented on papers/benchmarking/main.tex
> +    \item \textbf{US Births \cite{Godahewa2021USBirth}}: Daily birth records in the United States, with a clear seasonal pattern, suitable for daily data performance assessment.
I note again the three different references to data sets here render as identical.  This is likely a Curvenote issue.

2024-07-16 20:45 UTC, JuanCab commented on papers/benchmarking/main.tex
> +The ranked based evaluation show that diverse results regarding the different metrics. E.g. while CI Empirical Residual performs best on CRPS, it is only mediocre regarding the Pinball Loss and the A
You have an error, at least if I read Table 4 correctly:  " On PinballLoss, the best method is CI Empirical and on AUCalibration, it is **Moving Block Bootstrap** (not Squaring Residuals)"

Also, you clearly cut/paste the phrase "Regarding the runtime, the fastest method is the fallback probabilistic prediction of the base forecaster. The slowest methods are NaiveVariance and SquaringResiduals. Furthermore, it seems that the ConformalIntervals are slightly faster than the **BaggingForecasters**" (note the misspelling of last word) to describe the three models you fit.  This was probably because you expected to have to edit it and then discovered the results were the same in all three cases.  Since the results were the same, I would suggest cutting that text out here and using it ONCE to describe all three models afterward.

2024-07-16 20:45 UTC, JuanCab commented on papers/benchmarking/main.tex
> +Furthermore, it seems that the ConformalIntervals are slightly faster than the BasggingForecasters.
Consider removing "Regarding the runtime, the fastest method is the fallback probabilistic prediction of the base forecaster. The slowest methods are NaiveVariance and SquaringResiduals.  Furthermore, it seems that the ConformalIntervals are slightly faster than the BasggingForecasters." since it is a repeat phrase (including the typo).  See previous comment.

2024-07-16 20:45 UTC, JuanCab commented on papers/benchmarking/main.tex
> +Regarding the AUCalibration, the best score is achieved by CI Conformal. Regarding the runtime, the fastest method is the fallback probabilistic prediction of the base forecaster. The slowest methods
Consider removing "Regarding the runtime, the fastest method is the fallback probabilistic prediction of the base forecaster. The slowest methods are NaiveVariance and SquaringResiduals.  Furthermore, it seems that the ConformalIntervals are slightly faster than the BasggingForecasters." since it is a repeat phrase (including the typo).  See previous comment.

2024-07-16 20:45 UTC, JuanCab commented on papers/benchmarking/main.tex
> +Our experiments demonstrate that the benchmarking framework in \texttt{sktime} provides an easy-to-use solution for reproducible benchmarks. We showed this by conducting simple benchmark studies of p
Didn't you test "three" different systems, not "two"?

2024-07-16 20:45 UTC, JuanCab requested changes
This paper was genuinely interesting although a bit challenging for me to read.  I am machine learning "adjacent" as a domain in that I am aware of a lot of ML ideas but have not actually used ML extensively outside of classwork. I am aware of some of the challenges in applying machine leaning techniques to time series data.

This paper provided a reasonable review of the `sktime` package for Python while demonstrating some of its capabilities through a set of three test cases covering different time spans and time scales. It is generally logically structured and its narrative makes sense.  That said, it does have a few (small) flaws that I believe should be addressed before the paper is accepted for the proceedings.  The most repeated flaw is the use of ML jargon. Given the audience of the SciPy Proceedings are cross-disciplinary and cover a wide range of programming domains, I believe the jargon needs to be explained after its first use.  I have noted all the cases of this issue I ran across in my review.  I tried to be a little "harder" during the introductory part of the paper since that is more likely to be read by someone to gauge if they could follow the rest of the paper.

The other issue is the authors' use of LaTeX or rather the issues Curvenote seems to be having with there LaTeX. The document seems to be having mis-rendering issues.  First, many references to sections of the paper being shown as "?" (which apparently was [already caught by another reviewer](https://github.com/scipy-conference/scipy_proceedings/pull/915/files#r1646652574) who suggested a fix to this problem).  Secondly, references to bibtex citations that got mangled (notably in line 28 of main.tex, there are three separate references to three different papers (Godahewa2021Australian, Godahewa2021Sunspot, and Godahewa2021USBirth) that are all referred to as Godahewa et al 2021 in the rendered paper. I have noted this issue with the references but understand it may be beyond the power of the authors to fix the rendering issue and that this may need to be addressed by Curvenote.  

I have tried to note all the cases of the above problems in this paper via individual comments.

There is also another issue in that GitHub's review system is not designed for documents with lines as long as those shown in this latex document, but that is not really the authors' fault.  It does make noting problems via the commenting interface a little bit tricky.

Finally, there were a LOT of figures related to benchmarking that were submitted with this pull request that are not referenced in the paper.  I assume as they are not necessarily particularly enlightening, they were dropped, but they should be removed from the pull request as well.  I have noted them with individual comments.

And while I have found a lot of "issues" with this paper I want to point out I really hope they are addressed, particularly the issues with jargon, because this paper describes a very interesting toolkit and if it had less jargon, it would be an excellent way to make more scientific programmers aware of the possibilities of time-series machine learning and prediction.

** Code review**

I was unable to test the code snippets shown in part because the `import` necessary to run them was not shown.  I did experiment and review the documentation for sktime to determine that the proper import line was `from sktime.forecasting.naive import NaiveForecaster` but even then without sample time-series data, I could NOT run the code to test it.  I strongly suggest the authors show the import statements at least and really they should provide a data file to test these code snippets with.

I've noted these issues in individual comments as well.

2024-07-20 18:33 UTC, cbcunc commented
@rowanc1 @stevejpurves @fwkoch Would you please recommend solutions to the rendering problems @JuanCab called out above?

2024-07-20 18:48 UTC, fwkoch commented on papers/benchmarking/main.tex
> +We conducted experiments on several common datasets, including Australian electricity demand \cite{Godahewa2021Australian}, sunspot activity \cite{Godahewa2021Sunspot}, and US births \cite{Godahewa20
Thanks @JuanCab - yes, this is an existing bug in MyST https://github.com/jupyter-book/mystmd/issues/272 - The links are still unique, but the text is duplicated. I will address this before the final proceedings are published! @benHeid - You can leave this as-is!

2024-07-20 19:08 UTC, fwkoch commented
There are 2 issues @JuanCab noted that are caused by MyST (and therefore present in the Curvenote preview):

- Duplicate citation text for different citations - this is a known issue. There is nothing the author can currently do to address it, but I will make sure it is fixed before the final proceedings site goes live.
- Section references being rendered as "??" - The author _can_ fix this if they update their `myst.yml` file as I suggested in my review (which @JuanCab also linked to). However, Curvenote will also include my suggested change in the final proceedings site, so it is not critical that the author addresses this.

Much more important that @benHeid (1) add the missing citations to their bibtex and (2) address the content-related suggestions from @JuanCab's thoughtful review.

2024-07-22 17:50 UTC, benHeid commented on papers/benchmarking/main.tex
> +Additionally, the \texttt{R/fable} package \cite{hyndman2020package} has contributed similar concepts specifically tailored to forecasting, which \texttt{sktime} has expanded upon or adapted to fit w
Done

2024-07-22 17:51 UTC, benHeid commented on papers/benchmarking/main.tex
> +The remainder of this paper is organized as follows: In Section \ref{methods}, we describe the forecasting methods and probabilistic wrappers used in our experiments. Section \ref{datasets} provides
Done

2024-07-22 18:04 UTC, benHeid commented on papers/benchmarking/Figures/elec_T1_PinballLoss_mean.png
Removed

2024-07-22 18:04 UTC, benHeid commented on papers/benchmarking/Figures/elec_T1_IntervalWidth_mean.png
Removed

2024-07-22 18:04 UTC, benHeid commented on papers/benchmarking/Figures/elec_T1_EmpiricalCoverage_mean.png
Removed

2024-07-22 18:04 UTC, benHeid commented on papers/benchmarking/Figures/elec_T1_CRPS_mean.png
Removed

2024-07-22 18:04 UTC, benHeid commented on papers/benchmarking/Figures/elec_T1_AUCalibration_mean.png
Removed

2024-07-22 18:04 UTC, benHeid commented on papers/benchmarking/Figures/birth_runtime_secs.png
Removed

2024-07-22 18:04 UTC, benHeid commented on papers/benchmarking/Figures/birth_IntervalWidth_mean.png
Removed

2024-07-22 18:04 UTC, benHeid commented on papers/benchmarking/Figures/birth_PinballLoss_mean.png
Removed

2024-07-22 18:04 UTC, benHeid commented on papers/benchmarking/Figures/birth_EmpiricalCoverage_mean.png
Removed

2024-07-22 18:05 UTC, benHeid commented on papers/benchmarking/Figures/birth_CRPS_mean.png
Removed

2024-07-22 18:05 UTC, benHeid commented on papers/benchmarking/Figures/birth_AUCalibration_mean.png
Removed

2024-07-22 18:05 UTC, benHeid commented on papers/benchmarking/Figures/elec_T1_runtime_secs.png
Removed

2024-07-22 18:05 UTC, benHeid commented on papers/benchmarking/Figures/elec_T2_AUCalibration_mean.png
Removed

2024-07-22 18:05 UTC, benHeid commented on papers/benchmarking/Figures/elec_T2_CRPS_mean.png
Removed

2024-07-22 18:05 UTC, benHeid commented on papers/benchmarking/Figures/elec_T2_EmpiricalCoverage_mean.png
Removed

2024-07-22 18:05 UTC, benHeid commented on papers/benchmarking/Figures/elec_T2_IntervalWidth_mean.png
Removed

2024-07-22 18:05 UTC, benHeid commented on papers/benchmarking/Figures/elec_T2_PinballLoss_mean.png
Removed

2024-07-22 18:05 UTC, benHeid commented on papers/benchmarking/Figures/elec_T2_runtime_secs.png
Removed

2024-07-22 18:05 UTC, benHeid commented on papers/benchmarking/Figures/elec_T3_AUCalibration_mean.png
Removed

2024-07-22 18:06 UTC, benHeid commented on papers/benchmarking/Figures/elec_T3_CRPS_mean.png
Removed

2024-07-22 18:06 UTC, benHeid commented on papers/benchmarking/Figures/elec_T3_EmpiricalCoverage_mean.png
Removed

2024-07-22 18:06 UTC, benHeid commented on papers/benchmarking/Figures/elec_T3_PinballLoss_mean.png
Removed

2024-07-22 18:06 UTC, benHeid commented on papers/benchmarking/Figures/elec_T3_runtime_secs.png
Removed

2024-07-22 18:06 UTC, benHeid commented on papers/benchmarking/Figures/elec_T4_AUCalibration_mean.png
Removed

2024-07-22 18:06 UTC, benHeid commented on papers/benchmarking/Figures/elec_T4_CRPS_mean.png
Removed

2024-07-22 18:06 UTC, benHeid commented on papers/benchmarking/Figures/elec_T4_EmpiricalCoverage_mean.png
Removed

2024-07-22 18:06 UTC, benHeid commented on papers/benchmarking/Figures/elec_T4_IntervalWidth_mean.png
Removed

2024-07-22 18:06 UTC, benHeid commented on papers/benchmarking/Figures/elec_T4_PinballLoss_mean.png
Removed

2024-07-22 18:06 UTC, benHeid commented on papers/benchmarking/Figures/elec_T4_runtime_secs.png
Removed

2024-07-22 18:07 UTC, benHeid commented on papers/benchmarking/Figures/elec_T5_AUCalibration_mean.png
Removed

2024-07-22 18:07 UTC, benHeid commented on papers/benchmarking/Figures/elec_T5_CRPS_mean.png
Removed

2024-07-22 18:07 UTC, benHeid commented on papers/benchmarking/Figures/elec_T5_EmpiricalCoverage_mean.png
Removed

2024-07-22 18:07 UTC, benHeid commented on papers/benchmarking/Figures/elec_T5_IntervalWidth_mean.png
Removed

2024-07-22 18:07 UTC, benHeid commented on papers/benchmarking/Figures/elec_T5_PinballLoss_mean.png
Removed

2024-07-22 18:07 UTC, benHeid commented on papers/benchmarking/Figures/elec_T5_runtime_secs.png
Removed

2024-07-22 18:07 UTC, benHeid commented on papers/benchmarking/Figures/sunspot_AUCalibration_mean.png
Removed

2024-07-22 18:07 UTC, benHeid commented on papers/benchmarking/Figures/sunspot_CRPS_mean.png
Removed

2024-07-22 18:07 UTC, benHeid commented on papers/benchmarking/Figures/sunspot_EmpiricalCoverage_mean.png
Removed

2024-07-22 18:07 UTC, benHeid commented on papers/benchmarking/Figures/sunspot_IntervalWidth_mean.png
Removed

2024-07-22 18:07 UTC, benHeid commented on papers/benchmarking/Figures/sunspot_PinballLoss_mean.png
Removed

2024-07-22 18:08 UTC, benHeid commented on papers/benchmarking/Figures/sunspot_runtime_secs.png
Removed

2024-07-22 18:08 UTC, benHeid commented on papers/benchmarking/frog.jpg
Removed

2024-07-22 18:13 UTC, benHeid commented on papers/benchmarking/main.tex
> +which can be used to copy a full specification from a research paper and immediately construct the respective algorithm in a python environment, even if full code has not been shared by the author.
Done

2024-07-22 18:13 UTC, benHeid commented on papers/benchmarking/main.tex
> +To enable easy replication of the experiments, we provide for each used forecaster, and wrapper the hyperparameters by providing the used python object instantiation in Table~\ref{tab:hyperparams}. T
Done

2024-07-22 18:17 UTC, benHeid commented on papers/benchmarking/main.tex
> +Creating algorithms with compatible APIs is straightforward.
I agree, I removed the line

2024-07-22 18:17 UTC, benHeid commented on papers/benchmarking/main.tex
> +\texttt{sktime} and \texttt{tsbootstrap} provide fill-in extension templates for creating algorithms in a compatible interface, which can be shared in a third-party code base and indexed by \texttt{s
I added the link to https://github.com/sktime/sktime/tree/main/extension_templates

2024-07-22 18:18 UTC, benHeid commented on papers/benchmarking/main.tex
> +Additionally, the \texttt{R/fable} package \cite{hyndman2020package} has contributed similar concepts specifically tailored to forecasting, which \texttt{sktime} has expanded upon or adapted to fit w
Thank you, I added this reference now :)

2024-07-22 18:19 UTC, benHeid commented on papers/benchmarking/main.tex
> +    \item \texttt{BaggingForecaster(bootstrap\_transformer, forecaster)}: Provides probabilistic forecasts by bootstrapping time series and aggregating the bootstrap forecasts \cite{hyndman2018, berg
I added the reference

2024-07-22 18:27 UTC, benHeid commented on papers/benchmarking/main.tex
> +The design principles of \texttt{sktime} draw inspiration from several established machine learning frameworks. Notably, \texttt{scikit-learn} in \texttt{python} \cite{pedregosa2011scikit}, \texttt{m
I aggree

2024-07-22 18:35 UTC, benHeid commented on papers/benchmarking/main.tex
> +More details can be found in the official tutorials.
Thank you. Yes this is the correct link. I added it.

2024-07-22 18:41 UTC, benHeid commented on papers/benchmarking/main.tex
> +\end{itemize}
I completely agree and moved the sktime item as described. 

I also added the missing references

2024-07-22 18:45 UTC, benHeid commented on papers/benchmarking/main.tex
> +Our experiments demonstrate that the benchmarking framework in \texttt{sktime} provides an easy-to-use solution for reproducible benchmarks. We showed this by conducting simple benchmark studies of p
I agree. I changed it

2024-07-22 19:29 UTC, benHeid commented on papers/benchmarking/main.tex
> +Our paper is accompanied by easily reusable code, and we invite the open research and open-source communities to contribute to extending our experiments or using our code to set up their own. As is o
I ensured that all larger code snippets work as standalone code. 

I removed the SciPy monospace

* [ ] I will create a repository containing the exoerimental code. An alternative would be to include  the code in a dedicated section.

2024-07-23 16:32 UTC, benHeid commented on papers/benchmarking/main.tex
> +Forecasters are objects with \texttt{fit} and \texttt{predict} methods, allowing both endogenous and exogenous data to be passed. For example, the following code specifies a forecaster, fits it, and
I have rewritten it and put the ML/foreaster jargon in brackets so that these are still mentioned.

2024-07-23 16:32 UTC, jameslamb commented
👋🏻 I'll provide a review tonight. I've read all of the review comments so far and agreed with them, will try to focus on other things and the most recent set of changes.

2024-07-23 16:54 UTC, benHeid commented on papers/benchmarking/main.tex
> +This method uses a window sliding and residual collection strategy.
I tried to clarified it.

2024-07-23 17:08 UTC, benHeid commented on papers/benchmarking/main.tex
> +This creates a forecasting algorithm that first computes first differences, then deseasonalizes with periodicity 12, then applies the last-value-carry-forward method, reseasonalizes, and inverts the
`last-value-carry-forward method` just means that the last value is used as a prediction. I clarified it and also tried to mitigate jargon.

2024-07-23 17:09 UTC, benHeid commented on papers/benchmarking/main.tex
> +This hybrid use of \texttt{sktime} as a framework covering first-party (itself), second-party (\texttt{tsbootstrap}), and third-party (\texttt{statsmodels}, \texttt{statsforecast}) locations is signi
Clarified. Credit for implementing their package.

2024-07-24 07:18 UTC, jameslamb reviewed
Thanks very much for the opportunity to review this paper. I found it really interesting, and I'd like to try this library out some time.

Maybe we could even talk in the future about adding a `LightGBMForecaster`... some people seem quite fond of using `LightGBM` for forecasting problems (e.g. ["M5 accuracy competition: results, findings, and conclusions" (Makridakis et. al, 2021)](https://www.sciencedirect.com/science/article/pii/S0169207021001874)), even though tree-based models tend to struggle with extrapolation.

Anyway... the review!

----

I agree with all of @JuanCab 's suggestions. I tried to focus on other areas, and to not make minor stylistic or grammatical recommendations other than unambiguous typos.

----

I tested all the inline code snippets using Python 3.10 and `sktime==0.31.0`... found that they all ran successfully, except for one small typo which I've added a comment about. Thanks for taking the time to make minimal, reproducible examples 😊 

----

Leaving a "comment" review instead of "approve" because I would like to see my recommendations addressed, but none are so major that they should block merging this.

I don't have any additional high-level comments. I think this paper is a very good addition to the conference proceedings.

Thanks for all of your hard work on this paper and these open source projects!

2024-07-24 07:18 UTC, jameslamb commented on papers/benchmarking/main.tex
> +In \texttt{sktime} and \texttt{tsbootstrap}, algorithms and mathematical objects are treated as first-class citizens. All objects of the same type, such as forecasters, follow the same interface. Thi
`tsbootstrap` is not introduced in the abstract or in Section 1.

Could you please briefly introduce it and its relationship to `sktime`? It was quite distracting to have it be mentioned in this section but then:

* not used at all in the code sample in this section
* not obviously present in the link further down (*"sktime and tsbootstrap provide fill-in [extension templates](https://github.com/sktime/sktime/tree/main/extension_templates)"*)

I searched through the paper and found it is not actually defined at all in Section 2... it's linked to, with a brief description, in Section 3.

I might say something like the following in the beginning of Section 2. Or maybe even in Section 1, as `tsbootstrap` is in the title of the paper.

> *This work is aided by `tsbootstrap` ([code repository](https://github.com/astrogilda/tsbootstrap)), a Python library which provides methods to generate synthetic time-series data.*

2024-07-24 07:18 UTC, jameslamb commented on papers/benchmarking/main.tex
> +Currently, \texttt{sktime} supports the construction of 82 individual forecasters, either implemented within the package or interfaced from other packages in the ecosystem. Each forecaster is paramet
I do not understand what "interfaced from other packages in the ecosystem" means or where the number 82 comes from.

With `sktime==0.31.0` (the latest version as of this review), this snippet:

```python
from sktime.registry import all_estimators
print(all_estimators())
```

Returns a Python list object containing **417** classes.

At first I thought this referred to forecasters following the `sktime` API prescriptions, but distributed via other libraries. But after following the source code of `sktime.registry.all_estimators` ([code link](https://github.com/sktime/sktime/blob/7bb08dbe568237f77e4f11a837fe85d8cee41484/sktime/registry/_lookup.py#L42)), that does not seem to be the case. `all_estimators()` prints a list of Python classes which all appear to live in the `sktime` namespace.

But then again, I also see that the library imports others libraries which can produce timeseries forecasts, like `prophet` and `gluonts` ([pyproject.toml](https://github.com/sktime/sktime/blob/7bb08dbe568237f77e4f11a837fe85d8cee41484/pyproject.toml#L79)). Is the following accurate? I'd personally find it easier to understand.

> *... construction of 82 individual forecasters. Some of these are implemented directly in `sktime`, but `sktime` also provides adapters providing a unified API to forecasting routines from other libraries, such as `gluonts` and `prophet`.*

----

Similarly, I am not sure what "or filtered" in the statement about `all_estimators()` means.

I think it would be helpful to include a code snippet using `sktime.registry.all_estimators` which:

* returns the same number of forecasters as mentioned in the paragraph (for the latest version of `sktime`)
* demonstrates at least 1 example of what is meant by "filtered"

2024-07-24 07:18 UTC, jameslamb commented on papers/benchmarking/main.tex
> +forecaster = craft('NaiveForecaster(strategy="last", sp=12)')
I was very confused by this, because that string passed to `craft()` looks like it would be valid Python code. What is the purpose of `craft()` beyond avoiding the need to specify `import` statements?

This might be more impactful with a more complex example, and ideally one where the string has some obvious deviation from syntactically-valid Python code.

Or, alternatively, could you maybe show examples with and without `craft()` which generate the same forecaster in memory?

2024-07-24 07:18 UTC, jameslamb commented on papers/benchmarking/main.tex
> +This creates a forecasting algorithm that first computes differences, then remove the seasonality (deseasonalize) by assuming a periodicity of 12,
```suggestion
This creates a forecasting algorithm that first computes differences, then removes the seasonality (deseasonalize) by assuming a periodicity of 12, 
```

2024-07-24 07:18 UTC, jameslamb commented on papers/benchmarking/main.tex
> +then the \texttt{NaiveForecasster(strategy="last")} uses the last value as prediction for the next values (last-value-carry-forward method), finally it adds the seasonality back
```suggestion
then the \texttt{NaiveForecaster(strategy="last")} uses the last value as prediction for the next values (last-value-carry-forward method), finally it adds the seasonality back
```

2024-07-24 07:18 UTC, jameslamb commented on papers/benchmarking/main.tex
> +    estimator=NaiveForecasster(strategy="last", sp=12),
```suggestion
    estimator=NaiveForecaster(strategy="last", sp=12),
```

Without this fix, in v0.31.0, with the following error:

```text
Traceback (most recent call last):
  File "<stdin>", line 2, in <module>
NameError: name 'NaiveForecasster' is not defined. Did you mean: 'NaiveForecaster'?
```

2024-07-24 07:18 UTC, jameslamb commented on papers/benchmarking/main.tex
> +Currently, \texttt{sktime} supports the construction of 82 individual forecasters, either implemented within the package or interfaced from other packages in the ecosystem. Each forecaster is paramet
Updated comment (reading further).... the meaning of "interfaced from other packages in the ecosystem" is quite clearly explained at the beginning of Section 3 ("Algorithmic Setup").

*(the paragraph beginning "From a software perspective it is worth noting that sktime [Löning et al. (2019)](https://doi.org/10.48550/arXiv.1909.07872)[Király et al. (2024)](https://doi.org/10.5281/zenodo.11095261) contains multiple native implementations...")*

I think it'd be preferable for the language here about how many total forecasters are supported, and that language explaining the different between first-party, second-party, and third-party, to be in the same place. Section 1 would be best, I think.... `tsbootstrap` is in the title of the paper but what it actually is is not defined until the beginning of Section 3.

So, my recommendation..... move this to Section 1:

<img width="886" alt="image" src="https://github.com/user-attachments/assets/d0630ed3-c194-460b-8077-f69b55b14774">

2024-07-24 07:18 UTC, jameslamb commented on papers/benchmarking/main.tex
> +The ranked based evaluation show that diverse results regarding the different metrics. E.g. while CI Empirical Residual performs best on CRPS, it is only mediocre regarding the Pinball Loss and the A
```suggestion
The ranked based evaluation show that diverse results regarding the different metrics. E.g. while CI Empirical Residual performs best on CRPS, it is only mediocre regarding the Pinball Loss and the AUCalibration. On PinballLoss, the best method is CI Empirical and on AUCalibration, it is Squaring Residuals. Regarding the runtime, the fastest method is the fallback probabilistic prediction of the base forecaster. The slowest methods are NaiveVariance and SquaringResiduals. Furthermore, it seems that the ConformalIntervals are slightly faster than the BaggingForecasters.
```

There is also a typo on this line.

2024-07-24 07:18 UTC, jameslamb commented on papers/benchmarking/main.tex
> +Furthermore, it seems that the ConformalIntervals are slightly faster than the BasggingForecasters.
```suggestion
The ranked based evaluation show that BaggingForecaster with the Block Distribution Bootstrap scores clearly best regarding the CRPS and Pinball Loss, and AUCalibration. Regarding the runtime, the fastest method is the fallback probabilistic prediction of the base forecaster. The slowest methods are NaiveVariance and SquaringResiduals. 
Furthermore, it seems that the ConformalIntervals are slightly faster than the BaggingForecasters. 
```

If it is not removed... there's a typo here.

2024-07-24 07:18 UTC, jameslamb commented on papers/benchmarking/main.tex
> +Regarding the AUCalibration, the best score is achieved by CI Conformal. Regarding the runtime, the fastest method is the fallback probabilistic prediction of the base forecaster. The slowest methods
```suggestion
Regarding the AUCalibration, the best score is achieved by CI Conformal. Regarding the runtime, the fastest method is the fallback probabilistic prediction of the base forecaster. The slowest methods are NaiveVariance and SquaringResiduals. Furthermore, it seems that the ConformalIntervals are slightly faster than the BaggingForecasters. 
```

2024-08-04 09:31 UTC, benHeid commented on papers/benchmarking/main.tex
> +Bootstrapping methods generate multiple resampled datasets from the original time series data, which can be used as part of wrappers to estimate prediction intervals or predictive distributions. In t
Thank you. I try to clarify the other jargons similar to this.

2024-08-04 09:47 UTC, benHeid commented on papers/benchmarking/main.tex
> +Probabilistic forecasters are tagged with the \texttt{"capability:pred\_int"} tag. Currently, 45 of the 82 forecasters support probabilistic prediction modes, such as prediction intervals, quantile p
I added an explanation of the tag system

2024-08-04 09:51 UTC, benHeid commented on papers/benchmarking/main.tex
> +All forecasters are point forecasters, combined with one of the probabilistic wrappers to generate prediction intervals and probabilistic forecasts.
I added an explanation of point forecasters

2024-08-04 09:59 UTC, benHeid commented on papers/benchmarking/main.tex
> +Each forecaster is wrapped in a \texttt{Differencer} and a \texttt{Deseasonalizer} as preprocessing steps to improve stationarity. These preprocessors are necessary because some forecasters require t
I added an explanation

2024-08-04 10:05 UTC, benHeid commented on papers/benchmarking/main.tex
> +    \item \texttt{IntervalWidth} - width of prediction intervals, or sharpness measures the concentration of the prediction intervals. More concentrated intervals indicate higher confidence in the fo
I removed it. Since it is not required here.

2024-08-04 10:05 UTC, benHeid commented on papers/benchmarking/main.tex
> +    \item \texttt{EmpiricalCoverage} - Empirical coverage measures how much of the observations are within the predicted interval. It is computed as the proportion of observations that fall within th
I replaced the jargon here.

2024-08-04 10:15 UTC, benHeid commented on papers/benchmarking/main.tex
> +\end{table}
Thank you. I moved the tables. 

Regarding the step lengths, we selected 395 instead of 365 so that not only the same seasonality of the time series is covered in the test splits. When using a length of 365 (12 month) always the same month (of different years) would be the test split. For the Australian electricity demand dataset, the step length is unequal to the seasonality, so we used the same as for the window length

2024-08-04 10:34 UTC, benHeid commented on papers/benchmarking/main.tex
> +To enable easy replication of the experiments, we provide for each used forecaster, and wrapper the hyperparameters by providing the used python object instantiation in Table~\ref{tab:hyperparams}. T
I have rewritten it. Hopefully, it is now easier to understand.

2024-08-04 10:37 UTC, benHeid commented on papers/benchmarking/main.tex
> +    \item \textbf{Australian Electricity Demand \cite{Godahewa2021Australian}}: Half-hourly electricity demand data for five series in Australia, useful for high-frequency data evaluation.
Thank you for the remark. These are time series of five states of Australia. I added the five states.

2024-08-04 14:57 UTC, benHeid commented on papers/benchmarking/main.tex
> +The ranked based evaluation show that diverse results regarding the different metrics. E.g. while CI Empirical Residual performs best on CRPS, it is only mediocre regarding the Pinball Loss and the A
Thank you for the hints. There was an error in the text. The table was correct. I fixed it.

2024-08-04 15:03 UTC, benHeid commented on papers/benchmarking/main.tex
> +This design pattern is consistent across all forecasters in \texttt{sktime}, and called the "strategy pattern" in software engineering.
I agree that this explanation might be confusing. We referred to the fact that the forecasters in the user's code are exchangeable. However, this is already described in the previous sentence. Thus, I removed the sentence.

2024-08-04 15:27 UTC, benHeid commented on papers/benchmarking/main.tex
> +Currently, \texttt{sktime} supports the construction of 82 individual forecasters, either implemented within the package or interfaced from other packages in the ecosystem. Each forecaster is paramet
Thank you for the suggestion. It makes definitely more sense to move the explanation of first, second, third party to the introduction. 

I also added an example code for the `all_estimators`method with and without filtering.

2024-08-04 15:57 UTC, benHeid commented on papers/benchmarking/main.tex
> +In \texttt{sktime} and \texttt{tsbootstrap}, algorithms and mathematical objects are treated as first-class citizens. All objects of the same type, such as forecasters, follow the same interface. Thi
Thank you for your proposal. I added an explanation why tsbootstrap is used in the introduction.

2024-08-04 16:05 UTC, benHeid commented on papers/benchmarking/main.tex
> +    \item \texttt{ConformalIntervals(forecaster, strategy)}: Uses conformal prediction methods \cite{Stankeviciute2021} to produce non-parametric prediction intervals. Variants of the method are sele
I added a reference to bonferroni correction

2024-08-04 16:11 UTC, benHeid commented on papers/benchmarking/main.tex
> +    \item \texttt{BlockDistributionBootstrap}: Generates bootstrapped samples by fitting a distribution to the residuals of a model and then generating new residuals from the fitted distribution. Thi
Yes, the residuals are added back to the fitted values of the model. I added a sentence to make it clearer.

2024-08-04 16:20 UTC, fkiraly commented on papers/benchmarking/main.tex
> +forecaster = craft('NaiveForecaster(strategy="last", sp=12)')
> What is the purpose of craft() beyond avoiding the need to specify import statements?

There is a high-level and low-level answer to this.

The high-level answer is, it enables reproducibility workflows by allowing the strings to be shared as artefacts, together with an environment freeze, see this tutorial:
https://github.com/sktime/sktime-workshop-pydata-prague-2023/blob/main/notebooks/05_evaluation_and_benchmarking.ipynb

The lower-level answer relates to the concept of serialization and deserialization, to make the "blueprint" unique.

* the `craft` method is a deserialization inverse to string coercion. With a pip freeze as context, this becomes a unique inverse, as the `sktime` namespace is unique.
* as a "convenience" feature, `craft` also allow larger code blocks with variable references to define an estimator. This can also be shared as a blueprint for a complex composite.

2024-08-04 16:24 UTC, fkiraly commented
> Maybe we could even talk in the future about adding a `LightGBMForecaster`...

Just as side info, @jameslamb, this can already be constructed by combining the `sklearn` interface of `lightgbm` with one of the reduction forecasters:
https://www.sktime.net/en/stable/api_reference/forecasting.html#direct-and-recursive-sktime-native-2nd-generation

2024-08-04 16:32 UTC, JuanCab commented on papers/benchmarking/main.tex
> +forecaster = craft('NaiveForecaster(strategy="last", sp=12)')
> > What is the purpose of craft() beyond avoiding the need to specify import statements?
> 
> 
> 
> There is a high-level and low-level answer to this.

Thank you for the thoughtful answer.  I was confused about this myself!

2024-08-04 17:22 UTC, benHeid commented on papers/benchmarking/main.tex
> +Despite the critical importance of evaluating probabilistic forecasts in various domains, including finance, energy, healthcare, and climate science, no comprehensive software framework or interface
I have added references to two papers showing the lack of reproducibility.

2024-08-04 17:23 UTC, benHeid commented on papers/benchmarking/main.tex
> +which can be used to copy a full specification from a research paper and immediately construct the respective algorithm in a python environment, even if full code has not been shared by the author.
See comment here: https://github.com/scipy-conference/scipy_proceedings/pull/915#discussion_r1703283975

2024-08-04 17:44 UTC, benHeid commented on papers/benchmarking/main.tex
> +Our paper is accompanied by easily reusable code, and we invite the open research and open-source communities to contribute to extending our experiments or using our code to set up their own. As is o
Link to repository: https://github.com/sktime/code_for_paper_scipyconf24/tree/main

2024-08-04 17:51 UTC, benHeid commented
@jameslamb @JuanCab thank you very much for your extensive reviews. I think you addressed very valid points in the manuscript, which we tried to address. So I think that your reviews improved this manuscript clearly. 

If there is still something unclear, please comment on this PR. 

FYI. We commented on all of your comments to make it transparent on how we addressed the review comment.

2024-08-05 01:52 UTC, jameslamb commented on papers/benchmarking/main.tex
> +forecaster = craft('NaiveForecaster(strategy="last", sp=12)')
Thanks. The details you've shared here make the purpose of this function, and the reason for this functionality in `sktime`, much clearer than the example in the paper. Please do consider expanding on this in the paper, specifically in `2.2. - Reproducible Specification Language`.

The serialization format looking like like Python code led me to the (incorrect) conclusion that it literally **was** Python code. I suspect some other readers who are unfamiliar with `sktime` might also come to that come conclusion from reading this.

I think a more complex example, and a brief description of how the format intentionally looks like Python but is not actually `eval()`'d as Python, would be helpful to avoid such misunderstandings.

2024-08-05 01:54 UTC, jameslamb commented
Thank you very much @benHeid and @fkiraly for so thoroughly and thoughtfully considering the feedback. I don't have any further comments on this paper.

I would "approve" if I could, but it appears I don't have sufficient permissions here.

<img width="322" alt="Screenshot 2024-08-04 at 8 53 43 PM" src="https://github.com/user-attachments/assets/7504aea4-998d-428f-a61e-98d8e5b99816">

2024-08-05 21:37 UTC, JuanCab requested changes
Almost all the issues I am aware of have been addressed as of today (August 5), there are few typos I noted that should be fixed, but if those typo corrections are made, I can approve this as a peer reviewer.

2024-08-05 21:37 UTC, JuanCab commented on papers/benchmarking/main.tex
> +This hybrid use of \texttt{sktime} as a framework covering first-party (itself), second-party (\texttt{tsbootstrap}), and third-party (\texttt{statsmodels}, \texttt{statsforecast}) locations is signi
I honestly don't know if the use of `locations` is grammatically correct in this sentence, I would have used `packages`.  Not demanding a correction, just a double-check to confirm this.

2024-08-05 21:37 UTC, JuanCab commented on papers/benchmarking/main.tex
> +Forecasters are objects with \texttt{fit} and \texttt{predict} methods, allowing both the target time series (endogenous data) and the time series that influence the target time series (exogenous dat
Much nicer!  Thanks!

2024-08-05 21:37 UTC, JuanCab commented on papers/benchmarking/main.tex
> +y_pred = forecaster.predict()
Thank you for adding this code, when I ran it I did get a warning (but it did complete).  The warning was:
```
~/miniconda3/envs/reviewer915/lib/python3.12/site-packages/numpy/_core/getlimits.py:227: RuntimeWarning: invalid value encountered in exp2
  epsneg_f128 = exp2(ld(-113))
 ** On entry to DLASCLS parameter number  4 had an illegal value
 ** On entry to DLASCLS parameter number  4 had an illegal value
```
Not a show stopper (and much better than what code was present before, but just noting it.

2024-08-05 21:37 UTC, JuanCab commented on papers/benchmarking/main.tex
> +A crucial design element in the above is that the first line can specify any forecaster - for instance, \texttt{ARIMA} or \texttt{ExponentialSmoothing},
I don't think it is the "first line" any more, can I assume you mean line 9 which reads
```
forecaster = NaiveForecaster(strategy="last", sp=12)
```

2024-08-05 21:37 UTC, JuanCab commented on papers/benchmarking/main.tex
> +To better filter the forecasters (as well as the other estimators such as classifiers and regressors) based on their properties and capabilities and to control their behaviour, \texttt{sktime} implem
Much better and clearer (especially with that code snippet), thanks!

2024-08-05 21:37 UTC, JuanCab commented on papers/benchmarking/main.tex
> +
You might want to mention you are referring to the above code snippet or move that code snippet down here and directly refer to it more inline.

2024-08-05 21:37 UTC, JuanCab commented on papers/benchmarking/main.tex
> +y_pred_proba = forecaster.predict_proba()
Nice to have fully functional code, but I am realizing the code listings need captions otherwise it is hard to see what they connect to.

2024-08-05 21:37 UTC, JuanCab commented on papers/benchmarking/main.tex
> +The conformal prediction interval fits multiple instances of the wrapped forecaster on on parts of the time series using window sliding. In particular, each forecaster's instance $i$
Typo (repeated word)
```suggestion
The conformal prediction interval fits multiple instances of the wrapped forecaster on parts of the time series using window sliding. In particular, each forecaster's instance $i$
```

2024-08-05 21:37 UTC, JuanCab commented on papers/benchmarking/main.tex
> +This creates a forecasting algorithm that first computes differences, then remove the seasonality (deseasonalize) by assuming a periodicity of 12,
I agree with the suggested correction here although to avoid the run on sentence, I suggest a period to end this.
```suggestion
This creates a forecasting algorithm that first computes differences, then removes the seasonality (deseasonalize) by assuming a periodicity of 12.
```

2024-08-05 21:37 UTC, JuanCab commented on papers/benchmarking/main.tex
> +then the \texttt{NaiveForecaster(strategy="last")} uses the last value as prediction for the next values (last-value-carry-forward method), finally it adds the seasonality back
```suggestion
Then the \texttt{NaiveForecaster(strategy="last")} uses the last value as prediction for the next value (last-value-carry-forward method).  Finally it adds the seasonality back
```

2024-08-05 21:37 UTC, JuanCab commented on papers/benchmarking/main.tex
> +\end{verbatim}
Running this code crashed for me because
```
ModuleNotFoundError: Deseasonalizer requires package 'statsmodels' to be present in the python environment, but 'statsmodels' was not found. 'statsmodels' is a soft dependency and not included in the base sktime installation. Please run: `pip install statsmodels` to install the statsmodels package. To install all soft dependencies, run: `pip install sktime[all_extras]`
```
Not really a problem with the paper, but if you release the code separately, be sure to state a used needs to `pip install sktime[all_extras]`.

2024-08-05 21:37 UTC, JuanCab commented on papers/benchmarking/main.tex
> +Note the code for running the whole benchmark is provided in the Section~\ref{experiment}.
This reference rendered as `Section %s`,it should be as follows:
```suggestion
Note the code for running the whole benchmark is provided in the Section~\ref{experiments}.
```

2024-08-05 21:37 UTC, JuanCab requested changes
Almost all the issues I am aware of have been addressed as of today (August 5), there are few typos I noted that should be fixed, but if those typo corrections are made, I can approve this as a peer reviewer.

2024-08-06 18:22 UTC, benHeid commented on papers/benchmarking/main.tex
> +This hybrid use of \texttt{sktime} as a framework covering first-party (itself), second-party (\texttt{tsbootstrap}), and third-party (\texttt{statsmodels}, \texttt{statsforecast}) locations is signi
Thanks, packages is better

2024-08-06 18:26 UTC, benHeid commented on papers/benchmarking/main.tex
> +A crucial design element in the above is that the first line can specify any forecaster - for instance, \texttt{ARIMA} or \texttt{ExponentialSmoothing},
Thank you. You are right.

2024-08-06 18:29 UTC, benHeid commented on papers/benchmarking/main.tex
> +
I referred to the previous example

2024-08-06 18:32 UTC, benHeid commented on papers/benchmarking/main.tex
> +\end{verbatim}
Thank you for the hint. I added this in the requirements of the code

2024-08-06 19:00 UTC, benHeid commented on papers/benchmarking/main.tex
> +y_pred_proba = forecaster.predict_proba()
I agree. I added replaced the environments and added captions

2024-08-06 19:00 UTC, benHeid commented
> Almost all the issues I am aware of have been addressed as of today (August 5), there are few typos I noted that should be fixed, but if those typo corrections are made, I can approve this as a peer reviewer.

@JuanCab I fixed the typos and addressed the comments. Thank you again for the review :)

2024-08-07 19:50 UTC, JuanCab approved these changes
Only ONE issue, so I will mark this as approved, but you should fix it.

You marked as resolved but did not apply the corrections suggested for line 184 of your latex file.  Since you did apply the suggested correction for Line 185, it is now ungrammatical.

Fix line 184 currently reading
```
This creates a forecasting algorithm that first computes differences, then remove the seasonality (deseasonalize) by assuming a periodicity of 12, 
```
to read
```
This creates a forecasting algorithm that first computes differences, then removes the seasonality (deseasonalize) by assuming a periodicity of 12.
```
and the paper should be good to go!

2024-08-27 14:11 UTC, benHeid commented
> Only ONE issue, so I will mark this as approved, but you should fix it.
> 
> You marked as resolved but did not apply the corrections suggested for line 184 of your latex file. Since you did apply the suggested correction for Line 185, it is now ungrammatical.
> 
> Fix line 184 currently reading
> 
> ```
> This creates a forecasting algorithm that first computes differences, then remove the seasonality (deseasonalize) by assuming a periodicity of 12, 
> ```
> 
> to read
> 
> ```
> This creates a forecasting algorithm that first computes differences, then removes the seasonality (deseasonalize) by assuming a periodicity of 12.
> ```
> 
> and the paper should be good to go!

Thank you very much for all the efforts. I changed the comma to a point

2024-09-02 15:00 UTC, mepa commented
Hi @JuanCab, @jameslamb - Do you feel that this paper in its current form is ready for inclusion in the Proceedings?

From @JuanCab's PR approval and @jameslamb's comments (apologies for permissions issues) I will assume "yes" unless I hear back otherwise.

Thanks for reviewing!

2024-09-02 15:04 UTC, JuanCab commented
> Hi @JuanCab, @jameslamb - Do you feel that this paper in its current form is ready for inclusion in the Proceedings?

From my point of view, yes, it is ready!

2024-09-02 16:05 UTC, jameslamb commented
Yes, I think it is ready!

2024-09-25 17:18 UTC, merged