Paper: Mamba Models a replacement for Transformers?
scipy-conference/scipy_proceedings pull request #917
Opened 2024-05-31 16:11 UTC by JaynouOliver

If you are creating this PR in order to submit a draft of your paper, please name your PR with `Paper: <title>`. An editor will then add a `paper` label and GitHub Actions will be run to check and build your paper.

See the [project readme](https://github.com/scipy-conference/scipy_proceedings#preview-your-paper) for more information.

_Editor_:  

_Reviewers_:

2024-06-01 05:25 UTC, JaynouOliver commented
@hongsupshin is there any specific mistake from our side which led to curvenote checks getting skipped? Can't see the deployment preview.

2024-06-10 17:13 UTC, tkoyama010 commented
Hi. Thanks for invitation. I will review this paper :)

2024-06-11 13:21 UTC, HaoZeke commented
As per the email received yesterday from the Proc. Comm. I am happy to review this submission.

2024-06-21 17:12 UTC, JaynouOliver commented
Hi, @tkoyama010 @HaoZeke just wanted to know if there are any updates regardading the review, if we do have to make changes from here.

2024-06-23 12:38 UTC, tkoyama010 requested changes
Thank you for the great paper. State-space models are something I have used in my own career and I am amazed that they can be applied in this way. Is it possible to share the URL of the GitHub repository you used for this model in this paper? I am sure it would be even better if you could share it so we can actually implement this idea.

2024-06-23 21:37 UTC, JaynouOliver commented
I can share the code written originally by the authors of MAMBA https://github.com/state-spaces/mamba
Just wanted to check with you before I finally commit the changes

2024-06-24 08:17 UTC, tkoyama010 commented
Thanks, I was making that statement based on the fact that SciPy papers often emphasize being able to run the code and reproduce it. Do I need to run both Transformer and mamba to understand the results of this paper?

I think this paper could be an excellent introduction to mamba. To that end, I think it would be good to add a link to it appropriately (including Transformer) :)

2024-06-24 13:49 UTC, JaynouOliver commented
Sure I can add those links in the paper. I will make these changes right away.

2024-06-26 17:20 UTC, JaynouOliver commented
@tkoyama010 please add any further changes if needed after review.

2024-06-28 01:00 UTC, tkoyama010 requested changes

2024-06-28 01:00 UTC, tkoyama010 commented on papers/Suvrakamal_Das/mybib.bib
> +  url         = "https://github.com/state-spaces/mamba",
I'm sorry. In my operation, these URLs are not enabled in the Preview screen. Could you please check the operation to access it again, as I may have made a mistake?

2024-06-28 15:25 UTC, JaynouOliver commented on papers/Suvrakamal_Das/mybib.bib
> +  url         = "https://github.com/state-spaces/mamba",
I am having problems with DOIs, how do I not mention a github link DOI and pass the checks? 
I tried removing the checks, but it isn't working well.
Either I have to try pasting a DOI for a github link, else, I will have to remove the checks. 
Are there any other option?

2024-06-28 17:43 UTC, mepa commented
Hi @tkoyama010 and @HaoZeke! In case a little extra time is needed, the initial complete review deadline has been extended to next [Wednesday, July 3rd](https://github.com/scipy-conference/scipy_proceedings/blob/2024/README.md#instructions-for-reviewers).

2024-06-28 18:37 UTC, mepa commented on papers/Suvrakamal_Das/mybib.bib
> +  url         = "https://github.com/state-spaces/mamba",
Please see the sections "DOIs in bibliographies" and "Citing software and websites" in the [example paper](https://github.com/scipy-conference/scipy_proceedings/blob/2024/papers/00_myst_template/main.md) to see if that helps resolve the issue at hand.

2024-06-30 06:44 UTC, tkoyama010 commented
> Hi @tkoyama010 and @HaoZeke! In case a little extra time is needed, the initial complete review deadline has been extended to next [Wednesday, July 3rd](https://github.com/scipy-conference/scipy_proceedings/blob/2024/README.md#instructions-for-reviewers).

Yes please. Thanks!

2024-06-30 09:00 UTC, JaynouOliver commented on papers/Suvrakamal_Das/mybib.bib
> +  url         = "https://github.com/state-spaces/mamba",
Yes, it is working, thank you so much, it will be solved today.

2024-06-30 11:08 UTC, JaynouOliver commented
@tkoyama010 @mepa I see the github links are visible but not all checks are passsing due to missing DOI, if I add DOI (which doesn't exists for Github Links), the Github Links won't be visible. 
![image](https://github.com/scipy-conference/scipy_proceedings/assets/88646338/c4eb989a-d3f2-449f-9491-0acabad82536)

2024-06-30 14:06 UTC, JaynouOliver commented on papers/Suvrakamal_Das/mybib.bib
> +  url         = "https://github.com/state-spaces/mamba",
Thanks for the references, we needed to add those keywords under myst.yml to pass the checks. It's not mentioned profoundly, but some other PR examples helped.

2024-06-30 14:08 UTC, JaynouOliver commented
> @tkoyama010 please add any further changes if needed after review.

Hi, @tkoyama010 all working and good!

2024-07-02 17:37 UTC, tkoyama010 approved these changes
LGTM. Thanks!

2024-07-03 06:14 UTC, HaoZeke commented on papers/Suvrakamal_Das/main.md
> +**Recurrent Neural Networks (RNNs)** [@Sherstinsky_2020], often considered the natural choice for sequential data, are inherently stateful and require only constant computation per time step. However
It isn't wholly clear from my reading of this, how the SSMs evade the vanishing gradients issue, which I thought had more to do with the training and, so, would show up possibly again with a large number of coefficients after HiPPO?

2024-07-03 13:14 UTC, JaynouOliver commented on papers/Suvrakamal_Das/main.md
> +**Recurrent Neural Networks (RNNs)** [@Sherstinsky_2020], often considered the natural choice for sequential data, are inherently stateful and require only constant computation per time step. However
SSMs don't solve vanishing gradient problem but they have tricks to reduce the effect by HiPPO and NLPR, we have later discussed about this, we can refer to that section.

2024-08-04 11:32 UTC, JaynouOliver commented
Hi everyone @tkoyama010  @HaoZeke  @ameyxd ,

I hope you’re all doing well. If there are any additional suggestions, feedback, or corrections needed before the author revision period ends on August 7th, please let me know. I’d be happy to make the necessary changes and incorporate your feedback.

Thank you very much!

2024-08-04 20:13 UTC, tkoyama010 approved these changes

2024-09-02 14:47 UTC, mepa commented
Hi @tkoyama010 and @HaoZeke - Do you feel that this paper is ready for inclusion in the Proceedings?

@tkoyama010, I see that you have approved the PR so will assume "yes" unless I hear otherwise.

Thanks for reviewing!

2024-09-02 14:48 UTC, tkoyama010 commented
Yes! I am ready for it.

2024-09-02 15:29 UTC, HaoZeke approved these changes
LGTM, thanks for working on this!

2024-09-02 15:32 UTC, HaoZeke commented
LGTM as well; go ahead :)

On 9/2/24 2:49 PM, Tetsuo Koyama ***@***.***> wrote:
> Yes! I am ready for it.
> 
> —
> Reply to this email directly, view it on GitHub 
> <https://github.com/scipy-conference/scipy_proceedings/pull/917#issuecomment-2324918474>, or unsubscribe <https://github.com/notifications/unsubscribe-auth/ABBCUTZJ4J6M74DRK7J7IWTZUR3GNAVCNFSM6AAAAABITCUAZ2VHI2DSMVQWIX3LMV43OSLTON2WKQ3PNVWWK3TUHMZDGMRUHEYTQNBXGQ>.
> You are receiving this because you were mentioned.Message ID: 
> ***@***.***>
> 
>

2024-09-02 15:32 UTC, JaynouOliver commented
Thanks a lot @tkoyama010 and @HaoZeke for the approval!!

2024-09-02 21:59 UTC, mepa commented
Thanks very much for reviewing, @tkoyama010 and @HaoZeke.

2024-09-25 17:20 UTC, merged