Paper: THEIA: An Offline Tool for Tradespace Visualization
scipy-conference/scipy_proceedings pull request #920
Opened 2024-05-31 20:17 UTC by samuelcwilliams

If you are creating this PR in order to submit a draft of your paper, please name your PR with `Paper: <title>`. An editor will then add a `paper` label and GitHub Actions will be run to check and build your paper.

See the [project readme](https://github.com/scipy-conference/scipy_proceedings#preview-your-paper) for more information.

_Editor_:  

_Reviewers_:

2024-05-31 20:40 UTC, stevejpurves commented
@samuelcwilliams the `id` field in your `myst.yml` needs to conform exactly to the pattern `scipy-2024-<folder>`

2024-06-04 18:16 UTC, ameyxd commented
@samuelcwilliams thanks for the submission! Can you add the DOI for plotly? We can run the checks again after.

2024-06-04 19:41 UTC, samuelcwilliams commented
@ameyxd, I followed Plotly citation guidance found [here](https://plotly.com/chart-studio-help/citations/), and it didn't include a DOI, so I set it to ignore.

2024-06-04 19:47 UTC, ameyxd commented
thanks @samuelcwilliams cheers.

2024-06-19 19:25 UTC, fwkoch commented on papers/theia/mybib.bib
> +  author    = {Plotly Technologies Inc.},
This gets parsed as a name and shows up as `Inc., P. T.` in citations. You can prevent that by wrapping in brackets:
```suggestion
  author    = {{Plotly Technologies Inc.}}, 
```

2024-06-19 22:53 UTC, mihaimaruseac requested changes

2024-06-19 22:53 UTC, mihaimaruseac commented on papers/theia/main.md
> +Panel @panel is an open-source library for easily building tools, dashboards, and complex applications,
Should the citation be in parantheses? Right now this is rendered as

> Panel [Philipp Rudiger (2024)](https://doi.org/10.5281/zenodo.3706648) is an open-source library

instead of something like

> Panel ([Philipp Rudiger (2024)](https://doi.org/10.5281/zenodo.3706648)) is an open-source library

2024-06-19 22:53 UTC, mihaimaruseac commented on papers/theia/main.md
> +Param @param is an open-source library built for handling user-modifiable parameters, arguments, and attributes
Same here

2024-06-19 22:53 UTC, mihaimaruseac commented on papers/theia/main.md
> +HoloViews @holoviews is an open-source library built for data analysis and visualization with small amounts of code. This library is the
This one too (I'll stop pointing all of these citation issues)

2024-06-19 22:55 UTC, mihaimaruseac commented
Overall, this looks good, but I think it would be even more useful if you can show how the data listed at the beginning of the paper is processed to produce the screenshots at the end. Does the user have to type code? If yes, can you include the code? If not, can you then show how this will work with a more complex data type?

2024-06-19 23:29 UTC, rowanc1 commented on papers/theia/main.md
> +Panel @panel is an open-source library for easily building tools, dashboards, and complex applications,
This can be done by wrapping in square bracket: `Panel [@panel] is an ...`.

2024-06-24 14:26 UTC, samuelcwilliams commented on papers/theia/main.md
> +HoloViews @holoviews is an open-source library built for data analysis and visualization with small amounts of code. This library is the
Much appreciated! I have addressed the citation issues, and they seem to be rendering as they should now.

2024-06-24 20:15 UTC, samuelcwilliams commented
@mihaimaruseac I made some small changes and added in some new content regarding the data upload process and the details on the screenshots in the paper. Let me know if you think there are any areas I should expand on. I appreciate all the feedback!

2024-06-25 14:03 UTC, mihaimaruseac approved these changes
Thank you

2024-06-25 20:51 UTC, mihaimaruseac approved these changes

2024-06-26 00:39 UTC, mihaimaruseac approved these changes

2024-06-27 00:11 UTC, ssuzana commented on papers/theia/main.md
> +A view of the 'download configuration' and 'export plot' options.
Hi, this is Suzana, one of the reviewers for your paper. One suggestion here: it would be great if you could include a sentence or two on what the 'download configuration' button does.

2024-06-29 05:05 UTC, ssuzana approved these changes

2024-07-01 13:56 UTC, samuelcwilliams commented on papers/theia/main.md
> +A view of the 'download configuration' and 'export plot' options.
Hi Suzana, that's a good suggestion. I'll try to get that info in added later today.

2024-07-02 19:15 UTC, samuelcwilliams commented on papers/theia/main.md
> +A view of the 'download configuration' and 'export plot' options.
@ssuzana, I just added a few sentences explaining what those features do in more detail. Let me know if you have any additional feedback or guidance.

2024-07-04 04:43 UTC, ssuzana approved these changes

2024-07-04 13:36 UTC, mihaimaruseac approved these changes

2024-07-14 18:17 UTC, tkoyama010 requested changes
Thank you. The logic of this paper itself seems perfect to me. I just didn't quite understand background what Tradespace meant. I would like you to explain in more detail what kind of data you are trying to process.

2024-07-14 18:19 UTC, tkoyama010 commented
> Thank you. The logic of this paper itself seems perfect to me. I just didn't quite understand background what Tradespace meant. I would like you to explain in more detail what kind of data you are trying to process.

2024-07-14 23:49 UTC, tkoyama010 commented
> Thank you. The logic of this paper itself seems perfect to me. I just didn't quite understand background what Tradespace meant. I would like you to explain in more detail what kind of data you are trying to process.

@cbcunc I already finished review :)

2024-07-22 16:59 UTC, samuelcwilliams commented
@tkoyama010, I added in some additional details on what tradespace data is. I tried to be concise, as I tend to ramble on sometimes. Let me know of any additional edits that come to mind!

2024-07-23 05:40 UTC, tkoyama010 approved these changes
LGTM Thanks!

2024-09-23 21:21 UTC, hongsupshin commented
Thanks @tkoyama010 @mihaimaruseac @ssuzana for reviewing the paper!

2024-09-25 17:28 UTC, merged