Paper: PredxTools: Dispelling the Mystery in Histopathological Image Processing
scipy-conference/scipy_proceedings pull request #922
Opened 2024-05-31 21:58 UTC by bkf15

If you are creating this PR in order to submit a draft of your paper, please name your PR with `Paper: <title>`. An editor will then add a `paper` label and GitHub Actions will be run to check and build your paper.

See the [project readme](https://github.com/scipy-conference/scipy_proceedings#preview-your-paper) for more information.

_Editor_:  

_Reviewers_:

2024-06-19 19:12 UTC, fwkoch reviewed
Here are just a couple MyST-related suggestions. I think they make the final build slightly tidier, but feel free to ignore if you don't like them!

2024-06-19 19:12 UTC, fwkoch commented on papers/brian_falkenstein/main.md
> +Histopathological image analysis reveals insights into disease state and has potential to harness the immensely complex and heterogeneous tumor microenvironment to guide understanding of disease prog
MyST can build parenthetical citations if you use the `cite:p` role, e.g.:
```suggestion
Histopathological image analysis reveals insights into disease state and has potential to harness the immensely complex and heterogeneous tumor microenvironment to guide understanding of disease progression, response to treatment, and aid in patient stratification for clinical trials {cite:p}`doi:10.4132/jptm.2019.12.31, doi:10.3389/fonc.2022.889886, doi:10.1016/j.irbm.2019.06.001, doi:10.3390/cancers15194797, doi:10.1038/s41379-021-00919-2`. However, applying automatic image analysis routines continues to be challenging {cite:p}`doi:10.3390/cancers13123031, doi:10.1308/rcsann.2023.0091`. Often, human intervention in the form of manual annotation or quality control (QC) is required. Additionally, the data itself varies considerably in available features, size, and shape. Thus, a streamlined and interactive approach is a necessary part of any digital pathology pipeline {cite:p}`doi:10.1111/his.14356`. 
```

That will make the citations look like `(Nam et al., 2020; Baxi et al., 2022)` instead of `(Nam et al. (2020), Baxi et al. (2022))`

2024-06-19 19:12 UTC, fwkoch commented on papers/brian_falkenstein/main.md
> +> "*" = Limitation on image size
If you would like to add this as a "legend" to your table, rather than a standalone "quote" you can wrap your `list-table` in a `table`, then give it a caption in the body... Something like:
`````
````{table}
:label: tbl:comparison

```{list-table} 
:header-rows: 1
* - Software
  - View Raw
  ...
```

Comparison of available softwares.

"*" = Limitation on image size
````
`````

Results in:
![image](https://github.com/scipy-conference/scipy_proceedings/assets/9453731/966c1965-021d-46d0-80b3-9954d9e98634)

2024-06-24 16:54 UTC, bkf15 commented on papers/brian_falkenstein/main.md
> +Histopathological image analysis reveals insights into disease state and has potential to harness the immensely complex and heterogeneous tumor microenvironment to guide understanding of disease prog
Thank you, I have made the suggested changes and pushed the result.

2024-06-24 16:54 UTC, bkf15 commented on papers/brian_falkenstein/main.md
> +> "*" = Limitation on image size
Thank you, I have made the suggested changes and pushed the result.

2024-07-30 17:28 UTC, ameyxd commented
Sent review reminders to @KrishnaRekapalli and @arushimisra99

2024-08-07 01:56 UTC, hongsupshin requested changes
Hi @bkf15 , my name is Hongsup Shin, the editor of your paper. Unfortunately, we have had hard time getting reviews from the assigned reviews, so I and another SciPy proceedings co-chair will be stepping in as reviewers of your paper. I already left some comments in the manuscript for clarification. 

As a general note about the paper, I suggest the followings:
- Given that the SciPy conference highlights creative and novel uses of various Python libraries, and your proposed tool is built on various existing packages, I would appreciate if you can add more details on how the packages cited in your paper (like scikit-learn, for instance) were used to build your tool.
- I think the title of the paper is a bit exaggerating what the tool does. It's hard to find what exactly the "mystery" is. After reading the manuscript, I think the novelty here is that the proposed tool does multiple things altogether that the previous tools didn't. So please consider changing it to be more specific and accurate.
- Even though the summary table helps comparing your tool and the existing tools, while reading the manuscript, it was difficult to follow exactly how your tool is different from those. If you can add more detailed comparison, I think that would really help especially because the current manuscript very much reads like a manual of your tool.
- I am also wondering whether you have any data on how much efficiency your tool provides. For instance, your tool has some automation steps and how many man-hours can it save compared to manual approach (and also compared to other tools)? Is your tool faster than existing tools? If yes, then by how much?
- You mention challenges in dealing with "unseen data" but I wasn't able to find any ML elements. Does your tool alleviate these specific challenges with unseen data?

2024-08-07 01:56 UTC, hongsupshin commented on papers/brian_falkenstein/main.md
> +Raw data takes the form of either brightfield immuno-histochecmical (IHC) or hematoxylin and eosin (H&E) RGB images, or multiplex immunofluorescence (mIF) or imaging mass cytometry (IMC) N-channel im
Since it's likely that many readers might not be histology experts, could you add explanation on whether the listed raw data formats (IHC, H&E, etc.) are typical types one would encounter in histology image analysis?

2024-08-07 01:56 UTC, hongsupshin commented on papers/brian_falkenstein/main.md
> +Raw data takes the form of either brightfield immuno-histochecmical (IHC) or hematoxylin and eosin (H&E) RGB images, or multiplex immunofluorescence (mIF) or imaging mass cytometry (IMC) N-channel im
Can you also give an example of what a feature is in this case?

2024-08-07 01:56 UTC, hongsupshin commented on papers/brian_falkenstein/main.md
> +While there have been attempts at fully automating this procedure, it is nearly impossible to design routines that can account for all forms of variation across datasets. Thus, for optimal performanc
What is the challenge of handling unseen data? Is it about encountering a novel feature, data format, etc.? So in general, what is exactly unseen data and how do you use it?

2024-08-07 01:56 UTC, hongsupshin commented on papers/brian_falkenstein/main.md
> +To facilitate this, simple and easy to use tools must be developed to allow field experts to interact with the data with minimal effort. Oftentimes users may not be comfortable or familiar with progr
Who are the users? Lab technicians, doctors, etc.?

2024-08-07 01:56 UTC, hongsupshin commented on papers/brian_falkenstein/main.md
> +````{table}
Really like the summary table!

2024-08-07 01:56 UTC, hongsupshin commented on papers/brian_falkenstein/main.md
> +````{table}
If there's a way, it might be nice if we can highlight your tool in the table.

2024-08-07 01:56 UTC, hongsupshin commented on papers/brian_falkenstein/main.md
> +Once the experiment has begun and the data is loaded, the user will be shown an image and is asked to provide a label. The potential labels are listed in a table, and can be clicked to assign that la
- How is the boundary generated?
- So it seems that CellLabeler is not an automated labeling tool but more of an annotation tool for human users. Is this correct?

2024-08-07 01:56 UTC, hongsupshin commented on papers/brian_falkenstein/main.md
> +Additionally, one can fit a Gaussian Mixture Model to the current distribution using the right panel by simply specifying the number of mixture components and pressing enter. This will fit a model to
Can a user evaluate the results of the GMM fitting since they can decide the number of components and will be able to potentially try different scenarios?

2024-08-07 02:07 UTC, hongsupshin commented
@bkf15 By the way, even though the Open Review Period ends tomorrow (Aug 7), since this manuscript didn't have any reviews so far, you can continue making changes to the manuscript. We will provide one more review by the end of this week.

2024-08-12 05:30 UTC, mepa requested changes
Hi @bkf15, I am the other SciPy proceedings co-chair stepping in to provide a review for your paper. Thanks for your patience in waiting for your submission to be reviewed. I do not work in the field of histopathological image processing so my comments are mainly around making the paper more accessible to a reader from another domain.

2024-08-12 05:30 UTC, mepa commented on papers/brian_falkenstein/main.md
> +  Histopathological image contains insights into disease state, but applying automatic image analysis is challenging. Often, human intervention in the form of manual annotation or quality control (QC
Because SciPy is an interdisciplinary conference, the abstract to this paper can be made more accessible to readers by defining terms such as "histopathological image", by clarifying who the intended user of the tool suite is, etc.

Additionally, here are a few specific comments on the text.
- Please revise the first sentence to make it grammatically correct.
- "data itself vary" -> either "data themselves vary" or "data itself varies" for plural or singular self-consistency
- In the last sentence I believe it could help a reader unfamiliar with "all parts of a digital pathology pipeline" if it were directly stated _why_ "a suite of simple and easy to use python GUI applications" would "allow for a deeper understanding of the data".

2024-08-12 05:30 UTC, mepa commented on papers/brian_falkenstein/main.md
> +Histopathological image analysis reveals insights into disease state and has potential to harness the immensely complex and heterogeneous tumor microenvironment to guide understanding of disease prog
Could you give more detail about or some examples of variations in "features, size, and shape"?

2024-08-12 05:30 UTC, mepa commented on papers/brian_falkenstein/main.md
> +Raw data takes the form of either brightfield immuno-histochecmical (IHC) or hematoxylin and eosin (H&E) RGB images, or multiplex immunofluorescence (mIF) or imaging mass cytometry (IMC) N-channel im
histochecmical -> histochemical

2024-08-12 05:30 UTC, mepa commented on papers/brian_falkenstein/main.md
> +Raw data takes the form of either brightfield immuno-histochecmical (IHC) or hematoxylin and eosin (H&E) RGB images, or multiplex immunofluorescence (mIF) or imaging mass cytometry (IMC) N-channel im
I like the explanatory phrase following the statement about segmentation. Something similar after "registered" could be helpful to a reader who does not work with image data.

2024-08-12 05:30 UTC, mepa commented on papers/brian_falkenstein/main.md
> +* - `Fiji`
Not sure if I missed it, but are there links or references to the software packages listed in this table?

2024-08-12 05:30 UTC, mepa commented on papers/brian_falkenstein/main.md
> +Further, any arbitrary transformation can be performed on the raw pixel values before plotting them. By default, a log2 transform is applied to transform the data from range [0, 2^16] to [0, 16]. How
typo? [0, 2^16] -> [1, 2^16]

2024-08-15 02:24 UTC, nicole-brewer commented on papers/brian_falkenstein/main.md
> +  Histopathological image contains insights into disease state, but applying automatic image analysis is challenging. Often, human intervention in the form of manual annotation or quality control (QC
I suggests adding information about your intended user/audience. Who could benefit from this tool? Be sure to call them out clearly and early so you reach your intended reader.

2024-08-15 02:24 UTC, nicole-brewer commented on papers/brian_falkenstein/main.md
> +Histopathological image analysis reveals insights into disease state and has potential to harness the immensely complex and heterogeneous tumor microenvironment to guide understanding of disease prog
I’m not medical, and I could use a few words about what pathology and specifically histopathology, actually are.  I recommend breaking down the first sentence in the introduction. First introduce histopathology itself and be sure to tell us what the images are of! I had to look up that the images are of tissues, which in the past were probably viewed as slices on slides. Only then go on to say that histopathology is now often done with digital imaging instead of class slides and how that makes it amenable to computational analysis. Then you can go into the rest of your first paragraph, which is very nice.

2024-08-15 02:24 UTC, nicole-brewer commented on papers/brian_falkenstein/main.md
> +Raw data takes the form of either brightfield immuno-histochecmical (IHC) or hematoxylin and eosin (H&E) RGB images, or multiplex immunofluorescence (mIF) or imaging mass cytometry (IMC) N-channel im
As suggested by others, the first sentence contains a lot of jargon. You could explain them, but my intuition is to remove those terms altogether. Or, if you feel they are really necessary, mention them somewhere else where you have room to expand upon why mentioning those terms is important.

2024-08-15 02:24 UTC, nicole-brewer commented on papers/brian_falkenstein/main.md
> +Raw data takes the form of either brightfield immuno-histochecmical (IHC) or hematoxylin and eosin (H&E) RGB images, or multiplex immunofluorescence (mIF) or imaging mass cytometry (IMC) N-channel im
I’m also unclear which actions referenced in paragraph one (ex. Nuclei segmentation) were in reference to *physically* in lab activities, or in reference to an action taken on a digital image. This confusion might be prevented by replacing passive voice with active voice. Instead of “Then, nuclei and or cell segmentation must be performed”,  you might say “Then, lab scientists must perform nuclei and or cell segmentation [on the tissue sample]” or “Then, analysts must perform nuclei and or cell segmentation [on the digital image]”. The presence of the actor gives us more information and makes the process described easier to read.

2024-08-15 02:24 UTC, nicole-brewer commented on papers/brian_falkenstein/main.md
> +Raw data takes the form of either brightfield immuno-histochecmical (IHC) or hematoxylin and eosin (H&E) RGB images, or multiplex immunofluorescence (mIF) or imaging mass cytometry (IMC) N-channel im
Does segmented mean that a border is drawn around them?

2024-08-15 02:24 UTC, nicole-brewer commented on papers/brian_falkenstein/main.md
> +Raw data takes the form of either brightfield immuno-histochecmical (IHC) or hematoxylin and eosin (H&E) RGB images, or multiplex immunofluorescence (mIF) or imaging mass cytometry (IMC) N-channel im
What is differential analysis?

2024-08-15 02:24 UTC, nicole-brewer commented on papers/brian_falkenstein/main.md
> +To facilitate this, simple and easy to use tools must be developed to allow field experts to interact with the data with minimal effort. Oftentimes users may not be comfortable or familiar with progr
Instead of saying “users may not be comfortable or familiar with programming”, be even more specific. Who are your users? Researchers? Doctors? Who is your intended audience? Are people doing this analysis often have technical backgrounds? You mention that there are other tools, but you don’t mention who uses them and in what kind of numbers.

2024-08-15 02:24 UTC, nicole-brewer commented on papers/brian_falkenstein/main.md
> +````{table}
What are ground truth labels?

2024-08-15 02:24 UTC, nicole-brewer commented on papers/brian_falkenstein/main.md
> +Once the experiment has begun and the data is loaded, the user will be shown an image and is asked to provide a label. The potential labels are listed in a table, and can be clicked to assign that la
What is a biomarker?

2024-08-15 02:24 UTC, nicole-brewer commented on papers/brian_falkenstein/main.md
> +A configuration json file must be created for each project. Within the configuration file, the user specifies the possible labels that can be assigned to each object, the type of image data (RGB or N
I’m curious if the labels provided in the configuration make it into an autogenerated metadata file? Or even adds information to an already present metadata file? If so it would be mention that this tool helps improve data sharing best practices.

2024-08-15 02:24 UTC, nicole-brewer commented on papers/brian_falkenstein/main.md
> +We have also created PixelExplorer as a way to quickly perform basic analysis on pixel level data in raw or pre-processed histopathological datasets. Analyzing biomarker distributions and fitting mod
What is brightfield imaging?

2024-08-15 02:24 UTC, nicole-brewer commented on papers/brian_falkenstein/main.md
> +## CellExplorer
I felt that this section had a strong description of the GUI, that was easy for me to visualize, as well as a good description of design of the app. Great job

2024-08-15 02:24 UTC, nicole-brewer commented on papers/brian_falkenstein/main.md
> +Here we have described Predx-Tools, our suite of easy to use and flexible GUI applications for interfacing with histopathological image data at various stages of processing. We developed these tools
If I were to use this tool, I would want more information about how to access the tool. Is it a pip install? If so, is launching the gui done with a terminal command? Is it hosted somewhere and is there a way to access a hosted version? Are the GUIs packaged together or separately? I don’t need any code or specific details here, just a vague idea about what my next step is if I was a potential user interested in using the tool. A call to action so to speak.

2024-08-15 02:24 UTC, nicole-brewer commented on papers/brian_falkenstein/main.md
> +Here we have described Predx-Tools, our suite of easy to use and flexible GUI applications for interfacing with histopathological image data at various stages of processing. We developed these tools
Also, what about sharing? Do people typically use these tools in collaboration with others? What would that look like if people added your GUI to their workflow?

2024-08-15 02:24 UTC, nicole-brewer commented on papers/brian_falkenstein/main.md
> +Here we have described Predx-Tools, our suite of easy to use and flexible GUI applications for interfacing with histopathological image data at various stages of processing. We developed these tools
I love user interfaces for improved accessibility of computational workflows! Seems like a great tool, well done

2024-08-17 16:30 UTC, hongsupshin commented
Hi @bkf15 , just a friendly reminder that all initial reviews are in. I highly recommend you start responding to the comments soon since it'd take time for the reviewers to respond to the changes. Remember that the open review period ends on Sep 2, and you will not be able to make any changes to the manuscript after that point. If you have any questions, please let me know!

2024-08-23 14:06 UTC, bkf15 commented
> Hi @bkf15 , just a friendly reminder that all initial reviews are in. I highly recommend you start responding to the comments soon since it'd take time for the reviewers to respond to the changes. Remember that the open review period ends on Sep 2, and you will not be able to make any changes to the manuscript after that point. If you have any questions, please let me know!

Hello. Thank you for all the comments. I will be providing my thoughts and answering questions as well as pushing updates to the paper. Thank you for your patience.

2024-08-23 14:14 UTC, bkf15 commented on papers/brian_falkenstein/main.md
> +Raw data takes the form of either brightfield immuno-histochecmical (IHC) or hematoxylin and eosin (H&E) RGB images, or multiplex immunofluorescence (mIF) or imaging mass cytometry (IMC) N-channel im
> Given that the SciPy conference highlights creative and novel uses of various Python libraries, and your proposed tool is built on various existing packages, I would appreciate if you can add more details on how the packages cited in your paper (like scikit-learn, for instance) were used to build your tool.

I will add more details into the paper regarding how specifically the libraries are used. 

> I think the title of the paper is a bit exaggerating what the tool does. It's hard to find what exactly the "mystery" is. After reading the manuscript, I think the novelty here is that the proposed tool does multiple things altogether that the previous tools didn't. So please consider changing it to be more specific and accurate.

I agree and appreciate the input. A proposed change to the title would be "PredxTools: A Suite of GUI Applications for Histopathological Image Processing". I can make this change in the document. However, I'm not sure if I need to make any changes to the pull request, or if that's possible. Please advise, thank you.

> Even though the summary table helps comparing your tool and the existing tools, while reading the manuscript, it was difficult to follow exactly how your tool is different from those. If you can add more detailed comparison, I think that would really help especially because the current manuscript very much reads like a manual of your tool.

I will add a section which more clearly highlights the motivations and advantages behind our tools, and why we chose to develop these in house as opposed to using existing software. 

> I am also wondering whether you have any data on how much efficiency your tool provides. For instance, your tool has some automation steps and how many man-hours can it save compared to manual approach (and also compared to other tools)? Is your tool faster than existing tools? If yes, then by how much?

I will say here that the goal of the tools is not necessarily computational efficiency, but rather human time efficiency. So, we were finding that we were writing and running a lot of the same code for doing some of the basic analysis. This motivated the creation of simple tools for doing this type of analysis in a GUI setting. Although efficiency was considered during development (zarr compressed arrays as an example) it was not the key focus. 

>You mention challenges in dealing with "unseen data" but I wasn't able to find any ML elements. Does your tool alleviate these specific challenges with unseen data?

The challenges mentioned contain both 'unseen data' in the traditional ML meaning (data outside domain of training data) and also in the sense of metadata and data formatting. The latter being more the focus. There is no real heavy ML happening anywhere in this work.

2024-08-23 14:39 UTC, bkf15 commented on papers/brian_falkenstein/main.md
> +Raw data takes the form of either brightfield immuno-histochecmical (IHC) or hematoxylin and eosin (H&E) RGB images, or multiplex immunofluorescence (mIF) or imaging mass cytometry (IMC) N-channel im
> Since it's likely that many readers might not be histology experts, could you add explanation on whether the listed raw data formats (IHC, H&E, etc.) are typical types one would encounter in histology image analysis?

Yes, the formats mentioned are the keystone data types for histological image analysis. I will make this more clear in the paper. 

> Can you also give an example of what a feature is in this case?

Yes. I am understanding that the background section needs a good bit of fleshing out. I wasn't sure how much detail to go into in the background, but clearly I need more details. 

> I like the explanatory phrase following the statement about segmentation. Something similar after "registered" could be helpful to a reader who does not work with image data.

Great, I will add in a similar phrasing for registration as well.

2024-08-23 14:43 UTC, bkf15 commented on papers/brian_falkenstein/main.md
> +Raw data takes the form of either brightfield immuno-histochecmical (IHC) or hematoxylin and eosin (H&E) RGB images, or multiplex immunofluorescence (mIF) or imaging mass cytometry (IMC) N-channel im
> I’m also unclear which actions referenced in paragraph one (ex. Nuclei segmentation) were in reference to physically in lab activities, or in reference to an action taken on a digital image. This confusion might be prevented by replacing passive voice with active voice. Instead of “Then, nuclei and or cell segmentation must be performed”, you might say “Then, lab scientists must perform nuclei and or cell segmentation [on the tissue sample]” or “Then, analysts must perform nuclei and or cell segmentation [on the digital image]”. The presence of the actor gives us more information and makes the process described easier to read.

I will make it clear that everything discussed in the context of this work is done outside of a lab, entirely on digitized images.  

> Does segmented mean that a border is drawn around them?

Yes, each nucleus / cell is delineated from the background and its neighbor. This is a crucial step in histopathological image analysis. 

> What is differential analysis?

This is referring to analyzing patient data from various subsets (tumor grade, outcome, response to therapy etc) to find differences between the subsets. This can be used to create a prediction model, IE to predict if a patient is likely to respond to therapy or not. I will make this more clear.

2024-08-23 14:48 UTC, bkf15 commented on papers/brian_falkenstein/main.md
> +While there have been attempts at fully automating this procedure, it is nearly impossible to design routines that can account for all forms of variation across datasets. Thus, for optimal performanc
One challenge is as you mentioned, data formatting. This is simple enough, and often just requires simple pre-processing to get into a familiar format (this is included in the PredxTools). 
A separate challenge with unseen data is the vast differences in domains. IE, digitized slides of advanced lung cancer look vastly different from those of brain tissue. However, these differences are more encountered in the later stages of analysis, where biological insights are extracted. The PredxTools allows the user to better understand new and unseen data by allowing them to dive deep into the signals and guide the analysis. 
As a very specific example, CD56 is a marker that behaves very differently in small cell lung cancer (SCLC) and other tissues. This difference is revealed by visualization and inspection of the distribution of CD56 in cells in SCLC and non SCLC tissue.

2024-08-29 17:24 UTC, bkf15 commented on papers/brian_falkenstein/main.md
> +To facilitate this, simple and easy to use tools must be developed to allow field experts to interact with the data with minimal effort. Oftentimes users may not be comfortable or familiar with progr
User's may fall into a couple of buckets:

1. Researchers / biomedical researchers / computational researchers - these users will find the GUI tools to be useful in cutting down on redundant coding as well as facilitating a visual understanding of the data. It makes it easy to perform similar analysis on multiple datasets. These users will likely use the results and understanding from the GUI to guide further deeper analysis.
2. Pathologists / lab scientists - these users may be less experienced with coding but are still interested in engaging with the data. The GUI applications allow these users to perform simple analysis without the need for any coding. This can facilitate dialogue between the technical teams and biomedical teams.

2024-08-29 17:29 UTC, bkf15 commented on papers/brian_falkenstein/main.md
> +````{table}
Ground truth labels are any label provided by an expert for an object in a histopatholigical image. For our case, the input would be a set of images and masks, and the output is a label for the masked regions in the image. As a few examples: 

- Gathering cell type labels (Cell images and biomarker expressions are known, the user provides a label if the cell is Positive or Negative). IE, labeling cells with CD68 expression as macrophages or not. This can be useful in deriving models for biomarker positivity in cell masks.
- Gathering labels for larger tissue regions (regions of interest, ROI's). In this example, a larger region of tissue may be visualized along with a mask, and a label about the tissue state can be applied. Example labels may be 'benign', 'tumor', 'necrosis', etc. 
- Gathering information about quality of segmentation. Often it is important to understand the accuracy of segmentation results on new unseen data. Results can quickly be visualized and labels provided ('Good segmentaiton', 'Poor segmentation', ...). Labels can then be used to compute accuracy metrics

I will make sure to include some examples in the text.

2024-08-29 17:33 UTC, bkf15 commented on papers/brian_falkenstein/main.md
> +Once the experiment has begun and the data is loaded, the user will be shown an image and is asked to provide a label. The potential labels are listed in a table, and can be clicked to assign that la
> How is the boundary generated?

The boundary is generated from the input mask using the `find_boundaries` function from skimage. I will make it more clear in the text that this is part of the input to CellLabeler.

> So it seems that CellLabeler is not an automated labeling tool but more of an annotation tool for human users. Is this correct?

Correct

> What is a biomarker?

A biomarker is 1 channel of the image

2024-08-29 17:33 UTC, bkf15 commented on papers/brian_falkenstein/main.md
> +Additionally, one can fit a Gaussian Mixture Model to the current distribution using the right panel by simply specifying the number of mixture components and pressing enter. This will fit a model to
Currently, the evaluation is done by eye. One can visually check the quality of the fit of the distribution. Although, a nice addition would be to see a few metrics of fit.

2024-08-29 17:37 UTC, bkf15 commented on papers/brian_falkenstein/main.md
> +Here we have described Predx-Tools, our suite of easy to use and flexible GUI applications for interfacing with histopathological image data at various stages of processing. We developed these tools
Currently, the tool is still undergoing development. We are currently porting the applications to a web based front end (Streamlit) and intend to make the tools open for use to all. 

As for sharing, ideally the goal with this project is to facilitate discussions between technical and biomedical teams. We try to accomplish this by making the data analysis more accessible. By allowing the users to import and export all the data / plots they create, it allows more non-technical people to be involved in the data analysis.

2024-08-29 17:39 UTC, bkf15 commented on papers/brian_falkenstein/main.md
> +We have also created PixelExplorer as a way to quickly perform basic analysis on pixel level data in raw or pre-processed histopathological datasets. Analyzing biomarker distributions and fitting mod
Brightfield imaging is a type of digital imaging wherein the tissue is illuminated from below, and a digital image is taken (as in under a normal microscope condition). This results in a standard RGB image that we are used to. This is in contrast to other imaging modalities like immunoflourescnece where there may be many 'colors' in the image, where each color is a response of a biomarker in a frequency domain. This data is much higher dimensionality but can contain much deeper insight into tissue composition

2024-08-29 17:40 UTC, bkf15 commented on papers/brian_falkenstein/main.md
> +A configuration json file must be created for each project. Within the configuration file, the user specifies the possible labels that can be assigned to each object, the type of image data (RGB or N
Yes, all configuration data is saved into the output metadata. That is, the experiment can be reproduced entirely. The state of the experiment is saved at every iteration.

2024-08-29 17:41 UTC, bkf15 commented
I apologize for the delay. I will be pushing my changes to the paper shortly. I hope I have addressed all questions and concerns.

2024-08-29 17:42 UTC, bkf15 commented on papers/brian_falkenstein/main.md
> +Further, any arbitrary transformation can be performed on the raw pixel values before plotting them. By default, a log2 transform is applied to transform the data from range [0, 2^16] to [0, 16]. How
Correct, thank you. Technically the data does go from [0,2^16-1], but we add 1 before log transform :)

2024-08-29 17:43 UTC, bkf15 commented on papers/brian_falkenstein/main.md
> +* - `Fiji`
Thank you, I will add links to the referenced tools

2024-08-29 23:00 UTC, bkf15 reviewed
Addressing reviewer comments.

2024-09-10 17:23 UTC, hongsupshin approved these changes

2024-09-15 13:52 UTC, mepa approved these changes
@bkf15, thanks for the updates to make this paper more accessible to a wider audience. It looks great to me.

2024-09-15 13:52 UTC, mepa commented on papers/brian_falkenstein/mybib.bib
> +  url     = {https://zarr.readthedocs.io/en/stable/},
Is this the intended URL for PySimpleGUI?

2024-09-16 17:24 UTC, bkf15 commented on papers/brian_falkenstein/mybib.bib
> +  url     = {https://zarr.readthedocs.io/en/stable/},
Thank you for bringing this to my attention. I just made the fix and pushed it. I'm not sure if it's too late. Apologies.

2024-09-23 21:18 UTC, hongsupshin commented
Thanks @mepa @nicole-brewer for reviewing the paper!

2024-09-25 17:29 UTC, merged