Paper: How the Scientific Python ecosystem helps answer fundamental questions of the Universe
scipy-conference/scipy_proceedings pull request #924
Opened 2024-05-31 22:57 UTC by matthewfeickert

This PR adds the `myst.md` paper source for the SciPy 2024 proceedings for the talk "How the Scientific Python ecosystem helps answer fundamental questions of the Universe".

_Editor_:  

_Reviewers_:

2024-05-31 22:58 UTC, matthewfeickert commented
This has been placed in draft mode as I'm still continuing to write. I'm opening the PR now to ensure that it is created before the May 31 deadline.

2024-05-31 23:00 UTC, matthewfeickert commented
The `curvenote / publish / check` checks are failing as

```
 ❯ content (22/29 tests passed)
    × DOI Exists: Citation does not have DOI: S2I2HEPSP
    × DOI Exists: Citation does not have DOI: PyHEP
    × DOI Exists: Citation does not have DOI: nanobind
    × DOI Exists: Citation does not have DOI: ATL-SOFT-PUB-2021-001
    × DOI Exists: Citation does not have DOI: Dask
    × DOI Exists: Citation does not have DOI: Dask-awkward
    × DOI Exists: Citation does not have DOI: Dask-histogram
```

If I'm citing things that don't have DOIs (like software that doesn't have an archive on Zenodo) is there a way to communicate this to Curvenote to make it clear this is intended?

2024-06-01 06:38 UTC, leewujung commented
@matthewfeickert you can add citation keys you want to ignore in `myst.yml` under `error_rules`:
```yaml
  error_rules:
    - rule: doi-exists
      severity: ignore
      keys:
        - Atr03
        - terradesert
```

2024-06-04 18:20 UTC, ameyxd commented
@matthewfeickert can you make this update so we can run checks?

2024-06-07 17:18 UTC, cbcunc commented
@matthewfeickert Just a reminder that first submissions must be compete by today. Please do what you need to do to get your PR out of the draft state so we can mark it ready for review and assign a reviewer. We assign reviewers to papers all at once and not piecemeal paper by paper.

2024-06-07 17:27 UTC, matthewfeickert commented
> We assign reviewers to papers all at once and not piecemeal paper by paper.

I don't understand this last comment, but I'll assume that it is not something that affects actionable information on my side. Thanks for the reminder that the deadline is today at 23:59 Pacific. :+1:

2024-06-12 18:44 UTC, hongsupshin commented
> > We assign reviewers to papers all at once and not piecemeal paper by paper.
> 
> I don't understand this last comment, but I'll assume that it is not something that affects actionable information on my side. Thanks for the reminder that the deadline is today at 23:59 Pacific. 👍

No worries @matthewfeickert, we assigned two reviewers to your paper :)

2024-06-19 18:36 UTC, fwkoch commented on papers/matthew_feickert/uncovering-higgs.md
> +The operation is scaled out on a Dask cluster for read performance.
Directive options are parsed line-by-line - that means the second sentence here will be lost unless you move it to the previous line.

```suggestion
:caption: Using `coffea`, tree structured ROOT files are read with `uproot` from an efficient file cache, and the relevant branches for physics are filtered out into Awkward arrays. The operation is scaled out on a Dask cluster for read performance.
```

2024-06-27 22:15 UTC, Marcdh3 commented
I believe this paper does a good job of telling the story that complex, large-scale physics research is now feasible in Python due to recent advancements in the scientific Python ecosystem. The background information clearly defined
  the technological gap that needed to be addressed to make this type of research possible. The authors were thorough in indicating how each library addressed the former challenges, and how such code should be used in an
  analysis workflow. Finally, I believe the Higgs Boson example was a good choice because it is a convincing real-world problem that demonstrated the ease at which this research can now be conducted in Python.

2024-06-27 22:19 UTC, Marcdh3 commented on papers/matthew_feickert/introduction.md
> +These extreme energy density environments are created at the CERN international laboratory, in Geneva, Switzerland, using the Large Hadron Collider (LHC) to collide bunches of billions of protons at
For clarity, "bunches of" may be removed.

2024-06-27 22:20 UTC, Marcdh3 commented on papers/matthew_feickert/introduction.md
> +Collectively, these tools are modernizing the methods which researchers are engaging data analysis at large scale and providing a nobel end-to-end analysis ecosystem for the ATLAS collaboration.
```suggestion
Collectively, these tools are modernizing the methods which researchers are engaging data analysis at large scale and providing a novel end-to-end analysis ecosystem for the ATLAS collaboration.
```

2024-06-27 22:21 UTC, Marcdh3 commented on papers/matthew_feickert/scientific-python-ecosystem.md
> +This precedent made it difficult to take advantage of array programming paradigms that are common in Scientific Python given NumPy [@numpy] vector operations.
It would be beneficial to the audience to include a sentence explaining what array programming is and why it is useful in this context.

2024-06-27 22:23 UTC, Marcdh3 commented on papers/matthew_feickert/uncovering-higgs.md
> +To provide an overview of the tooling and functionality, a high level summary of a simplified analysis workflow of a Higgs "decay" to two intermediate $Z$ bosons that decay to charged leptons $(\ell)
(Optional) Restructure the first paragraph in this section by putting the message of the last sentence first. For example, "In this section we will demonstrate how the scientific Python ecosystem allows for ...  with an example of a simplified analysis workflow of a Higgs Boson decay." My reasoning for this suggestion is because during my first read through the paper I missed the subtle transition into the example; it felt like the paper jumped straight into it after giving background regarding the Higgs Boson phenomenon. So by moving the message of the final sentence up, I think it will stand-out more to the reader.

2024-06-27 22:24 UTC, Marcdh3 commented on papers/matthew_feickert/uncovering-higgs.md
> +Only physics object of adequate quality are kept for further analysis and those should reconstruct the topology of interest.
```suggestion
Only physics objects of adequate quality are kept for further analysis and those should reconstruct the topology of interest.
```

2024-06-27 22:24 UTC, Marcdh3 commented on papers/matthew_feickert/uncovering-higgs.md
> +In order to discriminate the events of interest, i.e. candidates of the Higss boson decay, from the vast background which has the same experimental signature, a discriminating feature is constructed.
```suggestion
In order to discriminate the events of interest, i.e. candidates of the Higgs boson decay, from the vast background which has the same experimental signature, a discriminating feature is constructed.
```

2024-06-27 22:25 UTC, Marcdh3 commented on papers/matthew_feickert/uncovering-higgs.md
> +where $E$ and $p$ is the total energy and momentum of the particles respectively.
```suggestion
where $E$ and $p$ is the total energy and momentum of the particles, respectively.
```

2024-06-27 22:26 UTC, Marcdh3 commented on papers/matthew_feickert/uncovering-higgs.md
> +_TODO: Quantify results._
Remove this line
```suggestion

```

2024-06-27 22:27 UTC, Marcdh3 requested changes
I believe this paper does a good job of telling the story that complex, large-scale physics research is now feasible in Python due to recent advancements in the scientific Python ecosystem. The background information clearly defined the technological gap that needed to be addressed to make this type of research possible. The authors were thorough in indicating how each library addressed the former challenges, and how such code should be used in an analysis workflow. Finally, I believe the Higgs boson example was a good choice because it is a convincing real-world problem that demonstrated the ease at which this research can now be conducted in Python.

2024-06-27 22:28 UTC, matthewfeickert commented
Thanks very much for your review @Marcdh3! We will get to work on incorporating your feedback shortly (hopefully before SciPy starts).

2024-07-31 11:45 UTC, cliffckerr reviewed
I thought this paper was clear and easy to follow. Some very minor comments:
- Should the abstract be updated to refer to the paper instead of the talk?
- You could include an explanation of why ROOT is preferable to other formats (e.g. Arrow?)
- Typo, "a specific calorimeter subsystems"
- The description of the role of "nanobind" probably doesn't need to be repeated between sections.
- Do all computations currently run on CPUs, and if so, is there interest in exploring GPU implementations?

2024-07-31 13:46 UTC, matthewfeickert commented
Thanks @cliffckerr for the review! I will address these post haste, but am in week 5 of travel for work and teaching at the moment so it probably won't be until next week.

2024-08-17 16:30 UTC, hongsupshin commented
Hi @matthewfeickert , just a friendly reminder that all initial reviews are in. I highly recommend you start responding to the comments soon since it'd take time for the reviewers to respond to the changes. Remember that the open review period ends on Sep 2, and you will not be able to make any changes to the manuscript after that point. If you have any questions, please let me know!

2024-08-19 06:38 UTC, matthewfeickert commented on papers/matthew_feickert/introduction.md
> +These extreme energy density environments are created at the CERN international laboratory, in Geneva, Switzerland, using the Large Hadron Collider (LHC) to collide bunches of billions of protons at
We actually do collide "bunches" of protons (that's the terminology we use too) at a time. (c.f. https://home.cern/news/news/accelerators/lhc-racks-records though we don't actually have a great public explainer in just text) It would be less correct to remove this, but if putting "bunches" in quotations makes it more clear we could do that.

2024-08-19 10:24 UTC, cbcunc commented on papers/matthew_feickert/introduction.md
> +These extreme energy density environments are created at the CERN international laboratory, in Geneva, Switzerland, using the Large Hadron Collider (LHC) to collide bunches of billions of protons at
Quoting seems reasonable. The citation seems also an additional clarifier.

2024-08-23 06:46 UTC, matthewfeickert commented on papers/matthew_feickert/scientific-python-ecosystem.md
> +This precedent made it difficult to take advantage of array programming paradigms that are common in Scientific Python given NumPy [@numpy] vector operations.
I'm hesitant to have this paper have the responsibility of explaining these concepts to the audience, given that we already provide a reference to the NumPy paper [Array programming with NumPy](https://www.nature.com/articles/s41586-020-2649-2). The NumPy paper doesn't make any attempt to further cite the concept of array programming or to elaborate on its definition any further than the first sentence of the paper, I would assume, given how widespread these concepts are in scientific computing. We do also mention in the introduction

> The use of dataframes and array programming for data analysis has enhanced the user experience while providing efficient computations without the need of coding optimized low-level routines.

2024-08-23 06:46 UTC, matthewfeickert commented on papers/matthew_feickert/uncovering-higgs.md
> +To provide an overview of the tooling and functionality, a high level summary of a simplified analysis workflow of a Higgs "decay" to two intermediate $Z$ bosons that decay to charged leptons $(\ell)
I understand your point, but I don't think we want to restructure that paragraph as this now means awkwardly introducing the Higgs in the middle of another sentence. The focus of the paper is the software, but we still need to motivate it with the science which is the primary driver and so some text needs to be devoted to the physics. Though to try to make the final sentence of the paragraph more clear we've repeated that it is the Pythonic tooling being used. Though if you feel that this still isn't helpful I'm happy to wordsmith this more.

2024-08-23 06:53 UTC, matthewfeickert commented
> Some very minor comments:
>
> * Should the abstract be updated to refer to the paper instead of the talk?

Done.

> * You could include an explanation of why ROOT is preferable to other formats (e.g. Arrow?)

I've added a short mention of it providing columnar data structures with good serialization compression for almost 30 years (1997) (Arrow wasn't released until 2016) along with an additional reference. Though the realities are more complex and well outside of the scope of this short paper, I will note that when the field has well over an exabyte of data stored in the same file format which is used for basically everything there's rather large inertia to switch regardless of motivation.

> * Typo, "a specific calorimeter subsystems"

Thanks! @cliffckerr I'm sorry that there were so many typos that you and @Marcdh3 had to catch (and this is even with the `codespell` pre-commit hook on). :grimacing:

> * The description of the role of "nanobind" probably doesn't need to be repeated between sections.

Can you elaborate a bit more on what is repeated? "nanobind" only appears in the main text in the following two sentences:

> The ATLAS collaboration is further extending this ecosystem of tooling to include high-level custom Python bindings to the low level C++ frameworks using nanobind Jakob, 2022.

and

> To expose these C++ libraries to the Pythonic tooling layer, custom Python bindings are written using nanobind for high efficiency, as seen in Figure 1.

The first sentence is introducing the concept of custom Python bindings, and the second is highlighting the fact that `nanobind` in particular was chosen given that the actual bindings it generates are more efficient than alternative binding generation tools. While connected, these ideas are distinct. Do you feel that these concepts need to be emphasized more?

> * Do all computations currently run on CPUs, and if so, is there interest in exploring GPU implementations?

Yes. At the moment the focus has been scaling out these workflows at dedicated "analysis facilities" to achieve required data processing throughput rates for the next iteration of the LHC ([reference presentation](https://indico.cern.ch/event/1369601/contributions/5924000/)). There is ongoing work to be able to utilize hardware acceleration across the tooling ecosystem. This work is still very much in the research stage and at varying stages of maturity across the ecosystem, but [Awkward Array computations work on GPUs](https://awkward-array.org/doc/2.6/user-guide/how-to-math-gpu.html) and the [statistical libraries support hardware acceleration](https://joss.theoj.org/papers/10.21105/joss.02823).

2024-08-28 22:39 UTC, cliffckerr commented
Thanks @matthewfeickert -- my original comment no longer seems so clear to me :joy: It's probably fine as-is. If you do want to revisit the `nanobind` references, I suppose there is a _bit_ of repetition, with each mention of it going into about the same level of detail:
- The ATLAS collaboration is further extending this ecosystem of tooling to include high-level custom Python bindings to the low level `C++` frameworks using `nanobind` [@nanobind].
- To expose these `C++` libraries to the Pythonic tooling layer, custom Python bindings are written using `nanobind` for high efficiency, as seen in @fig:access_layer_diagram.
- The interface takes advantage of `nanobind`'s efficient bindings and zero-copy exchange protocols to achieve viable performance. [@Kourlitis:2890478]
- computed on-the-fly using the `nanobind` Python bindings to the ATLAS `C++` correction tools.

But it's really not an issue, for some reason I thought there was a full paragraph or at least full sentence repeated.

2024-09-02 21:36 UTC, matthewfeickert commented
(Sorry for the slow reply @cliffckerr &mdash; been doing a week of work travel so I'm behind on a bit of everything.)

> * `The interface takes advantage of nanobind's efficient bindings and zero-copy exchange protocols to achieve viable performance. [@Kourlitis:2890478]`
> * `computed on-the-fly using the nanobind Python bindings to the ATLAS C++ correction tools.`

These two come from figure captions, and I generally like them to be as standalone as possible. Though as you do point out, the sentence preceding Figure 1 

> * `To expose these C++ libraries to the Pythonic tooling layer, custom Python bindings are written using nanobind for high efficiency, as seen in @fig:access_layer_diagram.`

makes the mention in the Figure 1 caption

> * `The interface takes advantage of nanobind's efficient bindings and zero-copy exchange protocols to achieve viable performance. [@Kourlitis:2890478]`

a bit redundant as the focus of Figure 1 is the interface, and while the interface decisions enable performance, the performance isn't the focus. So I'm going to remove this line from Figure 1. :+1:

2024-09-05 14:17 UTC, hongsupshin commented
@cliffckerr @Marcdh3 Hello reviewers, the author @matthewfeickert have responded to your feedback. If you don't have any further comments, could you please approve the PR? Thanks for your time and effort for the review!

2024-09-23 21:20 UTC, hongsupshin commented
Thanks @Marcdh3 @cliffckerr for reviewing the paper!

2024-09-23 21:53 UTC, cliffckerr commented
I don't seem to have the open to re-request review, but I approve!

2024-09-23 23:56 UTC, matthewfeickert commented
> I don't seem to have the option to re-request review, but I approve!

Thanks @cliffckerr! If you'd like to formally hit the button I've triggered review request from you. :) We will take no action to mean "approve" though. :+1:

2024-09-24 00:51 UTC, cliffckerr approved these changes
Looks great, nice work!

2024-09-24 20:45 UTC, matthewfeickert commented on papers/matthew_feickert/mybib.bib
> +      url           = "https://cds.cern.ch/record/2890478",
```suggestion
      url           = "https://indico.cern.ch/event/1330797/contributions/5796636/",
```

@hongsupshin this is very embarrassing, but I realized today while writing a talk that the URL in my reference manager for this poster had an ATLAS internal document server URL for the poster and not the public conference version. :grimacing: Though this is incredibly late would you mind if this got fixed with this suggested change? I didn't notice this before, given that I have access to the internal server and so my cached credentials took me to the document server page.

2024-09-24 20:54 UTC, hongsupshin commented on papers/matthew_feickert/mybib.bib
> +      url           = "https://cds.cern.ch/record/2890478",
Hey Matthew! No worries. Thanks for catching it. We are in the process of merging PRs and getting ready for publishing all the papers. This PR hasn't been merged yet, so I'd say you can commit this change as soon as possible. I will talk to other chairs to freeze the process for this PR in the meantime. Would this work?

2024-09-24 20:56 UTC, matthewfeickert commented on papers/matthew_feickert/mybib.bib
> +      url           = "https://cds.cern.ch/record/2890478",
@hongsupshin yes, and done. :+1: No need to wait as the suggested change was the only fix needed.

2024-09-25 17:30 UTC, merged

2024-09-25 18:52 UTC, matthewfeickert commented
Thanks very much to @cliffckerr @Marcdh3 for their hard work as reviewers to help improve the paper &mdash; it is truly appreciated. Thanks also to @hongsupshin and the rest of the Proceedings Committee for the heroic amounts of work that they did to once again serve the SciPy community and provide a wonderful service to the conference. :pray: