Paper: Climatic and Geographic Influences on Cumacea Genetics in the Northern North Atlantic
scipy-conference/scipy_proceedings pull request #925
Opened 2024-05-31 23:08 UTC by TahiriNadia

If you are creating this PR in order to submit a draft of your paper, please name your PR with `Paper: <title>`. An editor will then add a `paper` label and GitHub Actions will be run to check and build your paper.

See the [project readme](https://github.com/scipy-conference/scipy_proceedings#preview-your-paper) for more information.

_Editor_:  

_Reviewers_:

2024-06-04 12:15 UTC, rowanc1 reviewed
Thanks for the submission @JustGag  - could you please see a few minor technical pieces: (1) restore the presentations folder PDF, (2) update the ID to match the folder name; and (3) remove the unused subtitle.

2024-06-04 12:15 UTC, rowanc1 commented on papers/Gagnon_Kebe_Tahiri/myst.yml
> +  subtitle: LaTeX edition
```suggestion
```

2024-06-04 12:15 UTC, rowanc1 commented on papers/Gagnon_Kebe_Tahiri/myst.yml
> +  id: scipy-2024-00_gagnon_keke_tahiri
```suggestion
  id: scipy-2024-gagnon_keke_tahiri
```

2024-06-04 18:23 UTC, ameyxd commented
@TahiriNadia @JustGag thanks for the submission. Can you make the updates requested to run the checks?

2024-06-04 23:20 UTC, TahiriNadia commented on papers/Gagnon_Kebe_Tahiri/myst.yml
> +  subtitle: LaTeX edition
Thanks @rowanc1 for this observation, we updated.

2024-06-04 23:20 UTC, TahiriNadia commented on papers/Gagnon_Kebe_Tahiri/myst.yml
> +  id: scipy-2024-00_gagnon_keke_tahiri
Thanks @rowanc1 . We updated.

2024-06-05 01:47 UTC, TahiriNadia commented
I don't know why I found the following issue; the DOI is functional.

> × DOI Exists: DOI not found: https://doi.org/10.1016/S0967-0645(97)00046-5 [wilson_historical_1998]

2024-06-05 22:19 UTC, TahiriNadia commented
> Hi @ameyxd and @rowanc1 I don't know why I found the following issue; the DOI is functional.
> 
> > × DOI Exists: DOI not found: https://doi.org/10.1016/S0967-0645(97)00046-5 [wilson_historical_1998]

@cbcunc any idea related to DOI?

2024-06-24 16:22 UTC, kevinlacaille reviewed
Hello, @TahiriNadia! I am the reviewer for your paper. Could you please provide me with the compiled PDF in this PR?

2024-06-24 17:00 UTC, kevinlacaille commented on papers/Gagnon_Kebe_Tahiri/main.tex
> +\section{Related Works}\label{related-works}
Consider adding a brief summary at the end highlighting the gap this study fills.

2024-06-24 17:42 UTC, kevinlacaille requested changes
Dear @TahiriNadia et al.,

Thank you for your submission to the SciPy conference proceedings. I have reviewed your paper, and I commend you for the thorough research and detailed analysis presented. Below, I provide feedback and suggestions for improvement based on the [review criteria provided](https://github.com/scipy-conference/scipy_proceedings/blob/2024/README.md#instructions-for-reviewers).

#### Written Quality

1. **Clarity and Coherence:**
   - The language is clear and the narrative is coherent. However, a few sentences are lengthy and could be split for better readability. For example, in the abstract, "These initial findings necessitate further exploration to elucidate the intricate relationships between Cumacean genetics and their environment." could be revised to "These findings necessitate further exploration to understand the relationships between Cumacean genetics and their environment."
   - Some sections, particularly in the "Materials and Methods" and "Results" sections, use complex sentence structures that might be simplified for clarity.

2. **Jargon and Accessibility:**
   - Due to the interdisciplinary nature of SciPy, highly domain-specific jargon should be avoided or explained where possible. Terms like "phylogeographic models," "mitochondrial 16S rRNA gene," and "Robinson-Foulds distance" are well-explained. However, it might be helpful to provide brief explanations or footnotes for highly specialized terms, e.g., "thermohaline circulation" or "benthic habitats."

#### Technical Content

3. **Scientific Soundness:**
   - The scientific content is robust and well-referenced. However, some claims would benefit from additional support or clarification. For instance, the assertion that "Cumacean diversity also exhibited variation across habitat types" could be strengthened by directly referencing specific data or figures.
   - Ensure that all methodological steps are clearly defined. The section on DNA sequence analysis should detail the specific software versions and parameters used for reproducibility.

4. **Computational Content:**
   - The computational methods, including the use of `aPhyloGeo` software, are thoroughly explained. Including a supplementary section or appendix with the complete code used for the analyses could enhance verifiability.

#### Novelty and Impact

5. **Advancement of the Field:**
   - The study presents a novel investigation into the genetic and environmental correlations in Cumacea. Emphasize the novelty more explicitly by comparing it directly with previous studies in the introduction or conclusion sections.
   - Highlight how this research could influence future studies or practical applications in marine conservation and climate change mitigation.

#### Verifiability

6. **Source Code and Data:**
   - The paper includes references to the source code available on GitHub and PyPi, enhancing verifiability. Ensure that the links are up-to-date and that the repositories contain clear documentation for users to replicate the study.
   - Data sources are clearly identified, and the methodology allows for reproduction of results.

7. **Workflow Description:**
   - The workflow description is comprehensive. A flowchart or diagram summarizing the workflow could help readers better understand the sequence of steps involved.

#### Other Requirements

8. **Citations and Acronyms:**
   - Maintain consistency in citation style. For example, use either `"Figure \ref{fig}"` or `"Fig. \ref{fig}"` uniformly throughout the text.
   - Acronyms are well-defined at first mention. Ensure that all technical terms are consistently defined and used throughout the paper.

9. **Figures and Tables:**
   - Figures have clear captions, but some text within the figures is small and difficult to read. Increase the font size for better readability.
   - Ensure all figures are properly referenced in the text and discussed in detail.

10. **Code Snippets:**
    - Code snippets are well-formatted. Ensure that all code snippets are indented consistently and follow PEP8 guidelines.

#### Length

11. **Page Limit:**
    - TBD if the paper adheres to the page limit (8 pages). Some sections, such as the "Introduction" and "Results," could be trimmed to focus more on key findings and less on background information that might be well-known to the target audience.

### Summary Feedback

Overall, this paper is a valuable contribution to the field of marine biology and environmental science. It effectively combines genetic and environmental data to explore the adaptation of Cumacea to their habitats. The methodology is robust, and the findings are well-supported by the data. A few minor revisions could enhance clarity and accessibility for a broader audience.

Cheers,

Kevin Lacaille

2024-06-24 17:42 UTC, kevinlacaille commented on papers/Gagnon_Kebe_Tahiri/main.tex
> +As stipulated in the hypothesis of Darwin, individuals best adapted to their environment are likely to survive, reproduce, and evolve. The objective of this study is to deepen and strengthen the natu
Consider adding a brief summary at the end highlighting the gap this study fills.

2024-06-24 17:42 UTC, kevinlacaille commented on papers/Gagnon_Kebe_Tahiri/main.tex
> +\section{Materials and Methods}\label{materials-methods}
Consider adding a flowchart or diagram of the methodology.

2024-06-24 17:42 UTC, kevinlacaille commented on papers/Gagnon_Kebe_Tahiri/main.tex
> +In response to the current climate emergency, this study aims to undertake an in-depth analysis of the influence of extreme climatic parameters and environmental peculiarities on Cumacea (crustaceans
Some domain-specific jargon (e.g., phylogeographic terms) could benefit from brief explanations.

2024-06-24 17:42 UTC, kevinlacaille commented on papers/Gagnon_Kebe_Tahiri/main.tex
> +Our analyses reveal significant spatial variation in environmental parameters, particularly depth, temperature, and dissolved oxygen. Cumacean diversity also exhibited variation across habitat types.
Can you quantify "significant"? Consider adding p-values or effect sizes, etc.

2024-06-24 17:42 UTC, kevinlacaille commented on papers/Gagnon_Kebe_Tahiri/main.tex
> +These initial findings necessitate further exploration to elucidate the intricate relationships between Cumacean genetics and their environment. This study lays the groundwork for establishing correl
This first sentence is passive. Consider rephrasing actively: "These initial findings highlight the need for further exploration..."

2024-06-24 17:42 UTC, kevinlacaille commented on papers/Gagnon_Kebe_Tahiri/main.tex
> +In response to the current climate emergency, this study aims to undertake an in-depth analysis of the influence of extreme climatic parameters and environmental peculiarities on Cumacea (crustaceans
Provide a brief explanation of what `aPhyloGeo` does and why it's suitable for this analysis.

2024-06-24 17:42 UTC, kevinlacaille commented on papers/Gagnon_Kebe_Tahiri/main.tex
> +In response to the current climate emergency, this study aims to undertake an in-depth analysis of the influence of extreme climatic parameters and environmental peculiarities on Cumacea (crustaceans
Explain why 16S rRNA was chosen. Is it standard for this type of analysis?

2024-06-24 17:42 UTC, kevinlacaille commented on papers/Gagnon_Kebe_Tahiri/main.tex
> +These initial findings necessitate further exploration to elucidate the intricate relationships between Cumacean genetics and their environment. This study lays the groundwork for establishing correl
Great that you've provided links, thank you! Consider adding a DOI for the specific version used in this study.

2024-06-24 17:42 UTC, kevinlacaille commented on papers/Gagnon_Kebe_Tahiri/main.tex
> +APW (Arctic Polar Water) has a high family diversity, with a significant presence of the Leuconidae, Diastylidae, and Astacidae. APW/NSAIW (Arctic Polar Water/North Sub-Arctic Intermediate Water) sho
APW is not spelled out on first use, earlier on in the paper. Please define all acronyms when first introduced.

2024-06-24 17:42 UTC, kevinlacaille commented on papers/Gagnon_Kebe_Tahiri/main.tex
> +These diagrams are critical for designing the conditions of the habitats where the samples were collected, as high variability in the data may indicate heterogeneous habitats, while low variability i
Consider adding brief explanations of how to interpret violin plots for readers unfamiliar with this type of visualization.

2024-06-24 17:42 UTC, kevinlacaille commented on papers/Gagnon_Kebe_Tahiri/main.tex
> +    def robinsonFoulds(tree1, tree2):
Consider adding comments to explain what each part of the function does. What are x2, x3, x4, x5, etc.?

2024-06-24 17:42 UTC, kevinlacaille commented on papers/Gagnon_Kebe_Tahiri/main.tex
> +\begin{abstract}
Please consider quantifying some of the key findings (e.g., specific correlation values) for more precision.

2024-06-24 17:42 UTC, kevinlacaille commented on papers/Gagnon_Kebe_Tahiri/main.tex
> +\section{Introduction}\label{introduction}
Consider providing a brief overview of the importance of Cumacea in marine ecosystems at the beginning of the introduction to set the context.

2024-06-24 17:42 UTC, kevinlacaille commented on papers/Gagnon_Kebe_Tahiri/main.tex
> +\section{Related Works}\label{related-works}
Some sections in "Related Works" could be shortened or summarized to maintain focus on the primary research question.

2024-06-24 17:42 UTC, kevinlacaille commented on papers/Gagnon_Kebe_Tahiri/main.tex
> +\section{Materials and Methods}\label{materials-methods}
While detailed, some subsections could benefit from further simplification or breaking down into smaller, more digestible parts.

2024-06-24 17:42 UTC, kevinlacaille commented on papers/Gagnon_Kebe_Tahiri/main.tex
> +\section{Results}\label{results}
The interpretation of figures could be expanded to provide more context and implications of the findings.

2024-06-24 17:42 UTC, kevinlacaille commented on papers/Gagnon_Kebe_Tahiri/main.tex
> +\section{Conclusion}\label{conclusion}
The conclusion effectively summarizes the findings but could emphasize the broader implications more. For example, discuss how these findings could inform conservation strategies or future research directions. Consider adding a sentence or two about potential limitations of the study and how future research could address them.

2024-06-24 17:42 UTC, kevinlacaille commented on papers/Gagnon_Kebe_Tahiri/main.tex
> +The biological and environmental baseline data collected by the IceAGE project and its predecessors BIOFAR and BIOICE, which studied the biodiversity of the Faroe Islands and Iceland, are invaluable
The introduction provides a comprehensive background. However, the paragraph starting with "The biological and environmental baseline data..." could be shortened by summarizing the projects mentioned.

2024-06-24 17:42 UTC, kevinlacaille commented on papers/Gagnon_Kebe_Tahiri/main.tex
> +In response to the current climate emergency, this study aims to undertake an in-depth analysis of the influence of extreme climatic parameters and environmental peculiarities on Cumacea (crustaceans
Add a sentence at the end of the introduction clearly stating the main objectives and hypotheses of the study.

2024-06-24 17:42 UTC, kevinlacaille commented on papers/Gagnon_Kebe_Tahiri/main.tex
> +\subsection{Data pre-processing}
Consider breaking down lengthy paragraphs into bullet points or numbered steps for clarity. For instance, this subsection "Data pre-processing" could list steps in the data reduction process more clearly.

2024-06-24 17:42 UTC, kevinlacaille commented on papers/Gagnon_Kebe_Tahiri/main.tex
> +\section{Results}\label{results}
The results are comprehensive but could be more concise. Focus on key findings and their implications. For example, the detailed explanation of figures could be summarized, with in-depth analysis provided in supplementary materials.

2024-06-30 21:03 UTC, JustGag commented
Hi @kevinlacaille ,

Thank you for your comments and suggestions. 

Best regards and successful science,

Justin Gagnon

2024-07-01 15:08 UTC, JustGag commented
Written Quality
Clarity and Coherence:

The language is clear and the narrative is coherent. However, a few sentences are lengthy and could be split for better readability. For example, in the abstract, "These initial findings necessitate further exploration to elucidate the intricate relationships between Cumacean genetics and their environment." could be revised to "These findings necessitate further exploration to understand the relationships between Cumacean genetics and their environment."

Some sections, particularly in the "Materials and Methods" and "Results" sections, use complex sentence structures that might be simplified for clarity.

Reply: Thank you for your thoughtful comments. We have revised and applied your sentence in our article. 

We also consider simplifying and clarifying sentences throughout the article, especially in the "Materials and Methods" and "Results" sections.

2024-07-01 15:23 UTC, JustGag commented
Jargon and Accessibility:

Due to the interdisciplinary nature of SciPy, highly domain-specific jargon should be avoided or explained where possible. Terms like "phylogeographic models," "mitochondrial 16S rRNA gene," and "Robinson-Foulds distance" are well-explained. However, it might be helpful to provide brief explanations or footnotes for highly specialized terms, e.g., "thermohaline circulation" or "benthic habitats."

Reply: Thank you for your comments. We are considering adding a footnote for these specialized terms: "thermohaline circulation" and "benthic habitats".

2024-07-01 15:51 UTC, JustGag commented
Technical Content
Scientific Soundness:

The scientific content is robust and well-referenced. However, some claims would benefit from additional support or clarification. For instance, the assertion that "Cumacean diversity also exhibited variation across habitat types" could be strengthened by directly referencing specific data or figures.

Ensure that all methodological steps are clearly defined. The section on DNA sequence analysis should detail the specific software versions and parameters used for reproducibility.

Reply: Thank you very much for your comments. We are considering reinforcing some of our statements, including the one you mentioned, by referencing specific figures.

In addition, in the interest of reproducible science, we will add the specific software version and parameters used in the section on DNA sequence analysis.

2024-07-01 16:17 UTC, JustGag commented
Technical Content

Computational Content:

The computational methods, including the use of aPhyloGeo software, are thoroughly explained. Including a supplementary section or appendix with the complete code used for the analyses could enhance verifiability.

Reply: Thank you for your comment. We have made sure that all the code and parameters used in our analyses have been put on the aPhyloGeo library, which can be accessed via the GitHub link in the abstract.

Best regards,

Justin Gagnon

2024-07-01 16:47 UTC, JustGag commented
Novelty and Impact

Advancement of the Field:

The study presents a novel investigation into the genetic and environmental correlations in Cumacea. Emphasize the novelty more explicitly by comparing it directly with previous studies in the introduction or conclusion sections.
Highlight how this research could influence future studies or practical applications in marine conservation and climate change mitigation.

Reply: Thank you for this highly pertinent comment. We plan to include a section that discusses and highlights the potential influences this study could have on future studies or practical applications in marine conservation and climate change mitigation.

Best regards,

Justin Gagnon

2024-07-01 17:46 UTC, JustGag commented
Verifiability

Source Code and Data:

The paper includes references to the source code available on GitHub and PyPi, enhancing verifiability. Ensure that the links are up-to-date and that the repositories contain clear documentation for users to replicate the study.

Data sources are clearly identified, and the methodology allows for reproduction of results.

Reply: Thank you for your comment. We have ensured that the links are up-to-date and that the repositories contain clear and relevant documentation for users to reproduce our study.

Best regards,

Justin Gagnon

2024-07-01 18:08 UTC, JustGag commented
Verifiability

Workflow Description:

The workflow description is comprehensive. A flowchart or diagram summarizing the workflow could help readers better understand the sequence of steps involved.

Reply: Thank you very much for this pertinent comment. We will be sure to add a diagram in the "Materials and Methods" section that will summarize the pre-processing steps as well as the analyses of our data.

Best regards, 

Justin Gagnon

2024-07-01 18:42 UTC, JustGag commented
Other Requirements

Citations and Acronyms:

Maintain consistency in citation style. For example, use either "Figure \ref{fig}" or "Fig. \ref{fig}" uniformly throughout the text.

Acronyms are well-defined at first mention. Ensure that all technical terms are consistently defined and used throughout the paper.

Reply: Thank you for these remarks. We will ensure to maintain a consistent citation style throughout our article.

Additionally, we will verify that each technical term used in our article is consistently defined.

Best regards,

Justin Gagnon

2024-07-02 17:04 UTC, kevinlacaille commented
@JustGag thank you for your updates! Could you please attach the compiled PDF to this pull request?

2024-07-02 21:37 UTC, TahiriNadia commented
> @JustGag thank you for your updates! Could you please attach the compiled PDF to this pull request?

@kevinlacaille - Thank you for the positive reviews and detailed feedback. We will thoroughly review the paper multiple times to refine the writing.

For the PDF question, we currently only have the web version available:
https://sites.curvenote.com/build/01906ae9-4361-7ea5-b71c-46a1bceb0204

2024-07-03 11:30 UTC, JustGag commented
Jargon and Accessibility:

Due to the interdisciplinary nature of SciPy, highly domain-specific jargon should be avoided or explained where possible. Terms like "phylogeographic models," "mitochondrial 16S rRNA gene," and "Robinson-Foulds distance" are well-explained. However, it might be helpful to provide brief explanations or footnotes for highly specialized terms, e.g., "thermohaline circulation" or "benthic habitats."

Reply: Thank you for your comments. We have added a footnote to the article for the specific terms you suggested, such as thermohaline circulation and benthic habitats.

2024-07-03 20:17 UTC, kevinlacaille commented
@JustGag , @TahiriNadia , et al.,

Thank you for the updates. Please tag me back in when the paper is ready for a re-review!

Cheers,
Kevin

2024-07-04 00:56 UTC, JustGag commented
Novelty and Impact
Advancement of the Field:
The study presents a novel investigation into the genetic and environmental correlations in Cumacea. Emphasize the novelty more explicitly by comparing it directly with previous studies in the introduction or conclusion sections.
Highlight how this research could influence future studies or practical applications in marine conservation and climate change mitigation.

Reply: We thank you for this pertinent comment. We have included a section, in the last paragraph of the Related work section, explaining and highlighting the potential influences this study could have on future studies or practical applications in marine conservation and climate change mitigation.

2024-07-04 01:37 UTC, JustGag commented
Other Requirements

Citations and Acronyms:

Maintain consistency in citation style. For example, use either "Figure \ref{fig}" or "Fig. \ref{fig}" uniformly throughout the text.

Acronyms are well-defined at first mention. Ensure that all technical terms are consistently defined and used throughout the paper.

Reply: Thank you for your comments. We have made sure to maintain the citation style consistent throughout the article. In addition, we have checked that all acronyms are well-defined when first used.

2024-07-04 11:52 UTC, JustGag commented on papers/Gagnon_Kebe_Tahiri/main.tex
> +As stipulated in the hypothesis of Darwin, individuals best adapted to their environment are likely to survive, reproduce, and evolve. The objective of this study is to deepen and strengthen the natu
Thank you for your comment. We added a paragraph at the end of the "Related work" section highlighting the gap this study fills.

2024-07-04 11:56 UTC, JustGag commented on papers/Gagnon_Kebe_Tahiri/main.tex
> +These initial findings necessitate further exploration to elucidate the intricate relationships between Cumacean genetics and their environment. This study lays the groundwork for establishing correl
Thank you for your comment. We have changed the sentence in the article according to your recommendation.

2024-07-04 12:04 UTC, JustGag commented on papers/Gagnon_Kebe_Tahiri/main.tex
> +These initial findings necessitate further exploration to elucidate the intricate relationships between Cumacean genetics and their environment. This study lays the groundwork for establishing correl
Thank you for your comment. We have made sure that all acronyms are defined the first time they are used.

2024-07-04 22:40 UTC, JustGag commented on papers/Gagnon_Kebe_Tahiri/main.tex
> +In response to the current climate emergency, this study aims to undertake an in-depth analysis of the influence of extreme climatic parameters and environmental peculiarities on Cumacea (crustaceans
> Explain why 16S rRNA was chosen. Is it standard for this type of analysis?

Thank you for your comment. We have included in the last paragraph of the "Data pre-processing" section a sentence justifying why the 16S rRNA region was chosen for our study. It is indeed standard in phylogeny and phylogeography studies.

2024-07-05 03:10 UTC, JustGag commented on papers/Gagnon_Kebe_Tahiri/main.tex
> +These diagrams are critical for designing the conditions of the habitats where the samples were collected, as high variability in the data may indicate heterogeneous habitats, while low variability i
Thank you for your comment. We have included in the first paragraph of the "Results" section an explanation of how to interpret a violin diagram.

2024-07-05 04:49 UTC, JustGag commented on papers/Gagnon_Kebe_Tahiri/main.tex
> +\section{Introduction}\label{introduction}
Thank you for your pertinent comment. We have elaborated in the fourth paragraph of the "Introduction" section on the importance of Cumacea in the marine ecosystem.

2024-07-06 17:45 UTC, JustGag commented on papers/Gagnon_Kebe_Tahiri/main.tex
> +\section{Related Works}\label{related-works}
Thank you for your comment. We have shortened most of the sentences in the third and fourth paragraphs of the "Related work" section.

2024-07-06 20:09 UTC, JustGag commented on papers/Gagnon_Kebe_Tahiri/main.tex
> +\section{Conclusion}\label{conclusion}
We thank you for these pertinent comments. We have added explanations and clarifications in the penultimate paragraph of the "Conclusion" on how our results could improve conservation strategies and the direction of future studies on the subject. We also discuss this in the last paragraph of the "Related work" section. 

In addition, we have also added a fourth paragraph to the "Conclusion" concerning the limitations of our study and how future studies should address them.

2024-07-06 20:35 UTC, JustGag commented on papers/Gagnon_Kebe_Tahiri/main.tex
> +The biological and environmental baseline data collected by the IceAGE project and its predecessors BIOFAR and BIOICE, which studied the biodiversity of the Faroe Islands and Iceland, are invaluable
Thank you for your comment. We have shortened the paragraph you mentioned (the second paragraph of the "Introduction" section) by summarizing the projects mentioned.

2024-07-06 21:41 UTC, JustGag commented on papers/Gagnon_Kebe_Tahiri/main.tex
> +The biological and environmental baseline data collected by the IceAGE project and its predecessors BIOFAR and BIOICE, which studied the biodiversity of the Faroe Islands and Iceland, are invaluable
Thank you for your thoughtful comments. We have included bullet points in the paragraphs listing the attributes selected in this study. We have also added numbering to the section dealing with data processing (beginning of the "Data pre-processing" section).

2024-07-06 21:56 UTC, JustGag commented on papers/Gagnon_Kebe_Tahiri/main.tex
> +\subsection{Data pre-processing}
Thank you for your thoughtful comments. We have included bullet points in most of the paragraphs listing the attributes selected in this study. We have also added numbering to the section dealing with data processing (beginning of the "Data pre-processing" section).

2024-07-07 03:57 UTC, JustGag commented on papers/Gagnon_Kebe_Tahiri/main.tex
> +\section{Materials and Methods}\label{materials-methods}
> While detailed, some subsections could benefit from further simplification or breaking down into smaller, more digestible parts.

Thank you for your comment. We have broken down most of the "Materials and Methods" section into smaller parts to make it easier to read.

2024-07-09 04:10 UTC, JustGag commented
Ensure that all methodological steps are clearly defined. The section on DNA sequence analysis should detail the specific software versions and parameters used for reproducibility.

Reply: Thank you for this comment. In the abstract, we have included the YAML file in the aPhyloGeo GitHub link. We added the main parameters to the article (Methodology).

2024-07-09 04:32 UTC, JustGag commented on papers/Gagnon_Kebe_Tahiri/main.tex
> +These initial findings necessitate further exploration to elucidate the intricate relationships between Cumacean genetics and their environment. This study lays the groundwork for establishing correl
> Great that you've provided links, thank you! Consider adding a DOI for the specific version used in this study.

Thanks for the tip, but we don't have a DOI for the aPhyloGeo tool.

2024-07-23 00:22 UTC, JustGag commented
Some sections, particularly in the "Materials and Methods" and "Results" sections, use complex sentence structures that might be simplified for clarity.

Reply: Thank you for your pertinent comment. We have simplified the sentence structure in the “Materials and Methods” and “Results” sections.

2024-07-23 00:29 UTC, JustGag commented
Length

Page Limit:

TBD if the paper adheres to the page limit (8 pages). Some sections, such as the "Introduction" and "Results," could be trimmed to focus more on key findings and less on background information that might be well-known to the target audience.

Reply: Thank you for your comment. We have reduced the “Introduction” and “Results” sections to focus more on the key findings and less on background information that might be well-known to the target audience.

2024-07-23 00:32 UTC, JustGag commented on papers/Gagnon_Kebe_Tahiri/main.tex
> +Our analyses reveal significant spatial variation in environmental parameters, particularly depth, temperature, and dissolved oxygen. Cumacean diversity also exhibited variation across habitat types.
Thank you for your comment. As we cannot yet quantify our results, we have removed the word “significant” from the article.

2024-07-23 00:36 UTC, JustGag commented on papers/Gagnon_Kebe_Tahiri/main.tex
> +\begin{abstract}
Thank you for sharing the relevant comment. We have quantified some of the key findings of our analyses to add more precision.

2024-07-23 00:40 UTC, JustGag commented on papers/Gagnon_Kebe_Tahiri/main.tex
> +\section{Results}\label{results}
> The interpretation of figures could be expanded to provide more context and implications of the findings.

Thank you for your pertinent comment. We have expanded the interpretation of the figures to give more context and implications to our findings.

2024-07-23 00:43 UTC, JustGag commented on papers/Gagnon_Kebe_Tahiri/main.tex
> +In response to the current climate emergency, this study aims to undertake an in-depth analysis of the influence of extreme climatic parameters and environmental peculiarities on Cumacea (crustaceans
> Provide a brief explanation of what `aPhyloGeo` does and why it's suitable for this analysis.

Thank you for your comment. We have provided a brief explanation of what `aPhyloGeo` does and why it's suitable for our analyses.

2024-07-25 03:09 UTC, JustGag commented on papers/Gagnon_Kebe_Tahiri/main.tex
> +In response to the current climate emergency, this study aims to undertake an in-depth analysis of the influence of extreme climatic parameters and environmental peculiarities on Cumacea (crustaceans
> Add a sentence at the end of the introduction clearly stating the main objectives and hypotheses of the study.

We thank you for this comment. We added a sentence at the end of the introduction clearly stating the main objective and hypothesis of our study.

2024-07-27 11:15 UTC, JustGag commented
Verifiability

Workflow Description:

The workflow description is comprehensive. A flowchart or diagram summarizing the workflow could help readers better understand the sequence of steps involved.

Reply: Thank you for this insightful remark. We have included a flowchart in the Materials and Methods section that summarizes the workflow.

2024-07-27 11:15 UTC, JustGag commented on papers/Gagnon_Kebe_Tahiri/main.tex
> +\section{Materials and Methods}\label{materials-methods}
> Consider adding a flowchart or diagram of the methodology.

Thank you for this insightful remark. We have included a flowchart in the Materials and Methods section that summarizes the workflow.

2024-08-03 22:34 UTC, JustGag commented on papers/Gagnon_Kebe_Tahiri/main.tex
> +\section{Results}\label{results}
> The results are comprehensive but could be more concise. Focus on key findings and their implications. For example, the detailed explanation of figures could be summarized, with in-depth analysis provided in supplementary materials.

Thank you for this pertinent comment. We have summarized the results to focus on the key findings and their implications. We have also included an in-depth analysis of our results in the “additional” section on this GitHub link (https://github.com/tahiri-lab/Cumacea_aPhyloGeo).

2024-08-03 22:49 UTC, JustGag commented
Other Requirements

Figures and Tables:

Ensure all figures are properly referenced in the text and discussed in detail.

Reply: Thank you for your comments. We have ensured that all figures are correctly referenced in the text and discussed in detail. However, an in-depth analysis of the results can be found in the “supplementary” section of this GitHub link (https://github.com/tahiri-lab/Cumacea_aPhyloGeo).

2024-08-07 03:49 UTC, TahiriNadia commented
> @JustGag , @TahiriNadia , et al.,
> 
> Thank you for the updates. Please tag me back in when the paper is ready for a re-review!
> 
> Cheers, Kevin

Thank you, @kevinlacaille, for your valuable feedback. @JustGag and I have implemented the suggested modifications.

2024-08-07 05:48 UTC, kevinlacaille commented
Thank you @JustGag and @TahiriNadia! Before I re-review, could you please compile the latex and attach a PDF of the paper to the PR?

2024-08-07 16:43 UTC, TahiriNadia commented
> Thank you @JustGag and @TahiriNadia! Before I re-review, could you please compile the latex and attach a PDF of the paper to the PR?

Thank you, @kevinlacaille. This year, the format will be [HTML](https://proceedings.scipy.org/previews/01912ae8-a993-7765-ab2b-88823e4bb323?preview=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJodHRwczovL2pvdXJuYWxzLmN1cnZlbm90ZS5jb20iLCJleHAiOjE3MjM0ODA5MjYsImF1ZCI6InNjaXB5Iiwic2NvcGUiOiJzdWJtaXNzaW9uIiwic2NvcGVJZCI6IjAxOGZlNTM3LTQzYmMtNzMxOS1iNzNmLTk2ZGRkMjlkYjg4NSIsImlhdCI6MTcyMzA0ODkyNn0.z12fbIoSaMEo06zbyNjwtQ91t0-6uvIo85eysxdxC5o) during the preparation and review steps, and the PDF will be created only after acceptance, unlike in previous years. I asked the same question at the beginning because of the page limitations.
_Citation_: 'The paper is written and reviewed using the interactive HTML view (i.e. myst start), the PDF is built upon acceptance only'. 
_Source_: https://github.com/scipy-conference/scipy_proceedings?tab=readme-ov-file

2024-08-13 16:10 UTC, sanhitamj commented
> Thank you @JustGag and @TahiriNadia! Before I re-review, could you please compile the latex and attach a PDF of the paper to the PR?

@kevinlacaille, @TahiriNadia  you can see the (compiled) preview [here](https://proceedings.scipy.org/previews/01912ae8-a993-7765-ab2b-88823e4bb323?preview=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJodHRwczovL2pvdXJuYWxzLmN1cnZlbm90ZS5jb20iLCJleHAiOjE3MjM5OTcxMzUsImF1ZCI6InNjaXB5Iiwic2NvcGUiOiJzdWJtaXNzaW9uIiwic2NvcGVJZCI6IjAxOGZlNTM3LTQzYmMtNzMxOS1iNzNmLTk2ZGRkMjlkYjg4NSIsImlhdCI6MTcyMzU2NTEzNX0.OwCWEzc1_Yd6PGMrtmQQHcgA1HxeOyi6tzsyEdzVIyg). Or in the Github-Actions sections, click on the Inspect link.

2024-08-13 19:28 UTC, kevinlacaille requested changes
Dear authors,

Thank you for your revisions! Overall, the paper is well-structured and provides valuable insights into the study of cumacean genetics and their environmental interactions. By addressing the suggestions below, the authors can enhance the clarity, accessibility, and impact of their research.

**Language and Grammar**

1. Grammatical Errors:
   - In the abstract: "The most represent cumacean are those of the Diastylidae and Leuconidae families" should be "The most represented cumaceans are those of the Diastylidae and Leuconidae families."

2. Lengthy Sentences:
   - In the abstract: "These initial results underline the need for further exploration to understand the relationships between the genetics of cumacean and their environment." could be split into "These results highlight the need for further exploration. Understanding the relationships between cumacean genetics and their environment is crucial."
   
3. Awkward Phrasing:
   - In the introduction: "The slowdown in the formation of cold, deep waters due to the loss of Arctic sea ice can influence their regional dynamics and chemistry" could be rephrased to "The loss of Arctic sea ice and the resulting slowdown in cold, deep water formation may influence regional dynamics and chemistry."

4. Clarifying Terms:
   - In the introduction, terms like "benthic habitats" are defined well, but others, such as "thermohaline circulation," could benefit from brief explanations or a glossary to aid interdisciplinary understanding.

**Formatting and Consistency**

1. Consistent Terminology:
   - Ensure consistent use of "Cumacea" versus "cumacean" throughout the document. For example, use "Cumacea" when referring to the taxonomic group and "cumacean" when referring to individual species.

2. Citation Style:
   - Ensure consistency in citation formatting. For example, in the introduction, "as well as the North Atlantic at high latitudes, play an essential role in the {thermohaline circulation}" should consistently use either full citation or abbreviation within brackets: `{Thermohaline circulation}\citep{talley2013closure}.`

3. Figure Labeling:
   - Maintain consistency in figure references. For example, use "Figure \ref{fig:fig2}" uniformly throughout the text.

4. Section Headings:
   - Ensure consistent capitalization and formatting of section headings. For example, use either "Materials and Methods" or "Materials & Methods" consistently across the document.

5. Code Formatting:
   - Code snippets should consistently follow PEP8 guidelines, ensuring proper indentation and line spacing, as shown in the `aPhyloGeo` package code listings.
  - Provide comments within the code to explain key steps and logic, particularly for complex calculations.
  - Consider providing a brief description before each code listing to summarize its purpose and relevance to the study.


**Content and Structure**

1. Abstract:
   - The abstract effectively summarizes the study's goals and methods. However, it can be refined for clarity by splitting lengthy sentences and directly mentioning the implications of the findings.

2. Introduction:
   - The introduction provides a comprehensive background but can be streamlined to focus more on the study's specific objectives and less on broader context, which might already be familiar to the target audience.

3. Materials and Methods:
   - The section is detailed but could benefit from additional clarification on methodological steps. For example, specify software versions and parameters used in DNA sequence analysis for reproducibility.

4. Results:
   - The results are well-organized, but some claims would benefit from additional support or clarification. For instance, the assertion that "Cumacean diversity also exhibited variation across habitat types" could be strengthened by directly referencing specific data or figures.

5. Figures:
   - Figures are well-captioned, but some text within the figures is small and difficult to read. Consider increasing the font size for better readability.

6. Conclusion:
   - The conclusion effectively summarizes the study but could more explicitly highlight the novelty of the findings compared to previous research and their potential impact on future studies or practical applications.

**Overall Recommendations**

- Interdisciplinary Accessibility:
  - Due to SciPy's interdisciplinary nature, avoid or explain domain-specific jargon where possible. Consider adding a glossary for specialized terms like "thermohaline circulation" or "benthic habitats."

- Scientific Robustness:
  - The scientific content is robust and well-referenced. However, ensure all claims are supported with data or literature references, and consider trimming sections that may offer redundant background information.

- Conciseness:
  - While the paper remains within the page limit, consider trimming sections like the "Introduction" and "Results" to focus more on key findings and less on background information.

2024-08-13 19:28 UTC, kevinlacaille commented on papers/Gagnon_Kebe_Tahiri/main.tex
> +    climaticTrees = utils.climaticPipeline(climatic_data)
In this code example you mix up casing between `snake_case` and `lowerCamelCase`. In Python, it is common practice to set variable names with `snake_case`, so I would suggest changing the following:
```
sequenceFile > sequence_file
geneticTrees > genetic_trees
climaticTrees > climatic_trees
```

2024-08-13 19:28 UTC, kevinlacaille commented on papers/Gagnon_Kebe_Tahiri/main.tex
> +\begin{abstract}
**Content:** 
- The abstract provides a clear overview of the study's objectives, methods, and initial findings. It highlights the significance of Cumacea as indicators of benthic health and introduces the use of the `aPhyloGeo` software.

**Suggestions:** 
  - Clarify the term "most represent cumacean," which should be "most represented cumaceans."
  - Consider splitting lengthy sentences for better readability, e.g., "These initial results underline the need for further exploration to understand the relationships between the genetics of cumacean and their environment" could be divided for clarity.
  - Mention the broader implications or potential applications of the findings in a concise sentence to round off the abstract.

2024-08-13 19:28 UTC, kevinlacaille commented on papers/Gagnon_Kebe_Tahiri/main.tex
> +\section{Introduction}\label{introduction}
**Content:** 
- The introduction provides a comprehensive background on the ecological significance of the North Atlantic region, the role of Cumacea in marine ecosystems, and the study's objectives.

**Suggestions:**
  - Streamline the introduction by focusing more on the study's specific goals and less on the broad context, assuming some familiarity by the audience with general marine ecology topics.
  - Clarify terms like "thermohaline circulation" with brief explanations or footnotes for interdisciplinary accessibility.
  - Refine sentence structure for clarity, e.g., "The slowdown in the formation of cold, deep waters due to the loss of Arctic sea ice can influence their regional dynamics and chemistry" could be more direct.

2024-08-13 19:28 UTC, kevinlacaille commented on papers/Gagnon_Kebe_Tahiri/main.tex
> +\section{Related Works}\label{related-works}
**Content:** 
- This section reviews relevant literature on the biodiversity and biogeography of deep-sea benthic invertebrates, highlighting the need for integrated genetic and habitat analyses.

**Suggestions:**
  - Ensure clarity in the discussion of genotype-environment interactions and the complexity of the relationships between genetics and the environment.
  - Add more direct comparisons or contrasts with the current study to emphasize the novelty or advancement of this research.
  - Avoid dense technical jargon without explanation to maintain accessibility.

2024-08-13 19:28 UTC, kevinlacaille commented on papers/Gagnon_Kebe_Tahiri/main.tex
> +\section{Our Contribution}\label{contribution}
**Content:** 
- The section outlines the study's specific contributions, including insights into genetic variation, adaptation, and conservation implications.

**Suggestions:**
  - Highlight the novelty of the findings by comparing them directly with previous studies, particularly in the introduction or conclusion.
  - Consider emphasizing the practical implications of the research, such as potential applications in marine conservation strategies.

2024-08-13 19:28 UTC, kevinlacaille commented on papers/Gagnon_Kebe_Tahiri/main.tex
> +\section{Materials and Methods}\label{materials-methods}
**Content:** 
- This section details the data collection, pre-processing, and analysis steps using the `aPhyloGeo` software, including a comprehensive flow chart for clarity.

**Suggestions:**
  - Provide specific software versions and parameters used for reproducibility in DNA sequence analysis.
  - Ensure all methodological steps are clearly defined and logically ordered.
  - Consider adding more detail to the description of the `aPhyloGeo` software's functions and capabilities to enhance understanding.

2024-08-13 19:28 UTC, kevinlacaille commented on papers/Gagnon_Kebe_Tahiri/main.tex
> +\section{Metrics}\label{metrics}
**Content:** 
- The section explains the metrics used to evaluate phylogeographic models, including Robinson-Foulds distance, Euclidean distance, and Least-Squares distance.

**Suggestions:**
  - Ensure that the formulas are clearly explained, especially for a potentially diverse audience.
  - Consider providing examples of how these metrics are applied in the study for clearer understanding.
  - Ensure code snippets are consistent with PEP8 guidelines and clearly formatted.

2024-08-13 19:28 UTC, kevinlacaille commented on papers/Gagnon_Kebe_Tahiri/main.tex
> +\section{Results}\label{results}
**Content:** 
- The results are presented with supporting figures and analysis, showing environmental variability and genetic correlations.

**Suggestions:**
  - Provide additional support or clarification for claims by directly referencing specific data or figures.
  - Ensure that figures are easily readable, with text size and clarity optimized for presentation.
  - Discuss the implications of the results more explicitly in relation to the study's objectives.

2024-08-13 19:28 UTC, kevinlacaille commented on papers/Gagnon_Kebe_Tahiri/main.tex
> +\section{Conclusion}\label{conclusion}
**Content:** 
- The conclusion summarizes the study's findings and discusses their implications for future research and conservation efforts.

**Suggestions:**
  - Emphasize the novelty of the findings compared to previous research.
  - Highlight potential future research directions or practical applications in more detail.
  - Consider discussing the limitations of the study more explicitly and how they might be addressed in future work.

2024-08-13 19:28 UTC, kevinlacaille commented on papers/Gagnon_Kebe_Tahiri/main.tex
> +\subsection{Data pre-processing}
**Content:** 
- This subsection outlines the steps taken to filter and prepare the data for analysis.

**Suggestions:**
  - Clearly define the criteria for omitting attributes and samples, such as "irrelevant in the context of this study" or "high correlations."
  - Provide more detail on why certain thresholds were chosen, such as the variance threshold of ≤ 0.1.
  - Specify how the variance and correlation were calculated to enhance reproducibility.

2024-08-13 19:28 UTC, kevinlacaille commented on papers/Gagnon_Kebe_Tahiri/main.tex
> +\subsection{Description of the data}
**Content:** 
- Describes the study area, specimen collection, and attributes selected for analysis.

**Suggestions:**
  - Clarify the rationale behind selecting specific geographical and environmental attributes.
  - Consider summarizing key statistics or characteristics of the dataset in a table for quick reference.
  - Provide more context on the relevance of the selected habitats and water masses to the study objectives.

2024-08-13 19:28 UTC, kevinlacaille commented on papers/Gagnon_Kebe_Tahiri/main.tex
> +\subsection{{\textit{aPhyloGeo} software}\label{aPhyloGeo-software}}
**Content:**
- Details the use and capabilities of the `aPhyloGeo` software for phylogeographic analyses.

**Suggestions:**
  - Include a brief explanation of the sliding window approach and its significance in identifying genetic mutations.
  - Clarify any specific settings or parameters used in the software for this analysis.
  - Provide examples of how the software's output informed the study's conclusions.

2024-08-13 19:28 UTC, kevinlacaille commented on papers/Gagnon_Kebe_Tahiri/main.tex
> +\end{figure}
**Content:** 
- Violin diagrams illustrate the distribution of various geographical, climatic, and environmental attributes.

**Suggestions:**
  - Please increase the font size of labels better readability.
  - The caption should briefly explain the significance of each attribute and what the distributions indicate about the habitat.

2024-08-13 19:28 UTC, kevinlacaille commented on papers/Gagnon_Kebe_Tahiri/main.tex
> +\end{figure}
**Content:** 
- Histogram showing the frequency distribution of cumacean species in the sample.

**Suggestions:**
  - Provide context in the caption about why certain species are more represented and what implications this has for the study.

2024-08-13 19:28 UTC, kevinlacaille commented on papers/Gagnon_Kebe_Tahiri/main.tex
> +\end{figure}
**Content:** 
- Histograms depicting the distribution of cumacean families by water mass and habitat.

**Suggestions:**
  - Include a brief explanation in the caption of how these distributions relate to the ecological adaptations or preferences of cumacean families.

2024-08-13 19:28 UTC, kevinlacaille commented on papers/Gagnon_Kebe_Tahiri/main.tex
> +\end{figure}
**Content:** 
- Histograms depicting the distribution of cumacean families by water mass and habitat.

**Suggestions:**
  - Include a brief explanation in the caption of how these distributions relate to the ecological adaptations or preferences of cumacean families.

2024-08-14 03:08 UTC, JustGag commented
Language and Grammar

Grammatical Errors:

In the abstract: "The most represent cumacean are those of the Diastylidae and Leuconidae families" should be "The most represented cumaceans are those of the Diastylidae and Leuconidae families."

Lengthy Sentences:

In the abstract: "These initial results underline the need for further exploration to understand the relationships between the genetics of cumacean and their environment." could be split into "These results highlight the need for further exploration. Understanding the relationships between cumacean genetics and their environment is crucial."

Awkward Phrasing:

In the introduction: "The slowdown in the formation of cold, deep waters due to the loss of Arctic sea ice can influence their regional dynamics and chemistry" could be rephrased to "The loss of Arctic sea ice and the resulting slowdown in cold, deep water formation may influence regional dynamics and chemistry."


Reply: Thank you for your comment. We've reworded these three sentences according to the recommendations you gave us.

2024-08-14 03:13 UTC, JustGag commented
Language and Grammar

Clarifying Terms:

In the introduction, terms like "benthic habitats" are defined well, but others, such as "thermohaline circulation," could benefit from brief explanations or a glossary to aid interdisciplinary understanding.

Reply: Thank you for your comment. We have defined the term "thermohaline circulation" in a footnote. Place the mouse cursor on the number "[2]" at the top right of this term.

2024-08-14 03:43 UTC, JustGag commented
Formatting and Consistency

Citation Style:

Ensure consistency in citation formatting. For example, in the introduction, "as well as the North Atlantic at high latitudes, play an essential role in the {thermohaline circulation}" should consistently use either full citation or abbreviation within brackets: {Thermohaline circulation}\citep{talley2013closure}.

Reply: Thank you for your comment. We have used the abbreviation in brackets as you suggested.

2024-08-14 04:10 UTC, JustGag commented
Formatting and Consistency

Figure Labeling:

Maintain consistency in figure references. For example, use "Figure \ref{fig:fig2}" uniformly throughout the text.

Reply: Thank you for your comment. We have taken care to maintain consistency in figure references.

2024-08-19 19:44 UTC, JustGag commented
Overall Recommendations

Interdisciplinary Accessibility:

Due to SciPy's interdisciplinary nature, avoid or explain domain-specific jargon where possible. Consider adding a glossary for specialized terms like "thermohaline circulation" or "benthic habitats."

Reply: Thank you for this pertinent comment. We've added a glossary for benthic habitat as a footnote and removed the term "thermohaline circulation".  You can access it by placing your mouse cursor over the number “[1]” at the top right of the term. 

We have also added a footnote “[2]” for the term “phylogeographic models”.

2024-08-19 21:54 UTC, JustGag commented on papers/Gagnon_Kebe_Tahiri/main.tex
> +\begin{abstract}
> **Content:**
> 
> * The abstract provides a clear overview of the study's objectives, methods, and initial findings. It highlights the significance of Cumacea as indicators of benthic health and introduces the use of the `aPhyloGeo` software.
> 
> **Suggestions:**
> 
> * Clarify the term "most represent cumacean," which should be "most represented cumaceans."
> * Consider splitting lengthy sentences for better readability, e.g., "These initial results underline the need for further exploration to understand the relationships between the genetics of cumacean and their environment" could be divided for clarity.
> * Mention the broader implications or potential applications of the findings in a concise sentence to round off the abstract.

Thank you for your comments. We have clarified the term “most represent cumacean” by “most common cumacean”, separating long sentences for better readability and mentioning broader implications or potential applications of the results in a concise sentence to complete the summary.

2024-08-20 00:01 UTC, JustGag commented on papers/Gagnon_Kebe_Tahiri/main.tex
> +\section{Introduction}\label{introduction}
> **Content:**
> 
> * The introduction provides a comprehensive background on the ecological significance of the North Atlantic region, the role of Cumacea in marine ecosystems, and the study's objectives.
> 
> **Suggestions:**
> 
> * Streamline the introduction by focusing more on the study's specific goals and less on the broad context, assuming some familiarity by the audience with general marine ecology topics.
> * Clarify terms like "thermohaline circulation" with brief explanations or footnotes for interdisciplinary accessibility.
> * Refine sentence structure for clarity, e.g., "The slowdown in the formation of cold, deep waters due to the loss of Arctic sea ice can influence their regional dynamics and chemistry" could be more direct.

Thank you for your comments. We have removed the term “thermohaline circulation” as well as the phrase you mentioned (i.e., The slowdown in the ...). We have also simplified the introduction, focusing more on the specific objectives of the study and less on the general context.

2024-08-21 05:01 UTC, JustGag commented on papers/Gagnon_Kebe_Tahiri/main.tex
> +\section{Materials and Methods}\label{materials-methods}
Thank you for this comment. In the abstract, we have included the YAML file in the aPhyloGeo GitHub link. We added the main parameters to the article (Results).

2024-08-22 16:16 UTC, JustGag commented on papers/Gagnon_Kebe_Tahiri/main.tex
> +\section{Metrics}\label{metrics}
Thank you for your valuable comments. We have ensured that the formulas are clearly explained for a diverse audience, included examples of how these measures are applied in our study, and that the code extracts conform to PEP8 guidelines and are formatted.

2024-08-22 23:17 UTC, cbcunc commented
Closing to clear pre-commit.ci check. WIll reopen immediately.

2024-08-22 23:19 UTC, tkoyama010 commented
Hmm... Still have pre-commit.ci check.

2024-08-22 23:30 UTC, cbcunc commented
Trying again after hotfix https://github.com/scipy-conference/scipy_proceedings/pull/1018

2024-08-22 23:30 UTC, cbcunc commented
@tkoyama010 Still there.

2024-08-22 23:32 UTC, tkoyama010 commented
@cbcunc Could you please update branch for this PR.
![image](https://github.com/user-attachments/assets/80585570-4bae-4c9a-8240-08d8ac2783b6)

2024-08-22 23:38 UTC, cbcunc commented
> @cbcunc Could you please update branch for this PR. 

@tkoyama010 I'm not finding this dialog or button.

2024-08-22 23:40 UTC, tkoyama010 commented
Please go to the setting tab and enable this setting.
![image](https://github.com/user-attachments/assets/172602c5-d1d4-4207-a7c0-833863432ca6)

2024-08-22 23:44 UTC, cbcunc commented
Trying to add update button after changing settings.

2024-08-22 23:48 UTC, cbcunc commented
@tkoyama010 Setting changed and PR closed/reopened. Failing check is still there.
<img width="792" alt="Screenshot 2024-08-22 at 7 46 51 PM" src="https://github.com/user-attachments/assets/ee6c6f5f-fb79-4482-98aa-833f51288dd0">

2024-08-22 23:51 UTC, tkoyama010 commented
> @cbcunc Could you please update branch for this PR. ![image](https://private-user-images.githubusercontent.com/7513610/360707268-80585570-4bae-4c9a-8240-08d8ac2783b6.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjQzNzA5MzEsIm5iZiI6MTcyNDM3MDYzMSwicGF0aCI6Ii83NTEzNjEwLzM2MDcwNzI2OC04MDU4NTU3MC00YmFlLTRjOWEtODI0MC0wOGQ4YWMyNzgzYjYucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDgyMiUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDA4MjJUMjM1MDMxWiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9NmY3OGM4MDA4ZmE4MGU0NDExYTg0OTc5NTU2MTRhNzQ2ZjAwZGY5MTE3ZTA4MWUzODJiM2QyMzA2NTAwNmEwYiZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.fppBvkYEyqUnVzSbkMzrmem6R7ut5M1jf-MnTCjj5pA)

@cbcunc Please push this buttom.

2024-08-22 23:55 UTC, cbcunc commented
> > @cbcunc Could you please update branch for this PR.

Again, the button is not there.

2024-08-23 00:02 UTC, tkoyama010 commented
Hmm... That's wired. What I want to do is add .pre-commit-config.yaml to this PR branch. Is it possible to add it to this branch of the file I added in #1018?

2024-08-23 00:12 UTC, tkoyama010 commented
Even if this is an error, there is no problem with merging, so we can leave it as it is.

2024-08-23 03:42 UTC, matthewfeickert commented
> Even if this is an error, there is no problem with merging, so we can leave it as it is.

I agree that this is superficial (the current `.pre-commit-config.yaml` on the `2024` branch doesn't do anything at the moment) and so not any concern for merging, but if Nadia wants to try to do a rebase off of `2024` that would be an easy way to test this. Should be a "trivial" rebase too in the sense that all of the paper files are new files and so it shouldn't be possible to hit any conflicts.

2024-08-23 22:41 UTC, cbcunc commented
@tkoyama010 All it took was a new commit. Make sense as it was triggered on commit.

2024-09-01 03:39 UTC, JustGag commented on papers/Gagnon_Kebe_Tahiri/main.tex
> +\subsection{{\textit{aPhyloGeo} software}\label{aPhyloGeo-software}}
Thank you for your thoughtful comments. We have briefly explained the sliding window approach and its significance in identifying gene mutations. We have also clarified the specific settings used in the software for the analysis. Examples of the software's output can be found in Figure 6 and Figure 7 of the “Results” section and the paragraph following the two figures.

2024-09-01 05:41 UTC, JustGag commented on papers/Gagnon_Kebe_Tahiri/main.tex
> +\end{figure}
Thank you for your comments. We've given more context in the caption about why certain species are more represented and we've discussed its implications for our study in the text below Figure 3.

2024-09-01 15:36 UTC, JustGag commented on papers/Gagnon_Kebe_Tahiri/main.tex
> +\end{figure}
Thank you for your comment. We have included a brief explanation in the legend of this distribution about the ecological adaptation of the Diastylidae family.

2024-09-01 16:00 UTC, JustGag commented on papers/Gagnon_Kebe_Tahiri/main.tex
> +\end{figure}
Thank you for your comment. We have included a brief explanation in the caption of how this distribution relates to the ecological adaptations of the cumacean families.

2024-09-01 16:31 UTC, JustGag commented
Content and Structure 

Materials and Methods:

The section is detailed but could benefit from additional clarification on methodological steps. For example, specify software versions and parameters used in DNA sequence analysis for reproducibility.

Reply: Thank you for these comments. In the abstract, we have included the YAML file in the aPhyloGeo GitHub link. We added the main parameters to the article (aPhyloGeo section).

2024-09-01 22:10 UTC, sanhitamj commented
@JustGag tomorrow is the last day of the edits by the authors. 

@kevinlacaille will you please take a look at the paper and get back with your verdict about the final draft?

2024-09-03 17:50 UTC, kevinlacaille commented
Hi all, please let me know when updates have been completed so I can provide my final review.

2024-09-03 20:12 UTC, JustGag commented
Formatting and Consistency

Consistent Terminology:

Ensure consistent use of "Cumacea" versus "cumacean" throughout the document. For example, use "Cumacea" when referring to the taxonomic group and "cumacean" when referring to individual species.

Reply: Thank you for your comment. We have ensured the consistency of using “Cumacea” versus “Cumacean”.

2024-09-03 20:43 UTC, JustGag commented
Formatting and Consistency

Section Headings:

Ensure consistent capitalization and formatting of section headings. For example, use either "Materials and Methods" or "Materials & Methods" consistently across the document.

Reply: Thank you for your comment. We have made sure that the capitalization and formatting of section headings are consistent.

2024-09-03 21:18 UTC, JustGag commented
Formatting and Consistency

Code Formatting:

Code snippets should consistently follow PEP8 guidelines, ensuring proper indentation and line spacing, as shown in the aPhyloGeo package code listings.

Provide comments within the code to explain key steps and logic, particularly for complex calculations.

Consider providing a brief description before each code listing to summarize its purpose and relevance to the study.

Reply: Thank you for your kind comments. We have ensured that the code extracts comply with the PEP8 guidelines. We have also provided comments explaining the key steps and logic of each code. Finally, we've included a brief description before each code to summarize its purpose and importance in our study.

2024-09-03 21:34 UTC, JustGag commented
Hi @kevinlacaille<https://github.com/kevinlacaille>, I am replying that we have implemented your suggestions in the comments you filed on our GitHub page. Would it be better if I finished replying to these before you start reviewing the article?

Thank you very much

Justin Gagnon
________________________________
De : Kevin Lacaille ***@***.***>
Envoyé : 3 septembre 2024 13:50
À : scipy-conference/scipy_proceedings ***@***.***>
Cc : Justin Gagnon ***@***.***>; Mention ***@***.***>
Objet : Re: [scipy-conference/scipy_proceedings] Paper: Climatic and Geographic Influences on Cumacea Genetics in the Northern North Atlantic (PR #925)


Hi all, please let me know when updates have been completed so I can provide my final review.

—
Reply to this email directly, view it on GitHub<https://github.com/scipy-conference/scipy_proceedings/pull/925#issuecomment-2327100903>, or unsubscribe<https://github.com/notifications/unsubscribe-auth/BFW5PNNRUPIBLSCKEHLKH5DZUXZHBAVCNFSM6AAAAABITSMO6CVHI2DSMVQWIX3LMV43OSLTON2WKQ3PNVWWK3TUHMZDGMRXGEYDAOJQGM>.
You are receiving this because you were mentioned.Message ID: ***@***.***>

2024-09-03 22:43 UTC, kevinlacaille commented
@JustGag no need to reply to the comments, just please let me know when you're done updating the paper.

Cheers,
Kevin

2024-09-03 23:04 UTC, JustGag commented
All right, thank you very much.
Justin
________________________________
De : Kevin Lacaille ***@***.***>
Envoyé : 3 septembre 2024 18:43
À : scipy-conference/scipy_proceedings ***@***.***>
Cc : Justin Gagnon ***@***.***>; Mention ***@***.***>
Objet : Re: [scipy-conference/scipy_proceedings] Paper: Climatic and Geographic Influences on Cumacea Genetics in the Northern North Atlantic (PR #925)


@JustGag<https://github.com/JustGag> no need to reply to the comments, just please let me know when you're done updating the paper.

Cheers,
Kevin

—
Reply to this email directly, view it on GitHub<https://github.com/scipy-conference/scipy_proceedings/pull/925#issuecomment-2327566373>, or unsubscribe<https://github.com/notifications/unsubscribe-auth/BFW5PNNJ2JTDOGRKU2DIYLLZUY3SFAVCNFSM6AAAAABITSMO6CVHI2DSMVQWIX3LMV43OSLTON2WKQ3PNVWWK3TUHMZDGMRXGU3DMMZXGM>.
You are receiving this because you were mentioned.Message ID: ***@***.***>

2024-09-04 12:00 UTC, JustGag commented
Hi @kevinlacaille<https://github.com/kevinlacaille>, I've finished updating the document. I'd like to point out that we've increased the font size of most of the labels to improve readability. However, Figures 6 and 7 will have to be corrected at a later date.

Thank you for your understanding and have a nice day,
Justin
________________________________
De : Kevin Lacaille ***@***.***>
Envoyé : 3 septembre 2024 18:43
À : scipy-conference/scipy_proceedings ***@***.***>
Cc : Justin Gagnon ***@***.***>; Mention ***@***.***>
Objet : Re: [scipy-conference/scipy_proceedings] Paper: Climatic and Geographic Influences on Cumacea Genetics in the Northern North Atlantic (PR #925)


@JustGag<https://github.com/JustGag> no need to reply to the comments, just please let me know when you're done updating the paper.

Cheers,
Kevin

—
Reply to this email directly, view it on GitHub<https://github.com/scipy-conference/scipy_proceedings/pull/925#issuecomment-2327566373>, or unsubscribe<https://github.com/notifications/unsubscribe-auth/BFW5PNNJ2JTDOGRKU2DIYLLZUY3SFAVCNFSM6AAAAABITSMO6CVHI2DSMVQWIX3LMV43OSLTON2WKQ3PNVWWK3TUHMZDGMRXGU3DMMZXGM>.
You are receiving this because you were mentioned.Message ID: ***@***.***>

2024-09-04 20:14 UTC, kevinlacaille approved these changes
### Comprehensive Review

This paper provides an in-depth analysis of the genetic variability of Cumacea in the Northern North Atlantic, focusing on the correlation between genetic sequences and environmental, climatic, and geographic factors. The study leverages mitochondrial sequences of the 16S rRNA gene from 62 Cumacea specimens and integrates them with habitat attributes to explore evolutionary dynamics and local adaptations in marine ecosystems. It also introduces the Python package `aPhyloGeo`, which enhances phylogeographic analyses.

#### Strengths:

1. **Relevance and Originality**: 
   - The study addresses a highly relevant topic, given the increasing interest in how environmental and climatic factors influence the genetics of marine species. The focus on Cumacea, which are important indicators of benthic health, adds ecological value to the research.
   - The integration of the `aPhyloGeo` software in this study is a novel approach that advances the field of phylogeographic analysis by correlating genetic data with habitat attributes. This could have broad implications for future research in marine biology and conservation.

2. **Methodological Rigor**:
   - The methodological approach is robust and well-documented. The paper outlines each step of the data selection, pre-processing, and analysis, ensuring reproducibility. The use of multiple metrics (Least-Squares Distance, Robinson-Foulds Distance, Euclidean Distance) provides a comprehensive view of the genetic-habitat correlation.
   - The detailed explanation of the `aPhyloGeo` software and the mathematical formulations for calculating variance and correlation demonstrate a high level of precision.

3. **Clear Presentation of Results**:
   - The results are well-structured and supported by visual aids such as violin plots and histograms, which help in understanding the distribution of environmental and genetic attributes. The correlation between genetic sequences and habitat attributes is presented clearly, highlighting interesting findings related to wind speed and oxygen concentration.
   - The discussion on species distribution and adaptation to environmental conditions provides meaningful ecological insights, particularly in terms of species resilience and the potential impact of environmental change.

4. **Broader Impact**:
   - The paper highlights the importance of understanding genetic adaptations in response to environmental fluctuations, which is crucial in the context of climate change. The insights gained can inform conservation strategies, such as the designation of marine protected areas and better management of vulnerable marine ecosystems.

#### Areas for Improvement:

1. **Minor Spelling and Grammar Issues**:
   - There are a few minor spelling errors (e.g., "envirionmental" should be "environmental") and grammatical inconsistencies that have been highlighted earlier. These should be corrected to maintain the professionalism and readability of the paper.

2. **Clarification on Sample Size and Missing Data**:
   - The authors acknowledge the limitations of the sample size (`n=62`) and the missing data points for oxygen concentration. While this is a valid limitation, a stronger discussion of how this might affect the results and potential generalizations would improve the paper. Future work could address these gaps by incorporating larger sample sizes or more complete datasets.

3. **Expansion on Protein Identification**:
   - The paper mentions the goal of identifying "the potentially associated protein" related to specific genetic sequences. However, there is little follow-up on this in the results section. Adding a more detailed analysis or future directions on this aspect would enhance the paper’s depth and connect the genetic findings more closely to their functional implications.

4. **Conclusion Refinement**:
   - The conclusion is solid but could benefit from a more concise summary of the key findings and their implications. There is some repetition of information that could be streamlined for better impact.

#### Final Recommendation:

Based on the comprehensive review, I **recommend the inclusion of this paper in the proceedings**, with the following conditions:
1. Minor spelling and grammatical issues should be corrected.
2. The discussion of limitations, particularly regarding sample size and missing data, should be expanded slightly to give a clearer perspective on their impact.
3. The authors should consider adding a few more sentences or a paragraph elaborating on the potential protein identification and its biological significance.

Overall, the paper is a well-conducted, original contribution to the field of marine biology and phylogeography. The findings, tools, and methodologies presented have the potential to influence future research on marine invertebrates and their response to environmental change.

2024-09-04 20:14 UTC, kevinlacaille commented on papers/Gagnon_Kebe_Tahiri/main.tex
> +Cumacea (crustaceans: Peracarida) are vital indicators of benthic health in marine ecosystems. This study investigated the influence of envirionmental, climatic and geographic attributes on their gen
"envirionmental" should be corrected to "environmental"

2024-09-04 20:14 UTC, kevinlacaille commented on papers/Gagnon_Kebe_Tahiri/main.tex
> +Considering the current climate emergency, this study aims to analyze the influence of geographic, environmental, and climatic attributes on the genetics of Cumacea in the Nothern North Atlantic. Spe
"Nothern North Atlantic" should be corrected to "Northern North Atlantic"

2024-09-04 20:14 UTC, kevinlacaille commented on papers/Gagnon_Kebe_Tahiri/main.tex
> +The violon diagrams shown in Figure \ref{fig:fig2} are used to display summary statistics similar to box plots, showing medians (white dots), interquartile ranges (thickened black bars), and the rest
"violon diagrams" should be corrected to "violin diagrams"

2024-09-04 20:14 UTC, kevinlacaille commented on papers/Gagnon_Kebe_Tahiri/main.tex
> +The violon diagrams shown in Figure \ref{fig:fig2} are used to display summary statistics similar to box plots, showing medians (white dots), interquartile ranges (thickened black bars), and the rest
Latex doesnt support double quotes well. Please replace 
```latex
"extreme"
```
with 

```latex
``extreme''
```

2024-09-04 20:14 UTC, kevinlacaille commented on papers/Gagnon_Kebe_Tahiri/main.tex
> +\subsubsection{Taxomic attributes}
"Taxomic attributes" should be corrected to "Taxonomic attributes"

2024-09-04 20:14 UTC, kevinlacaille commented on papers/Gagnon_Kebe_Tahiri/main.tex
> +Cumacea (crustaceans: Peracarida) are vital indicators of benthic health in marine ecosystems. This study investigated the influence of envirionmental, climatic and geographic attributes on their gen
"O\textsubscript{2} concentration (mg/L)": The formatting should be consistent, and in some places, it has inconsistent spacing or issues with subscript notation.

2024-09-04 20:14 UTC, kevinlacaille commented on papers/Gagnon_Kebe_Tahiri/main.tex
> +The distribution and diversity of the various cumacean species found in our sample are shown in Figure \ref{fig:fig3}. It shows that the most represented species are (\emph{Leptostylis ampullacea} (1
"which is in line with our study's aim of relating genetic adaptation to habitat attributes" could be rephrased for clarity, for example, "aligns with our study’s aim of relating genetic adaptation to habitat characteristics".

2024-09-04 20:14 UTC, kevinlacaille commented on papers/Gagnon_Kebe_Tahiri/main.tex
> +    \caption{Violin diagrams of two geographic attributes, one climatic attribute, and three environmental attributes from our sample that provide essential information about the ecological and geogr
"wind conditions at the start of sampling" is missing an article and could be clearer as "the wind conditions at the start of sampling".

2024-09-04 20:14 UTC, kevinlacaille commented on papers/Gagnon_Kebe_Tahiri/main.tex
> +Our study focuses on the genetic variation of the 16S rRNA mitochondrial gene in cumacean populations in the face of environmental fluctuations, which has been little explored in previous studies \ci
"cumacean" and "cumaceans" should be consistent in plural/singular use throughout the paper, but the formatting jumps between these forms.

2024-09-04 20:14 UTC, kevinlacaille commented on papers/Gagnon_Kebe_Tahiri/main.tex
> +Furthermore, our results provide essential knowledge to guide future studies on the genetic adaptation of cumaceans and other invertebrates to ecological and geographic variability. On this basis, fu
"on this basis" could be replaced with "based on these findings" for better clarity.

2024-09-04 20:14 UTC, kevinlacaille commented on papers/Gagnon_Kebe_Tahiri/main.tex
> +Considering the current climate emergency, this study aims to analyze the influence of geographic, environmental, and climatic attributes on the genetics of Cumacea in the Nothern North Atlantic. Spe
"geographic, environmental, and climatic" appears multiple times. Consider varying the phrase for stylistic variety.

2024-09-04 20:14 UTC, kevinlacaille commented on papers/Gagnon_Kebe_Tahiri/main.tex
> +Assessing and quantifying the biodiversity of deep-sea benthic invertebrates has become increasingly crucial since it was discovered that their richness may be underestimated \citep{grassle1992deep}.
"richness may be underestimated" could be made more specific, e.g., "species richness may be underestimated."

2024-09-04 20:14 UTC, kevinlacaille commented on papers/Gagnon_Kebe_Tahiri/main.tex
> +Our study focuses on the genetic variation of the 16S rRNA mitochondrial gene in cumacean populations in the face of environmental fluctuations, which has been little explored in previous studies \ci
The phrase "represents a major advance over previous research, which often fails" could be softened slightly, e.g., "which has often struggled to."

2024-09-04 20:14 UTC, kevinlacaille commented on papers/Gagnon_Kebe_Tahiri/main.tex
> +\item The latitude (Figure \ref{fig:fig2}a) and longitude (Figure \ref{fig:fig2}b) at the start of sampling, both in decimal degrees (DD), as they are intimatly linked to the environmental gradients
"intimatly" should be "intimately."

2024-09-04 20:14 UTC, kevinlacaille commented on papers/Gagnon_Kebe_Tahiri/main.tex
> +The mean (6.26 m/s; Table \ref{fig:tab1}) and median (6.00 m/s; Table \ref{fig:tab1}) of wind speed (m/s) at the start of sampling (Figure \ref{fig:fig2}d) are fairly similar, with a high concentrati
consider changing "concentration of data" to "density of data."

2024-09-04 20:14 UTC, kevinlacaille commented on papers/Gagnon_Kebe_Tahiri/main.tex
> +Our results revealed variability in most cumacean habitat attributes, as shown in Figure \ref{fig:fig2}. For instance, the median of the latitude at the start of sampling (67.15 DD; Table \ref{fig:ta
The sentence "The bimodality is reflected in longitude (DD)..." could be revised for clarity, e.g., "This bimodality is also observed in longitude (DD)..."

2024-09-04 20:14 UTC, kevinlacaille commented on papers/Gagnon_Kebe_Tahiri/main.tex
> +Interpreting how marine invertebrates genetically adapt to variations in their habitat can help us better predict their responses to climate change and advance conservation plans to protect them. Rec
"Recognizing these specific attributes that affect the genetic variability" could be more fluid if rephrased as "Identifying the specific attributes that influence genetic variability."

2024-09-20 00:35 UTC, sanhitamj commented
@JustGag will you please stop pushing more commits now? We are closing the branches to merge everything for publishing the proceedings.

2024-09-20 00:51 UTC, JustGag commented
Hi,

I thought that September 23rd would be the date for the final signature of the acts by the publishers? So I still had time to edit our publication.

Do I still have time between now and the end of the evening?

Thank you very much.

Justin
________________________________
De : Sanhita Joshi ***@***.***>
Envoyé : 19 septembre 2024 20:36
À : scipy-conference/scipy_proceedings ***@***.***>
Cc : Justin Gagnon ***@***.***>; Mention ***@***.***>
Objet : Re: [scipy-conference/scipy_proceedings] Paper: Climatic and Geographic Influences on Cumacea Genetics in the Northern North Atlantic (PR #925)


@JustGag<https://github.com/JustGag> will you please stop pushing more commits now? We are closing the branches to merge everything for publishing the proceedings.

—
Reply to this email directly, view it on GitHub<https://github.com/scipy-conference/scipy_proceedings/pull/925#issuecomment-2362485181>, or unsubscribe<https://github.com/notifications/unsubscribe-auth/BFW5PNL34ARA4B4NL6ZDA2LZXNUX7AVCNFSM6AAAAABITSMO6CVHI2DSMVQWIX3LMV43OSLTON2WKQ3PNVWWK3TUHMZDGNRSGQ4DKMJYGE>.
You are receiving this because you were mentioned.Message ID: ***@***.***>

2024-09-20 00:59 UTC, JustGag commented
I have one last commit to push.

Thank you very much for your understanding
________________________________
De : Sanhita Joshi ***@***.***>
Envoyé : 19 septembre 2024 20:36
À : scipy-conference/scipy_proceedings ***@***.***>
Cc : Justin Gagnon ***@***.***>; Mention ***@***.***>
Objet : Re: [scipy-conference/scipy_proceedings] Paper: Climatic and Geographic Influences on Cumacea Genetics in the Northern North Atlantic (PR #925)


@JustGag<https://github.com/JustGag> will you please stop pushing more commits now? We are closing the branches to merge everything for publishing the proceedings.

—
Reply to this email directly, view it on GitHub<https://github.com/scipy-conference/scipy_proceedings/pull/925#issuecomment-2362485181>, or unsubscribe<https://github.com/notifications/unsubscribe-auth/BFW5PNL34ARA4B4NL6ZDA2LZXNUX7AVCNFSM6AAAAABITSMO6CVHI2DSMVQWIX3LMV43OSLTON2WKQ3PNVWWK3TUHMZDGNRSGQ4DKMJYGE>.
You are receiving this because you were mentioned.Message ID: ***@***.***>

2024-09-20 02:13 UTC, JustGag commented
Hi,

I commit my last push.

Thank you very much for your understanding.

Justin
________________________________
De : Sanhita Joshi ***@***.***>
Envoyé : 19 septembre 2024 20:36
À : scipy-conference/scipy_proceedings ***@***.***>
Cc : Justin Gagnon ***@***.***>; Mention ***@***.***>
Objet : Re: [scipy-conference/scipy_proceedings] Paper: Climatic and Geographic Influences on Cumacea Genetics in the Northern North Atlantic (PR #925)


@JustGag<https://github.com/JustGag> will you please stop pushing more commits now? We are closing the branches to merge everything for publishing the proceedings.

—
Reply to this email directly, view it on GitHub<https://github.com/scipy-conference/scipy_proceedings/pull/925#issuecomment-2362485181>, or unsubscribe<https://github.com/notifications/unsubscribe-auth/BFW5PNL34ARA4B4NL6ZDA2LZXNUX7AVCNFSM6AAAAABITSMO6CVHI2DSMVQWIX3LMV43OSLTON2WKQ3PNVWWK3TUHMZDGNRSGQ4DKMJYGE>.
You are receiving this because you were mentioned.Message ID: ***@***.***>

2024-09-20 12:00 UTC, JustGag commented
Hi,

Could you please confirm receipt of the e-mails I sent yesterday?

Thank you very much and have a nice day.

Justin
________________________________
De : Sanhita Joshi ***@***.***>
Envoyé : 19 septembre 2024 20:36
À : scipy-conference/scipy_proceedings ***@***.***>
Cc : Justin Gagnon ***@***.***>; Mention ***@***.***>
Objet : Re: [scipy-conference/scipy_proceedings] Paper: Climatic and Geographic Influences on Cumacea Genetics in the Northern North Atlantic (PR #925)


@JustGag<https://github.com/JustGag> will you please stop pushing more commits now? We are closing the branches to merge everything for publishing the proceedings.

—
Reply to this email directly, view it on GitHub<https://github.com/scipy-conference/scipy_proceedings/pull/925#issuecomment-2362485181>, or unsubscribe<https://github.com/notifications/unsubscribe-auth/BFW5PNL34ARA4B4NL6ZDA2LZXNUX7AVCNFSM6AAAAABITSMO6CVHI2DSMVQWIX3LMV43OSLTON2WKQ3PNVWWK3TUHMZDGNRSGQ4DKMJYGE>.
You are receiving this because you were mentioned.Message ID: ***@***.***>

2024-09-24 00:19 UTC, cbcunc commented
@TahiriNadia @JustGag Please cease creating commits to this paper as previously requested. The deadline for author revisions was September 2 as shown in the [timeline](https://github.com/scipy-conference/scipy_proceedings?tab=readme-ov-file#timeline-for-2024). The paper has already been reviewed. We need your cooperation in order to publish.

2024-09-24 12:00 UTC, JustGag commented
Hi,

We will stop creating commits to our paper.

Thank you and have a nice day.

Justin
________________________________
De : Chris Calloway ***@***.***>
Envoyé : 23 septembre 2024 20:19
À : scipy-conference/scipy_proceedings ***@***.***>
Cc : Justin Gagnon ***@***.***>; Mention ***@***.***>
Objet : Re: [scipy-conference/scipy_proceedings] Paper: Climatic and Geographic Influences on Cumacea Genetics in the Northern North Atlantic (PR #925)


@TahiriNadia<https://github.com/TahiriNadia> @JustGag<https://github.com/JustGag> Please cease creating commits to this paper as previously requested. The deadline for author revisions was September 2 as shown in the timeline<https://github.com/scipy-conference/scipy_proceedings?tab=readme-ov-file#timeline-for-2024>. The paper has already been reviewed. We need your cooperation in order to publish.

—
Reply to this email directly, view it on GitHub<https://github.com/scipy-conference/scipy_proceedings/pull/925#issuecomment-2369830786>, or unsubscribe<https://github.com/notifications/unsubscribe-auth/BFW5PNOAYE4INFBNDXOEEO3ZYCV2JAVCNFSM6AAAAABITSMO6CVHI2DSMVQWIX3LMV43OSLTON2WKQ3PNVWWK3TUHMZDGNRZHAZTANZYGY>.
You are receiving this because you were mentioned.Message ID: ***@***.***>

2024-09-25 17:36 UTC, merged

2024-10-01 19:02 UTC, JustGag commented
Hi @cbcunc, I hope you're well. After noticing some typos, I wanted to ask if it would be possible to make some changes to improve the robustness of our paper? We've already implemented the changes on our side, so it would be a matter of including them in the conference paper. 

Thank you for your understanding. 

Justin