Paper: AI driven WatermarkingTechnique for Safegaurding Text Integrity
scipy-conference/scipy_proceedings pull request #928
Opened 2024-06-01 02:53 UTC by Atharva-Rasane

If you are creating this PR in order to submit a draft of your paper, please name your PR with `Paper: AI driven WatermarkingTechnique for Safegaurding Text Integrity`. An editor will then add a `paper` label and GitHub Actions will be run to check and build your paper.

See the [project readme](https://github.com/scipy-conference/scipy_proceedings#preview-your-paper) for more information.

_Editor_:  

_Reviewers_:

2024-06-01 03:10 UTC, Atharva-Rasane commented
Hi @hongsupshin, I am not sure why the ID is returning null. Can you help please?

2024-06-04 00:38 UTC, fwkoch commented
Hey @Atharva-Rasane - thanks for the submission! The check is expecting your content at `papers/atharva_rasane/*` as opposed to `papers/atharva_rasane/00_myst_template/*`. Removing that extra level of nesting should allow the check to proceed.

2024-06-04 18:24 UTC, ameyxd commented
@Atharva-Rasane can you make the update requested here

2024-06-08 01:08 UTC, Atharva-Rasane commented
Apologies for the delay, I have made the changes. Do you need me to squash the changes into 1 commit or is this fine now?

2024-06-08 16:56 UTC, ameyxd commented
this should be okay. thanks

2024-06-11 12:22 UTC, Tolulade-A commented
Hello @Atharva-Rasane I'm Tolulade, Data & ML Architect, founder @ Reispar Technologies. I'm happy to be one of the reviewers for your paper.

2024-06-11 17:46 UTC, ameyxd commented
@Atharva-Rasane @Tolulade-A please review and update the paper title with correct spelling and grammar. 🙂

2024-06-12 08:07 UTC, Tolulade-A requested changes
hi @Atharva-Rasane I have added some comments for you to review.

2024-06-12 08:07 UTC, Tolulade-A commented on papers/atharva_rasane/main.md
> +  This paper presents a unique physical watermarking technique based on word substitution to address these challenges. The core idea is that AI models consistently produce the same output for the sam
@Atharva-Rasane you can add more context and clarity where the `ith` word is used, is this a random word sampling?

2024-06-12 08:07 UTC, Tolulade-A commented on papers/atharva_rasane/main.md
> +  The Python implementation of the algorithm in this paper employes models from the HuggingFace Transformer Library, namely "bert-base-uncased" and "distilroberta-base". The "[MASK]" placeholder was
@Atharva-Rasane the ith word is also used here, kindly add more context, is this a random word sampling ?

2024-06-12 08:07 UTC, Tolulade-A commented on papers/atharva_rasane/main.md
> +Watermarks are an identifying pattern used to identify the origin of the data. In this case, we specifically want to focus on text watermarking (watermarking of plain text). Text watermarking can bro
@Atharva-Rasane is MASK here an acronymn? If it is, it can be spelt in full.

2024-06-12 16:50 UTC, Atharva-Rasane commented on papers/atharva_rasane/main.md
> +  This paper presents a unique physical watermarking technique based on word substitution to address these challenges. The core idea is that AI models consistently produce the same output for the sam
Hello, yes it is a random index value. We could choose i-th to be say the 5-th word. If I added a hyphen, would that help a bit more with the clarity?

2024-06-12 16:56 UTC, Atharva-Rasane commented on papers/atharva_rasane/main.md
> +Watermarks are an identifying pattern used to identify the origin of the data. In this case, we specifically want to focus on text watermarking (watermarking of plain text). Text watermarking can bro
MASK here is not an acronym but signifies a special token which BERT model then identifies and replaces - This token and its usage was pulled directly from one of the cited papers.

2024-06-12 22:08 UTC, Tolulade-A commented on papers/atharva_rasane/main.md
> +  This paper presents a unique physical watermarking technique based on word substitution to address these challenges. The core idea is that AI models consistently produce the same output for the sam
Now I get you, adding a hypen would help and a bit of additional context like you did with this reply.

2024-06-12 22:10 UTC, Tolulade-A commented on papers/atharva_rasane/main.md
> +Watermarks are an identifying pattern used to identify the origin of the data. In this case, we specifically want to focus on text watermarking (watermarking of plain text). Text watermarking can bro
did I miss it ? Was there any place you elaborated slightly on what Mask is ? This could help simply things.

2024-06-21 04:48 UTC, Atharva-Rasane commented on papers/atharva_rasane/main.md
> +Watermarks are an identifying pattern used to identify the origin of the data. In this case, we specifically want to focus on text watermarking (watermarking of plain text). Text watermarking can bro
I have incuded it in the inroduction:
"In this paper, we will propose an algorithm to watermark text using BERT (Bidirectional Encoder Representations from Transformers), a model introduced by Google whose main purpose is to replace a special symbol "[MASK]" with the most probable word given the context."

2024-06-26 08:03 UTC, Tolulade-A commented on papers/atharva_rasane/main.md
> +Watermarks are an identifying pattern used to identify the origin of the data. In this case, we specifically want to focus on text watermarking (watermarking of plain text). Text watermarking can bro
Hi @Atharva-Rasane I have taken note of the changes, I still go through again and get back if there's any other feedback

2024-06-30 00:34 UTC, sanhitamj commented on papers/atharva_rasane/main.md
> +  The internet's growth has led to a surge in text usage. Now, with public access to generative AI models like ChatGPT/Bard, identifying the source is vital. This is crucial due to concerns about cop
Please replace "it's" with "it is". "It is" is formal.

2024-06-30 00:36 UTC, sanhitamj commented on papers/atharva_rasane/main.md
> +The growth of the internet is driven by the spread of web pages, which are written in HTML (Hyper Text Markup Language). These web pages contain large amounts of text. Almost every webpage in some fo
ChatGPT or Bard, (and not "and") unless other tools are specifically ignored here.

2024-06-30 00:37 UTC, sanhitamj commented on papers/atharva_rasane/main.md
> +Watermarks are an identifying pattern used to trace the origin of the data. In this case, we specifically want to focus on text watermarking (watermarking of plain text). Text watermarking can broadl
... into 2 types,  Logical Embedding and Physical Embedding, ...

Please add commas for readability.

2024-06-30 00:44 UTC, sanhitamj commented on papers/atharva_rasane/main.md
> +Note that a different variant of BERT can be trained on different language datasets and thus will generate a different result and as such the unique identity to consider here is the BERT model i.e. i
doesn't -> does not

2024-06-30 00:46 UTC, sanhitamj commented on papers/atharva_rasane/main.md
> +                # print("Done ", i + 1, "th word")
Consider removing commented code.

2024-06-30 00:48 UTC, sanhitamj commented on papers/atharva_rasane/main.md
> +# check_significant_difference(match_ratios)
Consider removing commented code.

2024-06-30 00:49 UTC, sanhitamj commented on papers/atharva_rasane/main.md
> +result = {0: 0.5384615384615384, 1: 0.6153846153846154, 2: 0.5833333333333334, 3: 0.6666666666666666, 4: 0.5833333333333334}
Consider rounding the decimals to fewer digits.

2024-06-30 00:51 UTC, sanhitamj commented on papers/atharva_rasane/main.md
> +(result) match_ratios = {0: 0.5714285714285714, 1: 0.5714285714285714, 2: 0.5384615384615384, 3: 0.38461538461538464, 4: 0.7692307692307693}
Consider rounding the decimals to fewer digits.

2024-06-30 00:51 UTC, sanhitamj commented on papers/atharva_rasane/main.md
> +    P-Value: 0.010908789440745323
Consider rounding the decimals to fewer digits.

2024-06-30 00:51 UTC, sanhitamj commented on papers/atharva_rasane/main.md
> +  P-Value: 0.010908789440745323
As above - Consider rounding the decimals to fewer digits.

2024-06-30 00:51 UTC, sanhitamj commented on papers/atharva_rasane/main.md
> +1. Versatility in applications: This method can be applied across various fields such as copyright protection, and content authentication, and in legal and academic settings where proof of authorship
"it's" -> it is

2024-06-30 02:13 UTC, Atharva-Rasane commented on papers/atharva_rasane/main.md
> +  P-Value: 0.010908789440745323
I have round all down to 2 decimal places

2024-06-30 02:16 UTC, Atharva-Rasane commented on papers/atharva_rasane/main.md
> +1. Versatility in applications: This method can be applied across various fields such as copyright protection, and content authentication, and in legal and academic settings where proof of authorship
I replaced all  contractions in the paper

2024-06-30 02:17 UTC, Atharva-Rasane commented on papers/atharva_rasane/main.md
> +                # print("Done ", i + 1, "th word")
I have removed the commented code

2024-06-30 02:17 UTC, Atharva-Rasane commented on papers/atharva_rasane/main.md
> +The growth of the internet is driven by the spread of web pages, which are written in HTML (Hyper Text Markup Language). These web pages contain large amounts of text. Almost every webpage in some fo
I have Replaced and with or

2024-09-01 22:13 UTC, sanhitamj commented
@Atharva-Rasane thanks for the submission and the subsequent edits. Tomorrow, 2nd Sept is the last day for the authors to make edits. 

 @Tolulade-A thank you for the help with the review. Will you please take a look and get back with your final decision by Sept 9?

2024-09-02 07:46 UTC, Tolulade-A commented
sure, will do that @sanhitamj

2024-09-09 16:17 UTC, Tolulade-A approved these changes

2024-09-09 16:17 UTC, Tolulade-A commented
this looks good to me.

2024-09-25 17:39 UTC, merged