Paper: Training a Supervised Cilia Segmentation Model from Self-SupervisionPaper added
scipy-conference/scipy_proceedings pull request #929
Opened 2024-06-01 03:15 UTC by salirezav

If you are creating this PR in order to submit a draft of your paper, please name your PR with `Paper: <title>`. An editor will then add a `paper` label and GitHub Actions will be run to check and build your paper.

See the [project readme](https://github.com/scipy-conference/scipy_proceedings#preview-your-paper) for more information.

_Editor_:  

_Reviewers_:

2024-06-01 08:36 UTC, rowanc1 reviewed
Could you please lower case title and abstract! There are also a few references with missing DOIs!

2024-06-01 08:36 UTC, rowanc1 commented on papers/Alireza_Vaezi/main.md
> +Title: Training a Supervised Cilia Segmentation Model from Self-Supervision
```suggestion
title: Training a Supervised Cilia Segmentation Model from Self-Supervision
```

2024-06-01 08:36 UTC, rowanc1 commented on papers/Alireza_Vaezi/main.md
> +Abstract: |
```suggestion
abstract: |
```

2024-06-04 18:25 UTC, ameyxd commented
@salirezav Thanks for your submission. Can you update the DOIs that fail the checks? 

You may be able to add citation keys you want to ignore if their DOIs don't exist in myst.yml under error_rules:

  ```
error_rules:
    - rule: doi-exists
      severity: ignore
      keys:
        - abc
        - def01
```

2024-06-05 19:09 UTC, salirezav commented
Hi,

Thank you for your help. I made sure that every bibliography entry has a valid DOI, and otherwise appended them to the error_rule section. However, the check step still fails to complete.

2024-06-20 19:49 UTC, iamtekson commented
Hi @salirezav, I am Tek Kshetri, A graduate student at the University of Calgary, Canada. and one of the reviewers of your paper. I am currently reading your paper and will provide you with some comments here.

2024-06-20 21:02 UTC, iamtekson reviewed
Overall, the paper is well-written and easy to understand, even for someone not from the medical field. I appreciate the clarity and thoroughness of the authors' explanations. Thank you for giving me the opportunity to review this work.

# Summary of paper:
The study introduces a self-supervised framework for automating cilia segmentation, crucial for diagnosing ciliopathies. Traditional methods rely on labor-intensive, manually labeled data. The new approach leverages optical flow to generate motion-based pseudolabels from healthy cilia videos, creating a robust training set for a semi-supervised neural network. This model effectively segments both motile and immotile cilia, overcoming inconsistencies in ciliary motion. Using a two-stage process involving optical flow and autoregressive modeling, the method achieves high accuracy without expert-drawn masks, significantly enhancing automated cilia analysis and potentially accelerating research and diagnostics for ciliopathies.

# My general comments
I have listed few general comments as below,

1. All the figures have two copies in `png` and `webp` formats. I suggest removing one of them.
2. The paper could be further enhanced by including a detailed discussion section. This section could compare the proposed method with existing approaches, elaborate on potential limitations, and suggest future research directions. Furthermore, it would be nice to explain about the generalization of the model. Additionally, a deeper analysis of the pseudolabeling accuracy and its impact on the model’s performance would provide more comprehensive insights into the framework’s efficacy.

2024-06-20 21:02 UTC, iamtekson commented on papers/Alireza_Vaezi/AR matrices.webp
Looks like, this file is the same as `AR_matrices.png`. I suggest removing one of these.

2024-06-20 21:02 UTC, iamtekson commented on papers/Alireza_Vaezi/main.md
> +Cilia are hair-like membranes that extend out from the surface of the cells and are present on a variety of cell types such as lungs and brain ventricles and can be found in the majority of vertebrat
In this sentence, `Categorized into motile and primary, motile cilia can help the cell to propel, move the flow of fluid, or fulfill sensory functions, while primary cilia act as signal receivers, translating extracellular signals into cellular responses`, I suggest to add the reference.

2024-06-20 21:02 UTC, iamtekson commented on papers/Alireza_Vaezi/main.md
> +Video segmentation techniques tend to be more robust to such noise, but still struggle due to the wild inconsistencies in cilia behavior: while healthy cilia have regular and predictable movements, u
I suggest adding the citation to this paragraph too. As I am not from the medical field, I find things interesting. How do you know healthy cilia have regular and predictable movements and unhealthy cilia display a wide range of motion?

2024-06-20 21:02 UTC, iamtekson commented on papers/Alireza_Vaezi/main.md
> +Taking advantage of this temporal regularity in ciliary motion, we use OF to compute the flow vectors of each pixel using optical flow to obtain motion vectors of the region where cilia reside. We be
Add full stop at the end of the paragraph `...constant throughout the video.`

2024-06-20 21:02 UTC, iamtekson commented on papers/Alireza_Vaezi/main.md
> +In our experiments, we chose $d = 5$ as the order of our autoregressive model.
It would be better to explain why you selected $d = 5$ instead of the other number. Is it referenced from other literatures? or randomly selected?

2024-06-20 21:02 UTC, iamtekson commented on papers/Alireza_Vaezi/main.md
> +A 5-order AR model of the OF component of the video
Suggest adding more information in the figure caption, such as what these colors represent in the image. and what are the x and y-axis numbers?

2024-06-20 21:02 UTC, iamtekson commented on papers/Alireza_Vaezi/main.md
> +In @fig:sample_AR, the first-order AR parameter is showing the most variance in the video, which corresponds to the frequency of motion that cilia exhibit. The remaining orders have correspondence wi
In this paragraph, `.......followed by a normalization of pixel intensities`, I suggest to add the normalization method such as, min-max normalization, standardization etc.

2024-06-20 21:02 UTC, iamtekson commented on papers/Alireza_Vaezi/main.md
> +        <td align="center">0.968</td>
Why are your validation and testing accuracy the same? My guess is you used a test dataset for the validation. If so, please remove validation accuracy from the table else please explain things.

2024-06-20 21:02 UTC, iamtekson commented on papers/Alireza_Vaezi/main.md
> +In this study, we employed a Feature Pyramid Network (FPN) [@kirillov2017unified] architecture with a ResNet-34 encoder. The model was configured to handle grayscale images with a single input channe
I found this section little bit incomplete. I suggest adding a table with hyperparameters and their values for a few of the hyperparameters such as, optimizer, loss function name, number of training/test/validation samples, callback function names (if any) etc.

2024-06-20 21:02 UTC, iamtekson commented on papers/Alireza_Vaezi/main.md
> +[^footnote-3]: $\mathrm{e^{-i\pi}}$ -->
suggest to remove this section as it is not the part of the paper.

2024-06-24 19:04 UTC, chongshenng commented
Hello @salirezav 👋 , thanks for your submission! I'm Chong Shen, one of the reviewers of your paper. I'll add my comments shortly.

2024-06-24 20:05 UTC, chongshenng commented
## General comments
The authors propose a two-stage process to improve image segmentation models for cilia detection. The first step of the process first applies a series of image processing techniques, followed by auto regressive modelling. Finally, they apply a FPN architecture to train their image segmentation model. 

The results from this work is promising especially since the proposed method appears to be quite novel. I've provided a few comments in the manuscript. However, there're still a few points below that I'd encourage the authors to address before accepting it:

* There's no description of the cilia video/image dataset in this paper. Can you provide a brief description of it in the `Methodology` section? Is it an open source dataset? What were the training data sizes?
* It'd be instructive to readers if a simple diagram can be included to show the workflow from raw video/image to a trained model. 
* The results refer to IoU, sensitivity, and specifity, which are fine. It would be more instructive to readers if there's an indication of a baseline for comparison of performance.

2024-06-27 23:01 UTC, sanhitamj commented on papers/Alireza_Vaezi/main.md
> +Taking advantage of this temporal regularity in ciliary motion, we use OF to compute the flow vectors of each pixel using optical flow to obtain motion vectors of the region where cilia reside. We be
Need the full form of OF when used first.

2024-06-28 02:40 UTC, chongshenng requested changes
Please refer to my commment [here](https://github.com/scipy-conference/scipy_proceedings/pull/929#issuecomment-2187313706).

2024-06-28 02:40 UTC, chongshenng commented on papers/Alireza_Vaezi/main.md
> +  Cilia are organelles found on the surface of some cells in the human body that sweep rhythmically to transport substances. Dysfunctional cilia are indicative of diseases that can disrupt organs suc
I like how clear the sentences are. To improve readability and flow, I suggest using words and phrases to link to the previous sentences. E.g.: 

> ... sweep rhythmically to transport substances. _When cilia become dysfunctional,_ they are indicative of diseases that can disrupt organs such as the lungs and kidneys. _Therefore,_ it is essential to understand cilia behaviour in diagnosing and treating such diseases. 

and 

> _But,_ the tasks of automatically analysing cilia are often labor and time-intensive, since there is a lack of automated segmentation. _In this work, we overcome this significant bottleneck_ by developing a robust, self-supervised framework ...

2024-06-28 02:40 UTC, chongshenng commented on papers/Alireza_Vaezi/main.md
> +A promising approach to overcome the dependency on manually labeled data is the use of unsupervised methods to generate ground truth masks. Unsupervised methods do not require prior knowledge of the
Since this paragraph is about unsupervised learning, it would be instructive to readers to clarify that your approach of computing the motion vectors is unsupervised. Consider rephrasing to:

> ... accurate segmentation masks for cilia. _Inspired by advances in unsupervised methods for image segmentation, in this work, we firstly compute the motion vectors using optical flow of the ciliary regions and then apply autoregressive modelling to capture their temporal dynamics. Autoregressive modelling is advantageous since the labels are features themselves._ By analyzing the optical flow vectors, ...

2024-06-28 02:40 UTC, chongshenng commented on papers/Alireza_Vaezi/main.md
> +A sample frame of a video in our cilia dataset
Since this is the first time readers would see an image of a cilia, it would be useful to annotate a region occupied by the cilia or describe in words.

2024-06-28 02:40 UTC, chongshenng commented on papers/Alireza_Vaezi/main.md
> +:::
I couldn't find a reference in the text to figures (1) and (2). Perhaps it'd be more useful to create combine all figures (1) to (3) into one, and then add a subfigure (a) to (c). Then, your reference could be updated to something along the lines of:

> `@fig:sample_OF` show a sample of the flow region around a cilia. The raw image is shown in (a) and a manually labeled ground truth in (b). The vorticity computed from the optical flow from (b) is shown in (c).

2024-06-28 02:40 UTC, chongshenng commented on papers/Alireza_Vaezi/main.md
> +@fig:sample_OF shows a sample of the optical flow component at a random time. From OF vectors, elemental components such as rotation are derived, which highlights the ciliary motion by capturing twis
It's unclear to me here what you're modelling. You mention 'rotation', but later refer to the temporal evolution of vectors, which is not intuitive. As I understand, rotation (in this case, a 2D rotation) would be vorticity and the vector is orthogonal to the page. Are you modelling the vorticity, velocity gradients, or the velocities themselves? Can you please revise this paragraph?

2024-06-28 02:40 UTC, chongshenng commented on papers/Alireza_Vaezi/main.md
> +In this study, we employed a Feature Pyramid Network (FPN) [@kirillov2017unified] architecture with a ResNet-34 encoder. The model was configured to handle grayscale images with a single input channe
I agree with @iamtekson. These information will also be useful for reproducibility and help increase visibility of your work.

2024-06-28 02:40 UTC, chongshenng commented on papers/Alireza_Vaezi/main.md
> +        <td align="center">0.968</td>
I agree with @iamtekson's comments - the test scores stood out to me since it is quite peculiar to have the same test and validation scores.

2024-06-28 02:40 UTC, chongshenng commented on papers/Alireza_Vaezi/main.md
> +Taking advantage of the orderly beating pattern in healthy cilia, we employed a two-stage segmentation process that effectively handles the inconsistencies and noise present in cilia microscopy video
Here, you mentioned "improved performance in accurately detecting ciliary regions". Can you clarify in the text what the improvement is compared relative to? I don't recall reading about a baseline comparison in the text.

2024-06-28 02:40 UTC, chongshenng commented on papers/Alireza_Vaezi/main.md
> +The process of computing the masks. a) Subtracting the second-order AR parameter from the first-order, followed by b) Adaptive thresholding, which suffers from under/over-segmentation. c) A Gaussian
It's not clear to me what are the training images. Is it (d)?

2024-07-01 17:44 UTC, salirezav commented
> Hi @salirezav, I am Tek Kshetri, A graduate student at the University of Calgary, Canada. and one of the reviewers of your paper. I am currently reading your paper and will provide you with some comments here.

Hello @iamtekson,
Thank you for your comments! I will be addressing your suggestions and comments in the following days.

2024-07-01 17:46 UTC, salirezav commented
> Hello @salirezav 👋 , thanks for your submission! I'm Chong Shen, one of the reviewers of your paper. I'll add my comments shortly.

Hello @chongshenng,
Thank you for your comments and suggestions! I will be addressing the suggestions throughout the following days.

2024-07-01 17:52 UTC, salirezav commented on papers/Alireza_Vaezi/AR matrices.webp
All webp files were removed

2024-07-01 18:02 UTC, salirezav commented on papers/Alireza_Vaezi/main.md
> +Cilia are hair-like membranes that extend out from the surface of the cells and are present on a variety of cell types such as lungs and brain ventricles and can be found in the majority of vertebrat
Citation added.

2024-07-01 18:22 UTC, salirezav commented on papers/Alireza_Vaezi/main.md
> +Video segmentation techniques tend to be more robust to such noise, but still struggle due to the wild inconsistencies in cilia behavior: while healthy cilia have regular and predictable movements, u
Citations added.

2024-07-01 18:28 UTC, salirezav commented on papers/Alireza_Vaezi/main.md
> +Taking advantage of this temporal regularity in ciliary motion, we use OF to compute the flow vectors of each pixel using optical flow to obtain motion vectors of the region where cilia reside. We be
Done.

2024-07-01 18:55 UTC, salirezav commented on papers/Alireza_Vaezi/main.md
> +In our experiments, we chose $d = 5$ as the order of our autoregressive model.
Explanation added.

2024-07-01 19:17 UTC, salirezav commented on papers/Alireza_Vaezi/main.md
> +In @fig:sample_AR, the first-order AR parameter is showing the most variance in the video, which corresponds to the frequency of motion that cilia exhibit. The remaining orders have correspondence wi
Done.

2024-07-02 14:11 UTC, salirezav commented on papers/Alireza_Vaezi/main.md
> +[^footnote-3]: $\mathrm{e^{-i\pi}}$ -->
Done!

2024-07-04 00:03 UTC, salirezav commented on papers/Alireza_Vaezi/main.md
> +A 5-order AR model of the OF component of the video
I added a colormap in the plot and provided an explanation of the values.

2024-07-04 00:56 UTC, salirezav commented on papers/Alireza_Vaezi/main.md
> +  Cilia are organelles found on the surface of some cells in the human body that sweep rhythmically to transport substances. Dysfunctional cilia are indicative of diseases that can disrupt organs suc
Resolved.

2024-07-04 01:08 UTC, salirezav commented on papers/Alireza_Vaezi/main.md
> +Taking advantage of this temporal regularity in ciliary motion, we use OF to compute the flow vectors of each pixel using optical flow to obtain motion vectors of the region where cilia reside. We be
Resolved.

2024-07-04 01:10 UTC, salirezav commented on papers/Alireza_Vaezi/main.md
> +A promising approach to overcome the dependency on manually labeled data is the use of unsupervised methods to generate ground truth masks. Unsupervised methods do not require prior knowledge of the
Thanks for the help. Resolved.

2024-07-04 01:19 UTC, salirezav commented on papers/Alireza_Vaezi/main.md
> +@fig:sample_OF shows a sample of the optical flow component at a random time. From OF vectors, elemental components such as rotation are derived, which highlights the ciliary motion by capturing twis
I added more detail to the OF and AR sections.

2024-07-07 18:50 UTC, salirezav commented on papers/Alireza_Vaezi/main.md
> +In this study, we employed a Feature Pyramid Network (FPN) [@kirillov2017unified] architecture with a ResNet-34 encoder. The model was configured to handle grayscale images with a single input channe
I appended a table including the details of the model and data.

2024-07-09 01:30 UTC, salirezav commented on papers/Alireza_Vaezi/main.md
> +A sample frame of a video in our cilia dataset
Resolved!

2024-07-27 23:17 UTC, salirezav commented on papers/Alireza_Vaezi/main.md
> +        <td align="center">0.968</td>
I fixed this issue.

2024-07-27 23:17 UTC, salirezav commented on papers/Alireza_Vaezi/main.md
> +:::
I replaced them with one figure.

2024-07-27 23:18 UTC, salirezav commented on papers/Alireza_Vaezi/main.md
> +Taking advantage of the orderly beating pattern in healthy cilia, we employed a two-stage segmentation process that effectively handles the inconsistencies and noise present in cilia microscopy video
I modified this paragraph.

2024-08-25 23:40 UTC, sanhitamj commented
Hi @salirezav Just a reminder that 2nd Sept is the final deadline for the author(s) to make edits to the submission.

2024-08-27 23:29 UTC, salirezav commented
> Hi @salirezav Just a reminder that 2nd Sept is the final deadline for the author(s) to make edits to the submission.

Hi @sanhitamj ! Thank you for the reminder! All of the changes suggested by the reviewers have been already made and pushed. I only need to make a minor change and then everything will be ready way before the deadline.

Thank you for all the help!

2024-09-01 22:15 UTC, sanhitamj commented
@salirezav thanks for the submission and the subsequent edits as well.

@iamtekson and @chongshenng thank you so much for the careful review. Will you please get back with your final decision about the paper by 9th Sept?

2024-09-03 20:38 UTC, iamtekson commented
Now, it looks much more improved. I vote for accepting it. Thanks @sanhitamj and @salirezav for providing me the opportunity to review it.

2024-09-25 18:25 UTC, merged