init
scipy-conference/scipy_proceedings pull request #931
Opened 2024-06-01 05:06 UTC by knaaptime

2024-06-04 15:47 UTC, hongsupshin commented
@knaaptime Hi Eli, could you update the PR name so that it reflects the title of the paper? This would avoid any confusion during the review process. Thanks!

2024-06-04 15:59 UTC, knaaptime commented
sorry, yes! making some updates shortly

2024-06-04 18:26 UTC, ameyxd commented
@knaaptime can you update the DOIs and link that fail checks?

2024-06-04 18:59 UTC, knaaptime commented
yes! I also need to add several abbreviations to the yaml. Can I add a wip tag for a day or two?

2024-06-06 14:42 UTC, ameyxd commented
@knaaptime [issue here](https://github.com/scipy-conference/scipy_proceedings/issues/935) also affects your paper. We are working on a fix.

2024-06-11 17:25 UTC, ameyxd commented
@knaaptime there are some citations that do not have DOIs. can you recheck the DOIs that fail checks? As long as they are valid DOIs we should be okay.

2024-06-11 17:54 UTC, knaaptime commented
pushed a fix for two articles that are missing. Not sure whats up with he rest of those 'doi fail to resolve' errors. If you click the link shown in the CI it will take you right to the article

2024-06-11 17:57 UTC, rowanc1 commented
Hi @knaaptime -- we are having some issues with doi.org at the moment (see #935), we should have this fixed by the end of the week. Thank you for adding DOIs, we will get the other checks passing soon!

2024-06-12 17:31 UTC, fwkoch commented on papers/eli_knaap/main.md
> +stream these datasets over [S3]((https://aws.amazon.com/s3/)), where they can be read
Removing these extra parentheses should resolve your last failing check.

```suggestion
stream these datasets over [S3](https://aws.amazon.com/s3/), where they can be read
```

2024-06-12 17:34 UTC, knaaptime commented on papers/eli_knaap/main.md
> +stream these datasets over [S3]((https://aws.amazon.com/s3/)), where they can be read
oops. thanks!

2024-06-12 18:32 UTC, fwkoch commented
Thanks for merging that suggestion - the previous failure is now fixed. The new failure is back to another, different DOI issue on the checks 🙁. Fixing it up now, nothing more for you to worry about 🙂.

2024-06-19 17:12 UTC, fwkoch commented on papers/eli_knaap/main.md
> +sequence-analysis methods [@Kang2020a; @Lee2017] (both of which are built into `geosnap`)
I noticed this `Kang2020a` citation does not have a corresponding entry in your bib file, so it does not resolve:

![image](https://github.com/scipy-conference/scipy_proceedings/assets/9453731/3766fb24-507a-487b-943d-c683cdf7970a)

Can you add an entry for this?

2024-06-20 22:43 UTC, ameyxd commented
Review requests sent to @shuangw1 and @shahnawaz323

2024-07-02 17:22 UTC, ameyxd commented
Resent email requests for review to @shuangw1 and @shahnawaz323

2024-07-02 23:37 UTC, shuangw1 commented
Hello organizers,
I have emailed before because of health issues I am not able to do review. Please assign the tasks to someone else. Thanks,
Shuang

在 2024年7月3日，01:22，Amey Ambade ***@***.***> 写道：

﻿

Resent email requests for review to @shuangw1<https://github.com/shuangw1> and @shahnawaz323<https://github.com/shahnawaz323>

—
Reply to this email directly, view it on GitHub<https://github.com/scipy-conference/scipy_proceedings/pull/931#issuecomment-2203892221>, or unsubscribe<https://github.com/notifications/unsubscribe-auth/AOUMVJKJGVCQRNCN4IVAR5TZKLOVFAVCNFSM6AAAAABIT22F3GVHI2DSMVQWIX3LMV43OSLTON2WKQ3PNVWWK3TUHMZDEMBTHA4TEMRSGE>.
You are receiving this because you were mentioned.Message ID: ***@***.***>

2024-07-30 17:29 UTC, ameyxd commented
Sent review reminder to @dcamron

2024-08-04 08:01 UTC, sumitkumar1212 reviewed
This was a new topic for me, and I found the content interesting to learn. The paper provides a foundational knowledge of the geosnap package and illustrates how it can be used for neighborhood analysis across four layers: ingestion of US based datasets, harmonizing geographic boundaries, and analyzing and visualizing various use cases.

I have three main suggestions for improvement:

1. Use of Acronyms: Spell out the full form the first time an acronym is used and include the acronym in parentheses if it will be used later in the paper.
2. Descriptive Captions: Provide detailed captions for each figure. Refer to these figures when explaining different analyses to help readers understand the content better.
3. Code Comments: Include brief comments on each code block to illustrate its purpose, improving the readability of the code.

Additionally, I have provided some comments inline.

2024-08-04 08:01 UTC, sumitkumar1212 commented on papers/eli_knaap/main.md
> +  providers including Census, EPA, LEHD, NCES, and NLCD, streamed efficiently from the
Need to spell out these acronyms -  EPA, LEHD, NCES, and NLCD

2024-08-04 08:01 UTC, sumitkumar1212 commented on papers/eli_knaap/main.md
> +data for every release of the 5-year ACS at both the tract and blockgroup levels
Pls add full form of ACS

2024-08-04 08:01 UTC, sumitkumar1212 commented on papers/eli_knaap/main.md
> +blockgroups are not exposed directly, but are accessible as part of the ACS and EJSCREEN
pls add full form of EJSCREEN

2024-08-04 08:01 UTC, sumitkumar1212 commented on papers/eli_knaap/main.md
> +[Stanford Education Data Archive](https://exhibits.stanford.edu/data/catalog/db586ns4974)
Pls add SEDA acronym here as its being used later.

2024-08-04 08:01 UTC, sumitkumar1212 commented on papers/eli_knaap/main.md
> +The LODES data contain job counts tabulated for home and workplace census block, and
Full form of LODES is missing

2024-08-04 08:01 UTC, sumitkumar1212 commented on papers/eli_knaap/main.md
> +its most useful when the polygons are small and homogenous
```suggestion
its most useful when the polygons are small and homogeneous
```

2024-08-04 08:01 UTC, sumitkumar1212 commented on papers/eli_knaap/main.md
> +scientific/academic side, many of the era's pressing problems are spatial and or urban
```suggestion
scientific/academic side, many of the era's pressing problems are spatial and/or urban
```

2024-08-04 08:01 UTC, sumitkumar1212 commented on papers/eli_knaap/main.md
> +
Please add caption to above figure(and all the figures in the paper) such as "Figure X: Description of the figure"

2024-08-04 08:01 UTC, sumitkumar1212 commented on papers/eli_knaap/main.md
> +```
Consider adding comments to explain purpose of each code block to improve code readability (applicable to all code blocks in the paper).

2024-08-04 08:01 UTC, sumitkumar1212 commented on papers/eli_knaap/main.md
> +using the returned `ModelResults` class (which shows significantly different transition
Where is this ModelResults class? can we provide some explanation.

2024-08-04 08:01 UTC, sumitkumar1212 commented on papers/eli_knaap/main.md
> +  those challenges, `geosnap`, the Geospatial Neighborhood Analysis Pacakge provides a
```suggestion
  those challenges, `geosnap`, the Geospatial Neighborhood Analysis Package provides a
```

2024-08-04 08:01 UTC, sumitkumar1212 commented on papers/eli_knaap/main.md
> +![Chicago Neighborhood Transitions](./transition_matrix.png)
This figure says that there are 6 Modal neighbors. However, the previous figure and code was showing 5 clusters. How do you reconcile?

2024-08-10 22:25 UTC, hongsupshin requested changes
Hi @knaaptime , my name is Hongsup Shin and I am a reviewer of your paper. I left line-by-line comments. Also, a few general thoughts:

- Consider running a spell/punctuation check on the manuscript.
- Consider removing adjectives/adverbs that do not provide much value (e.g., "extremely", "just", etc.). Instead, consider provide measurable impacts.
- It's not completely clear why your proposed package is better than existing methods, so please consider mentioning this early in the manuscript.
- As the other reviewer said, please provide more explanations on code snippets.

2024-08-10 22:25 UTC, hongsupshin commented on papers/eli_knaap/main.md
> +scientific/academic side, many of the era's pressing problems are spatial and or urban
and or -> or

2024-08-10 22:25 UTC, hongsupshin commented on papers/eli_knaap/main.md
> +scientific/academic side, many of the era's pressing problems are spatial and or urban
"many of the era's pressing problems" -> examples?

2024-08-10 22:25 UTC, hongsupshin commented on papers/eli_knaap/main.md
> +accurate inferences. Thus, while data science teams in industries across the planet race
"conquer 'geospatial data science' " -> perhaps you can be more specific what "conquer" means here

2024-08-10 22:25 UTC, hongsupshin commented on papers/eli_knaap/main.md
> +To address these challenges we introduce `geosnap`, the geospatial neighborhood analysis
Is your package the first ever geospatial neighborhood analysis package or was there an existing package? If yes, how is yours different from that?

2024-08-10 22:25 UTC, hongsupshin commented on papers/eli_knaap/main.md
> +opportunity, and the social determinants of health. The package provides extremely fast
I suggest considering providing specific measurable benefits instead of using words such as "extremely" or "hundreds"

2024-08-10 22:25 UTC, hongsupshin commented on papers/eli_knaap/main.md
> +quality indicators that allow researchers to move from zero data to an informative model
How is it possible to have an informative model if I have zero data?

2024-08-10 22:25 UTC, hongsupshin commented on papers/eli_knaap/main.md
> +and serving (those we are allowed to) over fast web protocols. This makes it much faster
much faster than what?

2024-08-10 22:25 UTC, hongsupshin commented on papers/eli_knaap/main.md
> +be extremely slow for even medium-sized datasets. While there are nice tools like
Can you show the comparison in terms of performance between the existing and the proposed?

2024-08-10 22:25 UTC, hongsupshin commented on papers/eli_knaap/main.md
> +To load a dataset, like the 2010 tract-level census data, just call it as a method,
What's special about "2010 tract-level census data"?

2024-08-10 22:25 UTC, hongsupshin commented on papers/eli_knaap/main.md
> +means it's impossible to see if tract XZY has changed over time because "tract XYZ"
XZY -> XYZ? Are you just making an example of a tract? If that's the case, would it be just enough to call it as "a tract"?

2024-08-10 22:25 UTC, hongsupshin commented on papers/eli_knaap/main.md
> +boundaries over time. Doing so is as simple as calling the `harmonize()` function
A period is missing.

2024-08-10 22:25 UTC, hongsupshin commented on papers/eli_knaap/main.md
> +its most useful when the polygons are small and homogenous
Missing period

2024-08-10 22:25 UTC, hongsupshin commented on papers/eli_knaap/main.md
> +(extensive), so we make sure to pass each to the appropriate list
Missing period

2024-08-10 22:25 UTC, hongsupshin commented on papers/eli_knaap/main.md
> +[intensive and extensive](https://en.wikipedia.org/wiki/Intensive_and_extensive_properties)
Please explain what these variables are in a few words in addition to linking them to the wikipedia page.

2024-08-10 22:25 UTC, hongsupshin commented on papers/eli_knaap/main.md
> +```python
You can probably add comments to explain what certain variables mean. Also please provide what this cell block does in a few sentences.

2024-08-10 22:25 UTC, hongsupshin commented on papers/eli_knaap/main.md
> +    sd,
what's sd?

2024-08-10 22:25 UTC, hongsupshin commented on papers/eli_knaap/main.md
> +In urban social science, a primary goal is often to study the social composition of
Examples of "social composition"?

2024-08-10 22:25 UTC, hongsupshin commented on papers/eli_knaap/main.md
> +To create a simple geodemographic typology, use the cluster function and pass a
"the cluster function" -> I don't think this was referred before?

2024-08-10 22:25 UTC, hongsupshin commented on papers/eli_knaap/main.md
> +of the results. Most often, this process happens repeatedly using diffferent
diffferent -> typo

2024-08-10 22:25 UTC, hongsupshin commented on papers/eli_knaap/main.md
> +    gdf=atl, method="kmeans", n_clusters=5, columns=columns, return_model=True
Does your package allow users to evaluate the quality of the clustering result?

2024-08-10 22:25 UTC, hongsupshin commented on papers/eli_knaap/main.md
> +useful. Here, we rely on the Tufte-ian principle of “small multiples”, and create a set
Please elaborate "Tufte-ian"

2024-08-10 22:25 UTC, hongsupshin commented on papers/eli_knaap/main.md
> +and inner-quartile range (IQR), and the “body” of the “violin” is a kernel-density
IQR is *interquartile* range, not inner

2024-08-10 22:25 UTC, hongsupshin commented on papers/eli_knaap/main.md
> +```python
Same issue. Please provide a short explanation about what this cells does

2024-08-10 22:25 UTC, hongsupshin commented on papers/eli_knaap/main.md
> +```python
See the previous comment

2024-08-10 22:25 UTC, hongsupshin commented on papers/eli_knaap/main.md
> +there is nothing ‘natural’ about it, this phenomenon would be akin to classic
double quote

2024-08-10 22:25 UTC, hongsupshin commented on papers/eli_knaap/main.md
> +A natural way to understand the transition matrix between two neighborhood types is the
it the plot -> is to plot

2024-08-10 22:25 UTC, hongsupshin commented on papers/eli_knaap/main.md
> +\hat{p}_{i,j} = \frac{n_{i,j}}{\sum_{k=1}^k n_{i,k} }
Do you need this equation? This is just a normalized value. Also, you don't provide what the variables mean

2024-08-10 22:25 UTC, hongsupshin commented on papers/eli_knaap/main.md
> +Further, the transition rates can be used to simulate future conditions (note this
How do you evaluate the simulate results?

2024-08-10 22:25 UTC, hongsupshin commented on papers/eli_knaap/main.md
> +#### Travel Isochrones
Can you add a short explanation of what Isochrones means?

2024-08-10 22:25 UTC, hongsupshin commented on papers/eli_knaap/main.md
> +organized around the concept of 'endogenous' neighborhoods. That is, it takes a
double quote

2024-08-10 22:25 UTC, hongsupshin commented on papers/eli_knaap/main.md
> +As a package focused on "neighborhoods", much of the functionality in geosnap is
What's the reason behind double quoting? Is this different from the neighborhoods you referred to previous? if yes, then why and how?

2024-08-13 19:22 UTC, knaaptime commented on papers/eli_knaap/main.md
> +To address these challenges we introduce `geosnap`, the geospatial neighborhood analysis
as far as we know it's the first

2024-08-13 19:27 UTC, knaaptime commented on papers/eli_knaap/main.md
> +As a package focused on "neighborhoods", much of the functionality in geosnap is
i tend to use double and single interchangeably

2024-08-13 19:28 UTC, knaaptime commented on papers/eli_knaap/main.md
> +quality indicators that allow researchers to move from zero data to an informative model
the user has zero data when they begin using the package; the package provides all data, thus everything necessary to move from zero to an informative model

2024-08-13 19:29 UTC, knaaptime commented on papers/eli_knaap/main.md
> +To load a dataset, like the 2010 tract-level census data, just call it as a method,
nothing, it's just an example

2024-08-13 19:29 UTC, knaaptime commented on papers/eli_knaap/main.md
> +be extremely slow for even medium-sized datasets. While there are nice tools like
added a simple example

2024-08-13 19:30 UTC, knaaptime commented on papers/eli_knaap/main.md
> +    gdf=atl, method="kmeans", n_clusters=5, columns=columns, return_model=True
yes, we return the model object. clarified in the text

2024-08-13 19:31 UTC, knaaptime commented on papers/eli_knaap/main.md
> +#### Travel Isochrones
added short explanation

2024-08-13 19:31 UTC, knaaptime commented on papers/eli_knaap/main.md
> +and serving (those we are allowed to) over fast web protocols. This makes it much faster
added simple comparison to FTP download and read-in with geopackage

2024-08-13 19:31 UTC, knaaptime commented on papers/eli_knaap/main.md
> +means it's impossible to see if tract XZY has changed over time because "tract XYZ"
removed xyz

2024-08-13 19:33 UTC, knaaptime commented on papers/eli_knaap/main.md
> +opportunity, and the social determinants of health. The package provides extremely fast
this is difficult because these metrics are hard to judge for spatial data. a relatively 'small' n of 200k can still have an enormous "size" because each record needs to store the vertices of each geometry (which depends on the kind of geometry and resolution, etc). Also we're talking about  downloads here, which are obviously dependent on external servers and the size of a given request. I tried to add some additional context

2024-08-20 04:38 UTC, dcamron requested changes
Thanks for the opportunity to review! There's a lot of cool stuff in here, and I learned a lot along the way. My overarching feedback looks similar to the other reviewers, and apologies if you've addressed some of this already. Do note, my background is not aligned technically here with your users, so a lot of this language is new to me.

* Please define all important technical terms and acronyms on first mention, and consider using simpler language where possible and appropriate. [MyST can help you here as well](https://mystmd.org/guide/glossaries-and-terms#abbreviations)! 
* Your per-functionality overview structure was super helpful for me to get a high-level look at geosnap's uses, and the narrative flowed cohesively between sections. 
* The use of interrupting parenthetical phrases throughout reduced clarity and impact for me, and I found them distracting. I think nearly all of these can be completely omitted, rephrased within the sentence, or moved to a footnote. Some later paragraphs had one or more per sentence.
* Similarly, inconsistent emphasis became distracting for me. I struggled to find consistent meaning across quote and emphasis styles, which confused me in some sections. Consider saving double quotes for directly quoting references and italics (sparingly) for internally-defined terms and concepts or strong contrasts. Or use [MyST's glossary and term functionality](https://mystmd.org/guide/glossaries-and-terms#glossaries).

Regarding the parentheses and the quotes/italics/emphases, I removed a lot of of my individual comments and left some in, **but please take a full look to remove or edit these for clarity and simplicity.**

I know so much of my feedback is regarding style. That is because I struggled to clearly learn about this new tool quickly and effectively on first read. Still, the potential impact of geosnap is absolutely visible here. I hope my feedback can help make your message clearer to new audiences, and please let me or the committee know if my feedback is too granular.

Thanks again, I'm looking forward to seeing this published!

2024-08-20 04:38 UTC, dcamron commented on papers/eli_knaap/main.md
> +  pipeline. Maintaining that balance is challenging for a variety of reasons. To address
The interrupted parallel here was difficult for me to follow. Consider breaking up into two phrases or reorder something like "However, the term 'neighborhood' differs in definition, connotation, and practical use depending on study or application, so neighborhood analysis and modeling requires both flexibility and adherence to a formal pipeline."

2024-08-20 04:38 UTC, dcamron commented on papers/eli_knaap/main.md
> +@Rey2022a; @wei2022ReducingRacial]. On the scientific/academic side, many of the
```suggestion
@Rey2022a; @wei2022ReducingRacial]. On the academic side, many of the
```
Slash is unnecessary.

2024-08-20 04:38 UTC, dcamron commented on papers/eli_knaap/main.md
> +inferences. Thus, while data science teams in industries across the planet race
```suggestion
era's pressing problems are spatial or urban in form, requiring
bespoke statistical methods and simulation techniques to produce accurate
inferences. Thus, while data science teams in industries across the planet race
```
1. Example of distracting and extending parenthetical phrase. Consider a footnote with citations or a separate sentence altogether.
1. This particular claim representing the body of academia is also un-cited. Compare to the citations of "practical" section above.
1.  "thus [...]. Thus,"

2024-08-20 04:38 UTC, dcamron commented on papers/eli_knaap/main.md
> +to conquer 'geospatial data science' few practitioners have expertise in the
Example 
```suggestion
to conquer geospatial data science few practitioners have expertise in the
```
Example of inconsistent emphasis. Is this an internal definition or a reference? Without knowing, it serves as "scare quotes" emphasis in my mind's voice, which I find distracting.

2024-08-20 04:38 UTC, dcamron commented on papers/eli_knaap/main.md
> +analysis/spatial econometrics and the applied fields of neighborhood change, access to
```suggestion
analysis and the applied fields of neighborhood change, access to
```
Is the slash and extra term necessary? If the terms are specific and both necessary to include, please define and contrast the terms ahead of this, then remove the slash and include both in the bridge metaphor.

2024-08-20 04:38 UTC, dcamron commented on papers/eli_knaap/main.md
> +It is organized into layers for data acquisition, analysis, and visualization, and
```suggestion
`geosnap` is organized into layers for data acquisition, analysis, and visualization, and 
```
Or similar. New paragraph and unclear continuation from previous phrasing.

2024-08-20 04:38 UTC, dcamron commented on papers/eli_knaap/main.md
> +computed) service areas and travel isochrones. We expect the tool will be immediately
```suggestion
creating geodemographic typologies that summarize and predict multidimensional
segregation over time, and network analysis tools that locally compute rapid service areas and travel isochrones. We expect the tool will be immediately
```
This is representative of my main style feedback above:
1. Distracting emphasis. If the "geodemographic typologies" is important, consider explicitly defining it. Italics could do if needed, or use MyST Terms.
1. I know you address in more detail in alter sections, but this section was particularly jargony on my first read.
1. Parenthetical phrase.

2024-08-20 04:38 UTC, dcamron commented on papers/eli_knaap/main.md
> +- Quick access to a large database of commonly-used neighborhood indicators from
```suggestion
- Quick access to a large database of commonly used neighborhood indicators from
```

2024-08-20 04:38 UTC, dcamron commented on papers/eli_knaap/main.md
> +  streamed efficiently from the cloud (or stored for repeated use).
```suggestion
  U.S. providers including the U.S. Census, the Environmental Protection Agency
  (EPA), Longitudinal Household-Employment Dynamics (LEHD), the National Center
  for Education Statistics (NCES), and National Land Cover Database (NLCD),
  streamed efficiently from the cloud or stored for repeated use.
```
1. Thanks for defining these acronyms. Consider using MyST acronyms for further clarity when published!
1. Parenthesis.

2024-08-20 04:38 UTC, dcamron commented on papers/eli_knaap/main.md
> +  PySAL
Add links or references for scikit-learn and PySAL

2024-08-20 04:38 UTC, dcamron commented on papers/eli_knaap/main.md
> +institutional, and economic conditions that characterize the area. The geosnap
```suggestion
Neighborhoods, cities, and regions can be characterized by a variety of data. Researchers use the social, environmental,
institutional, and economic conditions of the area to understand change in these places and the people who inhabit them. The geosnap
```

Run-on and repeat of "characterize[d]". Suggestion is just one option!

2024-08-20 04:38 UTC, dcamron commented on papers/eli_knaap/main.md
> +publicly-available datasets simpler, faster, and more reproducible by
```suggestion
publicly available datasets simpler, faster, and more reproducible by
```
As with above, modifying adverbs directly preceding adjectives shouldn't need this unless ambiguous.

2024-08-20 04:38 UTC, dcamron commented on papers/eli_knaap/main.md
> +scales or time frames). That works ok in some cases, but it is also cumbersome, and can
```suggestion
writing the same code to download  the same data repeatedly. That works in some cases, but it is also cumbersome, and can
```
1. Or include important pieces inline if needed. In my opinion the impact and clarity goes up when they're completely removed. I'll highlight some of them from here on and leave the specific solution to you.
1. "ok" is a vague quantity.

2024-08-20 04:38 UTC, dcamron commented on papers/eli_knaap/main.md
> +File Transfer Protocol (FTP) and outdated file formats (like shapefiles).
```suggestion
[pyrgris](https://walker-data.com/pygris/), but creating fast, scalable analyses with these tools is potentially limited by the data transfer protocols and file formats relied on by many government data providers [citation or further clarification].
```
1. Elaborate and support this claim in a way that connects to impact. Would it matter that FTP and shapefiles are old if they worked well to solve our problems?

2024-08-20 04:38 UTC, dcamron commented on papers/eli_knaap/main.md
> +[a public S3 bucket](https://open.quiltdata.com/b/spatial-ucr), thanks to the
Very cool!

2024-08-20 04:38 UTC, dcamron commented on papers/eli_knaap/main.md
> +geosnap's developers maintain this database as an additional layer.
```suggestion
the developers of `geosnap` maintain this database as an additional layer.
```
Or standardize without backticks. Either way, I suppose!

2024-08-20 04:38 UTC, dcamron commented on papers/eli_knaap/main.md
> +which is used in countless studies of neighborhood change [@Logan_2014]. One of the most
```suggestion
which is used in studies of neighborhood change [@Logan_2014]. One of the most
```
Snark incoming: I count one (1) 😂. I kid, but the word is unnecessary!

2024-08-20 04:38 UTC, dcamron commented on papers/eli_knaap/main.md
> +recognized benefits of this dataset is that it standardizes boundaries for census
Is this recognition possible to be quantified and cited? As a maintainer myself, I understand if it's not easy or possible to quantify.

2024-08-20 04:38 UTC, dcamron commented on papers/eli_knaap/main.md
> +analysis. An under-appreciated benefit of these data is the ease with which researchers
```suggestion
analysis. A benefit of these data is the ease with which researchers
```
"under-appreciated" verges on needing citation here, but could stay as well.

2024-08-20 04:38 UTC, dcamron commented on papers/eli_knaap/main.md
> +data for every release of the 5-year ACS at both the tract and blockgroup levels
Was this resolved?

2024-08-20 04:38 UTC, dcamron commented on papers/eli_knaap/main.md
> +**[fully open and reproducible](https://github.com/oturns/geosnap/blob/main/tools/process_census_gdb.ipynb)**.
```suggestion
Unlike LTDB or the National Historical Geographic Information System
([NHGIS](https://www.nhgis.org/)), these datasets are created using code that collects raw
data from the Census FTP servers, computes intermediate variables according to the
codebook, and saves the original geometries-- and is
[fully open and reproducible](https://github.com/oturns/geosnap/blob/main/tools/process_census_gdb.ipynb).
```
1. What is "the codebook" here?
1. Inconsistent emphasis.
1. What is "fully open and reproducible" here? The "code that collects raw data"? The phrase after the dash appears fragmented on first read, consider breaking up or reordering.

2024-08-20 04:38 UTC, dcamron commented on papers/eli_knaap/main.md
> +arguments). Geometries are available for all of the commonly used administrative units,
```suggestion
To load a dataset, e.g. 2010 tract-level census data, call it as a method to return a geodataframe. Geometries are available for all of the commonly used administrative units,
```
Here is where the aside "e.g." phrase could add clarity. Then the parenthesis.

2024-08-20 04:38 UTC, dcamron commented on papers/eli_knaap/main.md
> +- metropolitan statistical areas (MSAS)
```suggestion
- metropolitan statistical areas (MSAs)
```

2024-08-20 04:38 UTC, dcamron commented on papers/eli_knaap/main.md
> +which uniquely identifies every federally-defined geographic unit in the U.S.
```suggestion
which uniquely identifies every federally defined geographic unit in the U.S.
```

2024-08-20 04:38 UTC, dcamron commented on papers/eli_knaap/main.md
> +blockgroups are not exposed directly, but are accessible as part of the ACS and EJSCREEN
Reopening. I know the definition is below, but please move it up here or save this comment for after its definition.

2024-08-20 04:38 UTC, dcamron commented on papers/eli_knaap/main.md
> +The geosnap `io` module (aliased here as `gio`) has a set of functions for creating
```suggestion
otherwise it will be streamed from S3 with an available internet connection.
The geosnap `io` module (aliased here as `gio`) has a set of functions for creating
```
The second one here could be offset with commas, but this is fine enough.

2024-08-20 04:38 UTC, dcamron commented on papers/eli_knaap/main.md
> +and their metadata, see the EPA page, but this dataset includes important variables like
```suggestion
full list of indicators
and their metadata, see [this EPA page](https://www.epa.gov/ejscreen/overview-environmental-indicators-ejscreen). This dataset includes important variables like
```

Descriptive and direct links are most helpful for screen readers and other assistive tech. These sentences are also conceptually different and worth separating.

2024-08-20 04:38 UTC, dcamron commented on papers/eli_knaap/main.md
> +incredible resource for social science research.For more information on how to use the
```suggestion
incredible resource for social science research. For more information on how to use the
```

2024-08-20 04:38 UTC, dcamron commented on papers/eli_knaap/main.md
> +education. LODES also provides flow matrices that show the origin and
```suggestion
The LEHD Origin-Destination Employment Statistics (LODES) data contain job
counts tabulated for home and workplace census block. These data are broken down by
industrial sector and a handful of demographic characteristics like race and
education. LODES also provides flow matrices that show the origin and
```
These phrases are a bit disjointed.

2024-08-20 04:38 UTC, dcamron commented on papers/eli_knaap/main.md
> +time period. To help solve that problem geosnap leverages the pysal
```suggestion
time period. To help solve that problem `geosnap` leverages the PySAL
```

2024-08-20 04:38 UTC, dcamron commented on papers/eli_knaap/main.md
> +tracts and blocks are re-drawn with each census to accomodate population growth
```suggestion
A common issue in spatial analysis is that geographic tabulation units can change over time. For instance the U.S. census boundary polygons like
tracts and blocks are re-drawn with each census to accomodate population growth
```

Also, I'm unfamiliar: should "census" be consistently capitalized, or not? Or does it depend, a la "Earth" and "the earth"?

2024-08-20 04:38 UTC, dcamron commented on papers/eli_knaap/main.md
> +over time. Doing so is as simple as calling the `harmonize()` function.
```suggestion
over time. We do so by calling the `harmonize()` function.
```

2024-08-20 04:38 UTC, dcamron commented on papers/eli_knaap/main.md
> +(extensive), so we make sure to pass each to the appropriate list.
I appreciate the new explanations a ton!

Please see the [rendered preview](https://proceedings.scipy.org/previews/01914d45-e7a0-7684-8015-d2300078cdac?preview=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJodHRwczovL2pvdXJuYWxzLmN1cnZlbm90ZS5jb20iLCJleHAiOjE3MjQ1Mjc5MzUsImF1ZCI6InNjaXB5Iiwic2NvcGUiOiJzdWJtaXNzaW9uIiwic2NvcGVJZCI6IjAxOGZkZWNhLTQzMmUtN2FhYS1iMjRjLTExYmU1MTRmZjg3NSIsImlhdCI6MTcyNDA5NTkzNX0.SpWh5qh-WvhBL2aRRxVMIMBe3hm-hn24GEAGt27v-IU#harmonization). The mixing of emphasis (double quotes, single quotes, and italics are all used here) with unclear purpose or reference and the interruption from parentheses and example phrases have totally confused me here. Though, I do appreciate the contrasting "per <quantity>" phrases, they're difficult for me to parse inline when reading. Please heavily consider revising this fully for clarity and impact.

I'm also glad to step away from this point with input from others if this is more of a Me Problem.

2024-08-20 04:38 UTC, dcamron commented on papers/eli_knaap/main.md
> +sequence-analysis methods [@Kang2021; @Lee2017] (both of which are built into `geosnap`).
```suggestion
neighborhood change. For example, both Markov-based methods [@Agovino2019; @gallo_space-time_2004-1; @kang_rey_2018_ars; @rey_2016_jgs; @Rey2014] and
sequence-analysis methods [@Kang2021; @Lee2017] are built into `geosnap`.
```
An example to drop the parentheses.

2024-08-20 04:38 UTC, dcamron commented on papers/eli_knaap/main.md
> +Technically there is no formal *spatial analysis* in traditional geodemographics,
```suggestion
spatial data science
[@Abbas2009; @Adnan2010; @anderson2010UsingGeodemographics; @DeSabbata2019; @singleton2009CreatingOpen; @singleton2009GeodemographicsVisualisation].
Technically there is no formal spatial analysis in traditional geodemographics,
```
Emphases edited.

What are the references supporting here? Please describe their inclusion in more detail or pull explicit citations from specific references.

2024-08-20 04:38 UTC, dcamron commented on papers/eli_knaap/main.md
> +Social Area Analysis
```suggestion
studies from factorial ecology
[@Berry1971; @Hunter1972; @lebowitz1977CriticalExamination; @Perle1979; @Rees1969] and
social area analysis
```
These appeared not capitalized in the linked references.

2024-08-20 04:38 UTC, dcamron commented on papers/eli_knaap/main.md
> +are sold for their predictive power. Whereas social scientists often look at the
```suggestion
geodemographic analysis can be applied in academic studies of neighborhood
segregation and neighborhood change, and can be used in industry,
particularly marketing where products like
[tapestry](https://www.esri.com/en-us/arcgis/products/data/data-portfolio/tapestry-segmentation)
and
[mosaic](https://www.experian.com/small-business/geodemographic-segmentation-mailing-lists)
are sold for their predictive power. Whereas social scientists often look at the
```
These claims could use citations or simplified language, though I appreciate the links to industry competitors!

2024-08-20 04:38 UTC, dcamron commented on papers/eli_knaap/main.md
> +decisions.
This feels like a strong distinction to draw without example or justification.

2024-08-20 04:38 UTC, dcamron commented on papers/eli_knaap/main.md
> +for rapid exploration.
In 4 sentences here you feature 5 parenthetical phrases. This highlights my overall consideration to edit for clarity and simplicity!

From here I will stop highlighting them, but there are more above and below. Please evaluate their impact on readability and consider using them sparingly and where most impactful.

2024-08-20 04:38 UTC, dcamron commented on papers/eli_knaap/main.md
> +To create a simple geodemographic typology, use the `cluster` function from
What is a geodemographic typology?

2024-08-20 04:38 UTC, dcamron commented on papers/eli_knaap/main.md
> +of clusters endogenously. By default, this will z-standardize all the input
"endogenously" is unclear, or this process could be elaborated on. Also, last actual comment on parentheses here: this one remained unclosed! Consider editing as above.

2024-08-20 04:38 UTC, dcamron commented on papers/eli_knaap/main.md
> +at a distinct place in the region.
```suggestion
this case) which are similar in socioeconomic and demographic composition. If the goal
of geodemographics is to identify neighborhood *types* that could exist anywhere in the
region, the goal of regionalization is to identify *specific neighborhoods* that exist
at a distinct place in the region.
```
The italics could stay useful here for contrast.

2024-08-20 04:38 UTC, dcamron commented on papers/eli_knaap/main.md
> +empirical version of geographically-bounded neighborhoods, where the
```suggestion
empirical version of geographically bounded neighborhoods, where the
```

2024-08-20 04:38 UTC, dcamron commented on papers/eli_knaap/main.md
> +much code. Under the hood, the package provides tools for scaling each dataset
```suggestion
much code. The package provides tools for scaling each dataset
```
I assume this is functionality exposed to the user and not hidden "under the hood"?

2024-08-20 04:38 UTC, dcamron commented on papers/eli_knaap/main.md
> +the evolution of neighborhood change as a spatial Markov process. The following
a link or definition for spatial Markov process would be useful

2024-08-20 04:38 UTC, dcamron commented on papers/eli_knaap/main.md
> +cell creates a neighborhood typology in Chicago using four mutually-exclusive
```suggestion
cell creates a neighborhood typology in Chicago using four mutually exclusive
```

2024-08-20 04:38 UTC, dcamron commented on papers/eli_knaap/main.md
> +another type–then how these transition rates change under different conditions of
```suggestion
another type, then how these transition rates change under different conditions of
```

2024-08-20 04:38 UTC, dcamron commented on papers/eli_knaap/main.md
> +there is nothing ‘natural’ about it, this phenomenon would be akin to classic
```suggestion
This phenomenon would be akin to classic
```
I might recommend removing the phrase altogether without any additional context or citation.

2024-08-20 04:38 UTC, dcamron commented on papers/eli_knaap/main.md
> +\hat{p}_{i,j} = \frac{n_{i,j}}{\sum_{k=1}^k n_{i,k} }
Reopening as unresolved. Please reference and elaborate in the text or remove in favor of further figure explanation (unless I'm missing something somewhere!)

2024-08-20 04:38 UTC, dcamron commented on papers/eli_knaap/main.md
> +minute neighborhood" [@Calafiore2022].
I'm highlighting this paragraph and the resolved reviews as an illustration to my overall review point regarding emphasis. Inconsistent use of "double quotes", 'single quotes', _italics_, and **bold text** has lead to confusion for me. I'm not sure what here is a reference to specific language or definitions, what is emphasis, and what is internal definitions from the author.

Consider avoiding quotes (single or double) for implication or emphasis, and reserve them for direct citations from references. Italics could be used sparingly for clear internal definitions or the occasional emphasis. Please review the entire document for their use once standard formatting is chosen.

2024-08-20 04:38 UTC, dcamron commented on papers/eli_knaap/main.md
> +sometimes conceived as an "egohood" or "bespoke neighborhood"
Highlighting to show the distinction from before: "neighborhood" and previous quotes are not citations from the following references, but "egohood" etc. are, and the distinction is valuable to me the reader!

2024-08-22 14:53 UTC, ameyxd commented
@knaaptime Please send in your updates based on the reviews before the final deadline of September 2. Failure to do so may result in your reviewers potentially rejecting your paper.

2024-09-02 16:28 UTC, knaaptime commented on papers/eli_knaap/main.md
> +![Chicago Neighborhood Transitions](./transition_matrix.png)
there are 6 axes in the figure: one "global" transition heatmap that shows transition probabilities between all types pooled together. The other five heatmaps show transitions conditional on the modal neighbor. These correspond to each of the 5 possible clusters identified earlier

so the figure is correct

2024-09-03 19:49 UTC, knaaptime commented
ive addressed the comments but i cant get the curvenote preview to update

2024-09-03 20:26 UTC, knaaptime commented on papers/eli_knaap/main.md
> +File Transfer Protocol (FTP) and outdated file formats (like shapefiles).
elaborated in the text

2024-09-03 20:27 UTC, knaaptime commented on papers/eli_knaap/main.md
> +which is used in countless studies of neighborhood change [@Logan_2014]. One of the most
+100 :)

2024-09-03 20:28 UTC, knaaptime commented on papers/eli_knaap/main.md
> +tracts and blocks are re-drawn with each census to accomodate population growth
the latter. "a census" is different from the Census (shorthand for the Census Bureau)

2024-09-05 16:26 UTC, fwkoch commented on papers/eli_knaap/main.md
> +[S3]((https://aws.amazon.com/s3/)), where they can be read very quickly (and
@knaaptime - I believe these extra parentheses are causing link resolution to fail. See if this change allows the tests to pass. (For what it's worth, the preview build is still updating correctly, only the content checks are failing.)

```suggestion
[S3](https://aws.amazon.com/s3/), where they can be read very quickly (and
```

2024-09-05 16:39 UTC, honshi01 commented on papers/eli_knaap/main.md
> +Further, the transition rates can be used to simulate future conditions (note this
@knaaptime Hi, could you add some details on how you evaluate simulated results?

2024-09-05 16:49 UTC, ameyxd commented
@[sumitkumar1212](https://github.com/sumitkumar1212)
@sumitkumar1212

@[honshi01](https://github.com/honshi01)
@honshi01

@[hongsupshin](https://github.com/hongsupshin)
@hongsupshin

@[dcamron](https://github.com/dcamron)
@dcamron

@[stargaser](https://github.com/stargaser)
@stargaser

please confirm if your reviews have been incorporated by the author and approve. Leave a thumbs up here if you are satisfied. 

@knaaptime - please make sure to incorporate all feedback ASAP.

2024-09-09 17:17 UTC, knaaptime commented on papers/eli_knaap/main.md
> +Further, the transition rates can be used to simulate future conditions (note this
Hi, thanks for raising this issue. Evaluating the simulation results is a genuine challenge because the dataset can't be partitioned into train/test like many others can. We can't randomly sample within a cross section (because the spatial weights matrix that defines contiguity between observations, i.e. the local neighborhood, will no longer capture the proper neighbor set). We can't sample from time periods either because it breaks the temporal continuity. 

Thus, the only way (we're aware) to evaluate the simulation results is to truncate the training data by leaving out one or two of the most recent time periods, train a model on the earlier data, and compare the simulated results with the observed data in the most recent time periods, which is the approach they use in  [this paper](https://journals.plos.org/plosone/article?id=10.1371/journal.pone.0245357).

the `geosnap` package doesn't provide any specialized functionality for doing the latter (because it only requires the user to fit a model on a smaller subset of data), so we chose not to include any discussion in the paper

2024-09-17 17:09 UTC, ameyxd commented
Approving for publication.

2024-09-25 18:27 UTC, merged