Paper: Mandala: Persistent & Queriable Memoization for Easy and Powerful Scientific Data Management
scipy-conference/scipy_proceedings pull request #933
Opened 2024-06-01 06:58 UTC by amakelov

If you are creating this PR in order to submit a draft of your paper, please name your PR with `Paper: <title>`. An editor will then add a `paper` label and GitHub Actions will be run to check and build your paper.

See the [project readme](https://github.com/scipy-conference/scipy_proceedings#preview-your-paper) for more information.

_Editor_:  

_Reviewers_:

2024-06-04 08:22 UTC, rowanc1 commented on papers/scipy.tex
> +\documentclass[11pt,twoside=semi,openright,numbers=noenddot]{scrartcl}
Could you please move these documents into a folder under papers, following the latex template provided. There must be a myst.yml with your author/title/affiliations information included as well as a unique ID matching your folder. There is more information in the [readme](https://github.com/scipy-conference/scipy_proceedings?tab=readme-ov-file#setting-up-your-environment) under author instructions.

2024-06-08 11:36 UTC, amakelov commented on papers/scipy.tex
> +\documentclass[11pt,twoside=semi,openright,numbers=noenddot]{scrartcl}
Thanks for the clarification, added this as requested along w/ the new version of the paper

2024-06-11 17:25 UTC, ameyxd commented
@amakelov can you recheck the DOIs that fail checks? As long as they are valid DOIs we should be okay.

2024-06-12 15:33 UTC, ameyxd commented
Hey @amakelov are you skipping DOIs when they exist? I don't recommend skipping explicitly just because they are failing checks. Please lmk

2024-06-12 15:57 UTC, amakelov commented
Hi @ameyxd, I only skipped the DOIs for papers/other publications where I couldn't find a DOI after searching on [crossref](https://search.crossref.org/).

2024-06-12 16:04 UTC, ameyxd commented
okay. can you add your ORCiD and affiliation? :)

2024-06-12 17:56 UTC, amakelov commented
OK, this failed again - I guess I didn't follow the latex instructions? Is it correct that I must remove everything before and including \begin{document}?

2024-06-12 18:07 UTC, fwkoch commented on papers/aleksandar_makelov/main.tex
> +}
Hey @amakelov - Taking a look at your failure, the check is picking up on the `\author` defined here in your `tex` document (which does not have an affiliation), rather than the author defined in `myst.yml`. Can you just delete this author entry here?

```suggestion
```

2024-06-12 18:14 UTC, fwkoch commented
I think removing everything before and including `\begin{document}` would also be fine - that will remove any other conflicting metadata.

Is there anything in there you are concerned about losing? Some of the `newcommand` stuff might need to come into `myst.yml` `project.math`. There are a number of errors in your preview build, linked in the comment at the top of your PR (e.g. cross-references). Once the affiliation check is passing, I'll take a deeper look there...

2024-06-13 05:29 UTC, matthewfeickert commented
:wave: Hi @amakelov. I will be one of your reviewers for your SciPy 2024 proceedings submission. You should expect a full first pass review from me in the form of a PR review with comments and suggestions before 2024-06-29. Please tag me here with any comments you have for me. :+1:

2024-06-13 05:31 UTC, matthewfeickert requested changes
@amakelov Please do not edit any files outside of the `papers/aleksandar_makelov/` directory,

https://github.com/scipy-conference/scipy_proceedings/blob/1312327595fe187858f7194fa2ede453b88df2e9/README.md?plain=1#L199

 so please restore all files under `papers/00_tex_template/`.

2024-06-13 05:52 UTC, matthewfeickert requested changes

2024-06-13 05:52 UTC, matthewfeickert commented on papers/aleksandar_makelov/main.tex
> +\item In Section \ref{section:core-concepts}, we describe how memoization is
@amakelov There are multiple rendering issues on the current Curevenote build, such as Section references (like here), Figure references, and the `basic-usage` figure appearing much larger than expected.

@rowanc1 @fwkoch as this submission is written in LaTeX can you offer any suggestions on syntax changes and how to control figure size in the render?

2024-06-13 09:41 UTC, apaleyes commented
Hi @amakelov! I will also be reviewing your paper, alongside @matthewfeickert . Looking forward to reading it!

2024-06-13 12:29 UTC, amakelov commented on papers/aleksandar_makelov/main.tex
> +\item In Section \ref{section:core-concepts}, we describe how memoization is
Sorry about that - was not familiar with the Curvenote system, I thought it's fine to just submit a .tex file that compiles. Is there something I can read that explains the dos and don'ts when writing .tex for Curvenote?

2024-06-13 13:09 UTC, rowanc1 commented on papers/aleksandar_makelov/main.tex
> +\item In Section \ref{section:core-concepts}, we describe how memoization is
Hi @amakelov there are some instructions [in the readme](https://github.com/scipy-conference/scipy_proceedings?tab=readme-ov-file#instructions-for-authors); there is a video overview there. The system uses `mystmd` (https://mystmd.org) to compile. Curvenote is used for the hosting and checks only. There is some documentation on specifics of LaTeX here:
https://mystmd.org/guide/writing-in-latex

The readme has setup instructions to run/preview locally, including the two templates which you can follow!

For the image sizing, I can aim to take a look next week, I was under the impression that we already supported things like `\includegraphics[width=0.8\linewidth]{figure.png}`, but that might not be implemented.

2024-06-19 13:54 UTC, apaleyes reviewed
`mandala` is an interesting library, and I feel the paper does a good job motivating it and explaining some inner workings. The concept of computation frame analogous to database views is very interesting!

The latex build definitely needs fixing. The preview build log is full or errors and warnings, and none of the references (to sections and figures) render correctly, as already pointed out before.

Given that ML is mentioned in the paper as one of the motivating examples, I feel there is a place for showcasing how exactly is the library helpful for ML researchers. Few questions below hint at this.

Finally, it would be great to see examples of the library in action, so that its benefits become very clear and apparent. For example, a quick summary or an excerpt from the logistic regression example, found in the library's repo, could be a valuable addition here.

2024-06-19 13:54 UTC, apaleyes commented on papers/aleksandar_makelov/main.tex
> +  tracking -- turn \texttt{mandala} into a practical and radically simpler tool
"radically simpler" - simpler than what? Maybe just "simple"?

2024-06-19 13:54 UTC, apaleyes commented on papers/aleksandar_makelov/main.tex
> +computational pipelines, and increasingly safety-critical application domains
"increasingly safety-critical application domains" - do you mean these domains are increasingly more safety critical? Or that ML is more pervasive in these domains? Not very clear from how it's phrased

2024-06-19 13:54 UTC, apaleyes commented on papers/aleksandar_makelov/main.tex
> +\citep{ravi2016deep,abramson2024accurate} and large language model autonomous
LLM agents are hardly a safety critical domain in general

2024-06-19 13:54 UTC, apaleyes commented on papers/aleksandar_makelov/main.tex
> +high-level operations \cite{wickham2014tidy}, full data \& code provenance
cite{wickham2014tidy} -> citep{wickham2014tidy}

2024-06-19 13:54 UTC, apaleyes commented on papers/aleksandar_makelov/main.tex
> +\cite{ivie2018reproducibility} in complex projects.  Rules and practices that
citep again

2024-06-19 13:54 UTC, apaleyes commented on papers/aleksandar_makelov/main.tex
> +can optionally be made persistent, which is what you would typically want in a
What is "persistent" referring to? Hard disk storage as opposed to memory?

2024-06-19 13:54 UTC, apaleyes commented on papers/aleksandar_makelov/main.tex
> +and outputs are serializable by the \texttt{joblib} library); there is no
joblib serialisation is actually a very important point, thanks for calling it out. Have you tried `mandala` on some non-trivial datatypes, e.g. numpy/tensorflow/pytorch/jax structures?

2024-06-19 13:54 UTC, apaleyes commented on papers/aleksandar_makelov/main.tex
> +The trade-off is that referring to values without reference to code that
There is another trade-off here, I guess. Does modification of the source code invalidate the mandala's storage, and if so by how much?

2024-06-19 13:54 UTC, apaleyes commented on papers/aleksandar_makelov/main.tex
> +\section{Related Work}
This section feels incomplete without discussion of tensorflow and function tracing of the computation graph: https://www.tensorflow.org/guide/function

2024-06-19 13:54 UTC, apaleyes commented on papers/aleksandar_makelov/main.tex
> +While \texttt{mandala} is not very mature yet and still very much a work in
"not very mature" sounds weakening, there is no reason to leave the reader with an impression like that. How about more positive "is being actively developed"?

2024-06-19 13:54 UTC, apaleyes commented on papers/aleksandar_makelov/main.tex
> +\end{document}
SHouldn't these lines appear after the main text is concluded?

2024-06-19 13:54 UTC, apaleyes commented on papers/aleksandar_makelov/main.tex
> +\item First, we propose a simple design for a decorator for Python functions
Readers can argue that [functools](https://docs.python.org/3/library/functools.html) are full of similar function cache decorators. Is it worth spending some time in the paper explaining how mandala's `@op` is different?

2024-06-19 13:54 UTC, apaleyes commented on papers/aleksandar_makelov/main.tex
> +\section{An Essential vs. Accidental Complexity Analysis}
This section serves as a reasonable motivation, and thus shall appear much earlier in the text. In fact, seeing a section that comes after "Conclusion" is a bit confusing

2024-06-19 13:54 UTC, apaleyes commented on papers/aleksandar_makelov/main.tex
> +values passed as inputs together with content IDs (hashes of the Python objects)
How does the Ref object deal with float point precision as well as randomized inputs? E.g. imagine a classic example of training a neural net: it's common to start with randomized initial weights - would mandala still be helpful in any way in that scenario?

2024-06-19 23:53 UTC, fwkoch reviewed
Here are some suggestions to fix your two missing figures and your unresolved cross-references. I believe if you make these changes, your content will be building correctly.

Currently, MyST does not support some of the subfigure sizing/arrangement from your tex file: https://github.com/executablebooks/mystmd/issues/1337

2024-06-19 23:53 UTC, fwkoch commented on papers/aleksandar_makelov/main.tex
> +\input{math_commands.tex}
MyST currently does not support commands that come from an `\input` file: https://github.com/executablebooks/mystmd/issues/1326

However, I don't think you are actually using commands from there in your document, so maybe you can just remove this line?

If I missed something and you are using commands from that file, please just directly copy them into this tex file for now.

2024-06-19 23:53 UTC, fwkoch commented on papers/aleksandar_makelov/main.tex
> +\begin{wrapfigure}[23]{r}{0.5\textwidth}
MyST currently does not support `wrapfigure` so this figure and the subsequent figure that uses `wrapfigure` do not render.

For now, can you just replace these with normal `figure`:

```suggestion
\begin{figure}
```
etc.

2024-06-19 23:53 UTC, fwkoch commented on papers/aleksandar_makelov/myst.yml
> +  date: 2024-07-10
Regarding the broken section references in your MyST site that render as "??" - These are `\ref` commands looking for a section number, but your sections are not numbered.

Probably the easiest fix for this is to add to your `myst.yml`
```suggestion
  date: 2024-07-10
  numbering:
    headings: true
```

2024-06-20 22:56 UTC, ameyxd commented
Review reminders sent to @matthewfeickert and @apaleyes

2024-06-21 15:28 UTC, fwkoch commented on papers/aleksandar_makelov/main.tex
> +\begin{wrapfigure}[23]{r}{0.5\textwidth}
I updated MyST to support this, so you may leave `wrapfigure` in your manuscript.

2024-06-21 15:33 UTC, fwkoch commented on papers/aleksandar_makelov/myst.yml
> +  date: 2024-07-10
(Numberings will also be fixed on the final scipy proceedings site, but adding the change I suggested will fix your preview build.)

2024-06-21 16:45 UTC, amakelov commented on papers/aleksandar_makelov/main.tex
> +\begin{wrapfigure}[23]{r}{0.5\textwidth}
Wow, thanks a lot!

2024-06-22 18:53 UTC, amakelov commented on papers/aleksandar_makelov/main.tex
> +and outputs are serializable by the \texttt{joblib} library); there is no
I use it for all my ML work, which involves objects like `torch.Tensor`, `pandas.DataFrame`, as well as custom classes, e.g. `torch.nn.Module`. Have not used it with `jax` or `tensorflow` though.

My observations are the following:
- indeed it can be tricky with some types, for example, if you save a `torch.Tensor` with `joblib.dump` and then load it back with `joblib.load`, the `joblib.hash` of the object will be different (might be strictly a CUDA issue, haven't checked yet)
    - I use a workaround: when the given object is a tensor, or a (nested) Python collection of tensors, I first convert to `numpy.ndarray`, which does not suffer from this issue (I believe `joblib` is *specifically* designed to play nice with `numpy`)
    - But even then, custom classes that hide `Tensor`s inside are an issue (happens all the time with `nn.Module`). You could use some more heavyweight introspection to try to overcome this, but I haven't done it so far
- For a lot of other things it works pretty great though. E.g., a lot of ML analyses are just passing arrays around.

To get an idea, here's a content hash function from "the trenches":
```python
def get_content_hash(obj: Any) -> str:
    if hasattr(obj, "__get_mandala_dict__"):
        obj = obj.__get_mandala_dict__()
    if Config.has_torch:
        # TODO: ideally, should add a label to distinguish this from a numpy
        # array with the same contents!
        obj = tensor_to_numpy(obj) 
    if isinstance(obj, pd.DataFrame):
        # DataFrames cause collisions for joblib hashing for some reason
        # TODO: the below may be incomplete
        obj = {
            "columns": obj.columns,
            "values": obj.values,
            "index": obj.index,
        }
    result = joblib.hash(obj)  # this hash is canonical wrt python collections
    if result is None:
        raise RuntimeError("joblib.hash returned None")
    return result
```

2024-06-22 20:08 UTC, amakelov commented on papers/aleksandar_makelov/main.tex
> +The trade-off is that referring to values without reference to code that
Great question. There's a versioning system (I hope to write something more informative about it in the paper during the review period) which is turned off by default. This means that you can change the code, and the storage won't be invalidated. 

If you choose to use the versioning system (which admittedly is experimental, and has some kind-of-out-there ideas), it works roughly as follows:
- The overall idea is that, for each memoized function, we store its code, as well as the code of its dependencies, and when a change is detected (in either the memoized function or any dependency), the user has the option to mark the change as a "cosmetic" one (so that it doesn't invalidate saved calls) or a "semantic" one (in which case, when using this new code, memoized calls that used the old code will be recomputed).
- Crucially, the dependencies are tracked **dynamically**, meaning that each individual call keeps track of the functions it called (via a custom call stack in the `mandala` internals that does not invoke `sys.settrace`). This is nice because if you change some dependency, you want only the calls that actually accessed it to be invalidated.
    - The "version" of a memoized function `f` for a call is then a combination of `f`'s code at the time of the call, plus the code of all dependencies. 
- The system is **truth-of-the-code** [in the terminology of Rich Hickey](https://youtu.be/oyLBGkS5ICk?feature=shared&t=2928) like `git`, meaning that
    - it's content-based: there's no human annotation of versions, the only exception being the ability to mark some changes as non-invalidating (which brings some subtle problems).
    - the storage can figure out which "world" it is in w.r.t. versions by just looking at the state of the code at the time of calling the memoized function. This is a really powerful property! You can just "travel in time" to a previous code state, and interact with the storage at that point in time. 
        - It works because when you see the inputs to a call to `f`, you can find what dependencies `f` used in the past on these inputs. If one of the memoized calls matches the current state of the code w.r.t. these dependencies, you can re-use the memoized call. If none of the calls match, you have to re-compute. The key property is that, **assuming the set of dependencies invoked during a given call is deterministic**, there can't be two or more saved calls that both match the current state of the code, which allows you to uniquely resolve the version to use (and hence the memoized call whose outputs to return). 

The ability to mark some changes as non-invalidating opens the door to some subtle issues. Suppose we have a memoized function `f`. We extract a method `g` out of `f`, refactor `f` to
use `g`, and then mark the change as non-invalidating. However, the storage doesn't know that `g` is now effectively a dependency of `f`'s past calls . Then, if we change `g` and call `f` on some previously seen inputs, the storage will think it's fine to reuse the memoized call. 

I currently have no good solution to this that doesn't require some manual work by the user.

2024-06-22 20:15 UTC, amakelov commented on papers/aleksandar_makelov/main.tex
> +can optionally be made persistent, which is what you would typically want in a
Yes, persistent = hard disk storage, by default `Storage()` is in-memory.

2024-06-22 20:19 UTC, amakelov commented on papers/aleksandar_makelov/main.tex
> +\section{Related Work}
Thanks for the pointer - what do you think should be said about `@tf.function` (I'm not familiar with it btw)? The tracing system used in `mandala` is a very simple one, based on a decorator for functions/methods that manipulates an internal call stack. Do you mean that `@tf.function` could be a natural point of comparison because it's very similar?

2024-06-22 20:20 UTC, amakelov commented on papers/aleksandar_makelov/main.tex
> +\end{document}
Oops yes fixed!

2024-06-22 20:22 UTC, amakelov commented on papers/aleksandar_makelov/main.tex
> +\section{An Essential vs. Accidental Complexity Analysis}
At present I removed the section (it was scrapped after `\end{document}`, but I guess it still showed up in the preview); but if you found some things from it particularly valuable I'm happy to incorporate them in the paper!

2024-06-22 20:39 UTC, amakelov commented on papers/aleksandar_makelov/main.tex
> +values passed as inputs together with content IDs (hashes of the Python objects)
Regarding precision: great question, haven't really thought about that much! Currently there is no dedicated logic for that. When a memoized function is called on a value, the value is (roughly speaking) passed to `joblib.hash`, and the result is the "content ID". I think this is not entirely impractical (e.g. I haven't ran into issues):
- most times, inputs are either very specific scalar (or otherwise "small" and "explicit") values humans provide intentionally as some fixed expression (e.g., `True`, `[1, 2, 3]`, `0.75`), or more complex values that are results of other memoized functions - where it's very unlikely to run into two values that differ on the level of floating point error
- however, there are still some exceptions. For example, suppose two calls return arrays of zeros of the same shape, except there are some rounding errors. We want to treat the two outputs as the same object, which currently won't work.

Regarding randomness: this may be somewhat opinionated, but to me the best practice when dealing with randomness in projects where you actually want to save and be able to reproduce results is to 
- encapsulate randomness inside the memoized functions, 
- and ideally give these functions some arguments that control the randomness (easiest one would be the appropriate variant of `random_seed` to apply inside the function). This way you get to control and track your randomness precisely
- even without these random seed arguments, you get the property that the first time you call a memoized function, it samples whatever randomness it needs, and after that you reuse that same sample.

For the neural net example specifically, you'd typically have some function like `init_model(...)` that inits your model using some "deterministic" human-readable parametrization (e.g., this many layers, such and such architecture, and `random_seed=...`). You can return the model if you want to save and examine the randomly initialized weights later on.

2024-06-22 20:45 UTC, amakelov commented on papers/aleksandar_makelov/main.tex
> +  tracking -- turn \texttt{mandala} into a practical and radically simpler tool
Thanks, fixed

2024-06-22 20:46 UTC, amakelov commented on papers/aleksandar_makelov/main.tex
> +computational pipelines, and increasingly safety-critical application domains
The latter; it's been rephrased now.

2024-06-22 20:47 UTC, amakelov commented on papers/aleksandar_makelov/main.tex
> +\citep{ravi2016deep,abramson2024accurate} and large language model autonomous
Haha yes true, at least for now :) removed.

2024-06-22 20:47 UTC, amakelov commented on papers/aleksandar_makelov/main.tex
> +While \texttt{mandala} is not very mature yet and still very much a work in
Thanks, replaced!

2024-06-23 08:06 UTC, amakelov commented on papers/aleksandar_makelov/main.tex
> +\input{math_commands.tex}
Removed, thanks!

2024-06-23 08:30 UTC, amakelov commented on papers/aleksandar_makelov/myst.yml
> +  date: 2024-07-10
So after all the suggested changes, none of the figures are showing for me when I preview locally. I get the following type of errors:
```
convert-im6.q16: attempt to perform an operation not allowed by the security policy `PDF' @ error/constitute.c/IsCoderAuthorized/421.
convert-im6.q16: no images defined `_build/site/public/fig1-a9a37853ebabe041933dc9811dd4708b.png' @ error/convert.c/ConvertImageCommand/3229.
```
```
⛔️ main.tex:413:5 Cannot convert image "list-46402ef1b912376ea7cea258654f06ad.pdf" - may not correctly render.
   To convert this image, you must install imagemagick
⛔️ _build/site/public/fig5-12a209743562173f048a769ce611b87d.pdf Could not convert from PDF to PNG: _build/site/public/fig5-12a209743562173f048a769ce611b87d.pdf - Error: Command failed: convert -density 600 -colorspace RGB _build/site/public/fig5-12a209743562173f048a769ce611b87d.pdf -trim _build/site/public/fig5-12a209743562173f048a769ce611b87d.png
convert-im6.q16: attempt to perform an operation not allowed by the security policy `PDF' @ error/constitute.c/IsCoderAuthorized/421.
convert-im6.q16: no images defined `_build/site/public/fig5-12a209743562173f048a769ce611b87d.png' @ error/convert.c/ConvertImageCommand/3229.
```
```
⚠️  _build/site/public/fig3-340c6c379bf85d1626441d78f8180d55.pdf Could not convert to webp:
Error: Command failed: convert -density 600 -colorspace RGB _build/site/public/fig3-340c6c379bf85d1626441d78f8180d55.pdf -trim _build/site/public/fig3-340c6c379bf85d1626441d78f8180d55.png
convert-im6.q16: attempt to perform an operation not allowed by the security policy `PDF' @ error/constitute.c/IsCoderAuthorized/421.
convert-im6.q16: no images defined `_build/site/public/fig3-340c6c379bf85d1626441d78f8180d55.png' @ error/convert.c/ConvertImageCommand/3229.
```

2024-06-23 23:09 UTC, amakelov commented on papers/aleksandar_makelov/main.tex
> +and outputs are serializable by the \texttt{joblib} library); there is no
Actually, I've been doing some tests today, and there are indeed some problems around `joblib` hashing and serialization. For instance, consider the code below which trains a `RandomForestClassifier` and then makes a roundtrip through `joblib` serialization:

```python
import joblib
from sklearn.ensemble import RandomForestClassifier
from sklearn.datasets import load_digits
import random
import numpy as np
import io
from typing import Any

X, y = load_digits(n_class=10, return_X_y=True)
np.random.seed(42)
random.seed(42)

def serialize(obj: Any) -> bytes:
    buffer = io.BytesIO()
    joblib.dump(obj, buffer)
    return buffer.getvalue()


def deserialize(value: bytes) -> Any:
    buffer = io.BytesIO(value)
    return joblib.load(buffer)

X, y = load_digits(n_class=10, return_X_y=True)
model = RandomForestClassifier(max_depth=2, n_estimators=100, random_state=42).fit(X, y)
restored = deserialize(serialize(model))
joblib.hash(model), joblib.hash(restored)
```
You can see that not only are the two hashes (original and post-roundtrip) different, but they are non-deterministic (even after setting all the random seeds). Probably there's some memory address information in the random forest implementation that causes this.

This may not be a huge problem in practice, as long as you don't pass "pathological" objects like that as input to `@op`s - unless you computed these objects by another `@op` (using arguments without pathological behavior), in which case they are stored once and deserialized every time from the same stored representation. The issue might come up when you pass what is morally "the same" object as input to two different calls, but the hashing does not recognize that and recomputes the call.

2024-06-24 14:02 UTC, apaleyes commented on papers/aleksandar_makelov/main.tex
> +and outputs are serializable by the \texttt{joblib} library); there is no
Thanks @amakelov ! I really appreciate the way you dug into the library, and the elaborate response.

Something general I'd like to discuss here though. Most questions I've asked in this review are an opportunity to clarify stuff in the paper. For example this one - it clearly suggests paper could use "limitations" section to talk about serialization, and about code modification (below). Or the question above about storage really hints at rephrasing in the main text.

Are you planning to address these questions in the paper, rather than just stopping at (very detailed and elaborate) answers in the PR itself?

2024-06-24 14:43 UTC, apaleyes commented on papers/aleksandar_makelov/main.tex
> +\section{Related Work}
Yes, it is a very natural mechanism to compare to. Especially in ML context, where one would expect a lot of people to be aware of it.

2024-06-24 14:44 UTC, apaleyes commented on papers/aleksandar_makelov/main.tex
> +\section{An Essential vs. Accidental Complexity Analysis}
It's totally fine to just remove it, thanks

2024-06-24 19:30 UTC, amakelov commented on papers/aleksandar_makelov/main.tex
> +and outputs are serializable by the \texttt{joblib} library); there is no
Yes, certainly - once the discussion here is resolved, based on the consensus and feedback I'll update the paper and post a summary of the changes here.

2024-06-25 10:16 UTC, apaleyes commented on papers/aleksandar_makelov/main.tex
> +can optionally be made persistent, which is what you would typically want in a
ok, maybe worth clarifying this in the paper too

2024-06-25 10:18 UTC, apaleyes commented on papers/aleksandar_makelov/main.tex
> +and outputs are serializable by the \texttt{joblib} library); there is no
perfect, thanks! As mentioned above, I think your findings here warrant a "known limitations" section. Or "future work and improvements", to sound a bit more positive. Hopefully the idea is clear - to make sure paper presents the library in a fair way, and lets the potential users know what the limitations are.

2024-06-25 10:19 UTC, apaleyes commented on papers/aleksandar_makelov/main.tex
> +The trade-off is that referring to values without reference to code that
> I hope to write something more informative about it in the paper during the review period

so here's the golden chance to do it! this sounds both like something to add to the section about main mechanics, and to the "limitations" suggested above

2024-06-25 10:26 UTC, apaleyes commented on papers/aleksandar_makelov/main.tex
> +values passed as inputs together with content IDs (hashes of the Python objects)
Saving and reproducing results is important, no doubt. But the entire point of randomized weights is to make sure results are not dependent on a random draw. Yes, fixing seeds is a common practice, but if some method does not work without the seed fixed - it just does not work. I thus think randomized inputs is quite an important aspect of ML research. It's totally fine if the library has no great answer for it at the moment. Again, this is why i suggested "limitations" section.

On precision - perhaps there is time left to run some tests and report results in the paper? It may either reveal that library can handle these precision differences just fine, or that it cannot and then it's a future improvement that users need to be aware of. Who knows, maybe that'll lead to some library improvement even before the paper is accepted to the proceedings!

2024-06-28 08:05 UTC, matthewfeickert reviewed
## @matthewfeickert Initial review

@amakelov, thanks for the nice proceedings submission! I overall agree with @apaleyes's review and have added some small suggested changes and asked some questions of my own.

Overall, I think this is a very strong proceedings submission that does an excellent job of balancing technical detail with accessibility to a broader scientific audience! I enjoyed reading it and I look forward to discussing any questions on the review as is. :+1:

2024-06-28 08:05 UTC, matthewfeickert commented on papers/aleksandar_makelov/main.tex
> +can optionally be made persistent, which is what you would typically want in a
```suggestion
can optionally be made persistent to disk, which is what you would typically want in a
```

I agree that would be a helpful clarification. :+1:

2024-06-28 08:05 UTC, matthewfeickert commented on papers/aleksandar_makelov/main.tex
> +and outputs are serializable by the \texttt{joblib} library); there is no
Thanks very much @amakelov and @apaleyes for already having this discussion. I think it encapsulates the questions that I had in my review quite well, so I would agree with @apaleyes that some including some context on difficult serialization cases could be quite useful. It doesn't have to be in this section, but discussing it in the paper would be good.

2024-06-28 08:05 UTC, matthewfeickert commented on papers/aleksandar_makelov/main.tex
> +\textbf{computational graph} represented by the storage (Figure \ref{fig:comp-graph}). Importantly, the
You may discuss this elsewhere more, but is it possible to export the computational graph and inspect it, similar to how you might be able to optimize and visualize task graphs in Dask?

2024-06-28 08:05 UTC, matthewfeickert commented on papers/aleksandar_makelov/main.tex
> +high-level data manipulation -- \textbf{into Python's already familiar syntax
```suggestion
its core, it \textbf{integrates best data management practices} --- such as full
data provenance tracking, idempotent \& deterministic computation,
content-addressable versioning of code and its dependencies, and declarative
high-level data manipulation --- \textbf{into Python's already familiar syntax
```

In LaTeX em-dashes are made by `---`. `--` gets you an en-dash, but for the punctuation you're using you want an em-dash. This applies throughout the whole document, so following here I'll denote this same comment by just commending "em-dash". :+1:

2024-06-28 08:05 UTC, matthewfeickert commented on papers/aleksandar_makelov/main.tex
> +composition of memoized functions that produced a given value -- which must be specified anyway -- is already a canonical reference to it.
```suggestion
composition of memoized functions that produced a given value --- which must be specified anyway --- is already a canonical reference to it.
```

em-dash

2024-06-28 08:05 UTC, matthewfeickert commented on papers/aleksandar_makelov/main.tex
> +interface -- the function call}. This automatically enforces the good practice
```suggestion
interface: the function call}. This automatically enforces the good practice
```

I think you might actually want a colon here? Though an em-dash would work as well.

2024-06-28 08:05 UTC, matthewfeickert commented on papers/aleksandar_makelov/main.tex
> +Python's native collections -- lists, dicts, sets -- can be memoized
```suggestion
Python's native collections --- lists, dicts, sets --- can be memoized
```

em-dash

2024-06-28 08:05 UTC, matthewfeickert commented on papers/aleksandar_makelov/main.tex
> +  tracking -- turn \texttt{mandala} into a practical and simple tool for
```suggestion
  Several features implemented on top of the core memoization data structures ---
  such as natively and transparently handling Python collections, caching of
  intermediate results, and a flexible versioning system with dynamic dependency
  tracking --- turn \texttt{mandala} into a practical and simple tool for
```

em-dash

2024-06-28 08:05 UTC, matthewfeickert commented on papers/aleksandar_makelov/main.tex
> +new computations. A small example of retracing is shown in Figure
This is more of a general question than anything that you need to address in the paper, but this seems somewhat similar to checkpointing in automatic differentiation. Is this a fair comparison? (I'm asking in earnest, as I'm not a computer scientist).

2024-06-28 08:05 UTC, matthewfeickert commented on papers/aleksandar_makelov/main.tex
> +  \texttt{mandala}\footnote{\url{https://github.com/amakelov/mandala}}, a Python
Instead of only giving the GitHub URL for the project, if in https://github.com/amakelov/mandala you add a [`CITATION.cff` file](https://citation-file-format.github.io/) and optionally hook up the project repo to a DOI minting archive service like [Zenodo](https://zenodo.org/) then you could fully cite `mandala` here in the paper. :)

To be clear, I don't think this is something that is a problem for the paper as is, but just a suggestion as I have been thinking on software citation more in recent years: https://arxiv.org/abs/2309.14571

2024-07-03 13:16 UTC, amakelov commented on papers/aleksandar_makelov/main.tex
> +new computations. A small example of retracing is shown in Figure
Indeed, it is analogous to checkpointing in the sense that you choose the "boundaries" at which results are checkpointed by the way you define the functions decorated by `@op`. 

As a general guide, you should make something an `@op` if you want to save its
outputs, e.g. if they take a long time to compute but you need them for later
analysis. Since `@op` encourages composition, you should aim to have `@op`s work on the outputs of other `@op`s, or on the collections and/or items of outputs of other `@op`s. There's a bit of WIP documentation on collections [here](https://amakelov.github.io/mandala/05_collections/)

2024-07-03 20:53 UTC, amakelov commented on papers/aleksandar_makelov/main.tex
> +values passed as inputs together with content IDs (hashes of the Python objects)
**Regarding randomness**: I may be opinionated about this, but I think that randomization should not really be automated by the storage layer, because it expresses some non-trivial (and sometimes crucial in a subtle way) intent on part of the user. By enforcing the explicit use of randomness as a resource (if you want multiple random samples, you should parametrize this somehow as an argument to the `@op`), I think `mandala` actually encourages best practices. 

For example, it will be quite visible, looking at memoized code, whether multiple seeds were tested or only a single random instance was implicitly created when there was no random seed argument explicitly passed into the memoized call.

**Regarding precision**: This is a great point, currently the library is very sensitive to often negligible differences between numerical types:
```python
from mandala.utils import get_content_hash

print(get_content_hash(42))
print(get_content_hash(42.0))
print(get_content_hash(42.00000000001))
```
```
d922f805b5eead8c40ee21f14329d6c7
ca276c58eef17e13c4f274c9280abc1e
b61bb24b62bf6b1ab95506a62843be08
```
This is not insurmountable in principle, but it could be hard to have an automatic solution that always works:
- The easy case is when handling "simple" objects like numbers. There could be a custom numerical type, `RoundedFloat` or whatever, which is insensitive to precision differences by passing to a canonical representation before hashing. If an input/output to a function is annotated with `RoundedFloat`, the storage will save only this canonical representation. 
- A similar solution could apply to specific array types, like `np.ndarray`.
- Though I imagine it'll get out of control if more complex types are to be covered, which is the real issue. If someone gives you two huge ML models that differ by 1e-19 in one of their parameters, it seems reasonable to treat them as practically the same. But also, such a situation is unlikely to arise in most practical scenarios, where you'll be handling models that differ in much more significant ways. 
- Finally, if there's a use case where one really cares about this kind of issue, it's probably best to write a custom hash function for the type in question.

I'll certainly add a mention of this in the paper!

2024-07-03 23:30 UTC, amakelov commented on papers/aleksandar_makelov/main.tex
> +and outputs are serializable by the \texttt{joblib} library); there is no
Added a discussion of these topics in "Limitations"

2024-07-03 23:31 UTC, amakelov commented on papers/aleksandar_makelov/main.tex
> +The trade-off is that referring to values without reference to code that
Following our discussion, I extended the discussion of the versioning system in the main body, and added to the limitations section.

2024-07-03 23:32 UTC, amakelov commented on papers/aleksandar_makelov/main.tex
> +\textbf{computational graph} represented by the storage (Figure \ref{fig:comp-graph}). Importantly, the
There's now a figure illustrating this (Figure 2(c)) in the paper

2024-07-03 23:33 UTC, amakelov commented on papers/aleksandar_makelov/main.tex
> +\item First, we propose a simple design for a decorator for Python functions
Great point, added to related work!

2024-07-09 17:17 UTC, apaleyes commented
@amakelov looks like you've put quite a lot of work into updating the paper. Thanks! Do you think it is ready for another pass, or not yet?

2024-07-09 20:03 UTC, amakelov commented
> @amakelov looks like you've put quite a lot of work into updating the paper. Thanks! Do you think it is ready for another pass, or not yet?

@apaleyes indeed, the current version incorporates all the feedback as far as I'm aware - so it's a great time for another pass! 

In the meantime, in case anybody is interested, I've also greatly updated the documentation of the library in preparation for a next release:
- readme: https://github.com/amakelov/mandala
- docs: https://amakelov.github.io/mandala/

In particular, the "Caveats" notebook contains some of the things we discussed here: https://amakelov.github.io/mandala/tutorials/gotchas/

2024-08-06 17:20 UTC, ameyxd commented
@apaleyes, @matthewfeickert - can you confirm your feedback has been incorporated by the author and give me a thumbs up.

2024-08-06 23:45 UTC, apaleyes commented on papers/aleksandar_makelov/main.tex
> +Finally, we give an overview of related work in Section \ref{section:related-work}.
Not final anymore, with "limitations" now in place!

2024-08-06 23:46 UTC, apaleyes commented
@ameyxd yes, I am happy with the changes. Great job on the paper @amakelov , thanks for the insightful discussions!

2024-08-19 04:54 UTC, matthewfeickert approved these changes
Sorry for the delayed final review, but all LGTM. Thanks for the nice work here @amakelov. :+1:

2024-09-25 18:28 UTC, merged

2024-09-25 18:49 UTC, matthewfeickert commented
Congratulations @amakelov on having your paper accepted and merged! :rocket: Nice work. :)