Paper: multinterp: A Unified Interface for Multivariate Interpolation in the Scientific Python Ecosystem
scipy-conference/scipy_proceedings pull request #937
Opened 2024-06-07 21:23 UTC by alanlujan91

If you are creating this PR in order to submit a draft of your paper, please name your PR with `Paper: <title>`. An editor will then add a `paper` label and GitHub Actions will be run to check and build your paper.

See the [project readme](https://github.com/scipy-conference/scipy_proceedings#preview-your-paper) for more information.

_Editor_:  

_Reviewers_:

2024-06-11 17:26 UTC, ameyxd commented
@alanlujan91 can you recheck the DOIs that fail checks? As long as they are valid DOIs we should be okay.

2024-06-13 12:41 UTC, ameyxd commented
@alanlujan91 are you skipping valid DOIs? If so, please refrain and try the checks again. 😅

2024-06-13 12:45 UTC, alanlujan91 commented
@ameyxd I believe the ones I'm skipping don't have DOIs. I can try to look again

2024-06-13 12:48 UTC, ameyxd commented
Okay! please check "Paszke2019" in particular. lmk when complete and passing checks.

2024-06-13 13:01 UTC, alanlujan91 commented
@ameyxd Oh I remember what happened.

I found https://dl.acm.org/doi/10.5555/3454287.3455008
so I put that on my bib, then pushed, but mystmd didn't like the doi, probably because of this
<img width="400" alt="image" src="https://github.com/scipy-conference/scipy_proceedings/assets/5382704/5036db76-6002-407d-8525-6e63edfc2e74">
so then I set to ignore, but mystmd still didn't like it, so I removed it altogether from the bib
@rowanc1 any advice?

2024-06-20 22:53 UTC, ameyxd commented
Review reminders sent to @gcdeshpande and @aparoha

2024-06-21 18:40 UTC, cbcunc commented
> so then I set to ignore, but mystmd still didn't like it, so I removed it altogether from the bib @rowanc1 any advice?

@rowanc1 Any comment?

2024-06-21 22:33 UTC, aparoha requested changes
Thanks for raising your PR. The overall concepts look promising. I have provided in-line comments as well. Overall comments:-
1. The text could benefit from clearer organization and structure. For instance, some sections seem to repeat concepts without introducing new information or advancing the narrative.
2. The introduction of technical terms and concepts could be more gradual and systematic, ensuring the audience can follow the content smoothly.

2024-06-21 22:33 UTC, aparoha commented on papers/alan_lujan/main.md
> +```{list-table} Grids and structures implemented in "multinterp".
Question: Do you have plans to support other interpolations e.g. spline, inverse distance weight, natural neighbor etc.?

2024-06-21 22:33 UTC, aparoha commented on papers/alan_lujan/main.md
> +The set of input values on which we know the function's output values is called a **grid**. A grid (or input grid) of values can be represented in many ways, depending on its underlying structure. Th
The introduction of technical terms and concepts could be more gradual and systematic, ensuring the audience can follow the content smoothly. The 2nd paragraph directly jumps to grid interpolation without setting the context before.

2024-06-21 22:33 UTC, aparoha commented on papers/alan_lujan/main.md
> +The multinterp package (<https://github.com/alanlujan91/multinterp>) is currently in its beta stage.  It offers a strong foundation but welcomes community contributions to reach its full potential.
While the text mentions documentation and community contributions, specific links or guidelines for how users can contribute or access detailed documentation are not provided. Adding clear references or links to supplementary materials would enhance the text's utility.

2024-06-25 17:52 UTC, rowanc1 commented
Hi @alanlujan91 - we talked about this today in our editorial team meeting and would love to showcase your article with computational capabilities and reproducibility (as [per this note](https://github.com/scipy-conference/scipy_proceedings?tab=readme-ov-file#a-note-on-notebooks-for-2024) in the readme!).

I think following the review comment by @aparoha "some sections seem to repeat concepts without introducing new information or advancing the narrative.", it looks as though you are including the full notebooks, rather than individual cells. There is a way in MyST to include individual cells or outputs that keep links to the original location of the supporting materials. The [documentation is here](https://mystmd.org/guide/reuse-jupyter-outputs). That could be a way to change how you are showcasing the information and better highlight and link to your supporting materials.

If you are open to it I would love to work on you to change the use of MyST slightly to better highlight the computational aspects. Let me know if you have time this week or next week?

2024-06-25 17:58 UTC, alanlujan91 commented
@rowanc1 that would be great!

I am at a conference this week, so I haven't had time to address the previous comments, but will be available next week to discuss how we can improve this work

2024-06-25 17:59 UTC, rowanc1 commented
Fantastic - I will reach out to you separately and get a meeting scheduled soon. Very very excited to show off your content in the SciPy Proceedings this year, and elevate the use of Jupyter Notebooks and reproducibility. 🚀

2024-07-25 04:45 UTC, JennEYoon commented
Re: https://github.com/alanlujan91/scipy_proceedings/pull/1

Dear Alan @alanlujan91, 
Thank you for the opportunity to review Multinterp paper for SciPy Conference Proceedings 2024.  All of my comments are to improve readability for the general reader.  Please feel free to incorporate or ignore any of my suggestions. 

File edit:   main.md  `[[ suggestions enclosed between double brackets ]]`
Add file:   comments_figs_nbs.md ( suggestions on figures )  
screenshots (hand markup drawings) in `.\figures\ 

Sincerely,  
Jennifer Yoon, @JennEYoon  
best email:  mail@JenniferYoon.com 
July 24, 2024  PR1 submit

2024-07-31 20:38 UTC, ameyxd commented
@JennEYoon thanks for your reviews, please leave your commit as comments in this thread. You may refer to the work by other reviewers. Let us know if you have issues!

2024-08-05 03:55 UTC, JennEYoon reviewed
Review comments moved from a PR on author's multinterp branch
   ( https://github.com/alanlujan91/scipy_proceedings/pulls )  
to scipy_proceedings/pull/937 comments section.  
Jennifer 
Sunday August 4, 2024 update

2024-08-05 03:55 UTC, JennEYoon commented on papers/alan_lujan/main.md
> +
Is there a way to give a nod to PyTorch and TensorFlow for having call-backs, hooks, and function wrappers to allow a user to swap out an optimization function or module mid-stream? They do not cover all the use cases of the `multinterp` package, but some effort went into developing a layered API to cover varying use cases.  

NumPy also has structured data type, that can be used for custom data type and hierarchial data structures.  It can be seen as an attempt to provide a flexible (customizable) user interface, even though its aim and scope is different from 'multinterp.' (NumPy structured datatype's goal seems mostly for C code interface and optimized C module or C numerical recipe interface and explicit memory control or memory layout control.) The general reader may appreciate having some context. This package may be viewed as a further development of previous efforts at a flexible user interface for users of varying data types and data geometries. 
(See structured arrays in https://numpy.org/doc/stable/user/basics.rec.html)

2024-08-05 03:55 UTC, JennEYoon commented on papers/alan_lujan/main.md
> +
Question on abstract: did you mean "regular/irregular interpolation" in your abstract, in place of "regular/rectilinear interpolation"? 
Replace "I've developed the `multinterp` package" to "The `multinterp` package was developed to"

2024-08-05 03:55 UTC, JennEYoon commented on papers/alan_lujan/main.md
> +
Given your later example, it might be better to make j > i.  
Also vectors are "monotonically increasing," but x_i > x_j and y_i > y_j describe a decreasing function, from left to right.   

In $\forall i > j$, suggest replacing symbol with words "for all i > j," to help non-math readers.

2024-08-05 03:55 UTC, JennEYoon commented on papers/alan_lujan/main.md
> +
Memo, the alt-text sections in code blocks do not wrap properly when viewed on an iPad/Tablet device.  Curvenotes build version works properly. So this issue only comes up when viewed direcly from a GitHub repo.  Not sure if this is an issue for proceedings.  
(Also alt-text wrap issue in Rectilinear Interpolation and Curvilinear Interpolation sections.)

2024-08-05 03:55 UTC, JennEYoon commented on papers/alan_lujan/main.md
> +
Multilinear_Interpolation.ipynb comment
```
def squared_coords(x, y):
    return x**2 + y**2
```
It will be helpful to provide a short reason for choosing the squared coordinates function. Example: A squared x and y coordinates function is used to draw a figure whose grid geometry looks like a curved sheet (bowl) in 3D projection. 

This closed-form solution function, for which all points along the curved surface are known, is used as the baseline model. From this known model, we can draw sample points to approximate similarly shaped unknown functions.

2024-08-05 03:55 UTC, JennEYoon commented on papers/alan_lujan/main.md
> +
Multivariate_Interpolation.ipynb: figures comment
fig 1: 
  missing title, missing axes labels (x, y, z).  
  suggest adding color shading to increase contrast (center to edges)  
![screenshot3](https://github.com/user-attachments/assets/dadfaa71-be40-41e0-985f-85d32a90b94e)

2024-08-05 03:55 UTC, JennEYoon commented on papers/alan_lujan/main.md
> +
fig 2: interpolated figures  
   missing title, axes labels (x, y z)  
   suggest ways to show this figure is interpolated.  
Possibly blow up a small area with enhanced pixelation.  
![screenshot4](https://github.com/user-attachments/assets/8e28261a-d057-4b6c-886d-8c469092f361)

2024-08-05 03:55 UTC, JennEYoon commented on papers/alan_lujan/main.md
> +
Multivariate_Interpolation_with_Derivatives.ipynb comment
fig1, fig2, fig3, fig4 
   Axes need labels on all 4 figures (x, y, z) or (dz/dx, dz/dy, f(z)).  

Difficult to see the relationship between first group of 2 figures and second group of 2 figures (partial derivatives). Perhaps some lines can be drawn to show an example of the original function and its partial derivatives.  I leave this decision up to the author.  
![screenshot5](https://github.com/user-attachments/assets/a776bd7f-066e-472e-b0e0-a1977073a14f)

2024-08-05 03:55 UTC, JennEYoon commented on papers/alan_lujan/main.md
> +
Unstructured_Interpolation.ipynb comment
For figures after the 1st one, (group 1: nearest, linear, cubic, radial basis) and (group 2: original, gaussian process regression), eye-balling the differences in the figures maybe easier with grid lines drawn in white or black ink.  Also just a suggestion.  

![screenshot1](https://github.com/user-attachments/assets/067fec6f-6354-4f9c-a405-a2fdc58653ec)

2024-08-05 03:55 UTC, JennEYoon commented on papers/alan_lujan/main.md
> +
![screenshot2](https://github.com/user-attachments/assets/90953334-3ba6-4421-8be1-9da32099b8e0)

2024-08-05 03:55 UTC, JennEYoon commented on papers/alan_lujan/main.md
> +The multinterp package (<https://github.com/alanlujan91/multinterp>) is currently in its beta stage.  It offers a strong foundation but welcomes community contributions to reach its full potential.
Curvenoted build version comment  
This paper when viewed on-screen, right-bottom screen area shows a list of related files. If possible, files should be listed in its order of appearance.   

**Supporting Documents**  
*(shown in the order of appearance)*

Multivariate_Interpolation.ipynb
Multivariate_Interpolation_with_Derivatives.ipynb
Multivalued_Interpolation.ipynb
Curvilinear_Interpoliation.ipynb
Unstructured_Interpolation.ipynb
manim_notebook.ipynb (figure animation on Curvenotes build)
figures.ipynb (add?)

2024-08-06 17:22 UTC, ameyxd commented
@JennEYoon, @aparoha - can you confirm the author's updates are satisfactory for your feedback and give me a thumbs up! 🙂

2024-08-08 03:05 UTC, JennEYoon commented
Looks good.  All of my comments were up to the author's discretion. :-)

2024-08-08 03:25 UTC, JennEYoon commented on papers/alan_lujan/main.md
> +`multinterp` provides a simple and efficient implementation of *multilinear interpolation* for various backends (`numpy` (@Harris2020), `scipy` (@Virtanen2020), `numba` (@Lam2015), `cupy` (@Okuta2017
For the remainder of this section...  instead of "From the remaining of this section"...  Sorry missed moving this comment before; JY

2024-08-08 03:28 UTC, JennEYoon reviewed
Added ann edit forgot to copy over.

2024-09-25 18:31 UTC, merged

2024-11-05 19:37 UTC, stefanv commented
Hi folks, it doesn't look like the performance comparison made it to the published paper?

https://github.com/scipy-conference/scipy_proceedings/pull/937/files#diff-c6654a0adee03d2551feb82286acfd2863716a72e411ad6435c1bc1753445071R503

2024-11-05 20:19 UTC, fwkoch commented
Hey @stefanv - thanks for noticing this. As far as I can tell, labels referenced in the `Performance Comparison` section do not exist in any of the notebooks provided (`fig:performance_comparison_2d`, `fig:performance_comparison_3d`, `fig:backend_comparison_2d`, and `fig:backend_comparison_3d`).

If the notebooks with these figures are added, we can update the proceedings site and PDF! cc @alanlujan91

2024-11-07 17:30 UTC, alanlujan91 commented
thanks for catching that! I will make a PR against `2024`