Paper: [DRAFT IN PROGRESS] Orchestrating Bioinformatics Workflows Across a Heterogeneous Toolset with Flyte
scipy-conference/scipy_proceedings pull request #938
Opened 2024-06-07 23:39 UTC by pryce-turner

Hello! 

I didn't realize the review process started so early, this submission had to compete with a number of other high-priority items. As such, this is an incomplete first draft and I ask that reviewers kindly afford me some more time to clean it up before investing time reviewing it. I will adjust the PR title and contact relevant parties at that time.

Thank you for your patience and understanding!

_Editor_:  

_Reviewers_:

2024-06-10 21:56 UTC, hongsupshin commented
@pryce-turner Hi there, could you provide us with a timeline on when you can get the draft ready for the review?

2024-06-11 16:41 UTC, cbcunc commented
@pryce-turner Is this still a "draft in progress?" If not, please remove draft from the PR title. If so, we only accept complete drafts for submission. We need to assign reviewers and don't wish to assign reviewers to a paper that is not complete. Please indicate that the paper is ready for review.

2024-06-11 20:33 UTC, pryce-turner commented
Hi @hongsupshin and @cbcunc, this is now ready for review. Thanks for your patience!

2024-06-20 22:35 UTC, cbcunc commented
Review reminders sent to  @amjames and @davekits

2024-06-29 03:27 UTC, amjames requested changes
Overall this submission covers a topic of great interest to the scipy audience. Inline comments for more details. In general I suggest some structural changes to make the narrative flow better, and some suggestions to make the material more accessible to those outside the DNA sequencing field. 

Two general notes: 
- Missing abbreviations definitions
- The example code in the text is not stand-alone runnable, the full scripts w/ and missing task definitions and their image specs should be made available as an appendix/repo link.

2024-06-29 03:27 UTC, amjames commented on papers/pryce_turner/main.md
> +
This section leaves me with a few unanswered questions, addressing some of these 

- A counterpoint in favor of the "normal" container based approach may be fond in composability. Does ImageSpec support features that allow image definitions to be derived from others keeping the common base parts in sync?
- A few questions regarding the reproducibility aspect:
	- What is/are the lifetime(s) of the artifact(s) produced when an image is built and uploaded? 
	- Does the image build produce a lock file for the environment so someone else can re-create the solved environment after the fact, and could that lockfile be used to create an `ImageSpec` by someone else?
	- How does one specify the hardware configuration to be used by a task?

2024-06-29 03:27 UTC, amjames commented on papers/pryce_turner/main.md
> +Having rich data types to enforce compatibility at the task boundary is essential to these wrapped tools working together. Flyte supports arbitrary data types through Python’s dataclasses library. Da
Couple of comments on this paragraph: 

> Data types representing raw reads and alignment files allow us to reason about these files and their metadata more easily across tasks, as well as enforce naming conventions. 

Please consider dropping this sentence. As reader who is not working with genetic sequencing trying to understand what  "reads" and "alignment files" are at this point is distracting, to the point that I needed to come back after visiting the links found in the next paragraphs. Without this sentence (and a minor rewording of the penultimate sentence to avoid referring back to "these files") the paragraph does not loose anything. It still tells me we are going to be covering how individual units of data can be tied together in a way which conceptually makes sense for a particular workflow and removes extraneous details.

If you then present the dataclass with some brief indication of what it is, for example (based on my understanding from the reference link on paired-end reads below)
> DNA sequences are processed in smaller fragments called "reads", here is a dataclass that can be used to encapsulate the different artifacts making up a single read.

2024-06-29 03:27 UTC, amjames commented on papers/pryce_turner/main.md
> +More information related to alignments is being captured here. However, the standard methods for interacting with a local filesystem remain. In the next section we'll look at tasks that actually carr
Is the sentence beginning "However, ..." misplaced? It doe not logically flow from the statement before and seems to belong closer to the information about `FlyteFile` and `FlyteDirectory`

2024-06-29 03:27 UTC, amjames commented on papers/pryce_turner/main.md
> +Having rich data types to enforce compatibility at the task boundary is essential to these wrapped tools working together. Flyte supports arbitrary data types through Python’s dataclasses library. Da
> This not only makes it easier to work with these files, but also safer as you’re working with ephemeral storage during execution instead of a full production filesystem.

The convenience of having an abstraction to the object store at hand is clear, but the safety part needs some explanation. It is not clear what protection is offered by ephemeral storage that would be attractive here. I did not find an explanation for this in the following paragraph where the object store abstraction is covered.

2024-06-29 03:27 UTC, amjames commented on papers/pryce_turner/main.md
> +We're capturing a few important aspects: whether the reads have been filtered and the results of that operation, as well as if they're [paired-end](https://thesequencingcenter.com/knowledge-base/what
The paired-end reads reference clears up what `read1` and `read2` are, but the `uread` does not seem to be important to the example. It is also not clear how one can interrogate an object of this type to determine if a read is "paired". Is a `paired` field missing, or should the type implement `is_paired`?

2024-06-29 03:27 UTC, amjames commented on papers/pryce_turner/main.md
> +Since dataflow in Flyte is a first-class construct, having well defined inputs and outputs at the task boundary makes authoring workflows that much more reliable. Here is another dataclass representi
The introduction of the Alignment type leads me to expect a overview of what it is. I think it would be sufficient to mention that it will be used in the examples for the next section as a signal to the reader they need not spend much time trying to understand it if they are not already familiar, but can return to  the definition here later if needed.

2024-06-29 03:27 UTC, amjames commented on papers/pryce_turner/main.md
> +    setattr(alignment, "deduped", False)
While not technically wrong, the use of `setattr` here is a very strange choice. Is there any particular reason regular assignment (`a.x = val`) isn't used here.

2024-06-29 03:27 UTC, amjames commented on papers/pryce_turner/main.md
> +```
This end-to-end example brings things which have not been shown in the preceding examples. 

If any of these new tasks are provided by a dependency, I suggest adding the import to the example to make that clear. If these are custom tasks defined by the author, perhaps an abbreviated signature and docstring to make that clear.

```python 
# hypothetical 3rd party package providing a task definition
from fastqc_flyte_package import fastqc_task as fastqc

@task
def pyfastp(rs: RSType) -> ReturnType:
	"""Python wrapper for fastp doing x,y,z"""

@workflow
def simple_alignment_wf(...):
	# continued as in the original

2024-06-29 03:27 UTC, amjames commented on papers/pryce_turner/main.md
> +FastQC, an extremely common QC tool written in **Java**, starts off the workflow by generating a report for all FastQ files in a given directory. That directory is then turned into Reads objects via
I believe that the various packages/tools mentioned here should be referenced `FastQC`, `fastp`, `Bowtie2`.

2024-06-29 03:27 UTC, amjames commented on papers/pryce_turner/main.md
> +FastQC, an extremely common QC tool written in **Java**, starts off the workflow by generating a report for all FastQ files in a given directory. That directory is then turned into Reads objects via
`FastQC`, `Bowtie2` and the other packages/tools mentioned here should have references.

2024-06-29 03:27 UTC, amjames commented on papers/pryce_turner/main.md
> +FastQC, an extremely common QC tool written in **Java**, starts off the workflow by generating a report for all FastQ files in a given directory. That directory is then turned into Reads objects via
This paragraph is trying to do too many things. The interleaving of walking the reader through the example, calling out the tools, mentioning the various languages are all important points, but trying to go through them all at once is difficult to follow.

This might read better split up:

- Introduce the tools, and tasks components not mentioned in the previous example code. Refer back to one of the examples showing the pattern used to implement the task (shell tasks, `subproc_exectue`, etc). 
The languages used to implement the packages are not as important as discussing the interfaces they offer. That detail might be better served as a concluding statement "The workflow definition seamlessly integrates `n` different language ecosystems and compute environments" 
- The concepts of `map_task` and `dyanmic_workflow` are brand new, so say a bit more about them.  How they enable parallelism and what the tradeoffs/restrictions are, why are each used here. The reference seems to explain that map_task should be used if possible, but I'm not understanding why it is not possible to use it in both places in your example.

2024-06-29 03:27 UTC, amjames commented on papers/pryce_turner/main.md
> +FastQC, an extremely common QC tool written in **Java**, starts off the workflow by generating a report for all FastQ files in a given directory. That directory is then turned into Reads objects via
There should be a bit more said about the need for establishing a dependency between QC and filtering. Explain briefly why there needs to be a dependency established, and why execution of the first line before the 3rd line is not enough to ensure the ordering (compile time vs runtime execution is never talked about here).

2024-06-29 03:27 UTC, amjames commented on papers/pryce_turner/main.md
> +A real world alignment workflow exemplifies how to tie all these disparate parts together. Starting with a directory containing raw FastQ files, we'll perform QC, filtering, index generation, alignme
Possible Typo: `FastQ` -> `FastQC`?

2024-07-03 00:57 UTC, pryce-turner commented on papers/pryce_turner/main.md
> +
Let me know if the most recent commit answered your questions :)

2024-07-03 00:57 UTC, pryce-turner commented on papers/pryce_turner/main.md
> +Having rich data types to enforce compatibility at the task boundary is essential to these wrapped tools working together. Flyte supports arbitrary data types through Python’s dataclasses library. Da
I reworked it a bit to add better background information

2024-07-03 00:58 UTC, pryce-turner commented on papers/pryce_turner/main.md
> +More information related to alignments is being captured here. However, the standard methods for interacting with a local filesystem remain. In the next section we'll look at tasks that actually carr
Reworked this to make it less awkward

2024-07-03 00:58 UTC, pryce-turner commented on papers/pryce_turner/main.md
> +Having rich data types to enforce compatibility at the task boundary is essential to these wrapped tools working together. Flyte supports arbitrary data types through Python’s dataclasses library. Da
Let me know if those aspects of "safety" make sense here

2024-07-03 00:58 UTC, pryce-turner commented on papers/pryce_turner/main.md
> +We're capturing a few important aspects: whether the reads have been filtered and the results of that operation, as well as if they're [paired-end](https://thesequencingcenter.com/knowledge-base/what
Clarified

2024-07-03 00:58 UTC, pryce-turner commented on papers/pryce_turner/main.md
> +Since dataflow in Flyte is a first-class construct, having well defined inputs and outputs at the task boundary makes authoring workflows that much more reliable. Here is another dataclass representi
A brief overview has been added

2024-07-03 00:59 UTC, pryce-turner commented on papers/pryce_turner/main.md
> +    setattr(alignment, "deduped", False)
I like to think there was a good reason I got stuck into this pattern originally.. but maybe not! Thank you for the suggestion.

2024-07-03 00:59 UTC, pryce-turner commented on papers/pryce_turner/main.md
> +```
I added some explicit imports to match the true state of the repo and clarified why some of the tasks were not fully defined.

2024-07-03 01:00 UTC, pryce-turner commented on papers/pryce_turner/main.md
> +FastQC, an extremely common QC tool written in **Java**, starts off the workflow by generating a report for all FastQ files in a given directory. That directory is then turned into Reads objects via
Absolutely. I wanted to make sure everything included would make it into the final draft before citing them all. They're now cited.

2024-07-03 01:00 UTC, pryce-turner commented on papers/pryce_turner/main.md
> +FastQC, an extremely common QC tool written in **Java**, starts off the workflow by generating a report for all FastQ files in a given directory. That directory is then turned into Reads objects via
Agreed. I've separated this out and made the flow a lot clearer.

2024-07-03 01:01 UTC, pryce-turner commented on papers/pryce_turner/main.md
> +FastQC, an extremely common QC tool written in **Java**, starts off the workflow by generating a report for all FastQ files in a given directory. That directory is then turned into Reads objects via
Clarified

2024-07-03 01:01 UTC, pryce-turner commented on papers/pryce_turner/main.md
> +A real world alignment workflow exemplifies how to tie all these disparate parts together. Starting with a directory containing raw FastQ files, we'll perform QC, filtering, index generation, alignme
Not a typo but I've clarified the distinction here and above.

2024-07-03 01:02 UTC, pryce-turner commented
@amjames thank you so much for the thorough review! I think things are a lot clearer now but am of course always open to further suggestions.

2024-07-03 16:46 UTC, amjames reviewed
@pryce-turner thank you for your edits. I believe this is a significant improvement in clarity and accessibility for the general scipy audience.

Most of my comments on this pass call out minor issues, such as missing abbreviation definitions, and minor technical issues like updating the myst metadata with acronyms/abbreviations. There are a small number of suggestions for clarification in line as well. 

Thanks

2024-07-03 16:46 UTC, amjames commented on papers/pryce_turner/main.md
> +Tasks are the most basic unit of work in Flyte. They are pure-Python functions and their interface is strongly typed in order to compose the workflow. The workflow itself is actually a DSL that stati
Acronym definition -> DSL

2024-07-03 16:46 UTC, amjames commented on papers/pryce_turner/main.md
> +Different languages also come with different dependencies and approaches to dependency management, interpreted versus compiled languages for example handle this very differently. They also need to be
NIT: PATH -> `PATH`

2024-07-03 16:46 UTC, amjames commented on papers/pryce_turner/main.md
> +While it's possible to run Flyte tasks and workflows locally in a Python virtual environment, production executions in Flyte run on a Kubernetes cluster. As a k8s native orchestrator, all tasks run i
Define abbreviation "k8s" and reference for Kubernetes.

2024-07-03 16:46 UTC, amjames commented on papers/pryce_turner/main.md
> +While it's possible to run Flyte tasks and workflows locally in a Python virtual environment, production executions in Flyte run on a Kubernetes cluster. As a k8s native orchestrator, all tasks run i
> These additional dependencies can include apt, Python or conda packages. 

1) Is the image limited to debian based distributions (apt packages only)? Or is this just to say that the system package manager can be used? 
2) Instead of Python; PyPI is probably what you mean, as many packages installable with `conda` are also Python packages.

2024-07-03 16:46 UTC, amjames commented on papers/pryce_turner/main.md
> +    accelerator=GPUAccelerator("nvidia-tesla-v100"),
Awesome addition to the task decorator example IMO.

2024-07-03 16:46 UTC, amjames commented on papers/pryce_turner/main.md
> +Importantly, Flyte abstracts the object store, allowing you to load these assets into pods wherever is most convenient for your tool. This not only makes it easier to work with these files, but also
This is much more clear now, thank you.

2024-07-03 16:46 UTC, amjames commented on papers/pryce_turner/main.md
> +A real world alignment workflow demonstrates how to tie all these disparate parts together. Starting with a directory containing raw FastQ files, we'll perform QC, filtering, index generation, alignm
Acronym definition (QC)

2024-07-03 16:46 UTC, amjames commented on papers/pryce_turner/myst.yml
> +    MyST: Markedly Structured Text
In addition to defining the abbreviations in text on first occurrence. This section of the metadata should be populated. Doing so will not only create helpful hover text on the rendered paper, accessibility tools like screen readers can make use of the metadata.

2024-07-03 16:46 UTC, amjames commented on papers/pryce_turner/myst.yml
> +    - rule: doi-exists
If there is no DOI for the citation which is causing an error you can silence that by adding the key here. 

If there is a DOI for the citation then adding it to the bibliography entry would be best.

2024-07-03 16:46 UTC, amjames commented on papers/pryce_turner/main.md
> +List of workflow nodes and their status
Please consider populating the `:alt:` field for your figures with a longer text description of the image. A colleague referred me to [this](https://blog.degruyter.com/image-alt-text-how-to-make-your-scientific-publication-more-accessible/) resource which I found helpful for writing alt-text for figures in this kind of technical content.  

I do note that this does not seem to be a requirement per the reviewer guidelines. @cbcunc could you check my understanding of the guidelines as to alt-text being required/suggested/etc?

2024-07-03 16:46 UTC, amjames commented on papers/pryce_turner/main.md
> +Currently, a subset of the full Dockerfile functionality has been reimplemented in ImageSpec. A typical Dockerfile could include pulling micromamba binaries, creating and activating an environment, b
The link for *images* in the last sentence of this paragraph is the first place you mention the unionai-oss repo, and the way this is worded gives the impression that "the associated repo" refers to a repo associated with the `ImageSpec` type. 


I would suggest adding a paragraph to the end of the "Methods" section introduction that explains you are going to go through an example using Flyte in a bioinformatics workflow. Mention that parts (all?) of the example code is coming from that repo and name it "the `unionbio` package [link]" then throughout the following subsections you can refer to it explicitly by name. For example, here: "The `images` submodule of the unionbio ..." additional references to the repo can include direct links to the part you are talking about (like you have here) while the first link can point to the main repository/readme etc.

2024-07-05 01:30 UTC, davekits commented
My name is Kirtan, and I am one of the paper's reviewers.I will work on reviewing the paper and offering feedback.

2024-07-05 18:13 UTC, pryce-turner commented on papers/pryce_turner/myst.yml
> +    - rule: doi-exists
I added a key for the citation that doesn't have a DOI, but I never saw an error related to it. I just left that part in from the template. Were you seeing an error somewhere?

2024-07-05 18:32 UTC, pryce-turner commented on papers/pryce_turner/main.md
> +Currently, a subset of the full Dockerfile functionality has been reimplemented in ImageSpec. A typical Dockerfile could include pulling micromamba binaries, creating and activating an environment, b
I wasn't sure what the best way to incorporate it was - this works nicely, thank you!

2024-07-05 18:37 UTC, amjames commented on papers/pryce_turner/myst.yml
> +    - rule: doi-exists
If you follow the link in the [bot comment](https://github.com/scipy-conference/scipy_proceedings/pull/938#issuecomment-2161405872) it shows 3 failing checks, one of which (DOI Exists) is required.

2024-07-07 10:03 UTC, davekits commented
@pryce-turner The aligners utilize indexes to map reads, and it is crucial to have a comprehensive discussion on the mechanism and parameters of aligners, particularly for single-end and paired-end data types.Additionally, the method does not include the development of a VCF file, which is necessary for variant analysis.

2024-07-08 21:00 UTC, pryce-turner commented
Thanks for the comments @davekits! Despite alignment being a massive topic, I agree that a slightly more in-depth discussion, especially around the role of the index, is warranted. I'll avoid going too much into the weeds of dynamic programming or global vs local though, for example.
A similarly detailed investigation of variant calling would likely be beneficial. This will be a fair bit more work since I have to develop the actual tasks and update the workflow behind the paper before I can discuss them. I'll focus on the presentation for now since this example adequately motivates the discussion around different tools playing nicely together; I'll focus on your suggested edits next week!

2024-08-07 04:09 UTC, pryce-turner commented
@davekits I've been hard at work updating the supporting [repo](https://github.com/unionai-oss/unionbio/tree/pryce/se-85-unionbio-add-simple-variant-calling-workflow) to accommodate your suggestions, as well as add descriptions around some of the topics you've requested be clarified. There is still some cleanup to do, as well as update some figures, but I wanted to get this out to you for final impressions as soon as I could. 

Work has been extremely busy lately and as such this had to be deprioritized; I sincerely appreciate your and @amjames understanding and attention. I'll follow up tomorrow with a final commit. If you both find the final edits are not polished enough, I'd appreciate consideration of an earlier commit for publication as I believe the more limited set of examples still adequately supports the paper's motivation. Thank you again!

2024-09-09 19:04 UTC, amjames approved these changes
All of the issues raised by me have been addressed to my satisfaction.

2024-09-25 18:36 UTC, merged