Paper: Funix
scipy-conference/scipy_proceedings pull request #948
Opened 2024-06-08 06:17 UTC by forrestbao

If you are creating this PR in order to submit a draft of your paper, please name your PR with `Paper: <title>`. An editor will then add a `paper` label and GitHub Actions will be run to check and build your paper.

See the [project readme](https://github.com/scipy-conference/scipy_proceedings#preview-your-paper) for more information.

_Editor_:  

_Reviewers_:

2024-06-10 10:11 UTC, stevejpurves commented
Hi @forrestbao - looks like you have made changes to `.gitignore` outside of the paper folder, could you please revert that change (adding a `.gitignore` in your paper folder if you need to), then the checks will pass.

2024-06-20 22:33 UTC, cbcunc commented
Review reminders sent to @chongshenng and @cpk26

2024-06-25 05:12 UTC, chongshenng commented
Hi @forrestbao 👋, I'm Chong Shen one of the reviewers. I'll add my comments to your PR shortly.

2024-06-25 05:34 UTC, chongshenng requested changes
The authors present Funix, a supercharged hyper-simple way of converting Python native scripts/functions into a GUI _without_ needing to know about front-end or app development. Funix is an early stage project, but it shows tremendous promise and utility for scientific users. I am looking forward to this paper in its full form. 

In terms of comments, I only have very minor ones (please refer to the inline comments0. The writing is clear and the contents are informative. In fact, reading this paper is almost like reading the documentation of Funix (which is interesting because the authors wrote in their Motivation: "... all existing solutions require the developer to read their documentations before being able to create a GUI." 😉 ). 

To summarize, I only have minor comments and happy for the authors to amend them accordingly, where they think are appropriate.

2024-06-25 05:34 UTC, chongshenng commented on papers/funix/main.md
> +Existing Python-based solutions such as Streamlit or Grdio, do a great job for the first feature above but are still too complicated for the second one, requiring a developer to read their documentat
Tiny typo here: Grdio -> Gradio

2024-06-25 05:34 UTC, chongshenng commented on papers/funix/main.md
> +Currently, Funix depends on the type hint for every argument or return of a function. In the future, it will support type inference or tracing.
> In the future, it will support type inference or tracing.

❤️

2024-06-25 05:34 UTC, chongshenng commented on papers/funix/main.md
> +By default, Funix maps the following basic Python types to the following MUI components:
I'm assuming the users don't have to explicitly remember this mapping, if you push the boundaries of simplicity? Could you please comment on this?

2024-06-25 05:34 UTC, chongshenng commented on papers/funix/main.md
> +To avoid conflicting with the default behavior of printing to `stdout`, printing to the web needs to be explicitly turned on by a decorator.
Pretty cool feature. I was wondering how does `funix` handle `stderr`? For instance when using `logging.Logger` objects. It might be out of scope of this paper, so I'll leave it up to the authors to decide whether or not to mention this, or if it's something further down the line for development.

2024-06-25 07:15 UTC, Yazawazi commented on papers/funix/main.md
> +To avoid conflicting with the default behavior of printing to `stdout`, printing to the web needs to be explicitly turned on by a decorator.
Currently, Funix wraps the output in `stderr` in `<code>` to distinguish it from `stdout`, so perhaps in the future Funix will think about handling `stderr` and `stdout` in a better way.

2024-06-27 18:29 UTC, cpk26 commented
This paper introduces the early-stage Python project Funix. The aim of Funix is to automatically generate a web-based GUI for Python programs based on the types of function parameters and return values. It differentiates itself from existing frameworks by not requiring users to explicitly select the GUI elements used. Rather, Funix automatically selects elements based on types such as text boxes for string parameters or checkboxes for Boolean parameters. The correspondence between types and elements can be modified via themes. The motivation for Funix are the observations: that scientists and engineers are not necessarily experts in front-end development, that numerous use-cases exist for 'disposable' frontends where the idea is to provide a minimum-viable product or proof-of-concept, and that there exists relatively straight forward relationships between input/output elements and parameter types. The underlying mechanics of the project are implemented by transpiling Python into React.


Overall my impression of the project and paper are positive. It's well motivated in its discussion of simplifying GUI development for non-frontend developers, the mechanics of using Funix are described using examples, and there are three demos showcased at the end. As mentioned at the end of the paper, it has parallels to frameworks like Fire which automate generating a command line interface, which are quite useful. This paper makes good use of code examples and corresponding figures. The writing however, could use another pass at polishing. This includes fixes to the grammar, clarifying certain non-obvious points, and removing unnecessary opinions. See individual comments for more details.

While I did not run all the examples, getting the hello world example running was frictionless.

2024-06-27 18:37 UTC, cpk26 commented on papers/funix/main.md
> +  The raise of machine learning (ML) and artificial intelligence (AI), especially the generative AI (GenAI), has brought up the need for wrapping models or algorithms into GUI apps. For example, a la
'raise' -> 'rise' (plus in other locations)

2024-06-27 18:37 UTC, cpk26 commented on papers/funix/main.md
> +  Most of existing solutions require developers to manually create widgets and link them to arguments/returns of a function individually. This low-level process is laborious and usually intrusive. Fu
The connection to CSS is unclear to me. Perhaps expand a little? This reference is used a few times through the paper.

2024-06-27 18:37 UTC, cpk26 commented on papers/funix/main.md
> +
Very ambitious to try to eliminate reading the step of reading the docs!

2024-06-27 18:37 UTC, cpk26 commented on papers/funix/main.md
> +Every minute they spent on learning and building apps in existing solutions is a bad investment of their time because it does not advance their domain expertise or career goals.
I think there's varied opinions on whether this is a 'bad investment', or entirely separate from domain expertise and career goals. Bridging the gap between science and practice is important. This sentence might be better removed, as the motivation to help scientists do it faster is sufficient in the previous sentence is sufficient.

2024-06-27 18:37 UTC, cpk26 commented on papers/funix/main.md
> +Therefore, [Funix](http://funix.io) was born to automatically launch apps from existing functions. We notice that the choice of a widget has a weak correlation with the type of the function I/O it is
MUI library -- This should be introduced, or at least linked to?

2024-06-27 18:37 UTC, cpk26 commented on papers/funix/main.md
> +Funix is not only a GUI generator. It is a transcompiler that generates both the backend and the frontend of an app. The two ends communicate with each other in websocket. For the backend, Funix wrap
May be worth introducing the concept of a transpiler with a sentence or two as you are targeting scientists + engineers, not necessarily computer scientists.

2024-06-27 18:37 UTC, cpk26 commented on papers/funix/main.md
> +In summary, Funix has the following cool features to make building apps effortless (if not lazy or cheating):
"(if not lazy or cheating)" -- This can be removed

2024-06-27 18:37 UTC, cpk26 commented on papers/funix/main.md
> +A Dall-E app generated by Funix by simply wraping OpenAI's image generation API with a `str`-to-`Image` function. Source code in [](#code_dalle).
"wraping" -> wrapping

2024-06-27 18:37 UTC, cpk26 commented on papers/funix/main.md
> +| Python type     | Input or Output | MUI component or HTML
Does this table cover how the cat is displayed in the previous code example?

2024-06-27 18:37 UTC, cpk26 commented on papers/funix/main.md
> +Introducing a new type-to-widget mapping or modifying an existing one should not be the job of most Funix users. Only advanced users or the UI guys should be involved. This is like most scientists wh
"Only advanced users or the UI guys should be involved." -- Can be removed or should be reworded.

2024-06-27 18:37 UTC, cpk26 commented on papers/funix/main.md
> +:caption: Stremaing using yield in Funix. The corresponding GUI app is shown in [](#fig_stream).
Stremaing  -> streaming

2024-07-01 06:06 UTC, forrestbao commented on papers/funix/main.md
> +Existing Python-based solutions such as Streamlit or Grdio, do a great job for the first feature above but are still too complicated for the second one, requiring a developer to read their documentat
@chongshenng  Thanks very much. We will go though the paper a couple more times to carefully polish up the writing.

2024-07-01 06:09 UTC, forrestbao commented on papers/funix/main.md
> +By default, Funix maps the following basic Python types to the following MUI components:
Correct, users don't have to remember this mapping. The information here is just to document the correspondence between types and widgets in case some readers are curious.

2024-07-01 06:10 UTC, forrestbao commented on papers/funix/main.md
> +  The raise of machine learning (ML) and artificial intelligence (AI), especially the generative AI (GenAI), has brought up the need for wrapping models or algorithms into GUI apps. For example, a la
thanks for catching the error up. We will go through the paper a couple of times to polish the writing.

2024-07-01 06:16 UTC, forrestbao commented on papers/funix/main.md
> +  Most of existing solutions require developers to manually create widgets and link them to arguments/returns of a function individually. This low-level process is laborious and usually intrusive. Fu
Sure. As an abstraction, CSS manages the styles centrally (in one places, the `*.css` files) and separates the content from the style definitions. Changing the style for one class/id will update the looks of all tags of the class/id. Funix is like CSS in this sense. Widgets are grouped by their corresponding types. Changing the type-to-widget mapping in the theme will update the looks of all widgets of the involved type. Let me know if you have further questions.

2024-07-01 06:17 UTC, forrestbao commented on papers/funix/main.md
> +
We simply want developer to be able to fire up something quickly. Of course, a developer needs to read docs for customization.

2024-07-01 06:18 UTC, forrestbao commented on papers/funix/main.md
> +Every minute they spent on learning and building apps in existing solutions is a bad investment of their time because it does not advance their domain expertise or career goals.
sounds good. We will remove this sentence.

2024-07-01 06:19 UTC, forrestbao commented on papers/funix/main.md
> +Therefore, [Funix](http://funix.io) was born to automatically launch apps from existing functions. We notice that the choice of a widget has a weak correlation with the type of the function I/O it is
We will link to it.

2024-07-01 06:19 UTC, forrestbao commented on papers/funix/main.md
> +Funix is not only a GUI generator. It is a transcompiler that generates both the backend and the frontend of an app. The two ends communicate with each other in websocket. For the backend, Funix wrap
sounds good. We will explain it.

2024-07-01 06:19 UTC, forrestbao commented on papers/funix/main.md
> +In summary, Funix has the following cool features to make building apps effortless (if not lazy or cheating):
sounds good.

2024-07-01 06:20 UTC, forrestbao commented on papers/funix/main.md
> +A Dall-E app generated by Funix by simply wraping OpenAI's image generation API with a `str`-to-`Image` function. Source code in [](#code_dalle).
We will polish the writing.

2024-07-01 06:21 UTC, forrestbao commented on papers/funix/main.md
> +| Python type     | Input or Output | MUI component or HTML
In this table we only mention basic Python types. In the table below, we mention multimedia types, including the image type used to display the cat.

2024-07-01 06:22 UTC, forrestbao commented on papers/funix/main.md
> +Introducing a new type-to-widget mapping or modifying an existing one should not be the job of most Funix users. Only advanced users or the UI guys should be involved. This is like most scientists wh
We will remove it.

2024-07-01 06:22 UTC, forrestbao commented on papers/funix/main.md
> +:caption: Stremaing using yield in Funix. The corresponding GUI app is shown in [](#fig_stream).
Thanks. We will polish the writing

2024-07-01 06:24 UTC, forrestbao commented
@chongshenng @cpk26 Thank you both for the positive reviews and detailed feedback. Glad you liked Funix. We will go over the paper a couple of times to polish the writing.

2024-07-02 16:03 UTC, cpk26 commented on papers/funix/main.md
> +  Most of existing solutions require developers to manually create widgets and link them to arguments/returns of a function individually. This low-level process is laborious and usually intrusive. Fu
My impression is that this analogy isn't particularly helpful here. The reference to LaTeX themes later on was more useful, as its inline with your expectation that most folks take a stock theme and run with it. I'd recommend removing the reference to the CSS-like approach since it distracts from the rest of the sentence.

2024-09-09 19:13 UTC, chongshenng commented
The authors have adequately addressed my comments in their revision.

2024-09-09 22:00 UTC, cpk26 commented
The revised manuscript addresses my comments as well.

2024-09-09 22:14 UTC, forrestbao commented
Thank you very much @chongshenng and @cpk26.

2024-09-25 18:41 UTC, merged