Camron/Tyle SciPy 2024 Poster
scipy-conference/scipy_proceedings pull request #961
Opened 2024-07-12 05:19 UTC by ktyle

2024 SciPy Poster, **Open Source Farm to Open Source Table: Project Pythia's Cook-off Hackathons**, D. Camron and K. Tyle

2024-07-12 05:19 UTC, ktyle commented
@dcamron

2024-07-12 16:10 UTC, dcamron requested changes

2024-07-12 16:10 UTC, dcamron commented on presentations/posters/camron_tyle/info.json
> +      "affiliation": "NSF-University Corporation for Atmospheric Research/Unidata",
```suggestion
      "name": "M. Drew Camron",
      "affiliation": "UCAR / NSF Unidata",
```

2024-07-12 16:10 UTC, dcamron commented on presentations/posters/camron_tyle/info.json
> +  "description": "This poster describes Project Pythia's annual community hackathons, aka Cook-offs. These summer sprints blur the lines between scientist and software developer at an individual and
```suggestion
  "description": "This poster describes Project Pythia's annual community hackathons, aka Cook-offs. These summer sprints blur the lines between scientist and software developer at an individual and group level, and seed excitement and commitment to the open source, open science community." 
```

2024-09-30 14:02 UTC, mepa approved these changes

2024-09-30 14:02 UTC, merged